### ISSUE TITLE
feature ofRandom(ofVec3f) 

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#1005]
Propose the following functions:

``` c++
ofVec2f ofRandom(const ofVec2f&);
ofVec3f ofRandom(const ofVec3f&);
ofVec2f ofRandom(const ofVec2f& range1, const ofVec2f& range2);
ofVec3f ofRandom(const ofVec3f& range1, const ofVec3f& range2);
```

also lots of other candidates for this, e.g. `ofClamp`, `ofMap`, etc
some clever templating possible?

**Comment by artificiel** [comment]
this can be closed as there are now templated methods to apply std::random_distributions to glm::vec — see https://github.com/openframeworks/openFrameworks/issues/3198#issuecomment-1745243359 for more info.
