### ISSUE TITLE
ofSaveImage / ofImage::saveImage() problem with OF_IMAGE_GRAYSCALE / OF_PIXELS_MONO

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#1028]
I've just encountered a real 'wall meets head' bug, aka 'why is my camera image black??'

well it turns out that actually, ofSaveImage doesn't save mono images
it just saves out black pixels

testing on Windows, VS2010.
Anybody else getting this?

**Comment by div1234522** [comment]
I am also unable to save OF_IMAGE_GRAYSCALE images using saveImage/ofSaveImage function. I always get a black image, though of the correct dimensions. Happens in png/jpg/etc all formats.

ofx 0.84 + Win 10 + CB 13.12 + Freeimage 3.15 (Included in ofx)

Please help.

**Comment by div1234522** [comment]
Switched to Visual Studio on Windows (to enable OpenMP support, and to be ready for oF 0.9.0). Save Image works flawlessly in it. Jpg/Png/Bmp all of them. Using both the my_image.save_image() syntax and oFSaveImage() syntax. Though I'm not quite sure about the "grab screen area" code and saving that (as direct image saving works nicely).
