### ISSUE TITLE
regularize code for math addons

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#1062]
right now there is a lot of duplicated code in the vector math classes. for example, normalize() and getNormalized() have separate implementations. if we follow the pattern of always implementing things in self-modifying methods, then providing copy-returning methods as alternatives, this will reduce the amount of code and make it harder to cause bugs or behavioral discrepancies.

- implementations of an algorithm should always be self-modifying
- copy-returning versions should be implemented using a differently named method, internally making a copy and calling the self-modifying version on the copy.

e.g. something like (note, this isn't how it's implemented right now):

	inline ofVec2f& ofVec2f::normalize() {
		float length = (float)sqrt(x*x + y*y);
		if( length > 0 ) {
			x /= length;
			y /= length;
		}
		return *this;
	}

	inline ofVec2f ofVec2f::getNormalized() const {
		ofVec2f result = *this;
		return result.normalize();
	}

taken from this post https://github.com/openframeworks/openFrameworks/pull/1061#issuecomment-4455601

**Comment by arturoc** [comment]
We've decided already to migrate to glm so maintaining the current math library further doens't make much sense. if somone wants to tackle this i think we can merge it but i'm going to close it by now
