### ISSUE TITLE
Continuous integration/testing

### ISSUE THREAD

**Issue by gabrielstuff** [openframeworks/openFrameworks#1068]
Hey !

Me again. Didn't find anywhere this infos. I'm currently testing the travis-ci.org service.
As many people are working on the project and as many many issue are raised, and fixed, I thought it could be great to add some test and thus the travis service.

It would avoid the problem met here :
https://github.com/openframeworks/openFrameworks/commit/7ca7833ea1afb6bd5a6c54031e3fa688aa0c0ba8
and the discussion here :
https://github.com/openframeworks/openFrameworks/issues/804
or there :
https://github.com/openframeworks/openFrameworks/pull/921

I read that :

>feel free to make a unitTests folder at the root level of OF -
> that is where all unitTests will go.

But didn't find them.

The travis service will permit to get the little badge we know well : 
[![Build Status](https://secure.travis-ci.org/soixantecircuits/openFrameworks.png?branch=master)](http://travis-ci.org/soixantecircuits/openFrameworks)

Also, why not adding some spec test, to ensure future development of features.
I'm currently reading :
http://www.squidoo.com/cplusplus-behaviour-driven-development-tools#module124841511
http://sourceforge.net/apps/mediawiki/turtle/index.php?title=Turtle

For those who want some other nice reading :

http://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle

The travis test is here, currently it is a total fake, but I just proposed the idea of a test driven development
http://travis-ci.org/#!/soixantecircuits/openFrameworks/builds/854259

**Comment by danoli3** [comment]
For Windows testing we can use http://www.appveyor.com/

**Comment by danoli3** [comment]
After seeing @bilderbuchi 's comment about automated testing.. I setup a quick test branch for this:

- Branch: https://github.com/danoli3/openFrameworks/tree/Automated/Travis-OSX
- Travis Status: https://travis-ci.org/danoli3/openFrameworks/branches
- I had to remove the documentation compiler travis code (not sure why this is a travis thing in the core).
- Testing iOS and Testing OSX.
- Using the template/emptyExample project for both

Limitations we have with Travis are the time per build (max 1 hour). 
So I thought for now the emptyExample is perfect. It validates the core has not been broken by a commit.

Testing this I created another branch from this, one which should soon fail.
- https://github.com/danoli3/openFrameworks/tree/Automated/Travis-CoreFail
- https://travis-ci.org/danoli3/openFrameworks/builds/68468345

**Comment by bilderbuchi** [comment]
> Limitations we have with Travis are the time per build (max 1 hour). 

Ah nice, when I checked Travis in the beginning, this was 10min or so, so I discarded the idea of using it for OF.

Nice work! One thing: could you leverage the make system instead of xcodebuild on the travis job? (this does work in osx already, right?) That way we could also detect errors in our makefiles, and the build code would be more homogeneous  (could easily include linux, too).

**Comment by bilderbuchi** [comment]
ha, I just found out that you can create a virtual framebuff (xvfb) with Travis, now: http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29
This could enable us to compile and run OF applications (like the EmptyExample) on Travis.

**Comment by kylemcdonald** [comment]
can this be closed since CI is basically working now, and #4259 is the latest work on unit tests?

**Comment by bilderbuchi** [comment]
Yeah I guess, this issue has become very long anyway, so it will be better to open new issues when further work arises.

**Comment by bilderbuchi** [comment]
Related issue: #4162
