### ISSUE TITLE
ofStringUtils:: feature discussion

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#1132]
This is a feature discussion issue for what string features we should add to of.
ofZach mentioned some regexp ones from P5 match matchAll
Would be great to get some eyes on this.

One approach would be a static class or namespace.
The idea would be we could include a variety of handy functions that would be useful for people not wanting to get into regexp

```
ofString::contains(str, "apple")       //returns bool
ofString::starts(str, "The")           //returns bool
ofString::ends(str, ".")               //returns bool
ofString::count(str, "apples")         //count how many times apples appears in the 
ofString::join(myVectorStr, ", ");     //this is currently ofJoinString
ofString::split(someText, ".");        //this is currently ofSplitString
ofString::split(someHtml, "<", ">");   //this is the same but returns a vector of things between the start and end delims
ofString::limit(someText, 200);        //limit the text to 200 characters. optional arg to add ... to the end.
```

Questions:
- Should we mirror P5 with match and matchAll or should we indicate that regexp is required? ie regexMatch regexMatchAll ?
- Other string utils we could add?
- Should it be ofStringUtils:: or ofString:: ?
- Something to do a split and then return a vector of float int etc?

**Comment by bakercp** [comment]
@ofTheo @ofZach @roymacdonald there has been quite a bit of progress on the string front in the last 5 years.  I'm going to close this and suggest that we start a new discussion or reopen this issue if needed.
