### ISSUE TITLE
TTF type rendering in OF - fix fuzziness 

### ISSUE THREAD

**Issue by openframeworks** [openframeworks/openFrameworks#124]
http://www.openframeworks.cc/forum/viewtopic.php?f=7&t=3299&p=17852#p17852

**Comment by mattfelsen** [comment]
I took a look at this on the current master and these issues seem to be resolved. Here's the fonts example running both at 72dpi and 96dpi. Looks nice & crisp for both. This is running on a retina MBP with the app retina enabled (High Resolution Capable -> YES in the OF plist)

![retina-fonts-72dpi](https://cloud.githubusercontent.com/assets/2334552/5693042/587d9bd0-98da-11e4-9df5-6c57dc372482.png)
![retina-fonts-96dpi](https://cloud.githubusercontent.com/assets/2334552/5693046/7e0e07f4-98da-11e4-897e-484e19cd78fd.png)

For another comparison, here's ofTrueTypeFont vs. ofxFontStash. The character spacing & line heights are off, but the font size is the same and you can see the letters render at the same size. In addition, the new kerning support is better than in ofxFontStash! (Take a look at the AT in "NATURAL")

![screen shot 2015-01-10 at 2 42 37 pm](https://cloud.githubusercontent.com/assets/2334552/5693052/b201125e-98da-11e4-8611-8c15c971e5b1.png)
![screen shot 2015-01-10 at 2 43 01 pm](https://cloud.githubusercontent.com/assets/2334552/5693053/b2019922-98da-11e4-9c77-a8a20066d0e0.png)

**Comment by kylemcdonald** [comment]
great work matt, thanks!

**Comment by bilderbuchi** [comment]
thanks!
