### ISSUE TITLE
ofATan2GL  /  ofVecToGL ?

### ISSUE THREAD

**Issue by openframeworks** [openframeworks/openFrameworks#126]
Something that easily converts vector direction to openGL degrees?
I find myself constantly trying to guess 270 - atan2(y, x)*RAD_TO_DEG ..... etc
To rotate something along a vector. 

Might be good to have it be aware of the GL world orientation - or have it so you pass in the up

**Comment by kylemcdonald** [comment]
@ofTheo i didn't see a corresponding PR closing this, what happened?
