### ISSUE TITLE
oF in HTML5

### ISSUE THREAD

**Issue by ddnn55** [openframeworks/openFrameworks#1319]
Issue: openFrameworks does not run in the web browser.

Solution: the emscripten backend for the LLVM compiler generates JavaScript, many C++ OpenGL projects have been demonstrated running in the browser with WebGL.

Is anyone interested in this?

**Comment by reginaflores** [comment]
guys sorry that i am late to the party here... I am new to the OF community and very interested in using OF on the web with emscripten. does anyone know of a repo where i can download the example code that @arturoc used in his site http://arturocastro.net/files/of-emscripten/ ? i would love to see file structures and understand how to run this locally on my machine... thanks all for your help!

**Comment by kylemcdonald** [comment]
@reginaflores equally late in responding to your comment, but i think the status of emscripten is that it's been broken in master for some time https://github.com/openframeworks/openFrameworks/issues/3426#issuecomment-74256266

and as far as i can tell, there is no issue tracking this besides #3426...

**Comment by arturoc** [comment]
hey, sorry i couldn't answer this before and then i totally forgot. the emscripten build is working fine. you just need to install emscripten acording to the instructions on their site and using the nightly builds build any of the examples using the normal makefiles. instead of `make` you need to use `emmake make` but everything else is the same, any example, with some limitations, should compile to javascript right away

**Comment by Inuart** [comment]
`emmake make`
`...`

    INFO     root: (Emscripten: Running sanity checks)
    ERROR    root: i386: No such file or directory ("i386" was expected to be an input file, based on the commandline arguments provided)
    make[2]: *** [../../../libs/openFrameworksCompiled/lib/osx/obj/Release/libs/openFrameworks/3d/of3dPrimitives.o] Error 1

I have no idea what I'm doing

**Comment by reginaflores** [comment]
Hey All! Guess what????? IT'S WORKING!!!! http://faceproject.nyc/sphere/sphere.html

Guys Emscripten is AWESOME!

**Comment by kylemcdonald** [comment]
woo! looking good @reginaflores!

**Comment by Inuart** [comment]
Does this only work on Linux? Because I am getting the `'GL/glx.h' file not found` error on mac once I remove `-arch i386` from `config.osx.default.mk`.

**Comment by arturoc** [comment]
it shouldn't be using that file at all, are you using emmake make? you also need to have the emscripten tools in your path

**Comment by Inuart** [comment]
Yes I am using `emmake make` and I have emscripten in my path.

What I find strange is that the line of my error `../../../libs/openFrameworks/utils/ofConstants.h:180:18: fatal error: 'GL/glx.h' file not found` is inside an `#ifdef TARGET_LINUX`

**Comment by reginaflores** [comment]
Hi @Inuart - maybe this can help:
1) Make sure you are using the 'nightly builds' from open frameworks downloads page... not the regular OF
2) go into the project generator of the nightly build and make a test project into your MyApps folder
3) copy the source code from the project you want to get working into the newly generated project 
4) then try to do the emmake make... 

try those tricks... it worked for me... also to note: i had to actually put the files online to see them working. Some of the examples I tried didn't worked when I was running them locally... not sure why. 

Good luck!

**Comment by arturoc** [comment]
yes somethings need a sever mostly with chrome, firefox is usually ok with it. you can also use `emrun bin/whateverExample.html` to open the page under a miniserver that emscripten has to solve this problem

**Comment by Inuart** [comment]
Well nice @reginaflores ! It now compiles with the nightly builds! Although even running the `3d/ofBoxExample` in `http://localhost:8080/mySketch.html` produces 109 JS errors on Chrome. All OpenGL-related.
I'm so close..

**Comment by reginaflores** [comment]
yay! glad you got it to compile!!! 

As Arturo said (from my list above):
step 5) emrun bin/yourexample.html
step 6) put all those files online... for a very simple example I got it to work locally, but for a more detailed example I had to run it online.

For what its worth I put this in a blog post with picture... maybe it helpful:
http://www.reginafloresmir.com/blog/2015/5/14/openframeworks-on-the-line

**Comment by kalwalt** [comment]
Hey @arturoc @reginaflores @kylemcdonald @abergmeier ! It works!!! This is AWESOME! I was able to compile the color example, i need to refresh the page in firefoxbrowser to start the app (something to do with 'canvas'...). Tested in linux64 bit (Ubuntu 14.04): the most difficulties was due to my llvm installed. My wrong because you need the fastcomp llvm version as described in emscripten http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html. So thank you all!... as soon i will do something with it , you will see on my wep pages!

**Comment by reginaflores** [comment]
@kalwalt YAY!!!!! Awesome! Update us when you do something cool!!!

Thanks to @arturoc for your guidance in all of this!!!!
