### ISSUE TITLE
simple text file loading and saving

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#1362]
i think this is the simplest way to save a string to a text file right now:

``` cpp
string str = "hello";
ofBuffer msg(str.c_str(), str.length());
ofBufferToFile("out.txt", msg);
```

there should be a one-line (one-function, ideally) equivalent similar to http://processing.org/reference/loadStrings_.html and http://processing.org/reference/saveStrings_.html

if we made a constructor for ofBuffer that accepts a string, then it could just be:

``` cpp
ofBufferToFile("out.txt", "hello");
```

and a cast operator for ofBuffer to string:

``` cpp
string str;
ofBufferFromFile("out.txt", str);
```

i'd be ok with that, even though the naming would be a bit obscure.

**Comment by bakercp** [comment]
With the new ofBuffer::getLines() and other buffer iterator functions I think a lot of these issues have been addressed.  I'm closing this discussion for the moment.  Please feel free to reopen if needed.
