### ISSUE TITLE
feature: better shader examples

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#1396]
Hey all!

I'd like to push for more shader examples.
I'd even like to suggest we separate shader examples out into another folder (move out of 'gl' folder into 'shader' folder)

here's a first example: (watch out for the abrasive fan!)
http://www.youtube.com/watch?v=crHWEJ-xq3s&feature=youtu.be

**Comment by kylemcdonald** [comment]
in the end, the text got added to ofSite instead http://openframeworks.cc/tutorials/graphics/shaders.html

so i'm going to consider this closed.
