### ISSUE TITLE
ofSetBackgroundColor not working?

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#1400]
is it meant to change the background color in the same way ofBackground does? 
what is a simple use case for it? 

looking at the code it sets a color, but I don't see that color being applied to the window. 

		//----------------------------------------------------------
		void ofSetBackgroundColor(int r, int g, int b, int a){
			currentStyle.bgColor.set(r,g,b,a);
		}

**Comment by kylemcdonald** [comment]
closing this, i believe it's fixed by the PR above.
