### ISSUE TITLE
OF_ROOT location should be able to be given to PG as an argument

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#1412]
Hi!
The config file which indicates OF_ROOT is currently in `~/.ofprojectgenerator/config`. This just became a problem when I was working on Jenkins CI builds:
On the one hand, the dialog that pops up that wants you to select the root folder doesn't find a display to open (of course, since this is basically headless for now, and this is the only thing in the whole chain which would necessitate a display I think).
On the other hand, the jenkins user which by default executes these tests doesn't have a home folder, so you can't even put the file there by hand. (This I can work around by creating a home folder for this user)
Both these problems would disappear if one could give the OF_ROOT location to the PG as a separate argument. I propose `--ofRoot <path-to-OF>`

@arturoc @benben: opinions?

**Comment by bilderbuchi** [comment]
@arturoc @ofZach should we close this old issue?

**Comment by arturoc** [comment]
yes this is already implemented
