### ISSUE TITLE
ofTrueTypeFont is unicode-unaware

### ISSUE THREAD

**Issue by damian0815** [openframeworks/openFrameworks#1468]
It's the 21st century and oF is used all over the world (most notably in 日本国), and therefore ofTrueTypeFont should be able to draw UTF-8 strings. 

ref: "The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets (No Excuses!)" http://www.joelonsoftware.com/articles/Unicode.html 

The most complex part of this will be to enable dynamic character loading and unloading, as there are >110,000 unicode characters. @gimlids and I worked in the Futurelab on a project that could do this -- it's not actually as difficult as it might seem.

**Comment by jbacelar** [comment]
Is there any news about using more unicode with ofTrueTypeFont.. This tread is from 2012-14 , now using of0.9 and xcode8  seems to be kind a problematic to use those libraries (at least for me)...
is it possible to just extend the 256 characters at ofTrueTypeFont with some lib editing?

**Comment by arturoc** [comment]
this is already solved in master where you can add several alphabets when setting up the font, the only problem still not solved is rendering alphabets with ligatures but utf8 is fully supported.

going to close this issue.
