### ISSUE TITLE
ofxurlfileloader doesn't have a accept header

### ISSUE THREAD

**Issue by minusplusminus** [openframeworks/openFrameworks#1495]
HI,

I'm trying to parse a json database, but the developer said he doesn't receive an header in the request. Is it possible that there will be a header? Or a possibility to custom add an header.

**Comment by bakercp** [comment]
ofUrlFileLoader is meant to be a very simple interface.  For mar sophisticated http calls consider using `ofHttpRequest` which now enables the user to set arbitrary request headers.

Other solutions like [ofxHTTP](https://github.com/bakercp/ofxHTTP) also work well for more advanced features.

Closing this for now.
