### ISSUE TITLE
Adding support for ScaleGestureDetector on Android

### ISSUE THREAD

**Issue by noisecapella** [openframeworks/openFrameworks#1524]
This would basically add support for pinch zoom, similar to the current support for swipes. I'm willing to add the support myself, but I wanted to submit an issue first to make sure it wasn't already done and that the functionality was wanted.

It would also require Android 2.2 or higher. I think that's what is recommended currently but I wanted to make sure that's an absolute requirement for ofxAndroid. Can anyone comment whether I should go forward with this?

**Comment by ofZach** [comment]
this seems to be in ofxAndroid now (so I am suggesting this issue be closed) but there's not example about how to use it.  I have found that this seems to work for me: 

ofAddListener(ofxAndroidEvents().scaleBegin,this,&ofApp::scaleBegin);

**Comment by bilderbuchi** [comment]
closing this, then
