### ISSUE TITLE
ofVec2f::perpendicular to return a choice of left or right perpendicular

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#1557]
`ofVec2f::perpendicular`
should be able to return a choice of the left or right perpendicular to the vector.
could either be done by passing a variable into the function
or splitting the function into,
`ofVec2f::perpendicularLeft`
`ofVec2f::perpendicularRight`
(perhaps)

**Comment by bakercp** [comment]
Closing this, as we are deprecating ofVec* methods.  I believe you can get the same outcome with glm::perpendicular and specifying the normal.

https://glm.g-truc.net/0.9.2/api/a00206.html
