### ISSUE TITLE
ofVec3f/ofVec4f operator== and operator!= rely on float==

### ISSUE THREAD

**Issue by damian0815** [openframeworks/openFrameworks#1558]
float== is unreliable. cf http://stackoverflow.com/questions/17333/most-effective-way-for-float-and-double-comparison 

http://stackoverflow.com/questions/6837007/comparing-float-double-values-using-operator suggests using `if (fabs((double)a/b - 1) < epsilon)` to avoid issues occuring when you don't know the ranges of a and b, this is for java but probably would work with c++ also.

**Comment by bakercp** [comment]
This has been addressed with `ofIsFloatEqual` and won't be fixed in ofVec* due to deprecation, but it has been fixed in ofRectangle and other core classes.  Closing this for now.
