### ISSUE TITLE
update assimp to 3.0 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#1617]
Assimp 3.0 was released July 2012 - might be worth looking into. 

http://assimp.sourceforge.net/index.html

One thing I read stated that the 3.0 version breaks from the 2.0 api - so it might not be a straight swap.

Edit: here is the changelog 

3.0 (2012-07-07)

FEATURES:
   - new export interface similar to the import API. 
   - Supported export formats: Collada, OBJ, PLY and STL
   - added new import formats: XGL/ZGL, M3 (experimental)
   - new postprocessing steps: Debone
   - vastly improved IFC (Industry Foundation Classes) support
   - introduced API to query importer meta information (such as supported
       format versions, full name, maintainer info).
   - reworked Ogre XML import
   - C-API now supports per-import properties

FIXES/HOUSEKEEPING:

   - hundreds of bugfixes in all parts of the library
   - unified naming and cleanup of public headers
   - improved CMake build system
   - templatized math library
   - reduce dependency on boost.thread, only remaining spot
     is synchronization for the C logging API 

API COMPATIBILITY:
   - renamed headers, export interface, C API properties and meta data
     prevent compatibility with code written for 2.0, but in 
     most cases these can be easily resolved
   - Note: 3.0 is not binary compatible with 2.0

**Comment by danoli3** [comment]
Going to need this one for 0.9 rather than 0.9.3 (as libraries update is going to require it). @bakercp @liquidzym

**Comment by bakercp** [comment]
Hey @danoli3 Can you explain why the 3.0 update is required for 0.9.0?  Does the older version not support 64 bit or something?

**Comment by bilderbuchi** [comment]
If anybody updates ofxassimp, could I ask a favor? Please update by removing the source files, committing, then adding the new files and committing. This way hopefully the line ending headaches that crop up from time to time go away for good....

**Comment by danoli3** [comment]
@bakercp We will need to update the Apothecary formula if we don't want to update it to the latest Assimp yet. Currently it is set to the latest. 
I can try this out with the older version first... might be a better idea for now as this was quite a headache out of all the library updates. 

@bilderbuchi I know right! This has saved my git life so much when switch branches for oF https://help.github.com/articles/dealing-with-line-endings/ damn those ofxAssmipModelLoader line endings omfg XD.

**Comment by pizthewiz** [comment]
Those line endings were the pits!

**Comment by procedural** [comment]
So as of right now ofxAssimp targets 2.0, but [the formula](https://github.com/openframeworks/openFrameworks/blob/c77958d/addons/ofxAssimpModelLoader/scripts/formulas/assimp.sh) builds 3.1?

**Comment by danoli3** [comment]
@procedural correct.

I haven't had any success getting the old library 2.0 to build for iOS with the new Xcode and iOS SDK. Any make files I have found are way outdated and would require a lot of work just to get the old one to compile with latest architectures... if even arm64 is supported, since this was quite some time ago. 

Probably easier to get assimp updated to latest for 0.9, since we already have the changes in the addon fix.

**Comment by arturoc** [comment]
yes we should update the addon. arm linux doesn't have support for assimp either because of this. assimp 3 is in the repos so it's really easy to install but assimp 2 is a pain to compile so we just shipped 0.8.4 for arm linux without it

**Comment by ofTheo** [comment]
@procedural I think this PR #3237 actually deals with the assimp 3.0 issues.
I remember having to make some changes to ofxAssimpModelLoader and those should be included in the PR.

**Comment by bilderbuchi** [comment]
@ofTheo afaict, your PR #3237 was never merged, and the follow-up PR #3521 only contained an update to the formula, not the library code, so are you sure this here is fixed?

**Comment by procedural** [comment]
Yea, the addon still expects Assimp 2 and doesn't work with version 3...

**Comment by ofTheo** [comment]
ah okay - so once we switch the 3.0 lib in I'll merge in the changes from #3237 
Thanks @bilderbuchi !!

**Comment by arturoc** [comment]
this was merged a while ago
