### ISSUE TITLE
ofFbo readToPixels() causing crashes or garbled images

### ISSUE THREAD

**Issue by jasonlevine** [openframeworks/openFrameworks#1674]
Hi,
 I recently moved some of my 0071 source  files into 0072 projects.  For the most part everything works great but a major glitch has appeared in one of my projects.  When the running app attempts to read and ofFbo into an ofPixels object, either the app crashes or else the ofPixels contains a heavily garbled version of the image.

Here is my code:

``` c++
void testApp::exportHiRes(){
hiResFbo.begin();
    ofClear(0);
    if (imageAlpha != 0) {
        ofSetColor(imageAlpha);
        if (imageLoaded == true) image.draw(0, 0, image.width, image.height);
        if (videoLoaded == true) video.draw(0, 0, video.getWidth(), video.getHeight());
    }
    hiResFbo.end();

    ofPixels hiResPixels;
    hiResFbo.readToPixels(hiResPixels);
    ofFileDialogResult dialog_result = ofSystemSaveDialog("hi-res export", "export");
    string filename = dialog_result.getPath() + ".png";
    ofSaveImage(hiResPixels, filename);
}
```

the hiResFbo is allocated when the image or video is loaded just like this:

``` c++
hiResFbo.allocate(image.width, image.height);
```

or

``` c++
hiResFbo.allocate(video.getWidth(), video.getHeight());
```
## 
## 
## 

When the running app crashes, I get a EXC_BAD_ACCESS at his point

``` c++
glGetTexImage(texData.textureTarget,0,texData.glType,GL_UNSIGNED_BYTE, pixels.getPixels());
```

in void ofTexture::readToPixels(ofPixels & pixels), which is called from 

``` c++
getTextureReference(attachmentPoint).readToPixels(pixels);
```

in void ofFbo::readToPixels(ofPixels & pixels, int attachmentPoint) which is called by this line in my code:

``` c++
hiResFbo.readToPixels(hiResPixels);
```

The code is identical to the code in my 0071 project(where there is no prob).

Any ideas?
Anyone else have similar problems?

Thanks,
Jason

**Comment by corybarr** [comment]
I'm hitting a similar issue. When I readToPixels(pixels), I get "Unhandled exception at...Access violation writing location...". I'm on VS12.

The image is 453 x 512. I can draw the image, but just can't read to pixels. Oddly, resizing to 454 * 2 by 512 * 2 works. However, 454 by 512 doesn't. I've created a small app to reproduce the issue at https://github.com/corybarr/imageSizeIssue. I get to the call to glGetTexImage in ofTexture::readToPixels but am not sure how to debug further. Any advice? I'd love to get pixels for arbitrary image sizes. I'm also just really curious to know what's going on. Thanks!

**Comment by arturoc** [comment]
are you using latest from master or 0.8.4? i fixed an issue with this but it's only in the version in github

**Comment by corybarr** [comment]
I'm using 0.8.4. I'll try it with the latest from master. Very cool that it sounds like it's been preemptively fixed. Can I see the patch? I hit the call to glGetTexImage and couldn't debug further. I'm really curious to know what the patch was and how it was tracked down. Thanks!

**Comment by fabiaserra** [comment]
Hello all!

I'm getting a weird result also with readToPixels with the ofxFluid addon from Patricio. I'm using the 0.8.4 stable version.

Here an image of the output, in the left I draw the ofFbo* and in the right the image after using readToPixels, it appears divided in three diagonal parts and the colors are way different:

![screen shot 2015-04-09 at 4 56 58 pm](https://cloud.githubusercontent.com/assets/4348536/7079543/70a083e4-deda-11e4-8014-e83b11bd51bf.png)

Is this a bug or I'm doing something really bad? I wanted to get the pixel values of the fbo in order to get the velocities of the fluid.

This is the code I am using: 

    pingPong.src->draw(x,y,_width,_height);
    
    ofImage img;
    img.allocate(_width, _height, OF_IMAGE_COLOR);
    velocityBuffer.src->readToPixels(img);
    img.update();
    img.draw(300, 0, _width, _width);

Thanks!!!

**Comment by bilderbuchi** [comment]
can you please try with current `master`. probably you issue is already fixed.

**Comment by fabiaserra** [comment]
Yes it worked bilderbuchi! Thanks!!!
