### ISSUE TITLE
ofEnableSmoothing() forces OF_BLENDMODE_ALPHA

### ISSUE THREAD

**Issue by obviousjim** [openframeworks/openFrameworks#1699]
ofEnableSmoothing() doesn't respect the blend mode

excerpt from  ofGLRenderer:

```
void ofGLRenderer::startSmoothing(){
    #ifndef TARGET_OPENGLES
        glPushAttrib(GL_COLOR_BUFFER_BIT | GL_ENABLE_BIT);
    #endif

    glHint(GL_LINE_SMOOTH_HINT, GL_NICEST);
    glEnable(GL_LINE_SMOOTH);

    //why do we need this?
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
}
```

I think we can just take out the force to alpha blending mode, or at least set it to the respected one. Someone know why that's there?

**Comment by liukinwai** [comment]
What is the reason this one is closed. At least the documentation can mention that it will force alpha blend.

**Comment by arturoc** [comment]
it's said in a comment above, is a duplicate of #1546
