### ISSUE TITLE
ofTexture needs massive cleanup.

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#1756]
ofTexture is still very arbitrary, messy and inconsistent. 

There are some very strange things like:
- isAllocate() and bAllocated()
- ofSetMinMagFilters() which is immediate and doesn't actually write to variables
- same with the global clamping methods. 
- a ton of static functions at the top of the cpp
- too many #ifdef OPENGLES  
- duplicated allocate code 
- mipmaps only if texture compression is set ( should be sep ) 
- also no mipmaps for ES 
- supports arbitrary GL formats. we need a better way of handling a large number of formats. 

Outstanding ofTexture issues ( note this list doesn't mean we should implement all suggestions )
#1696
#228 
#810
#454
#292
#1175

I'm going to take a stab at doing a major cleanup.
Will add it as a PR once there is some stuff to review.

**Comment by kylemcdonald** [comment]
i'm going to close this tracking issue since #454 is the only issue left out of the ones listed above. any other remaining items should be added as extra issues.

thanks @danthemellowman for bringing this to my attention!
