### ISSUE TITLE
glPushAttrib causing slow rendering of ofMesh

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#1759]
glPushAttrib appears to be slowing down rendering quite a bit.
I have a considerable amount of box meshes that I am rendering perfectly fine at 60fps. I switched over to rendering a single ofMesh many times that only has 6 verts and it drops the frame rate in half.

I am using OF 0073 official release, non-git version.

When I comment out glPushAttrib in ofGLRenderer, it jumps back up to 60fps

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLRenderer.cpp#L71-L76

Thoughts on addressing this issue?

**Comment by procedural** [comment]
I think this issue can be closed :)
