### ISSUE TITLE
ios main.mm examples are a bit inconsistant  (examples vs template, etc)

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#1772]
the template for IOS and the main.mm for some of the examples are not the same, so it's hard to tell what the best main.mm is...  I am making new projects with the project generator and they have the thin main.mm below (no window generation / window options)....

there are currently two, which seem to be iphone / ipad specific: 

    #include "ofMain.h"
    #include "testApp.h"

    int main(){
        ofAppiPhoneWindow * iOSWindow = new ofAppiPhoneWindow();
        
        iOSWindow->enableAntiAliasing(4);
        
        iOSWindow->enableRetinaSupport();
        
        ofSetupOpenGL(iOSWindow, 480, 320, OF_FULLSCREEN);
        ofRunApp(new testApp);
    }

vs

    #include "ofMain.h"
    #include "testApp.h"

    int main(){
        ofSetupOpenGL(1024,768, OF_FULLSCREEN);			// <-------- setup the GL context

        ofRunApp(new testApp);
    }

I wonder if it would help things to standardize the main.mm and just have some #define for ipad vs iphone target or some commented out section explaining what to use when.

**Comment by admsyn** [comment]
@openframeworks/ios it looks like this can be closed now, right?

**Comment by kylemcdonald** [comment]
#3258 was merged without any problems, and after looking through a few of the most recent iOS examples main.mm files it looks like the original issue is closed.
