### ISSUE TITLE
dragEvent not working (ubuntu 12.04)

### ISSUE THREAD

**Issue by juji** [openframeworks/openFrameworks#1862]
OpenFrameWorks 0073 on Ubuntu 12.04

I tried to build eventsExample from the examples folder

Everything runs smoothly, except for dragEvent. I tried dragging some files, but the app does nothing. It simply doesn't work.

Is this a bug? Or am I doing something wrong?

**Comment by nadous** [comment]
Years later, I'm just wondering if something happens for the implementation of such behaviors on OF 9.8 and Ubuntu 16.04 LTS because I still have zero events fired on `ofApp::dragged(ofDragInfo &info)`.

**Comment by arturoc** [comment]
this is working now, the correct syntax is:

```
//--------------------------------------------------------------
void ofApp::dragEvent(ofDragInfo dragInfo){ 

}
```

also in ubuntu there's sometimes an strange effect where you have to stay in the destination window for a moment before releasing the mouse button, it's something related with unity (the window manager) and happens in other applications.

going to close this but feel free to keep commenting if it really doesn't work for you

**Comment by nadous** [comment]
Thank you for your reply. I should have been more specific: `dragEvent` doesn't appear to be working under **K**ubuntu, so KDE + Dolphin.
