### ISSUE TITLE
Feature: Poco::DateTimeFormatter

### ISSUE THREAD

**Issue by ascorbin** [openframeworks/openFrameworks#1876]
for a racing game i needed time formats like 00:00:000 and found everything inside poco. would be nice to wrap this for of. 

example:
// get pointer to mov
    ofVideoPlayer\* p = (ofVideoPlayer*) e->imgPtr;

```
// get mov times
Poco::DateTimeFormatter dateFormater;
float total = p->getDuration();
float current = p->getPosition();
Poco::Timespan totalTime = total*1000*1000;
Poco::Timespan currentTime = current*total*1000*1000;

string currentTimeString = dateFormater.format(currentTime , "%m:%S");
string totalTimeString = dateFormater.format(totalTime , "%m:%S");
```

greetings ascorbin

**Comment by bakercp** [comment]
Poco is no longer part of the core.  Please consider using c++11 chrono classes for formatting, e.g. 

http://en.cppreference.com/w/cpp/chrono/c/strftime

Closing this issue.
