### ISSUE TITLE
int ofGetFrameNum() to unsigned long long ofGetFrameNum()

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#1930]
Like our recently changed elapsed time functions, `ofGetFrameNum()` could roll over more quickly than expected.

As noted previously by @kylemcdonald 

"If your app is running at 1000fps then ofGetFrameNum() is effectively going to run over at the same point as ofGetElapsedTimeMillis(). so yes, i think it makes sense for it to be switched to an unsigned long long. in general i'm against adding unnecessary precision to things, but i think here it makes sense to be consistent."

This is slightly more work than the elapsed time upgrade because it requires windowing systems to be updated as well.

**Comment by bakercp** [comment]
@arturoc @kylemcdonald @ofTheo Should I make a PR for this?

**Comment by 2bbb** [comment]
:+1:

**Comment by bakercp** [comment]
@arturoc I noticed 

```cpp
unsigned int ofFpsCounter::getNumFrames() const{
	return nFrameCount;
}
```

Should I also set `ofFpsCounter` also use `unsigned long long` for its frame count?

**Comment by arturoc** [comment]
yes please, can you use uint64_t instead, as unsigned int, unsigned long long can be different sizes depending on the architecture.

**Comment by bakercp** [comment]
Will do.

**Comment by bakercp** [comment]
Updated w/ a new PR #4062
