### ISSUE TITLE
ofColor clamp

### ISSUE THREAD

**Issue by emmanuelgeoffray** [openframeworks/openFrameworks#1960]
Hello!
Running this:
```
ofColor c;
c.set(0);
c +=  150;
cout << "c: " << c.getBrightness() << endl;                                    
c +=  150;                                                                     
cout << "c: " << c.getBrightness() << endl;
```

I got this output:
```
c: 150
c: 44
```

Which is obviously an overflow.
I expected:
```
c: 150
c: 255
```

Am I right to expect a clamping at 255?

I use ofFloatColor instead which doesn't have an overflow issue.
But as it was discussed in issue #728, it's a bit confusing.
I think a beginner would use ofColor, and should not face an overflow issue.
What do you think?

Thank you for your enlightenment!
e

**Comment by DomAmato** [comment]
I think this is fixed and can be closed as they are handled by a specific clamping function depending on the type of operation performed

**Comment by kylemcdonald** [comment]
yes, this is fixed now. the output is:

```
c: 150
c: 255
```

closing. thanks!
