### ISSUE TITLE
Lacking ability to name threads

### ISSUE THREAD

**Issue by SoylentGraham** [openframeworks/openFrameworks#1971]
There is no interface to set the name of a Poco thread. Furthermore, setting the thread name in Poco::Thread doesn't set the OS thread name in windows (which is very handy for debugging)

I've implemented this in a branch, (as well as naming from ofThread constructor) but my git branches are a complete mess so I can't make a pull request right now
https://github.com/SoylentGraham/openFrameworks/commits/develop-ofThread_SetName

I have deadlines to meet at the moment but as soon as I've paid the bills I'll sort out my branches and make a PR. In the mean time, if anyone is looking for this feature, here it is... (Is this kind of post more appropriate for the forums?)

**Comment by bakercp** [comment]
Closing this PR as ofThread now supports thread names

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofThread.cpp#L34
