### ISSUE TITLE
Fonts become unreadable when ofEnableSmoothing() turned on in Linux

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#2028]
See forum post:
http://forum.openframeworks.cc/index.php/topic,12418.msg54211.html#msg54211

My fonts turn blocky in an app that has ofEnableSmoothing() turned on. If I disable smoothing everything renders normally.

This is in both 0.7.4 and git develop.
![window](https://f.cloud.github.com/assets/392160/383598/d5df5958-a61d-11e2-84c5-96c27d2f34a1.png)

I'm running Ubuntu 12.10 with an Intel HD4000. I'm wondering if this might be hardware specific.

**Comment by bilderbuchi** [comment]
is this bug still happening?

**Comment by pierrep** [comment]
I just tried to reproduce it, and I can't. I suspect that this original bug was in the MESA Intel Linux drivers...which has since been fixed.

PS: thanks for all your hard work Christoph, sad to see you go! (but understandable of course)

**Comment by bilderbuchi** [comment]
thanks for your kind words! :-)
