### ISSUE TITLE
NDEBUG is not defined in the makefile Release target

### ISSUE THREAD

**Issue by jamezilla** [openframeworks/openFrameworks#2054]
I'm running OF on Linux and noticed that assert() calls do not get compiled away in the Release target. Typically, this is handled by the Makefile (or an IDE project file) by being passed as a `-DNDEBUG` flag to the compiler (e.g. in the CFLAGS).

I don't know if this is a universal practice, but the c++ standard libraries expect this convention (e.g. http://www.cplusplus.com/reference/cassert/assert/) as a way to remove debugging code in the release versions.

I grepped around a bit in the code base, and found NDEBUG is defined in the Visual Studio project files for the Release target, but not anywhere else. Looking through the develop branch, there isn't an obvious place to put this info, but my best recommendation would be to put it in `libs/openFrameworksCompiled/project/makefileCommon/compile.core.mk`.

Maybe create a new variable `RELEASE_TARGET_FLAGS`, and possibly a corresponding `DEBUG_TARGET_FLAGS`? It could be useful to have access to analogs in the config.make template for user customization. Currently there's no easy way to add compiler options to specific make targets, which makes linking debug builds of libraries difficult.

**Comment by bakercp** [comment]
This appears to be fixed at this point https://github.com/openframeworks/openFrameworks/pull/5434
