### ISSUE TITLE
ofPolyline::getSmoothed uses ofVec2f instead of ofVec3f

### ISSUE THREAD

**Issue by jasonlevine** [openframeworks/openFrameworks#2056]
Hi all,

I recently noticed that when I smoothed a 3d polyline, the z coordinates are all wrong.  When I investigated the function I found that because cur is and ofVec2f, the function is only smoothing the x and y coordinates and is ignoring the z value. Changing cur to ofVec3f solved the problem

for(int i = 0; i < n; i++) {
        float sum = 1; // center weight
        for(int j = 1; j < smoothingSize; j++) {
            ofVec2f cur;
            int leftPosition = i - j;
            int rightPosition = i + j;
            if(leftPosition < 0 && bClosed) {
                leftPosition += n;
            }
            if(leftPosition >= 0) {
                cur += points[leftPosition];
                sum += weights[j];
            }
            if(rightPosition >= n && bClosed) {
                rightPosition -= n;
            }
            if(rightPosition < n) {
                cur += points[rightPosition];
                sum += weights[j];
            }
            result[i] += cur \* weights[j];
        }
        result[i] /= sum;
}

**Comment by bakercp** [comment]
Fixed with #2053
