### ISSUE TITLE
Finalize (linuxarm* aka Raspberry Pi) Integration 

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#2134]
Here is a TODO list for finalizing Raspberry Pi Integration (please add some of check them off as they are completed).

- [ ] Finish distcc VM image / distributed compile guide (@danthemelloman) https://github.com/openFrameworks-RaspberryPi/openFrameworks/issues/158
- [x] Update the HOWTO wiki entries for RPI/Panda
- [x] Figure out where to put our startup guide and move it over from the RPI branch
- [x] Create a minimal downloadable release (i.e. precompiled libs, examples, etc)
- [x] Stop referring to it as Raspberry Pi and start referring to it as something like ... linuxarm or enix (@kylemcdonald ).  We want people to know that this now actually brings in strong support for almost any armv6 (RPI) or armv7 platform (pcduino, pandaboard, beagleboard, etc).
- [ ] After #2094 is merged, make sure it plays nicely with the linuxarm components.
- [ ] Close (or migrate) all issues in the https://github.com/openFrameworks-RaspberryPi/openFrameworks, suspend the repo and make it clear that the branch has been integrated into the core.

@danthemellowman
@jvcleave
@arturoc

**Comment by kylemcdonald** [comment]
hey @bakercp can we close this? i think it's finalized ;)
