### ISSUE TITLE
ofxAssimp dealocation bug

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#2155]
Hi,
the ofxAssimp addon has a problem with dealocation. it crashes when the ofxAssimpModelLoader destructor is called, specifically when this is called

```
ofxAssimpModelLoader::clear(){
....
if(scene){
        aiReleaseImport(scene);//this is the function that crashes
        scene = NULL;
    }
....
}
```

No idea what´s going on. 
Anyone?

**Comment by underdoeg** [comment]
Looks like we are having the same problem. Did you find anything?
