### ISSUE TITLE
ofSystem with Poco::Process.

### ISSUE THREAD

**Issue by diasbruno** [openframeworks/openFrameworks#2162]
i'm writing an app with a node.js backend, so i'm using a lot ofSystem. the current implementation seems to be inconsistent. with Poco::Process, it works fine.

the new ofSystem would be something like this.

```
// like 'ofFileDialogResult'.
class ofSystemResult {
public:
    ofSystemResult();

    string result;
    int exit_code;      
};

ofSystemResult ofSystem( string cmd, ofSystemArgs& args );
```

**Comment by bakercp** [comment]
Closing this, as Poco is no longer part of the core.  If there is a discussion of a non-Poco way to implement it, then let's reopen because the need is probably still there.
