### ISSUE TITLE
Better mouse / scroll / touch gesture callbacks. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#2176]
moving this conversation from #2174 to a new issue. 

quoting @ofTheo: 
scroll would be so nice :) 
what if we made a single event type for gestures?

``` c++
testApp::gestureEvent(ofGestureArgs & args){
  if( args.type == OF_GESTURE_SCROLL ){
  }
}
```

that could allow for some higher level gestures for iOS / Android as well as gestures for OS X and things like scroll wheel.

it would also mean we could add/update the gestures over time?

quoting @arturoc 

yeah, that would be great to have, but perhaps it makes more sense for touch only?

for mouse perhaps we can do the same by creating a new ofMouseEvent event that has a type field which can be pressed, released, moved, dragged, scrollup and scrolldown. then apps will use the old syntax + a new listener function and the events can be joined in one. so:

ofEvents().mousePressed
ofEvents().mouseReleased
ofEvents().mouseDragged
ofEvents().mouseMoved

become

ofEvents().mouseEvent

where the argument has a type field (i think this kind of event is already there to make it easier to send the notification to the core from the appWindows)

and apps preserve the listener functions and add:

void mouseScroll(ofMouseScrollDir upDown)

where upDown can be OF_MOUSE_SCROLLUP/DOWN

although this would break lots of projects :)

**Comment by bakercp** [comment]
Hi @ofTheo I've done a lot of work to unify oF events into pointer events (based closely on the W3C spec).  You cay try it out here: https://github.com/bakercp/ofxPointer  The develop branch is 0.9.0 compatible.  I'm currently using it to develop ofxDOM, which also supports all the basic gesture events on desktop, mobile / touch, wacom tablet, etc.

**Comment by Teatoller** [comment]
Hi, @arturoc @ofTheo.
The two of you who were close to the origination of "Better mouse/scroll/touch gesture callbacks. #2176 issue.
It looks like @ghost! had a hack that was slightly questioned then put to rest by @groolot.

Was the hack acceptable to all?

Regards
Steven Ennis.

**Comment by ofTheo** [comment]
Hi @Teatoller 

Actually this is already addressed here:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L1361-L1373

So I guess we can close this 🙂

**Comment by Teatoller** [comment]
> Hi @Teatoller
> 
> Actually this is already addressed here:
> https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L1361-L1373
> 
> So I guess we can close this

Thank you for the comprehensive response and action.

Regards
Steven Ennis.
