### ISSUE TITLE
ProjectGenerator issues 

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#2273]
I'm noticing a number of issues with the "old" PG in `apps/devApps/projectGenerator`:
- seems to not use addons_config.mk ADDONS_INCLUDES_EXCLUDE
- if you generate/update projects for multiple CodeBlocks platforms(win, linux), the files are overwritten (I assume this is by design since a suffix in the name wouldn't be needed in the platform zip download)
- the win codeblocks project I generated fails to link with the following error:
  
  cannot find -lstrmbase
  cannot find -lz

**Comment by bakercp** [comment]
@danomatika Doing some housecleaning, has this been addressed?  If not, can we move it to the PG issue tracker?

**Comment by danomatika** [comment]
Close for now. We can reopen if similar issues persist.
