### ISSUE TITLE
Warnings from missing/invalid debug info (iPhone)

### ISSUE THREAD

**Issue by colevscode** [openframeworks/openFrameworks#233]
Hi. FreeImage and FreeType generate several warnings for me. They generally are the result of the dsymutil failing while attempting to create the dSYM file. 

Warnings look like this:

warning: (armv6) libs/freetype/lib/iphone/libFreeType_iphone_universal.a(ftinit.o) object file 'libs/freetype/lib/iphone/libFreeType_iphone_universal.a(ftinit.o)' doesn't contain architecture information for armv6.

And when building for the simulator I get a lot of these: 

warning: invalid DWARF generated by the compiler: DIE 0x000016a6 has multiple  AT_byte_size attributes in 'libs/FreeImage/lib/iphone/libFreeImage_iphone_universal.a'

Is there a way to clean these warnings up?

Thanks!!

**Comment by KNNMMDV** [comment]
Did you fix it?
