### ISSUE TITLE
kinectExample missing libusb0.dll on windows!!

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#2452]
In the current OF 0.8.0 release when you build and run the kinectExample on windows, at runtime there is an error: missing libusb0.dll 

Tested on Visual Studio 2012 and CB 12.11 on Windows 7 32bit 

The libusb libs its linking against look like stublibs hence why the app is looking for the dll. 

ping @danomatika

**Comment by igiso** [comment]
I am still seing this with kineckt for windows 1517 under windows 10 . tried everything includeing the zadig app. nothing worked, if I paste the .dll .sys either on the bin directory or inside windows system folder I get another criptic error about dll not for this system.


I am trying to set it up on a nuc i7 64 bit windows 10

any ideas...


I am thinking of downloading the windows runtime.. will it mess things up even further?

**Comment by moebiussurfing** [comment]
any succes on this @igiso ?

**Comment by igiso** [comment]
yes look it up in the forum

**Comment by LauraLaureus** [comment]
@igiso  can you provide the link to your forum thread. I'm still confusing, I have used the zapier programm and it stills prompts the missing dll error.  y.y I needs this project to get two Kinect v2 working together for my master final project.

**Comment by LauraLaureus** [comment]
There is another solution for windows 10? I have used zadig and it didn't solve the problem. I need this for my final project.

**Comment by ofTheo** [comment]
@LauraLaureus - I think the solution on our end is to include 64bit versions of the libusb dlls 
For now - does it work if you install the drivers via the OF inf files and then build and run your OF app as 32bit ( not 64bit )?

**Comment by LauraLaureus** [comment]
I have still blocked at this point. My drivers are pointing to the ia64 folders inside the inf, because somebody in openframeworks forum did so, and neither the 64bits nor 32bits buildings of the example works. 
I think that the main problem its that the instructions isn't clear enough. Where should I point the drivers to the inf folder (in this case the Win10 device administrator displays a yellow triangle telling the device cannot be started) or to the ia64 inside the inf folder?
Does the project only works in 32bits?

**Comment by igiso** [comment]
What error do you get, and what KINECT do you have, make sure you have a supported model that wasn't updated etc.

The guide in the forum is the correct way to do it.

Don't follow the guide in the OF readme , there is a minor "mistake" for the 64 bit that will mess things up,
Either way it is fixable by, removing the drivers from device manager, and then following the procedure in the forum.

(assuming you have a usable kinect)

Take care.

**Comment by LauraLaureus** [comment]
It doesn't find the libusb0.dll 

I use the Kinect v2 in Windows 10 64 bits with Visual Studio 2015.

**Comment by ofTheo** [comment]
@igiso  - it would be helpful if you could post a link to the guide you keep referencing. 
There are several forum posts in the forum about this issue, but if you could add a link here to the one you mention that would be great! 

Also if there is a small mistake you mentioned - in the read me - could you let us know what it is? We could then update it on our end.  

Our goal is to get it working the easiest way possible for new users, so anything we can change in OF to make that possible we will do.  

Thanks!!
Theo

**Comment by ofTheo** [comment]
@LauraLaureus Ahh the Kinect V2 is not supported with ofxKinect only the Kinect V1. 
For KinectV2 I would recommend - https://github.com/elliotwoods/ofxKinectForWindows2 

Its a fairly advanced addon and I should note that it only works in 64bit.

**Comment by LauraLaureus** [comment]
Do you know if it support several cameras? I have to use 2  for my master project and I'm getting crazy since de official microsoft SDK only support one camera at once u.u

**Comment by ofTheo** [comment]
@LauraLaureus - On Windows I don't believe you can use multiple Kinect V2 
Multiple V1 is possible. 

You can do Multiple V2 on OS X however with https://github.com/ofTheo/ofxKinectV2 ( if you have 2 USB 3 ports on the machine )

**Comment by LauraLaureus** [comment]
I have also two 3.0USB ports in my windows, there is any other restriction to have two cameras working? I'm think about testing that repo on windows.

**Comment by ofTheo** [comment]
@LauraLaureus  I don't believe it will work on Windows with more than one Kinect V2
