### ISSUE TITLE
Window not being redrawn while resizing

### ISSUE THREAD

**Issue by bgstaal** [openframeworks/openFrameworks#2456]
Since the switch to GLFW for windowing the window is not redrawn while being resized. See this screenshot from the advanced 3d example (Taken while resizing the window):

![redraw-error](https://f.cloud.github.com/assets/165258/953491/6db5463e-03f7-11e3-840e-961a49fc8516.png)

I tried switching to ofAppGlutWindow in main.c and then everything works fine.

I've only tested this on Mac OS 10.7

**Comment by kritzikratzi** [comment]
just looked into this in osx10.9/of 0.9.3.

in my sketch i used `ofSetBackgroundAuto(true)` and added `instance->draw();` to the end of the `resize_cb` callback. 
i've really tried to break it or make it crash, very solid so far. 
i'm gonna leave this change on my computer. if i'm not writing back within a few days there's a high chance it worked and there were no issues.

**Comment by igiso** [comment]
nice find hansi 🍺

**Comment by igiso** [comment]
![screen shot 2016-05-20 at 08 25 31](https://cloud.githubusercontent.com/assets/2058400/15418094/0f5ca402-1e65-11e6-8431-b5763f4a7e63.png)

![screen shot 2016-05-20 at 08 26 09](https://cloud.githubusercontent.com/assets/2058400/15418099/167cd4dc-1e65-11e6-8c11-9a08702d406f.png)

![screen shot 2016-05-20 at 08 26 20](https://cloud.githubusercontent.com/assets/2058400/15418102/1e92bc36-1e65-11e6-85f5-bb874d9e11fe.png)

**Comment by kritzikratzi** [comment]
@igiso that is basically the same. in of 0.9 the draw function no longer makes that call to poll events, so the bool param is unnecessary now.

**Comment by igiso** [comment]
ah, I see..
