### ISSUE TITLE
ofxTCPManager connect timeout feature

### ISSUE THREAD

**Issue by trentbrooks** [openframeworks/openFrameworks#2515]
Hi, I was wondering if it would be useful to have a timeout for the Connect method in ofxTCPManager as there is for sending, receiving and accepting TCP messages? Without a timeout, an application attempting to connect to an invalid ip address (eg. "126.0.0.1") will hang for about 90 seconds then crash.

Here's a post on the forum which describes the problem with a few back links-
http://forum.openframeworks.cc/index.php/topic,13104.0.html

And here is a fix (with 5 second timeout) -
https://github.com/trentbrooks/openFrameworks/commit/9ef106ceadee7953bfc02c37b7a62d79065b7ae5

Trent

**Comment by bilderbuchi** [comment]
closed by #2519
