### ISSUE TITLE
008 targets iOS 4.0 (Non-PIE Binary)

### ISSUE THREAD

**Issue by chrisoshea** [openframeworks/openFrameworks#2542]
submitted an app update using 008 and got an email from apple

Non-PIE Binary - The executable is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to
https://developer.apple.com/library/ios/qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354

Maybe the minimum deployment target for the openframeworks lib should be 4.3?

**Comment by bilderbuchi** [comment]
@julapy has this been fixed in the meantime?

**Comment by pizthewiz** [comment]
This might be fixed once #3651 is merged, I believe all the binary dependencies need to be build with PIE as well.

**Comment by danoli3** [comment]
Can definitely close this now.
