### ISSUE TITLE
C++11 support in OF

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#2577]
This is the overview issue to coordinate getting C++11 support in openFrameworks on all platforms. Feel free to comment and/or edit this post as appropriate.

A separate Github organisation has been created to facilitate the transition to C++11: https://github.com/organizations/openFrameworks-cpp11

Separate issues concerning different platforms are as follows:

## MacOS:
The way to go here is to go the route of `libc++` and `clang`. See issues #1864 (go there to discuss), #2335, #2087. 

## Windows: 
PR #2571 is underway to get C++11 suport for Visual Studio

## Linux: 
...

## Other platforms
...

## General issues:
#2005,

**Comment by bilderbuchi** [comment]
hm, should we close this issue, since C++11 coordination is handled in other issues throughout the tracker, afaict?

**Comment by yoiang** [comment]
Makes sense to me!
