### ISSUE TITLE
projectGenerator not opening in latest OSX (Mavericks)

### ISSUE THREAD

**Issue by ashszu** [openframeworks/openFrameworks#2649]
Not sure whether this is affecting others but I'm unable to open the projectGenerator on the latest mac OS. I get an error message stating:

"projectGenerator" can't be opened because it is from an unidentified developer.

I'm pretty new to OF so if there is a way so sort this out myself I'd love to know.

Thanks in advance

**Comment by bangnoise** [comment]
It would be nice if the PG and any other built apps in the distribution were code-signed. Not permitting unsigned software to run is the default on OS X, so most users will experience this and many will not know a solution.

Presumably OF has some budget to cover Mac Developer Program membership, or maybe there is an existing developer with program membership and a knowledge of the codebase who would be willing to sign the builds posted for distribution?

**Comment by ofZach** [comment]
yeah I was thinking about this, I'm not sure we will be able to hit this for 0.9, but it seems mostly to be related to this script, which is doing the actual building on OSX: 

https://github.com/openframeworks/projectGenerator/blob/master/scripts/osx/buildPG.sh

there's some info / starting points for how to do this here on travis (but alot of the details tend to be ios specific, but this should be a good starting point for researching this): 

https://github.com/travis-ci/travis-ci/issues/2149

Also, this is some info about how to sign the OSX electron app (it's not clear to me if the command line app needs to be signed as well as the electron shell): 

http://jbavari.github.io/blog/2015/08/14/codesigning-electron-applications/

it would be good to figure out how to do this in an automated fashion, in the past it's been really hard when we have a manual step in the build process.
