### ISSUE TITLE
iOS deployment target 7.0 leads to error: 'tr1/memory' file not found

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#2695]
apps have a really low deployment target (3.1), when you switch the deployment info under general->deployment info->deployment target or you pick a different device (ipad, iphone, etc) and the deployment target changes automatically, when it's set to iOS 7.0 you get the following memory tr1 error: 

In file included from ../../../libs/openFrameworks/utils/ofLog.h:5:
../../../libs/openFrameworks/types/ofTypes.h:9:10: fatal error: 'tr1/memory' file not found

the quick fix is to set the deployment target to 6.0, but I couldn't find a compile setting to get deployment target 7 to work ok.

**Comment by rstecca** [comment]
I'm having this issue with 0.8.4 ios on Yosemite
