### ISSUE TITLE
'androidCameraExample' doesn't display frames after resuming (Nexus-4)

### ISSUE THREAD

**Issue by fossterer** [openframeworks/openFrameworks#2719]
I'm using the latest version after Commit# e589c2e46d6134e56672d4d1ff228bee8951fdb0.

After resuming, the app displays frame rate as a valid number but no frames are visible. The app has to removed from the 'Recent Apps' list for it to function normally again

**Comment by danthemellowman** [comment]
this has been fixed.  tested with master on my Note 4

**Comment by arturoc** [comment]
thanks!
