### ISSUE TITLE
FBO not being drawn after 2dc1fed

### ISSUE THREAD

**Issue by martinell** [openframeworks/openFrameworks#2738]
I am using a version of the https://github.com/benMcChesney/ofxPixelHitTest extension on iOS to detect user interaction. It worked for me perfectly until this commit (2dc1fed). What the ofxPixelHitTest does, is to draw the scene into an FBO and then read the pixels of that FBO and draw the FBO as a texture. I need to comment the uploadMatrices call to get it working again: 
```cpp
 void ofGLProgrammableRenderer::setCurrentFBO(ofFbo * fbo){
 	if(fbo!=NULL){
 		matrixStack.setRenderSurface(*fbo);
	//	uploadMatrices();
 	}else{
 		matrixStack.setRenderSurface(*ofGetWindowPtr());
		uploadMatrices();
 	}
 }
```
The interesting part is that the extension, reads the FBO's texture pixels to perform the hit test, and this seems to work but, when I try to draw the FBO, it draws in black. Both operations are done after calling fbo.end().

For more info, I am using the OpenGL ES2 renderer.

**Comment by tgfrerer** [comment]
As of the current codebase, `ofGLProgrammableRenderer::setCurrentFBO` has no implementation, the implementation has been removed in commit 94cb65672e92dc33dc67733f4397699f15a41399

I suspect it's just the header file that needs updating to remove the method signature, but let's ask @arturoc if he remembers what's best.

**Comment by arturoc** [comment]
should we close this then?

**Comment by tgfrerer** [comment]
i would say so =)

**Comment by arturoc** [comment]
i don't think this is an issue anymore since other people would have noticed but if it's still a problem feel free to reopen
