### ISSUE TITLE
64 bit support (windows VS)

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#2758]
Sorry if this repeats another issue -- I couldn't find it.  There's different issues around 64 bit support (for osx, ubuntu, etc), this useful info for windows VS was posted on the forum (from @dotchang), just wanted to flag it as we attack 64 bit issues at once: 

http://forum.openframeworks.cc/t/where-can-i-get-glfwsetdropcallback-source-code/14211
http://cvl-robot.hateblo.jp/entry/2013/12/27/171912

looks like we'll need to replace the video player with @oftheo's new DS player and deal with drag and drop modifications to glfw (he's using pre-compiled version)

**Comment by bilderbuchi** [comment]
closed by #2571
