### ISSUE TITLE
Simplify renderer by use of cogl

### ISSUE THREAD

**Issue by abergmeier** [openframeworks/openFrameworks#2763]
Since _cogl_ is now [MIT licensed](http://anzwix.com/a/COGL/ThisRelicensesCoglUnderTheMITLicense), I wonder whether it would make sense to use it to simplify the rendering code. Has anyone ever looked into this?

**Comment by tgfrerer** [comment]
Yep, looked into this, but it doesn't seem to be a feasible cross-platform option at the moment. I'm closing this now, but feel free to re-open it if there's an easy way to make this work over all platforms we currently support.
