### ISSUE TITLE
Wrong version of the Poco Library for VS2012 support

### ISSUE THREAD

**Issue by philippelaulheret** [openframeworks/openFrameworks#2771]
It appears the VS2012 Poco library oF 0.8.0 is using is different than the one used by all the other platforms. 

````
printf("%x\n", Poco::Environment::libraryVersion()); 
````
Returns 0x1040601 instead of 0x1040301 (ie the library version should be 1.4.3p1)

It causes a missing reference to HTTPBasicCredentials::authenticate() (see [oF forum](http://forum.openframeworks.cc/t/problem-with-poco-static-libraries-on-windows/))

**Comment by LeoColomb** [comment]
Moved to #3843

**Comment by bilderbuchi** [comment]
closing this, then.
