### ISSUE TITLE
RFC: .gitignore template file for project generator

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#2791]
Preparing the OFbook chapter on version control, I realized that it would be useful for our users if our project generator would offer to add a `.gitignore` example file to newly generated projects, so users who want to use Git don't have to come up with their own solution.
Failing that (or until that is implemented), I would at least put such a file at an appropriate place in the OF repo so that interested users can get it manually.

Thoughts on that? Would this be welcomed? Where should I put this `example-.gitignore` file? I'm thinking `/scripts/` would be a good place, since all the project templates that the PG uses are deeper in that tree (correct?), in OS-specific directories, but `example-.gitignore` is not really OS-dependent. Or do we have a place where PG-related, OS/IDE-independent files reside?

@ofZach @arturoc @kylemcdonald @ofTheo

**Comment by bilderbuchi** [comment]
@ofZach @arturoc  would this be something you'd find useful in the PG/project templates?

**Comment by arturoc** [comment]
yes i think it would be useful, it could even be a new template that can be optionally applied to a project. do you want to send a PR?

**Comment by bilderbuchi** [comment]
can do, the proposed gitignore file is already [here](https://github.com/openframeworks/openFrameworks/issues/2791#issuecomment-35990153). question: where should I put it in the filetree?

**Comment by arturoc** [comment]
in scripts/templates/gitignore/.gitignore along with a template.config file, you can check the format in any of the none platform templates (any of the gl ones for example)

**Comment by bilderbuchi** [comment]
thank you, done: #4623
