### ISSUE TITLE
ofFbo: passed settings not equal to created ones error

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#2834]
I am using an ofFbo but am delaying the allocation in case it is not used. When I go to allocate it I get the message `ofFbo: allocation not complete, passed settings not equal to created ones, this is an internal OF bug`

It looks like wrapModeVertical/wrapModeHorizontal are not compared?

```
if (!fbo.isAllocated())
{
	ofFbo::Settings fboSettings;
	fboSettings.width = videoWidth;
	fboSettings.height = videoHeight;
	fboSettings.wrapModeVertical = GL_REPEAT;	
	fboSettings.wrapModeHorizontal = GL_REPEAT; 
	fbo.allocate(fboSettings);
}
```

**Comment by ofTheo** [comment]
this seems fixed now in 0.9.0
