### ISSUE TITLE
thread-safety issue w/ ofToDataPath & VS2012

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#2874]
Ok, so this is a pretty weird issue, and may be related to something within the visual studio compiler, but nonetheless a beast to debug.

It seems that the programming pattern used for openFrameworks static variables like dataPath (declared in utils.cpp) can lead to multi-threading issues: Some threads will see the static variable initialised, and others might not, hitting NULL, and failing the app with an Access Violation Error.

This seems to be related to the lazy-allocation pattern used for some openFrameworks static variables. ```dataPathRoot```, declared in ofUtils.cpp:L234 seems to be one of these.

If I insert this into ofApp::setup() all seems well:

	/// comment this line and see bad things happen in vs2012 debug mode:
	ofToDataPath("dummy");
	
	vector<std::thread> workers;

	for (int i = 0; i < 10; i++)
	{
		workers.push_back(std::thread([&,i](){
			ofLogNotice("pretending to load file: " + ofToDataPath(ofToString(i) + ".txt"));
			ofSleepMillis(10);
		}));
	}

	for (auto &w : workers){
		w.join();
	}

if i uncomment the line indicated, all sorts of weird things happen, especially in debug mode, release mode seems weirdly immune to the problem.

If the static variable had been initialised before going multithreaded, all is well, which is why i'd suggest - as a quick fix - to make sure to have these lazy allocated statics initialised by default before ofApp::setup() is hit.

@arturoc, what do you think?

**Comment by tgfrerer** [comment]
Seems this (the data race) has been fixed compiler-side with VS2015RC. Tested both release and debug on windows, and it works. 

The question remains whether we want to have an `init()` method which sets up the environment somewhere...

**Comment by arturoc** [comment]
we have an ofInit now which could set the path, it's in ofAppRunner

**Comment by arturoc** [comment]
oh actually it's already doing it :) going to close this then
