### ISSUE TITLE
settings.xml creation raise an error

### ISSUE THREAD

**Issue by LeoColomb** [openframeworks/openFrameworks#2901]
#### Examples

Everything about ofGui & parameters
#### Environmemnt
- Win8 x64
- VS2012
#### Output

```
[ error ] ofXml: loadFromBuffer(): DOM ERROR
```
#### Reproduction

Run `parameterGroupExample` for eg.
Click to save settings.
#### Notes
- The file `settings.xml` is created, and looks good.
- Reloading it works well.
- Rewrite / resave works perfectly without error.
- There are too many new lines.

``` xml
<settings>

    <vSync>1</vSync>

    <renderer1>

        <size>10</size>

        <number>2</number>

        <position>512, 384</position>

        <color>127, 127, 127, 255</color>

        <frameNum>108</frameNum>

    </renderer1>

    <renderer2>

        <size>10</size>

        <number>2</number>

        <position>512, 384</position>

        <color>127, 127, 127, 255</color>

        <frameNum>108</frameNum>

    </renderer2>

</settings>
```

**Comment by bakercp** [comment]
Now that ofXml is backed by pugi, I'm going to close this unless someone wants to retrofit the poco xml version.
