### ISSUE TITLE
ofImage.loadImage() can't detect format of .png

### ISSUE THREAD

**Issue by mysteryDate** [openframeworks/openFrameworks#2965]
While loading this image: 
![beaver_cycle20001](https://cloud.githubusercontent.com/assets/2529989/2879921/38abb042-d46f-11e3-8d28-a8d4cd0ef49f.png)
(a png with transparency) through ofImage.loadImage() I get the error:

```
ofGLUtils: ofGetGlFormatAndType(): internal format not recognized, returning GL_RGBA
```

  Which should work, as the image is RGBA, however it just shows up as black.

When loading this image:
![png_transparency_demonstration_1](https://cloud.githubusercontent.com/assets/2529989/2879931/4feb8dcc-d46f-11e3-9049-94ee218f5221.png)
(another png with transparency) everything works fine. The first image loads fine into other software (preview, obviously browsers). What might the problem be?

**Comment by dennishahn** [comment]
I am using the openframeworks version "of_v0.9.8_ios_release" and experience a very similar problem. 

Some of my .png files just don't load. I checked loading with around 30 files (all in the project's bundle folder) and experience the problem always with the same files. 

This is how I try to load the image:
```
ofImage ckeckImageLoad;
 BOOL worked = ckeckImageLoad.load("imageName.png")
```
I traced down the call stack to the position where loading differs from the once which can be loaded successfully. It's in Line 197 of the ofImage.cpp class:

`bmp = FreeImage_Load(fif, fileName.c_str(), 0);`

Is it possible that there is still a problem? Or is there any restrictions with png files in openframework. The files can be opend by methods within objectiv-c without any problems. 

Thanks for any help!
Dennis
