### ISSUE TITLE
get position of ofxAssimpModelLoader mesh

### ISSUE THREAD

**Issue by minusplusminus** [openframeworks/openFrameworks#2989]
Hi, 

I'm trying to get a position of a mesh from Assimp. But I could not figure out how. Is there a simple solution for this? This could be a handy feature.

**Comment by edap** [comment]
What if, ofxAssimpModelLoader, when importing the meshes, convert them to of3dPrimitive?
of3dPrimitive has ofNode, and all the meshes belonging to the same model could have as parent an ofNode that defines the position of the model.
In this way it is also easier move the model around and getting the position.

**Comment by NickHardeman** [comment]
Each node in ofxAssimp extends ofNode, ie meshes and bones. Meshes have both local and global bounding boxes and a center location. Functions have been added to get the transformed vertices as ofMeshes. 
https://github.com/openframeworks/openFrameworks/blob/5b651b93910478fc7e0adcc6b88cc04731c8bbd0/addons/ofxAssimp/src/ofxAssimpModel.h#L175-L182 

closed by #7776
