### ISSUE TITLE
Dragging a retina app from retina screen to non-retina screen causes very strange things

### ISSUE THREAD

**Issue by danzeeeman** [openframeworks/openFrameworks#3005]
Dragging a retina app from retina screen to non-retina screen causes very weird scaling issues. 

![screenshot 2014-05-30 11 22 54](https://cloud.githubusercontent.com/assets/719564/3153454/b016de26-ea9b-11e3-8596-9dc2db995136.png)
![screenshot 2014-05-30 11 22 51](https://cloud.githubusercontent.com/assets/719564/3153455/b01700b8-ea9b-11e3-968a-fa27c80efb94.png)

occurs on master running on a late 2013 mbp_r with NVIDIA GPU running 10.9.3

**Comment by valillon** [comment]
Probably related to #4703

**Comment by kritzikratzi** [comment]
yes, both bugs talk about the same problem and 4703 already has a (possible) patch. imho this can be closed.

**Comment by valillon** [comment]
Yes and it's already committed in #5717. So this can be closed.

**Comment by tgfrerer** [comment]
closing this then - @danzeeeman feel free to re-open should issue persist
