### ISSUE TITLE
bug : ofSystemLoadDialog and ofSystemSaveDialog hang on VS2012

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#3014]
Likely related to:

https://github.com/openframeworks/openFrameworks/commit/1a592c2981a1f21e280fd17215b398335c426f22

and perhaps observed by theo at:

https://github.com/openframeworks/openFrameworks/commit/0bc9db2f8c8efcc97b1ce65b63760a50ccc193d8

Symptoms:
Hangs on line
`		if(GetOpenFileName(&ofn)) {`
of ofSystemUtils.cpp (almost as if the dialog is invisible)

on call to either save or load dialogs after build with VS2012 (with or without any arguments).

**Comment by DomAmato** [comment]
I think this is fixed?

**Comment by elliotwoods** [comment]
yes it's fixed now. thank you!
