### ISSUE TITLE
Remove Poco CppUnit from all projects ( done on os x )

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#302]

**Comment by bilderbuchi** [comment]
that's only for iOS, though?

**Comment by danoli3** [comment]
All platforms in the Poco Formula have these omitted.
So when the new libs and headers are added it will be all done. 

This may be flagged as closed now, as the Formula script is in the master to fix this.

**Comment by bilderbuchi** [comment]
thanks for the update!
