### ISSUE TITLE
ofSystemUtils.cpp merging mingw&Visual Studio code 

### ISSUE THREAD

**Issue by igiso** [openframeworks/openFrameworks#3041]
Greetings friends!

ofSystemUtils.cpp splits the windows code into two pieces using 
# ifdef _MSC_VER
# define TMP_STR_CONVERT LPCWSTR

with the excuse that ming wants non wide

ming doesn't "want" ASCII nor vs "wants" wide characters

you can as easily make VS only use ASCII and ming use WideCharacters

It is not just a cosmetic issue it also creates a series of problem when working with other languages.

Luckily this can very easily be solved .

First we remove the precompiler stuff& ascii codeblocks code and only keep the VS part of the code

If we try to compile this in CODE::BLOCKS it will not work because ming will by default try to link 

WNDCLASSEX wc;

with 

WNDCLASSEXA wc;

instead of 

WNDCLASSEXW wc;

All we have to do to fix the code is replace all ambiguous calls to windows functions into widechar specific calls.

and this will not brake anything for English-speaking users

Here is an example of a function,

I wrote a ofSystemPassword() function that is based on the ofSystemTextBoxDialog()
to make things more clear. and also get something out of it.

ps:
I use ofSystemPassword() in cases like "RESET PROJECT SETTINGS" . you don't want a museum employ accidentally using your RESET function, do you? ,(not that I actually have a piece in a museum :) )

Anyway here is the example:

<pre lang="c++"><code>
string ofSystemPassword(string question, string text){
#if defined( TARGET_LINUX ) && defined (OF_USING_GTK)
 initGTK();
 GtkWidget* dialog = gtk_message_dialog_new (NULL, (GtkDialogFlags) 0, GTK_MESSAGE_QUESTION, (GtkButtonsType) GTK_BUTTONS_OK_CANCEL, question.c_str() );
 GtkWidget* content_area = gtk_dialog_get_content_area (GTK_DIALOG (dialog));
//this might now work on linux
 GksuuiDialog* textbox = gtk_entry_new();
 gtk_entry_set_text(GTK_ENTRY(textbox),text.c_str());
 gtk_container_add (GTK_CONTAINER (content_area), textbox);
 gtk_widget_show_all (dialog);
 if(gtk_dialog_run (GTK_DIALOG (dialog))==GTK_RESPONSE_OK){
  text = gtk_entry_get_text(GTK_ENTRY(textbox));
 }
 startGTK(dialog);
#endif
#ifdef TARGET_OSX
 // create password dialog
 NSAlert *alert = [[[NSAlert alloc] init] autorelease];
 [alert addButtonWithTitle:@"OK"];
 [alert addButtonWithTitle:@"Cancel"];
 [alert setMessageText:[NSString stringWithCString:question.c_str()
            encoding:NSUTF8StringEncoding]];
 // create secure pass field
 NSSecureTextField* label = [[NSSecureTextField alloc] initWithFrame:NSRectFromCGRect(CGRectMake(0,0,100,40))];
 [label setStringValue:[NSString stringWithCString:text.c_str()
            encoding:NSUTF8StringEncoding]];
 [alert setAccessoryView:label];
 NSInteger returnCode = [alert runModal];
 if ( returnCode == NSAlertFirstButtonReturn )
  text = [[label stringValue] UTF8String];
#endif

#ifdef TARGET_WIN32
    WNDCLASSEXW wc;
    MSG Msg;
    int OF_CENTER_POSX_ = 0;
    int OF_CENTER_POSY_ = 0;
    const LPCWSTR g_szClassName = L"myWindowClass\0";
    //Step 1: Registering the Window Class
    wc.cbSize        = sizeof(WNDCLASSEX);
    wc.style         = CS_HREDRAW | CS_VREDRAW;
    wc.lpfnWndProc   = WndProc;
    wc.cbClsExtra    = 0;
    wc.cbWndExtra    = 0;
    wc.hInstance     = GetModuleHandle(0);
    wc.lpszClassName = g_szClassName;
    wc.hbrBackground = (HBRUSH)(COLOR_3DFACE + 1);
    wc.lpszMenuName  = NULL;
    wc.hCursor       = LoadCursor(NULL, IDC_ARROW);
    wc.hIcon         = LoadIcon(NULL, IDI_APPLICATION);
    wc.hIconSm       = LoadIcon(NULL, IDI_APPLICATION);
    if(!RegisterClassExW(&wc)){
        DWORD err=GetLastError();
        if ((err==ERROR_CLASS_ALREADY_EXISTS)){
            ; // we are ok
            // http://stackoverflow.com/questions/5791996/re-registering-user-defined-window-class-c
        } else {
            MessageBoxW(NULL, L"Window Registration Failed!\0", L"Error!\0",
                        MB_ICONEXCLAMATION | MB_OK);
            return text;
        }
    }
    HWND dialog = CreateWindowExW(WS_EX_DLGMODALFRAME,
                                  g_szClassName,
                                  convertNarrowToWide(question).c_str(),
                                  WS_POPUP | WS_CAPTION | DS_MODALFRAME | WS_SYSMENU,
                                  OF_CENTER_POSX_, OF_CENTER_POSY_, 240, 140,
                                  WindowFromDC(wglGetCurrentDC()), NULL, GetModuleHandle(0),NULL);

    RECT rc;
    GetWindowRect ( dialog, &rc ) ;
    OF_CENTER_POSX_ = (GetSystemMetrics(SM_CXSCREEN) - rc.right)/2;
    OF_CENTER_POSY_ = (GetSystemMetrics(SM_CYSCREEN) - rc.bottom)/2;
    SetWindowPos( dialog, 0,  OF_CENTER_POSX_, OF_CENTER_POSY_, 240, 140, SWP_NOZORDER | SWP_NOSIZE );

    if(dialog == NULL)
    {
        MessageBoxW(NULL,L"Window Creation Failed!\0", L"Error!\0",
                    MB_ICONEXCLAMATION | MB_OK);
        return text;
    }
    EnableWindow(WindowFromDC(wglGetCurrentDC()), FALSE);
    HWND hEdit = CreateWindowExW(WS_EX_CLIENTEDGE, L"EDIT\0", convertNarrowToWide(text).c_str(),
                                 WS_CHILD | WS_VISIBLE | WS_TABSTOP | ES_PASSWORD,
                                 10, 10, 210, 40, dialog, (HMENU)101, GetModuleHandle(NULL), NULL);
    HWND okButton = CreateWindowExW(WS_EX_CLIENTEDGE, L"BUTTON\0", L"OK\0",
                                    WS_CHILD | WS_VISIBLE | WS_TABSTOP,
                                    10, 60, 60, 30, dialog, (HMENU)IDOK, GetModuleHandle(NULL), NULL);
    HWND cancelButton = CreateWindowExW(WS_EX_CLIENTEDGE, L"BUTTON\0", L"Cancel\0",
                                        WS_CHILD | WS_VISIBLE,
                                        80, 60, 60, 30, dialog, (HMENU)IDCANCEL, GetModuleHandle(NULL), NULL);
    SetFocus( hEdit );
    ShowWindow(dialog, SW_SHOWNORMAL);
    bool bFirstEmpty = true;
    while (true){
        if (!PeekMessageW( &Msg, 0, 0, 0, PM_REMOVE )){
            if (bFirstEmpty){
                // ShowWindow the first time the queue goes empty
                ShowWindow( dialog, SW_SHOWNORMAL );
                bFirstEmpty = FALSE;
            }
            if (!(GetWindowLongW( dialog, GWL_STYLE ) & DS_NOIDLEMSG)){
                // No message present -> send ENTERIDLE and wait
                SendMessageW( WindowFromDC(wglGetCurrentDC()), WM_ENTERIDLE, MSGF_DIALOGBOX, (LPARAM)dialog );
            }
            GetMessageW( &Msg, 0, 0, 0 );
        }
        if (Msg.message == WM_QUIT){
            PostQuitMessage( Msg.wParam );
            if (!IsWindow( dialog )){
                EnableWindow(WindowFromDC(wglGetCurrentDC()), TRUE);
                return text;
            }
            break;
        }
        if (!IsWindow( dialog )){
            EnableWindow(WindowFromDC(wglGetCurrentDC()), TRUE);
            return text;
        }
        TranslateMessage( &Msg );
        DispatchMessageW( &Msg );
        if((Msg.hwnd == okButton && Msg.message==WM_LBUTTONUP) || (Msg.message==WM_KEYUP && Msg.wParam==13)){
            break;
        }else if((Msg.hwnd == cancelButton && Msg.message==WM_LBUTTONUP) ||  (Msg.message==WM_KEYUP && Msg.wParam==27)){
            EnableWindow(WindowFromDC(wglGetCurrentDC()), TRUE);
            DestroyWindow(dialog);
            return text;
        }
        if (!IsWindow( dialog )){
            EnableWindow(WindowFromDC(wglGetCurrentDC()), TRUE);
            return text;
        }
        if (bFirstEmpty && Msg.message == WM_TIMER){
            ShowWindow( dialog, SW_SHOWNORMAL );
            bFirstEmpty = FALSE;
        }
    }

                wchar_t wstr[16384];

   GetDlgItemTextW( dialog, 101, wstr, 16384 );
    char mbstr2[16384];
    WideCharToMultiByte(CP_UTF8,0,wstr,16384,mbstr2,16384,NULL,NULL);

   text = mbstr2;

   DestroyWindow(dialog);
   EnableWindow(WindowFromDC(wglGetCurrentDC()), TRUE);

#endif
#ifdef TARGET_ANDROID
//code needed
#endif
 return text;
}

</code></pre>

If you guys agree with this approach, but don't have time, I can sit down and fix this for you and make a pull request or post code here for you to copy paste,

I don't see any negatives , only positives since it will fix the codeblocks part of the code, 

currently  if you use ofSystemTextboxDialog in codeBlocks and insert non english you get corrupted characters!.

Also no need to return widechar string in OF, you can return a normal string like in this example that is encoded UTF8 and thus print in OF using UTF8 encoding while non braking ascii since utf8 is ascii compatible!

So this way we have unified code that works in all languages.

**Comment by Teatoller** [comment]
Hi @igiso, @bakercp, @ofZach 
How did this initiative take off?
Was it successfully executed?

Is okay to still _keep this issue open_ **or** is it _time to close it_.?

Regards
Steven Ennis.

**Comment by igiso** [comment]
As I understand this was never solved properly to this day, but, since CODEBLOCKS is no longer used anymore we should close this

kind regards
