### ISSUE TITLE
API bug : ofFbo should have a clear()

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#3051]
following `clear()` the GPU memory should be freed and `isAllocated()` should then return `false`

**Comment by kylemcdonald** [comment]
@mattfelsen is tackling this one right now. his approach is like this:

1. rename `ofFbo::destroy()` to `ofFbo::clear()`
2. create a new `destroy()` that calls `clear()`
3. deprecate `destroy()` and replace instances
4. add `clearAlpha()`, `clearColorBuffers()`, `clearDepthBuffers()` (making a separate issue for this right now) this would cover theo's use case. the naming comes from a discussion with @ofzach and @mattfelsen.

**Comment by kylemcdonald** [comment]
closed by #3540 thanks again @mattfelsen
