### ISSUE TITLE
OSX Cursor Not visible after ofSetWindowShape

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3052]
So been experiencing this cursor bug after calling ofSetWindowShape where the cursor does not want to draw after leaving the window area and returning.

Screenshot after returning to screen after ofSetWindowShape
![bug-glfw](https://cloud.githubusercontent.com/assets/830748/3395463/7a576ccc-fcfe-11e3-8044-5da55c0f4451.png)

Expected (or what it looks like without ofSetWindowShape)
![bug-working](https://cloud.githubusercontent.com/assets/830748/3395440/01796f3a-fcfe-11e3-8229-83dbf92d14eb.png)

Problem occurs:
- After calling ofSetWindowShape()
- Only shows itself when you make the cursor move off the window and then return.
- Only occurs when new window shape/size is different to current

Test Environment:
- OSX Mavericks 10.9.3
- OF 0.8.2 RC2 && Master (most likely back to 0.8.1 as well)

Strange Notes:
- If cursor is returned to the window and you call ofSetWindowShape again the cursor returns!! (but if you go off screen again, bye bye cursor)
- Resets if you change to another open app and return to the oF window (resets somehow)
- Doesn't occur on Yosemite (10.10), not sure why not?!
- Occurs on Non-Retina window and Retina window.
- Yes ofShowCursor was set to true (tried calling it as well before/after/everyupdate to see if it would work; no dice)

Test Code:
- This shows a white circle where the cursor should be
- Press 'b' to trigger the bug
```
//--------------------------------------------------------------
void ofApp::update(){
//    ofShowCursor(); // for sanity check; don't need this but first thing I tried. Doesn't solve bug
}

//--------------------------------------------------------------
void ofApp::draw(){
    ofCircle(ofGetMouseX(), ofGetMouseY(), 10);
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
    if(key == ' ') {
        ofSetWindowPosition(ofGetWidth()-100, 0);
        ofSetWindowShape(ofGetWidth()-10, ofGetHeight()-10);
    } else if(key == 'b') { // This shows the bug
        ofSetWindowShape(ofGetWidth()-10, ofGetHeight()-10);
    } else if(key == 'u') { // This is okay
        ofSetWindowShape(ofGetWidth(), ofGetHeight());
    } else if(key == 'g') { // This is okay
        ofSetWindowPosition(ofGetWidth()-100, 0);
    }
}
```

Not sure what is causing internally. I had a look no idea's yet.

**Comment by kritzikratzi** [comment]
after downloading https://github.com/glfw/glfw/archive/master.zip
compile it with 

	cmake -DBUILD_SHARED_LIBS=false -DCMAKE_OSX_ARCHITECTURES=i386
	make
	cp src/libglfw3.a OF_PATH/lib/glfw/lib/osx/


if you are lazy download binary from http://asdfg.me/up/libglfw3.a for the lazy ones. 
but i'd compile it myself!

**Comment by timredfern** [comment]
works for me

**Comment by bilderbuchi** [comment]
thanks! @danoli3 can you still reproduce this?

**Comment by timredfern** [comment]
Actually I spoke too soon, I don't get the keyboard events with the new libglfw either. Will try to investigate in the next few days...

**Comment by kritzikratzi** [comment]
didn't copy the glfw include directory, the keyboard callback has changed! 

changes are need in: 
in ofAppGLFWWindow.h/.cpp: 

the callback keyboard_cb dropped the ```unsigned int codepoint``` parameter and becomes: 

	void ofAppGLFWWindow::keyboard_cb(GLFWwindow* windowP_, int keycode, int scancode, int action, int mods){
		...
			default:
				key = keycode;
		...
		if(action == GLFW_PRESS || action == GLFW_REPEAT){
			ofNotifyKeyPressed(key,keycode,scancode);
		}else if (action == GLFW_RELEASE){
			ofNotifyKeyReleased(key,keycode,scancode);
		}
	}

it seems the parameter that got removed was put into a new callback: 
https://github.com/glfw/glfw/blob/96b12ee504672824d98509b65bd46b3632416f8d/include/GLFW/glfw3.h#L789
typedef void (* GLFWcharfun)(GLFWwindow* window,unsigned int codepoint);

which should be implemented too i think.

**Comment by arturoc** [comment]
we use a patched version of glfw to be able to get unicode characters on the keyboard callback, that's why the offical branch won't work:

https://github.com/arturoc/glfw/tree/feature-keysUnicode

**Comment by timredfern** [comment]
the patched version of glfw doesn't build for me, does it need to be updated somehow?

Scanning dependencies of target glfw
[  2%] Building C object src/CMakeFiles/glfw.dir/clipboard.c.o
In file included from /work/workspace/glfw/src/clipboard.c:30:
In file included from /work/workspace/glfw/src/internal.h:57:
/work/workspace/glfw/src/../deps/GL/glext.h:6165:22: error: typedef redefinition with different types
      ('unsigned int' vs 'void *')
typedef unsigned int GLhandleARB;
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gltypes.h:28:18: note: 
      previous definition is here
typedef void    *GLhandleARB;
                 ^
1 error generated.
make[2]: *** [src/CMakeFiles/glfw.dir/clipboard.c.o] Error 1
make[1]: *** [src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

**Comment by timredfern** [comment]
trying to investigate this patched version, which does not build for me

I got the official build of glfw from https://github.com/glfw/glfw- builds fine on OSX

To try to see the differences with the patched version I rolled back to 3.0.2 (from the readme.MD description) however there still seem to be major differences.

Does anyone know what version of GLFW the patched version is based on?

Tim

**Comment by arturoc** [comment]
@igiso can you check this? it seems your merge with latest glfw broke every platform i thought it was only linux but it seems osx doesn't build either, which platforms did you tested your changes in?

**Comment by timredfern** [comment]
I've been trying to work out which commit of glfw the patched version came from, it seems to be somewhere between the 3.0.2 and 3.0.3 tags

However, the comments in the patched version are different from the ones in the glfw github repo

I would love to look at this and try to make it build, if someone could work out what exactly the starting point for the patched version was?

**Comment by timredfern** [comment]
actually, I was mistaken, when I switched to the feature-keysUnicode branch and used the right flags for cmake it did build for OSX. all good!

**Comment by ImanolGo** [comment]
Hi, 

I was able to compile the library of the patched version of glfw that arturoc suggested. However if I substitute the libglfw3.a library in OF 0.8.4,  I get massive linking errors. Anything else that I should take into account?

**Comment by ofTheo** [comment]
It should be named glfw3.a not libglfw3.a :)

**Comment by pizthewiz** [comment]
Are we still stripping the `lib` prefix from OS X static libs?

**Comment by ofTheo** [comment]
@pizthewiz - yes always because of a long standing bug with Xcode and it potentially linking to libs in /usr/local/lib instead of the ones supplied by OF.

**Comment by pizthewiz** [comment]
Probably external to this cursor issue but discussed in #2252 and #2882. I still wonder if it could have been a search path ordering issue and if not, possibly fixed in our minimum required Xcode version if it is that long standing :wink:.

**Comment by kylemcdonald** [comment]
i've seen this bug working with XCode without OF, but it could still be a path ordering issue...! after all cinder doesn't seem to care: https://github.com/cinder/Cinder/tree/master/lib/macosx

**Comment by ImanolGo** [comment]
I just realised that I needed to compile it for i386 architecture as @kritzikratzi suggested. 

cmake -DBUILD_SHARED_LIBS=false -DCMAKE_OSX_ARCHITECTURES=i386
make
cp src/libglfw3.a OF_PATH/lib/glfw/lib/osx/

Thanks for the tip, it worked perfectly!

**Comment by danoli3** [comment]
This is fixed.
