### ISSUE TITLE
Codeblocks Windows project generator crashes on addon selection 0.8.2

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3056]
PG runs, but then crashes when clicking the addons buttons (list of addons briefly seen, then crash).

**Comment by bilderbuchi** [comment]
does this bug still occur?

**Comment by sunekastbjerg** [comment]
I have not experienced it with my new laptop, which is running an AMD gpu. It might be a problem with Nvidia optimus, which is known for being pretty bad at changing from onboard to discrete graphics.
On 17-05-2015 15:57:10, Christoph Buchner <notifications@github.com> wrote:
does this bug still occur?

**Comment by bilderbuchi** [comment]
@pierrep do you still see this?

**Comment by pierrep** [comment]
I'll have a quick test...I normally don't have a Windows partition, but I've got another Windows installation laptop with me. My feeling is that it's fixed.

**Comment by pierrep** [comment]
Pretty sure the original bug was with Intel graphics, not Optimus, iirc.

**Comment by bilderbuchi** [comment]
OK, closing this, we can always reopen if someone else encounters it again.
