### ISSUE TITLE
ofxKinect compilation broken on Codeblocks MinGW

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3062]
I had to add changes some #defines in the code below in order to avoid a redefinition error. Seems like the MinGW constant has changed.

Old code:

```
// MinGW defines _SSIZE_T_DEFINED in sys/types.h when it defines ssize_t to be a long.
// Redefining it causes an error.
// MSVC does not define this.

#ifndef _SSIZE_T_DEFINED
#define _SSIZE_T_DEFINED
typedef long ssize_t;
#endif // _SSIZE_T_DEFINED

```

to this:

```
// MinGW defines _SSIZE_T_ in sys/types.h when it defines ssize_t to be a long.
// Redefining it causes an error.
// MSVC does not define this.


#ifndef _SSIZE_T_
#define _SSIZE_T_
typedef long ssize_t;
#endif // _SSIZE_T_
```

**Comment by armadillu** [comment]
I'm having this back on when compiling a VS2015 project with ofxKinect on 64Bit.

here: https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxKinect/libs/libfreenect/platform/windows/unistd.h#L36

changing to 
```
#ifdef _WIN64
typedef __int64 ssize_t;
#else
typedef long ssize_t;
#endif
```
allows me to compile in both 32 and 64 bit

**Comment by ofTheo** [comment]
Thanks for this fix!
Could you send a PR?
