### ISSUE TITLE
"cannot find -lstrmbase, cannot find -lz" on Windows

### ISSUE THREAD

**Issue by JobLeonard** [openframeworks/openFrameworks#3063]
Platform: Windows 8.1, Code::Blocks 13.12

All I did was download OF v0.8.2 and follow the instructions. [And yes, I did follow step (e)](http://www.openframeworks.cc/setup/codeblocks/#additions) (as suggested [here](https://github.com/openframeworks/openFrameworks/issues/2273)). Could it be something in the CB settings that cause it to not find the include/lib files even after doing so?

**Comment by wolfblood404** [comment]
I'm building the eyewriter1.0 and am having the same problem. I'm running windows 10. I had to downgrade from 64bit to 32 bit to run code blocks correctly. If they're isn't any solution can you give me some tips to run the code in VS express 2012? I need help urgently as possible.
