### ISSUE TITLE
ofDirectory - Path problem (Visual Studio 2012)

### ISSUE THREAD

**Issue by Wazhup** [openframeworks/openFrameworks#3068]
Hi there. 

I have this problem:

string a = "path/ãu"
 //what should i do here?
ofDirectory dir(a);
dir.listDir();

The problem is, everytime i have a path with accents, that is a folder or a file, ofDirectory cant load the information. I have read about it, and i have tried to change "string a" to "u16string a" but then ofDirectory, as normal, cant accept u16strings. 

So anyone here can help me? Thank you for your time.

Best regards.

**Comment by bakercp** [comment]
Closing this issue as it appears to be resolved and many changes have been updated with the addition of std::filesystem::path, etc in the core.  Please reopen if the issue persists.

**Comment by kritzikratzi** [comment]
i'm in the processing of upgrading to 0.11 after many years of using 0.9 with lots of tiny customizations (this being one of them). 

the problem absolutely still exists.

source of the problem: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofSystemUtils.cpp#L40-L49

    std::string convertWideToNarrow( const wchar_t *s, char dfault = '?',
                          const std::locale& loc = std::locale() )
    {
      std::ostringstream stm;
    
      while( *s != L'\0' ) {
        stm << std::use_facet< std::ctype<wchar_t> >( loc ).narrow( *s++, dfault );
      }
      return stm.str();
    }

this replaces special characters by a single '?' on my system. 

as a bugfix i have this in my old 0.9.3 installation: 

    #include <codecvt>
    static std::string convertWideToNarrow(const wchar_t* s, char dfault = '?',
    	const std::locale& loc = std::locale())
    {
        std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> converter;
        return converter.to_bytes(std::wstring(s));
    }


i'm not sure if this utf16->utf8 does the right thing under all circumstances, but the current situation is also not great. 

sorry for reoping such an old bug...
