### ISSUE TITLE
ofTrueTypeFont throws error when exiting application

### ISSUE THREAD

**Issue by K0j0** [openframeworks/openFrameworks#3091]
Just to preface I'm using eclipse on Linux  though I don't believe that should be the cause of the error. The issue is that if you close or otherwise exit a program that allocated fonts with ofTrueTypeFont then the ofTrueTypeFont destructor will throw an error. Specifially it's on line 393 in ofTrueTypeFont.cpp

if(face) FT_Done_Face(face);

Not really sure what the problem is, but it seems like face might have garbage in it. You can reproduce the error by running the fontsExample.

Again, the program runs fine but it doesn't seem right that it exits this way. Please let me know what you think. Thanks.

**Comment by cerupcat** [comment]
I'm seeing this on iOS now. Is this an issue again?
