### ISSUE TITLE
why can't we set "UdpSocketWin.cpp" the MAX_BUFFER_SIZE a bit bigger?

### ISSUE THREAD

**Issue by QiangJi** [openframeworks/openFrameworks#3106]
@ofTheo  at "404 const int MAX_BUFFER_SIZE = 4098;"

**Comment by micuat** [comment]
Hi @ofTheo,

>  add an option to increase the size with a function call.

Is it implemented? I'm using v20150910 nightly + VS2015 but the oscSend/Receive examples do not work unless `MAX_BUFFER_SIZE` is changed.
