### ISSUE TITLE
feature- getCocoaWindow() for GLUT - fix red Button in GLUT

### ISSUE THREAD

**Issue by igiso** [openframeworks/openFrameworks#3121]
in this branch:

https://github.com/igiso/openFrameworks/compare/feature-ofGetCocoaWindow()-for-GLUT#diff-a4fdfa0893d13a00650f8b21579b5fcdR303

I have added getCocoaWindow() for GLUT

so that ofGetCocoaWindow() can work with GLUT as well (now it just points to nothing)

additionally, to demonstrate the usefulness of this I added a fix for the missing redButton on the GLUT window.

we also need this, to implement mouseScrollbacks and ofGetMouseScroll() with  better code structure

let me know what you think

**Comment by admsyn** [comment]
Hey @igiso , did you delete that branch from your fork? The link doesn't work any more.

**Comment by igiso** [comment]
yeah,, it became unmeargable so I deleted it..
let me know if there is anything I can help anybody with..

**Comment by admsyn** [comment]
You can submit the `ofGetCocoaWindow()` tweak as a PR, but I *think* there's not too much interest in adding new features specifically for the GLUT window system (especially if it'll clutter up non-GLUT parts of the code base).

I'm going to close this, but if the change is fairly clean and minimal feel free to submit it as a PR. Thanks!

**Comment by igiso** [comment]
no worries,

:beer:
