### ISSUE TITLE
GL_VERSION_1_1 support was lost since v8.0

### ISSUE THREAD

**Issue by igiso** [openframeworks/openFrameworks#3125]
Hi friends,

so, Was this intentional? 

http://forum.openframeworks.cc/t/ofappglfwwindow-couldnt-create-glfw-window/13996/6

or is it a bug?

I think it would be nice if we could use OF regardless of openGL version. just like it was in 7.4 , 

higher openGl should be required only if the code needs it.

we shouldn't brake the entire framework for some extra texture functions

anyhow by

Using GLUT, I am able to compile with no problems 

I comment-out
//ofSetupGraphicDefaults();
//ofBackground(200);
//ofSetVerticalSync(true);
//ofEnableAlphaBlending();

from the ofGLReadyCallback() function inside

ofAppRunner.cpp

and I am able to run  OF 8.2 with graphics, transparencies blendings , threadings, render pdf send OSC network stuff, xmls, etc etc. not even sure what I am missing just by using Gl 1.1

but

With GLFW, things became more complicated, couldn't figure out if it was GLFW that created the problem or OF,

I think it must be openFrameworks,

 unfortunately I forgot to compile GLFW examples on that machine :( 
and I wont be able to try again until next month,

is there a trick to use openGl 1.1 by choice on a pc/laptop that has a higher version so I can debug this more easily??

maybe smthng like:
# undef GL_VERSION_1_2
# undef GL_VERSION_1_3
# undef GL_VERSION_1_4
# undef GL_VERSION_1_5
# undef GL_VERSION_2_0
# undef GL_VERSION_2_1
# undef GL_VERSION_3_0
# undef GL_VERSION_3_1
# undef GL_VERSION_3_2
# undef GL_VERSION_3_3
# undef GL_VERSION_4_0
# undef GL_VERSION_4_1

??

**Comment by dartecne** [comment]
> btw which card do you have in that computer? it must be something really old to not support at least openGL 2.1. i would also check if there's more recent drivers available but in general i think a card that only supports openGL 1.1 (as @tgfrerer said, a standard that is almost 20 years old) is just not usable with a nowadays openGL framework.
> 
> if you want to use such an old hardware then you can do it through an older version of OF.
> 
> also this is an open source project, most of us don't even have the hardware to test this so if you find a way to keep compatibility, even if it's only through GLUT, a PR is always welcome but please stop complaining in every channel about this or making misleading statements like in this thread in the forum: http://forum.openframeworks.cc/t/sup-with-all-of-the-linking-and-project-organization-issues-with-of/16623/5

And is it possible to see which version of OF corresponds to OpenGL version? I want to use OF that supports OpenGL v.1.4
Thanks a lot

**Comment by arturoc** [comment]
0.8 is the version that introduced glfw which broke compatibility with older versions. anything older than that will probably work with older opengl versions if your drivers do at all

**Comment by dartecne** [comment]
Thank you very much arturoc for your response.
Finally I discovered the setGLVersion method of ofGLWindowsSettings class, and that worked like a charm for my old graphic card that only supports to 1.4 openGL version.

https://openframeworks.cc/documentation/application/ofGLWindowSettings/#show_setGLVersion
