### ISSUE TITLE
iOS 8 breaks OF handling of Hardware Orientation

### ISSUE THREAD

**Issue by aefreedman** [openframeworks/openFrameworks#3158]
I haven't fully investigated the root cause, but the problem is related to iOS 8 changes to how it controls view bounding boxes. It seems that they do not change after rotation.

I'm cross-referencing issues #931, #1477, and #1976, though I'm making a new issue because my understanding that this is a iOS 8 specific issue, though related.

Edit: Also cross-referencing PR #2290. Also linking related forum [thread](http://forum.openframeworks.cc/t/ios-8-of-not-setting-orientation-properly/16729).

Observed behavior: using current versions if iOS + OF, the app will appear to always start in Portrait, despite setting the project to start in Landscape and disabling all Portrait orientations. You'll typically see a blank region on the right-hand side of your screen. It seems that your app is drawing Landscape while the device is oriented Portrait.

~~Disabling hardware orientation will allow you to draw the app correctly, but the device will always orient as Portrait. Additionally, activating the Notification or Control Center can cause the app to suddenly change orientation.~~ 

Update (10/13):
I'm currently using 
Xcode 6
OS X 10.10 Beta 5
Latest OF Master as of 10/13
iPhone 6 w/ iOS 8.0.2

~~Project details:
Xcode 6 beta 6
OS X 10.10 (14A299l)
OF 0.8.3 (I've looked through the current master and nothing looks like it applies)
Tested on: iPhone 5s (7.1.2), iPad Air (7.1.2), iPad 2 (8.0 (12A4345d))~~

Potential Fix:
the ofxiOSViewController is switching the width and height values based on orientation to get the correct center and bounding box. This is apparently unnecessary in iOS 8.

The following changes to ofxiOSViewController.mm will keep orientation working on iOS 8 without breaking previous versions. This change causes some unwanted behavior from the orientation animation that I haven't looked into yet (it seems to rotate around twice).

In rotateToInterfaceDirection the following (148-163):

    CGSize screenSize = [UIScreen mainScreen].bounds.size;
    
    CGPoint center;
    if(UIInterfaceOrientationIsLandscape(self.interfaceOrientation)) {
        center.x = screenSize.height * 0.5;
        center.y = screenSize.width * 0.5;
    } else {
        center.x = screenSize.width * 0.5;
        center.y = screenSize.height * 0.5;
    }
    
    CGRect bounds = CGRectMake(0, 0, screenSize.width, screenSize.height);
    if(UIInterfaceOrientationIsLandscape(interfaceOrientation)) {
        bounds.size.width = screenSize.height;
        bounds.size.height = screenSize.width;
    }

should be:

    CGSize screenSize = [UIScreen mainScreen].bounds.size;
    CGPoint center;
    CGRect bounds = CGRectMake(0, 0, screenSize.width, screenSize.height);
    
    // Is the iOS version less than 8?
    if( [[[UIDevice currentDevice] systemVersion] compare:@"8.0" options:NSNumericSearch] == NSOrderedAscending ) {
        if(UIInterfaceOrientationIsLandscape(self.interfaceOrientation)) {
            center.x = screenSize.height * 0.5;
            center.y = screenSize.width * 0.5;
        } else {
            center.x = screenSize.width * 0.5;
            center.y = screenSize.height * 0.5;
        }

        if(UIInterfaceOrientationIsLandscape(interfaceOrientation)) {
            bounds.size.width = screenSize.height;
            bounds.size.height = screenSize.width;
        }
    } else {
        center.x = screenSize.width * 0.5;
        center.y = screenSize.height * 0.5;
    }

additionally in willAnimateRotationToInterfaceOrientation, lines 224-233:

    CGSize screenSize = [UIScreen mainScreen].bounds.size;
    
    CGPoint center;
    if(UIInterfaceOrientationIsLandscape(toInterfaceOrientation)) {
        center.x = screenSize.height * 0.5;
        center.y = screenSize.width * 0.5;
    } else {
        center.x = screenSize.width * 0.5;
        center.y = screenSize.height * 0.5;
    }

should instead be:

    CGSize screenSize = [UIScreen mainScreen].bounds.size;
    
    CGPoint center;
    // Is the iOS version less than 8?
    if( [[[UIDevice currentDevice] systemVersion] compare:@"8.0" options:NSNumericSearch] == NSOrderedAscending ) {
        if(UIInterfaceOrientationIsLandscape(self.interfaceOrientation)) {
            center.x = screenSize.height * 0.5;
            center.y = screenSize.width * 0.5;
        } else {
            center.x = screenSize.width * 0.5;
            center.y = screenSize.height * 0.5;
        }
    } else {
        center.x = screenSize.width * 0.5;
        center.y = screenSize.height * 0.5;
    }

**Comment by bilderbuchi** [comment]
is this issue still relevant/occurring?

**Comment by susemiessner** [comment]
if I see correctly this issue still exists... at least I just checked the iOSOrientationExample on a couple of different devices and the issue still persists. the solution of @aefreedman doesn't seem implemented in current build (0.8.4). could someone tell me where to find ofxiOSViewController in OF folder structure? Would like to try the code suggested

**Comment by bilderbuchi** [comment]
pinging @openframeworks/ios

**Comment by kylemcdonald** [comment]
@susemiessner thanks for the info :) since this issue is still open, it means there is still interest in fixing it!

just to double check -- are you testing with the nightly build of openFrameworks? here is the most recent one: http://192.237.185.151/versions/nightly/of_v20150518_ios_nightly.zip

**Comment by danoli3** [comment]
@julapy I'll jump on this one, think I've worked it all out from landscape issue
