### ISSUE TITLE
OSX minimized app causes 100% CPU Usage

### ISSUE THREAD

**Issue by danzeeeman** [openframeworks/openFrameworks#3181]
When the App is actively drawing on the screen:
![screen shot 2014-08-28 at 3 00 15 pm](https://cloud.githubusercontent.com/assets/719564/4081226/bd73bd08-2ee5-11e4-8b2f-42d0717b2b14.png)

Then minimize the app:
![screen shot 2014-08-28 at 3 00 04 pm](https://cloud.githubusercontent.com/assets/719564/4081228/bd7a244a-2ee5-11e4-9504-ecacc541fedb.png)

CPU goes to 100%:
![screen shot 2014-08-28 at 2 59 57 pm](https://cloud.githubusercontent.com/assets/719564/4081227/bd78e0c6-2ee5-11e4-874e-9f5ece7549c3.png)

Anyone have an idea?  @laserpiloit just showed me this weird bug in 0.8.3?  I'm running off master.

**Comment by bilderbuchi** [comment]
#3979 has some additional discussion. the reason seems to be that, with no vsync, it just renders as fast as possible, leading to very high framerates and 100% CPU. One possible fix would be to
>  add a frame rate cap on loosing focus (for a window that has vsync and no frame rate set) and drop the frame rate cap when it's in focus.

**Comment by dimitre** [comment]
It seems this plist entry can disable app nap
```xml
 <key>LSAppNapIsDisabled</key>
    <string>True</string>
```
and here we have a class that can disable or enable app nap
https://github.com/bitcoin/bitcoin/blob/master/src/qt/macos_appnap.h
https://github.com/bitcoin/bitcoin/blob/master/src/qt/macos_appnap.mm

**Comment by dimitre** [comment]
Hey @ofTheo I've recently tested to see if the plist item fixes the issue. In my system I can't reproduce the issue anymore. Not sure if Apple changed anything, I'm using now macOs 11.6.4 now.
It would be great to investigate more if the issue still exists or if depends on the system.

**Comment by ofTheo** [comment]
@dimitre thanks for checking! I think its fixed too. Must be the newer GLFW we used in 0.11.0 
Just tried it on my macOS 10.14.6 ( _I know_ 😬 ) and FPS stayed solid when minimized or the window was hidden. 

So going to close - nice not to have another issue to fix!
