### ISSUE TITLE
ofxOscParameterSync examples not working in windows with version 0.8.3

### ISSUE THREAD

**Issue by antoniomechas** [openframeworks/openFrameworks#3185]
Hello,

I have an app that uses ofxOscParameterSync to sync my gui between 2 applications.
It was working fine until version 0.8.3, then I decided to check the basics with the included examples: oscParametersSender and oscParametersReceiver... and found out they don't work.
If I compile them with previous version 0.8.0, they work fine.
I'll try to get deeper into finding why it is not working.
I'm on Windows 7 with OF 0.8.3
Antonio.

**Comment by genekogan** [comment]
not working on OSX as well. 
i think the problem is in ofParameterGroup. the notifier method `ofParameterGroup::notifyParameterChanged(ofAbstractParameter & param)` is there but is never triggered, so ofxOscParameterSync never registers a change in the group.

**Comment by wasawi** [comment]
Any news on this? is it still to be fixed?

**Comment by arturoc** [comment]
i just checked this on 0.9 and it's working fine. should work with either master or the nightly builds.  what version are you using?

**Comment by wasawi** [comment]
Yep i was in 8.3 
thanks Arturo!
