### ISSUE TITLE
oF install dependencies 1.0-omx install problem

### ISSUE THREAD

**Issue by elid** [openframeworks/openFrameworks#3188]
Hi there,
I'm a newbie trying to install openframeworks on Raspberry (on Noobs - Raspbian dist).
I have problems installing 1.0-omx  package here s what it says:

The following packages have unmet dependencies:
gstreamer1.0-omx-dbg depends gstreamer1.0-omx (=1.0.0.1-0+rpi12rpi1) but 1.2.0-1 is to be installed

what should I do?
Thanks for your help

**Comment by hectorMiranda** [comment]
Excellent!, this fix my issue as well, thank you!

**Comment by ungerik** [comment]
How can I fix that when I install via apt-get install gstreamer1.0 and get this error?

**Comment by liaoweiduo** [comment]
I have the same problem while installing via apt-get. 
( gstreamer1.0-omx-dbg : Depends: gstreamer1.0-omx (= 1.0.0.1-0+rpi13rpi1) but 1.2.0-1 is to be installed). 
(sudo apt-cache policy gstreamer1.0-omx
gstreamer1.0-omx:
  Installed: 1.2.0-1
  Candidate: 1.2.0-1
  Version table:
 *** 1.2.0-1 0
        500 http://vontaene.de/raspbian-updates/ ./main armhf Packages
        100 /var/lib/dpkg/status
     1.0.0.1-0+rpi13rpi1 0
        500 http://archive.raspberrypi.org/debian/ wheezy/main armhf Packages)
But I only get a file called Packages without suffix from this website. I don't know how to use it? How to build it? Thanks a lot.
