### ISSUE TITLE
Why can't return the correct names which the function of ofxAssimpModelLoader::getMeshNames()?

### ISSUE THREAD

**Issue by QiangJi** [openframeworks/openFrameworks#3192]
If can't get the name of mesh, cannot very good control objects in the scene.

I had put the problem feedback to "Assimp github", link as below:
https://github.com/assimp/assimp/issues/360

I hope you con alse follow to update the ofxAssimpModelLoader.

It will be a very good thing, thank you very much!

**Comment by NickHardeman** [comment]
Node names, including meshes, now exposed in ofxAssimp add-on. Closed by #7776
