### ISSUE TITLE
Add documentation about ofRandom*()'s behavior in multi-threaded environments

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3198]
In response to https://github.com/openframeworks/openFrameworks/issues/3191 we should update the documentation to reflect the behavior of the internal `rand()` function in multi-threaded situations.  The documentation should suggest using third party solutions such as [Poco::Random](http://pocoproject.org/docs/Poco.Random.html) or upcoming c++11 random number generators in these situations.

**Comment by artificiel** [comment]
this can be closed as the random generator has been upgraded to an std::mersenne_twister_engine instance wrapped with std::shared_mutex according to the double-checked locking pattern. compiled in release, the performance of std::uniform_real_distribution is better than rand(), despite the mutex action.

the engine is initialized to a non-deterministic seed, which can be set to a specific seed (which will then produce the same results on all platforms). the single-instance design is in spirit of seeded generative works so a multithreaded deterministically seeded work is conceptually possible (of course it's dependent on how the threads are synchronized). 

templated wrappers have been made around the various std distributions (including boilerplate to handle glm) as well as some other functionalities.

you may check the action here http://varia.artificiel.org/of/RandomExplorer/ (also in devApps) — (NB chrome currently has the edge in performance, about 40% of native on Apple Silicon)

relevant code: [ofRandomEngine](https://github.com/openframeworks/openFrameworks/blob/eccd798d545ec2a6c83e82ecbfe301ba0de7653a/libs/openFrameworks/utils/ofRandomEngine.h), [orRandomDistributions](https://github.com/openframeworks/openFrameworks/blob/eccd798d545ec2a6c83e82ecbfe301ba0de7653a/libs/openFrameworks/utils/ofRandomDistributions.h), [ofSingleton](https://github.com/openframeworks/openFrameworks/blob/eccd798d545ec2a6c83e82ecbfe301ba0de7653a/libs/openFrameworks/utils/ofSingleton.h)
