### ISSUE TITLE
ofGstVideoPlayer crash when running on Odroid

### ISSUE THREAD

**Issue by mysteryDate** [openframeworks/openFrameworks#3219]
On an Odroid U3 running Ubuntu 14.04, videoPlayerExample compiles with no errors, but produces the following when attempting to run:
```
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 glesv1_cm glesv2 egl 
[ error ] ofGstVideoPlayer: allocate(): cannot get pipeline caps
Segmentation fault
make: *** [run] Error 139
```

I have looked at issues [2957] (https://github.com/openframeworks/openFrameworks/issues/2957) and [2582] (https://github.com/openframeworks/openFrameworks/issues/2582) which report similar problems with windows machines, but since I'm not on a windows machine, the fixes there won't work.

**Comment by tpltnt** [comment]
@mysteryDate is this still an issue/does this bug still exist? (I don't have an Odroid, so I can't replicate the bug, but would try to look into it.)

**Comment by mysteryDate** [comment]
Hey, I got rid of my odroid a while ago. Honestly I couldn't get very much at all to work on it. Sorry for the late response.
