### ISSUE TITLE
Multiple ofParameterGroups referring to the same ofParameter

### ISSUE THREAD

**Issue by bleppie** [openframeworks/openFrameworks#3263]
Multiple ofParameterGroups can refer to the same ofParameter, but each ofParameter has only a single parent. So when an ofParameter changes, it notifies only the last group to which it was added. In the following example, when parameterGeneralGui changes, it will notify generalParameters, but not allParameters:
```c++
ofParameter<float> paramGeneralGui;
ofParameter<float> paramCalibration;
ofParameterGroup allParameters;
ofParameterGroup generalParameters;

allParameters.add(paramGeneralGui)
allParameters.add(paramCalibration)
generalParameters.add(paramGeneralGui);
```
This has tripped me up a few times, and I wonder if it would be better to lose the notion of an ofParameter's parent, and rather have an ofParameterGroup add itself as a listener to the ofParameters it contains. So, in ofParameterGroup::add(...) we would change
```c++
p->setParent(this);
```
to this
```c++
p->addListener(this, &ofParameterGroup::notifyParameterChanged);
```
The problem, however, is that ofParameter::addListener doesn't exist on ofAbstractParameter. The event (changedE) is specialized to the ParameterType (float, int, ofVec2f, etc.). This means we can't add a listener in ofParameterGroup::add(ofAbstractParameter&).

The solution, I think, would be for event to be specialized to ofAbstractParameter rather than the underlying ParmeterType. Instead of
```c++
ofEvent<ParameterType> changedE;
```
It would be
```c++
ofEvent<ofAbstractParameter> changedE;
```
With delegates, we should be able to hide this from users so the functionality remains the same. In fact, it would add some nice functionality where listener methods could take either an ofAbstractParameter or the underlying ParameterType as an argument. Thus a single method could be used as a listener for multiple ofParameters, regardless of underlying ParameterType.

**Comment by arturoc** [comment]
closed via 5b2971a9b2e1cdec715c2338f0a7bddf22bb3188
