### ISSUE TITLE
projectGenerator in the package of 'of_v0.8.4_vs_release' crashes 

### ISSUE THREAD

**Issue by ZeroLu** [openframeworks/openFrameworks#3272]
Here is part of the log:
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp
[ error ] ofTrueTypeFont: getStringBoundingBox(): font not allocated
[ error ] ofTrueTypeFont: drawString(): font not allocated: line 1082 in ..\..\.
.\openFrameworks\graphics\ofTrueTypeFont.cpp

My computer is win7 64bit.

**Comment by manish-juneja** [comment]
@ofZach  @AlexBatuev is using visual studio 2013 is it supported ?

**Comment by LeoColomb** [comment]
@manish-juneja See #2571 
@bilderbuchi I think this issues can be closed as duplicate of #1743

**Comment by bilderbuchi** [comment]
Thank you. Closing as duplicate.
