### ISSUE TITLE
ofAVFMovieRenderer linker errors

### ISSUE THREAD

**Issue by aspeteRakete** [openframeworks/openFrameworks#3290]
Hi there,
whenever the ofAVFMovieRenderer is involved in a project, i get linker errors:
> Undefined symbols for architecture i386:
  ".objc_class_name_AVPlayer", referenced from:
      pointer-to-literal-objc-class-name in libopenFrameworks.a(ofAVFMovieRenderer.o)
  ".objc_class_name_AVPlayerItem", referenced from:
      pointer-to-literal-objc-class-name in libopenFrameworks.a(ofAVFMovieRenderer.o)
  ".objc_class_name_AVPlayerItemVideoOutput", referenced from:
      pointer-to-literal-objc-class-name in libopenFrameworks.a(ofAVFMovieRenderer.o)
  ".objc_class_name_AVURLAsset", referenced from:
      pointer-to-literal-objc-class-name in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_AVMediaTypeVideo", referenced from:
      ___28-[AVFMovieRenderer loadURL:]_block_invoke_2 in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_AVPlayerItemDidPlayToEndTimeNotification", referenced from:
      ___28-[AVFMovieRenderer loadURL:]_block_invoke_2 in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_CACurrentMediaTime", referenced from:
      -[AVFMovieRenderer update] in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_CMTimeGetSeconds", referenced from:
      -[AVFMovieRenderer duration] in libopenFrameworks.a(ofAVFMovieRenderer.o)
      -[AVFMovieRenderer currentTime] in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_CMTimeMakeWithSeconds", referenced from:
      -[AVFMovieRenderer setCurrentTime:] in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_CMTimeMaximum", referenced from:
      -[AVFMovieRenderer setCurrentTime:] in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_CMTimeMinimum", referenced from:
      -[AVFMovieRenderer setCurrentTime:] in libopenFrameworks.a(ofAVFMovieRenderer.o)
  "_kCMTimeZero", referenced from:
      ___28-[AVFMovieRenderer loadURL:]_block_invoke_2 in libopenFrameworks.a(ofAVFMovieRenderer.o)
      -[AVFMovieRenderer stop] in libopenFrameworks.a(ofAVFMovieRenderer.o)
      -[AVFMovieRenderer setCurrentTime:] in libopenFrameworks.a(ofAVFMovieRenderer.o)
ld: symbol(s) not found for architecture i386

Seems there are no 32 bit symbols. This is done on OSX 10.9.5 with Xcode 6 installed, with OF current master.
Calling make from cmdline.
Is this an OF issue or am I doing something wrong?

**Comment by pizthewiz** [comment]
Is this safe to close?

In what ever our project migration guide is, we'd need to mention that existing projects would need to add:
* AVFoundation.framework
* CoreMedia.framework
* QuartzCore.framework

@admsyn can these be hoisted into an `xcconfig` file that is part of the repo, that way we can update it with future releases and user projects would automatically pull in the changes? Maybe that is how it works already ¯\_(ツ)_/¯?

**Comment by admsyn** [comment]
Yes it looks like adding the build settings to CoreOF.xcconfig (as "-framework CoreMedia ...") would be a decent way of handling this. If Project.xcconfig is also modified to append the frameworks to OTHER_LDFLAGS it should go a long way to keeping the framework setup between apps and OF itself in sync.

Also, having the list of required frameworks available in a text file is much nicer than buried in multiple xcode projects IMO :)
