### ISSUE TITLE
Make pulseaudio optional?

### ISSUE THREAD

**Issue by jedahan** [openframeworks/openFrameworks#3314]
oF supports PulseAudio as a possible [backend for RtAudio](https://github.com/openframeworks/openFrameworks/blob/master/libs/rtAudio/include/RtAudio.h#L964-L992). Is it possible to make PulseAudio optional in the build scripts for linux? Could we require just one possible backend in [config.linux.common.mk#283](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk#L283)?

Paging @arturoc , who last modified that line in bc2292a0.

**Comment by bernardoaraujor** [comment]
I'm trying to route openFrameworks + Spotify through jack and its been a real nightmare, because jack and pulseaudio don't seem to like eachother.
