### ISSUE TITLE
Make file timestamp's accessible 

### ISSUE THREAD

**Issue by greengiant83** [openframeworks/openFrameworks#3324]
There should be a way to get a file's modified timestamp

**Comment by kylemcdonald** [comment]
with c++11 this is now possible via: `std::filesystem::last_write_time(file)` where file is an `ofFile` or `ofDirectory`. hard to say where, or if, this belongs in OF itself. also see #1120

**Comment by bakercp** [comment]
This is now possible with the integrated std::filesystem::last_write_time call.  Closing this issue.
