### ISSUE TITLE
ofxNetwork not compiling: current master branch

### ISSUE THREAD

**Issue by BananasGoMoo** [openframeworks/openFrameworks#3365]
Hello,

I downloaded the current master build (October 26, 2014 @ 2:45PM Pacific Time), because I was testing a new feature, but when I tried to compile with the ofxNetwork addon included, it would not compile (even using the project generator to create the project). The error given was that EALREADY, ENOPROTOOPT, EPROTONOSUPPORT were not defined inside ofxNetworkCheckErrno and ECONNRESET, ECONNABORTED were not defined inside of ofxTCPClient::receive.

not sure if this is because that addon is being modified, but I thought I'd bring it up, just in case.

BTW, I am using Code::Blocks with MinGW on Windows 7 to compile.

**Comment by bilderbuchi** [comment]
@BananasGoMoo can you still reproduce this on current master?

**Comment by BananasGoMoo** [comment]
Hello,

downloaded the current master and I cannot compile the oF library now (openFrameworksLib) because it gives me this error: "error: 'closeQuicktime' was not declared in this scope". It's inside an if statement checking whether I have a quicktime player, which I don't, but it activates anyways? not sure what's going on.

**Comment by bilderbuchi** [comment]
did you clean the all projects before compiling the new version? could be some stuff compiled with the previous version was left over.

**Comment by BananasGoMoo** [comment]
Hello,

Yes, I started with GCC 5.1.0, and that didn't work so I cleaned and rebuilt with GCC 4.8.1 and that didn't work either.

**Comment by bilderbuchi** [comment]
hmm, @openframeworks/windows @arturoc can you help out here?

**Comment by arturoc** [comment]
this is fixed by https://github.com/openframeworks/openFrameworks/pull/4208
