### ISSUE TITLE
ofScale API

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3366]
currently we have,
`void ofScale(float xAmnt, float yAmnt, float zAmnt = 1);`

but we don't have,
`void ofScale(const ofPoint & p)`

think it would be good to add it in.
and `ofTranslate` has both versions of the method signature so it will keep it consistent.

**Comment by DomAmato** [comment]
Couldn't we just make it a function overload so that it would look something like this:

    void ofScale(const ofPoint & p) { ofScale(p.x, p.y, p.z); }

**Comment by bakercp** [comment]
PR it :)

**Comment by DomAmato** [comment]
this can be closed since its been merged
