### ISSUE TITLE
project generator stops opening

### ISSUE THREAD

**Issue by lucymbonner** [openframeworks/openFrameworks#3370]
Does anyone know why the project generator stops working [even the next day] after downloading, and then re-downloading the oF package? It works when I first try it after downloading, then gives me a "cannot be opened -10810" error every time following.

**Comment by ofZach** [comment]
is this sill an issue? this seems very specific to your OSX install and the issue (http://www.thexlab.com/faqs/error-10810.html) seems not really OF related.  I'm going to close this for now but happy to re-open...

**Comment by lucymbonner** [comment]
It is, unfortunately. I am sorry I never replied! It must have gotten lost
in the midterm shuffle. I started using OFPlay, though. Thank you!

Lucy

**Comment by ofZach** [comment]
ok I am going to keep this closed, the specific error seems related to your machine as far as I can tell from researching "-10810" errors...    If you can, please try another machine and also, you might try making sure you don't have anything open and / or looking at if there's something you've installed that might be interfering.  Also, make sure your security permissions allow you to open the project generator.  thanks!
