### ISSUE TITLE
The addon of ofxOsc doesn't compile on the win7 VS2012. 

### ISSUE THREAD

**Issue by QiangJi** [openframeworks/openFrameworks#3378]
“netdb.h”: No such file or directory.
“pthread.h”: No such file or directory.

**Comment by ofTheo** [comment]
@QiangJi - could you see if you still have this issue with the current 0.9.0 release ( http://openframeworks.cc/download/ ) ? 

I tested the osc example on Windows before we did the 0.9.0 release so the issue should be closed now.

**Comment by javl** [comment]
To get back to this old issue: I'm getting the same error, using OF 0.9.3 and Visual Studio 2015, but only when I use the Visual Studio plugin to create a project using New -> project -> Openframeworks
After selecting to include ofxOsc and building the empty project, I get the same `Cannot open include file: 'netdb.h': No such file or directory` error.
But when I use the project generator to create my new project and open it in Visual studio, it builds without any problems.
Tested using current versions of OF and VS

**Comment by elburz** [comment]
@arturoc is the below still true? adding the project even by right clicking on solution and going to openFrameworks addons and checking off ofxOsc gives me the same issue as above. 

> adding the addon manually to the project won't work

**Comment by elburz** [comment]
just to add to above, i went through all the project properties and seemed like the osc receiver example has a Debugging working directory of $(ProjectDir)/bin whereas the projected I generated previously (that originally didn't have ofxOsc but was then added after) had a working directory of \bin. Not sure what that means but maybe useful information

**Comment by 5shekel** [comment]
i can confirm @javl findings. 
using the VS new project doesn't play nice with ofOSC. the project generator does.

**Comment by watershade** [comment]
of_v0.9.8_vs_release still cannot add ofxOSC by vs mode. But it is do useful by projectGenerator. So anyone know what is the reason for it. 
Just because of include the wrong files?

**Comment by kaminaly** [comment]
I had the same problem. but I found the difference between the project generator's one and VS2015 plugin's one.

plugin's one's `projectname.vcxproj.filters` includes `posix` path.
But the project generator's one doesn't.

As a test, I removed the path and built. then It worked!
