### ISSUE TITLE
ofAppNoWindow key events

### ISSUE THREAD

**Issue by igiso** [openframeworks/openFrameworks#3406]
(currently not working)
maybe I am missing something but I think
we should just use

   ofNotifyKeyPressed(getchar());

(inside runAppViaInfiniteLoop)

instead of GetAsyncKeyState .. or .. getch(), kbhit() etc..

**Comment by bilderbuchi** [comment]
is this still occuring in current master?

**Comment by bilderbuchi** [comment]
closing as there's no follow-up by the reporter.
