### ISSUE TITLE
static ofImageType  ofImageTypeFromPixelFormat() bug!

### ISSUE THREAD

**Issue by yty** [openframeworks/openFrameworks#3407]
Should add more support..

For example:
```
	case OF_PIXELS_BGR:
		return OF_IMAGE_COLOR;
	case OF_PIXELS_BGRA:
		return OF_IMAGE_COLOR_ALPHA;
```

Otherwise, use swapRGB() the error..
```
ofLog(OF_LOG_ERROR,"ofPixels: image type not supported");
```

**Comment by kylemcdonald** [comment]
i re-added the two relevant lines by hand.

i noticed @yty also commented out the pixel swapping part of `swapRgb()`, i think the suggestion is that with the way pixel formats work now, maybe we don't need to swap actual memory anymore. but i left it as it is instead of commenting it out :)
