### ISSUE TITLE
Support Android Studio

### ISSUE THREAD

**Issue by nneonneo** [openframeworks/openFrameworks#3408]
Currently, the projects only work with Eclipse. Android Studio looks like it is going to become Google's preferred IDE for Android code, so we should think about getting support for Android Studio for openFrameworks.

I have successfully created a set of Android Studio project files, and instructions for using them, over at https://github.com/nneonneo/openFrameworks-AndroidStudio. The build files basically just call out to the openFrameworks makefiles at strategic points. I have successfully built and deployed openFrameworks apps using Android Studio using this approach

Let's talk about how this could be integrated...

**Comment by bilderbuchi** [comment]
closed by #3422
