### ISSUE TITLE
project generator ADDON_CFLAGS only sets C++ Flags in Xcode

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#3430]
ADDON_CFLAGS in addon_config.mk actually sets the *Other C++ Flags* in Xcode. This is fine for C++ libs but does't work when compiling C libs.

For instance, ofxPd uses libpd which is a C library and requires a couple of defines to be set to build correctly. Those flags have to be set in *Other C Flags* to work in Xcode but they are only set in *Other C++ Flags*, so generated projects do not work.

The real fix would require two variables: ADDON_CFLAGS and ADDON_CPPFLAGS. Naturally, all add ons would need to be updated to use the new ADDON_CPPFLAGS variable, so this may not be the easiest solution.

**Comment by danomatika** [comment]
Any interest in this? Still a showstopper for ofxPd.

The easiest solution would be to introduce a new variable for the CFlags like ADDON_C_CFLAGS or ADDON_LOW_CFLAGS or some variant.

**Comment by bakercp** [comment]
Definitely interested, just not enough bandwidth at the moment ...

**Comment by danomatika** [comment]
Ok, have this working in the PG: https://github.com/ofZach/projectGeneratorSimple/pull/62

**Comment by danomatika** [comment]
FIx for this is in: https://github.com/openframeworks/openFrameworks/pull/3573

**Comment by danomatika** [comment]
This is basically done with my core PR and the PG PR.

**Comment by bilderbuchi** [comment]
thanks Dan, closing, then.
