### ISSUE TITLE
none of the core functions report how many dimensions they work for

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#347]
some of the core functions only work with 2d points, others only with 3d points, some work with both. but they all take ofPoints.

it's good for teaching purposes to have ofPoints because you don't have to explain what a 'vector' is, but it's unclear for advanced users whether the functions take 2d or 3d points...

**Comment by bakercp** [comment]
Very little of the core uses ofPoint now, but rather glm::vec2/glm::vec3.  Closing this.
