### ISSUE TITLE
matrix and vector math overhaul

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3477]
this issue is meant to capture a few development directions:
- `ofVec2f::average` has a strange behavior (#976)
- `ofMatrix3x3` is significantly different from `ofMatrix4x4` (#1403)
- `ofMatrix3x3` is missing many features
- libraries like [glm](http://glm.g-truc.net/) already provide great libraries for matrix and vector math, and we shouldn't be re-implementing these things

however, there are some inconsistencies between glm and OF-style operations, making a direct migration difficult.

let's discuss how we can fix our `ofMatrix3x3` problem and start on a better path towards consistency with OF's vector and matrix code.

**Comment by bakercp** [comment]
Closing this now that glm has been integrated.
