### ISSUE TITLE
ofxNetwork: improper error handling in TCPClient

### ISSUE THREAD

**Issue by philippelaulheret** [openframeworks/openFrameworks#3478]
The function ofxTCPClient::receiveRaw() is doing some crazy stuff : 

if (messageSize == TCP_MAX_MSG_SIZE) the string won't be null-terminated (while the buffer is allocated with one extra byte to handle this situation). 

if an error is returned, (messageSize == -1) a null-byte is written outside of the bounds of the array. 
A normal use case where this happen : on windows, calling the recieveRaw function when nothing was sent will trigger a WSAEWOULDBLOCK error

**Comment by arturoc** [comment]
this seems to be fixed with the recent changes,
