### ISSUE TITLE
ofVideoPlayer does not allocate texture under a custom shader on the master branch

### ISSUE THREAD

**Issue by youandhubris** [openframeworks/openFrameworks#3482]
When I try to pass a texture from ofVideoPlayer as a uniform, I get the following error:

**[ error ] ofTexture: getTextureData(): texture has not been allocated**

I also set **setUseTexture** to true, to make sure. I tried with openGL 4.1 and 2.1.
With ofVideoGrabber everything works fine. I'm using the current master branch, Mac OS 10.10.1, Xcode 6.1.

**Comment by bilderbuchi** [comment]
is this still occuring with current master?

**Comment by bilderbuchi** [comment]
closing as there's no follow-up
