### ISSUE TITLE
 Kinect depth texture not working under the Programmable Renderer

### ISSUE THREAD

**Issue by youandhubris** [openframeworks/openFrameworks#3483]
If I enable the ofGLProgrammableRenderer on the current release, or by setting up ofSetOpenGLVersion on the master version, the getDepthTexture function doesn't work. It just returns a black screen.

I'm using Mac OS 10.10.1, XCode 6.1 and I don't get any error messages.

**Comment by bilderbuchi** [comment]
is this still occuring with current master?
