### ISSUE TITLE
ofLoadImage on Win8 VS - FreeImage_Load() causes heap corruption.

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#3486]
When loading this particular image (and others):

http://images.collection.cooperhewitt.org/44777_05e33c1aec037de1_b.jpg

Visual Studio 2012 triggers a breakpoint deep inside freeImage ( FreeImage_Load() ) and it reports something along the lines "heap block at modified at past requested size of 1".

You can reproduce the issue with:
```
ofImage img;
img.load("44777_05e33c1aec037de1_b.jpg");
```

Not entirely sure how much of an issue can this really be, but given I am having random crashes here and there and I'm trying to fix them entirely, I thought this could be a cause, as I load lots of images over time.

The current version of OF uses freeImage 3.15.3 and but there's a version 3.16 available. I tried with that version of freeImage, and the exception is not triggered anymore. The change is quite simple (just replacethe FreeImage header, .dll and .lib). Wondering what's holding OF back from updating FreeImage to 3.16, there's quite a few improvements.

http://freeimage.sourceforge.net/changeslog.html

**Comment by bilderbuchi** [comment]
is this still occurring with the new libs?

**Comment by tgfrerer** [comment]
Just tested w/ VS2015RC debug+release 32 bit, and i'm bit seeing this anymore.

**Comment by bilderbuchi** [comment]
thanks!
