### ISSUE TITLE
ambiguous ofXml error messages

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#3488]
ofXml gives me this when it can't load a file aka file path is wrong:

    [ error ] ofXml: loadFromBuffer(): DOM ERROR

It would be a lot more helpful if there was a file path check *before* trying to load the given file so something like this could printed instead:

    [ error ] ofXml: couldn't load, file not found

`DOM ERROR` makes you think something is wrong with the markup when, in fact, the file path is wrong. Not very helpful to anyone, beginner or not.

Similarly, you get the general `DOM ERROR` when parsing fails. Accessing TinyXML directly in ofxXml, I was able to get line numbers and a better error description.

**Comment by danomatika** [comment]
After being tired of obtuse error messages for the last time, this turned out to be a pretty easy fix.

**Comment by danomatika** [comment]
Fix is in this PR: https://github.com/openframeworks/openFrameworks/pull/3745

**Comment by joshuajnoble** [comment]
+1
