### ISSUE TITLE
Missing Implementations: of3dPrimitive

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3494]
- [x] of3dPrimitive::clear()
- [ ] of3dPrimitive::removeTexture(int)
- [ ] of3dPrimitive::removeMesh(int)

From https://github.com/openframeworks/openFrameworks/issues/2748

**Comment by kylemcdonald** [comment]
i think these two methods should be removed. i can't find any corresponding `add*()` methods that would explain what these are supposed to be doing.
