### ISSUE TITLE
Remove Support for OSX 10.6

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3507]
- [X] ofConstants (Update)
- [X] Legacy QuickTimePlayer (do we still need this for windows?)
- [X] Makefiles

**Comment by pizthewiz** [comment]
I have these changes in a local branch and if we can get #3502 merged, should be able to test and PR shortly.

**Comment by pizthewiz** [comment]
`ofQuickTimePlayer` appears to be used by Windows when without MinGW, see [ofConstants.h#L308-323](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L308-323):
```c++


    #elif defined(TARGET_WIN32) && !defined(__MINGW32__)
        #define OF_VIDEO_PLAYER_DIRECTSHOW
    // (...)
    #else
        #define OF_VIDEO_PLAYER_QUICKTIME
```

`ofQuickTimeGrabber.h` would now be dead via preprocessor [ofConstants.h#L269-282](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L269-282):
```c++
	#elif defined (TARGET_WIN32)

		// comment out this following line, if you'd like to use the
		// quicktime capture interface on windows
		// if not, we default to videoInput library for
		// direct show capture...

		#define OF_SWITCH_TO_DSHOW_FOR_WIN_VIDCAP

		#ifdef OF_SWITCH_TO_DSHOW_FOR_WIN_VIDCAP
			#define OF_VIDEO_CAPTURE_DIRECTSHOW
		#else
			#define OF_VIDEO_CAPTURE_QUICKTIME
		#endif
```

**Comment by pizthewiz** [comment]
This is in limbo given #3543…

**Comment by kylemcdonald** [comment]
changing this issue to "remove 10.6 support" which will happen when @tgrerer's PR #3627 is pulled

**Comment by pizthewiz** [comment]
@tgfrerer now that #3627 has been integrated is OS X 10.7 is our new minimum and this can be closed yeah?

**Comment by tgfrerer** [comment]
Yes

**Comment by pizthewiz** [comment]
Closing, OS X minimum is now 10.7 :+1:
