### ISSUE TITLE
TARGET_NO_VIDEO?

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#3515]
So we have TARGET_NO_SOUND macro to disable sound if application don't need it, is it possible to do the same for video stuff?

I have an idea for a text editor application, but I don't want to force user install all the video codecs and libraries just so he could use the app. It's especially the problem for Linux where all the dependencies are usually linked dynamically and user should manually install them before using the application. Also, distro like Fedora requires user to enable [non-free repository](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/fedora/install_codecs.sh) to install codecs which he / she doesn't need in this case at all.

**Comment by bakercp** [comment]
+1 for this feature add.  It seems with NO_SOUND and NO_VIDEO we would be moving a little closer to the more modular OF that has been discussed in the roadmap and elsewhere.

**Comment by procedural** [comment]
Chris, exactly. I just hope it's not that much of a work to do, but I'm sure it's the last feature on my list which I would like to see in 0.9.0! :) I guess I can do a *proposal* PR if no one have time for this? And if it won't meet the requirements it can be closed.

**Comment by bakercp** [comment]
I'd suggest a proposal PR.  Since it's mostly pre-processor work and
backward compatible, it should be of interest ... (by the way, this is also
of interest for me with ofSketch, as we are running ofAppNoWindow).

**Comment by procedural** [comment]
> (by the way, this is also of interest for me with ofSketch, as we are running ofAppNoWindow)
Ah, yes, why would ofAppNoWindow care about videos! :)

**Comment by bakercp** [comment]
I suppose it might if it was just doing pixel-based stuff, but we're moving more and more toward direct to texture video, so having an option for no video (and no sound) makes a lot of sense to me.

**Comment by bakercp** [comment]
That said, for ofSketch you are always going to have to install dependencies to compile apps with the internal distro ... so I guess that's just going to be part of the game.

**Comment by procedural** [comment]
Well, at least ofSketch won't be so dependant on non-free codecs if people choose write non-audio-video apps. I'm using openFrameworks mostly for OpenGL, for example, it definitely would simplify my apps a lot...

**Comment by procedural** [comment]
I'll make it happen tomorrow! By the way, since only I and Chris agree on this, has anyone have something to say about the idea? @bilderbuchi, @arturoc, @tgfrerer?

**Comment by procedural** [comment]
Here's a recap:

 1. Apps won't depend on proprietary video codecs
 2. Less dependencies for end users to install to use applications
 3. Lesser binary size for application which don't require video capabilities (ofSketch, audio synths)
 4. Link time will be reduced. That's always good since compilers are great nowadays, but linkers still suck at handling big amount of libraries (MinGW's linker is the weakest one)
 5. The macro is deterministic. It won't be defined anywhere automatically and can be enabled by user only explicitly

**Comment by ofTheo** [comment]
I wouldn't be against that. Especially if we already have a TARGET_NO_SOUND. 
The main thing would be if it can be done cleanly. It would probably require checks then at the top of all video related files so you wouldn't have to manually pull the video files out of your project. 

@arturoc - any thoughts on this?
To me it doesn't seem as pressing a priority as other things we have but it also seems fairly logical too.

**Comment by arturoc** [comment]
anything that makes OF more modular is good imo. th only thing is that i added TARGET_NO_SOUND to be able to use OF in a platform where there were no sound support at all. so perhaps it would be good to check if it's the best way to go about this or there's some better way to enable/disable individual parts of OF

**Comment by arturoc** [comment]
and, yes, i agree with theo that this is not prioritary, also it's probably part of a bigger discussion of what needs to be done to be able to enable/disable different modules, not only video.

**Comment by procedural** [comment]
@arturoc, agree. [Found your comment](https://github.com/openframeworks/openFrameworks/issues/2587) on OF_SOUND_DISABLE,  I guess the plan was to make addons from sound, video and other features?

**Comment by arturoc** [comment]
That's something we discussed at the last OF meeting, making parts like the different video, sound... and probably at first anything that has different platform implementations into addons. that way it also makes it easier to swap from one system to another, like using gstreamer in  win or osx, or the different osx video implementations which would also help with the problem @bakercp found some days ago with qtkit/avfoundation in new platforms.

**Comment by bilderbuchi** [comment]
I got no strong feelings on this issue.

**Comment by procedural** [comment]
I'll close this since modularization of openFrameworks in a known issue which will be addressed at some point in future...
