### ISSUE TITLE
ofGLProgrammableRenderer mesh draw() is not maintaining fill state correctly

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3518]
In the function
```
void ofGLProgrammableRenderer::draw(const ofMesh & vertexData, ofPolyRenderMode renderType, bool useColors, bool useTextures, bool useNormals)
```

the use of 
```
glPolygonMode(GL_FRONT_AND_BACK, (ofGetFill() == OF_OUTLINE) ?  GL_LINE : GL_FILL)
```
causes fill state to leak. By this I mean, if you precede the draw() with an ofNoFill() statement, even if you follow this with ofPopStyle(), the following polygons will be drawn as outlines no matter what the prior state.

A temporary fix to this I found was to modify setFillMode:
```
void ofGLProgrammableRenderer::setFillMode(ofFillFlag fill){
    glPolygonMode(GL_FRONT_AND_BACK, (fill == OF_OUTLINE) ?  GL_LINE : GL_FILL);
	bFilled = fill;
}
```
Perhaps someone more familiar with this code can comment whether this is a proper solution...

**Comment by bilderbuchi** [comment]
pinging @openframeworks/2d-3d

**Comment by tgfrerer** [comment]
hey @pierrep, i'm trying to reproduce this, but keep failing. do you mind pasting a minimal example (just the code inside `draw()` so that i can hunt this down?

**Comment by pierrep** [comment]
Actually I just realised that it might not be reproducible with regular of generated geometry. I was having problems using a geometry shader that kept drawing outlines instead of being filled (for the above reason).

I triggered it by calling "ofDrawBitmapStringHighlight()" and then running a geometry shader in the draw(). Maybe try the geometry shader in the repo preceded by a ofDrawBitmapStringHighlight(). The latter has an ofNoFill() command that triggers the bug, due to the following ofGLProgrammableRenderer::draw() which calls glPolygonMode().

**Comment by pierrep** [comment]
I just tried to reproduce this easily, the Geometry shader example won't work because it's not built for GL 3.2. However, any example that uses an ofMesh will. So if you put an ofDrawBitmapStringHighlight() call at the start of the draw() function in the Assimp addon example, you'll see what I mean ( all non-wireframe meshes will now be wireframe)

**Comment by tgfrerer** [comment]
will check asap.

**Comment by tgfrerer** [comment]
hmm - sorry, still can't see anything. i'm adding a ofDrawBitmapStringHighlight at the top of ofApp::draw() in assimpExample. 

I think assimpExample (and the assimp addon) was written for fixed function GL, not for programmable GL. So it could be that in there (or in the assimp code) there are some bare GL methods flying around which modify the GL state in the background. 

If I had a minimal testcase a la: https://gist.github.com/tgfrerer/bce463cfa2213b7bf23f
that would make it a bit easier to track this down.

**Comment by pierrep** [comment]
Sorry, shouldn't have emphasised, you need to be using the programmable renderer, the bug only exists there. Did you do that?

**Comment by tgfrerer** [comment]
The thing is if I use the programmable renderer with an addon or project that uses bare OpenGL (2.0) calls (like assimpExample), all sorts of weird things can happen, and it wouldn't be necessarily be because of the renderer. Using assimpExample with the programmable renderer is quite brave in these respects, and makes it a bit more complicated to see what's actually going on; that's why i was hoping for an isolated test case =)

**Comment by pierrep** [comment]
OK, I'll try to reproduce it with a similar test case to the one above, with an ofMesh (it doesn't happen with a vboMesh because the ofPolygonMode() call doesn't happen.

**Comment by tgfrerer** [comment]
great =) here's the testcase i set up initially: https://gist.github.com/tgfrerer/b87b7427e0b1a4f0783c

**Comment by pierrep** [comment]
Hi Tim, just a quick update, you were right I wasn't able to reproduce the symptom in that test case. There's definitely a bug, but it's more insidious that I first thought. I'm busy at the moment but will revisit this as soon as I can and track down the exact problem...

**Comment by pierrep** [comment]
Ok, here's  a test case:

```
const ofIndexType Faces[] = {
    2, 1, 0,
    3, 2, 0,
    4, 3, 0,
    5, 4, 0,
    1, 5, 0,
    11, 6,  7,
    11, 7,  8,
    11, 8,  9,
    11, 9,  10,
    11, 10, 6,
    1, 2, 6,
    2, 3, 7,
    3, 4, 8,
    4, 5, 9,
    5, 1, 10,
    2,  7, 6,
    3,  8, 7,
    4,  9, 8,
    5, 10, 9,
    1, 6, 10 };
const float Verts[] = {
    0.000f,  0.000f,  1.000f,
    0.894f,  0.000f,  0.447f,
    0.276f,  0.851f,  0.447f,
    -0.724f,  0.526f,  0.447f,
    -0.724f, -0.526f,  0.447f,
    0.276f, -0.851f,  0.447f,
    0.724f,  0.526f, -0.447f,
    -0.276f,  0.851f, -0.447f,
    -0.894f,  0.000f, -0.447f,
    -0.276f, -0.851f, -0.447f,
    0.724f, -0.526f, -0.447f,
    0.000f,  0.000f, -1.000f };

ofVec3f v[12];
ofVec3f n[12];
ofFloatColor c[12];
ofVbo vbo;

//--------------------------------------------------------------
void ofApp::setup(){
    int i, j = 0;
    for ( i = 0; i < 12; i++ )
    {
        c[i].r = ofRandom(1.0);
        c[i].g = ofRandom(1.0);
        c[i].b = ofRandom(1.0);

        v[i][0] = Verts[j] * 100.f;
        j++;
        v[i][1] = Verts[j] * 100.f;
        j++;
        v[i][2] = Verts[j] * 100.f;
        j++;
    }

    vbo.setVertexData( &v[0], 12, GL_STATIC_DRAW );
    vbo.setColorData( &c[0], 12, GL_STATIC_DRAW );
    vbo.setIndexData( &Faces[0], 60, GL_STATIC_DRAW );

    glEnable(GL_DEPTH_TEST);
}

//--------------------------------------------------------------
void ofApp::update(){

}

//--------------------------------------------------------------
void ofApp::draw(){
    ofDrawBitmapStringHighlight("hello",30,30);


    ofTranslate(ofGetWidth()/2, ofGetHeight()/2, 100);
    ofRotate(ofGetElapsedTimef() * 20.0, 1, 1, 0);
    glPointSize(10.f);
    vbo.drawElements( GL_TRIANGLES, 60);

}
```

**Comment by pierrep** [comment]
The polygon should be drawn in wire-frame in this example. Remove the ofDrawBitmapStringHighlight() line, and it should draw with faces filled.
