### ISSUE TITLE
Master Fails to Compile Android

### ISSUE THREAD

**Issue by danthemellowman** [openframeworks/openFrameworks#3519]
./../../libs/openFrameworks/sound/ofSoundStream.h:14:31: error: cannot allocate an object of abstract type 'ofxAndroidSoundStream'
  #define OF_SOUND_STREAM_TYPE ofxAndroidSoundStream

@arturoc can you build?
I'm trying out a fresh bring up of Eclipse.

**Comment by danthemellowman** [comment]
@arturoc its a simple fix. I've got it.

**Comment by danthemellowman** [comment]
well now I get this when I try to build an project

../../../libs/FreeImage/lib/android/armeabi-v7a/libfreeimage.a(libraw_cxx.o):libraw_cxx.cpp:function LibRaw_bigfile_datastream::get_char(): error: undefined reference to '__srget'
collect2: error: ld returned 1 exit status
make[1]: *** [libs/armeabi-v7a/libOFAndroidApp.so] Error 1
make: *** [Release] Error 2

**Comment by danthemellowman** [comment]
well not the core compile but the the app fails to link.  Something is up with the FreeImage

**Comment by procedural** [comment]
@danthemellowman share linker errors, it's actually pretty easy to know what's missing on linking stage.

**Comment by danthemellowman** [comment]
Its in my previous comment 

../../../libs/FreeImage/lib/android/armeabi-v7a/libfreeimage.a(libraw_cxx.o):libraw_cxx.cpp:function LibRaw_bigfile_datastream::get_char(): error: undefined reference to '__srget'

there is an undefined ref in the android build of FreeImage.  I tried rebuilding it using apothecary but it throws some weird error.

**Comment by procedural** [comment]
`__srget` was removed in ndk 10c: https://developer.android.com/tools/sdk/ndk/index.html

As an option you can fall back to ndk 10b for now:

http://dl.google.com/android/ndk/android-ndk32-r10b-darwin-x86.tar.bz2
http://dl.google.com/android/ndk/android-ndk64-r10b-darwin-x86_64.tar.bz2

**Comment by danthemellowman** [comment]
ok cool. let me try that.  I was using r9d forever.

I was in the process of testing out bringing up a new version of Eclipse to update the Docs and it's turned into an all day process haha.

**Comment by danthemellowman** [comment]
ok yeah reverting to the old one works. :)

**Comment by procedural** [comment]
Cool :)

I wonder should we open an issue about that error you've got when tried to compile recent FreeImage with apothecary? Pinging @bakercp :) Curious is it ready for android...
