### ISSUE TITLE
OpenGL drawing broken on Windows

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#3523]
Neither programmable GL nor fixed function GL seem to work currently under windows 8.1.

This is what I'm seeing with the advanced3D example (notice the missing primitives):
![capture](https://cloud.githubusercontent.com/assets/423509/5614396/98b16b32-94e8-11e4-83ec-5caff7b9dad2.PNG)

I'm using VS2012, with a NVIDIA GT 750M with the latest Game Ready driver. Older, compiled projects still run, so we can rule out a driver issue.

I suspect it has something to do with an `ifdef` gone astray during one of the latest refactors, or a broken shader mapping. 

Trying to hunt this down currently, this issue in case someone else encounters this.

Possibly related to #3514

**Comment by tgfrerer** [comment]
Ok, seems i've narrowed it down to `ofBufferObject.cpp` using glNamed* methods, which are only available with OpenGL 4.5+, which my current driver doesn't seem to support.

These methods are `#defined` through `GLEW.h`, and have a `#define` around them in `ofBufferObject.cpp` - I come to think that's not enough, we'd need to check for whether these methods are actually *implemented*. Looking into this now.

Commenting out the `glNamed*` methods seems to fix the drawing issue on first sight.

**Comment by tgfrerer** [comment]
Fixed it, with some help from the friendly people on irc's #OpenGL channel (shout-out to slime there. \o/) 
PR on the way...

**Comment by arturoc** [comment]
if you can't find something very straight forward we can comment those out by now since i don't think anybody has 4.5 compatible drivers yet and the alternative implementation emulates the named buffers access.

**Comment by procedural** [comment]
> since i don't think anybody has 4.5 compatible drivers yet

[Nvidia claims to support OpenGL 4.5](https://developer.nvidia.com/opengl-driver) (in beta driver)...

**Comment by tgfrerer** [comment]
indeed! i'm already sailing on 4.5 in windows =)

**Comment by procedural** [comment]
Lucky you :) I'm on AMD....
