### ISSUE TITLE
our GLFW version is not up to date

### ISSUE THREAD

**Issue by igiso** [openframeworks/openFrameworks#3531]
hi,
our compiled  glfw  libraries have some bugs in them that are solved in the master branch of GLFW
 
Here are the bugs so we can keep an eye on them:

MAC:
MouseCursor disappears  
fix:
https://github.com/openframeworks/openFrameworks/issues/3052 (&fixed in master)

Pool Cursor position directly:
fix
https://github.com/glfw/glfw/issues/355 (solved in master)

weird
resizing problem:
fix:
https://github.com/openframeworks/openFrameworks/issues/2456
(not sure if this will ever be fixed in glfw master)
what I currently do is:

in ofAppGlfwWindow.h

change  display(void);
to:
<pre lang="c++"><code>
	void			display(bool usePollEvents_=true);
</code></pre>
& in ofAppGlfwWindow.cpp

<pre lang="c++"><code>
#if defined(TARGET_OSX)//fix white screen bug
	ofEvents().notifyUpdate();
    instance->display(false);
#endif
</code></pre>

//AND IN display():
//the very last line:
<pre lang="c++"><code>

	if(usePollEvents_)glfwPollEvents();

</code></pre>

This is basically what @elmindreda is describing as a solution in 
https://github.com/glfw/glfw/issues/1

ON PC:
https://github.com/glfw/glfw/issues/338

I followed these instructions to compile a GLFW window that can work under openGL 1.1
Maybe we can add a flag in our version of GLFW
and if glVersion 1,1
then … don't use "accelerated pixels"
else "accelerated pixels"
I currently have a compiled GLFW version for CODEBLOCKS that does that.
//this is not a high priority issue but anyway..

GLFW added this to a future milestone but haven't fixed it yet so that it can be modified without recompiling

**Comment by arturoc** [comment]
thanks so much Camilla we are releasing a new version soon too, we'll include 3.1.

**Comment by igiso** [comment]
ok brilliant! closing this as solved then

@arturoc (non glfw related)
I noticed that with the new 
implementation in master branch resize_cb is called BEFORE setup

with ofSetupOpenGL()

resize_cb is not called. so everything is OK

with ofCreateWindow()

reisze_cb is called once for some reason, 

and this means that the solution to the resizing problem will cause unexpected behavior as it is.



Thank's @elmindreda & @arturoc  for your insanely amazing great efforts.

**Comment by igiso** [comment]
my bad resize_cb is not called!!
I called setWindoSize in setup! :+1: 

weird how with ofCreateWindow is called but with ofSetupOpenGl is not!
