### ISSUE TITLE
ofVboMesh doesn't draw meshes on Mesa driver [2]

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#3532]
And if so, why it's not working for me?

Here I'm assigning `ofMesh` returned from `getMesh()` method to `ofVboMesh bitmapMesh`:

```cpp
#include <ofMain.h>

class ofApp : public ofBaseApp
{
  public:
	void draw();
};

void ofApp::draw()
{
	ofSetBackgroundColor(0);
	ofBitmapFont bitmapFont;

	ofVboMesh bitmapMesh = bitmapFont.getMesh("Verba volant, scripta manent.", 40, 40);

	bitmapFont.getTexture().bind();
	bitmapMesh.draw();
	bitmapFont.getTexture().unbind();
}

int main()
{
  ofGLFWWindowSettings settings;
  settings.setGLVersion(2, 1);
  settings.width = 315;
  settings.height = 75;
  ofCreateWindow(settings);

  return ofRunApp(new ofApp());
}
```

![screenshot](https://cloud.githubusercontent.com/assets/1072168/5680321/9dc1e7c8-981c-11e4-9812-b585559cd692.png)

Now I'm assigning `ofMesh` to **`ofMesh`**`bitmapMesh`:

```cpp
	ofMesh bitmapMesh = bitmapFont.getMesh("Verba volant, scripta manent.", 40, 40);
```

![screenshot](https://cloud.githubusercontent.com/assets/1072168/5680320/940c43ae-981c-11e4-94a8-40d2b6e16ce6.png)

I'm testing it on Linux with Mesa 10.5.0 driver.

**Comment by bilderbuchi** [comment]
pinging @openframeworks/2d-3d

**Comment by procedural** [comment]
Just to give a perspective here: because of this issue ofxGui is not showing button and slider bitmap labels...

[Here's an example from ofxLabel.cpp](https://github.com/openframeworks/openFrameworks/blob/b091db2/addons/ofxGui/src/ofxLabel.cpp#L38): getTextMesh returns `ofMesh` but [`textMesh` has `ofVboMesh` type](https://github.com/openframeworks/openFrameworks/blob/b091db2/addons/ofxGui/src/ofxLabel.h#L48). If I manually change it to `ofMesh` in headers, bitmap labels will work fine as in my code example above.

**Comment by arturoc** [comment]
yes this used in several places so it's strange that it's not working. i wonder if it's something similar to your other problem that seem to be related to the ATI driver. gui is drawing fine for me, i'm going to test your example...

**Comment by arturoc** [comment]
yeah it's working for me without problem. not sure what might be going on it's probably something related to how vbos are initialized.

**Comment by procedural** [comment]
Yea, maybe it's related to open source driver again, but now it's happens on OpenGL 2.1, which is entry level for all of consumer hardware out there...

**Comment by procedural** [comment]
> not sure what might be going on it's probably something related to how vbos are initialized.

Most probably, since ofMesh works fine and afaik it's converted to ofVboMesh at the end anyway?
