### ISSUE TITLE
AVF based ofVideoPlayer draw(x, y, w, h) does not work as expected

### ISSUE THREAD

**Issue by danthemellowman** [openframeworks/openFrameworks#3536]
Below is the output of ofVideoPlayer on OSX 10.9.  If I try to scale the video texture using the    

    video.draw(0, 0, video.width*scale, video.height*scale);

![screenshot 2015-01-10 12 44 03](https://cloud.githubusercontent.com/assets/719564/5692516/aac701c4-98c6-11e4-9e09-aa981a0036c3.png)

To scale the video texture and prevent this issue I must do this:

    ofPushMatrix();  
    ofScale(scale, scale).
    video.draw(0, 0);
    ofPopMatrix();

![screenshot 2015-01-10 12 44 29](https://cloud.githubusercontent.com/assets/719564/5692515/aac5917c-98c6-11e4-9966-e0aa9ced4b85.png)

**Comment by danthemellowman** [comment]
might have just pushed this to master.  I forgot I could just *do that*

**Comment by bilderbuchi** [comment]
:D
