### ISSUE TITLE
ofxOsc doesn't make use of OSC 1.1 types specifications

### ISSUE THREAD

**Issue by groolot** [openframeworks/openFrameworks#3537]
The OSC 1.1 specifications are not correctly implemented in ofxOsc and the oscpack extra library.
By now, the following message will not be interpreted:
`/to/my/boolean/path T`
nor this one:
`/to/my/boolean/path F`

By the way, oF developers seems to have choosen the `int`, `float` and `string` replacement like that:
`/to/my/path i 0` or `/to/my/path f 0` or `/to/my/path s true` interpreted as **TRUE** and `/to/my/path i 1` or `/to/my/path f 1` or `/to/my/path s false` interpreted as **FALSE**, but that's not enough and NOT according specifications.

**Comment by pizthewiz** [comment]
Isn't this just #3534? Or is this tracking *all* of the missing OSC 1.1 types?

**Comment by bilderbuchi** [comment]
I think it's a more general version. don't know why @groolot closed the other one, we could just have edited the title.

**Comment by groolot** [comment]
I'm working on. It's, in fact amistake to have closed the #3534.
Sorry

**Comment by pizthewiz** [comment]
No worries, is this issue just for the boolean type?

**Comment by groolot** [comment]
No. I'm working on ALL OSC 1.1 specification types.
Should be available soon. :)

**Comment by groolot** [comment]
Just have commited my modifications.
Could you please have a look?

**Comment by armadillu** [comment]
this seems to break OSC on Mac OS X 10.10 on 10.10 sdk.

/addons/ofxOsc/src/ofxOscSender.cpp:182:6: Use of overloaded operator '<<' is ambiguous (with operand types 'osc::OutboundPacketStream' and 'int64_t' (aka 'long long'))

**Comment by armadillu** [comment]
NVM, I see it's already fixed in https://github.com/openframeworks/openFrameworks/commit/ff6c6a4dd932f74f92cb4fadf91255e2aa5cf237
