### ISSUE TITLE
ios glew compiler errors

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3541]
when compiling ios examples using the latest master, theres quite a few glew compiler errors.
below are of few of those errors. anyone know what new changes could be causing this?

https://github.com/openframeworks/openFrameworks/blob/master/libs/glew/include/GL/glew.h#L1675
/Volumes/STORAGE/openFrameworks/libs/glew/include/GL/glew.h:1675:19: Typedef redefinition with different types ('ptrdiff_t' (aka 'int') vs 'long')

https://github.com/openframeworks/openFrameworks/blob/master/libs/glew/include/GL/glew.h#L1676
/Volumes/STORAGE/openFrameworks/libs/glew/include/GL/glew.h:1676:19: Typedef redefinition with different types ('ptrdiff_t' (aka 'int') vs 'long')

https://github.com/openframeworks/openFrameworks/blob/master/libs/glew/include/GL/glew.h#L17094
/Volumes/STORAGE/openFrameworks/libs/glew/include/GL/glew.h:17094:17: Unknown type name 'PFNGLBLENDEQUATIONEXTPROC'

**Comment by arturoc** [comment]
glew shouldn't be included by iOS so there's probably some wrong ifdef, can you check where that file is included?
