### ISSUE TITLE
Add push/pop style in FBO begin/end

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/openFrameworks#3547]
As suggested by @arturoc in #3542, this would be nice so that repeated calls to ofSetColor() aren't necessary. For example...

ofSetColor(ofColor::white);
obj.drawIntoFbo(); // <-- leaves color at red, for example

ofSetColor(ofColor::white);
obj.draw();

...could be simplified to...

ofSetColor(ofColor::white);
obj.drawIntoFbo(); // <-- leaves color at red, but it wouldn't matter :)
obj.draw();

**Comment by kylemcdonald** [comment]
thanks for pulling this into an issue. this would fix so many mistakes for beginners and advanced users alike.

@arturoc is there anything special we'd have to do to make this happen? or can we just add the push/pop style adjacent to wherever the screen setup is being done? presumably there's already a push/pop matrix or similar in there already.

**Comment by mattfelsen** [comment]
thanks ;)

**Comment by kylemcdonald** [comment]
thank you @arturoc :) looks like we need to work on better documentation of how ofRenderer interfaces with other classes so more people can make such simple changes ;)
