### ISSUE TITLE
ofxopencv compatible for ios plaform 

### ISSUE THREAD

**Issue by almog-kiki** [openframeworks/openFrameworks#3552]
After a lot of time in research i find there is  a problem with <code> clone() </code> function 
I try to run ofxASM for ios and when clone() is call the app is crash and i get exc_bad_error. 
you know something about this issue ?( for ios) 
(the project is work well on mac osx )

**Comment by bilderbuchi** [comment]
hey! please try to reproduce this without using external addons, so that we can make sure the problem lies within OF, not the addon.

**Comment by julapy** [comment]
@almog-kiki can you put together a simple iOS ofxOpenCV example which can demonstrate the crash?

**Comment by almog-kiki** [comment]
I run the opencvexapmle (there is no something to clone there so I created  "frame" as variable as a matrix , and did like this: 
<code>
frame = grayImage.getCvImage(); 
Mat a;
 a = frame.clone();
 </code>
and it's works properly .

**Comment by almog-kiki** [comment]
THE PROBLEM IT WAS THE FRAMEWORKS opencv2.frameworks is in the xcode project

**Comment by bilderbuchi** [comment]
...in which xcode project? ofxCv's? can we close this issue, then?

**Comment by almog-kiki** [comment]
not specific project. I just add this to my project because I used ofxASM.
yes u can close.
