### ISSUE TITLE
ofSerial.readByte misbehaving on some linux machines, working fine on others

### ISSUE THREAD

**Issue by mentarus** [openframeworks/openFrameworks#3554]
Anyone having issues with readByte on linux? My linux64 works fine, on another 4 32 bit linux machines it comes up with 0x85 followed by 0x00. Encountered when trying to run https://github.com/BlitzKraft/guino

**Comment by arturoc** [comment]
i did some fixes a while ago to ofSerial and ofArduino, i think they are not in the current version 0.8.4 but in master in github can you try using the latest OF from github and see if that fixes the problem?

**Comment by bilderbuchi** [comment]
no follow up by reporter, closing this.
