### ISSUE TITLE
ofxGui texts not rendered when depth test enabled

### ISSUE THREAD

**Issue by micuat** [openframeworks/openFrameworks#3556]
ofxGui needs `ofDisableDepthTest()`-ed to correctly render texts. Tested with oF 0.8.3 on OSX.

Maybe related: http://forum.openframeworks.cc/t/ofxgui-text-missing/17344

**Comment by arturoc** [comment]
this is expected, anything that has several layers of 2d elements won't draw properly if depth testing is enabled. i don't think we should check for this or disable depth testing internally, the main problem with that, is performance and that we shouldn't be checking for every possible setting that could make something not draw properly. if you do a translate or have a non default perspective settings the gui won't draw correctly either for example.

**Comment by kylemcdonald** [comment]
going to close this given explanation from @arturoc 

this seems like the kind of thing that could be documented somewhere, or at least the general idea of not checking for non-default values, but i'm not sure where to document it.
