### ISSUE TITLE
ofPolyline getCentroid2D() can return NAN / infinity coordinates

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#3558]
On perfectly decent ofPolylines (meaning with valid non-NAN points), you do get sometimes a centroid with x / y that's NAN. I suspect its related to the calculated area being zero. I can't fully test now, but I was getting NANs which where propagating to other parts of the code and ultimatelly leading to crashes while working with lots of user-generated ofPolylines.

I switched to .getBoundingBox().getCenter() which was good enough for the project, and I got no more NAN's.

**Comment by ofZach** [comment]
good test example (straight line = 0 area): 

    ofPolyline line;
    
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(40,40);
    
    cout << line.getCentroid2D() << endl;

**Comment by armadillu** [comment]
Ah of course, I didn't think of this case. I guess it's not a really a bug then...

**Comment by ofZach** [comment]
I've always felt the centroid is considering the polyline as a shape, but I prefer to just compute the centroid of the points as a point set (ie, add up all the pts and find the average).  I'm not sure of what the difference is, but I still feel like a polyline without an area should have a midpt.

**Comment by ofZach** [comment]
ah I take this back thinking about it a bit more (I think this makes sense if the line is uniformily sampled, but not so much if it's not uniform), but maybe, we should have some error handling when the area < epsilon, etc.

**Comment by bilderbuchi** [comment]
mathematically, it's pretty clearly defined:

> In mathematics and physics, the centroid or geometric center of a two-dimensional region is the arithmetic mean ("average") position of all the points in the shape. 

Here, "points" are the infinite points (e.g. of mass) making up the shape, not the vertices of a polygon.

However, there's a [formula](http://en.wikipedia.org/wiki/Centroid#Centroid_of_polygon) given for the centroid of a polygon, are we using that one? I haven't yet done the math manually to see if this holds up with degenerate points, but I'd assume so from a quick glance.

**Comment by bilderbuchi** [comment]
ok, the formula [we use](https://github.com/openframeworks/openFrameworks/blob/39e374059aa18f62c5590789ca0055302490c2c5/libs/openFrameworks/graphics/ofPolyline.cpp#L962-L980) is the same as the one from WP, with a workaround for the fact that our polygons are not closed, in that the first and last point are not identical - is that still correct?
It could also be that the requirement of non-selfintersecting polygons is violated in some polygons where this fails?
A quick git blame indicates that the code is from @memo.

**Comment by bilderbuchi** [comment]
Ah of course - at least in the example that @ofZach posted above, the *area* of the degenerate polygon is 0, so in the centroid calculation we divide by zero, pretty clear that that would give NaN.` >.<`

**Comment by kylemcdonald** [comment]
taking all of the above discussion into account, how about adding:

```c++
if(area == 0) {
	ofLogWarning("ofPolyline") << "centroid of zero-area polygon is undefined, using center of bounding box";
	centroid2D = getBoundingBox().getCenter();
} else {
	// centroid calculation
	// ...
}
```

here is the code i tested it with:

```c++
#include "ofMain.h"

class ofApp : public ofBaseApp {
public:
    void setup() {
        ofPolyline line;
        
        // straight line
        line = ofPolyline();
        line.addVertex(0,0);
        line.addVertex(20,20);
        line.addVertex(40,40);
        cout << line.getCentroid2D() << endl;
        
        // self-intersecting polygon
        line = ofPolyline();
        line.addVertex(0,0);
        line.addVertex(20,20);
        line.addVertex(0,20);
        line.addVertex(20,0);
        cout << line.getCentroid2D() << endl;
    }
    void draw() {
    }
};
int main() {
    ofSetupOpenGL(1280, 720, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

here is the output:

```
[warning] ofPolyline: centroid of zero-area polygon is undefined, using center of bounding box
20, 20, 0
[warning] ofPolyline: centroid of zero-area polygon is undefined, using center of bounding box
10, 10, 0
```

**Comment by kylemcdonald** [comment]
i'm testing some more code now and not convinced that the ofLogWarning() is necessary. it doesn't really tell you enough, and it will pop up every time you have a straight ofPolyline that you want to know something about... which is too often.

**Comment by ofZach** [comment]
I think this approach seems good, it's probably better to use an epsilon the do a floating point equality test.   I think disabling the warning is ok....

**Comment by kylemcdonald** [comment]
@ofzach i tried to create a situation where the area was so small that the value for the centroid was incorrect, but the only time i get the wrong behavior from this function is when the area is exactly 0.

```c++
#include "ofMain.h"

int main() {
    ofPolyline line;
    line.addVertex(0,0);
    line.addVertex(1,1);
    line.addVertex(2,2.00000015);
    cout << line.getCentroid2D() << endl;
}
```

```
[notice ] 1, 1, 0
```

even though in this case, if you look at the `area` inside the `updateCache()` function, it says it is `1.19209e-07` (i.e., equal to `FLT_EPSILON`).

**Comment by ofZach** [comment]
yeah I just have it ingrained to just never trust == with floats, I think different compilers / cpus might handle things differently.  We also have some parts of the code that use FLT_EPSILON to check for non-zero, it's probably good to be consistent.

**Comment by bilderbuchi** [comment]
Also, add an abs, if the cw/ccw winding is wrong, the area from the formula will be negative...

**Comment by bilderbuchi** [comment]
Also, +1 on proper float comparison.

**Comment by memo** [comment]
perhaps we could have a generic function to do float equality comparison?

    bool ofIsEqual(float f1, float f2) {
        return fabsf(f1-f2) < FLT_EPSILON;
    }

    bool ofIsZero(float f) {
        return ofIsEqual(f, 0.0f);
    }

**Comment by kylemcdonald** [comment]
@memo i was going to suggest the same but then i read this article https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

and the summary is basically "There is no silver bullet. You have to choose wisely." if we use something like you suggest it will lead to a lot of unintended errors for general floating point comparison. however, i think in terms of comparing zeros it's not the end of the world.

again, i think that the correct way to implement this function is with an exact comparison to 0, because all other values for area give correct results in my tests. but i've submitted PR #3567 with the epsilon comparison anyway under the assumption that i just don't completely understand this situation.

**Comment by memo** [comment]
wow that's mega hardcore geek :)
I usually have a little util like the below in my libs, so I can pass in different margins. 

    bool ofIsEqual(float f1, float f2, float margin = FLT_EPSILON) {
        return fabsf(f1-f2) < margin;
    }

Reading that article, it seems obvious that for most numbers a relative comparison actually makes more sense (but slowly to compute probably)

If I'm not mistaken, if < FLT_EPSILON doesn't work, == definitely won't either :)

**Comment by bilderbuchi** [comment]
yeah, I was also gonna suggest a relative comparison in your function, Memo. Also, I agree, floating-point is hard. :D:

@kylemcdonald can you test with a self-intersecting polygon whose area is not 0? Just a sanity check, the centroid calculation should give the wrong result. Don't know how we would easily test that, and log, though.

**Comment by bilderbuchi** [comment]
also, are we sure we don't want to at least emit a Verbose log message? What we do here is rather "magic", after all.

**Comment by kylemcdonald** [comment]
funny how we all hop onto the smallest most boring issue to cast our opinions :) on a sunday no less.

@bilderbuchi sorry i forgot to mention in the PR, but i tested the following:

```c++
#include "ofMain.h"

int main() {
    ofPolyline line;
    
    // straight line
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(40,40);
    ofLog() << line.getCentroid2D();
    
    // self-intersecting polygon, zero area
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(0,20);
    line.addVertex(20,0);
    ofLog() << line.getCentroid2D();
    
    // self-intersecting polygon, positive area
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(0,20);
    line.addVertex(15,5);
    ofLog() << line.getCentroid2D();
    
    // self-intersecting polygon, negative area
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(20,0);
    line.addVertex(5,15);
    ofLog() << line.getCentroid2D();
    
    // positive area
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(0,20);
    ofLog() << line.getCentroid2D();
    
    // negative area
    line = ofPolyline();
    line.addVertex(0,0);
    line.addVertex(20,20);
    line.addVertex(20,0);
    ofLog() << line.getCentroid2D();
}
```

output:

```
[notice ] 20, 20, 0
[notice ] 10, 10, 0
[notice ] 11.6667, 28.3333, 0
[notice ] 28.3333, 11.6667, 0
[notice ] 6.66667, 13.3333, 0
[notice ] 13.3333, 6.66667, 0
```

please let me know if there are others you think of that are worthwhile. i'm assuming that any behavior with ofPolyline in 3D is undefined and anything that works is coincidence.

**Comment by bilderbuchi** [comment]
> funny how we all hop onto the smallest most boring issue to cast our opinions :) on a sunday no less.

funny how one person's "boring" is another person's interesting. ;-) mathematics is a field where I feel at home (as opposed to html/ios/...), so naturally that's where I try to weigh in. 
Also, the weekend is (nearly) the only time where I got extended timespans available to analyze and write lengthy comments for OF...

**Comment by memo** [comment]
"funny how we all hop onto the smallest most boring issue to cast our opinions :) on a sunday no less."

I'm tagged in this post for some reason (UPDATE: just realized that I'd been blamed for the error, sorry bout that :)

And smallest boring issues are often the ones that require the least time investment in responding. And like @bilderbuchi says, potentially quite interesting with far reaching implications. So minimum input -> maximum output :) 

Yes verbose logging vs invisible-behind-the-scenes-magic is a valid debate. I added the updatecache stuff, and I do that kinda stuff all the time in my code as an obvious optimization. I did try to make sure that all bases are covered, and the fact that the meta-data is cached *should* have no affect on the user. But if there are situations which I haven't foreseen, then potentially it could have *could* have nasty side effects.

The current problem I have with the verbose logging system is, if you enable verbose logging **everything** starts logging everything and flooding the console, making it almost useless to use when trying to debug a particular class. It's almost as if it would be good to be able to set each class (instance?) log level individually. But I digress...

I vote for:
- the fix @kylemcdonald did but with an epsilon check 
- preferably the epsilon check is via ofIsZero, but I'm not going to argue for this too hard
- we lose the log (For the reason Kyle said, updateCache is called on many occasions, would cause more confusion I think).

**Comment by armadillu** [comment]
I like the idea of ofIsEqual() and ofIsZero() (probably as inline methods), but it should be used all across the core on similar float comparisons. I think this would help a lot at catching lots of those edge cases.

As for log, we could also have some sort of mechanism that analyzes a bit the log history, and if the same line is logged many times, then it makes a digest of it. (i.e. "centroid of zero-area polygon << this message repeated 155 times"). 

I'm not sure how to do this efficiently with the current ofLog(), but getting into @memo's argument, if we had logging somehow separated in realms then we could more easily do stuff like that. 

I have a fork of [ofxSuperLog](https://github.com/armadillu/ofxSuperLog/blob/master/src/ofxSuperLog.h) in which I add a class context to the log line through macros which helps a lot when debugging... Maybe something like this that automatically gets a realm from which the log() call is invoked could be used to be able to set log different levels across different realms...

**Comment by bilderbuchi** [comment]
I thought we already could set log levels per module? or was that just the prefix string?

**Comment by armadillu** [comment]
ah that's very nice, I was not aware of this. So when you call ofSetLogLevel() it overrides the individual module log levels?

**Comment by memo** [comment]
@bilderbuchi I had no idea that we could do that! that's great! Is this used in the of core (i.e. each class has it's own module for logs). 

@armadillu "centroid of zero-area polygon << this message repeated 155 times" would be ace. maybe for the "nice things to do one day" list :)

**Comment by bilderbuchi** [comment]
> So when you call ofSetLogLevel() it overrides the individual module log levels?

I don't know what happens when you call the general metthod, tbh.
Afaik, it's not used in the core too much, maybe because no one took the time to convert all the oflog calls.
