### ISSUE TITLE
Memory leak in QTKitVideoGrabber

### ISSUE THREAD

**Issue by tobiasebsen** [openframeworks/openFrameworks#3560]
I have discovered a small memory leak in ofVideoGrabber when used on Mac OSX where it is using the QTKitVideoGrabber. The leak originates from the call to vImageConvert_BGRA8888toRGB888() which seems to allocate 64 bytes per call, which is never released. This is, of cause, a very small leak, but it accumulates to more than a hundred megabytes over a day.

The leak is only there when compiling openFrameworks with MacOSX 10.8 SDK or later, since the function is only available from this version.

![screen shot 2015-01-15 at 09 49 49](https://cloud.githubusercontent.com/assets/1135364/5754657/fd9de6b4-9c9b-11e4-8427-1b1dbcba8f19.png)

**Comment by bilderbuchi** [comment]
I'm assuming you're talking about [this call](https://github.com/openframeworks/openFrameworks/blob/e8faa075a60db765e7e440e468a96b09bf844d38/libs/openFrameworks/video/ofQTKitGrabber.mm#L542)? If the leak is in that function, is that really our bug, or Apple's?

**Comment by bilderbuchi** [comment]
pinging @openframeworks/macos @openframeworks/video

**Comment by pizthewiz** [comment]
Hmm, the screenshot shows allocation detail _not_ leaks - though instruments does call out a leak shortly after app launch, indicated by the red bar. The allocations are climbing in this graph, but (knowing nothing about `ofQTKitGrabber`) I suspect a new buffer is used each frame for video decode.

If one leaves the _videoGrabberExample_ running for a while, are the allocations called out not being reclaimed?

**Comment by bilderbuchi** [comment]
is this still an issue with current master?

**Comment by bilderbuchi** [comment]
closing as there's no follow-up by the reporter.
