### ISSUE TITLE
Remove ofxSynth

### ISSUE THREAD

**Issue by admsyn** [openframeworks/openFrameworks#3564]
This was discussed around the time of the YCAM dev meet, and tucked into the mega-sound-PR that has since been broken down into smaller parts.

Should we remove ofxSynth from the core addons? If I remember correctly, the rationale is that at this point it's just a heavily outdated version of [ofxMaxim](https://github.com/micknoise/Maximilian) and we could be pointing people towards that instead.

Related: #861 

@openframeworks/owners @openframeworks/sound

**Comment by arturoc** [comment]
yes let's remove it, we should have done it a while ago anyway and in any case it's now complete outdated with the merge of ofSoundBuffer...
