### ISSUE TITLE
Infinite loop when exiting an OF program using GLUT on OSX

### ISSUE THREAD

**Issue by K0j0** [openframeworks/openFrameworks#3568]
So I'm using GLUT because I'm working on a project in Ubuntu and OSX but GLFW isn't working in Ubuntu 14.10 right now. I'm using Glut in the way it's referenced in [this forum post](http://forum.openframeworks.cc/t/ofappglfwwindow-couldnt-create-glfw-window/13996/2?u=k0j0) and everything was working great for awhile. Then after updating a few days ago my program crashes whenever I exit with the ESC key in OSX. It looks like there's an infinite loop in the exiting sequence.

[Here's the stack trace in XCode](https://www.dropbox.com/s/6lszv8xvh77hhxa/glut_error.png)

In revision 6505b032deeea446def89d8b5495480c336683a8 there was a change in `ofAppGlutWindow::close()` from using `std::exit(0)` to `ofExit(0)`. It looks like this is what's causing the infinite loop. Changing it back to `std::exit(0)` prevents the infinite loop but I'm not really sure if there are other ramifications for that change. Can we just change it back or is it not that simple?

**Comment by pizthewiz** [comment]
@arturoc would better understand that particular rev and change but GLUT has been defocused (deprecated?) in favor of GLFW so I think it would be worth filing a separate issue for the issue on Ubuntu 14.10.

**Comment by arturoc** [comment]
just changed it to std::exit. in linux there's a function to actually exit from the main loop in glut that is not present in osx and win so i never found that error. 

the problem in ubuntu + glfw is actually a bug in unity, i've reported it to glfw https://github.com/glfw/glfw/issues/368 and unity: https://bugs.launchpad.net/unity/+bug/1383429  it's actually been fixed today in unity but i think only for the next release although it should be back ported soon

**Comment by pizthewiz** [comment]
Awesome, looks like a pretty gnarly issue thanks for following up on it!

**Comment by K0j0** [comment]
Very cool. Thanks @arturoc
