### ISSUE TITLE
deadlock in ofxTCPServer

### ISSUE THREAD

**Issue by galsasson** [openframeworks/openFrameworks#3580]
This is really strange:

isClientSetup tries to hold the mConnectionsLock lock:

//--------------------------
bool ofxTCPServer::isClientSetup(int clientID){
	ofMutex::ScopedLock Lock( mConnectionsLock );
	return TCPConnections.find(clientID)!=TCPConnections.end();
}

while this lock is already held by another function that calls isClientSetup. For example:

//--------------------------
bool ofxTCPServer::isClientConnected(int clientID){
	ofMutex::ScopedLock Lock( mConnectionsLock );
	return isClientSetup(clientID) && getClient(clientID).isConnected();
}

This happens all over ofxTCPServer, not sure how no one caught it before.
Or maybe I'm missing something?

**Comment by ofTheo** [comment]
hmm - this looks like it came from http://github.com/openframeworks/openFrameworks/commit/498bdf8934304ea013f187c38bfb923a91254b20

@SoylentGraham @arturoc - any thoughts?

**Comment by galsasson** [comment]
I took another look at it seems that removing the lock from isClientSetup, though not optimal, should do the trick. Currently this function is being called only from already locked scopes.

And it came from:
https://github.com/openframeworks/openFrameworks/commit/e8400fd09e02166731c0b67c084fe08d37a15d00

**Comment by SoylentGraham** [comment]
The lock is recursive isn't it? In which case it shouldn't be a problem if the locks are on the same thread... If they're on different threads... I can't see how isClientSetup is going to deadlock... so that should free for the other thread.

Remove the lock at your peril, it's there for a reason... I added all the locks because it wasn't threadsafe before when accept() got new clients...

**Comment by galsasson** [comment]
Hi @SoylentGraham,
FastMutex should not be recursive, thats why the deadlock.
Also, I'm working in 64bit, so maybe its behavior is different on 32bit?

Can you please share the risk of removing this lock? I rely currently on ofxTCPServer in my project, so if there is reason to keep this lock, maybe we can find another solution.

Thanks

**Comment by SoylentGraham** [comment]
Hmm I though ofMutex's default was recursive... maybe this has changed (I haven't used openframeworks for about a year I don't think)
32bit vs 64bit shouldn't make a difference unless OF does something different with the mutex's

The risk is a crash if TCPConnections changes (eg. with a client connecting, which occurs on a different thread) whilst you're calling the function.

My advice is to keep the lock, but to get around this[recursiveness] is to do the check manually. (Note, there may be a lock in getClient too...)

bool ofxTCPServer::isClientConnected(int clientID){
ofMutex::ScopedLock Lock( mConnectionsLock );
if ( TCPConnections.find(clientID)!=TCPConnections.end() )
return false;
return getClient(clientID).isConnected();
}

**Comment by arturoc** [comment]
if `isClientConnected` is just calling other functions which are themselves locking it shouldn't be locking. @SoylentGraham can you change that? otherwise i can take a look later

**Comment by galsasson** [comment]
small correction, **isClientSetup** is locking and is being called from all over the file from locked contexts.
I agree that isClientSetup code should be executed when the lock is held, but this already happens (every function that called is first hold the lock). And since this function is private, although not optimal, its safe for now to remove the lock there.
