### ISSUE TITLE
windows 8.1 app window position issue

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/openFrameworks#3595]
when open up the app, the window always stay on top left corner of screen
win7&win8 got same issue
![windows](https://cloud.githubusercontent.com/assets/51957/5936138/acda90b6-a71c-11e4-801d-89ccba9a6c00.jpg)

**Comment by bilderbuchi** [comment]
@openframeworks/windows can anybody reproduce?

**Comment by bilderbuchi** [comment]
also @liquidzym please state your OF version and IDE you're using.

**Comment by tgfrerer** [comment]
Yes, I'm seeing this too, on windows 8.1. 

Also window does not restore its original size after toggling back from fullscreen.

**Comment by igiso** [comment]
this seems like undefined behavior of ofWindowSettings::position due to different c++ dialect (?)
.. can you guys try use the new initialization format with the ofWindowSettings
and set the position to something before creating the gl window?

do you get build warnings as well?


use this in main:

ofGLFWWindowSettings settings;
	settings.width = 900;
	settings.height = 600;
	settings.position.x = 300;
	settings.position.y= 300;
	settings.resizable = true;
        settings.closeOtherWindows=true;
	shared_ptr<ofAppBaseWindow> mainWindow = ofCreateWindow(settings);
        ofRunApp(mainWindow, mainApp);
	ofRunMainLoop();

**Comment by liquidzym** [comment]
@bilderbuchi，sorry about that,i'm using current master brunch which is 0.9.0, visual studio 2013 IDE

**Comment by liquidzym** [comment]
@igiso,ok,try with your code,not getting build warning,but seems there's no method called closeOtherWindows
besides that,it did works ,the main window postion at the 300,300

**Comment by natxopedreira** [comment]
Im also seeing this. current oF master branch, win 8.1 vs21012

**Comment by DomAmato** [comment]
has this been fixed? I dont have this problem on any of my machines

**Comment by liquidzym** [comment]
i think that's already been fixed at least on windows. should i close this issue?
