### ISSUE TITLE
ofbClearBg seems weird

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#3597]
I can't really put my finger on it, but the global method `bool ofbClearBg()` in `ofGraphics` seems to fall out of our general naming convention. I would suggest to deprecate it in favour of the already present `ofGetBackgroundAuto()`.

`ofGetBackgroundAuto()` is much more easier to read, and does what it says, while ofbClearBg() could be mis-read as a global function to clear the background.

**Comment by tgfrerer** [comment]
oh, i see, that's already been deprecated. my bad ;/

**Comment by kylemcdonald** [comment]
@tgfrerer also curious to hear your thoughts on #3566
