### ISSUE TITLE
ofFbo with multisampling enabled, does not clear.

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3598]
the code below should make the fbo all white.
instead its just showing gpu garbage.

it works correctly when disabling multisampling => `fbo.allocate(w, h, GL_RGBA, 0);`
so its an issue with multisampling on the fbo i believe.

````
void ofApp::setup(){
    fbo.allocate(512, 512, GL_RGBA, 4);
}
````
````
void ofApp::draw(){
    fbo.begin();
    ofClear(255, 255);
    fbo.end();
    fbo.draw(0, 0);
}
````

**Comment by ofTheo** [comment]
@julapy - that is weird I get white. 
I can also clear it with different colors. 
Is this with master branch? I'm testing with 0.8.4 

Whats your GPU hardware?

**Comment by tgfrerer** [comment]
Yes, I'm seeing this too, on latest master / programmable renderer, NVIDIA 980, vs2012. 

Using multisampling I'm not seeing the white frame I do indeed get when multisampling is disabled. That said, i vaguely remember that multisampling is not yet fully implemented with all bells and whistles. Will dig deeper.

**Comment by armadillu** [comment]
Hey I tried this (was also getting the "garbage" fobs with multisampling) and it works, but I'm seeing some really ugly antialiasing.

http://cl.ly/image/0R380r1L0y0G

Anyone else?

**Comment by tgfrerer** [comment]
Hey @armadillu, how anti-aliased lines render depends highly on the FBO sample count. Can you increase it to see what happens? 

The visual impression also depends on the physical size of the pixels. I find that lines sometimes look nicer on HiDPI displays when rendered without smoothing / MSAA.

When it somes to (line) smoothing and multisampling, the discussion under #2028 has a couple of references...

**Comment by armadillu** [comment]
hey @tgfrerer I have it set to 8, the max for my HW. Actually, disregard this; It was just bc I was drawing on a transparent FBO; the blending wasn't helping. When I clear the FBO with solid black (0,255) it looks as it should.

![screen shot 2015-03-12 at 12 12 58](https://cloud.githubusercontent.com/assets/167057/6622138/1985fc40-c8b1-11e4-9d2c-2cd8dd789437.PNG)

**Comment by tgfrerer** [comment]
Phew! Ahh, blend modes, the eternal curse of graphics programmers =)

**Comment by armadillu** [comment]
yep - and so is "jumping to conclusions too quickly". Thanks much! :)
