### ISSUE TITLE
error C2065: 'data' : undeclared identifier in ofxOSC, UdpSocket.cpp

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3609]
Visual studio 2012, github OF... @ofTheo ?

**Comment by pierrep** [comment]
Also  error C2664: 'setsockopt' : cannot convert parameter 4 from 'unsigned long *' to 'const char *'

**Comment by bilderbuchi** [comment]
sounds maybe like a wrong include in the VS project? mind that there's a posix and a win folder [here](https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxOsc/libs/oscpack/src/ip), but your project should only use one.

**Comment by pierrep** [comment]
Yes I'm aware of that...but no it's not that. The windows codebase is different and seems to be missing an undeclared data variable...

**Comment by yty** [comment]
@pierrep @bilderbuchi 

I submitted before... 

https://github.com/yty/openFrameworks/commit/d726292e8a13b8a58d2f66f03f22f1973ab6dc7a

**Comment by pierrep** [comment]
@yty Yes, that fixes it, thanks!

**Comment by arturoc** [comment]
why are there errors in the libraries files? are we still using a patched oscpack? i lost track wit @ofTheo last modifications

**Comment by bilderbuchi** [comment]
unfortunately, @yty 's commit contains strange stuff, like the Win32 ifdef in a posix file (which should not be included in windows), so if there's a fix in there we should tease it out. 
@yty did you ever submit this fix upstream with the oscpack developer? that's the proper place where such a fix should land, and I seem to remember that I asked if you could do that before?
