### ISSUE TITLE
Dependencies are missing their License Agreements with their Source/Headers in /libs/

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3614]
Just noticed in the https://github.com/openframeworks/openFrameworks/tree/master/libs folder for all of the repositories we are missing the license agreements from all or most of the libraries.

BSD (Poco for example) https://github.com/pocoproject/poco/blob/develop/LICENSE
> ... The copyright notices in the Software and this entire statement, including
>the above license grant, this restriction and the following disclaimer,
>**must be included in all copies of the Software**, in whole or in part, and
>all derivative works of the Software, unless such copies or derivative
>works are solely in the form of machine-executable object code generated by
>a source language processor. ...

Do we have to include the LICENSE.txt/.md from these 3rd party dependencies with their headers?

I know we are acknowledging them in the https://github.com/openframeworks/openFrameworks/blob/master/LICENSE.md with links to the original source, however are we still breaking some sort of agreement?

@arturoc

**Comment by kylemcdonald** [comment]
i don't think we need to modify any of the header files, but it would be great to get the license files and put them adjacent to the libraries.

**Comment by danoli3** [comment]
Yeah I didn't mean modify the source headers whoops, I meant add the license files with the header locations / libraries as you suggested :D!

**Comment by bilderbuchi** [comment]
strange that they aren't in there yet, aren't we mainly just dropping the libs in? in any case, :+1: to adding the license files.

**Comment by kylemcdonald** [comment]
i know that apothecary has a working directory for checking out source, but it would be AMAZING if after cloning OF and running apothecary it was also responsible for copying the headers and licenses of these libraries into the libs/ folder (and we left everything but the openFrameworks folder empty).

**Comment by bilderbuchi** [comment]
that would probably also ensure that headers and compiled libs always stay in sync.

**Comment by danoli3** [comment]
Yeah I think Apothecary should have another step to the API - like ```copy()``` except only for the license files.

So we can do 
```./apothecary -t ios license tess2```

For example to just copy the license files.
And also make this a default step in the update process.

@danomatika

**Comment by danomatika** [comment]
No, that's too fine grained a step to create a new function for. Simply add the cp line to the copy() function in the formulas. Super easy.

I would have added this when I started Apothecary, but my original goal was to replicate the existing libs layout at the time which didn't include LICENSE files, as fas as I can recall. Definitely should add that now.

**Comment by danomatika** [comment]
For Poco this would be simply:

    cp -v LICENSE $1/include/Poco

**Comment by danoli3** [comment]
Okay cool thanks @danomatika 
I'll add the cp for all the libs we have currently.

Yeah just a matter if seeing on each where the license file / type is, for the most part should be in the root directory (build dir for each lib).

**Comment by danoli3** [comment]
Should we create a new folder in each libs folder for  ```License```.

If we had a folder structure like:

``` libs/freetype/license ```


So a license folder in each external dependancy if appropriate.

![oflicense](https://cloud.githubusercontent.com/assets/830748/6071870/f01b10c0-adee-11e4-836e-a1ab22f3f59e.png)

Be much cleaner than mixing it with the include directory.
Also if the files are in the headers include directory they may be pulled into the compilation process in some way.

**Comment by danomatika** [comment]
Nah, just put it in the main dir, i.e.

    freetype/FTL.TXT
    freetype/GPLv2.TXT
    freetype/LICENSE.TXT

**Comment by danoli3** [comment]
:+1: 

Yeah most of the time it is just going to be the one file so I did think the main folder, but FreeType had the exception of 3 of them XD so thought maybe be a bit cleaner. All for the main directory though of the lib though.

**Comment by danoli3** [comment]
Ah having them in the main lib folder does make the ordering of things a little off (aesthetically) (especially in the freetype case:)
![order](https://cloud.githubusercontent.com/assets/830748/6072077/36b9a6b6-adf1-11e4-9036-897beb174d1c.png)

(if sorted by name/alphanumerically)

**Comment by danomatika** [comment]
... I think you're getting too deep. It's an end case. There's nothing wrong with creating a license folder just for ferrotype and putting it there, I would just avoid doing that fall *all* libs when the majority have only a single file.

**Comment by danoli3** [comment]
Yeah I just wanted to keep it consistent across them all. 
However I think the split main lib dir single file and license folder is a good solution.

So spec:
For multiple License files use ```license``` folder for a lib I.E. ```freetype/license/*```
For single License file: Use main lib directory I.E. ```freetype/LICENSE.*```

**Comment by danomatika** [comment]
I avoid renaming the files from the original project. I think you're getting too detailed here.

**Comment by danoli3** [comment]
Yeah no renaming just example of location

**Comment by bilderbuchi** [comment]
Really? An extra license folder because the order is not "aesthetic" with more than one file?? Am I reading that right, are you serious? BTW, is this maybe an osx quirk? I'm pretty sure windows and Linux group all the directories together even when ordering alphabetically....

**Comment by bilderbuchi** [comment]
Also, +1 to just dropping the files in the root folder.

**Comment by danoli3** [comment]
Nah it messes up the structure, makes it harder to navigate down to the libs folder.
Windows / Linux and OS X by default group alphanumerically... unless custom sorted by modification date / folders / etc, so this would be an issue by default.

It is just very messy without the **license** folder for the multiple files.
**FreeImage**, **FreeType** and **Cairo** currently have multiple license files.
License folder fixes this and suites the purpose.

However there are many named "COPYING" and this still messes up the default / aesthetic and functional "structure", not to mention the strange ambiguity of some of the license file names.

----------------------------------

#### So new outlook after testing all of the scripts and the structure 
I'm probably still for a pure ```license``` folder in each lib directory. If one and or many files.

#### Reasons for the license folder: 
- Developers at a glance know where the license information is
- Encapsulates ambiguous source license filenames. "readme" "randomlibname" "COPYING" "COPYING.txt" "COPYING.md" "LICENSE" "Lisence.txt"  "LICENSE.txt" "gplv2" "BSD.txt" etc...
- Easier to update and keep track of
- Multiple license files in one location for each lib (if applicable)
- Doesn't mess up structure when navigating into libraries headers or lib folder.

#### Reasons against: 
- Extra folder

**Comment by kylemcdonald** [comment]
this looks like the kind of thing that could go either way. thanks @danoli3 for outline the pros and single con of using an extra folder.

usually small decisions like this are resolved by whoever is doing the work to solve the bigger issue (in this case, @danol3). but because there's some sentiment against his solution, it would be great to have someone from @openframeworks/core chime in to pick one of the two options :) @ofZach @ofTheo @arturoc ?

**Comment by danomatika** [comment]
I still think it's an end case. Just use a license folder if there are tons of licenses & docs, otherwise put the license in the main lib folder. I don't think OF needs the readme for *every* lib, the LICENSE and perhaps a CHANGELOG are sufficient.

As for the copying command, I suggested not adding the name of the file to the designation part of the cp command since this would help avoid problems in the future if you update the name, etc. A small point yes, but it's these kinds of detail which need to be taken care of in a project like Apothecary ...

**Comment by pizthewiz** [comment]
Unless what @danoli3 has proposed is both detrimental to the project and permanent, I am of the opinion that there are a lot of important things to do to get 0.9.0 released and bike shedding this very minor detail is likely distracting from that.

**Comment by danomatika** [comment]
Agreed. However the issue was opened and my 2 cents were asked. Also, this is something we will all be looking at for a long time to come, so getting a clear decision is not a bad idea. In any case, nothing really breaks but could be a "paper cut" to someone in the future.

**Comment by kylemcdonald** [comment]
@pizthewiz makes a really good point: that even though there is not consensus on this, it also has basically no side effects and can be changed easily.

so i'm going to un-summon the core :) and propose that since @danoli3 offered to do the work, he gets to choose the approach.

once something with minor consequences like this is implemented and working, then let's talk later if someone else wants to do the work to change it.

and thanks to everyone for providing their thoughts :)

**Comment by pizthewiz** [comment]
Sorry for being a little sharp earlier - I do agree with some of the concerns raised and don't want to make them feel invalid, but hoped we could separate the immediate issue of needing to include licenses and then continue to discuss and address the finer points in a later pass.

**Comment by danomatika** [comment]
Yeah totally. Just go ahead. I think we covered everything by now :D

**Comment by kylemcdonald** [comment]
closed by #3623
