### ISSUE TITLE
android_configure.sh included in/executed via `apothecary update core`

### ISSUE THREAD

**Issue by notjosh** [openframeworks/openFrameworks#3630]
`apothecary update core` will loop through the contents of `formulas/` and try to execute each of the scripts.

This is made evident because my current env isn't set up for Android, and we're using `set -o nounset`.

```
$ ./apothecary update core
...
/Users/joshua/dev/ext/openFrameworks/scripts/apothecary/formulas/android_configure.sh: line 15: NDK_ROOT: unbound variable
```

Can we move util scripts like this elsewhere (say `_util` to follow the `_depends` convention), and then we can exclude it in a similar way: https://gist.github.com/notjosh/2dc11c184e9e284f35e5#file-apothecary-sh-L474-L476 ?

/cc @arturoc (creator of `android_configure.sh`)

**Comment by arturoc** [comment]
sure, can you send a PR?

**Comment by DomAmato** [comment]
This has been fixed has it not?

**Comment by arturoc** [comment]
yes i moved this to the apothecary root
