### ISSUE TITLE
Break typedef and make ofPoint subclass from ofVec3f?

### ISSUE THREAD

**Issue by corybarr** [openframeworks/openFrameworks#3632]
I just ran into a little issue calculating the angles between two ofPoints. ofPoint is typedefed to ofVec3f, but points and vectors have different semantics. Take, for example, calculating a distance between two points.

Take these two points:

        ofPoint start = ofPoint(0, 0, 0);
        ofPoint end = ofPoint(500, 500, 0);

The angle between them is 45 degrees. However, start.angle(end) is calculating the angle like it's a vector--based on dot product. That means the angle between a point in the upper left corner to any other point will always return an orthogonal 90 degrees. This is only true for vectors. ofPoint objects should calculate angles between them like this:

        ofPoint start = ofPoint(0, 0, 0);
        ofPoint end = ofPoint(500, 500, 0);
	float xDiff = end.x - start.x; 
	float yDiff = end.y - start.y; 
	return (float) atan2(yDiff, xDiff) * RAD_TO_DEG;

Thoughts on breaking the ofPoint typedef, inheriting from ofVec3f, and overriding this method?

**Comment by kylemcdonald** [comment]
#2060 is related

**Comment by corybarr** [comment]
Ah, yes. Let's move the discussion to #2060. Is there a way to fold this issue into that one, or should it just be closed?

**Comment by kylemcdonald** [comment]
if you add a comment similar to / copying what you wrote above, as a suggestion for one way to resolve the discrepancy in the `angle()` method, i think we can close this one. as it is now, this is a different enough suggestion i wouldn't want it to be overlooked.

**Comment by bilderbuchi** [comment]
thanks. closing this.
