### ISSUE TITLE
using multiple ofGLFW windows: white image from ofVideoGrabber

### ISSUE THREAD

**Issue by nylki** [openframeworks/openFrameworks#3636]
In the *master* of OF multiple window creation is natively supported without any addons (see eg. [example](https://github.com/openframeworks/openFrameworks/tree/master/examples/events/multiWindowExample) by @arturoc ) I wanted to convert a project to use the method.

however, calling the `draw()` function of ofVideoGrabber/ofImage results in white rectangles with the dimensions of the grabbed images. I tested if this might be an issue on my side or a general issue but drawing from a webcam in a standard example does still work. The issue remains inside `ofAppGLFWWindow` I suppose. Might this be related to #3514 ?

I setup the camera and update/draw it in both examples (multi window and standard single window) in the following way:

```cpp
void ofApp::setup(){
	cam.setup(640,480);
	int grabW = cam.width;
	int grabH = cam.height;
	printf("asked for 320 by 240 - actual size is %i by %i",
	 	grabW, grabH);
}

//--------------------------------------------------------------
void ofApp::update(){
	cam.update();
}

//--------------------------------------------------------------
void ofApp::draw(){
	ofBackground(111);
	cam.draw(0,0);
}

```

The multi window example's `main.cpp` is:
```cpp
#include "ofMain.h"
#include "ofApp.h"
#include "GuiApp.h"
#include "ofAppGLFWWindow.h"

//========================================================================
int main( ){
	ofGLFWWindowSettings settings;

	settings.width = 600;
	settings.height = 600;
	settings.position.x = 300;
	settings.resizable = true;
	shared_ptr<ofAppBaseWindow> mainWindow = ofCreateWindow(settings);

	settings.width = 300;
	settings.height = 300;
	settings.position.x = 0;
	settings.resizable = false;
	shared_ptr<ofAppBaseWindow> guiWindow = ofCreateWindow(settings);

	shared_ptr<ofApp> mainApp(new ofApp);
	shared_ptr<GuiApp> guiApp(new GuiApp);
	mainApp->gui = guiApp;

	ofRunApp(guiWindow, guiApp);
	ofRunApp(mainWindow, mainApp);
	ofRunMainLoop();

}
```

In the multi window example, this is should of course only draw in the main window, which is does, but as I stated, only a white filled rectangle.

![bildschirmfoto 2015-02-09 um 19 01 17](https://cloud.githubusercontent.com/assets/1710598/6112137/61de2e3a-b08e-11e4-81ef-9f8150905b68.png)

the working example:
![bildschirmfoto 2015-02-09 um 19 02 49](https://cloud.githubusercontent.com/assets/1710598/6112136/61ddd0c0-b08e-11e4-81b7-5574d34bb07e.jpg)

For completeness:
I have seen comparably strange things using the addon [ofxUI](https://github.com/rezaali/ofxUI) with multiple windows. The white blocks should be text:
![bildschirmfoto 2015-02-09 um 19 07 50](https://cloud.githubusercontent.com/assets/1710598/6112282/413e14b4-b08f-11e4-992b-fec3eb40ab8c.png)

I am on OS X 10.8.5, MBP mid 2012, Intel HD4000 and on OF *master*: d66e1962e25f56903639e1dd9715752bb8b9be1d

**Comment by nylki** [comment]
I have seen other strange things using the addon [ofxUI](https://github.com/rezaali/ofxUI) with multiple windows. The white blocks should be text:

![bildschirmfoto 2015-02-09 um 19 07 50](https://cloud.githubusercontent.com/assets/1710598/6112282/413e14b4-b08f-11e4-992b-fec3eb40ab8c.png)

**Comment by bilderbuchi** [comment]
ping @openframeworks/video @openframeworks/2d-3d

**Comment by igiso** [comment]
![screen shot 2015-02-09 at 11 45 08 pm](https://cloud.githubusercontent.com/assets/2058400/6116503/ce3a4a60-b0b5-11e4-9579-784a27076046.png)
this is due to the way we are sharing gl context among windows..

try keeping each assets separate and allocate whatever is meant to be used in one gl context (images videos etc) in that gl context and keep it isolated...

**Comment by nylki** [comment]
@igiso 
I am not sure I understand what the different gl contexts are in that case. I declare the ofVideoGrabber in ofApp.h and initialize it in ofApp.cpp and display it on the main window. Why would the other window affect it in any way? I probably miss some essential understanding here.
What would I need to change in my case; Could you post a code sample how your recommended structure looks like?

Thank you!

**Comment by igiso** [comment]
the short answer to your question is

remove everything, (ofxGui ofImage etc)

just create the two windows.

put ofVideoGrabber in the window is CREATED LAST in main

but …really just don't do this,  wait till we figure out exactly what is going on here..

you might burn your graphics card or something :)


It seems that classes like ofImage , ofVideoGrabber  don't know what GL context is current.. so things go haywire.. 
??

**Comment by igiso** [comment]
creating multiple windows in main is definately what is causing the issue,

if you create 1 window, load all things up, nice and isolated in that context

draw them etc.

then when is all done,

create your 2nd window dynamically 

then you can load whatever you want in there and it will be binded to the correct texture, and everything will be swell

As you can see I've loaded two images and videograbber in two seperate windows.


![screen shot 2015-02-10 at 9 28 36 am](https://cloud.githubusercontent.com/assets/2058400/6123205/f65461dc-b107-11e4-8b6b-88cd3606ce15.png)

**Comment by igiso** [comment]
you can even load all your stuff in main window::setup and then share the context to the sec window and use them (assuming they are external etc)
like:
        settings.shareContextWith = ofGetMainLoop()->getCurrentWindow();

or even better:

        settings.shareContextWith = ofGetMainLoop()->get("main"); //it doesn't exist in master yet

**Comment by nylki** [comment]
@arturoc most things work now, thx!
However, I still get problems with drawing ttf fonts on one of the windows, showing as blocks.

![bildschirmfoto 2015-02-18 um 18 19 25](https://cloud.githubusercontent.com/assets/1710598/6252467/ee2f417c-b79a-11e4-937b-6a9a8a2836f0.png)
this should say: `"Font Example - use keyboard to type"`
Interestingly the `-`renders fine.

**Comment by tgfrerer** [comment]
hi @nylki,

try calling `ofEnableAlphaBlending();` just before you draw your text.

if true type fonts are rendered while alpha blending is off, the blocks are due to the geometry for the fonts being rendered, but the alpha mask for the font not being applied.

**Comment by arturoc** [comment]
alpha blending should be enabled by default and even by the font itself when drawing it i think it's a problem with the texture being loaded in a different context. can you post an example that demos the problem?

**Comment by nylki** [comment]
@arturoc Sure, I'll try to assemble an example tommorow.

**Comment by nylki** [comment]
@arturoc It was a problem on my side, I loaded and setup the font in the wrong setup, not the setup of the window I wanted to draw to. Everything is fine now.
