### ISSUE TITLE
ofParameterGroup does not survive copying

### ISSUE THREAD

**Issue by bangnoise** [openframeworks/openFrameworks#3641]
Copying an ofParameterGroup renders it unusable.

    ofParameterGroup params2;
    {
        ofParameterGroup params1;
        params1.setName("parameters");
        ofParameter<bool> active_param("active", false);
        params1.add(active_param);
        params2 = params1;
    }
    params2["active"].cast<bool>() = true;

Causes a crash on the last line

`#7	0x003ee083 in Poco::MutexImpl::lockImpl() [inlined]
#8	0x003ee01f in Poco::FastMutex::lock() [inlined]
#9	0x003ee01f in Poco::ScopedLockWithUnlock<Poco::FastMutex>::ScopedLockWithUnlock(Poco::FastMutex&) [inlined]
#10	0x003ee01f in Poco::ScopedLockWithUnlock<Poco::FastMutex>::ScopedLockWithUnlock(Poco::FastMutex&) [inlined]
#11	0x003ee01f in Poco::AbstractEvent<ofAbstractParameter, Poco::PriorityStrategy<ofAbstractParameter, Poco::AbstractPriorityDelegate<ofAbstractParameter> >, Poco::AbstractPriorityDelegate<ofAbstractParameter>, Poco::FastMutex>::notify(void const*, ofAbstractParameter&)
#12	0x003eddd3 in void ofNotifyEvent<ofEvent<ofAbstractParameter>, ofAbstractParameter>(ofEvent<ofAbstractParameter>&, ofAbstractParameter&)
#13	0x003edb7d in ofParameterGroup::notifyParameterChanged(ofAbstractParameter&)
#14	0x003ecc0a in ofAbstractParameter::notifyParent()
#15	0x00005b92 in ofParameter<bool>::eventsSetValue(bool)
#16	0x000058a7 in ofParameter<bool>::set(bool)
#17	0x0000486f in ofParameter<bool>::operator=(bool const&)`

Tested with both OF HEAD and 0.8.4, OS X 10.10, Xcode.

This makes it impossible to store an ofParameterGroup in a container, have varying numbers of ofParameterGroup, etc.

**Comment by i-n-g-o** [comment]
we had a look at it today and figured the parents of ofParameter were not correctly set after copying a ofParameterGroup.

this should fix it: https://github.com/openframeworks/openFrameworks/pull/3809

**Comment by bilderbuchi** [comment]
thanks!

**Comment by arturoc** [comment]
there's actually a couple of cases where this will fail, i need to change the parent pointer to a weak_ptr and have the posibility of have several parents. i'm going to reopen the issue to remind myself to fix it

**Comment by arturoc** [comment]
closed via 5b2971a9b2e1cdec715c2338f0a7bddf22bb3188
