### ISSUE TITLE
ofXml removeContents() doesn't

### ISSUE THREAD

**Issue by bangnoise** [openframeworks/openFrameworks#3643]
Where settings.xml is

    <top>
        <next>
            <first_child/>
        </next>
    </top>

The following doesn't behave as expected

    ofXml xml("settings.xml");
    xml.setToChild(0);
    int numChild = xml.getNumChildren();
    xml.removeContents();
    numChild = xml.getNumChildren();
    // numChild == 1

OF HEAD and 0.8.4, OS X 10.10, Xcode

**Comment by joshuajnoble** [comment]
Addressed in https://github.com/openframeworks/openFrameworks/pull/3657
