### ISSUE TITLE
ofVbo.cpp#L330 in branch stable 

### ISSUE THREAD

**Issue by NeKoFu** [openframeworks/openFrameworks#3644]
Look at  https://github.com/openframeworks/openFrameworks/blob/stable/libs/openFrameworks/gl/ofVbo.cpp#L330

Here is the incriminated line:
```
supportVAOs = ofGetGLProgrammableRenderer();// || glewIsSupported("GL_ARB_vertex_array_object"); <- this should work but has false positives on some cards like emulation in vm's
```

This line doesn't affect a boolean value as needed and cause a compilation error in the official stable package 0.8.4.

**Comment by tgfrerer** [comment]
Interesting! Which compiler / operating system are you using?

Some compilers have trouble resolving the implicit cast, that's why I'm asking. It will help pinning down the issue of we know which configurations are affected. 

That said, I looked this morning and couldn't find the line

**Comment by arturoc** [comment]
this was problematic with newer versions of gcc if i'm correct but was fixed a while ago on master. i'm going to close it but feel free to reopen if you can test with master and still have a similar issue

**Comment by NeKoFu** [comment]
I use Visual Studio 2013 - Version 12.0.31101.00 Update 4 on Windows 8.1. This file has evolved in the branch master but the problem is embedded in the package available here:   http://openframeworks.cc/download/.
