### ISSUE TITLE
There seems to be confusion about what ofPixels::size() returns

### ISSUE THREAD

**Issue by hardmanko** [openframeworks/openFrameworks#3647]
In the current master version of the repo there is an error in the version of ofPixels::copyFrom() with complete type signature (in the header):
~~~{.cpp}
template<typename PixelType>
template<typename SrcType>
void ofPixels_<PixelType>::copyFrom(const ofPixels_<SrcType> & mom)
~~~

If the child has a pixel type with fewer bytes per pixel than the mom, an error occurs in this function. This function uses `ofPixels::size()` to control iteration over the contents of both objects while each pixel is copied. The reason for the error is that `ofPixels::size()` returns the number of bytes, whereas `copyFrom()` is written as though `size()` returns `width * height`. As such, the error happens when the iteration goes out of the range of the number of stored pixels.

The documentation for `size()` correctly says what it does, but it seems like `size()` should be changed to return `width * height` for three reasons:

1) As far as I can see, there is no function that returns `width * height`, yet this is a commonly desired thing.
2) There is a function called `getTotalBytes()` that does what `size()` currently does.
3) Other functions of `ofPixels` seem to expect `size()` to return `width * height`.

**Comment by ofTheo** [comment]
Thanks for the issue! 

I think size is currently correct as the total number of pixels * the number of channels. 
getTotalBytes is actually different from that as ofFloatPixels is 4 bytes per pixel channel where as ofPixels is 1 byte. 

It sounds like though there is a bug with the copyFrom as you mention. 
There should be a check and an error if the two ofPixels don't have the same number of channels. 
At this line: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofPixels.cpp#L224

I'm going to close this issue and open one for the copyFrom

**Comment by hardmanko** [comment]
Thanks for your quick response!

There is a mistake in my first post, that I talk about at the end here, but I was right about `getTotalBytes()` and `size()` returning the same value regardless of the pixel type, which you can get from the following snippet:
~~~{.cpp}
	ofFloatPixels fpix_alpha;
	ofFloatPixels fpix;
	ofShortPixels spix_alpha;
	ofShortPixels spix;

	fpix_alpha.allocate(10, 10, ofImageType::OF_IMAGE_COLOR_ALPHA);
	fpix.allocate(10, 10, ofImageType::OF_IMAGE_COLOR);
	spix_alpha.allocate(10, 10, ofImageType::OF_IMAGE_COLOR_ALPHA);
	spix.allocate(10, 10, ofImageType::OF_IMAGE_COLOR);

	cout << fpix_alpha.size() << " " << fpix_alpha.getTotalBytes() << endl <<
		fpix.size() << " " << fpix.getTotalBytes() << endl <<
		spix_alpha.size() << " " << spix_alpha.getTotalBytes() << endl <<
		spix.size() << " " << spix.getTotalBytes() << endl;
~~~
The output I get from this is that size() and getTotalBytes() return the same values in all 4 cases.

Looking at the source, `getTotalBytes()` is defined as
~~~{.cpp}
template<typename PixelType>
int ofPixels_<PixelType>::getTotalBytes() const{
	return bytesFromPixelFormat<PixelType>(width,height,pixelFormat);
}
~~~
and `size()` is trivial, just returning `pixelsSize`, where `pixelsSize` is set to a nonzero value twice, once in `setFromExternalPixels()`
~~~{.cpp}
template<typename PixelType>
void ofPixels_<PixelType>::setFromExternalPixels(PixelType * newPixels,int w, int h, ofPixelFormat _pixelFormat){
	//...

	pixelsSize = bytesFromPixelFormat<PixelType>(w,h,_pixelFormat);

	//...
}
~~~
and again in allocate
~~~{.cpp}
template<typename PixelType>
void ofPixels_<PixelType>::allocate(int w, int h, ofPixelFormat format){
       //...

	int newSize = bytesFromPixelFormat<PixelType>(w,h,format);

	//...

	pixelsSize = newSize;

       //...
}
~~~
In all three cases, `bytesFromPixelFormat()` is used with the same arguments.

It doesn't seem like `getTotalBytes()` is defined incorrectly. For example, for `spix.getTotalBytes()` above, I get 600. That is 10 * 10 * 2 * 3, 2 being the size of unsigned short and 3 being the number of channels.

If found another example where `size()` is used incorrectly for its current value:
~~~{.cpp}
template<typename PixelType>
void ofPixels_<PixelType>::copyFrom(const ofPixels_<PixelType> & mom){
	if(mom.isAllocated()) {
		allocate(mom.getWidth(), mom.getHeight(), mom.getPixelFormat());
		memcpy(pixels, mom.getData(), mom.size() * sizeof(PixelType));
	}
}
~~~
If `size()` already returns the number of bytes, then multiplying it by sizeof(PixelType) means that memcpy is going to copy too many bytes. Here it seems like `size()` is supposed to mean `width * height * channels`. Maybe this is supposed to divide by `sizeof(PixelType)`?

Looking at the `copyFrom()` that I was talking about in my first post, I can now see that I was making a mistake in what I though `size()` should be returning to work properly. I was thinking that ofPixels::operator[] returned some version of `ofColor`, but that was dumb. It returns each component of what might be an `ofColor`, so `size()` should return `width * height * channels` for both versions of `copyFrom()` to work correctly.

In 0.8.4, `size()` is defined as:
~~~{.cpp}
template<typename PixelType>
int ofPixels_<PixelType>::size() const{
	return width*height*channels;
}
~~~

I'm not saying that `size()` has to change, but it seems like there is disagreement about what it does within the code. It makes more sense to me that it should not include the size of the pixel type.

**Comment by arturoc** [comment]
you are correct, size should return the number of channels * w * h. channels is a bit ambiguous in some formats like some yuv variants that's where the confusion comes from. in 0.8.4 size was correctly returning w*h*channels but when refactoring ofPixels to introduce yuv formats i inadvertently changed it to return the number of bytes.

i'm going to reopen this since it seems to be a real issue.

thanks for the complete explanation!
