### ISSUE TITLE
ofPixels copyFrom doesn't check if num channels are the same

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3649]
If you have two ofPixels objects and one has different channels from the other currently it could lead to a crash. 

Solution as an error and don't do the copy here: 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofPixels.cpp#L224

**Comment by arturoc** [comment]
mmh, don't see the error, that allocate should do the right thing and allocate the dst with the same w, h and pìxelFormat than the src

**Comment by arturoc** [comment]
closing this since the original issue is actually the correct one

**Comment by ofTheo** [comment]
@arturoc - yeah sorry - my logic was totally wrong on this.  
closing real issues and creating fake ones :)

**Comment by arturoc** [comment]
:)
