### ISSUE TITLE
Android apps draw upside down

### ISSUE THREAD

**Issue by K0j0** [openframeworks/openFrameworks#3658]
It seems like the Y coordinate is flipped on Android. Here's what the image example looks like.

https://www.dropbox.com/s/bomgo3uh4qr4796/of_image_android_flipped.png?dl=0

I'm not seeing this on desktop or on iOS. I've poked around a bit and have a feeling that this has to do with the vFlipped property in either ofMatrixStack or ofGLRenderer. Not completely sure though.

I have a feeling that this is probably a super simple fix, but I'm not sure where to look. Gonna keep poking around.

**Comment by bilderbuchi** [comment]
pinging @openframeworks/android

**Comment by K0j0** [comment]
Thanks, that really did the trick! Seems like it was a bit more than simple fix.
