### ISSUE TITLE
Android events dont get called

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#3659]
The android specific window functions `resume()`, `reloadtexture()` etc dont get called anymore. I looked into the code, and i can see that  [here](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAndroid/src/ofAppAndroidWindow.cpp#L278) the `androidApp` is no set. And as far as i can see it's never getting set anywhere. 

There was [this](https://github.com/openframeworks/openFrameworks/commit/7f1bab217811989f56e87993bfa6982572f96501#diff-cd0c3e96a6abe657ef1221ba73b8f30f) merge that i'm not really sure what is where the setting of androidApp was removed. As far as i can see this commit got merged in #3397, but its not showing this change here on github. @tallavi @arturoc

**Comment by arturoc** [comment]
oh, didn't realized about this. with the refactoring of the window system i removed methods that pass a reference to an ofApp to the window. now everything works through events but the live cycle functions don't have an associated event yet. we need to create those events and make the app listen to them

**Comment by tallavi** [comment]
How is it related to PR #3397? I fail to see the connection. The only change there is handling jni calls from detached threads.
BTW, could it be somehow connected to issue #3555? Although I think it's an issue before the new window system, and I'm pretty sure I saw the events being called there..

**Comment by HalfdanJ** [comment]
@tallavi i think i got confused by my git log, since your name was on the merge that introduced the code. Not quite sure why that is some weird merging, but it seems like arturoc knows what the problem and solution is.
