### ISSUE TITLE
New bug in 0.9.0 : ofPixels::size() is pre-multiplied by sizeof(PixelType)

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#3663]
As we can see in:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofPixels.cpp#L225

The usage of `ofPixels::size()` has been to refer to width * height * channels

But since 
https://github.com/openframeworks/openFrameworks/commit/de4839df31d9a1a80dceb51a1665dfd533c4433e

`size()` has also been premultiplied by sizeof(PixelType), which obviously breaks a lot of things (e.g. things dealing with 16bit depth data).

suggest either:
* Return to previous usage
* Add both options under different names and add `///` note onto `size()` to explain what it means (esp. since it's now pre-cached it's difficult to dig up the definition).

**Comment by elliotwoods** [comment]
@arturoc - was this an intentional change?

**Comment by arturoc** [comment]
no, not at all. there's a similar issue to this. there's also a getBytesPerPixel and getTotalBytes methods so yeah it doesn't make sense that size also returns that. size should do be as similar as possible to vector.size
