### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by drumanart** [openframeworks/openFrameworks#3666]
Hello 
I get errors installinf OF

No LSB modules are available.
Distributor ID:	Peppermint
Description:	Peppermint Five
Release:	5
Codename:	trusty

The following packages have unmet dependencies:
 freeglut3-dev : Depends: libxt-dev but it is not going to be installed
                 Depends: libxext-dev but it is not going to be installed
 libcairo2-dev : Depends: libx11-dev but it is not going to be installed
                 Depends: libxrender-dev (>= 0.6) but it is not going to be installed
                 Depends: libxcb1-dev (>= 1.6) but it is not going to be installed
                 Depends: libxcb-render0-dev (>= 1.6) but it is not going to be installed
                 Depends: libxcb-shm0-dev but it is not going to be installed
                 Depends: libxext-dev but it is not going to be installed
 libgl1-mesa-dev : Depends: mesa-common-dev (= 10.5.0~git20150204.661c8bb2-0ubuntu0ricotz~trusty)
                   Depends: libx11-dev but it is not going to be installed
                   Depends: libx11-xcb-dev but it is not going to be installed
                   Depends: libxcb-dri3-dev but it is not going to be installed
                   Depends: libxcb-present-dev but it is not going to be installed
                   Depends: libxcb-sync-dev but it is not going to be installed
                   Depends: libxcb-dri2-0-dev but it is not going to be installed
                   Depends: libxcb-glx0-dev but it is not going to be installed
                   Depends: libxdamage-dev but it is not going to be installed
                   Depends: libxext-dev but it is not going to be installed
                   Depends: libxfixes-dev but it is not going to be installed
 libgtk-3-dev : Depends: libgdk-pixbuf2.0-dev (>= 2.27.1) but it is not going to be installed
                Depends: libpango1.0-dev (>= 1.32.4) but it is not going to be installed
                Depends: libx11-dev but it is not going to be installed
                Depends: libxext-dev but it is not going to be installed
                Depends: libxinerama-dev but it is not going to be installed
                Depends: libxi-dev but it is not going to be installed
                Depends: libxrandr-dev but it is not going to be installed
                Depends: libxcursor-dev but it is not going to be installed
                Depends: libxfixes-dev but it is not going to be installed
                Depends: libxcomposite-dev but it is not going to be installed
                Depends: libxdamage-dev but it is not going to be installed
 libxmu-dev : Depends: libxext-dev but it is not going to be installed
              Depends: libxt-dev but it is not going to be installed
              Depends: libxmu-headers (= 2:1.1.1-1) but it is not going to be installed
 libxxf86vm-dev : Depends: libx11-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: 

http://github.com/openframeworks/openFrameworks/issues

Thanks Martin

**Comment by arturoc** [comment]
this seems like some packages are broken in your distribution, try to install them by hand. the only officially supported distributions are debian, ubuntu, fedora and arch linux. anything based on those should work but some times the distribution packagers do changes and break some dependencies which seems to be your case.

i'm going to close this since it's not an issue in OF but feel free to add any comment if you or anyone else find a solution for the issue

**Comment by drumanart** [comment]
I had to downgrade the error packages manually. I did this with aptitude.

Thanks Martin
