### ISSUE TITLE
ofLoadImage() does not initialise a ofImage object.

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3673]
there a few different way of loading an ofImage... like there are skinning a cat.

this works fine,
````
ofImage * image = new ofImage();
bool bLoaded = image->load(filePath);
````

but when doing it this way, image is loaded ok but width, height are 0.
looks like the ofImage object is not initialised.
````
ofImage * image = new ofImage();
bool bLoaded = ofLoadImage(*image, filePath);
````

**Comment by jvcleave** [comment]
sounds like https://github.com/openframeworks/openFrameworks/issues/1663 :)

**Comment by julapy** [comment]
oops my bad, thanks for spotting @jvcleave.
ive moved my comment to the original issue.
closing this one.
