### ISSUE TITLE
ofFbo issues when using multiple windows

### ISSUE THREAD

**Issue by zen-kizu** [openframeworks/openFrameworks#3676]
Yesterday, I switched from the latest official release to the current master branch due to the multi window support, I implemented the approach illustrated in the example multiWindowOneAppExample.
What my program currently does is displaying multiple windows, each one has a dot grid, a red outlined rectangle and a wallpaper I apply some modifications to. Currently, these are:
* resize it to fill the window area
* apply a HSVA shader that lets me modify the HSV+alpha values
* apply a two-pass blur shader
The original wallpaper is stored in an ofImage, the modified result gets drawn into an ofFbo. If I resize the window, the wallpaper is resized, the shaders are re-applied and the result is drawn into the ofFbo.

The grid and the rectangle all are drawn fine, but the wallpaper behaves weird if I use more than one window:
* 2 windows: The first window has a black wallpaper, the second one works as expected. If I close the second window and resize the first one (which refreshes the wallpaper's ofFbo), the wallpaper suddenly gets drawn correctly in the first window.
* 3 windows: Same as above, but the 3rd window does have a wallpaper. But if I resize the window, the wallpaper apparently doesn't get re-drawn because it doesn't get resized accordingly. Now, if I close the second window, the wallpaper in the third window suddenly works again. If I then close that window, the wallpaper in the first window starts working. If I close a window with a non-functioning wallpaper, nothing happens, but if I then close the second window, the wallpaper in the remaining window starts working.
* 4+ windows: Similar to the case above.

I can reproduce these cases all the time.

Here's a short video of the 3-window-case: http://youtu.be/rOE4jaK92E8

**edit:** Log: http://pastebin.com/eHRHwSVk

If I don't draw the wallpaper into an ofFbo but apply the blur shader, the problem persists since the blur shader uses two ofFbos.
if I draw the wallpaper without shaders (i.e. just a simple ofImage.draw(0, 0, windowWidth, windowHeight)), there aren't any problems.

The code I use to create these windows:

	[...]

	ofGLFWWindowSettings windowSettings;
	windowSettings.resizable  = true;
	windowSettings.position.x = 0;
	windowSettings.position.y = 0;
	int i = -1;

	std::shared_ptr<ofAppBaseWindow> mainOFWindow = nullptr;

	for (auto itr = windowList.begin(); itr != windowList.end(); itr++) {
		ofLogNotice("Startup") << "Preparing window \"" << itr->first << "\"";

		windowSettings.width  = settings.get("windows." + itr->first + ".width",  1280);
		windowSettings.height = settings.get("windows." + itr->first + ".height", 720);
		windowSettings.position.x = ++i * 640;

		std::shared_ptr<ofAppBaseWindow> ofWindow = ofCreateWindow(windowSettings);
		ofWindow->setWindowTitle(settings.get<std::string>("windows." + itr->first + ".title", "KiUI"));
		ofWindow->setVerticalSync(false);

		std::shared_ptr<ofGLProgrammableRenderer> renderer = std::make_shared<ofGLProgrammableRenderer>(ofWindow.get());
		renderer->setup(4, 3);
		ofWindow->renderer() = renderer;

		KiWindow& window = kiGetWindow(itr->first);
		window.setOFWindow(ofWindow);

		if (itr->first == "main") {
			ofWindow->setVerticalSync(true);
			mainOFWindow = ofWindow;
		}

		ofAddListener(ofWindow->events().draw,          &window, &KiWindow::draw);
		ofAddListener(ofWindow->events().windowResized, &window, &KiWindow::windowResized);
	}

	if (!mainOFWindow) {
		ofLogFatalError("Startup") << "Mandatory window \"main\" wasn't defined in the window list";
		ofExit();
		return 0;
	}

	//
	//

	ofLogNotice("Startup") << "Starting application";

	ofRunApp(mainOFWindow, std::shared_ptr<ofBaseApp>(&app));
	ofRunMainLoop();

Code to draw the wallpaper into the ofFbo:

	cachedWallpaper.allocate(windowWidth, windowHeight);
	cachedWallpaper.begin();
	{
		ofSetColor(0, 0, 0, 255);
		ofFill();
		ofDrawRectangle(0, 0, windowWidth, windowHeight);

		ofPushMatrix();
		{
			ofTranslate((windowWidth - wallpaperWidth) / 2, (windowHeight - wallpaperHeight) / 2);

			modHSVAShader
				.setShiftH(wallpaperModH)
				.setShiftS(wallpaperModS)
				.setShiftV(wallpaperModV)
				.setShiftA(1)
				.begin();
			blurShader.begin();
			{
				ofSetColor(255, 255, 255, 255);
				wallpaper.draw(0, 0, wallpaperWidth, wallpaperHeight);
			}
			blurShader.end();
			modHSVAShader.end();
		}
		ofPopMatrix();
	}
	cachedWallpaper.end();

My system: Manjaro Linux x64, kernel 3.19; Nvidia GeForce GTX 660, proprietary drivers

**Comment by tgfrerer** [comment]
Hi @zen-kizu, you might be running into concurrency issues. Each window in openFrameworks has its own renderer. And each renderer owns its own OpenGL context. Contexts may share resources. But if you want to share dynamic resources - my suggestion is: think twice. 
* Then read this article: http://blog.gvnott.com/some-usefull-facts-about-multipul-opengl-contexts/.  
* Then this article: http://www.seas.upenn.edu/~pcozzi/OpenGLInsights/OpenGLInsights-AsynchronousBufferTransfers.pdf
* Also, the discussions we had (expand "under outdated diff") here: https://github.com/openframeworks/openFrameworks/pull/3601

You cannot share an FBO over multiple render contexts - you can, however, share it's associated textures, if you are willing to deal with a lot of complexity. 

If you share resources like dynamic textures over mulitple GL contexts you need to make sure that the context writing is finished when the context owning the other window will use it.

As there is no general and performant solution to these problems, as a rule of thumb, oF will not sync these objects for you - and assumes that you know what you do and add sync objects and make sure the contexts are working nicely together yourself.

Here's some more information on OpenGL sync objects: <https://www.opengl.org/wiki/Sync_Object>, and the wizards on OpenGL IRC over on freenode might be able to enlighten you a bit more on these darkest OpenGL arcana =)

**Comment by zen-kizu** [comment]
Thanks a lot for your input! I'm new to coding with OpenGL (I started a few weeks ago) so I still have to learn much about it. :)
