### ISSUE TITLE
ofBuffer.allocate() behaviour is inconsistent with other class functions

### ISSUE THREAD

**Issue by bangnoise** [openframeworks/openFrameworks#3677]
ofBuffer buffer;
    buffer.allocate(10);
    long length = buffer.size();
    // length == 9

ofBuffer (for better or worse) adds one byte to its internal vector size everywhere (?) except in `allocate()`. This means if you use `allocate()` you end up with a buffer which appears to be shorter than requested.

Fixing this will presumably break a lot of user and ofxAddon code that works around it by adding one to the value passed to `allocate()`.

As tracking the extra byte seems to be beyond the codebase, a more robust solution might be to ditch the extra byte entirely and to have functions which treat the buffer as a string check for non-NULL-terminated strings (guaranteeing NULL-termination appears to be the reasoning behind the extra byte).

OF 0.8.4 and git HEAD, all platforms.

**Comment by arturoc** [comment]
yes, allocate should allocate to 10 bytes in that case. i think it's ok to just fix it since most people use ofBuffer to read files... not allocating it directly. the fact that nobody has reported it before kind of proves that :)
