### ISSUE TITLE
Undeclared Macros in <cerrno> in ofxNetwork when compiling with MinGW on windows

### ISSUE THREAD

**Issue by Foaly** [openframeworks/openFrameworks#3680]
Hello everybody!
I have trouble compiling the latest master from github with MinGW on windows. I get errors about undefined macros in `ofxNetworkUtils.h`. The errors all look like this: `error: 'EALREADY' was not declared in this scope`
For a better description of the problem and what I tried to fix it can be found in this [forum post](http://forum.openframeworks.cc/t/undeclared-macros-in-cerrno-in-ofxnetwork-when-compiling-with-mingw-on-windows/18634).
I did a bit of research and the I found the  [breaking commit][1]. In Line 101 the three Macros that throw the error seem to have been forgoten and are not surrounded by an OFXNETWORK_ERROR(...) call. If I do that it fixes this issue.
You can find a gist, with my changes here: https://gist.github.com/Foaly/745087a4c18c36b545d7

Now the problem ist that if I fix this issue, ofxNetwork still doesn't compile, because I get an error in [`ofxTCPManager.cpp L170`][2] because `fcntl()` is used to put the socket in non-/blocking mode and this function is not available on windows.

So would you like me to send seperate pull request for these issues or try to find a solution for both. I haven't looked into the second issue, but it seems to be a bit hackey. Maybe [SFML's TCP Socket][3] can be used as in inspiration.

  [1]: https://github.com/openframeworks/openFrameworks/commit/36c3d24bbf79a6c5b6f95c0df91e10a85f6a90f9#diff-429b04bedd48b04f84713b5ef7efa05eL101
  [2]: https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxNetwork/src/ofxTCPManager.cpp#L170
  [3]: https://github.com/LaurentGomila/SFML/blob/188f7139005b3b3b65038c92685403133c7ecff2/src/SFML/Network/TcpSocket.cpp#L119

**Comment by ofTheo** [comment]
thanks for reporting the issue! 

you could do one PR for both. 

looking around I see a couple of answers which seem to point to cross platform options for making a socket non-blocking: http://stackoverflow.com/a/1544832 and the last post here: http://www.perlmonks.org/?node_id=74258

**Comment by Foaly** [comment]
OK I will try to find some time in the next couple of days to fix these bugs.
Thanks for the links, but I think I misread the lines. It's not about blocking / non-blocking, because there is a [dedicated method](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxNetwork/src/ofxTCPManager.cpp#L197) for that. The problem is related to the timeout code when connecting a socket.

**Comment by procedural** [comment]
Yea, I can't find `fcntl()` too, Visual Studio 2013 fails to compile the addon.

**Comment by procedural** [comment]
Missing `fcntl()` addressed in this PR: https://github.com/openframeworks/openFrameworks/pull/3784
