### ISSUE TITLE
ofPixels rotate90 not working correctly.

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3683]
on the latest master branch (a3b556888769772f336d1dfce845f5727c4fe93b)
`ofPixels::rotate90` is wigging out.

here is the test code,
````
#include "ofApp.h"

ofImage image;

void ofApp::setup(){
    image.load("image.jpg");
    image.rotate90(1);
    
    ofSetWindowShape(image.getWidth(), image.getHeight());
}

void ofApp::draw(){
    image.draw(0, 0);
}
````

no rotation,
![Image](https://dl.dropboxusercontent.com/u/3828359/OF/ofPixels_rotote90_0.jpg)

with 1 rotation,
![Image](https://dl.dropboxusercontent.com/u/3828359/OF/ofPixels_rotote90_1.jpg)

**Comment by i-n-g-o** [comment]
found and fixed:
https://github.com/openframeworks/openFrameworks/pull/3700

**Comment by i-n-g-o** [comment]
ah. just realized @admsyn assigned this to himself. sorry for the mess ;)

**Comment by i-n-g-o** [comment]
the transformation did not take the amount of channels into account, instead only descending one PixelType in the for-loop: --startPixels

simple test:
using a grayscale image works, anything with more than one channel would get messed up.

this PR fixes this by descending the current pixel by the amount of channels in the for loop:
startPixels -= channels;
