### ISSUE TITLE
Infinite ofMap() errors appear when Project Generator is minimized on Windows

### ISSUE THREAD

**Issue by nneonneo** [openframeworks/openFrameworks#3685]
On Windows, if the Project Generator window is minimized, the accompanying console will repeatedly spew the message

    [warning] ofMath: ofMap(): avoiding possible divide by zero, check inputMin and inputMax: 0 0

until the window is restored:

![spew](https://cloud.githubusercontent.com/assets/75449/6420431/05274af0-be94-11e4-96f7-89e5fa88939d.png)

This is probably caused by ofxGui seeing a zero width and height, but I am not certain about that.

**Comment by arturoc** [comment]
we should remove this warning it doesn't make any sense since the function solves the problem but then warns about it

**Comment by danthemellowman** [comment]
or can we just change the Log Level?

I've found that specific warning to be really useful when I forget to set a
variable or discovering some variable I'm passing into ofMap is going to
zero when it shouldn't be.

This is a FEATURE not a BUG

**Comment by nneonneo** [comment]
I think we may just want to make it ofLogDebug or ofLogVerbose. We may also
want to fix the reason for the warning in the first place.

Robert

**Comment by julapy** [comment]
personally i find this message super useful because it tells me that im calculating something wrong, then i just put a break point on the message and i can step back through the stack to see exactly where im making the mistake.

**Comment by danthemellowman** [comment]
so the bug is in the Project not the Core

**Comment by nneonneo** [comment]
I saw this kind of hang prior to adding the parallel-reject check in the
most recent version of the patch.

Please try disabling the parallel build and try it again.

**Comment by bilderbuchi** [comment]
+1 on keeping the warning, and changing the offending calling code

**Comment by bilderbuchi** [comment]
does this only occur with the PG, or other apps, too?

**Comment by ofZach** [comment]
i would guess any of the examples that come with OF that use the gui will have this behvior.  Perhaps there's a simple fix to determine if the window is minimized and not draw the gui.

**Comment by nneonneo** [comment]
This is fixed by https://github.com/ofZach/projectGeneratorSimple/pull/65. It turns out to be a PG bug.
