### ISSUE TITLE
Ubuntu 14.04.2 x64 install_dependencies.sh fails

### ISSUE THREAD

**Issue by napent** [openframeworks/openFrameworks#3687]
Hi, could you help me with this one?
On clean, updated install of Ubuntu desktop i get:

> The following packages have unmet dependencies:
>  libcheese-gtk23 : Depends: libclutter-gtk-1.0-0 (>= 0.91.8) but it is not going to be installed
>                    Depends: libcogl15 (>= 1.15.8) but it is not going to be installed
>  libcheese7 : Depends: libclutter-gst-2.0-0 (>= 0.10.0) but it is not going to be installed
>               Depends: gstreamer1.0-clutter but it is not going to be installed
>  libclutter-1.0-0 : Depends: libcogl-pango15 (>= 1.15.8) but it is not going to be installed
>                     Depends: libcogl15 (>= 1.15.8) but it is not going to be installed

**Comment by napent** [comment]
I've found, that there is a problem with installing freeglut3 package.
My workaround is to install it from synaptic, but first in Synaptic, Edit-->Fix Broken Packages.

**Comment by bilderbuchi** [comment]
so, was this a problem on your end? 
pinging @openframeworks/linux

**Comment by underdoeg** [comment]
A friend had the same problem on his fresh install. But I dont have more info ATM.

**Comment by softwareCxw** [comment]
Problem solved yet, I encountered the same problem. My Email is cxw825873709@gmail.com.  Can you help me ?

**Comment by underdoeg** [comment]
Please post your solutions in here instead of talking them over in private. That way you might help others too...

**Comment by napent** [comment]
Hello. I had this problem "unmet dependencies" on clean install of Ubuntu 12, 14.04 and 14.01 both on real computer as well as virtual box. I have solved this problem installing freeglut3 through synaptic after fixing broken packages as i said earlier.

The next problem i get in to, is that on ubuntu 14.10 instalation of dependencies runs smoothly as well as compiling OF and PG and building examples, but when it comes to running application, it freeze.

**Comment by arturoc** [comment]
> The next problem i get in to, is that on ubuntu 14.10 instalation of dependencies runs smoothly as well as compiling OF and PG and building examples, but when it comes to running application, it freeze.

this is a known bug in ubuntu's unity it won't get solved in 14.10 but it's solved already in 15.04

**Comment by badaf** [comment]
Hi,
I encounter the same issue 
--------------------------------------------------------------
Les paquets suivants contiennent des dépendances non satisfaites :
 unity-control-center : Dépend: libcheese-gtk23 (>= 3.4.0) mais ne sera pas installé
                        Dépend: libcheese7 (>= 3.0.1) mais ne sera pas installé
E: Erreur, pkgProblem::Resolve a généré des ruptures, ce qui a pu être causé par les paquets devant être gardés en l'état.
--------------------------------------------------------------
I tried to install freeglut3 package > same issue... :(

what can I do ?

**Comment by badaf** [comment]
I don't have the time to test forward on my launch break,
but following those steps, install_dependencies runs smoothly...
https://bugs.launchpad.net/ubuntu/+source/fglrx-installer/+bug/1424491/comments/24

**Comment by bilderbuchi** [comment]
@arturoc can we fix this on our end? when Travis switches to 14.04, we'll probably run into this bug?
