### ISSUE TITLE
Can't apt-get update after run OF script on armv6l

### ISSUE THREAD

**Issue by firmread** [openframeworks/openFrameworks#3688]
I'm not so fluent with linux, but it seems like a common problem with pi + OF, somewhere around adding [this](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/debian_armv6l/install_dependencies.sh?L4#L4) to package list. It causes this problem when I call `apt-get update`:

``W: GPG error: http://vontaene.de . Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY  F0DAA5410CC667A3E``

also on [the rPi forum](http://jp.raspberrypi.org/forums/viewtopic.php?f=28&t=87139), the repo owner also discourage adding his repo since quote: "nowadays raspbian already contains all gstreamer/omx packages"

**Comment by bilderbuchi** [comment]
thanks fot he bug report. closing as/closely related to #3669
