### ISSUE TITLE
Gstreamer and android, FreeImage incompatibility with gdkpixbuf

### ISSUE THREAD

**Issue by chuckleplant** [openframeworks/openFrameworks#3690]
*Heads up on a potential issue*

Recently banged my head on this one. When using gstreamer and android, I lost the ability to use `ofImage::loadImage` or any other FreeImage related function. After some debugging magic I discovered it was the [gdkpixbuf plugin](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-plugin-gdkpixbuf.html) plugin that caused this issue.

Leaving this here in case it's useful for somebody. Also, note that I statically linked most gstreamer plugins on startup. It might be that this issue appears only if the gdkpixbuf plugin is loaded, so it might never happen if your pipelines don't require that specific pipe.

**Comment by bilderbuchi** [comment]
ping @openframeworks/android @openframeworks/video

**Comment by bilderbuchi** [comment]
@chuckleplant is this still an issue with latest master?

**Comment by chuckleplant** [comment]
I'm afraid I no longer have access to the project that showed this. I'd say it's safe to assume it's no longer an issue. I used gstreamer as an external static library manually picking the gstreamer modules, which is not the usual way to use it. 

However there is a slight possibility that someone bumps into this again in the far future. I'll close it and leave it buried in the issue tracker so that someone can hopefully find this.
