### ISSUE TITLE
Can't pass ofVecXf parameters to ofNoise and ofSignedNoise functions.

### ISSUE THREAD

**Issue by andreasmuller** [openframeworks/openFrameworks#3695]
I find myself writing code like ofNoise( p.x, p.y, p.z ) a lot and this would be great syntactic sugar. 

https://github.com/andreasmuller/openFrameworks/commit/8960c38217b9bfc717f770e8327e7a27b980c2dd

**Comment by admsyn** [comment]
+1

**Comment by arturoc** [comment]
yeah can you send a PR?

**Comment by andreasmuller** [comment]
Sure thing, here goes.

https://github.com/openframeworks/openFrameworks/pull/3699
