### ISSUE TITLE
0.8.4 dependent on python2.6 python-argparse ==>> Jassie flavored Rasbian PRi2

### ISSUE THREAD

**Issue by laboratories** [openframeworks/openFrameworks#3703]
I might be jumping the gun here

but I got kinda crazy
After having a perfect flawless install of 0.8.4 on RPi2 (Wheezy)
following ->    http://forum.openframeworks.cc/t/raspberry-pi-2-setup-guide/18690/23

I thought I'd push my luck
and updated (successfully!) to the Jessie branch of Rasbian
and tried the install again

sadly I got

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-argparse : Depends: python2.6 but it is not installable
E: Unable to correct problems, you have held broken packages.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues
```

which seems kinda minor really
but I wanted to alert you as Jessie on Rasbian is working really well
and the world must move forward...

thanks in advance

g

**Comment by bilderbuchi** [comment]
pinging @openframeworks/linuxarm 
off the top of my hat, could this be a package dependency problem? iirc, argparse became part of the python standard library, and so that package should not be needed anymore on py2.7+. probably a little test in the install script should solve this.

**Comment by misteralex** [comment]
Remove the package <python-argparse> from installation script <linux/debian/install_dependencies.sh> to build properly of_v0.8.4 under Debian Jessie release  (not required for Debian Wheezy or Ubuntu 14.04). XDAQ @ www.embeddedrevolution.info

**Comment by jvcleave** [comment]
Dependency was removed for 0.9.0 so closing
