### ISSUE TITLE
Make loadAsync() in AVFoundationPlayer run without close() before.

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3704]
First: The loadAsync function is really a great improvement for background loading of clips. 

But repeated loading of movies without a movie.close() before does not work. As a workaround, you can of course always call .close() on the video player object before .loadAsync() again. But close() is quite slow, on my MBP about 50ms.

Like this, the loadAsync() functions looses a lot of it's intended functionality.

**Comment by julapy** [comment]
ok thats interesting.
so does calling `close()` usually take that long regardless if you have loaded the video sync or async?
or does it take longer to close when loading async only?

any thoughts on how this could be improved?

also pinging @HalfdanJ who added the async loading code.

**Comment by urshofer** [comment]
I'll provide some tests tomorrow. I'm quite new to the AVFoundation Framework, coming more from the gStreamer-Side so please excuse my not so accurate descriptions...

Back in the days when the AVFoundationPlayer was still an addon, it was possible to call load without close before. Although load was slower than loadAsync now, the whole process was a little bit faster without the necessity of close(). By then, I did some tests with removing the init function from the load function if the player was already loaded, which was the fastest solution but crashed after a while.


Am 11.03.2015 um 03:08 schrieb lukasz karluk <notifications@github.com>:

**Comment by urshofer** [comment]
okay, i did some tests. the function which is responsible for loading is here:


    void ofxGaplessVideoPlayer::_appendMovie(string _name)
    {
        int actionTimeout = ofGetElapsedTimeMillis();
        video.close();
        actionTimeout = ofGetElapsedTimeMillis() - actionTimeout;

        int loadTime = ofGetElapsedTimeMillis();
        video.loadAsync(_name);
        loadTime = ofGetElapsedTimeMillis() - loadTime;

        ofLogError() << "Loading: " << loadTime << "ms Closing: " << actionTimeout << "ms";
    }

Which results in this output:

__2015-03-12 14:16:40.969 AC PlayerDebug[26841:890f] video loaded at 640 x 358
[ error ] Loading: 1ms Closing: 124ms__

Closing is between 50 and 130ms.

Tests proved that changing to __.load()__ instead of __.loadAsync()__ has no influence on the closing time.

**Comment by arturoc** [comment]
not sure how this work on av foundation but on gstreamer once the player is running you have the option to change the file it's playing back, live, without shutting down the pipeline completely. there might be a similar option here that doesn't involve recreating the whole thing again every time you call load on an already running object

**Comment by urshofer** [comment]
Probably an interesting approach would be to use AVQueuePlayer instead of AVPlayer and change the load code to something like: If the player is already initialized, just append a clip to the queue and jump to the next item. This would skip all the closing and re-initializing…

Something similar pointed out here:

http://stackoverflow.com/a/14304007

**Comment by urshofer** [comment]
I just saw that the `[self.assetReader cancelReading];`in `(void)unloadVideo` takes around 50ms alone. So i did some tests adding a function (only as a test, w/o error handling) which is only changing the asset without cleaning up and redoing everything:

    - (BOOL)updateURL:(NSURL*)url async:(BOOL)bAsync {
      duration = [self.asset duration];
      [self createAssetReaderWithTimeRange:CMTimeRangeMake(kCMTimeZero, duration)];
      self.playerItem = [AVPlayerItem playerItemWithURL:url];
      [self.player replaceCurrentItemWithPlayerItem:self.playerItem];
      return true;
    }

this function is called from `bool ofAVFoundationPlayer::loadPlayer(string name, bool bAsync)`if the player has already been used before:

    if ([videoPlayer isReady]) {
      bLoaded = [videoPlayer updateURL:url async:bAsync];
    }
    else {
      bLoaded = [videoPlayer loadWithURL:url async:bAsync];
    }

The positive thing: `loadMovie()` works like this without an explicit `close()` before. The negative side effect: calls to `update()`now sometime hang for around 10 to 30ms if there's a loading action ongoing. Still: I'm not really into AVFoundation…

**Comment by urshofer** [comment]
I kind of hacked the proposed solution into the source in my fork (https://github.com/urshofer/openFrameworks/tree/master/libs/openFrameworks/video) - not sure if this works well in all circumstances. And as I mentioned already: Re-Loading works, but `update()` now hangs for a little while…

**Comment by urshofer** [comment]
bad news: my tests crash after a (longer) duration, at least on one of my mac minis. it's probably not a really good proposition. probably better would be to switch to the AVQueuePlayer or do the closing and reopening in a background task, similar to load async.

**Comment by urshofer** [comment]
For my own application I made smaller changes to AVFoundationPlayer. It's in the [patches](https://github.com/urshofer/automatic-cinema-playback/tree/master/patches) subdirectory of my Automatic Cinema project. I'm now calling `close()` always before loading, which makes it compatible to other players which work without an explicit `close()` before repetitive `load()` calls.

- More infos: [Automatic Cinema](http://automatic-cinema.com)

**Comment by i-n-g-o** [comment]
looking at the implementatio of ofxThreadedVideoPlayer, a garbage-collection thread is used to dispose a AVFVideoPlayer (and its assetreader).

this might be a way:
- when opening a new file, put the current ofAVFoundationVideoPlayer on a different (garbage)-thread and let use as much time as it needs to clean up
- create a new ofAVFoundationVideoPlayer for the new file...
(i will try that out at report back...)

**Comment by i-n-g-o** [comment]
okay, this seems to work fine. no issues reloading files without prior closing.
well, every time a movie gets loaded, a new ofAVFoundationVideoPlayer is created.
loading therefore is fast.
PR coming up - need to figure something out before...

**Comment by urshofer** [comment]
cool - I'll test it. quick closing is necessary for quick opening in repetitive situations.

**Comment by i-n-g-o** [comment]
the implementation takes no care about which file will get loaded. AVFoundation does some caching though. loading a file the first time takes longer, other times the same file loads faster.
it could be an improvement to check if the same file should get loaded and reset the internal assetReader in that case.

**Comment by urshofer** [comment]
so far it runs well and supersmooth. I got a player over here which is preloading a clip in a second player and switching the players to achieve gapless playback, triggered over the network. This means a lot of stress for the video framework:

![bildschirmfoto 2015-03-25 um 10 59 13](https://cloud.githubusercontent.com/assets/116976/6822309/0a87cefc-d2df-11e4-960f-0b9d8500b3f2.png)

What I can see after a quick look at the output of `lsof` is that file handles are left open. Probably assetreader needs to be closed differently if the the player object is thrown a way instead of reused. In my case this will produce a runtime problem since I got a constantly changing pool of small clips.

**Comment by urshofer** [comment]
Due to the fact that `loadAsync()` runs super quick with @i-n-g-o 's modification, a proper callback system for onLoad-Events (excuse the javascriptness) would be totally useful (see https://github.com/openframeworks/openFrameworks/issues/3721)

**Comment by i-n-g-o** [comment]
interesting.
can you drop a debug output in your `[ofAVFoundationVideoPlayer dealloc]` to verify it is getting called?
there is an issue with this pointed out here: https://github.com/openframeworks/openFrameworks/pull/3672

**Comment by urshofer** [comment]
I already did and interestingly `[ofAVFoundationVideoPlayer dealloc]` is indeed called.

**Comment by i-n-g-o** [comment]
ok. this is expected.
mentioned issue just appears if your update the player internally (if bWillBeUpdatedExternally is set to false)
so, we need to find the reason for mentioned left open filehandles

**Comment by urshofer** [comment]
I recall having the same problem with open file handles when I was working on a threaded player running the AVFoundationPlayer in a non-textured [background thread](https://github.com/urshofer/ofxGaplessVideo/blob/master/src/threadedPlayer.h).

Point was, that autorelease worked only in the main thread, so I had to include a NSAutoreleasePool. See here: https://github.com/openframeworks/openFrameworks/issues/3729

**Comment by i-n-g-o** [comment]
ok. with that GC in place, we put the player onto a different thread... not sure if we should use that NSAutoreleasePool construction then. it might be we create the player on the mainthread, so no autoreleasepool would get created if we do it like in #3729.

maybe better then to create and run the videoplayer in a thread and destroy it in the same. then we can install an autoreleasePool on that thread.

**Comment by urshofer** [comment]
The player probably needs to run in the main thread, otherwise texturing does not work properly.

**Comment by i-n-g-o** [comment]
ok fixed it in my branch.
needed an autoreleasepool in the garbagecollector.
no file stays open after disposing a videoplayer

**Comment by urshofer** [comment]
I just implemented your fix into my application and I can confirm:
- that the handles are closed
- additionally, according to Instruments a small memory leak is also gone with this fix (probably closing https://github.com/openframeworks/openFrameworks/issues/3715)

I'm now long-term testing the player, but it looks very promising. How about a PR to incorporate it into master?

**Comment by i-n-g-o** [comment]
i was thinking to merge https://github.com/openframeworks/openFrameworks/pull/3672 and https://github.com/openframeworks/openFrameworks/pull/3670 into the branch and propose all of it as one PR.

**Comment by admsyn** [comment]
Thanks for the work and please do send a PR!

**Comment by i-n-g-o** [comment]
ok. here it is: https://github.com/openframeworks/openFrameworks/pull/3736

**Comment by urshofer** [comment]
closed with PR https://github.com/openframeworks/openFrameworks/pull/3736
