### ISSUE TITLE
ofEvents() null pointer

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#3705]
So I just found a bug when trying to add a listener in the constructor of a class and having a global static
instance of it. This only happens with the new ofMainLoop class;
test code:
ofApp.h
````
#pragma once

#include "ofMain.h"
class test{
public:
	test(){
		ofAddListener(ofEvents().update, this, &test::onUpdate);
	}
	~test(){
		ofRemoveListener(ofEvents().update, this, &test::onUpdate);
	}
	void onUpdate(ofEventArgs & a){
		cout << "x" <<endl;
	}
};

class ofApp : public ofBaseApp{
	public:
	void setup(){}
	void update(){}
	void draw(){}
};
````
ofApp.cpp
````
#include "ofApp.h"
static test t;
````
as the static instance constructor gets called before creating the mainLoop, calling ofEvents() points to a null pointer;
in ofAppRunner.cpp
changing this
`static shared_ptr<ofMainLoop> mainLoop;`
to
`static shared_ptr<ofMainLoop> mainLoop = shared_ptr<ofMainLoop>(new ofMainLoop);`
didn't help.

I found out this trying to use an addon by sotoruhiga. Even tough this happens in a very specific situation, that could be avoided, it might also break a lot of stuff.
I'm not sure how to fix it, much more I don't know if it really is important but I had to point it out since I found it.
Best!

**Comment by arturoc** [comment]
that should fix it. in any case using a static variable like that with complex calls in the constructor and destructor is going to be problematic at some point. the best way to do it is to have a function that returns it as a singleton like:

```
test & t(){
    static test * t = new test;
    return *t;
}
```

**Comment by danthemellowman** [comment]
I think this commit opened up #3706
