### ISSUE TITLE
Source code for GLFW3

### ISSUE THREAD

**Issue by sammck** [openframeworks/openFrameworks#3709]
openFrameworks is using a modified version of glfw3. The binary libraries are committed into git, but the source code is missing. The nearest I can find is at https://github.com/arturoc/glfw/tree/feature-keysUnicode. But this branch is incomplete, the source code there for https://github.com/arturoc/glfw/blob/feature-keysUnicode/src/x11_window.c clearly won't even compile, as there are symbols defined in one block that are used in another. Do you have a branch somewhere that contains the actual source used to build your version of libglfw3? I would like to rebuild with different compile options.

**Comment by arturoc** [comment]
that branch is the one we are currently using, the current binaries are compiled from there. which error do you get when compiling?

**Comment by sammck** [comment]
Thanks for responding...

In function processEvent(), line 981, symbol 'character' is undefined. That variable is defined on line 902, but that is in a different block and is out of scope.  Also, the function translateChar() is not defined anywhere, although it looks as if it is intended to be a static function defined in the same file.

Am I missing a push or something?

**Comment by arturoc** [comment]
@igiso did you checked this on linux? it seems your merge with glfw 3.1 has broken it, i'm testing in my computer and also getting this errors

**Comment by arturoc** [comment]
this should be fixed now with https://github.com/arturoc/glfw/pull/3

**Comment by sammck** [comment]
Excellent, thank you, Arturo.

**Comment by pospears** [comment]
Hi arturoc,  
Would it be possible to provide a release tag for glfw3 dated 9/9/2014?  I am attempting to rebuild the modified version of glfw3 but recieve glfwSetKeyCallback errors on OSX 10.10
