### ISSUE TITLE
AVFoundationPlayer: Repetitive calls to movie.load() and movie.close() is leaking memory in OSX 10.9

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3715]
I'm encountering a strange memory effect when calling `load()`or `loadAsync()` and `close()` repeatedly:

On my MBP with 10.8.5 an application with the commands mentioned above runs w/o leaking memory for days. On a Mac Mini with 10.9.5 the application is leaking memory. It does not depend with which SDK (i've tested 10.9 and 10.10) the Application has been compiled. According to Xcode Instruments, the leak happens in MediaToolbox and AudioToolbox is constantly allocating more and more memory.

The problem is probably apple related, but I actually don't know really. I'm just posting this because it could be crucial for long running video installations.

![bildschirmfoto 2015-03-16 um 10 11 20](https://cloud.githubusercontent.com/assets/116976/6663567/34175f94-cbc8-11e4-993c-5767d0a45c2d.png)

**Comment by urshofer** [comment]
Update: Just updated the system to 10.10 - looks like the leaking is gone. Probably 10.9 includes a buggy AVFoundation implementation?

![bildschirmfoto 2015-03-16 um 14 26 35](https://cloud.githubusercontent.com/assets/116976/6666898/b0b9bbc6-cbe8-11e4-9a19-f144329c4198.png)

**Comment by bilderbuchi** [comment]
ping @openframeworks/macos

**Comment by admsyn** [comment]
Yeah that's a reasonable conclusion, going to close this.

**Comment by bakercp** [comment]
So, is there any suggested way around this issue?  We've been having loads of trouble with the master branch AVFoundation player when running our app [https://github.com/kibio/kibio] (compiled on 10.10) on 10.8 / 10.9 @brannondorsey ...

**Comment by admsyn** [comment]
This issue specifically or loads of trouble with the AVFoundation player in general? Judging from the output in Instruments, the leaks are just 4KB every reload which doesn't seem like it'd actually cause issues in practice.

Is there an issue on your repo with more info about the trouble you're running into? Couldn't find one with a quick scan.

**Comment by urshofer** [comment]
The leaks were not big, but after a night the memory consumption raised from 40mb at start to 520mb. I'm working with network triggered fragments of really short videos, from 1 up to 5 seconds. So there are plenty of load and unload calls. Not an ideal situation for a permanent installation.

To sum up the troubles I've encountered so far: 
- Memory leaking in 10.9, backwards playback issues [3629](https://github.com/openframeworks/openFrameworks/issues/3629). 
- No playback after repeated load calls without close (on 10.8 and 10.9) [3704](https://github.com/openframeworks/openFrameworks/issues/3704). This looks kind of fixed in Yosemite, but the player crashes after a certain while. 
- Furthermore, I'm not sure if the AVFoundation Player works in non-textured mode.

It would be nice to have gStreamer on all platforms :)

**Comment by i-n-g-o** [comment]
the leak is very likely to be related to this: https://github.com/openframeworks/openFrameworks/pull/3672

**Comment by i-n-g-o** [comment]
imho it would be good to keep this issue open as long as it holds true for any os-version...

**Comment by admsyn** [comment]
Apologies, my reading of the issue was "it's an apple bug" but I see I may have been mistaken :)

**Comment by i-n-g-o** [comment]
might be fixed by this PR: https://github.com/openframeworks/openFrameworks/pull/3736

**Comment by urshofer** [comment]
closed this with PR https://github.com/openframeworks/openFrameworks/pull/3736
