### ISSUE TITLE
ofGstUtils.h compile error (on OSX)

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3717]
Hi,
I got a small compilation issue in ofGstUtils.h (line 215)

changing 

	queue<shared_ptr<GstSample>> bufferQueue;

to

	queue<shared_ptr<GstSample> > bufferQueue;

fixed it.

(space between >>).

**Comment by bilderbuchi** [comment]
what was the compilation issue/error message? OS version? Is this with XCode?

**Comment by urshofer** [comment]
Yes - OSX 10.8.5, Xcode 5.1.1. The error of course only shows up if openFrameworks is compiled 
with Gstreamer, for example including Arturo's ofxGstreamer addon. I'v posted it here because the
file resides in OF.

Error Message: 

A space is required between consecutive right angle brackets (use '> >')



Am 17.03.2015 um 17:45 schrieb Christoph Buchner <notifications@github.com>:

**Comment by arturoc** [comment]
yes this is because the >> is not supported in pre c++11, can you send a PR?

**Comment by arturoc** [comment]
actually no worries, just fixed it :)

**Comment by Weedliam** [comment]
Hi, I actually have this error trying to compile for openFrameworks the "ofxGuiExtended" with an OS X 10.11.1 and Xcode 7.1.1, please tell me if Im missing something, or if is a problem on some C++ library
