### ISSUE TITLE
ofFmodSoundPlayer::unload() leaving file handles open after load() set to stream=true

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3720]
Hello -

I'm running a threaded sound player with 5 players, cycling and loading mp3's. Everything is running fine, but after a stress test with multiple consecutive `load(file, true)` the application crashed with too many files handles open. A quick look at:

    void ofFmodSoundPlayer::unload(){
    	if (bLoadedOk){
    		stop();						// try to stop the sound
    		if(!isStreaming) FMOD_Sound_Release(sound);
    		bLoadedOk = false;
    	}
    }

shows, that FMOD_Sound_Release will never be called if a sound file is loaded with the `stream=true` option. This leads to more and more open file descriptors (list is growing with every load):

    ei-liebi-3:~ urshofer$ lsof -p 14062 | grep .mp3
    AC\x20Pla 14062 urshofer   10r     REG                1,2    837245 26236305 /Users/urshofer/Documents/Work/Repositories/automatic-cinema-playback/openframeworks/apps/myApps/ACP_osx/bin/AC Player.app/Contents/Resources/data/movies/f40827ffe86740a2b89377e90b39eb1a.mp3
    AC\x20Pla 14062 urshofer   11r     REG                1,2    399568 26236306 /Users/urshofer/Documents/Work/Repositories/automatic-cinema-playback/openframeworks/apps/myApps/ACP_osx/bin/AC Player.app/Contents/Resources/data/movies/8806c4ad4f6262e00b50fd86f383a484.mp3
    AC\x20Pla 14062 urshofer   14r     REG                1,2    236146 26236319 /Users/urshofer/Documents/Work/Repositories/automatic-cinema-playback/openframeworks/apps/myApps/ACP_osx/bin/AC Player.app/Contents/Resources/data/movies/710b0cfb8bab575958fa583da8676ca3.mp3
    AC\x20Pla 14062 urshofer   19r     REG                1,2    236146 26236319 /Users/urshofer/Documents/Work/Repositories/automatic-cinema-playback/openframeworks/apps/myApps/ACP_osx/bin/AC Player.app/Contents/Resources/data/movies/710b0cfb8bab575958fa583da8676ca3.mp3
    AC\x20Pla 14062 urshofer   24r     REG                1,2    117027 26236321 /Users/urshofer/Documents/Work/Repositories/automatic-cinema-playback/openframeworks/apps/myApps/ACP_osx/bin/AC Player.app/Contents/Resources/data/movies/869f9d8debbaf183415eef15451da7ba.mp3

I'd really like to load the files in a streaming manner since they can be quite large. A quick fix like this solved the problem for me:

    void ofFmodSoundPlayer::unload(){
    	if (bLoadedOk){
    		stop();						// try to stop the sound
    		FMOD_Sound_Release(sound);
    		bLoadedOk = false;
    	}
    }

(Could probably be pushed into master)

**Comment by urshofer** [comment]
Probably pinging @admsyn on that?

**Comment by admsyn** [comment]
Yeah that looks like a pretty clear leak. I don't know really know much about the FMOD API (didn't write  this player), but that looks like the sort of code that was written to get around some crash, perhaps only visible on a platform other than yours?

In any case, yes that's a bug. Maybe migrating the player over to the C++ API at least is in order for the medium-near future. Seems like a bug that some basic RAII would fix.

The FMOD player's real old, it really needs some love to get it up to speed with the rest of OF in 2015. One of [the longest standing bugs in OF](https://github.com/openframeworks/openFrameworks/issues/167) is to drop FMOD, but realistically it looks like we're stuck with it for a bit.

There's an @openframeworks/sound to ping on sound issues, though it is just me at the moment I think :)

**Comment by bilderbuchi** [comment]
maybe @ofTheo knows about this, he was the one who first committed this code, [afaict](https://github.com/openframeworks/openFrameworks/commit/2b9c52ad147ddd284f8e719951b98f9c4a953227#diff-c3f2d4135282653faaa05042297b4419).

**Comment by ofTheo** [comment]
@urshofer thanks for this issue.
when you removed the streaming check did the file handle list match what you would expect?

if so this could def be merged in via PR.

**Comment by urshofer** [comment]
@ofTheo - I can confirm this. I have 5 players in a loop which had 5 file handles open constantly while running for hours.
With the check, the handle list was growing over time.


Am 19.03.2015 um 23:18 schrieb Theodore Watson <notifications@github.com>:
