### ISSUE TITLE
ofNode setParent maintaining global position doesn't work as expected

### ISSUE THREAD

**Issue by chuckleplant** [openframeworks/openFrameworks#3722]
Both :
```
ofNode::setParent( p, true );
ofNode::setParent( p, false );
```
do the same. When `bMaintainGlobalTransform == true` we should compute the future transform the child will have and then set it. Right [now](https://github.com/openframeworks/openFrameworks/blob/31d24eac22f817534c2a9c17d6fe3b6d01957a70/libs/openFrameworks/3d/ofNode.cpp#L20) the transform is reevaluated from the new parent, hence modifying the global transform. 

Here's what I think it should be:

```
if(bMaintainGlobalTransform) {
    ofMatrix4x4 postParentGlobalTransform = parent.getGlobalTransformMatrix().getInverse() * getGlobalTransformMatrix();
    this->parent = &parent;
    setTransformMatrix(postParentGlobalTransform);
} else {
    this->parent = &parent;
}
```

[PR](https://github.com/openframeworks/openFrameworks/pull/3723) sent!

**Comment by bilderbuchi** [comment]
pinging @openframeworks/2d-3d

**Comment by chuckleplant** [comment]
fix-proposed ! PR [here](https://github.com/openframeworks/openFrameworks/pull/3723)

**Comment by procedural** [comment]
@chuckleplant and you've closed your PR because ... ? :)

**Comment by chuckleplant** [comment]
The multiplication was flipped :sweat_smile:

**Comment by bilderbuchi** [comment]
so, are you saying this isssue should be closed?

**Comment by chuckleplant** [comment]
No, I'll re-PR in a few minutes.
