### ISSUE TITLE
ofFbo doesn't work with glesVersion = OFXIOS_RENDERER_ES2

### ISSUE THREAD

**Issue by dorald** [openframeworks/openFrameworks#3724]
Hi, I'm using @danoli3 repository https://github.com/danoli3/openFrameworks/tree/Apothecary/0.9.0-All .
FBO doesn't work when I change glesVersion to renderer es2. No errors or warnings, just doesn't draw fbo.

**Comment by danoli3** [comment]
Oh I see. I'll update its core to master in the hope it has been fixed
there. Else this may be a master issue as well.

**Comment by dorald** [comment]
Thank you @danoli3 . I have not tested the master version because there is a errors in ofxOpenALSoundPlayer class when i try to build iPhone+OF Library.

**Comment by danoli3** [comment]
@dorald The ofxOpenALSoundPlayer class was fixed on master just now. 
I'll try this out before we do the big merge

**Comment by danoli3** [comment]
Confirmed Master Fixed this for Pre 0.9.0 Libraries ( so definitely has been fixed in the past couple of months)

Also working on latest 0.9.0 as well for safety.
