### ISSUE TITLE
[bug] missing mouse cursor on running window - MAC

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/openFrameworks#3725]
when starting a window built in Xcode/mac, it does not always show the cursor, it just disappears. you have to move it around quite a bit before it comes back, but also goes right away again

**Comment by bakercp** [comment]
This is a known GLFW issue and is fixed upstream. To fix it in master, compile a new GLFW with apothecary.

**Comment by lewislepton** [comment]
cool spot. its not so much fully needed right now. but was sure i did find a fix to get it working, as in going to the source file and changing a line or 2, though cant remember or find it.

if you know of it, could you post it please ;)

thanks again

**Comment by bakercp** [comment]
Duplicates:
https://github.com/openframeworks/openFrameworks/issues/3267
https://github.com/openframeworks/openFrameworks/issues/3363
https://github.com/openframeworks/openFrameworks/issues/3107 
https://github.com/openframeworks/openFrameworks/issues/3100 
https://github.com/openframeworks/openFrameworks/issues/3052

Currently active discussion is here: https://github.com/openframeworks/openFrameworks/issues/3052
