### ISSUE TITLE
[request] change ofSoundGetSpectrum to ofGetSoundSpectrum

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/openFrameworks#3726]
to keep on track with how openframeworks deals in wording things. i feel ofSoundGetSpectrum should be changed to ofGetSoundSpectrum

**Comment by admsyn** [comment]
That naming style is a little out of place, but it's also the same as the rest of the related global sound functions (ofSoundUpdate(), ofSoundSetVolume() etc). At the moment, the ofGetWhatever() style is being phased out in favour of static methods on classes (if global methods are needed at all). In the case of this method in particular, I think it'd make sense to move it to something like `ofSoundPlayer::getSpectrum()`, though its existence as a free-standing global function is still pretty weird.

**Comment by lewislepton** [comment]
fair enough. thanks for clearing up ;)
