### ISSUE TITLE
Scroll up on ofxIntSlider doesn't work (ofxGui)

### ISSUE THREAD

**Issue by elaye** [openframeworks/openFrameworks#3728]
When scrolling up on a `ofxIntSlider` the value doesn't increase whereas it decreases when scrolling down. However it works well with an `ofxFloatSlider`.

I think the problem comes from the method `bool ofxSlider<Type>::mouseScrolled(ofMouseEventArgs & args)` (line 106) in `ofxSlider.cpp`:

	template<typename Type>
	bool ofxSlider<Type>::mouseScrolled(ofMouseEventArgs & args){
		if(mouseInside){
			if(args.y>0 || args.y<0){
				double range = value.getMax() - value.getMin();
				range /= b.width*4;
				Type newValue = value + ofMap(args.y,-1,1,-range, range);
				newValue = ofClamp(newValue,value.getMin(),value.getMax());
				value = newValue;
			}
			return true;
		}else{
			return false;
		}
	}

If `range < b.width*4` then range will be `< 1` after dividing  and then `ofMap(args.y,-1,1,-range, range)` will be `< 1` too. So if `Type` is an `int` it will be truncated.

**Comment by arturoc** [comment]
we should probably specialize this and make the minimum increment 1 for ints
