### ISSUE TITLE
AVFoundationPlayer: Problems if not run in the main thread

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3729]
I just encountered huge memory leaks and problems if AVFoundationPlayer is not run in the main thread. To avoid this I've added an autorelease pool to `init()`in ofAVFoundationVideoPlayer.m:

    if (![NSThread isMainThread]) {
      pool = [[NSAutoreleasePool alloc] init];
    }

and in `dealloc()`:

    if ([NSThread isMainThread]) {
      [super dealloc];
    }
    else {
      [pool drain];
    }

As far as i can see the memory usage is now quite steady. I'm really not into AVFoundation but autorelease w/o pool is only flushed in the main thread, isn't it?
Added a gist here: https://gist.github.com/urshofer/a8e36889dcf55c558bbc

Best,
Urs

**Comment by pizthewiz** [comment]
Only the main `NSThread

**Comment by pizthewiz** [comment]
The thread creator is responsible for putting a pool in place on secondary threads. Generally, the pool should be hoisted into the thread execution wrapping all operations, not intermixed in a particular object use:

```Objective-C
- (void)viewDidLoad {
    self.thread = [[NSSthread alloc] initWithTarget:self selector:@selector(runner:) object:nil];
    [self.thread start];
}

- (void)runner:(id)object {
    @autoreleasepool {
        // do stuff here 👍
     }
}
```

**Comment by pizthewiz** [comment]
It should be noted though that not all Cocoa/Cocoa Touch classes support execution on secondary threads, some require active runloops and what not.

**Comment by urshofer** [comment]
Yes - execution on secondary threads is only meant for background tasks. Not only cocoa stuff probably does not run, also openGL textures.

**Comment by i-n-g-o** [comment]
does this PR https://github.com/openframeworks/openFrameworks/pull/3736 solve this issue? (did not come around to test it myself...)

**Comment by urshofer** [comment]
closed issue since it is resolved with PR https://github.com/openframeworks/openFrameworks/pull/3736
