### ISSUE TITLE
Poco::Thread trySleep and wakeUp

### ISSUE THREAD

**Issue by quimnuss** [openframeworks/openFrameworks#3731]
I wanted to use Poco's functions trySleep and wakeUp to create a pointcloud multithreaded pipeline, but I couldn't find it on the poco library shipped with oF. Does anybody know why is that?

Otherwise, does anybody have suggestions on how to implement a pipeline with the following characteristics (by order of priority):

* No data should be copied, that is way too expensive.
* The computation should be made as fast as possible to achieve the maximum framerate, even if the threads overwork.
* Thread's should wakeUp when new data is available and sleep otherwise.
* One node can have many subscribers
* Reconfigurable nodes
* The program skips frames when running live and doesn't when 'rendering', so buffer queues would be in place.
* There's the input of the user that can change the behaviour of the processing nodes
* The nodes will br ran on one computer, otherwise I would directly switch to ROS

I've give it some thought and there are many options, data-flow design, threadpooling (thought given the sequentiallity of the process, not so much), signal-based libraries like boost Signals2, subscriber pattern...

What do you think?

**Comment by bakercp** [comment]
Regarding Poco -- currently, oF ships with Poco 1.4.6.  To use oF with the latest Poco 1.6+ run the apothecary script to update Poco on master.  See the help file for more https://github.com/openframeworks/openFrameworks/tree/master/scripts/apothecary

oF 0.9.0 will ship with the latest Poco.

**Comment by arturoc** [comment]
in OF master there's a new class that does more or less what you are asking, ofThreadChannel, you can send data between threads optionally sleeping while waiting for new data to arrive.

i'm going to close this since it's more a question than an issue. the forum is a better place to post this kind of threads

**Comment by quimnuss** [comment]
Thanks arturo,

sorry about the mishap of posting here instead of the forum, coding late at night... I was convinced I was posting on the forum, doh!
