### ISSUE TITLE
Missing libxcursor package in ArchLinux install_dependencies.sh

### ISSUE THREAD

**Issue by Maigre** [openframeworks/openFrameworks#3735]
Hi,

while compiling under ArchLinux / RPi 2 / armv7h 
i faced "cannot find -lXcursor error", so i think
libxcursor is missing in the ArchLinux install_dependencies.sh file
manual install did fix the problem:
sudo pacman -S libxcursor

Best,
Thomas

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by arturoc** [comment]
thanks!
