### ISSUE TITLE
ofQTKitPlayer::getLoopState() fails to return OF_LOOP_PALINDROME

### ISSUE THREAD

**Issue by quadbyte** [openframeworks/openFrameworks#3737]
In ofQTKitPlayer::getLoopState() the test for the OF_LOOP_PALINDROME "case" seems to be wrong. It tests if "loops" is true but if you compare with the setLoopState method it's inconsistent. It should be 

	else if(![moviePlayer loops] && [moviePlayer palindrome]) {
    	    state = OF_LOOP_PALINDROME;
	}

Steps to reproduce
- on Mac, load the video/videoPlayerExample project
- in ofApp::setup()  add 
     fingerMovie.setLoopState(OF_LOOP_PALINDROME);
- in ofApp::update() add
     fingerMovie.getLoopState();

Results
The video actually play in Palindrome mode, but on every frame you get an error in the console
     [ error ] ofQTKitPlayer: unknown loop state

**Comment by DomAmato** [comment]
This can probably be closed since QTKit is no longer supported by apple and moving forward will be depreciated
