### ISSUE TITLE
ofLoadURL (ofURLFileLoader) segfaults on RPI2/Arm7

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#3742]
I first ran into this testing out one of my RPI1 developed addons on the RPI2 but as noted [in this forum post] (http://forum.openframeworks.cc/t/raspberry-pi2-problems-with-http-requests/19071) apparently just the line

`ofHttpResponse resp = ofLoadURL("http://www.google.nl/robots.txt/");`

is enough to reproduce.

In trying to track down the bug I found just adding an ofLog call to to the `static ofURLFileLoader & getFileLoader()` [method](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofURLFileLoader.cpp#L285) changed the behavior and stopped the segfault. This leads me to think that something is being optimized out. 

Some other observations:
RPI1 compiled apps ran on the RPI2 don't crash

**Comment by jvcleave** [comment]
Mostly a note to myself to try this on the RPI2 when I get back on it but after reading http://www.cprogramming.com/tutorial/statickeyword.html I am wondering if the below will work

```
//in .h
static bool initialized;
static ofURLFileLoader * fileLoader;

//in .cpp
bool ofURLFileLoader::initialized = false;
static ofURLFileLoader & getFileLoader(){
	ofURLFileLoader::fileLoader = new ofURLFileLoader();
	ofURLFileLoader::initialized = true;
	return *ofURLFileLoader::fileLoader;
}
```

**Comment by jvcleave** [comment]
maybe even remove `initialized` and just use `if(ofURLFileLoader::fileLoader)` instead

**Comment by thyrrestrup** [comment]
Any news on this issue? I've had the same problem myself some time ago. I never had time to look into it though..

**Comment by arturoc** [comment]
can you post a stack trace of the crash?

**Comment by jvcleave** [comment]
@bakercp Would you happen to have an RPI2 configured to test this? (I currently don't)

**Comment by bakercp** [comment]
Yeah I'll check it out.

**Comment by bakercp** [comment]
I tested this and it's working on RPI2 with master  with http and https links.  I'm going to close it.
