### ISSUE TITLE
Android video grabber broken

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#3752]
I've just updated my openframeworks version to latest git version, and a android app using ofVideoGrabber stopped working. It turns out its initGrabber function that is broken. 

@arturoc I can see that there where made changes in that code last time in https://github.com/openframeworks/openFrameworks/commit/29e7c6b6f708ab1ce13c640a31a53050622356bc . I can't see that it should change how the code is used, is there an error in this commit?

**Comment by arturoc** [comment]
yeah i did some changes to add events back and modified the videograbber a lot, it's one of the oldest classes and it's architecture was slightly weird. i still need to check that everything is working though. will do as soon as i have a moment.

**Comment by bakercp** [comment]
@arturoc -- just running into this myself and with a student project as well.

**Comment by bakercp** [comment]
http://forum.openframeworks.cc/t/examples-with-camera-not-working-on-android/19165/2 for reference.

**Comment by danthemellowman** [comment]
this is still broken for reading back the pixels from the grabber... looks like the frontPixels and backPixels are never getting swapped in the ofxAndroidVideoGrabber::Data and the blank frontPixels are always being returned.

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by HalfdanJ** [comment]
I agree, this is still an issue. I just tried to bypass the frontPixels, and just return backPixels directly instead, and that worked. @arturoc what is the intention with the back and front pixels? Is it because of thread safety? Where should they in that case then swap?

**Comment by arturoc** [comment]
if you don't have double buffering you'll get tearing but i'm not sure what's the state of this it thought it was fixed already. not sure why this is in this state, i though it was fixed. we probably need to add a middle buffer too so the main thread is not locked while the frame is updated.

then the update function that gets called from java writes to the backpixels with out locking, locks and swaps back and middle and sets a flag indicating there's a new frame

the main thread on update locks and swaps middle and front (if there's a new frame)

@HalfdanJ if you want to give it a try? otherwise i can take a look sometime during the weekend

**Comment by arturoc** [comment]
also most new devices should support texture rendering which doesn't require updating the pixels i guess that's why i didn't catched the problem while refactoring the class

**Comment by HalfdanJ** [comment]
@arturoc Ill give it a try. Just to make sure I understand, `Java_cc_openframeworks_OFAndroidVideoGrabber_newFrame` gets called from a separate thread? 

Also, would it make sense to add a flag on the object to indicate if you need pixels, so if texture rendering is supported, and you don't need pixel data, then we can skip the whole copying step (i guess its expensive)? Or should we instead move some of that logic into getPixels so it happens lazily?

**Comment by arturoc** [comment]
yes the java callback happens in a different thread. 

during the last dev conference we talked about adding a setUsePixels method to the base video classes so every class can implement it if it makes sense but let's leave that for next release.
