### ISSUE TITLE
move to gstreamer 1.0 ?

### ISSUE THREAD

**Issue by tpltnt** [openframeworks/openFrameworks#3756]
Hi oF team,

gstreamer 1.0 was released quite a while ago[0]. It has some design advantages over 0.10 and is the place where new development is happening[1]. It also is largely ABI/API compatible with 0.10. Are there any plans/opinions/reservations which stop oF from adopting gstreamer 1.0?
Cheers,
tpltnt

[0] http://gstreamer.freedesktop.org/news/#2012-09-24T18:00:00Z
[1] https://lwn.net/Articles/464270/

**Comment by arturoc** [comment]
OF uses gstreamer 1.0 since about 2 years ago
