### ISSUE TITLE
project generator for win 7 64 bits not run

### ISSUE THREAD

**Issue by lozdanmultimedial** [openframeworks/openFrameworks#3759]
Hello, I download the openFramewrok for win 7 and code blocks of_v084 release. In my desktop Pc win 7 32 bits its run ok, but in my notebook win 7 64 bits Not run. A solution ??

**Comment by kylemcdonald** [comment]
the project generator has been under development for the last year and a half, and we will not be updating the current version. your best bet is to use copy+paste on existing project files, or generate project files onn your desktop and copy them to your notebook.
