### ISSUE TITLE
AVFoundationPlayer: SetVolume produces clicks and noises at start

### ISSUE THREAD

**Issue by urshofer** [openframeworks/openFrameworks#3763]
Hi

After loading a clip, pausing it and setting its volume to 0, I've always encountered some little audio-flickers (clicks/noises) when unpausing it. After the first frame, the volume is adjusted correct.

So I rewrote the `setVolume()` function, setting the Volume directly on the player, not the asset. Works for me, and is shorter. In ofAVFoundationVideoPlayer.mm:

    - (void)setVolume:(float)value {
	volume = value;
	
	if(![self isReady]) {
		return;
	}
	_player.volume = value;
    }

Also adding `_player.volume = volume;` at the end of the completionHandler block of the `loadWithUrl` function. This sets the player with a previously defined volume.

**Comment by kylemcdonald** [comment]
thanks, if you could submit a pull request for this that would be great. it seems no one has any obvious problems with it.

**Comment by urshofer** [comment]
all right. did it here: https://github.com/openframeworks/openFrameworks/pull/3803

**Comment by i-n-g-o** [comment]
merged from PR 4669
