### ISSUE TITLE
getID should be getId in ofHttpRequest / ofFileURLFileLoader

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3780]
For consistency's sake, `ofHttpRequest` && `ofFileURLFileLoader` should follow the same convention as other oF classes when referring to `Id`.

e.g.

ofFbo getIdsFB()
ofVbo getId()
ofBufferObject getId()

Generally we seem to be following the all caps convention for acronyms and the camel case for abbreviations.  Of course it could be argued that ID is not an abbreviation (http://www.thefreedictionary.com/ID) but anyway, consistency should be the key here.

**Comment by bakercp** [comment]
Of course that said, if we're using URL (e.g.  in names, `ofFileURLFileLoader `) then we should also be using HTTP in names (e.g. `ofHttpRequest`) Anyway, start with the small stuff. :small_blue_diamond:

**Comment by bilderbuchi** [comment]
fwiw, the Qt code style, which we based off of, says acronyms should also be camel-cased in names (i.e. `Xml`, not `XML`)
