### ISSUE TITLE
ofxOsc: osc::int32 is 8 bytes when compiling for arm64

### ISSUE THREAD

**Issue by galsasson** [openframeworks/openFrameworks#3785]
Just a missing macro check, I fixed it in my fork, under myios-64bit branch 
see:
galsasson/openFrameworks@15ed41a32a6f846f0e9a3135bfaaefc3533a03b5

**Comment by bilderbuchi** [comment]
Thanks. As this is in the oscpack source, it should be submitted as an upstream bug.

**Comment by bilderbuchi** [comment]
@arturoc @ofTheo should we patch this in our copy of oscpack? otherwise, I'll close this

**Comment by ofTheo** [comment]
I think we probably should patch it in. 
@galsasson can you send a PR to our master branch?  

Thanks. Theo

**Comment by bakercp** [comment]
for what it's worth, here's a similar problem / solution from the forum

http://forum.openframeworks.cc/t/osc-on-ipod-touch-7-1-assertion-fail/20260

**Comment by arturoc** [comment]
can you send the PR to https://github.com/arturoc/oscpack? i forked oscpack yesterday there to fix something else so the latest changes are there. i'll copy it into ofxOsc then

**Comment by ofTheo** [comment]
@arturoc OF's oscpack differs from upstream FYI. 
I had to add some changes to allow port reuse - I don't think these were ever pulled to upstream. 

see: https://github.com/openframeworks/openFrameworks/commit/0b42a71a31184d7e554d97b8af77251605a697fe 

and discussion:
https://github.com/openframeworks/openFrameworks/pull/3210

**Comment by arturoc** [comment]
i know i added those patches back in my repo

**Comment by galsasson** [comment]
Do you guys still want a PR to master? I lost track

**Comment by arturoc** [comment]
no, to my fork.

i'll move it later to the openframeworks code, that way it's easier to send back changes to the original author

**Comment by galsasson** [comment]
done

**Comment by arturoc** [comment]
thanks!

**Comment by bilderbuchi** [comment]
@arturoc is it feasible to keep all the changes to original oscpack source as patches in apothecary or whatever? that way it would be easier to both keep up-to-date, and keep track of our custom tweaks (although I'm not sure if oscpack is still really maintained, and won't disappear when Google shuts down google code)
