### ISSUE TITLE
ofTrueTypeFont bounding box / string width incorrect for non-ASCII

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3786]
```c++
#include "ofMain.h"

void drawWithBoundingBox(ofTrueTypeFont& font, string text, float x, float y) {
    ofNoFill();
    ofDrawRectangle(font.getStringBoundingBox(text, x, y));
    font.drawString(text, x, y);
}

class ofApp : public ofBaseApp {
public:
    ofTrueTypeFont font;
    void setup() {
        font.load(OF_TTF_SANS, 24, true, true);
    }
    void update() {
    }
    void draw() {
        drawWithBoundingBox(font, "äbcdëfghïjklmnöpqrstüvwxÿz", 24, 48);
        drawWithBoundingBox(font, "abcdefghijklmnopqrstuvwxyz", 24, 96);
    }
};
int main() {
    ofSetupOpenGL(640, 200, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

![screen shot 2015-04-26 at 18 00 16](https://cloud.githubusercontent.com/assets/157106/7338002/1f4b8cc0-ec3e-11e4-8025-6ed7c1bf1aba.png)

**Comment by procedural** [comment]
I bet it thinks `¨` diaeresis is a separate letter :)

**Comment by kylemcdonald** [comment]
@procedural yes i think you're right. i was considering that it was just UTF-8 which means `äëïöüÿ` is actually a 12-byte sequence `0xC3A4C3ABC3AFC3B6C3BCC3BF`, but this is more complex than just counting the number of bytes because character width is handled correctly.

**Comment by toshakluev** [comment]
Do we have any solutions for this problem?

**Comment by arturoc** [comment]
don't have time to fix it right now but this is related to the way the bounding box is calculated from the mix and max x instead of only taking into account the advance of the character as it's done when drawing the text

**Comment by toshakluev** [comment]
To calculate the boundingBox properly i try to replace all the umlauts in the text, and then insert in boundingBox... can you help me with this please? How can i compare something like this properly:

string letters = "das Örtliche"
vector <char> umlauts = {'Ä', 'ä', 'Ö', 'ö', 'Ü', 'ü', 'ß'};
vector <char> normals = {'A', 'a', 'O', 'o', 'U', 'u', 's'};
// for's...
if ( letters[n] == umlauts[i] ) {
    return normals[i];
} else {
    return letters[n];
}

Its not works :( i think the "letters[n] == umlauts[i]" not returns "true"
