### ISSUE TITLE
more useful semantic versioning on master between official releases

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3796]
As we're getting nearer to the 0.9.0 release, I'm trying to keep my addons up-to-date with new deprecations, etc.  Currently the version on master still says 0.8.4

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L5-L7

Would it be acceptable to adopt a versioning scheme where the develop branch is incremented as soon as a release is made so that addons can potentially support both the master branch and releases simultaneously with if-defs, etc?

My goal is basically to more gracefully transition during deprecations and avoid lots of warnings in my addons.

One solution might be to use patch-version extensions, for example, by adding a patch version extension of `develop` we could indicate that this is still a development version.  So, for instance, right now the version might be:

`0.9.0-develop`

Anyway, this would require one or two minor changes, but would all still constitute legal sem-ver 2.0.0 syntax, etc.

Thoughts?

**Comment by arturoc** [comment]
there's a similar PR already from @armadillu can't find it right now. anyway i think just updating the version number right after we do the release should be enough. other projects do that and it works without problem

**Comment by armadillu** [comment]
Hey @arturoc  I made no PR, I just asked in the forum as I was just wondering how others handled that. I don't care so much about warnings/deprecations, but I do care about missing/renamed methods that don't let the compile. In my case, its ofSetPixelStorei vs ofSetPixelStoreiAlignment:

https://github.com/armadillu/ofxProgressiveTextureLoad/commit/72f565d104b0f0eaea7eba08f3bae8b6957af481

We use branches inside the addon, but it gets out of control very quickly when several people are using the addon in different projects. I really can't see a good solution...

http://forum.openframeworks.cc/t/of-version-safe-addons/18886

**Comment by bakercp** [comment]
Just added a possible solution that incorporates semver version tags.

**Comment by bilderbuchi** [comment]
+1, this has been an itch for me for quite a while. I also know of other projects which increment/change the version immediately after release.

**Comment by bakercp** [comment]
@bilderbuchi do you have any thoughts on what the "tag" should be between releases?  Basically I want to be able to check and see if that tag is an empty string, I can know that it is an official release.  Perhaps it should be something more descriptive than "master" -- like "prerelease"?  And eventually "rc1, rc2, etc". until the release at which point it would just be a blank string?

**Comment by bilderbuchi** [comment]
My first instinct was to have a "dev" string, but "master" is descriptive, too, since it reflects the state of the master branch, after all.

**Comment by bakercp** [comment]
@bilderbuchi thanks -- also my first instinct, but my first instinct is also to go back to the old-days of the develop branch ... so in these modern times it seems "master" makes the most sense, with a rc1, rc2, etc just before those are packaged.

**Comment by bakercp** [comment]
Closed with #3797
