### ISSUE TITLE
ofxGui disabling ofParameterGroup events

### ISSUE THREAD

**Issue by chaosct** [openframeworks/openFrameworks#3799]
The way ofGui widgets are implemented, is by having a local `ofParameter` and then making a reference to the `ofParameter` passed as an argument ([example](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxGui/src/ofxSlider.cpp#L24)).

This means that `ofAbstractParemeter::parent` is not copied, preventing modifications of the value using the GUI to be notified to a `ofParameterGroup` holding the original `ofParameter`. Then `ofParameterGroup::parameterChangedE` is never fired.

I don't think this is the expected behavior.

I can propose a fix, but I'm afraid that there are some underlying details of `ofParameter` design I may not grasp.

**Comment by arturoc** [comment]
closed via 5b2971a9b2e1cdec715c2338f0a7bddf22bb3188
