### ISSUE TITLE
ofMesh texCoords not being sent to shader

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3805]
Setup: 0.9.0, OS X 10.10.3, XCode 6.3

`ofMesh::addColor()` gets through to the fragment shader in `gl_Color`, but `ofMesh::addTexCoord()` doesn't get through in `gl_TexCoord`. I tried adding my own vertex shader to capture `gl_MultiTexCoord0` into a custom varying, but that didn't do anything. If I switch from `ofMesh` to `ofVboMesh` then it works. I found something in the changelog mentioning this was refactored, but couldn't figure out what might have caused this bug.

Example code:

```c++
#include "ofMain.h"

#define str(x) #x
string frag =
str(
    void main() {
        float alpha = max(mod(gl_Color.r * 10., 1.),
                          mod(gl_TexCoord[0].g * 10., 1.));
        gl_FragColor = vec4(gl_Color.rgb, alpha);
    }
    );

class ofApp : public ofBaseApp {
public:
    ofShader shader;
    ofMesh mesh;
    void setup() {
        shader.setupShaderFromSource(GL_FRAGMENT_SHADER, frag);
        shader.linkProgram();
        mesh.setMode(OF_PRIMITIVE_TRIANGLE_FAN);
        
        mesh.addVertex(ofVec2f(0, 0));
        mesh.addColor(ofFloatColor(0, 0, 0));
        mesh.addTexCoord(ofVec2f(0, 0));
        
        mesh.addVertex(ofVec2f(256, 0));
        mesh.addColor(ofFloatColor(1, 0, 0));
        mesh.addTexCoord(ofVec2f(1, 0));
        
        mesh.addVertex(ofVec2f(256, 256));
        mesh.addColor(ofFloatColor(1, 1, 0));
        mesh.addTexCoord(ofVec2f(1, 1));
        
        mesh.addVertex(ofVec2f(0, 256));
        mesh.addColor(ofFloatColor(0, 1, 0));
        mesh.addTexCoord(ofVec2f(0, 1));
    }
    void draw() {
        ofTranslate(5, 5);
        shader.begin();
        mesh.draw();
        shader.end();
    }
};
int main() {
    ofSetupOpenGL(256+10, 256+10, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

Expected result (0.8.4, or with ofVboMesh on 0.9.0):

![expected](https://cloud.githubusercontent.com/assets/157106/7498324/0895603e-f3ee-11e4-9aaf-2f537c872566.png)

Actual result (0.9.0):

![actual](https://cloud.githubusercontent.com/assets/157106/7498335/12c38978-f3ee-11e4-8419-cc3975d903b6.png)

**Comment by arturoc** [comment]
there's a bug where tex coords won't be bound unless there's a texture bound

**Comment by bilderbuchi** [comment]
is this still occurring in latest master?
