### ISSUE TITLE
Adding setProjectionMatrix to ofCamera.

### ISSUE THREAD

**Issue by PetrosKataras** [openframeworks/openFrameworks#3808]
Hi,
I need to set a custom projection matrix to an ofCamera and I noticed that it is on the todo list. Do you see any issues with just returning the custom matrix if one set by the user or is there something more that should be accounted for?

**Comment by elliotwoods** [comment]
Hi @PetrosKataras 

I haven't been a part of the previous discussion around setProjectionMatrix being implemented for ofCamera. Personally I think it's likely to be more trouble than its worth.

ofCamera should use parameters such as fov, near clip plane, etc And if you have a setProjectionMatrix function, then you override those parameters with a matix, which is ambiguous to people using the ofCamera.

Alternatively, I'd propose a `ofLoadProjectionMatrix(const ofMatrix4x4 &)` which you could run directly after `ofCamera::begin()`, which would effectively override the projection matrix state on the GPU.

You can do `ofLoadProjectionMatrix` currently by:

```c++
	ofCamera camera;
	ofMatrix4x4 myProjectionMatrix;

	camera.begin();

	ofSetMatrixMode(ofMatrixMode::OF_MATRIX_PROJECTION);
	ofLoadMatrix(myProjectionMatrix);
	ofSetMatrixMode(ofMatrixMode::OF_MATRIX_MODELVIEW);

	/* do your usual stuff */

	camera.end();
```

**Comment by arturoc** [comment]
yes something like this would break encapsultion, setting a matrix and then asking for the getFov will return an incoherent value.

if you need to set the projection probably you need a specific camera, you can create your own by inheriting from ofNode and adding the projection matrix that you already have

**Comment by PetrosKataras** [comment]
Thanks for the info. 
For the shake of brevity I personally like the proposal for ofLoadProjectionMatrix and for symmetry ofLoadModelViewMatrix. If there is no objection about these I could add them and create a small PR.

**Comment by arturoc** [comment]
if you want to give it a try go for it. it might be slightly tricky in the fixed pipeline renderer since you need to go back to the previous state and i don't think we should rely on it always being model view. the alternative is to use glGet which would slow down things a lot or try to keep track of it which won't be reliable if people use glMatrixMode instead of the OF version, which is pretty common since we only added those functions relatively recently.

**Comment by PetrosKataras** [comment]
Hmmm.. Probably I am missing something since from what Elliot suggests I would expect that something like this would be enough:

```
ofLoadProjectionMatrix( const& ofMatrix4x4 m )
{ 
   ofSetMatrixMode(ofMatrixMode::OF_MATRIX_PROJECTION);
    ofLoadMatrix(myProjectionMatrix);
}
```

**Comment by arturoc** [comment]
if you do that then the matrix mode is left to projection and if you try to do something like ofTranslate it'll affect the projection matrix not the model view

**Comment by PetrosKataras** [comment]
Yes. Which means that you would get exactly what you asked for .. no ?? ;)

For me `ofLoadProjectionMatrix` and `ofLoadModelViewMatrix` would make sense if they both do exactly what the name suggests in each case and nothing more. It just loads the relevant matrix and its up to the user to keep track of things but this is just my opinion and maybe this does not fit to the overall philosophy.

**Comment by arturoc** [comment]
mmh, no if you do:

```
ofLoadProjectionMatrix(m);
ofRotateZ(20);
ofDrawRectangle(0,0,20,20);
```

you expect a rectangle rotated 20 degrees with whatever projection matrix you set but what you get is a broken projection matrix and no rotation.

the fixed pipeline has a global state that you would be changing and you need to restore it to whatever it was

**Comment by PetrosKataras** [comment]
If someone calls a function explicitely documented that it loads and applies a projection matrix and then tries to rotate an object in the way that you mentioned without switching first to model view for me it means that either the user didnt bother to read the docu or just does not have any idea of what he/she is doing which means that should not use this function directly and should just rely on OF internally for setting up matrices. 

But anyways I stop here and go with you on that since you have all the internals in your head already :)

I ll  have a look on the legacy renderer and see if it really worths the effort.

Thanks for your responses!

**Comment by arturoc** [comment]
for me a function like that implies that there's no global state (as can be done easily with the programmable renderer) otherwise i would expect the old model where i set the state and then the matrix.

ofLoadProjectionMatrix(m) for me says set the projection matrix to m. not change the global state to projection and then set m.

it'd be really nice to have something like this and it's relatively straight forward with the programmable renderer but we need a way of solving it for the fixed pipeline

**Comment by PetrosKataras** [comment]
I had a look on this. It seems that an alternative to glGetEnv, which is already used in ofGLRenderer for the view matrix, we could try glPushAttrib / glPopAttribute with the transform bit.

This is also not the most efficient thing since its also pushing/popping plane coefficients and some other stuff but I think it could an option for this case.

**Comment by PetrosKataras** [comment]
@arturoc What do you think about the glPush/Pop option ? 

If you are ok with this I could try and add them tonight.

**Comment by arturoc** [comment]
glPush/Pop is as slow as glGet. i guess the best would be to only have this functions when working with the programmable renderer but right now we don't have any way to do that except in platforms that exclusively use the programmable renderer through the USE_PROGRAMMABLE_GL ifdef, but right now that's only emscripten

**Comment by PetrosKataras** [comment]
Ok, I thought it could be a valid alternative for this case based on the third point of this ancient but still relevant ( for the explicit renderer  ) [opengl archive](https://www.opengl.org/archives/resources/features/KilgardTechniques/oglpitfall/).

**Comment by arturoc** [comment]
i'm not saying not to use it just that it's really slow and it'll limit the places where it can be used. we might also just set the mode back to model view always and just take that as the default which usually is.
