### ISSUE TITLE
use of GL_TEXTURE_RECTANGLE

### ISSUE THREAD

**Issue by aspeteRakete** [openframeworks/openFrameworks#3812]
Hey, according to this stackoverflow thread:
http://stackoverflow.com/a/6883457
There are no limitations on GL_TEXTURE2D for texture sizes. If not on OpenGL ES the programmable Renderer uses GL_TEXTURE_RECTANGLE. I also found this in static string shaderSource(...):
```
if(major<4 && minor<2){
		ofStringReplace(shaderSrc,"%extensions%","#extension GL_ARB_texture_rectangle : enable");
	}
``` 
I can't find any ressources on why this is not included in GL 4.2 anymore. When I write a shader on OSX and the programmable Renderer set to OpenGL 3.3 the shader won't compile because the extension is not found. Which seems kind of strange to me, since the line should be in all of the stock shaders? Wouldn't it be easier to unify all the Textures to GL_TEXTURE2D? Or are you keeping the _RECTANGLE to be able to use non normalized texture coordinates?

**Comment by tgfrerer** [comment]
We're keeping gl_texture_rectangle mainly for compatibility reasons, i believe, also, it seems a bit more intuitive for beginners to use pixel coordinates in shaders.

`GL_TEXTURE_RECTANGLE` is very limited when it comes to mipmaps, compression, etc, so generally using GL_TEXTURE_2D is a better option. In modern OpenGL you can query the texture dimensions in the shaders, so calling `vec2 textureSize(sampler, 0)` should give you the pixel dimensions.

As the name suggests, `GL_ARB_texture_rectangle` is an extension, and it made it into core GL with version 2.1, so there is no need to activate this extension "manually" in modern programmable GL. 

Instead, in the shader, you can assume the extension is present in Desktop GL from 2.1 onwards, and starting from shader language version 330 you would define the sampler unit as` sampler2DRect` for rectangle, and `sampler2D` for a regular 2D texture.

**Comment by arturoc** [comment]
also if you call ofDisableArbTex() at the beginning of your program it'll always use GL_TEXTURE_2D

**Comment by aspeteRakete** [comment]
Thanks a lot guys. That really cleared that up for me!
