### ISSUE TITLE
project generator and opencv

### ISSUE THREAD

**Issue by jingpe** [openframeworks/openFrameworks#3821]
Hello.. tried to check ofxOpenCv and ofxGui in the project generator and generate an OS X project.

Xcode reported error of the following.. while it didn't appears in download ver of 0.8.4

Undefined symbols for architecture x86_64:
  "typeinfo for ofBaseSoundInput", referenced from:
      typeinfo for ofBaseApp in main.o
  "ofBaseSoundOutput::audioOut(float*, int, int, int, unsigned long long)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "ofBaseSoundInput::audioIn(ofSoundBuffer&)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "typeinfo for ofBaseSoundOutput", referenced from:
      typeinfo for ofBaseApp in main.o
  "ofBaseSoundInput::audioIn(float*, int, int)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "ofBaseSoundOutput::audioOut(float*, int, int)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "ofBaseSoundOutput::audioOut(ofSoundBuffer&)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "ofSetupOpenGL(int, int, ofWindowMode)", referenced from:
      _main in main.o
  "vtable for ofBaseSoundOutput", referenced from:
      ofBaseSoundOutput::ofBaseSoundOutput() in main.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "ofBaseSoundInput::audioIn(float*, int, int, int, unsigned long long)", referenced from:
      vtable for ofBaseApp in main.o
      vtable for ofApp in ofApp.o
  "vtable for ofBaseSoundInput", referenced from:
      ofBaseSoundInput::ofBaseSoundInput() in main.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "ofRunApp(ofBaseApp*)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

.
.
.

**Comment by jingpe** [comment]
after linking up the frameworks and libraries, and embedded binaries.. its good to be compiled.

**Comment by danoli3** [comment]
Try a clean and see if it happens again. (Do a clean on the openFrameworks Static Library as well, just to be safe).

**Comment by danoli3** [comment]
Closing as author resolved the issue.
