### ISSUE TITLE
Cannot compile ofTrueTypeFont with Master branch for 64-bit device 

### ISSUE THREAD

**Issue by abrahamavnisan** [openframeworks/openFrameworks#3829]
I'm rewriting an iOS project originally written in OF 0.8.4 for my 64-bit iPad Air using the master branch that was [recently merged](https://github.com/openframeworks/openFrameworks/pull/3651#event-304306347) with danoli's apothecary branch for iOS 64.  I'm able to run empty examples and the [ofxCoreMotion addon](https://github.com/trentbrooks/ofxCoreMotion) example without any problems.

In my project, however, which uses @bakercp's updated ofTrueTypeFont, I'm running into this undefined symbols issue around ofTrueTypeFont: `Undefined symbols for architecture armv7:
  "ofTrueTypeFont::bind()", referenced from:
      ofApp::draw() in ofApp.o`.

I'm running Yosemite 10.10.3, Xcode 6.3.1, and iOS 8.3 on my iPad air.

My build architectures look like this (these same settings work for the ofxCoreMotion example):

![screen shot 2015-05-14 at 2 16 59 pm](https://cloud.githubusercontent.com/assets/5367696/7639755/e9379f5c-fa43-11e4-9900-880702b5e943.png)

And here is a screenshot of the errors I'm getting:

![screen shot 2015-05-14 at 2 13 40 pm](https://cloud.githubusercontent.com/assets/5367696/7639728/ad9ec934-fa43-11e4-9b87-c0d2af8e7566.png)

Any thoughts would be greatly appreciated!

**Comment by bakercp** [comment]
Did you run a project clean?

**Comment by abrahamavnisan** [comment]
Yes, @bakercp - I cleaned the project several times!

**Comment by danoli3** [comment]
Make sure you include the Xcode changes found in the ```scripts/ios/template/```

Any test project you could send that we could have a tinker with?

**Comment by bakercp** [comment]
So the problem is (and I'm not sure why) the current version of https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.cpp does not implement the `bind()` and `unbind()` methods (which is why you have undefined symbols).

**Comment by bakercp** [comment]
You can see the definitions are in the header file (https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.h) ... but not sure where the implementation went ... :/

**Comment by bakercp** [comment]
I have to say, it's a little odd ... those methods disappear sometime in the last few commits ...

https://github.com/openframeworks/openFrameworks/commits/master/libs/openFrameworks/graphics/ofTrueTypeFont.cpp

But I can't figure out the diff where they were deleted ...

**Comment by bakercp** [comment]
![history_for_libs_openframeworks_graphics_oftruetypefont_cpp_-_openframeworks_openframeworks](https://cloud.githubusercontent.com/assets/300484/7641716/212bac84-fa51-11e4-83a1-7a304567ee24.png)

**Comment by danoli3** [comment]
Curious! Could have been a merge issue!

**Comment by arturoc** [comment]
i think i removed them a while ago. this was a way to optimize ofTTF but there's now a better way to do it by getting the mesh and binding the internal texture. it was not even documented anywhere so i doubt anyone was using them. i'm going to remove them from the .h too

**Comment by bakercp** [comment]
Yeah, it was removed between here and here

https://github.com/openFrameworks/openFrameworks/compare/753aba17fc02eced869f2ac2951f623a94dac098...a7fe7f6040462e334c69e7c1164b3df8a2ac6937

Now it does the drawing in the current renderer.

So we need to remove the bind/unbind from the header and then @abrahamavnisan you'll have to update to follow the new render-specific drawing setup ...

**Comment by bakercp** [comment]
@arturoc looks like you already took care of it.  @abrahamavnisan we should talk offline and see how to deal with this -- as IIRC you were directly accessing bind / unbind because you created a subclass of ofTrueTypeFont ... I think you can probably just modify the subclass to use the new rendering scheme.  :)  Easy right? :)

**Comment by abrahamavnisan** [comment]
Wow - you guys are quick!  Thanks for helping me to understand what was happening.  @bakercp , I'm writing you an offline note about the ways in which I was using bind and unbind and how I can work that into the new rendering scheme.

**Comment by bakercp** [comment]
@abrahamavnisan sounds good.

**Comment by arturoc** [comment]
if you want to have more control over how it's drawn or cache the drawing somehow you should look into getStringMesh and getTexture
