### ISSUE TITLE
ofVideoPlayer width and height 0

### ISSUE THREAD

**Issue by kontur** [openframeworks/openFrameworks#3831]
As mentioned in the [source](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofVideoPlayer.h#L142), the `width` and `height` properties are there for legacy.

However, I found they are always 0 unless you use the `getWidth()` or `getHeight()` methods first.

**Comment by kylemcdonald** [comment]
it would be good to deprecate these member variables if possible.

**Comment by ofTheo** [comment]
+1 to deprecate but also we should have them update in the meantime.

**Comment by arturoc** [comment]
i think we could just remove them right away, not sure if we can deprecate variables as opposed to methods and they are constantly a source of problems + is one of the most basic wrong things to do in OOP. 

we are already breaking stuff in 0.9 if we just deprecate them it's going to be a couple of years more until 0.10 to remove them

**Comment by kylemcdonald** [comment]
+1 @arturoc 

it looks like they're still used inside `ofVideoPlayer.cpp` sometimes but could be substituted for `getWidth()` and `getHeight()` anywhere and those methods can call `player->getWidth()` and `player->getHeight()` instead of caching it.

**Comment by bilderbuchi** [comment]
I don't think this is a critical issue, so I pushed it back to 0.9.1. Feel free to fix it before that, but it should not delay 0.9.0.
