### ISSUE TITLE
Linux, Linux64, Linux arm6, linux arm7 poco libs

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3834]
I'm compiling all of these now ... can't find where we are tracking it ... so I'm just making note here.

- [x] Linux 64 https://github.com/openframeworks/openFrameworks/pull/3835
- [x] Linux 32 https://github.com/openframeworks/openFrameworks/pull/3836
- [x] Linux Arm6 https://github.com/openframeworks/openFrameworks/pull/3807
- [x] Linux Arm7 #4197

**Comment by bakercp** [comment]
@arturoc -- should I proceed with arm6 and arm7?

**Comment by arturoc** [comment]
sure, sure, i had only added linux64

**Comment by bakercp** [comment]
Cool.  RPI1 and RPI2 are chugging away on these ... RPI2 will be done soon ... RPI1 may be a while :)

**Comment by procedural** [comment]
I saw some deprecated commands which may cause compile errors for OpenGL ES in examples, like [`ofSetCurrentRenderer()`](https://github.com/openframeworks/openFrameworks/search?p=1&q=ofSetCurrentRenderer).

**Comment by bakercp** [comment]
@procedural -- sorry I didn't understand that comment relates to this issue -- could you clarify?

**Comment by procedural** [comment]
@bakercp oh, sorry, I missed poco part...

**Comment by bakercp** [comment]
@procedural no worries :+1:

**Comment by ptterb** [comment]
Are there plans to recompile android libs? I tried, but using apothecary (for the first time) wasn't successful for me.

**Comment by bakercp** [comment]
@ptterb definitely plans -- but haven't gotten around to it yet.  What kind of errors did you find?

**Comment by ptterb** [comment]
Great, thanks. First time trying to compile any of this for android.
I added the SDK and NDK paths, and then ran:

    ./apothecary -v -t android update poco

It downloads poco and starts preparing before giving me this:

    Auto-config: --toolchain=arm-linux-androideabi-4.6
    Host system 'darwin-x86' is not supported by the source NDK!
    Try --system=<name> with one of:  darwin-x86_64

I was trying to find where the host system was even being set, but couldn't find it.

**Comment by bakercp** [comment]
Just added a new issue for that one @ptterb let's pursue that separately from the linux libs.

**Comment by Daandelange** [comment]
Arm6 is done now in  https://github.com/openframeworks/openFrameworks/commit/26fdfd172e2763fd06ff6339147ceb78cf51e396

**Comment by bakercp** [comment]
I've got arm7 on the way.

**Comment by bilderbuchi** [comment]
any updates on this? arm7 already done, @bakercp ?

**Comment by bakercp** [comment]
@bilderbuchi Yeah ... it's been done for weeks.  Just been distracted with various projects.  I'll try get it uploaded tomorrow ... it's sitting right next to my computer in my studio ... :sleepy:

**Comment by bilderbuchi** [comment]
@arturoc if you're recompiling poco while taking care of the namespace issue (#4097), could you take a look at this?

**Comment by bakercp** [comment]
@arturoc let me know if you're recompiling, otherwise I will upload it as is.

**Comment by arturoc** [comment]
go for it i don't have any arm7 boards right now, was planing to set something on a server so it recompiles automatically but will take a while

**Comment by bakercp** [comment]
@arturoc OK.
