### ISSUE TITLE
dragevent removes the driveletter from the paths of the dropped files on windows

### ISSUE THREAD

**Issue by dahklfahdkghas** [openframeworks/openFrameworks#3848]
As posted in the forum:
http://forum.openframeworks.cc/t/dragevent-is-chopping-off-the-driveletter/19602

When files are dropped in the application the driveletter is removed from the filepath. 
The error occurs atleast on windows 7 (64bit) with codeblocks and of v0.8.4 and "Win 8 (64 bit) with of_v0.8.4_win_cb_release using Code::Blocks 13.12".

To see the problem, start with the "dragDropExample" and enter the following code:

```
void ofApp::dragEvent(ofDragInfo dragInfo){
    for (int i=0; i<dragInfo.files.size(); i++){
        cout << dragInfo.files[i] << endl;
    }
}
```

Run the modified example, drop some files and read the printout. If you drop them from a drive separate from where you have "of", the files won't be found and you should get an error. 

Unfortunately I'm too much of a beginner to have a go at figuring out the source of the problem.

**Comment by DomAmato** [comment]
This seems to be an issue with the URI in poco. When I debug the file path is correct in |

    void ofAppGLFWWindow::drop_cb(GLFWwindow* windowP_, int numFiles, const char** dropString) {
	ofDragInfo drag;
	drag.position.set(ofGetMouseX(), ofGetMouseY());
	drag.files.resize(numFiles);
	for(int i=0; i<(int)drag.files.size(); i++){
                //dropstring[i] gives the correct path
		drag.files[i] = Poco::URI(dropString[i]).getPath();
                //drag has missing drive letter
	}
	ofNotifyDragEvent(drag);
    }

**Comment by arturoc** [comment]
this is fixed in master

**Comment by DomAmato** [comment]
So then it should be safe to close this issue. I was just going through the issues seeing if we could pare things down a bit
