### ISSUE TITLE
projectGenerator: number of addons limited by height of window

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/openFrameworks#3850]
Since an ofApp is not scrollable, the project generator only shows a certain number of addons. 
Grouping addons in core addons and non core addons would at least increase the number of addons that can be shown.

**Comment by arturoc** [comment]
that project generator is an old version and it's not really used any more except for the command line functionality to use the packages.

the project generator simple that comes with the download or as a submodule of this repo already has that separation and also scrolls through the addons when you move the mouse
