### ISSUE TITLE
Unsupported Windows version poco 1.6

### ISSUE THREAD

**Issue by nykwil** [openframeworks/openFrameworks#3853]
update: 91eabdd04262e0f5fe955a973bd1817b98a522b9

Has broken the vs2012 project. 

	#if (_WIN32_WINNT < 0x0501)
		#error Unsupported Windows version.
	#endif

which is defined as 0x0500

Not sure what the best way to fix this is.

**Comment by danoli3** [comment]
```_WIN32_WINNT``` is defined as follows: 
- Windows XP = 0x0501
- Windows Server 2003 = 0x0502
- Windows Vista = 0x0600
- Windows 7 = 0x0601
- Windows 8 = 0x602 
- Windows 8.1 = 0x603

What version of Windows are you using @nykwil ?

**Comment by nykwil** [comment]
Windows 7.  I think it may be pulling the value from ofConstants.h.

**Comment by danoli3** [comment]
Yeah, for some reason it is defined in ofConstants.
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L100

Try and remove that line and see if it fixes it. If it does, definitely PR that change.
Not even sure why that is there.

**Comment by nykwil** [comment]
Removing the line unfortunately that creates this problem:
GetProcessInformation C linkage error #22
Which is documented here: https://github.com/sadmb/ofxKinectNui/issues/22

And incrementing it seems to give me a whole bunch of unresolved symbols.

Also I noticed the project was updated to vs2013.

2>openframeworksLib_debug.lib(ofAppRunner.obj) : error LNK2019: unresolved external symbol __imp__timeBeginPeriod@4 referenced in function "void __cdecl ofInit(void)" (?ofInit@@YAXXZ)
2>openframeworksLib_debug.lib(ofAppRunner.obj) : error LNK2019: unresolved external symbol __imp__timeEndPeriod@4 referenced in function "void __cdecl ofExitCallback(void)" (?ofExitCallback@@YAXXZ)
2>openframeworksLib_debug.lib(ofEvents.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofAppGLFWWindow.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofUtils.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofMainLoop.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofURLFileLoader.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofParameterGroup.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)
2>openframeworksLib_debug.lib(ofAppGLFWWindow.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)
2>openframeworksLib_debug.lib(ofThread.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)
2>openframeworksLib_debug.lib(ofMainLoop.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)
2>openframeworksLib_debug.lib(ofURLFileLoader.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)
2>openframeworksLib_debug.lib(ofParameterGroup.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)
2>openframeworksLib_debug.lib(ofEvents.obj) : error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::unexpected(char const *,int)" (?unexpected@Bugcheck@Poco@@SAXPBDH@Z)

**Comment by kentaroid** [comment]
I was also the same situation.

LNK2019:
Specify `winmm.lib` to Debug setting of openframeworksLib.
[openframeworksLib] -> [property] -> [Librarian] -> [Additional Dependencies]
It has already been specified for the Release setting.

LNK2001:
I tried to build poco library, now works.
[poco1.6mdLibs.zip](https://dl.dropboxusercontent.com/u/6792382/poco1.6mdLibs.zip)

**Comment by nykwil** [comment]
I tired this an now I'm only missing Poco::Bugcheck::assertion
Any ideas?

    Error	1	error LNK2001: unresolved external symbol "public: static void __cdecl Poco::Bugcheck::assertion(char const *,char const *,int,char const *)" (?assertion@Bugcheck@Poco@@SAXPBD0H0@Z)	D:\Code\Libraries\openFrameworks\scripts\vs\template\openframeworksLib.lib(ofUtils.obj)

**Comment by LeoColomb** [comment]
See #1432

**Comment by nykwil** [comment]
Maybe I should open another bug.  Not sure what the best thing to do with the missing external symbols, it's all the Bugcheck.h functions.  Should I rebuild poco?

**Comment by nykwil** [comment]
Rebuilding poco fixes the problem.  Should I make a pull request with the ofConstant, the project changes and my poco libs?  (File sizes are very different)

**Comment by bakercp** [comment]
So -- just to clarify -- @nykwil what was your final solution to get this working?  What was changed in the OF core and what did you change in Poco?

**Comment by nykwil** [comment]
I just had to recompile poco for some reason the bugcheck stuff was missing from the foundation lib.   in ofConstants.h _WIN32_WINNT 0x0501.  In the projects I added winmm.lib as an addition dependency.

**Comment by bakercp** [comment]
@domamato Have you had this problem?  I was able to get all dependencies compiled, compiled on your branch, but was unable to get any oF apps compiled due to this.

**Comment by DomAmato** [comment]
Yeah I had to change the ofConstants value to get things working

**Comment by quinkennedy** [comment]
I'm curious as to what _should_ be happening. Do the windows .h files need to be included earlier? seems like only a temporary solution to have ofConstants defining _WIN32_WINNT (especially without it actually checking the environment in any way).

**Comment by DomAmato** [comment]
Well the error that @nykwil ran into has to do with a redefinition issue with the quicktime headers so I am not sure that undefining the macro in ofConstants is actually problematic. I think this issue popped up somewhere else before with the quicktime headers. Maybe that has something to do with the macro definition since the quicktime issue doesnt seem to pop up on lower windows versions? really thats speculation but I am tinkering with poco.

**Comment by arturoc** [comment]
this is fixed in the latest commits
