### ISSUE TITLE
Compile Poco Libs for Android

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3860]
Some errors so far:

from https://github.com/openframeworks/openFrameworks/issues/3834#issuecomment-104404936 @ptterb via

Great, thanks. First time trying to compile any of this for android.
I added the SDK and NDK paths, and then ran:

    ./apothecary -v -t android update poco

It downloads poco and starts preparing before giving me this:

    Auto-config: --toolchain=arm-linux-androideabi-4.6
    Host system 'darwin-x86' is not supported by the source NDK!
    Try --system=<name> with one of:  darwin-x86_64

I was trying to find where the host system was even being set, but couldn't find it.

**Comment by bakercp** [comment]
We definitely shouldn't see the darwin stuff ... hmm @arturoc I think you successfully got that working last time -- did you compile it on OSX or did you do all of the lib compilation via apothecary on Linux?

**Comment by bakercp** [comment]
I'm wondering if we need to modify the scripts to work with the sdk/ndk on OSX.

**Comment by arturoc** [comment]
i've only done this from linux, the problem i think is in the detection of the host system. all those variables come from android_configure.sh in formulas.  don't have time to check this right now but i'll try to compile them when i have a moment.
