### ISSUE TITLE
0.9.0 fails to compile on Codeblocks 12.01 / Mingw

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3864]
Using the ofMinGW toolchain (which is the same version as the codeblocks and ofSketch) oF master fails to compile.  Two problems so far:

- [ ] The make files need to be updated to support c++11 because of the use of `auto` in `ofMainLoop` etc. (A PR is on the way for this).
- [ ] `ofSystem` fails to compile because _popen / _pclose are not available under normal circumstances for mingw.  A solution is to implement system calls using Poco's more sophisticated cross platform system call package.  We use this extensively in ofSketch and it works great, returns handles to the processes, allows pipe interaction, etc.

**Comment by arturoc** [comment]
about ofSystem does the unix version work? it's probably easily fixed by changing the `#ifdef TARGET_WIN32` to `#if (_MSC_VER)`

**Comment by bakercp** [comment]
Hi @arturoc -- yeah, I tried that.  Apparently popen / pclose don't play nicely with mingw and c++0x.  I suppose we could try adding strict ansi requirement (e.g. https://stackoverflow.com/questions/22166633/mingw-function-not-found-when-compiled-with-std-c11).

But it begs the question -- should we go ahead and upgrade our mingw setup?  I value it because it makes ofSketch possible (it supports makefiles, etc), but it seems like a lot more effort is going into VS2015 on the windows side.

**Comment by bakercp** [comment]
Or better, it appears we should just use `-std=gnu++0x` rather than the solution for part 1 which I copied from our linux makefiles - `-std=c++0x`  I'll test it out and report back next time I'm running Windows.

**Comment by ofTheo** [comment]
@bakercp just curious - would ofSketch work with VS or is it dependent on MingGW because of the makefiles?

**Comment by bakercp** [comment]
@ofTheo ofSketch could work with VS, but the goal is to be able to download one open-source zip file and not install Visual Studio, Xcode, etc.  Currently with ofMinGW this is possible with makefiles -- and it also makes it possible to use the same Makefile-based build system for linux, osx, and windows (which is much nicer :)

**Comment by bilderbuchi** [comment]
@bakercp any updates on this?

**Comment by bakercp** [comment]
@bilderbuchi on my TODO list.  @procedural might also have some insights here -- as he's a MinGW expert :)

**Comment by procedural** [comment]
@bakercp yeah, "expert" :smile: 

MinGW-w64 doesn't produce any errors on _popen / _pclose... Sucks that CB doesn't come with MinGW-w64, but I think it should be easy to make it default compiler. It can target both 32 and 64-bit architectures.

**Comment by procedural** [comment]
> The make files need to be updated to support c++11 because of the use of auto in ofMainLoop etc. (A PR is on the way for this).

I've added `-std=gnu++11` flag to emptyExample in [this PR](https://github.com/openframeworks/openFrameworks/pull/4166), not sure if it will be enough, though!

> ofSystem fails to compile because _popen / _pclose are not available under normal circumstances for mingw.

Quick search [reveals that](http://stackoverflow.com/questions/22166633/mingw-function-not-found-when-compiled-with-std-c11):

> this happens because popen is not standard ISO C++ (it comes from POSIX.1-2001).

The solution is quite simple: use `-std=gnu++11` flag which adds popen / pclose.

**Comment by procedural** [comment]
I've just installed Code::Blocks 13.12 that uses MinGW version based on GCC 4.7.1 and it doesn't support C++11 features which openFrameworks uses extensively now, we will have to use nightly builds from their official sourceforge page: http://sourceforge.net/projects/codeblocks/files/Binaries/Nightlies/

**Comment by procedural** [comment]
Ah, but they don't provide MinGW for users... I guess we can bundle the compiler in `codeblocks_additions.zip` [that was already required for OF 0.7.4+](http://openframeworks.cc/setup/codeblocks/)

**Comment by procedural** [comment]
Also, I see TDM-GCC copyright files in MinGW folder of Code::Blocks 13.12, so we can easily replace it with newer version.

**Comment by procedural** [comment]
But we won't use GCC 5 [since its runtime library breaks C++ ABI](https://gcc.gnu.org/gcc-5/changes.html#libstdcxx) with libraries compiled with GCC 4.x.x versions...

**Comment by bakercp** [comment]
@procedural Cool -- thanks for all this research!

**Comment by procedural** [comment]
Just saw this on Phoronix: ["GCC 5 Is Causing Headaches For Ubuntu Touch Developers"]((http://phoronix.com/scan.php?page=news_item&px=GCC-5-Ubuntu-Wily-Headaches))

> associated libstdc++6 ABI changes is causing headaches for some developers

:D

**Comment by ofTheo** [comment]
@procedural - so should we use GCC 4.8.1 then? 
Here is a page on its C++11 support: https://gcc.gnu.org/gcc-4.8/cxx0x_status.html

**Comment by procedural** [comment]
@ofTheo since CB 13.12 uses TDM-GCC under the hood, I guess we can grab the latest feature reach version: [tdm64-gcc-4.9.2-3](http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1309.0/)

**Comment by procedural** [comment]
> Here is a page on its C++11 support: https://gcc.gnu.org/gcc-4.8/cxx0x_status.html
>> Minimal support for garbage collection

what the hell, c++...

**Comment by ofTheo** [comment]
@procedural - sounds good.  Looking at Clang's C++11 support "Minimal support for garbage collection" is also missing http://clang.llvm.org/cxx_status.html

**Comment by procedural** [comment]
@ofTheo good to know! I hope it will be missing for a next decade.

**Comment by arturoc** [comment]
this would be fixed by https://github.com/openframeworks/openFrameworks/pull/4208 except that we don't support code blocks any more
