### ISSUE TITLE
ofShowWindow()?

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#3868]
This is [the only place which hides a window](https://github.com/openframeworks/openFrameworks/blob/9da55d1/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L206), but currently there's no way to unhide it later in app.

I know OF will be released soon, but can we squeeze in `ofShowWindow` / `ofHideWindow` functions?

**Comment by bilderbuchi** [comment]
For 0.9.0 we will stay with the remaining bug fixes and any new critical ones that appear. New features will go into a later release, as 0.9.0 is very late already, and nearing the final phase, sorry.

**Comment by procedural** [comment]
@bilderbuchi I understand that! Thanks for clarifying this, Chris :)

After all, they can be made into an addon...

**Comment by procedural** [comment]
If anyone will be interested: https://github.com/ofnode/ofxGLFWUsefulFunctions/commit/acea455

**Comment by bilderbuchi** [comment]
I think you misunderstood. This does not mean that this feature won't make it into OF, just that it probably won't be included in 0.9.0, but later, if appropriate.
ping @arturoc: reopen?

**Comment by procedural** [comment]
Yea I know, this particular issue was created with 0.9.0 in mind, that's why I closed it :)
