### ISSUE TITLE
projectGenerator in wrong directory

### ISSUE THREAD

**Issue by mruegenberg** [openframeworks/openFrameworks#3871]
When downloading the latest nightly (v20150518), the project generator is in `apps/projectGenerator/projectGeneratorSimple/projectGeneratorSimple/`.

The result is that the build script (in my case `scrips/linux/compilePG.sh`) doesn't work. 

Changing the hierarchy so that we only have *projectGeneratorSimple* once in the path solves the problem.

**Comment by bilderbuchi** [comment]
ping @ofZach

**Comment by ofZach** [comment]
I think this is a bug in how the nightly is packaged?   Is the issue that the PG is being placed in a different place in the nightly than in the release?

**Comment by bilderbuchi** [comment]
hm, @arturoc do you know?

**Comment by arturoc** [comment]
yes this sounds like a problem with the package generation. i'll take a look

**Comment by mruegenberg** [comment]
Just to confirm: when I directly pull OF and then do `git submodule update --init`, the projectGenerator is at the right place for the compile script.

**Comment by bilderbuchi** [comment]
thanks for the follow-up!

**Comment by bilderbuchi** [comment]
@arturoc did you fix that in the meantime?
