### ISSUE TITLE
ofSetWindowPosition() / ofSetWindowShape() doesn't update OF's variables

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#3875]
The code on setup:

```cpp
  ofSetWindowPosition(23, 42);
  ofSetWindowShape(512, 108);

  cout << ofGetWindowPositionX() << endl;
  cout << ofGetWindowPositionY() << endl;
  cout << ofGetWindowWidth()     << endl;
  cout << ofGetWindowHeight()    << endl;
```
Prints:
```
-9
-8
1024
768
```
The window is changed accordingly, but OF's variables are not updated and return old init values.

**Comment by procedural** [comment]
Including `ofGetWindowSize()` / `ofGetWindowRect()`:

```cpp
  cout << ofGetWindowSize() << endl;
  cout << ofGetWindowRect() << endl;
```

Prints:

```
1024, 768, 0
0, 0, 0, 1024, 768
```

**Comment by bilderbuchi** [comment]
Is it correct in the `update()` loop? I.e. is this a problem only on the first frame?

**Comment by procedural** [comment]
@bilderbuchi yeah, it's a first frame problem apparently, in update loop it returns correct values.

**Comment by procedural** [comment]
Oh, but also if I do this in update loop:

```cpp
if (doOnce) {
  ofSetWindowShape(640, 480);
  cout << ofGetWindowSize() << endl;
}
``

I won't get the right result until the next frame...

**Comment by procedural** [comment]
Kinda funky workaround, in update loop:

```cpp
  if (doOnce)
  {
      static int doTimes = 0;
      ++doTimes;

      if (doTimes == 1) {
        ofSetWindowShape(640, 480);
      }

      if (doTimes == 2) {
        cout << ofGetWindowSize() << endl;
        doOnce = false;
      }
  }
```

**Comment by bilderbuchi** [comment]
so it only updates the variables in the next frame or at the very end of the current one? @arturoc ?

**Comment by arturoc** [comment]
i think this is just a window manager thing, you ask it to change the size/position but it doesn't do it immediately. my guess is it won't happen until the next polling of events. i'd say this is correct, it's just something that happens somehow asynchronously or at least not immediately. when you ask for the values in the first frame after changing the size or position has not changed yet so the values that it's reporting are probably correct.

**Comment by procedural** [comment]
> you ask it to change the size/position but it doesn't do it immediately

Yea, I thought so. Another workaround would be using custom `winWidth` / `winHeight` / `winX` / `winY` variables so that if you change, say, `winWidth` and set it to `ofSetWindowShape` you can be sure it will set the value of `winWidth` on the next frame. It's called shadow state in programming terminology if I correct...

**Comment by arturoc** [comment]
the problem with that is that the values might be wrong. if you set the window position to -100,-100 the window manager could decide that it's not a legal position and set it to 0,0. this is how glfw is reporting the size and position anyway so if wanted a different behaviour probably the best would be to open an issue in their repo rather than hacking it ourselves
