### ISSUE TITLE
Memory from FcInit() is not freed causing tiny memory leak

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#3878]
[FcInit()](https://github.com/openframeworks/openFrameworks/blob/df80bbd/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L332) allocates 8 kilobytes of heap memory which is not freed anywhere with [FcFini()](http://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfini.html). 

At first I wanted to add it to ofTrueTypeFont destructor, but since the library initialization is a global thing that not tied to any particular font instance, I'm thinking it would be better to add it to a function which will be called at exit of openFrameworks.

As a workaround, one can free the memory manually like so:

```cpp
#include "fontconfig/fontconfig.h"

void ofApp::exit()
{
  FcFini();
}
```

**Comment by procedural** [comment]
Ok, calling `FcFini` if `FcInit` wasn't called is harmless, so I'll PR the change to fix this.

**Comment by arturoc** [comment]
this should go in the exit callback. there's other similar calls, it should be wrapped in a call like ofTrueTypeShutdown() or similar which will call FcFini or anything else needed in other platforms

**Comment by procedural** [comment]
@arturoc ok, I'll do that!
