### ISSUE TITLE
Deprecate non-C++11 platforms

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3881]
This means deprecating 32-bit OSX.

The rationale is that C++11 has a lot of features built in that are more standard than using Poco, and can even solve some complex things like random number generation which has been hard to resolve in #3842

Is there any problem with dropping 32-bit OSX?

**Comment by pizthewiz** [comment]
Cinder has gone `x86_64`-only by default for the pending 0.9.0 release and really the only catch point revolved around 3rd party libs used in user CinderBlocks and projects (namely Awesomium). While I'm bullish on embracing a more modern OS X oF experience, it should be noted that the use of C++11 doesn't require `x86_64`.

**Comment by bilderbuchi** [comment]
> While I'm bullish on embracing a more modern OS X oF experience, it should be noted that the use of C++11 doesn't require x86_64.

So, what do we have to do to get C++11 on 32-bit OSX running?

**Comment by arturoc** [comment]
just compile it with libc++ instead of libstdc++ but then old addons with compiled libraries that use the std won't work anymore. i would do it anyway since i'd say most addons don't have static libraries and only a few of those use the std
