### ISSUE TITLE
undefined reference to ai* assimp method in ofxAssimpModelLoader

### ISSUE THREAD

**Issue by jamet** [openframeworks/openFrameworks#3882]
hello,

i cloned today's openframeworks master (01 june ), and when compiling an app with ofxAssimpModelLoader, i'm getting the following error : 
/home/acryl/mapping/dev/openframeworks/git01062015/openframeworks/apps/devApps/lpmtX2/../../../addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp|37|undefined reference to `aiImportFileExWithProperties'|
and 20 more errors concerning assimp references.

i didn't have this problem before this commit : 
https://github.com/openframeworks/openFrameworks/commit/9839df42393dc078829b1a6fdf9a27116c3cbd3a

it seems codeblocks already knows about assimp libs since it can give a list of assimp methods, so it might not be a include issue....

don't really understand what is wrong in here....

can anyone try to reproduce or is it my laptop is badly configured?

(build failling on Asus ux303ln, lubuntu 14.04, kernel 3.19)

**Comment by arturoc** [comment]
we changed the version of assimp recently to 3 (we were using 2 before).
In linux the library is now installed through the
install_dependencies.sh script when you install OF so you'll need to
rerun the script now to install the new libraries

**Comment by jamet** [comment]
hi @arturoc ,

i rerun install_dependencies.sh, but it seems all deps are already installed : 

installing OF dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
Note, selecting 'libpython2.7-stdlib' instead of 'python-argparse'
freeglut3-dev is already the newest version.
g++ is already the newest version.
libasound2-dev is already the newest version.
libglew-dev is already the newest version.
libglu1-mesa-dev is already the newest version.
libpython2.7-stdlib is already the newest version.
libraw1394-dev is already the newest version.
libsndfile1-dev is already the newest version.
libusb-1.0-0-dev is already the newest version.
libxmu-dev is already the newest version.
libxxf86vm-dev is already the newest version.
libassimp-dev is already the newest version.
libfreeimage-dev is already the newest version.
libopenal-dev is already the newest version.
libopencv-dev is already the newest version.
librtaudio-dev is already the newest version.
libcairo2-dev is already the newest version.
libfreetype6-dev is already the newest version.
libgl1-mesa-dev-lts-utopic is already the newest version.
libpulse-dev is already the newest version.
libssl-dev is already the newest version.
libudev-dev is already the newest version.
python-lxml is already the newest version.
libdrm-dev is already the newest version.
libgtk-3-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
installing gstreamer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer1.0-alsa is already the newest version.
gstreamer1.0-plugins-base is already the newest version.
gstreamer1.0-plugins-good is already the newest version.
gstreamer1.0-pulseaudio is already the newest version.
gstreamer1.0-x is already the newest version.
libgstreamer-plugins-base1.0-dev is already the newest version.
libgstreamer1.0-dev is already the newest version.
gstreamer1.0-libav is already the newest version.
gstreamer1.0-plugins-bad is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
acryl@ultratux:~/mapping/dev/openframeworks/git01062015/openframeworks/scripts/linux/ubuntu$ dpkg -l |grep assimp
ii  libassimp-dev                               3.0~dfsg-2                                         amd64        3D model import library (development)
ii  libassimp3                                  3.0~dfsg-2                                         amd64        3D model import library


so as i understand, i-ve already installed libassimp-dev 3.0.


could it be a $PATH issue? but it seems strange since codeblocks can autocomplete ai methods....

(my $PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

and assimp libraries are located in /usr/include/assimp)

**Comment by arturoc** [comment]
mmh, yeah sorry i changed the install dependencies scripts but never updated the addon config so it uses the library from the system. will do it later but by now you can add to your project's config.make in the LDFLAGS section:

```make
PROJECT_LDFLAGS=-lassimp
```

**Comment by jamet** [comment]
that seems to make the thing OK and compiling, thanks a lot @arturoc !!!

should i close the issue?

**Comment by arturoc** [comment]
no leave it open, i'll close it when i fix the original problem without need to change the config file
