### ISSUE TITLE
assimp materials don't behave as they did

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#3887]
this is how the assimp example looks now:

![screenshot from 2015-06-02 10 52 59](https://cloud.githubusercontent.com/assets/48240/7932042/add1f3b4-0915-11e5-94f0-fe7ebaa0dcc9.png)

not sure what's going on, i've also tested other lighting examples and all look as they used to so i doubt the problem is in ofLight or ofMaterial

**Comment by vade** [comment]
I can maybe take a look @arturoc

**Comment by kylemcdonald** [comment]
for reference, here is what it used to look like (0.8.4):

![screen shot 2015-06-14 at 13 41 48](https://cloud.githubusercontent.com/assets/157106/8149693/1dabfb6a-129b-11e5-870f-4a9eeb2415f3.png)

**Comment by ofTheo** [comment]
I think this is due to the change in ofFilePath::getEnclosingDirectory() ( see: #3940 )

**Comment by ofTheo** [comment]
ps @arturoc did you fix the scale issue with assimp?
I'm putting an issue in for it - did you manually scale up the astroboy in your above screenshot?

**Comment by arturoc** [comment]
i'll add the trailing slash but that shouldn't be a problem. in any case this bug is from 2 weeks ago when getEnclosingDirectory was still using poco

**Comment by arturoc** [comment]
also the texture is really there, if you look closely the colors are there they are just almost white, it's something related with the materials colors probably

**Comment by arturoc** [comment]
actually that seems to fix it :) i guess i tried while developing the port to std::filesystem. sorry for the noise.

the assimp addon shouldn't rely on that trailing slash though it should be using ofFilePath::join instead

**Comment by arturoc** [comment]
btw, no idea about the scale issue, it's working fine now

**Comment by arturoc** [comment]
actually it's super small when compiling for emscripten, so it's possibly an openGL ES thing but no idea where it's coming from

**Comment by ofTheo** [comment]
oh weird - on OS X its also tiny.  Is there a chance your using a different ( or newer ) version of assimp on  linux?

**Comment by arturoc** [comment]
mmh, yeah that might be it, i'm using whatever is in the system repos which seems to be 3.0 emscripten which is using the same version as other platforms has the same problem so it's surely something in assimp. perhaps they have some scaling factor in later versions?
