### ISSUE TITLE
Change ofRandom implementation to uniform_real_distribution

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#3890]
As soon as we support C++11 on all platforms (currently lacking MacOS 32bit support), we should switch the `ofRandom*` implementations to use the [built-in](http://www.cplusplus.com/reference/random/uniform_real_distribution/) `uniform_real_distribution`instead of self-made code. 
Ref. #3842 
cc @2bbb @kylemcdonald @arturoc

**Comment by 2bbb** [comment]
:+1:

**Comment by bilderbuchi** [comment]
connected #3881

**Comment by DomAmato** [comment]
Reviving this issue since it ran into a wall during 0.9.0

See discussion here:
https://github.com/openframeworks/openFrameworks/pull/4262 

and relevant code 
https://github.com/DomAmato/openFrameworks/commit/1d74489440137a8db62997e9150903b80c74102c

**Comment by bilderbuchi** [comment]
@arturoc in the same vein of closing #1062, we can also close this one since it was decided to switch to glm, right?

**Comment by arturoc** [comment]
no, glm doesn't cover this, it's just for vector math.

**Comment by bilderbuchi** [comment]
ah ic.
