### ISSUE TITLE
ofPath.h : Thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#3891]
Using OS X 10.10 / XCode 6.3.2
I'm having the following issues to compile

/openFrameworks/libs/openFrameworks/graphics/ofPath.h:405:9: Thread-local storage is not supported for the current target

```c++
#if __cplusplus>=201103
	static thread_local ofTessellator tessellator;
```

/openFrameworks/libs/poco/include/Poco/Net/StreamSocket.h:171:3: Expected identifier

```c++
private:
	enum
	{
		BUFFER_SIZE = 1024
	};
```

**Comment by danoli3** [comment]
Same Applies for iOS. Also it was sneakily declared in the header as well.. Pushing PR now.
