### ISSUE TITLE
StreamSocket.h:171:3: Expected identifier

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#3892]
Using OS X 10.10 / XCode 6.3.2
/openFrameworks/libs/poco/include/Poco/Net/StreamSocket.h:171:3: Expected identifier

```c++
private:
	enum
	{
		BUFFER_SIZE = 1024
	};
```

**Comment by bilderbuchi** [comment]
looks like a bug in poco, not OF? @arturoc @bakercp

**Comment by bakercp** [comment]
OF and poco version info?

**Comment by bakercp** [comment]
Also, have you cleaned your project lately?

**Comment by dimitre** [comment]
I've used project generator. I've just created an empty project there and it compiles OK for 32 bit and for 64 I have some errors:
![screen shot 2015-06-04 at 4 45 08 pm](https://cloud.githubusercontent.com/assets/58289/7992943/261e783c-0ad9-11e5-874d-93b3c396fc86.png)

I'll try to discover which Addon is causing StreamSocket error and in which Schemes.

**Comment by bakercp** [comment]
What version of OF are you using? 64 bit doesn't work for 0.8.4 on OSX.

**Comment by arturoc** [comment]
@bakercp i think this is latest master i fixed another problem reported by @dimitre this morning on master.

@dimitre do the examples work or do you get compiling errors there too?

**Comment by dimitre** [comment]
@arturoc @bakercp yes it is git master. I don't know if the examples are working because buildAllExamples.sh is not running well here
```
-----------------------------------------------------------------
no xcode project for ../../examples/addons/assimpExample
-----------------------------------------------------------------
no xcode project for ../../examples/addons/kinectExample
-----------------------------------------------------------------
no xcode project for ../../examples/addons/networkTcpClientExample
-----------------------------------------------------------------
no xcode project for ../../examples/addons/networkTcpServerExample
-----------------------------------------------------------------
no xcode project for ../../examples/addons/networkUdpReceiverExample
-----------------------------------------------------------------
no xcode project for ../../examples/addons/networkUdpSenderExample
```

**Comment by arturoc** [comment]
yes you need to run the project generator over the examples to generate the project, can you check with one and see if that works?

**Comment by dimitre** [comment]
sure

**Comment by dimitre** [comment]
I've just build clean and it is not compiling in 64bit. in 32bit it is running OK
![screen shot 2015-06-04 at 6 11 39 pm](https://cloud.githubusercontent.com/assets/58289/7994626/3a5900ea-0ae5-11e5-9caf-fb61dca2d901.png)

**Comment by bilderbuchi** [comment]
@arturoc @bakercp any follow-up on this?

**Comment by bilderbuchi** [comment]
@dimitre is still occuring in latest master?

**Comment by bilderbuchi** [comment]
closing as there's no follow-up by the reporter.

**Comment by dimitre** [comment]
I've just discovered. Problem was a redefinition of #define BUFFER_SIZE 512 both in ofxSvg and some FFT library together. Thanks
