### ISSUE TITLE
Build OpenCV 3.0 Libraries

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3893]
Just released today: http://opencv.org/opencv-3-0.html

| osx | vs | win_cb | ios | android | emscripten |
|-----|-------|---------|-------------|-------------|----|--------|-----|---------|---------|
|   ✗      | ✗  | ✗      | ✗   | ✗       |    ✗     |

**Comment by danoli3** [comment]
Is this something tagged for 0.9.0?

**Comment by bilderbuchi** [comment]
hopefully not, as this one is _strictly_ a new feature...

**Comment by kylemcdonald** [comment]
i've tagged it 0.9.1 so it doesn't keep the release back, but to be clear, i think the API should be backwards compatible with ofxOpenCv.

**Comment by oxillo** [comment]
MSYS2 now comes with opencv 3.0 (#4478).

**Comment by bilderbuchi** [comment]
@arturoc would be great if you could leave comments saying why you close issues... I'm assuming this is already implemented?

**Comment by arturoc** [comment]
yeah we compiled and merged opencv 3.1 for every platform yesterday,
