### ISSUE TITLE
Request to add setLineWidth warning in ofGLProgrammableRenderer

### ISSUE THREAD

**Issue by corybarr** [openframeworks/openFrameworks#3896]
Hello. I was tracking down why ofSetLineWidth() and glLineWidth() wasn't having an effect. There's a very useful warning commented out in ofGLProgrammableRenderer::setLineWidth in v0.8.4. It looks like it's gone from master. How would people feel about uncommenting it and putting it back in? It would have helped me out.

Thanks!

**Comment by ofTheo** [comment]
Is the comment this?
I wouldn't be opposed. @arturoc ? 

```
//----------------------------------------------------------
void ofGLProgrammableRenderer::setLineWidth(float lineWidth){
	// tig: glLinewidth is 'kind of' deprecated.
	// http://www.opengl.org/registry/doc/glspec32.core.20090803.pdf
	// p.330: "LineWidth values greater than 1.0 will generate an
	// INVALID_VALUE error".
	// use geometry shaders to draw lines of varying thickness...
	
#ifndef TARGET_OPENGLES
	//ofLogVerbose("ofGLProgrammableRenderer") << "setLineWidth(): has no effect in OpenGL 3.2+;
	//<< "use a geometry shader to generate thick lines";
#else
	glLineWidth(lineWidth);
#endif
}
```

**Comment by arturoc** [comment]
yes i'm ok too, let's change it to something else though, asking people to implement a geom shader to get thick lines is kind of scary :) OF should do it internally but meanwhile let's just tell that line width is not supported on gl3+

**Comment by corybarr** [comment]
Yep, that's the comment @ofTheo. What about bumping the level up from ofLogVerbose to something most people would see by default?

I got it working with a geometry shader, but it brings up a lot of questions about how to best abstract it and similar things while still using other shaders. Perhaps more expressiveness is just simply going to mean more work.

**Comment by procedural** [comment]
Related issue: https://github.com/openframeworks/openFrameworks/issues/3460

:)

**Comment by bilderbuchi** [comment]
thank you @procedural, closing this as a near-enough duplicate.
