### ISSUE TITLE
Weird texture rendering on a ofSpherePrimitive

### ISSUE THREAD

**Issue by kontur** [openframeworks/openFrameworks#3902]
Hey,

I am a beginner with OF and 3D programming, so forgive me if this turns out not to be a bug but instead failure to use correctly.

Trying to render a simple 512x512 texture on a ofSpherePrimitive in a iOS openFrameworks project I get very odd results:

![rendering issue preview](http://forum.openframeworks.cc/uploads/default/optimized/2X/9/9fe7f3b622e6e208ef1560eb1b9e2ce0f0c990af_1_375x500.PNG)

Here is a basic checker pattern applied to a sphere, and you can see on the bottom part of the sphere there are parts that appear transparent and the texture there gets rendered from the back facing inside half of the sphere. The code for this [available in a repository here](https://github.com/kontur/openframeworks-ios-sphere-texturing-problem).

Even clearer you can see the problem with red illumination and a map applied. In this example, the reddish parts are rendered as I'd expect them, and some parts of the sphere show this odd "transparent" behaviour and instead render the texture on the inside of the back facing side with no ambient light.

![rendering issue preview 2](http://forum.openframeworks.cc/uploads/default/optimized/2X/a/a6c738690aa2ef660e05dac219f88db63c514c32_1_375x500.PNG)

The code that is used to render the sphere is essentially this:
```
void ofApp::setup(){
    r = 0;
    sphere.setRadius(100);
    texture.loadImage("test.png");
}

//--------------------------------------------------------------
void ofApp::update(){
    r += 0.25;
}

//--------------------------------------------------------------
void ofApp::draw(){
    ofPushMatrix();
    
    ofTranslate(ofGetWidth() / 2, ofGetHeight() / 2);
    ofRotateY(r);
    
    texture.getTextureReference().bind();
    sphere.draw();
    
    texture.unbind();
	
    ofPopMatrix();
}
```

I noticed that the "transparent" parts rotate with the sphere, and also those "stripy" transparent parts rendering the back side correlate with polygons on the back side, as if you were partially "seeing through" the geometry.

Any idea what is going wrong here and whether or not this is indeed a bug or instead expected behaviour?

**Comment by kontur** [comment]
Forgot to mention that the screenshots are from a iPad mini with iOS 8.01 and created with the of_v0.8.4_ios_release.

**Comment by tgfrerer** [comment]
Hey @kontur, two things come to mind- 

1. Try enabling backface culling 
2. Try disabling arb tex when loading the texture (although it should work without)

Maybe consider checking out the openFrameworks forum for hints & help. This also, so that if someone else runs into the same issue, there is a permanent record of the way to solve it =)

**Comment by kontur** [comment]
Thanks @tgfrerer 

I had previously tried `ofEnableArbTex()` and `ofEnableDepthTest()` but assumed that either by default or automatically openframeworks would enable backface culling.

After some searching, adding these two lines before drawing the texture and then rendering the sphere solved this, so it's a matter of Open GL instructions, I assume:

```
glEnable(GL_CULL_FACE); // Cull back facing polygons
glCullFace(GL_BACK);
````

Not sure though if this issue is thus resolved as solved application problem, or if either the results should be more predictable or the documentation more explicit? To a beginner this seems pretty weird default behaviour.

**Comment by kontur** [comment]
It turns out that this works fine also by explicitly setting the window mode in the generated `main.mm`. The problem, it seems to me, is that the ProjectGenerator creates a different kind of `main.mm` that doesn't use `ofAppiOSWindow` nor has depth buffering by default.
See the [forum topic here](http://forum.openframeworks.cc/t/texture-on-ofsphereprimitive-breaks/19824).

I'll close this issue and open a inquisitive issue checking why this is.
