### ISSUE TITLE
propose to replace `ofToString` if environments can use C++11.

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#3904]
i wanna propose to replace `ofToString` about, on environments that can use C++11.

like this:

```cpp
template <class T>
typename enable_if<!is_arithmetic<T>::value, string>::type ofToString(const T& value) {
	ostringstream out;
	out << value;
	return out.str();
}

template <class T>
typename enable_if<is_arithmetic<T>::value, string>::type ofToString(T value) {
	return to_string(value);
}
```

so, on my environment (Xcode6.3.2/clang on OSX 10.10), this code is 2-3 times faster than current version.

test with this:

```cpp
#include <iostream>
#include <string>
#include <sstream>
#include <type_traits>

struct SimpleStopWatch {
	void start() {
		_start = std::chrono::high_resolution_clock::now();
	}
	
	template <typename T = std::chrono::nanoseconds>
	typename T::rep rap() {
		_end = std::chrono::high_resolution_clock::now();
		return std::chrono::duration_cast<T>(_end - _start).count();
	}
	
	template <typename T = std::chrono::nanoseconds>
	typename T::rep getLastRap() const {
		return std::chrono::duration_cast<T>(_end - _start).count();
	}
	
	auto getLastRapMilliseconds() const 
	-> decltype(getLastRap<std::chrono::milliseconds>()) {
		return getLastRap<std::chrono::milliseconds>();
	}
	
	auto getLastRapMicroseconds() const 
	-> decltype(getLastRap<std::chrono::microseconds>()) {
		return getLastRap<std::chrono::microseconds>();
	}
	
	auto getLastRapNanoseconds() const
	-> decltype(getLastRap<std::chrono::nanoseconds>()) {
		return getLastRap<std::chrono::nanoseconds>();
	}
	
	decltype(std::chrono::high_resolution_clock::now()) _start, _end;
};

using namespace std;

template <class T>
string ofToString(const T& value){
	ostringstream out;
	out << value;
	return out.str();
}

template <class T>
typename enable_if<!is_arithmetic<T>::value, string>::type ofToString11(const T& value) {
	ostringstream out;
	out << value;
	return out.str();
}

template <class T>
typename enable_if<is_arithmetic<T>::value, string>::type ofToString11(T value) {
	return to_string(value);
}

int main(int argc, char *argv[]) {
	SimpleStopWatch w;
	long long elapsed;
	string s;
	
	w.start();
	for(int i = 0; i < 1000000; i++) s = ofToString(i);
	elapsed = w.rap();
	std::cout << "int of: " << elapsed << std::endl;
	
	w.start();
	for(int i = 0; i < 1000000; i++) s = ofToString11(i);
	elapsed = w.rap();
	std::cout << "int 11: " << elapsed << std::endl;

	w.start();
	for(int i = 0; i < 1000000; i++) s = ofToString(float(i));
	elapsed = w.rap();
	std::cout << "float of: " << elapsed << std::endl;
	
	w.start();
	for(int i = 0; i < 1000000; i++) s = ofToString11(float(i));
	elapsed = w.rap();
	std::cout << "float 11: " << elapsed << std::endl;

	return EXIT_SUCCESS;
}
```

and results is:

```
integer current: 479583704
integer C++11  : 161461449
float current: 568796952
float C++11  : 334966664
double current: 620954961
double C++11  : 314523148
```

please opinion or more good idea!!

**Comment by bilderbuchi** [comment]
hm, shouldn't the function parameter in both versions be `const`?

**Comment by 2bbb** [comment]
@bilderbuchi 
thanks for comment.

i think that it may attach `const`. but (i think) that is not important.

`template <class T>
typename enable_if<!is_arithmetic<T>::value, string>::type ofToString(const T& value)` for not arithmetic type, and `template <class T>
typename enable_if<is_arithmetic<T>::value, string>::type ofToString(T value)` for arithmetic type.
version of arithmetic type, that's parameter is not reference. just copy.

if you think to must attach, i do attach.

**Comment by 2bbb** [comment]
@bilderbuchi 

i was thinking about this.
i agree to add `const`.
that is more better to reading the codes.

and, similarly, i think better to use the functions of C++11 for ofToDouble, and others.
like this:

```cpp
double ofToDouble(const string &doubleString) {
	return stod(doubleString);
}
```

are those not bad as refactoring?
if those are not bad, i willi send PR after rewrite concretely about those, and please discuss again with new codes.
otherwise... i will think again.

**Comment by bilderbuchi** [comment]
I think that in current master, we can use c++11 on all platforms, so it's not necessary to have two versions. correct, @arturoc ?
and yes, refactoring to use C++11 functionality would be welcomed as far as I know.

**Comment by arturoc** [comment]
something that i doubt is if we should begin to deprecate functions that are already in the std. now you can do `to_string(5)` or `to_string(ofGetFramerate)` which are even faster than our impl with stringstreams so probably we should just mark those as deprecated with a message pointing out which is the std equivalent

**Comment by bilderbuchi** [comment]
yeah, that would be an even better solution.

**Comment by danoli3** [comment]
ofToString could just wrap the c++11 to_string(*)

**Comment by arturoc** [comment]
i think we shouldn't wrap things that are simple enough on the stl. before we were wrapping ofToString cause the implementation using a stringstream... was kind of convoluted but to_string is simple enough that probably doesn't make sense to rewrap it. we can keep it deprecated for a while since it's used a lot but i would remove it for the next major version

**Comment by 2bbb** [comment]
oh yeah, i agree to don't wrap.

i have just idea.
C++11 has [[deprecated("message")]]

so, we can notice deprecated as easier in C++11.
is only we notice [[deprecate("use to_string")]] better solution?
if it is better solution, i agree all of that.

**Comment by arturoc** [comment]
yes didn't remember about the deprecated annotation in c++11, we have a multi platform macro, OF_DEPRECATED for this but i guess it's better to use this from now on.

**Comment by ofTheo** [comment]
I think we could have that function and mark it deprecated for a long time.
Mainly because getting rid of it even at the next major version would probably make a good % of addons break.

**Comment by 2bbb** [comment]
okay.
maybe this problem (use deprecated attribute or OF_DEPRECATED macro) is i can't judge.
i think, this problem is judged by core oF members.
i will follow to decided things, and i can only proposing a idea.
i want the cool solution about this!
:+1:

**Comment by arturoc** [comment]
thinking of it our implementation can do things like:

```
ofToString(ofVec3f(0,0))
```
which std's can't, right? in that case perhaps your original proposal is better,

**Comment by 2bbb** [comment]
@arturoc 
yeah! i think, problem of `ofToString(ofVec3f(0, 0));` is important.
so, i believe, openFrameworks must support openFrameworks internal type.
i will think about this, as best solution.
just a idea, i think, solution is

```
return to_string(v.x) + "," + to_string(v.y) + "," + to_string(v.z);
```

but, perhaps, there are more better solution.
discuss about like this, is more constructive. i believe.

i will think again about complicated types of internal type of oF.
thanks for giving the direction.

**Comment by arturoc** [comment]
the current solution already works for anything that implements the << operator so there's no need change that. i think your original proposal is correct

**Comment by 2bbb** [comment]
@arturoc 
hmmmm…?
sorry, i can't understand your opinion.

do you say "correct answer is only deprecated, not extend ofToString"?
or, "extend ofToString as of internal types"?

in the former case, maybe i can do nothing, and close this issue.
in the latter case, we can propose some code, and we can discuss about it.

which is your opinion? or other?

**Comment by 2bbb** [comment]
(and sorry if i did a rude expression.)

**Comment by bilderbuchi** [comment]
> thinking of it our implementation can do things like:
> ofToString(ofVec3f(0,0))
> which std's can't, right? in that case perhaps your original proposal is better,

[apparently](http://stackoverflow.com/a/5171750/599884) you can make `to_string` work with custom classes, so it's just a matter of implementing that for our classes we want to be able to represent as string.

**Comment by arturoc** [comment]
@2bb no not at all :)  i was just trying to say that what you posted in the first post:

```
template <class T>
typename enable_if<!is_arithmetic<T>::value, string>::type ofToString(const T& value) {
    ostringstream out;
    out << value;
    return out.str();
}

template <class T>
typename enable_if<is_arithmetic<T>::value, string>::type ofToString(T value) {
    return to_string(value);
}
```

would be the most correct if to_string `won't` work with custom classes.

@bilderbuchi, we already do that but i think that only works with << not with to_string. not sure though

**Comment by bilderbuchi** [comment]
> @bilderbuchi, we already do that but i think that only works with << not with to_string. not sure though

argh you're correct, in haste I misread the SO question. :-/

**Comment by 2bbb** [comment]
@arturoc @bilderbuchi 
thanks a lot. maybe i understand...(?)

in that sense, i think my proposal is correct.

surely, `to_string` won't work with custom classes.

and, `typename enable_if<is_arithmetic<T>::value, string>::type` enables only case of `T` is arithmetic type, (i.e., `unsigned char`, `short`, `double`, etc...).
if we call the `ofToString(ofVec3f());`, then `ostringstream` version will be called.

**Comment by 2bbb** [comment]
sorry, i made a mistake. so, i wrote
> C++11 has [[deprecated("message")]]
but, [[deprecated]] attribute from C++14.

maybe we continue to use `OF_DEPRECATED` and `OF_DEPRECATED_MSG`. (as an example: newest Visual Studio doesn't support [[deprecated]] now.)

**Comment by arturoc** [comment]
yeah i realized about this later, i'll remove the ones i added. we can't use the macro by now for typedefs. also for this i don't think we should deprecate anything just send a PR with your original proposal

**Comment by 2bbb** [comment]
i sent a PR #3948 
and please do discussion on this PR.
