### ISSUE TITLE
Poco libraries and OSX/Cmake

### ISSUE THREAD

**Issue by growlerpig** [openframeworks/openFrameworks#3905]
Hi, the forum is down so I hope it's OK to raise this issue here. I'm trying to compile the master branch under OSX10.10 w/ CMake. Getting a bunch of Poco-related linker errors (though not as many as if the libraries weren't linked at all).

The errors disappear in x86_64, it's just in 32bit that they turn up.

`  "Poco::TextConverter::convert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ofTrueTypeFont::getStringAsPoints(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, bool) const in ofTrueTypeFont.cpp.o
      ofTrueTypeFont::createStringMesh(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float, float, bool) const in ofTrueTypeFont.cpp.o
      ofTrueTypeFont::drawStringAsShapes(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float, float) const in ofTrueTypeFont.cpp.o
  "Poco::SystemException::SystemException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      Poco::MutexImpl::unlockImpl() in ofEasyCam.cpp.o
      Poco::MutexImpl::lockImpl() in ofEasyCam.cpp.o
      Poco::MutexImpl::unlockImpl() in ofMainLoop.cpp.o
      ...`

It goes on... and I also get two non-Poco linker errors:
 ` "RtAudio::openStream(RtAudio::StreamParameters*, RtAudio::StreamParameters*, unsigned long, unsigned int, unsigned int*, int (*)(void*, void*, unsigned int, double, unsigned int, void*), void*, RtAudio::StreamOptions*, void (*)(RtError::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))", referenced from:
      ofRtAudioSoundStream::setup(int, int, int, int, int) in ofRtAudioSoundStream.cpp.o
  "ofParameterGroup::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const", referenced from:
      ofxOscReceiver::getParameter(ofAbstractParameter&) in ofxOscReceiver.cpp.o`

I checked and the libraries contain the exact symbols mentioned, so I don't understand why the linker won't see them... Any clues?

I updated Poco through the Apothecary. The project compiled fine under 0.8.4, before I started adapting it to C++11 / oF 0.9.0.

**Comment by bilderbuchi** [comment]
osx 32bit and c++11 currently don't work together. there is currently work ongoing to fix this: #3913
