### ISSUE TITLE
Minor project generator issues (iOS Platform)

### ISSUE THREAD

**Issue by mhashmi** [openframeworks/openFrameworks#3915]
Hi all,

A couple of minor issues when generating projects for iOS: 

 * The ofxiOS addon appears to get linked twice, resulting in duplicate symbol errors
 * When the OpenCV addon is included, the AssetsLibrary.framework does not get linked

Originally reported on the following [forum thread](http://forum.openframeworks.cc/t/some-errors-when-generating-ios-projects-git-checkout/19894)

Thanks.

**Comment by bilderbuchi** [comment]
pinging @ofZach

**Comment by danoli3** [comment]
Fixed.
