### ISSUE TITLE
opencv 32bit libs for vs2015

### ISSUE THREAD

**Issue by nykwil** [openframeworks/openFrameworks#3916]
The opencv libs are compiled with vs2012 and aren't compatible with the new build. 

Related to #3910

**Comment by bilderbuchi** [comment]
pinging @openframeworks/windows

**Comment by DomAmato** [comment]
@elliotwoods compiled the 64 bit ones. Did you change the script to get it to compile or how did you go about doing it?

**Comment by bilderbuchi** [comment]
ping @openframeworks/windows

**Comment by DomAmato** [comment]
I made a new PR with only the lib updates and the apothecary script update https://github.com/openframeworks/openFrameworks/pull/4086
