### ISSUE TITLE
vs2015 win32 High Res Timing linking error

### ISSUE THREAD

**Issue by patrickFuerst** [openframeworks/openFrameworks#3921]
When I try to run examples with VS2015 and the latest libs I get the following linking error. 

```
 Creating library bin\vboExample_debug.lib and object bin\vboExample_debug.exp
2>openframeworksLib_debug.lib(ofAppRunner.obj) : error LNK2019: unresolved external symbol __imp__timeBeginPeriod@4 referenced in function "void __cdecl ofInit(void)" (?ofInit@@YAXXZ)
2>openframeworksLib_debug.lib(ofAppRunner.obj) : error LNK2019: unresolved external symbol __imp__timeEndPeriod@4 referenced in function "void __cdecl ofExitCallback(void)" (?ofExitCallback@@YAXXZ)
2>bin\vboExample_debug.exe : fatal error LNK1120: 2 unresolved externals
```
To resolve this I added lib winmm.lib, but I'm not sure if this is the right way and why it shows me these linking error since I updated to VS2015. 
```
#if defined (TARGET_WIN32)
#include <mmsystem.h>
#pragma comment(lib, "winmm.lib")
#endif
```

Oh and of course if I undefine "WIN32_HIGH_RES_TIMING" the error also disappears 

Does someone else had the same errors, or should the lib be included somewhere else ?

**Comment by arturoc** [comment]
i thought i had fixed this by including winmm.lib in the project files, i might have not pushed that chnage. let me check

**Comment by arturoc** [comment]
i had fixed it in the c++11 branch but not in master, i just merged that so it should be fixed. feel free to reopen if it's still a problem

**Comment by patrickFuerst** [comment]
thanks. works now
