### ISSUE TITLE
Apothecary - OpenSSL 1.0.2c

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3923]
Updated to OpenSSL 1.0.2c (latest).

Will require libraries to be updated with Apothecary: (this will also means Poco needs recompiling)

### OpenSSL 1.0.2c current build status:

|                 | osx | vs | win_cb | ios | android |
|--------------|-----|-------|---------|-------------|-------------|----|--------|-----|---------|
| Merged? |   ✗   | ✓  | ✗      | ✗   | ✗       |
| PR          |         | #3895  |       | #3956  |        |

**Comment by bilderbuchi** [comment]
question: do we really need to update openssl for every sub-patch-level update? we currently don't have the binaries outside the repo, and all the lib recompiles will really bloat the repo. :-(

**Comment by danoli3** [comment]
We can do a historical delete for targeted archives in the repo to lighten the history. 

In this case though we have to get it up to date as we didn't have the VS libs until 1.0.2c was released. So those libs are built against it.

With SSL, it only seems to have updates every 4-6 months. 
Even minor patches seem to fix serious holes in security (heart bleed and other code words were patched in minor releases for example). If someone wants to use https:// with the file loader it is really necessary to keep this up to date.

**Comment by jedahan** [comment]
@bilderbuchi

At first glance, it would seem prudent to remove old archives using a tool like https://github.com/rtyley/bfg-repo-cleaner ... this would certainly reduce the initial clone of oF, but I would advise against it.

For people who want a lightweight repo (and I prefer a light/code-only repo, espcially with a tiny SSD...), we have two good options: git clone --depth=1, and downloading a release.

As someone who has spent a lot of time hunting down ancient archives and software (1995-1980s) for preservation and re-creation, I am forever grateful to organizations and people who keep old archives around.

In 20+ years, maybe someone will want to run software we created today, and having a git history with the compiled libs might be the only way / best way to do that.

That said, maybe the releases are a good enough archive of oF for archival/preservation purposes, and cleaning binaries is actually OK. I think as more and more statically compiled libraries switch to using apothecary this might resolve itself.

/2cents

**Comment by danoli3** [comment]
As long as https://github.com/rtyley/bfg-repo-cleaner doesn't touch the "Releases" binary's we have the best of both worlds.

**Comment by bilderbuchi** [comment]
> As long as https://github.com/rtyley/bfg-repo-cleaner doesn't touch the "Releases" binaries we have the best of both worlds.

sorry, but no. the biggest problem is that ripping the binaries out of the repo (using whichever tool) is going to break the repo for _all_ the people who have forked OF (because you're rewriting public history). 
Also, as clarification, the "Releases" zips are unconnected to the git repo binary bloat issues, and are _not_ our regular packaged releases, but archives of repo snapshots.

Please see the [wiki article](https://github.com/openframeworks/openFrameworks/wiki/Moving-binaries-out-of-the-repo) and #1805 (and the devlist) for previous and further discussion, let's remain ontopic here.

**Comment by liquidzym** [comment]
i'm trying to rebuild the openssl with vs,but the openssl.sh script saying that :line 402 :conditional binary operator expected

**Comment by liquidzym** [comment]
ok,i did complied openssl anyway,but seems missing opensslconf_vs.h file afterwards which required for compiling poco
