### ISSUE TITLE
Apothecary - Poco with OpenSSL 1.0.2c

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3924]
With the fixes in OpenSSL 1.0.2c it is required to rebuild Poco.
https://github.com/openframeworks/openFrameworks/issues/3923

### Poco current build status with OpenSSL 1.0.2c:

| osx | linux | linux64 | linuxarmv6l | linuxarmv7l | vs | win_cb | ios | android |
|-----|-------|---------|-------------|-------------|----|--------|-----|---------|
|   ✗ |   ✗   |   ✗     |     ✗       |       ✗     | ✓ |   ✗    |   ✗ |     ✗   |

**Comment by bakercp** [comment]
I can rebuild osx, arm6/7 and linux32/64.  I'm also looking working on win_cb/mingw 32/64.
