### ISSUE TITLE
Apothecary - Boost 1.58.0

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3926]
Boost for C++17 features for filesystem:

| | osx | vs | win_cb | ios | android | emscripten |
|----|-----|-------|---------|-------------|-------------|----|--------|-----|---------|-------|
| Merged? |   ✓      | ✓  | ✓      | ✓   | ✓       |✓   |
| PR |  #3913    | #3913  |  #3913     |  #3955 |   #3913   | #3913   |

**Comment by danoli3** [comment]
I'll get the iOS part going @arturoc

**Comment by arturoc** [comment]
thanks so much!

**Comment by danoli3** [comment]
Boost for iOS Completed with #3933

**Comment by danoli3** [comment]
Tested and working! All the new iOS PR's working well

**Comment by bilderbuchi** [comment]
so, close this?

**Comment by danoli3** [comment]
Yeah this is completed.
