### ISSUE TITLE
Apothecary - uricpp

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#3927]
| | osx | vs | win_cb | ios | android | emscripten | linuxarmv6 | linuxarmv7 |
|----|-----|-------|---------|-------------|-------------|----|--------|-----|---------|-------|
| Merged? |   ✓      | ✓  |  ✓      | ✓   | ✓       |✓   | ✗ | ✗|
| PR |  #3913   |  #3913   |      |  #3952   | #3913       |#3913   |  |  |

**Comment by danoli3** [comment]
@arturoc do you think that OSX patch should apply for the iOS version as well?

**Comment by arturoc** [comment]
might be, in any case it doesn't change the functionality at all so probably better to apply it just in case

**Comment by danoli3** [comment]
iOS Merged.

**Comment by arturoc** [comment]
closed by https://github.com/openframeworks/openFrameworks/commit/84793fa1f767bebbcae187d3e71a917f6b18675a
