### ISSUE TITLE
visual studio 2015RC link times very slow

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#3962]
Adding the `/time` link option in VS and profiling the link times tells me that VS spends about 10 seconds linking on my machine. It's a reasonably fast machine. 

#3961 should speed up things a little bit, but that's only happening after the linker stage has been passed.

One build output message might be revealing: 

`cairo-static.lib(cairo.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance`

Which means that the linker has to enable link time code generation because of cairo. This also spills out a ton of warnings onto the console: 

https://gist.github.com/tgfrerer/c1fc8616509c5418b9c3

--

@DomAmato, (reading the warnings it seems you originally compiled this module =) ) - I wonder if it were possible to compile cairo [without the /GL flag](https://msdn.microsoft.com/en-us/library/0zza0de8.aspx). Without it, I'd hope we could be able to do incremental linking for debug builds, and wouldn't see the cairo warnings spill onto the console every build. 

Btw, reading [this](https://bugzilla.mozilla.org/show_bug.cgi?id=682139) it seems that the libpng MMS warnings can be ignored.

**Comment by DomAmato** [comment]
I think thats an older library which can be fixed now using the apothecary scripts. When i first did the PR for the newer libs i didnt catch that right away since I was just trying to get it to compile.

**Comment by tgfrerer** [comment]
Sweet! 

I managed to recompile cairo using apothecary on my machine, and the errors disappear, and the link time drops to `>  Final: Total time = 2.359s`. 

We should update the cairo, libpng and pixman static lib from the apothecary generated ones.

It seems that when i compile cairo it re-compiles its dependency freetype, and the freetype header files it generates are more recent than the ones we have currently checked in in the repo. Is freetype 2.5.5 what we are using on all other platforms?

**Comment by DomAmato** [comment]
It should be I dont think I changed the version type when I updated the scripts for freetype.

**Comment by arturoc** [comment]
have you checked that is really different, in windows it usually shows as it has changed but it's only the breaklines

**Comment by tgfrerer** [comment]
I did the ol' push / pop stash trick, yes =) and then a git diff ... there are differences, our headers for example have their copyright up until 2013, the new headers go up to 2014.
