### ISSUE TITLE
Xcode 7.0 - Requires iOS 6.0+ as minimum. Time for iOS 7.0 Minimum step up

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#3977]
Building for a device under Xcode 7 fails due to
`clang: error: -fembed-bitcode is not supported on versions of iOS prior to 6.0`
Apple's new bitcode enhancements require at least iOS 6.0

This is due to the current Deployment Target of `5.1.1`

I think it's a good idea to push forward even further and make iOS `7.0` oF minimum.

The current statistics from Apple:
![ios8](https://cloud.githubusercontent.com/assets/830748/8297208/7791d096-199e-11e5-9d3e-3bc9e67c1431.png)

Within 2 months it is assumed 50-70% of all iOS devices used will be living in iOS `9.0`.
Coupled with iOS `9.0` being dubbed as a performance patch for older devices, as well as smaller install size, this number could be greater.
The vast majority of iOS devices still are supported for iOS 7.0 and greater.
#### Make iOS 7.0 minimum. Skip iOS 6.0 minimum.

Previous discussions: https://github.com/openframeworks/openFrameworks/issues/2568

**Comment by danoli3** [comment]
@openframeworks/ios

**Comment by danoli3** [comment]
Adding to this: When any static library is built without ENABLE_BITCODE for iOS 6.0 and above: The following "URGENT" warning is displayed for every object of every architecture of every static lib.

> ld: warning: URGENT: all bitcode will be dropped because '*.a(*.o)' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. Note: This will be an error in the future.

**Comment by julapy** [comment]
+1
also agree that moving to iOS 7.0 minimum would be a good idea.

**Comment by ofTheo** [comment]
That chart looks a bit dubious to me :)  Half my iOS devices are iOS 5 or 6. 
Any reason to not have iOS 6 as a minimum? 
Is there a huge workaround that we could then avoid? 

I know for people making games being able to support the most number of devices is really helpful.

If there is a really strong reason to make iOS 7 minimum I�m for it - but generally with OF if we can easily support more devices/OSs without much extra work we usually try and do so.

**Comment by julapy** [comment]
yeah apple is pretty aggressive with their iOS upgrades. generally when working on pure iOS commercial projects (non-OF), it's safe to target the last 2 major releases, so right now it would be iOS 7 & 8.

ofxiOS has always been behind this standard, and we tend to support the last 3 major releases. so following this pattern, we should be supporting iOS 6, until iOS 9 comes out anyway.

ok so lets agree to make iOS 6 the minimum?

**Comment by gorkacortazar** [comment]
While bitcode plans are not completely clear yet, seems that it will be some sort of intermediate code to compile for each new platform. Is not yet mandatory for ios 9 (but it will be for apple watch),  and will be mandatory in the near future. 

This article, while highly speculative, have some arguments that may make sense about this change
https://medium.com/@InertialLemon/apple-s-bitcode-telegraphs-future-cpu-plans-a7b90d326228

**Comment by danoli3** [comment]
I have a solution for the bit code issue in Xcode for now:
```ENABLE_BITCODE = NO``` in the config.

> Half my iOS devices are iOS 5 or 6.
@ofTheo Get updating your devices ! ;D

If they are back there for testing, well Apple's stance is test for the 98% not the 2% (that are not likely to download apps), they actually only do real AppStore submission test on the latest and the last (so 8.0 and 7.0 currently, it will be 8.0 and 9.0 in 2 months)
Apple removed the iOS Simulators for iOS 5, 6 and even iOS 7.0 (Xcode 7) from the latest versions of Xcode. It also should be noted that you are required to have the latest version of Xcode (6) to submit to the App Store as of February this year.

In regards to strong reasons, the iOS SDK adds more and more every revision, and with 7.0 and 8.0 the SDK saw vast re-writes and the creation of so many API's, some which would greatly benefit to be incorporated into the core, however we haven't thought yet of what we can use or how as we are not there yet. Setting to 7.0 lets us skip the 6.0 SDK updates which didn't add to much, mostly removed a lot (this will force our hand at fixing or removing the core location, maps and other things as well).

**Comment by ofTheo** [comment]
I think that graph is quite skewed in that it is based on people who downloaded apps in June 2015 which will always favor recent devices or very active users. 

A lot of older devices won't be downloading apps as they are already setup how the user wants them. My hunch is that if you were to survey the iOS versions in the wild. It would be probably less than 40% iOS 7 and above.  Apple just loves to make it seem like everyone updates their devices.  :) 

I don't always update because I enjoy my devices not being slow. 

Separately though I would love to organize some cleanup of the OF / iOS core. Maybe after 0.9.0? 
The keyboard code and image picker are both areas that could use some massive love.

**Comment by danoli3** [comment]
Google would be the first to call that card out if they were skewing the data (they do run the largest Analytics API in the world :D!).

I did think of that possibility though a while back and checked some sources, public SDK's being used in apps all over the AppStore and the stats do match or are usually less than what is actually out in the real world.

### References: 

#### Unity SDK
- Realtime stats from all Unity Applications / Games in the wild 
- http://stats.unity3d.com/mobile/os-ios.html
- 97% >= iOS 7+
- 75% iOS 8+
- 2 % iOS 6 
- 0.8 % < iOS 5.1.1

#### Mixpanel SDK:
- https://mixpanel.com/trends/#report/ios_8/from_date:-29,report_unit:day,to_date:1
- 98.9% >= iOS 7+
- 87 % iOS 8+
- 1 % < iOS 6

#### Fiksu SDK:
- https://www.fiksu.com/resources/ios_8_tracker
- 97 % >= iOS 7.0+
- 82 % iOS 8.0+
- 1.9 % iOS 6

**Comment by ofTheo** [comment]
touche!

**Comment by bakercp** [comment]
Seems like a pretty strong case for 7+ ... :) Thanks for all the research @danoli3

**Comment by julapy** [comment]
the move to iOS7 will also work nicely with @danoli3's tvOS work (#4413)
@danoli3, are you able to put a PR together for this so we can see what that looks like?

**Comment by danoli3** [comment]
Yeah no worries!

**Comment by ofTheo** [comment]
I agree as well. 
At this point ios7 and above makes sense!
