### ISSUE TITLE
GLUT on OSX? Broken on master.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3978]
I'm not sure what the current status is w/ Glut (are we leaving it behind for 0.9.0)?  Anyway, if one attempts to use the current master and something like this:

```c++
#include "ofApp.h"
#include "ofAppGlutWindow.h"


int main()
{
    ofAppGlutWindow window;
    ofSetupOpenGL(&window, 320, 240, OF_WINDOW);
	ofRunApp(new ofApp());
}
```

It will call this system GLUT framework, which is missing some symbols, namely:

```
dyld: lazy symbol binding failed: Symbol not found: _glutDragEventFunc
  Referenced from: /[redacted]/example_browser/bin/example_browserDebug.app/Contents/MacOS/example_browserDebug
  Expected in: /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT

dyld: Symbol not found: _glutDragEventFunc
  Referenced from: /[redacted]/example_browser/bin/example_browserDebug.app/Contents/MacOS/example_browserDebug
  Expected in: /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT
```

Anyway, if we're leaving GLUT behind, let's get rid of ofxAppGlutWindow, or go back to including the custom framework in the template by default so it still works.

**Comment by arturoc** [comment]
are you using 64bits? i think the modified framework is still there but it was never compiled for 64bits.

**Comment by bakercp** [comment]
No, using 32bit (I can't get 64 bit to compile at all on OSX / master).

I think the new project templates no longer are including the old 32bit glut framework in the project files, so it could be as simple as including them (all of the frameworks are no longer in the tree view of the osx empty project template used by PG).

**Comment by bakercp** [comment]
Looks like the copy phase of the updated project template is simply missing from the updated project templates.

![example_browser_xcodeproj](https://cloud.githubusercontent.com/assets/300484/8313230/1a41bb82-19a7-11e5-89d6-6f14fe65d4af.png)

**Comment by bakercp** [comment]
That said, it would be nice to not have this framework in every app if the app doesn't use it, so perhaps we just need to document this or copy it conditionally (not sure how to do this).

**Comment by bakercp** [comment]
So all of that said -- where is the glut source so that we can get the 64 bit version compiled and included (if we are keeping GLUT support)?

**Comment by arturoc** [comment]
i think only @ofTheo has them

**Comment by danoli3** [comment]
Kill GLUT. It's not open source. GLFW few

> GLUT is not open source. Mark Kilgard maintains the copyright. There are a number of newer and open source
https://www.opengl.org/resources/libraries/glut/

**Comment by ofTheo** [comment]
Okay there is a FAT build of GLUT now in master. I tested it and it works fine. 
The only issue is the examples are now building without adding the copy framework to the app frameworks so currently apps with GLUT windows on OS X are linking with the one in /System/Library/Frameworks. 

edit: okay I think its cause the template got converted to plist from xml. going to fix.

**Comment by bakercp** [comment]
Still broken -- see comment here https://github.com/openframeworks/openFrameworks/commit/4f4aa8455eaf13494fa79153b7d9525e8098f6ad

**Comment by bakercp** [comment]
Also, wouldn't it make more sense to use rsync like we do w/ ios instead of repeatedly copying libfmodx and GLUT?

**Comment by ofTheo** [comment]
@bakercp def feel free to change it to rsync - I think that could be fine as well. 
I just matched what we had there already.

**Comment by danoli3** [comment]
Just a heads up, by including the GLUT framework any app submitted to the OSX App Store, is rejected. Plz remove.
