### ISSUE TITLE
ofGetFrameNum increments super fast when in background (and covered by another window)

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3979]
Code on current master:
```c++
class ofApp: public ofBaseApp
{
public:
    void draw()
    {
        ofDrawBitmapString(ofToString(ofGetFrameNum()), 10, 10);
    }
};

```

When the window is in the background (and completely covered) the frame count is incremented by several thousand.

Here's a gif:

![ezgif-1296895755](https://cloud.githubusercontent.com/assets/300484/8311671/61e289b2-199d-11e5-9bef-7d803fba6516.gif)

Haven't tested it w/ GLUT as GLUT seems to be broken on OSX at the moment (ref #3978)

I'm assuming this is a GLFW related "bug", but wanted to register it here to make sure it isn't something with the new timer events.

Also, on OSX, this happens with both `ofSetVerticalSync(true);` or `ofSetVerticalSync(false);`

**Comment by arturoc** [comment]
i think this has always been there it's just how osx works. if a window is not visible or is minified the vertical sync doesn't work on it so it runs as fast as possible. in the PG we had to limit the fps so this won't happen cause it was eating a full cpu when it was in the background.

not sure if there's anything we can do and i think it's the same with glut

**Comment by bakercp** [comment]
Strange, yeah, I remember those older issues.  I didn't realize it was an issue.  If it's just the way it is, I'll close this.

**Comment by ofZach** [comment]
as a side note, glfw does provide good mechanisms for knowing if a window is out of focus or not (it's a callback for getting / loosing focus).  I don't know if that helps, this is more about it being covered, but I could imagine a kind of fix where you add a frame rate cap on loosing focus (for a window that has vsync and no frame rate set) and drop the frame rate cap when it's in focus.

**Comment by kylemcdonald** [comment]
related to #3181

**Comment by bilderbuchi** [comment]
thanks @kylemcdonald, I'll close this is a duplicate since it's basically about the same thing.
