### ISSUE TITLE
remove -lpthread C++ flag  

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3980]
I'm getting lots of warnings about the `-lpthread` flag not being used.

Can we delete this from the OSX project template flags for 0.9.0?

**Comment by arturoc** [comment]
didn't @tgfrerer removed them already?

**Comment by bakercp** [comment]
Hm.  Just pulled the latest ... checking again.

**Comment by arturoc** [comment]
this was a while ago, at least a week so you should have them just pinging tim so he tells us where that was it might have been in other platform or something

**Comment by tgfrerer** [comment]
Could be that I left some out.

The flags are set in the App project files and per configuration (so worst case in 4 places), so it's possible that the project generator project file might still have them set somewhere.

The project file template should not have them, and project files generated through the project manager should also not have them, but best double check.

**Comment by bakercp** [comment]
This is superseded by #3995 and @ofTheo 's commits.
