### ISSUE TITLE
Separate VS Builds

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#3983]
Changing architectures requires openframeworks to be rebuilt. Should we maybe have them separated by architecture so that it would be libs\openFrameworksCompiled\lib\vs\(Win32/x64) 

I don't think its a big deal but it will cut down on recompiling each time someone switches architectures

**Comment by bakercp** [comment]
If this is possible, it would be cool.  I ran into this issue today.


---
http://christopherbaker.net

**Comment by DomAmato** [comment]
Changing the output directory and intermediate directories didn't work

**Comment by bilderbuchi** [comment]
closed by #4025
