### ISSUE TITLE
ofx3DModelLoader Addon Example Fails to Build (texture3DS.cpp)

### ISSUE THREAD

**Issue by rezaali** [openframeworks/openFrameworks#3987]
Here are the errors when building: 

texture3DS.cpp:18:23: error: 'width' is a protected member of 'ofImage_<unsigned char>'
    m_width     = img.width;
texture3DS.cpp:19:23: error: 'height' is a protected member of 'ofImage_<unsigned char>'
    m_height    = img.height;
texture3DS.cpp:20:23: error: 'bpp' is a protected member of 'ofImage_<unsigned char>'
    m_bpp       = img.bpp;

Looks like texture3DS is trying to access protected members of ofImage (the first two are easy fixes I believe, but there isn't an easy way to get the bits per pixel from ofImage, or is there?) 

Will try to submit a pull-request.

**Comment by bilderbuchi** [comment]
Closed by #3989
