### ISSUE TITLE
master not compiling on linux "boost/filesystem.hpp not found"

### ISSUE THREAD

**Issue by jamet** [openframeworks/openFrameworks#4000]
hi all,

having a problem with might be related to this commit 96530d7 and the introduction of boost lib.

all dependencies are installed ok, but it seems boost lib is not present on linux

**Comment by arturoc** [comment]
fixed by https://github.com/openframeworks/openFrameworks/pull/3971

you need to run the install_dependencies script which will install the needed libraries
