### ISSUE TITLE
framerates drops when connecting hdmi display

### ISSUE THREAD

**Issue by jamet** [openframeworks/openFrameworks#4001]
hi all,

as the title says, when i connect my hdmi display to my laptop, every app that make a call to ofGetScreenWidth() or ofGetScreenHeigth() drops framerate to 1 FPS.

i described the problem in this thread, but have no ideas how to continue debugging : 
http://forum.openframeworks.cc/t/framerate-drops-when-connecting-hdmi-display-on-lubuntu-14-04-related-to-ofgetscreenwith/19970

**Comment by arturoc** [comment]
i think this is an OS thing, that call is requesting the screen size which might be slow depending on the config i guess. glfw the library we use has callbacks to detect when a new monitor is present so you can query the screen size only when that happens. also unless you have some special config that fakes all the screens being only one the reported size is for the monitor in which the app is running not for all the connected screens.

**Comment by jamet** [comment]
thanks for your answer @arturoc , i understand the point of the screen size being the one that the app runs too, so it seems ok that it always return same value.

i will try to test with latest master and to get deeper in xorg.conf, could try with Glut window instead maybe?

**Comment by jamet** [comment]
it seems i get rid of that comportement when using Glut window instead of glfw, so you wer right @arturoc , it seems it's not related with openframeworks at all but with glfw libs in ubuntu 14.04 lts.

i close the issue
