### ISSUE TITLE
ExtensionComparator / allowExt need . (dot) to be included in file path

### ISSUE THREAD

**Issue by obviousjim** [openframeworks/openFrameworks#4004]
In 0.8.4 The following use of ofDirectory::allowExt() works to filter for only pngs:

     ofDirectory dir(pathToFolder);
     dir.allowExt("png");
     dir.listDir();
     //now dir is full of only pngs

In current master one needs to include the . for the extension, otherwise no files pass the test

     ofDirectory dir(pathToFolder);
     dir.allowExt(".png");
     dir.listDir();
     //now dir is full of only pngs

The culprit is in how the ExtensionComparator works

      string curExtension = ofToLower(curPath.extension().string());  

curExtension still has the . included in the string. Is this intentional? is there a way to support both the old way and the new way?

**Comment by ofTheo** [comment]
It should be fairly easy to fix so it works both ways I think. 
We should also check if the behavior of ofFile::getExtension and ofFilePath::getExtension has changed too.

**Comment by arturoc** [comment]
i fixed getExtension but not this one, seems the std filesystem functions understand extension with the ., i'll fix it so it works as it did and we can consider later if we won't to make it work with the . too

**Comment by bilderbuchi** [comment]
> We should also check if the behavior of ofFile::getExtension and ofFilePath::getExtension has changed too. 

a situation like this is another +1 for automated tests. :-)

**Comment by danoli3** [comment]
@bilderbuchi I'll try out a branch on my fork for travis integration on OSX oF Lib + empty example for now. See how it handles it.

**Comment by bilderbuchi** [comment]
@danoli3  great! unfortunately travis is probably not gonna cut it, but it's a great initial step. see also  #2917
