### ISSUE TITLE
Safety : Intermediate paths for Visual Studio

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4006]
Since now we have Win32 and x64 support....

If you switch between Win32 and x64, VS will build the intermediate files (.obj, .lib, etc) to the same locations. Which :

1. Can cause Visual Studio to get confused (resulting in needing to rebuild solution)
2. Each time you switch platform you overwrite the previous platform's files 

I suggest that we change in `openFrameworks.vcxproj`
![image](https://cloud.githubusercontent.com/assets/328294/8370011/d3da1b32-1bfc-11e5-9498-f78ee93a3e84.png)

to
![image](https://cloud.githubusercontent.com/assets/328294/8370015/ea76c4a8-1bfc-11e5-9f99-eed602d7b314.png)

This should be transparent to the user.

cc: @DomAmato @liquidzym

**Comment by elliotwoods** [comment]
If we agree, I can PR this right away

**Comment by bakercp** [comment]
+1 on this.

**Comment by bakercp** [comment]
But also see this https://github.com/openframeworks/openFrameworks/issues/3983.

**Comment by arturoc** [comment]
@elliotwoods yes if you can send a PR with this it would be great. we should do the same for xcode i think it has the same problem

**Comment by DomAmato** [comment]
Seems to work using the above method which is super convenient for testing the platforms +1
