### ISSUE TITLE
Branch Pruning for openframeworks/openFrameworks

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#4007]
Might be a good idea to prune the old / closed and merged branches from the core repository.
I was thinking if you currently fork the repo, you get all these added by default.

Nice break down by github here: (with handy delete button :D!)
https://github.com/openframeworks/openFrameworks/branches

![branches](https://cloud.githubusercontent.com/assets/830748/8375215/b450107c-1c3e-11e5-93f0-6db15ea1ad3d.png)

**Comment by bilderbuchi** [comment]
Totally, yeah. I just deleted the ones which are definitely safe to delete. Only master and stable are permanent branches, and it's policy to work/create PR branches in your own repo, but some creep in anyway.

@ofTheo @ofZach @arturoc can you check and delete those of your old branches which we can nuke?

**Comment by bilderbuchi** [comment]
@ofTheo @ofZach @arturoc can you check and delete those of your old branches which we can nuke?

**Comment by arturoc** [comment]
just removed everything except: https://github.com/openframeworks/openFrameworks/pull/4028 which i'll remove once it's fixed and merged

**Comment by bilderbuchi** [comment]
thanks :-)
