### ISSUE TITLE
of compile error on linux 64bit: undefined reference to `std::__throw_out_of_range_fmt

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#4015]
I get the following error when compiling the current git version of OF on linux 64bit.
The dependencies are all installed.

```
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_parse.cpp.o): In function `std::bitset<256ul>::_M_check(unsigned long, char const*) const [clone .isra.985] [clone .part.986]':
uri_parse.cpp:(.text.unlikely+0x11): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_parse_authority.cpp.o): In function `std::bitset<256ul>::_M_check(unsigned long, char const*) const [clone .isra.661] [clone .part.662]':
uri_parse_authority.cpp:(.text.unlikely+0x11): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_resolve.cpp.o): In function `void network::detail::remove_last_segment<std::string>(std::string&)':
uri_resolve.cpp:(.text._ZN7network6detail19remove_last_segmentISsEEvRT_[_ZN7network6detail19remove_last_segmentISsEEvRT_]+0x9f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
```

**Comment by frauzufall** [comment]
I changed to an older revision (45cef3b771c5874a24b4d4c0f6064c919a567244) which used to work, but now I get a lot of these errors:

```
../../../libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofTexture.o): In function `_GLOBAL__sub_I__Z23ofEnableTextureEdgeHackv':
ofTexture.cpp:(.text.startup+0x23): undefined reference to `boost::system::generic_category()'
```

Is maybe something wrong with some Ubuntu packages that got included recently?

**Comment by bilderbuchi** [comment]
did you run `install_dependencies.sh` before your initial test? We changed dependencies a bit recently.

**Comment by bilderbuchi** [comment]
the initial error seems to be a problem with the new uri lib - @arturoc can you help here?

**Comment by frauzufall** [comment]
I did, and since I installed the new dependencies I seem to get errors no matter which revision I use.

**Comment by frauzufall** [comment]
The second error is not important I guess. That was just a try to get back to a working OF version and I was surprised that it did not work.

**Comment by bilderbuchi** [comment]
hm, did you clean the compiled libs out after switching?

**Comment by frauzufall** [comment]
Sorry, but how do I do that?

**Comment by bilderbuchi** [comment]
what IDE do you use? if you're using the make system, a `make clean` instead of `make` should do it.

**Comment by frauzufall** [comment]
Sorry, stupid question, thought I did that. Its working now, thank you! Back to the initial error.

**Comment by frauzufall** [comment]
By the way, I had to manually remove everything within `libs/openFrameworksCompiled/lib/linux64` in order for it to work. `make clean` does not do that.

**Comment by bilderbuchi** [comment]
that is strange, it should do that. I'll try to repro this sometime this week, otherwise @arturoc do you know what's going on there?

**Comment by arturoc** [comment]
you need to make clean the OF project, doing make clean will only clean the example and any addon it uses. the makefiles for the OF library are in libs/openFrameworksCompiled/project. you can easily clean from your project doing: `make clean -C ../../../libs/openFrameworksCompiled/project`  

do you still get any error after cleaning... ?

**Comment by bilderbuchi** [comment]
hm, I assumed that's what @frauzufall did because she talked about compiling OF, not compiling any example.

**Comment by frauzufall** [comment]
Alright, no, then I was doing the wrong cleanup, thanks for clarifying. 

The first error with the master version still remains:

```
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_parse.cpp.o): In function `std::bitset<256ul>::_M_check(unsigned long, char const*) const [clone .isra.985] [clone .part.986]':
uri_parse.cpp:(.text.unlikely+0x11): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_parse_authority.cpp.o): In function `std::bitset<256ul>::_M_check(unsigned long, char const*) const [clone .isra.661] [clone .part.662]':
uri_parse_authority.cpp:(.text.unlikely+0x11): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../../libs/uri/lib/linux64/libnetwork-uri.a(uri_resolve.cpp.o): In function `void network::detail::remove_last_segment<std::string>(std::string&)':
uri_resolve.cpp:(.text._ZN7network6detail19remove_last_segmentISsEEvRT_[_ZN7network6detail19remove_last_segmentISsEEvRT_]+0x9f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
```

**Comment by pierrep** [comment]
I'm getting this as well, latest GIT, Ubuntu 14.04 64 bits

**Comment by pierrep** [comment]
Also as @frauzufall says, rolling back to above commit works.

**Comment by arturoc** [comment]
@pierrep have you run install_dependencies again?

**Comment by pierrep** [comment]
Yes, tried all the usual tricks.

**Comment by arturoc** [comment]
oh, i think what's going on is that libraries compiled with ubuntu 15.10 are not compatible with 14.04, i got this when we compiled poco. can you try running the apothecary formular for liburi?

```
cd scripts/apothecary
./apothecary update uri
```

that should compile the library for your system, once you have it can you send a PR with the new binaries? those should be compatible with latest versions

**Comment by bilderbuchi** [comment]
will those be compatible with 15.10, though? (thinking about compiler version)

**Comment by arturoc** [comment]
> those should be compatible with latest versions
: )

**Comment by bilderbuchi** [comment]
:)

**Comment by pierrep** [comment]
OK just ran that command:

Downloading "uri"

Cloning into 'uri'...
remote: Counting objects: 7016, done.
remote: Total 7016 (delta 0), reused 0 (delta 0), pack-reused 7016
Receiving objects: 100% (7016/7016), 5.77 MiB | 945.00 KiB/s, done.
Resolving deltas: 100% (2093/2093), done.
Checking connectivity... done.
Note: checking out '55ec3cd78918c42dfb874e01c9745b4daf51091b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 55ec3cd... Merge pull request #57 from toonetown/android-compile

 Preparing "uri"


 Building "uri"

/media/Data/code/openFrameworks/scripts/apothecary/build/uri
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Performing Test HAVE_STD11
-- Performing Test HAVE_STD11 - Success
C++ Flags:  -std=c++11 link flags: 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindGTest.cmake:150 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:56 (find_package)


-- Configuring incomplete, errors occurred!
See also "/media/Data/code/openFrameworks/scripts/apothecary/build/uri/_build/CMakeFiles/CMakeOutput.log".
See also "/media/Data/code/openFrameworks/scripts/apothecary/build/uri/_build/CMakeFiles/CMakeError.log".

**Comment by pierrep** [comment]
I ran

    sudo apt-get install libgtest-dev
which installed it, but didn't fix the above

**Comment by arturoc** [comment]
can you try now?

**Comment by arturoc** [comment]
i just removed the problematic library since it was giving problems in other platforms so this should be fixed now.
