### ISSUE TITLE
parameterGroupExample does not compile out of the box

### ISSUE THREAD

**Issue by rezaali** [openframeworks/openFrameworks#4018]
on OSX 10.10.3 using xCode 6.3.2. Specifically: 

/openFrameworks/examples/gui/parameterGroupExample/src/ofApp.cpp:53:15: Unimplemented pure virtual method 'setSerializable' in 'ofCirclesRendererParam'

After adding the serSerializable function I got this error:
/openFrameworks/examples/gui/parameterGroupExample/src/CirclesRenderer.h:18:7: In instantiation of member function 'ofReadOnlyParameter<int, CirclesRenderer>::getFirstParent' requested here

I'd love to get a better understand of ofParameter, so fixing this example would really be helpful!

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by rezaali** [comment]
thanks @arturoc :D
