### ISSUE TITLE
ofCamera enableOrtho() not working correctly with translated viewport

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#4020]
When a translated viewport (any that has its x or y values non zero) is used as the viewport for an ofCamera in ortho mode the render appears translated. 
Digging a bit it happens that the orthomatrix that the camera uses that's created by calling ofMatrix4x4::newOrthoMatrix(...) might be the problem.
inside ofMatrix4x4::newOrthoMatrix(..) there seems to bee something weird.
according to this http://www.songho.ca/opengl/gl_projectionmatrix.html#ortho
the ortho matrix's fourth row is 0,0,0,1 yet in the aforementioned method it is not. 
Changing that row to 0,0,0,1 makes the ortho cam to render correctly.
When the viewport's x and y are 0 that row is computed as 0,0,0,1 that's why it doesn't show problems in such case.

so, the fix would be to change this
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/math/ofMatrix4x4.cpp#L824-L831
to 

```
SET_ROW(0, 2.0/(right-left),               0.0,               0.0, 0.0 )
SET_ROW(1,              0.0,  2.0/(top-bottom),               0.0, 0.0 )
SET_ROW(2,              0.0,               0.0,  -2.0/(zFar-zNear), 0.0 )
SET_ROW(3,               0,                0,                 0, 1.0 )
```

on the other hand.
The ofSetupScreenOrtho(...) function is using the values passed in another way so making the change that I just mentioned breaks this function. 
I don't know if changing this will break anything else, or why it was written that way on first place, but definitely something is wrong as there seem to be incompatibilities between these functions that use the ortho matrix. I'm not sure how to fix this. @arturoc @elliotwoods ?

Heres a testing app for both the ofSetupScreenOrtho function and the camera in ortho mode:
https://gist.github.com/6bcc930cb88282a5412e.git

And screenshots:
This is how it behaves right now.

![master_nocam_persp](https://cloud.githubusercontent.com/assets/974878/8395148/1a8dbf8c-1d35-11e5-913e-1e161adf47a7.png)
![master_nocam_ortho](https://cloud.githubusercontent.com/assets/974878/8395149/1a8e2328-1d35-11e5-95aa-0ed4f90e2a4d.png)
![master_cam_ortho](https://cloud.githubusercontent.com/assets/974878/8395150/1a8ffd06-1d35-11e5-881b-62b8db537349.png)
![master_cam_persp](https://cloud.githubusercontent.com/assets/974878/8395151/1a91ec24-1d35-11e5-9f0e-d529d9a61629.png)

This is how it behaves with the modification mentioned before:

![mod_nocam_ortho](https://cloud.githubusercontent.com/assets/974878/8395158/5093aae2-1d35-11e5-8e0c-8d3770a6be0a.png)
![mod_nocam_persp](https://cloud.githubusercontent.com/assets/974878/8395159/5094b48c-1d35-11e5-8cf1-4f5738dc3e22.png)
![mod_cam_persp](https://cloud.githubusercontent.com/assets/974878/8395160/509566ac-1d35-11e5-9455-7c5c36420bb7.png)
![mod_cam_ortho](https://cloud.githubusercontent.com/assets/974878/8395161/50972df2-1d35-11e5-883d-1d426845407b.png)

The expected behavior should be that in all the 4 different modes the five circles should be inside the viewport rectangle.
like this:
![mod_cam_ortho](https://cloud.githubusercontent.com/assets/974878/8395163/ad92734a-1d35-11e5-8373-7b4e8ac5af15.png)

Best!

**Comment by procedural** [comment]
> the ortho matrix's fourth row is 0,0,0,1 yet in the aforementioned method it is not. 
Changing that row to 0,0,0,1 makes the ortho cam to render correctly.

Great! Can you PR the change?

**Comment by roymacdonald** [comment]
Hi @procedural,
I cant PR. As said, making that change breaks the ofSetupScreenOrtho(...) function.
The images I attached should all render the same (the five circles inside the white rectangle) but it doesn't. Making the change I mention fixes the wrong render but makes a correct render to render wrong.
There's a gist in my first post with the example code. (the images are taken from it)

The thing is that the maths for are being split in two different ways in the ofSetupScreenOrtho function and the ofCamera in ortho mode. Both make use of ofMatrix4x4::newOrthoMatrix() method and each one of these expect from it a matrix in formed in a different way.  Currently ofMatrix4x4::newOrthoMatrix() returns a matrix that fits ofSetupScreenOrtho(...)'s expectations, but making the change that I mention, so to fit what ofCamera expects will make ofSetupScreenOrtho to get the matrix in way different than what it expects, thus breaking it. 

I certainly can fix both so the the whole thing  works  but the dilemma is which would be the correct way. So when someone asks for an ortho matrix he gets the mathematically correct matrix, not just the arbitrarily formed matrix that can solve this issue.

Best!

**Comment by roymacdonald** [comment]
This seems to be solved by the switch to glm. Just tested and it behaves correctly
