### ISSUE TITLE
bug : exceptions thrown on empty strings

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4030]
in 
* ofToLower
* ofTrueTypeFont::createStringMesh

(still finding them)

**Comment by elliotwoods** [comment]
generally throws on these kinds of lines:

```c++
utf8::iterator<const char*> it(&str.front(), &str.front(), (&str.back())+1);
```

**Comment by bilderbuchi** [comment]
probably empty iterators error out or something? this most probably comes from ofToLower. ping @arturoc
