### ISSUE TITLE
ofVideoPlayer + Programmable Render Incorrect behavior on draw(ofRect)

### ISSUE THREAD

**Issue by obviousjim** [openframeworks/openFrameworks#4032]
The expected behavior when drawing images with ofRectangle (or specifying x,y,w,h explicitly) is that the texture will be scaled into the rectangle. 

Under GLProgrammableRenderer, ofVideoPlayer's draw(ofRectangle) does not scale the video texture, rather it crops or stretches it.

    ofVideoPlayer player;
    player.load("mymovie.mov");
    ofRectangle rect(0,0,player.getWidth()*2,player.getHeight()*2);
    // video only fills top left and the rest of the rectangle space is texture stretched
    player.draw(rect);
    //correctly scales
    player.getTexture().draw(rect); 

The culprit is here: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L412 where the ofBaseVideoDraws is rendered by the programmable renderer using a mesh subsection.

**Comment by bilderbuchi** [comment]
ping @openframeworks/video @openframeworks/2d-3d

**Comment by bilderbuchi** [comment]
heh, the video team only has you in it. sorry ^^

**Comment by obviousjim** [comment]
haha! Well we should fix that cuz some wonderful hackers have risen to the
occasion :)

On Tue, Jun 30, 2015 at 2:45 PM, Christoph Buchner <notifications@github.com
> wrote:

> heh, the video team only has you in it. sorry ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4032#issuecomment-117298779>
> .
>



-- 
- James
