### ISSUE TITLE
removing using namespace std from core

### ISSUE THREAD

**Issue by tpltnt** [openframeworks/openFrameworks#4034]
This ticket spawned of #4012 & #2851. `using namespace std` shall be moved from `ofConstants.h` into `ofMain.h` to ease the transition for beginners. There could also group headers be added per folder so including different modules. `ofUtils.h` would include everything in the utils folder.

**Comment by tpltnt** [comment]
ping @arturoc @tgfrerer

**Comment by bilderbuchi** [comment]
Closed as duplicate of #2581
