### ISSUE TITLE
texData.glTypeInternal should be glInternalFormat

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#4036]
In OpenGL, a texture **format** is an enum specifying the number of color components and how these are laid out in memory, whilst a **type** refers to an enum specifying a data type such as `GL_FLOAT`,` GL_UNSIGNED_BYTE` etc. 

In openFrameworks `ofTextureData::glTypeInternal` is used to refer to the internal **format**, i.e. how data is laid out, but is named after the type. Let's fix this so that we're using the same (and not the flipped) terminology as in OpenGL, and change `ofTextureData::glTypeInternal` to `ofTextureData::glInternalFormat`.

cf. our call to `glTexImage2D` in line ofTexture.app#L401

	glTexImage2D(texData.textureTarget, 
		0,
		texData.glTypeInternal,
		(GLint)texData.tex_w,
		(GLint)texData.tex_h,
		0,
		glFormat,
		pixelType,
		0);

with the specs for glTexImage2D:

	void glTexImage2D(	GLenum target,
		GLint level,
		GLint internalFormat,
		GLsizei width,
		GLsizei height,
		GLint border,
		GLenum format,
		GLenum type,
		const GLvoid * data);
 
From: https://www.opengl.org/sdk/docs/man/html/glTexImage2D.xhtml

**Comment by kylemcdonald** [comment]
:+1: this always confused me and i thought i just didn't understand it correctly.
