### ISSUE TITLE
Project generator issue with VS2015

### ISSUE THREAD

**Issue by gorkacortazar** [openframeworks/openFrameworks#4038]
I am trying to build assimp for VS2015, and i noticed that creating a project with the Project Generator Simple (and legacy too) and adding ofxAssimpModelLoader addon doesn't add the proper lib in release mode.

In debug mode the lib gets added
![debug](https://cloud.githubusercontent.com/assets/608719/8457244/9b5a5d0e-2010-11e5-9175-80e714b8ce51.png)

But in release mode is not added
![release](https://cloud.githubusercontent.com/assets/608719/8457276/bb6a0270-2010-11e5-8bf2-ddc347201441.png)

**Comment by bilderbuchi** [comment]
ping @openframeworks/windows

**Comment by DomAmato** [comment]
This is consistent with all addons that require a library. However before a build is started all the additional dependencies are blank and VS seems to just populate them from the folders that are specified. I will have to investigate things more but thats just a preliminary observation. VS also adds all the libraries in those folders including the debug and release versions which creates further conflicts

**Comment by ofZach** [comment]
sorry I am not in front of a windows install at the moment, for this bug, I'd look here: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp#L369-L420

(this is the seperation of libs into debug and release) 

and here: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp#L255-L285

where the lib gets added to the project.....

maybe see, (a) are the libs getting put in the right place and (b) if debug and release libs are coming in, is the template designed so they can get put in the right place.

**Comment by gorkacortazar** [comment]
There is also the separation between Win32 and x64 that needs to be taken into consideration for the PG, similar to the osx case.

**Comment by DomAmato** [comment]
We might have to separate the libs into debug and release folders to make parsing easier. They are already separated by architecture but is there a reliable way to sniff out which is the debug lib and which isn't. Separating them is easy too so I don't see why we shouldn't just do that.  the current method: 

     for(int j = 0; j < addon.libs.size(); j++){
            // check if this lib name is contained within another lib name and is not the same name
            if(ofIsStringInString(addon.libs[j], firstPart) && addon.libs[i] != addon.libs[j]){
                // if it is then add respecitive libs to debug and release
                if(!isInVector(addon.libs[j], debugLibs)){
                    //cout << "adding to DEBUG " << addon.libs[j] << endl;
                    debugLibs.push_back(addon.libs[j]);
                }
                if(!isInVector(addon.libs[i], releaseLibs)){
                    //cout << "adding to RELEASE " << addon.libs[i] << endl;
                    releaseLibs.push_back(addon.libs[i]);
                }
                // stop searching
                break;
            }else

sort of works as in the debugLibs vector has less entries than the release, when I try with open CV it has 57 as opposed to 76 but its behavior isn't perfect, I think it only didnt scoop up the release version of the 64 bit libs, it had both the release and debug versions of the 32 bit libraries. The releaseLibs had every lib for both architectures

@ofZach it seems to indiscriminately grab all the libs but I see that right now it hasn't been setup to really discrimate when adding the libs anyways hence the comment:

    // TODO: iterate by <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='BUILD TYPE|SOME PLATFORM'">
which is at line ~257

**Comment by ofZach** [comment]
my intuition is that it might be the best to add debug and release qualifiers to the mk file (and add parsing for that) , since the file system parsing of an addon it always going to be full of edge cases and issues and it makes sense to have a more rigorous way of specifying what lib you want for what platform, etc. 

for example we use "ADDON_LIBS" but I could it being extended to do: 

ADDON_LIBS
ADDON_LIBS_RELEASE
ADDON_LIBS_DEBUG

so that, anything in ADDON_LIBS gets added to debug and release, but anything in release or debug gets added just to that target. 

It still looks like there's work to be done in putting them in the right place at the project level but just my intution that the filesystem way of parsing an addong will always have small gaps. 

(I've always felt like addons.mk was the more hyper-organized swiss way of doing things and that parseFromFS is the chill / laid-back Mediterranean way of doing things)

**Comment by DomAmato** [comment]
Right I think my idea would probably break older addons too if the file structure wasn't setup right. Once I have some time I will try to familiarize myself more with the ofxprojectgenerator
