### ISSUE TITLE
glew errors in VS compilations 

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4039]
When I try to compile the most recent master I get a litany of errors that all stem from glew.h complaining that it can't find GL/glu.h, fixing the path leads to glu.h complaining that it can't find gl.h

**Comment by DomAmato** [comment]
Seems that this is related to the platform target, if it is set to 8.1 it gives me the glew error if I set it to 

    <TargetPlatformVersion>10.0.10069.0</TargetPlatformVersion>

It compiles without problem

**Comment by bilderbuchi** [comment]
@openframeworks/windows do we have to change the VS project files somehow?
