### ISSUE TITLE
Add an implementation of std::make_unique<>?

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4048]
Hi all, I'm really enjoying these new C++11 capabilities and thinking through teaching this in the fall.  One small syntactic frustration (shared by others e.g. [here](https://stackoverflow.com/questions/7038357/make-unique-and-perfect-forwarding)) is that unlike `std::shared_ptr`, `std::unique_ptr` has no method like `std::make_unique` in C++11.  Apparently it was an oversight and will be added in [C++14](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique).  Anyway there are quite a few reasonable implementations out there for this helper method.  I've been using something like this:

```c++
#if __cplusplus <= 201103L

// Implementation from http://stackoverflow.com/a/13512344/1518329
namespace std {


template <typename T, typename... Args>
std::unique_ptr<T> make_unique_helper(std::false_type, Args&&... args) {
    return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}

template <typename T, typename... Args>
std::unique_ptr<T> make_unique_helper(std::true_type, Args&&... args) {
    static_assert(std::extent<T>::value == 0,
                  "make_unique<T[N]>() is forbidden, please use make_unique<T[]>().");

    typedef typename std::remove_extent<T>::type U;
    return std::unique_ptr<T>(new U[sizeof...(Args)]{std::forward<Args>(args)...});
}

template <typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args) {
    return make_unique_helper<T>(std::is_array<T>(), std::forward<Args>(args)...);
}


} // namespace std

#endif
```

Anyway, would it be a terrible idea to add something like that to openFrameworks for 0.9.0? @arturoc @ofTheo @ofZach

**Comment by arturoc** [comment]
linux is already using c++14 and vs, although it has some features of c++14, doesn't even report __cplusplus>=201103 so you need to ifdef for __cplusplus and make an exception for vs if that feature exists for it. but as long as you ifdef it properly i think it should be fine and yes it's really useful, the other syntax is quite verbose

**Comment by bakercp** [comment]
@arturoc good to know - if there are no objections, I'll put together a PR to test.
