### ISSUE TITLE
Problem with new projects in last nigthly build for OSX (ofxAssimpModelLoader related)

### ISSUE THREAD

**Issue by gorkacortazar** [openframeworks/openFrameworks#4049]
I am having problems with the ofxAssimpModelLoader, this time in OSX. I am testing with the last nightly build.

To replicate:
* Use the project generator to create an empty project with ofxAssimpModelLoader
* Compile

If i build the debug and release versions in 64bits and i get this errors in the linking phase:
```
Undefined symbols for architecture x86_64:
  "_CFBundleCopyResourcesDirectoryURL", referenced from:
      __glfwPlatformInit in glfw3.a(cocoa_init.m.o)
  "_CFURLCopyLastPathComponent", referenced from:
      __glfwPlatformInit in glfw3.a(cocoa_init.m.o)
etc..
```
Also happens switching to 32bits, as undefined symbols for i386.

It doesn't happen with a clean building of an empty project or with ofxGui only.

**Comment by ofTheo** [comment]
hmm - I think we need to add 
-framework CoreFoundation to the linker flags of the template

**Comment by danoli3** [comment]
Yeah that sounds like the fix

**Comment by ofTheo** [comment]
hmm - I don't see the issue in the master branch. 
if you run the assimpExample does it also occur for you? 

Looking at https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig#L66 

I see CoreFoundation in the list.

**Comment by gorkacortazar** [comment]
@ofTheo If do a clean checkout of the master, the PG and the assimp examples work well. But if download the last nightly build (of_v20150706_osx_nightly.zip) stills happen as in this screenshot. As all the recent commits are related to travis integration, it may be something in the nightly builds creation scripts? I created the project with the precompiled project generator that comes in the nightly build.

This is the screenshot of the compile errors:
![screen shot 2015-07-06 at 09 48 41](https://cloud.githubusercontent.com/assets/608719/8517830/eac8424a-23c4-11e5-8b55-f79fefd7e5c3.png)

**Comment by bilderbuchi** [comment]
@openframeworks/macos @arturoc can anybody reproduce this?

**Comment by admsyn** [comment]
The issue seems to be that the PG isn't keeping `$(OF_CORE_FRAMEWORKS)` in the linker flags when adding addons w/libs. So the resulting linker flags are
```
$(OF_CORE_LIBS)
<addon libs>
```
instead of
```
$(OF_CORE_LIBS)
$(OF_CORE_FRAMEWORKS)
<addon libs>
```

**Comment by ofZach** [comment]
checking...

**Comment by admsyn** [comment]
@ofZach it may be that the PG on the build server is out of date. Or at least, I don't see the same effect with my local copy of the PG.

**Comment by ofZach** [comment]
is the tool that generate the nightlies up to date with the latest changes on the project generator?  I think this has been fixed previously.  When I generate examples using the tools it's ok.   I'm not 100% certains, but I think this problem happens when you use an old PG tool with the newer template, since libs were moved around.

**Comment by ofZach** [comment]
(sorry on a slow internet !  just like @admsyn says... )

**Comment by bilderbuchi** [comment]
> is the tool that generate the nightlies up to date with the latest changes on the project generator?

I guess @arturoc can answer that.

**Comment by arturoc** [comment]
yes this seems to be the problem i've been trying to update it today but it's failing i'll take a look tomorrow but i think it's just a matter of updating it

**Comment by arturoc** [comment]
just recreated the packages using the new PG if anyone can check that they are working properly now?

**Comment by ofTheo** [comment]
@arturoc - just ran the assimp example from the nightly builds and the scale seems to be working perfectly now! also built and compiled without issue.
