### ISSUE TITLE
Events / Main Loop go out of scope before ofApp

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4052]
So, I'm not sure if this is a philosophical problem or an architecture problem, but in my attempt to practice RAII (which means I prefer to do my setup in constructors and teardown in destructors, rather than in setup() and exit() style functions), I'm running into this issue.  I don't think it's a new issue, but has caused problems for me in the past so, I thought I'd post a minimal code example of what I'd like to do.

Basically it boils down to to initialization and destruction ... some statically initialized psuedo-singletons-shared-pointer nuttiness here:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppRunner.cpp#L34-L43

I'm wondering if we can somehow guarantee that the app runner / main loop won't be destroyed before the `ofApp` instance?

Here's a minimal test case.

```c++
#pragma once


#include "ofMain.h"


class MyClass
{
public:
    MyClass(int required)
    {
        ofAddListener(ofEvents().exit, this, &MyClass::exit);
    }


    ~MyClass()
    {
        // Crashes here b/c the ofEvents instance has gone out of scope (?)
        ofRemoveListener(ofEvents().exit, this, &MyClass::exit);
    }

    void exit(ofEventArgs& e)
    {
        // Works here.
        // ofRemoveListener(ofEvents().exit, this, &MyClass::exit);
    }

};


class ofApp: public ofBaseApp
{
public:
    void setup()
    {
        _myClass = std::unique_ptr<MyClass>(new MyClass(0));
    }

    std::unique_ptr<MyClass> _myClass;
		
};



int main()
{
    ofSetupOpenGL(1024,768,OF_WINDOW);
    ofRunApp(new ofApp());
}
```

**Comment by bakercp** [comment]
Also, if it's helpful here is the call stack that I get on crash.  Basically when it's trying to access the core events, everything in that context is null ...

![ofmainloop_cpp](https://cloud.githubusercontent.com/assets/300484/8506257/0d13867a-21d1-11e5-8062-e8c3a05db9f4.png)

![ofmainloop_cpp](https://cloud.githubusercontent.com/assets/300484/8506264/7061b774-21d1-11e5-8dae-9f18ab56e7c5.png)

**Comment by bakercp** [comment]
Also, just one other reference where this same deregister-events-in-the-destructor pattern is used (and crashes similarly) in the core addons:

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxGui/src/ofxBaseGui.cpp#L98-L100

**Comment by arturoc** [comment]
this was introduced a couple of days ago fixing a similar problem, it's super tricky to get right having even one singleton (there were several before which made it even harder) that lasts for the full duration of the app and is used in the initialization and the destruction ( the main loop)

anyway should be fixed now.

**Comment by bakercp** [comment]
Hey @arturoc thanks for working on this -- now it works if you quit with a system call (command Q), but if you use a key callback (e.g. ESC) to quit the program, it crashes with similar issues.  I believe the core key event listener was not removed/unregistered from the event before its destruction, thus the last key causes the notify to fail on an invalid pointer.

![banners_and_alerts_and_ofevent_h](https://cloud.githubusercontent.com/assets/300484/8508217/92ca39c4-222d-11e5-986c-ba4473ceae4c.png)

**Comment by arturoc** [comment]
mmh, it's working for me fine, let me try in osx

**Comment by arturoc** [comment]
it's working fine in osx too, is this with the same code as in the original post?

**Comment by bakercp** [comment]
Hey @arturoc really sorry -- my mistake.  I commented out the event un-register in one of my destructor's code, thus the failure.  So, for now this issue is fixed.  Sorry for the extra work :/ and thanks for fixing this so quickly!
