### ISSUE TITLE
Warning "Couldn't set UTF-8 locale, string manipulation functions won't work correctly"

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#4053]
```
$ ./ofApp 
[warning] ofInit: Couldn't set UTF-8 locale, string manipulation functions
won't work correctly for non ansi characters unless you specify a UTF-8 locale
manually using std::locale::global(std::locale("locale"))
available locales can be queried with 'locale -a' in a terminal.
```
Here's output of `locale -a`: http://pastebin.com/raw.php?i=YbQiLUQw

I'm on Fedora 22, using master branch.

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by procedural** [comment]
Same warning on Manjaro (Arch Linux based distro).

On Ubuntu everything is fine, btw.

**Comment by bilderbuchi** [comment]
Intended resolution (TODO) before 0.9.0, by @arturoc:

> yeah, thanks, i added that warning mostly to see if some people would have any problem with this. usually by default the locale is 'c' but if in platforms where there's no c.utf8 it defaults to the current system language it's totally ok. i'll remove the warning before the release. thanks

**Comment by arturoc** [comment]
@procedural, can you check what's the default locale in those systems with the same method described in #4100

**Comment by procedural** [comment]
@arturoc missed your message, sure I'll test it

**Comment by procedural** [comment]
Yes, `std::locale("").name()` returns `en_US.UTF-8` on both Fedora 22 and Manjaro Linux (Arch-based). 

But I have a feeling that it would return `ru_RU.UTF-8` if I would install a system with Russian language, for example.

**Comment by arturoc** [comment]
yes that's ok, in debian it defaults to "C" which is not utf8 and some characters won't be upper or lower cased correctly for example but if you have a UTF8 locale it will work ok. i'll make that check also take into account if the default locale is utf8

thanks!
