### ISSUE TITLE
Compute shader texture sample isn't updated in each frame

### ISSUE THREAD

**Issue by mruegenberg** [openframeworks/openFrameworks#4054]
I'm not certain why, but the `computeShaderTextureExample` code only works correctly for me if I bind the video player's texture in every frame. I have to insert `                player.getTexture().bindAsImage(0,GL_READ_ONLY);` before `shader.begin()` in `ofApp::update()`.

(I'm on Arch Linux, with a GTX 680 and OpenGL 4.5.0. I pulled the repo earlier today.)

broken:
![broken](https://cloud.githubusercontent.com/assets/78885/8513719/811edb2c-2376-11e5-887b-3fa044fd4186.png)

fixed:
![fixed](https://cloud.githubusercontent.com/assets/78885/8513720/82a84bc2-2376-11e5-9baf-791da0333898.png)

**Comment by bilderbuchi** [comment]
ping @openframeworks/2d-3d

**Comment by openframeworkstests** [comment]
can you send a PR?

**Comment by mruegenberg** [comment]
I sent a PR. 

The underlying issue seems to be that ofVideoPlayer doesn't have a valid texture until its `update()` method was called once.
