### ISSUE TITLE
Use modernized data types for ofBaseSoundInput / ofBaseSoundOutput

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4070]
Currently the interface for ofBaseSoundInput ofBaseSoundOutput could use a cleanup.  This would also make it consistent with a modernized `ofSoundBuffer`, etc.

```c++
/// \brief A base class representing a sound input stream.
class ofBaseSoundInput{
	public:
		/// \brief Destroy the ofBaseSoundInput.
		virtual ~ofBaseSoundInput() {};
	
		virtual void audioIn( ofSoundBuffer& buffer );
		virtual void audioIn( float * input, int bufferSize, int nChannels, int deviceID, long unsigned long tickCount );
		/// \todo
		virtual void audioIn( float * input, int bufferSize, int nChannels );
		/// \todo
		virtual void audioReceived( float * input, int bufferSize, int nChannels ){}
};


/// \brief A base class representing a sound output stream.
class ofBaseSoundOutput{
	public:
		/// \brief Destroy the ofBaseSoundOutput.
		virtual ~ofBaseSoundOutput() {};
	
		virtual void audioOut( ofSoundBuffer& buffer );
		/// \todo
		virtual void audioOut( float * output, int bufferSize, int nChannels, int deviceID, long unsigned long tickCount  );
		/// \todo
		virtual void audioOut( float * output, int bufferSize, int nChannels );

		/// \todo
		/// \note This is a legacy method.
		virtual void audioRequested( float * output, int bufferSize, int nChannels ){
		}
};
```

Proposed (would also require updates in all of the various implementations).

```c++
/// \brief A base class representing a sound input stream.
class ofBaseSoundInput{
	public:
		/// \brief Destroy the ofBaseSoundInput.
		virtual ~ofBaseSoundInput() {};
	
		virtual void audioIn( ofSoundBuffer& buffer );
		virtual void audioIn( float * input, std::size_t bufferSize, std::size_t nChannels, int deviceID, uint64_t tickCount );
		/// \todo
		virtual void audioIn( float * input, std::size_t bufferSize, std::size_t nChannels );
		/// \todo
		virtual void audioReceived( float * input, std::size_t bufferSize, std::size_t nChannels ){}
};


/// \brief A base class representing a sound output stream.
class ofBaseSoundOutput{
	public:
		/// \brief Destroy the ofBaseSoundOutput.
		virtual ~ofBaseSoundOutput() {};
	
		virtual void audioOut( ofSoundBuffer& buffer );
		/// \todo
		virtual void audioOut( float * output, std::size_t bufferSize, std::size_t nChannels, int deviceID, uint64_t tickCount  );
		/// \todo
		virtual void audioOut( float * output, std::size_t bufferSize, std::size_t nChannels );

		/// \todo
		/// \note This is a legacy method.
		virtual void audioRequested( float * output, std::size_t bufferSize, std::size_t nChannels ){
		}
};
```

**Comment by arturoc** [comment]
those methods are there for compatibility reasons but everyone should be using the one that accepts an ofSoundBuffer as parameter, changing the types of the old ones will defeat the purpose which is keep old projects working

**Comment by bakercp** [comment]
Got it.

**Comment by bilderbuchi** [comment]
> everyone should be using the one that accepts an ofSoundBuffer as parameter,

are the "old" ones marked deprecated?

**Comment by bakercp** [comment]
Good point @bilderbuchi.  Will take a look.

**Comment by arturoc** [comment]
this is inherited not directly called so deprecating them won't really trigger a warning i think

**Comment by bilderbuchi** [comment]
I _do_ think so... wherever something is _used_, and I think constructing an instance (an therefore triggering the base constructor) is definitely a use in my mind (haven't tried this though)

**Comment by bakercp** [comment]
Am working on it now and it def triggers warnings.  So to be clear, all methods above except the ones that take the `ofSoundBuffer& buffer` argument are deprecated?

**Comment by arturoc** [comment]
mmh does it trigger a warning when creating a class that overwrites that method? we are calling that methods from the new one so it will always trigger the warning from there but that's not what we want

**Comment by bilderbuchi** [comment]
well then our new methods are using deprecated code/code they shouldn't use.  ;-)

**Comment by bakercp** [comment]
Yeah. .. that's what's happening.  Always triggering a warning.  It seems that 

```c++
        virtual void audioIn( float * input, int bufferSize, int nChannels, int deviceID, long unsigned long tickCount );
```

and 

```c++
		virtual void audioOut( float * output, int bufferSize, int nChannels, int deviceID, long unsigned long tickCount  );
```

isn't deprecated then?

**Comment by bakercp** [comment]
Or do we have to deprecate it in two steps to migrate the API over?

**Comment by bakercp** [comment]
Hm deprecating only two doesn't remove the warnings because they are cascading through all of the callbacks.

**Comment by arturoc** [comment]
they are deprecated but the way they are used is by inheriting in ofApp for example, nobody is going to call this methods except OF internally so it doesn't much sense to mark them as deprecated because it'll trigger the warning when compiling OF and nothing else so it'll never signal people that those methods they are using in their app are deprecated

**Comment by bilderbuchi** [comment]
> except OF internally

make them private could be an option, then?

**Comment by arturoc** [comment]
it won't make any difference, the way of using them is not by calling them but by overwriting them, if you make them private you can still override them

**Comment by arturoc** [comment]
in any case this isn't really a problem we just keep compatibility with an old way of receiving that callback we don't need to replicate functionality or anything like that  and it's fine as it is i said deprecated but we can call it legacy if you prefer :) it's totally ok if it remains there. as long as the examples show the new way we can remove the old ones in the future if we want but they can even remain as alternative ways of receiving that callback.

**Comment by bilderbuchi** [comment]
do they at least have docstrings warning users not to use the functions?

**Comment by bakercp** [comment]
@arturoc that seems like a reasonable solution.  I do think the data types should be updated or we should schedule it for true deletion.  If we can mark them with deprecation / warnings in the documentation, that might be a compromise.  And basically say -- this will be removed ... use at your own risk!

**Comment by bakercp** [comment]
OK.  Added documentation.  Should close this issue.
