### ISSUE TITLE
ofAVFoundationPlayer warnings

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4073]
The following null check creates a warning.  `CVOpenGLTextureCacheCreate` is a function that returns an int, not a pointer, thus it always evaluates to `true`.

```c++
#ifdef TARGET_OF_IOS
    bTextureCacheSupported = (CVOpenGLESTextureCacheCreate != NULL);
#endif
#ifdef TARGET_OSX
    bTextureCacheSupported = (CVOpenGLTextureCacheCreate != NULL);
#endif
```

The same method is called during `load`, but since `(CVOpenGLTextureCacheCreate != NULL)` always evaluates to `true`, it always gets called.

Some clarity here to get rid of the warning is needed.

@julapy ?

**Comment by i-n-g-o** [comment]
also just came across this.
CVOpenGLTextureCacheCreate is supported from OSX 10.4.
oF need 10.7 anyways? -> i think its safe to suppose that texture Caches are supported.

for IOS i don't know. there maybe we need to check.

**Comment by i-n-g-o** [comment]
for a safety-check we could do it like this:
```C
#if defined(TARGET_OSX) && defined(MAC_OS_X_VERSION_10_4)
	bTextureCacheSupported = true;
#endif
```

**Comment by pizthewiz** [comment]
If OF-0.9.0 requires OS X 10.7, we probably don't need checks for earlier versions no?

**Comment by pizthewiz** [comment]
Actually, `CVOpenGLESTextureCacheCreate` was first available in iOS 5 so I think we are good for both OS X and iOS without any explicit checks.

**Comment by julapy** [comment]
that sounds right to me.
we should remove the check all together, since it was introduced when ofxiOS target was > 5.0
now that 5.0 is minimum, we can assume those functions are there.

**Comment by i-n-g-o** [comment]
if not done already, here a PR:
https://github.com/openframeworks/openFrameworks/pull/4095
