### ISSUE TITLE
ofCamera orbit latitude 89º limit

### ISSUE THREAD

**Issue by autofasurer** [openframeworks/openFrameworks#4081]
ofCamera doesn't allow for 90º latitude due to the following in the orbit's function: 

    p.rotate(ofClamp(latitude, -89, 89), ofVec3f(1, 0, 0));

**Comment by bilderbuchi** [comment]
ping @roymacdonald (correct?)

**Comment by bilderbuchi** [comment]
@autofasurer this could be to avoid gimbal-locking the camera

**Comment by autofasurer** [comment]
@bilderbuchi yes, that's what @roymacdonald told me as well in his forum reply; he asked me to post it here.

**Comment by roymacdonald** [comment]
Hi,
right.
There's an ofClamp function that avoids having an angle of 90 degrees. This is there for some reason, which probably is to avoid gimbal lock. If done using quaternions it doesn't happen. 
I'll fix it later and PR.
best

**Comment by procedural** [comment]
>There's an ofClamp function that avoids having an angle of 90 degrees. This is there for some reason, which probably is to avoid gimbal lock. If done using quaternions it doesn't happen. 
I'll fix it later and PR.

Would've been great if you could update ofNode too! It has this clamp as well:

https://github.com/openframeworks/openFrameworks/blob/1f6f681/libs/openFrameworks/3d/ofNode.cpp#L340

**Comment by roymacdonald** [comment]
@procedural that the line I was referring to. ofCamera inherits from ofNode.
best

**Comment by roymacdonald** [comment]
Ok. so I just fixed this. 
it is here.
https://github.com/roymacdonald/openFrameworks/tree/fix-ofNodeOrbit
I tested it with the code in this gist
https://gist.github.com/roymacdonald/8d8e2260c593209e3918
Shall I PR?

**Comment by tgfrerer** [comment]
+1 looks sound =)

**Comment by arturoc** [comment]
yes send a PR
