### ISSUE TITLE
Regression bug introduced into ofMesh

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#4083]
Indices in getMeshForIndices() are being set to zero. Problem introduced into this commit:
https://github.com/openframeworks/openFrameworks/commit/ef7a0b30ca7116965e5822146667948d4fc98eed

````
    for(ofIndexType i = startIndex; i < endIndex; i++) {
        ofIndexType index = getIndex(i) - offsetIndex;
		index = 0;
		bFoundLessThanZero = true;
````

should be

````
    for(ofIndexType i = startIndex; i < endIndex; i++) {
        ofIndexType index = getIndex(i) - offsetIndex;
        if(index < 0) {
	     index = 0;
	     bFoundLessThanZero = true;
        }

**Comment by arturoc** [comment]
ofIndexType is an unsigned type so the comparison should be done in some other way

**Comment by pierrep** [comment]
Is it at all meaningful to do that test then? Can indices be less than zero?

**Comment by arturoc** [comment]
no but if getIndex(i) < offsetIndex then index will overflow and probably crash the app when trying to access such an index, i guess

**Comment by pierrep** [comment]
@bakercp  @tgfrerer  any input on this?

**Comment by tgfrerer** [comment]
if (startIndex < endIndex) {
        for(ofIndexType i = startIndex; i != endIndex; ++i) {
            ofIndexType index = 0;
            if(offsetIndex >  getIndex(i)) {
                 bFoundLessThanZero = true;
            } else {
                index = getIndex(i) - offsetIndex
            }
    }
