### ISSUE TITLE
multisampled ofFbo issues when drawing inside another ofFbo

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#4096]
Hi, I am finding weird issues when drawing one multisample FBO inside another one.

	int numSamples = 8;
	fbo1.allocate(300,300, GL_RGBA, numSamples);
	fbo2.allocate(300,300, GL_RGBA, numSamples);

	fbo1.begin();
	ofClear(0,0,55,255);
	ofDrawCircle(mouseX, mouseY, 33);
	fbo1.end();

	fbo2.begin();
	fbo1.draw(0,0);
	fbo2.end();

This should draw nothing to screen, but if numSamples is > 0, it does. 
In my setup (today's github master, OS X 10.10.4), if numSamples > 0, it draws fbo1 at the bottom-left of my window, flipped vertically.

It works as expected with numSamples == 0.

**Comment by tgfrerer** [comment]
Hm, maybe what happens is that the 8 samples fbo does not get allocated properly and the draw operation goes straight to screen instead of into the fbo...

Do you get error messages or printouts when allocating / drawing with such FBO when lowering the log level to OF_LOG_VERBOSE?

Also does it work as expected if the sample count is lower, say, 2?

**Comment by armadillu** [comment]
Yep, they allocate fine. It's also fine if I don't draw one inside of each other. I'm on an Nvidia GTX 650 TI if it helps.

**Comment by tgfrerer** [comment]
Just to flag that i'm working on this. I've currently narrowed it down to `ofFbo::updateTexture`, which is where multisample framebuffers (MSAA framebuffers) get resolved into textures. My current working theory is that there might be a subtle GL state leak.

**Comment by armadillu** [comment]
@arturoc  I think you forgot the update the ofGLRenderer and the ofGLProgrammableRenderer with the new method name, you probably meant this: #4107
