### ISSUE TITLE
Unicode support for MinGW

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#4103]
[Commenting on this comment in code](https://github.com/openframeworks/openFrameworks/blob/ec83be4/libs/openFrameworks/utils/ofSystemUtils.cpp#L633):

It's true that MinGW uses `char` by default, but if unicode flags are defined it switches to `wchar` and wide strings as MSVC, thus there's no need for separate code logic for these two compilers.

Here's a patch that makes MinGW compile openFrameworks with unicode characters:

https://github.com/ofnode/of/blob/4798f6c/dev/patches/openframeworks_mingw_unicode.patch

It's not a pull request because in order to make these changes work you should define `UNICODE` and `_UNICODE` flags in Code::Blocks projects and I don't know how to do that.

Pinging @ofTheo I suppose :)

**Comment by bilderbuchi** [comment]
> It's not a pull request because in order to make these changes work you should define UNICODE and _UNICODE flags in Code::Blocks projects and I don't know how to do that.

You can always make a PR, indicate what is missing, and people more knowledgeable in the area you need can send _you_ a PR to your originating branch, which when merged will automatically appear in the PR.

**Comment by procedural** [comment]
> can send you a PR to your originating branch, which when merged will automatically appear in the PR.

Ah, I didn't think of that! Thanks, Chris, I'll PR then.

**Comment by procedural** [comment]
The branch is merged, but `UNICODE` and `_UNICODE` flags should be defined in Code::Blocks projects

**Comment by arturoc** [comment]
can you add it in the template in scripts/win_cb/template ?

**Comment by procedural** [comment]
I don't know where to add, nor how to check if it will work, I don't use Code::Blocks. Guide me!

**Comment by procedural** [comment]
[Compiler options](https://github.com/openframeworks/openFrameworks/blob/master/scripts/win_cb/template/emptyExample.cbp#L20) maybe?

**Comment by arturoc** [comment]
what do you use? how do you usually pass this option?

**Comment by procedural** [comment]
@arturoc raw cmake & command line.

Ok, I've generated CB project and definitions indeed in <Compiler> section, each line looks like:

```xml
         <Compiler>
            <Add option="-DUNICODE" />
            <Add option="-D_UNICODE" />
            ...
```

**Comment by arturoc** [comment]
yes that looks correct

**Comment by bilderbuchi** [comment]
@procedural btw, project files generation for which IDEs does cmake support? I dream of a day where we don't have to futz around with N sets of project files anymore.. ^^ (We use XCode, Codeblocks, VS, Eclipse, make afaik)

**Comment by procedural** [comment]
I use Qt Creator, it parses CMake and generates Ninja project files for faster compiling, also it can generate for Code::Blocks as I tested today, I used it with VS2013 just fine, except for [some tiny quirks](https://github.com/ofnode/of/issues/15#issuecomment-120452331) people generate projects for Xcode too. Here's the full list of all supported IDEs (Eclipse is there): http://www.cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html#extra-generators

**Comment by procedural** [comment]
I knew about CMake from VFX industry where it is used heavily, when I saw openFrameworks for the first time I thought "gee, it must be error prone to make changes for each project like that" and started [ofnode/of](https://github.com/ofnode/of) to fix it. Currently it totally works for my needs.

**Comment by bilderbuchi** [comment]
> "gee, it must be error-prone to make changes for each project like that" 

I'm happy that we at least have a encompassing makefile structure now, this was a huuge effort by @arturoc and @bakercp (and others?), but that thought is one I have often had.. :-D

**Comment by bilderbuchi** [comment]
It's a pity that you didn't fork OF properly, this way we can't really compare what has changed w.r.t. to OF proper.

**Comment by procedural** [comment]
> It's a pity that you didn't fork OF properly, this way we can't really compare what has changed w.r.t. to OF proper.

Nothing was changed, it's not a fork :)

**Comment by bilderbuchi** [comment]
I don't understand?

**Comment by procedural** [comment]
It's vanilla openFrameworks, repackaged for CMake which repo size is around 16 MB of download :) It syncs automatically by scripts with this repo.

**Comment by procedural** [comment]
#4166 is merged, the issue can now be closed!
