### ISSUE TITLE
Visual Studio 2015 Release

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4129]
Microsoft released the release version of VS2015 which replaces the Release Candidate, I will run a test to make sure everything works properly. I don't expect there to be anything different but certainly needs to be checked

**Comment by kylemcdonald** [comment]
awesome! thanks for keeping up to date on this, it will be great to release 0.9.0 with support for the latest IDE :)

**Comment by DomAmato** [comment]
Everything seems to compile ok, I will probably reopen this when windows 10 gets officially released next week,especially with their added support of ARM processors that could add another wrinkle in the process
