### ISSUE TITLE
Projectgenerator ios - overwrites ios icons/images on project update.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4137]
Overwrites all icons with names:

```
Default-568h@2x~iphone.png
Default.png
Default@2x.png
Default@2x~ipad.png
Default@2x~iphone.png
Default~ipad.png
Default~iphone.png
Icon-72.png
Icon-72@2x.png
Icon.png
Icon@2x.png
```

This makes sad if one didn't duplicate and save all customized icons before updating the project files ... :(

**Comment by ofZach** [comment]
relevant lines if you want to add a fix, such as checking if files exists and not overwriting, etc: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/xcodeProject.cpp#L277-L287

**Comment by bakercp** [comment]
@ofZach thx.  Will do.

**Comment by danoli3** [comment]
I'll fix this up @bakercp

**Comment by danoli3** [comment]
Okay fixed! https://github.com/openframeworks/projectGenerator/pull/100
