### ISSUE TITLE
Minibug : ofParameter throws lots of warnings

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4144]
Since `ofParameter` supports `bool` and treats bool as a number, the compiler throws lots of warnings.

I'm getting 5 warnings per every one of my cpp files which includes ofMain on VS2015.

Do you experience anything similar on Xcode / other?

**Comment by bilderbuchi** [comment]
would be great to know _which_ warnings you get, and where. ;-)

**Comment by DomAmato** [comment]
From my compilation tests its just resizing errors from sizet to int etc... nothing that appears problematic

**Comment by DomAmato** [comment]
Is this corrected by https://github.com/openframeworks/openFrameworks/pull/4160?

**Comment by bakercp** [comment]
Some of this should be corrected ... I'm not sure about the bool issues though.

**Comment by DomAmato** [comment]
@elliotwoods can you test it with the newest master? I will compile it too but I don't know how many warning you were getting

**Comment by elliotwoods** [comment]
hey!
i'm on a version of master which is about a week old right now
don't want to pull because in the middle of something. did something change with the warnings?

for reference:
```
f:\openframeworks\libs\openframeworks\types\ofparameter.h(217): warning C4804: '-': unsafe use of type 'bool' in operation
f:\openframeworks\libs\openframeworks\types\ofparameter.h(217): note: while compiling class template member function 'bool ofTypeInfo_<T,true>::min(void)'
        with
        [
            T=bool
        ]
f:\openframeworks\libs\openframeworks\types\ofparameter.h(364): note: see reference to function template instantiation 'bool ofTypeInfo_<T,true>::min(void)' being compiled
        with
        [
            T=bool
        ]
f:\openframeworks\libs\openframeworks\types\ofparameter.h(229): note: see reference to class template instantiation 'ofTypeInfo_<T,true>' being compiled
        with
        [
            T=bool
        ]
f:\openframeworks\libs\openframeworks\types\ofparameter.h(360): note: see reference to class template instantiation 'ofTypeInfo<ParameterType>' being compiled
        with
        [
            ParameterType=bool
        ]
f:\openframeworks\libs\openframeworks\types\ofparameter.h(360): note: while compiling class template member function 'ofParameter<bool>::Value::Value(void)'
f:\openframeworks\libs\openframeworks\types\ofparameter.h(408): note: see reference to function template instantiation 'ofParameter<bool>::Value::Value(void)' being compiled
f:\openframeworks\libs\openframeworks\types\ofparameter.h(350): note: see reference to class template instantiation 'ofParameter<bool>::Value' being compiled
f:\openframeworks\libs\openframeworks\types\ofparameter.h(349): note: while compiling class template member function 'const ofParameterGroup ofParameter<bool>::getFirstParent(void) const'
```

i think that's just 1 warning, just a very long one :)

**Comment by elliotwoods** [comment]
no i haven't got that commit yet in my local copy. will test and report.
just not right this minute :)

**Comment by bilderbuchi** [comment]
I don't know how conclusie this is, but in the build log  [of a recent CI build](https://ci.appveyor.com/project/arturoc/openframeworks/build/1.0.332/job/cwm34foubn62rrrr), there's no mention of C4808. Loads of other warnings, though ^^.

**Comment by elliotwoods** [comment]
on recent master (today's) and most warnings seem to be gone. as bilderbuchi noted, no ofParameter warnings of that type any more
congrats!

still get the `Unknown compiler version - please run the configure tests and report results` in Boost

**Comment by bilderbuchi** [comment]
Apparently that warning will [go away](http://stackoverflow.com/a/30959156/599884) as soon as we upgrade to Boost 1.59.

**Comment by elliotwoods** [comment]
for the time being, i recommend commenting out Line 292 from visualc.hpp. Perhaps even in our github repo

**Comment by elliotwoods** [comment]
the most common warning we have right now is warning C4267
which is a lazy cast (e.g. `size_t` to `int`)
since it's so pervasive (all over the code base), i'm suggesting we add it to an ignored warning
here's an example set of those warnings from a from a build:
https://gist.github.com/elliotwoods/a8e55dcd924614746029
