### ISSUE TITLE
Raspberry Pi Updates gcc updates for 0.9.0

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4146]
So as far as I know, the default compiler on RPi is still 4.6, which doesn't support a handful of our required updates (`thread_local` etc).  It is easy enough to install gcc-4.8 / g++-4.8 as they are standard packages.  While we could write scripts that will create gcc/g++ symlinks, I'd suggest that we download g++4.8 with our install scripts and then defined `CXX` as g++-4.8 in the raspberry pi make file configs.  That way it won't change the default compiler for the system.

Also, since raspberry pi is our default armv6 variant, would it make sense to make raspberry pi 2 our default armv7 variant?  There are lots more armv7, and I'm not exactly sure what our default armv7 config currently targets.  To get raspberry pi 2 compiled with the master branch (or at least mostly compiled) the command is something like:

```
make -s -j4 PLATFORM_VARIANT=rpi2 CXX=g++-4.8
```

**Comment by bakercp** [comment]
OK.  I did bunch more investigation on this and my conclusion is that we should figure out the easiest way to compile oF with g++-4.8+.  I tried to go back and modify the core to compile with the version of g++ shipped with raspbian, but @ 4.6.3, there are just too many errors to fix (problems with `using` bunch of places, problems with no thread_local -- etc).  It's certainly possible to make it work, but it would be easier I believe to include create a raspberry pi dependencies script which simply calls the core debian dependency script (to avoid more dependencies) and installs g++ 4.8.  Alternatively we could modify the dependency script to conditionally install an updated version of g++ if the system version is < 4.8.

Then, in our rpi and rpi2 makefiles we should just set the CXX variable to g++4.8.  That way the transition from 0.8.4 to 0.9.0 is fairly transparent to the user.

@arturoc thoughts on this strategy?

**Comment by arturoc** [comment]
i'd detect the debian version and just install gcc 4.9 if we are on wheezy. this:

```bash
DIST_CODENAME=$(lsb_release -c | cut -f2)
```

should return wheezy or perhaps raspbian on raspbian

**Comment by bakercp** [comment]
@arturoc OK.  I'll check it out.

**Comment by bakercp** [comment]
`lsb_release` is not on raspbian by default, so I'm going to use a slightly different approach to getting the current version like this:

https://askubuntu.com/questions/450298/how-to-get-ubuntu-distributions-full-code-name

**Comment by groolot** [comment]
my experience tells me to follow what @bakercp suggested. it is better, i think, to test the g++ availability with correct C++ flavour instead of testing the distribution.
