### ISSUE TITLE
Apothecary scripts for addons Windows issues

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4156]
Perhaps I am doing it wrong but when I use apothecary to try and update the libs for assimp and openCV it doesn't place the resulting files in the right place. Perhaps my syntax is wrong but I sort of had this problem before. This is with Git Bash for windows.

 I try calling assimp with

    apothecary update ../../../addons/ofxassimpmodelloader/scripts/formulas 
and everything runs fine but when it comes time to copy the files over it move them to
libs/assimp/include etc... instead of addons/ofxassimpmodelloader/libs/assimp/include etc...

**Comment by bilderbuchi** [comment]
ping @openframeworks/apothecary

**Comment by gorkacortazar** [comment]
@DomAmato can you check with the sintax
´´´
apothecary update addonName
´´´

It's the one I tested when I updated the assimp for VS 2015. Be aware that creates separated libs for 32/64 bits, but the project generator add both to all the profiles and you have to correct it manually.

**Comment by DomAmato** [comment]
just typing 

    apothecary update assimp 
gives the response: 

    no formula for lib "assimp"
which is why I included the path to the script, the inverse also doesn't appear to work when i change the directory to where the assimp formula is and then use the path to apothecary

**Comment by gorkacortazar** [comment]
It  should be
```
apothecary update ofxAssimpModelLoader
```

I think that opencv and assimp resides in their addons, not in the core ofx.

**Comment by DomAmato** [comment]
That seems to work but I think its slightly strange since it doesn't really conform to the standard of other apothecary scripts but thats a discussion thats beyond the scope of this issue

**Comment by bilderbuchi** [comment]
>  it doesn't really conform to the standard of other apothecary scripts but thats a discussion thats beyond the scope of this issue

How so? That's the way it's specified in the apothecary readme, and assimp lives in an addon...

**Comment by DomAmato** [comment]
Right but in terms of the core scripts calling it like

    apothecary update glew
feels like your calling the script, I get why you call ofxOpenCV since the ofx is acting as a delimiter to let apothecary know its looking in the addons rather than the default formulas folder but it just seems inconsistent when the actual script name is openCV. It also seems like placing the scripts in the addons folder is kinda arbitrary because you wouldn't use the apothecary scripts as a normal user and since ofxKinect, ofxOpenCV and ofxAssimp are essentially core parts of openframeworks it seems to me like they would be better suited in the normal formulas folder and then would be updated when you do:

     apothecary update core
Thats just my ten cents though my stance is just as arbitrary

**Comment by gorkacortazar** [comment]
@DomAmato I beg to differ, while OpenCV or Assimp are distributed with the core, they are separated addons to not be part of the core (not every project needs it). Another interesting stuff of how it is done is that you can create apothecary formulas for non core addons. This not happen that much currently, but seems a good feature.
