### ISSUE TITLE
Fix remaining CI issues

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#4162]
The new CI build has a couple of remaining TODOs/problems, I'll try to deal with those in further PRs

* [x] Linux build sometimes fails with " "g++-4.9: internal compiler error: Killed (program cc1plus)"", due to lack of RAM/swap, apparently. (also happens on Arturo's build). Could be that [this](http://stackoverflow.com/a/16372032/599884) or [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56746#c7) could reduce g++ memory consumption.
* [x] Sometimes (currently often) the apt-get step in linux builds fails with Error 137 when installing g++-4.9, reason currently unknown.
* [ ] doc builds fail, see HalfdanJ/ofDocGenerator#3. set to allow failure for now.
* [x] Move docs to docker builds (all packages are whitelisted), cf. travis-ci/travis-ci#4557
* [x] Confirm cache works correctly, maybe have to remove ever-changing files (.awk?)
* [x] add allAddonExample to build stage
   * ~~Ask for 14.04 beta access (done but doesn't work when using macos builds, too)~~ Done - needs a `dist: trusty` and `sudo: required` (so does not work on the docker builds)
   * `dist: trusty` flag to activate 14.04 workers does collide with `os: osx`, making those builds run on Linux. Therefore, this has been postponed until this is fixed by travis.
   * With 14.04, we (hopefully) get recent enough versions of the addons' dependencies (e.g. opencv, assimp) to activate compiling the allAddonsExample, which would cover more of the OF codebase.

**Comment by bilderbuchi** [comment]
so,  g++ and apt-get being killed seems to have disappeared now.
I have no idea how to fix the docs build.

**Comment by danoli3** [comment]
@arturoc Want to just add Linux to Allowed Failures for the moment till that is sorted?

**Comment by arturoc** [comment]
it's now fixed

**Comment by HalfdanJ** [comment]
Regarding the doc generator. Please just remove it form the travis file for now. I'm working on an update, but there is no reason for now to letting it fail all the time

**Comment by bilderbuchi** [comment]
@HalfdanJ I just did, [looks godd so far](https://travis-ci.org/openframeworks/openFrameworks/builds/91895109).
