### ISSUE TITLE
Option to set an ofParameter without notifying event listeners?

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4174]
Right now, as far as I can tell, the only way to set an ofParameter value without notifying its listeners is to do something like:

```c++
ofParameter<int> i = 0;

// subscribe to events

i.disabledEvents();
i.set(23);
i.enableEvents();
```

This seems like a pretty fast operation, as it's just binding and setting the `setMethod` to the no event setter, but this seems a little verbose, and perhaps slow.

Would there be opposition to adding a final argument to the set methods like --

```c++
	ofParameter<ParameterType> & set(const ParameterType & v, bool disableNotification = false);
	ofParameter<ParameterType> & set(const string& name, const ParameterType & v, bool disableNotification = false);
	ofParameter<ParameterType> & set(const string& name, const ParameterType & v, const ParameterType & min, const ParameterType & max, bool disableNotification = false);
``` 

In this scheme it wouldn't break the encapsulation (as users already have the ability to enable and disable events) but it would potentially allow the implementation to be a bit faster and more flexible.

@arturoc?

**Comment by bakercp** [comment]
Made a slight modification to clarify that the parameter will still respect the existing "disabled() / enabled()" state.

**Comment by bakercp** [comment]
This would also us to get rid of the `updatingParameter` variable in `ofxOscParameterSync` which was a little confusing at first.

**Comment by arturoc** [comment]
i'd rather prefer to add a setWithoutEvents(value) or setDontNotify(value) or somthing like that, passing booleans like that in a method makes the syntax really confusing, we use it in a couple of places and it's not a very good idea, like:

```
fbo.begin(false)
```

which means begin the fbo but don't set the default perspective.

also i would only add it for the version that only sets the value not the name, min, maxx... as you usually don't need to set those without notifying the events

**Comment by bakercp** [comment]
OK.  I like that approach.  I was looking for the method that wouldn't add additional methods.  I'll add a method like setWithoutEventNotifications().  PR shortly.
