### ISSUE TITLE
ofxKinect can support v2 device?

### ISSUE THREAD

**Issue by yty** [openframeworks/openFrameworks#4181]
@ofTheo 

I have seen https://github.com/ofTheo/ofxKinectV2

But it seems very old version, can not and now libfreenect2 Compatible.

https://github.com/OpenKinect/libfreenect2

**Comment by ofTheo** [comment]
It is an old version but the new libfreenect2 has issues with OF as it uses threaded OpenGL shaders to decode the depth frames, which causes flickering as the GL calls are getting mixed up between threads. 

If you are on windows I recommend @elliotwoods - https://github.com/elliotwoods/ofxKinectForWindows2
Its really clean and gives you access to all the K4W stuff.
