### ISSUE TITLE
ofFile and ofDirectory doesn't understand "~" symbol

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#4182]
I had code from a while ago that used to check for folder in home directory, but it doesn't work now because `ofFile` and `ofDirectory` doesn't understand `~` paths:

```
cout << ofDirectory("~").exists() << endl; // Returns 0, should 1.
```

Can we have it back or there's another way to get a path to home dir now without using commands like `string HOME = ofSystem("printf $HOME");`?

**Comment by bilderbuchi** [comment]
can you pin down when it broke (with git bisect)?

**Comment by procedural** [comment]
@bilderbuchi I would like to, but I will be dead by the end of git clone of the repository.

**Comment by bilderbuchi** [comment]
are you working from a downloaded release package right now?? or do you have a shallow clone of current master?

**Comment by ofZach** [comment]
I'd guess it's the change to boost filesystem for path things (trying to move away from poco for parts of the core):
https://github.com/openframeworks/openFrameworks/pull/3913

this may be relevant?
http://stackoverflow.com/questions/4891006/how-to-create-a-folder-in-the-home-directory

**Comment by procedural** [comment]
@bilderbuchi

> or do you have a shallow clone of current master?

Shallow clone with depth of 1

@ofZach 

my thoughts, too.

**Comment by arturoc** [comment]
yeah this is happening because we changed to boost (which will be std) filesystem. since this is going to be the standard i think it's ok to leave it as it is, in any case `~` as home is only a bash thing: http://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html not even unix so i think it's safe to not have support for it.

The multiplatform way to do it is:

```
ofDirectory(ofFilePath::getUserHomeDir()).exists();
```

**Comment by procedural** [comment]
@arturoc Didn't knew it's only a bash thing... The issue can be closed then. Thanks for multi-platform example!
