### ISSUE TITLE
shader tutorials are missing in the last ubuntu release

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4184]
maybe this is by intention, but the [online tutorial](http://openframeworks.cc/tutorials/graphics/shaders.html) says "You can find them in the tutorials folder  of your OF download" which is then wrong

**Comment by bilderbuchi** [comment]
you mean in the packaged release? @arturoc do you strip those in the packaging script?

**Comment by avilleret** [comment]
yes shader tutorials are missing in the packaged release

**Comment by arturoc** [comment]
we should also fix the tutorial to show the right way to create a window using opengl 3+

**Comment by arturoc** [comment]
what should we do about this? i see 4  possibilities:

1) change the tutorials text to say that they should be downloaded from github
2) host the tutorials in the webpage with the texts as a zip or something with the project files for every platform
3) include the tutorials folder in the download
4) move the tutorials examples to the gl examples
