### ISSUE TITLE
ofEvent::notifyAsync missing after dropping Poco

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4192]
ofxSniffer was using notifyAsync to send packets from inside a threaded function to another thread, to avoid blocking either the sniffing thread or the main loop: https://github.com/HalfdanJ/ofxSniffer/blob/master/src/ofxSniffer.cpp#L200

This method was inherited from Poco and is no longer available with the new Event implementation. Is there another method that can replace this behavior? I can imagine another way to do it that will probably have less overhead (though I'm not sure how notifyAsync worked internally, I bet there was a lot of thread creation & joining), but it will take a bit more code.

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by arturoc** [comment]
For doing inter thread communication the new ofThreadChannel is the way to go. notifyAsync was creating a new thread every time only to send a message, otThreadChannel allows for asynchronous communication between 2 threads in a more correct way than notifyAsync. 

I see that ofxSniff already uses ofThreadChannel, i would just change rawPacketEvent with a public channel so people can query that channel directly in case they need to get the messages as fast as possible or from a thread other than the main thread. That avoids having to use locks or even being aware that those messages are coming from a different thread as it is advised in the comments now

**Comment by kylemcdonald** [comment]
great, going to move to ofThreadChannel instead of ofEvent for this.
