### ISSUE TITLE
openFrameworks can't be compiled in a path that contains spaces on Linux

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#4195]
Can be reproduced by placing openFrameworks folder in a path like `~/test folder`

**Comment by bakercp** [comment]
https://github.com/openframeworks/openFrameworks/issues/3160
https://github.com/openframeworks/openFrameworks/issues/2673

**Comment by bakercp** [comment]
http://stackoverflow.com/a/9516081/1518329 One of many imperfect but functional solutions.

**Comment by procedural** [comment]
> This is a makefile issue.

I'm sure it is... :)

**Comment by procedural** [comment]
Closed as duplicate.
