### ISSUE TITLE
ofFbo issues on ios platform

### ISSUE THREAD

**Issue by roikr** [openframeworks/openFrameworks#4199]
ofFbo on ios is broken in HEAD commit (edbbc1911)

it is working on 0.84 so something went wrong on 0.9 in master.
using standard allocation and calling it in update or draw,
will cause ignoring following drawing to main frame buffer.

UPDATE1:
the problem is with defaultFramebufferId first initialization, more specifically

void ofGLRenderer::setup(){
#ifdef TARGET_OPENGLES
	// OpenGL ES might have set a default frame buffer for
	// MSAA rendering to the window, bypassing ofFbo, so we
	// can't trust ofFbo to have correctly tracked the bind
	// state. Therefore, we are forced to use the slower glGet() method
	// to be sure to get the correct default framebuffer.
	GLint currentFrameBuffer;
	glGetIntegerv(GL_FRAMEBUFFER_BINDING, &currentFrameBuffer);
	defaultFramebufferId = currentFrameBuffer;
#endif

which is called before setting EAGL context in 
- (void)startRender {
    [EAGLContext setCurrentContext:context];
}
so the default is set to 0 (should be 2).

a workaround will be to move these lines to the begining of

void ofGLRenderer::startRender(){
#ifdef TARGET_OPENGLES
	// OpenGL ES might have set a default frame buffer for
	// MSAA rendering to the window, bypassing ofFbo, so we
	// can't trust ofFbo to have correctly tracked the bind
	// state. Therefore, we are forced to use the slower glGet() method
	// to be sure to get the correct default framebuffer.
	if (defaultFramebufferId==0) {
		GLint currentFrameBuffer;
		glGetIntegerv(GL_FRAMEBUFFER_BINDING, &currentFrameBuffer);
		defaultFramebufferId = currentFrameBuffer;
	}
#endif

but this workaround limits us to update fbos only in the draw event.

the workaround apply for the programmableRenderer also.

Roee

**Comment by bilderbuchi** [comment]
Hey @roikr, thanks for you bug report. Did you read the CONTRIBUTING.md document, like the New issue form asked you to? Specifically, [this section](https://github.com/openframeworks/openFrameworks/blob/master/CONTRIBUTING.md#report-a-bug) is important for you, as it tells you what information we need to properly deal with bug reports.
Thank you!

**Comment by bilderbuchi** [comment]
thank you. 
ping @openframeworks/2d-3d

**Comment by arturoc** [comment]
@julapy can you check if we can call setup after setting up the context? i'll check emscripten and android

**Comment by julapy** [comment]
have tested this by inserting the renderer setup call in the draw loop,
here >> https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxiOS/src/core/ofxiOSEAGLView.mm#L161

````
	uint64_t frameNum = ofGetFrameNum();
	if(frameNum == 0) {
		if(window->isProgrammableRenderer()){
			static_cast<ofGLProgrammableRenderer*>(window->renderer().get())->setup(window->getSettings().glesVersion, 0);
		} else{
			static_cast<ofGLRenderer*>(window->renderer().get())->setup();
		}
	}
````

and this fixes the fbo issue.
works when allocating the fbo in `setup` and in `update` or `draw`

it still feels like a hack thought and i'll try to figure out a better solution.

@arturoc you might have some other ideas on how this can be better achieved in the core perhaps?

**Comment by julapy** [comment]
turned out to be a timing issue.
not exactly sure what change in the core made this knock on effect...
but to fix, calling setup on the renderer had to be moved to a different point in the ofxiOS setup.
the renderer setup was moved to `ofxiOSEAGLView setup`

**Comment by arturoc** [comment]
thanks!
