### ISSUE TITLE
can't build projectGenerator/commandLine

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4201]
still running after a working project for building shader tutorials (see #4194), I tried to build what looks like a command line tool project generator to my eyes, but it fails with : 

~~~~
/home/antoine/lib-src/openFrameworks/apps/projectGenerator/commandLine/src/main.cpp:14:28: fatal error: CBLinuxProject.h: Aucun fichier ou dossier de ce type
 #include "CBLinuxProject.h"
~~~~

any hint ?

**Comment by ofZach** [comment]
can you move this issue to https://github.com/openframeworks/projectGenerator ?

**Comment by avilleret** [comment]
sure, here it is : https://github.com/openframeworks/projectGenerator/issues/7

then I'm closing this one and let you put the appropriate label (duplicate ?)

**Comment by avilleret** [comment]
I agree with most of the comment, but it doesn't really answer the question on how to build tutorials.
Thanks to @arturoc for the up-to-date code.
But I think a tutorial targets beginner, then its build workflow should be easy to understand and to do.
At least it should be documented somewhere.
For now the only way I found is to use the legacy project generator.
And I have to run it for each tutorial one by one, which is quite boring.
I think it should be good to have a tool like the `generate example` in the legacy project generator for the tutorials.
Maybe this tool exists, but again, it should be documented more obviously, because if it exists I missed it for some days... :-) 

So in my point of view the project generation should be done by the `buildAllExamples.sh` script.
For now this script just run `make` in each example folder, I think it should also generate project if they don't exists, to avoid error (btw this will make #4183 obsolete).
And the same applies to the tutorials.
We need a script to generate tutorials project and then build them.

If people should understand the whole project building process before trying thing it's unproductive I think.
At least, in my point of view, if I can quickly see what I can do with a tool then I'll want to learn more about that tool, but if I have to learn how the tool works *before* seeing what I so with it then I may give it up quickly. :-)
