### ISSUE TITLE
Issue Slimming

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4202]
Slightly meta to make an issue about trimming down issues but as of me writing this there are 520 issues and I think at least a few of them have been resolved though never closed. I've gone through and commented on a few and some are duplicates like:

https://github.com/openframeworks/openFrameworks/issues/1743
https://github.com/openframeworks/openFrameworks/issues/3068

the above aren't fixed to my knowledge and I intend to take a look at the problem tonight but they essentially are concerning the same bug, one is from 3+ years ago. Not to put more work on others its just a task to browse through the issues. If I find more duplicates ill post them in this issue as well

**Comment by DomAmato** [comment]
https://github.com/openframeworks/openFrameworks/issues/728
https://github.com/openframeworks/openFrameworks/issues/1960

These are now handled are they not with the clamped(operator) that is in ofColor

**Comment by DomAmato** [comment]
https://github.com/openframeworks/openFrameworks/issues/224
https://github.com/openframeworks/openFrameworks/issues/1134

These are in ofMath? I feel like i might be misunderstanding 1134's request but that the older issue is addressed

**Comment by bilderbuchi** [comment]
@DomAmato would be great if you would just comment on the affected issues themselves (i.e. flag them for closing, or close-as-duplicate, etc), that way the people originally discussing it can pick any further discussion up, if necessary.
Also re #224, I don't see a Gaussian random noise in ofMath, but I only glanced over it - could you point it out if you don't mind?

**Comment by bilderbuchi** [comment]
I'll close this, please discuss anything further in the relevant issues. Thanks for caring about removing duplicates and reducing the number of open issues, though!

**Comment by DomAmato** [comment]
No prob, I have been combing through and addressing the simple feature requests too that require very minor additions to code so hopefully can close another handful of issue on small requests

**Comment by kylemcdonald** [comment]
what @bilderbuchi said -- but also, if you have an idea about any more general approaches to slimming the issue list, post to of-dev. that's a great place for more meta discussions!
