### ISSUE TITLE
emscripten setup guide

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#4206]
- where to download and how to install emscripten.
- the emscripten download is included in the desktop one
- just compile with `emmake make` from a console or any ide that supports make and run by following the instructions from make or `emmake make run`

**Comment by kylemcdonald** [comment]
@arturoc were you planning on covering this, or would you like some help? maybe @reginaflores would be interested in contributing here?

**Comment by reginaflores** [comment]
Hi friends! @arturoc and @kylemcdonald I am happy to help! I have a short blog post about this here:
http://www.reginafloresmir.com/blog/2015/5/14/openframeworks-on-the-line

I can certainly write a bit more in detail about downloading and setting up if that is helpful. Would you like me to write it here in GitHub?

Happy to help!

**Comment by arturoc** [comment]
Hi regina, yes i've been sending people wanting to try emscripten to your post, i think what you have there is mostly it but if you want to add a couple of lines on how to install emscripten itself that might be useful too.

It's better to add it to ofSite, it's also markdown. you just need to add a new emscripten folder in setup:

https://github.com/openframeworks/ofSite/tree/master/setup

and add an index.html.make file in there. the file can be written in markdown and you can also use html in parts that need some more specific formatting that can't be done with markdown. you can also add images... in that folder.

the only requirement is that the index.html.mako file needs to have this as the first lines:

```
## -*- coding: utf-8 -*-
<%inherit file="/_templates/markdown.mako" />
```

**Comment by bilderbuchi** [comment]
@reginaflores @arturoc any news about this issue?

**Comment by reginaflores** [comment]
Hey guys! My bad I have been super busy. I will try to get it done this week.

**Comment by edap** [comment]
@reginaflores @arturoc @bilderbuchi I can take care of this issue in the weekend, I'm going to try out emscripten anyway, it would not take too long to add it to ofSite. Unless someone else is already working on it

**Comment by reginaflores** [comment]
ok great! let me know if i can help... i am so sorry i have been slammed with thesis work!

**Comment by edap** [comment]
@reginaflores @arturoc the pull request is created, you can have a look here https://github.com/openframeworks/ofSite/pull/353
Unfortunately I could not add the example `Sol Lewitt Met` because I didn't have the source. I've used one project in the examples folder. Consequently, some rewording was necessary.

**Comment by reginaflores** [comment]
This is great guys! I was promoting this yesterday at Parsons! @patriciogonzalezvivo is teaching a course at Parsons and I am encouraging the students to put their OF projects online using these instructions! Thanks for all your help in getting this going @edap @arturoc @kylemcdonald @bilderbuchi !!!!

**Comment by bilderbuchi** [comment]
openframeworks/ofSite#353 is merged, so I think we can close this. thank you very much @edap !
