### ISSUE TITLE
mingw windows

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#4207]
I have mingw windows compiling using msys2. msys2 includes a package manager, linux style, so i'm using a install_dependencies script as we do in linux and have added apothecary scripts for the missing libraries.

I propose to have that as a platform to run things like ofSketch and only support makefiles and drop codeblocks support in windows. The main reasons are that codeblocks hasn't get much better in all the years we've supported it and visual studio is now really easy to install. Also having support for makefiles and mingw we give people the option to still any IDE that supports compiling through makefiles (codeblocks does)

**Comment by ofZach** [comment]
+1 seems like a good approach.   it also keeps open the possibility of a mingw based IDE working down the line and helps ofSketch.

**Comment by arturoc** [comment]
btw, we only have 32bits version of mingw by now, there's no 64bit version of fmodex but once we have a different sound system it's pretty trivial to compile for 64bits, in fact is just a matter of changing some prefixes in the install_dependencies script and the windows specific makefile

**Comment by bilderbuchi** [comment]
@arturoc can you make that setup work/compile on appveyor? afaik, mingw is supported by appveyor, so would be cool if that were included in our CI builds
