### ISSUE TITLE
error when running the script ./install_dependencies.sh on raspberry pi B+

### ISSUE THREAD

**Issue by chfakht** [openframeworks/openFrameworks#4209]
Hi ,
i want to use openframworks on my raspberry pi B+ , so i have downloaded "of_v0.8.4_linuxarmv6l_release" ,after extraction and giving permission i runned ./install_dependencies.sh but i get the following errors

inserting gstreamer 1.0 repository
rm: cannot remove `/etc/apt/sources.list.d/gstreamer.list': No such file or directory
touch: cannot touch `/etc/apt/sources.list.d/gstreamer.list': Permission denied
./install_dependencies.sh: line 4: /etc/apt/sources.list.d/gstreamer.list: Permission denied
updating apt database
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
detecting latest gtk version
N: Unable to locate package libgtk3.0-dev
N: Couldn't find any package by regex 'libgtk3.0-dev'
E: No packages found
installing OF dependencies
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
error installing dependencies, there could be an error with your internet connection

thanks for help

**Comment by arturoc** [comment]
i think you are running install_dependencies without sudo. in any case most bugs should be fixed against the latest version in github so if you still have problems after running the script with sudo or su try using the nightly builds

**Comment by chfakht** [comment]
thanks but this is weird : i have give all permission with chmod to the user

**Comment by arturoc** [comment]
the script uses apt-get when it runs which needs root permissions so it's not so much about the permissions of the script but the permissions required by what it runs
