### ISSUE TITLE
Fix broken Android CI builds

### ISSUE THREAD

**Issue by bilderbuchi** [openframeworks/openFrameworks#4214]
@arturoc broke the Android builds on Travis with 9ede51464b2624899d91cce6072becd977032475 / https://travis-ci.org/openframeworks/openFrameworks/builds/74739344. This was not caught by a PR before landing in master. I currently don't have time to hunt this down, so I'll leave an issue.

One (to me) open question: which version of the NDK is the appropriate one for toolchain 19?

**Comment by bilderbuchi** [comment]
Problem found: I previously stripped out all android-1* toolchains, since we were on 21 already, so toolchain 19 got stripped out.
@arturoc can you add the android-19 folder to the ndk file, recompress and upload to our server [as before](https://github.com/openframeworks/openFrameworks/blob/1f6f6813908b4df56b6742d79fd21f27c9bed205/scripts/ci/android/install.sh#L14-L15)? Then you'll have to delete the [travis caches](https://travis-ci.org/openframeworks/openFrameworks/caches) and re-trigger some build (or just wait) - as soon as we got one upload/decompress working we'll have a new cached version, and builds should start working again.

I will add a revised exclusion file in #4167 some time later (as that is not a "live" change anyway, currently)

Also, introducing changes via PRs (as per our policy) would be appreciated, as we could have avoided breaking the CI for all current builds that way. Thanks.

**Comment by arturoc** [comment]
yes that seems to be the problem i'll recreate the package tomorrow and upload it to our server again. that should solve it.

thanks!

**Comment by arturoc** [comment]
just recreated the packages using the new PG if anyone can check that they are working properly now?

**Comment by arturoc** [comment]
sorry, wrong issue :)

**Comment by arturoc** [comment]
i changed the package in the server and cleaned the cache and it's working again. thanks!
