### ISSUE TITLE
ofImage load crashes again with certain sizes in 0.9.0

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4216]
Hi,

the ofImage load function crashes with certain images resolutions. I tried various sizes, most work with out problems but some produce a bad access.

I've seen it already happened in 0.7 (https://github.com/openframeworks/openFrameworks/issues/1066) with the same symptoms, but now it points to ```__x = _VSTD::move(__y);``` in 'swap()'.

```
swap(_Tp& __x, _Tp& __y) _NOEXCEPT_(is_nothrow_move_constructible<_Tp>::value &&
                                    is_nothrow_move_assignable<_Tp>::value)
{
    _Tp __t(_VSTD::move(__x));
    __x = _VSTD::move(__y);
    __y = _VSTD::move(__t);
}
```

test sizes:

4334x2889 -> bad access
4334x2890 -> works
4333x2889 -> bad access
4334x2888 -> works
4333x2888 -> works

Any ideas?

**Comment by arturoc** [comment]
any specific format?

**Comment by kimasendorf** [comment]
I just tested jpegs. Here are my files: http://kimasendorf.com/_of/test-images.zip

**Comment by arturoc** [comment]
thanks, this fixes it for me but let me know if it's still a problem.

**Comment by kimasendorf** [comment]
fixes it for me too! thx =)

**Comment by radeise** [comment]
Hi,

I have the same problem in 0.9.2 with huge images files (7200x35700 px).
It was working fine with 0.8.4.

Something happen around 16 776 000 px (7200*2330 or 3533*4748 for example).
I used png and tif format with the same problems.

Any ideas ?

**Comment by arturoc** [comment]
can you post an image that crashes for you?

**Comment by radeise** [comment]
For example this one crash : http://proteiforme.fr/OF/chat.zip

```
swap(_Tp& __x, _Tp& __y) _NOEXCEPT_(is_nothrow_move_constructible<_Tp>::value &&
                                    is_nothrow_move_assignable<_Tp>::value)
{
    _Tp __t(_VSTD::move(__x));
    __x = _VSTD::move(__y);
    __y = _VSTD::move(__t);
}
```

:rooster:
