### ISSUE TITLE
Update RPI Makefiles to newer compiler requirement for cross compiling

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4219]
Just adding this as a note -- not necessarily required for 0.9.0.

These sections should be updated:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv7l/config.linuxarmv7l.rpi2.mk#L194-L238

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L193-L238

**Comment by arturoc** [comment]
closing this since @jvcleave added this but feel free to reopen if it's still not completely fixed.
