### ISSUE TITLE
Update ofArduino to newest Firmata Version 2.4.4

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4221]
I have been keeping up with the Firmata revisions and there are some features that I have adapted over time like Stepper Motor, Encoder, I2C, and almost all of the OneWire protocol. https://github.com/brinnLabs/Robust-Firmata/tree/master/openframeworks%20Libraries 

The current code is outdated and wrong in terms of its capabilities. I am opening this issue because some of the feature set are not part of standard firmata. @soundanalogous who maintains firmata, has examples in the configurable branch that allow for the features above but that I am worried including the capabilities in the core library might cause confusion when they load up standard firmata and a certain feature doesn't work.

Would it be better to just update the core library to the standard firmata capability and create a core addon for the features available from configurable/advanced/robust firmata or just keep it all in one place?

**Comment by soundanalogous** [comment]
You could update ofArduino in such a way that you can infer based on the Firmata configuration query which features are supported. Then throw an error if a user attempts to use an unsupported feature (the error should ideally point the user to the more full featured version of Firmata).

**Comment by DomAmato** [comment]
The configuration query would infer version number on standard firmata right, I actually haven't tried configurable firmata but does it include the modules or would it be something like 

    if version # < 2.5 "assume standardFirmata" 
    if version # >= 2.7 "assume configurable Firmata"

or should it attempt a sysex and if it returns as an error assume the feature isn't supported. Then just reset and configure based on known capabilities

**Comment by soundanalogous** [comment]
configurable firmata is now a separate project so the version numbers could overlap at some point. What you want to do is look at the pin types returned by the configuration query. There is a unique pin type for each feature. Some examples from ConfigurableFirmata:

https://github.com/firmata/ConfigurableFirmata/blob/master/src/OneWireFirmata.cpp#L26-L32
https://github.com/firmata/ConfigurableFirmata/blob/master/src/StepperFirmata.cpp#L49-L55

Same thing in StandardFirmata:
https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L536-L563

**Comment by DomAmato** [comment]
also suggested changes for windows platforms in ofSerial: 

    devices.push_back(ofSerialDeviceInfo(string(portNamesFriendly[i]), string(portNamesShort[i]), i));

which if on windows we can do:

    ofSerial	serial;
	vector <ofSerialDeviceInfo> deviceList = serial.getDeviceList();
	for (int i = 0; i < deviceList.size(); i++) {
		if (strstr(deviceList.at(i).getDevicePath().c_str(), "Serial") != NULL || strstr(deviceList.at(i).getDevicePath().c_str(), "Arduino") != NULL) {
			arduinoAttached = ard.connect(deviceList.at(i).getDeviceName(), 57600); //teensy's friendly name is USB Serial max speed = 125000
		}
	}
