### ISSUE TITLE
Make default linuxarmv7l makefile configuration work for Raspberry Pi / Raspberry Pi 2

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4224]
Currently in order to deal with all of the strange configuration issues associated with arm linux distros, we have a variable called `PLATFORM_VARIANT` in our makefiles that allows us to choose which configuration file to use.  For example, on linuxarmv7l, we have three configurations:

https://github.com/openframeworks/openFrameworks/tree/master/libs/openFrameworksCompiled/project/linuxarmv7l

I can't recall what target hardware / distro the default.  Thus in order to compile for Raspberry Pi 2 (which is linuxarmv7l) we need to call the makefile with:

`make PLATFORM_VARIANT=rpi2` etc.

To compile for udoo, we use

`make PLATFORM_VARIANT=udoo` etc.

For reference, the only known linuxarmv6l platform we've supported is raspberry pi 1, so we don't need to specify the PLATFORM_VARIANT, as rpi is our default.

https://github.com/openframeworks/openFrameworks/tree/master/libs/openFrameworksCompiled/project/linuxarmv6l

Anyway, the goal with this suggestion is to make it super easy to use the raspberry pi 2 because it is so popular.

P.S. In an ideal world we'd be able to detect exactly what hardware / distro is being used and pick the right distro ... but that's a very tricky business.

P.P.S I'd also like to update the documentation to clarify how this PLATFORM_VARIANT thing works for people working with platforms that we haven't tested.

**Comment by jvcleave** [comment]
Couldn't we stuff it into the user's directory as ~/.PLATFORM_VARIANT during install dependencies?

I think we do something similar with .OF_ROOT with the Project Generator
