### ISSUE TITLE
ofFbo not rendering on iOS

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4227]
here is a simple test,

```
void ofApp::setup(){	
    fbo.allocate(ofGetWidth(), ofGetHeight(), GL_RGBA);
}

void ofApp::draw(){
    fbo.begin();
    ofClear(ofColor::red);
    fbo.end();
    fbo.draw(0, 0);
}

```

on some older projects this was drawing a red fbo,
on the latest master its not rendering anything.

whats strange is that ive been testing this with one of my apps which records a fbo into a video, 
and that works fine.
but when i try to draw that fbo to screen, nothing happens.
perhaps a bug within the draw function somewhere?

**Comment by julapy** [comment]
can any android users check if they are having issues with fbo rendering?
potentially this could be a ES1 / ES2 issue...

**Comment by julapy** [comment]
can also confirm that the above FBO code doesn't work in emscripten, 
which is using ES2... so likely a core ES issue with FBOs

**Comment by pkmital** [comment]
This helped me get FBOs working again on iOS: https://github.com/openframeworks/openFrameworks/issues/4199

**Comment by julapy** [comment]
closing this issue as duplicate of #4199
