### ISSUE TITLE
ofxKinect: no available devices found

### ISSUE THREAD

**Issue by braitsch** [openframeworks/openFrameworks#4231]
Hello,

I just tried running the latest ofxKinect example against the latest on master and it's not seeing my Kinect(model 1656). The camera works fine however with the latest [Protonect/libfreenect2](https://github.com/OpenKinect/libfreenect2).

Any ideas?

```
ofxKinect: no available devices found
[warning] ofxKinect: update(): device -1 isn't delivering data,
```

Cheers,
Stephen

<img width="1030" alt="ofxkinect" src="https://cloud.githubusercontent.com/assets/144289/9211411/e8894cfc-4036-11e5-9edc-b505611c700e.png">

**Comment by ofTheo** [comment]
ofxKinect doesn't currently support Kinect V2 and probably won't. 
Most likely we would include the ofxKinectV2 addon for V2 usage.

**Comment by braitsch** [comment]
Awesome, thanks Theo for the explanation. I just pulled down your v2 addon and it appears to be working well.

Cheers,
Stephen
