### ISSUE TITLE
mac os x: new project with ofxEmscripten fails to compile due to EGL/egl.h

### ISSUE THREAD

**Issue by plural** [openframeworks/openFrameworks#4233]
this is with 0.9.0RC1_osx_release on os x 10.10.4

Steps:
 - open project generator
 - select ofxEmscripten addon
 - generate new project
 - open project in Xcode & build
 - build fails with addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h:14:10: 'EGL/egl.h' file not found

**Comment by arturoc** [comment]
emscripten doesn't work like that, it's not supported on xcode or the project generator. we'll publish a setup guide soon but right now you can only compile for the web from a console. go to the directory where the project is located and type:

```
emmake make
```

that will build the project and give you more help on how to run it. Here's a write up that explains pretty well how to use it on mac: http://www.reginafloresmir.com/blog/2015/5/14/openframeworks-on-the-line

**Comment by julapy** [comment]
have been digging around the emscripten docs and found this about building emscripten in visual studio,
http://kripken.github.io/emscripten-site/docs/getting_started/getting_started_with_emscripten_and_vs2010.html#getting-started-emscripten-from-visual-studio

**Comment by plural** [comment]
thanks, Arturo.  Why is the xcode project generated if it can't be used?  I guess this is veering into feature request territory, but it would be nice to not generate project files that can't be used and to remind users in the project generator that things need to be a bit different for this project.  I'm happy to file that as a feature request instead of leaving it here if you would like me to.
