### ISSUE TITLE
emscripten can not compile ofxGui

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4234]
its tripping up on a Poco include inside ofxXml.

btw, should we add a emscripten label in our github issues @bilderbuchi?

**Comment by bilderbuchi** [comment]
@julapy why not. will it only always be emscripten or is some more general/more encompassing formulation better? (no idea what, though - webos?) See e.g. the existing linuxarm instead of e.g. raspberrypi.

**Comment by julapy** [comment]
@bilderbuchi yeah maybe emscripten for now since i think that is what people will be looking for when logging these issues... webos would work if we supported more then one of these JS cross compilers.

**Comment by bilderbuchi** [comment]
done :-)
