### ISSUE TITLE
Compilation of ProjectGenerator

### ISSUE THREAD

**Issue by mrzl** [openframeworks/openFrameworks#4235]
I hope this is sufficient:

deploy@marchi:~/Downloads/of_v0.9.0RC1_linux64_release$ cd scripts/linux/
deploy@marchi:~/Downloads/of_v0.9.0RC1_linux64_release/scripts/linux$ ls -l
total 56
drwxr-xr-x 2 deploy deploy 4096 Aug 12 00:19 archlinux
drwxr-xr-x 2 deploy deploy 4096 Aug 12 00:19 archlinux_armv6
-rwxr-xr-x 1 deploy deploy 1018 Aug 12 00:19 buildAllExamples.sh
-rwxr-xr-x 1 deploy deploy  509 Aug 12 00:19 buildAllRPIExamples.sh
-rwxr-xr-x 1 deploy deploy  875 Aug 12 00:19 cleanAllExamples.sh
drwxr-xr-x 3 deploy deploy 4096 Aug 12 00:19 codeblocks_wizard
-rwxr-xr-x 1 deploy deploy 1006 Aug 12 00:19 compileOF.sh
-rwxr-xr-x 1 deploy deploy  731 Aug 12 00:19 compilePG.sh
drwxr-xr-x 2 deploy deploy 4096 Aug 12 00:19 debian
drwxr-xr-x 2 deploy deploy 4096 Aug 12 00:19 fedora
-rwxr-xr-x 1 deploy deploy  102 Aug 12 00:19 removeFMOD.sh
drwxr-xr-x 6 deploy deploy 4096 Aug 12 00:19 template
-rwxr-xr-x 1 deploy deploy  907 Aug 12 00:19 testAllExamples.sh
drwxr-xr-x 2 deploy deploy 4096 Aug 12 00:19 ubuntu
deploy@marchi:~/Downloads/of_v0.9.0RC1_linux64_release/scripts/linux$ ./compilePG.sh 
./compilePG.sh: line 8: cd: ../../apps/projectGenerator/projectGeneratorSimple: No such file or directory
make: *** No rule to make target `Release'.  Stop.
there has been a problem compiling the projectGenerator
please report this problem in the forums

Cheers for the RC, I'll digg through it.

**Comment by underdoeg** [comment]
Looks like a packaging error. The ProjectGenerator is within ```apps/projectGenerator/projectGenerator``` instead of ```apps/projectGenerator```

**Comment by LeoColomb** [comment]
Should be fixed by #4268, not?
