### ISSUE TITLE
ofParameter needs ofParameter<uint64_t> type

### ISSUE THREAD

**Issue by obviousjim** [openframeworks/openFrameworks#4238]
working with ofParameter is problematic when you need high precision numbers. For example, storing milliseconds of very long sequences.

same argument could be made to include doubles as well as floats
@arturoc / @ofTheo  Is there something preventing this or a reason against it? I'd be happy to implement it.

**Comment by arturoc** [comment]
you can create an ofParameter of any type you want, do you mean ofxSlider?

**Comment by roymacdonald** [comment]
doesn't this k

**Comment by obviousjim** [comment]
righ --  i'm referencing the built in functions of ofParameterGroup getters, which connects to ofxSliders

**Comment by arturoc** [comment]
for ofParameterGroup you can always use `group.get<uint64_t>(name)` 

for sliders we'll need to add the corresponding type. i'll add the types in ofxGui later

**Comment by obviousjim** [comment]
OK that makes sense, closing for now!
