### ISSUE TITLE
0.9.0 RC1 Failing to compile on RPI1

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4242]
Haven't dug in much yet but here is what I am getting out of the box

```
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
Compiling /home/pi/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.cpp
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
cc1plus: error: bad value (native) for -march switch
cc1plus: error: bad value (native) for -mtune switch
cc1plus: error: unrecognized command line option ‘-std=c++11’
cc1plus: error: bad value (native) for -march switch
cc1plus: error: bad value (native) for -mtune switch
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

**Comment by jvcleave** [comment]
looks like g++ 4.8 is required but the install_dependencies script will fail to find it as it is searching for 

`g++4.8`

this works for manual install (regex needs dash)

`sudo apt-get install g++-4.8`

**Comment by arturoc** [comment]
can you fix the install_dependencies script and send a PR?

**Comment by jvcleave** [comment]
I just updated it - I thought it would generate a PR but it just applied it directly - let me know if that causes any issues.

I'm still trying to get it to compile

**Comment by jvcleave** [comment]
ok, a few things

I tried to compile it natively on the RPI overnight but it was still going today so I canceled it. I'm not sure if this would be the same situation on the latest RPI Image

I did get it to compile via my cross-compiler setup using [Virtual Box but had to upgrade that to Jessie](https://gist.github.com/jvcleave/8489b3ec5897eb1a26a2)

The [lines with -mtune=native](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk#L189) were problematic with everything I tried. I was able to finally cross-compile with

```
ifeq ($(CROSS_COMPILING),1)
    PLATFORM_OPTIMIZATION_CFLAGS_RELEASE = -O3
    PLATFORM_OPTIMIZATION_CFLAGS_DEBUG = -g3
else
    PLATFORM_OPTIMIZATION_CFLAGS_RELEASE = -O3 -march=native -mtune=native
    PLATFORM_OPTIMIZATION_CFLAGS_DEBUG = -g3 -march=native -mtune=native
endif
```

also I don't think the current RPI cross compiler tools support c++14 so I had to do this [here:](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk#L129)
```
ifeq ("$(GCC_MINOR_GTEQ_9)","1")
                ifeq ($(CROSS_COMPILING),1)
                    PLATFORM_CFLAGS = -Wall -std=c++11
                else
                    PLATFORM_CFLAGS = -Wall -std=c++14
                endif
            else
                PLATFORM_CFLAGS = -Wall -std=c++11
            endif
```

**Comment by jvcleave** [comment]
some updates

Major issues:
g++-4.8 is not available on Debian Wheezy
The Disk Images distributed by the RPi Foundation are still Wheezy

I tried upgrading my existing SD card to Wheezy via `apt-get dist-upgrade`. It took over a day and didn't work in the end

I used [this project] (https://github.com/debian-pi/raspbian-ua-netinst) and modified it slightly to use Jessie. Jessie is nice in that you get g++-4.9 and RC 0.9 pretty much compiles out of the box

However [there is a bug] (https://bugs.launchpad.net/raspbian/+bug/1445648?comments=all) in the Jessie gstreamer repo that stopped gstreamer1.0-omx from installing. I did find a workaround by using 

`$ wget http://mirrordirector.raspbian.org/raspbian/pool/rpi/g/gst-omx1.0/gstreamer1.0-omx_1.0.0.1-0+rpi12+jessiepmg_armhf.deb`
 
`$ dpkg -i gstreamer1.0-omx_1.0.0.1-0+rpi12+jessiepmg_armhf.deb`

by using the net installer you are starting out as root which is different than the usual "pi" user workflow - this could cause some confusion

The RPi Cross compiler tools are only up to g++ 4.8.3 (where Jessie can use 4.9)

I'm not sure what to recommend - I see these as the options

1. Release OF 0.9.0 without arm6 support, keep 0.84 as the recommended version until the RPi Foundation adopts Jessie

2. Fork the https://github.com/debian-pi/raspbian-ua-netinst project and build around a process that builds a disk image for OF

Disclaimer:
I haven't tried just using the latest RPi Wheezy disk - I'm assuming OF's > g++ 4.7 requirement is a show stopper

**Comment by bakercp** [comment]
@jvcleave for all of my testing, I was able to get 4.8 using the latest raspbian.  Runs fine for me with a RPI2.  Have you tried it w/ the latest raspbian image?

**Comment by jvcleave** [comment]
@bakercp You are using OF's Arm7 version though right?

**Comment by arturoc** [comment]
check the latest posts in: http://forum.openframeworks.cc/t/0-9-0-release-candidate-1/20434/22  it seems there's an external repo for 4.8 not sure why other people have reported it being available in the default repositories.

we can add something to add that repo in wheezy in the install_dependencies script

**Comment by bakercp** [comment]
Yes - so I just burned a brand new raspbian image, and ran 

`sudo apt-get install gcc-4.8 g++-4.8`

and it installed.

I used 2015-05-05-raspbian-wheezy.img

I have tested this on a raspberry pi 1 (model A) and raspberry pi 2.

I'm going to run it through a full compile, but I'm pretty sure it will work just like the raspberry pi 2.

**Comment by arturoc** [comment]
do you need to specify CXX=gcc-4.8 when calling make?

**Comment by bakercp** [comment]
yes you have to specify CXX=g++-4.8 when calling make.

**Comment by bakercp** [comment]
or, you can make a symlink to make g++4.8 default.

**Comment by jvcleave** [comment]
@bakercp can you post the contents of the sources.list on your new Raspbian image?

**Comment by bakercp** [comment]
yeah

```
pi@raspberrypi ~ $ cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ wheezy main contrib non-free rpi
```

**Comment by arturoc** [comment]
there's a standard way to do this in debian rather than creating a symlink manually:

```
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100
```

where 100 is the priority, higher more priority.

we could add this after the detection for wheezy once we figure out why some distros don't seem to have it in their repos

**Comment by bakercp** [comment]
@arturoc nice!

**Comment by arturoc** [comment]
btw, perhaps we can remove the specific debian_armv6 folder in scripts and just use the normal debian one? i think they are pretty much the same now and if there's something specific like gstreamer omx we can just detect the platform and install it otherwise arm7 is not getting those packages right now and it makes it easier to maintain

**Comment by bakercp** [comment]
@arturoc yes -- I'd definitely vote for getting rid of duplicated folders.

**Comment by arturoc** [comment]
do any of you want to take care of this?

**Comment by bakercp** [comment]
I'm about to run through the whole armv6 process, so I can update it if @jvcleave doesn't get to it first.

**Comment by jvcleave** [comment]
I won't be getting into it today

Any thoughts on having libopenFrameworks.a available pre-compiled as part of the release packaging?

**Comment by bakercp** [comment]
I wouldn't be opposed to including libopenFrameworks.a for linuxarm*.  Just a little bookkeeping to recompile it and include it w/ the distros.  If we can automate it that would be awesome.  If we can't, I'd say we stick with how we have it now.

**Comment by arturoc** [comment]
if people for example want to use it with arch linux or in boards other than the rpi they'll have problems compiling that could be difficult to figure out

**Comment by bakercp** [comment]
@arturoc yeah -- I'm with you on that.  The main annoyance / reason for including it is that it takes so long to compile on RPI1.  But the RPI1 is no longer being manufactured and the RPI2 is super fast compiling the lib natively, so I'd tend to say that we should let each user compile the core like they are required to on all other platforms.

**Comment by arturoc** [comment]
also i'd rather put time in making a package to make cross-compiling easy

**Comment by jvcleave** [comment]
@bakercp You sure about the RPI1 not being manufactured anymore? There is also the A+ which is fairly new. I haven't tried the Compute module but it's also armv6

The proper way would probably be to get it into the Debian repo but that is probably an epic undertaking

**Comment by bakercp** [comment]
@jvcleave -- I'm not sure actually.  For some reason I thought I read that somewhere -- but it does appear they are still offering RPI1 A+ and B+.

**Comment by bakercp** [comment]
OK.  So I finally made it through the whole process with the RPI1.  It's just like the process with RPI2, except you don't have to specify a `PLATFORM_VARIANT=rpi2` and you don't have to wait all day.

My steps:

1.  Install the latest raspbian image.
2.  Run the plain debian (non armv6l) install_dependencies.sh.
3.  Enter a project / example folder.  Copy the normal Makefile to that location.
4.  `make CXX=g++-4.8`
5.  Wait for a really long time.
6. `make CXX=g++-4.8 run` (and leave the CXX out if you want).

So, I think we can get rid of the armv6l-specific install_dependencies scripts.

**Comment by bakercp** [comment]
Cleanup PR here #4271

**Comment by bakercp** [comment]
I think the last thing we need to do is address is these to bring them all up to speed.

https://github.com/openframeworks/openFrameworks/issues/4224
https://github.com/openframeworks/openFrameworks/issues/4219

Additionally, do we need `buildAllRPIExamples.sh`?

Also, would it be possible to combine archlinux_armv6 and archlinux scripts?

**Comment by jvcleave** [comment]
I still use buildAllRPIExamples.sh but may be the only one

I'm going to go ahead and close this issue
