### ISSUE TITLE
0.9.0 RC1 Project Generator - unrecognized selector sent to instance 0x7fe8168b4490

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#4243]
I've tried to generate a new project with some addons, and XCODE gives me an error while trying to open the new project

```
Project /Users/dd/src/of_v0.9.0RC1_osx_release/apps/myApps/TheYear009/TheYear009.xcodeproj cannot be opened: -[PBXBuildFile group]: unrecognized selector sent to instance 0x7fe8168b4490
```

![screen shot 2015-08-13 at 6 25 57 pm](https://cloud.githubusercontent.com/assets/58289/9262098/c44a2326-41e8-11e5-812a-fee7254c9564.png)

Thanks

**Comment by ofZach** [comment]
quick note, this is fixed with this PR which hasn't been merged yet but should be! 

https://github.com/openframeworks/openFrameworks/pull/4170

**Comment by dimitre** [comment]
ok thanks @ofZach

**Comment by ofZach** [comment]
(ps: just to double check, what are the addons you are adding?  I'm assuming one of them has a framework involved?)

**Comment by dimitre** [comment]
@ofZach I've noticed Syphon is causing this but I can check if any other

**Comment by ofZach** [comment]
yep!  that has a framework, this PR (listed above) will fix this for sure.
