### ISSUE TITLE
example/gl/textureBufferInstancedExample doens't work on Intel Graphic card

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4252]
I just see fps count on the top left corner
after switching to my nvidia geforce 525M (optimus system) it works

all of this under ubuntu 15.04 64bit with 704cfef

**Comment by arturoc** [comment]
i think this is a problem with the intel driver i've never managed to make it work in intel cards either

**Comment by bilderbuchi** [comment]
I'll close this as won't-fix. Agreed, @arturoc ?
