### ISSUE TITLE
ofEasyCam::disableMouseEvents segfaults

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#4283]
http://forum.openframeworks.cc/t/ofeasycam-disablemouseinput-has-error-on-of0-9rc/20512

**Comment by ofTheo** [comment]
@arturoc  can you reproduce this? 
I tried with latest master - but I don't get the error ( OS X )

**Comment by arturoc** [comment]
no i haven't tried it, i'll try to run the example with valgrind in case there's some weird memory access we are missing

**Comment by arturoc** [comment]
this is actually fixed already, there was a problem when removing listeners from the same event they were registered to but it's solved now
