### ISSUE TITLE
you have held broken packages

### ISSUE THREAD

**Issue by garpert** [openframeworks/openFrameworks#4285]
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopencv-dev : Depends: libopencv-objdetect-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-highgui-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-legacy-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-contrib-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-videostab-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-superres-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libopencv-ocl-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libcv-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libhighgui-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
                 Depends: libcvaux-dev (= 2.4.9+dfsg-1ubuntu4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

**Comment by bilderbuchi** [comment]
ping @arturoc you referenced this in some commits, what's the status of this issue?

**Comment by arturoc** [comment]
i think that was a mistake, probably refering to an issue in the PG but not sure, i find it also really strange that it's refering to julapy's repo.

in any case this is a bug in the repo not in OF probably from some extra ppa installed in the system but not sure

**Comment by bilderbuchi** [comment]
@garpert do you still get this issue? have you tried an apt-get update and apt-get upgrade to see if that fixes it?

**Comment by garpert** [comment]
Just A  belated followup:..I tried to Install Openframeworks on a fresh install of https://ubuntustudio.org/2015/08/your-chance-to-help-beta-testing/ after various updates to ubuntustudio I am  able get beyond this point but having trouble getting example to build, When I can articulate it as a coherent question I'll submit it as issue if needed thank sorry for any inconvenience

**Comment by bilderbuchi** [comment]
thank you for the follow up. for usage questions and assistance it's better to go to the [forum](http://forum.openframeworks.cc/), instead.
