### ISSUE TITLE
ios issues with 0.9.0 examples

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4290]
ive gone through a fixed up the smaller issues for all the ios examples.
below are remaining issues which are a little bit more involved,
including outstanding TODO items that will need to be fixed for 0.9.0 release.

* iosCustomSizeExample is buggy.
* iosExternalDisplayExample needs to be tested properly with an external display.
* ~~iosNativeExample reveals a bug with frame number not resetting~~ FIXED
* iosOrientationExample is broken.
* opencvExample needs AssetsLibrary.framework added for example to compile
* opencvFaceExample needs AssetsLibrary.framework added for example to compile
* oscReceiverExample runs but needs testing with OSC data
* oscSenderExample runs but needs testing with OSC data
* videoGrabberExample probably need some kind of message that it doesn’t run on the simulator.

**Comment by julapy** [comment]
@ofZach,
the `opencvExample` and `opencvFaceExample` examples require `AssetsLibrary.framework` to be added by the PG to the xcode project.
i seem to remember this being fixed for osx...
can you comment on how/if this works the same for ios.
cheers.

**Comment by arturoc** [comment]
@julapy if you add:

```make
ios:
    ADDON_FRAMEWORKS = AssetsLibrary
```

not sure now if you need to add the .framework

to addon_config.mk in the ofxOpenCv addon it should do the right thing, can you give it a try? i think there's a specific hack for this or something else related to the opencv addon in the PG code, but better to solve it through the config file.

**Comment by ofZach** [comment]
@julapy I'll take a look, frameworks (system level) should work via the method arturo is describing now with the latest PG (I tested it against a different addon, I think ofxMidi, but I'll check this with opencv shortly)

**Comment by arturoc** [comment]
> iosNativeExample reveals a bug with frame number not resetting.

in 0.9 the frame number is not hold by the window any more but by the main loop so recreating the window won't reset it. you can do the initialization more explicit by using a main loop like:

```
ofGLESSettings settings;
auto window = std::make_shared<ofAppiOSWindow>();
window->setup(settings);
auto mainloop = std::make_shared<ofMainLoop>();
auto app = std::make_shared<ofApp>();
mainloop->run(window, app);
ofSetMainLoop(mainloop);
ofRunMainLoop();
```

**Comment by julapy** [comment]
thanks @arturoc, ill look into implementing ofxiOS in this way.

**Comment by julapy** [comment]
hey @arturoc,
im having

**Comment by julapy** [comment]
hey @arturoc,
still trying to work out the most elegant solution for integrating the new ofMainLoop additions into ofxiOS.
think i might have decent solutions, but first i was wondering if its possible to swap the order of these two lines?
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofMainLoop.cpp#L63-L64

reason being, im using the `setup()` method in the window to reset the window state...

**Comment by julapy** [comment]
hey @arturoc, this seems to be the best solution ive been able to come up with so far >> PR ##4327
which includes the small change in `ofMainLoop` as mentioned above...

the challenge with ofxiOS is that ofAppiOSWindow is only created once, and it is reused when a new ofMainLoop is created. so to reset fps counters etc, the ofAppiOSWindow state needs to be reset, which im now doing when `ofAppiOSWindow::setup` is called.

does that make sense? or am im completely going about it the wrong way? :)

**Comment by arturoc** [comment]
i'd say it doesn't matter but relying on that seems really brittle. i'm doing it like that cause the main loop is the only global object now and although it's not correct to do any global call from the window setup it might be that someone tries to do it which would crash if there's no window yet.

i'm looking at the code but don't really get why you need it to happen in that specific order?

**Comment by julapy** [comment]
@arturoc
my issue is that im trying reuse the same ofAppiOSWindow between different ofMainLoops.
the correct way would be to destroy the ofAppiOSWindow and create a new one every time a new ofMainLoop is created.

the issue with this is that ofAppiOSWindow holds some global state settings like,
- a flag if to use retina scale
- a flag if to use anti-aliasing 
- etc.
these are settings you most likely only want to set once in main.mm when creating the ofAppiOSWindow for the very first time.

the issue is that these are global settings but they sit inside ofAppiOSWindow and when the window is destroyed, those settings are lost... 

anyway, i think the solution is that ofxiOS needs to create some global functions for storing these settings which can then be accesses via ofAppiOSWindow, so they never get reset and when a new ofAppiOSWindow is created, it can launch with these global settings.

will get a PR together for this approach to review.

**Comment by arturoc** [comment]
i see, perhaps you don't need to change things that much, if all you need is a way to reset the frame counter we can just add a call to ofMainLoop in order to do that instead of having to recreate it...

**Comment by julapy** [comment]
i guess it makes sense to destroy and re-create the window every time a new ofxiOS session is started.
i'll try this first and let you know if i get stuck.

**Comment by arturoc** [comment]
ok, great

**Comment by arturoc** [comment]
btw, i'm  checking now and the frame count isn't really in the main loop but in the core events which are contained in the window, if you reset the events (just reassign them to a new instance) you should be good to go but also restoring the whole window should work.

**Comment by julapy** [comment]
hey @arturoc, here is a new PR #4332 which creates a new ofMainLoop and window on every new ofxiOS session. can you please have a look and see if ive missed anything?

**Comment by kylemcdonald** [comment]
now that #4332 is merged, can this be closed?

**Comment by julapy** [comment]
@kylemcdonald, ill do some more testing today and report back.

**Comment by robert-wallis** [comment]
AssetsLibrary.framework still isn't added to to the project files.  And needs to be added manually for the openCV examples.  I tried adding it to ADDON_FRAMEWORKS as suggested and re-running projectGenerator but it still isn't automatically added.  BTW it produces these errors (for SEO) when compiling without first manually adding AssetsLibrary.framework

```
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in opencv_highgui.a(cap_ios_video_camera.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ofZach** [comment]
does this need to be added to all ios examples or just opencv ones?

I can take a look at adding it via ADDON_FRAMEWORKS and what's happening there, but if it needs to be in every ios project, we can also add it via the template.  (one thing to be careful about if you alter the template is to convert the pbxpoj back to xml via plutil http://hints.macworld.com/article.php?story=20050430105126392)

**Comment by danoli3** [comment]
Only required for OpenCV other external dependencies that require it.

**Comment by danoli3** [comment]
* ~~ iosCustomSizeExample is buggy. ~~ Works okay, just needs some work later for iOS 9.0
*  ~~iosExternalDisplayExample needs to be tested properly with an external display. ~~ Tested OKAY
* ~~iosNativeExample reveals a bug with frame number not resetting~~ FIXED
* ~~ iosOrientationExample is broken. ~~ FIXED
* opencvExample needs AssetsLibrary.framework added for example to compile - TESTED
* opencvFaceExample needs AssetsLibrary.framework added for example to compile - TESTED
*  ~~oscReceiverExample runs but needs testing with OSC data ~~ TESTED
*  ~~oscSenderExample runs but needs testing with OSC data ~~ TESTED
*  ~~videoGrabberExample probably need some kind of message that it doesn’t run on the simulator. ~~ iOS Core has this warning.

**Comment by danoli3** [comment]
Only thing remaining is the Asset Framework for the project generator.

**Comment by danoli3** [comment]
@openframeworks/ios I think this is a wrap though.
Maybe a new issue for enhancement for the opencv example fixes. 
I've currently added it to the projectGenerator issues.

**Comment by ofZach** [comment]
I don't think this is a change to project generator but rather a change to ofxOpenCv (by adding a addon_config.mk to add the framework).

**Comment by bilderbuchi** [comment]
@danoli3 thanks for checking all these examples!

**Comment by arturoc** [comment]
closing this since everything seems to be fixed now
