### ISSUE TITLE
Don't require ofParameter data to be serializable?

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4297]
`ofParameter` is super powerful and useful.  It would be nice to be able to use it with lots of other data types and even collections, vectors, tuples, etc.

The main roadblock right now is that the templated parameters must be serializable via ofToString / ofFromString. (called in ofParameter::toString/fromString).

So, there could be a few solutions -- 1. go down the serialization library road and implement more ofToString/ofFromString specializations 2. using templates, disable the to/FromString methods if the templated type is not serializable, 3. refactor serialization out of ofParameter and use a different patter e.g. the visitor pattern or something for serialization. 

Anyway, definitely needs a discussion before anyone starts hacking on it.

**Comment by bakercp** [comment]
Just thinking through this a little more -- and with all of the operators, etc it seems that ofParameter won't work well with non-POD and a few others (ofVec*f, etc) -- as it's not really designed to do that.  So that said, the main desire here is to get the very useful event system for other data types, collections, etc.  Perhaps there is another better way wrap arbitrary data variables to get events on change?

**Comment by arturoc** [comment]
i think there's 2 different problems here, ofParameter should allow any type no matter if they are serializable or not, the it would define some methods or others for serializable or non serializable types. this can be done with some templating and i thought it was currently working like that.

then there's the problem of serializing certain complex types which could make sense. there's already open issues for both problems but just to make it clear

**Comment by arturoc** [comment]
btw, ofParameter works well with ofVec* as it's used by ofxVectorSlider or ofxColorSlider, have you found any problem with those?

**Comment by bakercp** [comment]
Hey, nice fix I'll try it out!
