### ISSUE TITLE
ofTrueTypeFont rendering problem

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4300]
![screenshot_8_25_15__11_53_am](https://cloud.githubusercontent.com/assets/300484/9473382/12b8f5d8-4b20-11e5-9c48-b12f791bcc55.png)
![screenshot_8_25_15__11_53_am](https://cloud.githubusercontent.com/assets/300484/9473395/20316bd2-4b20-11e5-9587-d0236ffe1d6f.png)

For some reason, little pixels are not correctly anti-aliased on the lower left hand corner.  I haven't investigated, but it seems like a texture coordinate / mesh problem?

Just running the standard font example on OSX 10.10 on master.

**Comment by arturoc** [comment]
mmh, yeah that's really strange. i'm seeing the same in linux so i guess it's not related to freetype. i'll take a look too later but it's probably related to the tex coordinates. can you test if it happens in 0.8.4 too?

**Comment by kylemcdonald** [comment]
also seeing this, `OF_TTF_SANS` on osx has similar behavior on the h and i but instead of being completely black it's gray.
