### ISSUE TITLE
Makefile no longer respects addon_config.mk ADDON_DEPENDENCIES, etc.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4305]
@arturoc after c6d6430d1d4f9836eeae9e4bab299ce6c76a3992 ADDON_DEPENDENCIES are no longer included.

**Comment by bakercp** [comment]
Also confirming that this is broken on both OSX and Linux.  I haven't had a chance to dig into the Makefile updates yet, but bisect points to the changes here c6d6430.

**Comment by bilderbuchi** [comment]
funny that CI wouldn't catch this (as both linux and macos compile the allAddonsExample) - which PR was this part of @arturoc ?

**Comment by arturoc** [comment]
i think none of the official addons have dependencies so it won't get catched by compiling the allAddonsExample.

i'll take a look later

**Comment by bilderbuchi** [comment]
The issue title includes addon_config.mk, too, and at least ofxOpenCv has that...

**Comment by arturoc** [comment]
yeah but no addon dependencies
