### ISSUE TITLE
ofGetSoundStream()

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#4308]
I just made an addon out of the ofSoundObject developed at the YCAM ofDevCon.
It has been a while since we las updated that working branch. I think that having it as an addon will make other people aware of the ofSoundObjects, possibly contribute to it, and eventually get it merged to the master.
The only thing I need for it to work as an addon is to have the ofGetSoundStream() function.
Check it [here](https://github.com/roymacdonald/openframeworks/tree/feature-ofGetSoundStream).
Shall I PR?
Best

**Comment by arturoc** [comment]
perhaps send a PR so we can see the diff easier

**Comment by roymacdonald** [comment]
Sorry, I thought that I did so.
https://github.com/openframeworks/openFrameworks/pull/4309

**Comment by bilderbuchi** [comment]
@roymacdonald you just closed that PR, does that mean we can close this issue, too?

**Comment by roymacdonald** [comment]
@bilderbuchi Sure! I was about to make so.
