### ISSUE TITLE
ofVideoPlayer DirectShowVideo not fully working

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/openFrameworks#4310]
seems the ofVideoPlayer not fully working,i did testing with latest master and vs2015.
both 32&64,under the win10 and win7 64bit os.
in my case it'll break at the line of 595
VIDEOINFOHEADER * infoheader = (VIDEOINFOHEADER*)mt.pbFormat;
width = infoheader->bmiHeader.biWidth;
can't the video width&height
it would be great if someone can test it out
cheers
@ofTheo

**Comment by DomAmato** [comment]
you mean that infoheader->bmiHeader.biWidth; is returning a null value? sorry I am just not sure what error you are running into for testing purposes

**Comment by liquidzym** [comment]
yes,it returning a NULL value,does ofVideoPlayer works for you?

**Comment by DomAmato** [comment]
Nope it is also broken for me and is also returning null values. this line is not right at 587 as it is not setting the HResult so it doesn't signal that a failure occurred 

    m_pGrabber->GetConnectedMediaType(&mt);

it should be:

    hr = m_pGrabber->GetConnectedMediaType(&mt);

**Comment by DomAmato** [comment]
Seems to be a codec issue. Converting the video to a wmv plays with no problems.

**Comment by ofTheo** [comment]
The direct show player needs codecs to play mov files.  ie: k-lite codec Not sure if we should include a note in the download?

**Comment by DomAmato** [comment]
Plays most other formats except mp4. Media foundation doesnt seem to have this problem but it cant rewind well or at all really

**Comment by liquidzym** [comment]
ok,i can confirmed that's codec issue,i did installed the k-lite codec full version b4 which is 1120,seems this version only can play with wmv format
i upgraded it to 1140 mega version,now its working fine. play most of the format,also including .mp4
tested on win 10,btw.

**Comment by yty** [comment]
@liquidzym 
@ofTheo 
@DomAmato 

I also have this problem.
For example, 683 * 384 resolution video,
Unable to get information from VIDEOINFOHEADER.

**Comment by ofTheo** [comment]
Hey! 

Whats the video format?
On OS X I can have issues with Quicktime Files which don’t have a width divisible by 4. 

Do you have the codecs installed?

----------------------------------------------
Theo Watson
http://theowatson.com 
http://openframeworks.cc
----------------------------------------------

**Comment by Geistyp** [comment]
I cant play any video. Win10 vs2015. I have already installed k-lite codec 1140 mega.

ofVideoGrabber works.
ofVideoPlayer can load movie success, no error, width and height are correct. But DirectShowVideo::SampleCB not run.

Any ideas?

**Comment by Geistyp** [comment]
@DomAmato 

1 more missing hr check

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L500
```c++
m_pGrabber->SetCallback(this, 0);
if (FAILED(hr)){
    tearDown(); 
    return false;
}
```

**Comment by yty** [comment]
@ofTheo 

Video: FMP4 680x384 24fps [Video]
Audio: MP3 44100Hz stereo 64kbps [Audio]

I use ffmpeg recorded video.
I uploaded the gist.

https://gist.github.com/yty/1ccc564776ee1f150c0f/raw/ee744947f81c02f6b390b5ccedb57908a2a5bdf2/test.avi

General
Complete name                  : E:\GitFiles\1ccc564776ee1f150c0f\test.avi
Format                         : AVI
Format/Info                    : Audio Video Interleave
File size                      : 10.0 MiB
Duration                       : 4s 23ms
Overall bit rate               : 20.9 Mbps
Writing application            : Lavf55.10.100

Video
ID                             : 0
Format                         : MPEG-4 Visual
Format profile                 : Advanced Simple@L1
Format settings, BVOP          : Yes
Format settings, QPel          : No
Format settings, GMC           : No warppoints
Format settings, Matrix        : Default (H.263)
Codec ID                       : FMP4
Duration                       : 2s 0ms
Bit rate                       : 41.8 Mbps
Width                          : 680 pixels
Height                         : 384 pixels
Display aspect ratio           : 16:9
Frame rate                     : 24.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 6.672
Stream size                    : 9.97 MiB (99%)
Writing library                : Lavc55.17.100

Audio
ID                             : 1
Format                         : MPEG Audio
Format version                 : Version 1
Format profile                 : Layer 3
Mode                           : Joint stereo
Codec ID                       : 55
Codec ID/Hint                  : MP3
Duration                       : 4s 23ms
Bit rate mode                  : Constant
Bit rate                       : 64.0 Kbps
Channel count                  : 2 channels
Sampling rate                  : 44.1 KHz
Compression mode               : Lossy
Stream size                    : 31.0 KiB (0%)
Alignment                      : Aligned on interleaves
Interleave, duration           : 13 ms (0.31 video frame)
Interleave, preload duration   : 52 ms

**Comment by DomAmato** [comment]
I dont have any problem playing the file you linked

**Comment by yty** [comment]
@DomAmato 

sorry,I'm not using the latest version of OF.
The current version is no problem would be great.

**Comment by DomAmato** [comment]
I think this issue can be closed @bilderbuchi
