### ISSUE TITLE
'unordered_map' file not found

### ISSUE THREAD

**Issue by Miles-Tone** [openframeworks/openFrameworks#4311]
using OF9RC1 i get this error whilst trying to compile an iOS project in Xcode 6
the error message points to ofConstants.h

**Comment by bilderbuchi** [comment]
sounds like a problem with the project file/library include. Please also try with latest master, there were a couple of fixes recently.

**Comment by arturoc** [comment]
also is this with the examples that come with the download or with an old project? if it's an old project you might need to update it using the project generator

**Comment by Miles-Tone** [comment]
Ahh thanks Arturo, it was an old project so I did as you've said and it's now compiling
