### ISSUE TITLE
Xcode - iOS - clang failed with exit code 11 - Building for Archiving/Device

### ISSUE THREAD

**Issue by Miles-Tone** [openframeworks/openFrameworks#4314]
I get this error when trying to archive a project, it runs in the simulator, but not on a tethered Air 2
I can send the full message if thats useful, but i didn't want to clog things up if not needed

clang: warning: -lpthread: 'linker' input unused
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++-header -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++11 -stdlib=libc++ ETC......
..... ofxiOS_Prefix.pch.dia 
1.	Compilation construction
2.	Building compilation jobs
3.	Building compilation jobs
4.	Building compilation jobs
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 11

**Comment by bilderbuchi** [comment]
which macos/xcode/OF versions are you using?

**Comment by Miles-Tone** [comment]
thanks for the reply
OSX 10.10.4
Xcode 6.4
OF 0.9 RC1 & nightly builds

**Comment by bilderbuchi** [comment]
ping @openframeworks/macos @openframeworks/ios

**Comment by pizthewiz** [comment]
Hmm, the simulator destination builds for `i386`/`x86_64` and the device destination, used by _Archive_, `armv7`/`arm64`. Does this reproduce for you with an empty project?

**Comment by Miles-Tone** [comment]
riiiiiiiight, so it didn't work before when i tried an empty project, but it does now. Apologies for the false flag!
In the current project I use ofxPD and i have to add Other C-Flags, could this be something to do with it?

**Comment by pizthewiz** [comment]
No worries, it sounds as though it might be a configuration issue then. It might help if you could create a minimum project that reproduces the issue - maybe create a project with ofxPD and then copy over your cflags and then we could investigate from there.

**Comment by Miles-Tone** [comment]
ok, on a clean ofxPD example build without the C Flags i get the same issue

**Comment by Miles-Tone** [comment]
should i close this issue and bring it up with @danomatika on a separate ofxPD thread?

im looking forward to getting better and being able to contribute properly instead of taking up peoples time :-/ thanks for the input!

**Comment by pizthewiz** [comment]
Yeah, it sounds like it might be best to pursue with ofxPD, but feel free to create a Gist of the failing build output and we can give that a quick look too.

**Comment by Miles-Tone** [comment]
issue continued on ofxPD thread - https://github.com/danomatika/ofxPd/issues/45
