### ISSUE TITLE
ofMatrix4x4::decompose() decomposes scale incorrectly

### ISSUE THREAD

**Issue by procedural** [openframeworks/openFrameworks#4317]
I have a project that requires negative matrix scale by one of the axes, but the problem is `ofMatrix4x4::decompose()` returns incorrect scale values for other two axes if only one was negated.

Repro code:

```
void ofApp::setup()
{
  ofMatrix4x4 m;
  m.scale(ofVec3f(1,1,-1));
  cout << "Matrix (correct scale): \n" << m << endl;

  ofVec3f t;
  ofQuaternion r;
  ofVec3f s;
  ofQuaternion so;

  m.decompose(t, r, s, so);

  cout << "Decomposed scale (incorrect): \n" << s << endl;
}
```

Output:

```
Matrix (correct scale values): 
       1,        0,       -0,        0
       0,        1,       -0,        0
       0,        0,       -1,        0
       0,        0,       -0,        1
Decomposed scale (incorrect): 
-1, -1, -1
```

**Comment by procedural** [comment]
OF just multiplies every scale component by -1...

[Changed this part](https://github.com/openframeworks/openFrameworks/blob/6bdcd55/libs/openFrameworks/math/ofMatrix4x4.cpp#L1531-L1537) to print variables:

```cpp
    // mul be sign of determinant to support negative scales.

    cout << "parts.k.x(): " << parts.k.x() << endl;
    cout << "parts.k.y(): " << parts.k.y() << endl;
    cout << "parts.k.z(): " << parts.k.z() << endl;

    cout << "parts.f: " << parts.f << endl;

    mul *= parts.f;
    s.x= parts.k.x() * mul;
    s.y = parts.k.y() * mul;
    s.z = parts.k.z() * mul;

    cout << "parts.k.x() * mul: " << parts.k.x() * mul << endl;
    cout << "parts.k.y() * mul: " << parts.k.y() * mul << endl;
    cout << "parts.k.z() * mul: " << parts.k.z() * mul << endl;

    so.set(parts.u.x(), parts.u.y(), parts.u.z(), parts.u.w());
```

```
Matrix (correct scale): 
       1,        0,       -0,        0
       0,        1,       -0,        0
       0,        0,       -1,        0
       0,        0,       -0,        1
parts.k.x(): 1
parts.k.y(): 1
parts.k.z(): 1
parts.f: -1
parts.k.x() * mul: -1
parts.k.y() * mul: -1
parts.k.z() * mul: -1
Decomposed scale (incorrect): 
-1, -1, -1
```

I'll remind why this is incorrect: if you do operation directly on `matrix._mat` values, it gets correct scale  values from the matrix (1,1-1), but when you decompose it with this function it tells you that all three components were inverted which is not true. The problem is that OF internals use this function to return scale values in other functions, they all lie about the real scale of the matrix.

**Comment by procedural** [comment]
Damn...

http://answers.unity3d.com/questions/689997/need-help-supporting-negative-values-when-extracti.html

>According to this article, you can only determine if one of the three scale axis is negative by calculating the determinant of m00-m22(rotation matrix) and check its sign. Unfortunately you can not determine two, three axis or which axis is negative exactly, because in each case they're mathematically the same and may be hidden by rotation, like (-1,-1,1) scale is the same as rotation(0,0,180).

How 3D packages can scale by one axis then? I mean, classic mirroring in 3D modelling?

**Comment by procedural** [comment]
Closing this issue as unsolvable for now... Apparently at some point in history some stupid motherfucker thought that merging scale and rotation values in a matrix was a good idea. :fu:

**Comment by kylemcdonald** [comment]
got a good laugh out of your comment, but edited it bit to keep a good tone going here on github ;) ping me directly if it's an issue. also, did not know github had a middle finger emoji!

**Comment by procedural** [comment]
@kylemcdonald no, that's fine! I get little too emotional when someone does his job badly :)

**Comment by kylemcdonald** [comment]
that said, i bet @tgfrerer or @kpasko might have some insight here.

**Comment by procedural** [comment]
@kylemcdonald there's no way to retrieve scale signs back, it's an example of idiotic data loss. I do SRT transformations separately now, composing this 4x4 garbage at user's request.
