### ISSUE TITLE
ofImage crop() causes a crash

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4320]
Using it simply like that in the of_v20150830_osx_release (OS X 10.8):

```
ofImage img;
img.load("81Ke8C3Ie3L._SL1500_.jpg");
img.crop(10, 10, 30, 30);
```

> malloc: *** error for object 0x101056408: incorrect checksum for freed object - object was probably modified after being freed.

**Comment by arturoc** [comment]
thanks, i changed a couple of things yesterday and broke crop, i think it's fixed in master now
