### ISSUE TITLE
ofImage save creates broken jpegs

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4324]
save creates JPG files with 0kb. PNG is working fine.

**Comment by gorkacortazar** [comment]
I saw a similar thing last week while rendering an FBO in 0.8.4. In my case only happened in the source had an alpha channel while trying to save a jpg.

**Comment by kimasendorf** [comment]
ups, yes, i get the pixel data from an ofFbo. does it mean I have to change the image type before saving as jpeg?

**Comment by kimasendorf** [comment]
ok, when i set the image type to OF_IMAGE_COLOR it is working. sorry

**Comment by arturoc** [comment]
this should work anyway, it'll probably won't get fixed for 0.9 but let's keep it open. ofImage should convert to IMAGE_COLOR automatically when the image has alpha and you save to a format that doesn't support it

**Comment by frankiezafe** [comment]
could you point the place where it has to be done in the core?

**Comment by frankiezafe** [comment]
dirty hack (really dirty, but efficient)

[ofImage.cpp, line 350]
'''
if(fif == FIF_JPEG) {
    if ( pix.getBitsPerPixel() > 24 ) {
        delete bmp;
        bmp	= getBmp24FromPixels32(pix);
    }
'''

[ofImage.cpp, anywhere else]
'''
template<typename PixelType>
FIBITMAP* getBmp24FromPixels32(ofPixels_<PixelType> &pix){
    // sending alpha to jpg! this will be dirty if not fixed...
    ofPixels correctpix;
    correctpix.allocate( pix.getWidth(), pix.getHeight(), OF_PIXELS_RGB );
    for ( int y = 0; y < pix.getHeight(); ++y ) {
    for ( int x = 0; x < pix.getWidth(); ++x ) {
        ofColor c32 = pix.getColor( x,y );
        ofColor c24;
        c24.r = c32.b;
        c24.g = c32.g;
        c24.b = c32.r;
        correctpix.setColor( x, y, c24 );
    }
    }
    unsigned char * pixels = correctpix.getPixels();
    unsigned int width = correctpix.getWidth();
    unsigned int height = correctpix.getHeight();
    unsigned int bpp = correctpix.getBitsPerPixel();
    FREE_IMAGE_TYPE freeImageType = getFreeImageType(pix);
    FIBITMAP* bmp = FreeImage_AllocateT( freeImageType, width, height, bpp );
    unsigned char* bmpBits = FreeImage_GetBits(bmp);
    if(bmpBits != NULL) {
            int srcStride = width * correctpix.getBytesPerPixel();
            int dstStride = FreeImage_GetPitch(bmp);
            unsigned char* src = (unsigned char*) pixels;
            unsigned char* dst = bmpBits;
            for(int i = 0; i < (int)height; i++) {
                    memcpy(dst, src, srcStride);
                    src += srcStride;
                    dst += dstStride;
            }
    } else {
            ofLogError("ofImage") << "getBmpFromPixels(): unable to get FIBITMAP from ofPixels";
    }
    // ofPixels are top left, FIBITMAP is bottom left
    FreeImage_FlipVertical(bmp);
    return bmp;
}
'''

**Comment by nicoNz** [comment]
this simply works :)

```
fboVignet.readToPixels(px);
    ImgVignet.setFromPixels(px);
    ImgVignet.save("out1.png");
    ImgVignet.setImageType(OF_IMAGE_COLOR);
    ImgVignet.save("out1.jpg");
```

**Comment by dimitre** [comment]
I've tested this one now and it can be closed.
the only difference is JPEG files are more washed out, but I think it is a separate issue, color profiles (sRGB IEC61966-2.1)
