### ISSUE TITLE
ofApp::mouseDragged event gets fired during save dialog

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4325]
This is just happening on OS X 10.10, the bug does not occur on 10.8.

**Comment by kimasendorf** [comment]
It was the nightly build from yesterday (of_v20150831_osx_release).
No example. I had one image to drag around and then opened as save dialog. After closing the save dialog the image jumped to another position. I figured out that the drag event was called behind the save dialog and changed the image coordinates..

**Comment by bilderbuchi** [comment]
some short code to reproduce this would be awesome. :-)
ping @bakercp @arturoc

**Comment by kimasendorf** [comment]
I have a quite complex app and I am on 10.8 so it is not that easy. I'll be able to check it tomorrow on a colleague's computer. Today we weren't able to simply reproduce it, guess it could have something to do with ofThread.

**Comment by kimasendorf** [comment]
Hey, sorry, can't replicate the bug. Made some tests with ofThread, but all is working fine. Maybe it occurs because we use ofxUI..

**Comment by bilderbuchi** [comment]
thank you. closing this, then.
