### ISSUE TITLE
ofxAssimpModelLoader not cleaning up properly

### ISSUE THREAD

**Issue by prisonerjohn** [openframeworks/openFrameworks#4337]
When running the assimpExample, I noticed that it crashes whenever changing models (press keys 1-5).

It looks like ofxAssimpModelLoader is not clearing its resources properly in clean():
 * The `scene` shared pointer is not `reset()`, so calls like [this](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp#L48-L50) won't work.
 * I might be wrong here, but I don't think testing for `if (scene != NULL) { ... }` is valid since it's a shared pointer, I believe the [correct syntax](http://www.cplusplus.com/reference/memory/shared_ptr/operator%20bool/) is simply `if (scene) { ... }`.
 * Quickly glancing at the [assimp documentation](http://assimp.sourceforge.net/lib_html/cimport_8h.html#ab6085941982ef6158f3aa8be87470602), it looks like `aiPropertyStore` needs to be "manually destroyed using the [aiReleasePropertyStore](http://assimp.sourceforge.net/lib_html/cimport_8h.html#ac7e29d2f3bd4366bead505ed53f07108) API function", which is not happening.

I tried fixing these issues but I'm still getting crashes in the example, so maybe someone with better assimp knowledge can take a look?

My setup is OF master / Windows 10 / VS 2015.

**Comment by bilderbuchi** [comment]
possibly connected: #2155

**Comment by bakercp** [comment]
I'm getting similar issues on the example, but on my example, it crashes on loadModel

```c++
    // loads scene from file
    scene = shared_ptr<const aiScene>(aiImportFileExWithProperties(file.getAbsolutePath().c_str(), flags, NULL, store.get()), aiReleaseImport);
```

with a EXEC_BAD_ACCESS.  OSX, 10.10.5, Xcode7, master branch on both debug and release 64bit.

**Comment by tgfrerer** [comment]
This might be down to the calling order of shared pointer destructors. 

When using a `shared_ptr`, `aiReleasePropertyStore` is only called *after* a new `aiScene` object, held by the `shared_ptr` has been instantiated.

To illustrate the creation / destruction order of objects held by shared pointers, here's a [gist](https://gist.github.com/tgfrerer/1850b315db1c8f2b0324).

I'll send a PR in a minute, let's see if that fixes things =)

**Comment by arturoc** [comment]
i fixed this during the weekend :)

**Comment by arturoc** [comment]
do you still see the issue?

**Comment by tgfrerer** [comment]
Yes, there were a few minor issues, also with the way animations were loaded... I'm getting the PR ready in a sec...

**Comment by arturoc** [comment]
oh ok
