### ISSUE TITLE
Error running the ComputeShaderTextureExampleDebug on 0.9.0 RC1 macOS

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#4340]
This example in the example folder is giving me an error

```
if(settings.visible){
	glfwShowWindow(windowP);
}
if(settings.iconified){
	iconify(true);
}
if(requestedMode==OF_FULLSCREEN){
	setFullscreen(true);
}
```

glfwShowWindow(windowP) is throwing "Thread 1: EXC_BAD_ACCESS(code=1,address=0x30)"

That's the error in the console

[ error ] ofAppGLFWWindow: 65543: The requested client API version is unavailable
[ error ] ofAppGLFWWindow: couldn't create GLFW window
(lldb)

**Comment by tgfrerer** [comment]
Compute shaders require OpenGL version >= 4.3, which is not currently available on any Mac Operating system. 

To run compute shaders, use a recent Linux or Windows machine with modern drivers.
