### ISSUE TITLE
ofFbo::Settings renderer cache is problematic

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4345]
just picked up on a issue with the ofFbo::Settings caching the renderer in the constructor (introduced in PR #4102)

this is problematic on iOS when ofApp is created before the Renderer is created.
as soon as ofApp is instantiated, ofFbo is instantiated and the renderer is cached in the settings,
but on iOS, the renderer can be created later in the app lifecycle.

this is also problematic is someone decides to swap out renderers at run time.

i think it would make much more sense to cache the renderer when `allocate` is called on `ofFbo`

cc @arturoc @tgfrerer

**Comment by arturoc** [comment]
yes makes a lot of sense, just changed it. thanks!
