### ISSUE TITLE
how to reload ofxGuiGroup settings from file ?

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4350]
There is an undocumented method to set the file to save the data in `ofxGuiGroup`.
( use  `ofxGuiGroup :: setup(guiname, filename);` )
but is there a way to reload the current settings without knowing its filename ?
If no, this could be the `ofxBaseGui::loadFromFile()` (without arg).

**Comment by avilleret** [comment]
another trick could be `ofxBaseGui::loadFromFile(ofxBaseGui::filename)` but `filename` is protected.

**Comment by ludiccc** [comment]
More than a year after... (but still good for people looking for it):

`    parameters.setName("parameters");
    parameters.add(radio.set("Radio", 1, -10, 10));

    parameters.add(color.set("color",100,ofColor(0,0),255));
    
    gui.setup(parameters, "app-settings.xml", 0, 0);
    gui.loadFromFile("app-settings.xml");`

**Comment by avilleret** [comment]
thanks @ludiccc but this doesn't solve the problem, since in your example, you know the file name `"app-settings.xml"` and you have to store it somewhere outside the `gui` class.
Since this is already stored in the class, it would be more convenient to have a `void ofxBaseGui::reload()` method and/or a `string ofxBaseGui::getFilename()` method.

**Comment by ludiccc** [comment]
I'd just add the method `ofxBaseGui::reloadSettings()` to the ofxGuiGroup class to do this.

**Comment by avilleret** [comment]
thanks
