### ISSUE TITLE
ofFile::removeFile() fails on windows

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#4351]
simple test case: 

	ofFile temp("temp.txt");
	temp.create();
	ofFile::removeFile("temp.txt");

gets this output: 

    [ error ] ofFile: remove(): unable to remove ""data\temp.txt"": boost::filesyste
    m::remove: The process cannot access the file because it is being used by anothe
    r process: "data\temp.txt"

this is causing havok with the command line project generator since for updating there's a fair amount of moving files around.   more notes on that here

https://github.com/ofZach/pgElectron/issues/40

**Comment by ofZach** [comment]
I wonder if this is a permissions issue?

If you right click and make a new text file in the data folder and then try to delete it via ofFile() it also fails with the same error.

**Comment by ofZach** [comment]
here's another test -- try to open the file exclusively, then try to delete it: 

	HANDLE fh;
	fh = CreateFileA(ofToDataPath("blah.txt").c_str(), GENERIC_READ, 0 /* no sharing! exclusive */, NULL, OPEN_EXISTING, 0, NULL);
	if ((fh != NULL) && (fh != INVALID_HANDLE_VALUE))
	{
		cout << "we opened it exclusively" << endl;
		// the only open file to filename should be fh.
		// do something
		CloseHandle(fh);
	}
	else {
		cout << "we did not open it exclusively" << endl;
	}
	ofFile::removeFile("blah.txt");

in this case, results are: 

      we opened it exclusively
      [ error ] ofFile: remove(): unable to remove ""data\blah.txt"": boost::filesyste  
      m::remove: The process cannot access the file because it is being used by anothe
      r process: "data\blah.txt"

so I am skeptical about the error being reported by boost.

**Comment by arturoc** [comment]
that's because the file is still open, in windows you can't delete a file for which you ahve an open handle as far as i understand no?  when you create a file you can specify not to open it and instead only have a reference like:

```
ofFile temp("temp.txt",ofFile::ReferenceOnly);
```

also `temp.remove()` instead of the static version should work since it should close the file before attempting to remove it. if it's not working like that at least it's easy to fix

**Comment by bilderbuchi** [comment]
> in windows you can't delete a file for which you ahve an open handle as far as i understand no? 

AFAIK this is correct. I agree this sounds like an open handle problem, although this repro by zach should not fail, then.
> If you right click and make a new text file in the data folder and then try to delete it via ofFile() it also fails with the same error.

**Comment by ofZach** [comment]
hmm...

       ofFile temp("temp2.txt", ofFile::Reference);
	temp.create();
	temp.close();
	ofFile::removeFile("temp2.txt");

gives: 

[ error ] ofFile: remove(): unable to remove ""data\temp2.txt"": boost::filesyst
em::remove: The process cannot access the file because it is being used by anoth
er process: "data\temp2.txt"

I am having trouble removing even files that are def not open

**Comment by arturoc** [comment]
can you try now?

**Comment by ofZach** [comment]
cool ! this works now: 

       ofFile temp("temp.txt");
	temp.create();
	temp.close();
	ofFile::removeFile("temp.txt");

checking the command line tool now....

**Comment by ofZach** [comment]
yay!  updating is fixed now on the command line app :)

**Comment by arturoc** [comment]
great, also this:

```
ofFile temp("temp.txt");
temp.create();
temp.remove();
```

should work now too.

should we close this issue then?

**Comment by ofZach** [comment]
yes it seems fixed!
