### ISSUE TITLE
ofVideoPlayer ( AVFoundation ) doesn't loop by default ( regression ) 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4353]
In 0.8.4 the video player loops the video by default. 
In 0.9.0 / current master you have to explicitly tell it to loop.  

I'm pretty sure on Windows and Linux the default has been to loop. 

If there aren't any objections I will do a PR to reenable looping by default. 
I think without a fix this could break a ton of old projects that are expecting looping and not explicitly setting it.

**Comment by arturoc** [comment]
actually linux never looped until 0.9 :) but yes go for it.

btw it seems in: 3bd8c12ed339a85dabe7a2e5489e1f482d0935e9  you changed the fingers video with the opencv one, if you can change it back too?

**Comment by ofTheo** [comment]
huh - no idea why I changed that video. 
anyway I re-encoded the original video to H264 and it should be in there now.  
thanks!!
