### ISSUE TITLE
possible regression in programmable renderer. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4354]
Just noticed that it looks like the way OF is handling mesh colors vs global color in the programmable renderer might produce results different to the non-programmable renderer. 

In: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L2064

```
	void main(){
		gl_Position = modelViewProjectionMatrix * position;
		if(usingTexture>.5) texCoordVarying = (textureMatrix*vec4(texcoord.x,texcoord.y,0,1)).xy;
		if(usingColors>.5) colorVarying = color*globalColor;  // <--- for a mesh with colors set should't it be just the mesh color being shown.  In immediate mode the global color doesn't affect mesh colors. 
		else colorVarying = globalColor;
	}
```
I just commented the line above. 
Is this intentionally different from non-programmable renderer or is this a small regression? 
( or am I totally misunderstanding what is going on here :) ? )

**Comment by ofTheo** [comment]
ping @tgfrerer @arturoc

**Comment by arturoc** [comment]
that shader is only for the raspberry pi but yes i would have said that when using color coordinates the color would mix with the global color, if it really only shows the color coordinates i would change it to that

**Comment by ofTheo** [comment]
okay just checked and in 0.9.0 in both immediate and programmable mode global color doesn't affect the draw color of the mesh. 

going to fix this for the rpi to match. 
cheers @arturoc !
