### ISSUE TITLE
AVFoundation video player  crashes on 10.8

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4356]
It crashes at the two instances of:

		[notificationCenter removeObserver:self
									  name:AVPlayerItemPlaybackStalledNotification
									object:self.playerItem];

This is because AVPlayerItemPlaybackStalledNotification doesn't exist in the 10.8 framework. 
Going to submit a PR to do a check for this.

**Comment by ofTheo** [comment]
ping @julapy 
I thought this was totally safe to merge in - but just wanted to make you aware of the change.

**Comment by julapy** [comment]
yeah that looks good to me!
