### ISSUE TITLE
ofGstVideoPlayer loading with OF_PIXELS_NATIVE not working properly.

### ISSUE THREAD

**Issue by PetrosKataras** [openframeworks/openFrameworks#4358]
It seems that trying to load a video on the default format for avoiding the cpu colorspace conversion is broken somehow.  

The video will load but half of it is displaying correctly and the other half is just glitch. I will try to have a look but it would be great if someone else can confirm this also. For me it happens on both the programmable and the legacy renderer.

Just call :  

```
 player.setPixelFormat(OF_PIXELS_NATIVE)
```  
before loading.

I m testing with GStreamer 1.4 on OS X 10.10.4 and Linux 14.04.

**Comment by arturoc** [comment]
this only works with the programmable renderer since it needs shaders to do the colorspace conversion in the gpu

**Comment by PetrosKataras** [comment]
Yes, but the glitch happens on both the programmable and legacy renderer for me. The legacy should just draw the video on the default format without any colorspace conversion but it still has this glitch that I mentioned.

**Comment by PetrosKataras** [comment]
I think the problem comes from some recent changes to ofPixels. If I use this commit a34b9874e2cad988 which is  from April it works as expected . I cannot check properly though which commit exactly introduced the problem since right now I can only test on OS X and my version together with the changes for 64bit make it difficult to compile later commits. I ll have a go tomorrow on Linux also.

**Comment by arturoc** [comment]
yes I think it has to do with some changes to calculate the number of bytes per pixel. I'll take a look tomorrow
