### ISSUE TITLE
adding ofxOsc with project generator adds win32 folder

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4360]
I created a project with the new project generator, and added ofxOsc. It added the win32 folder to the project, which causes Xcode to complain `winsock2.h not found`.

**Comment by bilderbuchi** [comment]
shouldn't this go over to into the projectgenerator issue tracker?

**Comment by kylemcdonald** [comment]
Ah you're totally right. I saw a note about merging the repo and didn't
realize it was about merging pgElectron into peojectGenerator not into the
main repo. I'll fix it.

**Comment by bilderbuchi** [comment]
yeah, it's high time to get rid of that confusing situation with the PG(s), if even core devs get it wrong. :-)
