### ISSUE TITLE
project generator replaces dashes with underscores

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4361]
i sometimes use dashes in my project names and the pgElectron interface seems to replace them with underscores when i try to update the project file, which means it fails to open the addons.make correctly, and also generates new source files.

maybe a better behavior would be to throw an error when trying to import something rather than automatically replacing it with underscores?

**Comment by ofZach** [comment]
this code was from the pgSimple but I'm not even sure if it's necessary to change these symbols (but things like spaces definitely present problems, so changing them is needed).   let me check....

**Comment by arturoc** [comment]
yes `-` should be ok, spaces can be problematic with makefiles but i've been bitten by this with the PG simple several times when trying to update a project with `-` in it. i agree it should show an error instead or apart from changing the name.
