### ISSUE TITLE
Multi window fullscreen issue

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#4372]
I've been sitting with a lot of problems today with the multi window support. I'm not excatly sure what is going wrong, but i'm pretty sure there are some bugs / missing features. 

The case: I'm have an app (LightLeaks) that needs to run on a new Mac Pro (the bin). We need the installation to run on 3 projectors, so my thought was to change the app to initialize 3 windows, all sharing context, and making them fullscreen on each one display on startup. 

The projectors are running 1920x1200, and i had a primary display running 1920x1080. If i in main.cpp run

```
 window->setWindowPosition(1920, 0);
 window->setFullscreen(true);
``` 
on all 3 windows, they do fullscreen, but only 1080px high (not 1200px). If i toggle fullscreen twice they fullscreen correctly, but often they jump to main screen when I do it. I changed my main monitor to also run 1200px high, "fixing" this problem, but often they dont fullscreen correctly anyway. 

Second thing i tried was to run the windows without decoration, and setting the dimensions and position of the windows so they should fullscreen in setup. Initially this worked, but suddenly when one of the proejctors turned off and on again, the window was offset by half of the screen height, also after rebooting. So setting ofSetWIndowPosition(1920,0), did not set the window to the top left corner of the second screen, but instead above the screen. 

My last test was to run this code every frame in update. And that worked, now the windows are properly filling out the screens, but it seems like an odd way to do it. 

My suggestion is to add a function call that will tell a window to fullscreen on a monitor with a specific name or id. It seems like a very usefull feature of the multiwindows to be able consistently to fullscreen on the right monitors, even when the layout changes.

**Comment by bilderbuchi** [comment]
It's slightly tangent to the problem at hand, but have you considered getting a Triplehead2Go (matrox device) - it's a pretty great line of devices, and saves all kinds of multi-desktop, multi-window, v-sync, maximization, etc. issues if you just run your app in _one_ window with dimensions 3*width x height. :-)

**Comment by bilderbuchi** [comment]
also, are your monitor/projector ids constant over a power cycle of involved devices? what are the names/ids if you have a set of identical devices?

**Comment by kylemcdonald** [comment]
we've used a th2g in the past, but it only works for low resolution projectors (up to 1360 pixels wide on each iirc).

**Comment by ofTheo** [comment]
I've run into this issue quite a bit with my own GLFW multi window implementation. 
GLFW can be really fussy with the way the order that you do thing.  ( On MSFT Windows I even have to move the screen to the monitor on one frame and then a few frames later go fullscreen ). 

So I think ultimately we need a way to query available monitors and get back id, name and dimensions ( all available with GLFW ), then target the monitor ( as you suggested @HalfdanJ  ).

**Comment by ofTheo** [comment]
@bilderbuchi names can be the same, ids are consistent over power cycles ( at least on OS X and Windows ).

**Comment by charlesveasey** [comment]
I think the window position is not set by the system before the call to fullscreen. Something like this seems more reliable.

```

#include "ofMain.h"
#include "ofApp.h"

shared_ptr<ofAppGLFWWindow> win1;
shared_ptr<ofAppGLFWWindow> win2;

void windowPosCallback1(GLFWwindow *glfw, int x, int y){
    cout << "window 1 pos callback " << x << " " << y << endl;
    glfwSetWindowPosCallback(glfw, NULL); // remove callback function, as fullscreen sets position
    win1->setFullscreen(true);
}

void windowPosCallback2(GLFWwindow *glfw, int x, int y){
    cout << "window 2 pos callback " << x << " " << y << endl;
    glfwSetWindowPosCallback(glfw, NULL); // remove callback function, as fullscreen sets position
    win2->setFullscreen(true);
}

//========================================================================
int main( ){
	ofGLFWWindowSettings settings;
    settings.width = 1024;
    settings.height = 768;
    settings.decorated = true; // false doesn't completely fullscreen
    
    // monitor 1 -- res: 1920x1080 -- pos: 0,0
    settings.setPosition(ofVec2f(0,0));
    win1 = static_pointer_cast<ofAppGLFWWindow>(ofCreateWindow(settings));
    
    // monitor 2 -- res: 1680x1050 -- pos: -1679,0 (to the left of first monitor)
    settings.setPosition(ofVec2f(-1679,0));
    win2 = static_pointer_cast<ofAppGLFWWindow>(ofCreateWindow(settings));

	shared_ptr<ofApp> app1(new ofApp);
    shared_ptr<ofApp> app2(new ofApp);

    ofRunApp(win1, app1);
    ofRunApp(win2, app2);
    
    GLFWwindow *glfw1 = win1->getGLFWWindow();
    GLFWwindow *glfw2 = win2->getGLFWWindow();
    
    glfwSetWindowPosCallback(glfw1, windowPosCallback1);
    glfwSetWindowPosCallback(glfw2, windowPosCallback2);

    ofRunMainLoop();
}


```

**Comment by charlesveasey** [comment]
oddly, setting the 2nd window's position to (-1680,0) causes the window to jump to the first monitor when set to fullscreen, but (-1679,0) works

**Comment by charlesveasey** [comment]
Overloading the fullscreen function with a target monitor index would be convenient: 
```
ofAppGLFWWindow::setFullscreen(int monitorIndex);
```

**Comment by bilderbuchi** [comment]
> we've used a th2g in the past, but it only works for low resolution projectors (up to 1360 pixels wide on each iirc).

really? afaik, max resolution is 3x fullHD, i.e. 3x1920x1080@50Hz, and that is backed up by the [specs page](http://www.matrox.com/graphics/en/products/gxm/th2go/displayport/). I've never personally set up such a system due to lack of projectors/need at the time, though. were you maybe using the old VGA-equipped version instead of the displayport or dvi one?

**Comment by HalfdanJ** [comment]
@bilderbuchi Running the triplehead in that high resolution is very unstable. Many macs can't do it (even with active duallink dvi), and the new Mac Pro has big problems with that resolution. Also we needed 1920x1200, so a bit higher then the specs :) 

I like the `setFullscreen` overload solution from @charlesveasey, only i think it should be monitor ID instead og index (or both). Many applications like madmapper for example run with an unique ID per monitor with pretty good succes.

**Comment by arturoc** [comment]
looking a the osx code for fullscreen there's several hacks to make the window fullscreen related to the OS changing it's size and position to fit the window while it's being set to the new size to make it fullscreen. 

fullscreen in the glfw window is only a window without decorations so doing that manually should be the same as calling setFullScreen.

i would try to set the window to fullscreen in main using the window settings:

```
ofGLFWWindowSettings settings;
settings.windowMode = OF_FULLSCREEN;
ofCreateWindow window;
ofRunApp(new ofApp);
```

the main difference is that the window is created from the very beginning in fullscreen and it's also hidden so chances are that the operating system won't try to move it while it's not being shown.

but yes in the long term having an option to make a window appear or go fullscreen in an specific monitor is the best solution.

**Comment by arturoc** [comment]
this works fine in linux:

```cpp
#include "ofMain.h"

class ofApp: public ofBaseApp
{
public:
	void setup(){
	}

	void draw(){
		ofDrawBitmapString("window 1",ofGetWidth()/2,ofGetHeight()/2);
	}

	void keyPressed(int key){
	}
};


class ofApp2: public ofBaseApp
{
public:
	void setup(){
	}

	void draw(){
		ofDrawBitmapString("window 2",ofGetWidth()/2,ofGetHeight()/2);
	}

	void keyPressed(int key){
	}
};

int main()
{
    ofGLWindowSettings settings;
    settings.setPosition({0.f,0.f});
    settings.windowMode = OF_FULLSCREEN;
    auto win1 = ofCreateWindow(settings);

    settings.setPosition({(float)win1->getWidth(),0.0f});
    settings.windowMode = OF_FULLSCREEN;
    auto win2 = ofCreateWindow(settings);

    ofRunApp(win1, std::make_shared<ofApp>());
    ofRunApp(win2, std::make_shared<ofApp2>());

    ofRunMainLoop();
}
```

but the code to go fullscreen is very platform specific so it might not work in osx.

btw, looking into the code there's already a way to create a fullscreen window in a specific monitor, but it'll only work with OF_GAME_MODE and you need to specify the correct resolution for each window since game mode changes the resolution of the screen to the passed width and height rather than creating an undecorated window:

```cpp
#include "ofMain.h"

class ofApp: public ofBaseApp
{
public:
	void setup(){
	}

	void draw(){
		ofDrawBitmapString("window 1",ofGetWidth()/2,ofGetHeight()/2);
	}

	void keyPressed(int key){
	}
};


class ofApp2: public ofBaseApp
{
public:
	void setup(){
	}

	void draw(){
		ofDrawBitmapString("window 2",ofGetWidth()/2,ofGetHeight()/2);
	}

	void keyPressed(int key){
	}
};

int main()
{
    ofGLWindowSettings settings;
    settings.monitor = 0;
    settings.width = 1920;
    settings.height = 1280;
    settings.windowMode = OF_GAMEMODE;
    auto win1 = ofCreateWindow(settings);

    settings.monitor = 1;
    auto win2 = ofCreateWindow(settings);

    ofRunApp(win1, std::make_shared<ofApp>());
    ofRunApp(win2, std::make_shared<ofApp2>());

    ofRunMainLoop();
}
```

**Comment by arturoc** [comment]
just added a small fix that get's the size and position of the window from the monitor specified in settings in fullscreen too so now you can do too:

```cpp
#include "ofMain.h"

class ofApp: public ofBaseApp
{
public:
    void setup(){
    }

    void draw(){
        ofDrawBitmapString("window 1",ofGetWidth()/2,ofGetHeight()/2);
    }

    void keyPressed(int key){
    }
};


class ofApp2: public ofBaseApp
{
public:
    void setup(){
    }

    void draw(){
        ofDrawBitmapString("window 2",ofGetWidth()/2,ofGetHeight()/2);
    }

    void keyPressed(int key){
    }
};

int main()
{
    ofGLFWWindowSettings settings;
    settings.monitor = 0;
    settings.windowMode = OF_FULLSCREEN;
    auto win1 = ofCreateWindow(settings);

    settings.monitor = 1;
    auto win2 = ofCreateWindow(settings);

    ofRunApp(win1, std::make_shared<ofApp>());
    ofRunApp(win2, std::make_shared<ofApp2>());

    ofRunMainLoop();
}
```

but i've only tested it on linux and it's still calling `setFullscreen(true)` where i suspect is the issue in osx so it might not work there

**Comment by kylemcdonald** [comment]
i can confirm that the `monitor = 1` implementation you gave doesn't work for OSX arturo.

but @ofTheo just gave me a quick fix, which is to add this to `update()`:

```
        if( ofGetFrameNum() == 2 ){
            ofSetWindowPosition(1920, 0);
        }
        if( ofGetFrameNum() == 4 ){
            ofSetFullscreen(true);
        }
```

which makes me think @charlesveasey is right, that the call to fullscreen is happening before the window position is changed.

**Comment by NickHardeman** [comment]
I think the issue is in the getCurrentMonitor() function. https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L464-L465
The monitorRect.inside(xW, yW) function returns false if the point is lying on the rectangle and not inside it. So, setting the y to 0 means it is not actually inside the rectangle. I have done several tests on OSX 10.8 and it works like a charm. Seems intuitive to have it return true if it also lies on the rectangle.
So you can do:
`mainWindow->setWindowPosition(-920, 0);
mainWindow->setFullscreen(true);`
in the main.cpp or call 
'ofSetWindowPosition( -920, 0 );
ofSetFullscreen( true );'
in setup.
Sending a PR now. :)

**Comment by kylemcdonald** [comment]
wow @NickHardeman that's amazing! great find! thanks for this :)
