### ISSUE TITLE
ofAVFoundationPlayer previousFrame() then play() texture cache not updating

### ISSUE THREAD

**Issue by trentbrooks** [openframeworks/openFrameworks#4384]
When running the standard videoPlayerExample and rewinding via previousFrame() (in frame by frame mode), once you hit play again (toggle f key) the texture stays frozen until the playhead catches up to the time it was initially paused. The timecode updates, and sound plays as normal during this frozen texture state (tested with other videos). Note- this does not occur with nextFrame().

May be related to https://github.com/openframeworks/openFrameworks/issues/3629

**Comment by trentbrooks** [comment]
Basically the -seekToTime:toleranceBefore:toleranceAfter: values need to be set to kCMTimeZero for higher precision seeking instead of the default kCMTimePositiveInfinity (https://developer.apple.com/library/mac/documentation/AVFoundation/Reference/AVPlayer_Class/index.html#//apple_ref/occ/instm/AVPlayer/seekToTime:toleranceBefore:toleranceAfter:). 

In OF, this means changing line 881 in ofAVFoundationVideoPlayer.m... (https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofAVFoundationVideoPlayer.m#L881) to the following...

[self seekToTime:CMTimeMakeWithSeconds(timeSec, NSEC_PER_SEC) withTolerance:kCMTimeZero];

The fallout for using this method is the slight 'additional decoding delay', as mentioned in the apple docs. So not sure if this is something worth submitting a PR for?

Thanks,
Trent

P.S. without modifying the core, i used this ofApp snippet instead of previousFrame() https://gist.github.com/trentbrooks/f8a0bd42334c12890083

**Comment by trentbrooks** [comment]
Here's the commit if a future PR is required- https://github.com/trentbrooks/openFrameworks/commit/eaca4ca36967143619c4356fa69ac93970df57ed

**Comment by i-n-g-o** [comment]
while PR #4402 fixed reported issue another issue is related to the same problem: https://github.com/openframeworks/openFrameworks/issues/4651

closing this ticket and continue discussion in https://github.com/openframeworks/openFrameworks/issues/4651
