### ISSUE TITLE
ofFile::moveFromTo broken on 0.9

### ISSUE THREAD

**Issue by traumedy** [openframeworks/openFrameworks#4396]
Seems to create an ofFile with the source file, which opens the file, so the file is in use when Poco attempts the rename operation.
Tested with latest Windows VS nightly build, Windows 7 64 bit.

**Comment by arturoc** [comment]
that should fix it but if you can double check? i think this is only a windows problem since other OSs are ok with moving, deleting... a file that is being used.

**Comment by traumedy** [comment]
Sure I'll check it, do I need to wait for the next nightly build?  I've had
little luck building off the cloned repo..

On Sat, Sep 26, 2015 at 1:32 AM, arturo <notifications@github.com> wrote:

> that should fix it but if you can double check? i think this is only a
> windows problem since other OSs are ok with moving, deleting... a file that
> is being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143409835>
> .
>



-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential

**Comment by arturoc** [comment]
yes, unless you can check from the repo you'll need to wait until
tomorrow. the only file that has changed is ofFileUtils.cpp so you can
also just get that file from github and drop it in the current nightly

**Comment by traumedy** [comment]
Seems fixed from my one test,

On Sat, Sep 26, 2015 at 1:55 AM, arturo <notifications@github.com> wrote:

> yes, unless you can check from the repo you'll need to wait until
> tomorrow. the only file that has changed is ofFileUtils.cpp so you can
> also just get that file from github and drop it in the current nightly
>
> On 26.09.2015 10:35, traumedy wrote:
> > Sure I'll check it, do I need to wait for the next nightly build? I've
> had
> > little luck building off the cloned repo..
> >
> > On Sat, Sep 26, 2015 at 1:32 AM, arturo <notifications@github.com>
> wrote:
> >
> >> that should fix it but if you can double check? i think this is only a
> >> windows problem since other OSs are ok with moving, deleting... a file
> > that
> >> is being used.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >>
> > <
> https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143409835
> >
> >> .
> >>
> >
> >
> >
> > --
> > *JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
> > <http://www.obscuradigital.com/> | SF
> > <http://www.obscuradigital.com/contact/> +1 415 227 9979 |
> > <http://www.obscuradigital.com/contact/>
> > <http://www.obscuradigital.com/contact/>
> > <http://www.obscuradigital.com/contact/>NYC
> > <http://www.obscuradigital.com/contact/> |
> > <http://www.obscuradigital.com/contact/>
> > <http://www.obscuradigital.com/contact/>
> > <http://www.obscuradigital.com/contact/>
> > <http://www.obscuradigital.com/contact/>Stockholm
> > <http://www.obscuradigital.com/contact/>
> > | Proprietary & Conﬁdential
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143410920
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143412643>
> .
>



-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential

**Comment by traumedy** [comment]
Tested on Win 8.1 VS win32 and x64.

On Sat, Sep 26, 2015 at 8:13 PM, Josh Buchbinder <joshb@obscuradigital.com>
wrote:

> Seems fixed from my one test,
>
> On Sat, Sep 26, 2015 at 1:55 AM, arturo <notifications@github.com> wrote:
>
>> yes, unless you can check from the repo you'll need to wait until
>> tomorrow. the only file that has changed is ofFileUtils.cpp so you can
>> also just get that file from github and drop it in the current nightly
>>
>> On 26.09.2015 10:35, traumedy wrote:
>> > Sure I'll check it, do I need to wait for the next nightly build? I've
>> had
>> > little luck building off the cloned repo..
>> >
>> > On Sat, Sep 26, 2015 at 1:32 AM, arturo <notifications@github.com>
>> wrote:
>> >
>> >> that should fix it but if you can double check? i think this is only a
>> >> windows problem since other OSs are ok with moving, deleting... a file
>> > that
>> >> is being used.
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >>
>> > <
>> https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143409835
>> >
>> >> .
>> >>
>> >
>> >
>> >
>> > --
>> > *JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
>> > <http://www.obscuradigital.com/> | SF
>> > <http://www.obscuradigital.com/contact/> +1 415 227 9979 |
>> > <http://www.obscuradigital.com/contact/>
>> > <http://www.obscuradigital.com/contact/>
>> > <http://www.obscuradigital.com/contact/>NYC
>> > <http://www.obscuradigital.com/contact/> |
>> > <http://www.obscuradigital.com/contact/>
>> > <http://www.obscuradigital.com/contact/>
>> > <http://www.obscuradigital.com/contact/>
>> > <http://www.obscuradigital.com/contact/>Stockholm
>> > <http://www.obscuradigital.com/contact/>
>> > | Proprietary & Conﬁdential
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143410920
>> >.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openframeworks/openFrameworks/issues/4396#issuecomment-143412643>
>> .
>>
>
>
>
> --
> *JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
> <http://www.obscuradigital.com/> | SF
> <http://www.obscuradigital.com/contact/> +1 415 227 9979 |
> <http://www.obscuradigital.com/contact/>
> <http://www.obscuradigital.com/contact/>
> <http://www.obscuradigital.com/contact/>NYC
> <http://www.obscuradigital.com/contact/> |
> <http://www.obscuradigital.com/contact/>
> <http://www.obscuradigital.com/contact/>
> <http://www.obscuradigital.com/contact/>
> <http://www.obscuradigital.com/contact/>Stockholm
> <http://www.obscuradigital.com/contact/>
>  | Proprietary & Conﬁdential
>
>


-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential
