### ISSUE TITLE
Lack of color in ofxBullet scene with latest nightly build

### ISSUE THREAD

**Issue by traumedy** [openframeworks/openFrameworks#4397]
Compiled ofxBullet cloth example with 0.9 RC1, balls are yellow and cloth is red. Did same with the latest VS nightly build and background is color but objects in scene are all grey.

**Comment by arturoc** [comment]
i fixed an error with this some days ago. the material color wasn't being applied correctly, now it is. it might be that this example is applying the colors using ofSetColor instead of ofMaterial but then using lights? in that case you should either remove the lights or set the color to the diffuse of each material

**Comment by traumedy** [comment]
I'm just giving feedback regarding my observation of a well used addon example that changed behavior between RC1 and now.  If the oF API changed behavior, that should be documented somehow so that maintainers of addons and everyone else can adjust their code appropriately?

**Comment by traumedy** [comment]
I posted this thread link to the ofxBullet repo, but who else might this impact?

**Comment by arturoc** [comment]
can you post a link to the example?

**Comment by traumedy** [comment]
https://github.com/NickHardeman/ofxBullet/tree/master/ClothExample

**Comment by arturoc** [comment]
mmh, ok, yes i fixed this some days ago thinking it was a bug we introduced lately but didn't thought it had been there since so much time ago. i'll check in the developer list and decide what to do.

thanks!

**Comment by ofTheo** [comment]
ping @NickHardeman as this is his addon :)

**Comment by arturoc** [comment]
yes, also check the dev list

**Comment by traumedy** [comment]
I already opened an issue in that repo, posted a link to this thread and a
link to the dev list post Arturo made regarding this subject.

On Sat, Sep 26, 2015 at 11:01 AM, arturo <notifications@github.com> wrote:

> yes, also check the dev list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4397#issuecomment-143476428>
> .
>



-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential
