### ISSUE TITLE
setSpaceSize does not work anymore

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#4400]
Hi, I'm using the method setSpacesSize in the OF 0.9 release http://openframeworks.cc/documentation/graphics/ofTrueTypeFont.html1 to change the dimension of the space between the words, but it has no effect, I've tried with different fonts but I've always the same result. Another user in the forum reports to have the same problem http://forum.openframeworks.cc/t/font-set-spaces-size/20846

    ofTrueTypeFont font;
    font.loadFont("OpenSans-Regular.ttf", 30);
    font.setSpaceSize(3.0);

**Comment by bilderbuchi** [comment]
ping @openframeworks/typography

**Comment by arturoc** [comment]
thanks!
