### ISSUE TITLE
ofxAssimpModelLoader and example issues with VS latest nightly build

### ISSUE THREAD

**Issue by traumedy** [openframeworks/openFrameworks#4403]
Didn't try older versions, so not sure how long these issues have existed.
examples/3d/modelNoiseExample gets these errors and renders nothing:
[ error ] ofxAssimpModelLoader: loadGLResource(): texture doesn't exist: "dog.3ds" in "data\dog\dog sized ne"
[ error ] ofxAssimpModelLoader: loadGLResource(): couldn't load texture: "dog.3ds" from "data\dog\dog sized ne"

If a model IS loaded, even with the errors of modelNoiseExample, ofxAssimpModelLoader crashes during destruction, call stack:
>	modelNoiseExample_debug.exe!operator delete(void * block) Line 21	C++
 	modelNoiseExample_debug.exe!operator delete(void * block, unsigned __int64 __formal) Line 16	C++
 	modelNoiseExample_debug.exe!std::_Ref_count<aiPropertyStore>::_Destroy() Line 154	C++
 	modelNoiseExample_debug.exe!std::_Ref_count_base::_Decref() Line 113	C++
 	modelNoiseExample_debug.exe!std::_Ptr_base<aiPropertyStore>::_Decref() Line 339	C++
 	modelNoiseExample_debug.exe!std::shared_ptr<aiPropertyStore>::~shared_ptr<aiPropertyStore>() Line 573	C++
 	modelNoiseExample_debug.exe!ofxAssimpModelLoader::~ofxAssimpModelLoader() Line 15	C++

I also haven't been able to get it to actually draw a model, even with a model that reports no errors, though with no working example to go on it might be my own code error, but it still crashes on ofxAssimpModelLoader destruction.

**Comment by bilderbuchi** [comment]
ping @openframeworks/windows @arturoc
