### ISSUE TITLE
OpenCV OS X lib is only x64, can't compile lib with apothecary script

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/openFrameworks#4406]
I was trying to build a 32bit app with ofxCv and noticed that opencv.a is missing the i386 slice:

```
$ pwd
/Users/mattfelsen/Documents/Code/openFrameworks/github/addons/ofxOpenCv/libs/opencv/lib/osx

$ lipo -info opencv.a 
input file opencv.a is not a fat file
Non-fat file: opencv.a is architecture: x86_64
```

The latest change to that lib file was commit https://github.com/openframeworks/openFrameworks/commit/4f65adc114127227c28e5b9d49b0f2de0cd06ba0, and assimp.a, which was also updated then, looks correct:

```
$ lipo -info assimp.a 
Architectures in the fat file: assimp.a are: i386 x86_64 
```

The history on the OpenCV.sh apothecary script looks like it's split before/after a filename change from OpenCV.sh to opencv.sh.

Before: https://github.com/openframeworks/openFrameworks/commits/4f65adc114127227c28e5b9d49b0f2de0cd06ba0/addons/ofxOpenCv/scripts/formulas/OpenCV.sh
After: https://github.com/openframeworks/openFrameworks/commits/master/addons/ofxOpenCv/scripts/formulas/opencv.sh

In the last commit that touched opencv.a (https://github.com/openframeworks/openFrameworks/commit/4f65adc114127227c28e5b9d49b0f2de0cd06ba0) there's actually a new make_universal_binary() function introduced that (I think?) looks like it's creating a universal lib: https://github.com/openframeworks/openFrameworks/commit/4f65adc114127227c28e5b9d49b0f2de0cd06ba0#diff-bfefa9c47477314605eca6a2c934e932. But looking at the script in current master, that bit is now gone: https://github.com/openframeworks/openFrameworks/blob/56ba96309c2b580f6153ffdc3e14a32161f52b79/addons/ofxOpenCv/scripts/formulas/opencv.sh#L53-L122

I tried compiling anyway in case it is in fact making a universal lib, but ran into these errors:

```
$ pwd
/Users/mattfelsen/Documents/Code/openFrameworks/github/scripts/apothecary

$ ./apothecary update ofxOpenCv
```
... bunch of stuff ...

( This looks like it could be important for supporting older OS X versions. Do we need to compile addon libs against an older SDK? (10.7? 10.8?) )

```
CMake Warning at /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but the matching SDK does not exist
  at:
   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"

  Instead using SDK:
   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk".
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:56 (project)
```

And the actual error:

```
[ 93%] Building CXX object modules/contrib/CMakeFiles/opencv_contrib.dir/src/rgbdodometry.cpp.o
/Users/mattfelsen/Documents/Code/openFrameworks/github/scripts/apothecary/build/opencv/modules/contrib/src/rgbdodometry.cpp:65:12: fatal error: 'unsupported/Eigen/MatrixFunctions' file not found
#  include <unsupported/Eigen/MatrixFunctions>
           ^
1 error generated.
make[2]: *** [modules/contrib/CMakeFiles/opencv_contrib.dir/src/rgbdodometry.cpp.o] Error 1
make[1]: *** [modules/contrib/CMakeFiles/opencv_contrib.dir/all] Error 2
make: *** [all] Error 2

 ^ Received error ^
```

I also got *lots* of these warnings spit out at first:

```
CMake Warning (dev) at cmake/OpenCVModule.cmake:873 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "-framework Cocoa".
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:920 (__ocv_track_module_link_dependencies)
  CMakeLists.txt:578 (ocv_track_build_dependencies)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

64bit seems fine :smile:

**Comment by julapy** [comment]
i can also confirm this.
currently using ofxOpenCv for a project and can't build it under 32-bit as symbols are missing.
only works with 64-bit.

building with latest xcode, OSX 10.11

**Comment by arturoc** [comment]
i merged this from @i-n-g-o just so nobody freaks out if they see this commits without PR :)

**Comment by mattfelsen** [comment]
:wink: thanks!
