### ISSUE TITLE
RPi support strategy since Debian Jessie Release

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4408]
The RPi foundation is now has Jessie available on the [RPi downloads page](https://www.raspberrypi.org/downloads/raspbian/). 

Should we try supporting both Wheezy and Jessie or just pick Jessie for 0.9? The biggest issue with Jessie that I know of is OF's current requirement of a python module unavailable for python 2.7 #3703

**Comment by jvcleave** [comment]
apparently removing `python-argparse` from install dependencies may help with python 2.7

http://forum.openframeworks.cc/t/raspberry-pi-2-setup-guide/18690/69

**Comment by bilderbuchi** [comment]
sure, because as you can read in the other issue, from python 2.7 argparse is part of the standard lib, so a separate package/module is not needed.
Also, this is not an appropriate change for 0.9, too late in the release cycle for that, so it will come later than that.

**Comment by arturoc** [comment]
we don't use that python module any more, i thought i had removed it from the scripts a while ago but feel free to remove it if it's still there.

and if jessie is already oficially supported i'd say we should give support for jessie only, mainly the version of gcc, boost and gstreamer that comes with wheezy are relatively old and have some problems so even if it works right now i think for next versions we shouldn't try to keep support for wheeze (ie: using regex...)

**Comment by bilderbuchi** [comment]
> we don't use that python module any more

scripts/win_cb/createProjects.py still has an `import argparse` line, though.

**Comment by arturoc** [comment]
that is not used any more either, i didn't realize it was still there

**Comment by bilderbuchi** [comment]
so the script can be deleted?

**Comment by jvcleave** [comment]
the of_v20151003_linuxarmv6l_nightly.tar.gz seemed to work with the RPi Jessie disk image. I'll need to run through it again as libboost was taking forever so I may have opted for `libboost-all-dev ` instead - can't remember as I walked away from it.

Cross compiling is a mess because the [raspberry pi tools apparently are still using gcc 4.8.3] (https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64)

I think we will need to make adjustments [here](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L224) as well to make it use 4.9 references
