### ISSUE TITLE
[Suggestion] Bonjour/ZeroConf OSC automatic integration

### ISSUE THREAD

**Issue by Lyptik** [openframeworks/openFrameworks#4410]
Hello guys,

Here is a feature request.

Why not adding a Bonjour/zeroconf multiplatform integration when listening and sending osc data in the ofxOsc addons ?

This is actually how [https://github.com/mrRay/vvopensource](https://github.com/mrRay/vvopensource) does (but only on the OSX side), when you listen to osc on a port, it automatically advertises itself on the network that you are listening to something and on each port. The same goes when sending data.

This has been documented here [http://opensoundcontrol.org/topic/110](http://opensoundcontrol.org/topic/110) and there and is almost (yet non officialy) a "standard" way that is understood by most applications like Osculator, Vezer etc...

This way you can code your input output osc without even knowing that you are advertising them. Then you don't have to worry anymore about IPs and ports of computer in your network who sends osc to each other, this is just totally awesome and would save some precious time to everybody, from beginners to experts.

Cheers

PS : Arduino has a nice working opensource implementation of libbonjour btw.
PS2 : Yes I know there is quite some work to do but worth it. If anyone here has the time to start it, I'd love to discuss and collaborate on it once I have some more spare time
PS3 : First effort I found are here : [https://github.com/robotconscience/ofxBonjour](https://github.com/robotconscience/ofxBonjour) and here [https://github.com/2bbb/ofxBonjour](https://github.com/2bbb/ofxBonjour)

**Comment by kylemcdonald** [comment]
usually i rely on existing bonjour infrastructure for this kind of thing. so if i'm working with @ofZach i might create an osc connection to `zach.local` and he will create on to `kyle.local` to keep us in sync.

that said, depending on the network configuration this doesn't always work. it would be a cool feature to have but might also cause more maintenance headaches than necessary, and be better suited to an addon like the ones from @2bbb and @robotconscience you mention.

**Comment by Lyptik** [comment]
Yep, but here you are talking only on the mDns part of Zeroconf/Bonjour :) which only helps for the IP part. I am using also that to detect ip on network sometimes, but never in code.

With Bonjour/ZeroConf, you will directly see listed every software source providing osc, without thinking port or ip, and that happens only on your UI, so you don't have to change anything on your code.

This solution is network and platform agnostic, so you can work with Zach or anybody else in a workshop.

I totally agree that this should go first from an addon phase (and yes maintenance on that one would not be that easy either probably). But then the magic would really happen once it is integrated in the osc addon and when you use osc as usual without knowing it's here and taking advantage later on when needed or through other apps.

For example try this : [http://vidvox.com/rays_oddsnends/vvopensource_downloads/OSCTestApp_0.2.4.zip](http://vidvox.com/rays_oddsnends/vvopensource_downloads/OSCTestApp_0.2.4.zip) taken from the Readme here : [https://github.com/mrRay/vvopensource](https://github.com/mrRay/vvopensource)

And fire some application like this : [http://www.osculator.net/download/](http://www.osculator.net/download/)

(Which are by the way two great application to debug osc from a mac when you don't have your own close to your hand)

You will see that they will know each other even if they are not on the same computer, through the osc bonjour "standard" I was talking in the last message.

The magic would be just coding this : receiver.setup(PORT);
And then you have advertise as well on the network your port and ip through bonjour.

It's actually really simple. The hard work resides in the multiplatform aspect. I think that Qt has it but I'm not quitte sure.

Anyway thanks for the time taken to give me your opinion, I hope one day some this idea will get some attention from the community, I will maybe start it at some point during a residency or a workshop where I become crazy about my ten apps talking osc to each other :)

**Comment by bakercp** [comment]
Hey @Lyptik I've got an unreleased cross platform zeroconf library (wraps avahi on linux/android and bonjour on windows / mac).  I'm adding you to the repo.  If it looks like something that you think would contribute to the conversation, let me know and I can work on releasing it.

**Comment by bakercp** [comment]
By the way, I use the addon for just what you describe -- cross platform OSC advertising, etc.  I also use it for advertising local websites and services for installations.  Anyway, it's really close-to release-ready, just haven't taken the time.

**Comment by Lyptik** [comment]
Yay ! Pretty cool, that's exactly what I was talking about ! Did you start from scratch or did you look at some project who started doing this ? Did you check if Qt has this thing or not ? Anyway, wrapping avahi and bonjour on windows mac seems about the right thing to do. Except that for windows you had the choice of going other road right ? I guess you have to install the runtime bonjour lib from apple on windows to make it work ? I'm gonna look at your repo right now.

**Comment by bakercp** [comment]
@Lyptik yeah, I include the bonjour binaries for windows.  It's installed with itunes or as a standalone for printers.  Probably possible to do avahi on windows, but apple's bonjour implementation just worked out of the box with my dnssd code.

The code is pretty much from scratch, just wraps bonjour / avahi in a common interface (they already share most of the same interface anyway).

**Comment by Lyptik** [comment]
That’s really good news !

What do you think about the idea of overriding ofxOsx with that ?

**Comment by bakercp** [comment]
Well, ofxZeroconf - my addon is just a generic zerconf client / browser so I don't think it would make sense to make it officially part of ofxOsc.  I usually just do it in two parts like this ...

```
void ofApp::setupNetwork()
{
    uint16_t recieverPort = 9876;

    oscReceiver = std::make_unique<ofxOscReceiver>();
    oscReceiver->setup(recieverPort);

    ofx::Zeroconf::registerClientEvents(this);
    ofx::Zeroconf::registerBrowseEvents(this);

    browseRef = ofx::Zeroconf::browse(PLAYER_ZEROCONF_TYPE);

    Zeroconf::Service::TXTRecord rec;
    rec.add("version", getVersionString());

    Zeroconf::Service service(REMOTE_ZEROCONF_NAME,
                              REMOTE_ZEROCONF_TYPE,
                              recieverPort,
                              rec);

    serviceRef = ofx::Zeroconf::registerService(service);

}
```

**Comment by bakercp** [comment]
Then when the app gets closed down, the records are destroyed.

**Comment by Lyptik** [comment]
Ok.

My original idea was that all your lines after oscReceiver->setup(recieverPort);

are generic right ?

So why not implementing them into the ofxOscReceiver::setup(int) function ?

This way, you can use oscreceiever like before, but enjoy all the zeroconf goodness if you need so as well, or if you need that at a later point in the life of your app.

So my idea was to override ofxOsc to implement this at the same time, and having that features in a transparent manner.

But as ofxOsc is par of OF core, I asked for your opinion on Github. I guess that it’s more work to maintain that if we add ofxZeroconf to the core.

But then you came with it already done !

I’m browsing through the code and that’s exactly what I was looking for !

A multiplatform zeroconf library and an ofxwrapper, oh yeah :)

Trying to make it compile on my machine now. What was your config ? OF 0.8.4 ?

**Comment by bakercp** [comment]
@Lyptik Master branch should be up to date with 0.9.0.  If you want to help me test and document it (it still needs some testing on Linux), I'd be happy to release it.  But for now it's private code.  I'd still argue that ofxZeroconf would better be an addon.  I could certainly imagine a new addon that aggregates ofxZeroconf and ofxOsc though.  Like ... ofxZeroconfOsc.

**Comment by kylemcdonald** [comment]
going to close this since the consensus seems to be it's better to keep it an addon. but feel free to continue the discussion :)

**Comment by 2bbb** [comment]
:+1:

**Comment by 4quet** [comment]
@bakercp I couldn't find the ofxZeroconf addon, where could I find it ?
Thanks !
