### ISSUE TITLE
ofAVFoundationPlayer Thread count leaks

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#4414]
I'm working on a project that needs to load, playback, and unload an unlimited number of videos over time. The current ofAVFoundationPlayer (OS X) creates a great number of Threads when a video is loaded / played, but it doesn't make them disappear when the video is unloaded / destroyed. This make my app reach a freeze when the thread count reaches >1024 threads... After a couple hundred videos have been played.

Digging inside the ofAVFoundationPlayer implementation, I see the assets are not released on deallocate... I don't really know what I'm doing as I lost track of Apple's video technology quite a while ago but common sense dictates to release things you are not using any more. I might be missing something and it might not be be the best order in which to release things, but this seems to fix the thread leak for me. PR coming soon.

**Comment by armadillu** [comment]
On my quick test that consists of doing:

-loading a video
-playing a video for 1 sec
-deallocating it 

2000 times, the app stays at a healthy ~30 threads now. 

But I do see memory is 1.3Gb, so there's still a leak in there somewhere.

**Comment by armadillu** [comment]
I'm also seeing some errors every now and then, but it doesn't seem to affect performance:

```
[12:10:23.148] <<<< VMC >>>> vmc2PostDecodeError: posting DecodeError (-12903) -- PTS was 0.160 = 4004/25025
````

**Comment by ofTheo** [comment]
I've seen the -12903 error as well. 
I believe it stands for kVTInvalidSessionErr  see: https://github.com/lionheart/openradar-mirror/issues/2619

**Comment by armadillu** [comment]
I'm going to leave the issue open for a while as it still leaks memory. I'll have a look when I have a bit of time.

**Comment by i-n-g-o** [comment]
@armadillu are you creating and destroying `ofAVFoundationPlayer` objects or are you loading/closing videos on the same object?
i am testing with one `ofAVFoundationPlayer` object loading/closing the same video-file. as you proposed (load, play for  one second, close)
the app is on stable on ~32 threads, i cannot see an increase in memory consumption.

**Comment by i-n-g-o** [comment]
also tested creating and destroying `ofAVFoundationPlayer` objects, but could not detect a memory-leak.
tested on 10.10.5.

doing it this (pseudo-code):
```
shared_ptr<ofAVFoundationPlayer> myMovie;

setup(){
    myMovie = shared_ptr<ofAVFoundationPlayer>(new ofAVFoundationPlayer());
    myMovie->load("mymovie.mov");
    fingerMovie->play();
}

update(){
    if (elapsedTime > 1.0) {
        myMovie = shared_ptr<ofAVFoundationPlayer>(new ofAVFoundationPlayer());
        myMovie->load("mymovie.mov");
        fingerMovie->play();
    }
}
```

@armadillu how do you get these leaks?

**Comment by armadillu** [comment]
@i-n-g-o The thread count leak was fixed with my PR. The memory leak I see happens when I load-close on the same object, without release. Maybe it's codec dependent? I was testing with an mp4... I'll try again on monday.

**Comment by urshofer** [comment]
I'm running an application which is playing short video fragments triggered over the network. It was running perfect on yosemite in an installation (http://www.urshofer.ch/Work/Stereotypes) for the ZKM.
I recently recompiled it with of master and got the same ```vmc2PostDecodeError```. 

In the Installation I used the version of @i-n-g-o (https://github.com/openframeworks/openFrameworks/commit/27b09aae8c2108cb78cd1b18140ba6ab1040a891). Probably it has something to do with the changes in the meantime? Does it help to compile it against this version of the AVFoundationPlayer? I'm using my own extension https://github.com/urshofer/ofxGaplessVideo to preload and trigger the movies. It relies heavily on the async loading process - that makes it gapless.

We did some heavy testing on the AVFoundationPlayer back then to make it work (https://github.com/openframeworks/openFrameworks/pull/3736)

**Comment by arturoc** [comment]
is this solved now?

**Comment by urshofer** [comment]
i think not: https://github.com/openframeworks/openFrameworks/issues/4485#issuecomment-155791350

**Comment by ofTheo** [comment]
Is it possible to provide really simple example code that demonstrates the leak/crash? 

The other issues I was easily able to replicate with a modified ofVideoPlayer example. 

If you can show the issue with vanilla OF ie: not using your addon, that would be super helpful!!

Many thanks!
Theo

**Comment by ofZach** [comment]
not sure if it's helpful but if you do "analyze" in xcode it says "potential leak of an object" a few places.  when you double click it gives lot more detail as well about why it sees a potential leak: 

<img width="1482" alt="screen shot 2015-11-11 at 9 29 18 pm" src="https://cloud.githubusercontent.com/assets/142897/11109138/6d3089c6-88bb-11e5-8ffe-d238bb7644a5.png">

(there's also some dead stores it identifies around OF core, and a few logic errors) 

the analyze tool isn't always helpful but sometimes it picks up on useful things like uninitialized values, etc.

**Comment by ofTheo** [comment]
Oh amazing. 
That could be super helpful!!!

**Comment by ofZach** [comment]
yeah it's pretty interesting.  I like following the arrows it draws out which help you see how it got to it's conclusion :) 

<img width="1091" alt="screen shot 2015-11-11 at 9 53 22 pm" src="https://cloud.githubusercontent.com/assets/142897/11109466/b3315344-88be-11e5-93af-2d125ffaa8e1.png">

there are some other small things it catches, we should look into....

**Comment by urshofer** [comment]
cool!
I'll give it a try...

**Comment by urshofer** [comment]
Ok. I made a small example here, w/o any dependencies on other modules

Here's the soruce on gist:

https://gist.github.com/urshofer/511c28d970085a6afd59

Here's a dropbox link for the  zipped app including 3 example movies:

https://dl.dropboxusercontent.com/u/394122/videoTest.zip

From my point of view memory consumption is not stable. It grows over time. Here are the graphs from xcode 6.4, with or without a call to ```MO.close()```before ```MO.loadAsync()```. @i-n-g-o did something change in the close/unload behavior in the recent developments ?

![bildschirmfoto 2015-11-13 um 11 22 21](https://cloud.githubusercontent.com/assets/116976/11144025/bdb31f46-89f9-11e5-9f2d-0e0d0877da4a.png)
![bildschirmfoto 2015-11-13 um 11 19 57](https://cloud.githubusercontent.com/assets/116976/11144026/bdddec08-89f9-11e5-8324-36003918324c.png)

best,
Urs

**Comment by i-n-g-o** [comment]
cool. i never used the analyze feature. that's _really_ helpful. great!
a couple of potential leaks has to be fixed.

i did a lot shortly before 0.9.0 release to fix those crashes we encountered. might be that there still are things to be done.

generally i would like to restructure this assetReader-construction.
we cannot really get rid of it, it performs more stable in playback than the `AVPlayerItemVideoOutput` but has some serious problems, where i still don't know why and how to solve it.
it might be that restructuring that bit of code solves something.

**Comment by dimitre** [comment]
I think it is now fixed
https://github.com/openframeworks/openFrameworks/pull/6791

**Comment by dimitre** [comment]
I was working in a small PR (unmerged) which improves seek performance a lot in my usage.
We already tested with H265, Prores and other different options and performance is great, encouraging to revert back from Gstreamer.
If anybody else can test this one its here:
https://github.com/openframeworks/openFrameworks/pull/6797

**Comment by dimitre** [comment]
@ofTheo I think this can be closed too
