### ISSUE TITLE
Missing definition for functions

### ISSUE THREAD

**Issue by chaosct** [openframeworks/openFrameworks#4426]
Using these functions results into a linker error, as there is no definition:

```
ofMesh  ofTexture::getMeshForSubsection(float, float, float, float, float, float, float, float, float) const;
ofVec2f& ofVec2f::getLimited(float max); // not const
```

**Comment by bilderbuchi** [comment]
are you sure? at least for the first one the definition seems to be [there](https://github.com/openframeworks/openFrameworks/blob/f5dbc24b0d2c9ecc425b749a97680647e90001b9/libs/openFrameworks/gl/ofTexture.cpp#L981), and for the second one that line of code (including th "not const" comment is [not there](https://github.com/openframeworks/openFrameworks/blob/50fd501c2bec2d2c8b89723b0b0dc06bdbfdd4e6/libs/openFrameworks/math/ofVec2f.h#L775).
Which version of OF and operating system, IDE are you using? are you getting this with current master?

**Comment by chaosct** [comment]
The first declaration is [here](https://github.com/openframeworks/openFrameworks/blob/952d894a4943eaf8c9695cd664eb0e18fd7abafa/libs/openFrameworks/gl/ofTexture.h#L667) (different from [here](https://github.com/openframeworks/openFrameworks/blob/952d894a4943eaf8c9695cd664eb0e18fd7abafa/libs/openFrameworks/gl/ofTexture.h#L652))
The second is [here](https://github.com/openframeworks/openFrameworks/blob/121290d709e1ae2364ef185ea61b051106cc65a9/libs/openFrameworks/math/ofVec2f.h#L775) (the `no const` comment was me trying to emphasize that it was different from [this one](https://github.com/openframeworks/openFrameworks/blob/121290d709e1ae2364ef185ea61b051106cc65a9/libs/openFrameworks/math/ofVec2f.h#L773)) 

This is happening on OF nightly build, OSX; but I can't find those definition on master either.

**Comment by bilderbuchi** [comment]
thank you. 
ping @arturoc @ofTheo @openframeworks/2d-3d

**Comment by arturoc** [comment]
both declarations can be removed safely, can you send a PR?
