### ISSUE TITLE
increase ofxiOS minimum iOS support to 6.0

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4431]
now that iOS 9.0 has been released,
we can safely move ofxiOS minimum iOS support to 6.0

**Comment by danoli3** [comment]
Why not go the full iOS 7 jump https://github.com/openframeworks/openFrameworks/issues/3977

Also this would prevent the million warnings for having a lib that is minimum for iOS 7 included in a build (due to minimum for arm64 architectures).

**Comment by julapy** [comment]
@danoli3 ah forgot about that issue already being opened.
i'll close this one in favour of #3977
