### ISSUE TITLE
Font example renders really strange text on iOS

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4437]
This is with the OF master and iOS 8.1 SDK - building for the simulator. 
Going to look into this - but guessing its an issue with the Freetype simulator build?

<img width="489" alt="screen shot 2015-10-15 at 8 43 50 am" src="https://cloud.githubusercontent.com/assets/144000/10506521/20bd5dce-7319-11e5-8d6e-4fac2c7bda64.png">

ping @danoli3 @julapy

**Comment by danoli3** [comment]
Woah that is weird weird. Haven't seen that one before.

What architecture was that in? If it was debug it is possible maybe i386.

**Comment by ofTheo** [comment]
That was the simulator. 
I just tried Release as well as Debug which had the same results.  
I'm building on 10.9 with the iOS 8.1 SDK 

Just tried on OS X and the example runs fine. 
I'm guessing maybe an issue with the freetype lib. 

Other graphics examples seem to look fine.

**Comment by arturoc** [comment]
That looks more like something with how the mesh to draw the fonts is created than with the texture it self. No idea what's going on but i'd look in the indices of the mesh or that the mode is not somehow set to something different than it should

Something that has happened to me quite a few times in android is that the indices in openGLES are unsigned short but in the desktop they are unisgned int and that sometimes messes up the rendering but the times it's happened to me it was related to tess2 and the tessellator, i've never seen it with any other mesh

**Comment by danoli3** [comment]
I just tried on a Device, arm64, arvm7 same happening on both.

This definitely was not happening when we updated the libraries to 3.17.0
Something else has changed.

**Comment by danoli3** [comment]
I'm going to try and isolate the PR that broke it.

- [x] August 31st (23d15ea5ca110e4b117d129c8c76bcc561451d25) - All is Fine. Font Example is perfect. Not lib related.
- [x] September 7th (6ee40f6a996095d14de849d04cd7bab2674d7ec4) - Fine

**Comment by danoli3** [comment]
Ah got it!!! Wow this was amazing timing @ofTheo, this literally happened only 2 days ago!
blame: f5dbc24b0d2c9ecc425b749a97680647e90001b9

tess2 header lost it's preprocessors.

**Comment by ofTheo** [comment]
ha - lucky indeed! :) 
I was downloading the nightly to help out on someone else unrelated issue and randomly picked the font example to test compiling ofxiOS
