### ISSUE TITLE
Sanity fix : Comment out annoying pragma message in boost

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4443]
this line:
https://github.com/openframeworks/openFrameworks/blob/master/libs/boost/include/boost/config/compiler/visualc.hpp#L292

on VS2015
complains to the compiler output once for every cpp file which includes it
which is everything

i presume we need to update boost, but for the time being i'd recommend commenting out this line

**Comment by arturoc** [comment]
i commented this out a while ago but it seems not in apothecary and some recompile has bring it back. if you can send a PR?
