### ISSUE TITLE
SoundOutputStream issue on iOS - Doubling include of ofxiOS in project

### ISSUE THREAD

**Issue by chrisoshea** [openframeworks/openFrameworks#4446]
I'm attempting to build for iOS but get this build error using the latest version from github:

/addons/ofxiOS/src/sound/SoundOutputStream.m:111:24: Non-constant-expression cannot be narrowed from type 'NSInteger' (aka 'int') to 'Float64' (aka 'double') in initializer list

/addons/ofxiOS/src/sound/SoundOutputStream.m:115:24: Non-constant-expression cannot be narrowed from type 'NSInteger' (aka 'int') to 'UInt32' (aka 'unsigned long') in initializer list

Thanks

![screen shot 2015-10-17 at 14 53 16](https://cloud.githubusercontent.com/assets/104786/10559093/811b52f8-74df-11e5-86f6-2aaa54412351.png)

**Comment by danoli3** [comment]
What OSX Version do you have?

**Comment by chrisoshea** [comment]
@danoli3 10.10.5

**Comment by danoli3** [comment]
What is the suggested change from Xcode?
Can you make that change and PR.

I am not getting this error at all

**Comment by danoli3** [comment]
Oh what is your minimum iOS Target?!

**Comment by chrisoshea** [comment]
So build errors:
![screen shot 2015-10-17 at 16 45 58](https://cloud.githubusercontent.com/assets/104786/10559675/cd120972-74ee-11e5-8ffa-7b6aeec588fb.png)

changes suggested by xcode (auto inserted)
![screen shot 2015-10-17 at 16 46 58](https://cloud.githubusercontent.com/assets/104786/10559676/cd12a5f8-74ee-11e5-9c4a-f1bd4fa8ceeb.png)

then after those errors still get:
![screen shot 2015-10-17 at 16 45 20](https://cloud.githubusercontent.com/assets/104786/10559674/cd107c56-74ee-11e5-9414-424eca710579.png)

Thanks

**Comment by danoli3** [comment]
Looks good! Do you know how to Pull Request?

**Comment by chrisoshea** [comment]
Minimum iOS 7. It hasn't solved it though, I still get a load of errors (see third screenshot)

**Comment by danoli3** [comment]
Ah Minimum iOS 7. Yeah that is why. If you change your project to minimum 5.1 for for now. It should completely go away.

**Comment by danoli3** [comment]
iOS 7.0 support coming after 0.9 release.

**Comment by chrisoshea** [comment]
Ah tell a lie, its set to 5.1.1 however you can't actually select 5.1.1 in the xcode dropdown, the oldest you can support is 6.0

**Comment by danoli3** [comment]
Does the error go away at MIN 6.0?

**Comment by chrisoshea** [comment]
Sadly no...
![screen shot 2015-10-17 at 17 11 22](https://cloud.githubusercontent.com/assets/104786/10559913/4b8fe492-74f2-11e5-95b8-38484cf9ddb5.png)

![screen shot 2015-10-17 at 17 12 27](https://cloud.githubusercontent.com/assets/104786/10559915/50022e04-74f2-11e5-8c82-b7c3a7afb666.png)

**Comment by danoli3** [comment]
Ah revert your made changes to the files (from Xcode).
It's complaining about not being about to static_cast< in a Objective-C class. There is no static_cast in Objective-C (defined like that).

**Comment by chrisoshea** [comment]
Yes I tried it with the changes made by xcode (2nd image) and reverted back to the OF download version (first screenshot). Neither works.

Any idea what this bit of code should be like then?

Thanks :)

**Comment by danoli3** [comment]
Would you mind uploading the project to a zip or to github and I'll try it out?
Something sounds broke

**Comment by danoli3** [comment]
Did you use the project Generator to build your project?

**Comment by chrisoshea** [comment]
Sorry I can't upload this one. Yep used the project generator. Is that a bad thing? Thanks

**Comment by danoli3** [comment]
When new project created from projectGenereator for iOS and you have checked ofxiOS addon from then give error on build. Just don't include any 'native' addons when new iOS project from PG created.

I.E. Do not select: ofxiOS, ofxAccelerometer and ofxMultiTouch addons

**Comment by chrisoshea** [comment]
Does the project generator work, or should I just copy emptyExample?

so for iOS projects I shouldn't include ofxiOS in the project generator? thanks

**Comment by admsyn** [comment]
This looks a lot like the issue described in #4307, which I was able to reproduce by manually adding an unnecessary copy of ofxiOS to the project. I have no idea why it seems to cause it but there you go.

**Comment by danoli3** [comment]
Potentially project generator fix here:
https://github.com/openframeworks/openFrameworks/pull/4445
