### ISSUE TITLE
Qt Creator error - MacOSX

### ISSUE THREAD

**Issue by varoudis** [openframeworks/openFrameworks#4465]
Hi @arturoc, thank for the qtcreator commits!
Please see attached image for error.

![screenshot 2015-10-23 11 32 32](https://cloud.githubusercontent.com/assets/567895/10690561/ad48b5a6-797a-11e5-8cd7-12bec97e0221.png)

"/Users/varoudis/Dropbox/Git/openFrameworks/libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs:483: error: ReferenceError: Can't find variable: of"

Darwin 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

10.10.1 with 7.1 Xcode latest updates (MacPro tube, 12core 64gb)

**Comment by arturoc** [comment]
what version of qtcreator are you using? i changed that a couple of days ago cause it wasn't working with the latest version 3.5.1  if you are using an older version and don't want to update you can change it to:

```
files: ADDONS_SOURCES
```

**Comment by varoudis** [comment]
you are correct, my Qt setup was a bit outdated!
last error corrected. got something else though!

![screenshot 2015-10-23 12 03 16](https://cloud.githubusercontent.com/assets/567895/10691065/21d9b7e6-797e-11e5-96f9-7f2ba6bd5065.png)

**Comment by arturoc** [comment]
this is a problem with todays nightlies i just fixed it some minutes ago in master, you can get the openFrameworksCompiled/projects/qtcreator folder from git and copy it in the nightly build, otherwise it'll be fixed tomorrow

**Comment by varoudis** [comment]
thanks a lot, I truck the master so Ill pull it.

Tasos
