### ISSUE TITLE
ofxButton: Segmentation fault during destruction

### ISSUE THREAD

**Issue by lilive** [openframeworks/openFrameworks#4466]
Hi,
I've got a segmentation fault when an ofxButton is destroyed when the app exit.
This problem appeared at some state of my application development, don't know why, I was using many ofxButtons in the app before without problem.
I tried to debug: I saw the ofxButton destructor call, the ofxToggle destructor call, the ofVboMesh destructor call, the ofVbo destructor call, the ofMesh destructor call, I saw a std::vector destruction, and my debugger stop during this vector destruction (I guess. I'm not very experimented with the debugger, and the std code is hard to read for me. Say that the last line of code I can read when executing step by step is a line in the std library)

![call-stack](https://cloud.githubusercontent.com/assets/2719976/10703978/e795dfaa-79d3-11e5-9576-e3dad54c56fe.jpg)

I don't know how I can help more.

OF 0.8.4 / Windows 7 / Code::blocks 12.11

**Comment by arturoc** [comment]
i think this is just a problem in the destruction order in your application probably trying to destroy something that has been deleted already or something like that, i'm going to close this issue but please post or reopen again if you can post a simple example that demoes the problem

**Comment by lilive** [comment]
OK. Thank you arturoc.
For now all my debugging attempts failed, but you give me a clue to investigate again. I let you know if I find something that is not due to a mine mistake.
