### ISSUE TITLE
OS X and Qt Creator: run built app cannot find libfmodex.dylib

### ISSUE THREAD

**Issue by Meach** [openframeworks/openFrameworks#4479]
Hello,

I just tried OF 0.9 RC2 on mac, using Qt Creator.
All is fine, I can build and run an empty app with some addons inside Qt Creator.

The problem happen when I go to my app/bin folder and double click on the .app file to launch it.
I get a error and looking at the report, I see this message:

```
Dyld Error Message:
  Library not loaded: ./libfmodex.dylib
  Referenced from: /Users/USER/Documents/*/testQt_debug.app/Contents/MacOS/testQt_debug
  Reason: image not found
```

But looking at the app content, I can see that libfmodex.dylib is testQt_debug.app/Contents/MacOS

Did I miss anything?

**Comment by ofZach** [comment]
It might be useful to look at the dylibs it's trying to load and figure out if the paths are wrong?

I think "otool -L" against the binary name  (ie, /Users/USER/Documents/*/testQt_debug.app/Contents/MacOS/testQt_debug)  woulf give you info

for example, calling this against an xcode compiled app, I see the following: 

	@executable_path/libfmodex.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1347.57.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
	/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.8.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.10.0)
	/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1153.20.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

my intuition is that we might need a post build step that changes this dylib path, for example, we do this in the xcode projects: 

```install_name_tool -change ./libfmodex.dylib @executable_path/libfmodex.dylib "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/$PRODUCT_NAME";```

so that they are relative to the executable path and not a hard coded path (which would mean the app stops working when you move it from one location on your hard drive to another). 

if you want to investigate what's happening on the xcode side, it's in the "build phases" panel 

<img width="1180" alt="screen shot 2015-10-26 at 8 11 39 am" src="https://cloud.githubusercontent.com/assets/142897/10729704/4033d2c0-7bb9-11e5-92c5-df86ec8ceefa.png">


PS: lotta info about dylibs and paths here https://blogs.oracle.com/dipol/entry/dynamic_libraries_rpath_and_mac

**Comment by Meach** [comment]
Here is the output of otool:

```
otool -L testQt_debug 
testQt_debug:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1343.14.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
	/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1151.16.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.8.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.10.0)
	./libfmodex.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1151.16.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

I will try to look at Qt if it is possible to add similar script as in Xcode.

**Comment by Meach** [comment]
@ofZach you were right, going to "testQt_debug.app/Contents/MacOS/" and running the following fixed the path and the app is able to run correctly.

```
install_name_tool -change ./libfmodex.dylib @executable_path/libfmodex.dylib testQt_debug
```

I tried to look in Qt Creator if there is a way to have this included and I found this in of_v0.9.0RC2_osx_release/libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs:

```
    // Copy osx dylibs into bundle and run install_name_tool on the binary
    Transformer {
        condition: qbs.targetOS.contains("osx")
        Artifact {
            filePath: FileInfo.joinPaths(parent.destinationDirectory, parent.targetName + ".app", "Contents/MacOS/libfmodex.dylib")
            fileTags: "preprocessed_file"
        }
        prepare: {
            var cpLibsCmd = new JavaScriptCommand();
            cpLibsCmd.description = "copying dynamic libraries";
            cpLibsCmd.silent = false;
            cpLibsCmd.highlight = 'filegen';
            cpLibsCmd.sourceCode = function(){
                var exportDir;
                if(FileInfo.isAbsolutePath(project.of_root)){
                    exportDir = Helpers.normalize(FileInfo.joinPaths(project.of_root, "libs/fmodex/lib", product.platform));
                }else{
                    exportDir = Helpers.normalize(FileInfo.joinPaths(project.path, project.of_root, "libs/fmodex/lib", product.platform));
                }

                File.copy(FileInfo.joinPaths(exportDir,"libfmodex.dylib"), FileInfo.joinPaths(product.destinationDirectory, product.targetName + ".app", "Contents/MacOS/libfmodex.dylib"));
            }
            return [cpLibsCmd];

        }
    }
```

But I am not sure that install_name_tool is actually run on the binary.

**Comment by ofZach** [comment]
I don't know anything about qbs :)    pinging @arturoc 

if that command doesn't seem to work, maybe there's a way to run a post build script similar to what you did that works?

**Comment by arturoc** [comment]
looking about this while porting it to work on qbs i read that using install_name_tool is a bad idea and that it's a much better practive to use rpath and installNamePrefix settings on the compiler which are set in lines 470 and 471 in of.qbs as:

```
        cpp.installNamePrefix: "@rpath"
        cpp.rpath: "@executable_path/"
```

but not sure why it's only working from inside the IDE

**Comment by Meach** [comment]
@arturoc, I am total newbie with Qt but if there is anything I can do to help, let me know.
