### ISSUE TITLE
ofxOpenCv Error 

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#4481]
When compiling the opencvExample on OSX in 10.8 in 09RC2, the following error occurs
`dyld: Symbol not found: ___sincos_stret
  Referenced from: /Applications/OpenFrameworks/of_v0.9.0RC2_osx_release/examples/addons/opencvExample/bin/opencvExampleDebug.app/Contents/MacOS/opencvExampleDebug
  Expected in: /usr/lib/libSystem.B.dylib`

This error can be remedied by building the opencv lib against the 10.8 SDK by modifying the apothecary script and adding:
`-DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \`

**Comment by NickHardeman** [comment]
Related to: https://github.com/openframeworks/openFrameworks/issues/4412

**Comment by arturoc** [comment]
can you also send the recompiled libraries for opencv? we've tried to recompile them with this flags before in osx > 10.8 and it didn't work i think you really need to recompile it in a 10.8 machine which only a few people still have around

**Comment by NickHardeman** [comment]
Yes. I have openCv and assimp recompiled, but can't seem to get the cairo apothecary script to work. Any suggestions? Keep getting this error:
`/Applications/OpenFrameworks/of_v0.9.0RC2_osx_release/scripts/apothecary/apothecary: line 68: /Applications/OpenFrameworks/of_v0.9.0RC2_osx_release/scripts/ostype.sh: No such file or directory
/Applications/OpenFrameworks/of_v0.9.0RC2_osx_release/scripts/apothecary/apothecary: line 934: XS: unbound variable`

**Comment by ofTheo** [comment]
I think the issue might be here:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/apothecary/apothecary#L901

When it runs the apothecary script again for each dependency its path for APOTHECARY_DIR is incorrect 

This is what the value is when it starts:
```
 START - APOTHECARY_DIR is now openFrameworks/scripts/apothecary 
```

This is called from when the dependency is run as a separate script 
```
 depend is pkg-config 
 START - APOTHECARY_DIR is now openFrameworks/scripts/apothecary/build 
```

**Comment by ofTheo** [comment]
Okay this is definitely the issue:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/apothecary/apothecary#L901

On downloading this needs to be:
```
pushd ..
```
On preparing it needs to be 

```
pushd .../...
```

I think I have a fix which avoids doing ../.. but uses the absolute paths

**Comment by ofTheo** [comment]
Okay with the modifications below it works now for cairo. 
Going to do a bit more testing then submit a PR

```
function apothecaryDependencies() {
	if [ ${#FORMULA_DEPENDS[@]} -gt 0 ] ; then
		for depend in "${FORMULA_DEPENDS[@]}" ; do
            echo " depend is $depend "

            #store where we are
            CUR_DIR=$(pwd)

            #change back to APOTHECARY_DIR to run new script
            cd $APOTHECARY_DIR
            apothecaryDepend $1 $depend

            #restore dir to where we are
            cd $CUR_DIR
		done

        #also have to cd back to the APOTHECARY_DIR for the next commands to work
        cd $APOTHECARY_DIR
	fi
}
```
