### ISSUE TITLE
videoPlayerExample

### ISSUE THREAD

**Issue by livingbeams** [openframeworks/openFrameworks#4484]
With of_v0.9.0RC2_vs_release + VS 2015 (same issue wint Windows 8.1 and Windows 10)
With debug/relase win32 I get "unable to call getConnectedMediaType"
With debug/relase x64 I get "Error occured while playing or pausing or opening the file"

**Comment by arturoc** [comment]
you probably need to instal the codecs.

@ofTheo @DomAmato can you add a comment to this page explaining which are the codecs to install:

https://github.com/openframeworks/ofSite/blob/master/setup/vs/index.html.mako

**Comment by ofTheo** [comment]
closed by https://github.com/openframeworks/ofSite/commit/b1ad6ee1e0f08c0746262e14cfffc56e0b3eb19e

**Comment by arturoc** [comment]
thanks, i pointed you to the wrong branch, it should have been in 0.9.0 instead of master. i've just cherry picked the change and reverted on master

**Comment by ofTheo** [comment]
I'm going to add a link to a safe way to get the K-Lite codecs. 
Trying on a PC there is so much adware that is trying to get bundled with the codecs even from the official site. 

This service removes all adware before downloading the codecs: 
https://ninite.com/klitecodecs/

Going to add that to the documentation. 
Going forward it would be great to look at Media Foundation as a lot of the current codec packs don't support DirectShow anymore.

**Comment by bakercp** [comment]
+1 for a clean klitecodecs link.

**Comment by livingbeams** [comment]
Thank you for the clean download link!

**Comment by edap** [comment]
I have downloaded and installed the K-lite codec version, but on Windows, the videoPlayer example is still broken with the error "unable to call getConnectedMediaType" in both release, 32 or 64.
