### ISSUE TITLE
Windows 10 Qt Creator 0.9.0 RC2 Build Fails on includes

### ISSUE THREAD

**Issue by JordanParsons** [openframeworks/openFrameworks#4491]
I pulled the latest RC2 to start testing in Qt creator on my Windows 10 machine. The install process worked as expected but the makefile gave the following error:
```
of_v0.9.0RC2_win_cb_release\libs\openFrameworksCompiled\project\makefileCommon\config.shared.mk:97:
*** This makefile does not support your operating system.  Stop.
```
In the MYSYS2 terminal uname reports the following:
```
uname -s
MINGW64_NT-10.0

uname -m
x86_64
```

**System Info:**
- Qt Creator 3.5.1 (opensource)
- Based on Qt 5.5.1 (MSVC 2013, 32 bit)
 - Compiler GCC from C:\msys64\mingw32\bin\gcc.exe
 - Desktop Kit using GCC with default settings.
- Windows 10.0.10240 64bit
- OF 0.9.0RC2

I then overrode the makefile with the code inserted at line 60 of config.shared.mk
```
ifeq ($(OS),Windows_NT)
    #Windows override
    PLATFORM_OS = MINGW64_NT
endif
```

That let the build process start. Then it misses *"glu.h" on line 101 in ofConstants.h*, changing that line to *"GL/glu.h"* allows the build to continue. Then it misses *"tesselator.h" at line 234*. Changing that to *"#include "../tess2/include/tesselator.h""* allows it to continue. The build then just reports:   "error: Process failed with exit code 2."

This is as far as I have gotten in the process. Is anyone else using Windows 10?

**Comment by kylemcdonald** [comment]
i know there were some changes since RC2 for msys/windows:

https://github.com/openframeworks/openFrameworks/commits/master?author=oxillo

did you see this too, @oxillo?

you could you try downloading a nightly and see if it's fixed already:

http://198.61.170.130/versions/nightly/

**Comment by oxillo** [comment]
@JordanParsons
I also work on Windows 10 but I haven't tried Qt Creator yet...
From the 'uname -s', it seems that you are trying to compile in 64bits (MINGW64). It is not supported actually (not even in the nightlies)
Try using MINGW32 shell and tell us if it solves the problem.

I've started a PR #4475 for MSYS2 documentation. Do not hesitate to contribute.

**Comment by bilderbuchi** [comment]
are we officially already supporting QtCreator for 0.9.0? I thought that still was in testing. @arturoc ?

**Comment by arturoc** [comment]
@bilderbuchi qtcreator is the official IDE for 0.9.0 in linux and windows mingw, here's the RC web with the new setup guides and downloads: http://openframeworks.cc/0.9.0/download

i'm still deciding on osx, if it's too problematic i might drop it as official even if it works with some quirks

@JordanParsons have you installed the install_dependencies script? you can follow the guide oxillo wrote to install msys2 and then the official guide for qtcreator in the web, i'll merge or link from one another later

**Comment by bilderbuchi** [comment]
alright. @openframeworks/openframeworks-devs, just FYI there is a new issue label "qtcreator" now to use for issues connected with Qt Creator.

**Comment by hluisi** [comment]
I'm having the same issue.  For some reason uname isn't working when using QtCreator. 

```
01:25:14: Running steps for project 3DPrimitivesExample...
building openFrameworks library
compiling main.cpp
compiling ofApp.cpp
c:/msys64/usr/bin/make.exe Debug -j4
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
make: uname: Command not found
makefileCommon/config.shared.mk:97: *** This makefile does not support your operating system.  Stop.
HOST_OS=
HOST_ARCH=
PLATFORM_ARCH=
PLATFORM_OS=
CROSS_COMPILING=0
Process failed with exit code 2.
The following products could not be built for configuration qtc_Desktop__3672d0e5-debug:
	3DPrimitivesExample
	openFrameworks
Error while building/deploying project 3DPrimitivesExample (kit: Desktop Qt 5.5.1 Clang 32bit)
When executing step "Qbs Build"
01:25:17: Elapsed time: 00:03.
```

**Comment by arturoc** [comment]
i think you are just missing setting the path, that step is missing in the qt creator guide, can you follow the steps in oxillo's guide in https://github.com/openframeworks/openFrameworks/pull/4475

**Comment by hluisi** [comment]
Path is set
```
Hunter@Dev MINGW32 ~
$ echo $PATH
/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/mingw32/bin:/home/Hunter/of_v0.9.0RC2/export/win_cb: ...
```

**Comment by arturoc** [comment]
how have you set it?

**Comment by arturoc** [comment]
you have to set the path in the windows properties not in msys otherwise applications won't get the same path

**Comment by hluisi** [comment]
Window System Properties->Environment Variables->System variables->Path
```
C:\msys64\mingw32\bin;C:\msys64\home\Hunter\of_v0.9.0RC2\export\win_cb; ...
```
right in the front like the guide said :)

**Comment by oxillo** [comment]
@hluisi 
could you try adding c:\msys64\usr\bin to your PATH ? uname.exe stands in \usr\bin and your PATH doesn't seem to include it. 
If it works, I'll add it to the documentation.

**Comment by JordanParsons** [comment]
@arturoc I did run the install dependencies script in both the 32bit and 64bit MINGW shell. I did not see @oxillo 's updates to the guide, with setting up msys2 

@oxillo I was using the 64it console, I didn't realize it wasn't supported. I am able to get openframeworks to compile by running make from the MINGW32 shell, but it would not build from inside of Qt Creator.

So the current status on my end is that using the mingw32 shell I can build and run openframeworks RC2, (haven't tried the nightly yet) by running make run. Advanced3Dexample builds and launches. Building inside of Qt Creator it gives the same error and will not launch, even with C:\msys64\mingw32\bin; added to the system path. I am going to uninstall everything following @oxillo 's guide for mysys64 on the nightly and see if that works.

**Comment by hluisi** [comment]
@oxillo adding "C:\msys64\usr\bin" to the PATH fixed the uname issue, but now I'm getting other errors.  Before I post them I'm going to do a fresh install of everything to double check it wasn't something I did

**Comment by JordanParsons** [comment]
@oxillo following your guide in #4470 worked from scratch to build the latest Master branch from the mingw32 shell. Setting up QtCreator still does not work.

I first followed the guide from #4470, then the guide from http://openframeworks.cc/0.9.0/download to setup Qt Creator.
Adding *C:\msys64\mingw32\bin* to my system path allowed Qt to auto-detect *C:\msys64\mingw32\bin\g++.exe* Adding that compiler to the desktop kit produces the same failure case. Adding my own compiler that pointed to *C:\msys64\mingw32\bin\gcc.exe* to the desktop kit allowed it to build with 27228 errors.

I realized halfway through that I also didn't have *"C:\msys64\usr\bin"* added to my path. @hluisi I think I'm around the same step as you. I'm going to clean everything and try again with *"C:\msys64\usr\bin; C:\msys64\mingw32\bin;"* added to my path.

**Comment by hluisi** [comment]
Ok everything is working now... It looks like adding "c:\msys64\usr\bin" to the path did the trick.

@JordanParsons you need to use g++.  Qt Creator should have auto-detected it. Check "Build & Run"->Compilers and look for "MinGW (x86 32bit in C:\msys64\mingw32\bin)" and make sure the compiler path points to g++ ("C:\msys64\mingw32\bin\g++.exe").  If it's not there or it points to gcc you'll need to add/change it.  Then goto Kits and make sure it's using the right compiler. 

**Also please note that the Qt install guide says to use gcc in the windows section

**Comment by oxillo** [comment]
I've updated the documentation to add the \usr\bin ... 
I also added a screenshot of my QtCreator settings. However, it's in french... so I welcome a volunteer to commit an english version.

**Comment by bilderbuchi** [comment]
@JordanParsons is everything cleared up/fixed now?

**Comment by JordanParsons** [comment]
@bilderbuchi Yep, I did a clean clone, and was able to rebuild inside of Qt Creator. Thanks a lot everyone.

**Comment by bilderbuchi** [comment]
thanks!
