### ISSUE TITLE
examples crash (segfault) on exit on MSYS2

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#4499]
I've build nearly all examples on MSYS2. The following ones crash on exit (Esc or close) : 3dCameraLensOffsetExample,addons/VectorGraphicsExample, gl/shaderExample, graphics/fontShapesExample, graphics/pdfExample, gui/guiExample, gui/guiFromParametersExample, gui/oscParametersReceiver, gui/oscParametersSender, gui/parameterGroupExample, math/noise1dOctaveExample, math/trigonometryExample.
I've tracked it down to the line : 

    if(!initialized()) return;
in `ofExitCallback` in `ofAppRunner.cpp`.

This line crash when ofExitCallback is called a second time...
Does the problem comes from calling ofExitCallback twice or from the initialized() call ?

**Comment by oxillo** [comment]
Finally, it doesn't seem to come from ofExitCallback.
gdb is giving me some 

    Program received signal SIGSEGV, Segmentation fault.
    0x004daf19 in deleteBucketAlloc ()

**Comment by bilderbuchi** [comment]
ping @arturoc @openframeworks/windows
