### ISSUE TITLE
Android: Camera updates very slowly

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#4502]
Running the android camera example on a Nexus 6, gives me a really slow refresh rate of the camera. The app is running ~60fps, but the camera is only running around 10fps. 

I can see that the current camera implementation is using the deprecated `android.hardware.Camera` module instead of the new `android.hardware.camera2`. Would it make sense to update this? 

There is some example code of using it here made by google creative lab in their shadercam example: https://github.com/googlecreativelab/shadercam/blob/master/shadercam/src/main/java/com/androidexperiments/shadercam/fragments/CameraFragment.java

**Comment by arturoc** [comment]
i haven't looked into it in a while but yes i've seen there's some deprecated functions would be great to get the new camera working.

**Comment by HalfdanJ** [comment]
Camera2 api requires API level 21, so its out of scope at the moment. But i'm going to look into getting better performance from the old version on modern phones.
