### ISSUE TITLE
Mac OSx Link error

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#4504]
I'm writing an application that works smoothly with OF 0.9 RC1. Today I've imported it in the latest nightly build and I've the following error.
![lin_error](https://cloud.githubusercontent.com/assets/161152/10862898/f631692e-7fbb-11e5-82d3-e73b1ded32ca.png)

I've thought that probably something went bad during the importing, so I've created a new project with the project generator used in the latest nightly, I've added the addon that is needed and I've imported the files through "add files", adding them to the target of the current project, but the error is the same.

**Comment by ofZach** [comment]
can you post more of the error log like what are the duplicate symbols it found?   thanks!

**Comment by edap** [comment]
Sure, the stacktrace was too big, I've to cut it in 2

![error1](https://cloud.githubusercontent.com/assets/161152/10863948/767948ec-7fdd-11e5-8811-dc3a0d9b0b18.png)


![error2](https://cloud.githubusercontent.com/assets/161152/10863935/152b853c-7fdd-11e5-8e2e-16fac0ad52bd.png)

**Comment by ofZach** [comment]
can you try cleaning and rebuilding?  Can you check if there's duplicate files in your sidebar (like ofApp included twice?)

**Comment by ofZach** [comment]
oh it looks like one of your addons has examples in there -- can you check ofxDatGui and see if the examples were added to the sidebar?

**Comment by edap** [comment]
I've cleaned (Product -> clean) and rebuild, but the error persists. ofApp is include only once
![sidebar](https://cloud.githubusercontent.com/assets/161152/10864107/eddc0bae-7fe2-11e5-8c1c-fd8b6b3aae87.png)
The addon contains examples, yes. Should I remove them?

**Comment by ofTheo** [comment]
@edap yes! :) 
there are multiple ofApp.cpp files in each example. hence the linking errors.

**Comment by edap** [comment]
cool, thank you.
