### ISSUE TITLE
Android: AndroidVideoGrabber/Camera cleanup

### ISSUE THREAD

**Issue by danthemellowman** [openframeworks/openFrameworks#4512]
I spent the day working with ofxAndroid and the ofxAndroidVideoGrabber fixing some regressions and bugs I've found.  I need to push everything to a branch and clean up most of the code but the main fixes include:

- Implementing void ofVideoGrabber::close()
- Implementing void ofVideoGrabber::setDeviceID(int id)
- ofPixels & ofVideoGrabber::getPixels() actually returns pixels

These fixes allow you to switch between the front and rear facing camera in your ofxAndroid app with a button press.

**Comment by kylemcdonald** [comment]
could you compare this to #4510 ?

**Comment by danthemellowman** [comment]
Yeah we are talking. I didn't see it.

**Comment by danthemellowman** [comment]
closed because of #4510
