### ISSUE TITLE
Travis NDK url wrong

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#4514]
@arturoc the url to the NDK is wrong (failing on my own travis instance https://travis-ci.org/HalfdanJ/openFrameworks/jobs/88752464). The file ending is wrong in the url to our own local version. But fixing the url is not enough, travis is failing with 

```
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Running the same commands on my own computer works fine, so not sure why it happens.

**Comment by arturoc** [comment]
oh, ok i think we were using bz2 before and i compressed it using gz instead somedays ago, let me recompress it

**Comment by arturoc** [comment]
i think it's fixed now but let me know if it's still a problem
