### ISSUE TITLE
Issues Compilling on Ubuntu 15.10

### ISSUE THREAD

**Issue by cjdg** [openframeworks/openFrameworks#4522]
Im having issues compilling of 0.8.3 on ubuntu 15.10

**Comment by bakercp** [comment]
First, 0.8.3 is quite out of date.  Second please read this section on how to report issues https://github.com/openframeworks/openFrameworks/blob/master/CONTRIBUTING.md#report-a-bug. The information provided is not sufficient to offer a helpful reply.
