### ISSUE TITLE
ofMouseEventArgs inconsistent for scrolling event

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#4523]
All mouse events appear to consistently set `x` and `y` of `ofMouseEventArgs` to the current mouse cursor position.

When capturing a scrolling event, however, `x` and `y` represent the scrolling offset. When using a unique responder to mouse events, similar to what #2176 is suggesting, this means two extra global calls to `ofGetMouse[XY]`, which seems far from elegant. 

Wouldn't it be nice (and less surprising) to have the scroll xy-offset (which appears to be a float rather than an int anyway) in its own member variable of `ofMouseEventArgs`?

With a slight change to `ofBaseApp.h#L107` (to forward the new scroll offset rather than the mouse pos) the current beginner-friendly API for mouse scroll events could be kept, while more advanced users might profit from being able to tell where on screen the scroll event has occured.

**Comment by arturoc** [comment]
can you send a PR? this was introduced during the 0.9 release cycle so if we fix it now we won't have to break the API later

**Comment by tgfrerer** [comment]
Sure thing! gimme 5 mins.
