### ISSUE TITLE
of 8.4 cant compile apps in ubuntu 15.10

### ISSUE THREAD

**Issue by cjdg** [openframeworks/openFrameworks#4532]
I updated to last ubuntu (15.10) and now nothing is compiling on my equipment

here is what i got

checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Compiling OF library for Release
make[1]: Entering directory '/home/cjdg/tools/frameworks/of_v0.8.4_linux64_release/libs/openFrameworksCompiled/project'
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
make[2]: Nothing to be done for 'ReleaseABI'.
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Done!
make[1]: Leaving directory '/home/cjdg/tools/frameworks/of_v0.8.4_linux64_release/libs/openFrameworksCompiled/project'

Compiling projectGeneratorSimple for Release
make[1]: Entering directory '/home/cjdg/tools/frameworks/of_v0.8.4_linux64_release/apps/projectGenerator/projectGeneratorSimple'
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Compiling src/main.cpp
g++ -c -O3 -Wall -march=native -mtune=native -DOF_USING_GTK -DOF_USING_GTK -DOF_USING_MPG123 -Isrc -Isrc/utils -Isrc/addons -Isrc/pugixmlLib -Isrc/pugixmlLib/scripts -Isrc/pugixmlLib/scripts/pugixml.xcodeproj -Isrc/pugixmlLib/src -Isrc/pugixmlLib/lib -Isrc/pugixmlLib/contrib -Isrc/projects -I./src -I./src/utils -I./src/addons -I./src/pugixmlLib -I./src/pugixmlLib/scripts -I./src/pugixmlLib/src -I./src/pugixmlLib/lib -I./src/pugixmlLib/contrib -I./src/projects -I../../../addons/ofxGui/src -I../../../addons/ofxXmlSettings/src -I../../../addons/ofxXmlSettings/libs -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include -I/usr/include/AL -I/usr/include/alsa -I/usr/include/GL -I/usr/include/libdrm -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../libs/fmodex/include -I../../../libs/glfw/include -I../../../libs/glfw/include/GLFW -I../../../libs/kiss/include -I../../../libs/openssl/include -I../../../libs/openssl/include/openssl -I../../../libs/poco/include -I../../../libs/rtAudio/include -I../../../libs/tess2/include -I../../../libs/openFrameworks -I../../../libs/openFrameworks/graphics -I../../../libs/openFrameworks/utils -I../../../libs/openFrameworks/sound -I../../../libs/openFrameworks/events -I../../../libs/openFrameworks/communication -I../../../libs/openFrameworks/3d -I../../../libs/openFrameworks/video -I../../../libs/openFrameworks/math -I../../../libs/openFrameworks/gl -I../../../libs/openFrameworks/app -I../../../libs/openFrameworks/types  -MMD -MP -MF obj/linux64/Release/src/main.d -MT obj/linux64/Release/src/main.o -o obj/linux64/Release/src/main.o -c src/main.cpp
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:191: recipe for target 'obj/linux64/Release/src/main.o' failed
make[1]: Leaving directory '/home/cjdg/tools/frameworks/of_v0.8.4_linux64_release/apps/projectGenerator/projectGeneratorSimple'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
there has been a problem compiling the projectGenerator
please report this problem in the forums

**Comment by arturoc** [comment]
hi, not sure what this error is but OF 0.8.4 won't be compatible with ubuntu 15.10. in ubuntu 15.10 there's been a change to gcc5 which is not compatible with libraries compiled for gcc4 so unless you recompiled the libraries  that come with OF it won't work.

you can use the nightly builds or download the latest release cnadidate from:

http://openframeworks.cc/0.9.0/download

be sure to run the new install_dependencies script

**Comment by arturoc** [comment]
i'm closing the issue but post here if you have any other doubt.

**Comment by alessandro-zomparelli** [comment]
Hi, I have a similar problem (I suppose):
`
make: Entering directory '/home/alessandro/.of/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Compiling OF library for Release
make[1]: Entering directory '/home/alessandro/.of/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Done!
make[1]: Leaving directory '/home/alessandro/.of/libs/openFrameworksCompiled/project'


Compiling projectGenerator for Release
make[1]: Entering directory '/home/alessandro/.of/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
cat: obj/linux64/Release/.compiler_flags: No such file or directory
Linking bin/projectGenerator for linux64
g++ -o bin/projectGenerator    /home/alessandro/.of/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections   /home/alessandro/.of/libs/poco/lib/linux64/libPocoNetSSL.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoNet.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoCrypto.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoUtil.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoJSON.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoXML.a /home/alessandro/.of/libs/poco/lib/linux64/libPocoFoundation.a  -L/usr/lib/x86_64-linux-gnu -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lpulse-simple -lpulse -lasound -lGLEW -lGLU -lGL -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123  -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -ldl -lpthread -lfreeimage -lrtaudio -lboost_filesystem -lboost_system
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
/build/buildd/glibc-2.21/csu/../sysdeps/x86_64/start.S:114: undefined reference to `main'
collect2: error: ld returned 1 exit status
/home/alessandro/.of/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:381: recipe for target 'bin/projectGenerator' failed
make[1]: *** [bin/projectGenerator] Error 1
make[1]: Leaving directory '/home/alessandro/.of/apps/projectGenerator/commandLine'
/home/alessandro/.of/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: *** [Release] Error 2
make: Leaving directory '/home/alessandro/.of/apps/projectGenerator/commandLine'
There has been a problem compiling the command line projectGenerator.
Please report this problem in the forums.
`

I tried also with the latest nightly build: of_v20160201_linux64_release

any suggestion?
thank you in advice

cheers
