### ISSUE TITLE
androidSwipeExample wont compile (using gradle)

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#4539]
Cant get the android sample `androidSwipeExample` to compile. It's not giving any errors, just freezing while compiling ofApp.cpp... If i remove the line `ofRegisterTouchEvents((ofxAndroidApp*)this);` then it works. Is this the correct syntax?

**Comment by danoli3** [comment]
The example shouldn't have that in the setup. For sure...
