### ISSUE TITLE
Can't install OF 0.9 dependencies on Ubuntu 15.10

### ISSUE THREAD

**Issue by cjdg** [openframeworks/openFrameworks#4543]
I downloaded the lates release of OF 0.90 and when i run ./install_dependencies script i get this error

Los siguientes paquetes tienen dependencias incumplidas:
 libopencv-dev : Depende: libopencv-objdetect-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-highgui-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-legacy-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-contrib-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-videostab-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-superres-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libopencv-ocl-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libcv-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libhighgui-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
                 Depende: libcvaux-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by arturoc** [comment]
can you try to run:

```
sudo apt-get install libopencv-objdetect-dev
```

to see what's failing? this usually happens because you have a ppa or any other package installed that is breaking dependencies in the official repo but it might also just be a bug in the ubuntu repos

**Comment by cjdg** [comment]
it seems a problem with the dependency:

libopencv-objdetect-dev : Depende: libopencv-highgui-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse (cant install)

**Comment by cjdg** [comment]
It seems a problem with 15.10:

Los siguientes paquetes tienen dependencias incumplidas:
 libopencv-objdetect-dev : Depende: libopencv-highgui-dev (= 2.4.9+dfsg-1ubuntu6) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

**Comment by arturoc** [comment]
if you follow the chain of dependencies at some point you'll arrive at the cause. try now to install libopencv-highgui-dev and if it still says it's not going to install, try the next dependency. at some point you'll get the real reason why it can't be installed

**Comment by MindContact** [comment]
Hello to all,
I Kubuntu 10.15 with repositories KXStudio.
I've also had the same problem, on the advice of Arturo arrived at the package libavcodec-ffmpeg56, manually installed are able to install the next until libopencv-dev.

Now I have a problem with librtaudio-dev: Depends: libjack-dev.
But installing libjack-dev would remove some packages I installed KXStudio.

Sorry for the English, I'm using an automatic translator.

**Comment by MindContact** [comment]
I've installed libjack-dev manually and all went ok!
