### ISSUE TITLE
Compiling OF on Linux Mint 17.2

### ISSUE THREAD

**Issue by julien** [openframeworks/openFrameworks#4546]
Hi,

In order to compile oF 0.9.0 on Linux Mint 17.2 (mate) before running 

`./scripts/linux/ubuntu/install_dependencies.sh`

I had to manually install

+ `libjack-dev`
+ `libjack0`
+ `libaudio4`

Hope this can help someone.

Cheers

**Comment by bilderbuchi** [comment]
ping @openframeworks/linux
