### ISSUE TITLE
IOS audioinput example in 0.9.0 doesn't receive any audio input

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#4551]
via ericrosenbaum (from the forum): 

the audioinput example in the 9.0 release compiles and runs, and can play sound, but doesn't receive any audio input.

I removed the ofSoundPlayer, and now the audio input does work. so I guess there's a conflict between ofSoundStream and ofSoundPlayer (I seem to recall a long-ago issue where this was the case- so maybe an old bug has reawakened).

http://forum.openframeworks.cc/t/ios-v9-0-audioinput-example-gets-no-audio-input-w-partial-fix/21319

**Comment by danoli3** [comment]
Ah I may have caused this with https://github.com/openframeworks/openFrameworks/pull/4442/files

It is set to Mix with others so should be okay. Test removing that patch and if issue goes away?

**Comment by danoli3** [comment]
Yeah this was caused by 4442. I think I'll revert that PR.
