### ISSUE TITLE
ofxAssimpModelLoader drawVertices drawWireframe doesn't work. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4553]
Trying to draw a wireframe or point version of a model draws the model with faces. 
However getting the meshes from the model and calling drawVertices does work. 

It looks like it might be this line:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp#L749

The #ifndef should be #ifdef ? 

Changing that fixes the issue on OS X.

**Comment by ofTheo** [comment]
Hmm looking at it further do we need this check at all? 
It looks like its possible to pass through OF_MESH_POINTS and OF_MESH_WIREFRAME to OPENGL_ES 

ping @arturoc as I think it was a check you added.

**Comment by ofTheo** [comment]
Okay so between 0.8.4 and 0.9.0 these lines were removed. 
So the glPolygonMode(GL_FRONT_AND_BACK, ofGetGLPolyMode(renderType)); is now not being set for regular GL. 

@arturoc  Should we just removed the #ifdef and make the switch function for all targets?  

    if(!ofGetGLProgrammableRenderer()){
	#ifndef TARGET_OPENGLES
		glPushAttrib(GL_ALL_ATTRIB_BITS);
		glPushClientAttrib(GL_CLIENT_ALL_ATTRIB_BITS);
		glPolygonMode(GL_FRONT_AND_BACK, ofGetGLPolyMode(renderType));
	#endif
		glEnable(GL_NORMALIZE);
    }



    if(!ofGetGLProgrammableRenderer()){
	#ifndef TARGET_OPENGLES
		glPopClientAttrib();
		glPopAttrib();
	#endif
    }

**Comment by arturoc** [comment]
i think we just need to add:

```
glPolygonMode(GL_FRONT_AND_BACK, ofGetGLPolyMode(renderType));
```

before the call to the vbo draw in the case of non gles

**Comment by tgfrerer** [comment]
It seems to me that you should be able to get rid of the #ifdefs and render the mesh, (not the mesh.vbo) with the polygonmode as a parameter, as in `mesh.draw(renderType)`.

ofMesh now has a method:
```
virtual void draw(ofPolyRenderMode renderType) const;
```

**Comment by arturoc** [comment]
yes but we really want to draw the vbo not the mesh

**Comment by arturoc** [comment]
i mean, mesh is not an ofVboMesh which would do the right thing but an ofxAsimpMeshLoader which has a vbo in it

**Comment by ofTheo** [comment]
@arturoc I think the 
```
glPolygonMode(GL_FRONT_AND_BACK, ofGetGLPolyMode(renderType));
```
would need the push / pop no? 
or at least a bool check and restore. 

wouldn't the safer option be to just use the same code as for OpenGL ES? 
this would also make the AssimpModelLoader less dependent on OpenGL calls. 

```
        switch(renderType){
		    case OF_MESH_FILL:
		    	mesh.vbo.drawElements(GL_TRIANGLES,mesh.indices.size());
		    	break;
		    case OF_MESH_WIREFRAME:
		    	mesh.vbo.drawElements(GL_LINES,mesh.indices.size());
		    	break;
		    case OF_MESH_POINTS:
		    	mesh.vbo.drawElements(GL_POINTS,mesh.indices.size());
		    	break;
        }
```

**Comment by arturoc** [comment]
if the meshes that assimp generates are always triangles, which i guess they should be, then yes probably better to just use the same code and avoid push/pop

**Comment by ofTheo** [comment]
I guess it doesn't work 100% the same :) 
going to do a restore with a bool instead. 

<img width="338" alt="screen shot 2015-11-12 at 11 14 33 am" src="https://cloud.githubusercontent.com/assets/144000/11123607/95de5556-892e-11e5-94ca-d95f8b3a195d.png">
