### ISSUE TITLE
unused ofVideoGrabber crashes on exit

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4554]
Looks like if the shared_ptr is not being set it will crash on destruction ( which calls close() ) 
Thats because the line below is not checking if the grabber exists 

I believe: 
```
	if(!grabber->getTexturePtr()) tex.clear();
```
at: 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofVideoGrabber.cpp#L244

should be: 
```
	if(grabber && !grabber->getTexturePtr()) tex.clear();
```

I wonder if it shouldn't have any checks and just do tex.clear() ?

**Comment by arturoc** [comment]
yes i guess any of those is ok
