### ISSUE TITLE
pixels don't draw in multiWindowOneAppExample

### ISSUE THREAD

**Issue by genekogan** [openframeworks/openFrameworks#4562]
when drawing an image in both windows in the multiWindowOneAppExample, all i get is a white rectangle in the guiWindow, whereas in the mainWindow the image displays fine. are windows not able to share pixel resources?  same thing happens for any `ofBaseHasPixels`, e.g. `ofVideoGrabber`, `ofImage`, etc. 

simple example with an ofVideoGrabber:

    //--------------------------------------------------------------
    void ofApp::setup(){
        grabber.initGrabber(640, 480);
    }
    //--------------------------------------------------------------
    void ofApp::setupGui(){
    }
    //--------------------------------------------------------------
    void ofApp::update(){
        grabber.update();
    }
    //--------------------------------------------------------------
    void ofApp::draw(){
        grabber.draw(50, 50);
    }
    //--------------------------------------------------------------
    void ofApp::drawGui(ofEventArgs & args){
        grabber.draw(50, 50);
    }
    
and main is:

    int main( ){
        ofGLFWWindowSettings settings;
        settings.width = 800;
        settings.height = 800;
        settings.setPosition(ofVec2f(300,0));
        settings.resizable = true;
        shared_ptr<ofAppBaseWindow> mainWindow = ofCreateWindow(settings);
        
        settings.width = 800;
        settings.height = 800;
        settings.setPosition(ofVec2f(0,0));
        settings.resizable = true;
        shared_ptr<ofAppBaseWindow> guiWindow = ofCreateWindow(settings);
        guiWindow->setVerticalSync(false);
    
        shared_ptr<ofApp> mainApp(new ofApp);
        mainApp->setupGui();
        ofAddListener(guiWindow->events().draw,mainApp.get(),&ofApp::drawGui);
        
        ofRunApp(mainWindow, mainApp);
        ofRunMainLoop();    
    }

**Comment by arturoc** [comment]
you need to have a shared context in order to share textures or any other resource:

```cpp
int main( ){
    ofGLFWWindowSettings settings;
    settings.width = 800;
    settings.height = 800;
    settings.setPosition(ofVec2f(300,0));
    settings.resizable = true;
    shared_ptr<ofAppBaseWindow> mainWindow = ofCreateWindow(settings);

    settings.width = 800;
    settings.height = 800;
    settings.setPosition(ofVec2f(0,0));
    settings.resizable = true;
    settings.shareContextWith = mainWindow;
    shared_ptr<ofAppBaseWindow> guiWindow = ofCreateWindow(settings);
    guiWindow->setVerticalSync(false);

    shared_ptr<ofApp> mainApp(new ofApp);
    mainApp->setupGui();
    ofAddListener(guiWindow->events().draw,mainApp.get(),&ofApp::drawGui);

    ofRunApp(mainWindow, mainApp);
    ofRunMainLoop();    
}
```

that should work but feel free to reopen if it doesn't

**Comment by genekogan** [comment]
yep, that works, thanks. it may be worth including a comment about this in the example. t

**Comment by arturoc** [comment]
yes also in the docs, if you want to send a PR?

**Comment by genekogan** [comment]
yeah, will do this later today.
