### ISSUE TITLE
ofToDataPath() wrong when a file starts with 'data...'

### ISSUE THREAD

**Issue by micuat** [openframeworks/openFrameworks#4563]
ofLogError() << ofToDataPath("a.txt");
    ofLogError() << ofToDataPath("data.txt");

results in

    [ error ] data\a.txt
    [ error ] data.txt

where the second one is wrong, and it can cause file-not-found errors. I'm using 0.9.0 + Windows 10.

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by ofTheo** [comment]
also another issue with ofToDataPath:

```
    cout << ofToDataPath("") << endl; 
    results in: ../../../data
```

in 0.8.4 and before it did:

```
    cout << ofToDataPath("") << endl; 
    results in: ../../../data/
```

I can open a separate issue for it, if needed - noticed it when some old projects didn't load files correctly.
