### ISSUE TITLE
iOS Template Project needs LaunchScreen and Image Assets to support new devices

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#4566]
Need to review and add the LaunchScreen.xib and change over to Assets. to support native resolutions of iPhone 6/6s / iPhone 6/6s Plus, iPad Pro

This will then be used and built into projects built with the project generator and prevent this issue some users are experiencing.

**Comment by ofZach** [comment]
if you alter the xcproj file, be sure to use plutil to convert it back to xml -- the project generator parses the xml file (it doesn't read it as a plist).  

http://hints.macworld.com/article.php?story=20050430105126392

on first open an xml based xcproj file is turned into a plist again....

**Comment by danoli3** [comment]
Thanks @ofZach I knew I had to do this, but was going to have to look into how to do it. Cheers! :+1:

**Comment by julapy** [comment]
@danoli3 i was thinking it might be time to introduce a `media assets` folder to the ios xcode template project... seems to be a much better way of managing icons and splash screens assets.
what do you recon?

**Comment by danoli3** [comment]
@julapy Yeah sounds like a great idea

**Comment by danoli3** [comment]
Okay since we need new resolutions / images... any ideas for new image style? 

Current from 0.7:
Icon:
![icon-72 2x](https://cloud.githubusercontent.com/assets/830748/11178285/fc50c034-8c9f-11e5-8299-b380e16addeb.png)

Splash:
![default](https://cloud.githubusercontent.com/assets/830748/11178359/71da153a-8ca0-11e5-9642-0a4738ca86e3.png)

--

OSX has a white oF logo and black textured background. I'll have a play around with the AppIcon template and the logo

**Comment by danoli3** [comment]
Hows this look for AppIcon: (Going for the Black oF on white/silver gradient).
<img width="558" alt="screen shot 2015-11-17 at 4 38 10 am" src="https://cloud.githubusercontent.com/assets/830748/11189648/429d338e-8ce5-11e5-967b-0f03ae487316.png">

**Comment by danoli3** [comment]
Splash:
![default-portrait 2x iphone4](https://cloud.githubusercontent.com/assets/830748/11190360/260d7eb4-8ce9-11e5-91b3-c54e8fb8658f.png)

**Comment by ofTheo** [comment]
awesome! :)

**Comment by danoli3** [comment]
Hmm Travis is having an issue with the storyboard... looking into this.

**Comment by julapy** [comment]
icons and splash screens are looking very slick!
will review the PR now.

**Comment by julapy** [comment]
btw, do we have illustrator assets for the OF logo?
should this be checked into the repo so everyone can access them?
good think about having it as vector, is we can scale up for future higher resolutions.

**Comment by pizthewiz** [comment]
I traced the bitmap logo in Sketch and attached an SVG to openframeworks/ofSite#255 but I think it might be good to redo it and edit the text directly to make sure it is exactly what we'd want.

**Comment by julapy** [comment]
yeah nice, 
maybe we can put into a folder in the OF root called `assets` or `media`
where we could store these vector files, icons, splash screens....

im not aware of any other location inside OF where this is done.
