### ISSUE TITLE
More optimal CFLAGS for Arm7?

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4567]
In reading about incorporating NEON into an Arm7/RPI2 project I came across these options for CFLAGS

```
-mcpu=cortex-a7 -mfpu=neon-vfpv4
```
We are currently using 
```
-march=armv7-a -mfpu=vfp
```

I was able to compile and run an OF app with the newer flags. (You have to remove `march` in favor of `mcpu`)

Would love to know a good test to compare. This post claimed a 32x speed up with an x264 library
https://www.raspberrypi.org/forums/viewtopic.php?p=682887#p682887

Reference
https://community.arm.com/groups/tools/blog/2013/04/15/arm-cortex-a-processors-and-gcc-command-lines

**Comment by arturoc** [comment]
yes we should enable neon, in anything that supports it, it allows to do lots of operations (128bits) at once.

the main problem is that raspbian, i think, doesn't enable it so even if we compile OF using it, the libraries that would benefit most from it, like opencv won't. i think archlinux does enable neon in their arm7 distro but not 100% sure

**Comment by jvcleave** [comment]
Going to close this due to https://github.com/openframeworks/openFrameworks/pull/4704
