### ISSUE TITLE
Null ptr issues in XML

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4569]
Found this with Xcode's analyze. 

Looking at the logic, curElement will be NULL at this line: 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofXml.cpp#L770

ping @joshuajnoble - it would be great if you could have a quick look at the logic here.

**Comment by joshuajnoble** [comment]
Did you have any code that you ran to get to this? curElement is the document root or whatever level the user has set it to, e.g. https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofXml.cpp#L748 so if the element is NULL then lots of things have gone wrong and I'd love to know how that could happen.

**Comment by ofTheo** [comment]
@joshuajnoble - actually looking at this further, I don't see the issue - apologies!!
