### ISSUE TITLE
changelog is missing cool ascii art

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#4572]
scroll down and you'll see that ascii art has always been a part of the changelog but seems to have dropped off in recent releases....  The high point might have been 007.   Let's bring it back!

https://raw.githubusercontent.com/openframeworks/openFrameworks/0.9.0/CHANGELOG.md

**Comment by 2bbb** [comment]
:+1:

**Comment by HalfdanJ** [comment]
:+1: vote for ascii art

**Comment by 2bbb** [comment]
simple handmade.

```
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooFFFFFFFoooooooooooooooooFFFFFFFoooooooooooooooooFFFFFFFooo
oooooooooooooFFFFFFFFFoooooooooooooooFFFFFFFFFoooooooooooooooFFFFFFFFFoo
oooooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFo
ooooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFoo
oooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFooo
ooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFoooo
oooooooFFooooooooFFooooooooooooooFFFFFFFFFFooooooooooooFFooooooooFFooooo
ooooooFFooooooooFFooooooooooooooFFFFFFFFFFooooooooooooFFooooooooFFoooooo
oooooFFooooooooFFooooooooooooooooooooooFFooooooooooooFFooooooooFFooooooo
ooooFFooooooooFFooooooooooooooooooooooFFooooooooooooFFooooooooFFoooooooo
oooFFooooooooFFooooFFFFooooFFooooooooFFooooFFFFooooFFooooooooFFooooooooo
ooFFooooooooFFooooFFFFooooFFooooooooFFooooFFFFooooFFooooooooFFoooooooooo
oooFFFFFFFFooooooFFFFooooooFFFFFFFFooooooFFFFooooooFFFFFFFFooooooooooooo
ooooFFFFFFooooooFFFFooooooooFFFFFFooooooFFFFoooooooFFFFFFFoooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

**Comment by danthemellowman** [comment]
Sorry Zach I forgot to do it this time. Let me make one.

Should we/I just make an example app that generates it.

On Saturday, November 14, 2015, ISHII 2bit <notifications@github.com> wrote:

> simple handmade.
>
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> ooooooooooooooFFFFFFFoooooooooooooooooFFFFFFFoooooooooooooooooFFFFFFFooo
> oooooooooooooFFFFFFFFFoooooooooooooooFFFFFFFFFoooooooooooooooFFFFFFFFFoo
> oooooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFo
> ooooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFoo
> oooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFooo
> ooooooooFFooooooooFFooooooooooooFFooooooooFFooooooooooooFFooooooooFFoooo
> oooooooFFooooooooFFooooooooooooooFFFFFFFFFFooooooooooooFFooooooooFFooooo
> ooooooFFooooooooFFooooooooooooooFFFFFFFFFFooooooooooooFFooooooooFFoooooo
> oooooFFooooooooFFooooooooooooooooooooooFFooooooooooooFFooooooooFFooooooo
> ooooFFooooooooFFooooooooooooooooooooooFFooooooooooooFFooooooooFFoooooooo
> oooFFooooooooFFooooFFFFooooFFooooooooFFooooFFFFooooFFooooooooFFooooooooo
> ooFFooooooooFFooooFFFFooooFFooooooooFFooooFFFFooooFFooooooooFFoooooooooo
> oooFFFFFFFFooooooFFFFooooooFFFFFFFFooooooFFFFooooooFFFFFFFFooooooooooooo
> ooooFFFFFFooooooFFFFooooooooFFFFFFooooooFFFFoooooooFFFFFFFoooooooooooooo
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4572#issuecomment-156682273>
> .
>


-- 
Sent from Gmail Mobile #autocorrect
