### ISSUE TITLE
OpenCV: nonfree module is included in OSX binrary opencv.a

### ISSUE THREAD

**Issue by r9y9** [openframeworks/openFrameworks#4573]
* master (and of_v0.9.0_osx_release)

```
 % otool -D addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a | grep "sift\|surf\|nonfree"
addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a(nonfree_init.cpp.o):
addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a(sift.cpp.o):
addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a(surf.cpp.o):
addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a(surf_gpu.cpp.o):
addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a(surf_ocl.cpp.o):
```

* of_v0.8.4_osx_release

```
% otool -D addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a | grep "sift\|surf\|nonfree"
# nothing
```

It seems like opencv with non-free module is bundled at some point (https://github.com/openframeworks/openFrameworks/commit/82f9773ed40a2bb86f09c1f0d2f28d44391e9186 ?) after v0.8.4 release. I wonder this would cause some license problem, but is this change intentional? (though I believe this is unintentional).

I haven't check windows and linux binaries yet, but I think we should check all binaries carefully.

**Comment by danoli3** [comment]
Yeah sounds unintentional.

Reading up on this: Likely from GPU based parts of OpenCV.

``` -D WITH_OPENCL=OFF ``` may fix this in the build script.

**Comment by danoli3** [comment]
Hmm I checked as for OSX the script definitely has:
``` 
      -DWITH_OPENCL=OFF \
      -DWITH_CUDA=OFF \
```

**Comment by r9y9** [comment]
I found that `-DBUILD_opencv_nonfree=OFF` should fix the problem.

**Comment by danoli3** [comment]
Awesome! I'll make the changes

**Comment by arturoc** [comment]
the main probem with this modules i think is that they are patented (sift and surf are). depending where you are, software patents don't apply so i'd say it's totally ok to use them.

so not sure if we should remove them or keep them there, these are advance features that come with opencv and probably people should know if they are using them what's the legal status in their countries  as they would do if they would be using opencv directly?

**Comment by r9y9** [comment]
I'm from industry. Even if users don't use SIFT and SURF (like me), they may happen to include patented modules implicitly once they built apps with ofxOpenCv. I would suggest nonfree modules to be removed by default.

**Comment by ofTheo** [comment]
I think we should keep the non free modules in for the reasons @arturoc mentioned. 

I've personally used them in OF to compare different techniques. Some of the patents are not clear, differ by region and many allow for non commercial use. 

A note in the license file of OF might be a good solution.

**Comment by r9y9** [comment]
I will close this issue. Feel free to open this if you think this is really an issue for you. I decided to use custom opencv libraries that was built without the non-free module, instead of builtin libraries in openFrameworks. That's fine to me.
