### ISSUE TITLE
Project Generator apps don't compile due to reference to OF_TARGET_WINGCC

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#4574]
Should this be changed to OF_TARGET_MINGW?

**Comment by arturoc** [comment]
yes it changed with mingw some days ago, do you want to send a PR?

**Comment by ofZach** [comment]
can you check if the submodule is up to date?  we've made this change already: (https://github.com/openframeworks/projectGenerator/commit/5233313662c9672db6670423ede30627a1092c1a)

**Comment by arturoc** [comment]
oh yeah that must be the problem. i wonder why submodules can't be set to track a specific branch, it would make things so much easier

**Comment by ofZach** [comment]
closing this now...  (I think we need to update the refs in OF to point to the lastest PG commit...  or merge the PG back in!)

**Comment by gameoverhack** [comment]
I'm still having this problem even after updating to latest master and projectorGenerator submodule.

**Comment by ofZach** [comment]
which app are you trying to compile?

**Comment by arturoc** [comment]
you might need to update the PG to master too
