### ISSUE TITLE
Project Generator broken on Ubuntu

### ISSUE THREAD

**Issue by bangnoise** [openframeworks/openFrameworks#4575]
OF 0.9.0
Ubuntu 14.04 LTS

Download the OF linux 64-bit distribution
Follow steps at http://openframeworks.cc/setup/linux-install/
Open Project Generator, don't change anything, click Generate
Observe the following error

```
Command failed: /bin/sh -c "projectGenerator"  -o"/home/parallels/Documents/of_v0.9.0_linux64_release" -a" " -p"linux64" "/home/parallels/Documents/of_v0.9.0_linux64_release/apps/myApps/mySketch"
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
```

**Comment by ofZach** [comment]
relevant lines to look at regarding the regex: 

https://github.com/openframeworks/projectGenerator/blob/aea0360c095bb0be832eff68a3e7edf13ef1df5a/ofxProjectGenerator/src/projects/qtcreatorproject.cpp#L77-L90

**Comment by arturoc** [comment]
what version of gcc do you have? you can check it with gcc -v

**Comment by bangnoise** [comment]
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by arturoc** [comment]
there's some problems with gcc and regex i think the minimum version that works correctly is 4.9. you can use this ubuntu ppa:

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa

to install gcc 4.9 (be sure to remove 4.8 or set 4.9 as default or it'll try to use that instead)

in any case the PG in linux only creates a makefile and a config.make which are always the same and you can copy directly from scripts/templates/linux

if you are using qtcreator, the IDE plugin allows you to create new projects add addons easily...

i'll look into using poco regex instead at some point so it works with older gcc

**Comment by ofZach** [comment]
if it's helpful here's an example of poco regular expression being used elsewhere in the PG: 

https://github.com/openframeworks/projectGenerator/blob/5233313662c9672db6670423ede30627a1092c1a/ofxProjectGenerator/src/addons/ofAddon.cpp#L134-L138

**Comment by gomezgomez** [comment]
I'm having the same issue. I installed and set gcc and g++ 4.9, gcc -v returns gcc version 4.9.3 (Ubuntu 4.9.3-8ubuntu2~14.04) . 
I tried arturoc suggestion of duplicating the project in scripts/templates/linux .
My question is, I'm following a basic tutorial, and it says to add ofxGUI and ofxOSC addons on the Project Generator. How do I add those if I start from the template instead? Also when I compiled the template (just to try), it takes way longer than the examples, and for what I understand it looks like it's including a lot of libraries, which I don't know if that's entirely necessary. 

Thanks!

**Comment by arturoc** [comment]
have you recompiled the PG after installing gcc 4.9? to add addons if you are using qtcreator just edit the projectfiles.qbs and in the of.addons section add the names of the addons. if you are using makefiles just add the names of the addons in addons.make

**Comment by gomezgomez** [comment]
That's it! Thank you

*Sebastian J. Gomez*
Visual Designer
*PORTFOLIO <http://www.sjgomez.com>*
*LINKED IN <http://www.linkedin.com/in/gomebigge>*

*SkypeID GomezBiggeri*


2016-01-17 1:27 GMT-08:00 arturo <notifications@github.com>:

**Comment by bakercp** [comment]
Closing this with gcc 4.9 being the solution.
