### ISSUE TITLE
Apothecary - Rebuild OpenCV iOS / OS X

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#4587]
Apothecary - Rebuild OpenCV iOS / OS X
---------------

To fix issues related to https://github.com/openframeworks/openFrameworks/issues/4576

```
Undefined symbols for architecture x86_64:
  "Imf::Header::Header(int, int, float, Imath::Vec2<float> const&, float, Imf::LineOrder, Imf::Compression)", referenced from:
      cv::ExrEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&) in opencv.a(grfmt_exr.cpp.o)
  "Imf::Header::channels()", referenced from:
```

- [x] Rebuild OSX lib
- [x] Rebuild iOS lib

**Comment by danoli3** [comment]
@bakercp Could you compile the OSX versions? Did you still need to do the build on an older OSX?

**Comment by namrata61193** [comment]
@danoli3 Can you please specify how to fix this? I've been stuck for the past 2 days

**Comment by danoli3** [comment]
@namrata61193 Oh go to /scripts/Apothecary in terminal and run the following:
```./apothecary -t osx update ofxOpenCv```

**Comment by danoli3** [comment]
I'll do this now.

**Comment by danoli3** [comment]
Okay that's done!

**Comment by danoli3** [comment]
All merged.
