### ISSUE TITLE
ofNode::lookAt gives incorrect results

### ISSUE THREAD

**Issue by chaosct** [openframeworks/openFrameworks#4594]
When an `ofCamera` (inheriting from `ofNode`) is situated in a position with the `x` and `z` components at 0, the result of `lookAt` is inconsistent.

To reproduce the bug:
```
camera.setPosition(0, 600, max(0, ofGetMouseX()-100));
camera.lookAt(ofVec3f());
ofSetColor(255, 0, 0);
camera.begin();
ofDrawBox(100);
camera.end();
```

**Comment by tgfrerer** [comment]
This could be because of the up-Vector in that case being ambiguous. Have you tried passing an up-vector as the second parameter to `lookAt`?

**Comment by chaosct** [comment]
I don't know exactly what up-vector I should pass to `lookAt`, or what a up-vector is exactly. If it means that I should pass a vector towards what I think is "up", like `ofVec3f(0,2,0)`, I get the same results.

**Comment by tgfrerer** [comment]
The up-vector is a vector that tells the camera where "up" is. 

Your camera sits on the y-axis and points forward. To help getting the up-vector I like to look at my right hand, and point the index finger in `lookAt` direction, then push the thumb up. 

That's your up-vector.

My guess is that your up-vector should be something like (0,0,-1), because if you're pointing straight down, your thumb would point forward, thus in -z.

By default, the up-vector is `(0,1,0)`, meaning the camera points straight ahead. If you set the camera on the y-axis, it can't calculate an unambiguous `lookAt` because the ray it points along and the up-vector are essentially the same.

**Comment by arturoc** [comment]
i'm testing this just in case and the problem is just what @tgfrerer is describing, you have the up vector parallel to the lookAt one which gives an ambiguous orientation and so the calculation gives an indeterminate result.

testing with:

```cpp
//--------------------------------------------------------------
void ofApp::draw(){
    auto z = max(0, ofGetMouseX()-100);
    camera.setPosition(0, 600, z);
    if(z>0){
        camera.lookAt(ofVec3f());
    }else{
        camera.lookAt(ofVec3f(),{0.f,0.f,-1.f});
    }
    ofSetColor(255, 0, 0);
    camera.begin();
    ofDrawBox(100);
    camera.end();
}
```

does the correct thing.

**Comment by arturoc** [comment]
mmh, @tgfrerer what if we calculated the up vector as a rotation of the default position for the default up vector, something like:

```cpp
void ofNode::lookAt(const ofVec3f& lookAtPosition){
    ofQuaternion q;
    q.makeRotate({0.f,0.f,1.f}, getPosition() - lookAtPosition);
    auto up = q * ofVec3f(0.f,1.f,0.f);
    lookAt(lookAtPosition, up);
}
```

that works for me with this case but not sure what would happen in other cases

**Comment by tgfrerer** [comment]
Yes, that looks promising. I've been trying to find singularities, i.e. values where the math will "blow up", but couldn't track down any, so far. I'm wondering if it will look right, though. Some thoughts:

* Our implementation of `ofQuaternion::makeRotate(ofVec3f, ofVec3f)` assumes according to the doxy that both vectors are unit vectors, which is not guaranteed in the above - it might need a normalize of the eye vector `(getPosition()-lookAtPosition()).getNormalised()` ? 

* I assume that the implementation of `makeRotate` generates a quaternion which would rotate vector `a` to vector `b` using the cross product of the two vectors as the rotation axis. If the vectors represent a full u-turn, this case is caught and dealt with, but in a way which I can't totally follow without reading up on the maths. 

* I wonder if the camera might start rolling (rotating on its z-axis) under some circumstances (e.g. if higher or lower than the `lookAtPosition`), but this might look cool.

**Comment by arturoc** [comment]
:) ok, i guess even if there's some problems the result in most cases would be more predictable than defaulting the up vector to y=1. i'll add the normalization and send a PR. thanks for looking into it!

**Comment by arturoc** [comment]
i'm looking at the source for that function and it seems to already normalize the passed parameters if necessary so i've just left it as in the example.
