### ISSUE TITLE
ofGetElapsedTimef() much slower than previous release. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4595]
From testing this code from the forum:
http://forum.openframeworks.cc/t/ofmesh-slow-fps-v0-9-0/21448/4

I get about 32 fps in 0.9.0 with vertical sync disabled. 
With 0.8.4 it is 300+ fps. 

Using a profiler - it looks like ofGetElapsedTimef() was using about 90% of the app cpu. 

In 0.8.4 the code for ofGetElapsedTimef looked like this:

```
unsigned long long ofGetElapsedTimeMicros(){
	return ofGetSystemTimeMicros() - startTimeMicros;
}

//--------------------------------------
float ofGetElapsedTimef(){
	return ofGetElapsedTimeMicros() / 1000000.0f;
}
```

in 0.9.0 it is now this: 

```
float ofGetElapsedTimef(){
    uint64_t seconds;
    uint64_t nanos;
	ofGetMonotonicTime(seconds,nanos);
	return (seconds - startTimeSeconds) + ((long long)(nanos - startTimeNanos))/1000000000.;
}
```

This looks like it was introduced in this commit:
https://github.com/openframeworks/openFrameworks/commit/d8a8a654735560c23b0b17339bcc30512eb996a3#diff-332d8b7d6f5fd5bf0109d93c9a7491b1R111

ping @arturoc  ( when you're back from holidays) @kylemcdonald as he was also working on this function a bit too. 

It would be good to address this if possible as it can be used quite heavily. 
I wonder if also a ofGetElapsedTimeForFramef() would be a good idea too?

**Comment by kylemcdonald** [comment]
i think i worked on an older, simpler version of this function... but this new version has a complex platform-specific implementation i don't understand it as well. sorry :(

**Comment by bakercp** [comment]
Now that we're using c++11 couldn't we use one of the new built-in high precision monotonic clocks (e.g. http://en.cppreference.com/w/cpp/chrono/system_clock or http://en.cppreference.com/w/cpp/chrono/high_resolution_clock?

**Comment by bakercp** [comment]
Sorry, would probably be http://en.cppreference.com/w/cpp/chrono/steady_clock for monotonic.

**Comment by danoli3** [comment]
Nice find @ofTheo! wow! 
Maybe just revert to the old one and have a higher precision version for those that need it.

```ofGetElapsedTimeMonotonicf```, updated with this chrono clock from c++11

**Comment by ofTheo** [comment]
Yeah I think that isn't a bad idea @danoli3 
I might try implementing the c++11 one - maybe its fast enough as is? 

always nervous about touching this stuff - super easy to cause mad damage

**Comment by arturoc** [comment]
mmh, i'll take a look next week, it's really weird that it might be taking that much time. @bakercp te c++11 implementation is still not very precise in some platforms (at least windows) so we would still need some platform specific code there but it might be the easiest

**Comment by arturoc** [comment]
just a quick test but can you try if this:

```cpp
#if defined(TARGET_OSX)
namespace{
    clock_serv_t & getOSXClockService() {
        static bool inited = false;
        static clock_serv_t cs;
        if(!inited){
            host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, cs);
            inited = true;
        }
        // mach_port_deallocate(mach_task_self(), cs);
        return *cs;
    }
}
#endif

//--------------------------------------
void ofGetMonotonicTime(uint64_t & seconds, uint64_t & nanoseconds){
#if (defined(TARGET_LINUX) && !defined(TARGET_RASPBERRY_PI)) || defined(TARGET_EMSCRIPTEN)
	struct timespec now;
	clock_gettime(CLOCK_MONOTONIC, &now);
	seconds = now.tv_sec;
	nanoseconds = now.tv_nsec;
#elif defined(TARGET_OSX)
        mach_timespec_t now;
        clock_get_time(getOSXClockService(), &now);
	seconds = now.tv_sec;
	nanoseconds = now.tv_nsec;
#elif defined( TARGET_WIN32 )
	LARGE_INTEGER freq;
	LARGE_INTEGER counter;
	QueryPerformanceFrequency(&freq);
	QueryPerformanceCounter(&counter);
	seconds = counter.QuadPart/freq.QuadPart;
	nanoseconds = (counter.QuadPart % freq.QuadPart)*1000000000/freq.QuadPart;
#else
	struct timeval now;
	gettimeofday( &now, nullptr );
	seconds = now.tv_sec;
	nanoseconds = now.tv_usec * 1000;
#endif
}
```

fixes it? i'll do more tests next week anyway

**Comment by ofTheo** [comment]
Thanks @arturoc  

It goes up to 90 fps - from 32 fps. 
If I patch in the functions from OF 0.8.4 it goes up to 420 fps.

**Comment by arturoc** [comment]
what version of osx are you using? i'm on 10.9 and getting the same fps if i call any of the elapsed time functions or not

i remember profiling this when i implemented it and there was also no difference between calling host_get_clock_service every frame or not so i left it like that so it was thread safe.

this implementation is much more accurate than the previous one and solved some problems with stuttery animation (mostly in windows) and fps calculation. it's also monotonic, so if the os adjusts the clock the application won't have any problem

**Comment by ofTheo** [comment]
I'm on 10.9 

Just double checked and its quite significant. 
With this test code its quite easy to see the difference. 

On 10.9 with 0.9 code
`delta is 0.098433 fps is 9.86463`

on 10.8 with 0.8.4 code
` delta is 0.00247002 fps is 60.0814`

Its about 40 times faster - from my measurements. 

```
//--------------------------------------------------------------
void ofApp::update(){
    
    float t1 = ofGetElapsedTimef();
    float fakeVar = 0;
    for(int d = 0; d < 50000; d++){
        fakeVar += ofGetElapsedTimef();
    }
    cout << " using fake var is its not optimized out " << fakeVar << endl;
    float t2 = ofGetElapsedTimef();
    cout << " delta is " << t2-t1 << " fps is " << ofGetFrameRate() << endl;
    
}
```

**Comment by ofTheo** [comment]
ps: totally agree that it would be better to have a more accurate system going forward. 
Just feel like a lot of people will run into issues where code which was running fast, runs a lot slower. 
Not sure if there are any areas for optimization. 

ps: this is with vanilla 0.9.0 ( master ) vs 0.8.4 - I didn't apply the patch you posted for this test.

**Comment by ofTheo** [comment]
with your patch I get:
` delta is 0.0400124 fps is 28.4781`

**Comment by arturoc** [comment]
yes i just noticed that the difference is noticeable if you call that function a ton of times per frame. i guess a possible fix would be to use the old, less accurate and non monotonic calls for ofGetElapsedTimef and ofGetElapsedTimeMillis which returns seconds and milliseconds (in windows the old implementation has 1ms accuracy) and leave the most accurate calls for the microseconds and nanoseconds versions. 

the fact that the clock is monotonic is also important and we'll loose that for the less accurate calls

another possibility would be to document that this calls can be relatively slow and that it's good practice anyway to call them once per frame and then use that value. in the original example in the forum this:

```cpp

for (float u = 0.0; u < 2 * PI; u += PI / 75) {
    for (float v = 0.0; v < 2 * PI; v += 2 * PI / 75) {


        time = ofGetElapsedTimef() * 1.0f;
        noise = cos(v) + ofNoise(time) * 5.0f;
        size = 100;
        coords.x = sin(v) * size;
        coords.y = cos(u) * size;
        coords.z = sin(u + time) * cos(noise) * size;
        color = ofFloatColor(.85,0.9,0.90, u * alpha);


        //Create
        mesh.addColor(color);
        ofVec3f vec = ofVec3f(coords);
        mesh.addVertex(vec);
    }
}
``` 
would be more correct as:

```
auto now = ofGetElapsedTimef()

for (float u = 0.0; u < 2 * PI; u += PI / 75) {
    for (float v = 0.0; v < 2 * PI; v += 2 * PI / 75) {


        time = now * 1.0f;
        noise = cos(v) + ofNoise(time) * 5.0f;
        size = 100;
        coords.x = sin(v) * size;
        coords.y = cos(u) * size;
        coords.z = sin(u + time) * cos(noise) * size;
        color = ofFloatColor(.85,0.9,0.90, u * alpha);


        //Create
        mesh.addColor(color);
        ofVec3f vec = ofVec3f(coords);
        mesh.addVertex(vec);
    }
}
```

which brings back the performance to the original but also is much more correct in terms of generating the correct shape

**Comment by ofZach** [comment]
what about a cached frame time like ofGetFrameStartTime() (or some other better name) ?  That would be a record of the time at the start of the frame.  I agree that using the cached value makes sense, this could help offer an option where people don't have to cache on their own....

**Comment by arturoc** [comment]
also a common practice is to pass the time in update (we could pass it in draw too) so ofApp update and draw would become:

```
void ofApp:update(double now){
}

void ofApp::draw(double now){
}
```

but having a function would be less disruptive i guess

**Comment by ofTheo** [comment]
Thinking about it more I think I'm okay with ofGetElapsedTimef being 50% slower but more accurate. 
If you are calling ofGetElapsedTimef() a ton every frame - you're probably doing it wrong :) 
You would rarely need to call it 50,000 times a frame. 

In our projects we usually cache the current frame time similar, to as Zach suggested. 
I would be okay with adding: ofGetFrameStartTime() ( I wonder if it gets complicated with multi windows / multiple ofMainLoops though ) 

Maybe for 0.9.1 we could just do the OS X patch?

**Comment by arturoc** [comment]
the problem with that patch is that it's probably not thread safe. since the performance is still poor compared to the old call i'd leave it like it is.

in c++11 there's a new way of declaring variables:

```
thread_local type var;
```

which creates an instance per thread which would be perfect for this but this is still not working for static variables with clang so it won't work in osx. 

i would leave it like it is and add the thread_local storage + a cached time per frame later

**Comment by arturoc** [comment]
also we could change line 67:

```cpp
#elif defined(TARGET_OSX)
```

with:

```cpp
#elif defined(TARGET_OSX) && !defined(OF_USE_OSX_LEGACY_TIMERS)
```

that way you can define OF_USE_OSX_LEGACY_TIMERS somewhere in the project settings or in ofConstants and will get the same calls as in 0.8.4.

it's super hacky but would give an easy way to get old projects that were calling the time functions in osx working with the same performance.

**Comment by ofTheo** [comment]
ahh thats a shame - because the static instance fix makes it go from 40 times slower to just 2 times slower. seems like a significant improvement. 

could we do a map with threadID as the index? 
```
clock_serv_t & cs ourClockMap[std::this_thread::get_id().hash()]; 
```
from: http://stackoverflow.com/questions/7432100/how-to-get-integer-thread-id-in-c11

**Comment by ofTheo** [comment]
this works for me - can you see anything dodgy with this @arturoc ?  :) 

```
#if defined(TARGET_OSX)
namespace{
	static map<size_t, clock_serv_t> ourClockMap;

    clock_serv_t & getOSXClockService() {
	
		auto index = std::hash<std::thread::id>()(std::this_thread::get_id());
		
		if( ourClockMap.count(index) == 0 ){
            host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &ourClockMap[index]);
		}
		
		return ourClockMap[index];
    }
}
#endif

```

**Comment by arturoc** [comment]
that's not thread safe since the map should be locked to access it from different threads, we would need a  mutex and also the map and the mutex should be created in the heap and never deallocated.

btw with the anonymous namespace there's no need to use static it already makes that variable local to the cpp file

should be something like:

```cpp
#if defined(TARGET_OSX)
namespace{
    

    clock_serv_t & getOSXClockService() {
        static auto * ourClockMap = new map<size_t, clock_serv_t>();
        static auto mtx = new std::mutex(); 
        auto index = std::hash<std::thread::id>()(std::this_thread::get_id());
        std::unique_lock<std::mutex> lck(mtx);
        if( ourClockMap.count(index) == 0 ){
            host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &ourClockMap[index]);
        }

        return ourClockMap[index];
    }
}
#endif
```

in general i think it's too complex to fix an issue derived from a wrong usage and it could even dead lock in some cases

**Comment by arturoc** [comment]
also i'm not even sure that using a clock_serv_t from different threads is not thread safe so it might be possible that we could just create it in some init function called from ofInit

**Comment by ofTheo** [comment]
agree that were starting to get to a point where its more likely new bugs 

`also i'm not even sure that using a clock_serv_t from different threads is not thread safe so it might be possible that we could just create it in some init function called from ofInit` 
this seems like a much safer option!

to me it might be worth implementing if it can be done simply ( like your suggestion ). 

ofGetElapsedtimef in a big project ( not in for loops ), might see a significant hit from being 40x slower than 0.8.4. 

At 1000 calls to that function ( not totally unimaginable on a really big project ) it would roughly equal a 1.96 ms hit which would cause an app going at 60 fps to run at 54 fps

**Comment by arturoc** [comment]
i can't find any info on how thread safe is that call though and every example i've found uses it by getting the clock and deallocating it every time so most probably the init call is not an option.

also 1000 calls to that function, no matter how big the project, would still be a bad implementation. the right thing to do is get that value per frame in the ofApp and pass it in update to every other object. also ofGetLastFrameTime gives you a delta which is usually more useful for animation and is already cached.

i'm ok trying to make it faster if we find a simple solution but right now everything seems worse than what we have (introduces potential deadlocks or even crashes)

we could also have a function that disables high resolution timers globally, in windows i enabled in 0.9 high resolution timers which are applied globally in the OS and can have some weird effects but it was the only way to solve some issues we were having with time meassurements (also some other software enables them anyway) so we could have somehitng like;

```
ofEnableHighResTimers()
ofDisableHighResTimers()
```

and have them enabled by default which might be slower if someone does a ton of calls to the timer functions but fixes some problems

**Comment by ofTheo** [comment]
hmm - I think its thread safe. 
look at mach_absolute_time in http://www.opensource.apple.com/source/Libc/Libc-320/i386/mach/mach_absolute_time.c

its using an externed clock_serv_t for calls. 

I would be happy doing your original patch as is. 
I tried hammering it pretty hard with multiple threads and didn't hit any issues. 

Could also do OS X time with mach_absolute_time which looks like it doesn't require the slow clock initialization. 

Some other useful info here: 
http://stackoverflow.com/a/6719178

**Comment by arturoc** [comment]
still i would do it on an init function and then deallocate it on the exit callback somehow. 

i was looking at mach_absolute_time when i implemented this but couldn't find anywhere saying that it was monotonic and the only calls that everyone ensure  are monotonic are the ones we are using now

**Comment by ofTheo** [comment]
cool cool! 
I'm up for that 

sorry for the worlds longest thread :)
