### ISSUE TITLE
ES2 glsl precision

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4596]
ive been working on a iOS ES2 project a have been experiencing a lot of triangles z-flighting.
figured out that the issue was with the glsl precision settings, currently set to `precision mediump float;`
by settings it to `precision highp float;`, this fixed all the z-fighting issues.

the two lines of code which define the ES2 glsl precision are here,
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L1826
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L1832

the only way i can increase the precision to high without hacking at the OF core is to write my own custom shader... but this won't be obvious for most users and is a bit of a hassle.

so wondering if there is a way of programmatically setting the ES2 precision in ofGLProgrammableRenderer?

**Comment by danoli3** [comment]
Might be worth setting up a macro define OPENGLES_HIGH_PRECISION and just wrap that line in the static const string. Then the programmer just has to pass
-DOPENGLES_HIGH_PRECISION and get instant access to the high precision

**Comment by julapy** [comment]
@danoli3 thats not a bad idea.
do you mean you would set `-DOPENGLES_HIGH_PRECISION` in Preprocessor Macros in xcode build settings? or in a different way?

**Comment by julapy** [comment]
also, if this is the correct approach, (cc @Arturo)
it might be worth creating a macro for 'OPENGL_LOW_PRECISION' as well.
if everyone agrees, i can put together a PR for this.

**Comment by arturoc** [comment]
yes there's no way to set it yet, i actually bumped it up to medium from low some time ago to fix some other issue. having some way to customize it would be great, what @danoli3 points out would be a good solution, the define would be in the shader not in the c++ code so we could recompile the shaders when that setting changes through a method in the renderer (and the corresponding global function)

**Comment by ofZach** [comment]
to add on to this -- I recently struggled with noisiness on ios when I applied a matrix to a point and drew it vs ofMultMatrix and drawing the unmodified point which was clean.  I've found using this in the default vertex shader

	uniform highp mat4 projectionMatrix;
	uniform highp mat4 modelViewMatrix;
	uniform highp mat4 textureMatrix;
	uniform highp mat4 modelViewProjectionMatrix;

helps a lot -- I now can draw either way....    Not sure of the performance implications but just want to mention it.

**Comment by danoli3** [comment]
Update on this.

I’m going to be pushing a PR with this fix however with HighP as default.

I have noticed a lot of issues caused by default mediump when converting
es1 targets to es2.

All modern devices are good for this.
I see no performance loss with the shader as it stands.

I’m going to run some comparative benchmarks just to show this.

Also I’m stepping up iOS oF dev over the next month. Lots of changes coming

**Comment by arturoc** [comment]
yeah i did this with an android nexus one so i can imagine things have changed a lot meanwhile :). let's change everything to highp

about new developments, we are about to release 0.10, just so you know that right now we'll only merge bugfixes and new features will have to wait until after the release
