### ISSUE TITLE
poco formula not working on linux64/ubuntu 15.10

### ISSUE THREAD

**Issue by nanu-c** [openframeworks/openFrameworks#4601]
My apps aren't building at the moment after upgrading to ubuntu 15.10.
The errors looking like
` Nicht definierter Verweis auf Poco::Thread::setName()`
when I run ther install dependencies script i get:
```
It seems you are running gcc 5 or later, due to incomatible ABI with previous versions
we need to recompile poco. This will take a while
Press any key to continue...  Skipping "poco": updateFormula not needed for type "linux64"
```
And the same with apothecary
```./apothecary -j linux64 update poco
 Skipping "poco": updateFormula not needed for type "linux64"```
I think the reason is in the
scripts/apothecary/formulas/poco/poco.sh
where it shows that the update for poco isn't implemented yet
`FORMULA_TYPES=( "osx" "ios" "tvos" "android" "emscripten" "vs" )`

**Comment by danoli3** [comment]
I'll fix this now

**Comment by danoli3** [comment]
@nanu-c Pull master, should be fixed. :+1:

**Comment by nanu-c** [comment]
okey that simple. Thanks

**Comment by nanu-c** [comment]
to get it built i had to 
touch ./scripts/apothecary/build/poco/lib/Linux/x86_64/ad.a
because rm lib/Linux/x86_64/*d.a failed. Don't know if its in the same apothecary formula.
