### ISSUE TITLE
Proposed fixes for ofxTCPManager

### ISSUE THREAD

**Issue by traumedy** [openframeworks/openFrameworks#4604]
Been thinking about how to deal with errors/disconnects/timeouts.  It's tricky as currently implemented.  As it would obviously be best not to change the user facing API, the easiest solution seems to me to be:

. On raw reads, return 0 on timeout or no data or error/disconnect, or on string return reads return empty string, but leave the connection intact if no real error..
. On sends, return false on timeout or disconnect or other error, but leave connection intact if no real error.
. Document well that isConnected() should be called after each call where zero or empty string was returned to distinguish between timeouts/non-blocks vs disconnect.  

What this doesn't address is ofxTCPManager::SendAll() calls (used from everywhere in ofxTCP\* ::send *()) where some but not all of the data might have been sent before a timeout/block occurred (network busy/full), as currently there is no way to return how MUCH data got sent.

Internally, ofxTCPManager::Receive() and Send\* () returns SOCKET_TIMEOUT on EWOULDBLOCK or timeout, SOCKET_ERROR for any other error, and every function that uses ofxTCPManager::Send*() or Receive() needs to check return values for both SOCKET_ERROR AND SOCKET_TIMEOUT, which NONE currently do in ofxTCPClient or ofxTCPServer.  Close connection on SOCKET_ERROR and leave connection as is on SOCKET_TIMEOUT.

If this sounds reasonable to others, I'll implement as described and do a PR.  
DISCUSS!

More issues with Accept/Connect timeouts need to be addressed, but I haven't thought trough those issues yet...

**Comment by ofTheo** [comment]
@traumedy I think this sounds reasonable. 
I wonder if a getLastError() function might be helpful in the cases of returning 0 / false as well? 

Many thanks for looking at this! 
Theo

**Comment by arturoc** [comment]
for complex error conditions like this, we can have some kind of struct/class that holds the data if correct or the error if there was one. would be something like:

```cpp
struct ofxNetworkResult{
    ofBuffer data;
    enum Error{
        Ok = 0;
        // all the error conditions available
    }error;
    std::string errorMessage;
    bool isOk();
    bool isError();
}
```

it would solve all the cases and it's much robust than returning an error code and printing some message on the console. also better than storing the last error and using some getLastError().

**Comment by ofTheo** [comment]
this looks a lot better! 
was thinking of a way which wouldn't break the current API, but to be honest breaking the API would be worth it for this addon.

**Comment by traumedy** [comment]
Sorry for the delayed response, holidays and work and life etc.

The proposed ofxUDPManager fix for timeouts needs to be changed for Windows
as the setsockopt(SO_*TIMEO, ..) calls expect a pointer to a DWORD in
milliseconds, not a timeval struct.

As for the general behavior of and breaking compatibility with the existing
API, seems to me for Receive calls, TCP or UDP, like there should be three
return values, which doesn't break most current use cases:
> 0:  data received.
0: timeout or Bonn blocking socket would have blocked.
-1:  socket/connection is broken and has been closed.  Re-create to try
again.

Adding a GetLastError() would be easy enough but I'm not sure how useful.

I've got some time this weekend to do some work on this and do a PR.

We still need to discuss the behavior for send timeouts/blocks as the API
currently returns bool which has no way to distinguish between a timeout vs
disconnect.

On Tuesday, November 24, 2015, Theodore Watson <notifications@github.com>
wrote:

> this looks a lot better!
> was thinking of a way which wouldn't break the current API, but to be
> honest breaking the API would be worth it for this addon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4604#issuecomment-159341049>
> .
>


-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential

**Comment by arturoc** [comment]
Hey @traumedy i would like to try the option of returning an object that wraps the return result + the error condition (the real one returned by the os internnally). that way people could check in their code the error, even print or show the error message...

returning an integer error code is really old school, more c than c++ and we only use it in one other place, in ofSerial where i would like to remove it as well.

i think there's even ways to not break the api completely using this pattern by having that object auto cast to true or false depending if the operation was an error or not.

right now we are using a pattern like:

```
do something
if it's an error
   print error message
   return empty value
else
   return correct value
```

this makes debugging something like looking for that error message printout setting a breakpoint and waiting for it to happen which is really strange. it also makes the console really verbose in some cases where there's error conditions or warnings that can be ignored.

the typical solution for this in c++ is something like

```
try to do something
catch exception
    try to recover from exception
    if not throw exception
finally clean up
```

but we don't throw exceptions in OF, among other things cause it's really hard to know when you have to catch and if you don't it crashes the whole application.

having a Result class that wraps the return value + an error if there was one is a nice solution that has the best of both worlds: doesn't crash unexpectedly (although we could even have the option to do so to allow for easier debugging) and allows to check the error condition from the caller

anyway, just to say that i don't think that we'll merge a solution returning int error codes. the next release 0.9.1 is a fixes only so we won't merge anything that breaks the api anyway and for next releases i would prefer to explore this option.

If you want to take a look at the windows implementation for the timeout that'd be great. 

thanks!

**Comment by traumedy** [comment]
@arturo:  If you want to up the game and change oF from a basic
API level interface designed for 'creative coders' who barely know
structured programming to OOP and exception handling design, fine with me.
I have yet to run across any c++ exception handling in any oF API.

I want to get the existing networking API working ASAP for the next
minor release.  It is embarrassing that the major release was broken.

On Saturday, November 28, 2015, arturo <notifications@github.com> wrote:

> Hey @traumedy <https://github.com/traumedy> i would like to try the
> option of returning an object that wraps the return result + the error
> condition (the real one returned by the os internnally). that way people
> could check in their code the error, even print or show the error message...
>
> returning an integer error code is really old school, more c than c++ and
> we only use it in one other place, in ofSerial where i would like to remove
> it as well.
>
> i think there's even ways to not break the api completely using this
> pattern by having that object auto cast to true or false depending if the
> operation was an error or not.
>
> right now we are using a pattern like:
>
> do something
> if it's an error
>    print error message
>    return empty value
> else
>    return correct value
>
> this makes debugging something like looking for that error message
> printout setting a breakpoint and waiting for it to happen which is really
> strange. it also makes the console really verbose in some cases where
> there's error conditions or warnings that can be ignored.
>
> the typical solution for this in c++ is something like
>
> try to do something
> catch exception
>     try to recover from exception
>     if not throw exception
> finally clean up
>
> but we don't throw exceptions in OF, among other things cause it's really
> hard to know when you have to catch and if you don't it crashes the whole
> application.
>
> having a Result class that wraps the return value + an error if there was
> one is a nice solution that has the best of both worlds: doesn't crash
> unexpectedly (although we could even have the option to do so to allow for
> easier debugging) and allows to check the error condition from the caller
>
> anyway, just to say that i don't think that we'll merge a solution
> returning int error codes. the next release 0.9.1 is a fixes only so we
> won't merge anything that breaks the api anyway and for next releases i
> would prefer to explore this option.
>
> If you want to take a look at the windows implementation for the timeout
> that'd be great.
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/4604#issuecomment-160266715>
> .
>


-- 
*JOSH BUCHBINDER* | Interactive Developer | +1 925 351 8049 | *OBSCURA*
<http://www.obscuradigital.com/> | SF
<http://www.obscuradigital.com/contact/> +1 415 227 9979 |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>NYC
<http://www.obscuradigital.com/contact/> |
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>
<http://www.obscuradigital.com/contact/>Stockholm
<http://www.obscuradigital.com/contact/>
 | Proprietary & Conﬁdential

**Comment by arturoc** [comment]
yeah, that's what i meant let's try to fix things without changing the api by now. 0.9.1 is a patch version so we shouldn't change the api and for next release i would like to explore some options in terms of error handling not only in this addon but also in some classes in the core like ofSerial or all the file utils

**Comment by ofTheo** [comment]
@traumedy any critical bug fixes you could do for 0.9.1 that doesn't break the current API in a hard way is really appreciated!!

I think send and sendAll currently return int - so getting the values to work as expected with the higher level ofxTcpClient/Server etc would be great for the bugfix release.  i.e: ( all errors that are critical errors or timeout errors return false, only successful send returns true ) 

I'm curious if going forward for 0.10.0 we should have something as DIY as the codebase we have right now. If we weren't moving towards dropping Poco from the core, I would suggest building off that.
C++11 doesn't currently have a networking implementation. 

curious what you think @arturoc - asio sockets?

**Comment by arturoc** [comment]
i just sent a PR that should fix all this problems + some others that i've found.

yes asio seems like the default for c++ sockets right now. also the main problem is not so much the sockets themselves. we could easily make a better c++ wrapper for sockets than ofxTCP/UDPManager  but ofxTCPServer/Client also have some logic for dealing with TCP streams so you can easily send/receive messages without having to deal with TCP being stream oriented rather than message oriented. maintaining that working when things change in the underlying socket is also a source of problems.

we could look into asio but before 0.9.0 i tried to include one of it's dependencies, cpp-uri and it made it crash xcode, i sent a patch to the orignal authors but they didn't want to merge it since it included some ifdefs so unless that's fixed i guess asio is not an option.

i think having a better way of handling errors as i described above and tests to check that a PR won't break the current implementation (it's included in the PR i just sent) is key for having a more robust implementation. 

also having a more stateless api than we have right now, things like getNumReceivedBytes, getLastError, setTimeout, setNonBlocking or anything that means tracking different states inside the object for every possible combination and call makes the implementation really hard to keep working properly since any minimal change anywhere else in the code makes it easy to break some other part

**Comment by bakercp** [comment]
Closing this with #4636.  @traumedy if these issues persist or the solution is insufficient, please reopen this issue or create a new one.  Thanks!
