### ISSUE TITLE
Emscripten error / Dont compile

### ISSUE THREAD

**Issue by Samsy** [openframeworks/openFrameworks#4607]
Latest emscripten version
Latest openframeworks version

Mac os Yosemite 10.10.5

error: Linking globals named '_ZN10ofxBaseGui21headerBackgroundColorE': symbol multiply defined!
Traceback (most recent call last):
  File "/Users/shonigstein/Downloads/emsdk_portable/emscripten/1.35.0/emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/Users/shonigstein/Downloads/emsdk_portable/emscripten/1.35.0/tools/shared.py", line 1471, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
make[1]: *** [bin/icoOF.html] Error 1
make: *** [Release] Error 2

**Comment by arturoc** [comment]
what's the example you are trying to compile? or if it's your own code can you post some more details about it? it seems there's a duplicated symbol in an ofxGui file but it's difficult to know what's going on without more details

**Comment by Samsy** [comment]
Yep sorry, It is my own code, I try to remove ofxGui and I tell you if it is working

**Comment by tpltnt** [comment]
@Samsy did it work?

**Comment by Samsy** [comment]
Yep it worked, OfxGUI is the problem ;)
