### ISSUE TITLE
OS X AppStore - FMOD issues and problems

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#4619]
As discussed in this PR . https://github.com/openframeworks/openFrameworks/pull/4615
### FMOD:

There are 4 current problems with FMOD when building for OS X (App Store).
- [x] 1. Using the **executable path** for the distribution location of fmod.dylib (this causes issues in validation).
- [x] 2. You must **code sign** all packaged dylibs / frameworks else failure (need to run a script on install to fix this).
- [x] 3. **Outdated fmod library** makes it impossible to validate app build post Xcode 7.0 (Fix only found in  4.44.59+ http://www.fmod.org/questions/question/error-submitting-app-with-fmod-designer-4-44-to-the-mac-app-store)
### Other Issues:
- [x] - You must **package the data folder** into the App Package (like iOS).
- [x] - Your application bundle must install to "**/Applications**"'. (currently set to $HOME/Applications)
- [x] - Must **remove all references to GLUT** and remove copying GLUT into application. (Using prohibited internal framework). 
- [x] - Must **remove references to QuickTime / QTKit**. (as it is deprecated and only 32bit)
- [x] - openFrameworks Lib must be set to **"Skip Install : YES"** (Else every archive of the project will be categorised into "Other Items" and not OSX Apps" in Organiser)

**Comment by danoli3** [comment]
Solutions:
1. Change the path to frameworks
```
rsync -aved ../../../libs/fmodex/lib/osx/libfmodex.dylib "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Frameworks/"; 
install_name_tool -change ./libfmodex.dylib @executable_path/../Frameworks/libfmodex.dylib "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/$PRODUCT_NAME";
```
2. Add a new script to automatically code sign the dylib on install
- Currently doing this:
```
codesign --entitlements exampleApp/exampleApp.entitlements -s "Mac Developer: Name (THEID493)" "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/MacOS/libfmodex.dylib"
```
However I have found a script someone wrote that does this automatically.
3. Update FMOD Ex to 4.44.59 for all platforms.
> Changelog 12/11/15 4.44.59 - Stable branch update (build 69790)
Mac - Fixed issue preventing FMOD Ex dylib from being accepted into the App Store due to missing LC_VERSION_MIN_MACOSX. We now build with a modern toolchain which causes the deprecation of PPC support.```

**Comment by danoli3** [comment]
Okay have a new code signing script:
```
# ---- Code Sign App Package ----
 
# WARNING: You may have to run Clean in Xcode after changing CODE_SIGN_IDENTITY!

# Verify that $CODE_SIGN_IDENTITY is set
if [ -z "${CODE_SIGN_IDENTITY}" ] ; then
echo "CODE_SIGN_IDENTITY needs to be set for framework code-signing"
exit 0
fi

if [ -z "${CODE_SIGN_ENTITLEMENTS}" ] ; then
echo "CODE_SIGN_ENTITLEMENTS needs to be set for framework code-signing!"

if [ "${CONFIGURATION}" = "Release" ] ; then
exit 1
else
# Code-signing is optional for non-release builds.
exit 0
fi
fi

ITEMS=""

FRAMEWORKS_DIR="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
echo "$FRAMEWORKS_DIR"
if [ -d "$FRAMEWORKS_DIR" ] ; then
FRAMEWORKS=$(find "${FRAMEWORKS_DIR}" -depth -type d -name "*.framework" -or -name "*.dylib" -or -name "*.bundle" | sed -e "s/\(.*framework\)/\1\/Versions\/A\//")
RESULT=$?
if [[ $RESULT != 0 ]] ; then
exit 1
fi

ITEMS="${FRAMEWORKS}"
fi

LOGINITEMS_DIR="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Library/LoginItems/"
if [ -d "$LOGINITEMS_DIR" ] ; then
LOGINITEMS=$(find "${LOGINITEMS_DIR}" -depth -type d -name "*.app")
RESULT=$?
if [[ $RESULT != 0 ]] ; then
exit 1
fi

ITEMS="${ITEMS}"$'\n'"${LOGINITEMS}"
fi

# Prefer the expanded name, if available.
CODE_SIGN_IDENTITY_FOR_ITEMS="${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
if [ "${CODE_SIGN_IDENTITY_FOR_ITEMS}" = "" ] ; then
# Fall back to old behavior.
CODE_SIGN_IDENTITY_FOR_ITEMS="${CODE_SIGN_IDENTITY}"
fi

echo "Identity:"
echo "${CODE_SIGN_IDENTITY_FOR_ITEMS}"

echo "Entitlements:"
echo "${CODE_SIGN_ENTITLEMENTS}"

echo "Found:"
echo "${ITEMS}"

# Change the Internal Field Separator (IFS) so that spaces in paths will not cause problems below.
SAVED_IFS=$IFS
IFS=$(echo -en "\n\b")

# Loop through all items.
for ITEM in $ITEMS;
do
echo "Signing '${ITEM}'"
codesign --force --verbose --sign "${CODE_SIGN_IDENTITY_FOR_ITEMS}" --entitlements "${CODE_SIGN_ENTITLEMENTS}" "${ITEM}"
RESULT=$?
if [[ $RESULT != 0 ]] ; then
echo "Failed to sign '${ITEM}'."
IFS=$SAVED_IFS
exit 1
fi
done

# Restore $IFS.
IFS=$SAVED_IFS
```

**Comment by danoli3** [comment]
CoreOF changes:
```
OF_CORE_FRAMEWORKS = -framework Accelerate -framework AGL -framework AppKit -framework ApplicationServices -framework AudioToolbox -framework AVFoundation -framework Cocoa -framework CoreAudio -framework CoreFoundation -framework CoreMedia -framework CoreServices -framework CoreVideo -framework IOKit -framework OpenGL -framework QuartzCore 
```

And remove ```LIB_GLUT =```

**Comment by danoli3** [comment]
Packaging the data folder into the App Resources folder:
```
rsync -avz --exclude='.DS_Store' "${SRCROOT}/bin/data/" "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/data/"
```

**Comment by danoli3** [comment]
@openframeworks/core What is the stance on removing GLUT ? QTKit and QuickTime from the coreOF.xconfig ? We could add a coreOFlegacy.xconfig with them in it if needed.

**Comment by ofTheo** [comment]
We would need to make OS Min be 10.8 ( thought it was 10.9 - but 10.8 has AVF ) but I think that would be okay. We should have done it for 0.9.0 as 10.7 is not a real OS ;)

**Comment by danoli3** [comment]
@ofTheo 0.10 OSX minimum is 10.9 though right so that change can go into 0.10 ;D

**Comment by dimitre** [comment]
@danoli3 I think this one can be closed

**Comment by danoli3** [comment]
only took 7 years :P
