### ISSUE TITLE
OF0.9 iOS, Cannot find protocol declaration for 'UIViewControllerTransitionCoordinator'

### ISSUE THREAD

**Issue by Meach** [openframeworks/openFrameworks#4627]
Hey guys,

I just grabbed OF0.9 for iOS, tried to compile the empty example and got this error:

> of_v0.9.0_ios_release/addons/ofxiOS/src/core/ofxiOSViewController.mm:307:77: Cannot find protocol declaration for 'UIViewControllerTransitionCoordinator'

I see that it's coming from this PR https://github.com/openframeworks/openFrameworks/pull/4381 and cannot find any information how to fix this. I use Xcode 6.1.1 and tried changing the SDK from 8.1 down to earlier version without any success.

**Comment by danoli3** [comment]
Yeah it seems that function was iOS 8+. Must have missed that one when merging that PR.

Once Travis passes this one I'll merge, it'll be fixed for the next nightly after that.
