### ISSUE TITLE
ofVideoPlayer cannot setup on Windows

### ISSUE THREAD

**Issue by micuat** [openframeworks/openFrameworks#4633]
When loading a video,

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L526

returns a fail value and aborts at line 678. If I comment out line 526 and uncomment line 529-540 like

        //this is the easier way to connect the graph, but we have to remove the video window manually
        //hr = m_pGraph->RenderFile(filePathW.c_str(), NULL);

        //this is the more manual way to do it - its a pain though because the audio won't be connected by default
        hr = m_pGraph->AddSourceFilter(filePathW.c_str(), L"Source", &m_pSourceFile); 
        if (FAILED(hr)){
            printf("unable to AddSourceFilter\n");
            tearDown(); 
            return false;
        }
        hr = ConnectFilters(m_pGraph, m_pSourceFile, m_pGrabberF);
        if (FAILED(hr)){
          printf("unable to ConnectFilters(m_pGraph, m_pSourceFile, m_pGrabberF)\n");
          tearDown(); 
          return false;
        }

then it aborts at line 539.

My environment is Windows 10 + Visual Studio 2015 + oF 0.9.0 release.

**Comment by micuat** [comment]
Never mind, I had to install k-lite codec pack as written on the IDE setup guide.

**Comment by arturoc** [comment]
This seems to be a really common issue, can we somehow detect that the codecs are not installed and show an error message explaining what's going on?

**Comment by DomAmato** [comment]
Sort of similar discussion we had a little ago when we first ran into this problem
https://github.com/openframeworks/openFrameworks/issues/4310

I'm not 100% sure you can detect the codec but if all non compatible codecs fail at the same spot we could probably throw an error or exception. OF error handling is usually more subtle than a flat out crash or error dialog but in this case it might be more informative than relying on people to read the installation guide.

**Comment by arturoc** [comment]
perhaps we could just print an message advicing to check if the codecs are installed if anything fails during load unless if it is some known error condition like a file that doesn't exist...

**Comment by ofTheo** [comment]
I added that in already I believe :)

**Comment by arturoc** [comment]
oh, ok yeah it's there already :)
