### ISSUE TITLE
Compile issue arm7 odroid xu4

### ISSUE THREAD

**Issue by bitSpaz** [openframeworks/openFrameworks#4634]
Howdy,
When trying to compile the"empty example" I get this error:

In file included from /home/odroid/of_v0.9.0/libs/openFrameworks/video/ofVideoPlayer.h:3:0,
                 from /home/odroid/of_v0.9.0/libs/openFrameworks/video/ofVideoPlayer.cpp:1:
/home/odroid/of_v0.9.0/libs/openFrameworks/utils/ofConstants.h:169:31: fatal error: bcm_host.h: No such file or directory
          #include "bcm_host.h"
                               ^
compilation terminated.

makefileCommon/compile.core.mk:239: recipe for target '/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Release/libs/openFrameworks/video/ofVideoPlayer.o' failed
make[2]: *** [/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Release/libs/openFrameworks/video/ofVideoPlayer.o] Error 1
makefileCommon/compile.core.mk:205: recipe for target 'Release' failed
make[1]: *** [Release] Error 2
make[1]: Leaving directory '/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/project'
/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: *** [Release] Error 2

Version 0.8.3. compiles.

Odroid XU4
Ubuntu-15.04-mate-odroid-xu3-20150710.img
of_v0.9.0.0 downloaded November 28 2015

Thanks

**Comment by jvcleave** [comment]
The RPi2 is the default platform variant for arm7 (since 0.9.0)

You will need to pass it in as a define

e.g.
```
make PLATFORM_VARIANT="generic"
```

**Comment by bitSpaz** [comment]
Hi Jason,
Thanks for the quick reply.
Could you provide an example?
So far everything I tried yields the bcm_host.h error .

Following the instructions in the readme.md:

cd  $(OF_ROOT)/libs/openFrameworksCompiled/Projects
make

then

make PLATFORM_VARIANT=generic

I also tried navigating to the empty example.
	• export MAKEFLAGS=-j8 PLATFORM_VARIANT=generic
then: 
make

As you might of surmised I’m new to this.

Thanks,

Barney

**Comment by jvcleave** [comment]
@bitSpaz your last post looks correct with the exception of the `Projects` location

try this

go into into your OF folder (where you unzipped OF into)
```
cd libs/openFrameworksCompiled/project
make clean
make PLATFORM_VARIANT=generic MAKEFILE_DEBUG=1
```

**Comment by bitSpaz** [comment]
@jvcleave
I followed your instructions, but the recipe failed.

Here are the (hopefully) relevant messages.

/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLProgrammableRenderer.h:20:7: note: ofGLProgrammableRenderer::ofGLProgrammableRenderer(const ofGLProgrammableRenderer&)
 class ofGLProgrammableRenderer: public ofBaseGLRenderer{
       ^
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLProgrammableRenderer.h:20:7: note:   candidate expects 1 argument, 0 provided
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLProgrammableRenderer.h:20:7: note: ofGLProgrammableRenderer::ofGLProgrammableRenderer(ofGLProgrammableRenderer&&)
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLProgrammableRenderer.h:20:7: note:   candidate expects 1 argument, 0 provided
/home/odroid/of_v0.9.0/libs/openFrameworks/app/ofAppGLFWWindow.cpp:159:53: error: no matching function for call to 'ofGLRenderer::ofGLRenderer()'
    currentRenderer = shared_ptr<ofBaseRenderer>(new ofGLRenderer);
                                                     ^
/home/odroid/of_v0.9.0/libs/openFrameworks/app/ofAppGLFWWindow.cpp:159:53: note: candidates are:
In file included from /home/odroid/of_v0.9.0/libs/openFrameworks/app/ofAppGLFWWindow.cpp:5:0:
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLRenderer.h:19:2: note: ofGLRenderer::ofGLRenderer(const ofAppBaseWindow*)
  ofGLRenderer(const ofAppBaseWindow * window);
  ^
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLRenderer.h:19:2: note:   candidate expects 1 argument, 0 provided
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLRenderer.h:17:7: note: ofGLRenderer::ofGLRenderer(const ofGLRenderer&)
 class ofGLRenderer: public ofBaseGLRenderer{
       ^
/home/odroid/of_v0.9.0/libs/openFrameworks/gl/ofGLRenderer.h:17:7: note:   candidate expects 1 argument, 0 provided
makefileCommon/compile.core.mk:239: recipe for target '/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/app/ofAppGLFWWindow.o' failed
make[2]: *** [/home/odroid/of_v0.9.0/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/app/ofAppGLFWWindow.o] Error 1
makefileCommon/compile.core.mk:213: recipe for target 'Debug' failed
make[1]: *** [Debug] Error 2
makefileCommon/compile.core.mk:229: recipe for target 'all' failed
make: *** [all] Error 2
odroid@odroid:~/of_v0.9.0/libs/openFrameworksCompiled/project$

Do they shed some light?

Thanks

**Comment by jvcleave** [comment]
Are you still trying to compile emptyExample or is this just the OF library? It looks like an error when trying to compile a pre-0.9.0 project

**Comment by bitSpaz** [comment]
The of_0.9.0 library.
The error messages I sent were produced when I executed: 
make PLATFORM_VARIANT=generic MAKEFILE_DEBUG=1

**Comment by jvcleave** [comment]
@arturoc 

should 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L157

look like

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L170

?

**Comment by arturoc** [comment]
yup

**Comment by jvcleave** [comment]
@bitSpaz you should be able to change those lines in your copy of OF to get further. It will be fixed for 0.9.1

**Comment by bitSpaz** [comment]
The #L157 version is missing the (this) reference, correct? I went to change mine and the (this) is there. In other words it looks very much like #L170
Thinking that there might be other inconsistencies I created a new ofAppGLFWWindow.cpp from #L170 and replaced the one in my distribution. This yielded the same error messages.

**Comment by jvcleave** [comment]
Line 159 is actually the one causing your error according to your log above. 

Currently both 157 and 159 should have `(this)`

**Comment by bitSpaz** [comment]
Progress! After I sorted out my confusion about which line to edit, OF compiles. There are problems with Shaders, however.

These errors occur with the emptyExample and the graphicsExample.

odroid@odroid:~/of_v0.9.0/examples/graphics/graphicsExample$ make run
HOST_OS=Linux
HOST_ARCH=armv7l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet

Thanks

**Comment by arturoc** [comment]
this should be fixed in latest master apart from adding (this) the line befor that should be

```cpp
if(settings.glesVersion>=2){
```

instead of


```cpp
if(settings.glesVersion>=1){
```

**Comment by bitSpaz** [comment]
@arturoc <https://github.com/arturoc> @jvcleave
Confirmed. That works! 
Thanks so much for tracking this down.
@bitSpaz <https://github.com/bitSpaz>
