### ISSUE TITLE
Symbol not found: __ZNSt12out_of_rangeD1Ev crash for libc++, OSX10.8

### ISSUE THREAD

**Issue by RVirmoors** [openframeworks/openFrameworks#4642]
Under MacOS 10.8 I get the following crash when launching my oF c++11 app:

> Dyld Error Message:
>  Symbol not found: __ZNSt12out_of_rangeD1Ev
>  Referenced from: [...my app]
>  Expected in: /usr/lib/libstdc++.6.dylib

(this doesn't occur in OS10.9+)
I've compiled openFrameworks.a in XCode with libc++, but it seems to have this leftover symbol from libstdc++ in a couple of places. A nm -grep search shows the following culprits containing the __ZNSt12out_of_rangeD1Ev symbol:

openFrameworks.a:ofUtils.o
openFrameworks.a:ofVbo.o
openFrameworks.a:ofParameterGroup.o
PocoData.a:RecordSet.o
PocoData.a:StatementImpl.o

Is there a way to remove this symbol or otherwise fix the crash?

**Comment by danoli3** [comment]
I'm not sure why any libstdc++ are in the Poco lib... however in the openFrameworks lib that's strange... Maybe you need to do a full clean of the project first.

**Comment by RVirmoors** [comment]
I also did it with a fresh install from the nightly OSX build, the oF lib ones are still there.

**Comment by bakercp** [comment]
Unfortunately, 10.8 is no longer supported.  That said, if you come up with a forward compatible solution, please submit a PR! Closing this issue.  Thanks.
