### ISSUE TITLE
OF 0.9.0 ofVideoPlayer OSX - setFrame/setPosition not working when paused / inconsistent behavior while playing

### ISSUE THREAD

**Issue by smidget** [openframeworks/openFrameworks#4651]
Hello,

OS: OSX 10.11.1

I'm encountering an issue getting the videoPlayerExample to work properly on OSX. Changing the playback speed works fine, as well as nextFrame/prevFrame. However, if I click and drag to scrub through the video, it does not work. It reports that it is on frame 150, and then on frame -inf. Then when I release the mouse, playback resumes at frame 0.

In testing, I built my own little video player. When the video is paused, calling setPosition or setFrame causes the video's position to go to -inf until it is unpaused. When the video is unpaused, it resumes from the beginning of the video. setPosition and setFrame work when the video is playing. However, when calling setPosition quickly several times in a row while the video is playing (like what the scrubbing is doing), the position also gets set to -inf and starts from the beginning of the video.

Any ideas for how to fix this issue?

Thanks!

**Comment by smidget** [comment]
After playing around with videoPlayerExample and ofAVFoundationPlayer.m part of the problem seems to be the usage of the tolerance kCMTimePositiveInfinity in the seekToTime method in ofAVFoundationPlayer.m. Changing this to kCMTimeZero allows the player to seek to the correct frame, albeit at what I understand to be a potentially costly performance hit depending on the video. 

I am still encountering issues while scrubbing with the video reporting the current time to be -inf, however I imagine that this is due to trying to read the time while the video is in the process of seeking.

**Comment by smidget** [comment]
OK so I think I've narrowed down the problem, but do not yet know how to fix it.

When a video is paused, the code path uses updateFromVideoOutput instead of updateFromAssetReader. If you then call seekToTime, the frame does not update ([self.videoOutput hasNewPixelBufferForItemTime:time] is false, so the method is skipped). Changing the code so that "updateFromAssetReader" is used when the current playback rate is >= 0 seems to fix this, but was there a reason updateFromVideoOutput was being used when rate == 0 that this could be breaking?

Unfortunately, this does not resolve the issue of the video's time going to -inf and then resetting to 0 when seekToTime is called too quickly. I'll keep playing around with it.

**Comment by i-n-g-o** [comment]
hi.
the reason using `updateFromVideoOutput` when available was to _not_ use the assetReader construction whenever possible and let the `AVPlayerItemVideoOutput` do it's magic setting the time and getting the frame.

the assetReader construction performs more stable when playing back (due to its frame-buffering), in stepping mode it is a pain though.

i think we might just take the `rate == 0` into account when seeking to a time...

**Comment by i-n-g-o** [comment]
in `seekToTime` the last thing done is to set the time in the player.
in `updateFromVideoOutput` the currentTime is taken from the player.
testing with the finger movie in paused mode and do some setPosition(seekToTime) works for me...

do you have an example illustrating the problem?

**Comment by talaron** [comment]
I experienced the same thing than @smidget 
setPosition seems to be able to seek only specific steps in the video.
With moviePlayerExample ann hands.m4v it's jumping from 0 to 6sec, then 10 seconds, but nothing between.

**Comment by jvcleave** [comment]
Are you only getting this with H.264 video? In my experience, scrubbing/seeking doesn't work very well due to the nature of the format. Compressing it with a keyframe every frame can help

**Comment by talaron** [comment]
Yes thank you, it's perfect now.
I did set keyframe interval to 1 and now seeking is accurate.
I would propose to set the same compression preset to "hands.m4v" video in moviePlayerExample

**Comment by jvcleave** [comment]
@talaron the problem with that is that the file is much larger. Maybe when we figure out how to reduce the repo size/binaries.

**Comment by ofTheo** [comment]
@talaron @i-n-g-o  can we close this issue now or are there code changes that are needed before we put out the 0.9.1 release? 

Thanks!!
Theo

**Comment by i-n-g-o** [comment]
@ofTheo i did not make code changes for this ticket. also never could verify the problem.
it's fine for me to close it.

**Comment by talaron** [comment]
In my case, adding x264 compression parameter "keyint=1" to have more keyframes let me scrub perfectly in the video. 
Fine to close it for me

**Comment by winduptoy** [comment]
This silly hack worked for me, even with H.264 with irregular keyframes.

```c++
void skipFrames(int frames) {
	unsigned int currentFrame = mPlayer.getCurrentFrame();
	
	if(frames > 0) {
		for(unsigned int i = currentFrame; i < currentFrame + frames; i++) {
			mPlayer.nextFrame();
		}
	} else if(frames < 0) {
		for(unsigned int i = currentFrame; i > currentFrame + frames; i--) {
			mPlayer.previousFrame();
		}
	}
	
	mPlayer.setPaused(true);
}
```
