### ISSUE TITLE
Minor fix : scale(float)

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4668]
We use a single float to represent universal scale in a number of places (e.g. `ofDrawXXX(float)`), but `ofScale` always asks for 3 parameters.

As far as I can imagine, applying the scale in all 3 dimensions isn't an issue for 2D use (and I can see it being useful there too).

I can't recollect right now if there's any effective reasoning for not having this

**Comment by mattfelsen** [comment]
+1, I often find myself typing `ofScale(float)` before getting a compile error and remembering I have to do `ofScale(float, float)`
