### ISSUE TITLE
ofDirectShowPlayer can't load a movie if the width/height of the movie are not divisible by 4.

### ISSUE THREAD

**Issue by motoishmz** [openframeworks/openFrameworks#4679]
Discussion on forum.openframeworks.cc:
https://forum.openframeworks.cc/t/ofdirectshowplayer-cant-load-uncommon-width-height-movies/21740

Solution for this problem:
https://gist.github.com/yoggy/df598c31bd3a74df10a0/revisions

[ofDirectShowPlayer::setPixelFormat()](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L1181) looks strange because it sets anything. `ofDirectShowPlayer::pixelFormat` should be used as a hook for switching RGB24/RGB32 in `DirectShowVideo::loadMovie()` and `processPixels::processPixels()` ?

Thanks,
Motoi

**Comment by ofTheo** [comment]
Thanks @motoishmz  

I guess the only issue would be the change from pixels being in a RGB format to an RGBA format. 
Would we manually strip the alpha out so as not to break existing code? 

Or just allow it do be 4 bytes per channel and let users deal with it via the higher level existing ofPixels queries.
