### ISSUE TITLE
ofSetOrientation OF_ORIENTATION_90_RIGHT/LEFT won't go fullscreen

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4682]
It looks like its trying to set the Window Width to the Window Height and vice versa. 

This is because ofAppGLFWWindow::getScreenSize();  swaps the width and height based on the orientation, but the fullscreen code doesn't account for orientation when setting fullscreen. 

see getScreenSize(): https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L477 

and setFullscreen():
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L693

This looks like it could be an issue for all platforms. 
Also potentially an issue when restoring the window shape from fullscreen too.

**Comment by ofTheo** [comment]
What looks like a fix is to disable the swapping of width / height sizes in 

getScreenSize():
 https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L477

Not sure if screen dimensions ( as well as window dimensions ) should be rotated based on OF_ORIENTATION.  In ofAppGlutWindow we did do screen dimensions swapping too, but the GLUT fullscreen code didn't need as much explicit info so we never had to swap x/y based on orientation. 

I feel like the screen dimensions should not rotate with orientation as that is something outside of the OF world context.  Also we're assuming in our fullscreen code that these coords are not rotated. 

Curious what people think.

Happy to do a PR to patch this. 
- We either need to rotate all our coords in our fullscreen code based on orientation.  That would be a fair bit of changes for all platforms. 
- Or not rotate our screen size in getScreenSize() and I think then it would fix all platforms. 
  ( we would just need to rotate the game mode queries here: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L518 )

**Comment by arturoc** [comment]
can't we just re-swap the coordinates in the code that does fullscreen if the orientation is one of the 90 degrees?

**Comment by ofTheo** [comment]
yeah for sure - I can do a PR for it.
