### ISSUE TITLE
ofParameterGroup.h empty, definitions in ofParameter.h, but implementation in ofParameterGroup.cpp

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4688]
This file structure is a bit confusing.  

I haven't dug into it, but I'm assuming it was done this way to make the extensively templated types compile more easily?  Would it be possible move the `ofParameterGroup` class definition into `ofParameterGroup.h`?

**Comment by arturoc** [comment]
yes, there's interdependencies between ofParameter and ofParameterGroup in templated functions so they can't be in the .cpp and having them in different .h was producing recursive include problems that couldn't be solved with forward declaration.

i left the empty ofParameterGroup.h cause it was late in the release cycle and didn't want to redo the project files for all platforms but will look into it for 0.10
