### ISSUE TITLE
xcode7 oF 0.9.0 , libc++ issues? No member named 'forward_as_tuple' in namespace 'std::__1' ??

### ISSUE THREAD

**Issue by sterlingcrispin** [openframeworks/openFrameworks#4693]
[log (3).txt](https://github.com/openframeworks/openFrameworks/files/72554/log.3.txt)

I've been trying to get this open frameworks voxel plugin ( https://github.com/weshoke/ofxOpenVDB )  working on my machine and I can't get around this error and I really can't figure out why

No member named 'forward_as_tuple' in namespace 'std::__1' 

I tried to recompile ofxOpenVDB for libc++ ( https://github.com/sterlingcrispin/ofxOpenVDB ) assuming that would fix this issue but it didn't

**Comment by arturoc** [comment]
have you tried recreating the project file with the project generator? this seems a c++11/c++03 issue

**Comment by ofZach** [comment]
also, are you compiling and older project file?  (I've seen similar c++11 issues when using an older project in newer OF / 0.9.  sometimes they can be fixed by altering the SDK target)

**Comment by sterlingcrispin** [comment]
Hey, yes I used the project generator to create a new project and include the plugin

I just tried with Cinder and I can include the header files and compile an openVDB program from there so I don't think the problem is with the underlying library

**Comment by ofZach** [comment]
if you want to see exactly what is happening on the compile side, you can show the report navigator and then expand any of the steps of the build -- I find it super useful to see the actual commands and parameters that go into compiling and linking. 

<img width="1388" alt="screen shot 2015-12-29 at 5 19 54 pm" src="https://cloud.githubusercontent.com/assets/142897/12043192/98c8996a-ae50-11e5-9fb9-9c97b88e244b.png">

**Comment by ofZach** [comment]
(if you don't see what you are looking for...  maybe this will help ?   http://stackoverflow.com/questions/5584435/how-to-print-dependencies-from-llvm-clang-equivalent-of-gcc-md -- you might copy the command from xcode (ie, the long string above) and then change it to list dependencies)

**Comment by arturoc** [comment]
also that addon seems like it hasn't been updated in 2 years so probably using a newer version of the library will fix the problem

**Comment by sterlingcrispin** [comment]
@arturoc as I mentioned I did recompile the underlying libraries, which was part of it

@ofZach I modified that from -MMD to -MD and found that it was linking against my local copy of boost which is version 105900 rather than open frameworks boost version 105700 

I noticed in oF there's two versions of boost, why is that?

libs/boost/include/boost   (version 105700)
libs/boost/include/OFXboost    (version 105800)

**Comment by arturoc** [comment]
i meant updating the library itself to a newer version not only recompile it but i guess you did that too.

i don't see that version of boost you mention in our source: https://github.com/openframeworks/openFrameworks/tree/master/libs/boost

**Comment by sterlingcrispin** [comment]
My mistake that duplicate folder of boost was my own doing,

@ofZach I copied the command from Xcode and changed it from -MMD to -MD and did a diff comparing a working example that has no files in addons/ofxOpenVDB/libs/ but has  /opt/local/include into my header search path,  against a project that wont compile but has copies from all the relevant libraries from opt/loca/include copied to addons/ofxOpenVDB/libs/ without /opt/local/include in the header search path

these are the files being linked in the main.d file that weren't in the version that can't compile, the crash log makes it seem like its just not finding the lbc++ library, but I'm kind of at my wits end with this. I've got a way to run ofxOpenVDB and openVDB in general on my laptop by using /opt/local/include but that doesn't fix ofxOpenVDB and make it distributable for other people. 
[log_ofxopenvdb.txt](https://github.com/openframeworks/openFrameworks/files/75846/log_ofxopenvdb.txt)


/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/MDImporter.h \		
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/MDItem.h \		
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/MDLabel.h \		
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/MDQuery.h \		
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/MDSchema.h \		
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Headers/Metadata.h \

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h \
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/condition_variable \
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread \		
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/tuple \

**Comment by jeonghopark** [comment]
It's a just information.
I have tried a other "of_64bit" git version. It's working at os 10.11, Xcode 7.0. And it should be "Carbon Frameworks" of osx.
@sterlingcrispin Maybe you can find other solution.

https://github.com/incredibleMachines/oF_64bit/tree/3656a95cba4c3b32909d73e9cd861f3bf712c1c8

![screen shot 2016-01-03 at 15 53 12](https://cloud.githubusercontent.com/assets/558046/12079269/fb91809e-b232-11e5-82b6-e0b5269847f9.png)

**Comment by sterlingcrispin** [comment]
Isn't the zip on the downloads page already 64 bit?http://www.openframeworks.cc/versions/v0.9.0/of_v0.9.0_osx_release.zip 

I've got a copy working on my machine with of v0.9.0 osx 10.11 Xcode7 and that was my goal, I'm not sure why I can't bundle the required libraries into a distributable package for others to use but at this point I've spent a month messing with this and I can't keep debugging it

**Comment by ofZach** [comment]
sorry I am not 100% sure what you are asking for help with.   (also, it's been holidays over here so I am just getting caught up).  Can you please clarify?   0.9.0 builds the openframeworks library as 32 and 64 bit at once (ie, a universal lib) and you can choose whether you want your app to be 32 bit or 64 bit.

<img width="396" alt="screen shot 2016-01-03 at 5 04 23 pm" src="https://cloud.githubusercontent.com/assets/142897/12081045/203188b4-b23c-11e5-845d-977074319616.png">

we're here to help, it's just not clear what you are having trouble with exactly.

**Comment by sterlingcrispin** [comment]
@jeonghopark that version of openframeworks you linked doesn't include boost, and it won't compile the example without it. Did you link to a local copy of boost? Also, do you mean to add Carbon.framework into the "Link Binary with Libraries" section of Xcode ?

@ofZach I appreciate all your input - I know that oF can be built with 64 bit - which is why @jeonghopark confused me, why is that incredibleMachines version of openframeworks 64 bit any different, why should it compile this library while the 64bit 0.9.0 fails? As I said I just tried and it didn't work out.

Zach if you wanted you could help by downloading a fresh copy of 0.9.0 and either of these and see if you can run the example without too much headache. Maybe my laptop is a special case but the only way I can use ofxOpenVDB is to add /opt/local/include/ to my user search paths and have all the necessary libraries installed via macports. VDB is a cool addon for oF because of its efficiency at converting volumes/points to meshes. I'm writing lots of functions that make it easier to use and I'd contribute them back to the community if I knew other people could use it.

libstd++ openvdb 2.1 https://github.com/weshoke/ofxOpenVDB
libc++ openvdb 3.2  https://github.com/sterlingcrispin/ofxOpenVDB

**Comment by ofZach** [comment]
ok - this is really an addon issue and not an OF issue per se, can we close this and take the conversation over there?  I'm happy to help and I have done a little sleuthing, and I can see the problem...

**Comment by ofZach** [comment]
I have added some info here: 

https://github.com/weshoke/ofxOpenVDB/issues/1

going to close this issue (but I do think it should require a separate conversation about our xcode settings, etc)

**Comment by jeonghopark** [comment]
@sterlingcrispin Right. The incredibleMachines version ([https://github.com/incredibleMachines/oF\_64bit/tree/3656a95cba4c3b32909d73e9cd861f3bf712c1c8]) doesn’t include boost. I already installed the boost in ‘/usr’. So i could compiled a example of openVDB in weshoke version.

And i added the carbon.frameworks into the "Link Binary with Libraries" section.
