### ISSUE TITLE
Multi window fullscreen broken on current master. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4698]
If you enable setMultiDisplayFullscreen on OS X via the window pointer it doesn't end up being set. 

If you do ofCreateWindow with settings and then cast the returned window to a ofAppGLFWWindows shared_ptr it works . 

Also this seems like an incorrect deprecation as there isn't : 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.h#L140

```
	OF_DEPRECATED_MSG("use ofGLFWWindowSettings to create the window instead", void setMultiDisplayFullscreen(bool bMultiFullscreen)); //note this just enables the mode, you have to toggle fullscreen to activate it.
```

Looking into this more. 
Its also confounded for me by issues with retina displays mixed with non retina displays.

**Comment by arturoc** [comment]
you should be able to do:

```
ofGLFWWindowSettings settings;
settings.multiMonitorFullScreen = true;
ofCreateWindow(settings);
```

**Comment by ofTheo** [comment]
@arturoc ah missed that it needed to be ofGLFWWindowSettings and not ofGLWindowSettings - makes sense - thanks! 

Working on a fix for the rest of this.

**Comment by ofTheo** [comment]
The problem is if you use the old approach, any settings you set like this:
```
    ofAppGLFWWindow * win = new ofAppGLFWWindow();
    win->setMultiDisplayFullscreen(true);
	ofSetupOpenGL(win, 1024,768, OF_WINDOW);			// <-------- setup the GL context
```

get overridden by this function which provides legacy support:

```
template<typename Window>
void ofSetupOpenGL(shared_ptr<Window> windowPtr, int w, int h, ofWindowMode screenMode){
	ofInit();
	ofWindowSettings settings;
	settings.width = w;
	settings.height = h;
	settings.windowMode = screenMode;
	ofGetMainLoop()->addWindow(windowPtr);
	windowPtr->setup(settings);
}
```

This works however: 

```
template<typename Window>
void ofSetupOpenGL(shared_ptr<Window> windowPtr, int w, int h, ofWindowMode screenMode){
	ofInit();
	auto settings = windowPtr->getSettings(); 
	settings.width = w;
	settings.height = h;
	settings.windowMode = screenMode;
	ofGetMainLoop()->addWindow(windowPtr);
	windowPtr->setup(settings);
}
```

Though it requires all implemented windows to have a getSettings() function. 

There might be a better way to do it - ideally we would just be changing the .width / .height and .windowMode of the current settings rather than overwriting them.  But as the settings are a different class per window type it makes it trickier

**Comment by arturoc** [comment]
we could just specialize the template for ofAppGLFWWindow since it's the only one which has this kind of methods i think and then remove them for 0.10 and only allow those kind of settings through the settings object.

you just need to add:

```
template<>
void ofSetupOpenGL(shared_ptr<ofAppGLFWWindow> windowPtr, int w, int h, ofWindowMode screenMode){
    ofInit();
    auto settings = windowPtr->getSettings(); 
    settings.width = w;
    settings.height = h;
    settings.windowMode = screenMode;
    ofGetMainLoop()->addWindow(windowPtr);
    windowPtr->setup(settings);
}
```

the `template<>` might not be necessary

**Comment by ofTheo** [comment]
awesome! that seems like a good solution. 
thanks!!! :)

**Comment by ofTheo** [comment]
@arturoc that approach seems to work well. 
If PR #4702 looks good - please merge.
