### ISSUE TITLE
Really strange issue with OpenGL and scale on second monitor. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4703]
This seems to be a regression since 0.9.0 
On my laptop if I move the window to the second monitor the coordinate system and scale completely changes. 

The example code for replicating is really simple:

```
//--------------------------------------------------------------
void ofApp::draw(){
    ofSetColor(0, 255, 0);
    ofDrawCircle(0, 0, 100);

    ofSetColor(255, 255, 0);
    ofDrawCircle(ofGetWidth(), 0, 100);

    ofSetColor(0, 0, 0);
    ofDrawCircle(ofGetMouseX(), ofGetMouseY(), 50);
}
```

On my laptop screen ( which is a retina MBP ) 
<img width="1138" alt="screen shot 2015-12-28 at 2 59 55 pm" src="https://cloud.githubusercontent.com/assets/144000/12024641/089cae1c-ad74-11e5-87da-be415a93abe6.png">

The black circle is where my mouse is. 

When I move the window to the second monitor the view switches and with my mouse in the center the black circle is in the top right corner while the other two circles disappear. 

![screen shot 2015-12-28 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/144000/12024644/150816a0-ad74-11e5-8bc1-913fb72ae156.png)

I'm guessing this is something to do with the pixelScreenCoordScale in ofAppGLFWWindow?
Did anything change since 0.9.0 ?

**Comment by ofTheo** [comment]
my guess is pixelScreenCoordScale is now being applied to the GL viewport whereas in 0.9.0 it wasn't. 

In 0.9.0 if I have a window of 1920x1080 this: draws a circle that takes up the window height. 
    ofDrawCircle(ofGetMouseX(), ofGetMouseY(), 1080/2);

With the current master 
    ofDrawCircle(ofGetMouseX(), ofGetMouseY(), 1080/2); 

the circle is half as big.

**Comment by ofTheo** [comment]
hmm - this looks like it came from having:
the High Resolution Capable flag set in the plist - not sure how it got enabled. 
this has the same affect on 0.9.0 so its not a regression. 

The problem is that when it moves from one window to the other the pixelScreenCoordScale needs to be recalculated. 

I can do a PR for this but I am going to push it back to 0.10.0

**Comment by valillon** [comment]
Same behavior detected in 0.9.8.
I managed a rapid workaround by refreshing `pixelScreenCoordScale` in class `ofAppGLFWWindow` like:
```cpp
/* ofAppGLFWWindow.h */
void refreshWindow(int scale) {pixelScreenCoordScale = scale;}

/* ofApp.h */
float screenCoordScale;

/* ofApp.mm */
void ofApp::setup() 
{
    // ...
    screenCoordScale = (float)[[NSScreen mainScreen] backingScaleFactor]; 
}
void ofApp:update() 
{
    CGFloat scale = [[[NSApplication sharedApplication] mainWindow] backingScaleFactor];
    if (scale != screenCoordScale)
    {
        ((ofAppGLFWWindow*)ofGetWindowPtr())->refreshWindow((int)scale);
        screenCoordScale = scale;
        // refresh your view here;
    }
    // ...
}
```
Note `ofAppGLFWWindow::getPixelScreenCoordScale()` returns the scale factor found at launch time, it do not change over time and `[[NSScreen mainScreen] backingScaleFactor]` does not updates scale factor after the dragged window is completely released on the screen.

Similar solution could be done inside `ofAppGLFWWindow::update()` so that the user would not take care of that. Anyone can commit a fix on the main branch for this?

**Comment by valillon** [comment]
Hi, anyone on this?

**Comment by kritzikratzi** [comment]
i tried the following change in OF0.9.3 and so far it seems to do what i want: 

```
//------------------------------------------------------------
void ofAppGLFWWindow::resize_cb(GLFWwindow* windowP_,int w, int h) {
	ofAppGLFWWindow * instance = setCurrent(windowP_);
	instance->windowW = w;
	instance->windowH = h;
	
	// hansi:
	// handle scale changes correctly?
	int framebufferW, framebufferH;
	glfwGetFramebufferSize(windowP_, &framebufferW, &framebufferH);
	instance->pixelScreenCoordScale = framebufferW / w;
	
	
	instance->events().notifyWindowResized(w*instance->pixelScreenCoordScale, h*instance->pixelScreenCoordScale);
	instance->nFramesSinceWindowResized = 0;
	instance->draw();
}
```

**Comment by tgfrerer** [comment]
Thanks, @kritzikratzi, that's a great find! I've found another edge case, which the pull request above covers.

**Comment by kritzikratzi** [comment]
ah, one more thing. i don't have a windows computer nearby, but i'm wondering if `pixelScreenCoordScale` being an int is a problem. i know their dpi sliders allow tons of different scalings. no clue what happens exactly on windows, just adding some worries :)

**Comment by tgfrerer** [comment]
@kritzikratzi it should be fine, otherwise we'd have seen strange things happen on windows machines with different pixel scale, as pixel scale is applied on startup of a window as well. There's a separate issue related to getting the window back to its original size once it comes back from fullscreen on hidpi monitors, for which i will open a separate issue, and send a PR once i've wrapped my head around it.

**Comment by valillon** [comment]
Back again... I detected and issue with ofxGui related to this on the master OF branch (OF 0.10 PR). When moving the GUI from the non-retina display to the retina display, the GUI is not responding anymore. It seems the coordinate system is tangled. Curiously, moving the window the other way around (to the non-retina display) the GUI's response is unaffected.
