### ISSUE TITLE
ofCamera::screenToWorld is incorrect

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4712]
ofCamera::worldToScreen works correctly, as shown by `pointPickerExample`. but running `worldToScreen` followed by `screenToWorld` does not result in the original point:

```c++
#include "ofMain.h"

class ofApp : public ofBaseApp {
public:
    void setup() {
        ofCamera cam;
        cam.setupPerspective();
        ofVec2f point(10, 20);
        ofLog() << point;
        ofVec2f world = cam.screenToWorld(point);
        ofLog() << world;
        ofVec2f screen = cam.worldToScreen(world);
        ofLog() << screen;
    }
};
int main() {
    ofSetupOpenGL(1280, 720, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

Output:

```
[notice ] 10, 20
[notice ] 1028.51, 858.614
[notice ] 1028.51, 581.386
```

Expected output:

```
[notice ] 10, 20
[notice ] 1028.51, 858.614 (looks incorrect?)
[notice ] 10, 20
```

**Comment by ofZach** [comment]
I think screen to world gives you a z value you are loosing here.  I rewrote your example: 

    ofCamera cam;
    cam.setupPerspective();
    ofPoint point(10, 20);
    ofLog() << point;
    ofPoint world = cam.screenToWorld(point);
    ofLog() << world;
    ofPoint screen = cam.worldToScreen(world);
    ofLog() << screen;

[notice ] 10, 20, 0
[notice ] 412.594, 456.079, 533.403
[notice ] 9.99991, 20.0002, 0

**Comment by kylemcdonald** [comment]
oh wow, that's absolutely the problem. @elliotwoods please feel free to make fun of me. thanks zach :)
