### ISSUE TITLE
is disconnectionAutoDetection correct test?

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#4715]
when i pushed to branch related to PR, ci-travis is failed at test/networkTcp/disconnectionAutoDetection.
https://github.com/openframeworks/openFrameworks/pull/4338
https://travis-ci.org/openframeworks/openFrameworks/jobs/100523116

but, other PRs around the above don't failed.
of course, i don't edit about ofxTCPClient in this branch.

does anyone know why...?

**Comment by arturoc** [comment]
yes this is a problem with running the network tests on the test servers, it seems that opening sockets there is not very reliable and sometimes it fails, i need to look into it to add some kind of test that only fails if it fails consistently over several tries.

i've just restarted the tests on your PR which usually solves the problem

**Comment by 2bbb** [comment]
@arturoc 
okay, i understand.
thanks!

**Comment by 2bbb** [comment]
oh...?
does ci-travis use hash (or other?) to seed?
#4338 failued in same place...

**Comment by 2bbb** [comment]
make sure.
#4733
