### ISSUE TITLE
ofxGui crashes ofTessellator::performTessellation with ofParameter<float> 

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4717]
It's a bit obscure but thought I would report 

if you create an `ofParameter<float>` and add it to ofxPanel, and try and change the value it will crash the app (tested on Mac desktop)

I think the problem may be that the range between `ofParameter <float>` min and max is too large to draw? 

```
#pragma once

#include "ofMain.h"
#include "ofxPanel.h"

class ofApp : public ofBaseApp{
    
public:
    ofxPanel panel;
    ofParameter<float> floatParam;
    void setup()
    {
        floatParam.set("test", 1000.0f);
        panel.setup();
        panel.add(floatParam);
    }
    void draw()
    {
        panel.draw();
    }  
};
```

**Comment by jvcleave** [comment]
![image](https://cloud.githubusercontent.com/assets/150037/12179433/d1ccbd4a-b544-11e5-81fc-885c8594c588.png)

**Comment by arturoc** [comment]
yes i've seen this i think the problem i thought the problem was that the tesselation library wasn't compiled with -NDEBUG which removes the asserts but that's a seg fault not an assert so not sure, will try to replicate it.

**Comment by jvcleave** [comment]
cool - with `ofParameter<int>` it is fine

**Comment by kritzikratzi** [comment]
possibly not directly related, but this exact error comes up when a single tesselator is used from multiple threads (eg converting ofPath to ofMesh from worker threads). but if it was the problem, i'm not sure why it would be fixed when using ofParameter<int> instead.

**Comment by arturoc** [comment]
the tessellator is not thread safe so using it from different threads will surely produce a seg fault but this is not related. also ofPath right now creates a tesselator per thread wherever thread local storage is available (not in osx) and one per path when it's not so unless you use the same path from different threads it should be ok

**Comment by danoli3** [comment]
@arturoc @ofTheo We almost ready for a 0.9.1 release then?!

**Comment by arturoc** [comment]
@danoli3 you can check the remaining issues here: https://github.com/openframeworks/openFrameworks/milestones/0.9.1  but yes it's almost done

**Comment by arturoc** [comment]
i've changed the range for floats to 0..1 instead of lowest..max which is also a more reasonable range for real numbers.

**Comment by ofTheo** [comment]
@arturoc - could that break existing projects?
And just to be clear the change is for the default min and max values if they aren't set explicitly?

**Comment by arturoc** [comment]
yes this is only in case they are not set, the previous values didn't make any sense, the default was the lowest and max values of float which are around -1e+38 .. 1e+38 which i doubt anybody was using, anyone not setting values was probably just not using the range. 0..1 is something that can make sense in a lot of use cases with real numbers

**Comment by ofTheo** [comment]
yeah was just thinking about it - if people aren't setting the min and max and then using sliders, its going to be basically not working as it currently is.

**Comment by jvcleave** [comment]
The way I "fixed" it was to just set the min/max to the value. I figured that way the min couldn't be larger than the value, or the max less
