### ISSUE TITLE
latest msys download not working

### ISSUE THREAD

**Issue by kritzikratzi** [openframeworks/openFrameworks#4719]
msys download is currently not working because of #4559 
the issue was fixed on nov 11, but the latest download package is from nov 8.

**Comment by tpltnt** [comment]
I am able to reproduce the issue. You can try a [nightly build](http://openframeworks.cc/download/) or wait until 0.9.1 ships (soon). How urgent is the issue?

**Comment by arturoc** [comment]
i'm going to close this since it's already fixed
