### ISSUE TITLE
makefiles for msys2 not copying export libraries

### ISSUE THREAD

**Issue by kritzikratzi** [openframeworks/openFrameworks#4720]
the current msys2 version doesn't copy the export libraries, so `make run` fails. 
not sure what's the best way to go about this. locally i fixed it by adding a line to the `afterplatform` task. 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/msys2/config.msys2.default.mk#L292

```
cp -r $(OF_EXPORT_PATH)/$(ABI_LIB_SUBPATH)/* bin/
```

**Comment by oxillo** [comment]
@arturoc @bakercp : This issue is solved by the copy_dlls task. 
It may be closed.
