### ISSUE TITLE
ofVideoPlayer doesn't work with ofDisableArbTex() set OS X 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4722]
From the forum: 
https://forum.openframeworks.cc/t/ofvideoplayer-and-ofdisablearbtex/22033

On OS X I could see how it might break with the new AVFoundation player using its own texture cache. 
Might mark this for 0.9.2 or 0.10.0 - but if we can easily fix it before then thats fine. 

Edit: misread the post - this isn't an issue on Windows.

**Comment by ofTheo** [comment]
ping @prisonerjohn 
I think a really simple fix for this is to disable the texture cache if not using ARB. 

```
bool ofAVFoundationPlayer::loadPlayer(string name, bool bAsync) {
	if( ofGetUsingArbTex() == false ){
		killTextureCache();
		bTextureCacheSupported = false; 
	}
```

Then it uses the ofVideoPlayer texture instead and that handles all the non ARB stuff correctly. 
Could you see if that works for you okay - it seems to work fine for me here?

Thanks!
Theo

**Comment by prisonerjohn** [comment]
Is `bTextureCacheSupported` something you added in? Do you just skip the CoreVideo calls if it's false?

**Comment by prisonerjohn** [comment]
It's working fine for me without that flag:

```
bool ofAVFoundationPlayer::loadPlayer(string name, bool bAsync) {
    if( ofGetUsingArbTex() == false ){
        killTextureCache();
    }
```

I'll go ahead and close that PR.

**Comment by ofTheo** [comment]
@prisonerjohn ahh that is something from a RC version of 0.9.0 - I'll work with the current master and double check the fix there.

But yes the idea is that all the video texture calls don't get executed and instead the ofVideoPlayer sees that the ofAVFoundationPlayer doesn't have a texture so it makes one correctly using the non ARB approach.
