### ISSUE TITLE
Default OSX file encoding is "Western" instead of "UTF-8"

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4728]
This means that when I write some code that has comments or text in UTF-8, like this:

<img width="366" alt="after" src="https://cloud.githubusercontent.com/assets/157106/12322646/ca063ab4-baf8-11e5-9101-7d753a68f229.png">

And then I generate a new project file with the project generator, it turns into this:

<img width="429" alt="before" src="https://cloud.githubusercontent.com/assets/157106/12322664/d65e7eac-baf8-11e5-86fe-3629aeec1a02.png">

But if I change the encoding and use "Reinterpret", then it is correct again:

<img width="230" alt="screen shot 2016-01-14 at 19 16 47" src="https://cloud.githubusercontent.com/assets/157106/12322674/e4bcd818-baf8-11e5-9c05-0087ea37cd26.png">

<img width="447" alt="screen shot 2016-01-14 at 19 16 51" src="https://cloud.githubusercontent.com/assets/157106/12322677/e99eced6-baf8-11e5-8331-0f122a06d3f1.png">

**Comment by ofTheo** [comment]
I don't see a reason why we shouldn't use UTF-8 as the default. 
Do you know if this would be simply changing the template Xcode file - or changing every single ofApp.cpp/.h and ofMain.cpp ?

**Comment by arturoc** [comment]
i think the code files are already in utf8, that's the default in linux and i've never had any issues with international text from the encoding of the files when working on the utf8 port for ofTTF

**Comment by kylemcdonald** [comment]
Yes afaict changing the XXode template will solve this problem. Good to
know Arturo hasn't had problems with the equivalent settings on Linux.

**Comment by ofZach** [comment]
noted on the PG issue but changing this line should help for the PG (it's setting the encoding on added src files to western, should be utf-8): 

https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L56-L57

**Comment by 2bbb** [comment]
:+1:

**Comment by bakercp** [comment]
Fix submitted.
