### ISSUE TITLE
ofTrueTypeFont/ofBitmapFont: bounding box width of empty strings should be 0

### ISSUE THREAD

**Issue by fx-lange** [openframeworks/openFrameworks#4730]
when calculating bounding boxes of an empty strings for ofTrueTypeFont or ofBitmapFont the width and height is negative ( = std::numeric_limits<float>::min() ). 

the width should be 0 and the height probably should also be 0 too (or maybe equal to the actual line height?).

**Comment by fx-lange** [comment]
I guess it is the same for x & y of the returned bounding box ...

**Comment by arturoc** [comment]
this probably comes from the initialization to min for doing the calculation for the bounding box. can you send a PR? it should just be comparing the final value at the end and set to 0 if it's equal to numeric_limits::min
