### ISSUE TITLE
ofTexture - can't find out if mipmaps already exist or not

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#4732]
I see enableMipmap(), disableMipmap() and generateMipmap(). None of them provide info regarding the existence of the mipmap.

getTextureData() could work, but "hasMipmap" is defined as private... Maybe its just a matter of making this public? Otherwise adding a method hasMipmap() to ofTexture could work too.

**Comment by tgfrerer** [comment]
Hi Oriol,

it might be a matter of adding a const getter for hasMipmap, yes.

I implemented the mipmap methods a while ago and can't remember if there was any particular reason for leaving the getter out, but off the top of my head can't think of anything that would speak against having it.

Can look into it tomorrow. Or maybe you want to send a PR? =)

Cheers
#

Tim

typed on tocuh

**Comment by armadillu** [comment]
ok! Ill send a PR with the getter

**Comment by armadillu** [comment]
PR ready
