### ISSUE TITLE
error message for all AVF video players on draw when the first frame is not ready. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4743]
Right now all videos will give you this error messages on OS X when you try and draw them until the video has the first frame come in which usually takes a few frames after load. 

`
[ error ] ofTexture: getTextureData(): texture has not been allocated
`

So even the videoPlayer example dumps out a bunch of these errors on launch. 
A simple fix would be to add something in the line below here:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofGLRenderer.cpp#L362

Where it checks if the texture has been allocated before trying to draw. 
We would need to add it for the programmable renderer too - but it would be the same.

**Comment by arturoc** [comment]
since now we have the pixels size already can't we allocate the texture with them?

**Comment by ofTheo** [comment]
We could - but that would mean a black texture vs not drawing a texture.  
Ideally we would block on load with the AVF player until there are pixels ready which it sounds like is what GStreamer does, but I think that something we could look at with the next round of AVF changes as its a fairly complex issue. 

The PR made isInitialized consistent between videoPlayer's which have a texture vs ones which use the ofVideoPlayer texture, so its a good fix for now I think.
