### ISSUE TITLE
ofAppendUTF8 should be called ofAppendUTF32

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4756]
``` cpp
void ofAppendUTF8(string & str, int utf8){
    try{
        utf8::append(utf8, back_inserter(str));
    }catch(...){}
}
```

With the int32 signature, this will actually append a single 32 bit unicode character, not a utf8 encoded multi-byte character.

**Comment by bakercp** [comment]
Since we are using utf8 encoding throughout with std::string (as opposed to `std::u32string`), this is appending is simply a matter of concatenation of two utf8 encoded `std::string`s.

**Comment by bakercp** [comment]
Proposed function replacement:

```c++
void ofAppendUTF32(std::string& text, char32_t c){
    try{
        utf8::append(c, std::back_inserter(text));
    }catch(...){}
}
```

**Comment by arturoc** [comment]
i don't think that's the case. from the utf8 cpp docs:

```cpp
 utf8::append

Available in version 1.0 and later.

Encodes a 32 bit code point as a UTF-8 sequence of octets and appends the sequence to a UTF-8 string.

template <typename octet_iterator>
octet_iterator append(uint32_t cp, octet_iterator result);
   

octet_iterator: an output iterator.
cp: a 32 bit integer representing a code point to append to the sequence.
result: an output iterator to the place in the sequence where to append the code point.
Return value: an iterator pointing to the place after the newly appended sequence. 
```

the first thing it does is encoding that as utf8 so what ends up in the string is utf8.

this is useful cause the code you get for example from keys is uint32 so you can append key presses as it's used in several examples and you'll end up with a utf8 string

if you already have a utf8 codepoint then you just need to append it into the string.

is there a specific use case you have in mind?

**Comment by bakercp** [comment]
I think my concern is about language not function since this function combines a conversion (utf32->utf8) and an append in one operation. The function name makes it sound like one is appending something that is already utf8.  Elsewhere in utf8cpp there are functions like 32to8 and in ofxUnicode I have a function like toUTF8(char32_t) which makes it a little clearer what's going on. For the append / conversion function in ofxUnicode I situate it in a class so it's a little clearer (e.g. ofx::UTF8::append(char32_t)).

Anyway, again this is more about function name clarity than anything else.

**Comment by bakercp** [comment]
Closing this as, I believe it just needs documentation.
