### ISSUE TITLE
Exception thrown at 0x005EDEEA in vDome_debug.exe: 0xC0000005: Access violation reading location 0x00000048.

### ISSUE THREAD

**Issue by uzarsalan** [openframeworks/openFrameworks#4758]
Hi! Visual Studio Community 2015 gave me some error:

 "Exception thrown at 0x005EDEEA in vDome_debug.exe: 0xC0000005: Access violation reading location 0x00000048.

If there is a handler for this exception, the program may be safely continued."

It stops on 

void ofAppGLFWWindow::hideCursor(){
	glfwSetInputMode(windowP,GLFW_CURSOR,GLFW_CURSOR_HIDDEN);
};

in file \libs\openFrameworks\app\ofAppGLFWWindow.cpp

Please help me!

Windows 10

**Comment by arturoc** [comment]
visual studio does this anoying thing where the debugger stops on any 
exception even if they are being capture by the application. i think 
it's only that and you can just press continue to keep running the app. 
the dialog with the error also gives you the option to disable capturing 
that exception in the future i think

**Comment by charlesveasey** [comment]
if this continues to be a problem, please file an issue on the vDome repo

**Comment by arturoc** [comment]
going to close this then, feel free to reopen if you think it's an OF specific problem
