### ISSUE TITLE
ofxGui crashes on construction (if the ofMainLoop is not setup) 

### ISSUE THREAD

**Issue by fx-lange** [openframeworks/openFrameworks#4769]
The constructor of any ofxBaseGui crashes if called before the ofMainLoop is up and running.

For example if I define an ofxPanel globally (in ofApp.cpp) the app will crash because of the line 69 in the ofxBaseGui constructor:

`currentFrame = ofGetFrameNum();`

Of course this can be easily avoided and is bad practice anyway to define it globally but also an constructor shouldn't call any oF internals right? That should happen in some setup function? Or is it often the case?

Thanks,
Felix

**Comment by arturoc** [comment]
This shouldn't be crashing anyway, i've added a some checks in this PR #5042 if you can try if it fixes this problem too?

**Comment by fx-lange** [comment]
@arturoc - yes works fine. thanks
