### ISSUE TITLE
0.9.1 not compiling on RPI2/arm7

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4773]
Looks to be the change I made with #4711 

I am guessing that `grep ID=raspbian $(RPI_ROOT)/etc/*-release` is returning false due to `RPI_ROOT` being unset and causing bash to return

```
-bash: RPI_ROOT: command not found
ID=raspbian
```

This seems to work as a temporary workaround
`make IS_RASPBIAN=1`

Sorry this slipped into the release - I could have sworn I checked everything again.

**Comment by arturoc** [comment]
i think we added the `ifdef RPI_ROOT` here: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk#L48 to avoid an error log in other platforms but that probably has broken the detection. 

the right check would be to check if that file exists instead something like:
```make
ifeq ($(wildcard $(RPI_ROOT)/etc/*-release), /etc/os-release)
    ifeq ($(shell grep ID=raspbian $(RPI_ROOT)/etc/*-release),ID=raspbian)
        IS_RASPBIAN=1
    endif
endif
```

if it's necessary we can branch stable and do this change here then do a quick 0.9.2

**Comment by jvcleave** [comment]
Yeah - it's currently broken. I can check your with your suggested fix tomorrow.

**Comment by arturoc** [comment]
great, it would be great to have a test env for the raspberry too. if we could upload an image of raspbian and a cross compiler we can probably have travis compile the core + some examples as we do for android

**Comment by jvcleave** [comment]
@arturoc I just tested and your code above works - do you want to apply the fix?

**Comment by arturoc** [comment]
yeah, perhaps do it on a branch from stable and let's do a 0.9.2. the 0.10 cycle is going to be relatively long and rpi would be broken meanwhile

**Comment by arturoc** [comment]
if you can send a PR against the 0.9.2 branch i've just created?
