### ISSUE TITLE
Qt creator defines OF_USING_MPG123 for all plattforms

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/openFrameworks#4781]
I think we libmpg123 just for linux, is that right?

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs#L398

**Comment by arturoc** [comment]
right now yes but there's a PR to use openAL in msys2 which will require mpg123 . in any case it's not as easy as just making it linux only the correct thing to do would be to check if mpg123 is really there since it might not be installed

**Comment by thomasgeissl** [comment]
How about osx? I ran into this issue when I tried to use ofxSoundObjects on osx.
https://github.com/roymacdonald/ofxSoundObjects/issues/5

Is there an easy way to do this in qbs, except checking all possible paths? Something similar like find_package modules for cmake.

**Comment by arturoc** [comment]
mmh, no it shouldn't be in use in osx by default. we are going to do a 0.9.2 to fix a couple of things in 0.9.1 i'll fix it there temporarily by removing that define for osx and windows

**Comment by thomasgeissl** [comment]
Thanks!
