### ISSUE TITLE
Regression in 0.9.1 with ofTTF font size. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4788]
In 0.9.0 the Font Example looks like this: 

![screen shot 2016-02-05 at 1 18 03 pm](https://cloud.githubusercontent.com/assets/144000/12855274/7daed14c-cc0c-11e5-8649-262e90249b8b.png)

In 0.9.1 there is an issue with font size ( it looks bigger ) and letter spacing 

![screen shot 2016-02-05 at 1 28 33 pm](https://cloud.githubusercontent.com/assets/144000/12855290/8d1bfd4e-cc0c-11e5-8b5b-5fdefc581f53.png)

Looks like the issue is that ofTrueTypeFont::setGlobalDpi is broken. This is used by the fonts example to set the DPI to 72. 

setGlobalDpi doesn't set the DPI anymore because its being set to 96 in the constructor 

https://github.com/openframeworks/openFrameworks/blob/stable/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L367

but the check lower down is checking if its set to 0 use the global dpi:
https://github.com/openframeworks/openFrameworks/blob/stable/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L622

so the check never succeeds. 

Note this is as of 0.9.1 and is from the Stable branch, but I am seeing the same issue with the current OF master. 

Okay in master the issue is that the default argument for the font DPI in load is 96 
so the same check is failing later.  Fix would be to change the default argument to 0 - so that it uses the global dpi. 

Here: 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.h#L193
and here:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.h#L201

**Comment by arturoc** [comment]
mmh yeah i changed this cause it was really weird to have an argument like that set to 0. 

i was teaching a workshop and showed how that parameter by default was 96 but the function signature in the header was 0 which was super confusing so i just changed it to 96 thinking that there was something that looked if it was 0 and if it was it would set it to 96 anyway.

i should have tested this but let's find a way to do this that doesn't rely on a value being 0 otherwise it's really confusing and error proone

**Comment by arturoc** [comment]
i'm checking this and it's hard to change it with the old api in 0.9, let's change it back to 0 for 0.9.2 and then for 0.10 since there's now a settings object it'll be easier to check if the default has been changed

**Comment by ofTheo** [comment]
@arturoc - awesome - totally agree about changing this for 0.10.0  

The current load calls are currently really weird and a lot of the arguments could be removed:
`
loadFont(string filename,  int fontsize, bool _bAntiAliased=true, bool _bFullCharacterSet=false, bool makeContours=false, float simplifyAmt=0.3f, int dpi=0));
`

all the contour stuff could be separate in some way.

**Comment by arturoc** [comment]
yeah that's solved already in master, there's now an ofTtfSettings object that has all the parameters so now load looks look like:

```
ofTtfSettings settings;
settings.fontName = "verdana";
settings.fontSize = 14;
ttf.load(settings);
```
