### ISSUE TITLE
ofImage::saveImage() should not modify the passed ofPixels.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4791]
If the pixel format passed to `ofSaveImage` (aka `ofImage::saveImage()`) is `OF_PIXELS_BGRA` (for example color bitmaps in FreeType2 are stored this way), ofSaveImage will modify the ofPixels object to swap the B/R pixels.

Besides leading to a very long debugging process, on principle, I'd argue that an image saving function should not modify the pixels to be saved.

Thus, I'd suggest that `ofSaveImage(ofPixels & pix, std::string fileName, ofImageQualityType qualityLevel)` and similar be `ofSaveImage(const ofPixels& pix, std::string fileName, ofImageQualityType qualityLevel)` and likewise `ofImage::saveImage(const ofPixels& pix ...);`.

Any modifications to the pixels that need to be done to make things easier for freeimage should be done on a local copy (saving is a slow operation, so memory manipulations probably won't be the bottleneck).

**Comment by bakercp** [comment]
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofImage.cpp#L346-L358

**Comment by bakercp** [comment]
Additionally, since we are already copying pixels in `getBmpFromPixels(ofPixels_<PixelType> &pix)` (Which should also be `getBmpFromPixels(const ofPixels_<PixelType> &pix)`) any FreeImage-required B/R swapping should be done there as the FreeImage bitmap is prepared.

**Comment by arturoc** [comment]
that make sense, can you send a PR?

**Comment by bakercp** [comment]
Yep, gonna pull it together.

**Comment by bakercp** [comment]
I haven't jumped into a deeper more efficient fix in `getBmpFromPixels`.  It appears to me that much of that function could be replaced with `FreeImage_ConvertFromRawBits`, including the vertical flip.  It seems that it's just a matter of setting the channel masks based on the pixel type, and the vertical flip flag.  This would prevent an additional copy (there are at least two now ...).  But for the moment, this PR fixes.  Primarily this could make the `ofImage::resizePixels()` and `ofImage::changeTypeOfPixels()` by reducing the number of copies.  Then again, all of these CPU pixel manipulations are understood to be pretty slow compared to the same GPU manipulations / display.

Anyway, if you think we need to tackle these efficiency issues in this PR, I can, otherwise, this should be ready to go.
