### ISSUE TITLE
ofVideoGrabber with bUseTexture = false does not update

### ISSUE THREAD

**Issue by antimodular** [openframeworks/openFrameworks#4811]
i'm on OS X 10.10 with OF 0.9.0 and Xcode 6.4

will trying to make a headless app via ofAppNoWindow i noticed when setting up ofVideoGrabber like so: 

```
vidGrabber.setup(camWidth,camHeight,false);
```

vidGrabber.isFrameNew() always returns 0.
looking in to void ofVideoGrabber::update() need bUseTexture to be true otherwise nothing happens.

is it even possible to use the camera image with bUseTexture = false?
thx

**Comment by arturoc** [comment]
this sounds like a bug, even if there's no texture, the pixels are updated and the grabber should return true on isNewFrame. sounds like an easy fix, just moving out of that if wheerever the flag is set to true

**Comment by antimodular** [comment]
in the hopes of helping here is a bit more info.

while in headless mode:
if vidGrabber.setup(camWidth,camHeight,**true**);
then app crashes here in line tex.push_back(ofTexture());
here 
````
    if( grabber->isInitialized() && bUseTexture ){
		if(!grabber->getTexturePtr()){
			for(int i=0;i<grabber->getPixels().getNumPlanes();i++){
				ofPixels plane = grabber->getPixels().getPlane(i);
				tex.push_back(ofTexture());
				tex[i].allocate(plane);
			}
		}
	}
````

while NOT in headless mode
if vidGrabber.setup(camWidth,camHeight,**false**);
everything works well and i can pass the ofVideoGrabber pixel to a texture

**Comment by arturoc** [comment]
yes, if you are in headless mode you can't use opengl at all and any call to an opengl command, like creating a texture will crash the app since there's no opengl context.

you should use setUseTexture(false) in that case

**Comment by antimodular** [comment]
i did try that with setUseTexture(false) before and after setup.
but that still causes a crash unless is i do setup(camWidth,camHeight,false)

here what crashes in headless mode
````
        vidGrabber.setUseTexture(false);
        vidGrabber.setDeviceID(deviceID);
        vidGrabber.setup(camWidth,camHeight); //,false);
        vidGrabber.setUseTexture(false);
````

**Comment by arturoc** [comment]
yes that's true you need to call setup(w,h,false) otherwise it'll try to create a texture in setup and crash too

**Comment by bakercp** [comment]
@antimodular is this fixed now with #5134?

**Comment by stephanschulz** [comment]
yes.
thanks for your efforts.

**Comment by bakercp** [comment]
Thanks @stephanschulz !
