### ISSUE TITLE
SSL-related Segmentation faults when using Poco SSL manager with custom settings on OSX, traced to . 

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4812]
After tracking down the source of this issue https://github.com/bakercp/ofxSMTP/issues/12 and this issue https://forum.openframeworks.cc/t/ofxhttp-segfault/22391/7 (both of which use ofxSSLManager to require valid SSL certs via a ca cert bundle ... which the core currently does not do) I traced it to this commit https://github.com/openframeworks/openFrameworks/pull/4390 that recompiled freeimage on 10.8.  There appears to be some mysterious issue that is fixed for users by recompiling freeimage on the local system (e.g. `./apothecary update freeimage`).  I'm honestly not sure what the solution is because if we compile FreeImage on a 10.9+ machine, it seems to break 10.8 machines (https://github.com/openframeworks/openFrameworks/issues/4385).  My initial suspicion is that maybe the faulty 10.8 compiled freeimage is not compatible with Poco because it linked to a different non ABI compatible system lib or something.  Any thoughts are appreciated.

**Comment by danoli3** [comment]
This is a strange one. We can assume majority developers are above board
with 10.9+ so we should compile with that for distribution. For those
under, they can just use Apothecary to recompile it.

Next major is 10.9+ anyway so this is really a legacy <0.9.2 issue.

**Comment by bakercp** [comment]
I'm all for 10.9+.  Supporting 10.11, 10.10, 10.9 seems great.  I'm doing a little testing now with 10.8 to see if the recommendation to custom compile via apothecary for 10.8 actually solves the problem.  Funny thing is I just tried the stable branch on 10.8 and got the same segfaults which leads me to believe that it may be an incompatibility between our precompiled static libs (Poco / FreeImage), rather than a specific 10.8 issue.  I'm wondering if we make sure that _everything_ is compiled on 10.8 (and make sure we aren't linking into _any_ system libs ... which I believe we may accidentally be doing now in some cases ... and just getting lucky) -- perhaps it will just work.  Anyway, firing up the 10.8 virtual machine and will report back sometime soon.

**Comment by danoli3** [comment]
Yeah awesome! Nice work!

**Comment by bakercp** [comment]
@arturoc and @danoli3 I recompiled _all_ OSX libraries from scratch on a 10.8 machine and updated all deployment and min os settings to 10.8 (there was a mix of 10.7 and 10.8).  This seems to have solved the problem.  It would be really great to get these libs in the 0.9.3 release.  Arturo -- since this is both an apothecary formula and oF build system, static lib, etc related, where should I direct a PR for a 0.9.3 release?  I know you're in the process of refactoring the repositories, but that you've got a patch branch going for 0.9.3 ... anyway, let me know when you get a chance.

**Comment by arturoc** [comment]
yeah that makes sense, can you send a PR against the 0.9.3 branch?

**Comment by bakercp** [comment]
Hi @arturoc I just noticed that when I rebuilt the core with `./apothecary update core`, a bunch of new libs / files were added (portaudio headers, libnetwork-uri + headers, boost asio, etc).  Should I commit all of those new 3rd party libs, headers, etc?

**Comment by bakercp** [comment]
Or -- perhaps those were coming from master and intended for 0.10.0.  I'll start fresh from the 0.9.3 branch ...

**Comment by arturoc** [comment]
yes better start from 0.9.3, those libraries are probably still there but they are not being used. also update core is not very reliable in some platforms, not sure about osx. but variables defined by one script remain in the environment and break some others.

the easiest is to create a script by now that runs one after another like:

```sh

for formula in $( ls -1 formulas | grep -v _depends) ; do
    formula_name="${formula%.*}"
    echo Compiling $formula_name
    ./apothecary update $formula_name
done
```

**Comment by bakercp** [comment]
Ugh.  Even with apothecary recompiling all of this stuff still takes so much time (less though).  OK.  So my recompiles have been working, then suddenly after a recompile I got this error, which we used to get:

```
In file included from /Users/dev/Desktop/openFrameworks/libs/openFrameworks/graphics/ofImage.cpp:5:
/Users/dev/Desktop/openFrameworks/libs/FreeImage/include/FreeImage.h:153:17: error: typedef redefinition with different types ('int32_t' (aka 'int') vs 'signed char')
typedef int32_t BOOL;
                ^
/usr/include/objc/objc.h:52:22: note: previous definition is here
typedef signed char             BOOL; 
```

while compiling the core.

Is this something that might have been fixed in master, but was not fixed in the 0.9.3 branch?

**Comment by danoli3** [comment]
Oh just don't let it overwrite the freeimage.h header should be fine (do a reset on that file in git)

**Comment by bakercp** [comment]
Which freeimage.h header -- the one already in $OF_ROOT/libs/FreeImage/include ?

**Comment by bakercp** [comment]
And is this something we can fix in the script / formula ... ?  Sorry I've been digging through old related issues and I can't figure out where the "fix" was ... I thought it was taken care of in your repo.

**Comment by bakercp** [comment]
@danoli3 can you give me your thoughts on this tomorrow when you have your apothecary hat on?  Thanks!

**Comment by danoli3** [comment]
Yes I can fix this from the FreeImage git repo with our modified header. The one in the core currently yeah.

**Comment by danoli3** [comment]
Ah so the FreeImage BOOL issue isn't a problem on newer compilers for some reason, why it's apparent on 10.8 (that's about the time it was first discovered and fixed: See: https://github.com/openframeworks/openFrameworks/commit/29226a915dc4a9669bcb328acde84adcfd1ca447 ).

I've repatched it with the FREEIMAGE_BOOL solution in the FreeImage repo.
I'll send a PR to the core as well... is this something we should send to 0.9.3 as well? I guess as it is the last with 10.8 support.

**Comment by arturoc** [comment]
yes this should go into 0.9.3, it's the last thing we need to fix to do the release i think

**Comment by danoli3** [comment]
Okay @bakercp see how she goes!

**Comment by bakercp** [comment]
Hi @danoli3 and @arturoc -- just catching up on all of this and will let you know what's up ASAP.

**Comment by bakercp** [comment]
Hmm ... fails hard here (on 10.8):

```bash
localhost:apothecary dev$ ./apothecary update FreeImage

 ----- FreeImage -----

 Downloading "FreeImage"

Downloading from https://github.com/danoli3/FreeImage for OSX/iOS
https://github.com/danoli3/FreeImage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    227      0 --:--:-- --:--:-- --:--:--   348
100 6185k    0 6185k    0     0   606k      0 --:--:--  0:00:10 --:--:--  835k

 Preparing "FreeImage"


 Building "FreeImage"

In file included from Source/FreeImage/BitmapAccess.cpp:37:
Source/FreeImageIO.h:37:2: error: unknown type name 'BOOL'
        BOOL delete_me;
        ^
In file included from Source/FreeImage/BitmapAccess.cpp:38:
Source/Utilities.h:85:59: error: unknown type name 'BOOL'
DLL_API FIBITMAP * DLL_CALLCONV FreeImage_AllocateHeaderT(BOOL header_only, FREE_IMAGE_TYPE type, int width, int height, int bpp FI_DEFAULT(8), unsigned red_mas...
                                                          ^
Source/Utilities.h:100:58: error: unknown type name 'BOOL'
DLL_API FIBITMAP * DLL_CALLCONV FreeImage_AllocateHeader(BOOL header_only, int width, int height, int bpp, unsigned red_mask FI_DEFAULT(0), unsigned green_mask F...
                                                         ^
Source/Utilities.h:116:65: error: unknown type name 'BYTE'
DLL_API FIBITMAP * DLL_CALLCONV FreeImage_AllocateHeaderForBits(BYTE *ext_bits, unsigned ext_pitch, FREE_IMAGE_TYPE type, int width, int height, int bpp, unsigne...
                                                                ^
Source/Utilities.h:122:9: error: unknown type name 'BOOL'
DLL_API BOOL DLL_CALLCONV FreeImage_HasRGBMasks(FIBITMAP *dib);
        ^
Source/Utilities.h:310:13: error: unknown type name 'BYTE'
AssignPixel(BYTE* dst, const BYTE* src, unsigned bytesperpixel) {
            ^
Source/Utilities.h:310:30: error: unknown type name 'BYTE'
AssignPixel(BYTE* dst, const BYTE* src, unsigned bytesperpixel) {
                             ^
Source/Utilities.h:317:23: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst)) = *(reinterpret_cast<const WORD*> (src));
                                           ^
Source/Utilities.h:317:63: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst)) = *(reinterpret_cast<const WORD*> (src));
                                                                                   ^
Source/Utilities.h:321:23: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst)) = *(reinterpret_cast<const WORD*> (src));
                                           ^
Source/Utilities.h:321:63: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst)) = *(reinterpret_cast<const WORD*> (src));
                                                                                   ^
Source/Utilities.h:326:23: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                           ^
Source/Utilities.h:326:64: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                                                                    ^
Source/Utilities.h:330:23: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                           ^
Source/Utilities.h:330:64: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                                                                    ^
Source/Utilities.h:331:23: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst + 4)) = *(reinterpret_cast<const WORD*> (src + 4));       
                                           ^
Source/Utilities.h:331:67: error: unknown type name 'WORD'
                        *(reinterpret_cast<WORD*>(dst + 4)) = *(reinterpret_cast<const WORD*> (src + 4));       
                                                                                       ^
Source/Utilities.h:337:23: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                           ^
Source/Utilities.h:337:64: error: unknown type name 'DWORD'
                        *(reinterpret_cast<DWORD*>(dst)) = *(reinterpret_cast<const DWORD*> (src));
                                                                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Source/FreeImage/BitmapAccess.o-i386] Error 1

 ^ Received error ^
localhost:apothecary dev$ 
```

**Comment by bakercp** [comment]
It didn't previously fail during library compilation, only during openFrameworks compilation ... which is odd.

**Comment by danoli3** [comment]
Maybe the undef is the wrong idea.

**Comment by danoli3** [comment]
@bakercp try again now.

**Comment by bakercp** [comment]
Trying it ...

**Comment by bakercp** [comment]
OK.  I'm getting mixed results.  I think it depends on the order in which you build Freeimage (which now builds).  Anyway, still compiling.

@arturoc @danoli3 Do we want to upgrade openssl and Poco for 0.9.3?  The openssl update is considered critical.  The Poco is mostly bugfixes, but not required.  Downside for any is that we need to build the updated static libs for all platforms for distribution.

**Comment by danoli3** [comment]
I'd say probably a good idea for 0.9.3. It's the last version supporting those old targets, so as long as there isn't unforeseen issues on all platforms, probably best.

**Comment by arturoc** [comment]
i'd keep the same versions, this is just a patch release supposed to only fix some small bugs in 0.9 but at all effects should be the same as 0.9.0. 

We can increase the version numbers in the apothecary branch. Also libraries are already being compiled and uploaded http://ci.openframeworks.cc/libs/ so if anyone needs the very latest version of the binaries they can just substitute their libs folder with that.

**Comment by arturoc** [comment]
any news on this? it's the only thing missing to release 0.9.3

**Comment by bakercp** [comment]
Hey, I'm trying this again today.  Last time I was able to get everything compiled on 10.8 -- but the resulting libs were causing the same crashes even after the fixes (there's something strange happening with apothecary settings I think).  

If we can't get this resolved in the next day or two, I'd say we compile on 10.9+ and make a release note that suggests that 10.8 users will have to recompile themselves on a local machine if they are having problems.

**Comment by bakercp** [comment]
Hey, I'm really close on this, but haven't been able to get it to all work.  The easiest solution that will solve the problem for the most people is to recompile libraries on 10.9+.  But that may require 10.8 users to recompile their own libraries.  I'll give it one more go on 10.8 today to see if the problem is related to environmental variables that are conserved between scripts ... but this has been a headache and I don't want to hold up the 0.9.3 release ...

**Comment by bakercp** [comment]
Alright.  After failing to get this to compile and run on 10.8, I simply recompiled on 10.11 (which was known to work) and then tested the same static libs on 10.8.  It appears to solve the problem on all platforms.  So, while I can't describe exactly why, it seems to be solved with this PR.

https://github.com/openframeworks/openFrameworks/pull/4977

Thanks for your patience!

**Comment by ofTheo** [comment]
@bakercp thanks for your work on this!!

**Comment by danoli3** [comment]
Wow nice work! Such a weird one!
