### ISSUE TITLE
ofPixels : move constructor not properly working

### ISSUE THREAD

**Issue by hanasaan** [openframeworks/openFrameworks#4821]
Hi,
When I tried to use ofThreadChannel with ofPixels, I found this issue.
Since oF v0.9.1, move constructor of ofPixels seems to be implemented but not working correctly.

issue 1: 
Pixel format is not copied. It is simple
```pixelFormat = mom.pixelFormat;```
should be added on L247 on ofPixels.cpp.

issue 2:
After fixed the issue 1, an another issue came.
It seems to be more complex, because I didn't get the intension to make the condition on the move constructor.
The issue is that the conditional statement is unexpectedly "false" after third call of ofThreadChannel::receive and it causes NULL ptr error when texture loading happens.

So, for work around the issue, simply roll back the code make the thing fine.

**Comment by arturoc** [comment]
wow yeah not sure why i was doing that in the assignment operator. it should be fixed here: https://github.com/openframeworks/openFrameworks/commit/96a77eee0119b59d99f0450dbb2b2625618dcaa4 

can you give it a try and let me know if it fixes it for you?

**Comment by hanasaan** [comment]
Thank you for fixing the issue! It works now.

**Comment by arturoc** [comment]
thanks!
