### ISSUE TITLE
0.9.2 won't compile on Rpi2

### ISSUE THREAD

**Issue by DeqingSun** [openframeworks/openFrameworks#4823]
I used http://openframeworks.cc/versions/v0.9.2/of_v0.9.2_linuxarmv7l_release.tar.gz

And I got this error

    pi@raspberrypi:~ $ make Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project
    make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project
    HOST_OS=Linux
    makefileCommon/config.shared.mk:217: *** This package doesn't support your platform, probably you downloaded the wrong package?.  Stop.
    make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'`

I tried to change following in config.shared.mk, from armv6l to armv7l

    ifdef IS_RASPBIAN
        PLATFORM_ARCH=armv6l
        HOST_ARCH=armv6l
        ifdef RPI_ROOT
            CROSS_COMPILING=1
        endif
And I got 

    /home/pi/openFrameworks/libs/openFrameworks/app/ofAppEGLWindow.cpp:1:0: error: target CPU does not support ARM mode

Then I did this and get it compiling

    pi@raspberrypi:~/openFrameworks/libs/openFrameworksCompiled/project $ make Release PLATFORM_VARIANT=raspberry2

**Comment by jvcleave** [comment]
armv6 is the supported platform for both the RPI1 and RPI2 under Raspbian. Raspbian has issues with the std library for threading.

**Comment by arturoc** [comment]
yes armv7 is not supported anymore for raspbian, you need to use armv6 i think it's stated in the docs, @jvcleave perhaps we should make it more obvious? we could even add something in the download link that says raspbian not supported or something like that in the armv7 section?

**Comment by DeqingSun** [comment]
OK I'll try again.
If so I think there shouldn't be a link for Rpi under linux armv7

**Comment by DeqingSun** [comment]
Yes armv6 did wotk
Looks like compiling 0.9.2 is much slower than 0.8.4
Is it caused by not using multiple core? If so is there an official tutorial on using multiple core on Rpi2?

**Comment by jvcleave** [comment]
Yes - I was thinking the same thing as @DeqingSun - just remove the raspberry pi link from under armv7

**Comment by jvcleave** [comment]
@DeqingSun `make -j2` will help compiling speed (`-j4` may also work but can cause you to run out of memory)

Compiling is slower in 0.9.0 - likely due to the use of more templates/c++11. Once you compile core, apps go much faster.

**Comment by DeqingSun** [comment]
Thanks
I just did a test, with "export MAKEFLAGS=-j4" polygonExample uses 40 seconds instead of 60 seconds by default.

**Comment by arturoc** [comment]
yes probably just removing the link should do the thing is you can still use raspberry pi with for example arch linux the problem is raspbian not the raspberry but perhaps is something we can specify so in the armv7 docs. someone recently added a guide to use rPI2 with armv7 archlinux perhaps we should link to that instead
