### ISSUE TITLE
OSX is copying data into the bundle

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#4825]
This should be optional but at least we should remove it for 0.9.3 since it's making applications that generate data grow in size indefinitely.

This was introduced in https://github.com/openframeworks/openFrameworks/pull/3563#issuecomment-182294915 and there's more comments about it there

@danoli3 can you take a look and send a PR against 0.9.3? the current folder structure inside the bundle should stay the same so 0.9.3 projects are compatible with 0.9.0 -> 0.9.2

**Comment by ofZach** [comment]
I also think it's good to investigate how many of the other app-store specific changes we need to the default OSX template and whether a separate app-store template is a better place for them.  (ie, there is now a post build script that does something with code signing, etc)

**Comment by danoli3** [comment]
Sounds good! I'll remove the post script stuff too @ofZach. We'll go with the alternative project file for AppStore for 0.10.x

**Comment by danoli3** [comment]
Fixed for 0.9.3 branch. I'll split it up for master into the 2 projects as discussed.
