### ISSUE TITLE
ofEasyCam : separated viewport and mouse inputs area

### ISSUE THREAD

**Issue by BaptisteTheoriz** [openframeworks/openFrameworks#4846]
Hi guys,
Should it be possible to add a function to separate camera's viewport and mouse input area ? It could be useful when rendering easycam inside a fbo which can be larger than app window, and then drawn scaled or translated in window.

**Comment by arturoc** [comment]
I don't think we want to have this as part of ofEasyCam, it would probably complicate the internal logic quite a bit to cover a case that seems pretty rare.

Something that could work is:

- making the event callbacks public, that way you can unregister the camera from the core events and pass your own mouse coordinates that are pre transformed to fit your needs
- ofEasyCam has a setEvents function that allows to use ofEasyCam in different windows, we could make that function more flexible so people could create their own "core events" class that transforms the coordinates and ofEasyCam would register to those
- Add some kind of transformation matrix to ofCoreEvents so you can just plug a custom transformation into the events

or something along those lines, i guess the idea is transform the events not add more logic to ofEasyCam.

The first one of them is the easiest to implement but is probably more open to confusion, if someone for example uses ofEasyCam normally and tries to call the mouse events too but seems really unlikely

**Comment by BaptisteTheoriz** [comment]
I didn't considered the problem from events point of view. 

But, for me, it sounds more complicated and confusing to create some custom events with remapped mouse positions than simply telling to the camera which screen area can control it. 

I tried to simply add a new ofRectangle inside easycam, and tell mousePressed ... functions to check mouse inside this rectangle instead of viewport. In my case, it does perfectly the job, allowing me to allocate a part of my screen to the control of the camera (and so, I can render my easycam inside a FBO of any size, then draw this FBO anywhere, scaled or not, and tell my easycam to take mouse inputs exactly where and how my fbo's texture is drawn).

In my opinion it's easier and clearer than creating custom events, but I could be wrong.

**Comment by tgfrerer** [comment]
I agree with @BaptisteTheoriz here -- i've actually run into this situation a couple of times -- the classic scenario is to draw into an ofFbo and then render the fbo at half scale - if the mouse coordinates are not modulated by the render rectangle, the mouse input is super inaccurate. 

i believe it could be solved by passing a rect for the mouse rect as an optional parameter to ofEasyCam.begin() - with the default being the viewport rect...

**Comment by arturoc** [comment]
my point was that if we begin to add hacks for edge cases things come become quite messy while having a solution that allows any kind of transformation from user code would be much more flexible and without adding any complexity to the internal logic for ofEasyCam.

if it's a common case and the solution doesn't complicate the internals much then i guess it's ok.

@BaptisteTheoriz can you send a PR with your solution so we can check it?

**Comment by charlesveasey** [comment]
I agree with @arturoc. I'd prefer simply making the event callbacks public. Then we can scale, offset, or populate the mouse coordinates as needed.  

For example to populate the ofMouseEventArgs with controller or socket data and then call the mousePressed function when ready would be very useful.

**Comment by charlesveasey** [comment]
I'll ping this since there has been some recent work on easycam. Any issue with making the event callbacks public? Happy to PR.

**Comment by danzeeeman** [comment]
I added something a while ago to my OF that uses the ofRectangle to set the
listening bounds of the EasyCam mouse inputs. It's useful when you have
multiple Cameras with multiple viewports. Basically it checks of the mouse
is inside the Rect and enables mouse events. This is a pretty easy addition.
