### ISSUE TITLE
ofVideoPlayer::isInitialized() should be deprecated.

### ISSUE THREAD

**Issue by brannondorsey** [openframeworks/openFrameworks#4852]
`ofVideoPlayer::isInitialized()` is an alias of `ofVideoPlayer::isLoaded()` and should probably be deprecated.

In `ofBaseTypes.h`:
```cpp
virtual bool isInitialized() const{ return isLoaded(); }
```

**Comment by bakercp** [comment]
Brannon and I determined that this is actually part of `ofBaseVideo` and shouldn't be deprecated.  The difference between isLoaded and isInitialized was a little confusing, but the load() vs setup() difference is a bit clearer now.
