### ISSUE TITLE
threadChannelExample: problem with ofPixelFormat when passing pixels from ofVideoGrabber to ofThread

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#4862]
The threadChannelExample located in ``examples/utils/threadChannelExample``` is not running properly. It should show a black and white image of the webcam input but the format is messed up and it throws the following errors:

    [ error ] ofPixels: format doesn't support channels`
    [ error ] ofGLUtils: ofGetGLFormatFromPixelFormat(): unknown OF pixel format-1, returning GL_LUMINANCE`

At the following point in the example, the pixels of the ```ofVideoGrabber``` instance are being sent to the ```ofThread``` instance:
https://github.com/openframeworks/openFrameworks/blob/master/examples/utils/threadChannelExample/src/ofApp.cpp#L12
The grabber has an ```internalPixelFormat``` of ```OF_PIXELS_RGB (2)```.

In the ```ofThread``` derived class at the point where it receives these pixels, the ```pixelFormat``` of ```pixels``` is ```OF_PIXELS_UNKNOWN (-1)```:
https://github.com/openframeworks/openFrameworks/blob/master/examples/utils/threadChannelExample/src/ImgAnalysisThread.cpp#L33

Maybe this is the source of the errors?

**Comment by arturoc** [comment]
this was actually already fixed in 0.9.3 but wasn't merged yet in master. it was just a problem with move constructors introduced in 0.9.2

thanks!
