### ISSUE TITLE
OF_MOUSE_BUTTON_RIGHT should be 1

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#4873]
OF_MOUSE_BUTTON_RIGHT should be 1 and OF_MOUSE_BUTTON_MIDDLE should be 2

(or just remove the switch here?)
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L954

![image](https://cloud.githubusercontent.com/assets/150037/13192348/eba4e2fe-d738-11e5-9863-2a12b015e2b5.png)

```
    #define OF_MOUSE_BUTTON_1      0
    #define OF_MOUSE_BUTTON_2      1
    #define OF_MOUSE_BUTTON_3      2
    #define OF_MOUSE_BUTTON_4      3
    #define OF_MOUSE_BUTTON_5      4
    #define OF_MOUSE_BUTTON_6      5
    #define OF_MOUSE_BUTTON_7      6
    #define OF_MOUSE_BUTTON_8      7
    #define OF_MOUSE_BUTTON_LAST   OF_MOUSE_BUTTON_8
    #define OF_MOUSE_BUTTON_LEFT   OF_MOUSE_BUTTON_1
    #define OF_MOUSE_BUTTON_MIDDLE OF_MOUSE_BUTTON_2
    #define OF_MOUSE_BUTTON_RIGHT  OF_MOUSE_BUTTON_3
```

**Comment by arturoc** [comment]
this was like that in glut and we've always considered that left was 1 and middle was 2. i'm not sure that changing it after so much time is a good idea. do you think it would have any advantage?

**Comment by jvcleave** [comment]
I can understand GLFW's reasoning as with GLUT/OF a 2-button mouse would be 1,3 with 2 just missing. Other than that I don't see an advantage other than following GLFW's convention? 

It's not hard for me to remap it for my addon
