### ISSUE TITLE
allAddonsExample gone

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#4923]
We were using it for testing that all the addons are still compiling so right now all the tests are failing. The PR that introduced this in the first place and broke the tests shouldn't have been merged until the tests were correct.

Anyway, can anyone fix it?

**Comment by frauzufall** [comment]
Sorry, Arturo!

The allAddonsExample is now located at examples/templates/allAddonsExample. Are you fine with that? If you can tell me where the test script is I can update the link.

**Comment by bakercp** [comment]
I'll coordinate with Deborah and we'll take care of this before anything
else is merged.

**Comment by arturoc** [comment]
that's fine, the change is good, having an addons folder probably didn't make much sense anymore but be careful to not merge anything that is not passing the tests for all platforms
