### ISSUE TITLE
ofFile api inconsistencies

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#4931]
Noticed a few things when documenting ofFileUtils.h:

ofFile(path, mode, binary) constructor opens w/ default binary=true while:
* ofFile::open() opens w/ binary=false
* ofFile::changeMode() uses binary=false
* ofDirectory::getFile() uses binary=false

ofFile::create(), how to set path before creating? Both the constructor and open() set the path but also try opening the file...

ofFile::setReadOnly() & ofDirectory::setReadOnly() should be setReadable() to match setWriteable(). I feel this naming also conflicts with the ReadOnly access mode.

**Comment by arturoc** [comment]
oh, i thought i had changed everything to binary=true. that should be the default, it doesn't mean binary file really but only that it'll do no break lines transformations.

and yes it would be useful to have a version of create that accepts a path. you can do it with:

```
ofFile("file.txt", ofFile::Reference).create();
```

or any combination of open/create using Reference as open mode. or even:

ofFile("file.txt", ofFile::WriteOnly);

 but it would be easier to have a create with a parameter.

Also setReadOnly right now is not setReadable, it just removes the write permissions from the file, which is really strange cause you can just do setWritable(false) so yes having setReadable instead would be much better

do you want to send a PR?

**Comment by arturoc** [comment]
we might even have an static create that accepts a parameter and returns an ofFile

**Comment by danomatika** [comment]
Sure. Chris and I thought the binary flag might have been an oversight and we hope nobody has been *relying* on that so far.

**Comment by arturoc** [comment]
it's really not so important, it only affects files that have windows breaklines in unix and unix breaklines in windows so it's hard to have any problem with it. the main use is to set it to true when you want to open a binary file so it doesn't change anything.

**Comment by danomatika** [comment]
Right. So the doxy lines could basically be something like:

    opens as a text file by default: split individual lines & strip endline characters
    \param binary set to false when working with binary files so data will not be interpreted as lines of text

**Comment by arturoc** [comment]
yep

**Comment by bakercp** [comment]
+1 to this effort to clarify this api :)

**Comment by danomatika** [comment]
Closed via #4979
