### ISSUE TITLE
PLY vertex color data not working 9.2

### ISSUE THREAD

**Issue by crecord** [openframeworks/openFrameworks#4935]
Hi there,

It looks like ply vertex colors have stopped working between 8.4 and 9.2. [Here](https://forum.openframeworks.cc/t/ply-color-data-not-working-properly/21408
) is a forum post describing the issue. 

here is a reduced size sample ply with vertex colors:
[sampleVertexColor.ply.zip](https://github.com/openframeworks/openFrameworks/files/143190/sampleVertexColor.ply.zip)

Here is what is look  like loaded into OF 9.2 using mesh.load(); and mesh.drawFaces(); 
<img width="626" alt="screen shot 2016-02-23 at 1 59 50 pm" src="https://cloud.githubusercontent.com/assets/3160465/13263028/d4f40954-da35-11e5-8dfd-a5e7099489f5.png">

Here is what is look like loaded into OF 8.4 
<img width="483" alt="screen shot 2016-02-20 at 8 25 18 am" src="https://cloud.githubusercontent.com/assets/3160465/13262246/d78d9274-da31-11e5-9d78-7a54ce62f4ac.png">

I am on xcode 6.2 on a 10.9 mac with a newly downloaded copy of 9.2 incase any of that is relevant.

**Comment by tgfrerer** [comment]
Thanks for the bug report! I can reproduce this on my machine, and it appears that this is down to the colours in this particular PLY being stored as uchar byte values. 

When these get ingested, the colour values get cast to floats, and strange things happen.
I'll see to work on & file a fix by the end of this week. 

In the meantime, a workaround would be to make sure the colour values are stored as float values, if your PLY exporter allows it. Unfortunately, meshlab for example, does not allow you to set the data type for colour values.

As a quick hack, you could replace the `case Color` switch branch in `ofMesh.cpp` (at line 935ff) with the following: 

	case Color:
			{
				int c = 0;
				sline >> c;
				*(&data.getColors()[currentVertex].r + (cAttr++)%colorCompsFound) = c/255.f;
			}
	break;

**Comment by crecord** [comment]
Hey, thanks for your reply and temporary fix! Luckily I have no immediate need for this feature, but just thought it would be good to report since I have seen a few couple people encounter this.
