### ISSUE TITLE
PLY flipped normals when using ofxAssimpModelLoader

### ISSUE THREAD

**Issue by crecord** [openframeworks/openFrameworks#4936]
When loading a ply file using ofxAssimpModelLoader it reverses all the normals. I checked the normals in blender and they are facing outward, but when I load it into OF these get flipped somehow. 

Here is what it looks like in 9.2: 
<img width="787" alt="screen shot 2016-02-23 at 2 08 55 pm" src="https://cloud.githubusercontent.com/assets/3160465/13263483/af0d7a7a-da37-11e5-820f-1ba9613be248.png">

Here is the file: 
[penguin.ply.zip](https://github.com/openframeworks/openFrameworks/files/143249/penguin.ply.zip)

**Comment by NickHardeman** [comment]
There is an option in the new ofxAssimp add-on to fix in facing normals. Set to true  and load with settings.
https://github.com/openframeworks/openFrameworks/blob/dd09e975ad1166ea0cb48edeae35c1f75dc9ed4b/addons/ofxAssimp/src/Source/ofxAssimpSrcScene.h#L41
