### ISSUE TITLE
Libraries download for OF v0.8.4 win codeblocks

### ISSUE THREAD

**Issue by pabloriera** [openframeworks/openFrameworks#4938]
Hi,

I was looking in the OF site for the zip files that had some DLLs that where ment to use with codeblocks on OF v0.8.4 windows. Also there are some version of Codeblocks that are inconpatible but couldn't find that info. I think they where here http://openframeworks.cc/setup/codeblocks/ but this is out now. Is there a place where I can find them?

Thanks

**Comment by arturoc** [comment]
you can find older releases here: http://openframeworks.cc/download/older/

**Comment by pabloriera** [comment]
Thanks, but I already got the old OF:

The DLLs neede for codeblocks are Inside de export folder?

It would by nice to have access to the old setup instruction page, there said the codeblock versions to use and where to download the zip files.

THanks

**Comment by pabloriera** [comment]
Here it is!
http://www.openframeworks.cc/content/files/codeblocks_additions.zip

**Comment by arturoc** [comment]
you can always check old versions of the web through archive.org: https://web.archive.org/web/20150429073819/http://openframeworks.cc/setup/codeblocks/

**Comment by pabloriera** [comment]
Marvelous!
