### ISSUE TITLE
Deprecate ofTTFCharacter (typedef for ofPath)

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#4942]
in ofTrueTypeFont we have a data type called "ofTTFCharacter" which is just a typedef of ofPath: 

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.h#L28

I suggest we deprecate this in favor of just using ofPath.   I don't think this class name gives us much benefit, has a somewhat different naming convention (TTF instead TrueTypeFont like the main class name) and on a personal note I find myself always having to look this up each time I use, which is usually a good sign it's not as intuitive as it could be.

**Comment by arturoc** [comment]
yeah totally, this was done like that to keep compatibility with the old class when we introduced ofPath but it doesn't make much sense. I don't think we can deprecate something like this, as in using the deprecation macro so we could just remove it.

**Comment by ofZach** [comment]
do you think we should do this for 0.1.0 ?  cc @ofTheo
