### ISSUE TITLE
Raspberry PI 3

### ISSUE THREAD

**Issue by mojibaked** [openframeworks/openFrameworks#4961]
Got a new Raspberry PI 3 today!

I was able to run a previously compiled (on RPI2) application binary on the RPI3 successfully, but compiling openFrameworks 0.9.2 armv7l failed. (no surprise)
```
makefileCommon/config.shared.mk:217: *** This package doesn't support your platform, probably you downloaded the wrong package?. Stop.
```

**Comment by arturoc** [comment]
you should use the armv6 download as it's explained in the download page and the setup guides for the rapsberry
