### ISSUE TITLE
v0.9.2 PLATFORM_VARIANT not found for "rpi2" with armv6l

### ISSUE THREAD

**Issue by brannondorsey** [openframeworks/openFrameworks#4965]
Hey all,

I know that some folks have gotten RPi 2 to work with the `linuxarmv6l` (which I understand is what we are now using instead of `linuxarmv7l`) build of OF, however I am getting the following error when trying to `compileOF.sh` after `install_dependencies.sh`:

```
HOST_OS=Linux
makefileCommon/config.shared.mk:226: *** Platform Variant "rpi2" is not valid. Valid variants include [default default]. Stop. 
there has been a problem compiling Debug OF library
please report this problem in the forums
```

I'm trying to build examples with:

```
make -j4 PLATFORM_VARIANT=rpi2
```

Have also tried with `PLATFORM_VARIANT=raspberry2` but to no avail. I've consulted [this recent issue](https://github.com/openframeworks/openFrameworks/issues/4823) but my problem seems to be different. Cloning OF Master onto my RPi2 now to see if the same problem arises.

**Comment by brannondorsey** [comment]
No errors w/ OF Master and something interesting. Output of `./compileOF.sh` seems to include the env variable `HOST_ARCH` which my v0.9.2 download does not. The first two lines of output are
```
HOST_OS=Linux
HOST_ARCH=armv7l
```

**Comment by brannondorsey** [comment]
I can confirm that I am experiencing this as well with a fresh pull of OF master. I'm using the basic raspian image, although it is perhaps a few months old.

**Comment by arturoc** [comment]
it shouldn't be doing rpi2, only `make`. in armv6 raspberry is the default variant so just using make it should work.

i'm looking the conmpileOF.sh script and it's not using any variant, have you modified it or something?

**Comment by brannondorsey** [comment]
Nope, no modifications, simply curled and unzipped from the downloads page. Running make alone (without the variant) results in the same error.

**Comment by brannondorsey** [comment]
Has anyone else experienced this issue with an RPi two since v0.9.2 or has it been all smooth sailing?

**Comment by jvcleave** [comment]
0.9.2 Has been fine for me

Some system info
```
pi@jvcrpi2 ~/openFrameworks/scripts/linux $ uname -a
Linux jvcrpi2 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

pi@jvcrpi2 ~/openFrameworks/scripts/linux $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
and when I run it

```
./compileOF.sh 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
Compiling /home/pi/openFrameworks/libs/openFrameworks/3d/ofMesh.cpp
g++ -g3  -Wall -std=c++14 -DGCC_HAS_REGEX -march=armv6 -mfpu=vfp -mfloat-abi=hard -fPIC -ftree-vectorize -Wno-psabi -pipe -DOF_USING_GTK -DOF_USING_GTK -DTARGET_RASPBERRY_PI -DSTANDALONE -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM
```

**Comment by brannondorsey** [comment]
I'm not near my RPi rn but it just dawned on me that it is possible that my `~/.bashrc` could be exporting the env var `PLATFORM_VARIANT` from when it was required from an earlier OF release. I haven't used this RPi in a while so maybe I did something like that a few months ago for an earlier release where that was required. Will post soon.

**Comment by brannondorsey** [comment]
Turns out `export MAKEFLAGS="-j4 PLATFORM_VARIANT=rpi2"` was in my `~/.profile`. Curse my old self, thanks to both of you for providing helpful information and sorry for the scare.
