### ISSUE TITLE
ofAVFoundationPlayer - getPixels() results in error if the first movie load was unsuccessful

### ISSUE THREAD

**Issue by fakob** [openframeworks/openFrameworks#4967]
There seems to be a bug with the ofAVFoundationPlayer. 

Using getPixels() to grab a frame of a movie throws an error if the first movie load was unsuccessful. If the first movie load is successful and sometime later you have an unsuccessful one the error does not appear.

These lines work fine:
```
ofVideoPlayer loadedMovie;
ofPixels tempPixels;

loadedMovie.load("ExistingMovie.mp4");
tempPixels = loadedMovie.getPixels();
```

These lines result in an error:
```
ofVideoPlayer loadedMovie;
ofPixels tempPixels;

loadedMovie.load("NonExistingMovie.mp4"); // failed movie load, no movie gets loaded
loadedMovie.load("ExistingMovie.mp4");
tempPixels = loadedMovie.getPixels();
```

Error:
> [ error ] ofAVFoundationPlayer: getPixels(): Returning pixels that may be unallocated. Make sure to initialize the video player before calling getPixels.

I also tried to close() the player after the failed movie load and before loading a new one, but that made no difference. How can I initialize the video player again or is there something else wrong? Any ideas would greatly be appreciated?

There was another post regarding this error, but for the ofxiOSVideoPlayer. Are they maybe related?
Video to sequence - https://forum.openframeworks.cc/t/video-to-sequence/19117

My setup:
Using of v0.9.2 with Qt Creator 3.6.0 on OS X 10.11

**Comment by ofTheo** [comment]
Thanks for reporting the bug! 

Does this fix it for you:

if you replace ofAVFoundationPlayer::loadPlayer with this:

```
//--------------------------------------------------------------
bool ofAVFoundationPlayer::loadPlayer(string name, bool bAsync) {
	if( ofGetUsingArbTex() == false ){
        killTextureCache();
		bUseTextureCache = false;
    }
	
	NSString * videoPath = [NSString stringWithUTF8String:name.c_str()];
	NSString * videoLocalPath = [NSString stringWithUTF8String:ofToDataPath(name).c_str()];
	
	BOOL bStream = NO;
	
	bStream = bStream || (ofIsStringInString(name, "http://"));
	bStream = bStream || (ofIsStringInString(name, "https://"));
	bStream = bStream || (ofIsStringInString(name, "rtsp://"));
	
	NSURL * url = nil;
	if(bStream == YES) {
		url = [NSURL URLWithString:videoPath];
	} else {
		url = [NSURL fileURLWithPath:videoLocalPath];
	}

	bFrameNew = false;
	bResetPixels = true;
	bUpdatePixels = true;
	bUpdateTexture = true;
	
	bool bLoaded = false;
	
    // reuse videoplayer
    if(videoPlayer != nullptr) {
		// use existing player
		bLoaded = [videoPlayer loadWithURL:url async:bAsync];
    }else{
		// create a new player
		videoPlayer = [[ofAVFoundationVideoPlayer alloc] init];
		[videoPlayer setWillBeUpdatedExternally:YES];

		bLoaded = [videoPlayer loadWithURL:url async:bAsync];
	}
		
	pixels.clear();
	videoTexture.clear();
	
	bool bCreateTextureCache = bUseTextureCache && (_videoTextureCache == nullptr);
	
	if(bCreateTextureCache == true) {

		CVReturn err;
		
#if defined(TARGET_OF_IOS) && defined(__IPHONE_6_0)
		err = CVOpenGLESTextureCacheCreate(kCFAllocatorDefault,
										   nullptr,
										   [EAGLContext currentContext],
										   nullptr,
										   &_videoTextureCache);
#endif
		
#if defined(TARGET_OF_IOS) && !defined(__IPHONE_6_0)
		err = CVOpenGLESTextureCacheCreate(kCFAllocatorDefault,
										   nullptr,
										   (__bridge void *)[EAGLContext currentContext],
										   nullptr,
										   &_videoTextureCache);
#endif
		
#ifdef TARGET_OSX
		err = CVOpenGLTextureCacheCreate(kCFAllocatorDefault,
										 nullptr,
										 CGLGetCurrentContext(),
										 CGLGetPixelFormat(CGLGetCurrentContext()),
										 nullptr,
										 &_videoTextureCache);
#endif
		
		if(err) {
			ofLogWarning("ofAVFoundationPlayer") << "load(): error when creating texture cache, " << err << ".";
		}
	}

	
	if( bAsync == false && bLoaded){
		pixels.allocate(getWidth(), getHeight(), getPixelFormat());
	}
	
    return bLoaded;
}
```

**Comment by fakob** [comment]
Hi Theo, thanks for the fast reply. 
Your fix might work, but I am sorry to say, I do not know where to add it. 
I can not find "ofAVFoundationPlayer::loadPlayer" anywhere and adding it to ofAVFoundationPlayer.h or ofAVFoundationVideoPlayer.h brings errors. 
Please explain.

**Comment by ofTheo** [comment]
@fakob - no problem :) 
loadPlayer is in ofAVFoundationPlayer.mm on line 63

https://github.com/openframeworks/openFrameworks/blob/0.9.3/libs/openFrameworks/video/ofAVFoundationPlayer.mm#L63

**Comment by ofTheo** [comment]
I should also note though that with the way the AVF video player is designed you won't usually get the video pixels immediately after load is called. 

You would need to call the update function and then wait for isFrameNew to be true to grab the first frame of pixels. 

Currently we're just allocating the pixels to be the correct size, but they won't have video data until isFrameNew is true. 

I hope that helps!

The issue you pointed out though is definitely a bug. 
Which I think the code above should fix.

**Comment by fakob** [comment]
@ofTheo thanks. Your magic fixed the bug. Qt Creator does apparently not show the .mm files so my search wasn't successful.
And thanks for pointing out, that AVF video player runs asynchronously in this regard. 
I am trying to update my [MoviePrint app](http://www.fakob.com/2014/movieprint-an-osx-tool/) for which frame grabbing and frame wise going back and forth is essential.
