### ISSUE TITLE
OF v 0.9.0, Ubuntu 15.10 poco undefined references

### ISSUE THREAD

**Issue by ramalhoruben** [openframeworks/openFrameworks#4969]
I followed the installation instruction on:
http://openframeworks.cc/setup/linux-install/

I even manually recompiled poco with:
./apothecary update poco

But I am getting a lot of undefined references when compiling any of the examples:

ofURLFileLoader.cpp:(.text+0x6ed3): referência indefinida a `Poco::URI::URI(std::string const&)'
ofURLFileLoader.cpp:(.text+0x6ee2): referência indefinida a `Poco::URI::getPathAndQuery() const'
ofURLFileLoader.cpp:(.text+0x6f14): referência indefinida a `Poco::Net::HTTPMessage::HTTP_1_1'
ofURLFileLoader.cpp:(.text+0x6f19): referência indefinida a `Poco::Net::HTTPRequest::HTTP_GET'
ofURLFileLoader.cpp:(.text+0x6f21): referência indefinida a `Poco::Net::HTTPRequest::HTTPRequest(std::string const&, std::string const&, std::string const&)'
ofURLFileLoader.cpp:(.text+0x6f44): referência indefinida a `Poco::Net::NameValueCollection::add(std::string const&, std::string const&)'
ofURLFileLoader.cpp:(.text+0x6fa8): referência indefinida a `Poco::Net::HTTPSClientSession::HTTPSClientSession(std::string const&, unsigned short)'
ofURLFileLoader.cpp:(.text+0x7234): referência indefinida a `Poco::Net::HTTPClientSession::HTTPClientSession(std::string const&, unsigned short)'
ofURLFileLoader.cpp:(.text+0x741d): referência indefinida a `Poco::Exception::displayText() const'
ofURLFileLoader.cpp:(.text+0x74f9): referência indefinida a `Poco::Exception::displayText() const'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofURLFileLoader.o): na função `Poco::ScopedLock<Poco::FastMutex>::~ScopedLock()':
ofURLFileLoader.cpp:(.text._ZN4Poco10ScopedLockINS_9FastMutexEED2Ev[_ZN4Poco10ScopedLockINS_9FastMutexEED5Ev]+0x65): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofUtils.o): na função `ofLaunchBrowser(std::string const&, bool)':
ofUtils.cpp:(.text+0x8cf9): referência indefinida a `Poco::URI::URI(std::string const&)'
ofUtils.cpp:(.text+0x8d2e): referência indefinida a `Poco::URI::setQuery(std::string const&)'
ofUtils.cpp:(.text+0x8d54): referência indefinida a `Poco::URI::toString() const'
ofUtils.cpp:(.text+0x8e42): referência indefinida a `Poco::URI::toString() const'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o): na função `ofThread::run()':
ofThread.cpp:(.text+0x299): referência indefinida a `Poco::Exception::displayText() const'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o): na função `ofThread::startThread(bool)':
ofThread.cpp:(.text+0x888): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
ofThread.cpp:(.text+0x90a): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o): na função `ofThread::getThreadName() const':
ofThread.cpp:(.text+0xb06): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
ofThread.cpp:(.text+0xb64): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o): na função `ofThread::threadedFunction()':
ofThread.cpp:(.text+0xe7a): referência indefinida a `Poco::SystemException::SystemException(std::string const&, int)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o):ofThread.cpp:(.text+0xed3): seguem-se mais referências indefinidas a `Poco::SystemException::SystemException(std::string const&, int)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofThread.o): na função `ofThread::ofThread()':
ofThread.cpp:(.text+0x152e): referência indefinida a `Poco::Thread::setName(std::string const&)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofImage.o): na função `bool loadImage<unsigned short>(ofPixels_<unsigned short>&, std::string)':
ofImage.cpp:(.text+0x28cc): referência indefinida a `Poco::URI::URI(std::string const&)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofImage.o): na função `bool loadImage<float>(ofPixels_<float>&, std::string)':
ofImage.cpp:(.text+0x2dac): referência indefinida a `Poco::URI::URI(std::string const&)'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofImage.o): na função `bool loadImage<unsigned char>(ofPixels_<unsigned char>&, std::string)':
ofImage.cpp:(.text+0x328c): referência indefinida a `Poco::URI::URI(std::string const&)'
collect2: error: ld returned 1 exit status
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:381: recipe for target 'bin/noise1dExample' failed
make[1]: *** [bin/noise1dExample] Error 1
make[1]: Leaving directory '/home/ruben/Transferências/of_v0.9.0_linux64_release/examples/math/noise1dExample'
/home/ruben/Transferências/of_v0.9.0_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: *** [Release] Error 2

Can anyone help me?

**Comment by arturoc** [comment]
This is related to poco not being compatible when it's compiled with gcc 4.x and gcc 5. ubuntu 15.10 uses gcc 5 but the library was originally compiled with 4.8

When the install_dependencies script runs it should recompile poco to solve this problem. when you run the script does it tell you that it's going to recompile poco? 

You can also try deleting the original poco folder in libs/poco and run the install_dependencies script or apothecary to be completely sure that poco is being updated

**Comment by ramalhoruben** [comment]
Yes it does tell me that it's going to recompile poco. But the error still
happens. I will try to delete poco in lib and retry to run the examples,
I'll report the results soon.
Em 04/03/2016 12:56, "arturo" <notifications@github.com> escreveu:

**Comment by ramalhoruben** [comment]
The same thing happened. Unfortunately.. Any ideas of why?

**Comment by arturoc** [comment]
can you check the version of gcc you have installed? with gcc -v

**Comment by ramalhoruben** [comment]
Yes. Here's the output:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu
4.9.3-5ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs
--enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr
--program-suffix=-4.9 --enable-shared --enable-linker-build-id
--libexecdir=/usr/lib --without-included-gettext --enable-threads=posix
--with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls
--with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug
--enable-libstdcxx-time=yes --enable-gnu-unique-object
--disable-vtable-verify --enable-plugin --with-system-zlib
--disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo
--with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre
--enable-java-home
--with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64
--with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64
--with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar
--enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686
--with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib
--with-tune=generic --enable-checking=release --build=x86_64-linux-gnu
--host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.3 (Ubuntu 4.9.3-5ubuntu1)


2016-03-04 15:32 GMT+00:00 arturo <notifications@github.com>:

**Comment by arturoc** [comment]
yeah that's the problem, ubuntu 15.10 uses gcc 5 and the standard
library that comes with it is the one for gcc5 so if you try to compile
with 4.9 it'll have some problems. not sure why you have gcc 4.9 it
should default to 5. perhaps you've installed it manually or something.
try removing it and check again until it reports the correct version

**Comment by ramalhoruben** [comment]
Ohhh.. now I remember.
I do happen to use theano, and for that reason I had to install nvidia cuda
toolkit which required me to use a version earlier than 5.
I can't really change my gcc version, is there any workaround? :/

Thank you

2016-03-04 15:40 GMT+00:00 arturo <notifications@github.com>:

**Comment by arturoc** [comment]
try using the libraries that come with the download instead of
recompiling them.

**Comment by martialgallorini** [comment]
hello,

Similar problem here.

i am building a project under Debian Jessie 32 bits or 64 bits on intel platform
Building the project with openFrameworks 0.9.2 is fine

`In file included from /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp:1:0: /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.h:29:48: error: expected class-name before ‘{’ token class TerminalListener : public Poco::Runnable { ^ /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.h:42:9: error: ‘Thread’ in namespace ‘Poco’ does not name a type Poco::Thread thread; ^ /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp: In member function ‘void ofx::piMapper::TerminalListener::setup(ofx::piMapper::KeyListener*, int)’: /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp:37:8: error: expected unqualified-id before ‘.’ token thread.start(*this); ^ /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp: In member function ‘void ofx::piMapper::TerminalListener::run()’: /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp:41:15: error: expected primary-expression before ‘.’ token while (thread.isRunning()){ ^ /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp:62:10: error: expected unqualified-id before ‘.’ token thread.sleep(sleepTime); ^ /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp: In member function ‘void ofx::piMapper::TerminalListener::close()’: /home/major/oF092/addons/ofxPiMapper/src/Utils/TerminalListener.cpp:69:8: error: expected unqualified-id before ‘.’ token thread.tryJoin(50); ^ /home/major/oF092/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:335: recipe for target '/home/major/oF092/addons/obj/linux64/Release/ofxPiMapper/src/Utils/TerminalListener.o' failed make[1]: *** [/home/major/oF092/addons/obj/linux64/Release/ofxPiMapper/src/Utils/TerminalListener.o] Error 1 make[1]: Leaving directory '/home/major/oF092/apps/myApps/ofMapper' /home/major/oF092/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed make: *** [Release] Error 2`
