### ISSUE TITLE
Feature : ofAppGLFWWindow::getSettings()

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4982]
When creating new windows on the fly, it's handy to be able to get the settings from the main window, e.g.:
```c++
	ofGLFWWindowSettings getSettings() const {
		return this->settings;
	}
```
this might also better be called `getGLFWWindowSettings`

**Comment by arturoc** [comment]
This is already there: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.h#L97

:)
