### ISSUE TITLE
assimpExample app crashes in OF 0.9.3

### ISSUE THREAD

**Issue by antimodular** [openframeworks/openFrameworks#4994]
i am on OS X 10.10 with xcode 6.4 running the OF 0.9.3

compiling assimpExample works well but right after the app starts this crash error appeared in the console:
[verbose] ofxAssimpModelLoader: loadModel(): loading "astroBoy_walk.dae" from "../../../data/"
(lldb) 

here a screen shot
<img width="1398" alt="screen shot 2016-03-15 at 10 03 09 am" src="https://cloud.githubusercontent.com/assets/3649364/13780278/284f806e-ea95-11e5-8f97-75bc30062e5b.png">

**Comment by ofTheo** [comment]
Thanks for reporting this.
I can confirm. 

It seems to be a bug with the optimize flag. 
If you set optimize to false in loadModel, it won't crash. 

I tried replacing the assimp lib from 0.9.3 with the one from 0.9.0 and that seems to fix the issue. 

Ping @NickHardeman as it looks like he updated the lib:
https://github.com/openframeworks/openFrameworks/tree/0.9.3/addons/ofxAssimpModelLoader/libs/assimp/lib/osx

@NickHardeman if you try the 0.9.3 download does the assimp example crash for you ( needs to be 64bit as 32bit is broken in 0.9.3 ) ?  If you replace the assimp lib with the 0.9.0 does that work fine?

If so then it could be an easy fix to put back the old lib.

**Comment by antimodular** [comment]
thanks.
changing model.loadModel("astroBoy_walk.dae", true); to model.loadModel("astroBoy_walk.dae", false);
worked.

**Comment by arturoc** [comment]
i think this happens in linux too. i've had crashes with that same model lately and didn't knew why so it's surely a bug in assimp itself since the library in linux is the one in the system.

we can just change the example to not use optimizations

**Comment by ofTheo** [comment]
I can switch the debug to false for the example thought it might be worth seeing if replacing the lib also fixes it for both.

**Comment by danoli3** [comment]
3.2 Assimp was released Nov15... should look at merging those changes for 0.10.x

**Comment by NickHardeman** [comment]
Yes the example crashes for me in 64 bit. I'm using Xcode 5.1.1 on OSX 10.8.5.
I switched out the assimp lib and include directory for the 090 version and get a crash in ofApp::setup() here:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp#L40
But turning off the optimize flag eliminates the crash in both the 090 and 093 versions.

**Comment by NickHardeman** [comment]
If I remove the aiProcess_OptimizeGraph from the initImportProperties method https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp#L77
then it removes the crash.

**Comment by bakercp** [comment]
Hi @antimodular could you check and see if this is still an issue in the current master branch?  Thanks!

**Comment by kylemcdonald** [comment]
i was just able to run assimpExample using the current master on macOS 10.13.

but it does seem strange to have an optional flag that makes the difference between crashing and not crashing.
