### ISSUE TITLE
ofParameterGroup::clear not removing parent from ofParameter

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#4996]
I found this odd behaviour when clearing an ```ofParameterGroup``` and re-adding ```ofParameter```. The ```parents``` variable of the parameter grows, the references to the group are not removed on the group clearing. Lead to freezes in an app I wrote.

This is the code:
``` c++
ofParameterGroup group;
ofParameter <float> parameter;

parameter.set("parameter", 0, 0,1);

group.setName("group");
group.add(parameter);

for(int i = 0; i < 20; i++){
	group.clear();
	group.add(parameter);
}
```
And a screenshot of my compiler showing the ```parents``` of the parameter:
![parameter parents](https://cloud.githubusercontent.com/assets/708121/13792701/79a67e50-eaf3-11e5-9c2c-b266f046fd41.png)

I would love to solve this but the ```ofParameter``` class is pretty difficult to read. If one can give me a hint or if this has a reason please leave a comment.

**Comment by arturoc** [comment]
Yeah this sounds like a bug. i guess when you clear a parameter group it should iterate over the children and remove itself from it's parents. this is probably even not possible right now since there's no methods to remove parents i think.

i'll take a look when i have a moment

**Comment by arturoc** [comment]
actually i'm looking into this and it seems correct. the parameter group doesn't remove itself as a parent but the parameters contain weak pointers to the parent so once it's deleted it won't try to use it any more. the vector growing you are seeing is correct but then the parameter when it tries to find the first parent in line 491:

```
auto first = std::find_if(obj->parents.begin(),obj->parents.end(),[](weak_ptr<ofParameterGroup::Value> p){return p.lock()!=nullptr;});
```
it should find the first valid parent if there's one.

can you post an example that it's crashing?

**Comment by arturoc** [comment]
oh sorry i see what you mean now, the weak ptr will only work when the parent is destroyed not when it's cleared

**Comment by arturoc** [comment]
@frauzufall can you check if #5000 fixes it?

**Comment by frauzufall** [comment]
#5000, congrats :) 

No, the weak pointers still pile up in the ```parents``` vector. Why is the erasing done in ```getFirstParent()```? I don't see that function get called anywhere.

**Comment by arturoc** [comment]
:) yes it's ok if they accumulate it's done like that so the parent doesn't need a destructor, copy constructor.... 

whenever the parent goes away, the weak pointer becomes invalid, next time the parameter tries to trigger the event it'll try to get the parent through that method and delete the invalid pointers all at once.

is the crash still happening?

**Comment by frauzufall** [comment]
Yes you are right. It's working now, thank you! 
Just one small thing: It now deletes the group name on ```clear()```. I don't think that's expected, at least not for me.

**Comment by frauzufall** [comment]
And thank you for explaining!

**Comment by arturoc** [comment]
no, that shouldn't be happening, i'll fix it in a moment
