### ISSUE TITLE
ofImage: move constructor doesn't actually move

### ISSUE THREAD

**Issue by Spacechild1** [openframeworks/openFrameworks#5034]
Hi, I'm currently trying to fix some move constructors and assignments of container classes (mostly adding the noexcept keyword to make them work with the STL containers).
I noticed that ofImage's move constructor actually calls clone(), which only takes const lvalue refs and simply copies the pixels and allocates a new texture.
Move assignements are missing at all.
I don't see any reason why there couldn't be real move semantics involved: If you pass an ofImage that is an rvalue reference, why not simply steal the texture and pixels? Given that both ofPixels and ofTexture themselves already support move semantics this seems like a rather obvious thing to do.
Is this avoided on purpose?
If not, I'll include a commit with revised move constructors and assignments for ofImage in my future pull request.

**Comment by arturoc** [comment]
yes i'm taking a look and it seems that particular constructor was copied from the copy constructor but never adapted to really be a move constructor. if you can fix it that would be great.

btw, it seems you are generating some weird commits directly in the repo, not sure how, probably you are editing things directly in github? would be better if you could work directly in your machine and test things there for a something like this

thanks!

**Comment by Spacechild1** [comment]
Yeah, I tried to do some small things directly in github, but it's cumbersome and confusing. I'll do everything on my desktop.

**Comment by BrianSipple** [comment]
Just stumbled upon this issue now -- it looks like it can be closed after #5101 (cc @arturoc)

**Comment by arturoc** [comment]
thanks!
