### ISSUE TITLE
Fix : use size_t in ofPixels for size variables

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#5038]
right now ofPixels fails in a few places with very large images because it uses `int` as the size variable

e.g. in:
- `allocate`
- `size()`
- `getTotalBytes()`
- `bytesFromPixelFormat()`
- `resizeTo()`

**Comment by bakercp** [comment]
+1

**Comment by bakercp** [comment]
Fixed with 5f29231573564a8fa0cc0da5e5c66380e9943c01 and related.
