### ISSUE TITLE
Add `notifyAsync` to ofEvents to allow safer, easier cross thread ofEvent notification.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5039]
In the past, I've used the Poco notification system for cross thread messaging (e.g. `Poco::TaskNotification` in [ofxTaskQueue](https://github.com/bakercp/ofxTaskQueue/blob/master/libs/ofxTaskQueue/include/ofx/TaskQueueEvents.h)), but as we move away from Poco, I'm exploring possibilities using `ofThreadChannel` etc.  Here is pattern that extends `ofEvent` (although not completely, since it's just a mockup) to achieve thread-safe cross thread ofEvents.

`EventChannel.h`

``` c++

#pragma once


#include "ofThreadChannel.h"
#include "ofEvents.h"


namespace ofx {


/// \brief A thread-safe event dispatch channel.
///
/// Events dispatched using `notifyAsync` will be queued in an ofThreadChannel
/// until they are dispatched in the main thread on application update. This
/// allows event arguments to cross thread boundaries without requiring users
/// to synchronzie event callbacks that are registered with processes running
/// in an outside thread.
///
/// \tparam EventArgType The event argument type.
/// \tparam mutex The ofEvent internal mutex type.
template<typename EventArgType, typename Mutex=std::recursive_mutex>
class EventChannel: public ofEvent<EventArgType, Mutex>
{
public:
    /// \brief Create an event channel.
    ///
    /// Upon construction, the event channel registers itself to receive updates
    /// from the main thread.
    EventChannel():
        _updateListener(ofEvents().update.newListener(this, &EventChannel::update))
    {
    }

    /// \brief This update listener dispatches events from the main thread.
    /// \param args The update event arguments.
    void update(ofEventArgs& args)
    {
        EventArgType evt;

        while (_channel.tryReceive(evt))
        {
            // Notify the underlying ofEvent.
            this->notify(evt);
        }
    }

    /// \brief Add an event to the threadsafe notification queue.
    void notifyAsync(EventArgType& evt)
    {
        _channel.send(evt);
    }

private:
    /// \brief The update listener handle.
    ofEventListener _updateListener;

    /// \brief The thread channel for async events.
    ofThreadChannel<EventArgType> _channel;

};


} // namespace ofx

```

It's pretty simple, but I'm wondering if there would be interest in integrating this `notifyAsync` functionality as a part of `ofEvent`?  Or, perhaps this is better left as an ofEvent subclass?

Curious to hear what people think or other approaches cross-thread ofEvent use.

**Comment by underdoeg** [comment]
This looks awesome. Just to clarify, do I understand it correctly that the use case for this would be: 

You have a threaded function, dispatch the event there. Then you it will automatically be notified safely in the main thread? 

But it won't allow you to notify the event and then receive in another thread?

**Comment by bakercp** [comment]
Basically it allows ofEvents to be used safely back in the main thread (the same thread as update).  This is meant for users who want to seamlessly deliver events back to the main thread as events, rather than setting it all up with an ofThreadChannel manually.

**Comment by bakercp** [comment]
That said, going to close this for now as I'm using it in various addons and don't really need it in the core, as the response hasn't been significant.
