### ISSUE TITLE
Compile Errors Armv7 generic install : odroid XU4

### ISSUE THREAD

**Issue by bitSpaz** [openframeworks/openFrameworks#5044]
Hello,
I'm trying to compile openFrameworks with the ./compileOF.sh -j8 script. Hopefully I'm doing something wrong that can easily be addressed. 

Thanks,

Barney

Particulars:
Ubuntu 15.10 (image from Odroid site)
Odroid XU4

Errors:
 /home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofGLRenderer.o -c /home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofTexture.cpp: In member function 'void ofTexture::generateMipmap()':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofTexture.cpp:684:42: error: 'glGenerateMipmap' was not declared in this scope
    glGenerateMipmap(texData.textureTarget);
                                          ^
Compiling /home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLUtils.cpp
g++ -g3  -Wall -std=c++14 -DGCC_HAS_REGEX -march=armv7 -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -fPIC -ftree-vectorize -Wno-psabi -pipe -DOF_USING_GTK -DOF_USING_GTK -DOF_USING_MPG123 -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/include -I/usr/include/AL -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/libdrm -I/home/odroid/of_v0.9.3/libs/fmodex/include -I/home/odroid/of_v0.9.3/libs/glfw/include -I/home/odroid/of_v0.9.3/libs/glfw/include/GLFW -I/home/odroid/of_v0.9.3/libs/kiss/include -I/home/odroid/of_v0.9.3/libs/poco/include -I/home/odroid/of_v0.9.3/libs/tess2/include -I/home/odroid/of_v0.9.3/libs/utf8cpp/include -I/home/odroid/of_v0.9.3/libs/utf8cpp/include/utf8 -I/home/odroid/of_v0.9.3/libs/openFrameworks -I/home/odroid/of_v0.9.3/libs/openFrameworks/video -I/home/odroid/of_v0.9.3/libs/openFrameworks/events -I/home/odroid/of_v0.9.3/libs/openFrameworks/app -I/home/odroid/of_v0.9.3/libs/openFrameworks/communication -I/home/odroid/of_v0.9.3/libs/openFrameworks/sound -I/home/odroid/of_v0.9.3/libs/openFrameworks/graphics -I/home/odroid/of_v0.9.3/libs/openFrameworks/math -I/home/odroid/of_v0.9.3/libs/openFrameworks/gl -I/home/odroid/of_v0.9.3/libs/openFrameworks/utils -I/home/odroid/of_v0.9.3/libs/openFrameworks/3d -I/home/odroid/of_v0.9.3/libs/openFrameworks/types -DDEBUG  -MMD -MP -MF /home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofGLUtils.d -MT/home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofGLUtils.o -o /home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofGLUtils.o -c /home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLUtils.cpp
makefileCommon/compile.core.mk:239: recipe for target '/home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofTexture.o' failed
make[1]: **\* [/home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofTexture.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In function 'void releaseShader(GLuint, GLuint)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:50:30: error: 'glDetachShader' was not declared in this scope
    glDetachShader(program, id);
                              ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:51:21: error: 'glDeleteShader' was not declared in this scope
    glDeleteShader(id);
                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:56:29: error: 'glDetachShader' was not declared in this scope
   glDetachShader(program, id);
                             ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:57:20: error: 'glDeleteShader' was not declared in this scope
   glDeleteShader(id);
                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In function 'void releaseProgram(GLuint)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:76:22: error: 'glDeleteProgram' was not declared in this scope
    glDeleteProgram(id);
                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:81:21: error: 'glDeleteProgram' was not declared in this scope
   glDeleteProgram(id);
                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'bool ofShader::setupShaderFromSource(GLenum, std::__cxx11::string, std::__cxx11::string)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:222:37: error: 'glCreateShader' was not declared in this scope
  GLuint shader = glCreateShader(type);
                                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:247:41: error: 'glShaderSource' was not declared in this scope
  glShaderSource(shader, 1, &sptr, &ssize);
                                         ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:248:24: error: 'glCompileShader' was not declared in this scope
  glCompileShader(shader);
                        ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:252:50: error: 'glGetShaderiv' was not declared in this scope
  glGetShaderiv(shader, GL_COMPILE_STATUS, &status);
                                                  ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'bool ofShader::checkProgramLinkStatus(GLuint)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:416:49: error: 'glGetProgramiv' was not declared in this scope
  glGetProgramiv(program, GL_LINK_STATUS, &status);
                                                 ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::checkShaderInfoLog(GLuint, GLenum, ofLogLevel)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:435:55: error: 'glGetShaderiv' was not declared in this scope
  glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &infoLength);
                                                       ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:439:75: error: 'glGetShaderInfoLog' was not declared in this scope
   glGetShaderInfoLog(shader, infoLength, &infoLength, infoBuffer.getData());
                                                                           ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::checkProgramInfoLog(GLuint)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:473:57: error: 'glGetProgramiv' was not declared in this scope
  glGetProgramiv(program, GL_INFO_LOG_LENGTH, &infoLength);
                                                         ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:477:77: error: 'glGetProgramInfoLog' was not declared in this scope
   glGetProgramInfoLog(program, infoLength, &infoLength, infoBuffer.getData());
                                                                             ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::checkAndCreateProgram()':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:505:30: error: 'glCreateProgram' was not declared in this scope
    program = glCreateProgram();
                              ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'bool ofShader::linkProgram()':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:525:38: error: 'glAttachShader' was not declared in this scope
     glAttachShader(program, shader.id);
                                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:529:24: error: 'glLinkProgram' was not declared in this scope
   glLinkProgram(program);
                        ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:536:59: error: 'glGetProgramiv' was not declared in this scope
   glGetProgramiv(program, GL_ACTIVE_UNIFORMS, &numUniforms);
                                                           ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:546:95: error: 'glGetActiveUniform' was not declared in this scope
    glGetActiveUniform(program, i, uniformMaxLength, &length, &count, &type, uniformName.data());
                                                                                               ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:550:68: error: 'glGetUniformLocation' was not declared in this scope
    uniformsCache[name] = glGetUniformLocation(program, name.c_str());
                                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::bindAttribute(GLuint, const string&) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:609:52: error: 'glBindAttribLocation' was not declared in this scope
  glBindAttribLocation(program,location,name.c_str());
                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform1i(const string&, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:728:37: error: 'glUniform1i' was not declared in this scope
   if (loc != -1) glUniform1i(loc, v1);
                                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform2i(const string&, int, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:736:41: error: 'glUniform2i' was not declared in this scope
   if (loc != -1) glUniform2i(loc, v1, v2);
                                         ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform3i(const string&, int, int, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:744:45: error: 'glUniform3i' was not declared in this scope
   if (loc != -1) glUniform3i(loc, v1, v2, v3);
                                             ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform4i(const string&, int, int, int, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:752:50: error: 'glUniform4i' was not declared in this scope
   if (loc != -1)  glUniform4i(loc, v1, v2, v3, v4);
                                                  ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform1f(const string&, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:760:37: error: 'glUniform1f' was not declared in this scope
   if (loc != -1) glUniform1f(loc, v1);
                                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform2f(const string&, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:768:41: error: 'glUniform2f' was not declared in this scope
   if (loc != -1) glUniform2f(loc, v1, v2);
                                         ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform3f(const string&, float, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:776:45: error: 'glUniform3f' was not declared in this scope
   if (loc != -1) glUniform3f(loc, v1, v2, v3);
                                             ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform4f(const string&, float, float, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:784:49: error: 'glUniform4f' was not declared in this scope
   if (loc != -1) glUniform4f(loc, v1, v2, v3, v4);
                                                 ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform1iv(const string&, const int_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:813:44: error: 'glUniform1iv' was not declared in this scope
   if (loc != -1) glUniform1iv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform2iv(const string&, const int_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:821:44: error: 'glUniform2iv' was not declared in this scope
   if (loc != -1) glUniform2iv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform3iv(const string&, const int_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:829:44: error: 'glUniform3iv' was not declared in this scope
   if (loc != -1) glUniform3iv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform4iv(const string&, const int_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:837:44: error: 'glUniform4iv' was not declared in this scope
   if (loc != -1) glUniform4iv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform1fv(const string&, const float_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:845:44: error: 'glUniform1fv' was not declared in this scope
   if (loc != -1) glUniform1fv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform2fv(const string&, const float_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:853:44: error: 'glUniform2fv' was not declared in this scope
   if (loc != -1) glUniform2fv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform3fv(const string&, const float_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:861:44: error: 'glUniform3fv' was not declared in this scope
   if (loc != -1) glUniform3fv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniform4fv(const string&, const float_, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:869:44: error: 'glUniform4fv' was not declared in this scope
   if (loc != -1) glUniform4fv(loc, count, v);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniformMatrix3f(const string&, const ofMatrix3x3&, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:896:63: error: 'glUniformMatrix3fv' was not declared in this scope
   if (loc != -1) glUniformMatrix3fv(loc, count, GL_FALSE, &m.a);
                                                               ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setUniformMatrix4f(const string&, const ofMatrix4x4&, int) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:904:69: error: 'glUniformMatrix4fv' was not declared in this scope
   if (loc != -1) glUniformMatrix4fv(loc, count, GL_FALSE, m.getPtr());
                                                                     ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute1f(GLint, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:937:32: error: 'glVertexAttrib1f' was not declared in this scope
   glVertexAttrib1f(location, v1);
                                ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute2f(GLint, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:943:36: error: 'glVertexAttrib2f' was not declared in this scope
   glVertexAttrib2f(location, v1, v2);
                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute3f(GLint, float, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:949:40: error: 'glVertexAttrib3f' was not declared in this scope
   glVertexAttrib3f(location, v1, v2, v3);
                                        ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute4f(GLint, float, float, float, float) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:955:44: error: 'glVertexAttrib4f' was not declared in this scope
   glVertexAttrib4f(location, v1, v2, v3, v4);
                                            ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute1fv(const string&, const float_, GLsizei) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:962:68: error: 'glVertexAttribPointer' was not declared in this scope
    glVertexAttribPointer(location, 1, GL_FLOAT, GL_FALSE, stride, v);
                                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:963:38: error: 'glEnableVertexAttribArray' was not declared in this scope
    glEnableVertexAttribArray(location);
                                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute2fv(const string&, const float_, GLsizei) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:972:68: error: 'glVertexAttribPointer' was not declared in this scope
    glVertexAttribPointer(location, 2, GL_FLOAT, GL_FALSE, stride, v);
                                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:973:38: error: 'glEnableVertexAttribArray' was not declared in this scope
    glEnableVertexAttribArray(location);
                                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute3fv(const string&, const float_, GLsizei) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:983:68: error: 'glVertexAttribPointer' was not declared in this scope
    glVertexAttribPointer(location, 3, GL_FLOAT, GL_FALSE, stride, v);
                                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:984:38: error: 'glEnableVertexAttribArray' was not declared in this scope
    glEnableVertexAttribArray(location);
                                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::setAttribute4fv(const string&, const float_, GLsizei) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:993:68: error: 'glVertexAttribPointer' was not declared in this scope
    glVertexAttribPointer(location, 4, GL_FLOAT, GL_FALSE, stride, v);
                                                                    ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:994:38: error: 'glEnableVertexAttribArray' was not declared in this scope
    glEnableVertexAttribArray(location);
                                      ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'GLint ofShader::getAttributeLocation(const string&) const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1027:50: error: 'glGetAttribLocation' was not declared in this scope
  return glGetAttribLocation(program, name.c_str());
                                                  ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::printActiveUniforms() const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1044:58: error: 'glGetProgramiv' was not declared in this scope
  glGetProgramiv(program, GL_ACTIVE_UNIFORMS, &numUniforms);
                                                          ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1056:87: error: 'glGetActiveUniform' was not declared in this scope
   glGetActiveUniform(program, i, uniformMaxLength, &length, &count, &type, uniformName);
                                                                                       ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1061:67: error: 'glGetUniformLocation' was not declared in this scope
   line << " @ index " << glGetUniformLocation(program, uniformName);
                                                                   ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp: In member function 'void ofShader::printActiveAttributes() const':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1069:62: error: 'glGetProgramiv' was not declared in this scope
  glGetProgramiv(program, GL_ACTIVE_ATTRIBUTES, &numAttributes);
                                                              ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofShader.cpp:1081:90: error: 'glGetActiveAttrib' was not declared in this scope
   glGetActiveAttrib(program, i, attributeMaxLength, &length, &count, &type, attributeName);
                                                                                          ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp: In member function 'virtual void ofGLRenderer::bind(const ofShader&)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp:447:34: error: 'glUseProgram' was not declared in this scope
  glUseProgram(shader.getProgram());
                                  ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp: In member function 'virtual void ofGLRenderer::unbind(const ofShader&)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp:452:16: error: 'glUseProgram' was not declared in this scope
  glUseProgram(0);
                ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp: In member function 'virtual void ofGLRenderer::bind(const ofFbo&)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp:500:56: error: 'glBindFramebuffer' was not declared in this scope
  glBindFramebuffer(GL_FRAMEBUFFER, currentFramebufferId);
                                                        ^
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp: In member function 'virtual void ofGLRenderer::unbind(const ofFbo&)':
/home/odroid/of_v0.9.3/libs/openFrameworks/gl/ofGLRenderer.cpp:534:56: error: 'glBindFramebuffer' was not declared in this scope
  glBindFramebuffer(GL_FRAMEBUFFER, currentFramebufferId);
                                                        ^
makefileCommon/compile.core.mk:239: recipe for target '/home/odroid/of_v0.9.3/libs/openFrameworksCompiled/lib/linuxarmv7l/obj/Debug/libs/openFrameworks/gl/ofShader.o' failed

**Comment by jvcleave** [comment]
Did you run install_dependencies.sh?

**Comment by bitSpaz** [comment]
Yes I did. I followed the generic arm7 setup guide to the letter. Out of curiosity how come the guide doesn’t have the compile open frameworks step that the RPi guide does? I found it in the INSTALL.md file. It seems important since the -j8 (XU4 has 8 cores) option is exposed.

Thanks,

Barney

**Comment by jvcleave** [comment]
From your compiler messages it looks like certain OpenGL libraries/headers are missing (which is why I asked about install_dependencies.sh). Sometimes on these boards they can be in a weird path (where usually in `/usr/include/GL`, '/usr/include/GLES', etc). If they provide any examples, I would look for a regular OpenGL example Makefile  and compare it to what OF is looking for.

At the time of the RPi guide I don't think CompileOF.sh worked on the RPi. As for -j8, you have to be careful as each job takes up quite a bit of memory and can cause the compiler to get killed.

**Comment by bitSpaz** [comment]
I’m not sure where to look for a regular OpenGL makefile.  I concocted another way to compare them. It could be a problematic strategy, but here goes.
I compared  the GL and GLES file paths and folders in an older working version of OF to the new one. They new one has a couple extra header files, but I couldn’t see much difference.
I hope this sheds some light on the issue.

Thanks

Old version:
Ubuntu Mate 10.4
OF 9.0

New:
Ubuntu Mate 10.10
OF 9.3

Old:


New:

**Comment by bitSpaz** [comment]
I meant 15.10 and 15.04. I reverted to OS X versioning.

What I don’t understand is that it worked on 15.04 and OF 0.09.

Could this be the issue?

Updated Mali Driver to r9p0 (OpenGL <http://odroid.com/dokuwiki/doku.php?id=en:opengl> ES 3.1 works on X11)

I found this which may be a tangent since it doesn’t have the same problems. It does have to do with openGl issues.

http://forum.odroid.com/viewtopic.php?f=61&t=2893

Really flailing here, but…

**Comment by jvcleave** [comment]
[This post] (http://forum.odroid.com/viewtopic.php?p=94831&sid=0534208cf4b30a86d8898a78fb3cd73c#p94831) is the scenario I was talking about with "weird path". I would try that

**Comment by bitSpaz** [comment]
I’m still having trouble compiling.
Is there any documentation about defining file paths in config or make files?
Specifically how does one point OF to the  mali-egl directory? I tried the symlink in the post without success,
Thanks

**Comment by ntzovanis** [comment]
@bitSpaz I'm having the same issue, were you able to find a workaround? I'm using Ubuntu 16.04 and oF 0.9.8

Thanks!

**Comment by alberto2000** [comment]
Having the same issue here ... compileOF.sh fails and also compiling any example fails with errors about methods that can't be found... I'd be happy on any update on this

**Comment by bitSpaz** [comment]
No, I haven’t resolved this. Been too busy, but may give it another go around this summer. In the interim I’ve been using a Raspberry Pi 3 for my embedded projects.
If I do manage to solve this I’ll post the solution to this thread.

**Comment by johnkingsley** [comment]
I had similar errors building on Raspberry Pi 3, using the a fresh checkout from github.

The problem was that download_libs.sh was getting the wrong library from
http://ci.openframeworks.cc/libs/

To get around this, I supplied the parameter --platform on the download_libs.sh script, like this:
```
cd scripts/linux
./download_libs.sh --platform linuxarmv6l
```

If you don't supply --platform then it uses the linuxarmv7l libraries on the Rasp Pi 3.
Once I got the correct libraries installed, my compile and link errors were gone.

I'm not sure if this is your problem or not, but it sounds similar.

**Comment by bakercp** [comment]
The download_libs.sh script was recently fixed to correctly get linuxarmv6l on raspberry pi.  Closing those for now.  @bitSpaz If you have updates, please reopen this thread.

**Comment by ntzovanis** [comment]
I got it compiling on the Odroid Xu4 by doing this:

`apt-get --assume-yes remove libgles2-mesa-dev`
`apt-get --assume-yes install libgles2-mesa-dev`
`apt-get --assume-yes remove libgles1-mesa-dev`
`apt-get --assume-yes install libgles1-mesa-dev` 

I'm not sure how does that solve it, but it my case it does. Hope it helps.

**Comment by bitSpaz** [comment]
@bakercp 
I haven't had any problems with the Pi install. It's the linuxv7 install on the Odroid XU4 that has been problematic. I'm going to try @ntzovanis solution next week and report back. 
Nicolas, 
At what stage did you implement the apt-get commands outlined above?

**Comment by ntzovanis** [comment]
@bitSpaz I run those commands right before compiling. It seems that the installation of Mali drivers somehow affects the libraries.

**Comment by bitSpaz** [comment]
@bakercp @ntzovanis 
That fixed the compiling issue.
I'm disappointed with the XU4 though considering all the advertised fire power. Maybe others will get better results, but for now I'm sticking with the Pi 3.
Thanks though!

**Comment by Hi-Angel** [comment]
For peoples who as me came here from google simply trying to figure out where `glUniform1i` is declared — use `#include <GL/glew.h>`.
