### ISSUE TITLE
ofSystemLoadDialog on linux fails assertion in fccache at program exit, yields SIGABRT

### ISSUE THREAD

**Issue by macpete** [openframeworks/openFrameworks#5061]
Hi,

I could reproduce this problem on 64bit Ubuntu versions 12.04, 14.04, and 15.10, with oF 0.9.0 through 0.9.3, and master.

Just run  examples/input_output/fileOpenSaveDialogExample. Hit space to trigger the load dialog, press Escape or select a file. Exit the demo by pressing Escape. This results in the following output:

Upon bringing up the load dialog:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`

Upon closing the demo:
```
fileOpenSaveDialogExample: fccache.c:525: FcCacheFini: Assertion 'fcCacheChains[i] == ((void *)0)' failed.
[verbose] ofSignalHandler: Aborted
Aborted (core dumped)
```

The failing line in fccache.c varies with the Ubuntu/gtk version, but seems to be the same check on all affected systems.

Until the abort() at the end, the demo and my application, too, run fine. However the crash prevents my app from proper clean-up of its hardware resources, which means I can't just ignore it...

**Comment by macpete** [comment]
Please refer to this discussion:
[https://bugs.chromium.org/p/chromium/issues/detail?id=32091]

There the solution is to not call `FcFini()` and live with the leaks. I can report that commenting the only call to FcFini() in all of the  oF code base (libs/openFrameworks/graphics/ofTrueTypeFont.cpp, in function `ofTrueTypeShutdown()`) avoids the failed assertion also for my tested oF apps.

According to another discussion [http://www.spinics.net/lists/font-config/msg04334.html] the assertion may fail due to lingering Patterns, which were not destroyed before. I didn't dive deep enough into oF, yet, to identify the culprits.

**Comment by saki7** [comment]
:+1: on this issue

**Comment by camilasan** [comment]
Hi @saki7, I am getting the same error in Ubuntu 14.04, oF 0.9.3, when using ofSystemSaveDialog  or ofSystemLoadDialog and then closing the app.

`fccache.c:525: FcCacheFini: Assertion `fcCacheChains[i] == ((void *)0)' failed.
Aborted (core dumped)`
