### ISSUE TITLE
Refactor iOS code to use ARC?

### ISSUE THREAD

**Issue by rsanchezsaez** [openframeworks/openFrameworks#5063]
I think it'd be a good idea to refactor the iOS code to use ARC, as it's much safer and simpler.

I have a forked version of oF with ARC enabled that compiles and runs, but I'm afraid some parts of the sound streaming and video playing subsystems may be broken (and/or have retain cycles or memory leaks). I think this is due to the hack of including `void *` pointers in C++ headers that are used to reference ObjC objects (ARC doesn't really like that). Probably it'd be a good idea to rewrite these classes in a more modern ObjC style.

**Comment by jvcleave** [comment]
I worked on a project where I made the majority of OF ARC compatible. If I were to start to merge it what branch should I start with? With my project I started with 0.9.8

**Comment by arturoc** [comment]
master, the 0.9.x branch is only for minor bugfixes

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/6889
