### ISSUE TITLE
calling functions on ofParameter with Custom Object

### ISSUE THREAD

**Issue by underdoeg** [openframeworks/openFrameworks#5067]
According to the docs this should be possible:
```
For an ofParameter with a custom object such as ofParameter<MyObject> myObject, MyObject's methods can be accessed using pointer syntax, e.g. myObject->myMethod();.
```

But I think because the operator overloader -> returns a const Object. I get the following error:

```
error: passing ‘const Orderable’ as ‘this’ argument discards qualifiers [-fpermissive]
```

**Comment by underdoeg** [comment]
What is the reason the operator overload -> for ofParameter returns a const? Since it only return a pointer it wouldn't matter if it gets copied or something?

**Comment by underdoeg** [comment]
Would it be feisable to have both options, like with ofParameter::getBool, where also both exist?

```
	const ofParameter<bool> & getBool(const string& name) const;
	ofParameter<bool> & getBool(const string& name);
```

**Comment by arturoc** [comment]
This is a known limitation but there's no way around it: the main functionality of ofParameter is to trigger an event when an object changes so others can know about that change. if we returned a non-const reference when using -> you could call a method that modified the internal value but ofParameter wouldn't be able to trigger the event after the value had changed.

If you need such functionality perhaps you can create a new parameter type extending ofAbstractParameter.

**Comment by underdoeg** [comment]
Ok, now I see the problem. Thx.  I'll create something like ofObjectParameter internally then. Maybe something like this might make it to the core at some point? It kind of makes sense to have a different parameter type for Objects. Since changed events won't work with them anyways...

**Comment by arturoc** [comment]
the idea is to follow a more functional approach in which you wont' mutate objects once created but you can still query their properties using -> or just completely replace them by a new one, so instead of doing:

```cpp
ofParameter<ofVec3f> p;
p->normalizze();
```

you do:

```cpp
ofParameter<ofVec3f> p;
p = p->getNormalized();
```

**Comment by underdoeg** [comment]
ok, I see. In my case I have just solved it by storing all necessary data as an integer. And my class now extends ofParameter<int>
