### ISSUE TITLE
Problems with OpenCV 3

### ISSUE THREAD

**Issue by mruegenberg** [openframeworks/openFrameworks#5086]
Since a few weeks, the OpenCV package on Arch Linux [installs OpenCV 3 by default](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/opencv). Unfortunately, ofxOpenCV seems to not be compatible (as can be seen when e.g trying to run a sample from ofxGLWarper).

This means that `install_dependencies.sh` is currently broken for Arch Linux.
Installing and using the [opencv2 package](https://aur.archlinux.org/packages/opencv2/) from AUR instead would presumably solve this.
(Anyone that runs into this problem can also try to `pacman -U /var/cache/pacman/pkg/opencv-2.4...` for a faster temporary fix.)

**Comment by underdoeg** [comment]
Interesting. I am also an arch user but I don't have this problem. Although it totally makes sense... :)

**Comment by mruegenberg** [comment]
I'm assuming this only happens after `pacman -Syu` with a fresh oF install. 

The example might not break (can't test this right now), but ofxGLWarper does, because it uses the `cvFindHomography` function, which was replaced by `cv::findHomography` in OpenCV 3. (see [old](http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#findhomography) and [new](http://docs.opencv.org/3.1.0/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780) docs).

So this *might* actually just be a problem of addons using older OpenCV APIs. However, it would be good to have a consistent version from ofxOpenCV (ie use either OpenCV 2 or OpenCV 3 on all systems).

**Comment by bakercp** [comment]
@mruegenberg is this still an issue on the master branch?

**Comment by mruegenberg** [comment]
I just tried the current oF nightly and a sample from ofxGLWarper and did not have any problems, so I assume this is no longer an issue.

**Comment by bakercp** [comment]
Thanks!
