### ISSUE TITLE
String tests failing on MSYS2

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#5087]
The 'tolower' and 'toupper' tests on accentuated characters are failing on MSYS2 (on my system and on Appveyor)

```
[ warning] ofUtils: Couldn't create locale  using default, C
[  error ] tolower failed 
[  error ] test_eq(ofToLower("AbCéÉBbCcc"), "abcéébbccc")
[  error ] value1: ofToLower("AbCéÉBbCcc") is abcéÉbbccc
[  error ] value2: "abcéébbccc" is abcéébbccc
[  error ] C:/projects/openframeworks/tests/utils/strings/src/main.cpp: 58
[ warning] ofUtils: Couldn't create locale  using default, C
[  error ] toupper failed 
[  error ] test_eq(ofToUpper("AbCéÉBbCcc"), "ABCÉÉBBCCC")
[  error ] value1: ofToUpper("AbCéÉBbCcc") is ABCéÉBBCCC
[  error ] value2: "ABCÉÉBBCCC" is ABCÉÉBBCCC
[  error ] C:/projects/openframeworks/tests/utils/strings/src/main.cpp: 59
```

The other tests pass even if there is the "Couldn't create locale  using default, C" warning.

Should we test for accentuated characters as the result may depend on the locale? Shouldn't we force locale for the tests ?

**Comment by dimitre** [comment]
I think I'm having similar issues while trying to convert strings with accents to upper or lower.
ofw 0.9.8 on OS X

**Comment by oxillo** [comment]
Using C setlocale seems to correct the issue but I'm concerned about side effects.


`setlocale(LC_ALL,locale.c_str())`

**Comment by arturoc** [comment]
we do something similar for linux if we detect a non utf8 locale so let's do this if it fixes the problem.

can you add a similar ifdef for windows non visual studio ater: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppRunner.cpp#L143-L156

```
#if defined(TARGET_WIN32) && !_MSC_VER
```

should detect windows but not visual studio
