### ISSUE TITLE
Problem with a new QT creator IDE

### ISSUE THREAD

**Issue by CharlesPL** [openframeworks/openFrameworks#5095]
/home/charllie/of-workspace/libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs:19: błąd: RangeError: Maximum call stack size exceeded.

Is there a solution for this?

**Comment by arturoc** [comment]
this is a problem with qtcreator 4.0, it's already solved in master so the nightly build should work fine. or you can download qtcreator 3.6.1

**Comment by CharlesPL** [comment]
So if I clone the github repo everything should be fine?

**Comment by underdoeg** [comment]
yes

**Comment by CharlesPL** [comment]
Big thanks guys :)
