### ISSUE TITLE
does lock in thread not block by default?

### ISSUE THREAD

**Issue by underdoeg** [openframeworks/openFrameworks#5106]
I just saw this line: 

https://github.com/openframeworks/openFrameworks/blob/ac79b88f0c290c7842a3da81b683085f3527eefc/libs/openFrameworks/utils/ofThread.cpp#L48

This sets mutexBlocks to false. I did not do a full search but it looks like this sets the default behavior of the thread to try locking instead of waiting?

**Comment by underdoeg** [comment]
Shouldn't this whole block be removed and just set to mutex.lock()? 

https://github.com/openframeworks/openFrameworks/blob/ac79b88f0c290c7842a3da81b683085f3527eefc/libs/openFrameworks/utils/ofThread.cpp#L70

Since setting the blocking mode is set to deprecated und there also is tryLock.

**Comment by arturoc** [comment]
yeah mutexBlock should be true by default, but the block that chooses if it should block or just try is ok as it is, that functionality is deprecated but it's still there so it should work as expected until is completely gone

**Comment by underdoeg** [comment]
You're right. I've sent a PR. This tiny boolean just gave me an afternoon of erratic app behaviour ;)

https://github.com/openframeworks/openFrameworks/pull/5107

**Comment by arturoc** [comment]
yeah i can imagine, it must be a bug i introduced when porting ofthread to std::thread, sorry!

**Comment by underdoeg** [comment]
no problem. glad I found it
