### ISSUE TITLE
ofMain.f file not found.

### ISSUE THREAD

**Issue by MiteshiOS** [openframeworks/openFrameworks#5113]
![screen shot 2016-05-30 at 4 45 38 pm](https://cloud.githubusercontent.com/assets/17427703/15648129/1ded6ff0-2686-11e6-9640-c9f1e9166f2e.png)

Please help me to solve this

**Comment by bakercp** [comment]
This is a question for the forum as it likely has to do with an out of date third party project file. This issue tracker is meant for reproducible bugs in the in the openframeworks project core etc.  Check out the friendly forum here:

https://forum.openframeworks.cc.
