### ISSUE TITLE
Relax IEEE Compliance on by default in build settings?

### ISSUE THREAD

**Issue by gwio** [openframeworks/openFrameworks#5115]
Hi, i had some issues with strange variable output when building for release (xcode 7.3, of master). Turning _Relax IEEE Compliance_ off in the build settings solved this.

See also https://forum.openframeworks.cc/t/output-difference-with-debug-release-settings/23566

**Comment by arturoc** [comment]
Thanks. Yes this shouldn't be enabled by default since it'll give wrong results in math operations. In general i think the optimization flags in xcode are too aggressive and should be left as the come by default since otherwise it can be problematic for some people.

**Comment by danoli3** [comment]
Okay just PR'd a config fix for the oF project. Wasn't in the template, just the oF core project.
