### ISSUE TITLE
ofxCvImage.h have list of erros

### ISSUE THREAD

**Issue by MiteshiOS** [openframeworks/openFrameworks#5117]
![screen shot 2016-06-02 at 12 36 19 pm](https://cloud.githubusercontent.com/assets/17427703/15737233/a57e0ebe-28c2-11e6-94c2-b2c8d5f817dd.png)
Please help me to solve this.

**Comment by arturoc** [comment]
This is a problem with a specifc project, please open an issue in their repo

**Comment by MiteshiOS** [comment]
@arturoc Thank you sir and sorry for inconvenience. I think there are some issue related to framework file.

**Comment by arturoc** [comment]
no, this is a problem with the setup of this specific project missing some config for sure. you can also try asking in the forum

**Comment by MiteshiOS** [comment]
Yes sure sir. i am working with this repo [THVideoFaceSwapper](https://github.com/thehackerati/THVideoFaceSwapper) . Help me if you know about this.
