### ISSUE TITLE
./compilePG.sh error missing -lgl

### ISSUE THREAD

**Issue by elbaro** [openframeworks/openFrameworks#5141]
Ubuntu 16.04 comes with libGL.so but OF cannot find it.

```
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
/home/~/of/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/projectGenerator' failed
```

my workaround:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1.0.0 /usr/lib/libGL.so`

This was a fresh Ubuntu install + cuda/nvidia driver. It may be a good idea to locate libGL in install_dependencies.sh.

**Comment by bakercp** [comment]
Closing as this is related to PG. Please submit this as an issue with https://github.com/openframeworks/projectGenerator/issues if the issue persists.
