### ISSUE TITLE
CMake / Hunter / Cross-Compilation

### ISSUE THREAD

**Issue by lucmichalski** [openframeworks/openFrameworks#5143]
Hi guys,

hope you are doing all well !

I was wondering if there is any projects related to openframeworks allowing to compile ofx librairies and app with CMake.

The bigger goal would be to use:
- https://github.com/ruslo/hunter
- https://github.com/ruslo/polly
- https://github.com/hunter-packages

It would allow to make easier the cross-compilation of projects (Linux, Mac, Windows, iOS, Android, Raspberry Pi).

Cheers,
Luc Michalski

**Comment by andyli** [comment]
duplicate of #4193

**Comment by damian0815** [comment]
Surprised no-one has mentioned ofnode yet. https://github.com/ofnode/of

**Comment by bakercp** [comment]
Closing this as a duplicate.
