### ISSUE TITLE
GLFW in OS X is 64bit. Feature or bug?

### ISSUE THREAD

**Issue by c-mendoza** [openframeworks/openFrameworks#5153]
The GLFW library in the OS X version of OF is 64 bit only, not a Universal binary. Is this by design? If so, compiling 32 bit code is not possible.

**Comment by charlesveasey** [comment]
Pretty sure this is intentional. Apple is pushing for 64-bit apps.

**Comment by arturoc** [comment]
this is a bug. is this on current master or the latest release?

**Comment by c-mendoza** [comment]
Current master only. I just checked the 0.9.3 release and it is Universal.

**Comment by ofTheo** [comment]
just pushed a fix to the apothecary repo: 
https://github.com/openframeworks/apothecary/commit/1e3a7766c7af17e5255802c726effc3aa81cad61

and pushed up a new lip to the OF repo which is universal.
