### ISSUE TITLE
Qt Creator 4.0.2 and Ubuntu 16.04

### ISSUE THREAD

**Issue by charlesveasey** [openframeworks/openFrameworks#5154]
project template doesn't work: 

`Range Error: Maximum call stack size exceeded.`

on ofApp.qbs line 19

tested on:
of_v0.9.3_linux64_release
of_v20160701_linux64_release

**Comment by devtronslab** [comment]
Already discussed in #5095

**Comment by martialgallorini** [comment]
Same issue here under OSX El Capitan and Qtcreator 4.0.2
Using of_v20160701 nightly

**Comment by hamoid** [comment]
Is this still valid? We're at QtCreator 4.2.2 now. I use it daily on ArchLinux...

**Comment by arturoc** [comment]
no thanks, this was solved a while ago
