### ISSUE TITLE
error installing libboost-filesystem-dev

### ISSUE THREAD

**Issue by jambonbill** [openframeworks/openFrameworks#5159]
E: Unable to correct problems, you have held broken packages.
error installing libboost-filesystem-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libboost-filesystem-dev : Depends: libboost-filesystem1.54-dev but it is not going to be installed

**Comment by bakercp** [comment]
Did you get this resolved?  If not, what linux distro / version are you using and what version of openFrameworks are you using?

**Comment by chept** [comment]
I am having the same issue on tag `0.9.8` of the repo.

```
Installing libboost-filesystem-dev
E: Unable to correct problems, you have held broken packages.
error installing libboost-filesystem-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libboost-filesystem-dev : Depends: libboost-filesystem1.54-dev but it is not going to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues
```

My system is:
```
Distributor ID:	Ubuntu  
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by bakercp** [comment]
@chept Have you tried suggestions like this: https://askubuntu.com/a/223267

**Comment by chept** [comment]
Yes.
I looks like I don't have held package.
`dpkg --get-selections | grep hold` return nothing.

**Comment by chept** [comment]
Yes.
aptitude made the deal.

It looks like a conflict of version between libboost1.55 and libboost1.54.
Thanks !

**Comment by bakercp** [comment]
(@chept so how did you fix it?)

**Comment by chept** [comment]
Using `aptitude` as proposed in the link you gave me ([https://askubuntu.com/a/223267](https://askubuntu.com/a/223267)) :

```
$ sudo aptitude install libboost-filesystem-dev
The following NEW packages will be installed:
  libboost-filesystem-dev libboost-filesystem1.54-dev{a} libboost-filesystem1.54.0{a} 
  libboost-system1.54-dev{a} libboost1.54-dev{a} 
0 packages upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 5 769 kB of archives. After unpacking 96,7 MB will be used.
The following packages have unmet dependencies:
 libboost-system1.55-dev : Conflicts: libboost-system1.54-dev but 1.54.0-4ubuntu3.1 is to be installed.
 libboost1.55-dev : Conflicts: libboost1.54-dev but 1.54.0-4ubuntu3.1 is to be installed.
 libboost-filesystem1.55-dev : Conflicts: libboost-filesystem1.54-dev but 1.54.0-4ubuntu3.1 is to be installed.
The following actions will resolve these dependencies:

     Remove the following packages:
1)     libboost-filesystem1.55-dev 
2)     libboost-system1.55-dev     
3)     libboost1.55-dev   
```

After that `install_dependencies.sh` has been executed normally.

**Comment by bakercp** [comment]
Thanks for the clarification @chept.  I'm sure other's with the same problem will benefit!

I'm going to close this issue for now.
