### ISSUE TITLE
ofAppEGLWindow can't find keyboard on Raspberry Pi

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#5169]
I consistently fail get keyboard control on the rpi. 

```
[notice ] ofAppEGLWindow: setupKeyboard(): keyboard_fd=-1 devicePath=/dev/input/by-pathplatform-3f980000.usb-usb-0:1.5.5.2:1.0-event-kbd
[ error ] ofAppEGLWindow: setupKeyboard(): did not open keyboard
```

Digging a bit into the issue, it seems it's trying to open a device that doesn't exist...
"/dev/input/by-pathplatform-3f980000.usb-usb-0:1.5.5.2:1.0-event-kbd"

```
$ ls /dev/input/by-pathplatform-3f980000.usb-usb-0:1.5.5.2:1.0-event-kbd
ls: cannot access /dev/input/by-pathplatform-3f980000.usb-usb-0:1.5.5.2:1.0-event-kbd: No such file or directory
```

It seems a trailing "/" is missing in "/dev/input/by-path" when constructing the device path:

`string devicePathBuffers[2] = { "/dev/input/by-path", "/dev/input/" };`

it affects both keyboard and mouse; in here:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppEGLWindow.cpp#L1352

and here:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppEGLWindow.cpp#L1392

Seems pretty obvious; I'll prepare a PR if its cool.

**Comment by bakercp** [comment]
Seems like a reasonable fix ... perhaps a PR?

**Comment by armadillu** [comment]
seems it's been fixed in the mean time.

**Comment by bakercp** [comment]
Thanks for following up!
