### ISSUE TITLE
iOS build fail: missing ofMesh.cpp

### ISSUE THREAD

**Issue by drinkius** [openframeworks/openFrameworks#5170]
Trying to build the app generated from an example "videoGrabberExample" I get an error:

no such file or directory: '/Users/drinkius/Documents/xcode/openFrameworks/libs/openFrameworks/3d/ofMesh.cpp'

Don't see such a file in the directory and can't find it in a repo, how do I overcome this issue?

**Comment by danoli3** [comment]
In the process of updating to current glm and master changes

**Comment by bakercp** [comment]
Unable to reproduce.  Please reopen if it persists.
