### ISSUE TITLE
broken ofToString support for new glm vector types

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5171]
Previously `ofToString` supported serialization of the `ofVec*f` types via <<.  

e.g.
```c++
ofVec2f myVec(2, 2);
ofDrawBitmapString(ofToString(myVec), 14, 14);
```
would work.  For now

```c++
std::cout << glm::vec2(1,1) << std::endl;
```
works but

```c++
std::cout << ofToString(glm::vec2(1,1)) << std::endl;
```
doesn't.

~~It would be easy enough to add template specializations, but as a lot of work has been done recently with the `ofTo<>` functions, I'm not sure if that is the best way.  @arturoc what do you think?~~  _See below_.

**Comment by bakercp** [comment]
Ah, just noticed that this is already included in `ofVectorMath.h`, but there is an error in the implementation during compilation:

![ofvectormath_h](https://cloud.githubusercontent.com/assets/300484/17074708/76651506-5044-11e6-9347-b41471922d4b.png)

**Comment by bakercp** [comment]
So just to clarify, 

```c++
    std::cout << glm::vec2(1,1) << std::endl;
```

works.

```c++
    std::cout << ofToString(glm::vec2(1,1)) << std::endl;
```

fails with the error above.

**Comment by arturoc** [comment]
moving the overloaded operators to the glm namespace or changing the include order should fix this. probably better to move the operators to the glm namespace so it's easier to use

can you send a PR?
