### ISSUE TITLE
projectGenerator doesn't see ofxiOS addon

### ISSUE THREAD

**Issue by drinkius** [openframeworks/openFrameworks#5172]
I'm trying to run ofxFaceTracker but run into problems in main.mm file - it doesn't recognise ofiOSWindowSettings class, which is part of ofxiOS addon and is pre-imported in OF examples.

I can't import ofxiOS with projectGenerator - it doesn't see it, even though its in the addons folder, I didn't make any changes to it after downloading it from the iOS release on the http://openframeworks.cc/ website.

How can I make projectGenerator add the addon or import it in my project manually?

**Comment by bakercp** [comment]
Closing this issue.  Please reopen it at https://github.com/openframeworks/projectGenerator/issues if the issue persists.
