### ISSUE TITLE
Installing Revkit 2.2

### ISSUE THREAD

**Issue by HariMohan84** [openframeworks/openFrameworks#5175]
hari@ubuntu:~$ cd revkit-2.2
hari@ubuntu:~/revkit-2.2$ cd build
hari@ubuntu:~/revkit-2.2/build$ cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
--   regex
--   filesystem
--   graph
--   program_options
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hari/revkit-2.2/build
hari@ubuntu:~/revkit-2.2/build$ make
[  6%] Built target aiger
[ 11%] Built target cudd
[ 17%] Built target puma
[ 19%] Built target objlib_classical
[ 29%] Built target objlib_core
[ 78%] Built target objlib_reversible
[ 78%] Built target revkit_classical
[ 78%] Built target revkit_classical_static
[ 78%] Built target revkit_core
[ 78%] Built target revkit_core_static
[ 78%] Built target revkit_reversible
[ 78%] Built target revkit_reversible_static
[ 78%] Built target adding_lines_optimization
[ 78%] Built target bdd_info
[ 79%] Built target benchmark_table
[ 80%] Built target calculate_required_lines
[ 80%] Built target circuit_info
[ 81%] Built target circuit_to_truth_table
[ 82%] Built target dd_synthesis
[ 83%] Built target embed_pla
[ 83%] Built target exact_synthesis
Linking CXX executable example1
../src/librevkit_reversible.so: undefined reference to `revkit::revkit_version()'
../src/librevkit_reversible.so: undefined reference to `revkit::properties::set(std::string const&, boost::any const&)'
../src/librevkit_reversible.so: undefined reference to `typeinfo for revkit::program_options'
../src/librevkit_reversible.so: undefined reference to `revkit::BDDTable::BDDTable(DdManager*)'
../src/librevkit_reversible.so: undefined reference to `revkit::set_error_message(std::shared_ptr<revkit::properties>, std::string const&)'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::is_set(std::string const&) const'
../src/librevkit_reversible.so: undefined reference to `revkit::pla_parser(std::string const&, revkit::pla_processor&, bool)'
../src/librevkit_reversible.so: undefined reference to `revkit::read_pla_to_characteristic_bdd(revkit::BDDTable&, std::string const&, bool, bool)'
../src/librevkit_reversible.so: undefined reference to `revkit::properties::clear()'
../src/librevkit_reversible.so: undefined reference to `revkit::make_cube(Cudd&, std::vector<BDD, std::allocator<BDD> > const&)'
../src/librevkit_reversible.so: undefined reference to `revkit::properties::begin() const'
../src/librevkit_reversible.so: undefined reference to `revkit::BDDTable::BDDTable()'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::parsed() const'
../src/librevkit_reversible.so: undefined reference to `revkit::BDDTable::~BDDTable()'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::~program_options()'
../src/librevkit_reversible.so: undefined reference to `revkit::properties::end() const'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::program_options(unsigned int)'
../src/librevkit_reversible.so: undefined reference to `revkit::pla_parser(std::istream&, revkit::pla_processor&, bool)'
../src/librevkit_reversible.so: undefined reference to `revkit::inc(boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >&)'
../src/librevkit_reversible.so: undefined reference to `revkit::read_pla_to_bdd(revkit::BDDTable&, std::string const&, revkit::read_pla_to_bdd_settings const&)'
../src/librevkit_reversible.so: undefined reference to `revkit::properties::properties()'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::good() const'
../src/librevkit_reversible.so: undefined reference to `revkit::program_options::program_options(std::string const&, unsigned int)'
collect2: error: ld returned 1 exit status
make[2]: *** [programs/example1] Error 1
make[1]: *** [programs/CMakeFiles/example1.dir/all] Error 2
make: *** [all] Error 2
hari@ubuntu:~/revkit-2.2/build$ 

**In the installation of Revkit 2.2, the above problems have occurred, I have installed mostly all the requirements (as per the best of my knowledge)....Please help me out**  @Siddhant

**Comment by tgfrerer** [comment]
This looks like it has been posted by error - if this was an openFrameworks specific issue, you might want to check out the openFrameworks [forum](https://forum.openframeworks.cc), @HariMohan84.
