### ISSUE TITLE
QtCreator Issue: Won't Show Source Files

### ISSUE THREAD

**Issue by toliaferrode** [openframeworks/openFrameworks#5181]
I don't know why this is happening I've installed and uninstalled Qt Creator quite a few times over this year. Anyway, I'm getting back into oF, compiled oF and pG. Install Qt Creator 3.51 and also tried 4.0.3, openFrameworks 0.9.3 and the nightly builds and I get out of Qt Creator under the issues panel: 

> :-1: error: Unknown or empty profile 'qtc_Desktop_34351b58'.

 I checked out the project qbs.user file and I noticed that there are several occurances of "qtc_Desktop_34351b58" in it. Don't know what's happening but thought I should report it. Anybody know what I can do? I'll be switching to vim in the mean time I guess.

**Comment by hamoid** [comment]
I've received 3 or 4 QtCreator updates this year, and each one breaks openFrameworks. Last one yesterday with 4.1.0. 

It was working fine with 4.0.3 (openFrameworks+apothecary from Git). 4.1.0 wouldn't show source files (they deprecated something in the qbs files). I reverted to 4.0.3, cleaned all, rebuilt all, and now I can compile and run again. I see at least 10 lines marked with red circles and yellow triangles. Hovering does not tell me what's wrong with them. No info in the issues panel. Unfortunately it feels quite buggy.

**Comment by hamoid** [comment]
It would be nice if it was stated somewhere which version of QtCreator is supported when using OF from Git.

**Comment by underdoeg** [comment]
QtCreator 4.1 should be fixed with this PR: https://github.com/openframeworks/openFrameworks/pull/5244

**Comment by arturoc** [comment]
@hamoid do you want to send a PR to ofSite adding a comment of the supported versions?

**Comment by underdoeg** [comment]
I think we now support qtcreator 4 and upwards? Or does 3.6 still work?

**Comment by hamoid** [comment]
@arturoc I would be happy to do that, if I knew what is supported :) 

I would not write "qtcreator 4 and above", but maybe be more specific, like: "tested with 4.0.3 ~ 4.1.0". Just in case a future 4.1.x is not immediately compatible (as happened with 4.1.0).

This is probably not an issue for most users, but with ArchLinux I receive new packages as soon as they are out, and I had to learn how to avoid updating qtcreator.

**Comment by arturoc** [comment]
the current stable version, 0.9.3 should work with 3.6.1
master with 4.1.0

**Comment by toliaferrode** [comment]
Hi. I just compiled master and Qt Creator 4.1.0 is still saying "Unknown or empty profile etc..."

**Comment by arturoc** [comment]
That's strange, it's working fine for me fine now, can you double check you are on the latest commit?

**Comment by toliaferrode** [comment]
I'm running the latest commit, yeah. Master.

**Comment by underdoeg** [comment]
@toliaferrode Strange. Did you also delete the build directory?

I have tried to clarify the QT creator versions in this PR https://github.com/openframeworks/ofSite/compare/master...underdoeg:patch-1

**Comment by toliaferrode** [comment]
Not that I'm aware of. I've tried all different kinds of versions of Qt Creator. None of them work.

**Comment by underdoeg** [comment]
What is the exact error? Does it point to the qbs file or something else? Does it also happen with a newly created project?

**Comment by toliaferrode** [comment]
The error is: "Unknown or empty profile 'qtc_Desktop_34351b58'." With the examples. I'm not sure about a newly generated project. I'll check tomorrow.

**Comment by underdoeg** [comment]
I am not sure but I think this error has to do with your kits configuration. Check in options -> Build & Run -> Kits, if the Desktop configuration looks ok. And maybe also remove the "build-YourProjectName-" directory in the same folder as the project.

**Comment by toliaferrode** [comment]
There's a warning icon next to the Desktop kit. I'm not sure what it's supposed to look like.

**Comment by edap** [comment]
just as info, I have installed qt creator 4.4.1 and the last nightly build (20180411) and I have the error "unknown or empty profile qtc_Desktop...". 4.4.1 it is the same version that I'm using on another machine, with an OF version that is maybe 2 weeks behind the current master.

**Comment by hamoid** [comment]
@edap I'm using QtCreator 4.6.0 with OF master. Recently some issues regarding to QBS on 4.6.0 were fixed (one or two weeks ago).

**Comment by arturoc** [comment]
yeah sorry i told you on the forum 4.5 but it's 4.6
