### ISSUE TITLE
Quicktime Framework Removal MacOS 10.12 Sierra/Xcode 8 - Unable to build

### ISSUE THREAD

**Issue by laserpilot** [openframeworks/openFrameworks#5190]
I haven't tried this with master, but noting it here as well as on the forums. The quicktime framework has been removed as of MacOS 10.12 Beta 3 (probably since Beta 1) and Xcode 8 beta 4. This means that old OF versions will not build in 10.12 without this workaround: 

https://forum.openframeworks.cc/t/macos-10-12-sierra-xcode-8-quicktime-deprecation-workaround/24179/1

I've only tested this with 0.9.3 release, but from looking at the 0.9.4 branch, all of that stuff is still in there.

Im guessing all 0.9.4+ versions will need to just remove Quicktime entirely for ease, or just have compiler flags to not try to compile the missing framework.

**Comment by danoli3** [comment]
Yeah definitely, deadline is September 15th for Xcode 8 Gold, so that's the
timeline

**Comment by surayashivji** [comment]
Is there an update on any workaround or fix for this?

**Comment by ofTheo** [comment]
The branch 0.9.4 has a fix and we'll be doing a release very soon. 
In the meantime there is some advice here - mainly adding the 10.11 sdk and building against 10.11. 

https://forum.openframeworks.cc/t/quicktime-quicktime-h-file-not-found/24494/8

**Comment by danomatika** [comment]
I can confirm manually re-adding the 10.11 SDK allows me to build OF 0.9.3 in Xcode 8.

Kudos for all the work done years ago on the AVFondation grabber/player and preparing an update. It's going to pay off now!

**Comment by ofTheo** [comment]
Hey all - we have an 0.9.4 RC out which should close this issue. 

If you are able to please give it a try and post feedback in this thread.
https://forum.openframeworks.cc/t/0-9-4-release-candidate-1/24627

Thanks!!
Theo
