### ISSUE TITLE
ofFile::create - possible bug when open hasn't been called? 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5196]
This is how it currently looks at:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofFileUtils.cpp#L474

```
//------------------------------------------------------------------------------------------------------------
bool ofFile::create(const std::filesystem::path & path){
	bool success = false;

	if(!myFile.string().empty()){
		auto oldmode = this->mode;
		auto oldpath = this->path();
		success = open(path,ofFile::WriteOnly,binary);
		close();
		open(oldpath,oldmode,binary);
	}

	return success;
}
```

With the check for myFile.string() being empty it looks like it would only succeed if the ofFile object had been used to open a file first.  

i.e. this would fail:
```
ofFile myFile; 
myFile.create("test.txt"); 
```

But this would work:

```
ofFile myFile; 
myFile.open("somefile.txt"); 
myFile.create("test.txt"); 
```

I just wanted to double check I am understanding it correctly before trying to fix it :) 
ping @openframeworks/core

**Comment by arturoc** [comment]
i think this probably comes from the version without arguments that would create a file from the already opened path. i think it's correct to just remove that condition

**Comment by ofTheo** [comment]
Here's the PR: 
a bit easier to see with the whitespace suppressed: 
https://github.com/openframeworks/openFrameworks/pull/5198/files?w=1
