### ISSUE TITLE
update the project generator so that it can automatically add dll to bin

### ISSUE THREAD

**Issue by IanByun** [openframeworks/openFrameworks#5204]
as far as i know, current skeleton for an addon is like this:
addon_name
    |-example
    |-src
    |-libs
        |-library_name
            |-includes
            |-lib
                |-vs
                    |-Win32
                        |-Debug
                        |-Release
                    |-x64
                        |-Debug
                        |-Release
and generating a project with the project generator, all the src, includes and libs are automatically added to the project.

What I am suggesting is to add another skeleton folder, namely dlls, and the project generator copies all the dlls to your bin folder, just like dlls in export folder.
addon_name
    |-dlls
    |-example
    |-src
    |-libs
...

By doing so, app developers can be saved from painful process of installing some library and copying all the dlls manually for all the projects,
and addon developers can manage their libs and dlls to be of the same version

just think of ofxOpenCv some openframeworks version ago - it's opencv libs were built based on unix (if my guess is right) and could not be properly linked in windows envirionment, conflicting with pre-installed version of opencv

suggesting automation process can save such conflictions and time

**Comment by bakercp** [comment]
Please re-open this issue on the Project Generator issues page.

https://github.com/openframeworks/projectGenerator/issues
