### ISSUE TITLE
Adding something in namespace std could lead to undefined behavior

### ISSUE THREAD

**Issue by saki7** [openframeworks/openFrameworks#5240]
Due to the clause _17.6.4.2.1_; it leads to undefined behavior in most cases (except for certain cases e.g. template specialization)
See also: http://en.cppreference.com/w/cpp/language/extending_std

So far I've found the following line:

https://github.com/openframeworks/openFrameworks/blob/3804b4ae3288d76b597d391d0256dc557fa59e7d/libs/openFrameworks/utils/ofFileUtils.h#L10

This shall be considered ill-formed.

**Comment by saki7** [comment]
pinging @arturoc since he introduced the feature

**Comment by arturoc** [comment]
std::filesystem will be valid in c++17, once compilers begin moving that module from experimental into std proper will remove it from there and will also remove boost. this can also be done gradually detecting the compiler version and platform.

so although it's not very orthodox it should be ok since the current implementation in std is almost the same as that in boost

**Comment by saki7** [comment]
So then `will-be-fixed-in-the-future` label is something you are suggesting.

But I have further concerns for people currently using `-std=c++1z` which could cause a conflict in the namespace std (which assumes the ACTUAL `std::filesystem` will be used rather than `boost::filesystem`)

**Comment by arturoc** [comment]
that hasn't happened yet, once it happens we'll fix it but if you have any ideas on how to detect the compilers that already have filesystem a PR is always welcome

**Comment by saki7** [comment]
Thanks for the feedback. Okay, my plans for using C++17 is when it comes to the stable release of GCC (when `-std=c++17` is available) so I'll post an update then.

**Comment by bakercp** [comment]
I'm going to close this for now, @saki7 please reopen or create a new issue when `-std=c++17` is available.
