### ISSUE TITLE
Discussion: remove using namespace std; from ofConstants.h?

### ISSUE THREAD

**Issue by saki7** [openframeworks/openFrameworks#5241]
Rationally speaking, it's not a good way to achieve stuff by defining `using namespace std;` in **header** files. It may be necessary to remove it from the global headers (so far I've found in `ofConstants.h` only)

I know the removal might break many addons, so we could define a macro for this:
```cpp
#ifndef OF_NO_USING_NAMESPACE_STD
using namespace std;
#endif
```

... and make proper fixes for core files to use the prefix `std::` everywhere.

Any opinions for this?

**Comment by tgfrerer** [comment]
Check out the discussion under #2581

**Comment by saki7** [comment]
Sorry for the duplicate! I'll be more careful next time.

**Comment by tgfrerer** [comment]
No worries - i think it's good to see this popping up now and again, just to show that there is some traction behind the issue =)
