### ISSUE TITLE
Not able to compile openframework on Raspberry Pi 

### ISSUE THREAD

**Issue by umang-sh** [openframeworks/openFrameworks#5243]
Getting this issue whenever I try to run this command 

make Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project 

I get this error

HOST_OS=Linux
makefileCommon/config.shared.mk:226: *** Platform Variant "rpi2" is not valid. Valid variants include [default default].  Stop.
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'

**Comment by arturoc** [comment]
what version of OF have you downloaded?

**Comment by umang-sh** [comment]
Arturo many thanks , I  have solved the issue .

Issue was due to the process mentioned here
http://forum.openframeworks.cc/t/raspberry-pi-2-setup-guide/18690

solved now 👍
