### ISSUE TITLE
Footfall plus openframework Compilation failed on Raspberry Pi

### ISSUE THREAD

**Issue by umang-sh** [openframeworks/openFrameworks#5245]
I complied openframeworks as per the instructions here 
http://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/
Then build and compiled with footfall using this 
(https://github.com/WatershedArts/Footfall/blob/master/docs/rpi.md)
Attaching the last few lines of terminal output from raspberry Pi 3 : 

/home/pi/openFrameworks/addons/ofxCv/libs/ofxCv/src/Calibration.cpp:218:15: warning: unused variable 'principalPointYLt' [-Wunused-variable]
         float principalPointYLt = xml.getFloatValue("stCamera:PerspectiveModel/stCamera:ImageYCenter");
               ^
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:336: recipe for target '/home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxCv/libs/ofxCv/src/Calibration.o' failed
make[1]: **\* [/home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxCv/libs/ofxCv/src/Calibration.o] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/ThreadedFootfall'
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: **\* [Release] Error 2

**Comment by bakercp** [comment]
This is a compilation issue with ofxCv and Footfall, please open a discussion there.  Closing this, unless we can determine that it's a openFrameworks core issue.
