### ISSUE TITLE
Image glitches in iMac 5K / noFill and bold Linewidth

### ISSUE THREAD

**Issue by leico** [openframeworks/openFrameworks#5247]
in draw()
----

```
ofEnableBlendMode(OF_BLENDMODE_ALPHA);
ofSetLineWidth(16);
ofNoFill();

```

ofSetLineWidth(1);
----
![2016-09-06 1 56 59 3](https://cloud.githubusercontent.com/assets/1610962/18254081/3d2c6276-73d5-11e6-89bd-f42fcaae0882.png)

ofSetLineWidth(2);
----
![2016-09-06 1 59 09 3](https://cloud.githubusercontent.com/assets/1610962/18254110/8c5b1158-73d5-11e6-9829-fb06fe7ce091.png)

ofSetLineWidth(4);
----
![2016-09-06 2 00 02 3](https://cloud.githubusercontent.com/assets/1610962/18254134/b88b155c-73d5-11e6-9417-d64a8d92772e.png)

ofSetLineWidth(8); **//few strange**
----
![2016-09-06 2 02 19 3](https://cloud.githubusercontent.com/assets/1610962/18254167/fcf3a970-73d5-11e6-9bcd-7f9273e69387.png)

ofSetLineWidth(16); **//Strange**
----
![2016-09-06 2 04 20 3](https://cloud.githubusercontent.com/assets/1610962/18254200/4d69b656-73d6-11e6-9782-ea852e334474.png)

**Comment by arturoc** [comment]
This is just how openGL works, drawing lines with width only draws line segments but it won't do proper caps or joints. indeed glLineWidth (which ofSetLineWidth calls internally) is deprecated in openGL 3+.

There's several addons and examples on how to do thick lines in OF in the forum, for example: https://forum.openframeworks.cc/t/how-to-draw-joined-up-thick-line-segments/23176
