### ISSUE TITLE
Xcode 8/macOS 10.12 removed QtKit support

### ISSUE THREAD

**Issue by gottfired** [openframeworks/openFrameworks#5264]
Just updated to Xcode to the latest version. QtKit is not supported anymore with BaseSDK 10.12 which leads to compile errors.

**Comment by ofZach** [comment]
relevant: 

https://forum.openframeworks.cc/t/quicktime-quicktime-h-file-not-found/24494/3
https://forum.openframeworks.cc/t/macos-10-12-sierra-xcode-8-quicktime-deprecation-workaround/24179/1

**Comment by arturoc** [comment]
yeah there's a couple of fixes for latest versions of qtcreator and i
think we still haven't done a release for some library that wasn't
compiled for 32bit in osx so if someone can send a PR for this against
the 0.9.4 branch we can do a release right away

**Comment by joaodafonseca** [comment]
Would be really helpful to have OF building in Xcode 8 as soon as possible. I'm in a middle of a IOS project and need to build it to IOS 10. Any ideas when is this going to happen? Thanks

**Comment by ofZach** [comment]
@joaodafonseca is there an IOS issue that's different then the quicktime issue?

this is the workaround for osx which should fix things: 

https://forum.openframeworks.cc/t/macos-10-12-sierra-xcode-8-quicktime-deprecation-workaround/24179

**Comment by joaodafonseca** [comment]
Hi @ofZach thanks for the reply. I don't get any issue with quicktime in IOS, this is what I got:
![screen shot 2016-09-15 at 15 09 20](https://cloud.githubusercontent.com/assets/1932216/18550946/a4d93a56-7b56-11e6-9ac9-7616b264aab1.png)

Any thoughts?

**Comment by joaodafonseca** [comment]
Ok so I found a way to build it for IOS 

Targets -> Build Settings -> Build Active Architecture Only -> set to 'YES'

And now it Builds, no complains about the quicktime issue.

Sorry if this was off topic

**Comment by ofTheo** [comment]
Made a PR for OS X here: #5267 If anyone with 10.12 can test that would be helpful!

**Comment by ofTheo** [comment]
This is actually a bit more complicated than just adding the preprocessor guards. 
Currently we are using AVFoundation for video file playback, but we are using QTKit for video camera capture.  So with the above PR ( #5267 ) there is still an error that OF_VIDEO_PLAYER_QTKIT is not defined. 

It looks like we will need to port the ofxiOSVideoGrabber over for OS X and bring AVFoundationVideoGrabber into the openFrameworks/video/ folder 

This could be relatively straight forward, but as its a shift of API for OS X it might have some unforeseen side effects. 

Will give it a go in the following branch:  https://github.com/openframeworks/openFrameworks/tree/0.9.4-xcode-hotfix

**Comment by ofTheo** [comment]
Okay added an AVF grabber for OS X
#5267 should be ready for testing with Xcode 8 / 10.12

**Comment by ofTheo** [comment]
closes by #5267
