### ISSUE TITLE
./compilePG throws undefined reference to poco

### ISSUE THREAD

**Issue by miguelitoVargas** [openframeworks/openFrameworks#5265]
hello, for the past week i have been compiling a fresh clone of the master branch in a fresh manjaro linux install. 
all the dependencies are installed, poco updates ok, although i changed REL_LIBS_DIR= ../ in the apothecary script  to REL_LIBS_DIR = ..  so it would not copy to ..//poco/\* 
./compileOF.sh compiles with no problems, and when i compile PG throws a lot of undefined references to poco.
below the output until the first undefined, any help with this thanks a lot. 

I have tested the downloadable official version from the site and compiles just fine.
Working with gcc 6

 `sudo ./compilePG.sh 
make: Entering directory '/home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Compiling OF library for Release
make[1]: Entering directory '/home/acorde/ides_frameworks/repo/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Done!
make[1]: Leaving directory '/home/acorde/ides_frameworks/repo/libs/openFrameworksCompiled/project'

Compiling projectGenerator for Release
make[1]: Entering directory '/home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Linking bin/projectGenerator for linux64
g++ -o bin/projectGenerator  obj/linux64/Release/src/ofApp.o obj/linux64/Release/src/main.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/utils/LibraryBinary.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/utils/Utils.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/baseProject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/CBLinuxProject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/CBWinProject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/xcodeProject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/qtcreatorproject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/src/projects/visualStudioProject.o /home/acorde/ides_frameworks/repo/apps/projectGenerator/commandLine/obj/linux64/Release/addons/ofxProjectGenerator/libs/pugixml/src/pugixml.o /home/acorde/ides_frameworks/repo/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -L/home/acorde/ides_frameworks/repo/libs/fmodex/lib/linux64/ -lfmodex /home/acorde/ides_frameworks/repo/libs/kiss/lib/linux64/libkiss.a /home/acorde/ides_frameworks/repo/libs/tess2/lib/linux64/libtess2.a  /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoNetSSL.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoNet.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoCrypto.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoUtil.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoJSON.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoXML.a /home/acorde/ides_frameworks/repo/libs/poco/lib/linux64/libPocoFoundation.a  -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lglfw -lrtaudio -ljack -lpulse-simple -lpulse -lasound -lGLEW -lGLU -lGL -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123 -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -ldl -lpthread -lfreeimage -lrtaudio -lboost_filesystem -lboost_system -lXinerama
/home/acorde/ides_frameworks/repo/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofUtils.o): In function `ofLaunchBrowser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
ofUtils.cpp:(.text+0x93db): undefined reference to`Poco::URI::URI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

`

**Comment by miguelitoVargas** [comment]
the path where apothecary script copies libs after updated is wrong.... solved it 
changing REL_LIBS_DIR=../ to:
REL_LIBS_DIR=../../../libs

in the apothecary script

**Comment by arturoc** [comment]
this is fixed now in master, thanks!
