### ISSUE TITLE
xcode 8 and OFiOS

### ISSUE THREAD

**Issue by joaodafonseca** [openframeworks/openFrameworks#5274]
Hey guys,

Having trouble in running OF in a iOS in the device with Xcode 8.

Getting the following issue:
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

Any ideas?

**Comment by ofTheo** [comment]
@joaodafonseca did you select an iOS Developer Profile in the build settings? 
You need to have a valid iOS Developer account to build OF for iOS. 

Please re-open this issue if that is not the cause of the error.

**Comment by ofTheo** [comment]
Looks like it might be something new in Xcode 8. 
see: http://stackoverflow.com/questions/37806538/code-signing-is-required-for-product-type-application-in-sdk-ios-10-0-stic

Maybe we need to set 'automatically manage signing' to true in the ofxiOS template?

Ping @danoli3 @julapy

**Comment by danoli3** [comment]
Should definitey be automatic signing now as of Xcode 8

**Comment by joaodafonseca** [comment]
Hey guys,

I found a workaround. Under targets -> build settings make sure that in signing options everything is set to iOS developer:

<img width="692" alt="screen shot 2016-09-22 at 22 13 31" src="https://cloud.githubusercontent.com/assets/1932216/18764506/0b8ba3cc-8112-11e6-9b76-9f6035eac22a.png">

Then make a clean, close Xcode, restart the computer

try to build one, fail...
try to build twice, fail...
try to build for the 3rd time and it worked(don't ask me)
now it's working, do you think it is going to be a problem to submit to app store?

**Comment by ofTheo** [comment]
yeah I was able to build fine Xcode 8.0 with iOS 10 when I was signed into a developer account. So going to keep this closed.
