### ISSUE TITLE
CompileOf.sh RtAudio.h not found Debian

### ISSUE THREAD

**Issue by gad-o** [openframeworks/openFrameworks#5276]
Hi,
I added this and problem solved
PLATFORM_PKG_CONFIG_LIBRARIES += rtaudio

**Comment by arturoc** [comment]
this was fixed for 0.9.6, thanks!

**Comment by yoosamui** [comment]
install the of_v0.9.7_linux64_release on linux debian.
install the install_dependencies.sh script successfully.
but i can't compile OF:
I'm trying to compile but i get this make error:
/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/sound/ofRtAudioSoundStream.cpp:8:21: fatal error: RtAudio.h: No such file or directory
#include "RtAudio.h"
^
compilation terminated.
does this: PLATFORM_PKG_CONFIG_LIBRARIES += rtaudio
help ? where should i put this ?

I don't know what to do more...
Any Ideas?
Thanks in Advance!!!

**Comment by arturoc** [comment]
what version of debian are you using?
can you check if `sudo apt-get install librtaudio-dev` works? and what's the output?
can you post the output of `ls /usr/include/*RtAudio* *rtaudio*`

**Comment by yoosamui** [comment]
Hello arturoc,
i'm using  Debian “stretch” Alpha testing.
yes, sudo apt-get install librtaudio-dev works! i install it and i can  compile for the first time OF without errors.
However i have still issues. here the output for ls /usr/include/*RtAudio* *rtaudio* :
ls /usr/include/*RtAudio* *rtaudio* 
yoo@os:~$ ls /usr/include/*RtAudio* *rtaudio*
ls: cannot access '/usr/include/*RtAudio*': No such file or directory
ls: cannot access '*rtaudio*': No such file or directory

also i can't  compile the samples. I'm trying to compile the the emptysample. here is the make output:
---------------------------------------------------------------------------------------------------------------------------
yoo@os:~/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample$ make -j6
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
Compiling OF library for Release
make[1]: Entering directory '/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
Done!
make[1]: Leaving directory '/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project'


Compiling emptyExample for Release
make[1]: Entering directory '/home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
cat: obj/linux64/Release/.compiler_flags: No such file or directory
Compiling /home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src/ofApp.cpp
g++ -c -O3 -DNDEBUG -march=native -mtune=native -Wall -std=c++14 -DGCC_HAS_REGEX -DOF_USING_GTK -DOF_USING_GTK  -pthread -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/AL -I/usr/include/rtaudio -I/usr/include/alsa -I/usr/include/libdrm -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/fmodex/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/glfw/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/glfw/include/GLFW -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/kiss/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/utf8cpp/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/utf8cpp/include/utf8 -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/utils -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/communication -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/app -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/events -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/types -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/gl -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/3d -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/video -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/graphics -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/math -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/sound -I/home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src -MMD -MP -MF obj/linux64/Release/src/ofApp.d -MT obj/linux64/Release/src/ofApp.o -o obj/linux64/Release/src/ofApp.o -c /home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src/ofApp.cpp
Compiling /home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src/main.cpp
g++ -c -O3 -DNDEBUG -march=native -mtune=native -Wall -std=c++14 -DGCC_HAS_REGEX -DOF_USING_GTK -DOF_USING_GTK  -pthread -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/AL -I/usr/include/rtaudio -I/usr/include/alsa -I/usr/include/libdrm -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/fmodex/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/glfw/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/glfw/include/GLFW -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/kiss/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/utf8cpp/include -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/utf8cpp/include/utf8 -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/utils -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/communication -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/app -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/events -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/types -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/gl -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/3d -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/video -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/graphics -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/math -I/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworks/sound -I/home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src -MMD -MP -MF obj/linux64/Release/src/main.d -MT obj/linux64/Release/src/main.o -o obj/linux64/Release/src/main.o -c /home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample/src/main.cpp
Linking bin/emptyExample for linux64
g++ -o bin/emptyExample  obj/linux64/Release/src/ofApp.o obj/linux64/Release/src/main.o  /home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -L/home/yoo/Develop/of_v0.9.7_linux64_release/libs/fmodex/lib/linux64/ -lfmodex /home/yoo/Develop/of_v0.9.7_linux64_release/libs/glfw/lib/linux64/libglfw3.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/kiss/lib/linux64/libkiss.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/lib/linux64/libtess2.a  /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoNetSSL.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoNet.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoCrypto.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoUtil.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoJSON.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoXML.a /home/yoo/Develop/of_v0.9.7_linux64_release/libs/poco/lib/linux64/libPocoFoundation.a  -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lrtaudio -lasound -lpulse-simple -lpulse -lGLEW -lGLU -lGL -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -ldl -lpthread -lfreeimage -lboost_filesystem -lboost_system
/usr/bin/ld: /home/yoo/Develop/of_v0.9.7_linux64_release/libs/kiss/lib/linux64/libkiss.a(kiss_fftr.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/lib/linux64/libtess2.a(tess.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/lib/linux64/libtess2.a(mesh.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/lib/linux64/libtess2.a(sweep.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/yoo/Develop/of_v0.9.7_linux64_release/libs/tess2/lib/linux64/libtess2.a(dict.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/emptyExample' failed
make[1]: *** [bin/emptyExample] Error 1
make[1]: Leaving directory '/home/yoo/Develop/of_v0.9.7_linux64_release/examples/empty/emptyExample'
/home/yoo/Develop/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2
---------------------------------------------------------------------------------------------------------------------------
Thanks a lot!

**Comment by yoosamui** [comment]
Hello arturoc,

i check again for rtaudio. It is there... 
ls /usr/include/rtaudio
RtAudio.h

**Comment by arturoc** [comment]
the install dependencies script should have installed rtuadio the first time, not sure why it wasn't installed.

about the other problem i think this is the same that happens in the latest ubuntu where gcc 6 ic conmpiled with some flags incompatible with the gcc that we used to compile the libraries originally.

can you try to run the ubuntu install dependencies instead and see if that fixes it?

**Comment by yoosamui** [comment]
Hello arturoc,
yes, the ubuntu install dependencies SOLVE the problem.
I can now compile the samples without errors.

Thank you so much!

**Comment by gad-o** [comment]
Hi, I also using Debian “stretch” Alpha testing, if it will help

**Comment by arturoc** [comment]
just published a new release 0.9.8 that should fix this

**Comment by abocanegra** [comment]
I ran into this issue in 0.9.8 on ubuntu 17.10 ( also with my archival projects in 0.9.3 ). Solved it with 
`sudo ln -s /usr/include/rtaudio/RtAudio.h /usr/include/RtAudio.h`
