### ISSUE TITLE
OF 0.9.3 is missing Icon / Splash screen files - breaks build.

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5277]
Checking issue #5274 I ran into another issue with the 0.9.3 iOS release. 
It looks like the project generator is not copying the files from inside 
`OF_ROOT/scripts/templates/ios/bin/data/` to the examples data/ folder

So the following files are missing from every iOS example which causes every build to fail. 

```
 Default@2x~ipad.png
 Default@2x~iphone.png
 Default~ipad.png
 Default~iphone.png
 Icon-72.png
 Icon-72@2x.png
```

This can be seen in the current iOS release at:
http://openframeworks.cc/versions/v0.9.3/of_v0.9.3_ios_release.zip

I am guessing this is a PG issue?
As we're about to do a 0.9.4 hotfix release it would be good to get this fixed for that. 

Ping @ofZach @danoli3 @julapy

**Comment by ofTheo** [comment]
ps: any fix for this should be PR'd against the 0.9.4 branch 
Thanks!!

**Comment by ofTheo** [comment]
I should add that the files are being correctly added to the example projects, so maybe its just an issue with ofFile::copyFromTo changing slightly since the switch to boost?  

@ofZach - if you could point me to where the files are added/copied from the template -> to the example, I could see if I could fix it. 

Thanks!
Theo

**Comment by ofZach** [comment]
sorry I'm not 100% sure what you are looking for -- there's a few places that seem useful to investigate

(not 100% sure if this gets called or if it's specific to other templates) : 

https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/baseProject.cpp#L136

this is where stuff gets copied on the osx side: 

https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L330-L347

**Comment by ofZach** [comment]
ps - I'd start poking at the baseProject level and track things there -- most of the project specific (xcodeProject) stuff is about adding libs / include paths and other things to the template and renaming things from emptyExample....

**Comment by ofTheo** [comment]
Thanks! That's really helpful!

**Comment by ofTheo** [comment]
Okay this is fixed now with the latest master in Project Generator ( see commit https://github.com/openframeworks/projectGenerator/commit/3340b00687c65717a1b4490026b0fcca0002d90e ) 

@ofZach @arturoc what is the process of updating the compiled PG app for the iOS release? 
This is the last thing we need to do for a 0.9.4 release. 

Thanks!!
Theo

**Comment by arturoc** [comment]
it's automatically done by the test servers, whenever there's a commit in projectGenerator, it gets compiled and uploaded to the ci server which then packages it with the electron app
