### ISSUE TITLE
mesh polygon tessellation failed

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#5286]
I'm testing out the 0.9.4 rc1 on macOS 10.11.5 (i will test on linux as soon as possible). The example cameraLensOffsetExample runs but I've this error

```bash
** BUILD SUCCEEDED **

-----------------------------------------------------------------
running ../../examples/3d/cameraLensOffsetExample
-----------------------------------------------------------------
[ error ] ofTessellator: performTessellation(): mesh polygon tessellation failed, winding mode 0
[ error ] ofTessellator: performTessellation(): mesh polygon tessellation failed, winding mode 0
[ error ] ofTessellator: performTessellation(): mesh polygon tessellation failed, winding mode 0
```

And something is missing in the top left part of the screen
![screen shot 2016-09-28 at 13 44 26](https://cloud.githubusercontent.com/assets/161152/18912344/3390619a-8582-11e6-8fa3-80dc7a8a53c5.png)

**Comment by arturoc** [comment]
do you have a camera connected? the missing part in the top left part is
the camera output and the tessellation errors probably come from trying
to tesselate an empty polyline since there's no data

**Comment by edap** [comment]
yes, that was the problem. I've updated Skype and my camera was disabled. Enabling the camera fixes the problem. I'm closing the issue
