### ISSUE TITLE
Ubuntu install_dependencies script

### ISSUE THREAD

**Issue by Maigre** [openframeworks/openFrameworks#5295]
Hi,
just to mention: i am installing OF on a fresh ubuntu (gnome) 16.04.1 machine,
and there is a little quirk that can easily be fixed: when running install_dependencies.sh
everything succeed, but the script then offer to recompile poco.
Here it fails because 'curl' is missing. Adding curl to the dependencies install should fix the problem.
Thanks !
Best,
Thomas

**Comment by arturoc** [comment]
this was fixed in 0.9.6. thanks!
