### ISSUE TITLE
ofPixels::setChannel should work to combine YUV planes?

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5296]
Currently `ofPixels::setChannel` doesn't seem to be aware of pixel layout for YUV (e.g. I420) pixel types. 

```c++
ofPixels yPixels;
yPixels.setFromAlignedPixels(pData[0], iWidth, iHeight, OF_PIXELS_Y, iStride[0]);

ofPixels uPixels;
uPixels.setFromAlignedPixels(pData[1], iWidth / 2, iHeight / 2, OF_PIXELS_U, iStride[1]);

ofPixels vPixels;
vPixels.setFromAlignedPixels(pData[2], iWidth / 2, iHeight / 2, OF_PIXELS_V, iStride[1]);

ofPixels pixels;
pixels.allocate(iWidth, iHeight, OF_PIXELS_I420);
pixels.setChannel(0, yPixels);
pixels.setChannel(1, uPixels);
pixels.setChannel(2, vPixels);
```

I can confirm that each of the `yPixels`, `uPixels` and `vPixels` all render correctly when uploaded to a single plane `ofTexture`, yet calling `setChannel() like this is leading to out of bounds exceptions.

Perhaps this is asking too much of `setChannel()`.  If it's not trivial to implement though, perhaps we should log a warning (like we do with other I420-related features).

Thoughts?

**Comment by arturoc** [comment]
yeah, yuv doesn't work with setChannel, anything that has planes won't work with channels right now that function or perhaps getPixelIter should show an error and return the end of the pixels so the iterator does nothing.

what you can do with I420 and every format which has separate plane for each component is:

```
pixels.getPlane(0) = yPixels;
pixels.getPlane(1) = uPixels;
pixels.getPlane(2) = vPixels;
```

which is also much faster than using channels since it's a memcpy internally

**Comment by bakercp** [comment]
Thanks @arturoc -- that makes sense.  Perhaps we just need a little more documentation around planes vs. channels in general.  Additionally, like a few of the other functions perhaps we should just log a warning for things that can't be done or aren't implemented.  Thanks.

**Comment by bakercp** [comment]
Ah, one other idea to better differentiate between planes / channels ... perhaps we could have function like:

`pixels.setPlane(0, yPixels)`?

Tricky part there would be keeping plane maps to make sure that everything was lined up ... (e.g. plane 0 -> yPixels).  I suppose that is also relevant to your example, e.g. if we switched the plane indices ...

```cpp
pixels.getPlane(1) = yPixels;
pixels.getPlane(2) = uPixels;
pixels.getPlane(0) = vPixels;
```

we're not enforcing correct behavior and it wold probably crash.
