### ISSUE TITLE
UTF-8 text encoding source code is broken after update with projectgenerator

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/openFrameworks#5302]
sometimes I comment out with korean, and automatically xCode update cpp/h file with UTF-8 encoding. 

but update projectfile with "projectGenerator", UTF-8 encoding being corrupted. 
I think it's because projectGenerator dealing all files in Western(MAC OS Roman).
I didn't check with Win(VS2015) and Linux.

**Comment by ofZach** [comment]
can you open an issue here: 
https://github.com/openframeworks/projectGenerator

**Comment by ofZach** [comment]
closing this since its PG related.

**Comment by ofZach** [comment]
(also as a note it might be this line of the PG specifically https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L57 to take a look at)

**Comment by icq4ever** [comment]
thank you !
