### ISSUE TITLE
Libs download issues on VS

### ISSUE THREAD

**Issue by prisonerjohn** [openframeworks/openFrameworks#5311]
I think there's an issue with the new libs download script (referencing #5299)

In Visual Studio, I just tried using the .ps1 script to download the libs and I think it messed up with assimp and opencv.

The following is my ofxOpenCv folder. There's a bunch of assimp stuff in there, and there are no opencv header files.
![capture](https://cloud.githubusercontent.com/assets/119702/19404598/57aa0ece-923d-11e6-84e5-fc8b72edca4f.PNG)

The following is my libs folder. I see ippicv in here but no assimp or opencv. Is this where these are all supposed to go?
![capture-2](https://cloud.githubusercontent.com/assets/119702/19404603/686067b8-923d-11e6-9f5c-528e1364254d.PNG)

If I'm doing this wrong, what's the procedure for getting these files in the right place?

**Comment by prisonerjohn** [comment]
Digging into the scripts I'm seeing some issues:

https://github.com/openframeworks/openFrameworks/blob/master/scripts/vs/download_libs.ps1#L54-L55

- assimp getting copied inside ofxOpenCv
- no mention of ippicv

https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/download_libs.sh#L174-L177

- assimp getting copied inside ofxOpenCv

And I don't see any includes anywhere in there (or even in the zips at http://ci.openframeworks.cc/libs/).

I can take a stab at fixing the VS scripts if you tell me where stuff is supposed to go.

**Comment by arturoc** [comment]
this should be fixed now if you can check again?

**Comment by prisonerjohn** [comment]
The files for different architectures are going in different places. I'm seeing similar patterns for both ofxOpenCv and ofxAssimpModelLoader.

Win32 does `openframeworks\addons\ofxOpenCv\libs\lib\vs\$(Platform)\$(Configuration)`
<img width="755" alt="capture-win32" src="https://cloud.githubusercontent.com/assets/119702/19530601/8860ae38-9602-11e6-97f8-c3be4ebc12f1.PNG">

x64 does `openframeworks\addons\ofxOpenCv\libs\opencv\lib\vs\$(Configuration)`
<img width="755" alt="capture-x64" src="https://cloud.githubusercontent.com/assets/119702/19530609/90b53716-9602-11e6-8927-c909bd754527.PNG">

I believe it should be `openframeworks\addons\ofxOpenCv\libs\opencv\lib\vs\$(Platform)\$(Configuration)` for both cases.

**Comment by arturoc** [comment]
yeah that's not correct i'll take a look tomorrow

**Comment by arturoc** [comment]
i think this should be fixed already, going to close it. thanks!
