### ISSUE TITLE
ofxKinect is broken in visual studio

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#5314]
seems like some libusb functions called from freenect like libuse_error_name called from here and other places:

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxKinect/libs/libfreenect/src/usb_libusb10.c#L280

don't exist in the libusb windows emulation header:

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxKinect/libs/libfreenect/platform/windows/libusb10emu/libusb-1.0/libusb.h

**Comment by ofTheo** [comment]
closed by #5711
