### ISSUE TITLE
DoesDirectoryExist can crash the app

### ISSUE THREAD

**Issue by Taprik** [openframeworks/openFrameworks#5315]
I'm experiencing crash when I call the doesDirectoryExist function. The path searched does not exist and the app crash.
The setup : windows7, OF 0.9.3.
It's not crashing the app with windows 10.
The solution is to use this version of doesDirectoryExist
`bool ofDirectory::doesDirectoryExist(const std::string& _dirPath, bool bRelativeToData){
    std::string dirPath = _dirPath;
    try {
        if (bRelativeToData) {
            dirPath = ofToDataPath(dirPath);
        }
        return std::filesystem::exists(dirPath) && std::filesystem::is_directory(dirPath);
    }
    catch (std::exception & except) {
        ofLogError("ofDirectory") << "doesDirectoryExist(): couldn't find directory \"" << dirPath << "\": " << except.what()<<endl;
        return false;
    }
}`

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/issues/5315
