### ISSUE TITLE
Non-public API usage in 0.9.4 __tlv_atexit, __tlv_bootstrap

### ISSUE THREAD

**Issue by kame31** [openframeworks/openFrameworks#5317]
Uploading a 0.9.4 iOS app to the AppStore results in this message:

Non-public API usage:
The app references non-public symbols in: __tlv_atexit, __tlv_bootstrap

**Comment by kame31** [comment]
Still happens with latest 0.9.6 version. It is not possible to upload an iOS app to the Store / Testflight.

**Comment by arturoc** [comment]
i've done some changes that should fixed it and re-uploaded the packages can you give it a try with: http://openframeworks.cc/versions/v0.9.6/of_v0.9.6_ios_release.zip

**Comment by kame31** [comment]
I can confirm that it works now. Thanks!
