### ISSUE TITLE
ofPixels::getColor(int index) is broken. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5321]
It looks like the index is not referring to the pixel index but incorrectly to the byte index. 
So with a three or four channel image this doesn't work correctly. 

```
            for(int d = 0; d < pix.size(); d++){
                ofColor color = pix.getColor(d);
            }
```

Where any of the below does work correctly. 
I am pretty sure this is a bug, as we shouldn't be returning a color based on a byte index as the color spans multiple bytes. 

```
            int numChannels = pix.getNumChannels();
            int i = 0;
            for(int d = 0; d < pix.size(); d++){
                ofColor color = pix.getColor(i);
                i+= numChannels;
            }

```

```
            for(int d = 0; d < pix.size(); d++){

                int x = d % pix.getWidth();
                int y = d / pix.getWidth();

                ofColor color = pix.getColor(x,y);
```

```
            for(auto line: pix.getLines()){
                for(auto pixel: line.getPixels()){        
                    ofColor color = pixel.getColor();
                }
            }
```

**Comment by arturoc** [comment]
just fixed this so it goes in 0.9.5

**Comment by ofTheo** [comment]
oh awesome! :)

**Comment by bakercp** [comment]
So just to clarify ...

```cpp
  for(std::size_t d = 0; d < pix.size(); d++){
                ofColor color = pix.getColor(d);
  }
```

still won't work as it used to right?  As far as I can tell, `pix.size()` still returns the width * height * numChannels?  Then it returns a `PixelType` value ... right?


Is the updated syntax now:

```cpp
  for(std::size_t d = 0; d < pix.getWidth() * pix.getHeight(); d++){
                ofColor color = pix.getColor(d);
  }
```

Maybe I'm not looking at the right version or something?

**Comment by bakercp** [comment]
Currently `pixels.size() == std::distance(pixels.begin(), pixels.end())`, which makes sense as the "iterable" item should be a pixel though, not the number of `PixelType` (width x height x numChannels).

**Comment by bakercp** [comment]
Sorry, to clarify, I'd argue that the iterable group should be the "Pixel" (which is numChannel dependent), so the `size()` should always be `width` x `height` and the `getColor()` takes an index.

Then, since we still need channel level access and the ability to write directly into contiguous memory (the YUV planes system complicates this ...) we need a different set of iterators to get the raw underlying `PixelType` array.

That said, I'm not sure how this fits in with the `pix.getLines()` iteration scheme ...

**Comment by arturoc** [comment]
mmh, has this ever be like that? i'd say that size has always returned the size of the whole memory. in any case the preferred way to iterate through pixels instead of compenents is:

```
for(auto & pixel:  pix.getPixelsIter()){
    pixel.getColor()
}
```

which avoids a ton of multiplications so it's way faster

**Comment by bakercp** [comment]
Looking into this deeper and clearly I'm / was confused.  No I don't think it's ever been like that.  I believe size has (in recent time) been the width * height * numChannels.

That said, what does it mean then to use @ofTheo's original for loop?

```cpp
 for(int d = 0; d < pix.size(); d++){
     ofColor color = pix.getColor(d);
 }
```

```cpp
	/// \brief Get the number of values that the ofPixels object
	/// contains, so an RGB data 400x400 would be 480,000, whereas RGBA data
	/// of the same dimensions would be 640,000.
	size_t size() const;
```

For a 3 channel image, what would it mean to ask for the color of the index == 5?

```
R G B | R G B | R G B
0 1 2 | 3 4 5 | 6 7 8
```

That is, what "ofColor" does `pixels.getColor(5)` return?

```
    ofPixels pixels;

    pixels.allocate(2, 1, OF_PIXELS_RGB);
    pixels[0] = 0;
    pixels[1] = 1;
    pixels[2] = 2;
    pixels[3] = 3;
    pixels[4] = 4;
    pixels[5] = 5;

    std::cout << pixels.getColor(0) << std::endl;
    std::cout << pixels.getColor(1) << std::endl;
    std::cout << pixels.getColor(2) << std::endl;
    std::cout << pixels.getColor(3) << std::endl;
    std::cout << pixels.getColor(4) << std::endl;
    std::cout << pixels.getColor(5) << std::endl;

```

returns 

```cpp
0, 1, 2, 255
1, 2, 3, 255
2, 3, 4, 255
3, 4, 5, 255
4, 5, 0, 255
5, 0, 0, 255
```

I understand it's just starting with the given index and grabbing the next values and synthesizing as needs (see e.g. it assumes alpha == 255 for all and makes up B and and G, B values for index 4 and 5).

So, I suppose my question is ultimately one of interface.  I guess I feel that the `pix.getColor(std::size_t index)` function is confusing :)

This whole section needs clarification and we should prefer iterators I believe:

```

	/// \brief Get the pixel index at a x,y position
	///
	/// ~~~~{.cpp}
	/// ofColor yellow = ofColor::yellow;
	/// size_t ind = pix.getPixelIndex(mouseX, mouseY);
	/// pix.setPixel(ind, yellow);
	/// ~~~~
	size_t getPixelIndex(size_t x, size_t y) const;
	
	/// \brief Get the color at a x,y position
	ofColor_<PixelType> getColor(size_t x, size_t y) const;

	/// \brief Get the color at a specific index <<<<<< doesn't have to be the 0th channel.
	ofColor_<PixelType> getColor(size_t index) const;
	
	/// \brief Set the color of the pixel at the x,y location <<< for a 3 color image does it write the alpha channel ...? 
	void setColor(size_t x, size_t y, const ofColor_<PixelType>& color);

	/// \brief Set the color of the pixel at a specific index
	void setColor(size_t index, const ofColor_<PixelType>& color);

	/// \brief Set the color of all pixels?
	void setColor(const ofColor_<PixelType>& color);

	/// \brief Provides access to each channel of each pixel. If you have RGB pixel
	/// data, then you'll have 3 values for each pixel, if you have RGBA,
	/// you'll have 4
	const PixelType& operator[](size_t pos) const;
	PixelType& operator[](size_t pos);
```

Maybe this is just a documentation issue ... but anyway, there is a bit of magic here for convenience that seems like it should be clarified.

My "solution" would be to leave direct byte array access as that is essential, and get rid of the index based getter / setter.  Setting by x / y still makes sense and is intuitive for new users.  Setting and getting `ofColor` by index is confusing.

Thanks for your patience as I'm working through this :)

**Comment by arturoc** [comment]
i think the only problem is that size might be confusing, we can deprecate it and rename it to getNumComponents / getNumPixels or something like that

getColor(i) returns the ith pixel so it can't be used in combination with size(), theo's original example should have been:

```cpp
            for(int d = 0; d < pix.getWidth() * pix.getHeight(); d++){
                ofColor color = pix.getColor(d);
            }
```

**Comment by arturoc** [comment]
btw, the way you explain it's working was before the fix no? it should now be returning the color for each pixel.

**Comment by ofTheo** [comment]
Oh man - I was actually incorrectly assuming size() was the number of pixels not number of total bytes, mainly because we already have ofPixels::getTotalBytes(); 

Looking at the comment in the inline code and checking it, however size() is the same as getTotalBytes() ( though it looks like it could be different if pixels are stored with a different pixel type ). 

For an HD video: 
```
 pix size is 6220800, getTotalBytes is 6220800, num pixels is 2073600
```

I guess if you are doing raw byte level access, I would use size() to iterate through every byte. 
But in this case when using getColor by index, I assumed that size represent the number of pixels and not the number of bytes. 

So I think the current code is correct. 

I think maybe just a getNumPixels as @arturoc suggests would be helpful. 

And what @arturoc said was correct - my original example should have been: 
```
            for(int d = 0; d < pix.getWidth() * pix.getHeight(); d++){
                ofColor color = pix.getColor(d);
            }
```

**Comment by bakercp** [comment]
@ofTheo I think I was under the same (incorrect it seems) assumption of what size() was counting.

Also, remember that "byte" level access is different for `ofFloatPixels`, `ofShortPixels` etc.  So we need to be clear whether it is truly `byte` (octet) level access or it is `channel` level access (which is probably more accurate because deep down inside of `ofPixels` it's just a:

```cpp
PixelType * pixels = nullptr;
```

**Comment by bakercp** [comment]
Just to add, I think the current functionality is correct (size() should be counting the number of `PixelType` there are ... width x height x number channels.  The solution, to me, seems that we simply need to have a function that returns the number of PixelType.

Thus, in my understanding 

`ofPixels::getTotalBytes() == ofPixels::size() * sizeof(PixelType)`

Which is different depending on the PixelType.

Then we should have a function that is `ofPixels::getNumPixels()` which is just `width x height` and _that_ index is what should be used for pixel level access.

Then `ofPixels::size()` is the index that gives us the ability to get individual elements of the underlying `PixelType * pixels = nullptr;` array, which may (or may not be) a single octet per channel (e.g. float, short etc).  If people _actually_ want to iterate over octets, then they can:

```
uint8_t* data = reinterpret_cast<uint8_t*>(pixels.getData());

for (std::size_t i = 0; i < pixels.getTotalBytes(); ++i)
{
  uint8_t actualByte = data[i]; // which will not fully == a channel for ofFloatPixels, ofShortPixels, etc).
}

```

Anyway, I think ofPixels is designed really well and I think all of the above is already the case.  It is possible that this may just come down to a misunderstanding / documentation.

**Comment by bakercp** [comment]
Based on my tests, 3aa7ef0 cases segmentation faults on Linux, but 64/armv6.

I believe it should be reversed.

**Comment by arturoc** [comment]
can you post an example showing the crash? i've tested it and was working correctly for me.

as it was before it wasn't doing what it should do.

**Comment by ofTheo** [comment]
That all sounds perfect to me Chris! 
Thanks for summing it up so nicely.

**Comment by bakercp** [comment]
https://forum.openframeworks.cc/t/ofpixels-throwing-exception-well-inside-xy-bounds/24881/3
https://github.com/Betecher/Code-review/issues/1

**Comment by johanjohan** [comment]
Hey, as stated in the link referenced by Christopher above, there is a xy-indexing issue with ofPixels (OF 096 win10 downloaded yesterday). I pasted code with an image that throws an exception.

**Comment by arturoc** [comment]
yeah saw this yesterday what happened is that getColor(int) has always worked the way it did before this fix.

when we introduced ofPixels we were more used to work directly with an array of unsigned char so getColor just received the index in the raw array that was usually calculated with getPixelIndex or just iterating with a for loop using +=4

after using ofPixels for a while and using iterators that can jump to the exact position of every pixel it seems more correct that getColor received the pixel index rather than the index in the raw array.

not sure what to do:
- should we go back to the previous version? 
- change getPixelIndex to return the pixel index as in number of pixels rather than index in the raw array?
- perhaps we can add a getRawPixelIndex getColorAtRawIndex (or something like that) revert this change and deprecate the old methods?

**Comment by johanjohan** [comment]
i have not yet fully contemplated the iterative elegance described above, but suggest that keeping a working getColor(x,y) would be a good way bridging the oldstyle scary array index calculations with the new concept of implementing iterators. getColor() is ineffective and a bit slow but i use it a lot for non-realtime work as it hides the array index calculus. wouldn't a change in the general approach break a lot of people's code?

**Comment by arturoc** [comment]
> wouldn't a change in the general approach break a lot of people's code?
yeah totally that's why i was suggesting to add new methods with a more descriptive name and keep the old ones with the exact same behavior but deprecated

**Comment by bakercp** [comment]
I think this is a case where deprecation is really important because it breaks at runtime and even when you follow the backtrace it isn't exactly clear what the problem is.  Based on the discussion above it also gives us a chance to document iterators and start building better habits(as both teachers and users) with the new iterators.

**Comment by ofTheo** [comment]
@bakercp the getColor(int index) works for me in 0.9.6 
but getColor(int x, int y) does seem broken. 

This is the test code I used:

```
static ofPixels pix;

//--------------------------------------------------------------
void ofApp::setup(){
    ofLoadImage(pix, "/Users/theo/Pictures/tintin-small.jpg");
    

}

//--------------------------------------------------------------
void ofApp::draw(){

    int x, y =0;
    int numPixels = pix.getTotalBytes() / pix.getNumChannels();
    for(int d = 0; d < numPixels; d++){
        
        ofColor color = pix.getColor(d);
        
        ofSetColor(color);
        ofDrawRectangle(x, y, 1, 1);
        x++;
        if( x >= pix.getWidth() ){
            x = 0;
            y ++;
        }
    }
}
```

**Comment by ofTheo** [comment]
> not sure what to do:
> 
> should we go back to the previous version?
> change getPixelIndex to return the pixel index as in number of pixels rather than index in the raw array?
> perhaps we can add a getRawPixelIndex getColorAtRawIndex (or something like that) revert this change and deprecate the old methods?

I guess I would argue that ofPixels::getColor(int index) only makes sense as pixel index instead of raw array position.  A color spans multiple positions in the array, so you wouldn't loop through each array position and ask for a color as then you could be reading a color from multiple pixels. 

To me the way it works now does seem correct ( for index based lookup ). 
I think we are just missing a ofPixels::getNumPixels() and a fix for 2D lookup. 

But maybe I don't completely understand the current issue? :)

**Comment by fishinggame** [comment]
ofApp.h:

#include "ofMain.h"
#include "pong.h"
#include "side.h"
class ofApp : public ofBaseApp {

public:
	void setup();
	void update();
	void draw();
	pong ball;
	side wall;
};

ofApp.cpp:


#include "ofApp.h"
#include "pong.h"
#include "side.h"
//--------------------------------------------------------------
void ofApp::setup() {
	float i = 300, j = 100;
	int x=10;	
	wall.l();
	ball.l(i, j, x);
}

//--------------------------------------------------------------
void ofApp::update() {
}

//--------------------------------------------------------------
void ofApp::draw() {
	wall.draw();
	ball.draw();
}

pong.h

#include "ofMain.h"
class pong {
public:
	void l(float x, float y, int dim);
	void draw();
	ofImage i;
private:
	float cor_x, cor_y, speed, alpha;
	int radius;
};

pong.cpp:



#include "ofMain.h"
#include "pong.h"
#include <cstdlib>
#include <math.h> 

void pong::l(float x, float y, int dim) {
	i.loadImage("ball.png");
	cor_x = x;
	cor_y = y;
	speed = 0.1;
	radius = dim;
	alpha = 30;
}

void pong::draw() {
	i.draw(cor_x, cor_y, radius, radius);
}

side.h:

#include "ofMain.h"
class side {
public:
	void l();
	void draw();
	ofImage k;
private:
};

side.cpp:

#include "ofMain.h"
#include "side.h"
#include <cstdlib>
void side::l() {
	k.loadImage("side.png");
}

void side::draw() {
	k.draw(0, 0, 800, 20);
	k.draw(0, 580,800, 20);
}

main.cpp:


#include "ofMain.h"
#include "ofApp.h"

//========================================================================
int main() {
	ofSetupOpenGL(800, 600, OF_WINDOW);			// <-------- setup the GL context
	ofRunApp(new ofApp());

}




Hi! I'm writing this code to make a game like old Pong. I'm using image to draw a ball, and another image to draw a rectangles which represents borders of the game. If i'm drawing only ball, or only rectangles everything is working. But if i want them both my program throws this exception:
"Exception thrown: read access violation.
this->k. was 0xA."

And i think that it is a problem with the function discribed in this topic. 
Can you help me solve my problem?
I'm new with OF so please dont laught:)

**Comment by arturoc** [comment]
@ofTheo the problem is that this function has never worked like you posted originally. the correct way of using it has always been:

```
for(int d = 0; d < numPixels; d+=pixels.getNumChannels()){
```

which made a lot of sense if you were used to using raw unsigned char arrays but it's kind of weird after a few years using the ofPixels abstraction, i'm going to revert the change and do a 0.9.7 with a few other fixes and we can then discuss what to do for 0.10

**Comment by arturoc** [comment]
@fishinggame this is a bug there's not much you can do except using an older version, until it's fixed. 0.9.4 should work fine

**Comment by ofTheo** [comment]
Okay. That sounds good!
Makes sense.

**Comment by johanjohan** [comment]
@fishinggame yes 0.9.4 works as suggested

**Comment by fishinggame** [comment]
Thanks a lot! On 0.9.4 works fine!
