### ISSUE TITLE
Can't generate projectgenerator on 0.9.5

### ISSUE THREAD

**Issue by thyeun** [openframeworks/openFrameworks#5324]
OS : ubuntu 16.04 64-bits
OF : 0.9.5

`thyeun@thyeun-laptop:~/OF/scripts/linux$ ./compilePG.sh
make: Entering directory '/home/thyeun/OF/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 libmpg123 
Compiling OF library for Release
make[1]: Entering directory '/home/thyeun/OF/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 libmpg123 
Done!
make[1]: Leaving directory '/home/thyeun/OF/libs/openFrameworksCompiled/project'

Compiling projectGenerator for Release
make[1]: Entering directory '/home/thyeun/OF/apps/projectGenerator/commandLine'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 libmpg123 
make[1]: *** No rule to make target '/home/thyeun/OF/addons/obj/linux64/Release/ofxPoco/./src/ofApp.o', needed by 'bin/projectGenerator'.  Stop.
make[1]: Leaving directory '/home/thyeun/OF/apps/projectGenerator/commandLine'
/home/thyeun/OF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2
make: Leaving directory '/home/thyeun/OF/apps/projectGenerator/commandLine'
There has been a problem compiling the command line projectGenerator.
Please report this problem in the forums.
`

Cant generate projectGenerator

**Comment by arturoc** [comment]
can you try if this works? http://openframeworks.cc/versions/v0.9.6/

**Comment by thyeun** [comment]
@arturoc good day, will try it out and feedback to you if it is still given the same problem.

**Comment by thyeun** [comment]
@arturoc it is working now, thank you so much.
