### ISSUE TITLE
VS2015 - Code mismatch - Master 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#5330]
Hey was just building master and noticed this error.

I downloaded the latest libs so I think something went wrong with uriparser or one of the new additions as it was working fine 2 weeks ago.

Issue is one of the libs or something is compiled with VS 2013 (20130802) rather than VS 2015 (20150812)

```
1>LINK : fatal error C1900: Il mismatch between 'P1' version '20150812' and 'P2' version '20130802'
1>LINK : fatal error LNK1257: code generation failed
```

**Comment by arturoc** [comment]
that's really strange, it's compiling fine in the test servers with 2015 in both 32 and 64 bit. is this happening in release or debug?

**Comment by danoli3** [comment]
Classic, I traced it back to Cygwin installing an old version of Boost 1.55.0 compiled with VS 2013 which it decided to add to my windows path variables...

VS just didn't give me any symbol or feedback errors as to exactly what the issue or problem was so I didn't think it was something external to the project libs.

All working!

**Comment by KhalilKhalaf** [comment]
it is unclear what was the fix?
