### ISSUE TITLE
gitignore for project generator

### ISSUE THREAD

**Issue by fooness** [openframeworks/openFrameworks#5334]
Dear openFrameworkers,

I thought there’d already be a .gitignore file project generator on OSX uses when creating new projects. https://github.com/openframeworks/openFrameworks/issues/2791

Wasn’t that added to openFrameworks (osx-v0.9.7) yet? Kindest regards!

**Comment by d-egan** [comment]
Sounds like a duplicate of #5792 ?
Closed with #5824

**Comment by bakercp** [comment]
It sure looks like it.  @fooness if you don't agree, please reopen with additional information.
