### ISSUE TITLE
Wrong PixelType for ofImage::grabScreen() on Raspberry Pi

### ISSUE THREAD

**Issue by hobzcalvin** [openframeworks/openFrameworks#5336]
I'm running 0.9.3 on a Rapberry Pi 3 Model B. To reproduce, put this draw method in an empty project:
```
void ofApp::draw(){
  ofBackground(10, 20, 30);
  ofImage grab;
  grab.grabScreen(0, 0, ofGetWidth(), ofGetHeight());
  for (int i = 0; i < 5; i++) {
    cout << i << ": " << grab.getColor(i) << "\n";
  }
}
```
it outputs:
```
0: 10, 20, 30, 255
1: 20, 30, 255, 10
2: 30, 255, 10, 20
3: 255, 10, 20, 30
4: 10, 20, 30, 255
```

It seems that the internal pixels object for the grabbed image is in RGBA format, but `sizeof(pixels[0])` is 3 when it should be 4. Somehow it's indexing 3 bytes at a time when it should be indexing 4 bytes at a time, though the data itself is RGBA and returned values are in RGBA format.

**Comment by hobzcalvin** [comment]
Sorry, that'll teach me to code late at night...clearly getColor(N) needs to be called with multiples of 4, whereas getColor(X, Y) appears to figure out the proper indexing.

**Comment by bakercp** [comment]
Hey @hobzcalvin there were some recent changes / discussion on this topic and what index getColor() refers to -- if you want the low-down (and a quick sanity check with 0.9.3 vs. updates with the `getColor()` functions since then, check out this thread ...

https://github.com/openframeworks/openFrameworks/issues/5321

**Comment by hobzcalvin** [comment]
Thanks @bakercp. I think my confusion may have come from the fact that I had things working on my Mac which has version 0.9.6. When I tried to run the project on the pi with 0.9.3, things behaved differently?

**Comment by bakercp** [comment]
That is a possibility -- I believe there was a regression in 0.9.5, that was reverted in 0.9.7, bringing it back in sync with < 0.9.5.  Anyway, not sure how / if it affected you but it would explain why it worked differently between your 0.9.6 version and 0.9.3.  Bottom line is that the `index` used in  `getColor(index)`  must be incremented by the number of channels `index+=3` for rgb or `index +=4` for rgba if you want the returned colors to make sense.  `getColor(x, y)` works more intuitively and we're in the process of clarifying the use of these `getColor()` functions.
