### ISSUE TITLE
0.9.7 gstreamer0.10-plugins-ugly error on Ubuntu 16.04

### ISSUE THREAD

**Issue by cjdg** [openframeworks/openFrameworks#5342]
There is an error when i want to install the codecs package on ubuntu 16.04 x64 cause there is no candidate for installation

**Comment by underdoeg** [comment]
Can you post the output of ```sudo apt-get install gstreamer0.10-plugins-ugly```?

**Comment by arturoc** [comment]
i think the probelm is that it's failing to detect the gstreamer version, it should be trying to install gstreamer1.0-plugins-ugly not 0.10

can you try installing that manually?

**Comment by cjdg** [comment]
Sure

**Comment by cjdg** [comment]
It works! :) with the 1.0

**Comment by echorebel** [comment]
@arturoc yes it's failing to detect the version.
I get following error when executing [install_codecs.sh](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/ubuntu/install_codecs.sh):
`./install_codecs.sh: 16: [: 0: unexpected operator`
therefor it's not setting the version to 1.0

**Comment by genleung** [comment]
You should run install_codecs.sh with BASH instead of SH, like this way:
`sudo bash ./install_codecs.sh`
It's the test [ ] operator problem.

**Comment by echorebel** [comment]
@genleung works. thx for the hint!

**Comment by bakercp** [comment]
Closing as this seems to be fixed.
