### ISSUE TITLE
ofxGui save and load are broken with new ofXml api.

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#5344]
Hi,
with the current HEAD I cannot save to xml as the ofSerialize and ofDeserialize were not added to the new implementation of ofXml. I have a working version of for it. Should I PR?

Also saving to json works but loading is half working as it only loads basetype ofParameters. It will not load ofColor or ofVecs. Any clues on this?
@arturoc 

all the best!

**Comment by roymacdonald** [comment]
Ok. so Here's the fix
https://github.com/roymacdonald/openFrameworks/commit/120760f2725363fb1b33ff866f218d3b42690b28
The problem with saving to json that the nested groups were not being parsed. I've also added this fix in the commit. 
PR?

**Comment by arturoc** [comment]
yes please can you send a PR? thanks!
