### ISSUE TITLE
ofPolyline not working with ofVec2f

### ISSUE THREAD

**Issue by javl** [openframeworks/openFrameworks#5346]
The docs mention:
`ofPolyline(...) Creates an ofPolyline from a vector of ofVec2f or ofPoint objects.`

This seems to be wrong; you can't use `ofVec2f` but need `ofVec3f`. Is this an error in the docs, or would it be possible to make this work with `ofVec2f` as well?
Seeing as you often use `ofPolyline` with 2D graphics, it seems logical to use `ofVec2f`.

I can't seem to find the `ofPolyline.cpp` file in the online repo to edit, though I do have one in my local folder at `/libs/openframeworks/graphics/ofPolyline.cpp`.

See this post on the forum:
https://forum.openframeworks.cc/t/cant-create-ofpolyline-from-ofvec2f/24620

**Comment by arturoc** [comment]
answered in the forum, going to close it since it isn't really an issue
