### ISSUE TITLE
Calling ofGetWidth() or ofGetHeight() in update() or draw() while in full screen mode causes a massive slowdown [Linux][0.9.7]

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#5350]
Currently observing this under Ubuntu 16.04, but could affect other platforms.

Basically take an empty app. Put this in the draw():
```javascript
    int x = ofGetHeight();
    ofDrawBitmapString(ofToString(ofGetFrameRate()),20,20);
```

Then toggle fullscreen mode and watch the FPS go up and down!

**Comment by pierrep** [comment]
Seems like if I move the mouse in fullscreen I get freezes too. The culprit appears to be:
```
		glfwGetMonitorPos(monitors[iC], &xM, &yM);
```

This gets called in ofAppGLFWWindow::getScreenSize() which would explain the slowdowns in ofGetWidth/Height too.

**Comment by arturoc** [comment]
are you using OF from the downloads or the repository? i fixed something similar to this here: https://github.com/openframeworks/openFrameworks/pull/5028 so not sure if it's cropped up again.

**Comment by arturoc** [comment]
sorry just saw that you are on 0.9.7, can you try if it's fixed in the nightlies?

**Comment by pbaret** [comment]
Same issue for me under Ubuntu 14.04 and Ubuntu 16.04 with of_0.9.7

**Comment by pierrep** [comment]
I got 0.9.7 from git tags. Will try the latest.

**Comment by victor-shepardson** [comment]
I am also seeing exactly this problem with 0.9.3, 0.9.7, and stable. No difference changing the window manager.

**Comment by pierrep** [comment]
It's fixed in the nightlies.

**Comment by arturoc** [comment]
going to close this since it's an already fixed issue but won't be released until 0.10 since that class has other changes that make it difficult to backport to 0.9.x

**Comment by pbaret** [comment]
I have just done another test on Ubuntu 16.04 with of_0.9.8  running examples/3d/3DPrimitivesExample
In window mode: 60 fps no problem
In fullscreen mode: less than 1fps total lag ^^
So I will wait for 0.10 to add fullscreen to my project. 

Thanks for your efforts.

**Comment by arturoc** [comment]
the nightly builds should be pretty stable by now

**Comment by pbaret** [comment]
As I said, I downloaded OF 0.9.8 from website today and test 3DPrimitive example, in fullscreen the framerate drops.


________________________________
De : arturo <notifications@github.com>
Envoyé : mercredi 30 novembre 2016 15:59
À : openframeworks/openFrameworks
Cc : pbaret; Comment
Objet : Re: [openframeworks/openFrameworks] Calling ofGetWidth() or ofGetHeight() in update() or draw() while in full screen mode causes a massive slowdown [Linux][0.9.7] (#5350)


the nightly builds should be pretty stable by now

-

**Comment by arturoc** [comment]
yeah that's not the nightly builds, you can find those after the official downloads in the same download page

![image](https://cloud.githubusercontent.com/assets/48240/20779952/b2ab1eba-b756-11e6-8a9c-9c13cbab1915.png)

**Comment by pbaret** [comment]
Okay thank you very much, I will try that.

Sorry I did not understand that.


Thanks again for your work.


________________________________
De : arturo <notifications@github.com>
Envoyé : jeudi 1 décembre 2016 03:43
À : openframeworks/openFrameworks
Cc : pbaret; Comment
Objet : Re: [openframeworks/openFrameworks] Calling ofGetWidth() or ofGetHeight() in update() or draw() while in full screen mode causes a massive slowdown [Linux][0.9.7] (#5350)


yeah that's not the nightly builds, you can find those after the official downloads in the same download page

[image]<https://cloud.githubusercontent.com/assets/48240/20779952/b2ab1eba-b756-11e6-8a9c-9c13cbab1915.png>

-
