### ISSUE TITLE
Compiling on Ubuntu16.04 x64 fails with "tesselator.h: No such file or directory"

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#5358]
Hi,

I cannot compile the current master branch of openFrameworks or any example on Ubuntu 16.04 x64. I ran the `install_dependencies.sh` script. I ran `make clean` in the openFrameworks project directory. I got rid of a first error by installing `libcurl` (should this be added to the install_dependencies script?) , but this one remains:
```
libs/openFrameworks/utils/ofConstants.h:287:24: fatal error: tesselator.h: No such file or directory
```
Am I doing something wrong or what is missing?

**Comment by nanu-c** [comment]
There is missing the tess library, maybe you have to run the _new_ download_libs.sh script?

**Comment by frauzufall** [comment]
Argh yes. I did not know about that, thank you!
