### ISSUE TITLE
Install openFrameworks on Wandboard

### ISSUE THREAD

**Issue by aletes67** [openframeworks/openFrameworks#5360]
Hi
I have tried to install "of_v0.9.7_linuxarmv7l_release" on Wandboard with 

Linux wandboard 3.10.53-1.1.0_ga-wandboard-06034-g13bb184-dirty #1 SMP PREEMPT Thu Apr 30 14:15:30 CST 2015 armv7l armv7l armv7l GNU/Linux

with this commands:

sudo ./install_dependencies.sh
sudo ./install_codecs.sh

but I get this error on make of example:
------------------------------------------
root@wandboard:/opt/of_v0.9.7_linuxarmv7l_release/scripts/linux/ubuntu# cd ../../../examples/graphics/polygonExample/
root@wandboard:/opt/of_v0.9.7_linuxarmv7l_release/examples/graphics/polygonExample# make
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl gtk+-3.0 libmpg123 glesv1_cm glesv2 egl 
/opt/of_v0.9.7_linuxarmv7l_release/libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk:294: *** glesv1_cm not installed. Did you run the latest install_dependencies.sh?.  Stop.

**Comment by aletes67** [comment]
I solved running 
sudo ./install_dependencies.sh
sudo ./install_codecs.sh
from /opt/of_v0.9.7_linuxarmv7l_release/scripts/linux/debian

**Comment by bakercp** [comment]
Nice!
