### ISSUE TITLE
Is there anyway to get the recorder power Using AudioUnit or AudioSeesion?

### ISSUE THREAD

**Issue by levinXiao** [openframeworks/openFrameworks#5366]
I can't get the input Volumn when recoding using Audio Unit

Is there anyway to get the recorder power Using AudioUnit or AudioSeesion ?

Is there API like AVAudioRecorder averagePowerForChannel:channel ?

can you help me to get the volumn :)?

**Comment by bakercp** [comment]
I'd recommend asking for help on this on http://forum.openframeworks.cc. Closing this for now.
