### ISSUE TITLE
Bug? ofPixels allocates wrong amount of memory

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#5369]
looking at:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofPixels.cpp#L465

it seems that we always allocate the wrong amount of memory whenever `PixelType != unsigned char` since we're allocating an array of `PixelType` with array size being the desired size of memory in bytes (i.e. if `PixelType` is float, we're actually allocating 4* as much memory as we need).

perhaps instead we should be using `pixels = new PixelType[pixelsSize];`

**Comment by elliotwoods** [comment]
for reference pasting the function here:

```c++
template<typename PixelType>
void ofPixels_<PixelType>::allocate(size_t w, size_t h, ofPixelFormat format){
	if (w == 0 || h == 0 || format == OF_PIXELS_UNKNOWN) {
		return;
	}

	size_t newSize = bytesFromPixelFormat(w,h,format);
	size_t oldSize = getTotalBytes();
	//we check if we are already allocated at the right size
	if(bAllocated && newSize==oldSize){
		pixelFormat = format;
		width = w;
		height = h;
		return; //we don't need to allocate
	}

	//we do need to allocate, clear the data
	clear();

	pixelFormat	= format;
	width 		= w;
	height 		= h;

	pixelsSize = newSize / sizeof(PixelType);

	pixels = new PixelType[newSize];
	bAllocated = true;
	pixelsOwner = true;
}
```

**Comment by arturoc** [comment]
it should be `new PixelType[pixelsSize]` right? can you send a PR? otherwise i'll fix it later
