### ISSUE TITLE
ofVideoPlayer::isPlaying() behaves differently on Linux than OSX

### ISSUE THREAD

**Issue by microcosm** [openframeworks/openFrameworks#5370]
I tested how `ofVideoPlayer` responded to three method calls across two platforms, before, during and after playback via `play()`.

On Mac OSX:

```
         isPlaying()  isPaused()  getIsMovieDone()
Before   0            1           0
During   1            0           0
After    0            1           1
```

On Raspberry Pi running Arch Linux:

```
         isPlaying()  isPaused()  getIsMovieDone()
Before   1            1           0
During   1            0           0
After    1            0           1
```

Linux always thinks it's playing.

In case anyone sees this and needs a workaround for `isPlaying()` until it's fixed, try this method which appears to work on both platforms:

```
bool isCurrentlyPlaying() {    
    return !isPaused() && !getIsMovieDone();
}
```

From [this forum post](https://forum.openframeworks.cc/t/ofvideoplayer-isplaying-behaves-oddly-on-linux/).

**Comment by dimitre** [comment]
I think this one can be closed. Behavior was modified by this one https://github.com/openframeworks/openFrameworks/pull/6987
