### ISSUE TITLE
Offer PPA with prebuild packages for Raspberry Pi

### ISSUE THREAD

**Issue by PanderMusubi** [openframeworks/openFrameworks#5374]
Please, offer PPA with prebuild packages for Raspberry Pi. This will greatly reduce the time to install openFrameworks on any Raspberty Pi.

**Comment by tiagmoraismorgado** [comment]
definitely something to take into account

**Comment by danzeeeman** [comment]
We have discussed this in the past. Currently RPi builds are not the slowest that award goes to VIsual Studio followed by Xcode. Closing the issue as it is a non issue

**Comment by PanderMusubi** [comment]
What was the reason back then not to offer builds for Raspbian?
