### ISSUE TITLE
v0.9.8 not compiling on Raspberry Pi

### ISSUE THREAD

**Issue by autr** [openframeworks/openFrameworks#5377]
No problems compiling v0.9.3 but getting this error trying to compile the latest v0.9.8;

`pi@autr1:~/openFrameworks0.9.8/scripts/linux/debian $ make Release -C /home/pi/openFrameworks0.9.8/libs/openFrameworksCompiled/project/
make: Entering directory '/home/pi/openFrameworks0.9.8/libs/openFrameworksCompiled/project'
HOST_OS=Linux
makefileCommon/config.shared.mk:217: *** This package doesn't support your platform, probably you downloaded the wrong package?.  Stop.
make: Leaving directory '/home/pi/openFrameworks0.9.8/libs/openFrameworksCompiled/project'`

**Comment by arturoc** [comment]
what operating system (raspbian? arch linux?) and which version of OF are you downloading? (armv6? 7?)

**Comment by bakercp** [comment]
Closing this due to no feedback and RPi is working on master branch.
