### ISSUE TITLE
OF 0.9.8 + iOS 10.1 + Xcode 8.1 "library not found for -lcrt1.3.1.o"

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#5378]
I fixed this by:

1. Clicking on the project "emptyExample" at the top left.
2. Clicking on "Build Settings" near the top center/right.
3. Changing "Build Active Architecture Only" to "Yes".

The fix was found in [this post](http://qiita.com/dropcontrol/items/d22d768b6448cd8a786b) by @dropcontrol

**Comment by csotiriou** [comment]
@kylemcdonald  Will this have any effect when deploying to production?

When deploying to production, we should build the application for all architectures, not just the active one.

**Comment by jvcleave** [comment]
I've also ran into this recently - I believe I fixed it by raising the [deployment target ](http://stackoverflow.com/questions/39632155/ld-library-not-found-for-lcrt1-3-1-o-error-while-running-app-in-device-with-xc)

**Comment by csotiriou** [comment]
@jvcleave Indeed. OF Samples seem to be linking against iOS 5.1.1. When I raised it to iOS 9, the problem disappeared.
