### ISSUE TITLE
iosStoryboardExample "Could not find a storyboard"

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#5379]
The `iosStoryboardExample` fails to run. This is an old bug mentioned by @NickHardeman in this comment https://github.com/openframeworks/openFrameworks/issues/1829#issuecomment-37434178 which @julapy says had "something to do with the way PG adds storyboards and xibs to xcode projects". I couldn't find an issue tracking this problem so I thought I'd contribute one.

**Comment by ofZach** [comment]
I've opened an issue on the PG side.  going to close this one...
