### ISSUE TITLE
Raspberry pi3 can not find packages when installing openFrameworks

### ISSUE THREAD

**Issue by vaimik** [openframeworks/openFrameworks#5395]
Hello, 
I'm trying to install openFrameworks on rpi3. I was following step by step tutorial from here:
http://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/ .
I have tried few openFramework releases: v0.8.4, v0.9.3, v0.9.7 with few raspbian versions (2016-09-23-raspbian-jessie, 2016-11-25-raspbian-jessie) with no luck - always the same problem: unmet dependencies libgtk-3-dev and libegl1-mesa-dev: 
```
The following packages have unmet dependencies:
libegl1-mesa-dev: Depends: libwayland-dev (>=1.2.0) but it is not going to be installed
libgtk-3-dev: Depends: libwayland-dev (>=1.4.0) but it is not going to be installed
E:Unable to correct problems, you have held broken packages.
```

I have already tried dist-upgrade, manually tried to install libgtk3 and other solutions from forums, but nothing helped...

Any thoughts?

**Comment by sy1vain** [comment]
I have the same problem since last friday, using the same script I have been using for weeks now, but the install_dependencies fails. As a quick fix I removed `libgtk${GTK_VERSION}-dev`, `libegl1-mesa-dev`, `libgles1-mesa-dev` and `libgles2-mesa-dev` from the install_dependencies.sh script. Now it continues and I can build my project. It might kill some things for some projects, for me at this moment it works.. But awaiting a fix.

**Comment by arturoc** [comment]
this sounds like a problem in raspbian itself. try uninstalling libwayland-dev first to see if that solves it but not sure if that will break other packages. perhaps report this problem in the raspberry pi forum

**Comment by vaimik** [comment]
already reported :)

**Comment by sy1vain** [comment]
`libwayland-dev depends` on `libwayland-client0=1.6.0-2` which would be a downgrade, and that would also remove a lot (if not all) of the needed modules for xorg.

Discussing this on raspbian forum as well, will do a pull request if we find a solution.

@vaimik what examples are not working for you.

**Comment by vaimik** [comment]
I'll check all the examples and report (some of examples were not working on my old rpi B+ too).

**Comment by vaimik** [comment]
Good news, that now, after apt-get update and apt-get dist-upgrade, all dependencies are correct and openFrameworks compiles. But half of the examples still are not working... But it is too many error text to post it there, also my old program does not work, which I wrote 3 years ago with rpi B+ and openFrameworks 0.8.4.  And I am a bit dissapointed of empty template - it is so basic, that i cannot even use any of my addons: openCV, rpi camera grabber and shaders.

**Comment by sy1vain** [comment]
The codebase has changed indeed. So not all code works directly, but in most cases it is a matter of some small changes. Addons can be most easily added through a add-ons file which will be handled through the `make` command. See the add-on examples.

And can you mention some examples that are still not working?

**Comment by bakercp** [comment]
Closing this as it is now working and tested on Raspberry Pi 3 with master.   Please open again if there are specific issues remaining.
