### ISSUE TITLE
ofxPanel.setup("title") doesn't display panel title (since 0.9.4)

### ISSUE THREAD

**Issue by ciaron** [openframeworks/openFrameworks#5396]
On versions >0.9.3, setting  `collectionName` in `ofxPanel.setup()` as per the [documentation](http://openframeworks.cc/documentation/ofxGui/ofxPanel/#show_setup) doesn't work. The panel title remains blank.

Tested on Linux and Mac, qtcreator, Xcode and command line:
0.9.3 (title appears)
0.9.4 (no title)
0.9.8 (no title)

Test code: `examples/gui/guiExample/ofApp.cpp`, line 11:

1. `gui.setup("test"); // most of the time you don't need a name`
 
2. `gui.setup(); // most of the time you don't need a name`

**Comment by arturoc** [comment]
it's fixed now in master. thanks!

**Comment by didibib** [comment]
I still got the issue with version 0.9.8, thoughts?
