### ISSUE TITLE
optimizations in open frameworks renderer

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5405]
Greetings
It would be interesting, within a sense, to come up with the following updates to open frameworks renderer:
- A) completing the Vulkan Renderer;
- B) creating bindings of openframeworks renderer to Khronos SYCL;
- C) taking advantage of algorithms present in game engines such as: id tech 2, 3, 4 and 5; unity, unreal engine, and cry engine

**Comment by roymacdonald** [comment]
Hi, it certainly could be interesting.
Do you have any working implementations of what you mention with OF?
At first it sounds to me that the correct thing would be to implement these as addons, then if these work fine add them to the core (which happens to be a quite common strategy).
Cheers

**Comment by bakercp** [comment]
Closing this for now.  Please open a discussion on the forum for feature requests and then we can migrate them into issues once it's a clear bug or an actionable PR.
