### ISSUE TITLE
iosExternalDisplayExample does not compile.

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#5417]
Trying out the iosExternalDisplayExample it does not compile, I get this error:

  "ofxAccelerometerHandler::setup()", referenced from: ofApp::setup() in ofApp.o

  "_ofxAccelerometer", referenced from: ofApp::setup() in ofApp.o

Not sure if it was needed, but removing

	// initialize the accelerometer
	ofxAccelerometer.setup();

from testApp.h makes it work.

**Comment by bakercp** [comment]
Related #5443

**Comment by bakercp** [comment]
Closing this as there is more discussion in #5443
