### ISSUE TITLE
Ubuntu Studio 64 build issues

### ISSUE THREAD

**Issue by DrumAliens** [openframeworks/openFrameworks#5418]
Downloaded openFrames from Github and ran install_dependencies.sh and install_codecs.sh

When I ran compileOF.sh it came up initially with an error which I resolved by installing libglm-dev. On re running the compile script I then get an error about a missing file tessalator.h

Any ideas thank

**Comment by arturoc** [comment]
when using OF from github you need to run the download_libs script in scripts/platform (scripts/linux in your case)

this is explained in the readme file
