### ISSUE TITLE
ofImage: loadImage(): couldn't load image from

### ISSUE THREAD

**Issue by ravisahu** [openframeworks/openFrameworks#5419]
Hello @arturoc ,

App is getting crash if we are loading image third time,its works fine for first 2 time.Below is log please check.

E/ofImage: loadImage(): couldn't load image from "/data/user/0/pacakage/files/input.png"

           [ 01-20 10:52:53.039 20757:17304 I/         ]
           Method found!

           [ 01-20 10:52:53.039 20757:17304 E/         ]
           ofPixels: format doesn't support channels
E/cv::error(): OpenCV Error: Assertion failed (ssize.area() > 0) in void cv::resize(cv::InputArray, cv::OutputArray, cv::Size, double, double, int), file /home/arturo/Code/openFrameworks/scripts/apothecary/build/opencv/modules/imgproc/src/imgwarp.cpp, line 1834
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17304 (GLThread 1267)

**Comment by arturoc** [comment]
this doesn't seem related to ofImage, the error seems to be comming from opencv instead. probably because you are passing a wrong size or something like that. try debugging the application to see where it's crashing exactly

**Comment by ravisahu** [comment]
Hi @arturoc 
On logging into OpenCv it was found that the assertion failed as size was 0.
And size was 0 because the loading of image could not happen.

It is verified that the image and path have been same in the three attempts.
**Could not understand why the image load fails for the third time when it is perfect for the first two time.**

**Comment by arturoc** [comment]
can you post a short example that shows the problem?
