### ISSUE TITLE
Support for Ubuntu based OSes like Elementary

### ISSUE THREAD

**Issue by austince** [openframeworks/openFrameworks#5431]
The install scripts for ubuntu do not get the correct Major and Minor versions when run on OSes based on ubuntu because they report their own releases by default, not the release of the underlying ubuntu base. This forces people to do [janky](https://forum.openframeworks.cc/t/cannot-install-of-0-9-0-on-elementary-os-freya-ubuntu-14-04/21616) things to get their dependencies installed. 

Elementary, at least, reports the ubuntu base version by just appending `-u` to the `lsb_release -r` command, but I don't believe this flag exists in the straight ubuntu version. 

Shouldn't be a biggie, what do y'all think about using the _/etc/os-release_ file to determine distro id and go from there?

**Comment by arturoc** [comment]
sounds good, do you want to send a PR?

**Comment by austince** [comment]
on it! #5432

**Comment by bakercp** [comment]
Closed with #5432
