### ISSUE TITLE
ofPolyline needs smarter cache-updates ...

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5442]
... or I need to learn to use it better.

Currently when executing this code:

```c++
ofPolyline contour; // not const ...

/// ... cause I need to fill the polyline

for (std::size_t j = 0; j < contour.size(); ++j)
{
    auto currentPoint = contour[j];
    auto normalPoint = contour.getNormalAtIndex(j);
    float scale = 10;
    auto normalEndPoint = currentPoint - (normalPoint * scale);
    ofDrawLine(currentPoint, normalEndPoint);
}
```

accessing the `contour[i]` (which is calling the non const `operator[]` version), even if I assign it with `const auto& currentPoint = contour[j];` is internally calling `flagHasChanged()` _every time_ the polyline is accessed.  While I totally understand why a non-const `operator[]` would want to be safe and call `flagHasChanged()`, it's causing some significant performance hits.

My solution is, after I've filled my polyline, to just do ...

```c++
ofPolyline _polyline; // not const ...
// fill it

const ofPolyline polyline = _polyline;
```

but I'm wondering if it would make sense to add a const only accessor, or if there might be another way to improve performance without making const copies.

**Comment by roymacdonald** [comment]
Hey,
so  I guess that on your code snippet `contour` should be `polyline`. :)

I think that `flagHasChanged();` shouldn't be called when using either the [] operator or the `getVertices()` method as these are not really modifying the polyline, and if it gets to be modified the coder should be in charge of calling `flagHasChanged();`. Yet changing this can break some code as users can be used to not calling flagHasChanged().
I understand why `updateCache()` method is called in `getNormalAtIndex()` but by using the snippet code shown it actually updates the cache on every for loop iteration!
So, maybe another solution could be to have something like 	`vector<T> & getNormals();` and it's const version.
so we could do
```
auto& normals = polyline.getNormals();
float scale = 10;
for (std::size_t j = 0; j < polyline.size(); ++j)
{
    auto currentPoint = polyline[j];
    auto normalEndPoint = currentPoint - (normals[j] * scale);
    ofDrawLine(currentPoint, normalEndPoint);
}
```

**Comment by tgfrerer** [comment]
@bakercp the const methods are called from within a const context, i would assume (and have tested) that if you access your polyline through a const handle, the cache should not be invalidated. 

Perhaps if you try: 

    const auto& drawContour = contour;

	for ( std::size_t j = 0; j < drawContour.size(); ++j ){
		auto currentPoint = drawContour[j];
		auto normalPoint = drawContour.getNormalAtIndex( j );
		float scale = 10;
		auto normalEndPoint = currentPoint - ( normalPoint * scale );
		ofDrawLine( currentPoint, normalEndPoint );
	}

The cache won't be invalidated on each access, as the polyline is evaluated in const context. The important line here is `const auto& drawContour = contour;`, as it's worth noting that the `ofPolyline` is the object which must be accessed in const context...

**Comment by arturoc** [comment]
this will also work:

```
ofPolyline contour;

void draw() const{
    for ( std::size_t j = 0; j < contour.size(); ++j ){
	auto currentPoint = contour[j];
	auto normalPoint = contour.getNormalAtIndex( j );
	float scale = 10;
	auto normalEndPoint = currentPoint - ( normalPoint * scale );
	ofDrawLine( currentPoint, normalEndPoint );
    }
}
```

as long as the method you access the polyline from is const it'll also call the const [] operator. the other solution would be to have an update() method in the polyline and call it everytime you change the polyline externally which is easy to forget.

as tim says creating a const reference on any non const function will work the same too.

**Comment by bakercp** [comment]
Thanks for the work-around ideas.  I'll close this for now and perhaps update documentation.
