### ISSUE TITLE
PocoNetSSL.a missing symbols on OSX 

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5447]
This is happening on OSX on both travis and locally with the downloaded libs.

https://travis-ci.org/bakercp/ofxHTTP/jobs/201034304#L1213

This just started breaking within the last week or two -- but not sure when exactly.

**Comment by arturoc** [comment]
we haven't changed poco in months so it seems weird that it's only failing in the last week or so, perhaps some change in the osx toolchain or you've started using some symbols that you weren't using before?

**Comment by bakercp** [comment]
Hm.  I'll look into it.  How often are the osx libraries are re-compiled with CI? (i.e. those that are downloaded with `download_libs.sh`)?

**Comment by arturoc** [comment]
they are only built if there's any change in the apothecary server but the last change is from january 5th: https://github.com/openframeworks/apothecary/commits/master you can also check the date of the packages on the ci server: http://ci.openframeworks.cc/libs

**Comment by bakercp** [comment]
cool. thx.


---
http://christopherbaker.net

**Comment by bakercp** [comment]
This problem seems to have disappeared.  Not sure why, but I'll not ask questions.  ;)

https://travis-ci.org/bakercp/ofxHTTP/jobs/203639910
