### ISSUE TITLE
Regression in fullscreen in linux (0.9.8)

### ISSUE THREAD

**Issue by gorkacortazar** [openframeworks/openFrameworks#5454]
We are using this code for creating mutimonitor fullscreen windows on linux.

```
int main( ){
   ofGLFWWindowSettings settings;
   settings.height = 1080;
   settings.width = 1920;
   settings.multiMonitorFullScreen = true;
   settings.decorated = false;
   shared_ptr<ofAppBaseWindow> mainWindow = ofCreateWindow(settings);
   shared_ptr<ofApp> mainApp(new ofApp);
   ofRunApp(mainWindow, mainApp);
   ofRunMainLoop();
}
```
This code works perfectly in 0.9.3, and also in the current github master, if you call ofSetFullScreen(true) from the setup.

But with 0.9.8 in Linux (in windows works perfectly), after calling ofSetFullScreen(true) the application completely freezes. The mouse remains active, but you see an immediate drop in frame rate (form 60 to 49) and then the screen stops updating and the keyboard and mouse events stops working (system wide). I tried commenting the multi monitor full screen and the behavior is the same and I am unable to send mouse events or keyboard events to the operative system, even in a different window already open on my second screen. I am in Ubuntu 16.04.2 LTS.

I uploaded a minimal test case that calls ofSetFullScreen on a keypress here:
https://www.dropbox.com/s/1rc0tlfntgdn5rm/fullscreenTest.rar?dl=0

**Comment by gorkacortazar** [comment]
I spotted the change to this commit 96c71262b2c8cfe3a7b40174e20d5882d10cd79d, if the OSX ifdef are commented, the freeze doesn't occur.

@arturoc you did this change for solving other fullscreen issues in several windows managers, i just tried with openbox and the freeze also happens there.

Do you think that worth trying to fix it for 0.9.x?

**Comment by arturoc** [comment]
i don't think we'll do anymore 0.9 releases, 0.10 is almost done except for some issues

**Comment by gorkacortazar** [comment]
Ok, I'll take a look to the 0.10 implementation to see if I spot another issue in this area.. Thanks!
