### ISSUE TITLE
Window title disappears after toggling fullscreen

### ISSUE THREAD

**Issue by valillon** [openframeworks/openFrameworks#5463]
The window title set by `ofSetWindowTitle()` disappears after calling `ofToggleFullscreen()` to fullscreen (`OF_FULLSCREEN`) and then toggling back again (`OF_WINDOW`). Testing with OSX 10.12, Xcode 8.2.1 and OF 9.8.

**Comment by tgfrerer** [comment]
Tested with oF from git at revision fb2da472128fc3c77c33ccbf959d55241fe52709

* windows: can't reproduce
* macOs: bug confirmed
