### ISSUE TITLE
ofSerial device name not available on Windows

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/openFrameworks#5465]
I noticed that in the Windows implementation of `ofSerial`, the device name is never available, as both `getDevicePath()` and `getDeviceName()` return the same, "short" name of something like `COM3`. The full device name is available and correctly parsed at some point, but the descriptive portion is discarded. For example, `Silicon Labs CP210x USB to UART Bridge (COM3)` is never available as it is reduced to `COM3`.

The string handling is already in place as there are arrays for `portNamesShort` and `portNamesFriendly`, but the latter is never used. The change is minimal:
`devices.push_back(ofSerialDeviceInfo(string(portNamesShort[i]), string(portNamesShort[i]), i));
`
becomes
`devices.push_back(ofSerialDeviceInfo(string(portNamesShort[i]), string(portNamesFriendly[i]), i));`

I wanted to open this issue first to see if there was any reason this is the case before sending a PR? The change works for me, I'm able to open a port by its short name/path (`COM3`) and have access both to the path & description (name). I looked at the history of that portion of code, and it's been unchanged for at least 6 years 😆 
https://github.com/openframeworks/openFrameworks/blame/4a872404bcf4f11a5c99ed2a3fd62f7f721ffb87/libs/openFrameworks/communication/ofSerial.cpp#L218

**Comment by arturoc** [comment]
this sounds like a bug, feel free to send a PR
