### ISSUE TITLE
OSC Receiver example crashes if UDP port is already used

### ISSUE THREAD

**Issue by valillon** [openframeworks/openFrameworks#5467]
I found that `ofxOscReceiver` throws and exception if the UDP socket cannot be connected when the port is already busy by somebody else (another program). The `oscReceiveExample` does not catch that exception and then crashes.

I could update the current example to something like:

```cpp
    try {
        receiver.setup(PORT);
	ofLogVerbose() << "Listening osc messages on port " << PORT;
    } catch (std::runtime_error& error) { 
       string errorMessage = error.what(); 
       ofLogError(errorMessage) << "Failed connection to " << PORT << " port. Probably another program is using it";
    }
```

**Comment by danomatika** [comment]
This is fixed in the master branch from what I can tell. I'm doing an update of ofxOsc and ofxOscReceiver prints the exception as an error.

**Comment by valillon** [comment]
Nice, thanks!
