### ISSUE TITLE
drawStringAsShapes() different looking to original

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5468]
Hi, I just figured out some font's character can look different when drawing with drawStringAsShapes()
I used sansation.ttf font and as you can see, the 'x' character looks different.
There's an empty area in the cross section when drawing 'x' with drawStringAsShapes()

<img width="266" alt="f44fc78eb56ebac93cba640bfb973c9e1af3a416" src="https://cloud.githubusercontent.com/assets/24947986/23536220/d0376cec-0006-11e7-9ad5-9ebef74553f0.png">

I think this is a bug.  it probably just needs a change in the winding mode if the paths produced by oftruetypefont. 

I attached the font in case anybody wants to try it out.
[sansation.ttf.zip](https://github.com/openframeworks/openFrameworks/files/815685/sansation.ttf.zip)

And here's a posting I created on the forum.
https://forum.openframeworks.cc/t/drawstringasshapes-different-looking-to-original/25892

**Comment by arturoc** [comment]
That should fix it, if you can give it a try?

**Comment by cuinjune** [comment]
Yes, I tried and it works fine now. Thank you Arturo!
