### ISSUE TITLE
Downloads on web site out of date?

### ISSUE THREAD

**Issue by carloscastellanos** [openframeworks/openFrameworks#5477]
Hey guys I was having a problem compiling the examples for the ofxKinectForWindows2 addon and I think the issue is that the downloads for openFrameworks on the openFrameworks site are out of date (at least those for Visual Studio and XCode).

For example this is the error I get when I try to build:
![capture1](https://cloud.githubusercontent.com/assets/6315240/23685125/05fa317a-0368-11e7-8f8d-f6f00afba00f.PNG)

This is happening because the ofGraphics.h and .cpp files that I downloaded from the ofx site do not contain the ofRotateDeg() methods while the same files on the Github repo clearly do. As it stands now none of the ofxKinectForWindows2 examples will compile due to this error.  I think a workaround would be to download ofx directly from the GitHub repos and just add the VS project/solution files but it would be great to fix this so new ofx users (like me) do not get confused!

Thanks

**Comment by carloscastellanos** [comment]
Never mind i was looking at a dev, not release version of the code. Sorry!

**Comment by bakercp** [comment]
Yeah,
