### ISSUE TITLE
ofFile & ofDirectory std::string open() & constructor

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#5478]
I'm running into an issue with the ofxLua SWIG bindings and the std::filesystem::path type as used in ofFileUtils.h. Usually when wrapping types, SWIG needs to basically wrap the entire type in order to be able to translate between the scripting language and C++. From what I can tell, the std::filesystem::path type is mainly used internally and by the ofFile & ofDirectory open() & constructors. I'd rather avoid wrapping std::filesystem::path when a std::string would do &, so far, some fancy lower-level SWIG-fu is not working for me.

Couldn't we add the following which use simple std::strings and translate internally to the std::filesystem::path member var?:

    ofFile::ofFile(const string &path);
    bool ofFile::open(const string &path);
    
    ofDirectory::ofDirectory(const string &path);
    bool ofDirectory::open(const string &path);

**Comment by arturoc** [comment]
this is done like this so you can pass anything that represents a path into those functions, for example ofFile extends filesystem::path so you can list a directory get the files in it and pass them to open an image directly. or use any of the functions in std::filesystem and use the result to open anything in OF.

i think this is pretty useful but perhaps we could have an ifdef'd version using strings for this functions and a macro in ofConstants that allows to compile OF using one or the other

**Comment by danomatika** [comment]
So can std::string's be passed as std::filesystem::paths now? It's not a huge deal as I ended up making wrapper functions for SWIG which use explicit std::string types.

**Comment by arturoc** [comment]
yes, std::filesystem::path can be constructed from strings so you can still pass a string to any of the load/save functions

**Comment by danomatika** [comment]
No need for a define, etc. Simplest option for me, as suggest in first post, is to have explicit std::string overloads. But also not a big deal if not as I have it working with some simple wrappers: https://github.com/danomatika/swig-openframeworks/blob/master/openFrameworks.i#L1048

**Comment by arturoc** [comment]
the problem with overloads is that std::filesystem::path can be constructed from a strnig so haivng both versions would result in ambiguities, that's why i was suggesting to use overloads but ifdef'd. in any case if you've solved it already i think we can close this.
