### ISSUE TITLE
weird font to fbo with getStringBoundingBox() behavior

### ISSUE THREAD

**Issue by dmtth** [openframeworks/openFrameworks#5482]
I have this weird issue when i draw some text into an fbo with the following code:

   ```
    string someText = "yoYOyo";
    verdana14.load("verdana.ttf", 28, true, true);
    bounds = verdana14.getStringBoundingBox(someText, 0, 0);
    fbo1.allocate(bounds.width, bounds.height);
    fbo1.begin();
    ofClear(255,0,255,255);
    ofSetColor(0);
    verdana14.drawString(someText, 0, bounds.height);
    fbo1.end();
```

and i get this:
![screenshot 2017-03-14 01 41 58](https://cloud.githubusercontent.com/assets/4683230/23880982/8216ef20-0857-11e7-90b3-1255d4c22f4b.png)

instead of this:
![screenshot 2017-03-14 01 42 19](https://cloud.githubusercontent.com/assets/4683230/23880990/8d9c5ef2-0857-11e7-894f-98ece96948cc.png)

Could somebody tell me what am i missing here to make it right?

**Comment by ofZach** [comment]
getStringBoundingBox also returns x,y which is the offset from the position you pass in (0,0) -- in your case, your string descends so you will need to shift it up (using bounds.y) when you draw it to position it right in the fbo....  AFAIK the behaviour is correct it's just that your string has got descenders so you need to consider the offset of the box from the 0,0 position you are trying to draw at...

**Comment by ofZach** [comment]
ps: in other words, even though you say "get bounding box if I draw string at (0,0)" you are not guaranteed a box that starts at (0,0), just a box that completely contains the text...  here, you are drawing into the FBO assuming the box starts at (0,0)....

**Comment by adamtth** [comment]
thanks! using bounds.y instead of bounds.height it is working now just as expected.
