### ISSUE TITLE
installation process via Terminal unable to find libgl1-mesa-dev-hwe-16.04

### ISSUE THREAD

**Issue by CreArtCom** [openframeworks/openFrameworks#5495]
Hello,

I'm get issues with OF install process on ubuntu 16.04.
I've installed curl but next step I get this from the console:
```
Couldn't find any package ny glob 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04
this seems an error with your distribution repositories but you can also report an issue in the openFrameworks github: https://github.com/openframeworks/openFrameworks/issues
```
Is there anything I can do here?
Any help would be great, I'm starting with of ...

**Comment by arturoc** [comment]
can you try updating all your packages before installing OF:

```
sudo apt dist-upgrade
```

**Comment by CreArtCom** [comment]
Okay, this is done, Thanks.
But I still get the same message in the Terminal:
-
Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04
this seems an error with your distribution repositories but you can also report an issue in the openFrameworks github
...
-
 
What is that package? Is there a way to install it manually.
Any help would be appreciated.

**Comment by CreArtCom** [comment]
Okay, this is done, Thanks.
But I still get the same message in the Terminal:
-
Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04
this seems an error with your distribution repositories but you can also report an issue in the openFrameworks github
...
-
 
What is that package? Is there a way to install it manually.
Any help would be appreciated.

**Comment by danzeeeman** [comment]
It is listed in ubuntu xenial repos 
https://launchpad.net/ubuntu/xenial/+package/libgl1-mesa-dev

Is this a fresh installation of ubuntu?

**Comment by CreArtCom** [comment]
Yes indeed thanks! And Yes this is a recent install of ubuntu.
My configuration is amd64:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
-
I've dowloaded this file from your link: 
libgl1-mesa-dev 12.0.6-0ubuntu0.16.04.1 (amd64 binary) in ubuntu xenial

Here is what I get after sudo ./install_dependencies
-
Installing libgl1-mesa-dev-hwe-16.04
E: Impossible de trouver le paquet libgl1-mesa-dev-hwe-16.04
E: Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « libgl1-mesa-dev-hwe-16.04 »
error installing libgl1-mesa-dev-hwe-16.04
Lecture des listes de paquets… Construction de l'arbre des dépendances… Lecture des informations d'état…
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues
-

**Comment by arturoc** [comment]
this seems to be a problem in ubuntu itself, it'll probably get solved but you can also post in their issue tracker.

btw, using `-` to separate paragraphs is making all your text really big i've edited your previous posts but please use a triple backtick or simply indent by four spaces instead to mark code blocks

**Comment by danzeeeman** [comment]
I wonder if he needs to enable these checkboxes?

![image](https://cloud.githubusercontent.com/assets/719564/24008677/b1439aa8-0a48-11e7-962a-e3f1b7db9820.png)

[Or follow this process to restore the default repositories?](http://askubuntu.com/questions/124017/how-do-i-restore-the-default-repositories)

Might be using different repositories in the source.list?

Can we close this bug as it really isn't an OF bug?

**Comment by CreArtCom** [comment]
Thanks guys for your help.
@arturoc : okay for the minus sign that make monster letters :( and sorry, I understand know ...
Do you know where is that Ubuntu issue tracker where I can post about that issue ?
@danzeeeman : where can I find that window "Software Sources" ?
We can close just after those last answers?
Thx.

**Comment by CreArtCom** [comment]
One more thing. I've installed the file listed in ubuntu xenial repos
https://launchpad.net/ubuntu/xenial/+package/libgl1-mesa-dev
Please see attached.
Should I do something to tell my computer where is that file (or something) during the installation process with install_dependencies ...? 
![libgl1-mesa-dev](https://cloud.githubusercontent.com/assets/1799399/24012130/37a44442-0a7d-11e7-8ed6-e8b5620d9410.png)

**Comment by CreArtCom** [comment]
Hello,
I had good help here [http://askubuntu.com/questions/893756/terminal-cant-install-something-named-libgl1-mesa-dev-hwe-16-04](http://askubuntu.com/questions/893756/terminal-cant-install-something-named-libgl1-mesa-dev-hwe-16-04)
and indeed the problem comes from ubuntu depos.
