### ISSUE TITLE
Ubuntu 16.04.2 LTE HWE packages cannot be found

### ISSUE THREAD

**Issue by alberto2000** [openframeworks/openFrameworks#5496]
> Installing libgl1-mesa-dev-hwe-16.04
E: Unable to locate package libgl1-mesa-dev-hwe-16.04
E: Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
E: Couldn't find any package by regex 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04

I found this thread on Stack Exchange: http://askubuntu.com/questions/893756/terminal-cant-install-something-named-libgl1-mesa-dev-hwe-16-04

How can this be fixed? Did the package move to another repository?

**Comment by arturoc** [comment]
This has already been reported by the same person that posted in ask ubuntu, we've closed it cause it's not an openframeworks problem but an ubuntu one. there's nothing we can do, you can probably report it in ubuntu's launchpad: https://bugs.launchpad.net/ubuntu
