### ISSUE TITLE
ofHexToFloat() return 0.000000?

### ISSUE THREAD

**Issue by BentleyBlanks** [openframeworks/openFrameworks#5505]
Here is the code:

```cpp
// The number was from ofUtils.h's annotations(of 0.9.8 line 704)
// Testing Platform: Windows 7, Visual Studio 2015
printf("%f\n", ofHexToFloat("4060000000000000"));
```
And it always return ```0.000000```. Is the way to call the function right ?

**Comment by arturoc** [comment]
yes there seems to be some bug with this function, i'll look into it.

also if what you really need is to write a number in hex you don't need this function you can just do:

```
float a = 0xae1620;
```

**Comment by arturoc** [comment]
was testing this a bit more and it seems there's just a documentation problem. the docs say 4060000000000000 is 128 but that gives nan, doing the operation in the reverse order i get that 43000000 is 128

i wonder if this is a 32bit vs 64bit problem and i have changed some things internally to make sure that the integer used is always 32bit but as far as i understand this was just a documentation problem

**Comment by BentleyBlanks** [comment]
Thx a lot ! I'm not familiar with Hex number~And the 43000000 is works now~
