### ISSUE TITLE
Incorrect use of 'normalized' argument in glVertexAttribPointer

### ISSUE THREAD

**Issue by Ahbee** [openframeworks/openFrameworks#5508]
In the documentation it says

> For glVertexAttribPointer, if normalized is set to GL_TRUE, it indicates that values stored in an integer format are to be mapped to the range [-1,1] (for signed values) or [0,1] (for unsigned values) when they are accessed and converted to floating point. Otherwise, values will be converted to floats directly without normalization.

so it should not have any effect on floats attributes

openframeworks  seems to think it will normalize normals

```
void ofVbo::setNormalData(const float * normal0x, int total, int usage, int stride) {
	// tig: note that we set the 'Normalize' flag to true here, assuming that mesh normals need to be
	// normalized while being uploaded to GPU memory.
	// http://www.opengl.org/sdk/docs/man/xhtml/glVertexAttribPointer.xml
	// Normalizing the normals on the shader is probably faster, but sending non-normalized normals is
	// more prone to lead to artifacts difficult to diagnose, especially with the built-in 3D primitives.
	// If you need to optimise this, and you've dug this far through the code, you are most probably
	// able to roll your own client code for binding & rendering vbos anyway...
	normalAttribute.setData(normal0x, 3, total, usage, stride);
	normalAttribute.normalize = true;
	enableNormals();
}
```

either way I think the correct behavior should be to not change any data that the user sends to the vbo. If he wants to normalize attributes then let him, but dont do it for him.

**Comment by arturoc** [comment]
that makes sense, i've just removed it. thanks!
