### ISSUE TITLE
ofxOsc: Uncaught exception for malformed messages

### ISSUE THREAD

**Issue by valillon** [openframeworks/openFrameworks#5514]
I'm currently working with a buggy server which turns out to be sending corrupt messages. An exception is thrown by `oscpack` if the received OSC message is malformed. Unfortunately `ofxOsc` is not catching that exception so the app crashes. By catching the exception the crash goes away, but then the socket gets frozen. So I temporary solved it by making the receiver to send an event saying "hello I was in trouble with this socket so you better setup again".

```cpp
class ofxOscReceiver : public osc::OscPacketListener
{
public:
    ofEvent<void> onSocketNeedsRestart;
    //...
}
```
```cpp
void ofxOscReceiver::setup( int listen_port )
{
   //...
   listen_thread = std::thread([this]{
      try { listen_socket->Run(); }
      catch (osc::MalformedMessageException& error) 
      {
         ofLogWarning("Malformed OSC message") << error.what();
         ofNotifyEvent(onSocketNeedsRestart);
         return;
      }
   });
   //..
}
```

Then the app just needs to setup the receiver again every time it listens the broadcasted event.

```cpp
void ofApp::setup()
{
   // ofxOscReceiver receiver;
   ofAddListener(receiver.onSocketNeedsRestart, this, &ofApp::startReceiver);
   //...
}
void ofApp::startReceiver()
{
    inPort = DEFAULT_OSC_INPORT;
    try {
        receiver.setup(inPort);
        ofLogNotice(LOG_OSC) << "Starting receiver: listening from in-Port " << inPort;
    }
    catch (std::runtime_error& error) { ofLogNotice(LOG_OSC) << error.what(); }
}
```
That worked out, but temporarily because `listen_thread` seems not being killed after catching and every time `ofxOscReceiver::setup()` is re-called a new thread for a new socket receiver is created.
BTW testing with OSX 10.12.3 Xcode 8.2.1.

Any clue?

**Comment by bakercp** [comment]
@danomatika would you be willing to take a look at this?

**Comment by bakercp** [comment]
I think it may be fixed in https://github.com/openframeworks/openFrameworks/pull/5476 in master.  @valillon would you be able to test this using the master branch and @danomatika recent overhaul?

**Comment by danomatika** [comment]
@valillon if you want to test with current OF release, simply copy out the ofxOsc src folder from th OF master branch into your local copy of ofxOsc.

**Comment by valillon** [comment]
Solved!

ofxOSC now catches exceptions on malformed messages, sends a console warning and the Receiver keeps receiving. Tested on the commit a6bfb9a1ab76bce4d41dd2d01a7ac62e8f570a95.

Thanks you both @bakercp and @danomatika.
