### ISSUE TITLE
[ error ] ofDirectShowPlayer: Cannot load video of this file type

### ISSUE THREAD

**Issue by AndrewGentile** [openframeworks/openFrameworks#5517]
I'm new to OF and was trying to create a simple video player based on this page: http://openframeworks.cc/learning/03_video/how_to_load_and_play_a_video/1

I have tried using multiple .mp4 files and an .avi file but keep getting this error:

Error occured while playing or pausing or opening the file
[ error ] ofDirectShowPlayer: Cannot load video of this file type. Make sure you have codecs installed on your system. OF recommends the free K-Lite Codec pack.

I am using Windows 10, OF 0.9.8, Visual Studio 2015, and downloaded K-Lite Codec pack 12.1.0. I looked at some other forums but couldn't find any solutions.

**Comment by baskeboler** [comment]
Had this same problem and the solution was copying the mp4 file to data/ in
the same folder where the executable is.

**Comment by AndrewGentile** [comment]
That fixed it, thanks!
