### ISSUE TITLE
function signature passed to ofxButton via .addListener requires bool argument for macOS and void for Windows

### ISSUE THREAD

**Issue by caedn** [openframeworks/openFrameworks#5527]
On macOS I'm using the latest git version of openFrameworks (2408fef) on Windows of_v0.9.8_msys2_release.

I'm declaring an ofxGui button in my .h:
```
ofxButton button;
```

In my .cpp I'm adding a listener to it:
```
gui.add(button.setup("click me!"));
button.addListener(this, &ofApp::buttonPressed);
```

The problem is that to successfully compile on macOS the function signature has to be
```void buttonPressed(bool &buttonState);``` but for Windows it has to be ```void buttonPressed(void);```.

**Comment by arturoc** [comment]
this was a bug recently introduced it should be fixed now. thanks!
