### ISSUE TITLE
ofXml::loadFromBuffer in documentation, but not in source code

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#5554]
I was looking for a way to load data from ofBuffer to ofXml and found this function: http://openframeworks.cc/documentation/utils/ofXml/#show_loadFromBuffer But ofXml does not appear to include such a function. I guess the documentation needs to be updated, but I also would really like to use this function. Do I have to do that with ofxXmlSettings or is there another way in ofXml?

**Comment by arturoc** [comment]
is this with 0.9.8 or master? ofXml has changed quite a bit in master and this function is porbably missing but should be pretty straight forward to bring it back

**Comment by frauzufall** [comment]
I am using the master branch. Is the documentation (http://openframeworks.cc/documentation/utils/ofXml/) related to master or to the last release version? It refers to the old version. 

I added the function and filed a PR, please have a look :)

**Comment by bakercp** [comment]
Fixed w/ #5555
