### ISSUE TITLE
Feature request: ofGetLoggerChannel() / ofLog::getChannel()

### ISSUE THREAD

**Issue by daniel-at-yoke** [openframeworks/openFrameworks#5558]
There's no way to retrieve the currently-set logger channel - only a setter, no getter.

A getter would be very nice, if, for instance, you want use a custom logger to that _also_ forwards calls to whatever channel's already set. E.g. it'd allow something like this:

```
shared_ptr<CustomLoggerChannel> channel(new CustomLoggerChannel);
channel->setForwardingChannel(ofGetLoggerChannel()); // forward to existing channel
ofSetLoggerChannel(channel);
```

**Comment by bakercp** [comment]
This seems like a reasonable request -- do you want to submit a PR?
