### ISSUE TITLE
ofxPoco linking with ofxHttpUtils error

### ISSUE THREAD

**Issue by hardjob** [openframeworks/openFrameworks#5574]
I tried to compile an app which use ofxHttpUtils , but i got this error addons/ofxHttpUtils/src/ofxHttpUtils.h:18:50: fatal error: Poco/Mutex.h No such file or directory

i'm using the current openframeworks-master version

**Comment by bakercp** [comment]
Did you include ofxPoco in your addons.make file?

**Comment by bakercp** [comment]
This os fixed with https://github.com/openframeworks/openFrameworks/pull/5616
