### ISSUE TITLE
[FEATURE REQUEST] tweaking memo akten open frameworks tensor flow implementation

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5578]
<h1>Greetings, awesome crowd of open frameworks community</h1>

_Memo akten has made an awesome implementation of a tensor flow add-on for open frameworks. that's a really an awesome thing, although I think, on my standing point, that its installation should rely on the overall path to python installation of open frameworks in your system. shall we fix this together?_
 
**shared with love:**
**Tiago**

**Comment by bakercp** [comment]
Interesting ideas.  I think these feature request discussions would probably be a better fit on the openFrameworks forum, rather than posted as an issue.

**Comment by bakercp** [comment]
Generally these would be implemented as openFrameworks addons, like those indexed here http://ofxaddons.com.
