### ISSUE TITLE
[FEATURE REQUEST] implementing a deep convolutional recursive swarm of hybrid bdi and Ann in openframeworks

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5579]
<h1>Greetings</h1>

<h2>it would be interesting if we could:</h2>
- <I>implement a deep convolutional recursive swarm of hybrid bdi and Ann in openframeworks</I>
<br/><br/>
<b>Shared with love<br/>
T.</b>

**Comment by danzeeeman** [comment]
Please only post real issues. Use the OF form for these types of requests/nice to have/discussions

**Comment by bakercp** [comment]
Generally these would be implemented as openFrameworks addons, like those indexed here http://ofxaddons.com.
