### ISSUE TITLE
[FEATURE REQUEST] Making an ofx add-on for importing cinema 4d project files straight into ofx

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5580]
<h1>Hey Guys</h1>

<I>It would be super duper really rubber leaker grotte gedanke fantasticwhen if we could have, within sense, create an open frameworks add-on for importing cinema 4d project files straight into open frameworks</I>

<b>Shared with love<br>
T.</b>

**Comment by tiagmoraismorgado** [comment]
and not only cinema 4d, but also other 3d modeling environments. the reason why I point out cinema 4d, is that it seems for me the one which has an aesthetic that aligns the most with open frameworks one.

peace
T.

**Comment by bakercp** [comment]
Generally these would be implemented as openFrameworks addons, like those indexed here http://ofxaddons.com.
