### ISSUE TITLE
"missing separator" error in config.addons.mk for addon with addon_config.mk file

### ISSUE THREAD

**Issue by frauzufall** [openframeworks/openFrameworks#5582]
Since a few days (probably after this commit https://github.com/openframeworks/openFrameworks/commit/a1222458669ea477c500428d86f4818c7ec3bac5) I cannot compile ofxCv. I get this error:
```
/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: *** [Debug] Error 2
```
I tried different addons and I only get this error when using `ofxCv`. The addon uses its own `addon_config.mk` file. If I rename this file, the error is not thrown. Since I did not update the addon and it was working with the OF master about 2 weeks ago I thought I should post this here.

**Comment by arturoc** [comment]
can you check if there's any spaces at the beginning of any line in the addon_config.mk for that addon? makefiles don't support spaces and have to use tabs instead.

**Comment by frauzufall** [comment]
Thanks for answering! No, I cannot find a space there (https://raw.githubusercontent.com/kylemcdonald/ofxCv/master/addon_config.mk), but in the depending addon ofxOpenCv.. I filed a PR (https://github.com/openframeworks/openFrameworks/pull/5584). But the error is still remaining.

**Comment by frauzufall** [comment]
Found a workaround that may point to the problem. `ofxCv` depends on `ofxOpenCv`. With the current master I have to add both to `addons.make`, before commit https://github.com/openframeworks/openFrameworks/commit/a1222458669ea477c500428d86f4818c7ec3bac5 I could just use `ofxCv`...

**Comment by arturoc** [comment]
yeah that can be useful to figure out what's going on. thanks!

**Comment by ThomasLengeling** [comment]
I think I had the issue as franzufal, I added ofxOpenCv before ofxCv in the addons.make and that fix it

**Comment by armadillu** [comment]
I'm running into this when trying to add CI to some of my addons. It's super weird bc it happens only on a few, and I can't tell how are they different from others in which it all works. It goes as far as working on some of the examples of a particular addon, but fail for other examples.

As an example, [ofxAnimatable](http://github.com/armadillu/ofxAnimatabe) compiles fine the 1st two examples, but fails on the third (example-AnimationQueue) with the same error. See more here: https://travis-ci.org/armadillu/ofxAnimatable/jobs/257154137

```
/home/travis/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory `/home/travis/openFrameworks/addons/ofxAnimatable/example-CurveParameters'
make: *** [DebugNoOF] Error 2
```

By trial and error, I realised that as soon as one of those examples gets [ofxRemoteUI](http://github.com/armadillu/ofxRemoteUI) as a dependency, it triggers the error, so I am in the process of trying to see what's causing it. Will post more as I find out.

**Comment by armadillu** [comment]
So, in my case, it turns out that just adding the addon in "addons.make" will create this issue if mentioned addon has dependencies of its own. 

So for example, if my project uses ofxRemoteUI, I must add ofxRemoteUI and ALL the addons depends on (ofxPoco, ofxXmlSettings, ofxOsc)  to my "addons.make", otherwise it will trigger this "missing separator" issue.

**Comment by bakercp** [comment]
Confirming that I am also getting this issue.

**Comment by bakercp** [comment]
Basically, this is preventing us from relying on the `ADDON_DEPENDENCIES` field in the `addon_config.make` file.  On a related note the project generator also does not respect the `ADDON_DEPENDENCIES` flag - see:

https://github.com/openframeworks/projectGenerator/issues/30
https://github.com/openframeworks/projectGenerator/issues/127
https://github.com/openframeworks/projectGenerator/pull/90

**Comment by armadillu** [comment]
My workaround to this has been explicitly cloning addons in the ci script of addons that I know rely on 3rd party addons;

as an example:

ofxAnimatable doesn't depend on any other addons, but its some of its examples have dependencies. 

OF addons ci allows for addons to provide their custom script which is exectuted before the ci build, in `addonRepo/scripts/ci/install.sh` (and `addonRepo/scripts/ci/vs/install.sh`for VisualStudio or custom per-platform scripts)

So I just use that chance to preemptively clone all the addons I know will be required. If the addons are there, the `addons.make` "missing separator" error doesn't show up. I spend uncountable hours on that error, it just happens to be really hard to debug the makefiles as the log printing doesn't necessary stop where the errors happens, especially on makefiles calling other scripts.

https://github.com/armadillu/ofxAnimatable/blob/master/scripts/ci/install.sh

**Comment by armadillu** [comment]
Yep I forgot to mention, I also add the addons dependencies in each example's `addons.make`, but for that to work they must be cloned into the addons folder first (by using the scripts I mentioned before). So many moving parts! And yeah the slow reaction times of Ci can really wear you down. I alleviated some of the debug pains with local docker images, but still...

**Comment by kflak** [comment]
I started getting this error today for some reason I haven't been able to fathom: I didn't change a single thing in my oF-workspace, and all of a sudden I can't build anything that contains an addon_config.mk file. I am on Arch Linux. Running the scripts/linux/install_dependencies.sh I was getting this error at the end: 
```
sed: can't read /addons/ofxOpenCv/addon_config.mk: No such file or directory`
```
so I had to remove $ROOT from line 22:
```
addons_dir="$(readlink -f "../../../addons")"
```
which seemed to do the trick, but unfortunately the problem persists. I was using of_v0.11.0_linux64gc6 when it started happening, and now I'm attempting to get it to work on of_v20200208_linux64gcc6_nightly.

So, to repeat: any addon without an addon_config.mk file works, and addon with one gives me something like this: 
```
Compiling kinectExample for Release
make[1]: Entering directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
/home/kf/of_v20200208_linux64gcc6_release//libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
make: *** [/home/kf/of_v20200208_linux64gcc6_release//libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

**Comment by slzatz** [comment]
@kflak thanks much for this solution which I had already spent hours on before I saw your post.  Arch did upgrade make to version 4.3 in the last week or so and downgrading as you suggested fixed the problem for me too.

**Comment by kflak** [comment]
@slzatz Much obliged :-) took me a day to figure it out, so happy if that will save other people’s time. This is not so much a fix as a temporary workaround, unfortunately. Hopefully the capable of devs will find a solution soon, I’m a bit worried about disturbing the delicate ecosystem of Arch dependencies by having an out-of-date make in my box.

**Comment by slzatz** [comment]
This is probably in the category that I should know the answer to this but when make was at version 4.3 on my Arch system, I could still compile code with qt creator and standard OF .qbs file while invoking make directly from the command line didn't work until I downgraded the system version of make.  Doesn't the qt creator tool chain eventually call the system's make executable?

**Comment by kflak** [comment]
No idea, really. I’m just getting started with cpp in general and of in particular, and I have a strong aversion against leaving my very comfortable nvim development environment ;-)

**Comment by FlashBlaze** [comment]
@kflak how did you downgrade? I downloaded the stable version of oF which does not contain projectGenerator. So I cloned the repo and since it requires commandLine to work, I need to compile it. But I cannot due to make version being 4.3.
Thanks

**Comment by kflak** [comment]
I used the downgrade utility in Arch Linux. Can’t remember if it’s in AUR or community repo atm

**Comment by FlashBlaze** [comment]
@kflak I was able to compile the commandLine, but it doesn't work. I mean, the `.exe` is generated but nothing happens when I execute it. The same goes for electron app. It generated the windows build with `$npm_package_productName.exe` name and I also get this error

`Command failed: C:\WINDOWS\system32\cmd.exe /s /c ""D:\of_v0.11.0_msys264_release\apps\projectGenerator\frontend\dist\$npm_package_productName-win32-ia32\resources\app\app\projectGenerator"  -o"D:\of_v0.11.0_msys264_release\" -a" " -p"osx,vs" -t"msys2" "D:\of_v0.11.0_msys264_release\apps\myApps\myProject""`

**Comment by kflak** [comment]
No idea, really. Haven’t poked around in a Windows for 20 years or so.

**Comment by FlashBlaze** [comment]
Dropped the project generator completely. Lol. Going `cmake` all the way.

**Comment by sphaero** [comment]
This is fixed in patch-release but not in master. How does this flow to master?

**Comment by arturoc** [comment]
just pulled patch-release into master, thanks for the hint. going to close this then
