### ISSUE TITLE
[FEATURE REQUEST] porting id tech 4 and 5 to open frameworks

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5583]
<h1>gente bonita da comunidade de openframeworks </h1>
<h2>joyeux personnes dans la communité d'utiliseurs du open frameworks</h2>

<b>it would  would be awesome if, within sense, we could</b>
- <I>port id tech 4 and 5 to open frameworks,</I>

<b>shared with love
T.</b>

**Comment by bakercp** [comment]
Interesting ideas.  I think these feature request discussions would probably be a better fit on the openFrameworks forum, rather than posted as an issue.

**Comment by bakercp** [comment]
Generally these would be implemented as openFrameworks addons, like those indexed here http://ofxaddons.com.
