### ISSUE TITLE
[FEATURE REQUEST] adding an app to download addons

### ISSUE THREAD

**Issue by tiagmoraismorgado** [openframeworks/openFrameworks#5585]
_Pd has deken. Supercollider has QuarksGui. Processing has also something similar. So, why shouldn't open frameworks have like an app to download a list of pre-existing addons to your openframewroks installation?_

**shared with love**

**Comment by tiagmoraismorgado** [comment]
posted to forum as well

**Comment by bakercp** [comment]
It's a great idea that lots of people have thought about and worked on.  I'll post some links on the forum and close this issue.  Forum link here https://forum.openframeworks.cc/t/adding-an-application-to-download-addons-automatically-from-centralized-source-i-e-github/26659
