### ISSUE TITLE
ofSetFullscreen() Broken On Linux 64 Again

### ISSUE THREAD

**Issue by toliaferrode** [openframeworks/openFrameworks#5597]
Hello,

Just tried ofSetFullscreen(true) on Linux 64 and it seems to be broken again as it does nothing. Works just fine on the Raspberry Pi/Arm 6, though.

**Comment by hamoid** [comment]
In git master?

**Comment by toliaferrode** [comment]
Oh no, I forgot to include version. 0.9.8 from the site. Thank you very
much.

On May 11, 2017 4:06 PM, "Abe Pazos" <notifications@github.com> wrote:

In git master?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openframeworks/openFrameworks/issues/5597#issuecomment-300902139>,
or mute the thread

**Comment by bakercp** [comment]
A few questions / comments:
- What is `Linux 64` (is this a custom distro?)
- You said it is broken again.  Can you provide a link to the previous issue to help cross reference?
- Raspberry Pi uses a completely different custom window system, whereas Linux and most other desktop platforms use GLFW.
- If you use a nightly build of openFrameworks does the issue persist?

**Comment by toliaferrode** [comment]
@bakercp Hi.

- I was referring to Linux 64 as the openFrameworks distribution for Linux 64-bit (as opposed to 32-bit) from the oF site.
- I don't have the issue on hand, but I posted one last year about this. I tried searching "fullscreen linux" in closed issues but it didn't come up.
- Indeed, true.
- Ah, I see.
- I'll try the nightly build. Last time that actually worked while the distribution from the site didn't work.

**Comment by bakercp** [comment]
Super.  Keep us posted.

**Comment by toliaferrode** [comment]
@bakercp Sorry about the delay.

I just tried the nightly build and it is not working there either.

**Comment by hamoid** [comment]
I'm using master from Dec 29th, 2016 and it works fine on ArchLinux on an i7 laptop with Intel 4600 integrated graphics. 

I added ofSetFullScreen(true); inside keyPressed() and it does what it should.

**Comment by toliaferrode** [comment]
@hamoid Ah, interesting! It must be something to do with Ubuntu then. About GLFW being out of date. Ubuntu is known for having woefully out of date packages for some things.

**Comment by bakercp** [comment]
You might try this fix as well: 

https://github.com/openframeworks/openFrameworks/issues/5507

**Comment by arturoc** [comment]
what ubuntu version are you using? this is working for me without problem in 17.04 and don't remember it was ever broken in any recent version

**Comment by toliaferrode** [comment]
@arturoc Oh duh, I'm using an out of date version of Ubuntu. I don't want to upgrade and risk my development system going down. I'm going to upgrade when I get a new computer.

Sorry about all this everyone!
