### ISSUE TITLE
ofJson.h is not on the last release

### ISSUE THREAD

**Issue by juanitoddd** [openframeworks/openFrameworks#5607]
Hello guys and girls,
Seems like ofJson.h is not included under /libs/openFrameworks/utils
Is this on purpose ? Cant compile a ofxAddon because of it.
Much respect and love

**Comment by bakercp** [comment]
ofJson is not included in 0.9.* but will be included in 0.10.+. Perhaps
leave an issue with the soon creator to make a note of the requirement in
their readme?

**Comment by juanitoddd** [comment]
Thank you ;)
I will

**Comment by VVZen** [comment]
Hi guys, I hope this is the right place to write down this.
@bakercp There's the ofxPS3EyeGrabber that still includes this ofJson.h file.
Can it be substituted with ofxJSON.h?
Thanks

**Comment by bakercp** [comment]
You can't substitute.

@VVZen if you're trying to use ofxPS3EyeGrabber with the last stable release of openFrameworks (see the README), then use the stable branch of the addon.  There have been significant improvements in the addon lately though, so I'd recommend using the OF master branch with the master branch of openFrameworks.

**Comment by 2bbb** [comment]
@juanitoddd 
ofxJsonUtils what i wrote includes ofJson (a.k.a. nlohmann::json) and maybe it is compatible of0.10.
if you interest, please use it.
