### ISSUE TITLE
this seems an error with your distribution repositories but you can also report an issue in the openFrameworks github:

### ISSUE THREAD

**Issue by ibouvousaime** [openframeworks/openFrameworks#5610]
Hello, 

I wanted to install OpenFrameworks on my ubuntu 16.04 pc but when I try launch the script to install dependencies on the ubuntu folder I get this error "this seems an error with your distribution repositories but you can also report an issue in the openFrameworks github:"

here is the full log btw : 

[result.txt](https://github.com/openframeworks/openFrameworks/files/1006124/result.txt)

**Comment by bakercp** [comment]
This appears to be a duplicate issue as indicated by this line in your errors:

```
Installing libxxf86vm-dev
 Already installed
Installing g++
 Already installed
Installing libgl1-mesa-dev-hwe-16.04
error installing libgl1-mesa-dev-hwe-16.04
```

Please see these issues:

https://github.com/openframeworks/openFrameworks/issues/5495
https://github.com/openframeworks/openFrameworks/issues/5496
