### ISSUE TITLE
Ambiguous << operator when using glm::ivec

### ISSUE THREAD

**Issue by prisonerjohn** [openframeworks/openFrameworks#5621]
Not sure if this is a glm or OF thing...

This works:
```
auto thing = glm::vec3(0.0f);
cout << thing << endl;
```
but this doesn't:
```
auto thing = glm::ivec3(0);
cout << thing << endl;
```

Error is:
```
more than one operator "<<" matches these operands:
            function "glm::operator<<(std::ostream &os, const glm::vec3 &vec)"
            function "glm::operator<<(std::ostream &os, const glm::vec2 &vec)"
            operand types are: std::ostream << glm::ivec3
```

I'm on master 3ae16bcc65afdf51bc0e1617a66293a18c2013ef with glm at 0.9.8.0. This is in Visual Studio 2015.

**Comment by arturoc** [comment]
just to clarify that this was working until now, it's something that has broken when updating glm to 0.9.8.0

**Comment by bakercp** [comment]
It's an OF issue.  glm is tightening up their types.  I'll PR a fix in a minute.

**Comment by bakercp** [comment]
Just pushed a fix.  If tests pass I'll merge it.  In the mean-time @prisonerjohn, feel free to pull the PR and test it locally.

**Comment by bakercp** [comment]
Also, we're currently on gml 0.9.8.4.

**Comment by bakercp** [comment]
... which fixed a ton of warnings etc, but also brought some changes to the way GLM handles swizzling / explicit construction, etc.

**Comment by bakercp** [comment]
@prisonerjohn can you confirm that my commit fixed your issue?

**Comment by prisonerjohn** [comment]
just tested, yes it did. thanks!
