### ISSUE TITLE
Wrong viewport after calling ofSetOrientation() while in Landscape device orientation

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5627]
When I try to change orientation by using ofSetOrientation(), it works well if I do it while the device is in a Portrait orientation(OF_ORIENTATION_DEFAULT or OF_ORIENTATION_180).

But if I call ofSetOrientation() while the device is in a Landscape orientation(OF_ORIENTATION_90_LEFT or OF_ORIENTATION_90_RIGHT), the viewport gets in a wrong position.

Here's a simple example code you can test.
If you touch the screen, the orientation changes in a clockwise order.

in main.mm

make sure to enable hardware orientation as below.

```c++
settings.enableHardwareOrientation = true; // enables native view orientation.
settings.enableHardwareOrientationAnimation = false; // enables native orientation changes to be
```

in ofApp.mm, copy the following implementations respectively.
```c++

//--------------------------------------------------------------
void ofApp::draw(){
	
    ofSetBackgroundColor(0);
    ofSetColor(255, 255, 255);
    ofNoFill();
    const int offset = 100;
    ofDrawRectangle(offset, offset, 0, ofGetWidth()-offset*2, ofGetHeight()-offset*2);
    ofDrawBitmapString("TOP LEFT CORNER", offset, offset);
}

//--------------------------------------------------------------
void ofApp::touchDown(ofTouchEventArgs & touch){

    switch (ofGetOrientation()) { //change orientation in a clockwise order
            
        case OF_ORIENTATION_DEFAULT:
            cout << "OF_ORIENTATION_90_RIGHT" << endl;
            ofSetOrientation(OF_ORIENTATION_90_RIGHT);
            break;
        case OF_ORIENTATION_180:
            cout << "OF_ORIENTATION_90_LEFT" << endl;
            ofSetOrientation(OF_ORIENTATION_90_LEFT);
            break;
        case OF_ORIENTATION_90_LEFT:
            cout << "OF_ORIENTATION_DEFAULT" << endl;
            ofSetOrientation(OF_ORIENTATION_DEFAULT);
            break;
        case OF_ORIENTATION_90_RIGHT:
            cout << "OF_ORIENTATION_180" << endl;
            ofSetOrientation(OF_ORIENTATION_180);
            break;
        default:
            break;
    }
}

//--------------------------------------------------------------
void ofApp::deviceOrientationChanged(int newOrientation){

    switch (newOrientation) {
            
        case OF_ORIENTATION_DEFAULT:
            cout << "OF_ORIENTATION_DEFAULT" << endl;
            ofSetOrientation(OF_ORIENTATION_DEFAULT);
            break;
        case OF_ORIENTATION_180:
            cout << "OF_ORIENTATION_180" << endl;
            ofSetOrientation(OF_ORIENTATION_180);
            break;
        case OF_ORIENTATION_90_LEFT:
            cout << "OF_ORIENTATION_90_LEFT" << endl;
            ofSetOrientation(OF_ORIENTATION_90_LEFT);
            break;
        case OF_ORIENTATION_90_RIGHT:
            cout << "OF_ORIENTATION_90_RIGHT" << endl;
            ofSetOrientation(OF_ORIENTATION_90_RIGHT);
            break;
        default:
            break;
    }
}
```
And here are screenshots.
If you run the app, it looks like this. (orientation : OF_ORIENTATION_DEFAULT)
![img_0359](https://cloud.githubusercontent.com/assets/24947986/26310268/3169b18c-3f3b-11e7-82f9-9ddb496637c8.jpg)

When you touch the screen, if will be changed to OF_ORIENTATION_90_RIGHT.
![img_0360](https://cloud.githubusercontent.com/assets/24947986/26310288/41b6cef8-3f3b-11e7-8685-4baeec0fa34d.jpg)

Now, when you actually rotate your device, it will be still OF_ORIENTATION_90_RIGHT.
![img_0361](https://cloud.githubusercontent.com/assets/24947986/26310300/4fa9e590-3f3b-11e7-824d-f2870814ff75.jpg)

And then when you touch the device, it changes to OF_ORIENTATION_180 as it should be.
But as you can see, the viewport suddenly gets in a wrong position.
![img_0362](https://cloud.githubusercontent.com/assets/24947986/26310320/5b648eda-3f3b-11e7-9510-8f6766aac973.jpg)

I think this is clearly a bug that should be fixed.
I will try to fix this but in case someone has an idea how to fix this, please let me know. I would really appreciate it.

link to the forum post : 
https://forum.openframeworks.cc/t/ios-wrong-viewport-after-calling-ofsetorientation-while-in-landscape-device-orientation/26840

**Comment by cuinjune** [comment]
I figured out how to fix this.

in ofxiOSViewController.mm,

inside
```
 - (void)rotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
                            animated:(BOOL)animated {}
```
You will find below code
```

		//assumes Portrait orientation
		if(screenSize.width>screenSize.height){
			center.x = screenSize.height * 0.5;
			center.y = screenSize.width * 0.5;
		}else{
			center.x = screenSize.width * 0.5;
			center.y = screenSize.height * 0.5;
		}
```
replace it with this code below.

```
		//assumes Portrait orientation
		if(screenSize.width>screenSize.height){
			center.x = screenSize.width * 0.5;
			center.y = screenSize.height * 0.5;
		}else{
			center.x = screenSize.width * 0.5;
			center.y = screenSize.height * 0.5;
		}
```

After this fix, if you test the above example code again, you will see that everything works well.
I tested this on both OF v0.9.8 and the latest nightly builds.
I also tested this on both simulator and real device(iPad Air 2)

I would appreciate if someone can confirm this fix so it can be updated in OF.

**Comment by hamoid** [comment]
So you could just get rid of the if statement? Both cases are equal in your new code...

**Comment by cuinjune** [comment]
@hamoid 
You are right! I just changed that.
