### ISSUE TITLE
master is broken on windows

### ISSUE THREAD

**Issue by danzeeeman** [openframeworks/openFrameworks#5631]
Visual Studio is complaining about glm::vec3 calls not being found

specifically
```
void ofRectangle::alignTo(const glm::vec3& targetPoint,
						  ofAlignHorz thisHorzAnchor,
						  ofAlignVert thisVertAnchor) {

	alignTo(targetPoint.xy(), thisHorzAnchor, thisVertAnchor);
}
```
 
it can't find .xy()
or do I need to redownload things?

**Comment by bakercp** [comment]
Make sure you have the right SWIZZLE constant  https://github.com/openframeworks/openFrameworks/blob/be2c3bbcb7445c682bb3dbaf5033617b636b9633/libs/openFrameworks/utils/ofConstants.h#L71 and update your libs which will install and updated glm.

**Comment by bakercp** [comment]
The SWIZZLE constant is in charge of generating those .xy, method in glm.

**Comment by bakercp** [comment]
To clarify, we changed to the new constant (the old one was deprecated), and if you haven't updated your GLM libs, it won't enable swizzling.  `download_libs.sh` should fix it.

**Comment by danzeeeman** [comment]
10-4.  

I haven't messed with master in while and that did the trick!

**Comment by danzeeeman** [comment]
also need to re-generate the project files!!
