### ISSUE TITLE
ofAndroid "App Not Installed"

### ISSUE THREAD

**Issue by toliaferrode** [openframeworks/openFrameworks#5633]
So I've been experimenting with Android lately for a project. I've got a previous prototype fully working (albeit with oF complaining a bit), but now I can't replicate it. I know Android/Android Studio support is experimental. 

So first of all, I've noticed that running some examples on Android give me an "App Not Installed" when I try to install it. The one I can remember is the GUI example using the ofxGui addon. And that brings me to the point. It seems using addons effects whether I can install the app or not. I'm trying to use ofxNetwork. I previously got this to work as I stated, and I also did some experiments outside of the GUI example with ofxGui on Android and it worked. 

Why do I think it has something to do with addons? I just got a successful app install to happen in my testing, but only if I don't include any addons. I'll keep testing.

Edit: After trying many times with the projectGenerator and multiple projects, multiple settings, I got it to work. The only thing that was different is that I added "#include ofxNetwork.h" But I don't see why it would work this time and not others. I mean after all in the GUI example for Android "#include ofxGui.h" is already there and it didn't work. I'll keep testing.

**Comment by bakercp** [comment]
Could you share a bit more information about your setup, including your version numbers, screen shots, devices, etc?

**Comment by toliaferrode** [comment]
@bakercp That seemed to do it. I got the app to install 3 times.

I'm using an older and unsupported version of Ubuntu MATE. oF 0.9.8 for Android. Samsung Galaxy Tab 4 (although it's damaged, so that could be part of it), Android Studio 2.1.3 (because newer versions don't work for me. And I can't upgrade Gradle as it'll break as I explained in another issue.

**Comment by bakercp** [comment]
Have you dug into other solutions for this error:

**Comment by toliaferrode** [comment]
Thanks for that. In reference to the first reference, I'm not signing my apks yet and just doing debug builds. In part because I don't know how to make signed/release apks yet. I'll keep testing.

**Comment by hiroMTB** [comment]
Did you install via USB or web?

**Comment by hiroMTB** [comment]
I tried to regenerate this error with ofxGuiExample on USB and web install.
Both works ok without sign Android 2.3.3, Nexus 5X, API level 19, oF master repo.
Did you maybe install same apk of different oF version?
I couldn't find any official document about this error but here is "practical" doc.
https://www.digitbin.com/app-not-installed-fix-error/

I think we can close this issue so far.

**Comment by toliaferrode** [comment]
Yes, I'm sorry I didn't close this. When I take a break from Android stuff for awhile I forget to include the correct headers. Would be great if the project generation would do this based on which addons you select before you generate a new project.
