### ISSUE TITLE
Depth test does not function correctly when drawing textures with transparency

### ISSUE THREAD

**Issue by BenBergman** [openframeworks/openFrameworks#5644]
When I set `ofEnableDepthTest()` I expected textures closer to the camera to only draw opaque pixels over textures behind it regardless of the draw order presented. Instead, textures that are drawn later but are behind earlier textures are cut off by the other texture's border.

Here is a simple program that demonstrates this behaviour. The blue boxes are drawn first, then the white one, then the red ones. The white one's z value is adjusted by moving the mouse left and right.

```
//--------------------------------------------------------------
void ofApp::setup(){
    ofFbo buffer;
    buffer.allocate(50, 50, GL_RGBA);
    buffer.begin();
    ofClear(255, 255, 255, 0);
    ofSetRectMode(OF_RECTMODE_CENTER);
    ofDrawRectRounded(25, 25, 30, 50, 10);
    buffer.end();
    
    myTexture = buffer.getTexture();
    
    ofEnableDepthTest();
}

//--------------------------------------------------------------
void ofApp::draw(){
    ofPushStyle();
    ofSetColor(ofColor::blue);
    myTexture.draw(650, 320);
    myTexture.draw(550, 320);
    ofPopStyle();
    
    
    ofPushMatrix();
    ofTranslate(0, 0, ofGetMouseX());
    myTexture.draw(600, 350);
    ofPopMatrix();
    
    
    ofPushStyle();
    ofSetColor(ofColor::red);
    myTexture.draw(650, 380);
    myTexture.draw(550, 380);
    ofPopStyle();
}
```

I have confirmed that this behaviour is present in 0.9.8 as well as commit 5e51b99... (the latest commit on master with passing builds for macOS).

In this trivial example, I know that I could solve the problem by changing the order in which I draw the textures to the screen. In my actual project that I'm working on at the moment I am drawing textures as point sprites on an ofVboMesh object, much like in the billboards example project. In my project, I am drawing the sprites out in a grid and varying their z values based on an image. This makes manually drawing in the correct order non-trivial (to my knowledge anyway - I'm still pretty new to oF).

Edit: Note that this also affects textures drawn at the same z position but are very close together.

**Comment by arturoc** [comment]
this is just how opengl works, whenever you draw something with transparency you need to reorder it since although you should see through the pixels with alpha the depth buffer is being written for those pixels too so anything drawn after that is further won't be drawn.

you need to draw objects with transparency in a second pass or if your transparency is 0 or 1 you can draw a shader to discard the fragments that have alpha

**Comment by BenBergman** [comment]
Thanks @arturoc for the clarification. After sleeping on it, I found a clean way to sort my objects prior to drawing, so this solution is working fine for me.
