### ISSUE TITLE
gcc 7.1.1 breaks OF OF 0.9.8

### ISSUE THREAD

**Issue by riccardolardi** [openframeworks/openFrameworks#5647]
I just updated gcc and gcc-lib packages on Arch Linux and cannot make any OF project anymore. It seems to be an issue related to nlohmann's json.hpp. See here: https://github.com/nlohmann/json/issues/590

**Comment by bakercp** [comment]
Seems to be related to `using namespace std`.

Here's the location:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L435

Here is the open issue related to removing using namespace.

https://github.com/openframeworks/openFrameworks/issues/2581

**Comment by dimitre** [comment]
potentially closed by https://github.com/openframeworks/openFrameworks/pull/7005
