### ISSUE TITLE
Video missing in release build from visual studio 2015

### ISSUE THREAD

**Issue by david-sullivan** [openframeworks/openFrameworks#5648]
i have been having problems with video in the release builds of visual studio 2015 projects and of0.9.8. running windows 10 on intel i7 with geforce gtx 970

the videos run fine in the debug builds, but are completely missing in the release build.
however, videos play in both debug and release builds of the OF example files i've tested.

for instance, the videoPLayerExample does what it should in debug and release.
if i create a new project using the project generator and then copy and paste the code from the videoPlayerExample (and the bin/data directory), the video plays in debug build, but is once again missing in the release build.

**Comment by bakercp** [comment]
Do you get any console messages or errors?

**Comment by bakercp** [comment]
This sounds a lot like a visual studio 2015 project file configuration issue ... but my experience with VS is quite limited. @tgfrerer @openframeworks/windows team do you have any tips?

**Comment by tgfrerer** [comment]
@david-sullivan hmmm, difficult to say, but i'd agree with @bakercp that it might be a project file config issue. I've tried to reproduce with current openframeworks/master on windows 10 and it worked fine, in 32 and 64bit release. 

Perhaps try rebuilding your project file if you can, using the project generator. Save your old project file (or commit your latest changes) to be safe before, then issue, from a console inside the directory of your app:

`../../../apps/projectGenerator/commandLine/bin/commandLine.exe -o"../../.." .`

This should re-create the project files for your app using the command line project generator.

**Comment by david-sullivan** [comment]
it took me a loooong time to be able to test this out (I couldn't even compile PG until i finally updated VS2015).  unfortunately there was no change on my end. any other ideas?
i tried to setup qt creator but could never get it to compile any project.

**Comment by danzeeeman** [comment]
Are the release DLLs getting copied to /bin?

**Comment by david-sullivan** [comment]
yes. i'm not sure i could tell if they are release dlls, but i deleted everything in /bin, and then rebuilt, and there are 9 dlls now.

**Comment by david-sullivan** [comment]
if this is a vs project file config problem, how might one go about fixing it? is this something i can dig around in vs for?

**Comment by david-sullivan** [comment]
i just reinstalled vs and  of with no change. i guess my windows install is just cursed.    .....back to the reliability of xcode....

**Comment by david-sullivan** [comment]
i was trying this again on a new windows computer, with a new install of everything (of, vs2015, klite codecs). apparently this problem occurs only if my target name is "main". if i set the target name to "main2", the video plays just fine in release. 
this is happening with the videoPlayer example and OF0.9.8

**Comment by vooku** [comment]
Apparently switching the pixel mode to BGRA helps, see the [forum](https://forum.openframeworks.cc/t/videos-not-playing-in-exe-build-in-release-mode/11979/4).

**Comment by dimitre** [comment]
I'll be closing this one as Visual Studio 2015 is not supported anymore. if the issue persists in recent OF feel free to re-open or open a new updated issue
