### ISSUE TITLE
oF 0.9.8: of3DPrimitive Loaded .PLY Mesh Broken

### ISSUE THREAD

**Issue by toliaferrode** [openframeworks/openFrameworks#5656]
Hi, I am doing 3D rendering testing on the Raspberry Pi with oF and Blender. What I'm doing is loading .ply files into of3DPrimitive. When I draw a normal 3D primitive, like ofSpherePrimitive, in wireframe mode everything is ok. But when I load a .ply into of3DPrimitive and draw it's wireframe it shows up weird. It resembles the model enough, but it looks like there's vertices and edges missing in what seems to be random places. I even imported a more simple model and it rendered weird, as well.

Also I should report that when a .ply mesh is drawn solid, but with no materal, just with a color, and with semi-transparency it also looks broken. Weird artefacts and missing triangles, verticies, and edges here and there.

I'll keep you posted as to whether this issue is on desktop as well.

Edit: Oh wow, I could have sworn desktop was effected by this as well, but it's not. The mesh displays correctly as it should in wireframe mode.

Edit 2: I don't know if this is related, but I noticed that by default on the Pi and on desktop ofSpherePrimitive shows quads and triangles respectively. But of3DPrimitive can only take meshes that are triangulated.

**Comment by bakercp** [comment]
Please include code to reproduce and screenshots of errors, build/version of OS on Raspberry Pi, etc.

**Comment by toliaferrode** [comment]
Acknowledged, I'll have something in a few hours.

**Comment by bakercp** [comment]
Also, can you try this with the master branch of OF, a bunch of tesselation-related fixes for RPI were fixed recently.

**Comment by arturoc** [comment]
this is not a bug or at least not one that is solvable, openGL ES doesn't have a straightforward way to render a wireframe of a triangles mesh so we just draw it as lines. if you want to draw the wireframe in the pi, android... you need to turn the triangles into lines manually
