### ISSUE TITLE
Compiling examples from projectGenerator: There was a problem updating your project...

### ISSUE THREAD

**Issue by Deejep** [openframeworks/openFrameworks#5657]
I got this when I click : update multiple
Platform: Ubuntu 16.04

`Command failed: /bin/sh -c "/home/djeb/openFrameworks/projectGenerator-linux64/resources/app/app/projectGenerator" -r  -o"/home/djeb/openFrameworks" -p"linux64" "/home/djeb/openFrameworks/examples"
/home/djeb/openFrameworks/projectGenerator-linux64/resources/app/app/projectGenerator: 3: /home/djeb/openFrameworks/projectGenerator-linux64/resources/app/app/projectGenerator: Syntax error: Unterminated quoted string
`

**Comment by bakercp** [comment]
Please submit this issue to the projectGenerator issue tracker:

https://github.com/openframeworks/projectGenerator

Closing for now.
