### ISSUE TITLE
The method to replace processDataCallback

### ISSUE THREAD

**Issue by DyInCN** [openframeworks/openFrameworks#5658]
We have a old project used the QuickTime.framework. In order to playback the video with special sound effects，we used the QTAudioContextInsertRegistryInfo API,and set the processDataCallback of the 
QTAudioContextInsertRegistryInfo object.The processDataCallback is said like this:

<typedef CALLBACK_API( OSStatus , AudioContextInsertProcessDataCallback )(void *inUserData, AudioUnitRenderActionFlags *ioRenderFlags, const AudioTimeStamp *inTimeStamp, UInt32 inNumberFrames, AudioBufferList *inInputData, AudioBufferList *outOutputData);>

When the program excutes this callback, we can get the inInputData and outOutputData. And then, 
there is a third C++ API,which need the parameters are from the inInputData and outOutputData.
This API can run audio effects for the playing data.

Now we need to abandon the QuickTime.framework, and replace it by AVFoundation.framework.
The third C++ API was made into a static library, and we can not modify the source code about it.
So there is a question is that how can I get the inInputData and outOutputData by AVFoundation?
If someone can help us, it is so much thanks。

**Comment by bakercp** [comment]
Since this isn't a specific bug in openFrameworks, please ask about it on the forum https://forum.openframeworks.cc/.

Closing this issue for now.

**Comment by DyInCN** [comment]
OK，sorry for that
