### ISSUE TITLE
Feature Request: Add Support for Brew

### ISSUE THREAD

**Issue by RabbitMC** [openframeworks/openFrameworks#5659]
Add support for [Brew](https://brew.sh) on macOS would be a comfortable way to easy manage OF on macOS.

**Comment by bakercp** [comment]
Could you elaborate? System libraries installed with Brew can already be used.

**Comment by danomatika** [comment]
I think he means:

    brew install openframeworks

Instead of downloading and extracting a zip from openframeworks.cc.

**Comment by eivindml** [comment]
Yes. Would love this as well.

**Comment by danzeeeman** [comment]
not an issue

**Comment by bakercp** [comment]
It's an interesting proposal indeed, but perhaps it would be better to discuss the feature on the forum and then submit a PR if there is a consensus on how it should be done.
