### ISSUE TITLE
ofPolyline::getResampledBySpacing() often returns wrong resampled number

### ISSUE THREAD

**Issue by TetsuakiBaba** [openframeworks/openFrameworks#5662]
ofPolyline::getResampledBySpacing has a bug for resampled number. When it is resampled by Spacing or Count, sometimes the resampling point won't make correct number. It is because of for loop is used under the float condition,  for( f=0.0; f < totalLength; f=f+spacing){...}.  For example, the below shows that 10th point is lacking in spite of using getResampledByCount(11). 
![graph_resample](https://user-images.githubusercontent.com/1846131/27093622-6130e43a-50a2-11e7-8fe3-6654bf677d18.png)

The solution is changing the for loop condition from float to int in the getResampledBySpacing function.

```c++
ofPolyline ofPolyline::getResampledBySpacing(float spacing) const {
    if(spacing==0 || size() == 0) return *this;
    ofPolyline poly;
    float totalLength = getPerimeter();

	for( int i = 0; i <= totalLength/spacing; i++ ){
		poly.lineTo(getPointAtLength(i*spacing));
	}
	
    if(!isClosed()) {
        if(poly.size() > 0) poly.points.back() = points.back();
        poly.setClosed(false);
    } else {
        poly.setClosed(true);
    }
    
    return poly;
}
```

**Comment by bakercp** [comment]
Are these related:

https://github.com/openframeworks/openFrameworks/issues/3557
https://github.com/openframeworks/openFrameworks/issues/1664

**Comment by TetsuakiBaba** [comment]
Thanks, very related and shame on my thoughtless. I'm now using OF 0.9.8 which still includes this issue. hoping it'll be solved next update.
