### ISSUE TITLE
OpenFrameworks example not working on Raspberrpi when OpenGL driver is enabled

### ISSUE THREAD

**Issue by waqarrashid33** [openframeworks/openFrameworks#5670]
Hello,
I am been trying to run some of the openframeworks examples on raspberry pi but I can't make them work. They work fine when the Legacy driver is in use but when I enable the OpenGL driver experimental driver, and try to run them using `make RunRelease`, the following error is thrown at me:
(In the new version of raspbian, there are two experimental drivers, output for both is give)

**1. G1 GL (Full KMS): OpenGL desktop driver with full KMS**
```
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl gtk+-3.0 
[ error ] ofAppEGLWindow: getScreenSize(): tried to get display size but failed
[notice ] ofAppEGLWindow: setupRPiNativeWindow(): screenRect: 0x0
[notice ] ofAppEGLWindow: setupRPiNativeWindow(): windowRect: 0x0
[ error ] ofAppEGLWindow: setupRPiNativeWindow(): dispman_element == DISPMANX_INVALID
[warning] ofAppEGLWindow: getNativeDisplay(): window not initialized, returning NULL
[warning] ofAppEGLWindow: getNativeDisplay(): window not initialized, returning NULL
[notice ] ofAppEGLWindow: createSurface(): setting up EGL Display
* failed to add service - already in use?
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:176: recipe for target 'RunRelease' failed
make: *** [RunRelease] Error 1
```
**2. G2 GL (Fake KMS): OpenGL desktop driver with fake KMS**
```
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl gtk+-3.0 
[notice ] ofAppEGLWindow: setupRPiNativeWindow(): screenRect: 1280x1024
[notice ] ofAppEGLWindow: setupRPiNativeWindow(): windowRect: 1024x768
[notice ] ofAppEGLWindow: createSurface(): setting up EGL Display
* failed to add service - already in use?
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:176: recipe for target 'RunRelease' failed
make: *** [RunRelease] Error 1
```

**Comment by bakercp** [comment]
The openFrameworks build system and EGL window is not set up to user the new drivers on RPI. It creates an EGL context manually. 

What are you trying to do that requires the experimental GL drivers exactly?

**Comment by waqarrashid33** [comment]
I am new to OpenGL and openframeworks. I want to port some shaders to raspberrypi.
With the experimental driver disabled, wouldn't these be rendered only using CPU?

**Comment by bakercp** [comment]
Shaders run fine on the GPU on RPI as long as they are gles compatible.

**Comment by waqarrashid33** [comment]
So they doesn't need the experimental driver to be enabled, and runs on GPU?

**Comment by bakercp** [comment]
Which shader examples have you tried that didn't work?

**Comment by waqarrashid33** [comment]
All examples doesn't work. Gives the same error. They only work when I use
legacy driver for opengl.

**Comment by bakercp** [comment]
Yes, they are supposed to work that way. They are still using the GPU. So
if they are working with the defaults, what are you trying to achieve with
the new drivers?

**Comment by waqarrashid33** [comment]
That sounds good then. I was under the impression that they are using CPU
untill the new driver is enabled.

**Comment by bakercp** [comment]
They are definitely running on the GPU.  

The new driver is specifically intended to bring GPU acceleration to the Raspberry Pi desktop experience.  You can read more about it (and its purpose) here https://www.raspberrypi.org/blog/another-new-raspbian-release/

The main way we might benefit from using it is if we wanted to work toward using GLFW as a windowing system on Raspberry Pi.  This may feel a little less little less hacky, particularly with regard to user input support (i.e. it would allow us to use XWindows based events, etc).  But until someone can show that it improves performance and reliability (or ease of code upkeep), we'll probably continue to use our custom `dispmanx` based window. 

I'm going to close this issue for now.  If we want to pursue a GLFW-based window on RPI using the new drivers, we should discuss that further on the forum.

Cheers!

**Comment by waqarrashid33** [comment]
Thank you very much for the help. It was very helpful.

**Comment by webkhanh** [comment]
wow thank you that was easily the best explanation I've seen about this driver mess! I've also been trying to wrap my head around the difference between the 2 and why the legacy ones are still relevant
