### ISSUE TITLE
Device Orientation Change Callback in Android?

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5672]
Hi, I want to detect device orientation change in Android.

I wonder if there's something similar to iOS's deviceOrientationChanged() callback in Android. 

If there's none, how can I implement Java callback function in ofApp.cpp file?
I would appreciate any advice. Thanks in advance!

**Comment by bakercp** [comment]
Hi, since this is still a question and not a bug, please ask about it on the forum.

https://forum.openframeworks.cc/

Thanks!
