### ISSUE TITLE
ofxAssimpModelLoader deforms model geometry

### ISSUE THREAD

**Issue by taavuu** [openframeworks/openFrameworks#5673]
I have a sketch loading a 3D model and I am compiling it under win7 and raspberry pi 3. On rpi3 the model geometry gets deformed and therefore texture wont load.

The code is identical on both platforms and I am using OF 0.9.8. RPI is running raspbian (jessie) with latest updates.

I am not sure if it's ofxAssimpModelLoader problem per se or is connected to some other underlying libraries.

![of-0 9 8-assimp-win7-vs-rpi3](https://user-images.githubusercontent.com/29501754/27252321-0fa24824-5364-11e7-8089-7a44b0a63d1d.jpg)

Test code:
[model_test.zip](https://github.com/openframeworks/openFrameworks/files/1082496/model_test.zip)

**Comment by bakercp** [comment]
Could you please try this on the Raspberry Pi 3 with a nightly build?

**Comment by taavuu** [comment]
Tried OF [nightly build](http://ci.openframeworks.cc/nightlybuilds.html) and OF latest git checkout and both deform the model on rpi3 as above

**Comment by jvcleave** [comment]
I think this may be a limitation of OpenGL ES 

https://forum.openframeworks.cc/t/ofmesh-missing-vertical-lines-in-opengl-es/23474

**Comment by taavuu** [comment]
@jvcleave Thanks for the link! I wondered if it was something to do with opengl, but then again, if you look at the image I posted then you can see straight lines going through the model on rpi3, so it's not only wireframe being incomplete but something else is going on there aswell -- wrong connections being made between existing vertices

**Comment by arturoc** [comment]
as @jvcleave points out thus is just an opengl es limitation. the lines going through the model is just cause triangles group vertices 3 by 3 while lines group them 2 by 2 so some lines are connecting vertices from 2 different triangles.

there could be a way to generate the indices for a wireframe in ofmesh but the api would be different tgan the current one

riggt now you need to do this manually
