### ISSUE TITLE
Boost libraries are overwritten by emscripten libs download script

### ISSUE THREAD

**Issue by chuckleplant** [openframeworks/openFrameworks#5693]
Follow up on #5613, when running the emscripten download_libs.sh script, the desktop (in this case XCode) project stops working, this is due to:

```
clang: error: no such file or directory: '../../../libs/boost/lib/osx/boost_filesystem.a'
clang: error: no such file or directory: '../../../libs/boost/lib/osx/boost_system.a'
```
Downloading the libraris from the osx script fixes this, but then emscripten has a similar error when running the html build

**Comment by arturoc** [comment]
the download_libs script removes all the libraries by default but you can tell it to not overwrite by passing -n you can also call it with --help to see usage instructions
