### ISSUE TITLE
addon_config.mk ADDON_CFLAGS doesn't read assigned values 

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#5694]
I am trying to build a proper ```addon_config.mk``` for one of my addons, and it relies on a pre-processor macro to be defined with a certain value for it to work;

I am looking at the source code of the command line project generator, and it seems it can't parse something like:

```
ADDON_CFLAGS  =  DEBUG_LEVEL=1
```
 

It seems it uses "=" and "=+" to tokenise the whole file; so it seems it's just not supported.
Is there a way to define a macro with a value using the addon_config.mk file? 

Would it be cool to use a special token for such macros, something along the lines of

```
ADDON_CFLAGS  =  DEBUG_LEVEL#1
```

or some other char that could make sense? I'm happy to look into implementing that in the project generator to support such macro definitions from the addon_confg.mk file.

**Comment by arturoc** [comment]
cflags are not preprocessor macros but flags passed to the compiler, the correct syntax would be:

```
ADDON_CFLAGS  =  -DDEBUG_LEVEL=1
```

i've started adding an ADDON_DEFINES but it's not working for every platform yet

**Comment by armadillu** [comment]
Great to hear, thx!
