### ISSUE TITLE
emscripten: warning: unresolved symbol , on linux system

### ISSUE THREAD

**Issue by wolf188** [openframeworks/openFrameworks#5698]
**while compile the emptyExample project with emmake make.**

2 warnings generated.
Compiling /home/project/emscripten/of_v0.9.8/addons/ofxEmscripten/src/ofxEmscriptenURLFileLoader.cpp
Compiling /home/project/emscripten/of_v0.9.8/addons/ofxEmscripten/src/ofxEmscriptenSoundStream.cpp
Compiling /home/project/emscripten/of_v0.9.8/addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp
Compiling /home/project/emscripten/of_v0.9.8/addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp
Compiling /home/project/emscripten/of_v0.9.8/addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp
Linking bin/emptyExample.html for emscripten
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEED2Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_jjRKS4_
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE4syncEv
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2ERKS5_
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE6xsgetnEPci
warning: unresolved symbol: _ZNSt3__18ios_base5clearEj
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKcj
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE6setbufEPci
warning: unresolved symbol: _ZNKSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEPKc
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEED0Ev
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEj
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEED2Ev
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEi
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE5writeEPKci
warning: unresolved symbol: _ZNSt3__114basic_iostreamIcNS_11char_traitsIcEEED2Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcj
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEjc
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6resizeEjc
warning: unresolved symbol: _ZNSt3__114basic_iostreamIcNS_11char_traitsIcEEED0Ev
warning: unresolved symbol: _ZNSt3__19basic_iosIcNS_11char_traitsIcEEED2Ev
warning: unresolved symbol: _ZNSt13runtime_errorC2ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKcj
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKc
warning: unresolved symbol: _ZNSt3__114basic_iostreamIcNS_11char_traitsIcEEED1Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEjc
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKc
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5uflowEv
warning: unresolved symbol: _ZNSt3__113basic_istreamIcNS_11char_traitsIcEEED1Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__grow_byEjjjjjj
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE5imbueERKNS_6localeE
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSEc
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcjj
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE5eraseEjj
warning: unresolved symbol: _ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv
warning: unresolved symbol: _ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv
warning: unresolved symbol: _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEED1Ev
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7replaceEjjPKcj
warning: unresolved symbol: _ZNSt3__113basic_istreamIcNS_11char_traitsIcEEED0Ev
warning: unresolved symbol: _ZNKSt3__18ios_base6getlocEv
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE6xsputnEPKci
warning: unresolved symbol: _ZNKSt3__16locale9use_facetERNS0_2idE
warning: unresolved symbol: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev
warning: unresolved symbol: _ZNSt3__18ios_base4initEPv
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEEC2Ev
warning: unresolved symbol: _ZNSt3__16localeD1Ev
warning: unresolved symbol: _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE9showmanycEv
warning: unresolved symbol: _ZNSt3__15ctypeIcE2idE
warning: unresolved symbol: _ZTINSt3__113basic_istreamIcNS_11char_traitsIcEEEE
warning: unresolved symbol: _ZTINSt3__113basic_ostreamIcNS_11char_traitsIcEEEE
warning: unresolved symbol: _ZTINSt3__114basic_iostreamIcNS_11char_traitsIcEEEE
warning: unresolved symbol: _ZTINSt3__115basic_streambufIcNS_11char_traitsIcEEEE
Warning: bin/data@data does not exist, ignoring.
Nothing to do!
HOST_OS=Linux

     compiling done

**Comment by dimitre** [comment]
I think this can be closed. what do you think @Jonathhhan

**Comment by Jonathhhan** [comment]
@dimitre I think so, too.

**Comment by dimitre** [comment]
thanks, I'll be closing this
