### ISSUE TITLE
API support for soundStream is missing in version 0.9.8 for Visual Studio

### ISSUE THREAD

**Issue by good-grief** [openframeworks/openFrameworks#5699]
It seems that the [Visual Studio download](http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_vs_release.zip) does not contain the changes in the sound library to specify the API (Asio, WASAPI, Direct Sound).

The problem was discussed in the [forum](https://forum.openframeworks.cc/t/quick-tip-supporting-wasapi-and-asio/22898), by that time version 0.9.3 was out.

The audioInputExample still contains this code:
`
#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){	 
	
	ofSetVerticalSync(true);
	ofSetCircleResolution(80);
	ofBackground(54, 54, 54);	
	
	// 0 output channels, 
	// 2 input channels
	// 44100 samples per second
	// 256 samples per buffer
	// 4 num buffers (latency)
	
	soundStream.printDeviceList();
	
	//if you want to set a different device id 
	//soundStream.setDeviceID(0); //bear in mind the device id corresponds to all audio devices, including  input-only and output-only devices.
	
	int bufferSize = 256;
	
	
	left.assign(bufferSize, 0.0);
	right.assign(bufferSize, 0.0);
	volHistory.assign(400, 0.0);
	
	bufferCounter	= 0;
	drawCounter		= 0;
	smoothedVol     = 0.0;
	scaledVol		= 0.0;

	soundStream.setup(this, 0, 2, 44100, bufferSize, 4);

}
`

**Comment by arturoc** [comment]
this is already in master or in the nightly builds and will be also in the 0.10 release which should be ready soon
