### ISSUE TITLE
ofxKinect libusb fix for Visual Studio 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5700]
Currently ofxKinect in OF master doesn't work with Visual Studio. 
This is because libfreenect uses latest libusb which breaks the Windows libusb emulation layer. 

Using the latest libusb from:
https://github.com/libusb/libusb/ 

And applying this PR:
https://github.com/libusb/libusb/pull/246 

Then building ( in Visual Studio 2015 with the latest DDK / WDK ) results in a working lib for ofxKinect that only requires the libusb header and .lib to run. 

All the code in:
https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxKinect/libs/libusb-win32 is now no-longer required. 

NOTE: you need to install the libusbK drivers via Zadig for the device.  But that is already much easier than the all .inf approach. 

So the ofxKinect structure can be quite a bit simpler as a result.  

I am going to work on a PR to the current master to get things working for VS. 

Then look at what else needs changing.
Like MSYS2 etc.

**Comment by arturoc** [comment]
great, if you can send the PR for the libraries to apothecary instead of here that would be great, (unless the libraries are source code)

**Comment by ofTheo** [comment]
@arturoc - the libs for the ofxKinect addon ( and apothecary scripts ) are still in the main OF repo though right?

https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxKinect/libs 

I can probably get the ofxKinect addon updated for VS fairly easy in the main repo, just by adding a vs folder to libs. 

Getting libusb to build via apothecary with the patch might take quite a bit more. 
I guess I could host a patched version of the libusb master and then try windows command line tools, but I am def not very versed with apothecary on Windows.
