### ISSUE TITLE
ofEasyCam::disableMouseInput() doesn't work in setup()

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#5703]
Calling ofEasyCam::disableMouseInput() in setup() doesn't work. Mouse input get's reenabled when ofEasyCam::begin() is called the first time.

**Comment by roymacdonald** [comment]
thanks for pointing this out. I'll take a look at it. 
cheers

**Comment by roymacdonald** [comment]
fixed by https://github.com/openframeworks/openFrameworks/pull/5710.
please close this issue.
cheers
