### ISSUE TITLE
emmake make fail to compile 3DPrimitivesExample

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#5705]
I've just pulled the current master and i was not able to compile the project to emscripten as explained here http://openframeworks.cc/setup/emscripten/

OS: Mac 10.11.5 (15F34)
emscripten SDK version: 1.37.16

Error log
[emmake_error.txt](https://github.com/openframeworks/openFrameworks/files/1169626/emmake_error.txt)

**Comment by cuinjune** [comment]
I also have this issue on Mac OSX 10.11.6.

**Comment by arturoc** [comment]
have you tried the nightly builds?

**Comment by edap** [comment]
I've tried now, same error, log in attachment
[errorlog.txt](https://github.com/openframeworks/openFrameworks/files/1170580/errorlog.txt)

It can not find the compiler_flags, cat: 
Sources/OF/of_v20170714_osx_release/libs/openFrameworksCompiled/lib/emscripten/obj/Release/.compiler_flags: No such file or directory

are they strictly necessary?

**Comment by edap** [comment]
@arturoc let me know if there is something that I can do, or if you have an idea about something that I could try, I would like to start to fix some issues.

**Comment by chuckleplant** [comment]
Latest master is working for me on OSX. @edap Have you ran the emscripten download_libs script? See #5613 for a related topic. My problem was that I was overwriting libraries, see #5693 for how to keep all libraries when using both emscripten and desktop builds. Hope this helps.

**Comment by AndresCuervo** [comment]
@chuckleplant I'm having the same issue on OS X, have used `-n` with both emscripten and osx download_libs scripts but still getting the errors below when I 
<img width="1680" alt="screen shot 2018-01-23 at 8 45 25 pm" src="https://user-images.githubusercontent.com/5826638/35314965-79fc1eda-007e-11e8-8350-fe064c11de4a.png">


from the terminal:

```
Executing /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary --incognito --enable-nacl --enable-pnacl --disable-restore-session-state --enable-webgl --no-default-browser-check --no-first-run --allow-file-access-from-files http://localhost:6931/3DPrimitivesExample.html
Created new window in existing browser session.
[8262:48131:0123/204647.561182:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
missing function: _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKc
-1
-1
exception thrown: abort(-1). Build with -s ASSERTIONS=1 for more info.
```

**Comment by bakercp** [comment]
I just got it working yesterday with these steps:

Worked first time for me.  Here are my steps on the macOS terminal.

Download and unpack emscripten.

`curl -LO https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz && tar xvf emsdk-portable.tar.gz`

`cd emsdk-portable/`

Initialize emscripten.

`./emsdk update`
`./emsdk install latest`
`./emsdk activate latest`

Set up your environement.

`source ./emsdk_env.sh`

Set `MAKEFLAGS` to make it compile faster (optional).

`export MAKEFLAGS="-j8 -s"`

Get the latest version of openFrameworks.

`git clone --depth=1 https://github.com/openFrameworks/openFrameworks.git`

`cd openFrameworks`

Install openFrameworks libraries for emscripten.

`scripts/emscripten/./download_libs.sh`

Go to an example:

`cd examples/3d/3DPrimitivesExample/`

Copy a MAKEFILE into the example:

`cp ../../../scripts/templates/emscripten/Makefile .`

Build the project:

`emmake make`

Run the project.

`emrun bin/3DPrimitivesExample.html`

![openframeworks](https://user-images.githubusercontent.com/300484/35315124-4d3dbf86-0090-11e8-9d7e-a3256a230574.png)

**Comment by bakercp** [comment]
Closing this, as it works with the latest master branch.

**Comment by AndresCuervo** [comment]
Ah, the steps above worked for me, I suppose the Makefile template was necessary to sort things out. Thanks @bakercp !

**Comment by Mach1Studios** [comment]
I would like to reopen this as it does not work with all current

**Comment by arturoc** [comment]
can you create a new issue with the error you are gettng now?
