### ISSUE TITLE
APP_NAME not replaced by project name in Android Studio project

### ISSUE THREAD

**Issue by hamoid** [openframeworks/openFrameworks#5715]
### Environment

* openFrameworks: master from Git
* OS & version: build on Arch Linux for Android 5.1.1

### Expected result

Using the command line projectGenerator I should get a project that runs on Android Studio

### Actual result

The project builds, the apk is transferred to the device, but it crashes because it does not find the Activity class. See the errors at the forum: https://forum.openframeworks.cc/t/can-the-same-install-of-of-be-used-for-desktop-and-android/27440/3

### Proposed Solution

I suspect the projectGenerator is not replacing the variable APP_NAME with the current project name. I used the command line projectGenerator, in case that makes a difference. The replacement apparently should be happening, according to https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/androidStudioProject.cpp
Anything I can do to check if the issue is in my set up or in the code?

**Comment by hamoid** [comment]
I have the impression my project generator is outdated because:

* The project generator tries to copy `config.make` and `Makefile` which don't exist.
* The content of the `templates/android` folder is copied successfully: `res/`, `src/`, `srcJava/`, `AndroidManifest.xml`, `build.gradle` and `settings.gradle`.
* Substitutions not done inside `AndroidManifest.xml`: `TEMPLATE_PACKAGE_NAME` (twice).
* The `srcJava/cc/openframeworks/APP_NAME` folder should have been renamed.
* Substitutions not done inside `srcJava/cc/openframeworks/APP_NAME/OFActivity.java`: `TEMPLATE_APP_NAME` (once).

If I download a recent Electron based PG binary it fails because it does not find the command line projectGenerator:

```
Command failed: /bin/sh -c "projectGenerator"  -o"/home/funpro/src/openFrameworks" -a" " -p"android" "/home/funpro/src/openFrameworks/examples/android/androidCameraExample"
/bin/sh: projectGenerator: command not found
```

**Comment by hamoid** [comment]
I figured out one of the issues. After compiling the project generator it asks if it should be installed with a `[Y/n]` question, which seems to imply that Y is the default you get by just pressing `ENTER`, but it's not the case. If you press `ENTER`, the binary is NOT installed, but I assumed it was. See here: https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/compilePG.sh#L17

Once installed by choosing `Y`, the Electron based PG binary does no longer fail to find the command line projectGenerator, but for some reason the `APP_NAME` folder is not renamed, nor is the first line of `OFActivity.java` substituted with the correct value.

**Comment by arturoc** [comment]
cc @danzeeeman @HalfdanJ

**Comment by HalfdanJ** [comment]
Hmmm.. I also keep getting confused about projectGenerator versions, but I know that the one build from github does work well (also on linux since thats where the CI tests are running). 

The CI is using the build that is build here automatically: http://ci.openframeworks.cc/projectGenerator/projectGenerator_linux, could you try with that?

**Comment by hamoid** [comment]
Hi! Thank you, I didn't know about that location for downloading the pg. If it's a stable source, we could mention it on https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md

When I ran it I got
`./projectGenerator_linux: error while loading shared libraries: libcurl-gnutls.so.4: c` so I did `sudo pacman -S libcurl-gnutls`

Then I get `./projectGenerator_linux: error while loading shared libraries: libGLEW.so.1.10: cannot open shared object file: No such file or directory`. These are available:

```
extra/glew 2.1.0-1 [installed: 2.0.0-1]
    The OpenGL Extension Wrangler Library
community/glew1.10 1.10.0-1
    A cross-platform C/C++ extension loading library
```

Can I have both 2.1 and 1.1 installed?

**Comment by arturoc** [comment]
that won't work as easily in linux since it's compiled on an old version of ubuntu in the ci servers so the dynamic libraries it uses are not compatible with the nerwer ones in your archlunux.

what you can do if you are using OF from git is to checkout latest master for the project generatro:

```
cd apps/projectGenerator
git checkout master
git pull origin master
```
then try to recompile it again. that should give you the latest version with all the fixes

**Comment by hamoid** [comment]
I ran those three commands, compiled the PG, answered "Y" to install, then did
`projectGenerator -o"/home/funpro/src/openFrameworks" -a"" -p"android" "/home/funpro/src/openFrameworks/examples/android/androidAudioExample/"`
and still the first line of `OFActivity.java` is `package cc.openframeworks.TEMPLATE_APP_NAME;`

I could show this happening at the next OF meetup...

**Comment by HalfdanJ** [comment]
And its not because you have a older version of projectGenerator installed somewhere on PATH that is being called instead of the newly compiled version? (`which projectGenerator`) 

This is where its getting replaced: https://github.com/openframeworks/projectGenerator/blob/0d28e5b21a5274366ce73adab8fb194c40b2640a/ofxProjectGenerator/src/projects/androidStudioProject.cpp#L115 

This is the script that is being run to test the setup on each commit: https://github.com/openframeworks/openFrameworks/blob/master/scripts/ci/android/build.sh

**Comment by hamoid** [comment]
Thanks for your patience! These were my steps:

```bash
$ which projectGenerator
/usr/local/bin/projectGenerator
$ sudo rm /usr/local/bin/projectGenerator
$ cat src/openFrameworks/apps/projectGenerator/ofxProjectGenerator/src/projects/androidStudioProject.cpp | grep OFActivity
findandreplaceInTexfile(ofFilePath::join(from,"OFActivity.java"), "TEMPLATE_APP_NAME", projectName);
$ cd src/openFrameworks/scripts/linux/
$ ./compilePG.sh -j8
# (I see the androidStudioProject.cpp file above being compiled)
$ which projectGenerator
/usr/local/bin/projectGenerator
$ cd src/openFrameworks/examples/android/
$ projectGenerator -o"/home/funpro/src/openFrameworks" -a"" -p"android" "/home/funpro/src/openFrameworks/examples/android/androidSwipeExample/"
$ ls /home/funpro/src/openFrameworks/examples/android/androidSwipeExample/srcJava/cc/openframeworks/
APP_NAME/
$ cat /home/funpro/src/openFrameworks/examples/android/androidSwipeExample/srcJava/cc/openframeworks/APP_NAME/OFActivity.java | head -1
package cc.openframeworks.TEMPLATE_APP_NAME;
```

I'm probably doing something wrong, but I can't see what.

**Comment by arturoc** [comment]
@hamoid i think this should be fixed now with #165 but if you can give it a try?

**Comment by hamoid** [comment]
I feel like it's 2010 all over again :P  165?

**Comment by arturoc** [comment]
:) sorry it's 165 from the PG repo: https://github.com/openframeworks/projectGenerator/pull/165

**Comment by hamoid** [comment]
Thanks, I'll try those! 

Weird. The link to #165 takes you to a super old issue. Issues and PRs numbers had so far a sequential shared ID. I wonder if this is a GitHub glitch?
