### ISSUE TITLE
Problem install in raspberry Pi 2

### ISSUE THREAD

**Issue by mianel** [openframeworks/openFrameworks#5719]
Hi,

I followed the instructions from the website but when I tried to install the dependencies I have problems with this:

Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libtiffxx5 armhf 4.0.3-12.3+deb8u2
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main gir1.2-gtk-2.0 armhf 2.24.25-3+deb8u1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavutil-dev armhf 6:11.8-1~deb8u1+rpi1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavresample-dev armhf 6:11.8-1~deb8u1+rpi1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavcodec-dev armhf 6:11.8-1~deb8u1+rpi1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavformat-dev armhf 6:11.8-1~deb8u1+rpi1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libswscale-dev armhf 6:11.8-1~deb8u1+rpi1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libgtk2.0-dev armhf 2.24.25-3+deb8u1
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libjasper-dev armhf 1.900.1-debian1-2.4+deb8u2
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libtiff5-dev armhf 4.0.3-12.3+deb8u2
  404  Not Found [IP: 93.93.128.193 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libudev-dev armhf 215-17+deb8u6
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tiff/libtiffxx5_4.0.3-12.3+deb8u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/g/gtk+2.0/gir1.2-gtk-2.0_2.24.25-3+deb8u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/liba/libav/libavutil-dev_11.8-1~deb8u1+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/liba/libav/libavresample-dev_11.8-1~deb8u1+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/liba/libav/libavcodec-dev_11.8-1~deb8u1+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/liba/libav/libavformat-dev_11.8-1~deb8u1+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/liba/libav/libswscale-dev_11.8-1~deb8u1+rpi1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/g/gtk+2.0/libgtk2.0-dev_2.24.25-3+deb8u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/j/jasper/libjasper-dev_1.900.1-debian1-2.4+deb8u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tiff/libtiff5-dev_4.0.3-12.3+deb8u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/s/systemd/libudev-dev_215-17+deb8u6_armhf.deb  404  Not Found [IP: 93.93.128.193 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by arturoc** [comment]
that looks like a problem with your setup or perhaps even just a temporary problem with your connection? do you have internet connection from the raspberry?

**Comment by mianel** [comment]
My raspberry has internet connection. I tried using chrome go in to "http://mirrordirector.raspbian.org/raspbian/pool/main/g/gtk+2.0/" and when I tried to find one of the link for example "gir1.2-gtk-2.0_2.24.25-3+deb8u1_armhf.deb" I don't find it. So I don't know if is an internet problem.

**Comment by bakercp** [comment]
https://forum.openframeworks.cc/t/problem-install-in-raspberry-pi-2/27449/3

Closing this issue in favor of forum discussion.

**Comment by Crcanlix** [comment]
solucione ese error### 

>  formatiando la sd  card

 y luego flasheando el raspbian creo, no estoy seguro al flashear encima de un sistema da errores no siempre pero puede dar errores
