### ISSUE TITLE
ofxXml ; could not load the xml file

### ISSUE THREAD

**Issue by AntonioFrog** [openframeworks/openFrameworks#5727]
I am new to OpenFrameworks, and I am making a program to send Kinect DepthImage through ethernet, and change the address by edit the XML file.
But **no matter where there exist the .xml file or not, the **_XML.load("settings.xml")_**  always returns false,** i tried it on both windows and mac, always flase, is anyone could help me?
Everytime I edit the XML then run the application, the xml was rewrite by the app again.

the Code as follow:

    if( XML.load("settings.xml") ){
        message = "settings.xml loaded!";
    }else{
        
        XML.addChild("ADDRESS");
        XML.setTo("ADDRESS");
        
        XML.addChild("ADDRESS 1");
        XML.setTo("ADDRESS 1");
        XML.addChild("IP");
        XML.addChild("PORT");
        XML.addChild("PACKET SIZE");
        XML.setValue("//IP", "192.168.1.107");
        XML.setValue("//PORT", "12345");
        XML.setValue("//PACKET SIZE", "1024");
        
        XML.setToParent();
        XML.addChild("ADDRESS 2");
        XML.setTo("ADDRESS 2");
        XML.addChild("IP");
        XML.addChild("PORT");
        XML.addChild("PACKET SIZE");
        XML.setValue("//IP", "192.168.1.108");
        XML.setValue("//PORT", "12345");
        XML.setValue("//PACKET SIZE", "1024");
        
        XML.save("settings.xml");
    }

**Comment by hamoid** [comment]
Hi! Does the `examples/input_output/xmlExample` project work for you? Which OF version are you on?

**Comment by AntonioFrog** [comment]
OF 0.9.8 and I fix it now;
I delete all the space in the XML, and everything works well;
Is space not supported?

**Comment by hamoid** [comment]
Could you paste here the file that fails to load?

**Comment by AntonioFrog** [comment]
the file now:

<ADDRESS>
	<ADDRESS1>
		<IP>192.168.1.107</IP>
		<PORT>12346</PORT>
	</ADDRESS1>
	<ADDRESS2>
		<IP>192.168.1.108</IP>
		<PORT>12346</PORT>
	</ADDRESS2>
</ADDRESS>

the file before

<ADDRESS>
	<ADDRESS 1>
		<IP>192.168.1.107</IP>
		<PORT>12346</PORT>
	</ADDRESS 1>
	<ADDRESS 2>
		<IP>192.168.1.108</IP>
		<PORT>12346</PORT>
	</ADDRESS 2>
</ADDRESS>

i have put the code on github;
[https://github.com/AntonioFrog/KinectDepthImageTrans/blob/master/KinectSender/data/settings.xml](url)

**Comment by hamoid** [comment]
From https://en.wikipedia.org/wiki/XML#Well-formedness_and_error-handling `Tag names cannot contain any of the characters !"#$%&'()*+,/;<=>?@[\]^`{|}~, nor a space character, and cannot begin with "-", ".", or a numeric digit.`

I guess this issue can be closed, as it doesn't seem to be OF related.

**Comment by AntonioFrog** [comment]
I got it, thank you a lot for spending your precious time on this!
