### ISSUE TITLE
reduce compile times by using more specific header includes

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#5731]
Lately, a full (from clean) compile of openFrameworks seemed to take 3min30s on a reasonably fast 12 core machine. Also, linker and code generation times seem quite high, and it appears to take about 10 sec from changing a single line of code (inserting a line break) in ofApp.cpp to be able to see a simple app run. 

Wouldn't it be great to have a really fast change-compile-run cycle?

I did some measurements using VS2017, and set the following diagnostic compiler switch: 

* `/Bt+` (added to openFrameworksLib property page under "Command Line" -> "Additional Options")

This enables compile time measurement for individual compilation units (i.e. `.cpp` files). On average, a single file takes about 30s to compile, some files, like `ofAppRunner.cpp`, take about 48sec. 

I believe this is partly due to the way we're currently including headers:

`ofConstants.h` is included nearly everywhere:
![ofconstants](https://user-images.githubusercontent.com/423509/29707726-32eb9a4c-897e-11e7-8dee-31f79aeae308.png)

And `ofConstants.h` currently does more than its name suggests it should do: apart from setting constants, it includes glm, opengl, and tesselator. And since this header is included nearly everywhere - these headers in turn get included nearly everywhere. 

There's a switch in VS which allows you to see which headers get included in compilation: it's under 
"C/C++" -> "Advanced" -> "Show Includes" (set to Yes)

Hit compile and my bet is you'll be amazed at what you see =)

---

I found the following immediate steps could reduce comile times:

1) remove "wholesale" include of "glm/ext.hpp" (this is something glm itself recommends) from `ofConstants.h` and replace it with:

```
#define GLM_META_PROG_HELPERS
#define GLM_FORCE_SWIZZLE
#define GLM_FORCE_SIZE_FUNC
#include "glm/glm.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include "glm/gtc/quaternion.hpp"
#include "glm/gtx/quaternion.hpp"
#include "glm/gtx/matrix_transform_2d.hpp"
#include "glm/gtx/vector_angle.hpp"
```

This means only the glm headers we actually use are included. This saves about 7sec per file on average.

2) remove `boost::filesystem` and replace it with `std::experimental::filesystem` on systems/compilers which support this (saves 5 sec per file on avg)

In total these two measures reduce total compile time on my system from 3.30 min to 2.30 min - still not ideal, but about 30% faster.

---

I believe we could make things faster still, by modularizing our includes. This could also help maintaing things in the long run. Discussion in this direction seem already under way in the thread discussing our use of `using namespace std`. Note: we've discussed this a couple of times in the [past](https://github.com/openframeworks/openFrameworks/issues/2581), and the most recent discussion seems to happen [here](https://github.com/openframeworks/openFrameworks/pull/5671).

Some other areas where I believe we could get faster compile times:
* streamline - and forward-declare ofMesh -this is a heavily templated-include-only module currently, and although this might be fast to execute, templates are notoriously slow to compile
* modularize openFrameworks into a system of libraries which are linked dynamically (this will mostly help with linker-times, but might also allow us to do interesting things like real-time-compiled c++)

**Comment by hamoid** [comment]
Hi! improvements in this area are my wish #1 :) I miss the instant compilation of Processing / Java and jealous of Jon Blow's sub-second compilation times with cpp-like performance in his Jai language.

I tried to apply what you suggested (in my current project) to measure the difference but it didn't work out. 

1. The glm change seems to cause many problems where `int`s are used in the OF code which need to be replaced by `float`s. For instance in `ofTrueTypeFont.cpp`

```cpp
lastPoint = (conicPoint + lastConnic) / 2;
// should be
lastPoint = (conicPoint + lastConnic) / 2.0f;
```
Did you try this with a `hello world` or with a larger program?

2. `std::experimental::filesystem` needs to be downloaded first?

**Comment by tgfrerer** [comment]
ad 1) i think it's good that this gets caught - the intention is clearly to do a non-integer division. floats should indeed be used. I had to fix this in four or five occurrances.

2.) std::experimental whould come build-in with any modern compiler, and becomes visible if you include the system <filesystem> header

**Comment by arturoc** [comment]
std native support for filesystem is a c++17 feature but usually comes already with most compilers, as far as i know vs2017 and gcc 6 already support it.

here's code that enables it conditionally in ofFileUtils:

https://github.com/Entropy/openFrameworks/blob/entropy/libs/openFrameworks/utils/ofFileUtils.h

and the necessary flags are already there but commented out in the qtcreator project in amster

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs#L245-L252

with those two bits qtcreator will detect the compiler version and enable std's filesystem instead of boost's
