### ISSUE TITLE
Environment variables destroyed by shell script (window, msys2)

### ISSUE THREAD

**Issue by merfii** [openframeworks/openFrameworks#5740]
under windows (msys2), when execute
scripts\msys2\install_dependencies.sh
the line 35

> setx PATH "%PATH%;${MSYS2_ROOT}mingw32\\bin;${MSYS2_ROOT}usr\\bin\\"

set the local variable PATH to "$PATH$;D:\mingw32\bin;D:\usr\bin\"
The environment variable syntax $PATH$ wasn't resolved properly and old content was destroyed.

**Comment by danoli3** [comment]
Oh wow, so should be ?
```
setx PATH "{$PATH};${MSYS2_ROOT}mingw32\bin;${MSYS2_ROOT}usr\bin\"
```

**Comment by oxillo** [comment]
The command is a mix of Windows command line and Linux shell. 
Setting the PATH is useful : 
- to launch your exe by double-clicking on it. With version 0.10, you can use `make copy_dlls` to copy all required dlls to the executable folder. Setting the PATH is then no longer required
- to use IDE program (QtCreator, VsCode) that will trigger the build process. It may be necessary to set the PATH for this.

So it may be better to remove 'setx' instruction from install_dependencies and let the user handle setting the PATH as needed.

We may put some instructions in QtCreator setup guide on how to handle this task.

**Comment by oxillo** [comment]
Recently, the piece of code that is responsible of setting the PATH is blocking/freezing the execution of install_dependencies.
