### ISSUE TITLE
Feature: ofxInputField set min and max values

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#5746]
I've added some button to be able to switch if you want to change the min and max values of the ofxInputField.
It is here:
https://github.com/roymacdonald/openFrameworks/commit/58c4afbf2548faaec16220f46801345f63ab5a32
I've needed this several times and now it came really handy on a recent project I worked on.
It would be great to be able to merge it with the core.

Looking forwards for feedback.
cheers!

**Comment by roymacdonald** [comment]
Any feedback on this? @arturoc @frauzufall 
cheers

**Comment by arturoc** [comment]
can you post a couple of screenshots of how this works?

**Comment by roymacdonald** [comment]
These tiny buttons appear on the right side of the inputfield from these you can select to edit either the slider value, its min or max. the default is the slidervalue.
I had to implement a small button class to make this work, although I didn't check if I would be able to achieve the same by extending ofxToggle. Anyway, This simple button class could be useful in other parts of ofxGui, like the save and load buttons (currently, these dont provide any visual feedback while hovering or pressing).
The buttons images are hardcoded just like floppy disk in ofxPanel.
If this get to the core it would also be needed to save and load the min and max values from the xml.

<img width="223" alt="screen shot 2017-10-19 at 13 13 37" src="https://user-images.githubusercontent.com/974878/31781631-524f6b30-b4cf-11e7-9fcc-0b562571fea7.png">
<img width="252" alt="screen shot 2017-10-19 at 13 14 06" src="https://user-images.githubusercontent.com/974878/31781632-5274d5fa-b4cf-11e7-9241-352bcd4ca75b.png">
<img width="257" alt="screen shot 2017-10-19 at 13 14 15" src="https://user-images.githubusercontent.com/974878/31781633-52963d44-b4cf-11e7-97bf-2889a3659c54.png">

**Comment by arturoc** [comment]
how does that look if you change the default height or font? seems like it will be too small for retina screens too, no?

**Comment by roymacdonald** [comment]
It doesn't change :( I didn't consider what you point out. 
The text of these buttons is really a bitmap, as making these with a font would need to include the font somehow, which became really cumbersome, and the ofBitmapFont was to large to fit in that space and it did not shrink well.
I have a retina screen, but I use it in the "best" setting, which doesnt shrink eveything. Just tested it in retina mode and it is unreadable, although still usable.
As for the font, it could be that if the default height is changed to a larger size, where it can fit, then it is used instead of the bitmaps. This would apply for both ofBitmapFont and a custom font.
I'll implement all this and let you know. 
Glad that you pointed this out.
As for the retina screen I see no solution using this button arrangement.
cheers

**Comment by arturoc** [comment]
i think using a bitmap is fine by now, but perhaps it can be scaled up and down to fit the size of the control?

**Comment by roymacdonald** [comment]
it could be but might look odd when enlarging. I'll give it a try though. I'll post results next week as I am super busy right now.
best

**Comment by roymacdonald** [comment]
Hi there!
I just updated this feature, it is in https://github.com/roymacdonald/openFrameworks/tree/feature-ofxInputFieldMinMax

Features:
- When entering the input field of a slider, by right clicking on it, now 3  buttons are displayed on the right side, min, val and max. val is the default selection. These 3 buttons are stacked vertically. by clicking on any of these you can change the sliders value, minimum and maximum. As val is the default, if you ignore this buttons the input field will work just in the same way as it is right now.
- A minimal bitmap button is hardcoded in order to fit the default height.
- When the height of the slider is changed it will automatically choose the ofBitmapFont once it can fit in the height. If a custom ttf font is being used for the gui it will use it if the height of the sliders is enough.
-The buttons highlight when hovered.

I made a small private button class to handle this buttons as it was cleaner than not using a class yet the ofxButton class didn't provide what I needed.

Screenshots:
Buttons with hardcoded minimal font
<img width="287" alt="screen shot 2018-01-03 at 12 04 49" src="https://user-images.githubusercontent.com/974878/34640218-5b9720de-f2cd-11e7-9cfc-50d75097c26b.png">
buttons with custom TTF font
<img width="318" alt="screen shot 2018-01-03 at 12 06 36" src="https://user-images.githubusercontent.com/974878/34640219-5bb5dccc-f2cd-11e7-8902-5273dce8e526.png">
buttons with ofBitmapFont
<img width="280" alt="screen shot 2018-01-03 at 12 06 25" src="https://user-images.githubusercontent.com/974878/34640220-5bd3fa5e-f2cd-11e7-9733-3bb24d8e7fa1.png">

TODO:
save/load the min and max with the ofParameter

I've been using it a lot. It is super helpful. Hope this gets merged soon.
should I PR?

best!

**Comment by arturoc** [comment]
yes please send a PR, we're about to release 0.10 so i won't merge it yet but ping me after the release and i'll merge it asap so we can test it for the next release

**Comment by roymacdonald** [comment]
sure! I didnt knew that 0.10 was so close. is there anything I can help with its release?
best

**Comment by ofTheo** [comment]
sorry - just seeing this for the first time, curious what the typical use case for this might be? 

I can see the case for being able to input the slider value with the keyboard, but I would imagine min and max values would be set for a reason in code. Plus changing them while the app is running is not persistent, so I don't quite get it.  

Maybe I am missing something? :)

**Comment by roymacdonald** [comment]
Hi @ofTheo 
Well I've found my self several times having to manually set the min and max values, for instance setting the position of an element where simply keeping the min and max values for the full possible positions range leaves you with a super coarse slider. Also you might want to fine tune a parameter, so setting its min and max during runtime will allow you to do such. 

Right, there's no persistance on this, although I am working on adding it, by having the min and max values stored into the xml/json.

Maybe it could be an optional feature, that could be enabbled/disabled.

does it make any sense to you?

**Comment by roymacdonald** [comment]
Hi @ofTheo,
Thanks for the feedback. I see your point and I agree with you quite much. Being honest I have not used this feature since I made this PR, although at that moment it was really handy but as you say. The issue about allowing users to set the min and max when it shouldnt be allowed is a really good reason for not having this feature. 
Maybe it might be better to move this into something like an addon just in case anyone needs it.
cheers.

**Comment by ofTheo** [comment]
Thanks @roymacdonald ! 

I appreciate the reply :) 
I'll close this for now.   Also if you have trouble getting feedback on an issue or PR def tag me or shoot me an email. Its sometimes hard to keep track on all the Github issues during busy stretches. 

Many thanks! 
Theo

**Comment by roymacdonald** [comment]
Hey @ofTheo  no prob. :D
I'll certainly will tag you. 
If there was a way for me to get automatic notifications of new issues I would be happy to help on following those and/or tag whom ever is appropriate. 
cheers.

**Comment by arturoc** [comment]
Hey sorry i completely missed the discussion, i don't find it particularly useful either but wasn't opposed to it as long as it was well implemented and probably optional instead of always on

In any case @roymacdonald if you think it's not so useful anymore glad to just close it for now
