### ISSUE TITLE
ofOpenALSoundPlayer::setPositionMS(int ms) set wrong position when streaming audio

### ISSUE THREAD

**Issue by hiroMTB** [openframeworks/openFrameworks#5749]
probably this is the problem.

```
ofOpenALSoundPlayer::setPositionMS(int ms){

        ...

	if(streamf){
		sf_seek(streamf,float(ms)/1000.f*samplerate*channels,SEEK_SET);
		stream_samples_read = 0;    <- should change position after seek
	}else{

        ...

```

**Comment by hiroMTB** [comment]
I noticed we should pass frame number without multiple of channel numbers.
see this link.
http://www.mega-nerd.com/libsndfile/api.html#seek

So correct code will be something like,

...

	if(streamf){
		stream_samples_read = sf_seek(streamf,float(ms)/1000.f*samplerate,SEEK_SET);
		stream_samples_read *= channels;
	}else{

        ...

**Comment by arturoc** [comment]
can you send a pull request?

**Comment by hiroMTB** [comment]
done.
sorry PR is the one to my own fork. ;-)
