### ISSUE TITLE
initialization state of OF in ctors/dtors: 

### ISSUE THREAD

**Issue by johanjohan** [openframeworks/openFrameworks#5750]
i am using of 0.9.8 on win10. let's say that i want to share a sqlite database between apps. 
as i want to share paths to the DB in constructors and destructors, i realized that several OF functions are not yet or no more initialized in ctors or dtors:

- the ofLog() functionality
- the ofFilePath:: functionality (boost paths are crashing)
- ofToDataPath()

i am talking about something like:
```
	someClassCtor()
	{
		string sPath = ofFilePath::getAbsolutePath("data/../../../../../apps/logger-sqlite/", false);
		sPath = ofFilePath::getCurrentExeDir() + "data/../../../../../apps/logger-sqlite/";
                spath = ofToDataPath(../../../../../apps/logger-sqlite/");
		sPath = ofFilePath::removeTrailingSlash(sPath) + "/";
		return sPath;
	}
```
above functions may not be valid in ctors and dtors. if ofDataPath() has an issue it creates another issue calling the unitialized ofLog().

i am repeatedly running into this issue and have not figured out a workaround that works on all platforms ( i use win and linux/rpi). it is especially an issue when i work with threads and dtors. and i wish to keep the relative path system of OF, so i can share the apps between platforms and OF versions.

any hints? thx!

**Comment by jvcleave** [comment]
Assuming you want to avoid pointers, the way I approach this is to create a `setup` method and call it in `ofApp::setup`

```
string someClass::setup()
	{
		string sPath = ofFilePath::getAbsolutePath("data/../../../../../apps/logger-sqlite/", false);
		sPath = ofFilePath::getCurrentExeDir() + "data/../../../../../apps/logger-sqlite/";
                spath = ofToDataPath(../../../../../apps/logger-sqlite/");
		sPath = ofFilePath::removeTrailingSlash(sPath) + "/";
		return sPath;
	}
```

**Comment by arturoc** [comment]
the only thing that is not warrantied to work is opengl calls and only on ios and android everything else should work on constructors without problem so if you have any trouble with a specific function it's probably a bug. can you post a small example that shows the issue for every function that is problematic?  that would help a lot finding out what might be going on

**Comment by johanjohan** [comment]
Simple example to trigger the issue:

```
#include "ofApp.h"

// >>> uncomment any of the below and cause a crash on OF 098 on win10 vs2015

#define THE_PATH "../../../../../addons/test.txt"

class ctorCrash {
	const string sPath = string(THE_PATH); // works with this, but i believe it wouldnt find the path on linux? may need to be "data/" + string(THE_PATH)
	//const string sPath = ofToDataPath(THE_PATH, true);
	//const string sPath = ofToDataPath(THE_PATH, false);
	//const string sPath = ofFilePath::getAbsolutePath("data/" + string(THE_PATH) , false);

public:

	ctorCrash() {
		cout << "sPath: " << sPath << endl;
		//ofLogError("ctorCrash::ctorCrash") << sPath;
		//ofLogNotice("ctorCrash::ctorCrash") << sPath;
		//cout << "ctorCrash::ctorCrash: does file exist: " << (ofFile::doesFileExist(getPath()) ? "yes" : "no") << endl;
	}

	string getPath() { return sPath; }
};

ctorCrash theCrashCausedByCtor; // crashes

//--------------------------------------------------------------
void ofApp::setup() {
	ctorCrash doesNotCrashHere; // all ok if declared here
	ofLogNotice("setup") << "does file exist: " << (ofFile::doesFileExist(doesNotCrashHere.getPath()) ? "yes" : "no");
}

```

@jvcleave: yes thx, but as these are constants and possibly a lot of them, i prefer to have them auto initalized

**Comment by johanjohan** [comment]
one more:

```
someCtor()
{
    vector<ofColor> col ={ofColor::red,ofColor::green,ofColor::blue,ofColor::cyan,ofColor::yellow,ofColor::magenta};
}
```
colors are all set to 0,0,0,0

**Comment by johanjohan** [comment]
as i suggested, it is like this on win & linux

```
#if defined TARGET_WIN32
		string sPath = "../../../../../addons/ofx3JCurlSSLWilly/ssl/cacert.pem";
#else if defined TARGET_LINUX
		string sPath = "data/../../../../../addons/ofx3JCurlSSLWilly/ssl/cacert.pem";
#endif
```

that's why ofToDataPath() would be handy in ctors, but well, not too bad once you know...

**Comment by arturoc** [comment]
i've just fixed ofLog. The main problem though is that you are creating the instance of that class as an static variable so the order of creation is undefined and it's really hard to guaranty that all initializations are done by the time that variable is constructed.

If you move the variable inside ofApp instead it will work even as it was before my fix.

Some things like ofColor constants are impossible to make work as you are expecting unless we convert them into functions (see https://github.com/openframeworks/openFrameworks/pull/5756) and since the way you are using it (by having variables directly in the file, using constructors is ok) is known to be problematic i don't think it's worth changing ofColor constants into functions

If you find some similar problem please open a new issue since there's chances it can be solved, mostly if it's a function call.

**Comment by johanjohan** [comment]
thx arturo. it does not seem to affect many people, so i will keep working around it. 
Q: is there a safe way (std::) to work with platform independent relative file paths in ctors?

**Comment by johanjohan** [comment]
Q: you say "you are creating the instance of that class as an static variable ". would it work if i pass the paths using functions() in ctors?

**Comment by arturoc** [comment]
> Q: is there a safe way (std::) to work with platform independent relative file paths in ctors?

that is solved already but it would work even before as long as you create your variables as instance variables or inside functions

> Q: you say "you are creating the instance of that class as an static variable ". would it work if i pass the paths using functions() in ctors?
not sure what you mean, i think this is more of a question about how to use OF rather than an issue can you post in the forum instead?

**Comment by johanjohan** [comment]
@arturoc  one more: also disfunctional in ctors is ofTrueTypeFont:
calling font.load(...) crashes in a ctor.
i am aware that there are workarounds for all these issues. but as there is incosistent behaviour regarding the use of OF calls in ctors, i suggest to document this behaviour or make it consistent.

**Comment by arturoc** [comment]
is this in a variable declared on a file or on an class/function? if it's in a file the behavior is undefined cause the order of initialization is undefined

**Comment by johanjohan** [comment]
@arturoc it is a variable on a class:

```
ofTrueTypeFont	font;

called in a ctor, it crashes:
bool b = font.load(...);

the same happens with a pointer initialized in a ctor:

ofTrueTypeFont	*pFont = nullptr;
pFont = new ofTrueTypeFont();
bool b = pFont->load(_sFontPath.empty() ? sFontPathDef : _sFontPath, _fontsize, true, true);
```

**Comment by johanjohan** [comment]
might be due to call of odDataPath() in ofTrueTypeFont.cpp

```
static std::shared_ptr<FT_FaceRec_> loadFontFace(const std::string& _fontname, int _fontSize, std::string& filename){
    FT_Face face;
	std::string fontname = _fontname;
	filename = ofToDataPath(fontname,true);
       ....
```

**Comment by johanjohan** [comment]
@arturoc sorry to keep posting on a closed issue, but i keep finding related issues:

poco is not initialized in ctors:

below func works in setup but not in a ctor


```
 int64_t epochMicrosFromDateTime(const string &_sDateTime, const string sFormat) {
		 Poco::DateTime dt;
		 int tzd;
		 if (!DateTimeParser::tryParse(sFormat, _sDateTime, dt, tzd)) {
			 cerr << "epochMicrosFromDateTime: " << endl;
			 cerr << "error DateTimeParser::tryParse: " << _sDateTime << endl;
			 cerr << "error sFormat: " << sFormat << endl;
			 ofSleepMillis(5000);
			 return Timestamp().epochMicroseconds();
		 }

		 return dt.timestamp().epochMicroseconds();
	 }
```

**Comment by arturoc** [comment]
can you open a new issue for each bug you find like this? also please post a full small example showing how you are using it, not only the failing function but how you are creating the variable. that way it's easy to track each individual problem

thanks!
