### ISSUE TITLE
ofCamera bug introduced with switch to glm

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#5751]
I found out a bug in ofCamera's lens offset. When ofMatrix4x4 was being used its `translate(...)` method applied a post mult over the matrix, while glm::translate(glm::mat4, glm::vec3) works as premult.
The fix is quite simple.
It's here https://github.com/roymacdonald/openFrameworks/tree/fix-ofCamera_lensOffset_glm_math
the specific line that changed is
https://github.com/roymacdonald/openFrameworks/blob/fix-ofCamera_lensOffset_glm_math/libs/openFrameworks/3d/ofCamera.cpp#L159

Should I PR?
@arturoc @bakercp @elliotwoods 

Cheers

**Comment by bakercp** [comment]
Yes, PR 👍
