### ISSUE TITLE
ofTrueTypeFont not loading default system fonts

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#5761]
ofTrueTypeFont will not load system fonts, either by explicitly passing their name or by using `OF_TTF_SANS`, `OF_TTF_SERIF` or `OF_TTF_MONO`.

The fix is quite simple. 
I'll PR asap.

(The guideline says that I have to make an issue before PRing. In cases like this, is it really needed to have an issue? Isn't enough just with the PR?)

**Comment by arturoc** [comment]
yes a PR is enough, an issue is only needed if you plan to send a new feature or a fix that is not obvious and might introduce some side effects

**Comment by roymacdonald** [comment]
great! 
gracias.
