### ISSUE TITLE
NEWBIE! All sorts of errors while running tutorial

### ISSUE THREAD

**Issue by BLCKPSTV** [openframeworks/openFrameworks#5773]
When running the tutorial => http://openframeworks.cc/setup/xcode/
The everything works part. I stumble on numerus errors.
And no clue what causes them.
I'm pretty sure I installed all the Xcode dependencies. 
![schermafbeelding 2017-10-08 om 14 26 57](https://user-images.githubusercontent.com/6031569/31316813-5c391486-ac35-11e7-983a-a7163ad10a8d.png)

I know i'm giving vague information, but I have no clue where to start debugging these. And because there are so many, i'm pretty sure its either a version wise error or a general setting error?

**Comment by bakercp** [comment]
These are warnings, not errors. These warnings should already be fixed in the latest version of openframeworks.  If you are using the master branch, then please reopen this issue.  If you are a new user with questions, please post an issue on the forum. Im. Losing this as it has already been fixed.
