### ISSUE TITLE
ofEasyCam drifts when moving mouse

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#5774]
I solved this a while ago but it's broken again now, my latest commit on ofEasyCam still works properly:

https://github.com/openframeworks/openFrameworks/commit/e6c96b11ec2b25fcb547110f74c87df6d0ecef48#diff-e167c292c98022e716ec35e4d559f763

so this must have been introduced in some of the latest additions from @roymacdonald from 3b440a1617731d5fc32dbd4613aadc409a409213 to ae0e8794d50714d6fbc2b8c285a798cfbdd7f08a

roy, can you check what's going on? to test it just rotate the move the mouse around the center of the screen, in my latest commit the camera stays where it was originally if you end the movement where you started it but now it drifts and the camera rolls onto itself

**Comment by roymacdonald** [comment]
Hi arturo! 
Sure, I'll take a look at it now.

**Comment by roymacdonald** [comment]
@arturoc check out this https://github.com/roymacdonald/openFrameworks/commit/691e6414e734cdb64ca7175e65b3d66b2a759d28
I haven't tested it thoroughly, but at least it "passes" the test you describe.
I'll test it more tomorrow.
cheers!

**Comment by roymacdonald** [comment]
@arturoc did you give a try to my solution? It seems to revert the issues that you describe, as well as making sense why this issues arose.
best!

**Comment by roymacdonald** [comment]
Just added a fix to the translation that was introduced with the change I made for the rotation drift. Now all the interaction modes work correctly.
Should I PR?

**Comment by arturoc** [comment]
yes please

**Comment by roymacdonald** [comment]
@arturoc did you check the PR? 
cheers

**Comment by roymacdonald** [comment]
close issue please! :)

**Comment by arturoc** [comment]
thanks!

**Comment by roymacdonald** [comment]
Hey @arturoc I can go through closing and/or labeling issues and PRs if it is of any help. I would need the necessary permissions to do so.
best
