### ISSUE TITLE
Cannot install openFrameworks on Ubuntu Linux

### ISSUE THREAD

**Issue by arrangereality** [openframeworks/openFrameworks#5786]
I am trying to install openFrameworks on my Ubuntu Linux laptop, but cannot seem to get past the initial installation due to some errors with using install_dependencies.sh and compileOF.sh. Following this links instructions: http://openframeworks.cc/setup/linux-install/

I run:
cd OF/scripts/linux/ubuntu
sudo ./install_dependencies.sh

I get:
Installing libgl1-mesa-dev-hwe-16.04
E: Unable to locate package libgl1-mesa-dev-hwe-16.04
E: Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
E: Couldn't find any package by regex 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04
Reading package lists... Building dependency tree... Reading state information...
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

I run:
cd OF/scripts/linux
./compileOF.sh -j3

i get:
logname: no login name
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl gl glu glew libmpg123 
makefileCommon/config.shared.mk:294: *** cairo not installed. Did you run the latest install_dependencies.sh? gstreamer-app-1.0 not installed. Did you run the latest install_dependencies.sh? gstreamer-video-1.0 not installed. Did you run the latest install_dependencies.sh? freetype2 not installed. Did you run the latest install_dependencies.sh? fontconfig not installed. Did you run the latest install_dependencies.sh? sndfile not installed. Did you run the latest install_dependencies.sh? openal not installed. Did you run the latest install_dependencies.sh? openssl not installed. Did you run the latest install_dependencies.sh? glew not installed. Did you run the latest install_dependencies.sh?.  Stop.
there has been a problem compiling Debug OF library
please report this problem in the forums

**Comment by Paul92** [comment]
Try the method suggested in the answers to this question: https://askubuntu.com/questions/893756/terminal-cant-install-something-named-libgl1-mesa-dev-hwe-16-04/893766

If it doesn't work, can you please indicate which version of Ubuntu are you using?

**Comment by arrangereality** [comment]
I'm on an Ubuntu 16.0.4 LTS. I was able to get openFrameworks up and running by saying "No" to the libgl1-mesa-dev-hwe-16-04 ask, which is the first question, and yes to all the others. I am now able to run complile openFrameworks examples.
