### ISSUE TITLE
ofImage::setFromPixels() causes crash on iOS

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5790]
Hi, I just figured out calling ofImage::setFromPixels() causes crash on iOS while it works fine on MacOS.

Here's my test code.

    ofFbo fbo;
    ofImage img;

    //--------------------------------------------------------------
    void ofApp::setup(){

        ofSetBackgroundColor(0);
        
        //allocate an image space
        img.allocate(ofGetWidth(), ofGetHeight(), OF_IMAGE_COLOR_ALPHA);
        
        //clear and allocate a fbo
        fbo.begin();
        ofClear(0,0,0,0);
        fbo.end();
        fbo.allocate(ofGetWidth(), ofGetHeight(), GL_RGBA);
        
        //draw an ellipse to the fbo
        fbo.begin();
        ofClear(0,0,0,0);
        ofSetColor(255);
        ofDrawEllipse(ofGetWidth()/2, ofGetHeight()/2, ofGetWidth(), ofGetHeight());
        fbo.end();
        
        //copy pixels from fbo to image
        ofPixels pixels;
        fbo.getTexture().readToPixels(pixels);
        img.setFromPixels(pixels);
    }

    //--------------------------------------------------------------
    void ofApp::update(){
        
    }

    //--------------------------------------------------------------
    void ofApp::draw(){
        
        //draw the image
        img.draw(0, 0, ofGetWidth(), ofGetHeight());
    }

And this is the result you will see if you run the code on MacOS.
<img width="400" alt="screen shot 2017-10-27 at 12 07 02 am" src="https://user-images.githubusercontent.com/24947986/32069153-447a45c6-bac3-11e7-8206-a43d3a017e74.png">

However, if you run the same code on iOS, it crashes on startup with the following error.
<img width="1440" alt="screen shot 2017-10-27 at 12 08 43 am" src="https://user-images.githubusercontent.com/24947986/32069166-4c848326-bac3-11e7-8d6b-7b15568cadb1.png">

It doesn't produce any error if I comment out `img.setFromPixels(pixels);` 

Can anyone confirm that is a bug? 
And is there any other way to copy pixels from ofFbo to ofImage?
Thanks!

**Comment by cuinjune** [comment]
I just tested this on Android and the same problem occurred.
Just like on iOS, It crashes when calling `img.setFromPixels(pixels);`
And if I add `pixels.allocate(ofGetWidth(), ofGetHeight(), OF_PIXELS_RGBA);` after `ofPixels pixels;` it doesn't crash but doesn't draw properly. All I see is a black screen.

**Comment by ofZach** [comment]
what happens if you do this instead: 

fbo.readToPixels(pixels);

it seems like there is code in that function to handle opengles

**Comment by cuinjune** [comment]
Hey That fixed the problem on iOS. I will see if it also fixes the problem on Android and post here soon.
Thank you so much!
