### ISSUE TITLE
ofNode::clearParent give me a exception when accessing to the parent and parent's value is <Unable to read memory>

### ISSUE THREAD

**Issue by GinesMendoza** [openframeworks/openFrameworks#5817]
![image](https://user-images.githubusercontent.com/9090336/33807593-7947392e-ddd9-11e7-9dc7-d5a3891f3e55.png)

I'm using ofxNI2 to get the skeleton of the body (to get the skeleton I'm using the example from the repository 'https://github.com/satoruhiga/ofxNI2/tree/master/example-user-tracker' ) but when I'm out of the kinect the method clearParent throw the exception 'Exception thrown: read access violation.
this was 0xFFFFFFFFFFFFFFF7.'

any suggestions!! :)

**Comment by edap** [comment]
Please, use the forum for this kind of question. To me, it looks like the node you are querying has no parent. Open a question on the forum and I will try to help you there

**Comment by danzeeeman** [comment]
you're also using an old addon... I would post on the ofxNI2 issues page to see if @satoruhiga would help you out...  The addon might need to be updated to support the API changes within OF.
