### ISSUE TITLE
ofLoadURL can not resolve https on android

### ISSUE THREAD

**Issue by i-n-g-o** [openframeworks/openFrameworks#5819]
on current master
test-code:

```
ofHttpResponse response = ofLoadURL("https://google.com");

ofLog() << response.status;
ofLog() << response.error;
```

output:
```
-1
Peer certificate cannot be authenticated with given CA certificates
```

from curl error-buffer:
"SSL certificate problem: unable to get local issuer certificate"

removing SSL checkup makes https resolve:
```
curl_easy_setopt(curl.get(), CURLOPT_SSL_VERIFYPEER, 0);
curl_easy_setopt(curl.get(), CURLOPT_SSL_VERIFYHOST, 0);
```

tested with:
Android 5.0
API 21

**Comment by hiroMTB** [comment]
I also see this error and your two lines saved my night. Thanks.
Tested on oF master repo, Genymotion emulator, Android API 19

**Comment by hiroMTB** [comment]
This is already in the latest code. We can close this.

https://github.com/openframeworks/openFrameworks/blob/0e806391eeacf6395eb34f9263c1af75e07b8c35/libs/openFrameworks/utils/ofURLFileLoader.cpp#L180-L183

**Comment by arturoc** [comment]
thanks!
