### ISSUE TITLE
debian install - curl dependency missing

### ISSUE THREAD

**Issue by d-j-a-y** [openframeworks/openFrameworks#5823]
When installing on debian strech , poco is recompiled, but will failed out of the box, curl is needed.

**Comment by bakercp** [comment]
What version are you trying to install on Debian stretch?

**Comment by d-j-a-y** [comment]
sorry to forgot that crutial info ! 0.9.8

(has i understood, this version is not supported in deb9, right now i'm looking at 20170714_linux64gcc6_nightly)

**Comment by bakercp** [comment]
Yep, it's not supported currently.  The mater branch of nightly builds should work though.  Closing!
