### ISSUE TITLE
ofFbo.getTexture().bind()/unbind() doesn't work properly on iOS

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5826]
Hi, I figured out calling ofFbo.getTexture().bind()/unbind() methods doesn't bind the FBO's texture correctly on iOS.

Here's my simple test code.

in ofApp.h

    ofFbo fbo;
    ofMesh mesh;

in ofApp.cpp

    //--------------------------------------------------------------
    void ofApp::setup(){
        
        ofDisableArbTex();
        ofSetCircleResolution(50);
        
        int fboWidth = ofGetWidth()/4;
        int fboHeight = ofGetHeight()/4;
        
        fbo.allocate(fboWidth, fboHeight, GL_RGB);
        
        fbo.begin();
        ofClear(255, 0, 0, 255);
        ofSetColor(0, 255, 0);
        ofDrawEllipse(fboWidth/2, fboHeight/2, fboWidth, fboHeight);
        fbo.end();
        
        mesh = ofMesh::plane(fboWidth, fboHeight);
    }

    //--------------------------------------------------------------
    void ofApp::update(){
        
    }

    //--------------------------------------------------------------
    void ofApp::draw(){
        
        fbo.draw(0, 0);
        
        ofTranslate(ofGetWidth()/2, ofGetHeight()/2);
        fbo.getTexture().bind();
        mesh.draw();
        fbo.getTexture().unbind();
    }

If I run this code on MacOS, it draws correctly as the screenshot below.
<img width="768" alt="macosscreenshot" src="https://user-images.githubusercontent.com/24947986/34287144-a2d661b8-e728-11e7-95dc-874983c4d56b.png">

But If I run the same code on iOS, the bound texture is not drawing correctly.
![ipadscreenshot](https://user-images.githubusercontent.com/24947986/34287148-a76fc688-e728-11e7-9cde-72c5cb8b6b4c.jpg)

When I print the texCoords of the plane mesh, it is correctly set. so I don't think it is ofMesh's problem but I think it is ofFbo's texture's problem.

Could any one please give me an advice on fixing this issue?
Thanks in advance!

**Comment by hamoid** [comment]
Is it because in GLES the textures have to be power of 2? I think it's automatically increasing the size of the texture. I wrote this in my own program, maybe it helps you figure out the issue? 

```cpp
            // Resizing the mask is apparently needed in GLES,
            // because it works with power of 2 textures.

            // Even if we had the mask be the same size as the video,
            // it would be shown too small. It looks like internally
            // it would enlarge the texture from 1280x304 to 2048x512,
            // leaving empty space on the right and bottom borders.
            // Then it would scale it down to 1280x304, keeping
            // the empty area, and the mask would be way too small.

            // So I increased the mask to 2048x512, and scale it down
            // to whatever the texture is using as size.
            auto & t = tutorialPlayer.getTexture();
            auto & td = t.getTextureData();
            tutorialMask.resize(static_cast<int>(td.tex_w),
                                static_cast<int>(td.tex_h));
```

**Comment by ofZach** [comment]
ofMesh::plane() is just giving between 0-1 it looks like for the texture coordinate: 

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/3d/ofMesh.inl#L1877-L1878

but in the case of ios, our internal texture may be larger then the overall size of the requested amount since it's only using power of 2 textures.   maybe ofMesh::plane() needs to be smarter about this?

If it's helpful,  usually do the mesh myself, with the helper functions: 

```
ofMesh m;
m. addTexCoord(fbo.getTeture().getCoordFromPct(0,0));
m. addTexCoord(fbo.getTeture().getCoordFromPct(1,0));
m. addTexCoord(fbo.getTeture().getCoordFromPct(0,1));
m. addTexCoord(fbo.getTeture().getCoordFromPct(1,1));
```

**Comment by cuinjune** [comment]
@hamoid @ofZach Thanks for the ideas.
I used the following trick to fix the problem.
Once the ofMesh is set, I modify the texture coordinates.

Based on the above example, I simply added the following code below `mesh = ofMesh::plane(fboWidth, fboHeight);` in `setup()`.

```
#if defined(TARGET_OF_IOS)
    ofPolyline polyline(mesh.getVertices());
    const ofRectangle box = polyline.getBoundingBox();
    const float widthRatio = static_cast<float>(box.width) / ofNextPow2(box.width);
    const float heightRatio = static_cast<float>(box.height) / ofNextPow2(box.height);
    for (size_t i=0; i<mesh.getNumTexCoords(); ++i)
        mesh.setTexCoord(i, mesh.getTexCoord(i) * ofVec2f(widthRatio, heightRatio));
#endif
```
And then the mapped texture is correctly viewed on iOS.
The fix applies to other mesh shapes like box, sphere... etc.
While this seems to work, it's kinda hacky and it should be implemented inside OF class anyway. (which I have no idea how to do it properly)
Therefore, I still look forward to finding the better solution.

**Comment by cuinjune** [comment]
I could fix this issue by commenting out the below code in ofTexture.cpp (line 421)

```
//		if(ofGLSupportsNPOTTextures()){
//			texData.tex_w = texData.width;
//			texData.tex_h = texData.height;
//		}else{
//			//otherwise we need to calculate the next power of 2 for the requested dimensions
//			//ie (320x240) becomes (512x256)
//			texData.tex_w = ofNextPow2(texData.width);
//			texData.tex_h = ofNextPow2(texData.height);
//		}
```

And then insert this one right below.

```
texData.tex_w = texData.width;
texData.tex_h = texData.height;
```

Now binding the texture to shapes works correctly after the fix on iOS.
Can any one confirm this fix please?

**Comment by ofTheo** [comment]
this issue is mainly due to the fact that you are not setting the texture coords for the plane mesh.  
usually you would do something like zach suggested: 

```
ofMesh m;
m. addTexCoord(fbo.getTeture().getCoordFromPct(0,0));
m. addTexCoord(fbo.getTeture().getCoordFromPct(1,0));
m. addTexCoord(fbo.getTeture().getCoordFromPct(0,1));
m. addTexCoord(fbo.getTeture().getCoordFromPct(1,1));
```

I don't think this is a bug as far as I can tell. 

If you do the above - does it work as expected without the change to ofTexture?

**Comment by ofTheo** [comment]
I'll re-open if there are still issues. 

Can you try this code to confirm: 
 
```

//--------------------------------------------------------------
void ofApp::setup(){
    
    ofDisableArbTex();
    ofSetCircleResolution(50);
    
    int fboWidth = ofGetWidth()/4;
    int fboHeight = ofGetHeight()/4;
    
    fbo.allocate(fboWidth, fboHeight, GL_RGB);
    
    fbo.begin();
    ofClear(255, 0, 0, 255);
    ofSetColor(0, 255, 0);
    ofDrawEllipse(fboWidth/2, fboHeight/2, fboWidth, fboHeight);
    fbo.end();
    
    mesh = ofMesh::plane(fboWidth, fboHeight);
    mesh.clearTexCoords();
    mesh.addTexCoord(fbo.getTexture().getCoordFromPercent(0,0));
    mesh.addTexCoord(fbo.getTexture().getCoordFromPercent(1,0));
    mesh.addTexCoord(fbo.getTexture().getCoordFromPercent(0,1));
    mesh.addTexCoord(fbo.getTexture().getCoordFromPercent(1,1));
}

//--------------------------------------------------------------
void ofApp::update(){
    
}

//--------------------------------------------------------------
void ofApp::draw(){
    
    fbo.draw(0, 0);
    
    ofTranslate(ofGetWidth()/2, ofGetHeight()/2);
    fbo.getTexture().bind();
    mesh.draw();
    fbo.getTexture().unbind();
}

```

**Comment by hamoid** [comment]
I find it confusing to request a size but get a different one with no warning, even if it's not a bug. In my app it was not easy to debug (where the size is specified in a json file and different classes and addons are involved in drawing the fbo).

Would it make sense to notify the user that the size was changed?

**Comment by arturoc** [comment]
i don't think ww need power of two in most devices nowadays and it's something we can check. we are doing so in desktop gl if i remember well and we can surely do the same on gles

**Comment by cuinjune** [comment]
@ofTheo I'm sorry for the delay. Yes, your test code works fine on iOS without the problem.
But don't ofMesh's built-in primitives have default texture coordinates?
I mean if you create ofMesh::plane() it should have default vertices, normals and texture coordinates so users can use the mesh immediately. And it all works fine on Desktop platforms without having to explicitly set the texture coordinates. If users should always reset the texture coordinates anyway, what's the point of having the default texture coordinates?
