### ISSUE TITLE
Problem with poco version during install OF_v0.9.8

### ISSUE THREAD

**Issue by zanart1984** [openframeworks/openFrameworks#5834]
Hello world! And happy new year !
 
"""--- I'm a new linux user and an artist. Would to install OF but i've a message that explain to me... :

All packages were installed correctly

It seems you are running gcc 5 or later, due to incomatible ABI with previous versions
we need to recompile poco. This will take a while
Press any key to continue... 
 ----- poco -----

 Downloading "poco"

SHA== https://github.com/pocoproject/poco
/home/zan/Téléchargements/of_v0.9.8_linux64_release/scripts/apothecary/formulas/poco/poco.sh: line 36: curl: command not found

 ^ Received error ^
logname: no login name
chown: cannot access 'build/poco': No such file or directory  """

I've tried recompiled poco but i've the same message again and again. So i've uninstall poco and gcc g++. The same thing is happened. I read a lot of issues and documents but The game is over !

i've ubuntu 16.04, gcc 5 or later version.

PLEASE ! HELP MEEEeeeeee

**Comment by hamoid** [comment]
Happy new year :)

Your error above is telling you that `curl: command not found`. Maybe try installing curl? :)

In Ubuntu it would be `sudo apt-get install curl`. Cheers!

**Comment by zanart1984** [comment]
THX a lot hamoid !
You've resolved my problem. 
But now the problem is:

" Finished "poco"
logname: no login name"

Why i need a logname? Do you have an idea ?

Greetings from France

**Comment by arturoc** [comment]
not sure where that's coming from but if poco has finished compiling try running any of the examples, it should work already.

**Comment by arturoc** [comment]
i'm going to close this since this problem is solved in master already but feel free to keep posting if it doesn't work for you

**Comment by zanart1984** [comment]
Hi Arturo!
All is okay! The logname isn't a problem. OF is compiled ands works...
Thx everybody for the help.

Greetings from France
