### ISSUE TITLE
Bug in nightly build 01/07/2017 compiling example

### ISSUE THREAD

**Issue by BoredBored** [openframeworks/openFrameworks#5835]
My OS: Ubuntu

/usr/bin/ld: /home/abc/Downloads/of_v20170714_linux64_release/libs/kiss/lib/linux64/libkiss.a(kiss_fftr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/abc/Downloads/of_v20170714_linux64_release/libs/tess2/lib/linux64/libtess2.a(tess.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/abc/Downloads/of_v20170714_linux64_release/libs/tess2/lib/linux64/libtess2.a(mesh.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/abc/Downloads/of_v20170714_linux64_release/libs/tess2/lib/linux64/libtess2.a(sweep.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/abc/Downloads/of_v20170714_linux64_release/libs/tess2/lib/linux64/libtess2.a(dict.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

In the current 0.9.8 release there is something in the qbs that causes an error:
ERROR: /home/abc/OF/libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js:5 Cannot open '/home/abc/OF/libs/openFrameworksCompiled/project/qtcreator/modules/of/qbs'.

I investigated this and it was because the file 'qbs' did not exist, only of.qbs . so what I did was rename of.qbs to qbs and the following error occurred:
ERROR: /home/abc/OF/libs/openFrameworksCompiled/project/qtcreator/modules/of/helpers.js:5 /home/abc/OF/libs/openFrameworksCompiled/project/qtcreator/modules/of/qbs:1:1 Syntax error

Also can you please make open Frameworks a shared library with everything in it. I hate having to wait 2 minutes every time I want to test my an app.

**Comment by arturoc** [comment]
hi, depending on the gcc version your system has you need to download the gcc5 or gcc6 version of openFrameworks. you can check your version typing `gcc -v` in a terminal

**Comment by BoredBored** [comment]
I have gcc version 7.2.0

**Comment by danzeeeman** [comment]
please keep this to one issue thread.

you need to install a version of gcc that is compatible with openFrameworks. the versions of gcc that are compatible are version 5 and version 6.

**Comment by arturoc** [comment]
@BoredBored the gcc6 version of OF is compatible with gcc 6 or anything newer
