### ISSUE TITLE
ofPolyline.getVertices() incompatibility with vector<ofPoint> [master branch]

### ISSUE THREAD

**Issue by autr** [openframeworks/openFrameworks#5847]
Repo has a “.inl” file in place of a “.cpp” for the ofPolyline.h class, which defines methods like; vector & getVertices(); as std::vector< T > & getVertices(); and breaks implementation. Can the .inl be compiled into .cpp?

**Comment by tgfrerer** [comment]
It appears that this issue has been resolved in the forum (https://forum.openframeworks.cc/t/ofpolyline-inl-in-0-10-0-compile/28572/13)

Closing this for now - feel free to expand the issue report above and re-open the issue if it persists.
