### ISSUE TITLE
[improvement] - openframeworks/openframeworks - adding a contributors list to the repo

### ISSUE THREAD

**Issue by tmm2018** [openframeworks/openFrameworks#5849]
[Improvement] - openframeworks/openframeworks - adding a contributors list to the repo

Greetings

IMHO, it's important to create:
- a contributors list to this repository, for indexation and metadata purposes. 

this can be done: 
- in the changelog for each new version
- or in a separate file, named contributors

looking forward 
cheers

**Comment by danzeeeman** [comment]
this is already maintained by github here https://github.com/openframeworks/openFrameworks/graphs/contributors
