### ISSUE TITLE
[ofxusers&developers: use this] shell script for automatic pull requests in debian

### ISSUE THREAD

**Issue by tmm2018** [openframeworks/openFrameworks#5851]
[ofxusers&developers: use this] shell script for automatic pull requests in debian

hey guys

i recently wrote this script in shell for unix debian. it's a way of drastically simplifying the amount of time necessary to pull a request from shell. if you are interested, please use this:

- https://github.com/tmm2018/tmm_shell/blob/master/_scripts/_tmmScrp/mgc.sh

**Comment by danzeeeman** [comment]
please take this to the [forums](https://forum.openframeworks.cc/c/linux) or the [slack channel ](https://ofslack.herokuapp.com/)
