### ISSUE TITLE
ofxAndroidPauseApp() declaration is missing

### ISSUE THREAD

**Issue by hiroMTB** [openframeworks/openFrameworks#5853]
see 
https://github.com/openframeworks/openFrameworks/blob/android-r15/addons/ofxAndroid/src/ofxAndroidUtils.h

**Comment by hiroMTB** [comment]
This is still missing in .h file.

https://github.com/openframeworks/openFrameworks/blob/8e01052ec278bb52ecc26d511dd5da1c6f0ea31c/addons/ofxAndroid/src/ofxAndroidUtils.cpp#L93-L107

**Comment by arturoc** [comment]
Not sure if this is supposed to be public? what's the purpose of pausing an app? bringing it to the background?

**Comment by hiroMTB** [comment]
I need to pause app but I forgot the reason, it was couple of months ago.
Something like pause app and launch web browser.

Two few question
*I thought most of ofxAndroid*** function is designed to be public. But is this wrong? not only Android but 
*ofxAndroidPauseApp() is not used anywhere in the oF code, is this for preparation for future release?

Anyway I will close If it's intentionally hidden.

**Comment by arturoc** [comment]
No i just wasn't sure, i thought perhaps it was something recently added but it seems i added it a ton of time ago and should move the app to the background. can you send a PR with the declaration?

**Comment by hiroMTB** [comment]
solved by PR https://github.com/openframeworks/openFrameworks/pull/5976
