### ISSUE TITLE
apt-get : relocation error :

### ISSUE THREAD

**Issue by adiaholic** [openframeworks/openFrameworks#5855]
/usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
error installing g++-4.9

**Comment by arturoc** [comment]
when do you get this error?

**Comment by adiaholic** [comment]
when you try to install it on ubuntu 16.04 by modifying the lsb-release .

**Comment by adiaholic** [comment]
Also the entire system comes to hault when we change that lsb-release file.
I had to reinstall ubuntu twice .

**Comment by arturoc** [comment]
what do you mean change the lsb-release file? what install guide are you following?

**Comment by adiaholic** [comment]
http://openframeworks.cc/setup/linux-install/

In this install on 3rd party linux distribution

**Comment by bakercp** [comment]
What 3rd party linux distribution are you using?  Is it based on Ubuntu?

**Comment by adiaholic** [comment]
Ubuntu itself is a linux distribution .
I'm using ubuntu 16.04

**Comment by bakercp** [comment]
The instruction you are using "Install on Third-Party Linux Distribution" is a supplemental instruction set for third-part Ubuntu derivatives (Mint, Elementary OS, etc) that do not already list Ubuntu (e.g. they list something else, like `elementary OS`).  If you are running Ubuntu 16.04 you won't need to follow those instructions.  It should just work on 16.04 using the master branch when you build from https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md.
