### ISSUE TITLE
VSCode Support [Feature] - Finally a cross platform editor (Linux, Win and OSX)

### ISSUE THREAD

**Issue by danoli3** [openframeworks/openFrameworks#5857]
Should look at supporting this as our go to @arturoc (It may already be with .sln's) just need to document.

VSCode now is the sole editor for Unity for OSX and Windows (they dropped monodev cause of it)
https://code.visualstudio.com/download

**Comment by hiroMTB** [comment]
Here it is.
https://github.com/hiroMTB/vscode_oF

**Comment by bakercp** [comment]
Can we close this @arturoc ?

**Comment by arturoc** [comment]
fixed
