### ISSUE TITLE
file not found #include <boost/filesystem.hpp>

### ISSUE THREAD

**Issue by zkg** [openframeworks/openFrameworks#5858]
I have a problem compiling any android app from the master branch on Ubuntu 16.04. 

When gradle builds the project on Android Studio, I get the following error:

```
Error:Note: /home/osboxes/openFrameworks/addons/ofxAndroid/ofAndroidLib/src/cc/openframeworks/OFAndroidVideoGrabber.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
In file included from /home/osboxes/openFrameworks/libs/openFrameworks/gl/ofBufferObject.cpp:4:
In file included from /home/osboxes/openFrameworks/libs/openFrameworks/graphics/ofPixels.h:6:
In file included from /home/osboxes/openFrameworks/libs/openFrameworks/utils/ofLog.h:4:
/home/osboxes/openFrameworks/libs/openFrameworks/utils/ofFileUtils.h:20:11: fatal error: 'boost/filesystem.hpp' file not found # include <boost/filesystem.hpp>
```

I thought it was a problem of configuration on my machine, so I took a clean VM image and tried again: same result. Clearly install_dependencies.sh was executed beforehand and I can see my /usr/include/boost/filesystem.hpp.

Any help is greatly appreciated.

**Comment by arturoc** [comment]
take a look at the instructions on how to install from github: https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md

Going to close this since it's not an issue, please ask in the forum if you keep having problems.
