### ISSUE TITLE
ofTessellator Error

### ISSUE THREAD

**Issue by schmidh** [openframeworks/openFrameworks#5859]
Dear OF community,

just trying to run example _**fontShapesExample**_ from master branch of OF on GitHub. Unfortunately I get following error message:

**[ error ] ofTessellator: performTessellation(): mesh polygon tessellation failed, winding mode 0**

Could also be a consequential error from _**ofTrueTypeFont**_ loading a font. Not sure. Has anybody else seen this error?

Kind regards!

**Comment by schmidh** [comment]
How can you fix that so quickly? Frigging frustrating! **Thanks a lot!!!**

**Comment by arturoc** [comment]
hey thanks!, this was a bug when trying to tessellate empty shapes like spaces and found some other problem on the way
