### ISSUE TITLE
windowMode not being passed on to ofAppGLFWWindow

### ISSUE THREAD

**Issue by PTS93** [openframeworks/openFrameworks#5861]
I discovered that the windowMode variable in ofAppGLFWWindow.cpp is always OF_WINDOW because of the constructor [setting it to that](https://github.com/openframeworks/openFrameworks/blob/f4341627bf22c5569979dbc8da1336a352afaf92/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L52) by default but the variable is never changed by the settings from ofBaseWindow(?). Many instances of the code work with settings.windowMode (which works) some only use the local windowMode variable (which does not work because its always OF_WINDOW).
See f.e.:
https://github.com/openframeworks/openFrameworks/blob/f4341627bf22c5569979dbc8da1336a352afaf92/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L220

https://github.com/openframeworks/openFrameworks/blob/f4341627bf22c5569979dbc8da1336a352afaf92/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L496

Because of that many functions are basically broken for OF_FULLSCREEN and OF_GAME_MODE.

I would fix it by having settings.windowMode assigned to the local windowMode variable in the setup and then from there on only use windowMode throughout the rest of the code.
Before I do that and make a pull request I wanted to ask here first though if that is the proper approach for OF or not, maybe there is a different intention there that I'm missing.

**Comment by arturoc** [comment]
i think i would remove the redundant local variable and only use the one in settings that way nobody changing the code can do this mistake again

**Comment by PTS93** [comment]
great, I will create pull request then.

**Comment by arturoc** [comment]
great thanks! i'm going to reopen this until you send the PR. If you include Fixes and the number of this issue in your  PR commit or in the message the issue will get closed automatically once we merge the PR

**Comment by PTS93** [comment]
Should this maybe changed for https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGlutWindow.cpp
and possibly others as well? In ofAppGlutWindow it is using the local variable and assigning it the  value of settings.windowMode in setup. There it is at least consistent after that and no mixed usage.

**Comment by arturoc** [comment]
which functions didn't work originally for you? i'm testing your changes but some things are broken. for examples starting a window in full screen doesn't work now. i'm fixing them but would be good to know what was the original issue in the first place

**Comment by PTS93** [comment]
Sorry, I must have missed the mail. My personal original issue was that the mouse pointer was not disappearing, when I created the fix for that I discovered that my check for the windowMode was not working as windowMode was always 0. So through that I found out about this issue.
I wasn't directly affected as a user, though there were some oddities with GAME_MODE where  I'm not sure if this was maybe causing that, primarly the resolution was always set wrongly and the renderer was never scaled to fullscreen.

**Comment by arturoc** [comment]
no worries, can you check if my fix solves your issue too?

**Comment by PTS93** [comment]
I won't be able to get back at it until next week but I will report if everything still works. The only thing that could happen though is that your changes broke the fix that got merged earlier but it doesn't look like it.
https://github.com/openframeworks/openFrameworks/commit/8faa193976fd0f64906e4051766ad3996544fec4
