### ISSUE TITLE
fontShapesExample not working

### ISSUE THREAD

**Issue by schmidh** [openframeworks/openFrameworks#5863]
Dear OF Community,

in the **_fontShapesExample_** the calls to **_getOutline_** are not working. So the loops to access the individual points are never run:

["// we can also access the individual points"](https://github.com/openframeworks/openFrameworks/blob/master/examples/graphics/fontShapesExample/src/ofApp.cpp#L61)

Any ideas?

Kind regards!

**Comment by schmidh** [comment]
Dear OF community,

think I found the smelly line of code without knowing why. (Because I do know too little of the inner workings of OF.)

I commented out following line in the method `makeContoursForCharacter(FT_Face face)` of `ofTrueTypeFont` and then **fontShapesExample** works again:


[charOutlines.setPolyWindingMode(OF_POLY_WINDING_NONZERO)](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L174)

Maybe someone could have a look at the code at this point who has more knowledge than me.

Kind regards!

**Comment by ofTheo** [comment]
can confirm this! 
thank you for finding the fix, will PR against this issue.

**Comment by arturoc** [comment]
mmh sorry, there was another problem with the way we where using the contour path where we never set the line width to one so the first contour for th char was never drawn either. That's fixed now but not really this issue.

I'm going to reopen it but i think the winding mode is the correct one for fonts so it shouldn't be changed

**Comment by arturoc** [comment]
oh, ok this was really the same problem. when we took the font path we were never setting the width to 1 so it wasn't generating a contour at all. it wasn't related to the winding. not sure why changing the winding fixes it though.

**Comment by arturoc** [comment]
btw, theo, i didn't saw your comment until after committing the fix, i had been fixing something related to this some days ago and had the fixes for the example in my computer but had never committed them

**Comment by schmidh** [comment]
Thanks a lot!

**Comment by ofTheo** [comment]
abs, no worries @arturoc :) 
awesome that its fixed!  thanks @schmidh  for reporting this!
