### ISSUE TITLE
Mac OF_TTF_SANS changed

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#5865]
On `TARGET_OSX`, `OF_TTF_SANS` corresponds to:

```c++
fontname = "Helvetica Neue";
fontID = 4;
```

But the way this font looks has changed at some point (either 10.12 or 10.13 I believe).

Here are some variations, from fontId 6 to 0:
 
<img width="128" alt="fontid 6" src="https://user-images.githubusercontent.com/157106/35700775-c9114f56-0748-11e8-9d46-b39cdfcb9c49.png">
<img width="128" alt="fontid 5" src="https://user-images.githubusercontent.com/157106/35700763-c37f4dfe-0748-11e8-91c0-7318a10ff873.png">
<img width="128" alt="fontid 4" src="https://user-images.githubusercontent.com/157106/35700764-c396a3d2-0748-11e8-990a-df9844e554cf.png">
<img width="128" alt="fontid 3" src="https://user-images.githubusercontent.com/157106/35700765-c3b2c0d0-0748-11e8-83f2-f99403373c99.png">
<img width="128" alt="fontid 2" src="https://user-images.githubusercontent.com/157106/35700767-c3c79c26-0748-11e8-8b65-1e656b497363.png">
<img width="128" alt="fontid 1" src="https://user-images.githubusercontent.com/157106/35700768-c3e10968-0748-11e8-8b45-29045050afc5.png">
<img width="128" alt="fontid 0" src="https://user-images.githubusercontent.com/157106/35700769-c4032d86-0748-11e8-8fa5-0318f23d9939.png">

I suggest changing it to fontId 0 (the final image).

**Comment by ofTheo** [comment]
Agree!

**Comment by arturoc** [comment]
@ofTheo can you change it?

**Comment by ofTheo** [comment]
will do!

**Comment by ofZach** [comment]
ps: I haven't dug into this but I wonder if it's related to OSX listing files different under APFS vs the previous file system.   see also 

https://github.com/openframeworks/openFrameworks/issues/5852
