### ISSUE TITLE
Nightly builds don't add addons includes correctly to examples. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5869]
This seems to affect opencv, assimp and a bunch of others. 

You can see in the build settings only the src/ is added for assimp and opencv. 

<img width="504" alt="screen shot 2018-02-05 at 4 22 58 pm" src="https://user-images.githubusercontent.com/144000/35835700-18603b76-0a91-11e8-9393-c84abbee04c7.png">

Looking at the addons.make file there aren't any excludes for os x, so not sure if this is a PG issue or a an issue with the  addons.make. 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/addon_config.mk

**Comment by ofTheo** [comment]
Update: using the PG included in the downloaded nightly zip to regenerate the examples, correctly adds the includes back in. Going to cross-post this to https://github.com/openframeworks/projectGenerator

**Comment by arturoc** [comment]
This has to be something on the create_packages script then but not sure why since it's just calling the PG

**Comment by arturoc** [comment]
Theo is this still an issue? Not sure what might be going on since all the tests are passing and that config is the same as the one use to create the packages for the nightly builds

**Comment by ofTheo** [comment]
@arturoc can confirm this is still an issue with the current nighty builds. 
Running the PG included in the nightlies on the examples fixes the issue.  

Not sure what is different with the PG app and the scripts running on the server?

**Comment by ofTheo** [comment]
Also can confirm same issue for iOS

**Comment by arturoc** [comment]
that's really strange. this is the script that creates the nightlies: 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/nightlybuilds.sh

which really calls this one per platform to create the packages:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh

that last script downloads the latest compiled version of the PG from http://ci.openframeworks.cc/projectGenerator/ (which looks up to date) and creates the projects with it. 

you should be able to call the create_packates.sh script locally to test, it clones the OF repo shallowly so it's pretty fast now that we don't have binaries

**Comment by ofTheo** [comment]
so I believe this line here: 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L320 

Needs to come after: 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L504

**Comment by ofTheo** [comment]
I can make the change - but just want to get a second set of eyes on it :)

**Comment by arturoc** [comment]
hey thanks for looking into it, that makes a lot of sense but i think the problematic lines are 

https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L320

and

https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L435

The second block downloads the libraries for the platform so i think the PG is being run before the libraries are actually downloaded which is why it's not including those paths in the project. I can try to do that change later.

thanks!
