### ISSUE TITLE
Scary first responder warning GLFW/OSX 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#5871]
Seeing this with the nightlies on OS X 10.13. 
Both with the old style ofRunApp code in main.cpp and the new approach. 

```
2018-02-05 19:50:48.715832-0800 allAddonsExample[2581:6668253] [General] ERROR: Setting <GLFWContentView: 0x608000140630> as the first responder for window <GLFWWindow: 0x60c0001e1600>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fff546cd52e -[NSWindow _validateFirstResponder:] + 578
	1   AppKit                              0x00007fff53e14a58 -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fff53eb317d -[NSWindow _realMakeFirstResponder:] + 448
	3   allAddonsExample                    0x00000001000f794e createWindow + 1230
	4   allAddonsExample                    0x00000001000f724f _glfwPlatformCreateWindow + 63
	5   allAddonsExample                    0x00000001000f12ed glfwCreateWindow + 877
	6   allAddonsExample                    0x00000001005a2444 _ZN15ofAppGLFWWindow5setupERK20ofGLFWWindowSettings + 1476
	7   allAddonsExample                    0x00000001005455dd _ZN10ofMainLoop12createWindowERK16ofWindowSettings + 141
	8   allAddonsExample                    0x0000000100520175 _Z14ofCreateWindowRK16ofWindowSettings + 37
	9   allAddonsExample                    0x0000000100002191 main + 257
	10  libdyld.dylib                       0x00007fff7e074115 start + 1
)

```

**Comment by arturoc** [comment]
That looks like a glfw problem, perhaps you can try compiling and running one of the glfw examples to see if it has the same problem?

**Comment by ofTheo** [comment]
will do!

**Comment by ofTheo** [comment]
@arturoc - looking into the GLFW issues on GitHub it seems to be an issue with the 3.2 release. Most of the suggestions are to use the 3.3 version of GLFW which is currently in the master branch. https://github.com/glfw/glfw/issues/1057#issuecomment-320476008 

I just tested the master GLFW and it links/runs fine and it does resolve this issue.

**Comment by arturoc** [comment]
can you update the apothecary formula? it should be just a matter of changing the version number in the script

**Comment by kylemcdonald** [comment]
it looks like this has transformed, with the latest from github / 0.10.0rc1 now i see this:

```
2018-04-14 15:32:47.148207-0700 MinimalExample[55385:2933560] ApplePersistence=NO
2018-04-14 15:32:47.379209-0700 MinimalExample[55385:2933633] MessageTracer: Falling back to default whitelist
```

if this makes it into 0.10.0 i think it could be good to pin a notice somewhere (like on the downloads page) that this can be ignored. otherwise i think there will be a lot of questions about what it means.

i tried googling this and couldn't find any more obvious info about where this comes from, sorry..

**Comment by ofTheo** [comment]
I think this is actually a separate xcode bug. 
I found a post about it where basically apple devs where saying to ignore it. 

A post might still be useful. But I think it's not related to GLFW.
