### ISSUE TITLE
Error while installing on ubuntu 16.04 when script  "install_dependencies.sh"  is run

### ISSUE THREAD

**Issue by adiaholic** [openframeworks/openFrameworks#5873]
E: Unable to locate package libgl1-mesa-dev-hwe-16.04
E: Couldn't find any package by glob 'libgl1-mesa-dev-hwe-16.04'
E: Couldn't find any package by regex 'libgl1-mesa-dev-hwe-16.04'
error installing libgl1-mesa-dev-hwe-16.04

**Comment by cuinjune** [comment]
I had this issue on ubuntu as well. I just skipped installing libgl1-mesa-dev-hwe-16.04 by typing N when asked to install it. It seemed to be working fine without installing it.

**Comment by adiaholic** [comment]
so were you able to compile those sample programs

**Comment by adiaholic** [comment]
because of this error i'm unable to run that 'compileOF.sh' giving me an error as 

logname: no login name
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 libudev freetype2 fontconfig sndfile openal openssl gl glu glew libmpg123 
makefileCommon/config.shared.mk:294: *** cairo not installed. Did you run the latest install_dependencies.sh? zlib not installed. Did you run the latest install_dependencies.sh? gstreamer-app-0.10 not installed. Did you run the latest install_dependencies.sh? gstreamer-0.10 not installed. Did you run the latest install_dependencies.sh? gstreamer-video-0.10 not installed. Did you run the latest install_dependencies.sh? gstreamer-base-0.10 not installed. Did you run the latest install_dependencies.sh? libudev not installed. Did you run the latest install_dependencies.sh? freetype2 not installed. Did you run the latest install_dependencies.sh? fontconfig not installed. Did you run the latest install_dependencies.sh? sndfile not installed. Did you run the latest install_dependencies.sh? openal not installed. Did you run the latest install_dependencies.sh? openssl not installed. Did you run the latest install_dependencies.sh?.  Stop.
there has been a problem compiling Debug OF library
please report this problem in the forums

**Comment by adiaholic** [comment]
we don't need to install those libgl1-mesa-dev-hwe-16.04 dependencies in ubuntu 16.04

**Comment by adiaholic** [comment]
we don't need to install those libgl1-mesa-dev-hwe-16.04 dependencies in ubuntu 16.04
