### ISSUE TITLE
fbo.getTexture().bind(); causes crash on iOS nightly.

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5874]
Hi, I just tried to run this code (https://github.com/openframeworks/openFrameworks/issues/5826) to see if it works in the latest iOS nightly build.
But it crashes when calling `fbo.getTexture().bind();`
Here's a screenshot of it when crashed.
<img width="1138" alt="screen shot 2018-02-07 at 12 13 32 am" src="https://user-images.githubusercontent.com/24947986/35867112-4c385bfc-0b9c-11e8-916e-d9f77d27b9c7.png">

**Comment by arturoc** [comment]
can you post an example that produces that crash?

**Comment by cuinjune** [comment]
Here's the test code.

in ofApp.h

    ofFbo fbo;
    ofMesh mesh;

in ofApp.cpp

    //--------------------------------------------------------------
    void ofApp::setup(){
        
        ofDisableArbTex();
        ofSetCircleResolution(50);
        
        int fboWidth = ofGetWidth()/4;
        int fboHeight = ofGetHeight()/4;
        
        fbo.allocate(fboWidth, fboHeight, GL_RGB);
        
        fbo.begin();
        ofClear(255, 0, 0, 255);
        ofSetColor(0, 255, 0);
        ofDrawEllipse(fboWidth/2, fboHeight/2, fboWidth, fboHeight);
        fbo.end();
        
        mesh = ofMesh::plane(fboWidth, fboHeight);
    }

    //--------------------------------------------------------------
    void ofApp::update(){
        
    }

    //--------------------------------------------------------------
    void ofApp::draw(){
        
        fbo.draw(0, 0);
        
        ofTranslate(ofGetWidth()/2, ofGetHeight()/2);
        fbo.getTexture().bind();
        mesh.draw();
        fbo.getTexture().unbind();
    }

It crashes when calling `fbo.getTexture().bind();` in the `draw()` function.

**Comment by ofTheo** [comment]
Thanks for checking about this! 

I just checked with your code and it seems that this is working now. I think maybe due to the other fbo related fixes. Give the nightly build a try tomorrow and let me know if it still doesn't work for you. 

Many thanks!!

**Comment by cuinjune** [comment]
Hey @ofTheo Thank you for your confirmation.
Yes, the code no longer crashes but it still has this problem #5826 which I figured out how to fix it. (Please see my last comment)
I would appreciate if you could confirm that the fix is correct. It seems to work well after the fix.
Thank you so much for you help!
