### ISSUE TITLE
iOS is rebuilding OF library repeatedly on each example

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#5895]
on xcode 9+ I'm seeing iOS have to rebuild OF on each new example you launch :( 

taking a closer look at the build commands that are compiling OF, it seems that one of the commands in the build has the derived data (unique to each OF app) folder name in it: 

`"-index-store-path /Users/Zach/Library/Developer/Xcode/DerivedData/...."
` 
which is why the rebuild seems to happen....

If I disable this feature on both OF library and projects this issue goes away, but I'm not 100% sure what this is feature is doing. 

![Uploading Screen Shot 2018-02-12 at 6.54.07 AM.png…]()

fixing this would significantly help iOS build times and developer sanity. 

cc @ofTheo @danoli3

**Comment by ofZach** [comment]
not sure why the image didn't work trying again <img width="986" alt="screen shot 2018-02-12 at 6 54 07 am" src="https://user-images.githubusercontent.com/142897/36096045-99d5ab60-0fc2-11e8-8740-7cf27a76d33a.png">

**Comment by danoli3** [comment]
Oh wow super weird. Yeah lets turn that off.

**Comment by ofTheo** [comment]
@ofZach I have no idea what is causing the rebuild. It looks like it was a big issue in Xcode 8 and something Apple was dealing with with Swift. 

Things I have tried: 
- Editing the scheme build and unchecking Find Implicit Dependencies 
- Adding the Macro HEADERMAP_USES_VFS = YES
- Changing the OF project and the Example to build only active archs 
- Changing the OF project and the Example deployment target to iOS 9 ( it was set to 7.0 which doesn't come up as an option in Xcode 9 ) 

The only thing that comes close is to remove the OF project from the project dependency build phase and to uncheck Find Implicit Dependencies - but then it won't build the OF project if it needs to.  

I am going to double check that this doesn't happen with the macOS nightly.  
If it doesn't there could be some sort of setting difference that might give us a clue but I am not optimistic.

**Comment by ofTheo** [comment]
oh @ofZach I see that you actually have a solution in the body of your issue - haha :)
so it just that setting to be made default for the projects?  I think that could be an easy change. 

Happy to take a stab
