### ISSUE TITLE
ofEasyCam inertia

### ISSUE THREAD

**Issue by Paul92** [openframeworks/openFrameworks#5907]
I saw this issue as task in the checklist for 0.10 - the broken inertia for easyCamExample, and I would be willing to take a look int o it.

This boils down to the way the camera's inertia works: whenever the mouse button is pressed, the camera saves the current orientation and when the mouse is released, the camera will return at this orientation. The rotation can be permanently changed with inertia disabled. See:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/3d/ofEasyCam.cpp#L319-L337

What is the intended behavior for this?

**Comment by roymacdonald** [comment]
this is not the intended behavior. I'll take a look at it.
cheers

**Comment by roymacdonald** [comment]
the intended behavior is that the camera will slow down it's movement gradually after releasing the mouse. it just gives a fancier feeling to it.
