### ISSUE TITLE
Android projects don't parse addons libraries correctly

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#5910]
Addons with binary libraries don't add those libraries unless they are specified in the addons_config.make file. For example any project using the assimp addon will fail with undefined symbols cause it's not linking any libraries.

Adding:

```
android/armeabi-v7a:
	ADDON_LIBS=
	ADDON_LIBS+=libs/assimp/lib/android/armeabi-v7a/libassimp.a 
	ADDON_LIBS+=libs/assimp/lib/android/armeabi-v7a/libIrrXML.a

android/x86:
	ADDON_LIBS=
	ADDON_LIBS+=libs/assimp/lib/android/x86/libassimp.a 
	ADDON_LIBS+=libs/assimp/lib/android/x86/libIrrXML.a
```

makes the projects work but the gradle config should find those files from the file system if they are in an standard location like in this case as it already does correctly for include files for example.

@HalfdanJ could you take a look at this?

**Comment by wssbygone** [comment]
hello, I've build the libassimp.a using this CMD: cmake  CMakeLists.txt  -DANDROID_FORCE_ARM_BUILD=ON -DANDROID_ABI="armeabi-v7a" -DANDROID_NATIVE_API_LEVEL="android-22"  
-DCMAKE_C_COMPILER=/tmp/ndk-root/bin/arm-linux-androideabi-gcc-4.9 
-DANDROID_TOOLCHAIN_NAME="/home/wss/android_toolchain/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9",  but the libassimp.a is not available when compile OF example androidAssimpExample, could tell me, how to build the right ibassimp.a（armeabi-v7a）
