### ISSUE TITLE
OSC parameter receiving doesn't support ofColor

### ISSUE THREAD

**Issue by alexdmiller** [openframeworks/openFrameworks#5916]
The OSC parameters example (`examples/gui/oscParametersReceiver`) features a `parameter<ofColor>`, but I haven't been able to get the example to actually receive color data over OSC. Upon further investigation, it looks like `ofxOscReceiver` doesn't even support colors in `ofxOscReceiver::getParameter`.

**Comment by ShadowMitia** [comment]
I've launched the `examples/gui/oscParametersReceiverExample)` and `examples/gui/oscParametersSenderExample)` and they work, and that includes transmitting color. This was on oF 0.10.0.

What version of oF did you try?

**Comment by arturoc** [comment]
Yes this is fixed now, thanks!
