### ISSUE TITLE
There are conflicts between core library and openNI2 on linux

### ISSUE THREAD

**Issue by yaoyaoyaoGit** [openframeworks/openFrameworks#5922]
I cannot make the empty example in openframeworks when including the file **oniEnums.h**  in openni2.
typedef enum
{
	STATUS_OK = 0,
	STATUS_ERROR = 1,
	STATUS_NOT_IMPLEMENTED = 2,
	STATUS_NOT_SUPPORTED = 3,
	STATUS_BAD_PARAMETER = 4,
	STATUS_OUT_OF_FLOW = 5,
	STATUS_NO_DEVICE = 6,
	STATUS_TIME_OUT = 102,
} Status;

The error message is **error: multiple types in one declaration**
After debugging, I found in the file **Xlib.h** which is included by the **glx.h** (I believe belongs to the GL library).
There is code in line 30:
#define Status int

I think this is where the error comes out. 
The problem is very serious because I think it will result in that any addons using openNI2 cannot be built in Linux.
Can anyone tell me how to fix this?

**Comment by arturoc** [comment]
This problem should be solved in latest version of OF in github or the nightly builds. Can you try if you still have the problem with those versions?

**Comment by yaoyaoyaoGit** [comment]
It works well when I use the nightly builds. I used v0.9.8 before.
it can also be fixed by using #undef in the conflict file, see https://github.com/ofTheo/ofxKinectV2/issues/27
Thank you!

**Comment by arturoc** [comment]
great, going to close this then
