### ISSUE TITLE
libjasper-1.dll missing using msys2 build

### ISSUE THREAD

**Issue by sphaero** [openframeworks/openFrameworks#5923]
make copy_dlls error:
```
cp: cannot stat '/mingw32/bin/libjasper-1.dll': No such file or directory
```
It seems the lib is now called libjasper-4.dll?

```
$ find / -name "*jasper*"
/mingw32/bin/jasper.exe
/mingw32/bin/libjasper-4.dll
/mingw32/include/jasper
/mingw32/include/jasper/jasper.h
/mingw32/lib/libjasper.a
/mingw32/lib/libjasper.dll.a
...
```
using latest msys2 on win10

**Comment by oxillo** [comment]
The copy_dlls task copies a static list of files. So when libs evolve, it will break (and we also copy unnecessary libs...).
We need to think of a way to build that  list dynamically.

For the time being, you could edit the libs\openFrameworksCompiled\project\msys2\config.msys2.default.mk file to change the jasper file name
