### ISSUE TITLE
"local addons" undocumented and apparently breaking with make builds

### ISSUE THREAD

**Issue by anselanza** [openframeworks/openFrameworks#5932]
I would like to use "local addons" in my projects (in combination with git submodules) in order to make my projects more portable. I typically build for Linux so I use `make` for compiling everything. I have no problem when addons are in the `ofroot/addons` location as "normal".

As I understand it, so-called "local addons" were added somewhere around oF 0.9.0 - I reference the following from @arturoc and @ofZach 
* https://forum.openframeworks.cc/t/how-do-you-use-git-for-versioning-an-of-project/22229/2
* https://forum.openframeworks.cc/t/local-addons-in-of-0-9-0-projects/21445/2

The mechanism is supposed to be some combination of putting the addons into `./addons` or `./local_addons` (it is unclear which) relative to the project folder, and then in `addons.make` adding either `../local_addons/my-addon` or just `my-addon` (also unclear which) and then automagically the project should `make` as normal.

However, I have noticed that no combinations of the above work for me, and there is some misconfiguration of paths happening but I don't know where to start trying to fix this in the various levels of Makefiles and configuration files...

A reproducible example:
1. Move a standard addon, such as ofxOsc, out of the `ofroot/addons` folder and into a project's `./local_addons` folder
1. Add the relative path or name of the addon as described above (both methods fail with the same issue anyway)
1. Build with `make` from the project root. The error always looks like something went strange concatenating relative paths:
```
make[1]: *** No rule to make target '/home/pi/of/addons/obj/linuxarmv6l/Release/ofxOsc/./local_addons/ofxOsc/libs/oscpack/src/osc/OscTypes.o', needed by 'bin/lidar-blob-tracker'.  Stop.
```
Any tips? It would be great to document this very useful feature.

**Comment by arturoc** [comment]
This should work for any folder the name doens't matter. For example if you have:

```
OF/apps/myProjects/someProject
```

and your addon is in:

```
OF/apps/myProjects/someProject/addons/ofxSomeAddon
```

adding:

```
addons/ofxSomeAddon
```

in addons.make should work

or if your addons are in

```
OF/apps/myProjects/addons/ofxSomeAddon
```

then in your project's addon.make you can set

```
../addons/ofxSomeAddon
```

In general the makefiles (and the project generator, qt creator project and vs wizard) will parse each line of addons.make by checking first if it's a valid path and if not by checking if it exists in OF/addons so any path relative from the project path and even absolute paths pointing to an addon folder will work

let me know if it's still problematic.

**Comment by anselanza** [comment]
Thank you so much for the detailed response! It works perfectly now.

This will make for much more portable oF projects for me (and hopefully others who come across this issue).

**Comment by anselanza** [comment]
I would just add that it does seem to be necessary to explicitly exclude the local `addons` folder (or whatever you name it) from the project compilation if it is indeed a subfolder of the project. In my project `config.make` file I needed the following:
```
PROJECT_EXCLUSIONS = $(PROJECT_ROOT)/addons%
```
Otherwise the addon source apparently gets compiled twice - once because it's in the project folder and once because it's specified in the the `addons.make` file.

**Comment by jedahan** [comment]
So is this documented anywhere besides this issue and the forums? Is there an appropriate place we could add this to? I'm not sure if there is some sort of 'intermediate oF' doc anywhere but this seems distracting for an introduction to oF but helpful otherwise.

**Comment by hamoid** [comment]
Would the [wiki](https://github.com/openframeworks/openFrameworks/wiki) be a good place? Maybe a page about writing reusable code or how to organize many not-so-tiny projects? The OF book has an advanced topics chapter: http://openframeworks.cc/ofBook/chapters/foreword.html

**Comment by jedahan** [comment]
@hamoid great pointers. I started sketching out some wiki topics I'd like covered with https://github.com/openframeworks/openFrameworks/wiki/Home/_compare/1a308cf852b21a3c70d23e3534060df85b85c0cb . Maybe once thats in a state people like, we can re-ify to the ofBook

**Comment by jedahan** [comment]
@hamoid great pointers. I started sketching out some wiki topics I'd like covered with https://github.com/openframeworks/openFrameworks/wiki/Home/_compare/1a308cf852b21a3c70d23e3534060df85b85c0cb . Maybe once thats in a state people like, we can re-ify to the ofBook

**Comment by anselanza** [comment]
I feel like it should be documented somewhere, perhaps in a section relating to version control and making oF projects portable. Perhaps of less concern to newcomers, for sure, but for anyone doing serious work with openFrameworks it's kind of essential to have a workable strategy for maintaining your own projects and allowing other developers to work on them (move them between machines and environments easily).
