### ISSUE TITLE
Do we need a ray class?

### ISSUE THREAD

**Issue by edap** [openframeworks/openFrameworks#5934]
In the last month I have built a ray tracer in openFrameworks and I had to work with threejs and the classes Ray and Plane.
https://threejs.org/docs/#api/math/Plane
https://threejs.org/docs/#api/math/Ray
During this experience, I had the feeling that it would be nice to have these classes also in openFrameworks, an maybe a method to calculate the intersection between a plane and a ray, or a primitive and a ray.

References:
- glm gives us, out of the box, all the math that we need https://glm.g-truc.net/0.9.5/api/a00203.html, I have used some of these methods in my raytracer implementation (https://github.com/edap/ofxRayTracer/blob/master/src/ofxRayTracer.cpp#L217)
- There is this addon by @elliotwoods https://github.com/elliotwoods/ofxRay that has already experimented with this topic.

@arturoc , would you consider a simple, minimal and basic PR for a ray class ?

**Comment by armadillu** [comment]
I've used ofxRay in the past and I found it really useful.

**Comment by edap** [comment]
I have checked that one but I do not like: 
1) the naming convention. A ray does not have a start and an end, it is not a segment. A ray has an origin and a direction.
2) a lot of math is now available through glm, maybe it is safer to rely on that functions.

**Comment by bakercp** [comment]
@edap It sounds like probably the answer is no?  @arturoc ?

**Comment by edap** [comment]
let's close this

**Comment by arturoc** [comment]
yeah this shoould be an addon
