### ISSUE TITLE
error when compiling OF in Raspberry Pi 3 / Jessie

### ISSUE THREAD

**Issue by andreirt** [openframeworks/openFrameworks#5940]
Dear all, when I try to compile OF in Rasperry Pi 3, I get this error:
"target CPU does not support ARM mode"

The distro being used is last Jessie build available at Raspberry 3 website:
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

I tried the stable release and the last nightly release at openframeworks.cc/download

Screenshot below:

![of_raspberry_erro](https://user-images.githubusercontent.com/838446/37990682-63343274-31dd-11e8-9d5c-a4bc0c579bd9.png)

Thank you for your time.

**Comment by arturoc** [comment]
raspbian is compiled for armv6 even if rapsberry pi 3 is arm7. you need to use the armv6 download. armv7 has only been tested with archlinux

**Comment by andreirt** [comment]
Thank you.

**Comment by zetteeh** [comment]
with of_v0.9.8_linuxarmv6l_release on a raspberry pi 3 i get errors trying to install the dependencies. is there a working solution somewhere? does anyone have experience with the new 3B+ raspberry model? 
thanks!

**Comment by sourya-sen** [comment]
That's weird, I have 0.10.0 running without any issues on my Pi. What error
error are you getting? Which version of Raspbian are you running?

**Comment by zetteeh** [comment]
and you would use the armv7 for the 3b+?

**Comment by sourya-sen** [comment]
No, 6.

**Comment by zetteeh** [comment]
worked. thanks!
