### ISSUE TITLE
OF doesn't handle high resolution displays on macOS

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#5943]
After not liking the fuzzy menu font for OF apps on a retina screen, I added the NSHighResolutionCapable key to the app bundle Info.plist:

~~~
<key>NSHighResolutionCapable</key>
<true/>
~~~

This does indeed fix the menu font rendering but it also results in the OF graphics window being half size as the high resolution point size becomes the pixel size. This appears to be related to #5167.

As far as I can tell, GLFW should be able to handle this as of version 3.0.3. Maybe OF is not handling the pixel <-> point size conversion?

It's 2018 and IMO OF should be able to handle native retina display rendering.

**Comment by ofTheo** [comment]
@danomatika I think this issue #4789 is where things left off. 

Its a fair amount of work to get retina to be a completely painless on/off toggle in OF. 

Right now I think we pretty much let you know if you are working in retina and then leave it completely up to the developer to account for it with scaling / layout etc with `ofAppGLFWWindow::getPixelScreenCoordScale();`

If you set the window shape to 1024x768 in main.cpp you will get a retina sized window 1024x768 ( which will look smaller ) as opposed to a 2048x1536 window sized the same as a non retina 1024x768 

I was originally leaning towards a simple approach that would just do an internal scale to account for the getPixelScreenCoordScale, but fonts would need to load at 2x or 3x the size and potentially we would need a system for loading images based on the pixel density. 

Right now to just get the window to be the equiv size and to see the graphics correctly. 
This gets you most of the way there. 

in ofApp::setup
`    ofSetWindowShape(win->getPixelScreenCoordScale()*1024, win->getPixelScreenCoordScale()*768); `

in ofApp::draw 
`    ofScale(win->getPixelScreenCoordScale(), win->getPixelScreenCoordScale(), 1.0);`

Anyway - happy to look at this again. 
I would love to get this in. It is much needed for iOS as well.

**Comment by danomatika** [comment]
In my experience, the Apple frameworks handle this transparent for you and I believe NSOpenGLView does as well. Perhaps there is some way for GLFW to leverage this unless they aren't using NSOPenGLView.

**Comment by danomatika** [comment]
In any case, I'll close this in favor of #4789.
