### ISSUE TITLE
Question about recent change with ssl/linux / 0.10 RC1

### ISSUE THREAD

**Issue by gorkacortazar** [openframeworks/openFrameworks#5971]
Testing our applications with 010 RC1, we noticesd that ssl is not included anymore in the compilation basic compilation andd was moved to ofxPoco in this commit bacdb86a8d112e2fb24971d04c31d25bec21e269

Should we update our addons to include the the SSL and assume that the main compilation will not include ssl anymore? In Windows seems to be included included in the default set of libraries.

**Comment by arturoc** [comment]
In which platform? do you mean you have addons that use openssl without using poco?

In that case probably yes, you should include ssl the way it's included in poco.

From my tests, in linux it's ok to not include ssl anymore in the core, curl seems to be able to do https requests without problem. 

In osx we use apple's ssl implementation for curl and only use openssl when including poco.

And in windows i think we include openssl still in the core cause curl depends on it but tbh I haven't tested in much depth if it's really needed

**Comment by arturoc** [comment]
perfect, good to know. I'll close this then but feel free to keep posting if you find any further problem.
