### ISSUE TITLE
Cannot open file 'libcrypto.lib' when using ofxPoco and certain poco functionalities

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#5973]
In vs2017 (testing against 0.10rc1), making a new project that uses ofxPoco and certain Poco calls, triggers the error:

```
LINK : fatal error LNK1104: cannot open file 'libcrypto.lib'
```

The code happens to be https://github.com/armadillu/ofxSimpleHttp; I haven't bisected what code is to blame but I bet its the `HTTPSClientSession` or the `Poco::Net::SSLManager::instance()`.

The test project was created on purpose entirely within the 0.10RC1 zip for VS2017, using the supplied project generator.

More on this in https://github.com/openframeworks/openFrameworks/issues/5903.

**Comment by arturoc** [comment]
This is a problem with the version of Poco we use. It seems to be linking against this library in their headers: https://github.com/pocoproject/poco/blob/develop/Crypto/include/Poco/Crypto/Crypto.h#L106-L107 but that library doesn't exist when compiling openssl, probably cause they are already using openssl 1.1 but we are still in 1.0

We probably need to use a different version of openssl or go back to an earlier version of poco.

**Comment by armadillu** [comment]
I've just tested the with the new libs generated by apothecary available in  http://ci.openframeworks.cc/libs/ but it seems Poco is still on version 1.8.1
```
#define POCO_VERSION 0x01080100
```

**Comment by arturoc** [comment]
yes the change wasn't really building 1.7.9 but building 1.7.9 fails in several platforms. i'm now trying to build openssl 1.1 instead. That's why i haven't closed this yet

**Comment by armadillu** [comment]
ok! let me know, happy to test again

**Comment by arturoc** [comment]
This should be working now

**Comment by armadillu** [comment]
@arturoc trying this out in RC2, I wanted to create a project from scratch with PG... But the Electron front end fails to create one. Looking into the command line (projectGenerator.exe), I see that it wont launch;

"The code execution cannot proceed because libssl-1_1.dll was not found. Reinstalling the program may fix this problem."

I looked for that dll in the zip, but I see libssl 1.1 only comes with libs? 
This is in windows10 btw.
