### ISSUE TITLE
xcode change linking / dependency structure in Xcode

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#5981]
recently I've found difficulty with how OF is embedded as a sub-project of projects in Xcode. 

some issues involve: 

- clean cleaning everything (OF lib as well as the core project).  compile times of OF are pretty long now...
- students loading a project and having it set to build OF (not the debug or release target), and getting confused when nothing happens
- if you have a bunch of projects open and close more all but one, you can sometimes get this weird error 

<img width="866" alt="screen shot 2018-04-23 at 10 06 58 am" src="https://user-images.githubusercontent.com/142897/39132028-de92d4b4-46de-11e8-81e2-8766f1cd33c7.png">

that goes away when you open a second project or quit and restart Xcode.   I have yet to track this down but I know it relates to the number of projects open at a time. 

wonder if it would make sense to revisit how OF is embedded in projects to fix some of these issues.  maybe making OF lib more independent and more like a framework or dylib, etc.

**Comment by hiroMTB** [comment]
I see this disappered during building problem. I start happening from recent version of High Sierra or Sierra, so it might be problem of Xcode itself.

And I found that oF can be used as static lib easily on OSX. (probably on other platforms as well).
I will check if it solves some of these issues. Good point is we can clean project without cleaning oF. Might be nice to add it as PG option. For example use oF as Source, Static lib and Shared lib.

**Comment by dimitre** [comment]
I think this one was already addressed right? can this be closed?

**Comment by ofTheo** [comment]
yup def fixed! thanks!!
