### ISSUE TITLE
setTransformMatrix in ofnode is gone

### ISSUE THREAD

**Issue by wearenocomputer** [openframeworks/openFrameworks#5987]
Hi everybody,

Not sure if this is an actual issue or maybe rather a choice by the oF dev team, but we wanted to flag that the setTransformMatrix() function is gone in the ofNode class. Would be awesome to have it back :-)

**Comment by arturoc** [comment]
hi, yes this was removed on purpose cause matrix decomposition is not 100% reliable and was confusing when it didn't work. you can still manually decompose the matrix into position, scale and rotation using glm or even ofMatrix and feed the components into an ofNode
