### ISSUE TITLE
0.10.0RC4 for MSYS2

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#5996]
libcurl (required by pkg-config in makefile) is not installed by install-dependencies.sh
It should be installed with paman -Sy mingw-w64-i686-curl

**Comment by arturoc** [comment]
hey thanks, can you send a PR? otherwise i can take a look later

**Comment by oxillo** [comment]
Sorry! It is included. I took the wrong install of MSYS2 on my PC!
So closing.
