### ISSUE TITLE
ofNode::setGlobalOrientation wrong order of quaternion multiplication.

### ISSUE THREAD

**Issue by yusuketomoto** [openframeworks/openFrameworks#6005]
Hi, I found a bug that ofNode doesn't correctly set global orientation. The order of quaternion multiplication seems to be flipped. I guess this has been happening since glm was introduced.

Here : 
`auto m44 = q * glm::toQuat(invParent);`
should be
`auto m44 = glm::toQuat(invParent) * q;`
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/3d/ofNode.cpp#L238

Also here is a minimum code that reproduces the bug:
```
class ofApp : public ofBaseApp {
    ofNode parent, child, independent;
    ofEasyCam ecam_l, ecam_r;
    
public:
    void setup() {
        ofBackground(0);
        
        glm::quat parent_orientation(0.707106, -0.0012919, -0.707105, 0.0012919);
        glm::quat target_orientation(-0.083116, -0.649839, 0.0718156, 0.752093);
        
        child.setParent(parent);
        parent.setOrientation(parent_orientation);
        child.setGlobalOrientation(target_orientation);
        
        independent.setOrientation(target_orientation);
    }
    void draw() {
        // The both should be headed in the same direction
        ecam_l.begin(ofRectangle(0, 0, ofGetWidth() * 0.5, ofGetHeight()));
        child.draw();
        ecam_l.end();
        
        ecam_r.begin(ofRectangle(ofGetWidth() * 0.5, 0, ofGetWidth() * 0.5, ofGetHeight()));
        independent.draw();
        ecam_r.end();
    }
};
```

Tested on macOS Sierra 10.12.6 with Xcode 9.2 (9C40b).
Thanks

**Comment by yusuketomoto** [comment]
I am sorry about bad timing posting this issue just after of_0.10.0 is released. That was not my intention 🙇

**Comment by arturoc** [comment]
no worries! :) there'll be more issues for sure, can you send a PR against the stable branch? we can do a patch release with any issues that are found in the following days
