### ISSUE TITLE
Undefined symbols in ios assimpExample: "irr::io::createIrrXMLReader(irr::io::IFileReadCallBack*)"

### ISSUE THREAD

**Issue by eighteight** [openframeworks/openFrameworks#6009]
release ios 0.10.0

**Comment by pierdr** [comment]
Any updates on this issue? I'm on of 0.10.1 (mac 10.13.6, Xcode  10.1) and I still have the same error.

**Comment by kimkulling** [comment]
This issue is closed on the latest master of assimp. So updating will fix this.

**Comment by dimitre** [comment]
Assimp was updated so I'll be closing this one
