### ISSUE TITLE
ofxOpenCV in 0.10 unable to compile CV_RGB error

### ISSUE THREAD

**Issue by misteryyy** [openframeworks/openFrameworks#6012]
Hello, 
I am trying to compile for gcc5 empty example with ofxOpenCv included. 
When I am trying to compile it with make I am getting this error:

/home/misteryyy/afekt/of_v0.10.0_linux64gcc5_release/addons/ofxOpenCv/src/ofxCvImage.cpp:393:32: error: ‘CV_RGB’ was not declared in this scope

Is there any way how to fix it?
Thank you for help, 
Josef

**Comment by Wolftronics-SBC** [comment]
//CV_RGB(color,color,color) );
                cv::Scalar(color,color,color) );

**Comment by biswajitcsecu** [comment]
dirty fix...
//CV_RGB(color,color,color) );
cv::Scalar(color,color,color) );

Working... thank you.

**Comment by xlla** [comment]
> dirty fix...
> //CV_RGB(color,color,color) );
> cv::Scalar(color,color,color) );
> 
> Working... thank you.

it's wrong sequence.
