### ISSUE TITLE
[proposal] rename `test` macro to `ofxTest()` or other name.

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#6014]
i want to use ofxUnitTests, but it has brutal macro `test`.

maybe someone use `test` in SFINAE idiom like:
https://stackoverflow.com/questions/4136359/why-cannot-the-following-sfinae-test-detect-a-template-member-function
and broken by macro.

i can understand why ofxUnitTests uses `test` macro.
and, of course, i can remove it with `undef test`.
but i want to propose to use more unique name like `ofxTest` or other.

what do you think about it?

**Comment by 2bbb** [comment]
ah... i can't clear problem with `undef`, it will break ofxUnitTests...
i clear it with order of include.

**Comment by arturoc** [comment]
that makes a lot of sense, can you send a PR changing the macros to ofxText* and updating the tests?

**Comment by 2bbb** [comment]
@arturoc 

okay. i will try it!
