### ISSUE TITLE
0.10 for iOS release on downloads page has the OSX Project Generator, not iOS

### ISSUE THREAD

**Issue by Miles-Tone** [openframeworks/openFrameworks#6015]
I downloaded 0.10 through the site and the iOS download's Project Generator is the OSX one, made evident when you try to create/update a project, it only has "OSX (Xcode)" within the "platform" section

**Comment by aferriss** [comment]
I ran into this today too. A simple work around is to just check the Advanced Features box and then choose iOS in the platform dropdown. 

@sortofsleepy made a [gist with some screenshots](https://gist.github.com/sortofsleepy/da09b4dc9f9f632f1411d37a1847a743)
