### ISSUE TITLE
ofParameterGroup:remove() issue

### ISSUE THREAD

**Issue by eduardfrigola** [openframeworks/openFrameworks#6016]
I think I found a bug in the `remove` function of `ofParameterGroup`.
When removing parameters of the group with `ofParameterGroup::remove(const string &name)`. The `parametersIndex` (the map that stores the position of each parameter in the `parameters` vector) is not updated when a parameter is removed.

I've tested this solution and works for me, don't know if is the best way to do it:
```cpp
void ofParameterGroup::remove(const string &name){
    if(!contains(name)){
       return;
    }
    int paramIndex = obj->parametersIndex[name];
    obj->parameters.erase(obj->parameters.begin() + obj->parametersIndex[name]);
    obj->parametersIndex.erase(name);
    std::for_each(obj->parametersIndex.begin(), obj->parametersIndex.end(), [&](pair<const string, size_t>& i){
       if(i.second > paramIndex){
           i.second--;
       }
    });
}
```

**Comment by roymacdonald** [comment]
Hi, I think that it might be safer to rebuild the map and have a private function for that, although it can be slower than what you are suggesting.
something like 
```
void ofParameterGroup::rebuildParameterIndexMap(){
   obj->parametersIndex.clear();
   for(size_t i =0; i < obj->parameters.size(); i++){
       obj->parametersIndex[obj->parameters[i]->getName()] = i;
   }
}
```
probably @arturoc  or @bakercp can have a better insight.
cheers

**Comment by eduardfrigola** [comment]
Yes, something like this seems better, and most of the times when using this function speed won't be crucial, but if you have a long list of parameters, and in the case you are only removing the last one, there is no need to rebuild the map because you know for sure the indexs won't change.
My thought was that I only want to edit the parameters that were after the parameter I've removed.
Also I think a map is safer enough to not use the clear method, or am I wrong?
```cpp
void ofParameterGroup::rebuildParameterIndexMap(int beginParameter){
   for(size_t i = beginParameter; i < obj->parameters.size(); i++){
       obj->parametersIndex[obj->parameters[i]->getName()] = i;
   }
}
```
And with beginParameter as 0, you have the same functionality as your function, besides the clear command.

Thanks!

**Comment by roymacdonald** [comment]
Hi,
I see your point and agree with you.  
Maybe it is a good idea to place a Pull Request. can you?
best

**Comment by eduardfrigola** [comment]
Newbie in Pull Requests but I think I can succeed in that.
Not sure if is better to mix things, but it is also a issue for the remove method, consistent to issue title.
Every time there is parameterGroup method which receives the parameter name to do things, like: `contains`, `get`, or `getPosition`. The name is escaped, so that when is searched in the map it can be found either you pass the name or you pass the escaped name of that parameter.
So I thing, for consistency the name should be escaped. Am I wrong with that? It's good thing to include that in the pull request?
