### ISSUE TITLE
Contours malformed on some fonts ofTrueTypeFont

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#6019]
v 0.10.0
Verified on macOS 10.13.4, Linux Mint / Ubtuntu using the macOS Helvetica.ttc system font.

![blank_skitch_document](https://user-images.githubusercontent.com/300484/39963306-7d391bfc-562d-11e8-9adc-c253614f5522.png)

```cpp
#include "ofMain.h"


class ofApp: public ofBaseApp
{
public:
    void setup() override
    {
        ttf.load("/System/Library/Fonts/Helvetica.ttc", 100, true, true, true);
        ofBackground(0);
    }
    
    void draw() override
    {
        ofNoFill();
        ttf.drawStringAsShapes("Hello World!", 100, 200);
    }
    
    ofTrueTypeFont ttf;
    
};


int main()
{
    ofSetupOpenGL(1024, 320, OF_WINDOW);
    return ofRunApp(std::make_shared<ofApp>());
}
```

**Comment by bakercp** [comment]
@arturoc I have a clean and simple solution from `ofxFont`that uses `FT_Outline_Decompose` to automatically iterate through the contours to produce an `ofPath`.  It happens to be the same way Skia, Cinder, et al create their contours and it requires very little custom code.  I'm happy to submit it in a PR, which would replace the manual `static ofPath makeContoursForCharacter(FT_Face face)` function.  This should probably be fixed for 0.10.1, but maybe you'd prefer to just sift through the code and fix the bug rather than replacing the whole function?  Let me know if you'd like a PR and what branch (patch or master) it should go to.

**Comment by arturoc** [comment]
yes if you have a more reliable method to do this a PR is welcome

**Comment by arturoc** [comment]
I'm testing this and it works fine for me at least in ubuntu with the latest helvetica.ttc from 10.13.6, haven't tested in osx itself yet
