### ISSUE TITLE
Works with Mac Cocoa Frameworks

### ISSUE THREAD

**Issue by tuduongquyet** [openframeworks/openFrameworks#6026]
Can we make openFrameworks work with Mac Cocoa Frameworks ?

For example, we can have ofVideoPlayer with view embedded in NSView or we can use ofOpenGLRenderer in NSOpenGLView?

**Comment by roymacdonald** [comment]
Hi there are some addons for doing such. although I'm not sure if these are updated. search in ofxaddons.com

best!

**Comment by roymacdonald** [comment]
btw, this is not an issue, it should have been posted in the OF forum instead.
I suggest closing this.
