### ISSUE TITLE
When calling close() on a shared_ptr of a ofAppBaseWindow, it causes it crash

### ISSUE THREAD

**Issue by EmersonSnow** [openframeworks/openFrameworks#6028]
Hello,

I'm working with multiple windows, and creating a singleton class that allows me access all windows functionality anywhere (which I think you should add to oF), however when calling close() on any window openFrameworks crashes. Where it points to is ofAppGLFWWindow::getWindowShouldClose(), it looks like windowP has become an nullptr within ofAppGLFWWindow::close(), while getWindowShouldClose() is still being called. 

I changed ofAppGLFWWindow::getWindowShouldClose() to this:
```
bool ofAppGLFWWindow::getWindowShouldClose(){
	if (windowP == nullptr)
		return true;

	return glfwWindowShouldClose(windowP);
}
```

And it fixed the problem.

All the Best

**Comment by arturoc** [comment]
windows' close method shouldn't be called from applications. if you want to close a window you should call `setWindowShouldClose` instead which will let the main loop know that that window needs to be closed when it's safe to do so. 

I've made that function private so others don't try to call it in the future
