### ISSUE TITLE
window larger than width of display is created at half size on mac

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#6032]
previously, large windows were causing a SIGABRT #5969

that's not a problem any more, but i do see another weird behavior when using "high resolution capable" mode on mac with the latest OF from github.

my display is 1440x900 retina (2x pixel density). running this code:

```c++
#include "ofMain.h"

class ofApp : public ofBaseApp {
public:
    void setup() {
        ofBackground(0);
        ofNoFill();
    }
    void draw() {
        ofDrawLine(0, 0, 1440, 900);
        ofDrawLine(1440, 0, 0, 900);
        ofDrawRectangle(0, 0, 1440, 900);
    }
};

int main() {
    ofSetupOpenGL(1440, 900, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

then i get:

<img width="720" alt="screen shot 2018-05-21 at 11 19 32" src="https://user-images.githubusercontent.com/157106/40323649-e17be482-5cea-11e8-9a1d-3f399eaa22c2.png">

perfect. if i change to `ofSetupOpenGL(1441, 900, OF_WINDOW);` i get:

<img width="1440" alt="screen shot 2018-05-21 at 11 19 44" src="https://user-images.githubusercontent.com/157106/40323677-ff00199c-5cea-11e8-9e9d-6f1db73f7e52.png">

strange. this only happens in the x axis. if i change the height it seems to handle it fine. changing the height to 1024 i get:

<img width="720" alt="screen shot 2018-05-21 at 11 20 18" src="https://user-images.githubusercontent.com/157106/40323731-26015952-5ceb-11e8-84fa-54f5fc0d6b4a.png">

**Comment by roymacdonald** [comment]
Hey Kyle.
Just PR'd a fix for this.
https://github.com/openframeworks/openFrameworks/pull/6033
best!

**Comment by roymacdonald** [comment]
you're welcome. happy to contribute. 
cheers
