### ISSUE TITLE
Poco issues on Windows (vs2015)

### ISSUE THREAD

**Issue by jordiexvision** [openframeworks/openFrameworks#6044]
I'm getting a linker error:

```
Severity	Code	Description	Project	File	Line
Error	LNK2019	unresolved external symbol GetAdaptersInfo referenced in function "public: static void __cdecl Poco::EnvironmentImpl::nodeIdImpl(unsigned char (&)[6])" (?nodeIdImpl@EnvironmentImpl@Poco@@SAXAEAY05E@Z)	ofxVideoRecorderExample	G:\openFrameworks\addons\ofxVideoRecorder\ofxVideoRecorderExample\PocoFoundationmdd.lib(Environment.obj)	1
```

Any ideas on how to fix it?

(I did run the latest download_libs.ps1 successfuly)

**Comment by jordiexvision** [comment]
I managed to compile only in 64bit (both release and debug) by doing the following:
- adding this header `#include <Iphlpapi.h> `
- changing my project to load the following system library `Iphlpapi.lib`

I guess the addon has to work straight without any additional hacks.
Should I start a PR?

**Comment by arturoc** [comment]
vs2015 is not supported anymore what version of OF are you using? the current ofxPoco addon is addnig that library through the addon_config.mk already

**Comment by jordiexvision** [comment]
Thank you @arturoc ,
I'm in current stable branch. 
If vs2015 is not supported anymore we can close this. 
No idea if it happens in vs2017 tho.

**Comment by arturoc** [comment]
i was asking cause i found it weird that it would work with 2015 at all but it might be that you have an old project (we only dropped 2015 at  the very end of the release cycle) so it still works with 2015 but the addon is not properly configured.

if that's the case try running the PG that will surely break the project for 2015 but will solve this

**Comment by jordiexvision** [comment]
Great thanks! 
One last thing. I realized that the addon_config.mk uses "iphlpapi.lib" but the lib starts with uppercase "Iphlpapi.lib". 
Could that cause any problem?
