### ISSUE TITLE
0.10 iOS multitouch doesn't work

### ISSUE THREAD

**Issue by Miles-Tone** [openframeworks/openFrameworks#6052]
touch.id is always 0, and touch.numTouches is always 1

**Comment by kkshmz** [comment]
Hi, what development environment and what is the version of the iOS?

**Comment by Miles-Tone** [comment]
XCode and iOS 11
I’m away from my machine, so I can’t give the specific version numbers of both.
When I move my whole project into oF0.9.8 it works as expected through Xcode and iOS 11

**Comment by AndresCuervo** [comment]
> touch.id is always 0, and touch.numTouches is always 1

I'm seeing the same behavior for iOS 12.0 & OF 0.10.0.

**Comment by dimitre** [comment]
I confirm the same behavior here in OF 0.10.0, XCode 9.2 (9C40b) and IOS 9.3.5

**Comment by sourya-sen** [comment]
Any update on this?

**Comment by sourya-sen** [comment]
It was not broken, `settings.enableMultiTouch = true;` needs to be added to the main.mm file, that's all. Just added that into the template for main.mm (default false) so that it's an easier setting to find.
