### ISSUE TITLE
PROJECT_CXX in config.make does not work (here is why)

### ISSUE THREAD

**Issue by ghost** [openframeworks/openFrameworks#6059]
The problem is caused by commit [https://github.com/openframeworks/openFrameworks/commit/56ad3fd926e12b3ccc8d5c5c4691600f00f89ed5](https://github.com/openframeworks/openFrameworks/commit/56ad3fd926e12b3ccc8d5c5c4691600f00f89ed5).

The thing is that CXX is an automatic variable in make ([https://www.gnu.org/...](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html), [https://stackoverflow.com/...](https://stackoverflow.com/questions/11394659/where-does-the-value-of-cxx-in-a-makefile-come-from)) The commit makes it so that PROJECT_CXX is assigned to CXX only if CXX is not set. But CXX is always set by default by make so the PROJECT_CXX will never have any effect.

I do not know exactly why that change was made, but I guess that reverting the commit will not be a good enough solution.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/6787
