### ISSUE TITLE
ProjectGenerator missing symbol from FreeImage

### ISSUE THREAD

**Issue by Paul92** [openframeworks/openFrameworks#6061]
I might have done something stupid, but I can't figure out what.

The operating system is Archlinux, with the latest updates, trying to compile OF from the master branch.

The error I am getting while running projectGenerator is

 ./projectGenerator: symbol lookup error: /usr/lib/libfreeimage.so.3: undefined symbol: _ZTIN7Iex_2_27BaseExcE

Any advice?
Thanks

**Comment by Najrim** [comment]
I'm new to openFrameworks and just began setting it up today. I get the same error as you just trying to run a compiled example program, also with the undefined symbol `_ZTIN7Iex_2_27BaseExcE`. `make` finishes without errors but when I try `make run` I get that exact same error message (Error code 127). I'm running Arch Linux.

**Comment by Paul92** [comment]
Thanks for letting me know
