### ISSUE TITLE
pugixml.lib 64 bit release is wrong version

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#6062]
Running the download libs script currently returns the wrong libs for the release version of VS2017 pugixml.lib. Compiling in release mode with this lib throws:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1047	The object or library file 'openFrameworks\libs\openFrameworksCompiled\project\vs\\..\..\..\..\\libs\pugixml\lib\vs\x64\pugixml.lib' was created with an older compiler than other objects; 
```
The debug version is correct.

**Comment by fred-dev** [comment]
This was due to various addon in several projects and not OF. Sorry for the misdiagnosis, I just got to the bottom of it.

**Comment by autr** [comment]
Hi @fred-dev , can you elaborate how you got to the bottom of it? I'm having the same problem on Release, but cannot see any includes for pugixml in my addons
