### ISSUE TITLE
videoGrabberExample fails with runtime error in Win10 x64 due to missing VCOMP120.dll

### ISSUE THREAD

**Issue by golanlevin** [openframeworks/openFrameworks#6063]
I encountered a fatal runtime error with videoGrabberExample, as follows: 
- In a brand-new, clean install of 64-bit Windows10, 
- Using OF 0.10.0 with VisualStudio 2017 
- Compiling videoGrabberExample as debug or release for x64 (not Win32)
The OS complains that VCOMP120.DLL is missing ("The program can't start because VCOMP120.DLL is missing from your computer"), and the grabber program fails to run. 

An internet search turns up that this DLL had been included in the VisualStudio 2013 Redistributables. 
I first tried installing the VisualStudio 2017 Redistributables, figuring they might be more appropriate for my newer OS. This did NOT work. I then installed the VisualStudio 2013 Redistributables, using the ones from here: https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package . Everything now works fine. 

My only guess is that @ofTheo's VideoInput library may have some old cruft from 2013 in it (?). 
best
Golan

**Comment by wasawi** [comment]
I had similar issues but in my case it was happening only when VisualStudio was not installed at all in the machine.
We had [a discussion ](https://forum.openframeworks.cc/t/msvcp140-dll-and-vcruntime140-dll-are-missing/25252) on the forum. Not sure if it will be of any help in your case tho.
best,
jordi

**Comment by arturoc** [comment]
This seems to happen with any project and it's actually related to freeimage not sure if we can remove the dependency at all or just advice to install the 2013 redistributable when installing vs
