### ISSUE TITLE
Video Grabber immediately crashes on setup in 0.9.8 with xcode 10 on release

### ISSUE THREAD

**Issue by aferriss** [openframeworks/openFrameworks#6067]
I'm trying to run the video grabber in 0.9.8 with xcode 10 beta 2. The grabber works fine in debug build mode, but upon switching to release the app will instantly crash with an error in the setup method of the video grabber. It looks like it's happening in the setPixelFormat function. 

![screen shot 2018-07-06 at 12 56 05 pm](https://user-images.githubusercontent.com/3698659/42397800-2f9b3122-811c-11e8-957b-2c6ae9d5b4ae.png)

**Comment by arturoc** [comment]
HAve you tested with 0.10? we are not maintaining 0.9.8 anymore

**Comment by aferriss** [comment]
Yep, it does fine with 0.10. I'll close since 0.9.8 isn't being updated any longer.

**Comment by arturoc** [comment]
thanks!
