### ISSUE TITLE
Unable to install on Pi due to dependencies.sh fail

### ISSUE THREAD

**Issue by jtreg** [openframeworks/openFrameworks#6071]
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/s/systemd/libudev-dev_232-25+deb9u2_armhf.deb  404  Not Found
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/g/glib2.0/libglib2.0-dev_2.50.3-2_armhf.deb  404  Not Found
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/libx/libxcb/libxcb-shm0-dev_1.12-1_armhf.deb  404  Not Found
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/libe/libepoxy/libepoxy-dev_1.3.1-2_armhf.deb  404  Not Found
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/o/opencv/libopencv-stitching-dev_2.4.9.1+dfsg1-2_armhf.deb  404  Not Found
E: Failed to fetch http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/pool/main/p/pulseaudio/libpulse-mainloop-glib0_10.0-1+deb9u1_armhf.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

**Comment by jtreg** [comment]
Sure, but is there a work-around; can I get each missed dependency somehow please?

**Comment by arturoc** [comment]
this doesn't seem like a bug in OF and it probably has been solved by itself but please ask in the forum if you still have the same problem
