### ISSUE TITLE
Removing warnings from videoInput.h

### ISSUE THREAD

**Issue by CyrCom** [openframeworks/openFrameworks#6072]
There is a bunch of warnings that can be annoying if you have to see them a 1000 time, here is a quick fix to apply (if requested, I can make a PR, but it would be really easier for me if someone just incorporates it quickly)

Warning: converting to non-pointer type `<long int>` from null
In videoInput.h : those function have a default argument NULL that has to be 0, like this:
```
                bool setVideoSettingFilter(int deviceID, long Property, long lValue, long Flags = 0, bool useDefaultValue = false);
                bool setVideoSettingFilterPct(int deviceID, long Property, float pctValue, long Flags = 0);
		bool getVideoSettingFilter(int deviceID, long Property, long &min, long &max, long &SteppingDelta, long &currentValue, long &flags, long &defaultValue);

                bool setVideoSettingCamera(int deviceID, long Property, long lValue, long Flags = 0, bool useDefaultValue = false);
                bool setVideoSettingCameraPct(int deviceID, long Property, float pctValue, long Flags = 0);
		bool getVideoSettingCamera(int deviceID, long Property, long &min, long &max, long &SteppingDelta, long &currentValue, long &flags, long &defaultValue);
```

It is really quick if you already have a fork. Thanks you so much.

**Comment by arturoc** [comment]
This is an issue in an external dependency, can you open an issue in it's own repo? https://github.com/ofTheo/videoinput
