### ISSUE TITLE
gstreamer not installed correctly by OF install script. 

### ISSUE THREAD

**Issue by steeley** [openframeworks/openFrameworks#6080]
Platform: raspberry pi3 B+
OS: 2018-06-27-raspbian-stretch-lite
OF: 0.10

issue: 'ofGstVideoUtils not loaded' errors in OF apps that require video input.

Apparent solution: install gstreamer from command line as per developers instruction:

**apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools**

Test: plug in a USB webcam and  run videoGrabberExample.

**Comment by arturoc** [comment]
did you run the install_codecs script? most of those modules are installed in install_dependencies except for plugins_ugly which has some code that can be patented in some countries or have some problematic licenses so we install it in install_codecs as explained in the documentation

going to close this but feel free to re-open if you think it's still an issue

**Comment by eightlines** [comment]
I can confirm I'm having this problem, 
oF 0.10.1 (Downloaded Nov 26, 2018)
Raspbian Jessie (8.0)

I've installed both the plugins in the initial post as well as the install_codecs.sh script. Trying to run the /examples/video/videoGrabberExample.

[warning] ofGSTVideoUtils: update(): ofGstVideoUtils not loaded

**Comment by steeley** [comment]
This error will also happen if your camera is not detected correctly, or gstreamer is installed incorrectly(or not at all). If using a Pi camera make sure it works using raspivid.
(https://www.raspberrypi.org/documentation/usage/camera/raspicam/raspivid.md)

You can can test gstreamer from the command line without any server running:
gst-launch-1.0 videotestsrc ! fbdevsink device=/dev/fb0

you should see a test card image.

**Comment by CarloCattano** [comment]
I also have this issue 
```[warning] ofGstVideoUtils: update(): ofGstVideoUtils not loaded```

Cant really downgrade gstreamer cause it would break my dependencies on arch.

Any good known workaround apart of whats already stated in this thread that you can think of ?
There should be a way to manually compile the gstreamer last known working version and point it with an env Variable to the binary or so ?

**Comment by ofTheo** [comment]
@CarloCattano - what hardware / system are you on?
Raspberry Pi?  What OS version? 

Are you trying the nightly build of OF? or 0.12.0
https://github.com/openframeworks/openFrameworks/releases/tag/nightly 

Thanks!
Theo

**Comment by ofTheo** [comment]
Ahh I was hoping it might be fixed by #8344 
cc @artificiel 

Def something to address before 0.12.1 

@CarloCattano can you try the `examples/video/videoPlayerExample` with the nightly release just to confirm it's an issue with OF? 

Also did you make sure to run:
`scripts/linux/archlinux/install_codecs.sh` ?

**Comment by artificiel** [comment]
current test setup that works correctly for `videoPlayerExample`:
```
$ pacman -Q|grep gstreamer
gstreamer 1.26.0-2
$ pwd
/home/artificiel/Downloads/of_v20250411_linux64_gcc6_release/examples/video/videoPlayerExample
$ ldd bin/videoPlayerExample |grep gst
    libgstapp-1.0.so.0 => /usr/lib/libgstapp-1.0.so.0 (0x00007e1162058000)
    libgstvideo-1.0.so.0 => /usr/lib/libgstvideo-1.0.so.0 (0x00007e1161f89000)
    libgstbase-1.0.so.0 => /usr/lib/libgstbase-1.0.so.0 (0x00007e1161f05000)
    libgstreamer-1.0.so.0 => /usr/lib/libgstreamer-1.0.so.0 (0x00007e1161aa6000)
```
@CarloCattano can you confirm the `videoPlayerExample` in `20250411` is not working for you? are you trying to playback or ingest? 

here no camera on that machine to test that now, which is still at `1.26.0-2` (2-3 weeks old?), perhaps something happened at `-3` but [changes are confined to the webkit](https://gitlab.archlinux.org/archlinux/packaging/packages/gstreamer/-/commit/91505dda7f75365f0cf348d67430f5f155595b41) (unfortunately not the right moment for an `-Syu`).

**Comment by CarloCattano** [comment]
@ofTheo  I did install the codecs.
On my nightly OF and arch the videoPlayer example works, some weird console output though
Might be cause I run it under xwayland
```

(videoPlayerExample:3158): GStreamer-CRITICAL **: 11:03:39.017: gst_segment_position_from_running_time_full: assertion 'segment->format == format' failed

(videoPlayerExample:3158): GStreamer-CRITICAL **: 11:03:39.017: gst_segment_do_seek: assertion 'segment->format == format' failed
```

But it does work, the error I posted is from trying the video Grabber example

**Comment by CarloCattano** [comment]
This is the current video Grabber example 

![Image](https://github.com/user-attachments/assets/42248ad2-dd62-4e7c-9eea-0cb4c972e642)

**Comment by CarloCattano** [comment]
thanks I'll do so

**Comment by CarloCattano** [comment]
@artificiel  I wrote a [forum post ](https://forum.openframeworks.cc/t/ofgstvideoutils-not-loaded-video-grabber-wont-grab/44571)

However I just tried on Ubuntu both nightly and 0.12 and I have the same exact issue . 
Should we open a new issue or reopen this one ?

**Comment by CarloCattano** [comment]
Other interesting logs 
```
[notice ] ofGstUtils: setPipelineWithSink(): gstreamer pipeline: v4l2src name=video_source device=/dev/video2 ! video/x-raw,format=DMA_DRM,width=640,height=360,framerate=30/1  ! videoscale method=2   ! appsink name=ofappsink enable-last-sample=0 caps="video/x-raw, format=RGB, width=640, height=480"
[ error ] ofGstUtils: setPipelineWithSink(): couldn't create pipeline: could not link video_source to videoscale0, video_source can't handle caps video/x-raw, format=(string)DMA_DRM, width=(int)640, height=(int)360, framerate=(fraction)30/1
```

**Comment by artificiel** [comment]
@CarloCattano yes it’s a different issue than this issue, which is about the install script. The error you are getting could be that “something changed” in GST and the pipeline OF uses needs tweaking, but it could also be environmental. Let’s wait a bit on the forum thread so the problem can be correctly diagnosed (you won’t get more eyes with an extra issue here as people watching GitHub issues are also watching the forum). I will try to find an usb cam in the meantime.
