### ISSUE TITLE
ofVideoPlayer setPosition and getPosition not consistent.

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6083]
I was trying to solve in my application a certain flickering and discovered a strange behavior on ofVideoPlayer.
if I set a new position on videoPlayer it doesn't go immediately to the video position, and even an immediate getPosition doesn't return the same value. 
One way of emulating this:
```c++
float pos = ofRandom(0,1);
cout << pos << endl;
video.setPosition(pos);
cout << video.getPosition() << endl;
```
I've even tried to update or draw the videoplayer before the .getPosition but even this way I get erratic behavior, I have to set position twice to get the right position and my impression is the actual video position is one command behind from what I want.
Thank you

OFW 0.10.0, Mac OS X 10.13.6, XCode 9.4.1

**Comment by dimitre** [comment]
if my new position is inferior to the actual video position the video.getPosition() even returns -inf (minus infinite)

**Comment by danomatika** [comment]
I believe the AVFoundation backend needs some amount of time to seek the video position, so you probably can't expect it to jump to the correct position immediately. It also depends on the timing tolerances that are being used (I've not looked).

**Comment by arturoc** [comment]
yes this is not expected to work like this anymore, all platforms video player backends now are multithreaded so when you call setPosition that doesn't happen immediately.

We might want to have a synchronous API and that's been discoursed explicitly in other issues so i'm going to close this one

**Comment by danomatika** [comment]
As a follow up, I checked and ofAVFoundationVideoPlayer is indeed using the minimum tolerance values for fastest seeking. It still takes time to buffer and decode, though.
