### ISSUE TITLE
ofSaveImage not thread safe

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#6084]
I have an addon [ofxImageSequenceExport](https://github.com/armadillu/ofxImageSequenceExport) to  save ofPixels to disk across multiple threads. I noticed some crashes when lots of threads are used to save images at the same time. The crash is pretty much always happening in [FreeImage_GetFIFFromFilename()](https://github.com/openframeworks/openFrameworks/blob/c67cd48a9eac10027bc9678c2c064215feb73d33/libs/openFrameworks/graphics/ofImage.cpp#L364) I suspect it's not thread safe. Address Sanitizer confirmed my suspicions.

As a test workaround, I mutexed both function calls with a static mutex

```c++
static std::mutex mutex;
mutex.lock();
fif = FreeImage_GetFileType(fileName.c_str(), 0);
if(fif == FIF_UNKNOWN) {
    // or guess via filename
    fif = FreeImage_GetFIFFromFilename(fileName.c_str());
}
mutex.unlock();
```

and the crashes disappeared.

**Comment by hiroMTB** [comment]
FreeImage itself looks thread safe except only one function (TagToString()).
https://sourceforge.net/p/freeimage/discussion/36109/thread/4a1f6f55/

**Comment by arturoc** [comment]
If that's theoretically the case but this function is in practice not thread safe you should report this in freetype. the proposed solution is quite hacky and adding this kind of patches here and there to fix problems in external dependencies would be problematic to maintain.

going to close this since it i don't think it's something we should solve in OF but please post if you find a solution that is not so problematic

**Comment by armadillu** [comment]
@hiroMTB they might say that, but it doesn't behave like so. 

@arturoc Yep, ok, it's quite a rare case. I should probably use freeImage directly (or another faster lib) instead of the ofSaveImage() anyway. I wasn't a proposing this as a fix, I was just trying to proof the crashes were coming from FreeImage_GetFileType() not being thread safe. 

I'm using this hack in production for now. The methods within the mutex are very short lived, so it doesn't seem to affect performance too much.

I will write a basic test case and report to FreeImage.
