### ISSUE TITLE
OpenGLES2 broken in Android (OF v0.10)

### ISSUE THREAD

**Issue by kkirby** [openframeworks/openFrameworks#6086]
Hello,

OpenGLES2 is, from what I can tell, completely broken in v0.10. If I try and use the shader example for Android all I get is a blank screen. When using v0.10 in my own personal project I also only get a blank screen. If I have a simple app to draw a red square, I still only get a blank screen. Only when I change it to use OpenGL (1?) will the app render to the screen.

I used `GAPID` to debug the app what's weird is the app is actually rendering correctly, it's just not outputting to the screen.

I've seen a few people talk about similar issues, but there is only one other issue that referencing something similar to this (#6047), but I think this issue is more general and consuming of the actual issue.

I've done a general skim through the code but I can't find anything super glaringly obviously wrong.

**Comment by kkirby** [comment]
I haven't found the issue yet, and unfortunately this has taken up too much of my time and I need to move on for now. It's unfortunate that I cannot upgrade my project to the latest OF because of this bug.

At any rate, here is what I've determined.

I made a simple project that renders a red square. When the app launches the background is set and is visible but the red square is not. I noticed that if I enable `Show GPU view updates` in the Developer Settings, and if I rotate the device enough times in a random fashion the square will eventually appear, but it will be rendered behind the task bar at the bottom of the screen, sometimes cutoff. If I rotate the screen again, it'll disappear. I have a screenshot of this below.

I've dug through `ofxAndroid` and I don't see much different between 0.9 and 0.10 other than most functions were extracted out to a helper class. I originally suspected something must have changed with how the surface view is created which would be inside of `OFAndroidWindow`, however it was left pretty much unchanged between the two versions.

As an aside I did notice that the private method `OFAndroidWindow::setup()` never gets called, but that's irrelevant.

I also tried initializing the app using EGL2 but overriding `ofxAndroid` to use the`ofGLRenderer` instead, which worked fine, sans shaders.

**ofApp.cpp**

```c++
ofGLESWindowSettings settings;
settings.setGLESVersion(2);
```

**ofAppAndroidWindow.cpp**

```c++
if(glesVersion<2){
    currentRenderer = make_shared<ofGLRenderer>(this);
}else{
    currentRenderer = make_shared<ofGLRenderer>(this);
}
```

I'm inclined to believe the issue isn't in `ofxAndroid`. I suspect highly the issue is contained inside of `ofGLProgrammableRenderer`. I logged the path of functions calls and checked them all against the previous working version and I'm unable to see anything that would really cause an issue like this. The only major change that I see is that `ofPoint` was changed to `glm` structs.

Ideally it would be nice to be able to revert this specific change to test if that's the issue, however
I think it may be more work than I can take on right now.

I noticed that inside of `ofGLProgrammableRenderer::draw(ofMesh)` that we're passing the `sizeof(ofVec3f)` instead of `sizeof(glm::vec3)`. I wasn't sure if this would be an issue, but changing it to use `sizeof(glm::vec3)` doesn't change anything that I can see.

I thought it may have something to do with the NDK platform being used so I changed it to one that I knew worked (can't remember which one). Though if this were the case I feel like more people would be reporting issues outside of OpenFrameworks.

I've debugged the application using GAPID and GAPID correctly renders the square using their simulator. I've attached a screenshot of the function calls to OpenGL and the shader code, etc.

I've also tried disabling the default shader (though I think it's necessary to render the color of the object, not really sure).

At this points I'm at a total loss of ideas.

Heres the details:

### Screenshot of square being rendered below task bar

![screenshot_nowpik_20180725-120236](https://user-images.githubusercontent.com/34333/43216196-f04bdaca-9003-11e8-823a-0aea83bf87b8.png)

### Path of function calls in ofGLProgrammableRenderer:

	::finishRender() 110
	::startRender() 88
	::beginDefaultShader() 1651
	::bind() 1402
	::uploadMatrices() 1622
	::setDefaultUniforms() 1637
	::viewport() 586
	::getBackgroundAuto() 1003
	::background() 1022
	::setBackgroundColor() 1015
	::setupScreen() 710
	::beginDefaultShader() 1651
	::setupScreenPerspective() 643
	::getCurrentViewport() 594
	::matrixMode() 802
	::loadMatrix() 815
	::uploadCurrentMatrix() 867
	::matrixMode() 802
	::loadViewMatrix() 841
	::uploadCurrentMatrix() 867
	::setColor() 936
	::setFillMode() 1047
	::drawRectangle() 1741
	::draw() 122
	::setAttributes() 1311
	::beginDefaultShader() 1651
	::finishRender() 110

### GAPID Stuff

#### Program 7 Fragment Shader

	uniform mediump vec2 _uuImageIncrement_Stage1;
	uniform mediump vec4 _uuKernel_Stage1[4];
	uniform lowp sampler2D _uuTextureSampler_0_Stage1;
	varying mediump vec4 _uvcolor_Stage0;
	varying highp vec2 _uvTransformedCoords_0_Stage0;
	void main(){
	mediump vec4 _uoutputColor_Stage0 = vec4(0.0, 0.0, 0.0, 0.0);
	{
	(_uoutputColor_Stage0 = _uvcolor_Stage0);
	}
	mediump vec4 _uoutput_Stage1 = vec4(0.0, 0.0, 0.0, 0.0);
	{
	(_uoutput_Stage1 = vec4(0.0, 0.0, 0.0, 0.0));
	highp vec2 _ucoord = (_uvTransformedCoords_0_Stage0 - (7.0 * _uuImageIncrement_Stage1));
	highp vec2 _ucoordSampled = vec2(0.0, 0.0);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[0].x));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[0].y));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[0].z));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[0].w));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[1].x));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[1].y));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[1].z));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[1].w));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[2].x));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[2].y));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[2].z));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[2].w));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[3].x));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[3].y));
	(_ucoord += _uuImageIncrement_Stage1);
	(_ucoordSampled = _ucoord);
	(_uoutput_Stage1 += (texture2D(_uuTextureSampler_0_Stage1, _ucoordSampled, -0.5).xxxx * _uuKernel_Stage1[3].z));
	(_ucoord += _uuImageIncrement_Stage1);
	(_uoutput_Stage1 *= _uoutputColor_Stage0);
	}
	{
	(gl_FragColor = _uoutput_Stage1);
	}
	(gl_FragColor = gl_FragColor.wwww);
	}

#### Program 7 Vertex Shader

	uniform highp vec4 _usk_RTAdjust;
	uniform highp mat3 _uuCoordTransformMatrix_0_Stage0;
	attribute highp vec2 _uinPosition;
	attribute mediump vec4 _uinColor;
	attribute highp vec2 _uinLocalCoord;
	varying mediump vec4 _uvcolor_Stage0;
	varying highp vec2 _uvTransformedCoords_0_Stage0;
	void main(){
	mediump vec4 _ucolor = _uinColor;
	(_uvcolor_Stage0 = _ucolor);
	highp vec2 _upos2 = _uinPosition;
	(_uvTransformedCoords_0_Stage0 = (_uuCoordTransformMatrix_0_Stage0 * vec3(_uinLocalCoord, 1.0)).xy);
	(gl_Position = vec4(_upos2.x, _upos2.y, 0.0, 1.0));
	(gl_Position = vec4(((gl_Position.x * _usk_RTAdjust.x) + (gl_Position.w * _usk_RTAdjust.y)), ((gl_Position.y * _usk_RTAdjust.z) + (gl_Position.w * _usk_RTAdjust.w)), 0.0, gl_Position.w));
	}

#### Rendered Frame Buffer

![07-25-2018 11 39 05 am](https://user-images.githubusercontent.com/34333/43215500-f08ae442-9001-11e8-80c6-00575c848c7e.png)

#### OpenGL Calls

![07-25-2018 11 38 57 am](https://user-images.githubusercontent.com/34333/43215524-fc74bea4-9001-11e8-8e36-04e4bc588f2e.png)

I would upload the GAPID capture but it contains information specific to my project since the OpenFrameworks activity is contained inside another activity that launches it. If someone thinks it would help diagnose the issue I can re-capture it in a cleaner environment.

**Comment by ivorne** [comment]
I had this same problem. Gles version was fied on the default gles 1 version and I was unable to change it from c++ code. One solution would be to hardcode the change in java activity code (on more than 1 places). The coro of the problem is in concurrency in java android activity code. The gles version settings are applied before we are able to change them from c++ code with createWindow. My solution was to do some minor changes in structure and concurrency of the activity code to ensure that gles context is created after initialization was done in c++ code. The commit that solves it in my fork is here: https://github.com/ivorne/openFrameworks/commit/74d6249b6856ab0b7bdf0d88dbe45f5f79459e1d

**Comment by arturoc** [comment]
Can you send a pull request with those changes?

**Comment by ivorne** [comment]
The pull request for this is https://github.com/openframeworks/openFrameworks/pull/6088.

**Comment by kkirby** [comment]
That makes total sense. I should have known the API calls wouldn't have been compatible. Thank you, times a million!

**Comment by ivorne** [comment]
@kkirby Glad to help. I spent a long time on it and I do not like Java much so the fact that somone else uses it cheers me up. I would apperciate if you would report how it works for you.

@arturoc May I know, why did you ask me to create the pull request? I am eager to learn that you had sincere reasons for it.

**Comment by arturoc** [comment]
@ivone what do you mean?

**Comment by ivorne** [comment]
@arturoc I wasn't sure if you intend to do something with it, like merging it. Never mind.
