### ISSUE TITLE
No console window

### ISSUE THREAD

**Issue by lilive** [openframeworks/openFrameworks#6103]
Hi,
OF 0.10.0, QtCreator 4.6.1, Windows 7
I have no console window when I run an executable built with OF and QtCreator. So I can't read the output logs of the application.

**How to reproduce this issue:**

- Create a new OF app with QtCreator > New project > OF application
- Add `ofLogWarning() << "No console !";` in setup()
- Build the app
- Double-click over the executable icon (using windows explorer)

Only one window is created for the application, there is no console window anymore. 
With the previous OF versions, a second windows was created, allowing to read the output message, logs, warnings, errors.

**Other informations:**

Even if I run the .exe from the command line, I can't read the logs. The console don’t wait for the app to close, and I can use it for other commands:

![729ae1bd9c59ff106640acae1f2974b06b33ab90](https://user-images.githubusercontent.com/2719976/43848876-3ea8d23c-9b34-11e8-8858-6ead2b1c0beb.gif)

The only way to be able to read the logs is to run the app from QtCreator. The logs are then printed to the "application output" panel.

Let me know if I can help.

**Comment by arturoc** [comment]
This is a feature not a bug, as explained already in the forum you can re-enable it with some qbs setting.

**Comment by lilive** [comment]
Ooops I missed it, sorry.

I tried to add an option in the QtCreator wizard, a check box which allow to enable or not the console window.
https://github.com/lilive/openFrameworks/commit/70190e6c488ed847c2290f6021aa795d2d5f2f0b
What do you think ?

**Comment by arturoc** [comment]
yeah that's really nice, please send a PR!

**Comment by lilive** [comment]
ok :)

Not sure about what to do with the changelog :
- Should I change it, as recommended in [CONTRIBUTING.md](https://github.com/openframeworks/openFrameworks/blob/master/CONTRIBUTING.md) ?
- If yes, is something like that correct:
```
PLATFORM SPECIFIC
-----------------
### msys2
    / QtCreator: New option in the wizard that allow to create a console window when the application start
```
- Where do I put these lines ? In the existing 0.10.0 section, or should I create a new 0.10.1 section at the beginning of the file ?

**Comment by arturoc** [comment]
no worries about the changelog, i'll add everything myself before the release

**Comment by lilive** [comment]
Thank you. Done !
https://github.com/openframeworks/openFrameworks/pull/6105
