### ISSUE TITLE
ofTrueTypeFont::getStringBoundingBox width returning different than previous versions

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6106]
using ofw 0.10.0 master (patch-release)
It seems to be missing exactly 4 pixels, independent of the string size. (comparing with 0.9.8 or 0.10.0 release)
<img width="179" alt="screen shot 2018-08-10 at 1 23 06 pm" src="https://user-images.githubusercontent.com/58289/43969836-cf22ae64-9ca1-11e8-8e26-ce89d4d55ba2.png">
Thanks

XCode 9.2 / OS X 10.12

**Comment by hiroMTB** [comment]
Is it ofDrawBitmapString()?
if you are using ofTTF, letterspacing calc has been change.
See details below.

issue
https://github.com/openframeworks/openFrameworks/issues/6066

solved by this commit
https://github.com/openframeworks/openFrameworks/commit/d9d7bc58ce6e882b1052b6090c438623c45d625b#diff-f3f73b7082dd42694f95ac109cbb1a05

**Comment by arturoc** [comment]
can you post a small example demoing the problem?

**Comment by dimitre** [comment]
```c++
#include "ofApp.h"

ofTrueTypeFont font;

//--------------------------------------------------------------
void ofApp::setup(){
	string fontFile = "mono0755.ttf"; //mono08_55.ttf //standard07_57.ttf
	font.load("_fonts/" + fontFile, 6);
}

//--------------------------------------------------------------
void ofApp::draw(){
	ofScale(10,10);
	string text = "teste de string";
	
	ofRectangle r = font.getStringBoundingBox(text, 10, 10);
	ofSetColor(255,0,0);
	ofDrawRectangle(r);
	ofSetColor(0,0,255);
	font.drawString(text, 10, 10);
}
```

<img width="983" alt="screen shot 2018-08-14 at 10 52 03 am" src="https://user-images.githubusercontent.com/58289/44095815-1d83c190-9fb0-11e8-9db2-69605619011d.png">

**Comment by dimitre** [comment]
Fonts, for a good cause. we delete this post after testing 
[Archive.zip](https://github.com/openframeworks/openFrameworks/files/2287177/Archive.zip)

**Comment by arturoc** [comment]
thanks! will give a try later
