### ISSUE TITLE
0.10.0 iOS assimpExample build/linking fails

### ISSUE THREAD

**Issue by streiten** [openframeworks/openFrameworks#6108]
Xcode 9.4.1 fails with a link error: undefined symbol "irr::io::createIrrXMLReader(irr::io::IFileReadCallBack*)" 

please find the full err [here](https://pastebin.com/ibya99jQ)
was trying to make this work for a couple of hours now but kind of stuck. found [this](https://github.com/assimp/assimp/issues/1283) on the way but no idea if this acuatlly relates to the assimp oF integration. 

ultimately trying to get some 3d animations together with ofxARKit and thus not able to revert to oF0.9.8 iOS where the ofxAssimpModelLoader building just fine.

**Comment by arturoc** [comment]
thanks, this has been reported already though so i'm going to close it

Duplicated https://github.com/openframeworks/openFrameworks/issues/6009
