### ISSUE TITLE
Is raspberry pi 3 supported for fox 0.10.0 and arm V7?

### ISSUE THREAD

**Issue by clankill3r** [openframeworks/openFrameworks#6120]
As the topic says:

Is raspberry pi 3 supported for fox 0.10.0 and arm V7?

I have been trying for around 7 hours now, with lots of digging in the fox forum and I can't get it done.

If I follow the most simple steps then I get:

> HOST_OS=Linux
> makefileCommon/config.shared.mk:207: *** This package doesn't support your platform, probably you downloaded the wrong package?. Stop.

**Comment by arturoc** [comment]
Not with raspbian. you need to use the armv6 download. The armv7 will only work with archlinux
