### ISSUE TITLE
ofVideoPlayer in emscripten doesn't support urls

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6124]
we should check if the passed path is an url and not try to open a file in that case

**Comment by kokawa2003** [comment]
Today I changed ofxEmscriptenVideoPlayer::load
like this
bool ofxEmscriptenVideoPlayer::load(string name){
cout<<“ookawa in:”<<name<<endl;
//string name2=ofToDataPath(name);
string name2=name; //temp please add check http://
cout<<“okawa out:”<<name2<<endl;
html5video_player_load(id,name2.c_str());
}
As a result,I can hear sound ,but no video(black out)
please tell me it’s reason.

**Comment by kokawa2003** [comment]
Next I call  fingerMovie.setPixelFormat(OF_PIXELS_???); ,before load
and change format from RGB to UYVY   
But not show correct picture.

**Comment by kokawa2003** [comment]
I found draw function is not call

**Comment by kokawa2003** [comment]
My poor knowledge of openframeworks cannot explain this:
it is streaming well,but it can not call draw.
Please help me

**Comment by kokawa2003** [comment]
And ofApp::draw and ofApp::update is working ,and sound well,
and can get picture(at least h,w>0)
but it can not show picture

My poor knowledge cannot explain this 
Must I do some initialize to campus? when it draw

**Comment by arturoc** [comment]
i think this is a cross origin security problem. by default you can't load resources in a canvas from a different server for security reasons. to solve it we need to add certain attribute to the canvas that plays the video in the background. I think in addons/ofxEmscripten/libs/html5video/lib/library_html5video.js line 89 add:

```js
videoImage.crossOrigin = "Anonymous";
```

but also the server where you load the video from needs to add a header to the response:

```
Access-Control-Allow-Origin "*"
```

https://stackoverflow.com/questions/22097747/how-to-fix-getimagedata-error-the-canvas-has-been-tainted-by-cross-origin-data

without that you want be able to see the video

**Comment by kokawa2003** [comment]
solved
right code is this 
html5video_player_create: function(){
var video = document.createElement('video');
video.loop = true;
video.pixelFormat = "RGB";
video.crossOrigin = 'anonymous';

 var player_id = VIDEO.getNewPlayerId();
 VIDEO.players[player_id] = video;
 video.onloadedmetadata = function (e){
 	console.log(this.videoWidth + 'x' + this.videoHeight);
 	VIDEO.players[player_id].width = this.videoWidth;
 	VIDEO.players[player_id].height = this.videoHeight;

     var videoImage = document.createElement( 'canvas' );
     videoImage.width = this.videoWidth;
     videoImage.height = this.videoHeight;
     //videoImage.crossOrigin = "Anonymous";
     var videoImageContext = videoImage.getContext( '2d' );
     // background color if no video present
     videoImageContext.fillStyle = '#000000';
     videoImageContext.fillRect( 0, 0, videoImage.width, videoImage.height );

     VIDEO.playersContexts[player_id] = videoImageContext;
 };

 return player_id;

},

**Comment by kokawa2003** [comment]
BTW
 which should I use "Anonymous" or   'anonymous'? 
A lot of Site is "Anonymous"  ...........

**Comment by dimitre** [comment]
cc @Jonathhhan

**Comment by Jonathhhan** [comment]
@dimitri yes :)
