### ISSUE TITLE
ofAbstractParameter::isType<ParameterType>()

### ISSUE THREAD

**Issue by eduardfrigola** [openframeworks/openFrameworks#6125]
I have been working with ofParameter a lot recently, and, despite trying to use templates as much as I can, somewhere I end up checking the type of a parameter. 

```cpp
if(p.type() == typeid(ofParameter<float>).name()){
    auto &cast = p.cast<float>();
}
else if(p.type() == typeid(ofParameter<int>).name()){
    auto &cast = p.cast<int>();
}
else if(p.type() == typeid(ofParameter<bool>).name()){
    auto &cast = p.cast<bool>();
}
else if(p.type() == typeid(ofParameter<ofColor>).name()){
    auto &cast = p.cast<ofColor>();
}
else if(p.type() == typeid(ofParameter<string>).name()){
    auto &cast = p.cast<string>();
}
```

I thing it will be nice to add a function to ```ofAbstractParameter``` class to be able to check the parameter type with less code, and something more readable. Something as:

```cpp
template<typename ParameterType>
bool isType(){
	return type() == typeid(ofParameter<ParameterType>).name();
}
```

The old code with the new function:
```cpp
if(p.isType<float>()){
    auto &cast = p.cast<float>();
}
else if(p.isType<int>()){
    auto &cast = p.cast<int>();
}
else if(p.isType<bool>()){
    auto &cast = p.cast<bool>();
}
else if(p.isType<ofColor>()){
    auto &cast = p.cast<ofColor>();
}
else if(p.isType<string>()){
    auto &cast = p.cast<string>();
}
```

Does this make sense? 
It makes ```type()``` unclear?
Does the name ```isType()``` is the correct one to use?

Eduard

**Comment by eduardfrigola** [comment]
Closing because #7620 implements this funcionality. Thanks @artificiel :)

**Comment by artificiel** [comment]
ha! i was not aware of this issue-proposal (there are too many issues...)
— typeid vs name, but pretty much the same effective result!
