### ISSUE TITLE
ofDirectory::sort() is slow! 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6129]
I noticed that with old projects which have a lot of png sequences that a project that used to take 20-30 seconds to load are now taking 15+ minutes. 

All I did was add sort() after calls to listDir() ( due to the non-sorted directories Apple lovingly introduced #5852 ) 

Taking the current dirListExample, calling sort() with listDir() makes a directory listing takes more than 10x longer than not calling sort(), but then getting randomly ordered results. 

I noticed that if I sort the files first as strings instead of as a vector ofFile::References it is almost as fast as not sorting at all. 

I think this might be due to the extra overhead of having files loaded into memory ( even as references ). 

I need to put together a PR for this, the main issue I see is that I am sorting inside of listDir before even creating the files vector. The plus side is you get sorted results by default without having to call sort(); But calling sort() will still be slow.  I could prob get the fix to work in sort() too without losing the performance improvement. It might just need to rebuild the file list which is doable. 

This is a comparison for sorting 110 files. 
```
Debug
 time diff for file list with current sort: 0.349263 seconds 
 time diff for file list with string based sort: 0.0325761 seconds 

= 10.7x faster with string based sort 

Release
 time diff for file list with current sort: 0.339156 seconds 
 time diff for file list with string based sort: 0.0316965 seconds 

= 10.7x faster with string based sort 
 ```

For 792 files:

```
Release:
 time diff for file list with current sort: 4.0761 seconds 
 time diff for file list with string based sort: 0.180382 seconds 

= 21x faster with string based sort
```

Going to post some more thoughts to this thread.

**Comment by arturoc** [comment]
i think when we open a file we open it by default for reading it so we are opening a handle to the file which can be quite expensive. when listing the dir i think we open it only in "reference" mode which doesn't open the file but there might be a bug somewhere where we are opening the file for read instead?

otherwise perhaps sorting over std::fs::path is probably more expensive than using strings but the fact that is so much is surprising

**Comment by ofTheo** [comment]
Here is some more timing. 
I think also part of the issue is the function calls inside of the natural compare function ( ofToString, ofToInt, getBaseName() ). 

If this is getting called for each compare it could be a source of some of the overhead.  

```
//------------------------------------------------------------------------------------------------------------
static bool natural(const ofFile& a, const ofFile& b) {
	string aname = a.getBaseName(), bname = b.getBaseName();
	int aint = ofToInt(aname), bint = ofToInt(bname);
	if(ofToString(aint) == aname && ofToString(bint) == bname) {
		return aint < bint;
	} else {
		return a < b;
	}
}
```

However if I do the sort inside of the listDir ( creating the files vector once ) its def faster. 
Here are some of the different timings. 

```
Current listDir() followed by sort():
0.867744 seconds 

New listDir() followed by sort() ( see code below ):
0.14695 seconds 

Sort before the files are opened in listDir()
0.0872705 seconds 

std::sort before the files are opened in listDir()
0.0605879 seconds 
```

Here's the code I have been using.
BTW I also think natural sort could use some love. It might be better to either just use std::sort or a real natural sort, but I'll open a new issue for that. 

```
//------------------------------------------------------------------------------------------------------------
struct StringSort{
    string path;
    string basename;
    int nameInt;
    string stringInt;
};

//------------------------------------------------------------------------------------------------------------
static bool naturalStr(const StringSort& a, const StringSort& b) {
    if(a.stringInt == a.basename && b.stringInt == b.basename) {
        return a.nameInt < b.nameInt;
    } else {
        return a.path < b.path;
    }
}

//------------------------------------------------------------------------------------------------------------
void ofDirectory::sort(){
	if(files.empty() && !myDir.empty()){
		listDir();
	}
 
    // -- new faster approach
//    vector <StringSort> sort;
//    sort.reserve(files.size());
//
//    for( auto & f : files ){
//        StringSort ss;
//        ss.path = f.getAbsolutePath();
//        ss.basename = f.getBaseName();
//        ss.nameInt = ofToInt(ss.basename);
//        ss.stringInt = ofToString(ss.nameInt);
//        sort.push_back(ss);
//    }
//
//    ofSort(sort, naturalStr);
//    files.clear();
//
//    files.reserve(sort.size());
//    for( auto & s : sort ){
//        files.emplace_back(s.path, ofFile::Reference);
//    }
    // -- end faster approach

    // -- old approach
    ofSort(files, natural);
    // -- end old approach
}
```

**Comment by arturoc** [comment]
That makes sense, if you want to send a PR i think that looks good.

**Comment by arturoc** [comment]
I think the default should be no sort since in some cases you might want to go through files in a directory as fast as possible and the order of the files won't matter.

Then listDir could have an optional sort parameter to sort files as it lists them instead of the current separate sort method. I wouldn't use an enum for the sort method but instead a compare function which is more standard and allows people to pass whatever function they want.

So something like:

```
ofDirectory::listDir();
template<typename CompareFunc>
ofDirectory::listDir(CompareFunc compare);
```

then have a couple of standard compare functions

```
ofSimpleCompare
ofNaturalCompare
...
```

not sure if the compare suffix is the most understandable probably something like Order would be beter?

We could even not call the second listDir simply listDir and instead name it something like:

```
template<typename CompareFunction>
ofDirectory::sortListDir(CompareFunction comapre = ofNaturalCompare);
```

so calling it without parameters will already give you natural sort which i imagine is what people would use more

**Comment by dimitre** [comment]
@ofTheo I think speed can be improved if we change this
```c++
std::vector <ofFile> files;
```
to this
```c++
std::vector <of::filesystem::path> files;
```
and update other functions accordingly. I can test this soon

**Comment by dimitre** [comment]
I've tested some code changes here and my test lists and sort 5845 image files.
time to dirList before = 171ms, after 16ms, subsequent runs = 4ms ( I suppose OS or disk caches something)

new implementation with sort from master = 2692 ms
replacing with ```std::sort(files.begin(), files.end());``` = 15ms
