### ISSUE TITLE
ofxGui scroll is active when it shouldn't be

### ISSUE THREAD

**Issue by samubence** [openframeworks/openFrameworks#6133]
You can change the value of a parameter e.g ofxSlider using the mouse scroll... which is a great feature.
But it still happens when the group is minimised and the cursor is not over the element. (it is very weird that in this case the slider only goes up and much faster than is was maximised)
The same happens when we don't display the panel, scroll still active.
This is a minimal code to demonstrate the behaviour. 

I'm using of_0.10.0 on macOS, xcode 10.0

```
#include "ofMain.h"
#include "ofxGui.h"

class ofApp : public ofBaseApp
{
public:
    void setup()
    {
        gui.setDefaultWidth(400);
        gui.setup();
        gui.setPosition(0, 0);
        group.setName("GROUP");
        group.add(param.set("param", 0, 0, 255));
        gui.add(group);
        displayGui = true;
    };
    
    void draw()
    {
        ofBackground(param, 0, 0);
        
        if (displayGui)
        {
            gui.draw();
        }
    };
    
    void keyPressed(int key)
    {
        displayGui = !displayGui;
    }
    
    ofxPanel gui;
    ofParameterGroup group;
    ofParameter<float> param;
    bool displayGui;
};

int main( )
{
	ofSetupOpenGL(400,100,OF_WINDOW);
	ofRunApp(new ofApp());
}
```

**Comment by roymacdonald** [comment]
I can see this happenig also. It is really annoying. It is related to the way that the scroll event is handled which is different to the rest of the mouse events. I am looking at this in order to fix it.
cheers

**Comment by roymacdonald** [comment]
just made a PR with the fix. Thanks for pointing it out
