### ISSUE TITLE
Closing second-to-last window & app breaks original app rendering

### ISSUE THREAD

**Issue by s-ol** [openframeworks/openFrameworks#6134]
My project consists of my main app `ofApp` and zero or more preview windows (`previewApp`).

In main.cpp I start up the `ofApp` only:

```C++
  auto window = ofCreateWindow(settings);
  auto app = make_shared<ofApp>();
  ofRunApp(window, app);
  ofRunMainLoop();
```

then at runtime I create the preview windows dynamically based on user input:
```C++
void ofApp::draw() {
...
      if (ImGui::Button("add output window")) {
        ofGLFWWindowSettings settings;
        settings.setGLVersion(4, 1);
        settings.shareContextWith = ofGetCurrentWindow();
        auto win = ofCreateWindow(settings);
        auto app = make_shared<previewApp>(*this);
        ofRunApp(win, app);
      }
...
}
```

I close the windows either using the window manager / close button or using 

```C++
void previewApp::keyPressed(int key) {
  switch (key) {
    case OF_KEY_ESC:
      ofGetCurrentWindow()->setWindowShouldClose();
      break;
...
  }
}
```

This works perfectly when I create two preview windows and close one of them; I can see that the `update` and `draw` hooks of the closed `previewApp` stop being called when I close the window using either method.

However when I close the last `previewApp` running, something strange happens. The main `ofApp`'s window goes black and stays that way, however my code in the `draw` method is still getting called. The app also doesn't run `exit` yet, which is correct, but leaves me with no clue of where this is going wrong.

Any help is very welcome.

**Comment by arturoc** [comment]
You shouldn't be running more than one window with the same application take a look at the multi window example. 

Also please for questions use the forum instead, this is only to report bugs or ask for new features

**Comment by s-ol** [comment]
@arturoc I've seen the example but it doesn't relate to what I am doing. Are you saying there shouldn't be more than one instance of each specific ofApp subclass?
Each window in my project is managed and associated with its own app instance - see above `make_shared<previewApp>()`

**Comment by arturoc** [comment]
oh sorry i thought you were using ofApp for the second window as well. using the same app for more than one window could be problematic though. i'll take a look when i have a moment

**Comment by s-ol** [comment]
@arturoc I will try to set up a minimal example if I find the time

**Comment by s-ol** [comment]
okay, so that first attempt failed - super simplified version seems to be working just fine (see attached example); so I'll have to investigate more.

Do you maybe have some ideas where windows closing could touch on my main window code? I use some extensions (ofxImGui, ofxMidi, ofxYAML), could one of them have a wrongly-set-up event handler maybe?
[repro.zip](https://github.com/openframeworks/openFrameworks/files/2426887/repro.zip)

**Comment by s-ol** [comment]
Okay, it looks like this is rather an issue with ofxImGui - draw() itself works fine, it's just that the UI completely (and silently) disappears when the second-to-last window closes. I will close this issue and continue the investigation in jvcleave/ofxImGui. If in the process of resolving it there this turns out to be an error in openframeworks I cannot find right now then I'll report back and reopen this.
