### ISSUE TITLE
mojave + xcode 10 issues

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#6139]
I'm looking at OF on Mojave and Xcode 10 which is kind of painful now -- 

some notes (cc @ofTheo) 

a) 32 bit needs to be removed (this has already been done in master...) 

b) on mojave apps need permission set as a plist for camera, microphone, and any other thing we might need to do that requires permissions (ala iPhone).  I feel like the easiest is we just add these to the template plist so that they are already set. 

c) there's something not right about the overall OF sub project, at the moment you can't open more than one OF project at the same time and build them (before you used to get an integrity warning but now it seems there is more of an error so you actually just can't build more than one project at once...  it's super weird) 

d) openframeworks library always gets rebuilt for each project :(  

(maybe looking at this issue which this reminded me of -- https://github.com/openframeworks/openFrameworks/issues/5895) 

I'm looking into b/c/d at the moment...

**Comment by ofZach** [comment]
update -- if I put projects in "legacy" build system they compile fine (meaning, no redundant compiling of OF, can have more than one OF project open at once and compile it, etc) 

<img width="589" alt="screen shot 2018-09-30 at 4 54 29 pm" src="https://user-images.githubusercontent.com/142897/46262621-c65d1c80-c4d1-11e8-937f-75917f4f7c96.png">

**Comment by ofZach** [comment]
also one issue I see with the main OF project in Xcode 10 is that it doesn't seem to build release lib for OF, I had to add another scheme for release (one scheme is for debug, the other for release)

**Comment by ofZach** [comment]
can confirm also that Xcode 9.4.1 works well on mojave (no repeat compiling of OF per project, no issues with multiple projects open) but we still have issues with the plist / permissions so things like video grabber example doesn't work yet. 

also if you add permissions to the plist 

<img width="1158" alt="screen shot 2018-09-30 at 5 32 07 pm" src="https://user-images.githubusercontent.com/142897/46262991-46d24c00-c4d7-11e8-9656-87e9db5286b9.png">

it seems that this plist doesn't doesn't work when you run the app from within xcode (9.4.1) but it does when you run outside of Xcode 

<img width="944" alt="screen shot 2018-09-30 at 5 38 05 pm" src="https://user-images.githubusercontent.com/142897/46263023-aa5c7980-c4d7-11e8-8665-e195d6c846b0.png">

I think this behavior is better on Xcode 10 but I'm not sure...

**Comment by arturoc** [comment]
This repeat compile of external dependencies for each project is kind of the norm in modern build systems. I think they do it cause then you can build more than one thing at once with different build flags... but it's kind of annoying for the way we use the OF library. 

In qt creator i just trigger a makefile build instead of using the internal dependency system, that way OF is compiled and only once. In xcode we could do something similar but we can either use makefiles or xcodebuild

**Comment by ofTheo** [comment]
This should now be all addressed in master / nightly builds as of the next nightlies.

**Comment by stephanschulz** [comment]
I am on macOS 10.14 Mojave with OF 0.10.1 on a 2018 Mac mini. 
when using crontab to open my OF app that uses a Logitech c920 usb camera and the ofxUVC camera controller the UVC connection does not get established. All works fine when manually opening it.
I guess it has todo with the sandboxing and hardening stuff?
