### ISSUE TITLE
Rendering completely broken on macos 10.14

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6147]
https://forum.openframeworks.cc/t/no-rendering-initially-in-mojave/30624

**Comment by ofZach** [comment]
I see this when I compile w/ xcode 10 on mojave, when I use xcode 9.4.1 on mojave things seem ok.  I'm seeing some very odd behaviors on xcode 10 (that are a little hard to understand) -- researching...

**Comment by ofTheo** [comment]
I wonder if this is connected to #6146 ? 
Maybe any window / gl calls fail in setup 

Might be worth looking and seeing if glfw has a update which addresses Mojave issues.

**Comment by arturoc** [comment]
yeah this is probably something to fix in glfw although it might be something with how we initialize it. we hide the window until after the first update which might be related. i would test not hiding the window and then running a glfw example compiled with xcode 10 to see where's the issue

**Comment by dimitre** [comment]
can this one be closed?
