### ISSUE TITLE
Android Studio for all of CPP files: This File is not part of the project...

### ISSUE THREAD

**Issue by whyameye** [openframeworks/openFrameworks#6153]
After trying the latest release of oF I switched to the master branch and am still having the same problem:
Using the project generator I convert an Android example to Android Studio. Then loading into Android Studio I get for all oF cpp files: "This file is not part of the project. Please include it in the appropriate build file..." I'm not an Android Studio expert and it is not obvious to me how to move forward as CMakelists.txt doesn't exist etc.

Android Studio compiles the code fine but practically every line is marked as an error in the IDE as all the references are broken.

**Comment by arturoc** [comment]
For questions please use the forum: https://forum.openframeworks.cc. This is only for reporting bugs or asking for missing features. Thanks

**Comment by whyameye** [comment]
Thanks for reopening. With a fresh download on the Android version of oF I found the cpp files of the examples that come with the download import correctly in Android Studio 3.14 but not in Android Studio 3.2, which is the latest Android Studio release and what I had been using. For now I'll just use 3.14, which is an OK workaround for me. I wonder if my issue is related to the last comment of #4193?

**Comment by arturoc** [comment]
Yes probably, they might have changed something in the experimental model that breaks our projects or even stopped supporting it, not sure. We moved to this experimental mode cause it was supposed the way they would handle cpp projects in the future after they deprecated eclipse but then they deprecated it right away without ever becoming stable so now we have to port the projects again to use cmake

**Comment by EHBradford** [comment]
Having this exact issue with a Flutter project.  When I try to run the project the following popup appears.  

It goes without saying that main.dart is exactly the file which is the entry point.  So tired of trying to fix this issue.  I am a total novice and have zero idea where to go other than re-sync with file-system, rebuild Gradle, etc. which makes Android Studio forget that I have enabled  Dart & Flutter.  Have to go back and re-enable them just about every time.

![tempsnip](https://user-images.githubusercontent.com/45748719/55103486-82209280-5096-11e9-94cf-edfc8a465fb4.png)

**Comment by EHBradford** [comment]
FYI, When I attempt to edit a file I get this popup

![tempsnip02](https://user-images.githubusercontent.com/45748719/55104259-0d4e5800-5098-11e9-8da8-15a9ee4ca2f2.png)

**Comment by EHBradford** [comment]
Okay, I just Synced the Project with Gradle files and this error has for the moment disappeared.  BUT, when I synced the project it lost the fact that I had enabled Dart.  The path to Dart was still there, but the checkmark enabling Dart was gone.  Flutter path was still.

I am writing this in the hopes that eventually the right person will see it and this can help them.
