### ISSUE TITLE
msys2 binary missing dependency

### ISSUE THREAD

**Issue by sphaero** [openframeworks/openFrameworks#6168]
I’m using appveyor to build an OF binary for windows. This used to work fine however I’m now running into an issue where my final binary is not working due to missing libraw-16.dll.

the log clearly shows libraw (19) being installed through pacman:

```
downloading mingw-w64-i686-libraw-0.19.0-1-any.pkg.tar.xz...
```

I’ve echoed ntldd -R to show what the dependencies are. It depends on libraw-16.dll as a dependency of freeimage but it is not found:

```
    libfreeimage-3.dll => C:\msys64\mingw32\bin\libfreeimage-3.dll (0x00ce0000)
	 libHalf-2_2.dll => C:\msys64\mingw32\bin\libHalf-2_2.dll (0x00760000)
	 libIex-2_2.dll => C:\msys64\mingw32\bin\libIex-2_2.dll (0x000d0000)
	 libIlmImf-2_2.dll => C:\msys64\mingw32\bin\libIlmImf-2_2.dll (0x01750000)
	  libIlmThread-2_2.dll => C:\msys64\mingw32\bin\libIlmThread-2_2.dll (0x000d0000)
	  libImath-2_2.dll => C:\msys64\mingw32\bin\libImath-2_2.dll (0x00760000)
	 libjpeg-8.dll => C:\msys64\mingw32\bin\libjpeg-8.dll (0x00dc0000)
	 libjxrglue.dll => C:\msys64\mingw32\bin\libjxrglue.dll (0x00760000)
	  libjpegxr.dll => C:\msys64\mingw32\bin\libjpegxr.dll (0x00790000)
	 libopenjp2-7.dll => C:\msys64\mingw32\bin\libopenjp2-7.dll (0x00760000)
	 libraw-16.dll => not found
	 libtiff-5.dll => C:\msys64\mingw32\bin\libtiff-5.dll (0x00760000)
```
Also posted on the forum: https://forum.openframeworks.cc/t/appveyor-build-installs-libraw-0-19-but-binary-depends-on-0-16/30916

Possibly an upstream bug in msys2?

**Comment by sphaero** [comment]
btw, I don't see this problem on my own windows build machine with msys2. It has mingw-w64-i686-freeimage Version 3.18.0-1. While on appveyor it has version  mingw-w64-i686-freeimage-3.17.0-4

**Comment by arturoc** [comment]
are you running pacman -Su at the beginning to update the packages?

**Comment by sphaero** [comment]
yes tried that as well, but will double check after the weekend

**Comment by sphaero** [comment]
yes tried that as well, here's a log which at least shows didn't need to update anything:
https://ci.appveyor.com/project/sphaero/mocap-csv2osc-0cqm8/builds/19975812

this is what it did before getting OF
```
%MSYS2_PATH%\usr\bin\bash -lc "pacman --needed --noconfirm -S bash pacman pacman-mirrors msys2-runtime"
warning: bash-4.4.019-3 is up to date -- skipping
warning: pacman-5.1.1-2 is up to date -- skipping
warning: pacman-mirrors-20180604-2 is up to date -- skipping
warning: msys2-runtime-2.10.0-2 is up to date -- skipping
 there is nothing to do
%MSYS2_PATH%\usr\bin\bash -lc "pacman --needed --noconfirm -Suu"
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

Weird because the msys guys are saying freeimage is linked against the right libraw. It must be something with the setup. I'll do some searching after the weekend.

**Comment by sphaero** [comment]
related as binaries produced through appveyor are missing ssl dlls:

https://github.com/appveyor/ci/issues/2571

**Comment by sphaero** [comment]
Ok I have a working build again. I did two changes to the appveyor config:

install missing ssl libraries:
https://github.com/hku-ect/NatNet2OSCbridge/commit/91b05050565edb50fbae3ef887014eaf957bdd08

upgrade pacman and msys on init 
https://github.com/hku-ect/NatNet2OSCbridge/commit/003a24bea1f336876515f4e7a7fea66eaf9eb96c

**Comment by arturoc** [comment]
great! do you think you can send a PR with the ssl change to the appveyor config in the OF repo?

**Comment by sphaero** [comment]
I've send a PR to master however it doesn't start appveyor automatically. Can you check if it resolves the appveyor errors?

**Comment by sphaero** [comment]
nevermind I should be more patient :)

**Comment by sphaero** [comment]
Ok, it works. You can merge the PR if you don't mind the history of tests, otherwise a new PR is needed
