### ISSUE TITLE
Can't compile on ubuntu 18.10

### ISSUE THREAD

**Issue by cjdg** [openframeworks/openFrameworks#6182]
Cant compile on Ubuntu 18.10, all the scripts end with exit status 1 and 2

**Comment by cjdg** [comment]
After checking i found the issue, but its getting weirder, its because ld its complaining about a missing library, "ld.gold: error: cannot find -lgl" but the thing is that all the libs are installed, so im continuing to trying to fix this.

**Comment by dimitre** [comment]
I'll be closing this, as it is probably fixed now. I've been using Ubuntu with no issues lately
