### ISSUE TITLE
Case sensitivity issue rtAudio.a

### ISSUE THREAD

**Issue by borg** [openframeworks/openFrameworks#6188]
"$(OF_PATH)/libs/rtAudio/lib/osx/rtAudio.a"
no such file or directory: '../../openFrameworks/libs/rtAudio/lib/osx/rtAudio.a'
Included lib lower case.

OSX
0.10.1

**Comment by ofTheo** [comment]
Hi! 

I think this is fixed in master / nightly builds: 
see #6184
