### ISSUE TITLE
ofImage doesn't maintain bUseTexture with emplace_back

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#6209]
I have some ofPixels coming from a decoder so I don't want to generate an ofTexture until it needs to be drawn (also making sure the generation happens on the main thread).

However I am running into this error when trying to use `emplace_back`. 

Here you can see `bUseTexture` is correctly set to false

![image](https://user-images.githubusercontent.com/150037/50877956-4123b680-13a2-11e9-84d6-a8d8238722df.png)

However at some time during the emplace_back process this is being set back to true, tries to generate the ofTexture and causes the error (because not on main thread)

![image](https://user-images.githubusercontent.com/150037/50877968-57317700-13a2-11e9-8573-627d7606761e.png)

**Comment by arturoc** [comment]
this must be a bug in the move or copy operator if you want to look into it.

**Comment by jvcleave** [comment]
just tried it outside my project and not seeing the same behavior. weird but will follow up if it happens again
