### ISSUE TITLE
Magic-Sand-1.5.4.1 (programm) failed on ubuntu 17.04 work with: of_v20190105_linux64gcc6_nightly.tar.gz

### ISSUE THREAD

**Issue by Code-shaker** [openframeworks/openFrameworks#6212]
`HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 
with PKG_CONFIG_LIBDIR=
/bin/sh: 1: ./Magic-Sand-1.5.4.1: not found
oF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:190: recipe for target „run“ failed
make: *** [run] Error 127`

$ sudo ./scripts/linux/ubuntu/install_dependencies.sh
$ sudo ./scripts/linux/ubuntu/install_codecs.sh
$ ./scripts/linux/compileOF.sh
and GCC is already installed

**Comment by arturoc** [comment]
Hi this is only to report bugs or ask for new features in openframeworks if you have problems with an specific OF application try asking the original author or in the openframeworks forum
