### ISSUE TITLE
Wrong mouse coordinates on raspberry pi 3

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6230]
Hello, I'm using a rapsberry pi 3 in FullHD resolution, an openframeworks of smaller dimensions (800x450) in a specific position (40,40).
I've noticed there is the normal cursor and another cursor in OF window. 
OF cursor moves with different speed and different position than system cursor, it seems to be constrained in OF window and if I  click inside the OF window the system handles the click for the other cursor too.
Thank you,

**Comment by sourya-sen** [comment]
I don't think this is a bug - oF doesn't use the Windowing system of the Raspbian Desktop but uses a native X11 (is this the correct term?) window (== why it can run straight from console without needing the X environment) so therefore it has it's own instance of the mouse etc constrained to that window.

**Comment by dimitre** [comment]
Thank you @sourya-sen
