### ISSUE TITLE
 I use ofArduino  to control my "mBot Ranger" car, but still don't work, please help to view my code. 

### ISSUE THREAD

**Issue by KallerLong1** [openframeworks/openFrameworks#6249]
ard.sendDigitalPinMode(4, ARD_OUTPUT);

	ard.sendAnalogPinReporting(5, ARD_PWM);

	ard.sendDigitalPinMode(7, ARD_OUTPUT);

	ard.sendAnalogPinReporting(6, ARD_PWM);

	ard.sendDigital(4, ARD_HIGH);
	ard.sendPwm(5, 200);
	
	ard.sendDigital(7, ARD_HIGH);
	ard.sendPwm(6, 200);

**Comment by arturoc** [comment]
Hi this is only for reporting bugs or ask for new features, for questions pleases use the forum: https://forum.openframeworks.cc
