### ISSUE TITLE
macOS 10.12 + OF0.10.1 ofAvFoundationGrabber no 4K ?

### ISSUE THREAD

**Issue by stephanschulz** [openframeworks/openFrameworks#6250]
```
[verbose] ofAvFoundationGrabber:  supported dimensions are: 2560 1440
```

I am trying to set the grabber to capture 4k or higher; 3840*2160. But I can't get the signal to come in properly. 

see here for detail discussion:
https://forum.openframeworks.cc/t/macos-4k-capture-with-magewell-usb-capture-sdi-4k-plus/31853

**Comment by ofTheo** [comment]
resolved in the forum
