### ISSUE TITLE
ofEvent::notify return value

### ISSUE THREAD

**Issue by eduardfrigola** [openframeworks/openFrameworks#6259]
Hi everyone!
I've noticed ofEvent.notify(...) does not return an usable value, seems to return false all the time. Looking at the code I understand why, if some func returns true, all other registers will be  not notified.
https://github.com/openframeworks/openFrameworks/blob/9d9f48619d2c4854253c01ed704373ed1f1723e1/libs/openFrameworks/events/ofEvent.h#L558-L584

Seems that what is preventing this to happen (to return true) is this, as seems to always return false, also no return statement seems that can be returned in listener functions.
https://github.com/openframeworks/openFrameworks/blob/9d9f48619d2c4854253c01ed704373ed1f1723e1/libs/openFrameworks/events/ofEvent.h#L88-L95

I've changed all this last piece of code so that does not return the value of the function, instead returns true if not exception is thrown (end of function). Also I've changed the event notify so that it checks if some func was send properly.

Maybe will be better to return the number times the event was cached?
Maybe there is a better approach for knowing if an event has someone registered to it?
I'm getting it totally wrong and it is not a bug?

Thanks
Eduard.

**Comment by arturoc** [comment]
This is not a bug, i think you are missunderstanding what the return value is supposed to mean. 

Listeners can optionally have a return value and if that value is true then it means the event is been attended and no other lsiteners will be notified. This allows for example to move a slider without ofEasyCam moving as well while you drag the mouse.

The return value of notify just means that the event was attended by some listener (true) or not (false)

**Comment by eduardfrigola** [comment]
Ok, thanks for the clarification! I found why is said: _"no return statement seems that can be returned in listener functions"_ . 
I was using a lambda listener but without using value by reference (I think is called like that), for example listening an ofEvent<string> I use `[this](string s){...}` and that compiled and worked.
The fact is that `[this](string s) -> bool {...}` does not work, but `[this](string &s) -> bool {...}` does.
