### ISSUE TITLE
Raspberry Pi3 Rasbian Strech + openFrameworks. v0.10.1

### ISSUE THREAD

**Issue by slagteriet** [openframeworks/openFrameworks#6264]
Hi, 

Ive been trying install openFramework 0.10.0 on a raspberry with latest Raspbian stretch lite.

It get this error ![openFrameworks](https://user-images.githubusercontent.com/23503773/54886255-5af37680-4e86-11e9-9f29-5638b9663490.png)

When I follow this guide. [Getting your Raspberry Pi ready for openFrameworks](https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/)

Im trying to compile a version of this project [PocketVJ.](https://github.com/magdesign/PocketVJ-CP-v3) 

Any guides to make it work ?

**Comment by slagteriet** [comment]
Got version 0.10.1 working by following this guide and then used latest version.
https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/

**Comment by ofTheo** [comment]
Hi!
Try the armv6l release on the downloads page. 
Following this guide: https://openframeworks.cc/setup/raspberrypi/
