### ISSUE TITLE
ofToString() returning hex memory address on OSx 10.13.6?

### ISSUE THREAD

**Issue by danbz** [openframeworks/openFrameworks#6270]
with OSx 10.13.6 and oF 0.10.1 -compiling in xcode 9.4.1 and also via make RunRelease in Terminal calling ofToString() and ofDrawBitmapString( ); returns values in hexadecimal for quoted strings and string variables. font.drawString() returns correct values.
eg;
```
ofDrawBitmapString( "hello", 20  , 20);
    ofDrawBitmapString( hello, 20  , 40);
    myFont.drawString("hello", 20 , 60);
    myFont.drawString(hello, 20 , 80);
    ofDrawBitmapString<string>( "hello", 20  , 100);
```

```
hex
hex
hello 
hello
hex
``` 

testing with ofDrawBitmapString<string>( ); as per @arturoc suggestion also returns hex values.

more details in the oF forum post here; 
https://forum.openframeworks.cc/t/oftostring-returning-hex-memory-address-was-string-being-printed-as-hexadecimal-in-window-but-not-in-console/32015/5

**Comment by 2bbb** [comment]
this is a just report.

i tested with same env -- osx 10.13.6, oF0.10.1, Xcode9.4.1, release build.
but, i got all correct results "hello"...

**Comment by danbz** [comment]
i will go back to check the environment in case there are other factors affecting this

**Comment by danbz** [comment]
can find no affecting alternative factors - still experiencing this issue

**Comment by bfallc** [comment]
I too have just encountered this issue today after successfully using OF for many months. MacOSX 10.13.6, Xcode 10.0. 

Last week I tried installing Emscripten (using git) and never really got it to work. According to their docs (`https://emscripten.org/docs/getting_started/downloads.html#uninstalling-the-emscripten-sdk`), to uninstall you should just delete the directory. After deletion, I still have the problem. 

Not sure what to try next.

**Comment by bfallc** [comment]
Clean install of OF fixed my issue. Never got emscripten to work properly according to the [docs](https://openframeworks.cc/setup/emscripten/)
