### ISSUE TITLE
transformFeedbackExample doesn't work on OSX

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#6274]
Runs fine but blank canvas on OSX 10.13.6.

**Comment by roymacdonald** [comment]
Hi, it will  not work on macos, because of its openGL implementation. It was mentioned somewhere which I cant recall where, but I think it was @arturoc who did.

**Comment by arturoc** [comment]
supposedly this should work in osx cause transform feedback is supported but for some reason it doesn't so if anyone wants to investigate what it's going on that would be really useful

**Comment by roymacdonald** [comment]
here it is, https://blog.openframeworks.cc/post/173258830179/opengl-new-features.
@arturoc There you say it will not work on osx. Has anything changed that you say that now it should run. Something related to mojave? If such, I am not running Mojave (and will not) so I cant test any further.
cheers

**Comment by arturoc** [comment]
yes that was wrong. I assumed that osx just didn't support it but transform feedback is old, supported since 3.0: https://www.khronos.org/opengl/wiki/Transform_Feedback  

Which makes me thing that it might just be that you need to use the programmable renderer to make it work

**Comment by roymacdonald** [comment]
Ha. Thanks for pointing it out.
The example at least is running the programable renderer. On my machine it does not work either, macos 10.12.6

I'll try yo dig about this on the next days.

best

**Comment by eduardfrigola** [comment]
Hi, I found a way to make transform feedback work on macOS.
I've tested it in both macOS 10.13.6, and win10, with latest master.
Without changing any code on the transform feedback example (using default gl 3.3).

While reviewing the full implementation of transform feedback, some tutorials point out that is "preferable" to cut gl pipeline just after vertex or geometry shader (http://ogldev.atspace.co.uk/www/tutorial28/tutorial28.html).

Seeing that in OF's implementation that didn't happen I implemented that and seems to fix it.
Just calling `glEnable(GL_RASTERIZER_DISCARD)` right before `glBeginTransformFeedback`, and then `glDisable(GL_RASTERIZER_DISCARD)` (to return to the previous state) right after `glEndTransformFeedback`.

It seems plausible that when apple did their implementation they required this state to be activated.

If you want to try it: https://github.com/PlaymodesStudio/openFrameworks/tree/bugfix-transform_feedback_macos

What do you think?

**Comment by roymacdonald** [comment]
Is this a preferable thing on any OS or just a macos thing? because if it is working properly on the other OSes I'd rather put these new gl calls inside `#if defined(TARGET_OSX) #endif` block.

**Comment by eduardfrigola** [comment]
I have not seen anything about that only be a macOS thing. That's why i tested it on windows with the same change. In the link I put above they just say (about `glEnable(GL_RASTERIZER_DISCARD`):

> The next function call is something that we haven't seen before. Since the only purpose of the draw call further down this function is to update the transform feedback buffer we prefer to cut the flow of primitives after that and prevent them from also being rasterized to the screen. We have another draw call later on that does that. Calling glEnable() with the GL_RASTERIZER_DISCARD flag tells the pipeline to discard all primitives before they reach the rasterizer (but after the optional transform feedback stage).

Tomorrow I can test with other macOS setups and with linux too. I think I can only help with tests, as my understanding of OpenGL is somehow basic...

**Comment by roymacdonald** [comment]
I see. I just tested it on macos 10.14.6 with Xcode 11.2.1 and it works fine.

**Comment by arturoc** [comment]
i remember reading about this when i implemented it and i thought it we were using it, i think it should be used for every platform, doesn't make sense to have the rasterizer enabled when doing transform feedback.

can you send a PR?

**Comment by ofTheo** [comment]
closed by #6473
