### ISSUE TITLE
ofTimerr::setPeriodicEvent bug on values over 1 second on macOS

### ISSUE THREAD

**Issue by youandhubris** [openframeworks/openFrameworks#6277]
Hi! As reported on the [forum](https://forum.openframeworks.cc/t/oftimer-nanoseconds-values/32190), if you **setPeriodicEvent** to 1 second or lower, everything runs as expected. If you go over that value, it just runs as fast as it can.

This was tested on macOS(High Sierra and Mojave) with OF 0.10.1, and it fails.
With OF version 0.9.8, it's okay.
On both versions of OF in Windows, is okay.
Couldn't test it on Linux.

The example below is based on the [OF documentation](https://openframeworks.cc/documentation/utils/ofTimer/):

~~~
class ofxWebScrapper: public ofThread
{
public:
    ofxWebScrapper()
{
//    uint64_t nanoseconds = 1000000000; // One second, OK
//    uint64_t nanoseconds = 500000000; // Half-second, OK
    uint64_t nanoseconds = 2000000000; // Two seconds, NOT OK
    
    timer.setPeriodicEvent(nanoseconds);
    startThread();
}

    ~ofxWebScrapper()
{
    waitForThread(true);
}
    
private:
    void threadedFunction()
{
    while(isThreadRunning())
    {
        timer.waitNext();
        cout << "Ping..." << "\n";
    }
}
    ofTimer timer;
};
~~~

**Comment by arturoc** [comment]
:) thanks!
