### ISSUE TITLE
examples Compile 

### ISSUE THREAD

**Issue by guohongbin2019** [openframeworks/openFrameworks#6279]
Hello
Why is the examples for each example the same? How to compile step by step?

**Comment by guohongbin2019** [comment]
How to compile step by step?

**Comment by tgfrerer** [comment]
Hi, we use github only to report bugs or ask for new features in openFrameworks. 

If you have problems with a specific oF application, or questions about using openFrameworks, try asking in the [openFrameworks forum](https://forum.openframeworks.cc/).
