### ISSUE TITLE
ofSetFullscreen broken again in Ubuntu 18?

### ISSUE THREAD

**Issue by genekogan** [openframeworks/openFrameworks#6283]
Fresh install of latest nightly (of_v20190324_linux64gcc6_release) in Ubuntu 18.04, methods to make window fullscreen in beginning of sketch fail for me, either using `ofAppBaseWindow::setFullscreen` or `ofSetFullscreen`.  A workaround is to wait 1 second, then call `ofSetFullscreen(true)`, this makes fullscreen work, but not sure what's wrong with the normal way.

**Comment by arturoc** [comment]
I believe ubuntu 18.04 came with wayland by default, we use a method specific to xwindows to change to fullscreen so that might be the reason, try starting the session with xorg instead of wayland (you can choose it in the password screen).

**Comment by arturoc** [comment]
also OF_GAME_MODE instead of OF_FULLSCREEN should work but doesn't allow to go back and forth between window and fullscreen

**Comment by gorkacortazar** [comment]
@arturoc I was researching this subject and is not wayland related. I tried:
- calling in the window settigns: fails in wayland and x11
- call ofSetFullscreen(true) in setup: fails in wayland and x11
- call ofSetFullscreen(true) in first run of the update: fails in wayland and x11 
- call ofSetFullscreen(true) in first run of the draw: works in wayland and x11 

in my case i was doing also multimonitor full screen, see some examples here https://forum.openframeworks.cc/t/ubuntu-18-and-fullscreen-multimonitor/33165

**Comment by ofTheo** [comment]
@gorkacortazar @genekogan -  very late follow up can you try the latest nightly builds and see if you still are having the issue?
( Botton of the page here https://openframeworks.cc/download/ )

**Comment by ofTheo** [comment]
Hi @gorkacortazar  - just tried on a fresh vanilla 20.04 install with the nightly builds ( see link in comment above ). 
This was in X11 not Wayland but I could both toggle fullscreen and start in fullscreen by setting it in main.cpp. 

Going to close for now but feel free to re-open or comment if this is still an issue.
