### ISSUE TITLE
Android arm64 support

### ISSUE THREAD

**Issue by lewisou** [openframeworks/openFrameworks#6299]
The download_libs.sh script only supports android - armv7 or x86. We need arm64 versions.

Google Play will enforce arm64 support from 1st Aug this year.

**Comment by cuinjune** [comment]
I think this should be updated soon for Android users.

If anyone knows a quick fix to make an Android app support `arm64-v8a`, please share it.

**Comment by lewisou** [comment]
The master branch has already supported android arm64. However, the download_libs script has not been updated yet. But you can download the arm64 libs from http://ci.openframeworks.cc/libs/ manually.

**Comment by lewisou** [comment]
https://github.com/openframeworks/apothecary/pull/134

**Comment by cuinjune** [comment]
@lewisou Thank you for your answer. I downloaded the arm64 libs from the link.
However, I don't know how to make `arm64-v8a` show up in Build Variant section.
<img width="466" alt="Screen Shot 2019-06-26 at 1 21 06 PM" src="https://user-images.githubusercontent.com/24947986/60151900-75d4de80-9819-11e9-898d-b12acc67aac5.png">
Do you mind sharing how to fix this?

**Comment by lewisou** [comment]
A fix for this
https://github.com/lewisou/openFrameworks/commit/3da93c9300b48068894308e95169a6dbfcc45776

**Comment by cuinjune** [comment]
@lewisou Thank you but when I do it I get this error after the gradle sync.

> Unable to find Android binary with buildType 'debug' and productFlavor 'arm64' in project ':openFrameworksProject'

I just replaced the `OF/libs` with the downloaded `arm64` libs. I used OF 0.10.1 stable release.
Should I use another OF release?

**Comment by lewisou** [comment]
I am using the master branch. You may check the function below in the common-functions.gradle

def getFlavorName(abi) {
    switch (abi) {
        case "armeabi":
            return "armeabi";
        case "armeabi-v7a":
            return "arm7"
        case "arm64-v8a":
            return "arm64"
        default:
            return abi.replaceAll('-', '_')
    }
}

**Comment by cuinjune** [comment]
@lewisou I have the exact same settings but didn't work. I also tried the master branch but I get the same error.

Without the `return ["arm64-v8a", "armeabi-v7a", "x86"]` fix, gradle builds fine though.

**Comment by lewisou** [comment]
I actually change the function so that only one ABI returns. The returned
value is then adjusted to what I want to build the project against.

such as:

def getAbis(){
    return ["armeabi-v7a"]
    //"x86", "arm64-v8a"
}

**Comment by cuinjune** [comment]
`return ["armeabi-v7a"]` works but `return ["arm64-v8a"]`, I get the following error:

> Unable to find Android binary with buildType 'null' and productFlavor 'null' in project ':openFrameworksProject'

Did you also change anything in `OF/libs/openFrameworksCompiled/project/android/config.android.default.mk` file?

**Comment by lewisou** [comment]
No. that file is not touched at all.

**Comment by lewisou** [comment]
I am using Android Studio 3.1.3 and gradle-3.3.

**Comment by cuinjune** [comment]
I use Android Studio 3.4.1 and gradle-3.3.

So does your project work fine when you do the following in `common-functions.gradle` and build the project?

```
def getAbis(){
    return ["arm64-v8a"]
}
```

**Comment by lewisou** [comment]
Yes. maybe I forget something.

**Comment by cuinjune** [comment]
I would really appreciate if you can share the two files:

```
OF/libs/openFrameworksCompiled/project/android/build.gradle
YourProject/build.gradle
```

**Comment by cerupcat** [comment]
@cuinjune Did you ever solve this? I'm running into the same issue.

**Comment by danoli3** [comment]
@cerupcat it should work, you just have to use the older gradle and not the latest android studio. I'm working on a full update for android currently

**Comment by cerupcat** [comment]
I get the same errors as cuinjune. Using v 0.10.0, I used the update libs script to pull in the latest libs and 64 bit versions.

I then updated getAbis() to include "arm64-v8a". However, building says "Unable to find Android binary with buildType 'debug' and productFlavor 'arm64' in project ':openFrameworksProject"

**Comment by cerupcat** [comment]
Following up here. This post was the fix https://forum.openframeworks.cc/t/how-to-make-arm64-v8a-show-up-in-build-variant-in-android-studio/32847.

I managed to solve it by modifying the 3 build.gradle files.

set target sdk from 25 to 28
targetSdkVersion.apiLevel 28

modify ndk platform version from 19 to 21
ndk { platformVersion = “21”
