### ISSUE TITLE
compileOF.sh fails on linux Mint 

### ISSUE THREAD

**Issue by CarloCattano** [openframeworks/openFrameworks#6300]
I get the following error when trying to compile .

Tried to follow the steps described in other issues but still no luck

makefileCommon/compile.core.mk:238: recipe for target '/home/x/Documents/of/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/lib/linux64/obj/Debug/libs/openFrameworks/utils/ofLog.o' failed
make[1]: *** [/home/x/Documents/of/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/lib/linux64/obj/Debug/libs/openFrameworks/utils/ofLog.o] Error 1
makefileCommon/compile.core.mk:212: recipe for target 'Debug' failed
make: *** [Debug] Error 2
there has been a problem compiling Debug OF library
please report this problem in the forums

[crash.log](https://github.com/openframeworks/openFrameworks/files/3225053/crash.log)

**Comment by arturoc** [comment]
It would help if you posted some more of the output, the bit you posted doesn't contain the real error

**Comment by CarloCattano** [comment]
Oh. Have you seen the attached crash.log? @arturoc

**Comment by arturoc** [comment]
oh i see sorry. that's really strange though there seems to be no compiler error or anything, not sure what's going on. try perhaps compiling one of the examples without running compileOF although i imagine you'll get the same error

**Comment by CarloCattano** [comment]
[Graphics_example.log](https://github.com/openframeworks/openFrameworks/files/3238865/Graphics_example.log)

it seems very similar to the error I get compiling ./compileOF.sh -j3

**Comment by ninivert** [comment]
I've got the same problem here, with version 0.10.1, using gcc6 on linux 64 bits ubuntu.
When running the script `compileOF.sh`, I get the error following error
[log.txt](https://github.com/openframeworks/openFrameworks/files/3240677/log.txt)

Running with sudo or -j3 not does not change anything.

Thank you for your help !

**Comment by arturoc** [comment]
@ninivert your error is not the same and it's already solved in the nightly builds, can you try using that? @CarloCattano yours is really strange cause there's no ourput that says what the error is related to but can you also try the nigtly builds just in case?

**Comment by ninivert** [comment]
@arturoc the nightly build `v20190324_linux64gcc6` has indeed fixed the problem. All the examples have compiled successfully and the few ones I've tested seem to work

Thank you !
