### ISSUE TITLE
how to build an available libassimp.a on linux with armeabi-v7a

### ISSUE THREAD

**Issue by wssbygone** [openframeworks/openFrameworks#6301]
hi, I've succeeded to build the libassimp.a on linux through this cmd : 
**_cmake CMakeLists.txt -DANDROID_FORCE_ARM_BUILD=ON -DANDROID_ABI="armeabi-v7a" -DANDROID_NATIVE_API_LEVEL="android-22"
-DCMAKE_C_COMPILER=/tmp/ndk-root/bin/arm-linux-androideabi-gcc-4.9
-DANDROID_TOOLCHAIN_NAME="/home/wss/android_toolchain/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9"_**, 
but the libassimp.a is not available when compile the OF example androidAssimpExample, 
could  anyone tell me how to compile the ibassimp.a（armeabi-v7a）on linux，thanks a lot

**Comment by arturoc** [comment]
Hi, this is only for reporting issues or asking for new features, if you have a question please ask in the openFrameworks forum: https://forum.openframeworks.cc
