### ISSUE TITLE
Issue compiling on arch linux OF_0.10.1.

### ISSUE THREAD

**Issue by rdtor** [openframeworks/openFrameworks#6305]
GCC 8.3
All dependencies and codecs are installed
Nightly build compiles without error.
Running the make command on openFrameworksCompiled/Projects or using the isntall script i get this error

/usr/include/GL/glew.h:22687:52: note: previous declaration ‘void (* __glewGetFragmentMaterialfvSGIX)(GLenum, GLenum, const GLfloat*)’
 GLEW_FUN_EXPORT PFNGLGETFRAGMENTMATERIALFVSGIXPROC __glewGetFragmentMaterialfvSGIX;
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:212,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.h:6,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.cpp:1:
/usr/include/GL/glext.h:12099:90: error: ‘void __glewGetFragmentMaterialivSGIX(GLenum, GLenum, GLint*)’ redeclared as different kind of symbol
  APIENTRY glGetFragmentMaterialivSGIX (GLenum face, GLenum pname, GLint *params);
                                                                                ^
In file included from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:210,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.h:6,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.cpp:1:
/usr/include/GL/glew.h:22687:52: note: previous declaration 'void (* __glewGetFragmentMaterialfvSGIX)(GLenum, GLenum, const GLfloat*)'
 GLEW_FUN_EXPORT PFNGLGETFRAGMENTMATERIALFVSGIXPROC __glewGetFragmentMaterialfvSGIX;
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:212,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.h:6,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.cpp:1:
/usr/include/GL/glext.h:12099:90: error: 'void __glewGetFragmentMaterialivSGIX(GLenum, GLenum, GLint*)' redeclared as different kind of symbol
  APIENTRY glGetFragmentMaterialivSGIX (GLenum face, GLenum pname, GLint *params);
                                                                                ^

In file included from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:210,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.h:6,
                 from /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/math/ofVec2f.cpp:1:
/usr/include/GL/glew.h:22688:52: note: previous declaration 'void (* __glewGetFragmentMaterialivSGIX)(GLenum, GLenum, const GLint*)'
 GLEW_FUN_EXPORT PFNGLGETFRAGMENTMATERIALIVSGIXPROC __glewGetFragmentMaterialivSGIX;
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [makefileCommon/compile.core.mk:240: /home/shank/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/lib/linux64/obj/Debug/libs/openFrameworks/math/ofVec2f.o] Error 1
make: *** [makefileCommon/compile.core.mk:212: Debug] Error 2
there has been a problem compiling Debug OF library
please report this problem in the forums

**Comment by arturoc** [comment]
sorry i asked you to open an issue if this didn't work with the nightlies, it's already solved there adn will be in the next release that we are going to do soon.
