### ISSUE TITLE
Cannot use ofAppNoWindow on iOS

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#6308]
I would like to create a window in the `ofApp::setup()` so I used `ofAppNoWindow` and this works fine on macOS but not on iOS. I cannot even build the project on iOS.

Here's my `main.mm`

```
#include "ofMain.h"
#include "ofApp.h"
#include "ofAppNoWindow.h"

//========================================================================
int main()
{
    ofAppNoWindow window;
    ofSetupOpenGL(&window, 1024, 768, OF_WINDOW);
    return ofRunApp(new ofApp);
}
```

And here's a screenshot of error messages:
<img width="858" alt="xAM3T" src="https://user-images.githubusercontent.com/24947986/59399798-4b723280-8dd0-11e9-8831-8c08c4f1dee1.png">

Shouldn't `ofAppNoWindow` supposed to work regardless of platform?
I would appreciate if any advice to fix this issue.

**Comment by ofZach** [comment]
I'm not sure what you are trying to do here but iOS apps can't be headless (ie, run without a window)

**Comment by cuinjune** [comment]
I think it is no longer important.
