### ISSUE TITLE
windows openframeworks build problem

### ISSUE THREAD

**Issue by ShuaiMXu** [openframeworks/openFrameworks#6311]
I'm a Mac user, First time try to use win openframework, 
I Follow visual studio setup guide install openframework and vs, and run emptyExample have this problem, please help me solve this problem.

openframeworks version: of_v0.10.1_vs2017_release
and visual Studio community 2017 (15.9.13)

![주석 2019-06-14 224022](https://user-images.githubusercontent.com/49175785/59539507-7013fa80-8ef5-11e9-9833-cf0e5df31ad7.png)

Many thanks 

Shuai

**Comment by ShuaiMXu** [comment]
openframeworks version:  of_v0.10.1_vs2017_release
and  visual Studio community 2017 (15.9.13)

**Comment by ShuaiMXu** [comment]
Also when I run any examples still have same problems.
![주석 2019-06-14 225206](https://user-images.githubusercontent.com/49175785/59540903-17ddf800-8ef7-11e9-9a18-94f460a1f7c2.png)

**Comment by arturoc** [comment]
Please use the forum to asks questions: https://forum.openframeworks.cc 

We only use github to report bugs or ask for new features
