### ISSUE TITLE
iOS landscape orientation is drawn upside down

### ISSUE THREAD

**Issue by liamlacey** [openframeworks/openFrameworks#6317]
When setting the iOS orientation mode to landscape (90_LEFT or 90_RIGHT) the window is drawn upside down (meaning touch position 0,0 is at the bottom right instead of the top left).

I’ve tested this with iosOrientationExample with iOS release version 0.10.1, using an iPhone 8 running the latest iOS version.

**Comment by liamlacey** [comment]
I've added a workaround for this by adding the following to my touch functions in order to get the correct touch x and y values:

```
    if (ofGetOrientation() == OF_ORIENTATION_90_LEFT || ofGetOrientation() == OF_ORIENTATION_90_RIGHT)
    {
        touch.x = ofGetWidth() - touch.x;
        touch.y = ofGetHeight() - touch.y;
    }
```

However a second issue I've now found is that if I do a double tap it will call `touchDoubleTap` as expected but then also trigger a `touchDown` with the correct touch x and y values, which then means by above workaround won't work.

**Comment by ofTheo** [comment]
Thanks @liamlacey !
Do the graphics also seem flipped or is it just the touch points?

**Comment by liamlacey** [comment]
Hi ofTheo, 
I seem to remember that the issue is that the whole window/view/graphics is being drawn upside down, but with the touch points being as they should be.

**Comment by liamlacey** [comment]
Resulting in the touch points being flipped compared to the view.

**Comment by ofTheo** [comment]
Thanks @liamlacey - I'll take a look! 
Sounds like it should be easy to reproduce :)

**Comment by ofTheo** [comment]
@liamlacey I was able to reproduce on my end for both device and simulator. 

Could you confirm that switching the `(CGPoint)orientateTouchPoint:(CGPoint)touchPoint {` in 

ofxiOS/src/core/ofxiOSEAGLView.mm 

to: 

```
        case OF_ORIENTATION_90_RIGHT:
            touchPointOriented.x = touchPoint.y;
            touchPointOriented.y = ofGetHeight() - touchPoint.x;
            break;
            
        case OF_ORIENTATION_90_LEFT:
            touchPointOriented.x = ofGetWidth() - touchPoint.y;
            touchPointOriented.y = touchPoint.x;
            break;
```

Fixes the issue for you?
It seems to work correctly now for me now.
