### ISSUE TITLE
Examples updated to use GLM

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6326]
Hi!
I've updated all the examples so these use glm instead of ofVec, ofMatrix and ofQuaternion.
These are [here.](https://github.com/roymacdonald/openFrameworks/tree/examplesToGlm)

So far I have updated all the standard ones and tested that all compile, run and behave in a similar way as before. 
There is a commit with updates to android. These were quite trivial stuff which should be ok but some more testing is needed.
Should I make this PR?

**Comment by sourya-sen** [comment]
This has been closed by #6389 right?

**Comment by roymacdonald** [comment]
@sourya-sen yes. Thanks for reminding.
