### ISSUE TITLE
ofQuaternion::makeRotate(ofVec3f v1,ofVec3f v2) replacement for GLM

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6327]
Hi, 
it happens that glm does not have a function that returns a quaternion that represents the angle between two vectors. It happens that ofQuaternion has a super handy function, `ofQuaternion::makeRotate(ofVec3f v1,ofVec3f v2) ` that will do such.
Considering the move into GLM I think it would be super handy to have such function as an OF function, maybe something like `glm::quat ofGetRotationBetweenVectors(glm::vec3 v1, glm::vec3 v2);`

The implementation for such is [here](http://www.opengl-tutorial.org/es/intermediate-tutorials/tutorial-17-quaternions/#how-do-i-find-the-rotation-between-2-vectors-) 

so it would look 
```
glm::quat ofGetRotationBetweenVectors(glm::vec3 start, glm::vec3 dest){
	start = glm::normalize(start);
	dest = glm::normalize(dest);
	
	float cosTheta = glm::dot(start, dest);
	glm::vec3 rotationAxis;

	if (cosTheta < -1 + 0.001f){
		// special case when vectors in opposite directions:
		// there is no "ideal" rotation axis
		// So guess one; any will do as long as it's perpendicular to start
		rotationAxis = cross(glm::vec3(0.0f, 0.0f, 1.0f), start);
		if (glm::length2(rotationAxis) < 0.01 ) // bad luck, they were parallel, try again!
			rotationAxis = glm::cross(glm::vec3(1.0f, 0.0f, 0.0f), start);
		
		rotationAxis = normalize(rotationAxis);
		return glm::angleAxis(ofDegToRad(180.0f), rotationAxis);
	}
	
	rotationAxis = glm::cross(start, dest);
	
	float s = sqrt( (1+cosTheta)*2 );
	float invs = 1 / s;
	
	return glm::quat(s * 0.5f,
				rotationAxis.x * invs,
				rotationAxis.y * invs,
				rotationAxis.z * invs);
}
```

What do you think @arturoc @bakercp @ofZach @elliotwoods  ?

**Comment by roymacdonald** [comment]
@arturoc @bakercp @tgfrerer Here is what we were discussing/trying to figure out yesterday.
I think it is a super useful function, will allow to have all the examples ported to glm (there is one that needs this) and I think it is harmless. Even when the idea is to slim down the core code, these kind of handy functions tend to be really useful, specially if we had it before and now glm does not.

**Comment by ofTheo** [comment]
We use the ofQuat equivalent function all the time in our projects. It's one of the most useful functions in terms of quaternions. Only thought is if it should be named like this or if it would fit better into a set of glm specific helper tools?  

Curious what others think. 

I would love to have some form of this though.

**Comment by roymacdonald** [comment]
I also find it super useful. 
What other naming do you suggest?

**Comment by arturoc** [comment]
i'd try to send a PR to glm itself as glm::rotation_between or at least open an issue asking if the feature is something they would merge if not then ofGetRotationBetween should be fine, the parameters already make it clear it's between vectors, no need to have it in the name

**Comment by ofTheo** [comment]
I was wondering why this is not included in glm - looks like it is in the experimental API: 
https://glm.g-truc.net/0.9.5/api/a00222.html 

```

template<typename T , precision P>
detail::tquat< T, P > | rotation (detail::tvec3< T, P > const &orig, detail::tvec3< T, P > const &dest)

``` 

so... could we expose that?

**Comment by bakercp** [comment]
It's already exposed on macOS.

```c++
    glm::vec3 theOrigin = { 1, 0, 0 };
    glm::vec3 theDestination = { 0, 1, 0 };
    glm::quat theRotation = glm::rotation(theOrigin, theDestination);
```

Reference implementation here

https://github.com/g-truc/glm/blob/0ceb2b755fb155d593854aefe3e45d416ce153a4/glm/gtx/quaternion.inl#L121-L158

**Comment by bakercp** [comment]
We already include it here to be specific:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/math/ofVectorMath.h#L26

**Comment by ofTheo** [comment]
oh wow - so its basically already there.  🙃
maybe then it would be more about updating examples and documentation then, so people know how to move from makeRotate to the glm equivalent.

**Comment by arturoc** [comment]
closing this then. @roymacdonald if you can update the missing example to use this?

**Comment by roymacdonald** [comment]
Ohh no! lol. My fault. I don't remember finding that function. 
The funny part is that it is exactly the same function I was referring to, you can tell by the comments.
I'll update the example right now.
