### ISSUE TITLE
MSYS2 executables have no icon

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#6328]
Seen in OF 0.10.1 (and before).
The OF executable is displayed in file explorer with the ugly default application icon. 
Would be proud to disaplay the OF icon (or a custom one).

**Comment by sphaero** [comment]
Inded, it needs some extra steps in the makefile. I was working on it but haven't found the time yet to pick it up again: https://forum.openframeworks.cc/t/app-icon-using-make-on-msys2/31342
