### ISSUE TITLE
help me start programing

### ISSUE THREAD

**Issue by Aplaus228** [openframeworks/openFrameworks#6329]
Hello, I am bigginer c++ developer and I will want help this project.
but I dont know how I can do it.If you have idei for new feature but no time for realise it I will do it.
And if you can be mentor for me its will be ideal.
Thank you all.

**Comment by roymacdonald** [comment]
Hi, please go to the [openFramworks forum](https://forum.openframeworks.cc/), there you'll find a lot of help. Also, a really good starting point is to read the [OFBook](https://openframeworks.cc/ofBook/chapters/foreword.html). 
Cheers
