### ISSUE TITLE
Many -wclass-memaccess warnings due to glm

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#6332]
Compilation of current master (july 2019) throws many warnings as below
```
N:/openFrameworks/libs/glm/include/glm/gtc/packing.inl: In function 'glm::vec4 glm::unpackUnorm4x16(glm::uint64)':
N:/openFrameworks/libs/glm/include/glm/gtc/packing.inl:437:37: warning: 'void* memcpy(void*, const void*, size_t)' copying an object of non-trivial type 'glm::u16vec4' {aka 'struct glm::tvec4<short unsigned int, glm::packed_highp>'} from an array of 'glm::uint64' {aka 'long long unsigned int'} [-Wclass-memaccess]
  437 |   memcpy(&Unpack, &p, sizeof(Unpack));
```

**Comment by oxillo** [comment]
Tried on MSYS2 using glm from pkgconfig (0.9.9.5). All warnings are gone.
Shouldn't OF switch to the GLM 0.9.9 branch instead of the 0.9.8.5 version.

**Comment by arturoc** [comment]
yes i'm trying it here but there's still some platforms where it doesn't work: https://github.com/openframeworks/apothecary/pull/136

**Comment by oxillo** [comment]
closed by #6409

**Comment by npisanti** [comment]
after `git pull`-ing to the latest version, and using `download_libs.sh` this is again an issue on Debian 10. I tried also downgrading glm to 0.9.9.5 as in the previous @oxillo comment and trying with a fresh copy of the stable 0.11.0, the results are the same.

**Comment by npisanti** [comment]
i've found it's fault of 
```
#define GLM_FORCE_CTOR_INIT
```
removing it from `ofConstants.h` stops the warnings, but obviously could break all the other places where glm vector needed initialization

**Comment by npisanti** [comment]
this is still an issue in the latest commits, ping @arturoc @ofTheo @ofZach

**Comment by br101** [comment]
Same here on Ubuntu 20.04
