### ISSUE TITLE
MSYS2ROOT path issue

### ISSUE THREAD

**Issue by darkworks** [openframeworks/openFrameworks#6333]
hi i have followed almost all instructions on that Qt page : https://openframeworks.cc/setup/qtcreator/
i installe 32 bit version of msys2  to  c:\msys64

i have build openframework  as guided on that page 
i have Qt creator 4.9.2 installed it location 
`C:\Qt\Tools\QtCreator\`
i copied openframeworks template to : C:\Qt\Tools\QtCreator\share\qtcreator\templates and overwrite wizards folder , 

now when i created openframework project in my Qt creator i get error 

```
> warning: error : your PATH is incorrect. Please make sure that {MSYS2ROOT}\mingw32\bin;{MSYS2ROOT}\usr\bin is at the beginning of your PATH
warning: Product 'app2' had errors and was disabled.
warning: Error while handling product 'openFrameworks':
 warning: Product 'openFrameworks' had errors and was disabled.
```

but my path variables are already set i used rapid env editor : https://www.rapidee.com/en/about

![image](https://user-images.githubusercontent.com/12841788/60864211-5e93e900-a23c-11e9-955e-5c43c289367b.png)

+ i have extract openframeworks into : C:\openframeworks

**Comment by oxillo** [comment]
There is a bug in the install_dependencies.sh script (#5740).
Please try to edit your PATH to replace {MSYS2ROOT} to %MSYS2ROOT%.

**Comment by darkworks** [comment]
> %MSYS2ROOT%

ok thank i did but still same error can u check screenshot please ,thanks 

![image](https://user-images.githubusercontent.com/12841788/60864954-6a80aa80-a23e-11e9-9550-fa5d36928e68.png)

**Comment by darkworks** [comment]
removed braces but still same error 

![image](https://user-images.githubusercontent.com/12841788/60865112-c3e8d980-a23e-11e9-9779-2e6fb00cd7bb.png)

**Comment by oxillo** [comment]
Did you reboot your computer ? Windows generally only applies PATH changes when starting.
Also, I see that you are using QtCreator 4.9.2. The doc recommends 4.6.1. 
I think this discussion shall rather go on the [forum](https://forum.openframeworks.cc/)

**Comment by darkworks** [comment]
> Did you reboot your computer ? Windows generally only applies PATH changes when starting.
> Also, I see that you are using QtCreator 4.9.2. The doc recommends 4.6.1.
> I think this discussion shall rather go on the [forum](https://forum.openframeworks.cc/)

yes i restarted computer now but same error . ya am using 4.9.2  but i thought document said 4.6.1 and later .

**Comment by oxillo** [comment]
see discussion on the forum [here](https://forum.openframeworks.cc/t/qtcreator-msys2root-detection-failure/32936)
MSYS2ROOT is incorrectly detected due to other installation of /usr/bin/find
