### ISSUE TITLE
nlohmann /ofJson automatic serialization 

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#6337]
`nlohmann::json` aka `ofJson` has pretty great "auto" serialization support.  I've been building it out for openFrameworks core classes (which makes it possible for me to support my own classes more easily).

Here is an example of how it works:

https://github.com/bakercp/ofxSerializer/blob/develop/tests/serializer/src/main.cpp

Here is the class where I've been collecting all of the classes:

https://github.com/bakercp/ofxSerializer/blob/develop/src/ofSerializer.h

Is there interest in integrating something like this into the core or would it work better as an addon?  Basically, this would get us robust JSON, BSON, CBOR, MessagePack, and UBJSON serialization support.

**Comment by arturoc** [comment]
my opinion right now is that we should tend to have more features in addons, even move things that are currently core to addons.  we should also work towards having very good tooling so adding  and downloading addons is as easy as possible.

in any case the main problem i see with this is that it needs manual implementation for any class we would like to support so i'm not sure it's the best way to go. i know there's solutions that allow to automate serialization implementation a bit more but as far as i know make compilation times much larger so not sure what's the best solution for this. that also is a good reason to try it first as an addon. if people start to use it then perhaps it could be included as an official addon or even core
