### ISSUE TITLE
ofSaveJson/ofFile ignores case on Windows

### ISSUE THREAD

**Issue by gwio** [openframeworks/openFrameworks#6350]
While using ofSaveJson I've run into some issues with ofFile. The filename case seems to be ignored. Maybe I'm missing something fundamental here.

```
ofFile save1("test.txt");
save1.create();
ofFile save2("TEST.txt");
save2.create();
```

This creates only the first lowercase file, and the second call just writes into the first file. Only one file is created.

Win10 64x, OF10.1_vs2017

**Comment by arturoc** [comment]
isn't windows filesystem case insensitive?

**Comment by gwio** [comment]
Yeah, you're totally right, did not think of this. 
It's possible to allow this per folder via
`fsutil.exe file setCaseSensitiveInfo C:\folder enable`
