### ISSUE TITLE
[BUG?] is the ofRotateDeg & ofRotateRad wrong?

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/openFrameworks#6351]
so I'm just doing some playing around, making tutorials etc. but coming across this for rotating objects does not make sense.
the x rotate deg & rad rotates vertically & the y rotate deg & rad rotates horizontally. this just does not makes a lot of sense. so im wondering if its something that has been overlooked.

```
ofApp.h

float rotate;
```

```
ofApp.cpp

void ofApp::update(){
  rotate++;
}

//--------------------------------------------------------------
void ofApp::draw(){
  
  ofTranslate(ofGetWidth() / 2, ofGetHeight() / 2);
//  ofRotateDeg(rotate);
  ofRotateXDeg(rotate);
//  ofRotateYDeg(rotate);
//  ofRotateZDeg(rotate);
  
//  ofRotateRad(ofDegToRad(rotate));
//  ofRotateXRad(ofDegToRad(rotate));
//  ofRotateYRad(ofDegToRad(rotate));
//  ofRotateZRad(ofDegToRad(rotate));
//  ofDrawRectangle(0, 0, 128, 128);
  ofDrawBox(60);
}
```

**Comment by lewislepton** [comment]
here are some GIF to show

x rotation
![X rotate](https://user-images.githubusercontent.com/11299322/62127066-1317ac80-b2c9-11e9-841e-2309838b385b.gif)

y rotation
![Y rotate](https://user-images.githubusercontent.com/11299322/62127082-1dd24180-b2c9-11e9-8687-ec852f4f0883.gif)

**Comment by lewislepton** [comment]
in some ways this does make sense, but only a tiny bit. but when bringing in 2d shapes. it doesn't at all.

**Comment by tgfrerer** [comment]
The rotations are named after the axes around which the rotation is performed.

rotateX rotates around the x axis (which points to the right if camera points straight onto negative z, in a right handed coordinate system)
rotateY rotates around the y axis (which points to top)

The gifs suggest rotations are performed as expected. 

You can use ofDrawAxes() to draw the axes which might help debut or clarify the issue...

**Comment by arturoc** [comment]
going to close this since the behaviour is correct

**Comment by lewislepton** [comment]
cool spot. that does clear up what I was thinking. thanks ;)

**Comment by bakercp** [comment]
We just went over this in class today.  Here's a slide :) ![8867F6B4-54D0-47E2-AF35-2464F809F9F6-1-2048x1536-oriented](https://user-images.githubusercontent.com/300484/62136289-6a0d8980-b2a9-11e9-978e-a331bb3a4ee2.png)

**Comment by lewislepton** [comment]
I it made sense when I worked it in my head & how axis worked. but was just something that popped up in myf head to ask. because for some reason, something felt off ;)
