### ISSUE TITLE
of_v0.10.1_linux64gcc6_release compilation fails in Ubuntu 18.04

### ISSUE THREAD

**Issue by bsounak** [openframeworks/openFrameworks#6352]
I was following the linux installation guide
https://openframeworks.cc/setup/linux-install/

The dependencies were installed successfully but the compilation failed

Here's the terminal output
https://pastebin.com/raw/36MRyGhU

**Comment by arturoc** [comment]
hey, this is solved already if you use the nightly builds instead of the normal downloads
