### ISSUE TITLE
Window content stretched when resizing

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6354]
I've noticed window content is stretched when resizing windows with cursor in the latest master. Content is correct again after mouse is released.

macOS 10.14.6
XCode 10.13
OFW git head 
![Screen Shot 2019-08-13 at 12 34 23 PM](https://user-images.githubusercontent.com/58289/62955425-69a3e100-bdc7-11e9-8b13-24dc1dc5de01.png)

**Comment by kkshmz** [comment]
Is this using the default windowing system?

**Comment by dimitre** [comment]
yes
