### ISSUE TITLE
EXC_BAD_ACCESS on pollEvents

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6356]
Hi,
I'm using OF latest github commit and xcode, both 8 and 9.
I've seen, and probably some of you, a quite random bug where it says that an EXC_BAD_ACCESS happened in [this line](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofMainLoop.cpp#L154), which is [this](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofMainLoop.h#L57)` function<void>` instance. This function is setup by  [ofMainLoop::addWindow()](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofMainLoop.h#L18-L32) which points to a static function that belongs to the window being added.

For some reason this bug has been appearing a lot on a project in which I use several threads through Intel Threaded Building Blocks as well as  ofSoundStream's thread. At the same time I am using a lot of audio files (~400) being played back simultaneously. Under this conditions is when it appears the most, but it still happens a lot when disabling TBB or reducing the number of audio files loaded. 

This happens regardless of performing full project cleanup and OF lib rebuilding, trying it on different computers and different XCode versions.

When I tried using Xcode's NSZombies, Malloc Guard, Thread Sanitizer or/and Memory Sanitizer, the bug does not happen any more :/ (Murphy's law, so I am not really sure what is triggering it)

So, the only thing that I am certain of is that memory is getting corrupted by some reason.
I think that it has to do with how this function is being "stored".

~~I made some changes which you can see [here](https://github.com/openframeworks/openFrameworks/compare/master...roymacdonald:fix_pollEvents?expand=1) where essentially I added the virtual abstract function` ofAppBaseWindow::pollEvents`, which is then implemented on each inheriting class. Then, instead of calling the function pointer being stored by ofMainLoop it calls the pollEvents function of the first registered window of the ofMainLoop. I'am not sure if this is a correct thing to do but so far I am getting this EXC_BAD_ACCESS no more.~~
I was wrong, it still happens with the changes I made. 
Look at the following screen shots. Notice that ofMainLoop becomes NULL when passing from one function into the next.
![Screen Shot 2019-08-18 at 21 51 58](https://user-images.githubusercontent.com/974878/63234259-88a8d580-c202-11e9-869e-d14f8b7ca6d1.png)
![Screen Shot 2019-08-18 at 21 52 13](https://user-images.githubusercontent.com/974878/63234269-8d6d8980-c202-11e9-8498-f936b23d89b3.png)

Any idea on what might be going on or what would be the proper fix?
@arturoc @bakercp @ofTheo 

best

**Comment by ofTheo** [comment]
Oh man - I was going to ask if there is a simple case you can make to trigger the bug - but it sounds like its a pretty complex / specific setup. 

My first thought is that sometimes its not the main thread that has crashed but one of the other many threads and it is just showing you were the main thread is when the other thread has crashed.  

Not sure if that makes sense? - but I would take a look at all the other threads in the sidebar and see if any look like they have crashed. 

It could also be that an exit() was triggered from another thread and that invalidated the main thread?  

All a bit of a long shot really but might be worth looking at. 

It might be worth seeing if using the 0.10.1 release results in the same crash - that way we could at least narrow it down a bit?

**Comment by roymacdonald** [comment]
Hi @ofTheo  thanks for replying.
I actually don't know how to exactly trigger this bug. It is super random. What I do know is that ofMainLoop becomes NULL, although it is a static. 
I understand what you mean with the threads on the sidebar. That's a good tip. :) I'll take a look at it as well as your other suggestions. 
cheers

**Comment by roymacdonald** [comment]
I am closing this as the problem seems to be related to something else, and I've not seen this happening again.
