### ISSUE TITLE
removeVertex() method is missing in the ofPolyline class

### ISSUE THREAD

**Issue by dom1817** [openframeworks/openFrameworks#6375]
It seems strange that _ofPolyline_ has an _addVertex()_ method, but not a _removeVertex()_. This method [has been already defined](https://github.com/openframeworks/openFrameworks/blob/b34f9a936badb4b9667daaa90d16e719fab8eb03/libs/openFrameworks/3d/ofMesh.inl#L351) in _ofMesh_ and does exactly what one would expect:

`vertices.erase(vertices.begin() + index);`

This could be especially useful for beginners who want to remove a vertex without dealing directly with iterators and vectors.

**Comment by bakercp** [comment]
This seems like a reasonable addition to me.

**Comment by ofZach** [comment]
+1 I use:
`line.getVertices().remove(line.getVertices().begin())`
quite often and wish for simpler access.

**Comment by arturoc** [comment]
feel free to send a PR, be aware that ofPolyline uses several caches that will need to be cleared whenever a vertex is removed

**Comment by bakercp** [comment]
@dom1817 Are you interested / able to make a PR for this feature? I'm happy to help review.

**Comment by dom1817** [comment]
@bakercp I'd be happy to help but my C++ programming skills are too basic for this
