### ISSUE TITLE
oF 0.10.1 nightly build projectGenerator error 

### ISSUE THREAD

**Issue by rossanag** [openframeworks/openFrameworks#6382]
Hello, I installed the nightly build, as ussual, I install dependencies, codecs,,I execute these scrpits.  compileOF, compileOG. 
However when I try to run the projectGenerator It fails, the same error windows appears twice, after I click on "Accept" it appears again, if I hit on "Accept" again, it closes. Thanks in advance.
Ubuntu 19:04 64 bits

![of1](https://user-images.githubusercontent.com/1948071/66545115-62235e80-eb10-11e9-9b75-351a07ce8aff.png)

**Comment by arturoc** [comment]
@hiroMTB I believe this might be related to your latest changes, can you take a look?. I think this is happening in windows as well.

**Comment by hiroMTB** [comment]
Yes, I'm familiar with this waring but can't remember the reason now. I will check asap.

**Comment by bakercp** [comment]
I had to `npm install && npm update` to get past these warnings.

---
https://new.christopherbaker.net

**Comment by bakercp** [comment]
I had to 

```npm install && npm update```

 to get past these warnings.

**Comment by rossanag** [comment]
@bakercp  I tryed that, but it didn't work for me. Did you install it under an specific directory? Thanks for the suggestion though.

**Comment by ofTheo** [comment]
Lets move the discussion to #218 
Thanks!!
