### ISSUE TITLE
Xcode 11 OSX Catalina 10.15 Build Fails "exit code 1"

### ISSUE THREAD

**Issue by kod3000** [openframeworks/openFrameworks#6383]
Build fails error on osx Catalina :

Mac Os Catalina 10.15
Xcode 11.0
oFx 0.10.1

> CodeSign bin/mySketchDebug.app
>     cd /Users/username/Desktop/of_v0.10.1_osx_release/apps/myApps/mySketch
>     export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
>     
> Signing Identity:     "-"
> 
>/usr/bin/codesign --force --sign - --entitlements /Users/username/Library/Developer/Xcode/DerivedData/mySketch-gliogieuiswcwxbciqjfollqduhh/Build/Intermediates.noindex/mySketch.build/Debug/mySketch.build/mySketchDebug.app.xcent --timestamp=none /Users/username/Desktop/of_v0.10.1_osx_release/apps/myApps/mySketch/bin/mySketchDebug.app
> 
> /Users/username/Desktop/of_v0.10.1_osx_release/apps/myApps/mySketch/bin/mySketchDebug.app: resource fork, Finder information, or similar detritus not allowed
> Command /usr/bin/codesign failed with exit code 1

>

**Comment by kod3000** [comment]
This error goes away when you go into  Building Settings >> Signing >> Other Code Signing Flags  and set it to "--deep"

![Screen Shot 2019-10-10 at 12 04 09 PM](https://user-images.githubusercontent.com/227072/66586136-24492900-eb56-11e9-9a7a-61b589426e1c.png)

**Comment by ofTheo** [comment]
Actually re-opening this. 

Even though we have a signed fmodex.dylib now which stops the error most users were having any other project with unsigned dylibs will get code signing errors ( even on 10.14 ).  Adding --deep as above will fix signing for all scenarios. 

Will submit a PR with a fix

**Comment by ZhijunSong** [comment]
I just updated to OSX 10.1. Thank you, it solves the problem.
