### ISSUE TITLE
Travis CI fails with RPi addons

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#6393]
Travis CI config is not recognizing the RPi flags (this is for https://github.com/jvcleave/ofxOMXPlayer)

```
g++: error: unrecognized command line option ‘-mfpu=vfp’

g++: error: unrecognized command line option ‘-mfloat-abi=hard’

make[1]: *** [obj/linuxarmv6l/Debug/src/main.o] Error 1

make[1]: Leaving directory `/home/travis/openFrameworks/addons/ofxOMXPlayer/example-basic'

```

entire log
https://api.travis-ci.org/v3/job/596267808/log.txt

**Comment by ofTheo** [comment]
@jvcleave going to close this as we are now using Github Actions. 
If this is still an issue on GH Actions can you rename the issue and reopen? Thanks!!
