### ISSUE TITLE
projectGenerator prompts for root directory on every launch (OSX Catalina)

### ISSUE THREAD

**Issue by iainnash** [openframeworks/openFrameworks#6395]
Every time I launch `projectGenerator` included in the nightly versions `of_v20191007_osx_release` it asks for the root directory of openFrameworks prompt (which usually is at some tmp folder) as opposed to remember the last path the program opened with.

It seems from the docs/ui that the GUI should remember the last path or keep those permissions from the OS but not sure if that code is broken or that is not possible with the latest version of OSX.

**Comment by bakercp** [comment]
This is related to the way Sierra+ macOS runs downloaded apps that haven't been distributed with a signed disk-image.

A quick fix is to drag the Project Generator app somewhere else (like the Desktop), run it, close it and move it back to the original location.  It should be able to remember its settings after that.  

![out](https://user-images.githubusercontent.com/300484/66803070-cf9e0900-eedb-11e9-802d-ced6bb93ca51.gif)

The longer term plan is to distribute the macOS builds as signed disk images.

References 

https://github.com/openframeworks/projectGenerator/issues/138
https://github.com/openframeworks/openFrameworks/issues/5975

**Comment by iainnash** [comment]
@bakercp Thanks a ton! Makes sense that the signed image would fix this issue. I'll close this ticket for now.
