### ISSUE TITLE
glm 0.9.9.5 merge errors

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6397]
Since we merged in glm 0.9.9.5 looks like there are a few different glm related errors. 
- I think this linux64 one might be related to this not being defined: GLM_HAS_TEMPLATE_ALIASES, https://travis-ci.org/openframeworks/openFrameworks/jobs/599075106 
- MacOS and Windows VS/MSYS seems to be an issue with the orientation failing in the tests `tests\math\ofnoderegressiontests\src\main.cpp: 136` and `tests\math\ofnoderegressiontests\src\main.cpp: 142` 

```
[  error ] value1: 0, 0, 0, 1
[  error ] value2: 0, 0, 0, 0
[  error ] 	orientation failed 
```

From what I have read: "(0,0,0,0) is not a valid rotation quaternion, as they are required to have length 1." 

The 0,0,0,0 value is from glm::quat() - see: https://github.com/openframeworks/openFrameworks/blob/master/tests/math/ofNodeRegressionTests/src/main.cpp#L136 
	
`ofxTest(aprox_eq(n3.getOrientationQuat(), glm::quat()), "\torientation");`

So maybe glm::quat() switched from 0,0,0,1 to 0,0,0,0 in 0.9.9.5 and thats why we see the failing tests? 

Hmm. See: https://github.com/g-truc/glm/issues/417 
It could be that this is now defined as default hence the issue: GLM_FORCE_NO_CTOR_INIT 

Actually looking at the 0.9.9.5 header it looks like we are missing this #define 

```
#if defined(GLM_FORCE_CTOR_INIT) && GLM_HAS_INITIALIZER_LISTS
#	define GLM_CONFIG_CTOR_INIT GLM_CTOR_INITIALIZER_LIST
#elif defined(GLM_FORCE_CTOR_INIT) && !GLM_HAS_INITIALIZER_LISTS
#	define GLM_CONFIG_CTOR_INIT GLM_CTOR_INITIALISATION
#else
#	define GLM_CONFIG_CTOR_INIT GLM_CTOR_INIT_DISABLE
#endif
```

If `GLM_CONFIG_CTOR_INIT == GLM_CTOR_INIT_DISABLE`
Then the quat is not set to 0,0,0,1 

```
#	if GLM_CONFIG_DEFAULTED_FUNCTIONS == GLM_DISABLE
		template<typename T, qualifier Q>
		GLM_FUNC_QUALIFIER GLM_CONSTEXPR qua<T, Q>::qua()
#			if GLM_CONFIG_CTOR_INIT != GLM_CTOR_INIT_DISABLE
			: x(0), y(0), z(0), w(1)
#			endif
		{}
```

So... to end a very long issue. 

**Solution?**
- I think forcing #define for GLM_FORCE_CTOR_INIT or making sure it doesn't end up as GLM_CTOR_INIT_DISABLE should fix the test issues.  this seems related: https://github.com/g-truc/glm/issues/735 
- And defining GLM_HAS_TEMPLATE_ALIASES should fix linux64.

**Comment by oxillo** [comment]
There was the same constructor initialisation problem for the polyline. 
#6366 fixed it by explicitly using glm::mat(1.0) instead of glm::mat().
Maybe the same explicit initialisation exist for quaternion ?

Also won't it be good to move to glm 0.9.9.6 as it fixes a bug on quaternion ?

**Comment by ofTheo** [comment]
There is some explanation here: 
https://github.com/g-truc/glm/issues/809#issuecomment-418092612 

Looks like the removal of default initializer is intentional. 
GLM_FORCE_CTOR_INIT helps with backwards compatibility. 

We actually might want to do both. 
Do explicit initialisation in the core but also #define GLM_FORCE_CTOR_INIT to help any addon breaking. 

for reference Cinder had similar issues upgrading to 0.9.9.5 
https://github.com/cinder/Cinder/pull/2118

**Comment by arturoc** [comment]
i don't think there's many addons using glm yet so perhaps it's better to just fix the core and let anything else break as well. The problem with using this defines is that they can go away (it happened before with some other flags we had enabled) but also that the code is not standard glm.

**Comment by ofTheo** [comment]
@oxillo yeah I think default values would be good. 
Though I think the default needs to be glm::quat(0,0,0,1)

where w = 1 
`Similarly, [0 0 0 1] (w=1) means that angle = 2*acos(1) = 0, so this is a unit quaternion, which makes no rotation at all.` 
 
I can do a PR with some of this stuff and see if it fixes the glm errors in the CI.

**Comment by ofTheo** [comment]
okay the other issue seems to be related to this commit: 
https://github.com/g-truc/glm/commit/41cf89516e3b6a5747c2d2c7fee187d84eb6c5cb 

So I think we can just switch all glm::tvec to glm::vec and things will be good. 

in 0.9.9.6 glm switched from using tvec to vec 
https://github.com/g-truc/glm/commit/4dd748f38051c3cb9abbde5abcc3ee5f6f320ffe

**Comment by ofTheo** [comment]
hmm nope - I think this is to do with `GLM_HAS_TEMPLATE_ALIASES` not getting defined for linux64 for some reason. 

```
#if GLM_COMPILER & GLM_COMPILER_CLANG
#	define GLM_HAS_TEMPLATE_ALIASES __has_feature(cxx_alias_templates)
#elif GLM_LANG & GLM_LANG_CXX11_FLAG
#	define GLM_HAS_TEMPLATE_ALIASES 1
#else
#	define GLM_HAS_TEMPLATE_ALIASES ((GLM_LANG & GLM_LANG_CXX0X_FLAG) && (\
		((GLM_COMPILER & GLM_COMPILER_INTEL)) || \
		((GLM_COMPILER & GLM_COMPILER_VC) && (GLM_COMPILER >= GLM_COMPILER_VC12)) || \
		((GLM_COMPILER & GLM_COMPILER_CUDA))))
#endif
```

going to do a test PR to see if 

`#define GLM_HAS_TEMPLATE_ALIASES 1 `

fixes the linux64 errors although we'll still need to figure out why its not being set.

**Comment by oxillo** [comment]
I stumble upon a strange behavior. Open GL 3.3 + glm 0.9.9.5 gives incorrect ouput : textures are rendered as a uniform colored rectable...
Going back to Open GL 2.1 or glm 0.9.8 solves the problem.

Tested with the gl/textureExample with the main.cpp modified to use glfwWindowSettings()

**Comment by ofTheo** [comment]
@oxillo I can reproduce. I see this issue even with glm 0.9.9.6 and my branch in #6397

If I put:

```
#define GLM_FORCE_CTOR_INIT 1 
``` 

at the top of ofConstants.h the issue goes away. 
So it suggests there are some glm variables needing initialization still. 🤔

**Comment by ofTheo** [comment]
Spent some hours today trying to track down this bug you mentioned @oxillo. 
At this point I have no idea. 

I think we could maybe just do `#define GLM_FORCE_CTOR_INIT 1 ` for now and get this release out. If we are feeling brave later we could remove the define and try and isolate the issue. 

Going to send a PR to test and make sure it works on all platforms.

**Comment by sphaero** [comment]
Not sure if it is related but I'm seeing glm errors on master. It's a travis build using makefiles so not sure if this happens on Xcode as well:

```
/Users/travis/openFrameworks/libs/openFrameworks/3d/ofNode.cpp:445:20: error: no type named 'uninitialize' in namespace 'glm'

                glm::mat3 m(glm::uninitialize);

                            ~~~~~^

/Users/travis/openFrameworks/libs/openFrameworks/3d/ofNode.cpp:445:14: warning: parentheses were disambiguated as a function declaration [-Wvexing-parse]

                glm::mat3 m(glm::uninitialize);

                           ^~~~~~~~~~~~~~~~~~~

/Users/travis/openFrameworks/libs/openFrameworks/3d/ofNode.cpp:445:15: note: add a pair of parentheses to declare a variable

                glm::mat3 m(glm::uninitialize);
```

**Comment by ofTheo** [comment]
@sphaero  hmm - I think you aren't on the latest master for OF. 
glm::uninitialize has been removed in master. 

See this commit: https://github.com/openframeworks/openFrameworks/commit/5fa86b5ca63119e8ae239208bcf7ff67069c48a4

**Comment by roymacdonald** [comment]
So what happens when you don't pass arguments to the constructor? it simply leaves garbage or the vec or quat or mat is not allocated properly?

**Comment by ofTheo** [comment]
Exactly, it just leaves the memory unallocated. This is because that is what glsl does and glm wants to have parity with glsl.  It’s a rough transition though.

**Comment by roymacdonald** [comment]
I see. thanks. 
So what happens then when you create an array with some of these. you'll have an array full with unallocated memory? would this lead to a crash? Does this also mean that all glm type need to be initialized explicitly upon declaration, even when in the .h file? Doesn't this go against the RAII idea?
