### ISSUE TITLE
ofVectorMath.h issues on latest

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6411]
Using the latest master today I've got multiple issues regarding 'vec' and 'sec' starting on line 125. 
thanks
![Screen Shot 2019-10-26 at 2 09 43 PM](https://user-images.githubusercontent.com/58289/67623339-4bf8ec00-f7fa-11e9-932c-61ecb3d01189.png)

Update:
latest working commit for me is 9af30346120a10c6de2644873da6f8bb3afeb963

**Comment by jeonghopark** [comment]
@dimitre Have you run the "download_libs.sh" script? My case, the issues were gone.

**Comment by dimitre** [comment]
Thank you very much. everything running now
