### ISSUE TITLE
glitch in ofxGuiColorPicker

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6419]
Sometimes the color picker draws the saturation slider with the last vertex extending outside of the control

**Comment by roymacdonald** [comment]
@arturoc does this happen under any special condition?

**Comment by roymacdonald** [comment]
sent PR with fix

**Comment by arturoc** [comment]
I've seen this happening after drawing two images, actually a video and an image and then a gui with an slider and a color picker. all of them coming from parameters

**Comment by roymacdonald** [comment]
I was looking at this issue and I still don't get a consistent behavior from it. 
It seems that some points of the mesh have garbage in the z value of its position. This might be related to the GLM changes done recently. Just setting to zero the z value at the ofRectangle-s constructor seems to work.
Does this make sense to you @arturoc ?

This might be also relate to [this](https://github.com/openframeworks/openFrameworks/issues/6435)
I'll test this a bit more before trying a fix.

**Comment by arturoc** [comment]
yes that sounds very likely. i also was getting this randomly so an uninitialized variable sounds very possible

**Comment by roymacdonald** [comment]
I still don't get to a conclusive test with this issue, although I think that we should initialize ofRectangle's position to 0 in order to avoid any other issue with it. What do you think?

**Comment by tgfrerer** [comment]
@roymacdonald can you point me to a test case which still fails?

**Comment by roymacdonald** [comment]
Lol @tgfrerer  you posted that PR just when I was saying that it should be done.
