### ISSUE TITLE
Package 'libgles1-mesa-dev' has no installation candidate (Pi 4 - Buster)

### ISSUE THREAD

**Issue by kod3000** [openframeworks/openFrameworks#6427]
I am installing OFX onto a rasp 4 using the release Buster.

Following the instructions from here :

https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/

I get the following error. 

> Package libgles1-mesa-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   libglvnd-dev
> 
> E: Package 'libgles1-mesa-dev' has no installation candidate
> error installing dependencies, there could be an error with your internet connection
> if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

**Comment by kod3000** [comment]
Removing the  'libgles1-mesa-dev' from the install_dependencies.sh file allows OFX to compile with no errors.

However, none of the examples want to compile after that point. They all give the same root error :

> ofUtils.cpp:(.text+0x9f8c): undefined reference to `__atomic_fetch_add_8'

Adding the flag 'PROJECT_LDFLAGS += -latomic ', to any example project allows them to compile. 


**References** :

https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856/26

**Comment by DeqingSun** [comment]
For anyone looking for a solution for this issue from a search engine. I found a better solution for the flag on https://qiita.com/felis_silv/items/2da88d3d7e9e4f3868f3

add "OF_PROJECT_LIBS_LDFLAGS += -latomic" in line 325 of openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.project.mk

Then there is no change needed for individual project.
