### ISSUE TITLE
Use of overloaded operator '*' is ambiguous with 'ofParameter<float>' and 'glm::tvec2<float, glm::packed_highp>'

### ISSUE THREAD

**Issue by sourya-sen** [openframeworks/openFrameworks#6428]
This should probably work as `float * glm::vec2` has no issues. I'll try taking a look at this in some time, unless someone else gets to it first!

Currently doing the following to make it work.
```
ofParameter<float> value;
glm::vec2 offset;

float(value) * offset; // (value * offset doesn't work)
```

**Comment by ofTheo** [comment]
hmm, curious if you see this with the OF 0.10.1 release? 
If not then it might be a regression. 

Also this is another way you can do it and avoid a cast. 

`value.get() * offset;`

**Comment by sourya-sen** [comment]
I'm on an early October nightly (of_v20191008_osx_release), so yes, OF 0.10.1

**Comment by ofTheo** [comment]
Thanks! I think this isn't a regression. 
`value.get()` is needed for some more strict operators to get the ofParameter to be treated as their templated type.
