### ISSUE TITLE
ofxGuiButton doesn't always draw the button 

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6435]
i've seen this in windows only but might be related to the specific graphics card

**Comment by roymacdonald** [comment]
I just got this on macos too.

**Comment by ofTheo** [comment]
@roymacdonald could you check if #6444 fixed this issue too? 
If so we can close - thanks!

**Comment by roymacdonald** [comment]
@ofTheo sure. 
Any idea on how to prefill the memory with garbage in order to increase the chances for this to happen?

**Comment by ofTheo** [comment]
@roymacdonald lol - I assumed you had a test case where this happened often. I can try the gui examples and see if I run into it.

**Comment by roymacdonald** [comment]
@ofTheo 😆  I've been trying to find a reliable way to trigger it but as it seems to be related to garbage memory, it happens randomly. So far what yields the highest chances is cleaning the project and build folder.

**Comment by ofTheo** [comment]
Just tested. 
Looks like #6444 fixed it. Thanks all!

**Comment by roymacdonald** [comment]
It looks like so. I can no longer get this error. @arturoc do you still get this glitch?
