### ISSUE TITLE
RPi 4 Support

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6436]
Making a comment to track getting RPi 4 working in the core. 

This thread on the forum has been really helpful: https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856

And there is a PR here which I haven't tried out yet. 
https://github.com/openframeworks/openFrameworks/pull/6325

Notes from @arturoc on allowing for switching between EGL and GL. 
https://github.com/openframeworks/openFrameworks/issues/6412#issuecomment-550284651 

This thread suggests legacy EGL support is not possible via the old approach:
https://www.raspberrypi.org/forums/viewtopic.php?p=1486714&sid=dc1c24dee4649d114b7cf089347f1833#p1486714 

**Current Status:** 
I have RPi 4 building the core and running headless ( using the nightly builds ) with these changes ( https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856/21 ) 

- 1
Switch this [line in install_dependencies.sh](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/debian/install_dependencies.sh#L40) to: 
```
apt-get install freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk${GTK_VERSION}-dev libopencv-dev libegl1-mesa-dev libglvnd-dev libassimp-dev librtaudio-dev libboost-filesystem-dev libglfw3-dev  liburiparser-dev libcurl4-openssl-dev libpugixml-dev
```

- 2
And add `PROJECT_LDFLAGS += -latomic ` to [this file](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L142).

Once I have a monitor/keyboard will start looking into the GL / EGL changes needed to get windowed apps running.

**Comment by sourya-sen** [comment]
This post for relating to making changes to the Rpi3/Stretch to run using the GL driver/windowed apps from @bakercp might be useful here.

https://forum.openframeworks.cc/t/compiling-of-in-raspbian-stretch/27562/15

**Comment by arturoc** [comment]
If you got it to work with the legacy driver, i think that could be enough for now. that's what most people would want to use i think, not a full x windows session

would be good to test it on the old rpi but i think if it compiles on the ci servers then it should be ok

**Comment by ofTheo** [comment]
Thanks @sourya-sen 

So far I can build and run with the legacy approach with those small changes and the ones @bakercp details, but no window appears on Rpi 4. 

The app gets mouse events and there isn't anything unusual in the debug so I think its something with buster configuration or the libs it's using. 

Would be ideal to get legacy working on both, before looking at the GL / GLFW method.

**Comment by ofTheo** [comment]
Nothing I have tried works so far. 
- Both using GLFW and the legacy approach. 
- #6325 doesn't work for me.

Next I am going to try this: 
https://github.com/ThomasColliers/openFrameworks/commit/36fd56f6ee1c33e25150be86126c8e02abf02086 

Which uses X11 combined with the ofAppEGLWindow.  
🤞

**Comment by ofTheo** [comment]
Okay got it working with @ThomasColliers 's commit.
I have a version which I'll push that has a single define for going between his changes and the current setup. 

@ThomasColliers did you ever get it working with GLFW or just ofAppEGLWindow + X11? 
If you didn't get the GLFW window working I'll leave out those changes - I haven't had any luck there so far.

**Comment by ThomasColliers** [comment]
> @ThomasColliers did you ever get it working with GLFW or just ofAppEGLWindow + X11?
> If you didn't get the GLFW window working I'll leave out those changes - I haven't had any luck there so far.
Ah.. I actually thought I was running GLFW but that doesn't seem to be the case:
https://pasteboard.co/IwAuGMN.png
So no, I did not get GLFW working either.

**Comment by ofTheo** [comment]
@ThomasColliers I did get GLFW working with some tweaks to your changes ( mainly just not changing ofConstants.h ) 

See this PR: #6438 
Uncomment this line for GLFW 
https://github.com/openframeworks/openFrameworks/pull/6438/files#diff-011c6dc421d3f054ec0e4dd9d10683d5R56 

Thanks again for your help with this!

**Comment by eshkrab** [comment]
Yay!! Sorry, I've been on another project and didn't respond to your question. thank you so much for getting it to work!
