### ISSUE TITLE
Kerning bug in ofTrueTypeFont::getKerning() - character pair lookup is backwards

### ISSUE THREAD

**Issue by tyhenry** [openframeworks/openFrameworks#6437]
There seems to be a bug in `ofTrueTypeFont::getKerning()` on [line 1027](https://github.com/openframeworks/openFrameworks/blob/b479caefd79b7e79104a3cd78429143ec8666678/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L1027) of ofTrueTypeFont.cpp.

The kerning lookup is being done backwards (when drawing a left-to-right font).

Here's the patch, referencing lines [1024-32](https://github.com/openframeworks/openFrameworks/blob/b479caefd79b7e79104a3cd78429143ec8666678/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L1024-L1032):
```c++
int ofTrueTypeFont::getKerning(uint32_t c, uint32_t prevC) const{
	if(FT_HAS_KERNING( face )){
		FT_Vector kerning;
		/* 
                   -- currently:
		FT_Get_Kerning(face.get(), FT_Get_Char_Index(face.get(), c), FT_Get_Char_Index(face.get(), prevC), FT_KERNING_UNFITTED, &kerning);
		   -- but should be: 
                */
		FT_Get_Kerning(face.get(), FT_Get_Char_Index(face.get(), prevC), FT_Get_Char_Index(face.get(), c), FT_KERNING_UNFITTED, &kerning);
		return kerning.x >> 6;
	}else{
		return 0;
	}
}
```

The FreeType function's signature, [from the doc](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_get_kerning), is:
```
  FT_Get_Kerning( FT_Face     face,
                  FT_UInt     left_glyph,
                  FT_UInt     right_glyph,
                  FT_UInt     kern_mode,
                  FT_Vector  *akerning );
```

When drawing a left-to-right font, `left_glyph` should be `prevC` and right_glyph should be `c`.
I can submit a PR with this patch - but I guess it should be extended slightly to account for right-to-left fonts using the internal `direction` setting?

**Comment by arturoc** [comment]
oh, thanks. yes can you send a PR? accounting for right to left should be relatively straightforward, just check the text direction and call this function the way it is now
