### ISSUE TITLE
MSYS@ install_dependencies doesnt run

### ISSUE THREAD

**Issue by Strum** [openframeworks/openFrameworks#6447]
trying to install OF in MSYS2

install_dependencies.sh just stalls and does nothing.

**Comment by oxillo** [comment]
@Strum Can you precise which version you are running ? This is know problem in of v0.10.1 and has been solved in the nightlies?
Please see this [solution](https://forum.openframeworks.cc/t/basic-question-about-setup-qt-creator-in-windows/25771/10?u=oxillo) in the forum.
If it solves your problem, can you please close the issue.

**Comment by oxillo** [comment]
@arturoc @ofTheo : This has been solved; can you close the issue ?

**Comment by ofTheo** [comment]
thanks @oxillo !
