### ISSUE TITLE
Unable to locate package libgl1-mesa-dev-hwe-18.04

### ISSUE THREAD

**Issue by kronikle** [openframeworks/openFrameworks#6449]
`Running` on ubuntu  18.04
Trovato:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Trovato:2 http://it.archive.ubuntu.com/ubuntu bionic InRelease
Trovato:3 http://it.archive.ubuntu.com/ubuntu bionic-updates InRelease         
Trovato:4 http://it.archive.ubuntu.com/ubuntu bionic-backports InRelease       
Ignorato:5 http://linux.dropbox.com/ubuntu bionic InRelease                    
Trovato:6 http://linux.dropbox.com/ubuntu bionic Release
Lettura elenco dei pacchetti... Fatto
detecting latest gstreamer version
Package: libgstreamer1.0-dev
Architecture: amd64
Version: 1.14.5-0ubuntu1~18.04.1
Multi-Arch: same
Priority: optional
Section: libdevel
Source: gstreamer1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Maintainers of GStreamer packages <gstreamer1.0@packages.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 5309
Depends: libgstreamer1.0-0 (= 1.14.5-0ubuntu1~18.04.1), libc6-dev | libc-dev, pkg-config, libglib2.0-dev, libc6 (>= 2.4), libglib2.0-0 (>= 2.40), gir1.2-gstreamer-1.0 (= 1.14.5-0ubuntu1~18.04.1)
Recommends: debhelper
Suggests: gstreamer1.0-doc
Conflicts: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Replaces: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Filename: pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.14.5-0ubuntu1~18.04.1_amd64.deb
Size: 397696
MD5sum: 9b73c09b06d333399b53eaae8b2837cf
SHA1: 733d37d88e4fded111d1c3d9b9f9e1cd98fa42c4
SHA256: 279ebcb6f51f2491323caacef8308bd4a24f54d79b957299ed24f31d3ce1af98
Homepage: https://gstreamer.freedesktop.org
Description-it: GStreamer core development files
 GStreamer è un'infrastruttura di streaming multimediale basata su
 diagrammi di filtri che operano su dati multimediali. Le applicazioni che
 usano questa libreria possono fare qualsiasi cosa, dall'elaborazione del
 suono in tempo reale alla riproduzione di video, fino a qualsiasi altra
 cosa relativa alla multimedialità. La sua architettura, basata su plugin,
 consente di aggiungere nuovi tipi di dati o capacità di riproduzione
 semplicemente installando il plugin interessato.
 .
 This package contains development files for the core library and elements.
Description-md5: de1692260510350a48f76ec91eae40a9
Supported: 5y

Package: libgstreamer1.0-dev
Architecture: amd64
Version: 1.14.1-1~ubuntu18.04.2
Priority: optional
Section: libdevel
Source: gstreamer1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Maintainers of GStreamer packages <gstreamer1.0@packages.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 5292
Depends: libgstreamer1.0-0 (= 1.14.1-1~ubuntu18.04.2), libc6-dev | libc-dev, pkg-config, libglib2.0-dev, libc6 (>= 2.4), libglib2.0-0 (>= 2.40), gir1.2-gstreamer-1.0 (= 1.14.1-1~ubuntu18.04.2)
Recommends: debhelper
Suggests: gstreamer1.0-doc
Conflicts: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Replaces: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Filename: pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.14.1-1~ubuntu18.04.2_amd64.deb
Size: 397272
MD5sum: b40bd335b801cdba152823cdb7e5fca1
SHA1: d82627d32ca204cba00817b619a3f3731d9194b4
SHA256: b27efe6e8215a812ef2c01a30112e65c6e1dff36ffbf0eed7a69daf54ba59458
Homepage: https://gstreamer.freedesktop.org
Description-it: GStreamer core development files
 GStreamer è un'infrastruttura di streaming multimediale basata su
 diagrammi di filtri che operano su dati multimediali. Le applicazioni che
 usano questa libreria possono fare qualsiasi cosa, dall'elaborazione del
 suono in tempo reale alla riproduzione di video, fino a qualsiasi altra
 cosa relativa alla multimedialità. La sua architettura, basata su plugin,
 consente di aggiungere nuovi tipi di dati o capacità di riproduzione
 semplicemente installando il plugin interessato.
 .
 This package contains development files for the core library and elements.
Description-md5: de1692260510350a48f76ec91eae40a9
Supported: 5y

Package: libgstreamer1.0-dev
Architecture: amd64
Version: 1.14.0-1
Priority: optional
Section: libdevel
Source: gstreamer1.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Maintainers of GStreamer packages <pkg-gstreamer-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 5285
Depends: libgstreamer1.0-0 (= 1.14.0-1), libc6-dev | libc-dev, pkg-config, libglib2.0-dev, libc6 (>= 2.4), libglib2.0-0 (>= 2.40), gir1.2-gstreamer-1.0 (= 1.14.0-1)
Recommends: debhelper
Suggests: gstreamer1.0-doc
Conflicts: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Replaces: libgstreamer-plugins-bad1.0-dev (<< 1.13.1)
Filename: pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.14.0-1_amd64.deb
Size: 397268
MD5sum: d51e56167a3cd514fb062c6c2b9242cf
SHA1: 2ed535bd120877db35fedb513df87b7d8b606491
SHA256: e302cb1062f30de6403c68c0abaea690b2cb09df2458b14179525c3ce8127528
Homepage: http://gstreamer.freedesktop.org
Description-it: GStreamer core development files
 GStreamer è un'infrastruttura di streaming multimediale basata su
 diagrammi di filtri che operano su dati multimediali. Le applicazioni che
 usano questa libreria possono fare qualsiasi cosa, dall'elaborazione del
 suono in tempo reale alla riproduzione di video, fino a qualsiasi altra
 cosa relativa alla multimedialità. La sua architettura, basata su plugin,
 consente di aggiungere nuovi tipi di dati o capacità di riproduzione
 semplicemente installando il plugin interessato.
 .
 This package contains development files for the core library and elements.
Description-md5: de1692260510350a48f76ec91eae40a9
Supported: 5y

selecting gstreamer 1.0
detecting latest gtk version
Package: libgtk-3-dev
Architecture: amd64
Version: 3.22.30-1ubuntu4
Multi-Arch: same
Priority: optional
Section: libdevel
Source: gtk+3.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 10900
Depends: libgtk-3-0 (= 3.22.30-1ubuntu4), gir1.2-gtk-3.0 (= 3.22.30-1ubuntu4), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.49.4), libgdk-pixbuf2.0-dev (>= 2.30.0), libpango1.0-dev (>= 1.40.5), libatk1.0-dev (>= 2.15.1), libatk-bridge2.0-dev, libcairo2-dev (>= 1.14.0), libepoxy-dev (>= 1.0), libfontconfig1-dev, libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config, libegl1-mesa-dev, libwayland-dev (>= 1.9.91), wayland-protocols (>= 1.9), libxkbcommon-dev
Suggests: libgtk-3-doc
Filename: pool/main/g/gtk+3.0/libgtk-3-dev_3.22.30-1ubuntu4_amd64.deb
Size: 896768
MD5sum: 8254c8f2fd9e2d9c3500418a2aada628
SHA1: 5b96a85d3593636dcf57c5c8b8104fea6db09b37
SHA256: 7745630de7a12fdd770a5c336dcd9d8319e89b86847e11ab0205dfe1a06c1ba2
Homepage: https://www.gtk.org/
Description-it: development files for the GTK+ library
 Gtk+ è un toolkit multipiattaforma per creare interfacce utente grafiche.
 Poiché offre un insieme completo di widget, Gtk+ è adatto a progetti che
 vanno da piccoli strumenti autonomi a complete suite di applicazioni.
 .
 This package contains the header and development files which are needed
 for building GTK+ applications.
Description-md5: 5e247317651e3625eb226ee49f0cfec7
Supported: 5y

Package: libgtk-3-dev
Architecture: amd64
Version: 3.22.30-1ubuntu1
Multi-Arch: same
Priority: optional
Section: libdevel
Source: gtk+3.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 10899
Depends: libgtk-3-0 (= 3.22.30-1ubuntu1), gir1.2-gtk-3.0 (= 3.22.30-1ubuntu1), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.49.4), libgdk-pixbuf2.0-dev (>= 2.30.0), libpango1.0-dev (>= 1.40.5), libatk1.0-dev (>= 2.15.1), libatk-bridge2.0-dev, libcairo2-dev (>= 1.14.0), libepoxy-dev (>= 1.0), libfontconfig1-dev, libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config, libegl1-mesa-dev, libwayland-dev (>= 1.9.91), wayland-protocols (>= 1.9), libxkbcommon-dev
Suggests: libgtk-3-doc
Filename: pool/main/g/gtk+3.0/libgtk-3-dev_3.22.30-1ubuntu1_amd64.deb
Size: 896856
MD5sum: c012e7cc07777856ab7ddae9e096f0c8
SHA1: c710df89535fe40f5fe60e18e94733fdc16711df
SHA256: 19eb2c6960ec575b5e9ccdd2e4ff6344fdb0a201f3c30b482fbc9603752b25cc
Homepage: https://www.gtk.org/
Description-it: development files for the GTK+ library
 Gtk+ è un toolkit multipiattaforma per creare interfacce utente grafiche.
 Poiché offre un insieme completo di widget, Gtk+ è adatto a progetti che
 vanno da piccoli strumenti autonomi a complete suite di applicazioni.
 .
 This package contains the header and development files which are needed
 for building GTK+ applications.
Description-md5: 5e247317651e3625eb226ee49f0cfec7
Supported: 5y

selecting gtk 3
 installing OF dependencies with -hwe-18.04 packages, confirm Y/N ? y
installation of OF dependencies with -hwe-18.04 packages confirmed
Package: libglfw3-dev
Architecture: amd64
Version: 3.2.1-1
Multi-Arch: same
Priority: optional
Section: universe/libdevel
Source: glfw3
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 196
Depends: libglfw3 (= 3.2.1-1) | libglfw3-wayland (= 3.2.1-1), libgl1-mesa-dev | libgl-dev
Recommends: libegl1-mesa-dev, libvulkan-dev, libwayland-dev, libx11-dev, libxrandr-dev
Conflicts: libglfw-dev
Filename: pool/universe/g/glfw3/libglfw3-dev_3.2.1-1_amd64.deb
Size: 30908
MD5sum: 0233fb2568cc26bf00dad636b31ba1ae
SHA1: 1cb05c20b01dd924f7087d335ffa3b8694f48efb
SHA256: 9130da62993b887b1802a0e22e86b88011d79dc675f258e3efbeb92a9ec415b9
Homepage: http://www.glfw.org/
Description-it: portable library for OpenGL, window and input (development files)
 GLFW is an Open Source, multi-platform library for creating windows with
 OpenGL contexts and managing input and events. It is easy to integrate
 into existing applications and does not lay claim to the main loop.
 .
 Questo pacchetto fornisce i file di sviluppo.
Description-md5: d32f1f76941ab1185f332cadd1f7fa2b

installing OF dependencies
OF needs to install the following packages using apt-get:
curl libjack-jackd2-0 libjack-jackd2-dev freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev-hwe-18.04 libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk-3-dev libopencv-dev libassimp-dev librtaudio-dev libboost-filesystem-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-pulseaudio gstreamer1.0-x gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good gdb libglfw3-dev liburiparser-dev libcurl4-openssl-dev libpugixml-dev
Do you want to continue? [Y/n] y

Installing...

Installing curl
 Already installed
Installing libjack-jackd2-0
 Already installed
Installing libjack-jackd2-dev
 Already installed
Installing freeglut3-dev
 Already installed
Installing libasound2-dev
 Already installed
Installing libxmu-dev
 Already installed
Installing libxxf86vm-dev
 Already installed
Installing g++
 Already installed
Installing libgl1-mesa-dev-hwe-18.04
E: Impossibile trovare il pacchetto libgl1-mesa-dev-hwe-18.04
E: Impossibile trovare alcun pacchetto tramite il glob "libgl1-mesa-dev-hwe-18.04"
E: Impossibile trovare alcun pacchetto tramite l'espressione regolare "libgl1-mesa-dev-hwe-18.04"
error installing libgl1-mesa-dev-hwe-18.04
Lettura elenco dei pacchetti... Generazione albero delle dipendenze... Lettura informazioni sullo stato...
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues
`

**Comment by kronikle** [comment]
I've yet said no to -hwe and installed the others packets but I can't compile OF...

**Comment by ofTheo** [comment]
Hmm similar to #6360 

Did you try:
`libgl1-mesa-dev`
or 
`libgl1` 

If you remove it all together do you have any issues running OF?

**Comment by kronikle** [comment]
I edited the script install_dependencies.sh both removing `${XTAG}` aflter `libgl1-mesa dev` and with just `libgl1` and the installation of the packages were fine.

But.. Trying to execute the script compileOF.sh I had many errors like this:
`makefileCommon/compile.core.mk:238: recipe for target '/home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworksCompiled/lib/linux64/obj/Debug/libs/openFrameworks/communication/ofSerial.o' failed`

I attach the complete output here.
[result_compileOF.txt](https://github.com/openframeworks/openFrameworks/files/3851435/result_compileOF.txt)

**Comment by ofTheo** [comment]
Posting an example of the errors. 
This looks like a known issue on the forums: https://forum.openframeworks.cc/t/cannot-compile-of-errors-on-of3dprimitives-and-conflicting-gl-glew-declarations/30307/14 

Solution is to comment out GL/glext.h and now looking at our master branch it looks like that is already done. 

@kronikle  Could you try the nightly builds and see if that fixes it? 
See the links at the bottom of this page: https://openframeworks.cc/download/ 

If you still get the error can you re-open this issue?

`
In file included from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:212:0,
                 from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/communication/ofArduino.h:29,
                 from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/communication/ofArduino.cpp:47:
/usr/include/GL/glext.h:12066:105: error: conflicting declaration 'typedef void (* PFNGLFRAGMENTLIGHTFVSGIXPROC)(GLenum, GLenum, const GLfloat*)'
 typedef void (APIENTRYP PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, const GLfloat *params);
                                                                                                         ^
In file included from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/utils/ofConstants.h:210:0,
                 from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/communication/ofArduino.h:29,
                 from /home/samuele/openframeworks/of_v0.10.1_linux64gcc6_release/libs/openFrameworks/communication/ofArduino.cpp:47:
/usr/include/GL/glew.h:16092:28: note: previous declaration as 'typedef void (* PFNGLFRAGMENTLIGHTFVSGIXPROC)(GLenum, GLenum, GLfloat*)'
 typedef void (GLAPIENTRY * PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, GLfloat* params);
`
