### ISSUE TITLE
Dependencies: Ubuntu

### ISSUE THREAD

**Issue by csverma610** [openframeworks/openFrameworks#6451]
Hello,

I am trying to install OpenFrameWorks on ubuntu and I have all the dependencies installed. However,
it seems the install_dependencies.sh does not check properly if the software has already been installed and it says: 

detected ubuntu 18.04 or greater
OF needs to install poco libraries in the system with the following packages:
libpoco-dev
Do you want to continue? [Y/n] y

This, I think, is unnecessary.

**Comment by bakercp** [comment]
This is not a clearly articulated bug report for openFrameworks.  Please post your question on the forum.  https://forum.openframeworks.cc/
