### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by csverma610** [openframeworks/openFrameworks#6453]
Hello,

The webpage says that to run an example, we should do

cd OF/examples/graphics/polygonExample
make
make run

But I do not see Makefile in the folder. How makefile will work then?

**Comment by 2bbb** [comment]
https://forum.openframeworks.cc/

**Comment by bakercp** [comment]
This is not a bug in openFrameworks, please post your question on the forum.  https://forum.openframeworks.cc/
