### ISSUE TITLE
OF_USE_LEGACY_VECTOR_MATH not working

### ISSUE THREAD

**Issue by miflck** [openframeworks/openFrameworks#6463]
when OF_USE_LEGACY_VECTOR_MATH is set to 1, i cant compile and get several Shell Script Invocation Error Group like:

`'reference' is a protected member of 'std::__1::__deque_base<ofVec3f, std::__1::allocator<ofVec3f> '`

on macOs 10.14.6 and XCode 11.1 
oF 10.1_osx_release and of_v20191118_osx_release nightly build.

**Comment by arturoc** [comment]
thanks for the report, does this happen on any example or with a particular project?

**Comment by miflck** [comment]
I have it on any project I tested so far. Also with newly generated ones from Projectgenerator. Unfortunately i am not familiar with that types of errors and don't really get, what they are trying to tell me. So i have no idea where to start digging.

**Comment by arturoc** [comment]
that's fine, just wanted to make sure this is something we can easily reproduce or it was something that only happened on a particular project

**Comment by ofTheo** [comment]
I took a quick look yesterday. 
Most of the errors seem to come from forward decelerations of the ofVec types and needing the complete types in the header or in inline functions. 

ie: 

```
class ofVec2f; 
class ofVec3f; 
``` 

And then using the type but without it being defined. 

I tried some quick fixes but it was a bit of a puzzle and might take a bit of work to get compiling.
