### ISSUE TITLE
Confused about the build process after installation

### ISSUE THREAD

**Issue by Franceshe** [openframeworks/openFrameworks#6466]
Hi, I am new to this project and just downloaded it and forked it as the recommended way of installation of MAC OSX.
So I had followed exactly INSTALL_FROM_GITHUB.md as following, and indeed see the success of build message for the compilation of all examples of project generator.
But i am confused where can i acess this compiled examples in my directories.
Say where are they in the openFrameworks folder and how can i access/execute them by command line or xcode?
I also successfully build a single example for 3DPrimitivesExample by using Xcode.
Does that mean now i have two compiled example, one build from xcode and another one build from fully compilation process of project generator? 
Thanks!

The following is from  INSTALL_FROM_GITHUB.md 
```
### Get the Project Generator

Now that you have all the required files, you need to compile them and set up all the projects contained in the `examples` folder. The easiest way to do this is by using the Project Generator to compile all the examples.
The Project Generator app facilitates creating new openFrameworks projects and adding or removing addons to existing projects. As it is a separate project with a well defined scope, the openFrameworks developers decided to put it into its own repository. You can get the project generator in two different ways:
* Initialize and update all the git submodules (including the Project Generator) by first running `git submodule init` and then `git submodule update`.
* Or, easier, download an already packaged openFrameworks installation from the [download page](http://openframeworks.cc/download/), and copy the `projectGenerator` folder into your openFrameworks installation.

As the first option can lead to [unexpected results](https://forum.openframeworks.cc/t/how-to-build-project-generator-from-of-git-repo/26232), we suggest you use the second approach.

### Compile all the examples

Now that you have the Project Generator, you are ready to compile all the examples:

#### Option 1 - With the Project Generator app
* Start the Project Generator application by double clicking on it.
* Hit the cog wheel on the right side of the Project Generator window and select `advanced options`.
* Select the `update multiple` tab, enter the path to the examples folder inside the current OpenFrameworks repo folder.
* Make sure to select your platform in the platforms field below.
* Click on `update multiple` and wait. This operation can take a while depending on your hardware.

Once the success message appears you are done.
```

**Comment by roymacdonald** [comment]
Hi, if you are new to openFrameworks the recommended way of using it is to download the prepackaged version for the platform you are using instead of building form github.
download it from openframeworks.cc/download 
Using this download you'll get all the needed libraries as well as the project generator, and examples should build simply by opening on xcode and pressing the run button (the "play" triangle in the top left).

**Comment by roymacdonald** [comment]
btw, where did you read that the recommended way for MACOS is to fork and build from github? This is only needed if you want to contribute with code.

**Comment by roymacdonald** [comment]
This might be useful https://openframeworks.cc/ofBook/chapters/setup_and_project_structure.html
cheers

**Comment by Franceshe** [comment]
> btw, where did you read that the recommended way for MACOS is to fork and build from github? This is only needed if you want to contribute with code.

Thanks for the reply, at first I downloaded 0.10.1 version from https://openframeworks.cc/download/ for OSX but when i run the default 3dpreview example, but can't build and run into the same issue as https://forum.openframeworks.cc/t/cant-run-examples-in-xcode-signing-issue-with-libfmodex-dylib/33463.
But I did not notice the nightly build at the same, later I found out it was bottom of the page...
I then follow the INSTALL_FROM_GITHUB.md cause i can't not resolve the code sign issue.

Thanks, the setup structure helps my understanding better.

**Comment by ofTheo** [comment]
@Franceshe the code sign issue is fixed in Github master and the nightly builds. We should have a release out soon.  In the meantime please use the nightly releases or use some of the other [tips in the forum.](https://forum.openframeworks.cc/t/cant-run-examples-in-xcode-signing-issue-with-libfmodex-dylib/33463/8) 

As this isn't really a GitHub issue, I'm going to close this. 
The forum is a better place for these sorts of questions.
