### ISSUE TITLE
App submission issue with 'libfmodex.dylib'

### ISSUE THREAD

**Issue by thedofl** [openframeworks/openFrameworks#6472]
Hi Teo,

I think you already figured out the app submission issue with 'libfmodex.dylib' on Master version but am still getting below error from latest Master version. Any thought?

"macOS High Sierra is the last version of macOS that will run 32-bit apps without compromise. The Mac App Store will require all apps (including updates) to be exclusively 64-bit by June 2018."

Thanks in advance,

Dofl

**Comment by ofTheo** [comment]
I think you might need to strip the 32bit code from libfmodex.dylib with lipo. 
I think we could make this part of the build for AppStore scheme in the Xcode project.  
( which I notice is not working now in master ). 

```
lipo -remove i386 libfmodex.dylib -o libfmodex.dylib 
```
If you call this on the libfmodex.dylib in `libs/fmodex/lib/osx/` ( after you backup the dylib ) that should make it 64bit only. 

Going to look into making this part of the AppStore scheme though.

**Comment by thedofl** [comment]
Theo, your suggestion works nicely. You saved my life.

**Comment by ofTheo** [comment]
no problem @thedofl 
thanks for reporting - it will be fixed in the next release, so when you select the AppStore config it will happen automatically.
