### ISSUE TITLE
ofOpenALSoundPlayer conflicts with latest OpenAL

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6490]
See: https://forum.openframeworks.cc/t/compilation-failing-due-to-confliting-definition-in-openal/33927/2 

Due to OpenAL 1.2 ( released less than a week ago ) changing some struct typedefs. 
This should be an easy fix.

**Comment by ofTheo** [comment]
closed by #6498

**Comment by saucesaft** [comment]
Hey, i'm having this issue as well on my MSYS2/MINGW64 environment and can confirm this patch indeed works but i needed to apply it manually. Can i open a pull request so that the solution/patch for linux is also applied to MSYS2 or should i open a new issue?

**Comment by arturoc** [comment]
yes sure!
