### ISSUE TITLE
ofxGui improvements

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6491]
Hi, 
I've been doing improvements to `ofxGui`some of which are PRs https://github.com/openframeworks/openFrameworks/pull/6479 https://github.com/openframeworks/openFrameworks/pull/6429

- Removing elements from an `ofxPanel` or `ofxGuiGroup`instance, either by name, position or referenced `ofParameter`. ( https://github.com/openframeworks/openFrameworks/pull/6479 already adds the needed support for doing this properly by storing unique pointers. It is just the functions that need to be added).
- Add  `enable()`, `disable()`, `bool isEnabled()`  methods to `ofxBaseGui`which mainly set a flag for rendering or not the element and passing or not the mouse events. This would allow to make `ofxGui` much more dynamic (ie. show certain parameters only under specific conditions, make contextual menus, etc)
- Add a dropdown menu class. I already made an [addon for such](https://github.com/roymacdonald/ofxDropdown) which works ok but needs a bit more work on how to support different data types and make easier to use. 
- Add Enable/Disable functions for the scroll listener of the sliders (although useful I find more useful to use scrolling for moving guis that are larger than the window )

What do you think @arturoc @ofTheo @ofZach @bakercp ?

**Comment by ofTheo** [comment]
Thanks @roymacdonald 
Think both those PRs are tagged for 0.11.1. I was planning on pulling them all in and testing soon to check there aren't any issues. I'll tag some of the others you mentioned in the 0.11.1 checklist.

**Comment by roymacdonald** [comment]
Merged to master. closing
