### ISSUE TITLE
`projectGenerator` requires gconf2, but it is not installed (Debian)

### ISSUE THREAD

**Issue by galexite** [openframeworks/openFrameworks#6493]
The script `scripts/linux/debian/install_dependencies.sh` doesn't install the `libgconf-2-4` package required by `projectGenerator`, resulting in the following error when trying to execute the generator:

    error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

This script should install this dependency to allow the `projectGenerator` to work.

Tested with openFrameworks 0.11.0, on Debian 10.2 (buster).

**Comment by ofTheo** [comment]
Thanks!
I know libgconf-2-4 is included in the ubuntu install_dependencies.sh. 
We can add it to the Debian one too.

**Comment by arturoc** [comment]
we should include this to every linux distro install script
