### ISSUE TITLE
MSYS2 64bits : many GLM warnings

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#6496]
When compiling, many warnings emitted :

```
N:/openFrameworks/libs/glm/include/glm/gtc/packing.inl:506:37: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'glm::i16vec4' {aka 'struct glm::vec<4, short int, glm::packed_highp>'} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  506 |   memcpy(&Unpack, &v, sizeof(Unpack));
      |                                     ^
```

Undefining GLM_FORCE_CTOR_INIT in ofConstants.h solve the problem.
Seems like a GLM issue g-truc/glm#854

**Comment by ofTheo** [comment]
Adding this to 0.11.1 
I get the warnings on my PI setup, so I'll dig in and see if there is a way to resolve them without undefining GLM_FORCE_CTOR_INIT.

**Comment by oxillo** [comment]
on MSYS2, using system installed GLM (0.9.9.7) solves the problem.

**Comment by arturoc** [comment]
I don't want to move glm to a system library until there's a stable release. Until then it changes too much to have people use different versions. can you send a PR to apothecary changing the version number for glm here https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/glm/glm.sh#L9  that should solve the issue as well

**Comment by ofTheo** [comment]
Should be closed by: 
https://github.com/openframeworks/apothecary/pull/182

**Comment by oxillo** [comment]
GLM_FORCE_CTOR_INIT shall also be undefined in ofConstants.h

**Comment by ofTheo** [comment]
Hmm @oxillo I don't think it should. 

For a test like:
```
    glm::vec3 val;
    glm::vec2 val2;
    cout << " val is " << val << " - val 2 is " << val2 << endl;
```

with GLM_FORCE_CTOR_INIT defined ( as it is now ) I get:
`val is 0, 0, 0 - val 2 is 0, 0`

not defining GLM_FORCE_CTOR_INIT I get: 
`val is 2.20597e+31, 2.20597e+31, 2.20597e+31 - val 2 is 2.20597e+31, 2.20597e+31`

So I think moving from 0.9.9.6 to 0.9.9.7 didn't change the behavior for that define. 
If we remove it, it would break countless projects and addons.

**Comment by oxillo** [comment]
@ofTheo fixed it with the PR above keeping GLM_FORCE_CTOR_INIT !
Just removed glm/ext.hpp from ofVectorMath.h. It removes defienition of specific types not used in OF.

**Comment by ofTheo** [comment]
awesome - thanks @oxillo 👍
