### ISSUE TITLE
OF slow on Raspberry Pi4

### ISSUE THREAD

**Issue by Bencilari** [openframeworks/openFrameworks#6497]
OF 0.11.0 seems quite slow on a raspberry pi 4 (raspian, based on debian buster).
A simple example (graphics/polygonExample), at 1024x768 run at ~40FPS. Run with OF_FULLSCREEN, the FPS it's only half of this, ~20FPS.
With smaller window (e.g. 800x600) seems catch the expected 60FPS (not tested in full screen mode)

**Comment by jvcleave** [comment]
I don't have an RPI4 to try but I am wondering if the shaders need to be changed for the new drivers? As I remember the previous ones were kinda quirky but worked well.

some reference points

https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L2394

https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L2125

**Comment by ofTheo** [comment]
Just to add the thread on the forum: https://forum.openframeworks.cc/t/of-slow-on-rpi4/33977/7 
Also I get a big FPS difference by setting numSamples to 0. 

```
    ofGLFWWindowSettings msettings;
    msettings.setSize( 1024, 768 );
    msettings.numSamples = 0; 
    auto mainWin = ofCreateWindow( msettings );

    auto app = make_shared<ofApp>();
    ofRunApp( mainWin, app );
    ofRunMainLoop();
```

I think maybe making numSamples=0; on GLFW Window for Pi would help a lot.

**Comment by arturoc** [comment]
are we still using openGL ES with the new driver? cause if we are using openGL that could slow down things a lot since the graphics card only has support for openGL ES so it might be emulating some stuff to provide full openGL

**Comment by ofTheo** [comment]
Yes, it is still currently OpenGL ES.
I think its mostly the numSamples and maybe the X environment too? 

But from the forum post they can get 60fps now with GLFW and X with numSamples = 0.

**Comment by Bencilari** [comment]
> Yes, it is still currently OpenGL ES.
> I think its mostly the numSamples and maybe the X environment too?
> But from the forum post they can get 60fps now with GLFW and X with numSamples = 0.

Just a note: setting numSamples=0 speed up the FPS, but obviusly the image quality it's not the same.
I'm not aware of the RPi4 GL capabilities, but i think this solution should be considered a workaround

**Comment by ofTheo** [comment]
That's correct! 
But the old default window for RPi didn't have 4x AA on by default, so this just matches the old behavior and hopefully framerates. Users can still manually set the numSamples they want for their project.

**Comment by dasoe** [comment]
Hi all,

I don't think this issue should be closed. It's much better with numSamples set to 0 but still slower than expected. 
At least for me, 3DPrimitvesExample in Fullscreen (which makes the difference) on a PI4 runs with 37 FPS. Running the same on a Pi3 (also Fullscreen, also with X-windows in background) gives me 50-60 FPS, so quite a regression. Same outcome with adjusted stable Version and nightly build.
In my usecase (big Museum, Pis running differnet OF projects) I also do not really need (or want) X-Windows but I did not get the legacy way working. 

Thanks & have a great day!
oe

**Comment by ofTheo** [comment]
@dasoe could you try @jvcleave 's addon and see if that works better for you performance wise?
I imagine that this could be a default window for Rpi4 and newer. 

https://forum.openframeworks.cc/t/new-ofxaddon-ofxrpi4window/34388/18
