### ISSUE TITLE
"No matching overloaded function" in ofEvent.h because of call to ofRegisterURLNotification?

### ISSUE THREAD

**Issue by P-v-K** [openframeworks/openFrameworks#6504]
On Windows using Microsoft Visual Studio Community 2017, and OF 0.10.1 (nightly code from 10/31/2019: of_v20191031_android_nightly.tar.gz).

This also happens using OF 0.11.0 on Windows using Microsoft Visual Studio Community 2017.

Trying to follow the example here: https://openframeworks.cc/documentation/utils/ofURLFileLoader/#show_ofLoadURLAsync

The line is ofApp::Setup():
`ofRegisterURLNotification(this);`

Seems to cause compilation errors in ofEvent.h line 535:
> Error C2672 'ofEvent<ofHttpResponse,std::recursive_mutex>::addNoToken': no matching overloaded function found
> Error C2661 'ofEvent<ofHttpResponse,std::recursive_mutex>::make_function': no overloaded function takes 3 arguments	
> in handleRequestAsyncBugDemo c:\of0.10.1vs2017\libs\openframeworks\events\ofevent.h	line 535	

Even when simply adding that line and an urlResponse handler function of a clean ofApp class created by the ProjectGenerator.

i.e. I simply added:

in ofApp.h:
`void` urlResponse(const ofHttpResponse & response);

in ofApp.cpp:
```
void ofApp::setup(){
    ofRegisterURLNotification(this);
}

void ofApp::urlResponse(const ofHttpResponse & response) {}
```

**Comment by roymacdonald** [comment]
Hi, the problem is that the callback function's argument should not be `const`
change
`void ofApp::urlResponse(const ofHttpResponse & response) {}`
to 
`void ofApp::urlResponse(ofHttpResponse & response) {}`

**Comment by P-v-K** [comment]
Thanks Roy!
That does make the compiler error go away.
I'm still blocked by https://github.com/openframeworks/openFrameworks/issues/6505 , but this aspect of the problem is at least wrapped up by your comment, I think.
