### ISSUE TITLE
makefiles on osx 10.15

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/openFrameworks#6509]
The makefile build seems to be broken on osx catalina (or my colleague misconfigured his machine). I have not yet updated to 10.15 and cannot really test for now. I will check with my colleague when i am back at work next year.

```
Compiling OF library for Release
makefileCommon/config.shared.mk:217: *** This package doesn't support your platform, /Users/username/Documents/projects/projectname/of_v0.11.0_osx_release/libs/openFrameworksCompiled/project probably you downloaded the wrong package?.  Stop.
```

xcode is not updated to the most recent version. command line build tools are up to date.

https://forum.openframeworks.cc/t/of-0-11-0-release/33918/21?u=thomasgeissl

**Comment by oxillo** [comment]
Looks quite similar to #6158

**Comment by ofTheo** [comment]
going to close this at least for now. 
If there is a specific way to reproduce we can reopen.
