### ISSUE TITLE
win10 of011: ofLog() not printing in debugging console

### ISSUE THREAD

**Issue by johanjohan** [openframeworks/openFrameworks#6511]
As reported 1 year ago in the forum, ofLog() messages do not show up in debugging console. I have the same issue on win10 vs2017 of0.11 (downloadpage). 
I have set ofSetLogLevel(OF_LOG_VERBOSE);

Is this known or resolved?
see
https://forum.openframeworks.cc/t/debug-exe-screen-not-showing-oflog-messages/30693

**Comment by ofTheo** [comment]
According to @NickHardeman 's reply on the forum - calling: `ofLogToConsole();` makes logging work as expected.

**Comment by johanjohan** [comment]
Thank you @ofTheo , I confirm that calling: ofLogToConsole(); makes logging work as expected.

**Comment by ofTheo** [comment]
@johanjohan could you see if this also works?

commenting out these lines in libs/openFrameworks/utils/ofLog.cpp:
https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/utils/ofLog.cpp#L30-L32

**Comment by johanjohan** [comment]
@ofTheo now i am confronted with the situation, that I cannot reproduce the bug anymore: all combinations work without any change:
		Debug: x64 works, x32 works
		Release: x32 works, x64 works

Changes I had made before, that may have had to do with this

* I made a system wide change yesterday, since After Effects refused to start: AE Error: Could not convert Unicode Characters
So I successfully changed in win10 --> Control Panel\Clock and Region --> administrative --> change system locale --> UNCHECK: beta: use unicode UTF8.... (which I had checked until yesterday)

* Compiler flag used: /utf-8

* defines in order to use assert() i release mode:
#undef NDEBUG
#include <assert.h>

but, as I said, I cannot reproduce the bug anymore, I changed these back and forth just now.

**Comment by ofTheo** [comment]
okay - thanks!  @johanjohan 
@prisonerjohn have you noticed this issue at all with 0.11.0?

**Comment by johanjohan** [comment]
@ofTheo thank you! yes, i noticed the issue in 0.11.0

**Comment by ofTheo** [comment]
closing as I can't reproduce on a clean install.
