### ISSUE TITLE
ofOpenALSoundPlayer::play() in thread crashes

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#6514]
ofOpenALSoundPlayer::play() calls glGetError() so if I run it in a thread, it crashes. Is there a reason this is there or can I make a pull request removing it?

**Comment by oxillo** [comment]
May be it should be alGetError() instead ? OpenGL and openAL look so close…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Neil Mendoza<mailto:notifications@github.com>
Envoyé le :lundi 6 janvier 2020 18:58
À : openframeworks/openFrameworks<mailto:openFrameworks@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :[openframeworks/openFrameworks] ofOpenALSoundPlayer::play() in thread crashes (#6514)


ofOpenALSoundPlayer::play() calls glGetError() so if I run it in a thread, it crashes. Is there a reason this is there or can I make a pull request removing it?

**Comment by arturoc** [comment]
yes that's meant to be alGetError, can you send a PR?
