### ISSUE TITLE
make 4.3 breaks compilation

### ISSUE THREAD

**Issue by kflak** [openframeworks/openFrameworks#6535]
Every project that depends on addons with an `addon_config.mk` file will not compile with make 4.3.1 on Arch Linux. I am getting the error:
```
Compiling kinectExample for Release
make[1]: Entering directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
/home/kf/of_v20200208_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
make: *** [/home/kf/of_v20200208_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

```
Downgrading to make 4.2.1 solves the issue. The issue persists over all the versions of oF that I've tried: 0.11, nightly builds etc.

**Comment by arturoc** [comment]
This is now happening for msys2 as well which is failing the CI tests since it's using make 4.3 already

**Comment by arturoc** [comment]
related issue: https://github.com/openframeworks/openFrameworks/issues/5582

**Comment by gevhaz** [comment]
Same issue on Manjaro when trying to compile projectGenerator. Downgrading makes it possible to compile.
