### ISSUE TITLE
archlinux install_dependencies.sh missing ROOT variable

### ISSUE THREAD

**Issue by themancalledjakob** [openframeworks/openFrameworks#6542]
**Steps to reproduce:**
- run install_dependencies.sh

**Expected result:**
- it should install dependencies without relying on additional environment variables, which are not handled by the script.

**Actual result:**
- the script implies a `ROOT` variable to be present, containing the parent directory of the script itself. If this is not present, the script fails to update openCV, because it can't find the right addons directory.

terminal output:
```
Updating ofxOpenCV to use openCV4
sed: can't read /addons/ofxOpenCv/addon_config.mk: No such file or directory
sed: can't read /addons/ofxOpenCv/addon_config.mk: No such file or directory
```

**Potential fix:**
```
--- a/scripts/linux/archlinux/install_dependencies.sh
+++ b/scripts/linux/archlinux/install_dependencies.sh
@@ -18,8 +18,12 @@ if [ $exit_code != 0 ]; then
        exit $exit_code
 fi

+# get the root directory of this script
+ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+
 # Update addon_config.mk files to use OpenCV 3 or 4 depending on what's installed
 addons_dir="$(readlink -f "$ROOT/../../../addons")"
```

System details:
openFrameworks v0.11.0
5.4.18-1-MANJARO

**Comment by ImtiazKabir** [comment]
I am struggling with the same problem. I tried with the nightly builds too. But apparently it is still broken.
Can anyone help me with this problem? I am using manjaro

**Comment by themancalledjakob** [comment]
hey,

the issue is, that the script uses a "$ROOT" variable. This variable seems to be empty for me, and apparently for you as well.
you can either use the fix that I proposed above to create the variable, or just hardcode "addons_dir" in line 22 to the addons directory in your openFrameworks installation to fix it.
For example: 
`addons_dir = /absolute/path/to/openFrameworks/addons`
that should do it.

**Comment by ImtiazKabir** [comment]
Thank u so much! I changd the directory and it worked!

**Comment by themancalledjakob** [comment]
You can also put `ROOT=$(cd $(dirname $0); pwd -P)` somewhere above in the script.
In scripts for ubuntu, etc you'll find that line, they just forgot to put it in here (and also some other install scripts). It is basically just finding the directory in which the script is in.
If it's gonna be fixed ever, then that is how it'll be done.

But I just realized, if you don't want to change the file itself, you can also just do
```
$ cd path/to/openFrameworks/scripts/linux/archlinux
$ export ROOT=$(pwd)
$ sudo ./install_dependencies.sh
```
and all troubles shall be forgotten. This might be more elegant than changing the file, because then you might get issues when pulling updates from the openframeworks repository in the future.

Ah, I see just now your reply. Glad it worked for you, I'll keep these second comments just in case someone else stumbles over this. :)

**Comment by pierrep** [comment]
Thanks this worked for me too. Yes the ROOT variable is missing.
@arturoc any chance we could get this merged? Seems like a simple fix

**Comment by themancalledjakob** [comment]
i don't know. I tried a couple of times to add this as a pull request, but I might do something wrong here #6638 

The fix indeed is super simple :)

**Comment by Tomaqa** [comment]
I suppose it can be closed?
