### ISSUE TITLE
Emscripten: Webaudio crashes if heap resizes (solved)

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#6547]
I opened an issue on the Github page from Emscripten, because Webaudio is crashing when heap  resizes. Apparently it is more an issue with html5audio which is part of ofxEmscripten, so I post it here....
https://github.com/emscripten-core/emscripten/issues/10488

"Ah, then I'd guess this is a bug in

https://github.com/openframeworks/openFrameworks/blob/patch-release/addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js

in Open Frameworks. Specifically, it probably keeps a view alive to the old data. My guess is it's in html5audio_stream_create, where inbufferArray is captured once, then referred to from later callbacks, at which time it may be invalid. If that's it, the fix is to not create a subarray once and reuse it, but create one in each callback."

**Comment by Jonathhhan** [comment]
Thanks kripken, your guess fixed the issue.
I just put moved those two lines of code to the callback:
```
var inbufferArray = Module.HEAPF32.subarray(inbuffer>>2,(inbuffer>>2)+bufferSize*inputChannels);
		        var outbufferArray = Module.HEAPF32.subarray(outbuffer>>2,(outbuffer>>2)+bufferSize*outputChannels);
```


```
html5audio_stream_create: function(context_id, bufferSize, inputChannels, outputChannels, inbuffer, outbuffer, callback, userData){
		var stream = AUDIO.contexts[context_id].createScriptProcessor(bufferSize,inputChannels,outputChannels);
		var id = AUDIO.lastStreamID++;

		stream.onaudioprocess = function(event){
                        var inbufferArray = Module.HEAPF32.subarray(inbuffer>>2,(inbuffer>>2)+bufferSize*inputChannels);
		        var outbufferArray = Module.HEAPF32.subarray(outbuffer>>2,(outbuffer>>2)+bufferSize*outputChannels);
			var i,j,c;
			if(inputChannels>0){
				for(c=0;c<inputChannels;++c){
					var inChannel = event.inputBuffer.getChannelData(c);
					for(i=0,j=c;i<bufferSize;++i,j+=inputChannels){
						inbufferArray[j] = inChannel[i];
					}
				}
			}

			dynCall('viiii',callback, [bufferSize,inputChannels,outputChannels,userData]);

			if(outputChannels>0){
				for(c=0;c<outputChannels;++c){
					var outChannel = event.outputBuffer.getChannelData(c);
					for(i=0,j=c;i<bufferSize;++i,j+=outputChannels){
						outChannel[i] = outbufferArray[j];
					}
				}
			}
		};
```

**Comment by Jonathhhan** [comment]
It is not really solved. I can load long soundfiles without chrashing now, but the heap is growing with every loaded audio file. So I assume I also need to free/destroy the subarray at the end of each callback?

**Comment by kripken** [comment]
You shouldn't need to destroy the subarray, it will be garbage collected automatically (unless something holds on to it, but I don't see anything). Also, the subarray is allocated in JS memory, not the emscripten memory, so if the heap grows that's something else doing `malloc()` calls. Maybe that's normal when loading an audio file?

**Comment by Jonathhhan** [comment]
Thanks, that is good to know. So whether that is normal for loading audio files, or I made some mistakes in my embind interaction (which could easily be possible, because I am quite new to C++ and Java Script).

**Comment by Jonathhhan** [comment]
So I tested a bit, and it seems to work :) A thing that I do not really understand is that the heap grows until 2071724032 (or something like that, it was growing while loading the first 4 audio files) and after that I can replace audio file after audio it the heap size stays the same.

**Comment by kripken** [comment]
It could be a memory leak in the program somewhere. If so the sanitizers might help, https://emscripten.org/docs/debugging/Sanitizers.html#memory-leaks

**Comment by Jonathhhan** [comment]
I already use this flags: `ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=1GB -s ASSERTIONS=2 -s SAFE_HEAP=1 -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s DEMANGLE_SUPPORT=1`
Earlier I got an error message from `SAFE_HEAP=1` (alignment fault / segfault), but that is fixed.
When I try to use sanitizers with the additional flags `-g4 -fsanitize=address -s EXIT_RUNTIME` I get this error messages:
`shared:ERROR: Sanitizers are not compatible with the fastcomp backend. Please upgrade to the upstream wasm backend by following these instructions: https://v8.dev/blog/emscripten-llvm-wasm#testing`
I am not sure, but I think it makes sense how it works right now, because I copy a lua table (from Embind) into an Pure Data array. So at least for a short time they need to exist at once, and that could be the max needed memory amount.

**Comment by Jonathhhan** [comment]
Just wanted to mention that the issue is solved...
