### ISSUE TITLE
Raspberry PI - cannot install dependencies 

### ISSUE THREAD

**Issue by egotrip01** [openframeworks/openFrameworks#6550]
I can't install dependencies on raspbian, any idea?
libgles1-mesa-dev not available

**Comment by oxillo** [comment]
Can you provide more information about your Pi model and raspbian version ?

**Comment by egotrip01** [comment]
Actually I didn't even remember what I tryed to install... so much shame...
But n case it's helpfull for anyone, I'm on raspberry 4B
with raspbian 2.8.5
Thanks for answer

**Comment by Jewseephish** [comment]
I'm also having this issue on an rpi 4B while trying to instal ofxPiMapper. when trying to run the install_dependencies.sh script in ~/openFrameworks/scripts/linux/debian I get:

```
Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
Package libgles1-mesa-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libglvnd-dev

E: Package 'libgles1-mesa-dev' has no installation candidate
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

```

**Comment by dimitre** [comment]
@Jewseephish @egotrip01 now the latest raspberry pi os is supported on nightly builds.
Try again if you have time.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7069
