### ISSUE TITLE
Where do we stand with Vulkan?

### ISSUE THREAD

**Issue by kkirby** [openframeworks/openFrameworks#6554]
I’m wondering what the consensus on implementing Vulcan would be. Vulkan is supported on Linux. Android and Windows, and I found a [nifty open source library (MoltenVK)](https://github.com/KhronosGroup/MoltenVK) that can convert Vulkan to Metal for iOS and MacOS. This would easily bridge the gap and allow us to drop OpenGL entirely. Paving the way for a more standard OpenFrameworks.

I don’t really have the time right now to do any work on this, but I wanted to get the discussion rolling since I wasn’t able to find anything about Vulkan support in the issues here.

**Comment by ofTheo** [comment]
Hi @kkirby 

There are a couple of threads on the forum about it: 
https://forum.openframeworks.cc/t/vulkan-renderer/23800 

Also I've been toying with Dawn / WebGPU which wraps Vulkan, Metal, GL and DX. 
https://dawn.googlesource.com/dawn 

Probably good to continue this sort of discussion on the forum though. 
Feel free to follow up on the threads there or start a new discussion. 

Thanks!
Theo
