### ISSUE TITLE
Check video device capabilities issue in Linux

### ISSUE THREAD

**Issue by mchelifpv** [openframeworks/openFrameworks#6556]
Program crashed with segmentation fault, if I use ofVideoGrabber. OF wrong check capabilities from video devices.
Please replace one string in ofGstVideoGrabber.cpp
guint cap = v2cap.capabilities;
to
guint cap = v2cap.device_caps;

More info:
https://bugzilla.kernel.org/show_bug.cgi?id=199575

**Comment by ofTheo** [comment]
closed by #6688
