### ISSUE TITLE
getPixels is behaving funny

### ISSUE THREAD

**Issue by jucajuca** [openframeworks/openFrameworks#6561]
The following code is throwing an error. According to the documentation and also the source code this should work.

I call this:
bool ofPixels_::pasteInto(ofPixels_ &dst, size_t x, size_t y)

Using this:
ofPixels_ & ofImage_::getPixels()

Any ideas?

```
ofFloatImage ofApp::processImg(ofFloatImage img) {

  ofFloatImage processImg;
  int processImgW = 100;
  int processImgH = 100
  processImg.allocate( processImgW, processImgH, OF_IMAGE_COLOR);
  ofPixels tempPixels = img.getPixels();
  tempPixels.pasteInto(processImg.getPixels(), 0,0 );

  return processImg;

}
```

```
/mnt/FILES/CODE/OF/OF_100_64B_GCC6/apps/myApps/myApp/src/myApp.cpp: In member function ‘ofFloatImage ofApp::processImg(ofFloatImage)’:
/mnt/FILES/CODE/OF/OF_100_64B_GCC6/apps/myApps/myApp/src/myApp.cpp:276:44: error: cannot bind non-const lvalue reference of type ‘ofPixels_<unsigned char>&’ to an rvalue of type ‘ofPixels_<unsigned char>’
  276 |   tempPixels.pasteInto(processImg.getPixels(), 0,0 );

```

**Comment by 2bbb** [comment]
@jucajuca 

hi.
you need to change type of `tempPixles` from `ofPixels` to `ofFloatPixels`.

because,

* `processImg` is `ofFloatImage`
* `tempPixels` is `ofPixels`
* `processImag.getPixels()` returns `ofFloatPixels`
* `first argument of tempPixels.pasteInto` needs is `ofPixels`

so, implicitly conversion from `ofFloatPixels` to `ofPixels` is happen. and Implicitly conversion makes rvalue.

**Comment by jucajuca** [comment]
thanks! i did not know that there was ofFloatPixels. 
I adjusted the code but I got a core dumped error.  I then inserted this line:

`ofLogNotice() << typeid(processImg.getPixels()).name();`

and it returned "9ofPixels_IfE". I expected to see ofFloatPixels...

I don't know. for the moment I found a workaround but I thing there is an issue with the return value of ofPixels, especially when working with Float images.

```

ofFloatImage ofApp::processImg(ofFloatImage img) {

  ofFloatImage processImg;
  int processImgW = 100;
  int processImgH = 100
  processImg.allocate( processImgW, processImgH, OF_IMAGE_COLOR);
  ofFloatPixels tempPixels = img.getPixels();
  tempPixels.pasteInto(processImg.getPixels(), 0,0 );

  return processImg;

}
```

**Comment by 2bbb** [comment]
`9ofPixels_IfE` is correct result for `ofFloatPixels`.
because `typeid(processImg.getPixels()).name()` is not demangled. 

please try this code.

```cpp
#include "ofMain.h"
#include <cstdlib>
#include <memory>
#include <cxxabi.h>

std::string demangle(const char* name) {

    int status = -4; // some arbitrary value to eliminate the compiler warning

    // enable c++11 by passing the flag -std=c++11 to g++
    std::unique_ptr<char, void(*)(void*)> res {
        abi::__cxa_demangle(name, NULL, NULL, &status),
        std::free
    };

    return (status==0) ? res.get() : name ;
}

class ofApp : public ofBaseApp {
    ofFloatImage processImg(ofFloatImage img) const {
        ofFloatImage processImg;
        int processImgW = 100;
        int processImgH = 100;
        processImg.allocate(processImgW, processImgH, OF_IMAGE_COLOR);
        ofLogNotice() << demangle(typeid(processImg.getPixels()).name());
        ofFloatPixels tempPixels = img.getPixels();
        tempPixels.pasteInto(processImg.getPixels(), 0,0 );
        return processImg;
    }
public:
    inline virtual void draw() override {
        ofFloatImage image;
        image.load("https://avatars3.githubusercontent.com/u/24567185?s=120&v=4");
        auto processed = processImg(image);
        processed.draw(0, 0);
        image.draw(processed.getWidth(), 0);
    }
};

int main() {
    ofSetupOpenGL(1280, 720, OF_WINDOW);
    ofRunApp(new ofApp());

}
```

https://stackoverflow.com/questions/281818/unmangling-the-result-of-stdtype-infoname

(`ofFloatPixels` is alias of `ofPixels_<float>`)

but, sorry,  i didn't test on linux.
i tested on macOS. (and it works on macOS.)
