### ISSUE TITLE
Is it a bug that red and blue swap when using ofImage.grabscreen?

### ISSUE THREAD

**Issue by nakamuraprocess** [openframeworks/openFrameworks#6562]
Using of ofImage.grabscreen() the image is saved with R and B swapped with each other ver0.10 later.
Genius found a solution using ofPixels.swapRgb(), but is ofImage.grabScreen() swapping the correct behavior?

https://forum.openframeworks.cc/t/wrong-color-saved-when-using-ofimage-save-jpeg-after-using-ofimage-grabscreen-within-v0-10-0/30240

**Comment by oxillo** [comment]
duplicate with #6528 ?

**Comment by arturoc** [comment]
yes thanks!
