### ISSUE TITLE
ofNode::setOrientation() Euler Angles Issue

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#6589]
I think it would make sense if feeding the result of **ofNode::getOrientationEulerRad()** into **ofNode::setOrientation(const glm::vec3& eulerAngles)** resulted in an node orientated the same way. With the current implementation, that's not the case. It can be fixed by using the euler angles as a constructor to a **glm::quat** in **ofNode::setOrientation**. Can send a pull request if you want?

**Comment by 2bbb** [comment]
fyi:
it is caused by `glm::vec3` what `glm::eulerAngles(q);` returns is `zyx` on glm 0.9.9.
I fixed it from:

```cpp
void ofNode::setOrientation(const glm::vec3& eulerAngles) {
	setOrientation(glm::angleAxis(ofDegToRad(eulerAngles.x), glm::vec3(1, 0, 0)) * glm::angleAxis(ofDegToRad(eulerAngles.z), glm::vec3(0, 0, 1)) * glm::angleAxis(ofDegToRad(eulerAngles.y), glm::vec3(0, 1, 0)));
}
```

to

```cpp
void ofNode::setOrientation(const glm::vec3& eulerAngles) {
	setOrientation(glm::angleAxis(ofDegToRad(eulerAngles.z), glm::vec3(0, 0, 1)) * glm::angleAxis(ofDegToRad(eulerAngles.y), glm::vec3(0, 1, 0)) * glm::angleAxis(ofDegToRad(eulerAngles.x), glm::vec3(1, 0, 0)));
}
```

but neil's solution is better I think.

**Comment by ofTheo** [comment]
@neilmendoza this does sound like a bug. 

Though was this just due to the switch to glm? 
Does it seem that getOrientationEulerRad() is the correct result and if so is the issue just that we are setting the orientation assuming eulerAngles is xyz formatted? 

going to tag this for 0.11.1 happy if others want to chime in.

**Comment by ofTheo** [comment]
Okay dug into this a bit today and both of these solutions proposed above work:

```
void ofNode::setOrientation(const glm::vec3& eulerAngles) {
    auto eulerAnglesRad = glm::radians(eulerAngles);
    glm::quat q(eulerAnglesRad);
    setOrientation(q);
}
```

and 

```
void ofNode::setOrientation(const glm::vec3& eulerAngles) {
    setOrientation(glm::angleAxis(ofDegToRad(eulerAngles.z), glm::vec3(0, 0, 1)) * glm::angleAxis(ofDegToRad(eulerAngles.y), glm::vec3(0, 1, 0)) * glm::angleAxis(ofDegToRad(eulerAngles.x), glm::vec3(1, 0, 0)));
}
```

I think I will go with the first at @2bbb 's and @neilmendoza 's suggestion. 

Before making that change the test below would change the orientation of the node on every spacebar hit. Using the fixes above the orientation stays the same. 

```
ofEasyCam cam;
ofNode testNode;

//--------------------------------------------------------------
void ofApp::draw(){
    ofBackground(0);
    ofEnableDepthTest();
    
    cam.begin();
        ofSetColor(40);
        ofDrawBox(0, 0, 0, 60);
        ofSetColor(255, 255, 0);
        ofDrawLine(testNode.getPosition(), testNode.getPosition() + testNode.getLookAtDir() * 150.0);
    cam.end();
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
   if ( key ==  ' ' ) {
       auto orientEuler  = testNode.getOrientationEulerDeg();
       cout << endl << "TEST: euler is " << orientEuler << endl;
       testNode.setOrientation(orientEuler);
       cout << "NOW: euler is " << testNode.getOrientationEulerDeg() << endl;
   }
   if( key == 'm' ){
        glm::vec3 pt( ofRandom(-40, 40), ofRandom(-40, 40), ofRandom(-40, 40) );
        testNode.lookAt(pt);
   }
}
```
