### ISSUE TITLE
bad_function_call exception with handleRequestAsync

### ISSUE THREAD

**Issue by chriship** [openframeworks/openFrameworks#6591]
I seem to be getting the following error when I try to do async http calls. 

`Exception thrown at 0x00007FFD4150A799 in emptyExample_debug.exe: Microsoft C++ exception: std::bad_function_call at memory location 0x000000000014F580.`

It looks like it's caused inside `ofURLFileLoaderImpl::update()` with the line `response.request.done(response)`

```
void ofURLFileLoaderImpl::update(ofEventArgs & args){
	ofHttpResponse response;
	while(responses.tryReceive(response)){
		try{
			response.request.done(response); // <---- this is the line causing the exception
		}catch(...){

		}

		ofNotifyEvent(ofURLResponseEvent(),response);
	}
}
```

The error is handled by the try catch but it's a bit disconcerting. I have no idea what that response.request.done line is doing, it doesn't seem to affect anything if I comment it out (apart from stopping the exception).

Code to replicate here:
```
ofURLFileLoader http;

void ofApp::setup(){
	ofRegisterURLNotification(this);
}

void ofApp::urlResponse(ofHttpResponse& response) {

	if (response.status == -1)return;

	if (response.status == 200) {
		if (response.request.name == "test") {
			string data = response.data.getText();
			cout << data << endl;
		}
	}
}

void ofApp::keyPressed(int key){
	ofHttpRequest request;
	request.method = ofHttpRequest::GET;
	request.url = "https://jsonplaceholder.typicode.com/users";
	request.name = "test";

	http.handleRequestAsync(request);
}
```

**Comment by quadbyte** [comment]
response.request.done seems to be a callback which can be used once the download is completed.
The problem is the code is calling this callback even when it is not set, which cause the disconcerting error in the logs.

I fixed it by simply checking if the callback is set before calling it : 
```
			if (response.request.done) {
				response.request.done(response);
			}
```

**Comment by chriship** [comment]
Ah well done!
