### ISSUE TITLE
bug with making contours from fonts 

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#6592]
one of my students was experimenting with this font and this code

https://www.dropbox.com/s/p02qyulbud26fqb/lato.ttf?dl=0
https://github.com/ofZach/RTP_SFPC_SUMMER20/tree/master/typeExample3

and found that the parsing looks a little weird, some screenshots when you zoom in

<img width="429" alt="Screen Shot 2020-06-07 at 7 04 09 AM" src="https://user-images.githubusercontent.com/142897/83967222-86952d80-a88d-11ea-9a4d-d21a698fa32c.png">
<img width="517" alt="Screen Shot 2020-06-07 at 7 04 01 AM" src="https://user-images.githubusercontent.com/142897/83967223-872dc400-a88d-11ea-8fce-d747441ca70b.png">

it seems that when you change the makeContoursForCharacter and make all the 64 to **64.0** instead it fixes things, so perhaps it's just a resolution issue?

<img width="398" alt="Screen Shot 2020-06-07 at 7 04 43 AM" src="https://user-images.githubusercontent.com/142897/83967232-9e6cb180-a88d-11ea-97dd-52f5575fd814.png">
<img width="455" alt="Screen Shot 2020-06-07 at 7 04 37 AM" src="https://user-images.githubusercontent.com/142897/83967233-9e6cb180-a88d-11ea-97d5-1b8375e2402a.png">

happy to submit a PR just wanted to mention it as an issue in case anyone has ideas.

**Comment by dimitre** [comment]
I think this is related to the fact assumes as a default parameter for simplifyAmt the value of 0.3
so maybe every loaded font is simplified?

**Comment by dimitre** [comment]
I've checked out the code and confirm simplifyAmt = 0.0 fixes this
This PR closes this issue
https://github.com/openframeworks/openFrameworks/pull/7065


![Screen Shot 2022-09-27 at 21 05 26](https://user-images.githubusercontent.com/58289/192658512-50c8fbdf-b998-42a0-92b9-69c4445f602c.png)

**Comment by ofTheo** [comment]
closed by #7065
