### ISSUE TITLE
Openframeworks (20200808) libraw-20.dll dependency issue

### ISSUE THREAD

**Issue by chosamuel** [openframeworks/openFrameworks#6609]
Hello all!

I'm trying to build the OF mingw 64 nightly build 20200808. The installation of the dependencies as well as the libraries went smoothly. However, when I tried to compile an example (I compiled the graphics example), it gave an error, saying that libraw-19.dll was not found. 

After checking which dlls I have in the folder, I notice that I have libraw-20.dll.

**Comment by chosamuel** [comment]
Hi! I tried today's nightly build and got the same result. Installing the dependencies automatically installed libraw-20 when OF currently depends on libraw-19.

I suddenly realized I could downgrade a package in MSYS2 and...did just that. After downgrading libraw-20 to libraw-19 (and recopying the dlls), OF works.

**Comment by tgfrerer** [comment]
great find! perhaps related to #6605

**Comment by chosamuel** [comment]
Hi! Yes, I had the same error throwing in MINGW and it didn't show which library was missing. Clicking on the .exe though showed the correct error.

**Comment by oxillo** [comment]
The faulty library was freeimage that was relying on libraw -19. The package has been updated since.
@arturoc : This issue can be closed.

**Comment by arturoc** [comment]
Thanks!
