### ISSUE TITLE
setDoubleBuffering(false) causes no output (black screen)

### ISSUE THREAD

**Issue by liasomething** [openframeworks/openFrameworks#6612]
to reproduce:
1) open ofBoxExample
2) in main.cpp replace
`ofSetupOpenGL(1024,768, OF_WINDOW); `
with 
```
ofAppGLFWWindow window;
window.setDoubleBuffering(false);
ofSetupOpenGL(&window, 1024,768, OF_WINDOW);
```
3) compile and run

expected result: boxes on screen
actual result: black screen

of0.11, osX catalina 10.15.6

I downloaded master, but could not figure out how to make a project, as the project generator is missing.

**Comment by ofTheo** [comment]
Hi @liasomething ! 

From what I remember single buffering doesn't work on all platforms or graphics cards. 
Are you trying to accumulate the screen buffer or is there a reason you want to disable double buffering? 

If you want to accumulate the screen buffer you can do this in ofApp::setup()
```
    ofBackground(0, 0, 0);
    ofSetBackgroundAuto(false);
```

If that solves your issue feel free to close it. 
If not it would be helpful to know more about what you are trying to achieve.  

Cheers!
Theo

**Comment by liasomething** [comment]
Hi Theo,

I need to turn off double buffering, because at some point in my app I stop rendering (to deliberately pause the app) and with double buffering turned on and `ofSetBackgroundAuto(false)` the screen flickers between the last two frames rendered. Rendering into an fbo would solve my problem, but I assumed that if OF had a function called `setDoubleBuffering()` and I called it with `false` and did not get any error message, it would disable double buffering, silly me ! ;)

all the best
Lia.-

**Comment by ofZach** [comment]
it sounds like it should :).  just a quick note that I see this line ifdef'd out for OS X 

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L178-L180

I'm not 100% why but maybe worth investigating if that's why it doesn't work properly on osx.

**Comment by liasomething** [comment]
Hi Zack,
thanks ! 
so, commenting out the `ifndef` did not help, but adding a hint for `GLFW_DOUBLEBUFFER` did:
```
// #ifndef TARGET_OSX
    //glfwWindowHint(GLFW_AUX_BUFFERS, settings.doubleBuffering ? 1 : 0 );
    glfwWindowHint(GLFW_DOUBLEBUFFER, settings.doubleBuffering ? GL_TRUE : GL_FALSE );
// #endif
```
i haven't tested this anywhere else, but it works for me.

all the best
Lia.-
