### ISSUE TITLE
wget is not available by default on macOS/OSX

### ISSUE THREAD

**Issue by rnkn** [openframeworks/openFrameworks#6616]
Hello!

Your `scripts/osx/download_libs.sh` script uses wget, but wget is not available on OSX by default. (It's actually a dirty Linuxism.)

Use curl instead for greater compatibility with Unix systems.

**Comment by danoli3** [comment]
PR already in place for this. Will look into and finishing that this week
https://github.com/openframeworks/openFrameworks/pull/5848

**Comment by rnkn** [comment]
I saw that. It's weird. Usually it would go like...
"You're using wget. You should use curl."
"Oh okay."
And they all lived happily ever after.

**Comment by danoli3** [comment]
Fixed on master
