### ISSUE TITLE
patch-release vs master

### ISSUE THREAD

**Issue by prisonerjohn** [openframeworks/openFrameworks#6618]
Not really an issue, but can someone explain the rationale of `patch-release` vs `master`? Which should we use for PRs? Thanks!

**Comment by eduardfrigola** [comment]
Hi Elie!
I had the same doubt, I found this comment from @arturoc https://github.com/openframeworks/openFrameworks/issues/6483#issuecomment-562044487

Seems clear what the difference is, but then sometimes is tricky to tell if something is a fix, or a new feature, for example [this PR](https://github.com/openframeworks/openFrameworks/pull/6614) that adds a new feature, that it’s intention is to fix a rare [bug](https://github.com/openframeworks/openFrameworks/issues/6576)...

Eduard

**Comment by arturoc** [comment]
when we do a major release like 0.11 there's usually several small bugs that need fixing so we create a patch-release version for that. any change that is only minor bug fixes should go to patch-release and will be in the next minor versions (like 0.11.1) once some time has passed we usually remove patch-release and merge everything to master and anything that adds new functionality or changes the public api should always go into master

**Comment by prisonerjohn** [comment]
Thanks for clarifying
