### ISSUE TITLE
ofImage close() doesn't close

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6621]
Apologies if I don't understand the real usage of ofImage::close() but it seems it is not working.
if I use clear() the ofImage object still draws and still returns isAllocated()
the only way of deallocating it is making another uninitalized ofImage object and assigning to the other
like:
```c++
ofImage imageUnallocated;
image = imageUnallocated;
```
Am I missing something? Thank you

platform : macOS 10.14
ofw from git, head master

**Comment by jivido** [comment]
Hi,
Do you mean `clear()` in the title of this issue? `ofImage::close() `doesn't seem to exist. 
And I can't replicate it on macOS 10.15.7, of_v20201026_osx_release. Everything works as expected. 
```
ofImage img;

//--------------------------------------------------------------
void ofApp::setup(){
    ofBackground(255);
    img.load("test.jpg");
}
//--------------------------------------------------------------
void ofApp::update(){
    cout << img.isAllocated() << endl;
}
//--------------------------------------------------------------
void ofApp::draw(){
    ofBackground(0);
    img.draw(0, 0);
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
    if(key == 'c')
        img.clear();
}
```
The drawing stops when I press c, and `img.isAllocated()` returns 0 instead of 1.
The memory usage shown in XCode also drops after I press c.

**Comment by dimitre** [comment]
Thank you @jivido indeed it is working as expected. 
Not sure what exactly happened for me to open this so I'm closing now
Maybe I was mistaking ofVideoPlayer::close() with ofImage::clear() 
cheers!
