### ISSUE TITLE
OF_ROOT does not exist

### ISSUE THREAD

**Issue by ImtiazKabir** [openframeworks/openFrameworks#6631]
Hey,
I recently downloaded OF and installed the dependencies. Then I compiled OF. There was no problem so far.
When I tried to compile polygon example, it said
`Makefile:13: /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory
make: *** No rule to make target '/home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.`
I noticed that the variable `OF_ROOT` in the makefile, does not exist. So where did the project Makefile go?!
Also, `projectGenerator` is not recognised as a command. So I must have missed something.
I previously used OF in Ubuntu 18.04 and didnt face any problem.
I am currently using arch linux (manjaro)

**Comment by ofTheo** [comment]
Hi - I think this is the same issue as #6650 and is fixed in latest master/patch-release. 
Can you try the nightly builds at the bottom of the download page and see if this is still an issue?  
https://openframeworks.cc/download/

**Comment by themancalledjakob** [comment]
Hey Theo,

I think what you reference to is the OF_ROOT in the make system.
These scripts are run independently in bash, just as a script. Therefore the OF_ROOT variable is missing if it not set in the very same script.
Afaik this is not fixed yet.
