### ISSUE TITLE
macOS Bigsur Error when Linking file for osx 

### ISSUE THREAD

**Issue by junjzhang** [openframeworks/openFrameworks#6633]
System Info
macos 11.0.1
of.0.11.0

Error info
Linking bin/mySketch_debug for osx
c++ -o bin/mySketch_debug  obj/osx/Debug/src/ofApp.o obj/osx/Debug/src/main.o  /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvColorImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvShortImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvContourFinder.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvHaarFinder.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvFloatImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvGrayscaleImage.o  /Users/zhangjunjie/OF/libs/openFrameworksCompiled/lib/osx/libopenFrameworksDebug.a  /Users/zhangjunjie/OF/addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a  -stdlib=libc++ -mmacosx-version-min=10.9 -v -framework Accelerate -framework QTKit -framework AGL -framework ApplicationServices -framework AudioToolbox -framework CoreAudio -framework CoreFoundation -framework CoreServices -framework OpenGL -framework IOKit -framework Cocoa -framework CoreVideo -framework AVFoundation -framework CoreMedia -framework QuartzCore -framework Security -framework LDAP /Users/zhangjunjie/OF/libs/FreeImage/lib/osx/freeimage.a /Users/zhangjunjie/OF/libs/boost/lib/osx/boost_system.a /Users/zhangjunjie/OF/libs/boost/lib/osx/boost_filesystem.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/cairo-script-interpreter.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/cairo.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/png.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/pixman-1.a /Users/zhangjunjie/OF/libs/curl/lib/osx/curl.a /Users/zhangjunjie/OF/libs/freetype/lib/osx/freetype.a /Users/zhangjunjie/OF/libs/glew/lib/osx/glew.a /Users/zhangjunjie/OF/libs/glfw/lib/osx/glfw3.a /Users/zhangjunjie/OF/libs/pugixml/lib/osx/pugixml.a /Users/zhangjunjie/OF/libs/rtAudio/lib/osx/rtaudio.a /Users/zhangjunjie/OF/libs/tess2/lib/osx/tess2.a /Users/zhangjunjie/OF/libs/uriparser/lib/osx/uriparser.a  /Users/zhangjunjie/OF/libs/fmodex/lib/osx/libfmodex.dylib  -lobjc
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.9.0 11.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o bin/mySketch_debug -L/usr/local/lib obj/osx/Debug/src/ofApp.o obj/osx/Debug/src/main.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvColorImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvShortImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvContourFinder.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvHaarFinder.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvFloatImage.o /Users/zhangjunjie/OF/addons/obj/osx/Debug/ofxOpenCv/src/ofxCvGrayscaleImage.o /Users/zhangjunjie/OF/libs/openFrameworksCompiled/lib/osx/libopenFrameworksDebug.a /Users/zhangjunjie/OF/addons/ofxOpenCv/libs/opencv/lib/osx/opencv.a -framework Accelerate -framework QTKit -framework AGL -framework ApplicationServices -framework AudioToolbox -framework CoreAudio -framework CoreFoundation -framework CoreServices -framework OpenGL -framework IOKit -framework Cocoa -framework CoreVideo -framework AVFoundation -framework CoreMedia -framework QuartzCore -framework Security -framework LDAP /Users/zhangjunjie/OF/libs/FreeImage/lib/osx/freeimage.a /Users/zhangjunjie/OF/libs/boost/lib/osx/boost_system.a /Users/zhangjunjie/OF/libs/boost/lib/osx/boost_filesystem.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/cairo-script-interpreter.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/cairo.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/png.a /Users/zhangjunjie/OF/libs/cairo/lib/osx/pixman-1.a /Users/zhangjunjie/OF/libs/curl/lib/osx/curl.a /Users/zhangjunjie/OF/libs/freetype/lib/osx/freetype.a /Users/zhangjunjie/OF/libs/glew/lib/osx/glew.a /Users/zhangjunjie/OF/libs/glfw/lib/osx/glfw3.a /Users/zhangjunjie/OF/libs/pugixml/lib/osx/pugixml.a /Users/zhangjunjie/OF/libs/rtAudio/lib/osx/rtaudio.a /Users/zhangjunjie/OF/libs/tess2/lib/osx/tess2.a /Users/zhangjunjie/OF/libs/uriparser/lib/osx/uriparser.a /Users/zhangjunjie/OF/libs/fmodex/lib/osx/libfmodex.dylib -lobjc -lc++ -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.osx.a
ld: file not found: /usr/lib/libstdc++.6.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/mySketch_debug] Error 1
make[1]: *** [Debug] Error 2
make: *** [all] Error 2

**Comment by ofZach** [comment]
here's a fix -> https://forum.openframeworks.cc/t/building-in-macos-11-0-big-sur/36581/5

**Comment by junjzhang** [comment]
> here's a fix -> https://forum.openframeworks.cc/t/building-in-macos-11-0-big-sur/36581/5

Thx! It works if I build from Xcode. But there are still problems when I build from the command line. Is there any rules to fix it?

**Comment by msf567** [comment]
I also need a fix when building from the makefiles on osx big sur, the makefiles themselves dont have anywhere to edit the run script line like the fix sugests. the makefile [here](https://gist.github.com/labe-me/1190981/c177d6cdb0ce1e625c8fad23c2815a47efe4ee35) does however, but simply changing that line does not fix the issue.

**Comment by ofTheo** [comment]
I think this is fixed now in master/patch-release and nightly builds.
Including the makefiles. Could you give it a try from the nightly builds and let me know if you still have issues? 
https://openframeworks.cc/ci_server/versions/nightly/of_v20210113_osx_nightly.zip 

If there are still issues we can re-open. 

Thanks!
Theo

**Comment by suyashjoshi** [comment]
We need to re-open this issue as it's not fixed. I ran into the same error today on my Intel MBP running mac OS Big Sur.

`File not found: /usr/lib/libstdc++.6.dylib for architecture x86_64`

I download the official open frameworks from https://openframeworks.cc and tried to follow instructions to setup from https://openframeworks.cc/setup/xcode/ which didn't work.
