### ISSUE TITLE
Opencv4 compatibility issues -Ubuntu 20.04

### ISSUE THREAD

**Issue by rossanag** [openframeworks/openFrameworks#6637]
Hi everyone, i am stucked trying to compile the opencv example. I upgraded to Ubuntu 20.04 from 19.10 (it wasnt a fresh install), and since then anything related to opencv stop to compile. I was searching in here, but I didnt find something similar.
I did a fresh install of oF, even the nightly build, and both of them adviced me that opencv was updated to use opencv4.

This is the error that appears in both oF flavors:

```
from /home/rossana/of11/apps/myApps/slicedVideoMus/src/main.cpp:2:
/usr/include/opencv4/opencv2/dnn/dnn.hpp:47:10: fatal error: opencv2/core/async.hpp: No existe el archivo o el directorio
   47 | #include "opencv2/core/async.hpp"

```
It doesn't find the _async.hpp_ file, and me either. 

Maybe I have to reinstall opencv? I appreciate any suggestions to solve this, thanks!
Ubuntu 20.04 (64 bits)
oF 11
gcc 9.3.0

Ro

**Comment by rossanag** [comment]
I have solved this issue by modifying the config.addon.mk file of the ofxOpencv addon, I added the following lines:
(Not sure if it is an elegant workaround, but it worked. Any improvement is more than welcome)

```
linux64:
	ADDON_LIBS = /usr/lib/x86_64-linux-gnu/libopencv_core.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_objdetect.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_imgproc.a	
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_calib3d.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_videoio.a		
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_dnn.a	
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_features2d.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_highgui.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_flann.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_photo.a	
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_stitching.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_video.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libopencv_ml.a			
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libquirc.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/libittnotify.a
	ADDON_LIBS += /usr/lib/x86_64-linux-gnu/liblibprotobuf.a
```

**Comment by ofTheo** [comment]
Hi @rossanag 
I just tried the nightly builds ( bottom of https://openframeworks.cc/download/ ) with a fresh 20.04 Ubuntu install and both the allAddonsExample and openCv example all compiled fine with no issues. 

Could you try the nightly build and reopen the issue if it is still a problem?

**Comment by rossanag** [comment]
@ofTheo thanks for your response, I had to do Ubuntu updates, after that I reinstalled the nightly builds and the "official" verson and both worked. It wasnt necessary to modify addons.mk file. I guess the issue it was causes by the lack of the updates.
I am going to close the thread.
