### ISSUE TITLE
Vertical window resize affect content scale on Mac

### ISSUE THREAD

**Issue by TarGz** [openframeworks/openFrameworks#6646]
I came across a strange behavior while resizing a window on Mac, this only applies to vertical window resizing not horizontal resizing. 

Example : 

I just took the default project from the generator and added this :
```
void ofApp::draw(){
    camera.begin();
    camera.setPosition(0, 0, 1000);
    ofDrawGrid(100,50,true,false,false,true);
    camera.end();
}
```
View of the app rigth after the start 
![image](https://user-images.githubusercontent.com/4320/103404610-84116280-4b54-11eb-8854-f3f11411c172.png)

After a horizontal resize the grid in unchanged the size of the square are the same
![image](https://user-images.githubusercontent.com/4320/103404619-8bd10700-4b54-11eb-9284-db3721bcf6f5.png)

After a vertical resize the grid is scaled down the square are smaller  : 
![image](https://user-images.githubusercontent.com/4320/103404655-b4590100-4b54-11eb-8ffc-b2b55c64f3e3.png)

I've tried to log change to the camera location, scale or FOV, etc but didn't found any changes... all properties are consistent so I wonder if the issue might not be due to the camera.. maybe this is not a bug and I'm missing something? any advice very welcome.

OS: Catalina 10.15.7
Of: 0.11.0

**Comment by griv** [comment]
Just had a play, it appears to be the perspective camera FOV, which is linked to the window height. The FOV doesn't change so as you change the window height the camera adjusts to that new window size.
You can use an orthographic camera if you don't want this behaviour.
`camera.enableOrtho();` keeps the grid consistent across resizes.

**Comment by TarGz** [comment]
> Just had a play, it appears to be the perspective camera FOV, which is linked to the window height. The FOV doesn't change so as you change the window height the camera adjusts to that new window size.
> You can use an orthographic camera if you don't want this behaviour.
> `camera.enableOrtho();` keeps the grid consistent across resizes.

Hey thanks for your answer, I think you’re right I though the same but I didn’t found any properties from the camera that are changing. I logged camera properties before and after the scale and everything were consistent that why I tough it’s a bug.

**Comment by ofTheo** [comment]
yup! as described this is an intended feature. 
If you don't want the camera to set it's distance automatically you can call ofEasyCam::setAutoDistance(); to false. 

I hope that helps!
