### ISSUE TITLE
ofCamera's screenToWorld is inaccurate when using a rotated orthographic camera.

### ISSUE THREAD

**Issue by davidspry** [openframeworks/openFrameworks#6658]
CC: @roymacdonald

When using a rotated, orthographic `ofCamera`, the `screenToWorld` function returns a slightly inaccurate result.

The result is accurate in the centre of the viewport but it becomes less accurate as the mouse cursor moves away from the centre in the vertical direction.

The issue can be reproduced using the following steps:

1. Add `ofCamera camera` to the sketch.
2. Add `glm::vec2 xy` to the sketch.
3. Enable orthographic projection and rotate the camera in the following way.

```cpp
void ofApp::setup()
{
  camera.enableOrtho();
  camera.setFarClip (+10000.0f);
  camera.setNearClip(-10000.0f);
  
  const float theta = static_cast<float>(std::asin(1.0 / std::sqrt(3.0)));
  camera.rotateRad(theta, 1.0f, 0.0f, 0.0f);
  camera.rotateDeg(45.0f, 0.0f, 0.0f, 1.0f);

  ofSetRectMode(OF_RECTMODE_CENTER);
  ofNoFill();
}
```
4. Capture all mouse presses in a `glm::vec2`.
```cpp
void ofApp::mouseDragged(int x, int y, int button)
{
  const glm::vec3 cursor (x, y, 0.0f);
  xy = camera.screenToWorld(mouse);
}
```
5. Draw a rectangle in the centre of the viewport, and draw the captured mouse position as a circle.
```cpp
void ofApp::draw()
{
  camera.begin();
  ofDrawRectangle(0, 0, 500, 500);
  ofDrawCircle(xy, 5);
  camera.end()
}
```

The sketch should look like this:

![openFrameworks sketch](https://user-images.githubusercontent.com/45588554/104083225-13272480-5291-11eb-9ba1-5b2a35311c50.png)

On my machine, I cannot trace the sides of the rectangle with the mouse. The `screenToWorld` transformation is accurate in the centre of the screen but not in the upper half or the lower half.

I've recorded a short video demonstrating the issue, albeit with a different sketch: https://www.youtube.com/watch?v=kU5oWhE9XeE

I'm using OF version 11.

**Comment by roymacdonald** [comment]
Hi, there is a tiny problem in your code which induces the error. you must use a vec3 to store the results of screenToWorld, as world coordinates are 3d. The logic is that for instance your camera is looking "sideways" or along the worlds x axis, in such case the values of x wont matter so much while z and y will actually be the coordinates that you will se translated to your screen's x and y.
Please close this issue.

**Comment by davidspry** [comment]
Thanks for your help!
