### ISSUE TITLE
MSYS2 : videoInput warning at every compilation

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#6671]
Following warning is displayed at every 'application' compilation
```
C:/N/open Frameworks/libs/videoInput/include/videoInput.h:190:12: warning: 'comInitCount' defined but not used [-Wunused-variable]
  190 | static int comInitCount = 0;
```

**Comment by ofTheo** [comment]
Ahh - I think this could be moved to the top of the .cpp 
https://github.com/ofTheo/videoInput/blob/master/videoInputSrcAndDemos/libs/videoInput/videoInput.h#L190 

That would probably fix the warning. 
I feel like it was in the header file for a reason - but it has been so long at this point :) 

Just incase I will fix it in a  branch and change apothecary to use that branch.
