### ISSUE TITLE
Fullscreen on startup broken on M1 / Apple Silicon 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6685]
See: https://forum.openframeworks.cc/t/of-fullscreen-causing-crash-with-validaterenderpassdescriptor/37220/16

Starting in fullscreen on Apple Silicon machines causes a crash on this line: 
https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L445

With an error message like this:
`Display resolution 1440,900: validateRenderPassDescriptor:885: failed assertion renderTargetHeight (1800) must be <= minimum attachment height (1694).` 

I can reproduce this. 
A hacky fix which lets the app start in fullscreen is to set the window shape to be smaller than the fullscreen dimensions before the window is shown. ( The fullscreen code handles putting it to the right size fine ). 

So changing this line: 
https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L255

from: 
`setWindowShape(settings.getWidth(), settings.getHeight());`

to: 
`setWindowShape(settings.getWidth()/2, settings.getHeight()/2);`

Will work on a better fix though. 
Note: tested latest glfw master and the error is there. This might be a glfw error or a Apple Silicon error, that is only revealed by the unique way we initialize the window when in fullscreen mode.

**Comment by danoli3** [comment]
You should definitely write this up for GLFW and report there as well

**Comment by ofTheo** [comment]
@danoli3 yeah. good point. I'll try and get a minimal reproducible example working, to submit, 
right now our window system setup is pretty complex and I want to make sure the bug exists with a basic example too.
