### ISSUE TITLE
unwanted command line args passed to the app from xcode

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/openFrameworks#6687]
Heyho,
xcode passes some commandline args to the app.

```
int main(int argc, char *argv[])
{
    ofLogNotice() << "argc: " << argc;
    for(int i = 0; i < argc; ++i)
        cout << argv[i] << '\n';
}
```
```
[notice ] argc: 3
/Users/thomas.geissl/libs/of_v0.11.0_osx_release/apps/ixds/approccio/bin/approccioDebug.app/Contents/MacOS/approccioDebug
-NSDocumentRevisionsDebugMode
YES
```

how are the project files generated, is it based on a template that can easily be replaced?

It can be fixed by unchecking
xcode/product/scheme/edit scheme/Run/Options/Allow debugging when browsing versions

https://forum.openframeworks.cc/t/automatically-added-command-line-args-in-xcode/35479

I am using: Version 12.2 (12B45b)

Thomas

**Comment by ofTheo** [comment]
Actually is pretty easy I think. 
Just change all instances of this to NO:
https://github.com/openframeworks/openFrameworks/blob/patch-release/scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample%20Release.xcscheme#L49

In these three files:
https://github.com/openframeworks/openFrameworks/tree/patch-release/scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes

**Comment by ofTheo** [comment]
Actually is pretty easy I think. 
Just change all instances of this to NO:
https://github.com/openframeworks/openFrameworks/blob/patch-release/scripts/templates/osx/emptyExample.xcodeproj/xcshareddata/xcschemes/emptyExample%20Release.xcscheme#L49

**Comment by thomasgeissl** [comment]
thanks theo. do you want me to send a pr against master or patch-release?

**Comment by ofTheo** [comment]
I think Patch Release. 
That will be 0.11.1 Thanks @thomasgeissl !
