### ISSUE TITLE
Missing libs for 0.11.1; download_libs.sh not working

### ISSUE THREAD

**Issue by bensnell** [openframeworks/openFrameworks#6706]
The script at `scrips/dev/download_libs.sh` does not download libraries for the new version `0.11.1`. This is because the libraries for `0.11.1` are missing from [http://ci.openframeworks.cc/libs/0.11.1](http://ci.openframeworks.cc/libs/0.11.1). 

Could you upload the newest libs to that location? Thank you!

**Comment by ofTheo** [comment]
Hi! 
Thanks for this. Do you think you could check and see if it works for you now?

**Comment by bensnell** [comment]
Perfection! All is working well now. Thanks so much :)
