### ISSUE TITLE
ofDrawCircle alignment issue

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6707]
I've just noticed, after updating ofw to latest master branch, that ofCircle seems to be unaligned. 
It seems like it is has a Z axis in relation to other objects.
I've noticed too the issue is not there when using cairo renderer.

```c++
	for (int x=0; x<800; x+=40) {
		for (int y=0; y<600; y+=40) {
			ofPushMatrix();
			ofTranslate(x,y);
			ofDrawLine(-16, 0, 16, 0);
			ofDrawLine(0, -16, 0, 16);
			ofDrawCircle(0, 0, 12, 12);
			ofDrawRectangle(-6,-6,12,12);
			ofPopMatrix();
		}
	}
```
![Screen Shot 2021-03-08 at 20 05 13](https://user-images.githubusercontent.com/58289/110393631-a8ecef00-8049-11eb-8412-0c1a7593a301.png)

**Comment by ofZach** [comment]
can you try 

ofDrawCircle(0, 0, 12);

I think you are adding a z value of 12 with the other call

**Comment by dimitre** [comment]
Thank you @ofZach closing here
