### ISSUE TITLE
ofCairoRenderer stops working after setting ofScale(0, 0);

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6715]
I've noticed ofCairoRenderer stops working after setting ofScale(0, 0)
Maybe there is some destructive scale happening there. easy to reproduce.
Thanks

**Comment by arturoc** [comment]
I imagine what you mean is that it doesn't work afterwards even changing back the scale? It might be introducing some NaNs and never recover from it

**Comment by dimitre** [comment]
@arturoc yes this is what I mean.

**Comment by dimitre** [comment]
ok, almost there to close this one. I've discovered the ofScale uses the actual matrix as it was 100%.
so if you for example calls this every frame the circle shrinks
```c++
	ofScale(0.5, 0.5);
	ofDrawCircle(100,100,100);

```

**Comment by dimitre** [comment]
one possible solution is adding some lines to setupGraphicsDefaults, so it resets the matrix in new frames.
But only if we start using cairo with the second optional parameter = true
```c++
ofSetCurrentRenderer(cairo, true);
```

```c++
//----------------------------------------------------------
void ofCairoRenderer::setupGraphicDefaults(){
	setStyle(ofStyle());
	path.setMode(ofPath::COMMANDS);
	path.setUseShapeColor(false);
	clear();
	
// new lines
	cairo_matrix_t matrix;
	cairo_matrix_init_scale(&matrix, 1.0, 1.0);
	cairo_matrix_init_translate(&matrix, 0.0, 0.0);
	cairo_set_matrix(cr,&matrix);
};
```

**Comment by dimitre** [comment]
Closed by https://github.com/openframeworks/openFrameworks/pull/6991
