### ISSUE TITLE
Feature Request : VS2019 official support

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#6724]
VS2019 is out for some years now. 
Shouldn't we offer VS2019 out of the box.
Of course, we keep VS2017 (as default for next version, as secondary for the version after)

Can we target of 0.12.0 for this support ?

**Comment by danoli3** [comment]
Should happen soon agreed, just need to build libraries against it and
update templates. All for making it the default for 0.12.0.

VS2019 is default for most other frameworks engines, unreal/unity
integrations

**Comment by ofTheo** [comment]
I think the current project files do [build with VS2019](https://forum.openframeworks.cc/t/neither-i-can-download-a-visual-studio-plugin-nor-can-i-use-the-projectgenerator-exe-tool/37422/4). 
However it would be fairly easy to add a GitHub actions config to build on VS2019. 

I'll check out 0.11.2 on VS 2019 to see how it runs and then we could start recommending 2019 in the docs. 
Targeting 2019 for 0.12.0 makes sense too.

**Comment by ofTheo** [comment]
Just tested with VS 2019 and 0.11.2 

Aside from a popup when opening a project asking to retarget OF and the Project files to 142. 
Everything builds and runs fine on VS 2019.  ( Starting with VS 2017 and onwards binaries are compatible across major updates ). 

For compatibility then it probably makes sense to keep apothecary on VS 2017. 
We could move the project files though to default to 2019 for 0.12.0 and could start updating the site with info for installing VS 2019 ( like we do for VS 2017 ).

**Comment by elliotwoods** [comment]
I'm here on VS2019. I actually keep oF itself as a VS2017 project and set everything else to VS2019
Which works fine

**Comment by ofTheo** [comment]
Going to close this as OF does work with 2019 and 2022. 
I think we could update the installation instructions on the website for 2019 or 2022 but apart from that it is nice to have the flexibility to use older IDEs.

**Comment by paul-ferragut** [comment]
Examples are currently not building with Visual Studio Community 2019, for me and few others in my course. I wasn't able to find out why.
Everything is working with Visual Studio Community 2022, following a 'retarget' 'upgrade to v143'
Everything is working without any retarget with Visual Studio community 2017 but this one is not available to download anymore from Microsoft.
Would it be possible and make sense to directly switch to vs2022 for 0.12.0?
Then with the project generator to have vs 2022 as default platform

**Comment by ofTheo** [comment]
@paul-ferragut - can you share the error messages issues you are getting? 
We have been using VS2019 for our projects both with 0.11.2 and the nightly builds. 

One tip: if you are using addons switching between Debug and Release requires a Clean. This is only true with 0.11.2 and not the nightly builds ( bottom of download page ).

**Comment by ofTheo** [comment]
Going to reopen anyway as we should target VS 2019 or 2022 for the nightly and next release.

**Comment by paul-ferragut** [comment]
thank you for your reply, I tried again with a new openFrameworks download, then now visual studio 2019 is working :)

I think my problem is that I had already built openFrameworks libraries with v143 and I thought to retarget to v142 and doing a clean build would allow me to use vs 2019. Then I guess to switch between vs 2019 and vs 2022 I need two oF folders or to rebuild the entire oF folder somehow ?
![2023-01-25 19_58_41-2019test - Microsoft Visual Studio](https://user-images.githubusercontent.com/904819/214672391-45724f56-7757-4954-8928-1ca0656e6b42.png)

**Comment by ofTheo** [comment]
Ah yes, using the Retarget Solution ( a menu option if you right click on the project in the side bar of VS ) is the correct way to fix the issue if you somehow are not targeting 2019. 

In general though if you want to use 2019 and 2022 I would recommend two different folders as it will build OF and your project for 2019 and then that will break 2022. 

Hope that help!!
