### ISSUE TITLE
suggestion: ofxAssimpModelLoader load instead of loadModel?

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6729]
I know it is a tiny detail but it was great when loadImage and loadFont were uniformized to load. 
It would be great to have loadModel changed or aliased to load too

**Comment by arturoc** [comment]
that makes sense yes, if you can send a PR adding a load method and deprecating loadModel?

**Comment by dimitre** [comment]
Great @arturoc just did it
https://github.com/openframeworks/openFrameworks/pull/6732
I've changed tabs/spaces to tabs too. if it is not desirable just let me know
