### ISSUE TITLE
download_libs.sh is missing from the most recent release package for osx

### ISSUE THREAD

**Issue by klochowicz** [openframeworks/openFrameworks#6761]
`download_libs.sh` is missing from `scripts/osx` path inside  https://openframeworks.cc/versions/v0.11.2/of_v0.11.2_osx_release.zip
(other scripts are present there).

A way to circumvent the issue is to resort to cloning the github repo.

This might be a roadblocker for someone trying oF for the first time, especially if the docs mention the script.

**Comment by danoli3** [comment]
Thanks! This is pretty critical @ofTheo

**Comment by ofTheo** [comment]
Hmm I think this is intentional as the release package comes with all the osx libs needed. 

You would only need it if you are working with the git repo.
