### ISSUE TITLE
building OF on 64bit raspberry pi 4 fails

### ISSUE THREAD

**Issue by karno-ian** [openframeworks/openFrameworks#6770]
Platform: Rasberry pi4 model B
OF : 0.11.2
OS: tried Ubuntu server 20.04 LTS kernel 5.4.0, and Raspios May 7th 20201 kernel 5.10.

`make -j4  Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project`

immediately produces the following error on both platforms:
`make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
makefileCommon/config.shared.mk:96: *** recipe commences before first target.  Stop.`

**Comment by rjsworking** [comment]
Hi
Any updates ?

Same problem here

Platform: Rasberry PI4 model B 8Gb
OF : 0.11.2
OS: Latest Raspi OS 64bit - Debian GNU/Linux 11 (bullseye) aarch64
Kernel: 5.10.103-v8+ 

Cheers

**Comment by ofTheo** [comment]
At this point I don't think arm64 is supported. 
I believe we would need to add libs in https://github.com/openframeworks/apothecary/ for arm64 and then add make rules probably too. 

There is some WIP here: 
https://github.com/openframeworks/apothecary/pull/199 
https://github.com/openframeworks/openFrameworks/pull/6643 

ping @hfiguiere @danoli3

**Comment by danoli3** [comment]
This was very close just need to merge in changes mentioned by @hfiguiere
<https://github.com/hfiguiere>

Will have a look today

**Comment by CarloCattano** [comment]
Bumping this issue , is anyone trying on Raspberry pi 3 with 64 bit Raspberry pi OS ?

**Comment by philippopov** [comment]
any news?

**Comment by dimitre** [comment]
Same issues here. 
Trying to take a look at the config.shared.mk
debug info is here
```
PLATFORM_ARCH=aarch64
PLATFORM_OS=Linux
HOST_ARCH=aarch64
HOST_OS=Linux
CROSS_COMPILING=0
PLATFORM_VARIANT=default
IS_RASPBIAN=
```
and there is no aarch64 in the IF there.

**Comment by dimitre** [comment]
I've tried to make it run on latest raspberry pi os (bullseye) and made two draft PRs 
https://github.com/openframeworks/openFrameworks/pull/7069
https://github.com/openframeworks/apothecary/pull/233

with the first we can keep building with aarch64, and the second allows us to build kiss and tess2 with apothecary.
so the project gets compiled, but still getting a specific error
```
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x18): undefined reference to `main'
/usr/bin/ld: (.text+0x1c): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

I can try other compiler or linker settings too, let me know if you have any suggestions

**Comment by ofTheo** [comment]
Added a poll here relating to arm64 vs armv6 armv7 
https://github.com/openframeworks/openFrameworks/discussions/7138

**Comment by ofTheo** [comment]
@dimitre were you trying to just build the OF lib when you got that error or an example? 

I think it might end up being easier to get working on the Pi than the CI as we need to setup the cross compiler environment.  

If anyone has pointers for arm64 Pi cross compiler setup that could be helpful. 
( similar to the armv6 stuff we have here https://github.com/openframeworks/openFrameworks/blob/master/scripts/ci/linuxarmv6l/install.sh )

**Comment by dimitre** [comment]
@ofTheo not sure, don't remember.
I have one RPI4 around here but won't be working on this in the next weeks. 
If it is helpful I can try to setup some remote access and left it on for testing.

**Comment by leonyuhanov** [comment]
Trying to get this working on Ubunto x64 on an H5 Arm board. OF is installed and set up but no projects compile. Had this same issue on an rpi4 with ubunto x64. When i installed ubuntu 32bit it worked

**Comment by dimitre** [comment]
I've recently updated the core to work with linuxaarch64, so I'm compiling it on latest Raspberry PI OS .
but as today libraries have to be manually compiled using apothecary.

**Comment by dimitre** [comment]
@rjsworking @karno-ian OF now supports aarch64, 
I'm testing now with raspberry pi os latest, most of the examples are functional.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7069
