### ISSUE TITLE
ofURLFileLoaderImpl crashes curl when used from multiple threads

### ISSUE THREAD

**Issue by Ant1r** [openframeworks/openFrameworks#6776]
OF 0.11.0 - Linux + Android (but any platform using curl should see the bug)

When two threads try to download a file, the app is likely to crash (perhaps after eating all the RAM available...).

The crash can be exposed with a little change to `imageLoaderWebExample`:
ask OF to download the online image in sync mode just after the async download has been triggered by key press:
``` C++
void ofApp::keyPressed(int key){
	img.clear();
	ofLoadURLAsync("https://openframeworks.cc/about/0.jpg","about");
	ofLoadURL("https://openframeworks.cc/about/0.jpg"); // ADDED LINE
	loading =true;
}
```

The reason is that a CURL handler (which is created by `curl_easy_init()`) can only be used by a single thread  (see: https://curl.se/libcurl/c/threadsafe.html : "You must never share the same handle in multiple threads").

A possible quick fix is to remove the `curl` member from the `ofURLFileLoaderImpl` class, and create it locally at the beginning of the `handleRequest()` function:
``` C++
ofHttpResponse ofURLFileLoaderImpl::handleRequest(const ofHttpRequest & request) {
	std::unique_ptr<CURL, void(*)(CURL*)> curl =
		std::unique_ptr<CURL, void(*)(CURL*)>(curl_easy_init(), curl_easy_cleanup);
(...)
}
```

**Comment by arturoc** [comment]
If you want to send a PR that would be really useful

**Comment by Ant1r** [comment]
sure;-) #6778
