### ISSUE TITLE
ArchLinuxARM-rpi-2-latest.tar.gz not found

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#6827]
`http://fl.us.mirror.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz` does not exist. and the Linux test failed with this.
I don't know about arch Linux arm with raspi... but `ArchLinuxARM-rpi-latest.tar.gz` exists.
Do we need to change to this?

**Comment by ofTheo** [comment]
Yes! This seems to be breaking the current CI / Github Actions too. 

From the wiki this seems like the version to use:
`http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-armv7-latest.tar.gz`

In the installation section of: 
https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2#installation

**Comment by 2bbb** [comment]
#6834
