### ISSUE TITLE
ofSetBackgroundAuto(false) causes flicker

### ISSUE THREAD

**Issue by liasomething** [openframeworks/openFrameworks#6828]
MacOS 12.0.1, M1 Pro cpu

to reproduce:
1) use project generator to generate a new file.
2) in setup() write: 
ofSetBackgroundAuto(false);
ofSetFrameRate(5); // to see better what is going on
3) in draw() write:
ofCircle( ofRandom( ofGetWidth() ), ofRandom( ofGetHeight() ), 50, 50  );
4) run, observe flickering between two distinct frames.

**Comment by dimitre** [comment]
I can reproduce it here. 
It seems to be alterning two different textures like ping pong (or double buffering), and writing each time in a different one.
PS: I admire your work since 2002 :)
```c++
#include "ofApp.h"

void ofApp::setup(){
	ofSetBackgroundAuto(false);
	ofSetFrameRate(5);
}

void ofApp::draw(){
	ofDrawCircle( ofRandom( ofGetWidth() ), ofRandom( ofGetHeight() ), 50, 50 );
}

```

**Comment by dimitre** [comment]
@liasomething I was able to find a "workaround" if you disable your double buffering
```c++
#include "ofMain.h"
#include "ofApp.h"

//========================================================================
int main( ){

	ofGLFWWindowSettings settings;
	settings.doubleBuffering = false;
	settings.setSize(640, 480);
	settings.windowMode = OF_WINDOW;
    
	auto mainWindow = ofCreateWindow(settings);
	auto mainApp = make_shared<ofApp>();

	ofRunApp(mainWindow, mainApp);
	ofRunMainLoop();
}
```

**Comment by liasomething** [comment]
@dimitre This indeed has solved my problem! thank you very much for taking the time to look into this, it will save me a ton of work! :D

**Comment by tim-yates** [comment]
I just encountered this issue.
MacOS 14.6.1, M3 Max
Here is a [further solution on the oF forum](https://forum.openframeworks.cc/t/problem-with-ofsetbackgroundauto-false/44434) that doesn't require disabling double buffering.
