### ISSUE TITLE
fatal error: 'glm/mat4x4.hpp' file not found

### ISSUE THREAD

**Issue by zohairhadi** [openframeworks/openFrameworks#6860]
A c++ project is giving me the following error when I try to compile the code. I can't seem to find any solutions online about this.
Any help would be appreciated

**Comment by 2bbb** [comment]
do you use the library from the official zip release? or clone from github or master zip?
if you clone or download master.zip, you need to run script `download_libs` under scripts directory.
see: https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md

**Comment by dimitre** [comment]
Hello @zohairhadi please report back if @2bbb solved your question, I think this issue can be closed
