### ISSUE TITLE
Xcode template needs update to allow serial device access. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6864]
Affects ofSerial / ofxSerial:

```
[ error ] SerialDevice::setup: IO Exception (1): Operation not permitted, file of_v0.11.2_osx_release/addons/ofxSerial/libs/serial/src/impl/unix.cc, line 151.
[notice ] failed to open port /dev/cu.imu-03-DevB 
```

Possible related post and solution see: 
https://developer.apple.com/forums/thread/94177

I think we need to add this to the plist / entitlements. 
``` 
com.apple.security.device.serial
```

**Comment by dimitre** [comment]
Hey @ofTheo I've just took a look at this issue, and in my system ofSerial is working OK.
I'm using macOs 11.6.4 and XCode 13.2.1 and it connects without problem. Is this something relaced to macOs 12?

**Comment by ofTheo** [comment]
@dimitre I think it is isolated to deploying the app to other devices and is not an issue on the build machine. 
I actually don't think it is an OF specific bug but just how Apple treats all apps now. The solution I believe is to notarize the app before sharing it ( which is the correct  way to deploy apps in newer macOS ). 

I'll ping the person having the issue, incase they want to comment and reopen the issue, but I think we can close it for now.
