### ISSUE TITLE
IOS ofxAccelerometer issue - error in setup

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6884]
Undefined symbols for architecture arm64:
  "_ofxAccelerometer", referenced from:
      ofApp::setup() in ofApp.o
  "ofxAccelerometerHandler::setup()", referenced from:

I've added the addon manually
I've tried to add the addon via projectGenerator and no luck either (it doesn't appear listed)
It seems the same issue is happening here:
https://forum.openframeworks.cc/t/adding-ofxaccelerometer-to-a-project/33409/2

**Comment by dimitre** [comment]
I've just noticed on this thread it doesn't work anymore,
https://forum.openframeworks.cc/t/ofxaccelerometer-and-undefined-symbols/30134
Should it be removed from the core? Maybe replaced with something like this addon? https://github.com/trentbrooks/ofxCoreMotion

**Comment by 2bbb** [comment]
@dimitre 

oh...

`ofxAccelerometer` defined as global variable, and it is declare as `extern`. (because ofxAccelerometer.h is common interface for accelerometer on ofxAndroid and ofxiOS, maybe...?)
maybe it will be fix with adding instance definition in `ofxiOSAccelerometer.mm`?

**Comment by 2bbb** [comment]
I didn't know...

https://github.com/openframeworks/projectGenerator/blob/64aa630c66eeb8da26c2d5e875eb060fd370b2dd/frontend/index.js#L81-L89

https://github.com/openframeworks/projectGenerator/issues/62

**Comment by artificiel** [comment]
I'm confused by this issue: ofxAccelerometer is not needed on iOS -- it includes ofxCoreMotion since #4641.

just checked the CoreMotion example and with minor tweaks (ofQuat vs glm::quat) it runs fine. so what is the function of ofxAccelerometer? Android? (it should perhaps be moved in there to avoid confusion?)

**Comment by artificiel** [comment]
#7371 provides a functional example that does not relay on ofxAccelerometer -- unless it's needed elsewhere, ofxAccelerometer can be removed and this issue can be closed (and the task checked in #6968).

**Comment by artificiel** [comment]
ping @dimitre to close this!
