### ISSUE TITLE
Moving nightly builds and releases to Github Releases 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6888]
Just want to start an issue that can track some of the resources for doing this. 

Here is a workflow for publishing and updating a release ( updating will be needed for nightly builds ):
https://github.com/marketplace/actions/github-release-create-update-and-upload-assets 

And a workflow for doing nightly builds:
https://github.com/marketplace/actions/deploy-nightly 

We have 0.11.2 as a manual release here:
https://github.com/openframeworks/openFrameworks/releases/tag/0.11.2 

But the idea will be to be able to auto generate a release and nightly builds as part of the existing GH Actions automation.

**Comment by roymacdonald** [comment]
So what is needed in order to achieve this? Or do you need someone to look at how it is done?

**Comment by roymacdonald** [comment]
@ofTheo I will take a look at it throughout the next days and see what I can do. I have no experience at all with GH Actions, so this might be a good thing to get to understand how it works. :)

**Comment by dimitre** [comment]
Nice! We can start by making a script of building all apothecary and packaging in a file.
do you think Actions Artifacts is what we need? 
https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts#about-the-artifacts-api

**Comment by ofTheo** [comment]
Actually I got that working already @dimitre. 
But only for Apothecary. ( see https://github.com/openframeworks/apothecary/releases ). 

Next step would be to do it for the main repo. 
It actually shouldn't be too hard - might take a couple of days to implement.

**Comment by dimitre** [comment]
FANTASTIC @ofTheo !
Great news! what about we point the install scripts directly to the github packages?
This way we can have the latest GLFW and everything for installs, Github actions will be faster since both are hosted on the same place

**Comment by dimitre** [comment]
Looking forward a new release! we need a 0.11.3 soon :)

**Comment by dimitre** [comment]
Completed, thanks @ofTheo
