### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [openframeworks/openFrameworks#6890]
Hey there!

I belong to an open source security research community, and a member (@michaellrowley) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ofTheo** [comment]
Done - thanks @JamieSlome ! 
https://github.com/openframeworks/openFrameworks/blob/master/SECURITY.md

**Comment by JamieSlome** [comment]
Thanks, @ofTheo - we will get an e-mail over to you shortly. In the meantime, you can view the report directly here:

https://huntr.dev/bounties/42325662-6329-4e04-875a-49e2f5d69f78/

It is private and only accessible to maintainers with repository write permissions 👍

**Comment by JamieSlome** [comment]
@ofTheo - e-mail sent 👍
