### ISSUE TITLE
openFrameworks failed to build with "fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO' with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [openframeworks/openFrameworks#6899]
openFrameworks failed to build with "fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO' with MSVC on windows. It can reproduces on version https://github.com/openframeworks/openFrameworks/commit/b4dacc8f8e6d3c1f63d50706920ded58da686bc8. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/openframeworks/openFrameworks F:\openFrameworks
3. cd F:\openFrameworks
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. git submodule update --init --recursive
6. mkdir build_arm64 & cd build_arm64
7. Replace x64 to arm64 in examples/templates/emptyExample/emptyExample.vcxproj fold
8. set INCLUDE=F:\openFrameworks\libs\openFrameworks;%INCLUDE%
9. set INCLUDE=F:\openFrameworks\libs\openFrameworks\utils;%INCLUDE%
10. set INCLUDE=F:\openFrameworks\libs\glew\include;%INCLUDE%
11. set INCLUDE=F:\openFrameworks\libs\tess2\include;%INCLUDE%
12. set INCLUDE=F:\openFrameworks\libs\openFrameworks\events;%INCLUDE%
13. set INCLUDE=F:\openFrameworks\libs\utf8\include;%INCLUDE%
14. set INCLUDE=F:\openFrameworks\libs\glm\include;%INCLUDE%
15. set INCLUDE=F:\openFrameworks\libs\json\include;%INCLUDE%
16. set INCLUDE=F:\openFrameworks\libs\openFrameworks\types;%INCLUDE%
17. set INCLUDE=F:\openFrameworks\libs\openFrameworks\math;%INCLUDE%
18. set INCLUDE=F:\openFrameworks\libs\pugixml\include;%INCLUDE%
19. set INCLUDE=F:\openFrameworks\libs\openFrameworks\graphics;%INCLUDE%
20. set INCLUDE=F:\openFrameworks\libs\openFrameworks\communication;%INCLUDE%
21. set INCLUDE=F:\openFrameworks\libs\openFrameworks\gl;%INCLUDE%
22. set INCLUDE=F:\openFrameworks\libs\openFrameworks\app;%INCLUDE%
23. set INCLUDE=F:\openFrameworks\libs\openFrameworks\3d;%INCLUDE%
24. set INCLUDE=F:\openFrameworks\libs\cairo\include\cairo;%INCLUDE%
25. set INCLUDE=F:\openFrameworks\libs\openFrameworks\sound;%INCLUDE%
26. set INCLUDE=F:\openFrameworks\libs\fmod\include;%INCLUDE%
27. set INCLUDE=F:\openFrameworks\libs\openFrameworks\video;%INCLUDE%
28. set INCLUDE=F:\openFrameworks\libs\videoInput\include;%INCLUDE%
29. msbuild /m /p:Platform=arm64 /p:Configuration=Release ../examples/templates/emptyExample/emptyExample.vcxproj /t:Rebuild /p:OutDir=F:\openFrameworks\build_arm64 /p:PlatformToolset=v142 /p:useenv=true 

Build.log:
[openFrameworks_msbuild.log](https://github.com/openframeworks/openFrameworks/files/8283125/openFrameworks_msbuild.log)

**Error info:**
LINK : fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO'

**Comment by roymacdonald** [comment]
Hi @YangYang129, I would encourage you to use Project Generator to make the projects rather than manually creating these. Although, ARM64 on windows seems like it is not (fully) supported. Yet still you will probably need to run Apothecary and recompile all the libraries for ARM64.

**Comment by YangYang129** [comment]
@roymacdonald Thank you for your info. I still don't understand how to compile on ARM64 Windows. Can you help me with the relevant compilation commands? Thank you very much.

**Comment by roymacdonald** [comment]
I dont have a windows ARM64 machine so I have not tried it. But I am almost certain that it is not supported so far. There is no releases for it.
If you want to build from github check this document https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md
It mentions to run the install_dependencies.sh script but I think that will try to install the x64 dependencies.
All of openFrameworks dependencies are compiled and managed via apothecary https://github.com/openframeworks/apothecary/ but you will need to modify the scripts to make it work.
I dont know of a more straight forwards way. 
@ofTheo @oxillo might provide a better answer.

**Comment by ofTheo** [comment]
Hey @YangYang129, 

@roymacdonald is correct. We are currently only building x86_64 and x86 libs for Windows( and about to drop x86 ). 
To add arm64 for windows we would first need to do that in https://github.com/openframeworks/apothecary/ and then pull those libs into the OF release process. 

It could be something we look into, but it probably wouldn't happen urgently without some outside interest, contribution or funding. 

Going to close this issue for now as OF isn't currently targeting arm64 on Windows.

**Comment by danoli3** [comment]
All the code to compile Windows ARM and Windows ARM64 I have added to
Android PR on Apothecary. I have Windows ARM64 on Parallel’s will try it
out soon!

**Comment by ofTheo** [comment]
Oh wow, that's awesome @danoli3!

**Comment by danoli3** [comment]
In the process of supporting ARM and ARM64 Windows via Apothecary for
Dependency libs. Very close in vs2019/vs2022


I’ve been creating the compilers for this in the new scripts as apart of
massive update dependencies, all currently in the Android PR (it’s got a
bit out of hand how massive and how many platforms it updates)

**Comment by CFM880** [comment]
I occur same error when compile bochs 3.0 windows on arm64. Because ASLR(address space layout randomization) can't be disabled on ARM, ARM64, or ARM64EC architectures, /DYNAMICBASE:NO isn't supported for these targets. so we will occur this error

solution:
on vs2022: Project-->Properites-->Configuration Properites-->Linker-->Advenced->Randomized Base Address-> NO(/ DYNAMICBASE)-->Yes(/ DYNAMICBASE)

reference:
[/DYNAMICBASE (Use address space layout randomization](https://learn.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=msvc-170)

![Image](https://github.com/user-attachments/assets/3c24475e-9024-46fc-a275-995ac74f8edd)
