### ISSUE TITLE
update utf-8 library to compatible with c++17

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6905]
I've noticed there is an updated version of utf-8 library updated to remove std::iterator here
https://github.com/nemtrif/utfcpp/tree/master/source/utf8

**Comment by roymacdonald** [comment]
OF is using a really old version (2.3.4) which is like 7 years old. utfcpp is now in version 3.2.1 so it need to be thoroughly checked. can you do so? if it works can you PR please?
thanks

**Comment by danoli3** [comment]
Just updated on Apothecary, sent PR https://github.com/openframeworks/apothecary/pull/211

**Comment by ofTheo** [comment]
merged! thanks!!

**Comment by dimitre** [comment]
Hey a quick question, I'm trying to update utf8 locally using apothecary, and I have one doubt:
should it copy the files to libs folder? I think LIBS_DIR is pointing somewhere else.

I've updated submodules here and run the following:
```
./apothecary/apothecary update utf8
```

and the result is this one
```
./apothecary/apothecary update utf8
OF: /Volumes/tool/ofw/scripts/apothecary/apothecary/../../../
APOTHECARY: /Volumes/tool/ofw/scripts/apothecary/apothecary
FORMULAS: /Volumes/tool/ofw/scripts/apothecary/apothecary/formulas
BUILD: /Volumes/tool/ofw/scripts/apothecary/apothecary/build
LIBS_DIR: /Volumes/tool/ofw/scripts/apothecary/apothecary/../
ADDONS: /Volumes/tool/ofw/scripts/apothecary/apothecary/../../../addons
REL_ADDONS_DIR: /Volumes/tool/ofw/scripts/apothecary/apothecary/../../../addons

 ----- utf8 -----

 Downloading "utf8"

... skipping, utf8 src dir already exists in /Volumes/tool/ofw/scripts/apothecary/apothecary/build/utf8

 Preparing "utf8"



 Building "utf8"



 Copying "utf8"

source/utf8 -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8
source/utf8/cpp17.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8/cpp17.h
source/utf8/core.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8/core.h
source/utf8/unchecked.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8/unchecked.h
source/utf8/cpp11.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8/cpp11.h
source/utf8/checked.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8/checked.h
source/utf8.h -> /Volumes/tool/ofw/scripts/apothecary/apothecary/..//utf8/include/utf8.h

```

**Comment by danoli3** [comment]
Yeah it seems to have been configured to deploy the core apothecary
directory rather that core libs folder if build from dependency folder. I
thought if run from the core oF dir it would deploy correctly

We should fix this and make it easier for devs to build their own
dependencies easier

**Comment by dimitre** [comment]
Great @danoli3 I've just submitted a PR to fix the libs folder
https://github.com/openframeworks/apothecary/pull/213

**Comment by dimitre** [comment]
Hey @ofTheo can you please run the update on utf8 library so we have this updated on master?
```
./apothecary/apothecary update utf8
```
