### ISSUE TITLE
Mingw pkgconfig breaking msys2 for OpenCV

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#6933]
Been dealing with this issue the last few days on the CI. 
https://github.com/msys2/MINGW-packages/issues/11208 

The newer OpenCV for msys2 changed their dll naming and that broke the way mingw parses packages. 
So might wait for a few days to see if it fixes it self. Otherwise will look into a temporary solution. 

Note: this will affect current users installing msys2 version of OF.

**Comment by Biswa96** [comment]
This should be fixed now. New packages have been uploaded to pacman repositories.

**Comment by ofTheo** [comment]
Thank you @Biswa96 ! 
Really appreciate letting us know. Checking our CI now. 🙏
