### ISSUE TITLE
libfmod.dylib incompatible with XCode 13.3.1

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6938]
So it is best avoiding update XCode for now
```
mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
```

**Comment by dimitre** [comment]
I'll be closing. my fault I let xcode change to ENABLE_HARDENED_RUNTIME

**Comment by PSMackey** [comment]
I'm using Xcode 15.0 in MacOS 14.4 with openFrameworks v0.12.0 on an Apple M2. I'm getting a "dyld[9792]: Library not loaded: @executable_path/../Frameworks/libfmod.dylib" with "libfmod.dylib' (no such file, not in dyld cache)" thus my project won't compile. Is there any way around this? (other than going back about 4 years!)

**Comment by ofTheo** [comment]
Hmm - I am on Xcode 15.1 with macOS 14.2.1 and 0.12.0 and not having any issues. 

If you right click on the executable and do Show Package Contents and navigate to Contents/Frameworks/ do you see it there? 

Is your project in an iCloud enabled folder by any chance? 

If you run the examples/templates/emptyExample project do you get that error? 
Is it just with your own projects that you are getting the error ( ie: all the examples work )

**Comment by dimitre** [comment]
@PSMackey I can suggest you re-generate your project using this same OF version
or try downloading the nightly builds and re-generate the project there

**Comment by PSMackey** [comment]
Thanks to ofTheo and dimitre! Since the current of0.12.0_myApps emptyExample app was indeed working fine, I carefully added into that the code from the previous project I was trying to update, and worked with that successfully. My biggest issue was that Show Package Contents on the old executable I was trying had missing elements.
