### ISSUE TITLE
iOS simulator libs

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6966]
I've recently started to use iOS using github code, so I've noticed the simulator libs are absent.
We don't have precompiled libs here http://ci.openframeworks.cc/libs/0.11.2/ too
so I suppose the way of getting it working now is to build using apothecary right?
Is there a script to build all apothecary formulas for a specific platform?

Suggestions:
Simulator libs could be added to ci.openframeworks.cc and some new scripts added in /scripts/ios folder
like:
download_libs_ios.sh
download_libs_ios_simulator.sh
download_libs_tvos.sh

**Comment by danoli3** [comment]
Definitely they should be apart of it with x86_64 Intel. 
ARM64 simulator (M1 / Apple Silicon) however needs us to move to the new .xcframework as you can't fat lib (.a) two of the same architecture together. Apple also wants us to use .xcframework so we can version our dependancies and track what version each one is

**Comment by dimitre** [comment]
Nice! 
@danoli3 what do you think of splitting in two separate files the ios libs and tvos libs ?
and how to name this scripts? I can submit a PR.
I always interrupt the script when it starts downloading tvos stuff

**Comment by danoli3** [comment]
https://github.com/openframeworks/openFrameworks/pull/6975

**Comment by dimitre** [comment]
> tvOS split here #6975

Woww thanks @danoli3 :)

**Comment by ofTheo** [comment]
Not currently 😞 - that is something we need to tackle in apothecary:
https://github.com/openframeworks/apothecary/issues/208

**Comment by danoli3** [comment]
Just build for m1 via Designed for iPad it works

**Comment by NickHardeman** [comment]
@danoli3 Ok great, thank you. Xcode really wants me to have a developer license/team, is there a way to compile without one?

**Comment by danoli3** [comment]
xCFrameworks solved this
