### ISSUE TITLE
Idea: CoreOF.xcconfig, Boost as an optional include

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6967]
Suggestion: we could make boost a separate xcconfig file like this:

Boost.xcconfig
```xcconfig
// BOOST
HEADER_BOOST = "$(OF_PATH)/libs/boost/include"
LIB_BOOST_SYSTEM = "$(OF_PATH)/libs/boost/lib/osx/boost_system.a"
LIB_BOOST_FS = "$(OF_PATH)/libs/boost/lib/osx/boost_filesystem.a"

OF_CORE_LIBS = $(inherited) $(LIB_BOOST_FS) $(LIB_BOOST_SYSTEM)
OF_CORE_HEADERS = $(inherited) $(HEADER_BOOST)
```

and left the include as a comment, just in case somebody needs to use C++11 it can be included back
and using C++17 it doesn't need to be there so it can speed up things a tiny little bit.

**Comment by ofTheo** [comment]
Could we just have it in the Project.xcconfig ? 
It could be located near these lines as they are related? 

https://github.com/openframeworks/openFrameworks/blob/master/scripts/templates/osx/Project.xcconfig#L8-L10

**Comment by dimitre** [comment]
https://github.com/openframeworks/openFrameworks/pull/6969

**Comment by dimitre** [comment]
Just wondering here @ofTheo, how about we change this lines in Project.xcconfig
```
// BOOST - UNCOMMENT BELOW TO ENABLE BOOST
//HEADER_BOOST = "$(OF_PATH)/libs/boost/include"
//LIB_BOOST_SYSTEM = "$(OF_PATH)/libs/boost/lib/osx/boost_system.a"
//LIB_BOOST_FS = "$(OF_PATH)/libs/boost/lib/osx/boost_filesystem.a"
//OF_CORE_LIBS = $(inherited) $(LIB_BOOST_FS) $(LIB_BOOST_SYSTEM)
//OF_CORE_HEADERS = $(inherited) $(HEADER_BOOST)
```

to this?
```
// BOOST - UNCOMMENT BELOW TO ENABLE BOOST
//#include "../../../libs/openFrameworksCompiled/project/osx/boost.xcconfig"
```

**Comment by dimitre** [comment]
Closed by https://github.com/openframeworks/openFrameworks/pull/6969
