### ISSUE TITLE
ofSetBackgroundAuto flickering in IOS

### ISSUE THREAD

**Issue by drawcall** [openframeworks/openFrameworks#6990]
Use of_v0.11.2_ios_release project when set
```
settings.enableHardwareOrientationAnimation = false; // enables native orientation changes to be animated.
settings.glesVersion = OFXIOS_RENDERER_ES2; // type of renderer to use, ES1, ES2, ES3
settings.windowControllerType = ofxiOSWindowControllerType::GL_KIT; // Window Controller Type
settings.colorType = ofxiOSRendererColorFormat::RGBA8888;
```
If the screen clear is turned off, `ofSetBackgroundAuto(false);`
Then the screen will keep flickering, it seems to be caused by the repeated switching of the double buffer. But this mode cannot set setDoubleBuffering(false);

**Comment by ofZach** [comment]
in case it's helpful -- this isn't a fix but a recommendation would be to use an FBO, which you can clear once and not clear across frames, to get the same result.

**Comment by ofZach** [comment]
(side note, I wonder if it wouldn't be helpful to generally use an internal FBO in the case of ofSetBackgroundAuto(false) -- it feels like we have always had issues with single / double buffe and flickering and it feels perhaps easy to solve if we use an FBO internally -- not sure what the drawbacks / side effects of that might be)

**Comment by drawcall** [comment]
Oh a workable suggestion, I will try it.

**Comment by ofZach** [comment]
can we leave this open?  I feel like it's something that should be fixed across different platforms, etc.
