### ISSUE TITLE
App Store - Easier way

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6999]
Both for macOS and iOS. I'll start trying with macOS
![Screen Shot 2022-05-26 at 17 47 19](https://user-images.githubusercontent.com/58289/170577430-e9f5a5c0-8a7c-4f87-a58e-94a41d4121f5.png)
- [x] OF Icon with 1024x1024 (Debug and Release)
- [x] having basic project variables in xcconfig / plist
```
PRODUCT_BUNDLE_IDENTIFIER = org.dmtr.ofTest
VERSION = 0.76.0
DEVELOPMENT_LANGUAGE = English
ENABLE_HARDENED_RUNTIME = YES
```

- [x] configurations that can survive project generator, ex:
- https://github.com/openframeworks/openFrameworks/issues/6997
surviving project generator we can use a permanent PRODUCT_BUNDLE_IDENTIFIER to match the one created at appstoreconnect.
VERSION to separate each build
and custom ICON of course

- [x] info.plist updates (CFBundleShortVersionString, CFBundleVersion, LSApplicationCategoryType)
Some of them can be variables to be declared in Project.xcconfig, for some reason LSApplicationCategoryType doesn't seem to accept variables now.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIconFile</key>
	<string>$(ICON_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string></string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleShortVersionString</key>
	<string>$(VERSION)</string>
	<key>CFBundleVersion</key>
	<string>$(VERSION)</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.graphics-design</string>
	<key>NSCameraUsageDescription</key>
	<string>This app needs to access the camera</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app needs to access the microphone</string>
	<key>NSHighResolutionCapable</key>
	<false/>
</dict>
</plist>

```

- [x] Entitlements.
Maybe a file OF.entitlements with a basic sandbox configuration 

- [x] Enable Hardened Runtime
 ENABLE_HARDENED_RUNTIME[config=AppStore] = YES

- [x] Project Generator AppStore scheme.
There is an appstore schema created on template but for some reason PG doesn't copy all files over. I'm copying it in my fork, so it is easy to access like Debug / Release. 
The only thing I don't understand yet is how to choose a default option there when you open the project. XCode seems to choose alphabetically so you open with AppStore scheme.

- [ ] Near Future
this can go well with the possibility of building OF without some parts, like Cairo, or Audio (libfmod), so we can have a lean build.

any more ideas to the list?

**Comment by dimitre** [comment]
Finally submission done. 
just pointing some things as a recipe, and it would be helpful to have some of them ready or at least commented out in xcode project.
- set version
- set icon with all modern sizes. the only way I could do it was using this script from a 1024x1024 png https://gist.github.com/dimitre/349abac9d7e4aa2a913b440dd030f6f0
- creating entitlements for release, debug and appstore (will look at some way of consolidating the three later)
- without fmod things were faster to upload and check
- enabling hardened runtime

**Comment by dimitre** [comment]
Another issue, I've just discovered that Archive is building Debug to submit to AppStore. I think it should be changed to AppStore or Release. Easy to miss this step as things work ok anyway

**Comment by dimitre** [comment]
- https://github.com/openframeworks/openFrameworks/issues/7004

**Comment by dimitre** [comment]
Closed by https://github.com/openframeworks/openFrameworks/pull/7028

**Comment by danoli3** [comment]
Yeah I thought this was the case many many years ago.

I think def deployed a few apps in debug back in 2012 before I figured this
out haha! Thanks for solving though

I would just manually do it for AppStore by making my own AppStore target
