### ISSUE TITLE
XCode AppStore scheme - failing to build (Lipo)

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7004]
Issue was related here
https://forum.openframeworks.cc/t/big-sur-compile-run-error-uhoh/38903/30

Only happens using AppStore scheme, third script fails to complete, 
This step is not needed for libfmod.dylib, maybe you know some 32bit libs out there?

it seems to try to iterate the entire filename instead of architectures to strip, like this
```
/Users/z/Library/Developer/Xcode/DerivedData/Atsenaru2-hkqfatzjvrebfchflsiyjsqnoots/Build/Intermediates.noindex/ArchiveIntermediates/Atsenaru2 AppStore/InstallationBuildProductsLocation/Applications/Atsenaru2.app/Contents/Frameworks/libfmod.dylib

Stripping invalid archs '/Us'
```

/Us is the start of /Users/z
so in fact I think the intended thing was iterate the archs used in the library, like this:

```
lipo libfmod.dylib -archs
```
list archs
```
x86_64 arm64
```

but it runs another command I suppose it was meant to remove 32 bits archs, but I think it has the potential to strip arm64 too.
lipo -extract x86_64 ... 

maybe it is best to use  -remove to remove some specific arch?

**Comment by dimitre** [comment]
I've found the issue on the script. for some reason it was substituting the letter 'e' for a space, so a path like this:
```
/Volumes/tool/ofw/apps/ofApps/VideoPlayerNeue/bin/VideoPlayerNeue.app/Contents/Frameworks/libfmod.dylib
```
turns into this
```
/Volum s/tool/ofw/apps/ofApps/Vid oPlay rN u /bi /Vid oPlay rN u .app/Co t  ts/Fram works/libfmod.dylib
```
and it tries to iterate over each word, in the case of /Users the first work is '/Us'


changing the script to this solves the issue
```bash
for ITEM in "${ITEMS}";
```

**Comment by ofTheo** [comment]
Nice find!! 🙌

**Comment by dimitre** [comment]
Great! I'll submit another PR soon
and I'll replace this line 
```bash
lipo -extract x86_64 "${ITEM}" -o "${ITEM}"
```
for this one
```bash
lipo -remove i386 "${ITEM}" -o "${ITEM}"
```

so it removes the 32-bit (i386) without touching other architectures like arm.
ping: @danoli3

**Comment by ofTheo** [comment]
I would also maybe add to the end of the command: `&> /dev/null ` incase a lib doesn't have i386 architecture which can sometimes cause an error.

**Comment by dimitre** [comment]
Wondering if I apply those changes in this PR? 
https://github.com/openframeworks/openFrameworks/pull/7003
or if its best review it separately and fixing the script in another PR?

**Comment by dimitre** [comment]
Now we can check if undesired architecture is present before removing it 
```bash
if lipo -archs "${ITEM}" | grep -q 'i386'; then
	echo "Stripping invalid archs ${ITEM}"
	lipo -remove i386 "${ITEM}" -o "${ITEM}" 
else
	echo "No need to strip invalid archs {$ITEM}"
fi
```
