### ISSUE TITLE
 Nightly build + Xcode doesn't jump to error location

### ISSUE THREAD

**Issue by stephanschulz** [openframeworks/openFrameworks#7006]
I am using nightly build **of_v20220530_osx_release** with macOS **10.15.7** and Xcode Version **12.4** (12D4e) 

I noticed a problem, when I have a compile error and I click on the compile error in the Issue Navigator then Xcode does not jump to the error's location.

Here my simple example:
https://www.dropbox.com/sh/45tmj81bbb6oizs/AABTenKh9SDXYh6e12Z8UAnXa?dl=0

My project path:
![Screen Shot 2022-05-31 at 8 18 18 AM](https://user-images.githubusercontent.com/1054816/171175007-97aa0680-a6c8-4400-bbe9-a54f41778692.jpg)

Here you can see how after clicking on the error the code window did not jump to the location:
![Screen Shot 2022-05-31 at 8 14 01 AM](https://user-images.githubusercontent.com/1054816/171175073-7cbad23e-3ffe-4a17-81fb-847a669f85a4.jpg)

Here I am using OF 0.11.2 which does not have this problem.
![Screen Shot 2022-05-31 at 8 14 50 AM](https://user-images.githubusercontent.com/1054816/171175044-35872ca4-892c-460b-87fa-5b5783cc91ce.jpg)

The strange part is that this does not happen for all projects right away, but at some point (restarting Xcode, using project generator, etc) this happens to all projects, when using nightly build.

Has anyone had this problem?

**Comment by stephanschulz** [comment]
If I switch to 'legacy build system" then it works again.
![Screen Shot 2022-05-31 at 9 07 52 AM](https://user-images.githubusercontent.com/1054816/171180692-5b828828-6661-48b9-a385-e33ac5d1cd35.jpg)

**Comment by dimitre** [comment]
I've just tested with today's nightly build and github master and cannot reproduce. 
I'm using macOS 12.4 and XCode 13.4 (13F17a)

**Comment by dimitre** [comment]
@stephanschulz most changes are in Project.xcconfig. you can try to comment out compiler settings to see if it makes some difference in your system

**Comment by dimitre** [comment]
@stephanschulz are you still experiencing this? 
Can the issue be closed? Thanks

**Comment by stephanschulz** [comment]
I have not seen this issue with OF 0.11.2 on macOS 12.6 and on 10.15.7  doing legacy build solved it too. Thanks for your help.
