### ISSUE TITLE
review/fix line iterators in ofBuffer

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#7011]
as discussed in #6945 and #7010, iterators don't look right.

**Comment by 2bbb** [comment]
at first, I can't judge which is correct ignoring last line or not.

I point out only what I fixed on #6945

* `value_type` about iterator
* `RLine Lines::rbegin()/rend()` are not implemented
* RLines missed character at some cases.
  * e.g. "\nabc\ndef"

**Comment by dimitre** [comment]
Closed by https://github.com/openframeworks/openFrameworks/pull/7018
