### ISSUE TITLE
package/bundle gstreamer (and plugins) with the right version

### ISSUE THREAD

**Issue by ranjithshegde** [openframeworks/openFrameworks#7023]
Seeing as how gstreamer > `1.18.5` breaks comparability with openFrameworks, would it be possible to package prebuilt gstreamer with version = `1.18.4`, the same way libs like `freetype` or `kiss-fft` are bundled?

I have been using the older builds of gstreamer from arch-package-archives since incompatibility began, but so many other packages on my (or any) system depend on the later versions of gstreamer, its getting harder to continue this way

**Comment by dimitre** [comment]
@ofTheo I think this can be closed by this PR fix - https://github.com/openframeworks/openFrameworks/pull/7050

**Comment by ofTheo** [comment]
closed by #7050
