### ISSUE TITLE
of_v0.11.2_msys2_mingw64_release: Install error performing make on Win 10

### ISSUE THREAD

**Issue by elegolo** [openframeworks/openFrameworks#7024]
I followed the given instructions on Windows 10 system using of_v0.11.2_msys2_mingw64_release.
Error in C:/msys64/mingw64/include/sndfile.h:356:33: error: conflicting declaration 'typedef struct sf_private_tag SNDFILE', see end of listing (maybe version of msys64/mingw64, fresh install, incompatible?) :

Bernd@LAPTOP-BERND MINGW64 ~
$ pacman -Syu --noconfirm --needed
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

Bernd@LAPTOP-BERND MINGW64 ~
$ cd D:/openFrameworks/scripts/msys2

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks/scripts/msys2
$ ./install_dependencies.sh
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) make-4.3-3

Total Download Size:   0.46 MiB
Total Installed Size:  1.48 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 make-4.3-3-x86_64                                    466.2 KiB   505 KiB/s 00:01 [#############################################] 100%
(1/1) checking keys in keyring                                                    [#############################################] 100%
(1/1) checking package integrity                                                  [#############################################] 100%
(1/1) loading package files                                                       [#############################################] 100%
(1/1) checking for file conflicts                                                 [#############################################] 100%
(1/1) checking available disk space                                               [#############################################] 100%
:: Processing package changes...
(1/1) installing make                                                             [#############################################] 100%
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (2) libxxhash-0.8.1-1  rsync-3.2.3-2

Total Download Size:   0.36 MiB
Total Installed Size:  0.68 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 libxxhash-0.8.1-1-x86_64                              22.5 KiB  35.6 KiB/s 00:01 [#############################################] 100%
 rsync-3.2.3-2-x86_64                                 343.4 KiB   436 KiB/s 00:01 [#############################################] 100%
 Total (2/2)                                          365.9 KiB   436 KiB/s 00:01 [#############################################] 100%
(2/2) checking keys in keyring                                                    [#############################################] 100%
(2/2) checking package integrity                                                  [#############################################] 100%
(2/2) loading package files                                                       [#############################################] 100%
(2/2) checking for file conflicts                                                 [#############################################] 100%
(2/2) checking available disk space                                               [#############################################] 100%
:: Processing package changes...
(1/2) installing libxxhash                                                        [#############################################] 100%
(2/2) installing rsync                                                            [#############################################] 100%
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) zip-3.0-3

Total Download Size:   0.15 MiB
Total Installed Size:  0.45 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 zip-3.0-3-x86_64                                     157.1 KiB   255 KiB/s 00:01 [#############################################] 100%
(1/1) checking keys in keyring                                                    [#############################################] 100%
(1/1) checking package integrity                                                  [#############################################] 100%
(1/1) loading package files                                                       [#############################################] 100%
(1/1) checking for file conflicts                                                 [#############################################] 100%
(1/1) checking available disk space                                               [#############################################] 100%
:: Processing package changes...
(1/1) installing zip                                                              [#############################################] 100%
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) unzip-6.0-2

Total Download Size:   0.09 MiB
Total Installed Size:  0.45 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 unzip-6.0-2-x86_64                                    93.1 KiB   184 KiB/s 00:01 [#############################################] 100%
(1/1) checking keys in keyring                                                    [#############################################] 100%
(1/1) checking package integrity                                                  [#############################################] 100%
(1/1) loading package files                                                       [#############################################] 100%
(1/1) checking for file conflicts                                                 [#############################################] 100%
(1/1) checking available disk space                                               [#############################################] 100%
:: Processing package changes...
(1/1) installing unzip                                                            [#############################################] 100%
warning: wget-1.21.3-1 is up to date -- skipping
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (9) mingw-w64-x86_64-bzip2-1.0.8-2  mingw-w64-x86_64-gcc-libs-12.1.0-3  mingw-w64-x86_64-gmp-6.2.1-3
             mingw-w64-x86_64-libwinpthread-git-10.0.0.r54.gb4116e310-1  mingw-w64-x86_64-minizip-git-1.2.445.e67b996-2
             mingw-w64-x86_64-mpc-1.2.1-1  mingw-w64-x86_64-mpfr-4.1.0.p13-1  mingw-w64-x86_64-zlib-1.2.12-1
             mingw-w64-x86_64-assimp-5.2.4-1

Total Download Size:    5.09 MiB
Total Installed Size:  19.47 MiB

:: Proceed with installation? [Y/n]

.... big part of protocol deleted as too much data for comment ...

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-x86_64-tools-git-10.0.0.r54.gb4116e31...   310.3 KiB   452 KiB/s 00:01 [#############################################] 100%
(1/1) checking keys in keyring                                                    [#############################################] 100%
(1/1) checking package integrity                                                  [#############################################] 100%
(1/1) loading package files                                                       [#############################################] 100%
(1/1) checking for file conflicts                                                 [#############################################] 100%
(1/1) checking available disk space                                               [#############################################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-x86_64-tools-git                                       [#############################################] 100%
warning: mingw-w64-x86_64-zlib-1.2.12-1 is up to date -- skipping
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
Updating ofxOpenCV to use openCV4

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks/scripts/msys2
$ cd ..

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks/scripts
$ cd ..

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks
$ cd libs/openFrameworksCompiled/project

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks/libs/openFrameworksCompiled/project
$ make -j4
Compiler flags have changed, recompiling
Old:
New -g3 -DDEBUG -std=gnu++14 -DUNICODE -D_UNICODE -Wall -fexceptions -DOF_USING_MPG123 -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include/AL -IC:/msys64/mingw64/include/opus -I/d/openFrameworks/libs/fmod/include -I/d/openFrameworks/libs/glm/include -I/d/openFrameworks/libs/glm/include/glm -I/d/openFrameworks/libs/glm/include/glm/detail -I/d/openFrameworks/libs/glm/include/glm/ext -I/d/openFrameworks/libs/glm/include/glm/gtc -I/d/openFrameworks/libs/glm/include/glm/gtx -I/d/openFrameworks/libs/glm/include/glm/simd -I/d/openFrameworks/libs/json/include -I/d/openFrameworks/libs/kiss/include -I/d/openFrameworks/libs/pugixml/include -I/d/openFrameworks/libs/rtAudio/include -I/d/openFrameworks/libs/tess2/include -I/d/openFrameworks/libs/uriparser/include -I/d/openFrameworks/libs/uriparser/include/uriparser -I/d/openFrameworks/libs/utf8/include -I/d/openFrameworks/libs/utf8/include/utf8 -I/d/openFrameworks/libs/videoInput/include -I/d/openFrameworks/libs/openFrameworks -I/d/openFrameworks/libs/openFrameworks/3d -I/d/openFrameworks/libs/openFrameworks/app -I/d/openFrameworks/libs/openFrameworks/communication -I/d/openFrameworks/libs/openFrameworks/events -I/d/openFrameworks/libs/openFrameworks/gl -I/d/openFrameworks/libs/openFrameworks/graphics -I/d/openFrameworks/libs/openFrameworks/math -I/d/openFrameworks/libs/openFrameworks/sound -I/d/openFrameworks/libs/openFrameworks/types -I/d/openFrameworks/libs/openFrameworks/utils -I/d/openFrameworks/libs/openFrameworks/video
Compiling /d/openFrameworks/libs/openFrameworks/3d/of3dPrimitives.cpp
/mingw64/bin/g++ -g3  -DDEBUG -std=gnu++14 -DUNICODE -D_UNICODE -Wall -fexceptions -DOF_USING_MPG123 -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include/AL -IC:/msys64/mingw64/include/opus -I/d/openFrameworks/libs/fmod/include -I/d/openFrameworks/libs/glm/include -I/d/openFrameworks/libs/glm/include/glm -I/d/openFrameworks/libs/glm/include/glm/detail -I/d/openFrameworks/libs/glm/include/glm/ext -I/d/openFrameworks/libs/glm/include/glm/gtc -I/d/openFrameworks/libs/glm/include/glm/gtx -I/d/openFrameworks/libs/glm/include/glm/simd -I/d/openFrameworks/libs/json/include -I/d/openFrameworks/libs/kiss/include -I/d/openFrameworks/libs/pugixml/include -I/d/openFrameworks/libs/rtAudio/include -I/d/openFrameworks/libs/tess2/include -I/d/openFrameworks/libs/uriparser/include -I/d/openFrameworks/libs/uriparser/include/uriparser -I/d/openFrameworks/libs/utf8/include -I/d/openFrameworks/libs/utf8/include/utf8 -I/d/openFrameworks/libs/videoInput/include -I/d/openFrameworks/libs/openFrameworks -I/d/openFrameworks/libs/openFrameworks/3d -I/d/openFrameworks/libs/openFrameworks/app -I/d/openFrameworks/libs/openFrameworks/communication -I/d/openFrameworks/libs/openFrameworks/events -I/d/openFrameworks/libs/openFrameworks/gl -I/d/openFrameworks/libs/openFrameworks/graphics -I/d/openFrameworks/libs/openFrameworks/math -I/d/openFrameworks/libs/openFrameworks/sound -I/d/openFrameworks/libs/openFrameworks/types -I/d/openFrameworks/libs/openFrameworks/utils -I/d/openFrameworks/libs/openFrameworks/video  -MMD -MP -MF /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.d -MT/d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.o -o /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.o -c /d/openFrameworks/libs/openFrameworks/3d/of3dPrimitives.cpp

... compiling without errors or warnings removed ...

Compiling /d/openFrameworks/libs/openFrameworks/graphics/ofPath.cpp
In file included from D:/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.cpp:1:
D:/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.h: In constructor 'ofCairoRenderer::ofCairoRenderer()':
D:/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.h:206:22: warning: 'ofCairoRenderer::graphics3d' will be initialized after [-Wreorder]
  206 |         of3dGraphics graphics3d;
      |                      ^~~~~~~~~~
D:/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.h:187:19: warning:   'glm::mat4 ofCairoRenderer::projection' [-Wreorder]
  187 |         glm::mat4 projection;
      |                   ^~~~~~~~~~
D:/openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.cpp:21:1: warning:   when initialized here [-Wreorder]
   21 | ofCairoRenderer::ofCairoRenderer()
      | ^~~~~~~~~~~~~~~
/mingw64/bin/g++ -g3  -DDEBUG -std=gnu++14 -DUNICODE -D_UNICODE -Wall -fexceptions -DOF_USING_MPG123 -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include/AL -IC:/msys64/mingw64/include/opus -I/d/openFrameworks/libs/fmod/include -I/d/openFrameworks/libs/glm/include -I/d/openFrameworks/libs/glm/include/glm -I/d/openFrameworks/libs/glm/include/glm/detail -I/d/openFrameworks/libs/glm/include/glm/ext -I/d/openFrameworks/libs/glm/include/glm/gtc -I/d/openFrameworks/libs/glm/include/glm/gtx -I/d/openFrameworks/libs/glm/include/glm/simd -I/d/openFrameworks/libs/json/include -I/d/openFrameworks/libs/kiss/include -I/d/openFrameworks/libs/pugixml/include -I/d/openFrameworks/libs/rtAudio/include -I/d/openFrameworks/libs/tess2/include -I/d/openFrameworks/libs/uriparser/include -I/d/openFrameworks/libs/uriparser/include/uriparser -I/d/openFrameworks/libs/utf8/include -I/d/openFrameworks/libs/utf8/include/utf8 -I/d/openFrameworks/libs/videoInput/include -I/d/openFrameworks/libs/openFrameworks -I/d/openFrameworks/libs/openFrameworks/3d -I/d/openFrameworks/libs/openFrameworks/app -I/d/openFrameworks/libs/openFrameworks/communication -I/d/openFrameworks/libs/openFrameworks/events -I/d/openFrameworks/libs/openFrameworks/gl -I/d/openFrameworks/libs/openFrameworks/graphics -I/d/openFrameworks/libs/openFrameworks/math -I/d/openFrameworks/libs/openFrameworks/sound -I/d/openFrameworks/libs/openFrameworks/types -I/d/openFrameworks/libs/openFrameworks/utils -I/d/openFrameworks/libs/openFrameworks/video  -MMD -MP -MF /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/graphics/ofPath.d -MT/d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/graphics/ofPath.o -o /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/graphics/ofPath.o -c /d/openFrameworks/libs/openFrameworks/graphics/ofPath.cpp

... compiling without errors or warnings removed ...

Compiling /d/openFrameworks/libs/openFrameworks/sound/ofSoundBuffer.cpp
/mingw64/bin/g++ -g3  -DDEBUG -std=gnu++14 -DUNICODE -D_UNICODE -Wall -fexceptions -DOF_USING_MPG123 -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include/AL -IC:/msys64/mingw64/include/opus -I/d/openFrameworks/libs/fmod/include -I/d/openFrameworks/libs/glm/include -I/d/openFrameworks/libs/glm/include/glm -I/d/openFrameworks/libs/glm/include/glm/detail -I/d/openFrameworks/libs/glm/include/glm/ext -I/d/openFrameworks/libs/glm/include/glm/gtc -I/d/openFrameworks/libs/glm/include/glm/gtx -I/d/openFrameworks/libs/glm/include/glm/simd -I/d/openFrameworks/libs/json/include -I/d/openFrameworks/libs/kiss/include -I/d/openFrameworks/libs/pugixml/include -I/d/openFrameworks/libs/rtAudio/include -I/d/openFrameworks/libs/tess2/include -I/d/openFrameworks/libs/uriparser/include -I/d/openFrameworks/libs/uriparser/include/uriparser -I/d/openFrameworks/libs/utf8/include -I/d/openFrameworks/libs/utf8/include/utf8 -I/d/openFrameworks/libs/videoInput/include -I/d/openFrameworks/libs/openFrameworks -I/d/openFrameworks/libs/openFrameworks/3d -I/d/openFrameworks/libs/openFrameworks/app -I/d/openFrameworks/libs/openFrameworks/communication -I/d/openFrameworks/libs/openFrameworks/events -I/d/openFrameworks/libs/openFrameworks/gl -I/d/openFrameworks/libs/openFrameworks/graphics -I/d/openFrameworks/libs/openFrameworks/math -I/d/openFrameworks/libs/openFrameworks/sound -I/d/openFrameworks/libs/openFrameworks/types -I/d/openFrameworks/libs/openFrameworks/utils -I/d/openFrameworks/libs/openFrameworks/video  -MMD -MP -MF /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/sound/ofSoundBuffer.d -MT/d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/sound/ofSoundBuffer.o -o /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/sound/ofSoundBuffer.o -c /d/openFrameworks/libs/openFrameworks/sound/ofSoundBuffer.cpp
In file included from D:/openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp:10:
C:/msys64/mingw64/include/sndfile.h:356:33: error: conflicting declaration 'typedef struct sf_private_tag SNDFILE'
  356 | typedef struct sf_private_tag   SNDFILE ;
      |                                 ^~~~~~~
In file included from D:/openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp:1:
D:/openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.h:18:33: note: previous declaration as 'typedef struct SNDFILE_tag SNDFILE'
   18 | typedef struct SNDFILE_tag      SNDFILE ;
      |                                 ^~~~~~~
make[2]: *** [makefileCommon/compile.core.mk:238: /d/openFrameworks/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/sound/ofOpenALSoundPlayer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [makefileCommon/compile.core.mk:212: Debug] Error 2
make: *** [makefileCommon/compile.core.mk:228: all] Error 2

Bernd@LAPTOP-BERND MINGW64 /d/openFrameworks/libs/openFrameworksCompiled/project
$

**Comment by ofTheo** [comment]
Ah I think this is fixed in the nightly builds ( bottom of the OF download page )
Can you try the nightly msys2 release? 

Thanks!

**Comment by elegolo** [comment]
Compilation error free done with nightly build, lots of warnings though.

Thanks for this fast reply!
