### ISSUE TITLE
Reinstallation speedup:  install_dependencies.sh

### ISSUE THREAD

**Issue by elegolo** [openframeworks/openFrameworks#7025]
Doing reinstall, already installed modules are claimed with Warning: <module> is up to date -- skipping.
Instead of skipping, core and full system upgrade are called uselessly for each, consuming time.

**Comment by dimitre** [comment]
any suggestion of how to do that?

**Comment by elegolo** [comment]
Sorry, no. I do know nothing about the technology involved in your setup scripts and the possibilities for state requests within. Maybe it not possible and this is remaining as a nice-to-have only.

**Comment by oxillo** [comment]
@elegolo : Can you detail the platform where you've seen it ?

Generally the install_depencies scripts try to only install required packages.  For example, in MSYS2, we use pacman --needed <list of packages>.
I think that package-managers does a better job in checking what is required than what we could achieve by checking by ourselves.

If you think that this answer, could you please close the issue ?

**Comment by elegolo** [comment]
Sorry, no. I've put away that project. So, of course, I do close this issue.
