### ISSUE TITLE
CI / Github Actions - Update macOS to 11.0

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7036]
Notice says macOS environment for 10.15 will be removed as of August 30th. 
Need to update the CI script to 11.0

**Comment by dimitre** [comment]
Nice! I think updating to macOS 12 already is ok too
here are the list of tools available on macos-12 
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
```
    runs-on: macos-12
```
```
        DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"
        SDKROOT: "/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
```
