### ISSUE TITLE
Speed up Xcode - Default to NATIVE_ARCH instead of STANDARD_ARCH for Debug and Release

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7043]
Currently when you are building in Debug or Release in Xcode it is compiling both arm64 ( M1 ) and x86_64 ( Intel ) code for every changed file. 

This makes Xcode builds more than 2x as long for each compile. 

Compiling the core openFrameworksCompiled Xcode Project on an Intel MacBook Pro with:
`$(NATIVE_ARCH)` = **56s**
`$(STANDARD_ARCHS)` = **1m 58s** to **2m 20s** 

![image](https://user-images.githubusercontent.com/144000/183996789-8722a5f0-a200-40f4-8b3d-a317e133208c.png)

Suggestion: 
- Switch the the default Architecture in build settings ( for Debug and Release ) from `$(STANDARD_ARCHS)` to `$(NATIVE_ARCH)`. 
- Add a Deploy scheme similar to App Store to compile for both architectures. So we have `Debug`, `Release`, `Deploy`, `App Store`
- Or have a comment in the Project.xcconfig where it can easily be switched. 

ping @ofZach @dimitre @danoli3

**Comment by dimitre** [comment]
Great! Let's do it.
Not sure if it is needed to have a Deploy scheme.
We can do it already by Build -> Any Mac

**Comment by ofTheo** [comment]
Ah yes - I think then all we need to do is change Release to `Build Active Architecture Only` and make sure the `Any Mac` vs `My Mac` gets passed through to the openFrameworksCompiled Project. 

Or maybe we don't even worry about that last part as i t shouldn't be getting recompiled often anyway?

**Comment by dimitre** [comment]
I suppose (it is a guess) it will be passed automatically
Maybe it will try to compile everything anyway if there is some architecture missing, but we can test.
As I've been working with XCode template I can do this as a PR soon (maybe tomorrow)

**Comment by ofTheo** [comment]
Awesome - thanks @dimitre!

**Comment by dimitre** [comment]
@ofTheo I've just tested and NATIVE_ARCH doesnt work here when building Intel (Rosetta on M1) or Universal
so instead I suggest we use the variable $(ARCHS) which pass only the selected architecture(s) in drop down.
seems to be working great here.

I suggest also we change additional extensions from SSE3 (now) to Platform default.

**Comment by dimitre** [comment]
BTW it is a great improvement, since we are working a lot with the core ⚒️

**Comment by ofTheo** [comment]
closing @dimitre as the nightly builds seems to be just building the active architecture. 👍
