### ISSUE TITLE
ofSplitString is slow! 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7059]
In some cases the difference can between ofSplitString and this implementation can be 200:1 in terms of speed. 

Using a different implementation ( that only works for single chars as seperators )

```

//--------------------------------------------------------------
static vector<string> splitString(const string &s, char delim) {
    stringstream ss(s);
    string item;
    vector<string> tokens;
    while (getline(ss, item, delim)) {
        tokens.push_back(item);
    }
    return tokens;
}
```

The test ( csv.txt is just random comma separated values ):

```
    float t1 = ofGetElapsedTimef();
    auto arr = ofSplitString( ofBufferFromFile("csv.txt"), ",");
    float t2 = ofGetElapsedTimef();
    
    float t3 = ofGetElapsedTimef();
    auto arr2 = splitString( ofBufferFromFile("csv.txt"), ',');
    float t4 = ofGetElapsedTimef();
    
    cout << " arr size " << arr.size() << " arr2 size " << arr2.size()  << endl;
    cout << " time for OF " << t2 - t1 << " time for splitString " << t4-t3 << " how much faster? " << (t2-t1)/(t4-t3) << endl;
    
```
 
```
 arr size 978 arr2 size 978
 time for OF 1.48444 time for splitString 0.00714064 how much faster? 207.887
```

For someone trying to load a large textile the difference was 10 minutes vs 7 seconds. 
Thinking we can probably speed up the current ofSplitString without loosing functionality.

**Comment by dimitre** [comment]
One idea here, before having the full solution ready
we can have two functions with the same name, one ready to split fast with a char, and the legacy, slow and compatible one.
and we can update code in OF to use the char one in ofGLUtils.cpp, ofCairoRenderer.cpp, and ofGraphics.cpp
```c++
std::vector<std::string> ofSplitString(const std::string& source, const std::string& delimiter, bool ignoreEmpty = false, bool trim = false);
std::vector<std::string> ofSplitString(const std::string& source, const char & delimiter, bool ignoreEmpty = false, bool trim = false);
```

**Comment by ofTheo** [comment]
@dimitre - good idea - or even just keep the same interface but internally do the char split string if the string size is 1

**Comment by dimitre** [comment]
Yeah nice! I would go for both, and make the string one point to the char one when possible.
Just because char is a lot less complex than string, and 95% of the time a char separator is all we need (like in CSV files or TSV files for example)
I can do a PR if you think it is ok

**Comment by dimitre** [comment]
it will be great to see this one merged. 
suggestion: you can use ```emplace_back``` instead of ```push_back```

**Comment by dimitre** [comment]
wee need this one merged!

**Comment by artificiel** [comment]
interesting, I get different results. in release on M2pro the method above is 2X slower. the code (where `ofSplitStringNew` is the proposed method):
```c++
// tokenizing 1000 copies of Frankenstein
void ofApp::setup(){
    auto frank = ofBufferFromFile("frank.txt");
    std::string stuff;
    for (size_t i = 0 ; i < 1000; i++) {
        stuff +=frank.getText();
    }
    
    for (size_t i = 0 ; i < 5; i++) {
        auto a = ofGetElapsedTimeMillis();
        auto tokens = ofSplitString(stuff," ");
        ofLogNotice("old") << tokens.size() << " tokens in " << ofGetElapsedTimeMillis() - a << "ms";
        
        auto b = ofGetElapsedTimeMillis();
        auto tokens2 = ofSplitStringNew(stuff,' ');
        ofLogNotice("new") << tokens2.size() << " tokens in " << ofGetElapsedTimeMillis() - b << "ms";
    }
}
```
the data: [frank.txt](https://github.com/openframeworks/openFrameworks/files/12851568/frank.txt)

curious to see what is the data that takes 10 minutes? notwithstanding the actual splitting algo, at that scale maybe it's worth looking into allocators.

release results here:

```
[notice ] old: 71548001 tokens in 1810ms
[notice ] new: 71548001 tokens in 3135ms
[notice ] old: 71548001 tokens in 1799ms
[notice ] new: 71548001 tokens in 3053ms
[notice ] old: 71548001 tokens in 1766ms
[notice ] new: 71548001 tokens in 3054ms
[notice ] old: 71548001 tokens in 1789ms
[notice ] new: 71548001 tokens in 3059ms
[notice ] old: 71548001 tokens in 1778ms
[notice ] new: 71548001 tokens in 3039ms
```

for completeness, debug:
```
[notice ] old: 71548001 tokens in 2105ms
[notice ] new: 71548001 tokens in 3234ms
[notice ] old: 71548001 tokens in 2028ms
[notice ] new: 71548001 tokens in 3126ms
[notice ] old: 71548001 tokens in 2034ms
[notice ] new: 71548001 tokens in 3104ms
[notice ] old: 71548001 tokens in 2104ms
[notice ] new: 71548001 tokens in 3145ms
[notice ] old: 71548001 tokens in 2079ms
[notice ] new: 71548001 tokens in 3099ms
```

**Comment by ofTheo** [comment]
Wow @artificiel  
Maybe it is more of an issue on intel vs arm? 

@dimitre do you get similar results?

**Comment by artificiel** [comment]
hmm not near intel right now can't compare... but the difference is still a bit strange. (NB tried splitting on ',' and 'e' and the results are similar.)

one thing I just noticed in your original test is that you are also timing `ofBufferFromFile("csv.txt")`, and maybe the 2nd time (new method that clocked faster) there was some caching action going, at disk or CPU or OS/FS level? if you can get to the same hardware/data conditions, try only timing the split itself.
