### ISSUE TITLE
Xcode Template Issue - Addons not getting added to project 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7067]
@dimitre Not sure if this is a Project Generator Issue or something with the template itself, but it looks like the addon files are not being included in the Xcode project for the examples/ in the nightly builds. 

Seems to be the same for any example that uses addons. 
![image](https://user-images.githubusercontent.com/144000/189214503-826f623a-2ab7-4a79-bca8-566b4a43a4e5.png)

Also the project complains about not finding the addon files ( which makes sense ) 🙂

**Comment by dimitre** [comment]
@ofTheo I think I've mentioned somewhere, the built ProjectGenerator on nigtly builds are not up to date, so it is trying to parse the json file as xml.

**Comment by ofTheo** [comment]
Ahh okay. 
That makes sense as generating new projects worked just not the examples. I’ll see if I can track down why it’s not up to date. 

I do remember now you mentioning that 😁

Thanks!!

**Comment by dimitre** [comment]
Yeah that's it. here is the date modified of a freshly downloaded nightly build
![Screen Shot 2022-09-08 at 21 51 19](https://user-images.githubusercontent.com/58289/189250001-5f996718-1419-44e2-97b4-fcb80fe217e5.png)

**Comment by ofTheo** [comment]
Hmm - actually I think it is a new issue with the update multiple in the projectGenerator.  `--recursive` 

I just tried to generate all the examples again from the Gui PG app in the nightly download and it didn't add addons to the examples. 
But when I do the vectorGraphicsExample on its own via the import button, it works and adds the addon to the project.

So I think there might be a new bug with the update multiple option `--recursive` at the command line app level as it is appears broken in both the gui app and the nightly builds which are generated via the command line app.

**Comment by ofTheo** [comment]
Just to clarify @dimitre - the 28th July 2022 is the correct date for the PG as it is built and packaged whenever the last PR is merged to the PG master.  

So 28th July 2022 corresponds to the last commit: 
https://github.com/openframeworks/projectGenerator/commits/master 

When the osx nightly gets packaged it just pulls that zip in and unzips it - but the zip represents the latest PG build.

**Comment by dimitre** [comment]
I'll investigate the recursive here

**Comment by dimitre** [comment]
Yes, it works without recursive and it doesn't with recursive. 
First question: Did it work with previous versions? 
it seems to be unrelated to xcodeProject.
and all about our relative path "../../../"

**Comment by ofTheo** [comment]
Ah nice find @dimitre ! 👍
Yeah, was going to say I think it was working until recently as the nightly builds script uses `--recursive` for examples generation.

**Comment by dimitre** [comment]
Great I'm investigating this right now and I'll soon have news :)
