### ISSUE TITLE
Missing dependencies in Ubuntu script (Pop OS)?

### ISSUE THREAD

**Issue by javl** [openframeworks/openFrameworks#7097]
Not 100% sure this is a problem on all Ubuntu installs as I don't have any other machines running pure Ubuntu, but I'm using the popular Pop OS which is based on Ubuntu.

Trying to make any of the examples (after running `ubuntu/install_dependencies.sh`) results in three errors and a failed build:

    /usr/bin/ld.gold: error: cannot find -lXi
    /usr/bin/ld.gold: error: cannot find -lXcursor
    /usr/bin/ld.gold: error: cannot find -lXinerama

This can be fixed by installing the following dependencies:
    
    sudo apt install libxi-dev libxcursor-dev libxinerama-dev

**Comment by ofTheo** [comment]
Thanks @javl 
I think this should be fixed by:  https://github.com/openframeworks/openFrameworks/commit/3a96e0355233a157cb2e5d273ff5a84a3ca273b1

And all working in the nightly builds.
