### ISSUE TITLE
Github Actions - fails intermittently opening or releasing network ports

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7106]
If a matrix of actions (osx / osx makefiles) runs in parallel and they start TCP network testing at the same time, one of them fails to bind in IP 127.0.0.1

here is an example of a job failing, and then completing when I use only (re-run failed jobs)
https://github.com/openframeworks/openFrameworks/actions/runs/3139883547/jobs/5100902218

I think this sometimes happens in other matrices too.

![Screen Shot 2022-09-27 at 22 01 04](https://user-images.githubusercontent.com/58289/192663893-9bda2f23-c638-4f2d-809b-4593cede1530.png)

**Comment by ofTheo** [comment]
I wonder if we could remove these from the tests or use random ports so we don't bind the same port?

**Comment by dimitre** [comment]
Good ideas. I like both.

**Comment by dimitre** [comment]
port is random already...

**Comment by dimitre** [comment]
As tests are now commented out I'm closing this one
