### ISSUE TITLE
Github actions - caching broken for macOS

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7136]
This line: 
https://github.com/openframeworks/openFrameworks/blob/master/.github/workflows/build-macos.yml#L46

Is basically caching everything in libs/ including openFrameworks/ and openFrameworksCompiled/ 

So with the Shadow PR the existing files were being used instead of the ones in the PR. 
A fix would be to remove this line and explicitly add a line per library. Or maybe use a pattern that would avoid the OF folders altogether. 

This wouldn't work though:
`libs/*/lib/*` 

as openFrameworksCompiled uses:
`libs/openFrameworksCompile/lib/` 

For not removing the `libs` line would be great. 
Then we can add back in the libraries another way.

**Comment by dimitre** [comment]
ow nice good catch. sorry I didn't realize the compiled was there too.
I've added libs one by one, so it makes this separation. 
I'll check this PR actions twice, so it will build cache and then reuse it.
https://github.com/openframeworks/openFrameworks/pull/7137/checks

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7137
