### ISSUE TITLE
ofxAssimpModelLoader load is ambiguous

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7167]
if we use load with only a string as a parameter
like model.load(fileName);
it cannot differentiate between actual load or deprecated load.

the first thing that come to mind is actually remove the deprecated load, so it only uses the latest.
What do you think @ofTheo ?

**Comment by ofTheo** [comment]
Adding in #7165 as a duplicate.

**Comment by ofTheo** [comment]
closed by #7166
