### ISSUE TITLE
Header files missing in Windows for some first-party addons

### ISSUE THREAD

**Issue by c-mendoza** [openframeworks/openFrameworks#7169]
It seems like the header files for ofxPoco and ofxOpenCv are not being downloaded when requested via `download_libs.ps1`. Not sure if this is a Windows-only issue.

The release version of OF does not have this problem, and is shipping with both the `include` and the `license` folders when appropriate.

**Comment by ofTheo** [comment]
We switched the libs to being hosted on Github Releases - I am guessing those scripts would need to be updated with the correct url. See: https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/download_libs.sh#L38 

If you get it working could you submit a PR? 

Thanks so much!

**Comment by ofTheo** [comment]
closes by #7173
