### ISSUE TITLE
ofxEmscriptenVideoGrabber::listDevices() does not list any devices

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7180]
`ofxEmscriptenVideoGrabber::listDevices()` does not list any devices, while my webcam is connected and works with other programs (vlc/cheese) and the videoGrabberExample does not work with Emscripten (the desktop app does work). I tried this with Ubuntu.
Is it possible to use a webcam with Emscripten and OF or is the ofxEmscriptenVideoGrabber meant for other use cases?

**Comment by ofTheo** [comment]
@Jonathhhan I wonder if it is a browser privacy issue?
I think since the video grabber was written most browsers ask to ask the camera and you have to hit 'allow'. 

We might be missing the code that triggers the permission request?

**Comment by ofTheo** [comment]
This would be the file to look at I believe: 
https://github.com/openframeworks/openFrameworks/addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js

**Comment by ofTheo** [comment]
Looks like the call is now 

```
var constraints = { video: true, audio: true };
navigator.mediaDevices.getUserMedia(constraints);
```

So maybe we need to add this call to the top of the function list:

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js#L21-L26

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia 
[navigator.mediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)

**Comment by Jonathhhan** [comment]
With this changes the videoGrabberExample works: https://github.com/openframeworks/openFrameworks/compare/master...Jonathhhan:openFrameworks:Emscripten_videoGrabberExample-fix
But `vidGrabber.listDevices();` does not work (maybe get the devices from the Java Sript side?), drawing is only possible with `vidGrabber.getTexture().draw();`, the grabber never isInitialized() and it takes some time until vidGrabber.getWidth() is > 0 (it does not work on `ofSetup()`).

**Comment by ofTheo** [comment]
@Jonathhhan could you try this change and see if it fixes the issue?

```
getUserMedia: function(){
        	    var constraints = { video: true, audio: false };
        	    return navigator.mediaDevices.getUserMedia(constraints) || 
        	    navigator.getUserMedia ||
        	    navigator.webkitGetUserMedia ||
        	    navigator.mozGetUserMedia ||
        	    navigator.msGetUserMedia;
        },
```

**Comment by Jonathhhan** [comment]
@ofTheo that doea not change anything. But what seems to work is if I change `html5video_grabber_create()` like this:
```
    html5video_grabber_create: function(){

	        var video = document.createElement('video');
			video.autoplay=true;
			video.pixelFormat = "RGB";

	        var grabber_id = VIDEO.getNewGrabberId();
	        VIDEO.grabbers[grabber_id] = video;
		var texId = GL.getNewId(GL.textures);
		var texture = GLctx.createTexture();
        	texture.name = texId;
		GL.textures[texId] = texture;
		GLctx.bindTexture(GLctx.TEXTURE_2D, texture);
		GLctx.texParameteri(GLctx.TEXTURE_2D, GLctx.TEXTURE_MAG_FILTER, GLctx.LINEAR);
		GLctx.texParameteri(GLctx.TEXTURE_2D, GLctx.TEXTURE_MIN_FILTER, GLctx.LINEAR);
		GLctx.texParameteri(GLctx.TEXTURE_2D, GLctx.TEXTURE_WRAP_S, GLctx.CLAMP_TO_EDGE);
		GLctx.texParameteri(GLctx.TEXTURE_2D, GLctx.TEXTURE_WRAP_T, GLctx.CLAMP_TO_EDGE);
		VIDEO.grabbers[grabber_id].textureId = texId;
	        return grabber_id;

    },
```

**Comment by ofTheo** [comment]
oh awesome! 
this looks promising @Jonathhhan :)
