### ISSUE TITLE
Xcode code sign script: 2 problems with multiple $ITEMS

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7240]
in the Xcode code signing script step, $ITEMS accumulates a newline-separated collection of things found within the app. by default only libfmod.dylib ends up in there and things work. however, when a project has multiple things to sign a problem is revealed: the script modifies IFS like this (line 68): 

`IFS=$(echo -en "\n\b")`

echoing ${IFS} shows that it is now set to "-en"! which happens to have no consequences with the libfmod single-item situation, but does not work when a real list is assembled. I don't know why the -en flags are there in the first place, removing them (`IFS=$(echo "\n\b")`) correctly makes the IFS the newline characters.

then, on line 71 $ITEMS is quoted:

`for ITEM in "${ITEMS}";`

this also breaks the iteration when more than 1 element is present. removing the double-quotes (`for ITEM in ${ITEMS}`) lets the loop work, and code signs everything (I've tested with a project at a path containing spaces).

it's an easy fix and I can submit a pull request, but I'm not sure if something else is at play?

**Comment by dimitre** [comment]
cc @danoli3

**Comment by dimitre** [comment]
I think it is good to go ahead and make a PR. what do you think @ofTheo ?

**Comment by artificiel** [comment]
ok I made #7246 but the resulting pbxproj is quite different from the previous one (even though the only change were the 2 small edits as described above). perhaps an Xcode version thing? I've done it on macOS12.4, Xcode 13.4.1.

**Comment by dimitre** [comment]
To be able to work correctly with projectGenerator project needs to be in JSON format
so I'm using this to convert back after making changes:

brew install jq

```
cd $ofw/scripts/templates/osx/emptyExample.xcodeproj
plutil -convert json $ofw/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
jq --tab . project.pbxproj > ~/Desktop/project.pbxproj
cp ~/Desktop/project.pbxproj .
```

**Comment by artificiel** [comment]
ok got it.

not sure of the best GitHub practice but I removed the previous merge request and created another one with the JSON-variant (and indeed only the element related to the script step are different). #7247

**Comment by dimitre** [comment]
Thank you!
In next PRs you can make commits as you wish, OF uses "squash and merge", so it all become one commit in project history

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7247
