### ISSUE TITLE
ofShader header replacement for glsl version

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7242]
There are quite a few shader examples which would work on GLSL / Emscripten with just a different glsl versions header. 

For example the multiTexture3dExample just needs these two lines for OpenGL ES, but currently it means we have to have two different shader folders for the different platforms: 

https://github.com/openframeworks/openFrameworks/blob/master/examples/gl/multiTexture3dExample/bin/data/shadersGLES/shader.frag#L1-L3

```
#version 300 es
precision lowp float;
```

A possible better solution would be to have a shader header macro which we parse out ( like the includes ) and auto generate the header based on the Major and Minor versions. 

eg:

```
OF_GLSL_SHADER_HEADER

// we are going to use 2 lights
// we also have 2 ofLights in ofApp
#define MAX_LIGHTS 2

uniform sampler2D mapDiffuse;
uniform sampler2D mapNormal;
..........
```

With the changes below to ofShader 

```
	// look for OF_GLSL_SHADER_HEADER header placeholder 
	// this will swap the glsl version based on the OpenGL version set in main.cpp 
	// note this won't always work, but is handy for switching between compatible versions of GLSL based on the system 
	if( ofIsStringInString(source.source, "OF_GLSL_SHADER_HEADER") ){
		auto glRenderer = dynamic_pointer_cast<ofBaseGLRenderer>(ofGetCurrentRenderer());
		if( glRenderer ){
			string header = "#version " + ofGLSLVersionFromGL(glRenderer->getGLVersionMajor(), glRenderer->getGLVersionMinor());
			#ifdef TARGET_OPENGLES 
				//TODO: we should have a getGLSLExtensions for OpenGLES 
				header += "\n#extension GL_OES_standard_derivatives : enable";
				header += "\nprecision mediump float;";
			#endif 
			ofStringReplace(source.source, "OF_GLSL_SHADER_HEADER", header);
		}
	}
```

and an updated 

```

string ofGLSLVersionFromGL(int major, int minor){
#ifdef TARGET_OPENGLES
	if(major>=2){
		return "300 es";
	}else{
		return "ES1";
	}
#else
	switch(major){
	case 3:
		if(minor==0){
			return "130";
		}else if(minor==1){
			return "140";
		}else if(minor==2){
			return "150";
		}else{
			return ofToString(major*100+minor*10);
		}
	case 4:
		return ofToString(major*100+minor*10);
	default:
		return "120";
	}
#endif
}
```

We can use the same shader for both OpenGL and OpenGL ES 

Curious what people think: 
cc @Jonathhhan @dimitre @danoli3 @NickHardeman

**Comment by Jonathhhan** [comment]
That looks great :)

**Comment by NickHardeman** [comment]
This would be really helpful. 
What about adding a define as well so that different parts of the shader could be used for gles, something like:
`#define TARGET_OPENGLES`

**Comment by ofTheo** [comment]
Oh for sure! 
That would be easy to add. 👍

**Comment by ofTheo** [comment]
Going to work on a PR for this. 
cc @NickHardeman @Jonathhhan - anything else apart from the: 
`#define TARGET_OPENGLES` that would be helpful to have set for GLES / emscripten ?

**Comment by NickHardeman** [comment]
I think another function without the arguments would be helpful, ie
`string ofGLSLVersionFromGL();`
This function would internally get the renderer and major and minor version
