### ISSUE TITLE
materialPBR Example does not work in Windows 10

### ISSUE THREAD

**Issue by c-mendoza** [openframeworks/openFrameworks#7267]
Hello OF people,

The materialPBR example is not working on Windows 10. The shaders in ofCubeMapShaders.h have compilation errors because there is some funkiness in the strings that the STRINGIFY macro generates. Replacing STRINGIFY with raw string literals fixes the problem.  Any particular reason why raw string literals are not used?

Tagging @NickHardeman, and thanks for adding all of this goodness to OF!

**Comment by NickHardeman** [comment]
Hi @c-mendoza,
Thank you for testing this on Windows :) 
I can look into the string issue. No strong reason for using the macro; sounds like a straightforward fix to switch to string literals.

**Comment by NickHardeman** [comment]
Hi @c-mendoza, I removed the Stringify function and am using R() which was used previously in ofMaterial for the shaders, so I hope this solves the Windows issue :) #7316

**Comment by NickHardeman** [comment]
I checked on Windows 10 and #7316 has resolved the issue.
