### ISSUE TITLE
How to handle mouse release outside of canvas with Emscripten?

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7272]
It seems that with Emscripten (other than with desktop apps) it is not possible to receive mouse events, if the mouse is outside of the canvas.
Quite some time ago I added:
```
	if(mouseEvent->buttons == 0){
		instance->events().notifyMouseReleased(mouseEvent->targetX * (canvas_width / css_width), mouseEvent->targetY * (canvas_height / css_height), mouseEvent->button);
	}
```
To:
```
int ofxAppEmscriptenWindow::mouseenter_cb(int eventType, const EmscriptenMouseEvent *mouseEvent, void *userData){
	int canvas_width, canvas_height;
	emscripten_get_canvas_element_size("#canvas", &canvas_width, &canvas_height);
        double css_width, css_height;
	emscripten_get_element_css_size("#canvas", &css_width, &css_height);
	instance->events().notifyMouseEntered(mouseEvent->targetX * (canvas_width / css_width), mouseEvent->targetY * (canvas_height / css_height));
	if(mouseEvent->buttons == 0){
		instance->events().notifyMouseReleased(mouseEvent->targetX * (canvas_width / css_width), mouseEvent->targetY * (canvas_height / css_height), mouseEvent->button);
	}	
	return 0;
}
```
To solve the problem. But this affects other cases, so its not a very good solution.
What I want to achive: Get the information, if the mouse was released outside of the canvas without the change mentioned above (otherwise a dragged slider is for example still dragged, if I release the mouse outside of the canvas).

**Comment by artificiel** [comment]
i don't know enough about javascript/canvas to explain how this works but it does track the mouse (and button) outside of canvas (even outside of browser window): https://jsfiddle.net/WolfeSVK/s2tNr/

**Comment by Jonathhhan** [comment]
@artificiel thank you. I will have a look.
