### ISSUE TITLE
ofGetTouchX / ofGetTouchY?

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7273]
I wonder if it would make sense to have those functions (similar to ofGetMouseX / ofGetMouseY).

**Comment by artificiel** [comment]
as TouchEventArgs are implemented with an ID (as multitouch is supported) and modes (up/down/move/tap/etc) it's not clear what an ofGetTouchX() would return -- the position of the most recent touches? it could be convenient for the single-touch devices, or for purposes that don't involve tracking. but it's not like a mouse which is unique and "always at some position".

touch events originate from the various ofApp*Windows; i don't know what that means in the context of emscripten (which i presume you are working from), but i guess the most correct thing would be to map what you can get from the HID layer into the ofTouchEventArgs pattern.

**Comment by Jonathhhan** [comment]
@artificiel I was not aware of that, so than it is better not to have it.
