### ISSUE TITLE
ios sound player and soundstream not working

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#7280]
This is also a forum post (https://forum.openframeworks.cc/t/nightlies-and-ios-sound-input/41221) 

but maybe it is more relevant here. Sound input for iOS is not currently working.

When the `bool ofxiOSSoundStream::setup(const ofSoundStreamSettings & settings)`
function runs it has an error:

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x464630b96110)`
On this line:

       ` [(__bridge SoundInputStream *)soundInputStream start];`

Trying to trace these changes back, it seems maybe they came from this commit:

https://github.com/openframeworks/openFrameworks/pull/6889

EDIT: After some more checking, the sound player also does not work, it exits on another bridged function in load:

`bool ofxiOSSoundPlayer::load(const std::filesystem::path& fileName, bool stream) {
    if(soundPlayer != NULL) {
        unload();
    }

    string filePath = ofToDataPath(fileName);
    soundPlayer = (__bridge void *)[[AVSoundPlayer alloc] init];
    BOOL bOk = [(__bridge AVSoundPlayer *)soundPlayer loadWithPath:[NSString stringWithUTF8String:filePath.c_str()]];
    
    return bOk;
}
`

Giving the EXC_BAD_ACCESS error on this line:
`BOOL bOk = [(__bridge AVSoundPlayer *)soundPlayer loadWithPath:[NSString stringWithUTF8String:filePath.c_str()]];
`

**Comment by artificiel** [comment]
just fooling around with the 12-gauge in the dark as I don't have an iOS dev setup under hand: what happens if you try `__bridge_retained`:

`soundPlayer = (__bridge_retained void *)[[AVSoundPlayer alloc] init];
`

**Comment by fred-dev** [comment]
Thanks for the suggestion, but that doesnt do it. 
`Cast of C pointer type 'void *' to Objective-C pointer type 'AVSoundPlayer *' cannot use __bridge_retained`
I also tried __bridge_transfer, "Moves a Core Foundation pointer to Objective-C with transfer of the ownership to ARC" but this gives the same error. 

I tried these with both the soundstream and sound player classes to no avail.

**Comment by artificiel** [comment]
hmm the `__bridge_retained` should only be used on the allocation, not on the other casts. to be sure I tried this: fresh download of iOS nightly, open soundPlayerExample, remove `[vocals release];`, compile & run, get `EXC_BAD_ACCESS`, change line 28 of ofxiOSSoundPlayer.m to 

`soundPlayer = (__bridge_retained void *)[[AVSoundPlayer alloc] init];`

and it runs. it's presumably a good idea to decrement the count with a `CFRelease(soundPlayer);` in the `unload()` method. (but someone else with a firmer grip on ARC should be reviewing all that).

(macOS13.1 / iOS15.3.1). with similar doctoring the sound stream example also runs.

perhaps your code has some allocation subtleties? if you don't mind posting a compilable project please do so!

**Comment by fred-dev** [comment]
@artificiel thanks that did the trick. I don't really understand what implications that might have but this makes input and output work. Out of curiosity did you need to add any code to request permission for mic access, or just the permission string in the info.plait?

**Comment by artificiel** [comment]
OK good! although I am also not totally sure how solid this fix is... pinging @2bbb @danoli3 @ofTheo who were busy on #6889: is this the correct way of handling the audio player / sound stream pointer lifetime issue? (and maybe it applies to other things that have been moved to ARC?). it's a somewhat urgent issue to fix as the nightlies are now the recommended download!

As for your question about input, I just now tried the fresh input example: after fixing the _retain had this error in the console:

```
2023-01-28 21:09:10.351403-0500 audioInputExample[1675:438857] [access] 
This app has crashed because it attempted to access privacy-sensitive data without
a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription
key with a string value explaining to the user how the app uses this data.
```

I added the key, re-ran and got a permission request popup, and then input worked -- so no code per se.

**Comment by artificiel** [comment]
hey! I actually spoke too fast -- the sound does not actually come in (I thought it was audio-reactive and was a bit fast in concluding...). so the app runs but the "buffers received" stay at 0.

what I had to do to make it work was to postpone the streaming, by disabling line 71 here:
https://github.com/openframeworks/openFrameworks/blob/625df269a462dcbc988ca0bcd90aafd0b66767bf/addons/ofxiOS/src/sound/ofxiOSSoundStream.mm#L71

and inserting `ofSoundStreamStart();` in the `touchDown()` method. (so it concretely starts streaming after a touch).

please let me know if this aligns with what the behaviour you see?

I have no idea what is the real problem and why this is a solution, but something in there is not totally tight! note that the stream out works fine (with the `_retained` fix) and does not need that "delay".

**Comment by 2bbb** [comment]
I try to fix this problem and maybe PR-7283 got work.

please check it.

**Comment by fred-dev** [comment]
In my testing soundstream now seems to work for me, and AVSoundPlayer also works now, but ofSoundPlayer does not.

**Comment by dimitre** [comment]
@fred-dev can you pull the PR again and test ?
