### ISSUE TITLE
oscParameters Receiver + Sender not working with ofParameter<void>

### ISSUE THREAD

**Issue by stephanschulz** [openframeworks/openFrameworks#7284]
I noticed that with OF0.11.2 and of_v20230129_osx_release on macOS 12.6 on macbook pro with arm64 chip, xcode 13.4.1 the oscParameter sending for a ofParameter<void> does not get received.
I modified the examples and also added a listener to react to a <void> being send. But seems to not work. 

`oscParametersSenderExample`
https://gist.github.com/stephanschulz/1594b4c92847804589b8a174ec185388

`oscParametersReceiverExample`
https://gist.github.com/stephanschulz/58b82dc7e102fb65d11b43e26e239d41

**Comment by roymacdonald** [comment]
This has to do with the way ofParameters are checked in order to be sent:
```
//--------------------------------------------------------------
void ofxOscSender::sendParameter(const ofAbstractParameter &parameter){
	if(!parameter.isSerializable()) return;
....
}
```

in the case of an ofParameter<void>m its `isSerializable()` function returns false.
It would be super nice being able to send ofParameter<void> through osc
