### ISSUE TITLE
no openssl in ofxPoco on windows.

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#7292]
Maybe this is a deliberate omission, but every other platform has openssl included in ofxPoco except for windows. I was using an addon that depended on it and added it manually to my build, but I am assuming this would live in the apothecary (whcih sadly is beyond my understanding at the moment). 

Is there a reason for this omission, or is it a mistake?

**Comment by danzeeeman** [comment]
it looks like something is up with ofxPoco and how it is setup on windows.

**Comment by danzeeeman** [comment]
POCO was built for windows with POCO_EXTERNAL_OPENSSL_DEFAULT = POCO_EXTERNAL_OPENSSL_SLPRO and is looking for the wrong openssl lib names

**Comment by danzeeeman** [comment]
I'll look at rebuilding poco with the right settings using the openssl we ship for VS2019

**Comment by danzeeeman** [comment]
@fred-dev https://drive.google.com/drive/folders/1koqR6sytOHbuW5aS-QWE9bS_xvXm-q0Q?usp=drive_link drop those in you v0.12 package and it should work

**Comment by danzeeeman** [comment]
this is going to be addressed in v0.12.1
