### ISSUE TITLE
Current master (nighltly) does not compile for Raspberry pi Bullseye

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#7299]
I am on a stock standard Bulseye installation (going through the standard steps from the RPI website. I followed the download instructions for OF, but i used a nightly download [of_v20230204_linuxarmv6l_nightly.tar.gz](https://openframeworks.cc/ci_server/versions/nightly/of_v20230204_linuxarmv6l_nightly.tar.gz)

**In the current version of bullseye the grpahics setup allows for the Legacy  non-GL driver of GL (Full KMS) - not fake kms

Running `make Release -C /home/raspberry/openFrameworks_DNL/libs/openFrameworksCompiled/project`

(the _DNL is there as I had a nightly download and a GIT pull, the nightly download has the suffix)

Gives a bunch of GL errors compiling ofShadow:

`    | 
/home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.cpp: In member function ‘void ofShadow::_allocateFbo()’:
/home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.cpp:1084:9: error: expected unqualified-id before ‘=’ token
 1084 |  Status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
      |         ^
/home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.cpp:1089:13: error: expected unqualified-id before ‘!=’ token
 1089 |  if (Status != GL_FRAMEBUFFER_COMPLETE) {
      |             ^~
In file included from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/EGL/egl.h:39,
                 from /home/raspberry/openFrameworks_DNL/libs/openFrameworks/utils/ofConstants.h:213,
                 from /home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShader.h:10,
                 from /home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.h:9,
                 from /home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.cpp:8:
/home/raspberry/openFrameworks_DNL/libs/openFrameworks/gl/ofShadow.cpp:1091:74: error: expected primary-expression before ‘int’
 1091 |   ofLogError("ofShadow :: _allocateFbo : Frame buffer error, status") << Status;
`
I thought I would attempt to try the master from git directly but get a different error: 

`in file included from /home/raspberry/openFrameworks/libs/openFrameworks/utils/ofUtils.h:5,
                 from /home/raspberry/openFrameworks/libs/openFrameworks/types/ofParameterGroup.cpp:1:
/home/raspberry/openFrameworks/libs/openFrameworks/utils/ofConstants.h:278:10: fatal error: tesselator.h: No such file or directory
  278 | #include "tesselator.h"
`

This occurs from running `make Release -C /home/raspberry/openFrameworks/libs/openFrameworksCompiled/project`

or from running  compileOF.sh  in  /home/raspberry/openFrameworks/scripts/linux

Any clues on how to fix this and run the current master or nightlies on RPI bullseye?

**Comment by fred-dev** [comment]
Ok, it seems the supe rcool ofShadow class by @NickHardeman gets this error on RPI (maybe other platforms). IT seesm that Status is not a good option for a variable name - this is lin line 962 of ofShadow
	`GLenum Status = GL_FRAMEBUFFER_UNSUPPORTED;`
Changing that to a non keyword (I tried gl_read_status) lets this compile on RPI.

**Comment by dimitre** [comment]
Great finding @fred-dev I think this change deserves a PR. what do you think @ofTheo @NickHardeman ?

**Comment by cyphunk** [comment]
This issue of use of standard keywords shows up a lot. I ran into it at same step due to opencv use of "status" keyword and then boost use of "id" keyword.

Discussion of "status" [here](https://forum.openframeworks.cc/t/ofxcv-macro-error-on-x11/26022/23) and workaround suggested [here](https://github.com/openframeworks/openFrameworks/pull/6862) was to modify opencv ``sed -i 's/\<Status\>/EnumStatus/' /usr/include/opencv4/opencv2/stitching.hpp``.  For boost used similar workarond ``sudo sed -i 's/\<id\>/boostid/' /usr/include/boost/system/detail/std_interoperability.hpp``. Probably changing oF instead of modifying system files would be better

**Comment by NickHardeman** [comment]
@dimitre @fred-dev  Ah yes! Thank you for testing on raspberry. I am a bit surprised that a local variable is causing so much fuss with the other libs. I have been working on shadow support for emscripten and can change this variable name when I send the PR, hopefully soon. :)
ofFbo must have avoided it by using lower case:
https://github.com/openframeworks/openFrameworks/blob/72a6ea3296b554093b6c168da4c1a7eb13d4e05d/libs/openFrameworks/gl/ofFbo.cpp#L1178

**Comment by dimitre** [comment]
@cyphunk I find some errors like this when using make, like this enum which uses NO, 
trying to build examples/computer_vision/opencvExample
enum { NO, GAIN, GAIN_BLOCKS, CHANNELS, CHANNELS_BLOCKS };

**Comment by NickHardeman** [comment]
@dimitre @fred-dev I changed the name to gl_read_status and added shadow support for emscripten via this PR #7307

**Comment by ofTheo** [comment]
closed by #7307
