### ISSUE TITLE
openCV examples doesn't build using make with macOS

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7305]
it seems opencv use some defines (NO) in its enums, like this
```
#  warning Detected Apple 'NO' macro definition, it can cause build conflicts. Please, include this header before any Apple headers.
   ^
/Volumes/tool/ofw/addons/ofxOpenCv/libs/opencv/include/opencv2/stitching/detail/exposure_compensate.hpp:66:12: error: expected identifier
    enum { NO, GAIN, GAIN_BLOCKS, CHANNELS, CHANNELS_BLOCKS };
```
which conflicts with this one
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/objc/objc.h:90:13: note: expanded from macro 'NO'
#define NO  __objc_no
```

and for some reason this is not a problem building with XCode but with make, it is.

it can be reproduced using make to build opencv example
examples/computer_vision/opencvExample

**Comment by ofTheo** [comment]
Weird - it seems that its compiling files with ObjC flags in Make. 
A hack would be to do something like: 

```
#ifdef NO 
#undef NO 
#endif 
```

In the ofxOpenCV cpp files ( maybe its just one ) 
But that might break Obj C stuff. 

The better fix would be to figure out why Make is compiling .cpp as ObjC  🙂

**Comment by dimitre** [comment]
Yeah, we have to fix make. I took a look again and it seems to happen in files with extension .hpp

**Comment by dimitre** [comment]
Out of subject, but is there any reason why ofAVFoundationVideoPlayer.m have .m extension instead of .mm ?
