### ISSUE TITLE
multiTexture3dExample draw position

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7325]
Not sure, if it is intended, but if I start to draw in the middle of the screen it draws on the back of the sphere. I would expect it to draw on the front instead. Btw: The material looks nicer now, I guess because of the PBR shader? But there is no light on the sphere anymore.

**Comment by NickHardeman** [comment]
Hi @Jonathhhan, yeah that makes sense. Maybe the camera can be rotated 180º around the y-axis to start. 
The rendering has been switched to ofMaterial using the PBR shader. The lighting should be there, but is probably much more subtle. I can try to emphasize it a bit more so it's noticeable.

**Comment by NickHardeman** [comment]
There's also an #ifdef in there that can switch between ofMaterial and shaders from before ofMaterial received the added functionality. Should the example only use ofMaterial for simplicity or is it helpful to show a full shader implementation as well?
Tagging @ofTheo

**Comment by ofTheo** [comment]
I did test emscripten version and it was working using the ofMaterial shader from file.  

Not really sure what is best, if everything in the material shader can be done with ofMaterial built in - then maybe simplifying it makes sense?  But open either way 🙂

**Comment by NickHardeman** [comment]
@Jonathhhan, 
updated this example to use triangle intersection for draw position, can you give it a whirl? If it seems good, then I'll send a PR. 
https://nickhardeman.com/temp/OFExamples/MultiTexture3dExample/

**Comment by Jonathhhan** [comment]
@NickHardeman very nice, thanks. maybe the draw area can have a non-elliptic circle shape? And somehow I liked before that you need to press a button for drawing and rotate without (but then you can not draw anything on mobile...). TouchDown works for me on mobile, but not touchMove. I will have a look into that.

**Comment by NickHardeman** [comment]
Should be fixed by #7381 and #7380. 
Not going to address Emscripten on mobile for now since the touch drag events aren't coming through. Maybe a separate issue specific to Emscripten can be opened if it needs to be worked on.

**Comment by Jonathhhan** [comment]
@NickHardeman thanks, it works very well. I will have look into the drag events and maybe open an issue. I actually experienced the same with some GUI objects and solved it with drag events (thought that it is normal behaviour): https://github.com/Jonathhhan/ofEmscriptenExamples/blob/main/emscriptenAudioPlayer/src/hSlider.cpp
But would be nice to make it work without those additional drag events (not sure if it makes sense?)...

**Comment by ofTheo** [comment]
closed by #7380

**Comment by Jonathhhan** [comment]
@NickHardeman I tested your link https://nickhardeman.com/temp/OFExamples/MultiTexture3dExample/ again, and in fullscreen mode, touch move works very well on mobile.
