### ISSUE TITLE
Empty link on the Emscripten page

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7329]
On the Emscripten Github page is a list with Emscripten compiled projects. One of them is OF. But the link is dead. Maybe it can be replaced with something working?
https://github.com/emscripten-core/emscripten/wiki/Porting-Examples-and-Demos#utilities

For example from this page: https://arturocastro.net/files/of-emscripten/
But I can also upload an example of choice (maybe one without errors or warnings).
And probably it would fit best in the graphics category?

**Comment by ofTheo** [comment]
@Jonathhhan good catch. 
I am hoping to get the nightly builds on Github Releases soon, once we do that we could easily share a link with the project?

Okay to wait until then? 
Also happy if you want to host a stable nightly in the meantime.

**Comment by Jonathhhan** [comment]
@ofTheo no hurries at all :)
