### ISSUE TITLE
proper way to link CoreHaptics.framework within ofxiOS

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7340]
I have a basic CoreHaptics wrapper. there are a couple of design assumptions  that match my project's specs (in essence, direct control of amplitude/frequency) but I catch as many NSErrors as possible so if someone else's conditions are different it should be fairly easy to navigate and add fancier things.

for it to work it needs to link CoreHaptics.framework, which I added in the project's target "Link Library" phase.

But I'd like to PR it into ofxIOS. I presume it should be linked within the iOS static lib, but it does not work when the framework is added to that target. I'm not sure what I'm doing wrong and am a bit confused about the hierarchy of ofxiOS (there's no addon_config.make so cannot add the framework there), so my question is: 

what is the correct way of adding a framework to ofxiOS? (otherwise it's only a matter of adding ofxiOSCoreHaptics.h and ofxiOSCoreHaptics.mm in utils).

**Comment by dimitre** [comment]
Does it help if you try to add like this?
https://github.com/astellato/ofxSyphon/blob/master/addon_config.mk

**Comment by artificiel** [comment]
I think that would work if I make ofxiOSCoreHaptics into a "normal addon" but since it is only depending on iOS includes I think it belongs within ofxiOS? (along ofxCoreMotion, CoreLocation, CoreEtc...? so that it "just works" within an iOS project).

**Comment by 2bbb** [comment]
@artificiel 
maybe you need to edit `scripts/templates/ios/emptyExample.xcodeproj` and `libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj` to add `CoreHaptics.framework`.

**Comment by artificiel** [comment]
thanks for the pointers! the missing link was adding `-framework CoreHaptics` to `libs/openFrameworksCompiled/project/iOS/CoreOF.xcconfig`

#7343
