### ISSUE TITLE
ofxAssimpModelLoader: alpha blending and GL version

### ISSUE THREAD

**Issue by ammlyy** [openframeworks/openFrameworks#7348]
Hello everyone.
I'm using ofxAssimpModelLoader to load an .obj I created in Blender. It has a texture with different alpha values, some of them are even completely transparent.
Everything works fine using GL version <= 2, and the transparent texture gets correctly rendered using  ofEnableDepthTest() and ofEnableAlphaBlending().
As soon as I switch to GL >= 3, the parts of the model that should be transparent turn black. 
I need newer versions of openGL. Any clues on how to solve the issue?
I played a little bit with it but got stuck.

Thanks for your help!

**Comment by NickHardeman** [comment]
Hi @ammlyy, what version of OF are you using? The nightlies (at bottom of download page) should support alpha with GL3+. 
See this example via Emscripten. Press '2' to view the flight helmet and note the transparency in the goggles. 
[Assimp Example](https://nickhardeman.com/temp/OFExamples/AssimpExample/assimpExample.html)

**Comment by ammlyy** [comment]
@NickHardeman you're right. I was using the stable version. Thanks for the support!
