### ISSUE TITLE
Compile with OpenGL fails on MinGW

### ISSUE THREAD

**Issue by donarturo11** [openframeworks/openFrameworks#7359]
OS: Win10
MSYSTEM: MINGW64
Compiled project: [BrainwaveOSC](https://github.com/donarturo11/BrainWaveOSC)
Current result: ```D:/a/_temp/msys64/mingw64/include/GL/wglew.h:114:9: error: typedef 'BOOL' is initialized (use 'decltype' instead)```
Expected result: No error
Advanced description:
Application is compiled successfully on Linux and MacOS, but compiling on MinGW throws compiler error.
In attachment log from github workflow.
[BrainwaveOSC-github-workflow-log.txt](https://github.com/openframeworks/openFrameworks/files/10855278/BrainwaveOSC-github-workflow-log.txt)

**Comment by donarturo11** [comment]
@ofTheo To resolve this issue, try to compile on MinGW clang64 (after small modifications in scripts) or what thing should cause this error?

**Comment by oxillo** [comment]
I've managed to reproduce. 
The error occurs when compiling .mm files. If I rename .mm files to .cpp, compilation works.

BOOL in Objective-C conflicts with Windows BOOL definition.

I do not think it is an OF issue.  
@donarturo11  Can you  close the issue ?

**Comment by donarturo11** [comment]
Thank you very much and I'm sorry that I asked to wait too long for reply. I didn't test this solution like renaming .mm files.
