### ISSUE TITLE
Ubuntu 22.04 and libgstreamer in ci scripts

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7370]
install scripts doesn't work. any naming change on libgstreamer?

**Comment by ofTheo** [comment]
Hmmm. Whats the error message you are getting? 

I thought we had updated the install scripts for Ubuntu to work with 22.04

**Comment by dimitre** [comment]
Maybe it is just the CI scripts, edited the title
related here: https://github.com/openframeworks/openFrameworks/pull/7346/checks

**Comment by ofTheo** [comment]
Yeah I think it might be a CI only issue - the error seems to do with: `libunwind-dev` you could try adding that to the list ahead of libgstreamer-dev and see if that fixes it? 

Never seen that before though.

**Comment by dimitre** [comment]
I think this can be now closed right?

**Comment by ofTheo** [comment]
ah yes! closed by #7496
