### ISSUE TITLE
Nightly builds stay at the 6th of march

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7375]
Not really an issue for me, just want to mention it...
https://openframeworks.cc/download/

**Comment by dimitre** [comment]
Thanks for mentioning. 
it seems to be related to of::filesystem PR which broke PG for some time. 
now it seems to be working on actions. le't see if things normalize

**Comment by dimitre** [comment]
Finally new nightly builds generated! I'll be closing this one
