### ISSUE TITLE
of::filesystem in macOS using make defaults to boost::filesystem

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7384]
Is this the intended behavior? or maybe there is some work needed in makefiles?
Thanks

**Comment by ofTheo** [comment]
Hmm. It should be setting the C++17 flag. 
If it is then the code in ofConstants is not detecting it correctly. 

It might not be setting the C++17 flag though. That’s probably the most likely.

**Comment by dimitre** [comment]
I think make is not using c++17 / c++1z yet. 
Maybe for compatibility reasons? 
I've seen -mmacosx-version-min=10.9 too

**Comment by ofTheo** [comment]
Ahh yeah, 

I think it would be safe to change this line to C++17 and the min os line above. 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/config.osx.default.mk#L81

People could always define those vars if they want to build C++11 instead.
