### ISSUE TITLE
Nightlies VS Projects are broken

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#7401]
The following output is produced when I try to compile the VS projects included in the download. 
Rebuilding the project with the Project Generator fixes the problem. C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\computer_vision\opencvExample\opencvExample.vcxproj : error  : The imported project "C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\..libs\openFrameworksCompiled\project\vs\openFrameworksDebug.props" was not found. Confirm that the expression in the Import declaration "../../..libs\openFrameworksCompiled\project\vs\openFrameworksDebug.props" is correct, and that the file exists on disk.  C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\computer_vision\opencvExample\opencvExample.vcxproj
C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\..libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\..libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj'.  C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\..libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj

**Comment by dimitre** [comment]
Looking into that.
It is an issue on latest projectGenerator. maybe you are using an older one. 
I've submitted a PR that already works : https://github.com/openframeworks/projectGenerator/pull/328
I don't have a windows computer to test but paths seems correct in sln files

**Comment by ofTheo** [comment]
@dimitre I think the issue in Nick's output is this part. 
examples..libs in the path below. I think trailing slashes are being misses in two places in the paths generated. 

eg: C:\Users\Nick\Desktop\of_v20230317_vs_release\examples..libs\openFrameworksCompiled\project\vs\openFrameworksDebug.props

should be:
C:\Users\Nick\Desktop\of_v20230317_vs_release\examples\..\libs\openFrameworksCompiled\project\vs\openFrameworksDebug.props

going to see what the default paths are set to in the VS nightly zip

**Comment by ofTheo** [comment]
Opened an issue over on PG
https://github.com/openframeworks/projectGenerator/issues/329

**Comment by ofTheo** [comment]
closed by https://github.com/openframeworks/projectGenerator/pull/328
