### ISSUE TITLE
ofxAssimpModelLoader issue on Linux

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7404]
Ive got an old computer with an ancient linux distro here to try some OF stuff, and I found ofxAssimpModelLoader is not working.

The errors are 
```
ofxAssimpModelLoader.cpp:398:36: error: ‘const struct aiScene’ has no member named ‘GetEmbeddedTexture’
      auto embeddedTexture = scene->GetEmbeddedTexture(ogPath.c_str());
                                    ^
ofxAssimpModelLoader.cpp:430:37: error: ‘const struct aiScene’ has no member named ‘GetEmbeddedTexture’
       auto embeddedTexture = scene->GetEmbeddedTexture(ogPath.c_str());
                                     ^
```
but it is really cool to see OF things running in in a really old linux (Elementary os 0.4.1)

**Comment by dimitre** [comment]
It seems assimp libs are not being built for linux, at least I couldn't identify them here
https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/assimp.sh

And maybe nightlies are not packing libassimp.
What do you think @ofTheo ?

**Comment by ofTheo** [comment]
ah yes - Assimp is installed at the system level, so if you have a really old distro the recent addon changes might not be compatible. 

I tried to make it backwards compatible for at least 5-6 years old but beyond that, like the code above just won't be. 

I think it would be okay to close this.  🙂

**Comment by dimitre** [comment]
Yes thanks, maybe this old assimp is being built for c only, not c++. I've seen some functions like this missing one is inside a __cplusplus check
