### ISSUE TITLE
Error.... There was a problem generating your project.... In windows

### ISSUE THREAD

**Issue by Ahmedfarakha** [openframeworks/openFrameworks#7408]
![53a167f724514a87df950a7a8a84c0d47cefc4e4](https://user-images.githubusercontent.com/127881984/226666391-52b00a1c-bfaa-467d-b6af-286fef1e266c.png)

**Comment by ofTheo** [comment]
@Ahmedfarakha - that  is really strange. 
Is it possible to try unzipping of_v0.11.2_vs2017_release.zip to Desktop or Downloads and try again?  I wonder if it is something to do with the D: drive?

**Comment by dimitre** [comment]
try to copy everything in this text box after " Command Failed:"
open cmd
and paste the commands inside cmd window, press Enter

show us what error is happening there

**Comment by Ahmedfarakha** [comment]
![Uploading IMG_20230321_194747.jpg…]()
![Uploading IMG_20230321_194530.jpg…]()

**Comment by Ahmedfarakha** [comment]
![IMG_20230321_194747](https://user-images.githubusercontent.com/127881984/226702329-b99a2342-2848-463d-b7f7-e0a89525c8f3.jpg)

**Comment by Ahmedfarakha** [comment]
![IMG_20230321_194530](https://user-images.githubusercontent.com/127881984/226702420-2195cf42-72fb-459c-8384-a6dac358af2c.jpg)

**Comment by dimitre** [comment]
Great! with this image maybe somebody else more used to windows can jump in and help you making it work.

in the meantime I would suggest you try in a folder outside OneDrive.
Maybe there is an issue with Visual Studio installation and it needs to be reinstalled, but I'm not sure also.

**Comment by ofTheo** [comment]
yup - I think you just need to install Visual Studio 2019 following our guide and it should all work. 
https://openframeworks.cc/setup/vs/

**Comment by ofTheo** [comment]
going to close this for now
