### ISSUE TITLE
Emscripten Wasm.memory Exception

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#7412]
I am using the latest nightly OF build with Emscripten. I can compile everything and run the project locally, however when I upload to my server, it throws the following error and does not run. I have tested on OSX, both Safari and Chrome.  
I noticed that an additional _3DPrimitivesExample.worker.js_ file has been created which seems different than previous versions of OF. 
Here is an example:
https://nickhardeman.com/temp/OFExamples/3DPrimitivesExample/3DPrimitivesExample.html

```
var INITIAL_MEMORY = Module["INITIAL_MEMORY"] || 134217728;
assert(INITIAL_MEMORY >= 65536, "INITIAL_MEMORY should be larger than STACK_SIZE, was " + INITIAL_MEMORY + "! (STACK_SIZE=" + 65536 + ")");
if (ENVIRONMENT_IS_PTHREAD) {
    wasmMemory = Module["wasmMemory"]
} else {
    if (Module["wasmMemory"]) {
        wasmMemory = Module["wasmMemory"]
    } else {
        wasmMemory = new WebAssembly.Memory({
            "initial": INITIAL_MEMORY / 65536,
            "maximum": 2147483648 / 65536,
            "shared": true
        });
        if (!(wasmMemory.buffer instanceof SharedArrayBuffer)) {
            err("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag");
            if (ENVIRONMENT_IS_NODE) {
                err("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)")
            }
            throw Error("bad memory")
        }
    }
}
```
![image](https://user-images.githubusercontent.com/142694/226769212-30f1fe99-b3aa-424f-9b2c-cbbd101b93cd.png)

**Comment by NickHardeman** [comment]
Seems like the correct headers need to be set 
https://emscripten.org/docs/porting/pthreads.html

**Comment by Jonathhhan** [comment]
@NickHardeman yes I know the issue (and should have mentioned it earlier). 
https://emscripten.org/docs/porting/pthreads.html
> Browsers [that have implemented and enabled](https://webassembly.org/roadmap/) SharedArrayBuffer, are gating it behind Cross Origin Opener Policy (COOP) and Cross Origin Embedder Policy (COEP) headers. Pthreads code will not work in deployed environment unless these headers are correctly set. For more information click [this](https://web.dev/coop-coep)

You can also remove the -pthread flags in https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/emscripten/config.emscripten.default.mk then it should work like before (but without pthread support). (Currently there is an issue with ofVideoPlayer, that is not related to pthreads)...

**Comment by Jonathhhan** [comment]
@NickHardeman I can take a look later, how I set the CORS headers...

**Comment by ofTheo** [comment]
@Jonathhhan have you noticed any big improvements with the pthread support? Or are there critical parts of OF that need it? Just wondering if we should make it enabled by default or if it should be an optional flag for people who need it.

**Comment by Jonathhhan** [comment]
@ofTheo for some things it is needed, ofxPd for example. And everything that uses `ofThreads`. But for most of the basic stuff it is not needed. So maybe disable it by default (but with some information how to enable it?)...

**Comment by ofTheo** [comment]
Thanks @Jonathhhan - good to get a sense of how it is used. I am open to either approach, I just imagine some might run into similar issues that @NickHardeman had. 

Maybe there could be a way to enable the cross-origin stuff without PHP?

**Comment by dimitre** [comment]
Did you update the URL in the browser after renaming to .php? 
I know how to do it in Nginx which is the server I use. which is your server? apache?

**Comment by dimitre** [comment]
I've checked and it is apache. I don't know much about this but usually you do the following
ssh into your server and edit httpd.conf (apache configuration)
to serve headers in all of your site or some specific urls.
save the configuration
and restart server with something like 'service httpd restart'

And I think apache allows something like a small configuration file per directory, like a .htaccess file, so you can drop there, the same way you uploaded the html files.

**Comment by NickHardeman** [comment]
Ok I can try that. Thank you

**Comment by ofTheo** [comment]
> @ofTheo this can be made with server side languages or with the server itself.
> Nginx can be configured to serve a specific set of pages with the right headers if needed.
> I can help with this configuration if the idea is embedding examples in OF site

Thanks @dimitre!  I guess I am just thinking if editing an apache configuration is required to host OF emscripten projects then maybe the default should be no threads - with an explanation on how to enable and the server config needed to host.

**Comment by Jonathhhan** [comment]
@NickHardeman it works for me with those flags in `.htaccess` on my webspace:
```
Header set Cross-Origin-Embedder-Policy "require-corp"
Header set Cross-Origin-Opener-Policy "same-origin"
```

**Comment by NickHardeman** [comment]
@Jonathhhan yeah it works for me too :) The link loads correctly with the .htaccess

**Comment by dimitre** [comment]
@NickHardeman do you think the model itself is not good or maybe an issue with ofMesh? 
I've browsed old issues yesterday  and there are some open issues about ofMesh or ofVboMesh and indices.

**Comment by NickHardeman** [comment]
@dimitre it displays correctly on desktop, so not really sure
