### ISSUE TITLE
macOS Window blurry when building with make instead of xcode

### ISSUE THREAD

**Issue by dannylol19** [openframeworks/openFrameworks#7437]
This is the window after I built using `make Release`: (fyi I'm using VSCode)
<img width="105" alt="image" src="https://user-images.githubusercontent.com/83356017/227841009-56e0996c-83ce-4fa3-be37-ac7661a07651.png">

This is the window after I built in xcode:
<img width="105" alt="image" src="https://user-images.githubusercontent.com/83356017/227841137-efe14035-9ae8-43d7-8d65-01a7e5d10403.png">

The xcode build made the window twice as small and also sharper
But when I build it using `make` command in vscode terminal, I get a blurry window that is twice as big

I tried enabling High Resolution in the plist
<img width="332" alt="image" src="https://user-images.githubusercontent.com/83356017/227841269-0d8aa106-868b-4071-89e7-dd28ad8b2b07.png">

Still had the issue.
(I made the project with the of Project Generator, template VSCode)
(Project wasn't touched, its just the default window you get after creating the project)

System information:
OS: macOS Ventura 13.2.1 (22D68)
CPU: Apple M1
Display: Built-in Retina Display 13.3-inch (2560 × 1600)
OF Version: of_v20230326_osx_nightly

**Comment by dimitre** [comment]
which OF version?

**Comment by dannylol19** [comment]
@dimitre > which OF version?
Sorry I forgot to mention: OF Version: of_v20230326_osx_nightly
(and same issue occurred on 0.11.2 so I tried the nightly version with no luck)

**Comment by dannylol19** [comment]
For anyone who wants to use vscode on macOS in the future:
I just ended up using the `xcodebuild` command and then running `open -a bin/mySketch.app` this worked perfectly and I don't have a reason to use `make` anymore.

Thank you, I'm going to close the issue now, but maybe it's something to fix in the makefile sometime in the future.

**Comment by ofTheo** [comment]
Ahh. Looking at the forum post I bet the latest Xcode is enabling retina / high resolution by default now on Ventura ( macOS 13 ). The make behavior was the normal behavior for both up until recently so we might need to find a proper retina solution sooner rather than later or maybe force non retina via plist? 

Can you reopen this issue? It’s definitely something we’ll need to address. 

Thanks!

**Comment by dimitre** [comment]
I was in doubt if the changes were before or after he edited the plist file. 
@dannylol19 if you don't edit the plist file do you experience the icons the same in make and xcode? both blurry?

**Comment by dannylol19** [comment]
Yeah setting NSHighResolutionCapable to false in the plist seems to have made it blurry for the xcode build aswell. The make file is probably not even using the plist because the executable has no icon, but when I do the xcode build the application does have the default OF icon

**Comment by dannylol19** [comment]
@dimitre I found the problem
<img width="998" alt="image" src="https://user-images.githubusercontent.com/83356017/228406800-306639a5-8314-4e15-9144-26b5af347064.png">

The issue is here in /Applications/openFrameworks/libs/openFrameworksCompiled/project/osx/config.osx.default.mk

The Info.plist values are being hard coded, if you can find a way to make it so the user can change these values then the issue would be fixed.

To confirm this, I set `NSHighResolutionCapable` on line 392 to be `true`, and sure enough, when I built with make, the window is rendering properly and isn't blurry anymore.

Also in that same file, the CFBundleIconFile key is never set, so that is why the app doesn't have an icon when built with make.

**Comment by dimitre** [comment]
Yes, feel free to submit a Pull Request if you want to fix the icon.
And even if you want to change the way make inserts the plist file to use the same xcode does. I think that would be great. so both are uniformized.
