### ISSUE TITLE
iOS: "native" examples are broken -- perhaps ARC-related

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7457]
`iosNativeExample` `iosCustomSizeExample` `GLKitNativeARCExample` `iosStoryboardExample` compile and work a bit but crash when the "back" button of the native GUI is pressed (this does not happen under 0.9.0) (feels like something is not retained) — not clear if it's because of a pattern of how these examples are written, or an underlying cause.

**Comment by dimitre** [comment]
@artificiel @2bbb any idea of how to fix them?

**Comment by artificiel** [comment]
I am not familiar enough with the pattern used within these examples to spot the error (they are the remnants of what I was not able to make sense while processing #6723) but the 4 fail in the same manner, so it's probably a simple ARC oversight with the viewControllers.

**Comment by danoli3** [comment]
Yeah definitely some ARC related crashes. Looks like bridge code causing some issues. I've been able to fix by disabling ARC code for some select obj-c code.

**Comment by dimitre** [comment]
@artificiel can this one be closed by https://github.com/openframeworks/openFrameworks/pull/7601 ?

**Comment by artificiel** [comment]
yes!
