### ISSUE TITLE
opencvImageClassification - how to use CUDA support ?

### ISSUE THREAD

**Issue by paul-ferragut** [openframeworks/openFrameworks#7478]
how to use CUDA support for the openCV example opencvImageClassification?

I tried to use CUDA and got the following error:
> [ WARN:0@3.028] global D:\a\apothecary\apothecary\apothecary\build\opencv\modules\dnn\src\net_impl.cpp (179) cv::dnn::dnn4_v20220524::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

In yolo5ImageClassify.h
```
		//enabling CUDA might need a different OpenCV lib built with CUDA support
		//------------------------------------------------------------------------------------------------------------------------------------
		void setup(string modelFile, string classesFile, bool useCuda){
										
			//needs OpenCV 4.6 as earier has errors
			net = cv::dnn::readNetFromONNX(ofToDataPath(modelFile));
			
			if(useCuda){
				std::cout << "Attempt Yolo with CUDA\n";
				net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
				net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA_FP16);
			}else{
				std::cout << "Running Yolo on CPU with OpenCL if available\n";
				net.setPreferableBackend(cv::dnn::DNN_BACKEND_DEFAULT);
				net.setPreferableTarget(cv::dnn::DNN_TARGET_OPENCL);
			}

			//load the classes from text file
			classes.clear();
			auto buffer = ofBufferFromFile(classesFile);
			for( auto line : buffer.getLines() ){
				classes.push_back( line );
			}
		}
```

I don't know how to correctly build openCV libraries with CUDA

So far, I tried building openCV libraries using CUDA support following this [tutorial](https://machinelearningprojects.net/build-opencv-with-cuda-and-cudnn/
)
I replaced the .lib files in of_v20230408_vs_release\of_v20230408_vs_release\addons\ofxOpenCv\libs\opencv\lib\vs\x64\Release
with the new generated .lib files
Then building the example again in OF and getting a system error 
> The code execution cannot proceed because opencv_calib3d460.dll was not found.

**Comment by artificiel** [comment]
hello! I suggest you try the forum with this question; more eyes there than here!

**Comment by ofTheo** [comment]
yeah, I think this is more of a forum question. 
but my guess would be if its looking for the dll you might have built the libraries as shared/dynamic instead of static. 

two options:
1 - find the dlls in the build folder for OpenCV ( maybe in bin/ or in one of the folders where the libs were generated ) and copy them to the bin/ folder of your OF app. 
2 - switch the OpenCV build config to Static and rebuild. 

good luck! you might be fairly close :)
