### ISSUE TITLE
error installing libdrm-dev

### ISSUE THREAD

**Issue by FadriPestalozzi** [openframeworks/openFrameworks#7486]
While following [installation instructions](https://openframeworks.cc/setup/linux-install/) I experience the following error:

![image](https://user-images.githubusercontent.com/16454272/231591361-a127c18a-b8a6-418c-9d97-7c335159c3fb.png)

Installing libdrm-dev
E: Unable to correct problems, you have held broken packages.
error installing libdrm-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libdrm-dev : Depends: libdrm2 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-intel1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-radeon1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-nouveau2 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-amdgpu1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

Running Ubuntu 22.04.2 LTS

![image](https://user-images.githubusercontent.com/16454272/231592522-35a7e5f6-84b7-46b8-8e89-7abb8c6e4a40.png)

Did I miss something?

**Comment by ofTheo** [comment]
Hmm - I just setup OF on a clean 22.04 and only thing different I had to do was
adding `sudo apt-get install libunwind-dev`

If you have an existing install with lots of packages installed there might be a conflict. 
Could you try removing `libdrm-dev` from `scripts/linux/ubuntu/install_dependencies.sh` ?

And see if that works? 

Thanks!

**Comment by ofTheo** [comment]
It might simply be an issue with your system needing an update/upgrade maybe @FadriPestalozzi 
The CI and Nightly build scripts are both running now with 22.04 and I did have to make a few small changes, but nothing to do with libdrm. ( see: https://github.com/openframeworks/openFrameworks/commit/46d1e1669e8d9f715766343cfcb02eaf8f740cc5#diff-beaf40e939cade01fd14418f4bc97aa990b2f2b62f74ee81b01c90b41d38e4e3 )

**Comment by FadriPestalozzi** [comment]
> It might simply be an issue with your system needing an update/upgrade maybe @FadriPestalozzi The CI and Nightly build scripts are both running now with 22.04 and I did have to make a few small changes, but nothing to do with libdrm. ( see: [46d1e16#diff-beaf40e939cade01fd14418f4bc97aa990b2f2b62f74ee81b01c90b41d38e4e3](https://github.com/openframeworks/openFrameworks/commit/46d1e1669e8d9f715766343cfcb02eaf8f740cc5#diff-beaf40e939cade01fd14418f4bc97aa990b2f2b62f74ee81b01c90b41d38e4e3) )
> 
> Edit: maybe try overwriting the install_dependencies script with: https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/ubuntu/install_dependencies.sh
> 
> Maybe also `sudo apt-get remove libdrm-dev` before running `install_dependencies.sh` again?
> 
> And see if that fixes it?

After overwriting install_dependencies.sh as you suggested, the following error is shown:

Installing libdrm-dev
E: Unable to correct problems, you have held broken packages.
error installing libdrm-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libdrm-dev : Depends: libdrm2 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-intel1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-radeon1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-nouveau2 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed Depends: libdrm-amdgpu1 (= 2.4.110-1ubuntu1) but 2.4.113-2~ubuntu0.22.04.1 is to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

file:///home/fadri/Pictures/Screenshots/Screenshot%20from%202023-04-17%2020-25-45.png

**Comment by FadriPestalozzi** [comment]
After again removing libdrm-dev from install_dependencies.sh, error message is:


Installing libcairo2-dev
E: Unable to correct problems, you have held broken packages.
error installing libcairo2-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libglib2.0-dev : Depends: libglib2.0-0 (= 2.72.1-1) but 2.72.4-0ubuntu1 is to be installed Depends: libglib2.0-bin (= 2.72.1-1) Depends: libglib2.0-dev-bin (= 2.72.1-1)
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

**Comment by ofTheo** [comment]
Thanks for trying that @FadriPestalozzi 

It seems like there is some apt / package manager issue which I can't reproduce. 
( In addition to the CI which is installing fine, we also have a 22.04 machine here that can run it without problems ). 

Could you try some of the steps listed here: 
https://unix.stackexchange.com/posts/389170/revisions 

maybe these steps:
`sudo apt-get clean && sudo apt-get update` 
`sudo apt-get upgrade` 

I remember having an issue on a Linux Mint install a while ago which wasn't identical but similar and I just had to update the system packages ( in my case I used the System Gui updater ).

**Comment by FadriPestalozzi** [comment]
> Thanks for trying that @FadriPestalozzi
> 
> It seems like there is some apt / package manager issue which I can't reproduce. ( In addition to the CI which is installing fine, we also have a 22.04 machine here that can run it without problems ).
> 
> Could you try some of the steps listed here: https://unix.stackexchange.com/posts/389170/revisions
> 
> maybe these steps: `sudo apt-get clean && sudo apt-get update` `sudo apt-get upgrade`
> 
> I remember having an issue on a Linux Mint install a while ago which wasn't identical but similar and I just had to update the system packages ( in my case I used the System Gui updater ).

Thanks for your support @ofTheo !

Indeed, seems to be a weird error here. 

I went through the steps listed in https://unix.stackexchange.com/posts/389170/revisions without issues but also without additional installation "...already the newest version"

file:///home/fadri/Pictures/Screenshots/Screenshot%20from%202023-04-17%2021-12-31.png
-33:-94:63:46

The following 2 terminal inputs run without issue but also without any installation (0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.)
sudo apt-get clean && sudo apt-get update
sudo apt-get upgrade

Is it possible to upgrade to 22.10 without having to reinstall software packages?

**Comment by ofTheo** [comment]
> Is it possible to upgrade to 22.10 without having to reinstall software packages?

I think you can yes! 

I would maybe see if the Ubuntu Software Updater gui shows anything you can update? 

![image](https://user-images.githubusercontent.com/144000/232593239-5d8c3371-e071-428c-947e-3bc5cfc7efdb.jpeg)

**Comment by FadriPestalozzi** [comment]
ok, I updated to 22.10 and again copied your suggested code into install_dependencies.sh

upon running sudo ./install_dependencies.sh I get the following error:

Installing libassimp-dev
 Already installed
Installing librtaudio-dev
Selecting previously unselected package librtaudio6:amd64.
(Reading database ... 249769 files and directories currently installed.)
Preparing to unpack .../librtaudio6_5.2.0~ds1-1_amd64.deb ...
Unpacking librtaudio6:amd64 (5.2.0~ds1-1) ...
Selecting previously unselected package librtaudio-dev:amd64.
Preparing to unpack .../librtaudio-dev_5.2.0~ds1-1_amd64.deb ...
Unpacking librtaudio-dev:amd64 (5.2.0~ds1-1) ...
Setting up librtaudio6:amd64 (5.2.0~ds1-1) ...
Setting up librtaudio-dev:amd64 (5.2.0~ds1-1) ...
Processing triggers for libc-bin (2.36-0ubuntu4) ...
Installing libboost-filesystem-dev
Selecting previously unselected package libboost-system1.74.0:amd64.
(Reading database ... 249784 files and directories currently installed.)
Preparing to unpack .../libboost-system1.74.0_1.74.0-17ubuntu1_amd64.deb ...
Unpacking libboost-system1.74.0:amd64 (1.74.0-17ubuntu1) ...
Selecting previously unselected package libboost-system1.74-dev:amd64.
Preparing to unpack .../libboost-system1.74-dev_1.74.0-17ubuntu1_amd64.deb ...
Unpacking libboost-system1.74-dev:amd64 (1.74.0-17ubuntu1) ...
Selecting previously unselected package libboost-filesystem1.74-dev:amd64.
Preparing to unpack .../libboost-filesystem1.74-dev_1.74.0-17ubuntu1_amd64.deb ...
Unpacking libboost-filesystem1.74-dev:amd64 (1.74.0-17ubuntu1) ...
Selecting previously unselected package libboost-filesystem-dev:amd64.
Preparing to unpack .../libboost-filesystem-dev_1.74.0.3ubuntu7_amd64.deb ...
Unpacking libboost-filesystem-dev:amd64 (1.74.0.3ubuntu7) ...
Setting up libboost-system1.74.0:amd64 (1.74.0-17ubuntu1) ...
Setting up libboost-system1.74-dev:amd64 (1.74.0-17ubuntu1) ...
Setting up libboost-filesystem1.74-dev:amd64 (1.74.0-17ubuntu1) ...
Setting up libboost-filesystem-dev:amd64 (1.74.0.3ubuntu7) ...
Processing triggers for libc-bin (2.36-0ubuntu4) ...
Installing libgstreamer1.0-dev
Selecting previously unselected package libelf-dev:amd64.
(Reading database ... 249815 files and directories currently installed.)
Preparing to unpack .../libelf-dev_0.187-4_amd64.deb ...
Unpacking libelf-dev:amd64 (0.187-4) ...
Selecting previously unselected package libdw-dev:amd64.
Preparing to unpack .../libdw-dev_0.187-4_amd64.deb ...
Unpacking libdw-dev:amd64 (0.187-4) ...
Selecting previously unselected package libgstreamer1.0-dev:amd64.
Preparing to unpack .../libgstreamer1.0-dev_1.20.3-1_amd64.deb ...
Unpacking libgstreamer1.0-dev:amd64 (1.20.3-1) ...
Setting up libelf-dev:amd64 (0.187-4) ...
Setting up libdw-dev:amd64 (0.187-4) ...
Setting up libgstreamer1.0-dev:amd64 (1.20.3-1) ...
Processing triggers for man-db (2.10.2-2) ...
Installing libgstreamer-plugins-base1.0-dev
E: Unable to correct problems, you have held broken packages.
error installing libgstreamer-plugins-base1.0-dev
Reading package lists... Building dependency tree... Reading state information... Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies: libgbm-dev : Depends: libgbm1 (= 22.2.1-1ubuntu1) but 22.2.5-0ubuntu0.1~22.04.1 is to be installed
this seems an error with your distribution repositories but you can also
report an issue in the openFrameworks github: http://github.com/openframeworks/openFrameworks/issues

**Comment by FadriPestalozzi** [comment]
PS: during OS-update I agreed to remove a total of 137 deprecated packages

**Comment by ofTheo** [comment]
Hmm can you try: 

```
sudo apt-get remove libgbm-dev
sudo apt-get install aptitude
sudo aptitude install libgbm-dev
```

Then run the install_depencies script from the master branch:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/ubuntu/install_dependencies.sh 

ps: I swear OF is not normally this tricky to install on Linux 🙂

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232607892-5dc7bcf7-148d-4a42-808d-a728f24801ff.png)

**Comment by FadriPestalozzi** [comment]
should I downgrade?

**Comment by ofTheo** [comment]
sure! :)

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232608792-e3650cac-2e85-4d85-bf38-7f861b366cb4.png)

All packages were installed correctly

Updating ofxOpenCV to use openCV4


Yaaaaaaaayyyyyy!!! 

Let's see if I can run a sample to confirm it indeed works!

**Comment by ofTheo** [comment]
Awesome!! 
I should have said if you are not using the nightly build - definitely try that version over 0.11.2. 

https://github.com/openframeworks/openFrameworks/releases/tag/nightly

**Comment by FadriPestalozzi** [comment]
ok, thanks for the hint!

after downloading nightly build and opening blendingExample VSCode complains that there is no "ofMain.h"

maybe this is missing and can be copied from somewhere?

![image](https://user-images.githubusercontent.com/16454272/232612313-f176a786-a200-4cfd-ad14-9f168200918d.png)

**Comment by ofTheo** [comment]
If you go to the Terminal Menu -> Run Build Task -> Build Release
Does it work?

Or in the terminal in the blendingExample folder:
`make Release && make RunRelease` 

VS Code sometimes has issues understanding the OF folder structure without some configuration, but you can typically still build with it. 

In the terminal when you are in the blendingExample folder can you:
`pwd` 

Just curious if you have  spaces or other non Latin chars in your file path.

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232614822-f65cfa8b-d341-486d-94db-9044569d1a30.png)

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232614894-59e4c85b-21ac-4cca-8278-21774797a5d7.png)

**Comment by FadriPestalozzi** [comment]
Tried different build types like clang and g++

**Comment by ofTheo** [comment]
linux arm is the embedded release ( for small Raspberry Pi computers ) - try the linux64 build! 🙂

**Comment by FadriPestalozzi** [comment]
... Murphy ... lol !!!
:-)

**Comment by FadriPestalozzi** [comment]
ok, with linux64 the Build RELEASE option was available

make Release seems to work (compiling for some time)

but "make RunRelease" yields the following error

![image](https://user-images.githubusercontent.com/16454272/232617323-aebe30b3-0fd2-4735-807c-4778d324e684.png)

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232617872-2ecee252-d262-43bc-a26d-91160e22bc3e.png)

**Comment by ofTheo** [comment]
Hmm - could you try a different example?
Maybe `examples/3D/3DPrimitiveExample`

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232618157-62fb51b4-6c3f-47ba-b25e-b8e25c8142a3.png)

**Comment by FadriPestalozzi** [comment]
![image](https://user-images.githubusercontent.com/16454272/232618224-944d45db-ec03-4dd6-8a07-d7b9966a455d.png)

**Comment by FadriPestalozzi** [comment]
gcc installed but maybe not at expected location?

**Comment by FadriPestalozzi** [comment]
make Release && make RunRelease

primitives example compiles!!

![image](https://user-images.githubusercontent.com/16454272/232618488-b6ab2984-dfa3-4307-9d6b-3e1967ee2ba0.png)

**Comment by FadriPestalozzi** [comment]
so does this mean that some examples are more ex-equal than others?

**Comment by ofTheo** [comment]
great! 

yeah, I think we need to do some work maybe to get VS Code working. 
There is probably some modules/extensions that need to be installed. Will look into that in the next few days as we get ready for our 0.12.0 release. 

> so does this mean that some examples are more ex-equal than others?

No I think they should all work. 
It could be something on your system but I'll try the BlendingExample on our 22.04 system tomorrow and see if I can reproduce.
