### ISSUE TITLE
ofConstants not detecting c++17 in some systems

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7497]
first question: will linuxarmv6l be kept in the next release?
if yes it doesn't detect c++17 correctly in constants, but -std=c++17 is correct in compiling parameters. 
I'm using a pragma to output. As it is not defining OF_HAS_CPP17 1 it is using boost::filesystem

```
                 from /home/runner/work/openFrameworks/openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp:1:
/home/runner/work/openFrameworks/openFrameworks/libs/openFrameworks/utils/ofConstants.h:469:43: note: #pragma message: /home/runner/work/openFrameworks/openFrameworks/libs/openFrameworks/utils/ofConstants.h(469) : Reminder: OF_HAS_CPP17 0
  #pragma message(Reminder "OF_HAS_CPP17 0")
                                           ^
```
  
  
it can be seen here: https://github.com/openframeworks/openFrameworks/actions/runs/4724459607/jobs/8381699772

And msys2 is setting OF_USE_EXPERIMENTAL_FS 1 and in the end it is using std::filesystem::__cxx11
I don't know if this changes something but it is using  -std=gnu++17

https://github.com/openframeworks/openFrameworks/actions/runs/4724459599/jobs/8381699767

**Comment by ofTheo** [comment]
> first question: will linuxarmv6l be kept in the next release?
@dimitre yes! that will be the default RPi release until we get the arm64 stuff working 

> if yes it doesn't detect c++17 correctly in constants, but -std=c++17 is correct in compiling parameters.

hmm - that is strange. 
I can look into the msys2 and armv6 issues
