### ISSUE TITLE
ofMediaFoundationPlayer - returns RGBA breaks a bunch of examples 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7504]
![image](https://user-images.githubusercontent.com/144000/232921805-8d44d28a-6c38-4a98-99a1-530134160b44.png)

Probably should default to RGB unless the video has alpha or has OF_IMAGE_COLOR_ALPHA is set. 

tagging @NickHardeman

**Comment by NickHardeman** [comment]
ah, that's not good. #7506 should fix it.

**Comment by ofTheo** [comment]
closed by #7506
