### ISSUE TITLE
Older Linux - checklist to make it work

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7515]
- [ ] fix issue with GLFW_TRANSPARENT_FRAMEBUFFER detecting GLFW version OR, find a way of update GLFW - https://github.com/openframeworks/openFrameworks/pull/7532
- [ ] update config.linux64.default.mk adding PLATFORM_LDFLAGS += -lstdc++fs - https://github.com/openframeworks/openFrameworks/pull/7531

I'm testing now in an old distro equivalent to Ubuntu 16.04 and noticed that it fails  here
```
ofAppGLFWWindow.cpp: In member function 'void ofAppGLFWWindow::setup(const ofGLFWWindowSettings&)':
ofAppGLFWWindow.cpp:200:19: error: 'GLFW_TRANSPARENT_FRAMEBUFFER' was not declared in this scope
    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, settings.transparent);
                   ^
```
this is after this commit
https://github.com/openframeworks/openFrameworks/commit/dac8f6592307ade71b333ccac3b6a8ce9e3f04c6

maybe we can check if the OS supports it. 
cc @danoli3

**Comment by ofTheo** [comment]
Ah. Okay. It probably just needs a GLFW version #ifdef check. 
 But also okay if latest OF doesn’t work with such an old distro.

**Comment by dimitre** [comment]
Yes I agree with both but this is the only thing keeping it from running on abandonware :D

**Comment by dimitre** [comment]
closed by 
https://github.com/openframeworks/openFrameworks/pull/7532
https://github.com/openframeworks/openFrameworks/pull/7531
