### ISSUE TITLE
ofDirectory sort() without parameters issue

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7522]
After the last commit https://github.com/openframeworks/openFrameworks/commit/6ad07c350b7af1a7974966af7368e5f7027bdb74
```dir.sort();``` is not working anymore in my system. XCode doesn't complain but Make does
```
Undefined symbols for architecture arm64:
  "ofDirectory::sort(ofDirectory::SortMode const&)", referenced from:
```
cc @ofTheo

**Comment by ofTheo** [comment]
Hmm - I just tried the dirListExample from the nightly build and don't see the issue. 

@dimitre  can you try the nightly zip and see if it happens for you?

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/144000/234451302-2f361605-7971-421d-a761-03584a7296ac.png">

**Comment by dimitre** [comment]
Great, yes it is working now. I don't know what kind of mess I've done here in my git. Thanks!
