### ISSUE TITLE
[Discussion] macOS - build target options for x86_64 and aarch64?

### ISSUE THREAD

**Issue by ryohajika** [openframeworks/openFrameworks#7543]
Hi people!

First thing first, thanks so much for putting so much effort to maintenance OF! I really appreciate all of your work.

I have been using OF on Mac for long time, including academic research projects. Sometimes I need to use proprietary, precompiled libraries for research projects cannot be disclosed to the public. And it is often a case that the library is compiled only for OSX, x86_64.
When I compile my OF project with Rosetta 2 to support my app with Intel only library running on a Mac with M-series chip, this confuses other addons with their precompiled library if it's not fat (x86_64 + AARCH64) binary. Then I started to thinking of having build target options may make things easier for OF on Mac; Intel or Arm64. Addon developers who needs to bundle precompiled software library no longer need to compile a fat `.a` or `.dylib` library, and may get options to specify different header files or sources depending on the platform they use.

At the same time, this also brings more complexity to OF. The cost of maintenance may increase for the addon developers and OF developers. However, many people use either Intel Mac or Arm64 Mac or even both of them for their projects. This implementation may help other people to some extent.

Do you think would it be reasonable or doable to have build target options for Mac like `macosintel` and `macosarm` as similar to linux build targets like `linuxarm64`, `linuxarmv6l`, `linuxarmv7l` in future OF implementation? I'm not sure if this makes sense to do or others' life easier, but I just want to raise the point here to discuss.

**Comment by ofTheo** [comment]
Thank you for the kind words @ryohajika !

I always thought you could build an app for one arch but still linking to a mixture of FAT libs and X86_64 libs as it should pull just the x86_64 code from the FAT libs. 

What are the errors you are getting? 

I am 90% sure you should be able to get it working - but maybe the Rosetta 2 aspect is making it tricky. 

If not you could always `lipo remove` the libs - ( probably automated ) to remove the arm64 component. 

`lipo -remove [architecture] [location] -o [output_location]`

**Comment by ryohajika** [comment]
Hi @ofTheo !
I don't have any screenshot or error log at the moment, but I'm working on a maintenance of my addon [ofxProtobuf](https://github.com/ryohajika/ofxProtobuf).
First thing first, my project is working no problem! For now I simply use either one of the x86_64 only build or the arm64 only build depending on the target architecture I need to support.

The library got a build system based on CMake but with Bazel (I guess, since I saw it in the configure file), that doesn't support the compilation of a fat library to support both x86_64 and arm64 at a single shot. My goal here is to support whoever wants to use the addon regardless of their Mac CPU type, and I ended up in compiling two different libraries for x86_64 and arm64 then combined the two together by `lipo` command to make up my own fat lib.

However, when I load the fat lib into the OF project and compile it for Intel with Rosetta build option, I got an error on duplicated symbols, which should mean by "oh you loaded two same libraries".

How do you usually resolve the issue something like this? Do you try compile a fat library at single shot by customizing the Makefile or the configure file of the library, or do you distribute two precompiled libraries?

**Comment by ofTheo** [comment]
Hi @ryohajika 

it would be interesting to see what 
`lipo -i your_lib_name.a` says just to make sure it is two different architectures. 

Also would be good to see the duplicate symbols errors as it could point to the issue. 

Searching online I found one suggestion from:
https://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64-under-xcode 

`changing 'No Common Blocks' from Yes to No ( under Targets->Build Settings->Apple LLVM - Code Generation ) fixed the problem.`

> How do you usually resolve the issue something like this? Do you try compile a fat library at single shot by customizing the Makefile or the configure file of the library, or do you distribute two precompiled libraries?

 
In apothecary we do a mixture of lipo of two different libs as you have done, or passing both of the archtectures eg:
`-arch x86_64 -arch arm64` as in: https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/FreeImage/Makefile.osx#L18 

The only time I have seen issues with duplicated arch is when building for iOS where both the device and simulator use arm64 and then there are conflicts with duplicate symbols there.

**Comment by ryohajika** [comment]
@ofTheo 

The combined one says `Architectures in the fat file: libprotobuf.30.dylib are: x86_64 arm64`.

Changing `No Common Blocks` didn't work and I cannot dig in the build log for the duplicate symbols, however, I get many warnings on `no rule to process file of type 'file' for architecture 'x86_64'` in Rosetta build, so I feel like there are some links to the error.

I think I could use apothecary somehow for compiling libprotobuf at some point... I read a formula for opencv and found these CMAKE tags for cross compilation to support the both platforms. I should try the similar.
Is there any template file or procedure document to compile a third party library with apothecary?

**Comment by ryohajika** [comment]
I will close this for now since there's no update on this from my side or any community member. I will revisit this issue later on and give update if there's any progress.
