### ISSUE TITLE
A truly useless library is ...

### ISSUE THREAD

**Issue by kosetin** [openframeworks/openFrameworks#7550]
one that does not compile, does not link, has issues with e.g. libfmod that are known for years and are still not fixed, one that does not support cmake, one for which you lose hours for nothing ...

**Comment by dimitre** [comment]
Let us know how we can help.

**Comment by ofTheo** [comment]
All our nightly builds ( in releases ) link without issue.
 If you are having an issue, how about sharing specific error messages and details instead of offering a cheap and unhelpful critique?

**Comment by artificiel** [comment]
Also @kosetin FYI there is a pull request in the works for CMake #7524; it need more testing you can report to https://forum.openframeworks.cc/t/all-about-cmake/41777/18

Beyond that there is not much value in keeping this open —  welcome to open another issue with actionable information and relevant title.
