### ISSUE TITLE
ofImage loads sRGB 16bpp PNGs, but fails on greyscale 16bpp PNGs using ofx 11.2

### ISSUE THREAD

**Issue by bbogart** [openframeworks/openFrameworks#7552]
I'm working with various deep colour and float images, mostly in opencv, but I sometimes use ofx to render them in various ways. I just realized things were working fine with my RGB 16bpp PNGs (using version 11.2) but my 16bpp greyscale PNGs don't load using ofImage.

Note, I expect the 16bit versions are converted / scaled down to 8bit, which is OK, I'd just like to be able to load and render them without having to manually convert to 8bit.

See this simple test: [16bitTest.tar.gz](https://github.com/openframeworks/openFrameworks/files/11606097/16bitTest.tar.gz)

Since RGB 16bit are working, I suspect this would be an easy fix.

Ben

**Comment by dimitre** [comment]
I've tested here with your PNG in macOS and I can reproduce the issue. the grayscale doesn't draw.
it would be great to be able to work with 16bits greayscale image. 
Did you try using tiff also?
one good place to start is to find if freeimage supports this format, or if it is supported in more recent versions

**Comment by danoli3** [comment]
Updated FreeImage in new libs should have it

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7708
