### ISSUE TITLE
projectGenarator.exe shows js error

### ISSUE THREAD

**Issue by PeterYusuke** [openframeworks/openFrameworks#7554]
I download openFrameworks v0.11.2. 
When I execute projectGnerator.exe, it shows js error below.
```
A JavaScript error occured in the browser process.    
Cannot find module 'moniker' 
```
Is there any way to solve?

My computer.
Windwos 10
Node.js v16.16.0
VisualStudio 2019

**Comment by ofTheo** [comment]
Hi @PeterYusuke - can you try the nightly builds here: 
https://github.com/openframeworks/openFrameworks/releases 

It should be working now. 
If it doesn't work can you reopen the issue. 

Thanks!
Theo
