### ISSUE TITLE
Very teeny tiny issue in materialPBRAdvanced

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#7555]
Just came across all the new rendering features and they look amazing! Thanks @NickHardeman! Was playing around with **materialPBRAdvanced** and it has a commented out line in **main.vert** that let's you modify the geometry. The shadows don't match up if you uncomment that line as though as these shaders are omitted on the shadow pass. Maybe worth adding an extra comment about it to make it clear why that's the shadows aren't 100% correct there. The example works as is though so feel free to close this issue and ignore...

**Comment by NickHardeman** [comment]
Hi @neilmendoza, Thank you. I can add a comment about the geometry so it's more clear. :)

**Comment by neilmendoza** [comment]
Awesome, thanks!

Wonder if it might make sense to have the possibility to pass in a custom depth shader for situations where you do want to change the geometry on the GPU, e.g. this example or mesh instancing.

**Comment by NickHardeman** [comment]
Ah yes, that would definitely be beneficial. Were you thinking passing the custom depth shader to the light or using a material? 
Or maybe both 😉 
Something like 
`material.setShadowDepthPass(depthShaderBuffer.getText(), GL_VERTEX_SHADER, "shadow.vert");`
and the shadow class
`light.getShadow().setDepthPass( &myCustomDepthShader );`
after you're done, `light.getShadow().setDefaultDepthPass();`

So a custom depth pass shader could be used via material (internally it would automatically set the depth shader on the shadow) or via the shadow class directly.

**Comment by neilmendoza** [comment]
The material would probably make the most sense for the situations I'm thinking about, where lighting stays the same but some objects in the scene have their geometry modified on the GPU. Either would work though and who knows what crazy use cases might pop up.

**Comment by neilmendoza** [comment]
So I've been playing around with hacking this functionality into a project by doing...

```
light.beginShadowDepthPass(j);
dynamic_pointer_cast<ofGLProgrammableRenderer>(ofGetGLRenderer())->getCurrentShader().end(); customDepthShader.begin();
...
customDepthShader.end();
dynamic_pointer_cast<ofGLProgrammableRenderer>(ofGetGLRenderer())->getCurrentShader().begin(); 
light.endShadowDepthPass(j);
```

As I'd expect, if I don't enable my custom shader, there are no shadows. However, if I do enable it, the shadows remain the same whatever the contents of the custom shader, even if it is empty. Think I'm probably missing something obvious here about the way OF is handling these shader but not sure what it is. 🤔

**Comment by neilmendoza** [comment]
Hi @NickHardeman, I hacked a custom depth shader into the shadow class. After playing around a little, think it would make more sense in the materials class if we were just going to go one route. There's lots of situations where you'd want to have different geometry affected differently on the GPU, e.g. a background with instanced geometry in front of it. Tried hacking that approach too but if I add something like the below code in the depth pass, the custom depth shader gets overridden somewhere in the renderer back to the depth shader from the shadow class and haven't had a chance to pin down where yet.

`
...
depthShaderFromShadow.end();
customDepthShader.begin();
renderStuff();
customDepthShader.end();
depthShaderFromShadow.begin();
...
`

> Ah yes, that would definitely be beneficial. Were you thinking passing the custom depth shader to the light or using a material? Or maybe both 😉 Something like `material.setShadowDepthPass(depthShaderBuffer.getText(), GL_VERTEX_SHADER, "shadow.vert");` and the shadow class `light.getShadow().setDepthPass( &myCustomDepthShader );` after you're done, `light.getShadow().setDefaultDepthPass();`
> 
> So a custom depth pass shader could be used via material (internally it would automatically set the depth shader on the shadow) or via the shadow class directly.

**Comment by NickHardeman** [comment]
Hi @neilmendoza, I agree integrating it into the material makes sense. Definitely would want to support instanced rendering and GPU vertex manipulation with correct shadows. 
`light.beginShadowDepthPass()` calls `shadow.beginDepth();`
`ofShadow::beginDepth()` calls `glClear(GL_DEPTH_BUFFER_BIT);` So maybe that's getting called twice somehow?

**Comment by neilmendoza** [comment]
@NickHardeman I'm trying to use a custom depth shader after beginDepth() has been called so don't think thats the issue. I think something in the renderer is stopping a custom shader from getting bound during a depth pass. Deep in deadline land at the moment so no time to dig anymore for a couple of weeks.

**Comment by NickHardeman** [comment]
@neilmendoza thank you for looking into this. I submitted a PR #7613 that allows custom depth shaders with shadows. Maybe in the next minor release it can also be integrated into ofMaterial. Took a little bit to track it down. ;)

**Comment by NickHardeman** [comment]
Updated the materialPBRAdvanced example to demonstrate the custom depth shader in shadow passes #7643

**Comment by NickHardeman** [comment]
This PR adds custom depth shader via ofMaterial #7704. Updates textureBufferInstancedExample to show shadows with instanced rendering.

**Comment by NickHardeman** [comment]
Closing this issue as #7704 and #7643 have examples of setting a custom depth shader for shadows and on a material.
