### ISSUE TITLE
Project Generator - OSX 13.3.1 (a) Not Responsive

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#7556]
I downloaded the latest nightly and tried running the project generator. It took a while to load and then showed the "Running on macOS 10.12 or later for the first time?" 
I selected the openFrameworks path and then the interface froze and the app became non-responsive.
Running an older nightly build (of_v20230321_osx_release) version of the project generator works as expected.

**Comment by ofTheo** [comment]
moved to the PG repo  🙂
https://github.com/openframeworks/projectGenerator/issues/376
