### ISSUE TITLE
libgstreamer compile error on LinuxMint

### ISSUE THREAD

**Issue by pedruski** [openframeworks/openFrameworks#7559]
error installing libgstreamer-plugins-base1.0-dev

 Los siguientes paquetes tienen dependencias incumplidas: libgbm-dev : Depende: libgbm1 (= 22.2.5-0ubuntu0.1~22.04.1) pero 22.2.5-0ubuntu0.1~22.04.2 va a ser instalado

thanks

**Comment by ofTheo** [comment]
Are you on the nightly builds of OF or using 0.11.2?

We recommend nightly at this point:
https://github.com/openframeworks/openFrameworks/releases 

Looks like you might need to do an 
`sudo apt-get upgrade` 

But if that doesn't work and you are still having issues you can try installing `libgstreamer-plugins-base1.0-dev` with aptitude 

`sudo apt-get install aptitude`
`sudo aptitude install libgstreamer-plugins-base1.0-dev -y` 

That can often resolve these sort of dependency errors. 
Hope that works for you!

**Comment by pedruski** [comment]
this is my distribution - kept up to date
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"

followed your advice and then tried install again using the nightly build for linux gcc 64
and still:

Installing libgstreamer-plugins-base1.0-dev
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
error installing libgstreamer-plugins-base1.0-dev
Leyendo lista de paquetes... Creando árbol de dependencias... Leyendo la información de estado... No se pudieron instalar algunos paquetes. Esto puede significar que usted pidió una situación imposible o, si está usando la distribución inestable, que algunos paquetes necesarios aún no se han creado o se han sacado de «Incoming». La siguiente información puede ayudar a resolver la situación: Los siguientes paquetes tienen dependencias incumplidas: libgbm-dev : Depende: libgbm1 (= 22.2.5-0ubuntu0.1~22.04.1) pero 22.2.5-0ubuntu0.1~22.04.2 va a ser instalado
this seems an error with your distribution repositories

**Comment by pedruski** [comment]
today Mesa was updated in the Linuxmint repository and I could complete the install !
