### ISSUE TITLE
Windows project generator / 2 issues

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7568]
With the current nightly built the projects do not open automatically when I click "open in IDE" in the project generator. But it works, if I open the project manually. And (that was also the case with older versions), the project generator only seems to work for examples, that are in the examples folder. While with Linux and make it also seems to work, if the patch is in the addons folder, for example.

**Comment by dimitre** [comment]
Yes. already posted here: https://github.com/openframeworks/projectGenerator/issues/377
projectGenerator was modified a lot recently but changes didn't make to nightly yet. I think this week all the changes will be there, so some help testing would be great

**Comment by dimitre** [comment]
Hello @Jonathhhan can you please clarify the second issue?
And test if it is still relevant in latest OF PG? It is now updated in latest nighty

**Comment by Jonathhhan** [comment]
@dimitre sorry for the delay. Tested with todays nightly and I still have the same issues (actually it does not bother me too much...).
