### ISSUE TITLE
Code completion broken on Xcode 14/15-beta

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7569]
A good test case for this is the `examples/math/particles` example
Didn't have this issue with Xcode 12/13. 

<img width="1302" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/144000/b57ee281-ae7d-490c-981f-9758ff7e8d8f">

I tried:
- switching the Xcode project format to 11/12/14
- simplifying the project.xcconfig 
- clearing derrived data
- tried no `using namespace std;` 

Curious if others have had similar issues.

**Comment by dimitre** [comment]
I've tested now in XCode 14.2 and it is working OK. I'm using git master here.
I would try something about xcode-select or even create another user in the computer to see if it is related to folders permissions.

**Comment by dimitre** [comment]
it can be related too to projectGenerator folders (as some were with wrong paths in red)
Hopefully the latest PRs can fix path issues.

**Comment by ofTheo** [comment]
Ahh thanks @dimitre I'll test with latest nightly and maybe try resetting xcode-select. 
I did get at least two other reports confirming it from @danbz and @NickHardeman. I'm on an M1 laptop, so not sure if that is a difference ( on my older MBP I didn't see the issue ).

**Comment by ofTheo** [comment]
Oh sorry. Fixed that yesterday. Should be all good now. Latest PR was rerun and good.

**Comment by ofTheo** [comment]
@dimitre I can confirm it works fine on Xcode 14.1 
Xcode 14.3 and 15 beta both have the issue though. 

Going to stick a note on the forum for now. 

<img width="1728" alt="Screenshot 2023-07-12 at 11 39 53 AM" src="https://github.com/openframeworks/openFrameworks/assets/144000/b583af95-e4b6-40e5-a73e-17be6e3a2a6c">

**Comment by dimitre** [comment]
I think it can be closed now
