### ISSUE TITLE
ofPixels::allocate should init new memory

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#757]
in my opinion, it would make sense for ofPixels::allocate to initialize the new memory to 0. even for large images, i don't think this is such an expensive operation.

i discovered that it is not initialized to 0 when i had a really weird bug -- some code that gave me different results depending on whether i loaded another image before allocating or not. i was expecting OF to act like opencv, which also sets new memory to 0. this would be in line with ofVec*, ofColor, and a few other things, which are all allocated to 0.

**Comment by bakercp** [comment]
Won't fix #5632
