### ISSUE TITLE
linux-armv6: Github action build fails on <optional>

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7573]
I'm using `<optional>` and the armv6 build chokes on the header. I can see `-std=c++17` in the args above so that seems correct in terms of language version, but somehow I get:

```
/home/runner/work/openFrameworks/openFrameworks/addons/ofxOsc/src/ofxOscReceiver.h:5:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
```
other platforms are fine. ideas? in addition to `c++17` GCC 7.1 is the minimal version for `<optional>` (but I don't know how to know which gcc is being used by GitHub)

https://github.com/artificiel/openFrameworks/actions/runs/5560129779/jobs/10156882889#step:6:451

**Comment by ofTheo** [comment]
Looks like gcc 6 is being used for the nightly. 

https://github.com/openframeworks/openFrameworks/blob/master/scripts/ci/linuxarmv6l/install.sh#L33

We could try and bump it up? But we’d need to figure out the tool chain format for the downloaded file

**Comment by artificiel** [comment]
C++17 support is pretty thin in GCC 6. [most features require 7 or 8](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017)

I notice the action in the apothecary/cmake/package side, and perhaps this situation will self-resolve from that work? (I presume nightlies and test builds follow the same pipeline?)

however if that work has a fair amount of uncertainty it is worth it to bump the releases up as least to 8.1 in sync with 0.12, including for linux64 (currently my tests don't make it there as the failure in armv6 stops the process, but it seems the linux64 releases are also gcc6) so that >0.12.0 work can benefit from C++17 without hindrance in the tests/nightlies.

(this whole build thing is not yet limpid to me) is it [this script](https://github.com/openframeworks/apothecary/blob/c25bef39d6b6ef9e2a02bc40a80d7cd9d773a3bc/scripts/linuxarmv6l/CROSS_BUILD_TOOLS/build_cross_gcc.sh) building the rpi_toolchain_gcc6.tar.bz2?

**Comment by artificiel** [comment]
I don't know much about GitHub actions but I presume compiling/testing for rPi is a common task, and this seems to streamline it: https://github.com/pguyot/arm-runner-action

otherwise, these look like they have pretty much the same internal structure as the `rpi_toolchain_gcc6.tar.bz2`: https://github.com/abhiTronix/raspberry-pi-cross-compilers I don't know which one would be more appropriate for our process.

**Comment by ofTheo** [comment]
@artificiel - the arm-runner actions looks perfect!  Thanks, will try that instead.

**Comment by ofTheo** [comment]
Got it working! 
It takes about an hour to run / install dependencies and build but it's much simpler. 

https://github.com/openframeworks/openFrameworks/compare/master...ofTheo:openFrameworks:arm-runner

I think the next step would be to figure out caching or saving to an image and restoring it. 
Will do a PR soon.

**Comment by ofTheo** [comment]
So close to getting a new CI with gcc 9.4.0 running. 
- [x] OF core is building 
- [x] emptyExample is building 
- [ ] allAdoonsExample: fixing some opencv linking issues to do with libarmadillo and then I can do a PR.

**Comment by ofTheo** [comment]
<img width="484" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/144000/a74d493d-4e17-48b1-8be3-98730c27df4a">

cleaning this up and will merge after so we can do the ofRandom PR.
