### ISSUE TITLE
combined event of OF_MOUSE_BUTTON_LEFT && OF_KEY_ALT doesn't work

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7577]
I'm working now on macOS, OF latest master
I can get the events of  OF_MOUSE_BUTTON_LEFT and OF_KEY_ALT separately, but not together.
it work OK if I use OF_KEY_COMMAND 

```c++
	if (ofGetMousePressed(OF_MOUSE_BUTTON_LEFT)) {
		cout << "button" << endl;
	}
	if (ofGetKeyPressed(OF_KEY_ALT)) {
		cout << "alt" << endl;
	}
	if (ofGetMousePressed(OF_MOUSE_BUTTON_LEFT) && ofGetKeyPressed(OF_KEY_ALT)) {
		cout << "button and alt" << endl;
	}

```

**Comment by ofTheo** [comment]
I think this is because on macOS, alt like ctrl modifies the button clicked. 

Ctrl + click becomes `OF_MOUSE_BUTTON_RIGHT` 
and Alt + click becomes `OF_MOUSE_BUTTON_MIDDLE` or maybe scroll wheel click?

**Comment by dimitre** [comment]
Yess thank you!
