### ISSUE TITLE
Can't compile on Ubuntu 22.04 when using addons

### ISSUE THREAD

**Issue by larry104** [openframeworks/openFrameworks#7584]
I successfully compiled openFrameworks  0.11.2 on Ubuntu 22.04 (c++-11). I can run the examples  e.g. polygonExample and I can compile and run the example in apps/myApps/emptyExample. 

BUT, when I try to compile an example .e.g ofxLaser/example_LaserEffects by using the import via projectGenerator and then run the generated make file it fails because it can find cairo.h. So, looking at the g++ command the makefile runs in the first step it literally does not contain any of the required system library includes directories ... 

When I manually add CXXFLAGS to the make command e.g. `make GXXFLAGS="I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/opus -I/usr/include/AL -I/usr/include/x86_64-linux-gnu -I/usr/include/rtaudio"` it eventually fails again and it requires yet another missing flag -std=c++14 ... 

 I must be doing something fundamentally wrong here  ... any ideas?

**Comment by dimitre** [comment]
Did you install dependencies?
Can you try using the nightly build? it is more up to date

**Comment by larry104** [comment]
Yes, I ran the 2 scripts in $HOME/openFrameworks/scripts/linux/ubuntu in addition to some undocumented dependencies followed by the compileOF.sh and compilePG.sh and everything runs fine without any errors.

I will try the nightly build next ...

**Comment by larry104** [comment]
I compiled openFrameworks from github and that seems to work now ... at least the example from ofxLaser compiles and starts just does not show anything but a grey window ... but that's a different problem I guess.

Thanks for the suggestion though!

**Comment by dimitre** [comment]
@larry104 can this issue be closed? Thank you

**Comment by larry104** [comment]
Yes, we can close this issue. It seems installing from github installed quite a few more dependencies. I went back to the 0.11.2 and compiled again and then it worked. Unfortunately, its really hard to pinpoint what the exact issue was though.
