### ISSUE TITLE
ofxAssimpModelLoader, way of drawing internally only specific meshes

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7589]
I've been using some 3d previews to show LED panels in scenography directly from openFrameworks. Most of the time I can use a model and map UV coordinates to show a specific area of the texture, but with the need of output more than one screen it would be great to be able to draw specific model meshes. something like:
model.drawMesh(0);
and it used the same functionality as model.draw();

**Comment by ofTheo** [comment]
Yup! I think this would be excellent to have. 
Marked it for 0.12.1

**Comment by NickHardeman** [comment]
These functions are available in the new ofxAssimp add-on
https://github.com/openframeworks/openFrameworks/blob/dd09e975ad1166ea0cb48edeae35c1f75dc9ed4b/addons/ofxAssimp/src/ofxAssimpModel.h#L232-L234

**Comment by NickHardeman** [comment]
closed by #7776
