### ISSUE TITLE
Emscripten: no support for ofLaunchBrowser()?

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7591]
`ofLaunchBrowser()` is not available in emscripten. maybe there are security concerns that I'm not aware of, but it seems natural to be able to follow links in a web page?

for instance I use it to reference documentation: http://varia.artificiel.org/of/randomexplorer/randomexplorer.html unfortunately I have to take it out to compile.
```c++
#if !defined(TARGET_EMSCRIPTEN)
	ofLaunchBrowser(url_);
#endif
```
expected result would be to compile with the call, and open a window when called (or use the same? perhaps add a string param to `ofLaunchBrowser()` to specific a window name like like a `a href?)

**Comment by Jonathhhan** [comment]
It seems not to be implemented yet:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxEmscripten/src/ofxEmscriptenURLFileLoader.cpp
But in this example it does work, so it should be possible to implement:
https://clip.handmadeproductions.de/
https://github.com/Jonathhhan/ofEmscriptenExamples/blob/main/emscriptenCLIP3/clip.js

**Comment by Jonathhhan** [comment]
And it still does not work with every source because of CORS policy.
The image from the webLoaderImageExample does not work, but the Wikipedia image in this example does:
```
loadImage__deps = ['$GL'];

function loadImage(textureId1) {
	var link = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg/220px-Ash_Tree_-_geograph.org.uk_-_590710.jpg";
	var image1 = new Image();
	image1.crossOrigin = "Anonymous";
	image1.src = link;
	image1.onload = function () {
		GLctx.bindTexture(GLctx.TEXTURE_2D, GL.textures[textureId1]);
		GLctx.texImage2D(GLctx.TEXTURE_2D, 0, GLctx.RGBA, GLctx.RGBA, GLctx.UNSIGNED_BYTE, image1);
		GLctx.bindTexture(GLctx.TEXTURE_2D, null);
	}
}
```

**Comment by artificiel** [comment]
ah! to be clear my question about `ofLaunchBrowser()` is not about downloading stuff within the app, but having the OS tell the browser open an URL! just like in a web page with  `<a href=some.site target=some_window_name>`.

so having the app either load a new URL in place of the current app, or if `target` is defined create a new window and load the URL within.

**Comment by Jonathhhan** [comment]
This opens an url in the same tab:
```
	EM_ASM(
	window.location = "https://forum.openframeworks.cc/";
	);
```
And this in a new tab:
```
	EM_ASM(
	window.open("https://forum.openframeworks.cc/");
	);
```

**Comment by artificiel** [comment]
ah! i see the style...
