### ISSUE TITLE
Nightly releases stopped?

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7614]
@ofTheo 
Last nightly is from 23. 
wondering if intentional or something happened in latest PRs.

**Comment by ofTheo** [comment]
looks like it might be related to the ofRandom PR. #7598

![image](https://github.com/openframeworks/openFrameworks/assets/144000/eef5617a-b47d-4bc1-83c3-e323d9c0c649)

You can see it in the log here: 
https://github.com/openframeworks/openFrameworks/actions/runs/5960085691/job/16166819530

Maybe those need to be include with " " and not < >  ?

**Comment by ofTheo** [comment]
trying here: https://github.com/openframeworks/openFrameworks/commit/8d313d8274b50753ae3dc4db93438cbc01bfd4b3 

as the CI is working so mirroring now what the CI is doing

**Comment by ofTheo** [comment]
Ahh It looks like it is an issue with the projectGenerator not compiling due to #7598 
That would explain why it's only showing up in the nightly builds. 

Probably just needs some additional includes or ofConstants.h to be installed.

**Comment by artificiel** [comment]
hmmm PG includes `ofUtils.h` which now includes `ofRandomEngine.h`, which in turn includes `glm/glm.hpp` and `ofMath.h`, but these are actively excluded from includes in `openFrameworks/apps/projectGenerator/commandLine/config.make`:

https://github.com/openframeworks/projectGenerator/blob/f23599a3125be5b5b5f910db9d7507baad5f412e/commandLine/config.make#L155-L162

commenting the 2 lines makes things compile, but I'm not sure if it's a real solution, and/or how will it propagate to other platform than Make?

or maybe there is better structure for the inclusion of ofRandomEngine/ofRandomDistributions? I put them as includes of ofUtils.h (as the files are in the utils directory) but maybe they should be pulled "higher" and included in ofMain.h instead?

or perhaps even a new directory in openFrameworks/libs/random (the namespace for the functions is of::random::etc so maybe it makes sense to shadow the namespace hierarchy as the filesystem hierarchy?)

**Comment by artificiel** [comment]
[#410](https://github.com/openframeworks/projectGenerator/pull/410)

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/projectGenerator/pull/410
