### ISSUE TITLE
OF_emscripten's max fps is limit 30fps

### ISSUE THREAD

**Issue by byulparan** [openframeworks/openFrameworks#7615]
I use of_20230823 nightly and emscripten 3.1.44(from Homebrew).
I tested on macOS on x86 / m1 both.

I just call `ofSetFrameRate(60);` and draw simple cube.
Desktop version run in 60fps, but emscripten run just 30fps.

Is it setup problem? or limitation of emscripten?

**Comment by Jonathhhan** [comment]
@byulparan 
```
		// choose the render speed with the second argument. 1 is for every screen refresh, 2 for every second, 3 for every third. and so on...
		emscripten_set_main_loop_timing(1, 2);
```
Right now, the default is to render every second screen refresh (I think it is a good compromise)...
With a 60 FPS Monitor that is 30 FPS...
If you change the second argument to `1` it will render every screen refresh (request animation frame).
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Comment by byulparan** [comment]
I couldn't figure out where to insert the above code, 
I put it in the main function or  ofApp::setup function, but it didn't change.

when I put it in ofApp::update did I see it return to 60fps.
(Did I put it in the right place?)

Thank you so much, and I'll close this issue soon!

**Comment by Jonathhhan** [comment]
@byulparan You need to edit it in this file:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
