### ISSUE TITLE
emscripten - video doesn't play in safari if autoplay is enabled

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7626]
Was debugging video playback not working in emscripten and tracked it down to Safari preferences don't autoplay video. 
This gets added automatically for any site you visit if you have it set globally. 

<img width="771" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/144000/bded6d64-76fa-4e17-b227-84a492830b22">

Looking at other suggestions I tried muting the video, but that didn't help. 
Wondering if we could at least detect it and add notice to the webpage to unblock video for that site? 

This is what it looks like on safari: 

![image](https://github.com/openframeworks/openFrameworks/assets/144000/e20d96b1-63cb-4005-8709-152d6c7f9fe9)

Changing the website preference makes it work fine. 

tagging @Jonathhhan @artificiel

**Comment by Jonathhhan** [comment]
@ofTheo since there is no sound in the video, it could work, if volume is set to 0 (not tested yet):
https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide


> As a general rule, you can assume that media will be allowed to autoplay only if at least one of the following is true:
> 
> The audio is muted or its volume is set to 0
> The user has interacted with the site (by clicking, tapping, pressing keys, etc.)
> If the site has been allowlisted; this may happen either automatically if the browser determines that the user engages with media frequently, or manually through preferences or other user interface features
> If the autoplay [Permissions Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy) is used to grant autoplay support to an [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) and its document.

**Comment by Jonathhhan** [comment]
For audio with autoplay there is a warning in the js console: `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

**Comment by Jonathhhan** [comment]
@ofTheo 
setting
`fingerMovie.setVolume(0);`
before
`fingerMovie.play();`
works for me.

**Comment by artificiel** [comment]
I'm really a tourist in JS but this seems promising? support is not complete on all platforms but upcoming — i presume an empty list would be returned for an audio-less video:

  https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks 
  https://caniuse.com/?search=audiotracks

until audioTracks is widely supported this seems to aggregate platform-specific methods into a function: https://stackoverflow.com/questions/41776046/how-to-check-whether-a-video-is-audible#75273988

**Comment by Jonathhhan** [comment]
This seems to work:
```
       if (typeof video.audioTracks == "undefined") {
           video.muted = true;
       }
```
