### ISSUE TITLE
default PG settings fails if apps/myApps does not exist

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7634]
the .gitignore rules take out the apps/myApps dir, but PG defaults to it. this leads to an error:

<img width="466" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/2172370/4d93b492-ad7e-47c1-9a4e-aa66844aafae">

in command line, the reason is revealed:
```
of-dev % /Applications/projectGenerator\ mac\ 2023.app/Contents/Resources/app/app/projectGenerator  -o"/Users/brtn/source_control/of-dev/openFrameworks" -a" " -p"osx,osx"  -t"" "/Users/brtn/source_control/of-dev/openFrameworks/apps/myApps/gcc6singleton"
[notice ] PG v.20\
[notice ] Folder doesn't exist "/Users/brtn/source_control/of-dev/openFrameworks/apps/myApps"
```
should the PG create the missing dir?
or should the dir be included in gitignore?

(and could the error appear in the GUI PG mini-log? the screenshot above is cut, but the line displayed is only the command, not the result)

**Comment by artificiel** [comment]
PG version is fresh download from nightlies (seems aug 30)
<img width="512" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/2172370/12e5d3d9-678d-45aa-96f8-93a1a7df6a9c">

**Comment by ofTheo** [comment]
Maybe safer to just make a myApps folder in our Git repo?

**Comment by artificiel** [comment]
hmm I tried but I cannot figure out the combo between [$OF_ROOT/.gitignore](https://github.com/openframeworks/openFrameworks/blob/master/.gitignore) and [$OF_ROOT/apps/.gitignore](https://github.com/openframeworks/openFrameworks/blob/master/apps/.gitignore) to keep an empty $OF_ROOT/apps/myApps alive (with or without a .gitkeep)
