### ISSUE TITLE
emscripten - audioInputExample - switch to navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7638]
Get this warning in Firefox:
`navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia`

I think this is related to microphone not working on safari as if we use mediaDevices I at least get the pop up asking for mic access

see also: 
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers/Get_microphone_permission 

cc @Jonathhhan

**Comment by Jonathhhan** [comment]
@ofTheo I guess you can just replace it (not sure, but I do not think it solves the mic issue)...

**Comment by ofTheo** [comment]
This seems to work for Safari and Firefox - not sure if we need a backwards compatible solution too?

```
html5audio_stream_create: function(bufferSize, inputChannels, outputChannels, inbuffer, outbuffer, callback, userData) {
    var stream = AUDIO.context.createScriptProcessor(bufferSize, inputChannels, outputChannels);
    var inbufferArray = Module.HEAPF32.subarray(inbuffer >> 2, (inbuffer >> 2) + bufferSize * inputChannels);
    var outbufferArray = Module.HEAPF32.subarray(outbuffer >> 2, (outbuffer >> 2) + bufferSize * outputChannels);

    stream.onaudioprocess = function(event) {
        var i, j, c;
        if (inputChannels > 0) {
            for (c = 0; c < inputChannels; ++c) {
                var inChannel = event.inputBuffer.getChannelData(c);
                for (i = 0, j = c; i < bufferSize; ++i, j += inputChannels) {
                    inbufferArray[j] = inChannel[i];
                }
            }
        }

        {{{ makeDynCall('viiii', 'callback') }}}(bufferSize, inputChannels, outputChannels, userData);

        if (outputChannels > 0) {
            for (c = 0; c < outputChannels; ++c) {
                var outChannel = event.outputBuffer.getChannelData(c);
                for (i = 0, j = c; i < bufferSize; ++i, j += outputChannels) {
                    outChannel[i] = outbufferArray[j];
                }
            }
        }
    };

    if (inputChannels > 0) {
        navigator.mediaDevices.getUserMedia({ audio: true })
            .then(function (audioIn) {
                var mediaElement = AUDIO.context.createMediaStreamSource(audioIn);
                mediaElement.connect(stream);
                AUDIO.mediaElement = mediaElement;
            })
            .catch(function (error) {
                console.log("Error creating audio in", error);
            });
    }

    stream.connect(AUDIO.fft);
},
```

**Comment by Jonathhhan** [comment]
@ofTheo I think it is fine just to use the new one: 
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia?retiredLocale=de#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
