### ISSUE TITLE
remove gluProject and gluUnProject, add screenToWorld, worldToScreen

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#765]
edit: originally this issue was about adding glu functions. now i realize any remaining ones need to be removed. but it's still relevant to have an ofScreenToWorld and ofWorldToScreen. 

this would be really awesome. there is already some code in ofDrawBitmapString that's using gluProject, it would be good to clean it up.

the main issue is that glu is not on iOS, so we'd need to find/write our own implementation.

here's a first pass:

```
GLdouble modelviewMatrix[16], projectionMatrix[16];
GLint viewport[4];
void updateProjectionState() {
    glGetDoublev(GL_MODELVIEW_MATRIX, modelviewMatrix);
    glGetDoublev(GL_PROJECTION_MATRIX, projectionMatrix);
    glGetIntegerv(GL_VIEWPORT, viewport);
}

ofVec3f ofWorldToScreen(ofVec3f world) {
    updateProjectionState();
    GLdouble x, y, z;
    gluProject(world.x, world.y, world.z, modelviewMatrix, projectionMatrix, viewport, &x, &y, &z);
    ofVec3f screen(x, y, z);
    screen.y = ofGetHeight() - screen.y;
    return screen;
}

ofVec3f ofScreenToWorld(ofVec3f screen) {
    updateProjectionState();
    GLdouble x, y, z;
    screen.y = ofGetHeight() - screen.y;
    gluUnProject(screen.x, screen.y, screen.z, modelviewMatrix, projectionMatrix, viewport, &x, &y, &z);
    ofVec3f world(x, y, z);
    return world;
}
```

**Comment by kylemcdonald** [comment]
sort of wish we had ofScreenToWorld/ofWorldToScreen for the global context again... jumping back into this, it's not clear to me how to get the same results if i'm using ofCamera with ofTranslate/ofRotate/etc.

**Comment by arturoc** [comment]
you can now use glm::project and glm::unproject which are pretty much direct replacements for glu's

```
glm::project(pos, ofGetCurrentMatrix(), ofGetCurrentViewport());
glm::unproject(pos, ofGetCurrentMatrix(), ofGetCurrentViewport());
```
