### ISSUE TITLE
ofxAssimpModelLoader add ability to modify meshes

### ISSUE THREAD

**Issue by snibbe** [openframeworks/openFrameworks#7651]
Is it too janky to add the small hack from this post so that the underlying model mesh data can be exposed to modify the mesh vertices, texture coordinates, etc. of a model loaded with `ofxAssimpModelLoader`?

https://forum.openframeworks.cc/t/ofxassimpmodelloader-how-to-tweak-model-meshes/36665

It extends the class with the following method:

`ofxAssimpMeshHelper* getModelMeshHelper(int i) { return &modelMeshes[i]; }`

It would be more elegant to make an `ofxAssimpModelLoader` method such as `setMesh` that copied in the `ofMesh` to the internal mesh structures, but this is a quick fix that has helped more than one OF user already.

If so, I'd be happy to submit the change, but wanted to check with the team as to whether this is too much of a hack.

**Comment by ofTheo** [comment]
Thanks @snibbe !

Yes, this class is ripe for a big cleanup. @NickHardeman and I were just talking about this too. 

I think you can actually do this already with:
```
		ofxAssimpMeshHelper & getMeshHelper(int meshIndex);
```

The reference gives you access to the actual object so you could access it that way or even store a pointer to it if you want to access in another place. 

Let me know if that works for your use case, I think ultimately we'll probably do a big cleanup of this addon and add a lot of functionality to allow you to be able to better work with the loaded data ( ie being able to request a mesh back with the matrix transformations applied to the verts so you can work with an ofMesh without having to need the model loader to display it correctly.

**Comment by snibbe** [comment]
Thank you so much, my oversight. That works. The new OF release is really great and I was able to port over a new project last week and have it both running and immediately expandable in ways that were tricky in the framework I was using before (not to mention working cross-platform). Also, easily folding in @patriciogonzalezvivo's lygia! Thanks to you and all the great OF devs!
