### ISSUE TITLE
 ofDirectShowPlayer:  Cannot load video of this file type

### ISSUE THREAD

**Issue by DoloresGarci** [openframeworks/openFrameworks#7695]
Hi, I am having this issue with OF that it wasn't happening before. The error is: " ofDirectShowPlayer:  Cannot load video of this file type.  Make sure you have codecs installed on your system.  OF recommends the free K-Lite Codec pack. " . I already have downloaded K-Lite, and tried different solutions but nothing helped. Does anybody knows how to fix this problem?

**Comment by ofTheo** [comment]
Hi! 
What type of video file is it your trying to play?

Also did you do this step from the [setup guide:](https://openframeworks.cc/setup/vs/)
```
NOTE: The current version of K-Lite requires an additonal step: 1. Open the Code Tweak Tool ( which is part of K-Lite ) 2. Click the button: General -> Fixes 3. Check 'Re-register base Directshow Filters' and hit Apply
```

Also the recent OF 0.12.0 release now has a Media Foundation video player as the default, so codecs aren't needed. 
https://github.com/openframeworks/openFrameworks/releases/tag/0.12.0

**Comment by DoloresGarci** [comment]
Thank you so so so much! The new version worked!
