### ISSUE TITLE
How to clear or remove a specific texture from an ofMaterial object?

### ISSUE THREAD

**Issue by zhangew** [openframeworks/openFrameworks#7719]
Hello, I’m using ofMaterial class to set the appearance of my objects in the scene. I saw a series of methods of setTexture(), but didn’t find according removeText() methods.

What should I do if I want to remove the default texture attached by the model?
Thanks.

**Comment by NickHardeman** [comment]
Thank you @zhangew. This was addressed via #7707.
I have started a ofxAssimpModelLoader discussion here https://github.com/openframeworks/openFrameworks/discussions/7722
