### ISSUE TITLE
srand in 12.0

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7724]
someone raised an issue on the forum about the sending being not synchronized in 12.0 between old-school and new school. while I remember a discussion with @ofTheo about integrating a call to srand within of::random::seed to keep things somewhat coherent until the proper phase-out of srand (and there is such a call at engine construction to make srand non-deterministic by default) but it is evidently not in place in 12.0, and that is a bug. 12.1 is OK as there is no srand needed anymore.

what is the OF hotfix/backport policy? is something like that to be fixed within 12.0, or simply taken care of by 12.1?

**Comment by ofTheo** [comment]
I think if this fixed in nightly you could point them there. We wouldn’t typically backport a fix to 0.12.0 though we could do 0.12.1 fairly soon I think. 🙂
