### ISSUE TITLE
Emscripten - Assimp loading of GLTF Models crashes / throws exception

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#7738]
See this example: (Press '2' or '3' on keyboard to try and load gltf model).
https://nickhardeman.com/temp/OFExamples/ofxAssimpExample/

Maybe related to this issue in Assimp?
https://stackoverflow.com/questions/74982318/assimp-error-when-loading-model-in-the-browser-wasm

**Comment by NickHardeman** [comment]
I think the check may be fixed via this pull request to Assimp which was merged in 5.3.0
https://github.com/assimp/assimp/pull/5154
Seems to be quite a lot of other fixes as well. 
https://github.com/assimp/assimp/releases/tag/v5.3.0

For compiling Assimp for Emscripten for testing quickly on OSX, what might be the easiest approach? Apothecary? 
pinging @Jonathhhan :)

**Comment by ofTheo** [comment]
I think its a simple as downloading 5.3.0 and using the same commands as in apothecary: 

https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/assimp.sh#L201C1-L213C1

not sure if you need the copy files section but here it is :) 

```
        cp -Rv build_emscripten/include/* $1/include
        cp -Rv build_emscripten/lib/libassimp.a $1/lib/$TYPE/libassimp.a
```

**Comment by NickHardeman** [comment]
I built for osx and emscripten and it seems to fix the gltf model loading crashes
https://nickhardeman.com/temp/OFExamples/ofxAssimpExample_5.3.1/

**Comment by Jonathhhan** [comment]
@NickHardeman only the fifth model is not working after the update (it was not working before).

**Comment by NickHardeman** [comment]
I disabled the last model for emscripten;  the payphone; since it loads incorrectly before and still does after the update to 5.3.1
![image](https://github.com/openframeworks/openFrameworks/assets/142694/e14f6a52-fb2a-463a-a3c7-4ed34505af83)

**Comment by Jonathhhan** [comment]
> I disabled the last model for emscripten.

@NickHardeman makes sense, had the same issue.

**Comment by NickHardeman** [comment]
This pull request to apothecary would use assimp 5.3.1, but it's failing msys2 clang64. 
https://github.com/openframeworks/apothecary/pull/296
