### ISSUE TITLE
getBoundingBox / ofDrawBitmapStringHighlight question

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#7743]
Hello, 
I am not sure if this is the expected behavior,
but when I try yo get the text bounding box, I am getting the rectangle a bit displaced:

```.cpp
void ofApp::drawHelp() {
	int x = 100;
	int y = 100;

	string s;

	s = "";
	//s += " \n";
	//s += " \n";
	s += "HELP\n";
	s += "ofxSurfingPBR\n";
	s += "\n";
	s += "KEYS\n";
	s += "\n";
	s += "h Help\n";
	s += "d Debug\n";
	s += "g Gui\n";
	s += "s Draw Shadow \n";
	s += "b Draw BgAlt\n";
	s += "f FullScreen";
        s += " \n";
        //s += " \n";

	ofBitmapFont bf;
	auto bb = bf.getBoundingBox(s, 0, 0);

	//ofDrawBitmapString(s, x, y);
	ofDrawBitmapStringHighlight(s, x, y);

	ofPushStyle();
	ofNoFill();
	ofSetLineWidth(2);
	ofSetColor(ofColor::red);

	//fix
	float yoffset = 0;
	//yoffset = 11;
	
	ofDrawRectangle({ (float)x, (float)y - yoffset, bb.width, bb.height });
	ofPopStyle();
}
```

![imagen](https://github.com/openframeworks/openFrameworks/assets/2106149/e1b63393-e7f8-414c-b539-6bf7fef99ca9)

And this is with
yoffset = 11;

![imagen](https://github.com/openframeworks/openFrameworks/assets/2106149/65987512-8ffb-4616-b9aa-185da0c6d23c)

Maybe should I add offset by font size and internal spacing?
I don't know where to get them from ...

**Comment by dimitre** [comment]
drawBitmapString considers y as the baseline, so it is not the same y of drawing a rectangle (font baseline and y height)
if you draw the actual rectangle it is correct:
```
	ofBitmapFont bf;
	auto bb = bf.getBoundingBox(s, x, y);

	//ofDrawBitmapString(s, x, y);
	ofDrawBitmapStringHighlight(s, x, y);

	ofPushStyle();
	ofNoFill();
	ofSetLineWidth(2);
	ofSetColor(ofColor::red);

	ofDrawRectangle(bb);
	ofPopStyle();
```
but it caught my attention that maybe the \n is being counted as a character, it should not have the right space there.

**Comment by moebiussurfing** [comment]
yes, 
I noticed something weird too with the "\n",
when used starting or ending the string…
To make the "bounding box working", I needed to add an ' ' (space) before the \n.

For example:

Do not works:
```.cpp
	s += "F5 ColorsNoAlpha\n";
	s += "F6 ColorsAlpha\n";
	s += "F7 Alphas";
	s += "\n";
	s += "\n";
```

It works:
```.cpp
	s += "F5 ColorsNoAlpha\n";
	s += "F6 ColorsAlpha\n";
	s += "F7 Alphas";
	s += " \n"; // ->Note the space
	s += " \n"; // ->Note the space
```

(Not sure if something happens too when string starts with "\n")
