### ISSUE TITLE
[feature request] [macOS] info.plist: change app category to "games" to enable macOS14 "game mode" optimisations

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7763]
In order to trigger the macOS14 "game mode" (which beyond direct[ macOS rendering performance optimisations](https://eclecticlight.co/2023/10/18/how-game-mode-manages-cpu-and-gpu/)  is a way of circumventing the [macOS13+ GLFW vsync bug](https://github.com/glfw/glfw/issues/2249)), the "App Category" plist entry must be one of the games options. 

This has not been received favourably by the general macOS community as many non-games can gain from fullscreen optimisations, but for the time being (20231119) there is no other way to inform the System that an app should receive the fullscreen priority treatment, and the only negative drawback would be mis-categorization for an App Store distributed app.

**Comment by dimitre** [comment]
+1 for this change. 
I've randomly choose "Graphics & Design" but I think it is a good reason for changing the default template. 
Thoughts @ofTheo ? 
I can make this PR if you prefer. there is a JSON conversion and format needed after editing XCode template.

**Comment by danomatika** [comment]
The app category can be set as a key in the Info.plist via the Project.xcconfig and/or App.xcconfig override. I'd suggest documenting this and including a commented-out section in Project.xcconfig.

https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype


~~~
# set application category to games, this is required to enabled Game mode
# note: this sets the initial value in the Xcode UI
#INFOPLIST_KEY_LSApplicationCategoryType = public.app-category.games
~~~

**Comment by ofTheo** [comment]
yeah sounds good!  
I like @danomatika solution to this but maybe uncommented by default ?

**Comment by danomatika** [comment]
This needs to be documented somewhere to avoid confusion for users wondering why their app suddenly behaves differently after they change the category in the UI.

**Comment by artificiel** [comment]
the only "sudden" change that users will notice is the activation of "game mode" if they perform a native fullscreen (which is currently not possible within the exposed OF API)

**Comment by artificiel** [comment]
and also, that's only on macOS 14+. so users "suddenly wondering" about a change would be macOS14 users manually getting the objc pointer to the cocoa window and sending the native fullscreen message, and being surprised by the game mode activation.

**Comment by danomatika** [comment]
> This needs to be documented somewhere to avoid confusion for users wondering why their app suddenly behaves differently after they change the category in the UI.

I'm not sure why this comment can be taken in a negative way. I don't believe I wrote "no, don't do it". I believe I wrote: "if we do it, explain the reasoning so users who expect the old behavior can understand / work with / change" the new behavior.

**Comment by artificiel** [comment]
sorry if it was not clear I was just trying to define the set of users to whom the change could appear surprising so the wording of the comment would be as precise as possible in helping them identify and understand the said change.

**Comment by dimitre** [comment]
Good one about xcconfig! it is worth the change in template too, just to unselect and make the .xcconfig default.
About documenting the change, where do you think it is the appropriate place @danomatika? maybe in changelog?

**Comment by danomatika** [comment]
I would change the templates, just as we did with the version and app icon.

The changelog is a good place to note any important info like this. For instance, in ofxPd I often add an extra note for people to regenerate their projects if pure data has added any new files upstream. Maybe something like:
~~~
macOS: default app category now set to Game for system to enable Game Mode when available in macOS 14+,
       note: Game Mode capability may be lost when changing to a non-game-relate category, ie. "Music"
~~~

I think with something like game mode, if it provides a performance boost which is then lost by changing a setting which may seem unrelated, we just want to avoid people 1. not understanding why and 2. opening lots of issues about why their app may not perform as well.

**Comment by dimitre** [comment]
Here is a PR testing the changes suggested in here
https://github.com/openframeworks/openFrameworks/pull/7767
and the nice thing we can later (or now) migrate some or all .plist entries to xcconfig format too, this way we can preserve some special settings per project via App.xcconfig. 
I remember @2bbb already brought this need before.
