### ISSUE TITLE
Windows / Linux full screen crash

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7775]
If I leave the full screen mode, the app crashes on Windows and Linux (tried with several examples).
Maybe this is related: https://github.com/openframeworks/openFrameworks/pull/7538#event-9119259834?

**Comment by artificiel** [comment]
just to be clear, `examples/windowing/windowExample` crashes?

here of_v20231129_linux64gcc6_release on archlinux 6.4.12 with i3wm it works without problem.

**Comment by Jonathhhan** [comment]
Yes, also with that example. With Windows / Linux Ubuntu WSL. Have to try native Linux.

**Comment by ofTheo** [comment]
this might be a WSL issue - as we're using fullscreen on Linux a ton. 
Are you enabling fullscreen via the OF functions or via the window buttons?

**Comment by Jonathhhan** [comment]
@ofTheo I tried `OF_FULLSCREEN` in `main.cpp`  and `ofSetFullscreen(true)` in `ofApp.cpp`. Yes, probably it is a WSL issue.
