### ISSUE TITLE
Can't use OF_TTF_MONO as a font path anymore?

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#7810]
```.cpp
ofTrueTypeFont font
string p = OF_TTF_MONO;
bool b=font.load(p, 20, true, false, true);
ofLog() << (b ? "success" : "failed");
```

```.cpp
static const std::string OF_TTF_SANS = "sans-serif";
static const std::string OF_TTF_SERIF = "serif";
static const std::string OF_TTF_MONO = "monospace";
```

I remember using bundled `OF_TTF_MONO `font as a common path before in OF 0.11...
is it still possible to use it like this?

**Comment by dimitre** [comment]
it should work. which OS are you using?

**Comment by dimitre** [comment]
I was able to run OK on macOS
```c++
ofTrueTypeFont font;

void ofApp::setup(){
	font.load(OF_TTF_MONO, 15);
}

void ofApp::draw(){
	ofBackground(0);
	ofSetColor(255);
	font.drawString("Mono Testando 123\n129384098743021", 40, 40);
}

```

**Comment by danoli3** [comment]
Traced to two issues. one platform paths for variable path not used. 

Second the string for MONO was becoming "Courier New"
<img width="845" alt="Screenshot 2024-07-29 at 4 08 41 AM" src="https://github.com/user-attachments/assets/a80cdae4-54ad-4ed9-a93a-aac0ca2cd581">


In the return string this is "courier new" 

<img width="298" alt="Screenshot 2024-07-29 at 4 10 13 AM" src="https://github.com/user-attachments/assets/4f3a039d-8614-41cd-8de6-8fc975936d76">
