### ISSUE TITLE
ci.openframeworks.cc Down

### ISSUE THREAD

**Issue by frankplow** [openframeworks/openFrameworks#7812]
Not an issue with openframeworks itself, but I couldn't see a better place to post this sorry. It looks like https://ci.openframeworks.cc is down. The root directory and valid subdirectories I have found in various places all time out for me.

**Comment by ofTheo** [comment]
Yes, that's correct. 
We took it down because the server cost was too high and we have most of the content on the main site. What were you trying to access? 

We should have all the old versions at:
https://openframeworks.cc/versions/

**Comment by frankplow** [comment]
I am trying to get a hold of the dependencies which used to be under:
```
https://ci.openframeworks.cc/libs/openFrameworksLibs_master_<DEPENDENCY>
```
They don't look to be available at https://openframeworks.cc/versions/

**Comment by danoli3** [comment]
I cloned the ci site at some point for testing android stuff before we did the github releases, lucky you:

https://libs.danoli3.com/?dir=ci.openframeworks.cc/libs

**Comment by frankplow** [comment]
@danoli3 Amazing, thanks a lot.
