### ISSUE TITLE
Corrupted files from Download archive.

### ISSUE THREAD

**Issue by dorald** [openframeworks/openFrameworks#7813]
Hi, I downloaded 0.12.0 version from website and the archive seems to have corrupted files inside as I get these message(see screenshot) on extract.
![Screenshot 2023-12-10 at 15 50 17](https://github.com/openframeworks/openFrameworks/assets/472782/5366a8d1-d78f-4a4d-9e5e-5c27378340bf)
![Screenshot 2023-12-10 at 15 49 56](https://github.com/openframeworks/openFrameworks/assets/472782/309f0832-0be2-4a8e-8e04-49b856af4f13)

I've tried several times downloading an extracting and I get the same message.

macOS Sonoma 14.1.1

**Comment by ofTheo** [comment]
Can you try using the macOS built in archive tool ( Archive Utility )? 
It works fine for me on macOS 13.4

**Comment by dorald** [comment]
@ofTheo Yes, it worked with Archive Tool.
Thank you :)
