### ISSUE TITLE
Windows libs not getting linked properly for ofxAssimp

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#7816]
https://forum.openframeworks.cc/t/new-ofxassimp-add-on/42864/5?u=moebiussurfing

**Comment by NickHardeman** [comment]
@dimitre having trouble with linking the libs in ofxAssimpModelLoader to ofxAssimp using the Project Generator in VS since it supports Debug and Release. Do you know if there is a way to do separate lib paths for Debug and Release via the add-on config?

**Comment by ofTheo** [comment]
@NickHardeman - one thought I had with this would be to add a feature to the projectGenerator that would allow you to add paths where it would do the normal processing as if it was in the ofxMyAddon/libs/myLib 


So for example for your addon you could do this: 
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimp/addon_config.mk

```
vs:
	ADDON_LIBS=
	ADDON_LIBS=../ofxAssimpModelLoader/libs/assimp/lib/vs/
```

And if there was a Debug / Release subfolder it would auto add the correct lib in the project file to the target ( as if it were the libs from the ofxAssimpModelLoader addon ).

**Comment by danoli3** [comment]
Yeah projectGenerator should be able to find and update it. 

I was able to update addonsExample with project generator when adding Debug/Release subfolders from a prior working no subfolders and it figured it out.

**Comment by dimitre** [comment]
@NickHardeman I'll check in the code right now. Luckly today I have a windows machine to test :)

**Comment by dimitre** [comment]
the function that adds the addon libs folder recursively is now called hardcoded as addonName / "libs".
So it only does its magic inside the addon folder itself.
this function adds recursively all the needed headers and add folders according to platforms and targets.
We can change the projectGenerator functionality to be able to add another recursive folder outside of addon path, something like:
ADDON_ADDITIONAL_LIBS_RECURSIVE
Yeah this name is awful but it is just to remind we should differentiate from ADDON_LIBS 
which adds one path per line, non recursive.

**Comment by ofTheo** [comment]
@dimitre - I think something like that would be super!

**Comment by dimitre** [comment]
I have a functional PR here, working on windows:
https://github.com/openframeworks/projectGenerator/pull/445
Let's define the name for this new variable

**Comment by dimitre** [comment]
PR is ready to merge, which variable name we should use? 
cc @danoli3 
```
ADDON_ADDITIONAL_LIBS_RECURSIVE
ADDON_ADDITIONAL_LIBS_FOLDER
ADDON_ADDITIONAL_LIBS
```

**Comment by danoli3** [comment]
``` ADDON_ADDITIONAL_LIBS ```
lets get it in!

**Comment by danoli3** [comment]
Just to confirm the ADDON_ADDITIONAL_LIBS found location will also be checked for DLL's

**Comment by dimitre** [comment]
ok merged!

**Comment by dimitre** [comment]
@danoli3 yes it is making everything it does for "libs" including dlls. the only function out is adding ".props", but it can be easily added also

**Comment by dimitre** [comment]
projectGenerator and addon_config.mk updated
hopefully it will be working tomorrow on nightly

**Comment by NickHardeman** [comment]
@moebiussurfing are you able to test if the latest nightly solves the issue for you?

**Comment by moebiussurfing** [comment]
> @moebiussurfing are you able to test if the latest nightly solves the issue for you?

I tried but the PG.exe does not open now... sometimes it happens here...
i´ll try to reboot soon and retry

**Comment by moebiussurfing** [comment]
@NickHardeman 
nice! 
the 3 assimp examples worked perfect creating the project with this PG:
https://github.com/openframeworks/projectGenerator/releases

**Comment by moebiussurfing** [comment]
straightforward both debug/release without touching anything else
