### ISSUE TITLE
emscripten examples are all erroring when uploaded 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7824]
cc @Jonathhhan is this the CORS issue?

I tried uploading all the examples since we merged #7803 and I am seeing these errors with examples that worked before. 

page link: https://openframeworks.cc/examples/ 

![image](https://github.com/openframeworks/openFrameworks/assets/144000/7a53a2fa-17ee-4a3b-a5be-21ba4a5e0582)

![image](https://github.com/openframeworks/openFrameworks/assets/144000/ec86b468-5de1-449a-9d44-5abe12140fa0)

**Comment by ofTheo** [comment]
looks like that is the issue - if I add the cors header for one of the examples it works: 
https://openframeworks.cc/examples/gl/transformFeedbackAnimatedExample/ 

@Jonathhhan any idea why the injection script isn't working?

**Comment by Jonathhhan** [comment]
Yes. it seems that I forgot to delete the browser cache (sorry for that).
It only seems to work, if I add this: `<script async src=coi-serviceworker.js></script>` at the end of `template.html`
And upload the `coi-serviceworker.js` file seperately.  Or load it like: `<script async src=https://github.com/gzuidhof/coi-serviceworker/blob/master/coi-serviceworker.js></script>`

**Comment by Jonathhhan** [comment]
I made a new PR that hopefully works: https://github.com/openframeworks/openFrameworks/pull/7825

**Comment by dimitre** [comment]
Let me know if you need any CORS configuration on nginx.conf

**Comment by ofTheo** [comment]
@dimitre - thanks! 
I can definitely get it working by enabling that ( and will do in a sec just so I can text the examples ), but I just wanted to make a note that this def doesn't work out of the box so far. 

@Jonathhhan with your latest PR it still doesn't work: 

<img width="1920" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/144000/dbc28307-4e20-4772-9804-65a94dca04a8">

I had to modify the [template file](https://github.com/openframeworks/openFrameworks/blob/master/scripts/ci/emscripten/example-index.html#L1) which we use for the examples separately as it's different from the one bundled by emmake but it still doesn't seem to to work.  

Note: I am going to change the script to use the template file from emmake and then just append the source code stuff we are doing on the examples page as that way emscripten part of the index will be the same.

**Comment by ofTheo** [comment]
ahh - it needs to be: `https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js`

**Comment by ofTheo** [comment]
hmm nothing seems to work. even putting the script into the same folder as index.html I get: 

![image](https://github.com/openframeworks/openFrameworks/assets/144000/3a5da86e-7474-4465-8266-58611591a2f9)

Thinking we should revert pthreads on by default for now until we can get a solid solution.

**Comment by Jonathhhan** [comment]
@ofTheo yes, it needs to be reverted then. I tested different browser and it works only with the regular chrome browser (also after deleting the browser cache). But not Chrome Beta / Dev / Edge and Firefox.

**Comment by Jonathhhan** [comment]
Now also regular Chrome does not work anymore. Seems it took some time that clearing the browser cache took effect(?). Sorry for the confusion. Would have been nice, if it would be working.

**Comment by ofTheo** [comment]
yeah totally! 
there are definitely pros and cons to both approaches ( p-threads vs non ). 

it seems like it will be something needed in the future and maybe when we do the switch we can detect the error and provide a warning on how to setup the apache / ngnix headers?

**Comment by Jonathhhan** [comment]
Yes, Emscripten pthreads have their advantages, but make also a little more diffucult to use Emscripten (because of the CORS stuff).
