### ISSUE TITLE
Xcode builds app to build folder instead of bin folder

### ISSUE THREAD

**Issue by NickHardeman** [openframeworks/openFrameworks#7852]
Testing the nightly, it seems like the following line was removed
`CONFIGURATION_BUILD_DIR = $(SRCROOT)/bin/`
from 
_libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig_.
When compiling from the Xcode IDE it causes the app to be placed in _build/products/(Debug/Release)/myApp.app_ instead of _bin/myApp.app_ which causes the paths to the data folder to break. 
Putting that line back in the xcconfig fixed it for me.

**Comment by dimitre** [comment]
Hey Nick sorry about that. my bad. I'll put it back right now.

**Comment by NickHardeman** [comment]
closed by #7853. Thank you @dimitre :)
