### ISSUE TITLE
nightly release now doesn't include example files for Visual Studio 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#7856]
Just tested a nightly and while there are VS Code project files there are no Visual Studio files  ( for the examples )

**Comment by dimitre** [comment]
I've noticed the same for XCode projects, osx is packaging with only vscode.
I was wondering about ```create_package.sh```
```sh
        #add vscode to all platforms apart from ios/tvos/android
        if [ "$pkg_platform" == "android" ] || [ "$pkg_platform" == "ios" ]; then
            pg_template=" "
        else
            pg_template="-tvscode"
        fi
```

**Comment by ofTheo** [comment]
okay this is fixed now and current nightly should be good - phew!
