### ISSUE TITLE
ofAVEngineSoundPlayer - 'AVAudioSessionInterruptionTypeKey' is unavailable: not available on macOS

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7861]
I'm building an app without fmod on macOS by using
```
OF_NO_FMOD=1
USER_PREPROCESSOR_DEFINITIONS="OF_NO_FMOD=1"
```
on App.xcconfig, so it is automatically kicking in with ofAVEngineSoundPlayer
but it is bringing this error:
'AVAudioSessionInterruptionTypeKey' is unavailable: not available on macOS

**Comment by ofTheo** [comment]
@dimitre - I'll let @danoli3 chime in but I am guessing that is an iOS only thing. 

I am guessing those code sections need to be included in the #ifndef TARGET_OSX 

We should prob start switching tests to use OF_NO_FMOD so we can catch these things

**Comment by danoli3** [comment]
This was defined out for macOS. 

<img width="794" alt="Screenshot 2024-07-29 at 3 36 43 AM" src="https://github.com/user-attachments/assets/81358a93-a637-44f7-8f3b-df3825771d5a">
