### ISSUE TITLE
iOS : Single Touch Recognized as Double Touch on Second Touch Location Change on Simulation

### ISSUE THREAD

**Issue by azuremous** [openframeworks/openFrameworks#7871]
As you can see from the video, a double touch decision occurs unconditionally on the second touch even though it is a single touch. It does not occur after that, but occurs when you change the location again.

https://github.com/openframeworks/openFrameworks/assets/319589/8f5cfe2b-ce08-4df6-8a10-46c30231c652

Is it a problem that only occurs in simulations?

I tried logging in both of xiOSGLKView and ofxiOSEAGLView to see what is causing this problem, but I can't check the log. 

<img width="563" alt="checkDoubleTouch" src="https://github.com/openframeworks/openFrameworks/assets/319589/d36d7732-a551-4884-8d08-441966c30b9c">

of ver 0.12.0

**Comment by danoli3** [comment]
Yeah I think this is just an issue on Simulator as touch event and even tapCount is all coming from Apple's events
