### ISSUE TITLE
[msys2] Recent GLM update doesnt carry its pkg-config metadatas

### ISSUE THREAD

**Issue by ylmrx** [openframeworks/openFrameworks#7874]
The install script will pick latest packages, it seems glm package doesn't embed the relevant pc file, thus breaking the further make commands.

It builds fine rolling back to glm-0.9.9.x, like so:

```
wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-glm-0.9.9.8-2-any.pkg.tar.zst
pacman -U mingw-w64-x86_64-glm-0.9.9.8-2-any.pkg.tar.zst --noconfirm
```

**Comment by GorgeousOne** [comment]
I just spent 6 hours trying to learn what msys2 package management is and what make files do to come to this exact conclusion 😂 but good to see that there's already a fix

**Comment by danoli3** [comment]
Yeah not great
