### ISSUE TITLE
VS Code on Mac: None of the Header Files are being found.

### ISSUE THREAD

**Issue by Intisarw** [openframeworks/openFrameworks#7881]
None of my Header files are working when I open up my _workspace_ file on VSCode for OSX. I will attach some of the issues being found on the terminal. 

Thank you in advance! 

![Image 1-31-24 at 12 42 PM](https://github.com/openframeworks/openFrameworks/assets/135399824/6a4a425b-acf2-46ac-ba74-4794f9e1cc13)
![Image 1-31-24 at 12 42 PM (1)](https://github.com/openframeworks/openFrameworks/assets/135399824/a4949947-3c29-4adc-a2a8-664d7168a203)
![Image 1-31-24 at 12 42 PM (2)](https://github.com/openframeworks/openFrameworks/assets/135399824/f48ac130-4668-429c-b992-6601db5ef9aa)

**Comment by dimitre** [comment]
Hello @Intisarw I would try to disable all extensions
and also test with the code from latest master.

**Comment by dimitre** [comment]
closing this one
