### ISSUE TITLE
[actions] - linux arm failing : GPG Error NO_PUBKEY

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7891]
```
W: GPG error: http://deb.debian.org/debian bullseye InRelease: 
The following signatures couldn't be verified because the public key 
is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 
6ED0E7B82643E131 NO_PUBKEY 605C66F00D6C9793
```

**Comment by dimitre** [comment]
@danoli3 I'm not sure if it is related but the latest raspberry pi os now is bookworm

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by danoli3** [comment]
Yeah massive Raspberry Pi changes for the RiPi5 post launch.

They went nuclear on the APIs and other repos so will need to update

**Comment by dimitre** [comment]
we can try to add this step in GH action as a measure to have them running
```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 605C66F00D6C9793
```
