### ISSUE TITLE
Error compiling nightly on VS2022 cairolib missing? 

### ISSUE THREAD

**Issue by sebleedelisle** [openframeworks/openFrameworks#7892]
I'm getting the error : Cannot open input file libcairo.lib 
When I try to compile anything, even an empty project. 

VS 17.7 Windows 11
(I'm terrible at windows so not sure if I'm doing something wrong)

cheers!

Seb

**Comment by danoli3** [comment]
Ah yes the nightly for VS still pointing to old libs 

![image](https://github.com/openframeworks/openFrameworks/assets/830748/28979cbd-d571-47fd-8398-ce77eb1a78f4)

**Comment by danoli3** [comment]
You can fix this yourself in the nightly checkout by running the **download_latest_libs.sh** it will just download the latest libraries and extract them

**Comment by danoli3** [comment]
Okay so Nightly:
```
cd $OUTPUT_FOLDER

$ROOT/scripts/dev/create_package.sh linux64 $lastversion master gcc6
$ROOT/scripts/dev/create_package.sh linuxarmv6l $lastversion master
$ROOT/scripts/dev/create_package.sh linuxaarch64 $lastversion master
$ROOT/scripts/dev/create_package.sh osx $lastversion master
$ROOT/scripts/dev/create_package.sh ios $lastversion master
$ROOT/scripts/dev/create_package.sh msys2 $lastversion master mingw64
$ROOT/scripts/dev/create_package.sh vs $lastversion master

ls -la
cd $ROOT
```
scripts/ci/package_builds.sh 
does this 

Then create_package.sh
```
 #download external dependencies
    cd $pkg_ofroot/
    if [ "$pkg_platform" = "osx" ]; then
        scripts/osx/download_libs.sh
        scripts/emscripten/download_libs.sh -n
    elif [ "$pkg_platform" = "linux64" ]; then
        scripts/linux/download_libs.sh -a 64$libs_abi
        scripts/emscripten/download_libs.sh -n
    elif [ "$pkg_platform" = "linuxarmv6l" ]; then
        scripts/linux/download_libs.sh -a armv6l
    elif [ "$pkg_platform" = "linuxarmv7l" ]; then
        scripts/linux/download_libs.sh -a armv7l
    elif [ "$pkg_platform" = "linuxaarch64" ]; then
        scripts/linux/download_libs.sh -a aarch64
    elif [ "$pkg_platform" = "msys2" ]; then
        scripts/msys2/download_libs.sh -a $libs_abi
        scripts/emscripten/download_libs.sh -n
    elif [ "$pkg_platform" = "vs" ]; then
        scripts/dev/download_libs.sh -p vs
        scripts/emscripten/download_libs.sh -n
    elif [ "$pkg_platform" = "android" ]; then
        scripts/android/download_libs.sh
    elif [ "$pkg_platform" = "ios" ]; then
        scripts/ios/download_libs.sh
    fi
    ```
    
    Does this
    
    I've fixed by fixing to use latest libs. I can see an issue in nightly with emscripten on vs now though. Will need to get that fixed after this

**Comment by danoli3** [comment]
Should be fixed now @sebleedelisle sebleedelisle

**Comment by dimitre** [comment]
I'm having issues with windows also: win11 here, vs 2022, latest libs installed. 
and 
<img width="583" alt="Screenshot 2024-02-12 at 11 49 13" src="https://github.com/openframeworks/openFrameworks/assets/58289/d3aaa879-e523-415e-93c9-f899b8cc2810">

**Comment by danoli3** [comment]
How latest did you install the libs?

Okay really need to start packaging the version numbers, build times, with
binaries. I had a branch somewhere with version export into lib dir with
JSON file so we can track these issues.

Try to delete the libs/ and redownload avian.

I’ll try again as well later today.

Also try debug / release
And also make sure to clean both project and openframeworks protect now you
have the error.

**Comment by dimitre** [comment]
Yes good idea. I started to use a simple version in projectGenerator and it is great when trying to debug something. it even gets recorded inside an xcode generated project or visual studio, something like:
```	
"openFrameworksProjectGeneratorVersion": "34",
```

**Comment by dimitre** [comment]
cleaned up everything, project and core and libs folder, and installed again.
not sure if it is relevant but it complains in third zip. 
is each zip a complete zip file?

![libs](https://github.com/openframeworks/openFrameworks/assets/58289/bd957d49-5930-41a9-89d6-fdd6cae6954b)

**Comment by danoli3** [comment]
Oh okay I think maybe @dimitre that branch was not at latest master when you ran the script!

You can see bleeding libs which means latest, however there should only be 2 zip files now

**Comment by dimitre** [comment]
ok, are the scripts updated accordingly? ok that is kinda strange. I've pulled latest master into my PR before.
I'll be testing again in master to see how it goes

**Comment by danoli3** [comment]
Yeah semi concerning, probably just the gremlins

**Comment by danoli3** [comment]
![image](https://github.com/openframeworks/openFrameworks/assets/830748/a650c82b-becf-4d70-b38b-06833565cecc)

3rd zip?

**Comment by sebleedelisle** [comment]
This worked for me last time I checked the nightly a couple days ago. Ok to close?
