### ISSUE TITLE
computeShaderParticlesExample not running on macOS

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7906]
different errors using XCode and make.
similar issues with computeShaderTextureExample
macos 13.6.4, XCode 15.2, apple silicon

```
d@zen computeShaderParticlesExample % make RunRelease
[ error ] ofAppGLFWWindow: 65543: Requested OpenGL version 4.3, got version 4.1
[ error ] ofAppGLFWWindow: couldn't create GLFW window
/bin/sh: line 1: 42809 Segmentation fault: 11  ./computeShaderParticlesExample
make: *** [RunRelease] Error 139
```

<img width="1134" alt="Screenshot 2024-03-03 at 10 11 53" src="https://github.com/openframeworks/openFrameworks/assets/58289/9d48a9df-3af8-4114-ab42-a5ee7c95bfcd">

**Comment by artificiel** [comment]
Well compute shader is openGL4.3, and macOS is stuck at 4.1... for that reason it's removed from the releases:
https://github.com/openframeworks/openFrameworks/blob/c11edeffb5dbd6a19d88eb4687e8ddd03e7820ca/scripts/dev/create_package.sh#L312-L316
Do you mean a better error should be issued if openGL > 4.1 is requested on macOS? or  should `setupShaderFromFile()` alarm if `GL_COMPUTE_SHADER` when `#ifdef OF_TARGET_MAC`?

what would be the ideal behaviour?

**Comment by dimitre** [comment]
Yes, thanks for the reminder @artificiel.
Definetly it can be handled better, at least ofLogError but maybe std::exit with a message if the requested openGL version is higher than the system can provide.
