### ISSUE TITLE
utils/ofThread.h:42:7: warning: 'class ofThread' has virtual functions and accessible non-virtual destructor

### ISSUE THREAD

**Issue by lvdpower** [openframeworks/openFrameworks#7912]
utils/ofThread.h:42:7: warning: 'class ofThread' has virtual functions and accessible non-virtual destructor

appear with "g++ main.cpp ofApp.cpp -std=c++17 -Wall -Wnon-virtual-dtor .... "

It seems necessary to add  "virtual ~ofThread() { }  

timur123@gmail.com

**Comment by danoli3** [comment]
@lvdpower thanks for report should be fixed with https://github.com/openframeworks/openFrameworks/pull/8094
