### ISSUE TITLE
error loading .exr cubemaps

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#7935]
loading cubemaps gives error:
[ error ] ofCubeMap :: failed to load image from : "modern_buildings_2_1k.exr"
For example on this project, but in others too:
https://github.com/openframeworks/openFrameworks/tree/master/examples/gl/materialPBRExample

**Comment by dimitre** [comment]
Are you working with the latest master? if yes can you please pull latest and try again?

**Comment by moebiussurfing** [comment]
yes, i am at master branch up to date but doesn´t works

**Comment by dimitre** [comment]
which platform?

**Comment by moebiussurfing** [comment]
Windows 11, VS 2022

**Comment by NickHardeman** [comment]
@moebiussurfing, this may be an issue with FreeImage and EXR. Are you able to load a .hdr image?
Polyhaven has some to choose from
https://polyhaven.com/hdris

**Comment by NickHardeman** [comment]
I was able to reproduce the error on Windows 10 and VS 2022. Loading an HDR image works as it should.

**Comment by moebiussurfing** [comment]
yes, it worked here too. hdr files are loading well.
(btw i tried to rename the exr files to hdr but didn´t worked)

**Comment by NickHardeman** [comment]
@moebiussurfing thank you for checking
