### ISSUE TITLE
ofxSvg current svgtiny.lib does not work - Visual Studio

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7961]
If I replace it with `svgtiny.lib` from OF 12.0 it does work (that file is much larger, around 7 MB).

**Comment by dimitre** [comment]
which platform? is this addressable via apothecary update?

**Comment by Jonathhhan** [comment]
Visual Studio. Maybe it is a static lib instead of a shared lib? I guess, it should be addresble with the apothecary update (not sure, if it  is a good solution to just use the older version)...

**Comment by dimitre** [comment]
In macOS, latest libs (bleeding apothecary) are not working for me

**Comment by Jonathhhan** [comment]
Yeah, probably I was downloading the bleeding libs...

**Comment by dimitre** [comment]
@Jonathhhan Can you please check if it is the case with regular libs or latest?
And update the title or first text of issue? Thank you

**Comment by Jonathhhan** [comment]
@dimitre I will check it soon.

**Comment by danoli3** [comment]
Confirmed an issue with libxml2 binding

**Comment by danoli3** [comment]
Okay it was a bit deeper LibDOM and LibXML needed fixing! 
All fixed re patches and cmake fixing : https://github.com/netsurf-plan9/libdom/pull/2

New Apothecary Libs building now 

Proof of working 
![image](https://github.com/openframeworks/openFrameworks/assets/830748/634035c3-1b5b-4401-a1cb-677999778390)
