### ISSUE TITLE
assimp3DModelLoaderExample text mirrored in Visual Studio

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7962]
On the flighthelmet model of the `assimp3DModelLoaderExample` the text is mirrored (on the label and on the mask).
On the payphone model the text seems to be mirrored, too.

**Comment by dimitre** [comment]
Please add / edit platform. I've tested in macOS and text is ok

**Comment by Jonathhhan** [comment]
@dimitre sorry, Visual Studio.

**Comment by Jonathhhan** [comment]
@dimitri sorry again. it was compiled with visual studio, but with SWIG binding for Ofelia / Pure Data. If I compile the example app with VS, it works fine. So it is more an issue with Ofelia, I guess.
