### ISSUE TITLE
procedural posing of bones in ofxAssimpModelLoader

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#797]
we're working on some ideas regarding procedural animation and posing:

http://forum.openframeworks.cc/t/7714

which should be more powerful than playing back manual animations.

integrating it into the core would be ideal, but we're still trying to understand how it works.

**Comment by oxillo** [comment]
Hi,

We are trying to clean out the many issues that we have.
Many versions of OF have been released since this was issued.

Can you help us by checking if this feature is still requested for a next OF version ?

In case of inactivity, we'll close this issue by end of january, 2020.

Thanks

**Comment by NickHardeman** [comment]
closed by #7776
