### ISSUE TITLE
math PI define issue

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/openFrameworks#7983]
really not too sure what's causing this,  got lots of PI and DEG_TO_RAD  error issue after using the nightly build vs version,does it happen to anyone? vs2022 ide
![QQ截图20240521190546](https://github.com/openframeworks/openFrameworks/assets/51957/e8eecfda-5472-4ffa-9de8-81d3c0e4b573)
![QQ截图20240521190556](https://github.com/openframeworks/openFrameworks/assets/51957/cbd82f3b-7ccf-43b1-8048-b34fcc803e78)

**Comment by dimitre** [comment]
it should be working. I imagine this is ofxCv addon. which example are you building?
I'll check if the right includes are being used

**Comment by artificiel** [comment]
@liquidzym also during a moment an extra semi-colon found it's way in the macros https://github.com/openframeworks/openFrameworks/pull/7958/files and could have produced your problem, but the fix was merged last week — make ensure you have the very latest from git.

**Comment by liquidzym** [comment]
@artificiel ok, i see,its working now after grab the latest nightly version, thank you @dimitre
