### ISSUE TITLE
emscripten complied libpugixml issue

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/openFrameworks#7984]
got new complied issue which related with libpugixml, testing with nightly build version osx and emscripten  3.1.60

./../../libs/pugixml/lib/emscripten/libpugixml.bc:1:2: error: expected top-level entity
    1 | <U+0000>asm<U+0001><U+0000><U+0000><U+0000><U+0001><B0><81><80><80><U+0000><U+001B>`<U+0002><U+007F><U+007F><U+0001><U+007F>`<U+0003><U+007F><U+007F><U+007F><U+0000>`<U+0004><U+007F><U+007F><U+007F><U+007F><U+0001><U+007F>`<U+0003><U+007F><U+007F><U+007F><U+0001><U+007F>`<U+0004><U+007F><U+007F><U+007F><U+007F><U+0000>`<U+0001><U+007F><U+0001><U+007F>`<U+0001><U+007F><U+0000>`<U+0002><U+007F>|<U+0001>|`<U+0002><U+007F><U+007F><U+0001>|`<U+0002><U+007F>}<U+0001>}`<U+0002><U+007F>~<U+0001>~`<U+0003><U+007F>~~<U+0001>~`<U+0005><U+007F><U+007F><U+007F><U+007F><U+007F><U+0001><U+007F>`<U+0002><U+007F>|<U+0001><U+007F>`<U+0002><U+007F>}<U+0001><U+007F>`<U+0002><U+007F>~<U+0001><U+007F>`<U+0002><U+007F><U+007F><U+0000>`<U+0006><U+007F><U+007F><U+007F><U+007F><U+007F><U+007F><U+0000>`
      |         ^
1 error generated.
em++: error: '/Users/liquid/Desktop/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/Users/liquid/Desktop/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -isystem /Users/liquid/Desktop/emsdk/upstream/emscripten/cache/sysroot/include/freetype2 -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -O3 ../../../libs/pugixml/lib/emscripten/libpugixml.bc -c -o /var/folders/63/p36n6bnn21lc5x59z00d7nqw0000gn/T/emscripten_temp_2d4orxm2/libpugixml_0.o' failed (returned 1)
make[1]: *** [bin/em/graphicsExample/index.html] Error 1
make: *** [Release] Error 2
emmake: error: 'make' failed (returned 2)
liquid@liquiddeMacBook-Pro graphicsExample %

**Comment by dimitre** [comment]
related: https://forum.openframeworks.cc/t/emscripten-memory-init-file-is-no-longer-supported/43522

**Comment by danoli3** [comment]
https://github.com/openframeworks/openFrameworks/pull/7909 resolved
