### ISSUE TITLE
CI problem with VS jobs related to freetype / brotli

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7995]
happens since a few days on unrelated changes
```
freetyped.lib(sfnt.obj) : error LNK2019: unresolved external symbol BrotliDecoderDecompress referenced in function woff2_decompress
```
https://github.com/openframeworks/openFrameworks/actions/runs/9213490349/job/25347515265#step:6:9450

**Comment by dimitre** [comment]
related: https://github.com/openframeworks/apothecary/issues/375
probably fixed by https://github.com/openframeworks/openFrameworks/pull/7992
