### ISSUE TITLE
Emscripten Compiled Examples limited to 30 fps

### ISSUE THREAD

**Issue by emmadickson** [openframeworks/openFrameworks#8010]
I noticed that when I compile the asciiVideoExample using emscripten the frame rate of the app seems to be limited to 30fps while running in on my machine achieves a much faster framerate. 

The code I'm adding to view the framerate is just this.

```
 float fps = ofGetFrameRate();

		    // Create a char array to hold the formatted string
		    char fpsString[64];

		    // Format the FPS string
		    sprintf(fpsString, "FPS: %.2f", fps);
				// Draw the FPS string on the screen
				ofSetColor(255, 0, 255); // Set the color to white
				ofDrawBitmapString(fpsString, 500, 20); // Draw at coordinates (10, 20)

```

Am I missing something or is webassembly object I'm creating going to always be limited to 30 FPS? I was looking into compiling some apps that would require 60FPS using emscripten but this has me reconsidering.

**Comment by dimitre** [comment]
did you find a solution to your framerate limit?
