### ISSUE TITLE
Errors when including ofxNetwork.h

### ISSUE THREAD

**Issue by chinchichilla** [openframeworks/openFrameworks#8016]
Hello !
I am using this framework [https://github.com/nullboundary/ofxPJControl](url) to compile a .dll file, but when I include ofxPJControl.h I have more than 100 errors in the ws2def.h, winsock2.h and ws2tcpip.h. I think it's because of the ofxNetwork.h, when I delete the `#include "ofxNetwork.h"` in ofxPJControl.h it compiles succesfully, but I don't get why...

Thanks for your help !

**Comment by dimitre** [comment]
great. please share how did you solve this issue @chinchichilla, thanks
