### ISSUE TITLE
ofVideoPlayer is crashing when setVolume is called on update()

### ISSUE THREAD

**Issue by Vamoss** [openframeworks/openFrameworks#8024]
I am on VS 2019 with OF 0.12.0 in Windows 11.
The `ofVideoPlayer` craches the software specially when I try to set an audio fade during the update using `video.setVolume(value)`.

  | stack  | --
-- | -- | --
  | ntdll.dll!00007ff8ad4e1eef() | Unknown
  | (...) | (...)
  | ucrtbased.dll!00007ff82a3049c5() | Unknown
  | VideoPlayer_debug.exe!operator delete(void * block) Line 38 | C++
  | VideoPlayer_debug.exe!operator delete(void * block, unsigned __int64 __formal) Line 32 | C++
  | VideoPlayer_debug.exe!ofMediaFoundationUtils::AsyncCallback::`scalar deleting destructor’(unsigned int) | C++
  |  | VideoPlayer_debug.exe!ofMediaFoundationUtils::AsyncCallback::Release() Line 67 | C++

@NickHardeman proposed [this solution here](https://forum.openframeworks.cc/t/getting-0-12-0-to-build-in-vs-2017-on-machine-which-has-had-of-0-11-0-installed/43139/17?u=vamoss) on `ofMediaFoundationPlayer`:

```c++
//----------------------------------------------
void ofMediaFoundationPlayer::setVolume(float volume) {
    if (m_spMediaEngine) {
        double cvolume = ofClamp(volume, 0.0f, 1.0f);
        HRESULT hr = m_spMediaEngine->SetVolume(cvolume);
        if (hr != S_OK) {
            ofLogVerbose("ofMediaFoundationPlayer :: setVolume : Unable to set volume to ") << volume << ".";
        }
        //ofMediaFoundationUtils::CallAsyncBlocking(
            //[&] {m_spMediaEngine->SetVolume(static_cast<double>(volume));
            //[&] {m_spMediaEngine->SetVolume(cvolume);
        //});
    }
}
```

**Comment by NickHardeman** [comment]
Hi @Vamoss, 
Thank you for posting this here. It appeared to fix the issue for me for a simple test case. Were you able to test the proposed fix?

**Comment by Vamoss** [comment]
Hi @NickHardeman,
I just tested it. It seems to have fixed the issue, the software is not crashing anymore 🥳 
Thank you!
