### ISSUE TITLE
Empty project does not link when declaring a variable ofSoundStream in Windows_x64 - nightly 20240709

### ISSUE THREAD

**Issue by dgonzalezt** [openframeworks/openFrameworks#8035]
I wanted to migrate a project from version of 0.12 to a newer version that has RTAudio 6. But when I try the last nightly I get this, as soon as I declare an object ofSoundStream the project stops linking (vstudio), here below I put the error. I have created the project with the project generator and it is completely empty.

Error	LNK2019	unresolved external symbol "public: __cdecl ofRtAudioSoundStream::ofRtAudioSoundStream(void)" (??0ofRtAudioSoundStream@@QEAA@XZ) referenced in function "void __cdecl std::_Construct_in_place<class ofRtAudioSoundStream>(class ofRtAudioSoundStream &)" (??$_Construct_in_place@VofRtAudioSoundStream@@$$V@std@@YAXAEAVofRtAudioSoundStream@@@Z)	

Thanks in advance

**Comment by danoli3** [comment]
Install VS2022

Here is the vsconfig 
```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.DependencyValidation.Community",
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.Net.Component.4.8.SDK",
    "Microsoft.Net.Component.4.7.2.TargetingPack",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Component.VisualStudio.GitHub.Copilot",
    "Microsoft.Net.Component.4.8.1.SDK",
    "Microsoft.Net.Component.4.8.1.TargetingPack",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Component.Dotfuscator",
    "Microsoft.VisualStudio.Component.Windows11SDK.22621",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64EC",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
    "Microsoft.VisualStudio.Component.VC.ATL",
    "Microsoft.VisualStudio.Component.VC.ATL.ARM64",
    "Microsoft.VisualStudio.Component.VC.Modules.x86.x64",
    "Microsoft.VisualStudio.Component.VC.Modules.ARM64",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.Windows11Sdk.WindowsPerformanceToolkit",
    "Microsoft.VisualStudio.Component.CppBuildInsights",
    "Microsoft.VisualStudio.Component.VC.DiagnosticTools",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake",
    "Microsoft.VisualStudio.Component.VC.CMake.Project",
    "Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest",
    "Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest",
    "Microsoft.VisualStudio.Component.VC.ASAN",
    "Microsoft.VisualStudio.Component.Vcpkg",
    "Microsoft.VisualStudio.Component.VC.CLI.Support",
    "Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset",
    "Microsoft.VisualStudio.Component.VC.Llvm.Clang",
    "Microsoft.VisualStudio.Component.Windows11SDK.26100",
    "Microsoft.Component.VC.Runtime.UCRTSDK",
    "Microsoft.VisualStudio.Component.UWP.VC.ARM64EC",
    "Microsoft.VisualStudio.Component.UWP.VC.ARM64",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Component.MDD.Linux",
    "Component.Linux.CMake",
    "Microsoft.VisualStudio.Component.Git",
    "Microsoft.VisualStudio.Component.VC.ATL.Spectre",
    "Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre",
    "Microsoft.VisualStudio.Component.VC.ATL.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre",
    "Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre",
    "Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.Runtimes.ARM64EC.Spectre",
    "Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.Redist.MSM",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ARM",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ARM64",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ATL.ARM.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ATL.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.ATL.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.MFC.ARM.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.MFC.ARM64.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.40.17.10.MFC.Spectre"
  ],
  "extensions": []
}
```

**Comment by danoli3** [comment]
https://youtu.be/x4LLQhn8EOE?t=62

import in VS Installer this file as a .vsconfig and it will auto install the top

**Comment by danoli3** [comment]
Just confirmed nightly package contains:
```
name = "rtaudio"
version = "6.0.1"
buildTime = "2024-07-01 T03:26:37Z"
type = "vs"
gitUrl = "https://github.com/thestk/rtaudio"
binary = "rtaudio.lib"
binarySha = "d559eeb374c22f9edc3445268c6f74e9d069b171a645aa78d6d81112adcb2b73"

``

**Comment by danoli3** [comment]
<img width="634" alt="Screenshot 2024-07-10 at 11 16 37 PM" src="https://github.com/openframeworks/openFrameworks/assets/830748/155cc0bf-6a54-4e74-9328-68422a535a6b">

X64 working

**Comment by dgonzalezt** [comment]
Thanks for the help. 
I already have vs2022 installed, I don't want to have to reinstall it and adjust my whole development environment again. Let me see if I can deduce something from that .vsconfig file.
I don't know where I can look at that configuration you show me, but I look at the file of_v20240709_vs_x64_release\libs\rtAudio\include\RtAudio.h and I can confirm that it's 6.0.1.

![Captura de pantalla 2024-07-10 185117](https://github.com/openframeworks/openFrameworks/assets/14232672/1ad92cad-a0ca-4144-9aed-a074eed2861e)

**Comment by danoli3** [comment]
<img width="1420" alt="Screenshot 2024-07-11 at 3 18 37 AM" src="https://github.com/openframeworks/openFrameworks/assets/830748/1ef88738-1f64-4892-b041-77f34300c5b8">

What's your link command line look like?

You are using VS 2022 though right?

**Comment by danoli3** [comment]
Can you try clean, and try release mode

**Comment by dgonzalezt** [comment]
Right now I'm testing it on an empty project, just created with the project-generator, I haven't changed anything. I'll put the screenshots anyway. I've already tried cleaning, switching to release mode and everything simple I could think of.
Regards

![imagen](https://github.com/openframeworks/openFrameworks/assets/14232672/ce0268e6-cf44-4d61-8bf2-b9883b823120)

![imagen](https://github.com/openframeworks/openFrameworks/assets/14232672/f6cf2eb3-a050-44f0-8183-39d259748700)

**Comment by dgonzalezt** [comment]
Ok, I have the problem and a workaround solution that worked for me. 
The problem is that OF_RTAUDIO is not defined in ofRtAudioSoundStream.cpp or in .h. A solution that has worked for me is to forward the line `#include "ofUtils.h"`, putting it before the `#if defined(OF_RTAUDIO)`.

![imagen](https://github.com/openframeworks/openFrameworks/assets/14232672/c14bb7ec-9da0-44fb-af40-6a838bedd444)

**Comment by dgonzalezt** [comment]
What should I do with this issue? If I leave it open, will someone take care of this problem or should I close it?

**Comment by danoli3** [comment]
> What should I do with this issue? If I leave it open, will someone take care of this problem or should I close it?

on it, have a solution

**Comment by danoli3** [comment]
Oh wow this found deeper problems with RT Audio 
<img width="764" alt="Screenshot 2024-07-16 at 8 36 26 PM" src="https://github.com/user-attachments/assets/ac3d8717-c843-4f80-ae34-17ac90f9a1a9">
<img width="1288" alt="Screenshot 2024-07-16 at 8 37 01 PM" src="https://github.com/user-attachments/assets/c03f3219-8f6a-4ea2-8b92-f06f5d64a82b">

also why is the runner using 22.04.?? 
<img width="475" alt="Screenshot 2024-07-16 at 8 37 16 PM" src="https://github.com/user-attachments/assets/e73d58fa-a674-433f-9c0c-c7e8bb464bdf">

Going to add a define for OF_RTAUDIO5 to pass if you are on an old package manager system for now... might get this one on apothecary to solve this for all linux

**Comment by danoli3** [comment]
Fixed.
