### ISSUE TITLE
macos vs osx nightly releases?

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#8038]
the GitHub nightly releases https://github.com/openframeworks/openFrameworks/releases/tag/nightly offer both macos and osx downloads. It seems the macos version is broken with this error (from a freshly generated project from the downloaded project generator):

<img width="540" alt="image" src="https://github.com/openframeworks/openFrameworks/assets/2172370/171c64a2-e1bc-4473-b5ff-d0c43a153dad">

**Comment by danoli3** [comment]
Thanks will fix up the macOS one.

osx is pure arm64/x86_64.
macOS - it's the super all Apple targets/ platform build, need to tag that was experimental currently: more clear when Metal.

I'll take macOS off the nightly for the moment, however iOS is using the mega package for libraries currently

Unsure of issues with download_latest_libs.sh

Could you upload your of/libraries/download folder to gdrive and I'll investigate

**Comment by artificiel** [comment]
OK the naming makes more sense; closing this as solved
