### ISSUE TITLE
openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip is missing

### ISSUE THREAD

**Issue by PeteHaughie** [openframeworks/openFrameworks#8049]
Can't build and install nightlies because the file [openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip](https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip) is missing.

**Comment by danoli3** [comment]
[of_v20240715_msys2mingw64_release.zip](https://github.com/openframeworks/openFrameworks/releases/download/nightly/of_v20240715_msys2mingw64_release.zip)

how were u trying to install them, do u have a script? I think we should add the other msys2 as well, I can fix up the 
[openFrameworksLibs_bleeding_msys2_clang64.zip](https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_msys2_clang64.zip)
636 KB
4 days ago
[openFrameworksLibs_bleeding_msys2_mingw64.zip](https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_msys2_mingw64.zip)
638 KB
4 days ago
[openFrameworksLibs_bleeding_msys2_ucrt64.zip](https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_msys2_ucrt64.zip)
638 KB
4 days ago

**Comment by PeteHaughie** [comment]
```
$ ./download_libs.sh
 openFrameworks download_libs.sh v2.2
 -----
 [openFrameworks downloader v3.2.3] ...
  cURL [check_remote_vs_local] - LOCAL_FILE:[openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip] exists
  File sizes differ. Run the cURL. LocalSize:[9] RemoteSize:[]

 Downloading [cURL] urls:[https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip -o openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip ]

######################################################################################################################################################################################################################################################### 100.0%


 Overwrite - Removing prior libraries for [msys2]
 ------
 Uncompressing libraries [msys2] from [openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip]
[download/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of download/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip or
        download/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip.zip, and cannot find download/openFrameworksLibs_bleeding_msys2_mingw-w64-x86_64.zip.ZIP, period.
Error on or near line 310; exiting with status 1
```

**Comment by oxillo** [comment]
download_libs.sh is using MINGW_PACKAGE_PREFIX to suffix libs package whereas libs packages are suffixed with MSYSTEM.

**Comment by PeteHaughie** [comment]
Is there a fix I can apply to get this up and running?

**Comment by oxillo** [comment]
you can just : 

```bash
unset MINGW_PACKAGE_PREFIX
```

before running the download script
