### ISSUE TITLE
Nightly build with old project generator

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#8053]
Hi, 
The nightly build has an old and very buggy version of PG.
Also, the one linked in the PG readme is this same older one.
Please update the nightly download so it contains the newer and without so many bugs version of PG.

I guess that it just implies to run a remote build of PG.

@ofTheo

**Comment by ofTheo** [comment]
oh huh - I guess that we need to find a better way to keep the head up to date. 
but I think this might be more to do with Releases at https://github.com/openframeworks/projectGenerator/releases not being up to date. 

going to take a look now. 
pining @danoli3 and @dimitre

**Comment by ofTheo** [comment]
Hmm - yeah the nightly one does seem busted. 

If I use the PG app from April 2024 everything works fine. 

<img width="1070" alt="Screenshot 2024-07-17 at 8 01 40 PM" src="https://github.com/user-attachments/assets/38135706-4f7f-4ebc-acc3-f17bd3ad29f7">

If I use the nightly build I get:

<img width="966" alt="Screenshot 2024-07-17 at 8 02 48 PM" src="https://github.com/user-attachments/assets/4238d0a2-e840-47ce-b032-7820a4187b36">

It doesn't seem to be making the folder for the project name in OF/apps/myApps - so the generation errors out.

**Comment by danoli3** [comment]
Shall look into this more. No issues on my local end, shall do more folder
tests it might be downloads folder permissions

**Comment by danoli3** [comment]
Nightly says April but files are recent

**Comment by danoli3** [comment]
Wait what. I just tested the latest nightly, osx: no issues:

<img width="501" alt="Screenshot 2024-07-18 at 7 10 37 PM" src="https://github.com/user-attachments/assets/1f48938c-0d3f-4084-b1ac-7f63172e17b1">


What are the steps to produce this error.

**Comment by danoli3** [comment]
Also if you want Debug Console with the PG run it from double clicking on the macOS 
<img width="979" alt="Screenshot 2024-07-18 at 7 16 34 PM" src="https://github.com/user-attachments/assets/1702f42b-c9d2-4e6d-a974-644cbd135323">

**Comment by roymacdonald** [comment]
Thanks to you @danoli3 for all the energy and time you put into OF.

**Comment by danoli3** [comment]
Nightly still busted projectGenerator shall be fixed for today
