### ISSUE TITLE
OpenFrameworks failed to build due to rror LNK2001: unresolved external symbol _Cnd_timedwait_for with MSVC on Windows target arm64 or arm64ec

### ISSUE THREAD

**Issue by spacelg** [openframeworks/openFrameworks#8058]
Hi,

OpenFrameworks failed to build due to 'error LNK2001: unresolved external symbol _Cnd_timedwait_for' with MSVC on Windows target arm64 or arm64ec. but it can build pass on target x64. This issue can reproduce on version cbb57f2 on master branch. Could you please help look at this issue? Thanks in advance.

**Repro steps:**
1. Open VS2022 amd64 cmd.
2. git -C "C:\gitP" clone --no-checkout https://github.com/openframeworks/openFrameworks openframeworks\openFrameworks
3. git submodule init
4. git submodule update
5. "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
6. cd /d C:\gitP\openframeworks\openFrameworks
7. "C:\Program Files\Git\bin\sh.exe" ./scripts/ci/vs/install_bleeding.sh -p vs --silent
8. msbuild examples/templates/emptyExample/emptyExample.vcxproj /p:configuration=Release /p:platform=arm64 /p:PlatformToolset=v143

**Error log:**
[build_arm64.log](https://github.com/user-attachments/files/16357844/build_arm64.log)

**Error info:**
openframeworksLib.lib(ofThread.obj) : error LNK2001: unresolved external symbol _Cnd_timedwait_for [C:\gitP\openframeworks\openFrameworks\examples\templates\emptyExample\emptyExample.vcxproj]
bin\emptyExample.exe : fatal error LNK1120: 1 unresolved externals [C:\gitP\openframeworks\openFrameworks\examples\templates\emptyExample\emptyExample.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1151,5): error MSB6006: "link.exe" exited with code 1120. [C:\gitP\openframeworks\openFrameworks\examples\templates\emptyExample\emptyExample.vcxproj]
Done Building Project "C:\gitP\openframeworks\openFrameworks\examples\templates\emptyExample\emptyExample.vcxproj" (default targets) -- FAILED.

**Comment by danoli3** [comment]
Missing -pthreads

**Comment by danoli3** [comment]
@spacelg could you try this:

```
msbuild examples/templates/emptyExample/emptyExample.vcxproj /p:configuration=Release /p:platform=arm64 /p:PlatformToolset=v143 /p:AdditionalDependencies=concrt.lib
```

**Comment by danoli3** [comment]
Okay traced to inconsistency with C standard.

https://en.cppreference.com/w/c/thread/cnd_timedwait

+ to merge C++23 / C17 changes for VS

**Comment by danoli3** [comment]
@spacelg please try again now with C17 set
