### ISSUE TITLE
ofxAssimp pointing to other folder libs - not compatible with bleeding / latest libs

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8064]
in addon_config.mk it is pointing to a specific file like this
```
ios:
	ADDON_LIBS=
	ADDON_LIBS=../ofxAssimpModelLoader/libs/assimp/lib/ios/assimp.a
	
osx:
	ADDON_LIBS=
	ADDON_LIBS=../ofxAssimpModelLoader/libs/assimp/lib/osx/assimp.a
```

we can try to make it work by updating to bleeding paths (will it work?) but in any case it won't work for both.
any ideas? cc @danoli3

**Comment by danoli3** [comment]
Yeah I’ll fix! Can use %

**Comment by danoli3** [comment]
Looking into, it seems without the lines it works but it also is randomly including all libraries within other xcframeworks as well, in the compile list, which is weird, it also works, which is good but debugging this now in makefiles 

Have fix though at : https://github.com/openframeworks/openFrameworks/pull/8065
