### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by GitBruno** [openframeworks/openFrameworks#8066]
Trying to download required lib's but can't connect to the OF server.

    http://ci.openframeworks.cc/libs/openFrameworksLibs_master_vs2017_32_1.zip

Is there an alternative mirror? Or a guide on how to do it manually?

**Comment by danoli3** [comment]
Where did you read that guide that directed you there? 

Libraries can be found: or download via scripts/vs/download_latest_libs.sh

https://github.com/openframeworks/apothecary/releases/tag/bleeding


https://github.com/openframeworks/apothecary/releases/tag/nightly

**Comment by danoli3** [comment]
Also if you are looking for ancient libraries I have a backup here:

https://libs.danoli3.com

**Comment by GitBruno** [comment]
I was not trying to build an ancient version :) I was trying to build the `path-release` branch. 

`scripts/vs/download_latest_libs.sh` runs this file:

https://github.com/openframeworks/openFrameworks/blob/f93179bcfae8b5ff178cc60c483ddf41f295394b/scripts/dev/download_libs.sh#L33C1-L33C51
