### ISSUE TITLE
ofImage needs to include "ofPixels.h"

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#8071]
simple sample code with error.

```cpp
#include "ofImage.h"

struct X {
    ofImage image;
};
```

and error message is:
"libs/openFrameworks/graphics/ofImage.h:643:26 Implicit instantiation of undefined template 'ofPixels_<unsigned char>'"

this is caused by ofPixels is only declared without definition.

if it is needed to fix, I will create PR.

**Comment by danoli3** [comment]
ofPixels should be included by ofImage

**Comment by dimitre** [comment]
I've seen ofPixels.h is included in ofImage.cpp file.
are you using latest @2bbb ?

**Comment by 2bbb** [comment]
OK! I will create PR soon!
