### ISSUE TITLE
assimp.a not found in latest

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8075]
everything in latest master
I've installed libs using ./scripts/osx/download_latest_libs.sh
built examples/3d/assimp3DModelLoadeExample
tried to compile in XCode
error
```

Showing All Messages
No such file or directory: '/Volumes/tool/of/addons/ofxAssimpModelLoader/libs/assimp/lib/osx/assimp.xcframework/macos-arm64_x86_64/assimp.a'

```
it seems instead of lib/osx/ it installed in lib/macos

**Comment by dimitre** [comment]
my temporary fix was editing addon_config.mk and changing path, re-generating project

**Comment by danoli3** [comment]
PR that, maybe since it had a defined library path it didnt search 

Still something not working in the CMD PG, was there an exclusion dir in that mk.

I'm going to fix the PG UI today btw, so feel free to dive more into the cmd fixes
