### ISSUE TITLE
ofxSvg in macOS - libs not found

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8077]
it works if we add this two lines in addon_config.mk
```
osx:
	ADDON_LIBS = libs/svgtiny/lib/macos/svgtiny.xcframework/macos-arm64_x86_64/libsvgtiny.a
	ADDON_LIBS += libs/libxml2/lib/macos/libxml2.xcframework/macos-arm64_x86_64/libxml2.a
```

if it is correct I can make a PR. I'm confused with macos vs. osx folder usage
@danoli3

**Comment by danoli3** [comment]
removing osx: should yield the addon to link to the xcframework making this unnecessary. 

The problem manifesting really just need to remove the osx: and fix the pG
