### ISSUE TITLE
move libs/json/include/json.hpp to libs/json/include/nlohmann/json.hpp

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#8082]
when other libraries has `json.hpp`, `#include "json.hpp"` can't load `nlohmann::json`.

i think moving `include/json.hpp` to `include/nlohmann/json.hpp` and replace
`#include "json.hpp"`
to
`#include "nlohmann/json.hpp"`
or
`#include <nlohmann/json.hpp>`

for reference:
`#include <json.hpp>` works sometime.
but i think this is not complete solution, maybe...

**Comment by oxillo** [comment]
👍 

MSYS2 is already using #include <nlohmann/json.hpp> in ofJson.h

```cpp
#if !defined(TARGET_MINGW)
	#include <json.hpp>
#else
	#include <nlohmann/json.hpp> // MSYS2 : use of system-installed include
#endif
```

Also, examples from nlomann site are using #include <nlohmann/json.hpp>. So, I think this is the right move.

**Comment by 2bbb** [comment]
this fix need to use apothecary...?
if so, i don't know apothecary enough, please fix anyone! ☺️

**Comment by danoli3** [comment]
Can do

**Comment by dimitre** [comment]
Nice! should this should be changed also? 
in ofJson.h
```c++
#if !defined(TARGET_MINGW)
	#include <json.hpp>
#else
	#include <nlohmann/json.hpp> // MSYS2 : use of system-installed include
#endif
```

**Comment by danoli3** [comment]
Yes if someone could make the PR for that once the releases deployed to
merge

**Comment by danoli3** [comment]
Nice I think this changed exposed a few major automation test problems! XD
