### ISSUE TITLE
'openssl/evp.h' file not found

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8087]
using latest libraries in ./scripts/osx/download_libs.sh

../../../libs/openFrameworks/utils/ofURLFileLoader.cpp:17:10: fatal error: 'openssl/evp.h' file not found

**Comment by danoli3** [comment]
all files are exactly in location, please show ur download_libs log

**Comment by danoli3** [comment]
https://github.com/openframeworks/openFrameworks/pull/8089 since you use wget2 it might have been a corrupt file not fixing itself or clobbering correctly. this should solve it

**Comment by dimitre** [comment]
Hey @danoli3 I think this is not happening anymore. 
I was 6 commits behind in my branch, closing here
