### ISSUE TITLE
Apothecary - macos libs seems to have ios and tvos libs but not macos

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8088]
using ./scripts/osx/download_libs.sh

<img width="1265" alt="Screenshot 2024-08-20 at 22 05 03" src="https://github.com/user-attachments/assets/77f5a236-5a3c-4187-ad0e-aced3175b455">

**Comment by dimitre** [comment]
it is working, I had to update my fork with latest

**Comment by danoli3** [comment]
Any idea why, I think need to get apothecary on semantic releases as well should solve a lot of these hiccups
