### ISSUE TITLE
MAX_BUFFER_SIZE of UdpSocket in ofxOsc on Windows Env

### ISSUE THREAD

**Issue by 2bbb** [openframeworks/openFrameworks#8106]
on Windows, win32/UdpSocket.cpp

https://github.com/openframeworks/openFrameworks/blob/78a6a538615e53b32285bd989430a94ac817f927/addons/ofxOsc/libs/oscpack/src/ip/win32/UdpSocket.cpp#L450-L452

on posix,

https://github.com/openframeworks/openFrameworks/blob/78a6a538615e53b32285bd989430a94ac817f927/addons/ofxOsc/libs/oscpack/src/ip/posix/UdpSocket.cpp#L463-L469

is this an intentional limitation on size on Windows?

**Comment by 2bbb** [comment]
I refered source code of original oscpack, and I find posix UdpSocket was modified.
https://github.com/RossBencina/oscpack/blob/3e7e3a102e316d75fe176885a6dd08f216f2eac0/ip/posix/UdpSocket.cpp#L443-L445

so, I think It seems a mistake win32 UdpSocket hasn't been modified.
I will make PR.

**Comment by dimitre** [comment]
Great. it seems oscpack is stale, not receiving new PRs. this other fork has interesting changes
https://github.com/tai-studio/oscpack

**Comment by danoli3** [comment]
Just check if max size can be returned for windows. Looks like need to fix
for sure!
