### ISSUE TITLE
[macOS] make not working due to c++23

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8111]
in macOS 14.6.1, XCode 15.4 installed
we should change config.macos.default.mk, config.osx.default.mk
to 
```
MAC_OS_CPP_VER = -std=c++20
```
instead of
```
MAC_OS_CPP_VER = -std=c++23
```

**Comment by danoli3** [comment]
Xcode 14 supports some C++23, Xcode 15 supports most if not all c++23 
Having the setting to 23 enables C++23 features available in that development environment. 

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/ae77267d-4381-4549-a476-dccaa1375adb">

Clang Support: 
<img width="781" alt="image" src="https://github.com/user-attachments/assets/6ce517ba-ed01-44e5-96b8-2ef9ccddd015">

https://developer.apple.com/xcode/cpp/

**Comment by dimitre** [comment]
it is failing using make

**Comment by danoli3** [comment]
What clang version? Can you setup a test that fails, I tried a lot of macOS
variants to verify before. Merge the fix until we figure it out though then

**Comment by dimitre** [comment]
do you use Clang installed via Brew? I think I'm using the original one
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dimitre** [comment]
investigating further I found make template usually works because it is ending with
```
export MAC_OS_CPP_VER = -std=c++17
```
I'll propose a PR commenting out, and decreasing standard from c++23 to c++20
