### ISSUE TITLE
nightly build version missing the rtaudio.dll

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/openFrameworks#8114]
the lastest nightly build vs version seems missing the rtaudio.dll i.e complied and running the default audioinputexample

**Comment by dgonzalezt** [comment]
Yes, I have detected the same problem. On Windows with visual studio 2022, you just need to add an object ofSoundStream type and you can't run the application because of the missing dll.

**Comment by NickHardeman** [comment]
Same is happening for me too. 
pinging @danoli3

**Comment by danoli3** [comment]
Top priority

**Comment by danoli3** [comment]
Okay fixed. There is no spoon... I mean DLL... there never was.

**Comment by danoli3** [comment]
![image](https://github.com/user-attachments/assets/fdf5bed4-3b1f-4173-adb9-f4aca59f96d3)

Apothecary patch to no shared

**Comment by NickHardeman** [comment]
Hah! @danoli3 thank you for the quick fix :)
