### ISSUE TITLE
[ofxAssimp] addon_config refers to libs/osx but now seems to be libs/macos?

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#8125]
https://github.com/openframeworks/openFrameworks/blob/c98c50ad7f187b72342187b66dd994806c5e4807/addons/ofxAssimp/addon_config.mk#L112

I'm still a bit confused by the libs change osx/macos, so not sure what the exact problem/fix is (it it the addon_config, or some transitory thing), but right now from a fresh git OF download + download_libs.sh:

<img width="527" alt="image" src="https://github.com/user-attachments/assets/a6d6481d-6d8b-48fa-99a9-ba2463aba9cb">

(I know I'm not the only one confused by the macos/osx libs situation it would be great to have a point of documentation about what the expected usage is, specifically vs download_libs.sh)

**Comment by roymacdonald** [comment]
I think that the change from osx to macos it a bad move and should be reverted. it is breaking a lot of things and it is not really needed.

**Comment by artificiel** [comment]
closed by #8159
