### ISSUE TITLE
Linux Mint 22 Install Issue

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#8130]
When I run install_dependencies on Linux Mint 22 (Wilma), I get the following...

`E: Unable to locate package libgconf-2-4`

Installing manually seems to have fixed the issue...

```
wget -q http://mirrors.kernel.org/ubuntu/pool/universe/g/gconf/libgconf-2-4_3.2.6-8ubuntu1_amd64.deb
wget -q http://mirrors.kernel.org/ubuntu/pool/universe/g/gconf/gconf2-common_3.2.6-8ubuntu1_all.deb
sudo apt update 
sudo apt install ./gconf2-common_3.2.6-8ubuntu1_all.deb ./libgconf-2-4_3.2.6-8ubuntu1_amd64.deb
```

**Comment by ofTheo** [comment]
yeah I think there are a few small libs like this which are needed for Mint 22 and corresponding Ubuntu. 
`libgtk-3-dev` is another I think ( for the open / save dialogs ).

**Comment by chilina** [comment]
Hey I successfully installed it Mint 22 and the latest nightly today.  Worked great!  Maybe this can be closed?

**Comment by ofTheo** [comment]
Amazing - thanks @chilina
