### ISSUE TITLE
osx nightly signing errors for various libs

### ISSUE THREAD

**Issue by chilina** [openframeworks/openFrameworks#8135]
A recent nightly build for osx (of_v20240923_osx_release) seems to have some signing errors for various libs:

/Users/chilina/of_v20240923_osx_release/libs/pixman/lib/macos/pixman.xcframework:1:1 The signature of “pixman.xcframework” cannot be verified.
/Users/chilina/of_v20240923_osx_release/libs/rtAudio/lib/macos/rtAudio.xcframework:1:1 The signature of “rtAudio.xcframework” cannot be verified.

This was noted in #8126 but its a separate issue from that one.  Theo could fix it with:
```
codesign --remove-signature libs/*/lib/macos/*.xcframework
codesign --remove-signature addons/*/libs/*/lib/macos/*.xcframework
```

forum thread: https://forum.openframeworks.cc/t/macos-15-probably-you-downloaded-the-wrong-package/43919

**Comment by ofTheo** [comment]
In a pinch we could add:
```
codesign --remove-signature libs/*/lib/macos/*.xcframework
codesign --remove-signature addons/*/libs/*/lib/macos/*.xcframework
```

To the nightly packing script - at least that way we don't need to change anything in apothecary which is much harder to wrangle.

**Comment by ofTheo** [comment]
Closed by:
https://github.com/openframeworks/apothecary/commit/57213f40c4e8c0a12fcf4d5ee10333fa78014e0b

But there are still some issues with the nightly builds. 
Addon examples are referring to libs being in `osx` but apothecary is packaging them in `macos` will open another issue for that.

**Comment by roymacdonald** [comment]
> But there are still some issues with the nightly builds.
> Addon examples are referring to libs being in `osx` but apothecary is packaging them in `macos` will open another issue for that.

Hi @ofTheo, I have this issue solved in my PG updates PR. It works well for me on macos. Maybe you should use it for the nightly builds?
