### ISSUE TITLE
imageLoaderWebExample not loading image

### ISSUE THREAD

**Issue by chilina** [openframeworks/openFrameworks#8139]
The imageLoaderWebExample isn't loading the image (0.12.0 release, macOS 14.5); I get the following errors:
```
[ error ] ofImage: loadImage(): couldn't load image from ofBuffer, unable to guess image format from memory
[ error ] ofImage: loadImage(): couldn't load image from ""https://openframeworks.cc/about/0.jpg""
```
The example works great in the 0.11.2 release.  The following works OK:
```
ofHttpResponse resp = ofLoadURL("http://www.google.com/robots.txt");
```
forum thread:  https://forum.openframeworks.cc/t/imageloaderwebexample-not-loading-image/43947

**Comment by roymacdonald** [comment]
It works for me. with OF0.12 and nacos 14.6
Does it work when you hit the spacebar? (as it tries to load asyncronously)

**Comment by chilina** [comment]
Hey yes it works in the latest nightly too, and in the 0.12.0 release.  I was using a nightly from Oct 4, 2023.  So closing this and I'll start using a newer nightly.
