### ISSUE TITLE
ofSingleton errors in macOS 15, Xcode 16 and M1

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#8140]
I am having these errors:

<img width="479" alt="Screenshot 2024-10-08 at 4 34 54 AM" src="https://github.com/user-attachments/assets/4fdcbcae-36e9-47f7-a94a-e6ee08d0a050">

```.bash
/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:27:9 no member named 'lock_guard' in namespace 'std'

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:27:19 expected ';' after expression

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:27:20 use of undeclared identifier 'lock'; did you mean 'clock'?

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:27:24 expected ';' after expression

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:27:33 expected ';' after expression

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:37:9 no member named 'lock_guard' in namespace 'std'

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:37:19 expected ';' after expression

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:37:20 use of undeclared identifier 'lock'; did you mean 'clock'?

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:37:24 expected ';' after expression

/Users/manumolina/Documents/of_v20241007_osx_release/libs/openFrameworks/utils/ofSingleton.h:37:33 expected ';' after expression
```

This happens in master branch and `of_v20241007_osx_release` nigthly build too.

**Comment by moebiussurfing** [comment]
0.12.0 zip it's working fine.

**Comment by dimitre** [comment]
this is meant to close this one
https://github.com/openframeworks/openFrameworks/pull/8129
cc: @artificiel

**Comment by dimitre** [comment]
@moebiussurfing can you test this PR? if it fixes for you I'll be merging it

**Comment by artificiel** [comment]
not yet setup with Xcode 16 unfortunetely (current on a linux run). i will be able to upgrade a MacBook Pro next week.

but the missing include should do the trick!

**Comment by roymacdonald** [comment]
why do we even have a singleton class in OF´s core? I think that we have not had such a thing on purpose.  The [C++ guidelines say to avoid these](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#Ri-singleton)  and what they recommend instead can be seen in several places in OF's core.

**Comment by 2bbb** [comment]
@dimitre @artificiel 
I did build emptyExample (in 20241008_release) with macOS sequoia + Xcode 16, and it succeeds.

fyi:
ofSingleton.h exists in utils directory, but ofSingleton.h isn't in file navigator of Xcode.

**Comment by roymacdonald** [comment]
> fyi:
> ofSingleton.h exists in utils directory, but ofSingleton.h isn't in file navigator of Xcode.

It should not matter since the utils dir is already in the include paths. Maybe it is a good idea to leave "hidden"?

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/8129

**Comment by moebiussurfing** [comment]
> @moebiussurfing can you test this PR? if it fixes for you I'll be merging it

It works now on macOS 14.7.1 and Xcode 16.0.
