### ISSUE TITLE
[macOS] opencvPeopleDetection example: 'opencv2/videoio.hpp' file not found

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#8168]
<img width="592" alt="image" src="https://github.com/user-attachments/assets/57090a75-9f8f-4292-b069-8a71cada0e21">

**Comment by danoli3** [comment]
Replied same concept just add the xCFramework to project for the moment. Project Generator issue 

https://github.com/openframeworks/openFrameworks/issues/8170#issuecomment-2451470474

**Comment by dimitre** [comment]
I don't think the videoio.hpp is present today @danoli3 
in cmake I can see a define HAVE_VIDEOIO, is this option being used on apothecary?
https://github.com/opencv/opencv/blob/4.x/CMakeLists.txt

**Comment by dimitre** [comment]
I think this one is fixed
