### ISSUE TITLE
[libs] RPI - they are uncompressing in a folder inside libs, breaking OF

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8206]
libs are being installed in a folder inside libs, like 
```$ofw/libs/openFrameworksLibs_bleeding_linuxaarch64/glm```
as noticed in this other thread: https://github.com/openframeworks/openFrameworks/issues/8102

I've changed actions to actually LS recursively after downloading libs so we can see what is happening.
This folder is being added in the process of compressing tar.bz2 file. 
you can verify this by simply downloading and uncompressing this file: 
https://github.com/openframeworks/apothecary/releases/download/latest/openFrameworksLibs_latest_linuxaarch64.tar.bz2
it will uncompressed in a folder called ```openFrameworksLibs_bleeding_linuxaarch64``` which is not the file name.

The correct fix would be apothecary level which only @danoli3 can do. 
The not so correct fix would be changing install scripts to copy direct from one folder one level inside libs/downloads. This can be done also. there are lots of RPI needing love right now.

**Comment by dimitre** [comment]
This is a PR that is trying to fix the issue on install_libs level
https://github.com/openframeworks/openFrameworks/pull/8207

there are also issues with msys2 installation, I'll add a recursive LS to the github actions so we can see if libs are in place

**Comment by dimitre** [comment]
in msys2 svgtiny is missing

**Comment by ofTheo** [comment]
I'll check apothecary and see why svgtiny isn't getting included for msys2

**Comment by ofTheo** [comment]
This was the PR that removed it.  https://github.com/openframeworks/apothecary/pull/390/files#r1851042935
I thought maybe we could install via mingw packages but it looks like it doesn't exist as a package. 

I'll take a stab at adding it back in and see if it builds.

**Comment by ofTheo** [comment]
Almost got svgtiny working - its building just need to make sure it ends up getting copied.

**Comment by ofTheo** [comment]
Cool closing this! 
SVG on msys2 is fixed now too
