### ISSUE TITLE
VS Code Problem Matcher Does not accepts relative path correctly

### ISSUE THREAD

**Issue by mcpcseal** [openframeworks/openFrameworks#8208]
Clicking a problem in the problem matcher leads to `"${workspaceFolder}/full_absolute_path_to_the_file"` when the error comes out while building.

here's the fix:
(tasks.json in .vscode folder)
```jsonc
"problemMatcher": {
    "owner": "cpp",
    "fileLocation": "absolute", // needs to be modified as an absoloute path
    "pattern": {
      "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
      "file": 1,
      "line": 2,
      "column": 3,
      "severity": 4,
      "message": 5
    }
}
```

**Comment by ofTheo** [comment]
Thanks! 
Is this with the latest release or nightly? 

cc @dimitre - sounds like a PG issue doing absolute paths instead of relative

**Comment by mcpcseal** [comment]
> Thanks! 
> Is this with the latest release or nightly? 
> 
> cc @dimitre - sounds like a PG issue doing absolute paths instead of relative

This is the 0.12.0 release, and the tasks.json from PG is relative but I had to modify that into absolute path since vscode problem matcher interpreted it incorrectly.

**Comment by dimitre** [comment]
@mcpseal great. template was changed after 0.12 release
now it is like this:
```
	"problemMatcher": {
		"owner": "cpp",
		"fileLocation": ["relative", "${workspaceFolder}"],
		"pattern": {
			"regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
			"file": 1,
			"line": 2,
			"column": 3,
			"severity": 4,
			"message": 5
		}
	},
```

can you test copying the template files from latest git? Thank you

**Comment by mcpcseal** [comment]
It works! what was the change in tasks.json? It looks like the problemMatcher defined outside of the task section.

**Comment by dimitre** [comment]
you can see the entire template here
https://github.com/openframeworks/openFrameworks/tree/master/scripts/templates/vscode

**Comment by mcpcseal** [comment]
Oh I see. Thank you!

**Comment by dimitre** [comment]
@mcpseal thank you. Improvements are welcome in this latest template. ping here if you have any suggestions
