### ISSUE TITLE
iOS - ofTexture.loadScreenData issue when antiAliasing is on

### ISSUE THREAD

**Issue by momo-the-monster** [openframeworks/openFrameworks#822]
If I use loadScreenData with anti-Aliasing turned on in the program's startup like this:

ofAppiPhoneWindow \* iOSWindow = new ofAppiPhoneWindow();
iOSWindow->enableAntiAliasing(4);

then the texture will load in nothing but solid black. If I bypass this anti-aliasing, it works fine. I also cannot properly populate a texture using loadScreenData in a landscape orientation. Changing to Portrait orientation in the update loop, and then back to landscape after the grab fixes it.

**Comment by oxillo** [comment]
Hi,

We are trying to clean out the many issues that we have.
Many versions of OF have been released since this was issued.

Can you help us by checking if this issue is still present in the latest version ?

In case of inactivity, we'll close this issue by end of january, 2020.

Thanks
