### ISSUE TITLE
Cannot compile OF libs with msys2 on nightly build

### ISSUE THREAD

**Issue by Scylardor** [openframeworks/openFrameworks#8220]
Hello,

I'm failing at building openFrameworks for mingw64 using msys2.

I found this issue: #8034 
and realized there seems to be an issue with 0.12.0, so I tried installing the nightly build instead like what this issue suggested.

But at the step:

```
cd your_oF_directory/libs/openFrameworksCompiled/project
make
```

it starts compiling, but compilation fails quickly with this message:

```
Compiling ../../../libs/openFrameworks/gl/ofFbo.cpp
In file included from C:/msys64/mingw64/include/stdio.h:1302,
                 from C:/msys64/mingw64/include/c++/14.2.0/cstdio:42,
                 from ../../../libs/openFrameworks/utils/ofConstants.h:11,
                 from ../../../libs/openFrameworks/communication/ofSerial.h:4,
                 from ../../../libs/openFrameworks/communication/ofSerial.cpp:1:
C:/msys64/mingw64/include/swprintf.inl: In function 'int swprintf(wchar_t*, const wchar_t*, ...)':
C:/msys64/mingw64/include/swprintf.inl:37:19: error: invalid use of '__builtin_va_arg_pack ()'
   37 |   return _swprintf( __stream, __format, __builtin_va_arg_pack() );
      |          ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There seems to be a wrong compiler flag used here, or a missing one, as suggested by this SO post:
https://stackoverflow.com/questions/78503173/how-to-build-when-builtin-va-arg-pack-is-used

Is it a known issue? How could I try to fix this?

PS: my "real" issue is that I'm trying to use Visual Studio Code with openFrameworks on Windows, but it's unusable because the project generator doesn't generate the .vscode folder, so there are no DEBUG/RELEASE build tasks available. I don't know what to do. Hence I'm trying to install openFrameworks using msys2 instead of msbuild.

**Comment by Scylardor** [comment]
FYI: It seems a bug related to a similar issue is on the GCC tracker, but I cannot be sure it's the exact same one: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110834
It looks to me like a compiler bug.
Since it stems from an inlining attribute used in modes where inlining is disabled (i.e. Debug, Release is fine), I figured adding -Og to PLATFORM_OPTIMIZATION_CFLAGS_DEBUG in config.msys2.default.mk fixes the issue, as adding some level of optimization probably allows inlining.
It's not a great workaround, but at least I fixed my local msys2-mingw64 installation this way.
Let me know if it's worth opening a pull request...

**Comment by ofTheo** [comment]
what if you do: 
`make Release` 

or cd to one of the examples and do `make Release`

**Comment by Scylardor** [comment]
I can confirm the problem doesn't occur with the Release configuration. That works fine. I think the Makefile compiles both Debug and Release versions by default.

But I think it would be important to fix the Debug libs... That makes the setup instructions on the website effectively broken at the moment.

**Comment by ofTheo** [comment]
Thanks @Scylardor - I am assuming `make Debug` doesn't work but it would be good to confirm.

**Comment by dimitre** [comment]
@Scylardor I think this PR can fix this issue:
https://github.com/openframeworks/openFrameworks/pull/8222

**Comment by dimitre** [comment]
@Scylardor can you please re test it using the latest nightly?

**Comment by Scylardor** [comment]
I can confirm that using of_v20241209_msys2_mingw64_release the issue seems to have been fixed.

Thanks guys 👍

**Comment by dimitre** [comment]
Thank you! closed by 
- https://github.com/openframeworks/openFrameworks/pull/8222
