### ISSUE TITLE
ofURLFileLoader dosen't set HTTP User-Agent string and there is no way to set it

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#837]
I made a small example which uses the Wikipedia xml api to make queries which are then parsed by an ofXmlSettings object. The problem is Wikipedia complains there is no User-Agent string and dosen't return any data, while threatening to block by IP.

The fix was as simple as adding this to ofURLFileLoader.cpp line 144:

<pre>
        HTTPRequest req(HTTPRequest::HTTP_GET, path, HTTPMessage::HTTP_1_1);
            req.add("User-Agent", "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405");
</pre>

It uses the iOS safari user agent string. I think the best fix is to expose the HTTPRequest and HTTPResponse Poco objects so that, like in the ofxHttpUtils, you could add manually the string/value to the request before sending it. I don't think it should be set ti a default within the class. Also, it would be awesome to be able to add data into and pull data out of the requests. This is a great wrapper, especially the threading, I'd just like to have the full req/response control ... perhaps provide a method to add Poco::HttpRequests and recieve Poco::HttpResponses which could be set as references inside the ofxHttpRequest/ofxHttpResponse objects?

On another note, ofURLFileLoader seems like a rather specific name for a regular HTTP action. What's wrong with ofHttpSession etc since I've found it useful for more then just

**Comment by bakercp** [comment]
ofUrlFileLoader is meant to be a very simple interface.  For more sophisticated http calls consider using `ofHttpRequest` which now enables the user to set arbitrary request headers.

Other solutions like [ofxHTTP](https://github.com/bakercp/ofxHTTP) also work well for more advanced features.

Closing this for now.  There may be call for a discussion about default headers used with ofURLFileLoader (or lack thereof).  Please open a new issue if you'd like to take that on.  Cheers!
