### ISSUE TITLE
saveImage crashes in iOS Simulator

### ISSUE THREAD

**Issue by khlrqa** [openframeworks/openFrameworks#872]
testImg.saveImage(ofxiPhoneGetDocumentsDirectory() + "test.png");
crashes the App and results in this error:

Program received signal: "SIGARBT".

error thrown in this line:

    FreeImage_Save(fif, bmp, fileName.c_str());

**Comment by laserpilot** [comment]
tried to give this a test but it can't be tested currently -  empty example in master will successfully build to a device, but when you try to build to the simulator, it will not build - throws these errors:

ld: warning: ignoring file ../../../libs/FreeImage/lib/ios/freeimage.a, missing required architecture i386 in file ../../../libs/FreeImage/lib/ios/freeimage.a (2 slices)
ld: warning: ignoring file ../../../libs/glu/lib/ios/glu-ios.a, missing required architecture i386 in file ../../../libs/glu/lib/ios/glu-ios.a (2 slices)
Undefined symbols for architecture i386:
  "_fwrite$UNIX2003", referenced from:
      _WriteProc(void*, unsigned int, unsigned int, void*) in freeimage.a(FreeImageIO.o-i386)
      LibRaw::dcraw_thumb_writer(char const*) in freeimage.a(libraw_cxx.o-i386)
      _opj_image_create in freeimage.a(image.o-i386)
      _png_default_write_data in freeimage.a(pngwio.o-i386)
      LibRaw::ppm_thumb() in freeimage.a(dcraw_common.o-i386)
      LibRaw::jpeg_thumb_writer(__sFILE*, char*, int) in freeimage.a(dcraw_common.o-i386)
      LibRaw::write_ppm_tiff() in freeimage.a(dcraw_common.o-i386)
      ...
  "_mktime$UNIX2003", referenced from:
      LibRaw::get_timestamp(int) in freeimage.a(dcraw_common.o-i386)
      LibRaw::parse_rollei() in freeimage.a(dcraw_common.o-i386)
      LibRaw::parse_riff() in freeimage.a(dcraw_common.o-i386)
  "_strerror$UNIX2003", referenced from:
      Iex::throwErrnoExc(std::string const&, int) in freeimage.a(IexThrowErrnoExc.o-i386)
  "_strtod$UNIX2003", referenced from:
      _png_handle_sCAL in freeimage.a(pngrutil.o-i386)

**Comment by julapy** [comment]
this is because the xcode6 simulator will only runs 64bit applications. unfortunately OF is still only 32bit... but if you install Xcode 5.1 then you'll be able to run the example apps on the simulator.

**Comment by kylemcdonald** [comment]
closing this as a non-issue then. thanks @laserpilot and @julapy!

**Comment by ofZach** [comment]
I'm curious how far away is 64 bit ios OF and is there an issue for it (I've seen the osx 64 bit issue) ?   It seems there's a fair number of people hitting this problem now and given that and apples requirement of 64 bit apps some point in the future, it would be good to support: 

http://forum.openframeworks.cc/t/help-needed-latest-ios-ofx-examples-not-building/18175
